{'_data': [['Common',
            [['Cardiac', u'Arytmi.'],
             ['GI', u'Magknip, illam\xe5ende, diarr\xe9.'],
             ['Skin', u'Utslag.'],
             ['Skin', u'Flebit och sm\xe4rta vid infusionsst\xe4llet.']]],
           ['Uncommon', [['Skin', u'Urtikaria.']]],
           ['Rare',
            [['Ear',
              u'Reversibel h\xf6rself\xf6rlust (framf\xf6r allt hos patienter med nedsatt njurfunktion eller h\xf6ga doser).'],
             ['Immune system', u'Anafylaxi'],
             ['Hepato',
              u'F\xf6rh\xf6jda leverenzymv\xe4rden, bilirubinstegring, intrahepatisk gallstas, hepatit.']]],
           ['Unknown',
            [['Cardiac',
              u'QTc-intervallsf\xf6rl\xe4ngning, torsades de pointes, palpitationer, hj\xe4rtrytmrubbningar inklusive ventrikul\xe4ra takyarytmier.'],
             ['Ear', u'D\xf6vhet, tinnitus.'],
             ['GI',
              u'Obehag i \xf6vre delen av buken, kr\xe4kningar, pankreatit, anorexi, infantil hypertrofisk pylorusstenos, pseudomembran\xf6s kolit (se avsnitt 4.4).'],
             ['Skin',
              u'Kl\xe5da, exantem, angio\xf6dem, Stevens-Johnsons syndrom, toxisk epidermal nekrolys, erytema multiforme. Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Hepato',
              u'Kolestatisk hepatit, gulsot, leverdysfunktion, hepatomegali, leversvikt, hepatocellul\xe4r hepatit (se avsnitt 4.4).'],
             ['Blood',
              u'Eosinofili Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Nervous system', u'Konfusion, kramper, yrsel.'],
             ['Psychiatric', u'Hallucinationer'],
             ['Renal', u'Interstitiell nefrit'],
             ['Vascular', u'Hypotension']]]],
 '_pages': [5, 7],
 u'_rank': 19,
 u'_type': u'LSFU'}