{'_data': [['Common',
            [['Investigations', u'Vikt\xf6kning'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Psychiatric', u'Nedst\xe4mdhet, hum\xf6rf\xf6r\xe4ndringar, minskad libido'],
             ['GI', u'Illam\xe5ende, Magsm\xe4rta'],
             ['Reproductive system',
              u'Br\xf6stsm\xe4rtor, br\xf6stsp\xe4nningar, bl\xf6dningar']]],
           ['Uncommon',
            [['Metabolism', u'V\xe4tskeretention'],
             ['Nervous system', u'Migr\xe4n'],
             ['Vascular', u'M\xe5ttlig blodtrycksf\xf6rh\xf6jning'],
             ['GI', u'Kr\xe4kningar, diarr\xe9'],
             ['Skin', u'Utslag, urtikaria'],
             ['Reproductive system', u'Utebliven bortfallsbl\xf6dning, br\xf6stf\xf6rstoring']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Endocrine',
              u'S\xe4nkt glukostolerans, f\xf6rh\xf6jt blodsocker, \xf6kat insulinbehov'],
             ['Investigations', u'Viktminskning'],
             ['Psychiatric', u'\xd6kad libido'],
             ['Eye', u'Minskat t\xe5rfl\xf6de, kontaktlinsintolerans'],
             ['Vascular', u'Djup ventrombos, lungemboli, hj\xe4rtinfarkt'],
             ['Hepato',
              u'F\xf6r\xe4ndringar i leverfunktionen, kl\xe5da, gulsot av stastyp, gallsten, benigna leveradenom, fokal nodul\xe4r hyperplasi'],
             ['Skin', u'Kloasma, erythema nodosum, erythema multiforme'],
             ['Reproductive system', u'Br\xf6stsekretion, f\xf6r\xe4ndrad vaginal sekretion']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 9],
 u'_rank': 20,
 u'_type': u'MSFU'}