{'_data': [['Very common',
            [['Hepato', u' F\xf6r\xe4ndringar i leverv\xe4rden.  '],
             ['Metabolism', u' \xd6verg\xe5ende h\xf6jning av ammoniak i blodet.  '],
             ['Psychiatric', u' Hum\xf6r- och emotionella rubbningar.  ']]],
           ['Common',
            [['General',
              u' Yrsel. \xd6kad aptit, onormal vikt\xf6kning, anorexi och viktf\xf6rlust.  '],
             ['Blood',
              u' Lindrig trombocytopeni, nedsatt trombocytadhesivitet, f\xf6rl\xe4ngd  bl\xf6dningstid. '],
             ['Endocrine', u' Avvikelser vid tyreoideafunktionstest. '],
             ['GI',
              u' Sm\xe4rtor, sugningar, illam\xe5ende, kr\xe4kningar, diarr\xe9, asymtomatisk \xf6kning av serumamylasniv\xe5er. '],
             ['Skin',
              u' \xd6verg\xe5ende h\xe5ravfall, f\xf6r\xe4ndringar i h\xe5rkvalitet eller h\xe5rf\xe4rg. '],
             ['Nervous system', u' Tremor. ']]],
           ['Uncommon',
            [['General', u' Tr\xf6tthet.  '],
             ['Hepato',
              u' Sv\xe5r leverp\xe5verkan (ibland med letal levernekros) hos barn under  3 \xe5rs \xe5lder, vilka st\xe5tt p\xe5 kombinationsbehandling.  '],
             ['Nervous system', u' Nystagmus, dubbelseende, dysartri. '],
             ['Psychiatric', u' Beteendeavvikelser, insomningssv\xe5righeter. '],
             ['Reproductive system', u' Enures, \xf6kad miktionsfrekvens. ']]],
           ['Rare',
            [['General', u' Huvudv\xe4rk, hypotermi.  '],
             ['Blood',
              u' Sv\xe5r trombocytopeni, sv\xe5r leukopeni, bl\xf6dningar, l\xe4tthet att f\xe5  bl\xe5m\xe4rken, anemi, eosinofili, s\xe4nkt fibrinogenhalt. '],
             ['Endocrine',
              u' Oregelbunden menstruation, amenorr\xe9, polycystiskt ovariesyndrom, hirsutism. '],
             ['GI', u' Obstipation. '],
             ['Skin', u' Hudutslag, vaskulit. '],
             ['Hepato', u' Sv\xe5r leverp\xe5verkan hos barn \xf6ver 3 \xe5r. '],
             ['Nervous system', u' Parestesi, ataxi, parkinsonism. '],
             ['Psychiatric',
              u' Psykos, psykiatriska symtom (t.ex. irritabilitet, hyperaktivitet, konfusion, aggression). ']]],
           ['Very rare',
            [['Blood',
              u' Benm\xe4rgssuppression resulterande i neutropeni, leukopeni, aplastisk  anemi eller pancytopeni, makrocytos.  '],
             ['Nervous system',
              u' Stupor, koma, encefalopati, parkinsonism, reversibel demens ev. associerad med reversibel hj\xe4rnatrofi, anfallsf\xf6rs\xe4mring, extrapyramidala symtom. '],
             ['GI', u' Akut pankreatit. '],
             ['Skin',
              u' Erythema multiforme, Stevens-Johnsons syndrom, toxisk epidermal nekrolys, systemisk lupus erythematosus. Immunol.: \xd6verk\xe4nslighetsreaktioner. '],
             ['Metabolism',
              u' Uttalad hyperammonemi associerad med encefalopati, f\xf6rvirring, illam\xe5ende, kr\xe4kning, ataxi. '],
             ['Reproductive system', u' Fanconis syndrom ']]]],
 '_pages': [10, 11],
 u'_rank': 28,
 u'_type': u'DFSU'}