{'_data': [['Common',
            [['Infections', u'Bronkit, \xf6vre  luftv\xe4gsinfektion, faryngit#,  rinit#'],
             ['Metabolism', u'Hyperkalemi##, gikt#,  hyperurikemi#'],
             ['Psychiatric', u'Insomni#'],
             ['Nervous system', u'Yrsel#, huvudv\xe4rk#,  somnolens#'],
             ['Cardiac', u'Angina pectoris##,  takykardi#, hj\xe4rtklappning#'],
             ['Vascular', u'Vasodilatation#'],
<<<<<<< HEAD
             ['Vascular', u'Hosta#'],
=======
             ['Respiratory', u'Hosta#'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Kr\xe4kningar#, diarr\xe9#,  dyspepsi#, buksm\xe4rta#, illam\xe5ende#'],
             ['Musculoskeletal', u'Ryggv\xe4rk#, myalgi#'],
             ['General', u'Tr\xf6tthet#, asteni#,  br\xf6stsm\xe4rta#'],
             ['Investigations', u'\xd6kat serumkreatinin#, \xf6kat  blodureakv\xe4ve#*']]],
           ['Uncommon',
            [['Infections', u'Virusinfektion,  urinv\xe4gsinfektion, sinuit'],
             ['Metabolism', u'Nedsatt glukostolerans'],
             ['Psychiatric', u'F\xf6rvirring#, depression#,  oro#'],
             ['Nervous system',
              u'\xd6verg\xe5ende ischemiska  attacker#, synkop\xe9#, parestesier#, dysgeusi#'],
             ['Eye', u'Amblyopi#'],
             ['Ear', u'Vertigo#, tinnitus#'],
             ['Cardiac', u'Hj\xe4rtinfarkt#'],
             ['Vascular', u'Hypotoni#'],
<<<<<<< HEAD
             ['Vascular', u'Dyspn\xe9#, torr hals'],
=======
             ['Respiratory', u'Dyspn\xe9#, torr hals'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Flatulens#, torr mun#'],
             ['Skin',
              u'Alopeci#,  ljusk\xe4nslighetsreaktion#, pruritus#, utslag#, angio\xf6dem##, \xf6kad transpiration##'],
             ['Musculoskeletal', u'Artralgi#'],
             ['Renal', u'Njurdysfunktion#, proteinuri'],
             ['Reproductive system', u'Impotens#'],
             ['General', u'Generaliserat \xf6dem##,  feber#, perifert \xf6dem#']]],
           ['Rare',
            [['Nervous system', u'Balansst\xf6rningar'],
<<<<<<< HEAD
             ['Vascular',
=======
             ['Respiratory',
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
              u'Eosinofil pneumonit##, \xf6vre  luftv\xe4gsobstruktion orsakad av angio\xf6dem (kan vara fatal)#'],
             ['GI', u'F\xf6rstoppning, glossit'],
             ['Skin',
              u'Hudf\xf6r\xe4ndringar i  kombination med feber, muskel- och ledv\xe4rk (myalgi, artralgi, artrit), k\xe4rlinflammation (vaskulit), psoriasisliknande dermatit#']]],
           ['Very rare',
            [['Eye', u'Dimsyn#'],
             ['GI', u'Ileus#, intestinalt angio\xf6dem'],
             ['Skin', u'Urtikaria#']]],
           ['Unknown',
            [['Blood',
              u'Agranulocytos##, hemolytisk  anemi#\u221e, neutropeni##, trombocytopeni#, eosinofili#'],
             ['Immune system', u'Anafylaktoid reaktion#'],
             ['Nervous system', u'Cerebrovaskul\xe4r h\xe4ndelse#'],
             ['Cardiac', u'Arytmi'],
             ['Vascular', u'Ortostatisk hypotoni#'],
<<<<<<< HEAD
             ['Vascular', u'Bronkospasm#'],
=======
             ['Respiratory', u'Bronkospasm#'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Pankreatit#'],
             ['Hepato', u'Hepatit#, kolestatisk ikterus#'],
             ['Skin',
              u'Toxisk epidermal nekrolys#,  erythema multiforme#, exfoliativ dermatit#, pemfigus#, purpura, Stevens- Johnsons syndrom#'],
             ['Musculoskeletal', u'Systemisk lupus erytematosus'],
             ['Renal', u'Interstitiell nefrit'],
             ['General', u'Serosit'],
             ['Investigations',
              u'\xd6kade niv\xe5er av kolesterol#  och triglycerider#. Minskade v\xe4rden av hematokriter# samt f\xf6rh\xf6jt v\xe4rde av leverenzymer och blodbilirubin. \xd6kade niv\xe5er av antinukle\xe4ra antikroppar. \xd6kad hastighet av sedimentering f\xf6r r\xf6da blodkroppar.']]]],
 '_pages': [10, 12],
 u'_rank': 46,
 u'_type': u'TSFU'}