{'_data': [['Very common',
            [['Cardiac',
              u'\xe5terkommande ischemi / angina, hypotension och hj\xe4rtinsufficiens / lung\xf6dem, reperfusionsarytmier (t ex arytmi, extrasystole, AV-block I till komplett, f\xf6rmaksflimmer / -fladder, bradykardi, takykardi, ventrikul\xe4r arytmi, ventrikul\xe4r takykardi / ventrikelflimmer, elektromekanisk dissociation [EMD]'],
             ['Investigations', u'blodtrycksfall']]],
           ['Common',
            [['Cardiac', u'hj\xe4rtstillest\xe5nd, kardiogen chock, reinfarkt'],
             ['GI', u'illam\xe5ende, kr\xe4kningar'],
             ['Investigations', u'feber']]],
           ['Uncommon',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner / anafylaktoida reaktioner (t ex allergiska reaktioner inklusive hudutslag, n\xe4sselutslag, bronkospasm, angio\xf6dem, hypotension, chock eller andra symtom som har samband med allergiska reaktioner).'],
             ['Cardiac',
              u'mitralisregurgitation, lungemboli, andra systemiska embolier / cerebral emboli, ventrikul\xe4r septumdefekt Dessa hj\xe4rtbiverkningar kan vara livshotande och leda till d\xf6den.'],
             ['Vascular',
              u'emboli (trombotisk embolisering), som kan leda till f\xf6ljdverkningar i ber\xf6rda organ']]],
           ['Rare',
            [['Injury',
              u'fettemboli (embolisering av kolesterolkristaller), som kan leda till f\xf6ljdverkningar i ber\xf6rda organ']]],
           ['Very rare',
            [['Immune system',
              u'sv\xe5r anafylaxi \xd6verg\xe5ende bildning av antikroppar mot Actilyse har observerats i s\xe4llsynta fall och med l\xe5g titer, men den kliniska relevansen av dessa fynd har inte fastst\xe4llts.'],
             ['Nervous system',
              u'h\xe4ndelser relaterade till nervsystemet (t ex epileptiska anfall, konvulsioner, afasi, talst\xf6rningar, delirium, akut hj\xe4rnsyndrom, agitation, f\xf6rvirring, depression, psykos) ofta i samband med samtidig ischemi eller cerebrovaskul\xe4r bl\xf6dning']]],
           ['Unknown',
            [['Cardiac',
              u'Liksom med andra trombolytiska l\xe4kemedel, har f\xf6ljande h\xe4ndelser rapporterats som f\xf6ljd av hj\xe4rtinfarkt och/eller trombolytisk behandling.']]]],
 '_pages': [7, 9],
 u'_rank': 12,
 u'_type': u'LSFU'}