{'_data': [['Common',
            [['Blood', u'anemi  '],
             ['Metabolism', u'vanlig \xf6kad aptit mindre'],
             ['Metabolism', u'vanlig'],
             ['Nervous system',
              u'vanlig yrsel vanlig s\xf6mnl\xf6shet mindre mindre mindre mindre mindre'],
             ['Nervous system', u'vanlig vanlig vanlig vanlig vanlig'],
             ['Eye',
              u'vanlig makula\xf6dem 3 ingen k\xe4nd ingen ingen k\xe4nd ingen k\xe4nd ingen'],
             ['Ear', u'vanlig'],
             ['Cardiac',
              u'vanlig vanlig vanlig vanlig vanlig Andningsv\xe4gar, br\xf6stkorg och mediastinum dyspn\xe9 vanlig'],
             ['GI', u'vanlig'],
             ['Skin',
              u'vanlig Muskuloskeletala systemet och bindv\xe4v 5 benbrott vanlig vanlig vanlig vanlig vanlig artralgi vanlig vanlig vanlig ryggv\xe4rk vanlig'],
             ['Renal', u'vanlig proteinuri mindre'],
             ['Renal',
              u'vanlig Reproduktionsorgan och br\xf6stk\xf6rtel erektil dysfunktion vanlig Allm\xe4nna symtom och/eller'],
             ['Investigations',
              u'vanlig \xf6kning av alaninaminotransferas 7 ingen k\xe4nd ingen ingen k\xe4nd ingen k\xe4nd ingen']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighets- och allergiska ingen k\xe4nd ingen ingen k\xe4nd ingen k\xe4nd ingen reaktioner frekvens k\xe4nd frekvens frekvens k\xe4nd frekvens frekvens'],
             ['Metabolism', u'hypoglykemi mindre mycket vanlig'],
             ['Nervous system',
              u'hypestesi vanlig vanlig vanlig vanlig vanlig huvudv\xe4rk vanlig mindre'],
             ['Eye', u'synrubbningar 2 vanlig vanlig mindre'],
             ['Ear', u'mindre'],
             ['Cardiac',
              u'hj\xe4rtsvikt 4 vanlig Neoplasier; benigna, maligna och ospecificerade (samt cystor och polyper) bl\xe5scancer mindre mindre mindre mindre mindre'],
             ['GI', u'v\xe4dersp\xe4nning mindre vanlig'],
             ['Skin', u'mindre'],
             ['Renal', u'vanlig glykosuri mindre'],
             ['Investigations',
              u'vikt\xf6kning 6 vanlig vanlig vanlig vanlig vanlig f\xf6rh\xf6jt kreatinfosfokinas i blodet vanlig \xf6kning av laktatdehydrogenas mindre 21 Biverkningsfrekvens av pioglitazon efter behandlingsterapi kombination med Biverkning Monoterap med med metformin i metform sulfonylur och med in ea sulfonylur insulin ea']]]],
 '_pages': [6, 9],
 u'_rank': 23,
 u'_type': u'LSFU'}