{'_data': [['Very common', [['Nervous system', u'sedering/somnolens'], ['GI', u'dysgeusi']]],
           ['Common',
            [['Nervous system', u'yrsel'],
             ['Respiratory', u'halsirritation'],
             ['GI', u'muntorrhet'],
             ['General',
              u'tr\xf6tthet Beskrivning av valda biverkningar Bronkospasm I kortvariga (24-timmar) placebokontrollerade pr\xf6vningar p\xe5 patienter med agitation f\xf6rknippad med schizofreni eller bipol\xe4r sjukdom utan aktiv luftv\xe4gssjukdom, var bronkialspasm (i vilken ing\xe5r rapporter om pipande andning, andf\xe5ddhet eller hosta) mindre vanlig hos patienter som behandlades med ADASUVE. I placebokontrollerade kliniska pr\xf6vningar p\xe5 patienter med l\xe4tt till m\xe5ttlig kvarst\xe5ende astma eller m\xe5ttlig till allvarlig KOL var dock rapporter om biverkningar med bronkospasm mycket vanliga. De flesta av dessa o\xf6nskade h\xe4ndelser intr\xe4ffade inom 25 minuter efter doseringen, var av l\xe4tt till m\xe5ttlig sv\xe5righetsgrad, och kunde lindras med en inhalerad bronkdilaterare. Biverkningar som setts vid kronisk anv\xe4ndning av oralt loxapin Vid kronisk oral administrering av loxapin var de rapporterade biverkningarna bland annat sedering och d\xe5sighet, extrapyramidala symtom (t.ex. tremor, akatisi, rigiditet och dystoni), kardiovaskul\xe4ra effekter (t.ex. takykardi, hypotoni, hypertoni, ortostatisk hypotoni, omt\xf6ckning och synkope), samt antikolinerga effekter (t.ex. torra \xf6gon, dimsyn och urinretention).']]],
           ['Uncommon',
            [['Nervous system',
              u'dystoni, dyskinesi, okulogyration, tremor, akatisi/rastl\xf6shet'],
             ['Vascular', u'hypotoni'],
             ['Respiratory', u'bronkospasm (inklusive andf\xe5ddhet)']]]],
 '_pages': [5, 6],
 u'_rank': 9,
 u'_type': u'LSFU'}