{'_data': [['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighets- 5 Angioneurotiskt reaktioner \xf6dem'],
             ['Nervous system',
              u'Huvudv\xe4rk 6 Synkope Krampanfall ,2 Stroke (inklusive 5 Migr\xe4n \xf6verg\xe5ende bl\xf6dningar) 5 amnesi'],
             ['Eye',
              u'ischemisk optikusneuropati (NAION), retinalk\xe4rlsocklusion, synf\xe4ltsdefekter'],
             ['Ear', u'h\xf6rselneds\xe4ttning'],
             ['Cardiac',
              u'Br\xf6stsm\xe4rta ,Pl\xf6tslig Instabil angina hj\xe4rtklappning 2,5 hj\xe4rtd\xf6d ,pectoris, takykardi 2,5 ventrikul\xe4r arrytmi, hj\xe4rtinfarkt ,'],
             ['Vascular', u'Blodvallning Hypotoni Hypertoni'],
             ['Respiratory',
              u'(inkluderande n\xe4st\xe4ppa, tillt\xe4ppta bih\xe5lor och rinit)'],
             ['GI', u'buksm\xe4rta/besv\xe4r )reflux'],
             ['Skin',
              u'Utslag Urtikaria Stevens-Johnson hyperhydrosis 5 syndrom, exfoliativ (svettningar) dermatit'],
             ['Musculoskeletal',
              u'Myalgi, ryggsm\xe4rta, sm\xe4rta i extremiteterna (inkluderande obehag i armar och ben)'],
             ['Renal', u'Hematuri'],
             ['Reproductive system',
              u'\xd6kad uterin Priapism , penil F\xf6rl\xe4ngd erektion bl\xf6dning 4 hemorragi, hematospermi'],
             ['General',
              u'Ansikts\xf6dem, br\xf6stsm\xe4rta 7 (1) Dessa biverkningar har inte rapporterats i de kliniska pr\xf6vningar som ing\xe5r i registrerings dokumentationen och kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data. Biverkningarna har tagits med i tabellen till f\xf6ljd av data som inkommit efter marknadsf\xf6ring eller fr\xe5n kliniska studier vid anv\xe4ndning av tadalafil f\xf6r behandling av erektil dysfunktion (2) De flesta patienter, hos vilka dessa effekter rapporterades, hade sedan tidigare kardiovaskul\xe4ra riskfaktorer. (3) De MedDRA-termer som ing\xe5r \xe4r obehagsk\xe4nsla i buken, buksm\xe4rta, buksm\xe4rta i nedre delen av magen, buksm\xe4rta i \xf6vre delen av magen, magbesv\xe4r. (4) Klinisk icke MedDRA-term som inkluderar rapporter om onormala/rikliga menstruationer s\xe5som menorragi, metrorragi, menometrorragi, eller vaginal bl\xf6dning. (5) Biverkningarna har tagits med i tabellen till f\xf6ljd av data som inkommit efter marknadsf\xf6ring eller fr\xe5n kliniska studier vid anv\xe4ndning av tadalafil f\xf6r behandling av erektil dysfunktion; dessutom, baserar sig frekvensen ofta p\xe5 1 eller 2 patienters upplevelser av biverkningen i den placebo-kontrollerad huvudstudien f\xf6r ADCIRCA. (6) Se avsnitt c) c. Beskrivning av utvalda biverkningar Den vanligast rapporterade biverkningen var huvudv\xe4rk. Huvudv\xe4rk kan uppkomma i b\xf6rjan av behandlingen; och minska med tiden \xe4ven om behandlingen forts\xe4tter.']]]],
 '_pages': [6, 8],
 u'_rank': 13,
 u'_type': u'LSFU'}