{'_data': [['Common',
            [['Infections', u'Influensa Mindre'],
             ['Infections', u'Laryngit Mindre'],
             ['Infections', u'Lymfangit Mindre'],
             ['Eye', u'\xd6goninflammationMindre'],
             ['Vascular', u'Hematom Mindre'],
             ['Vascular', u'Blodvallningar Mindre'],
             ['Vascular', u'Blekhet Mindre'],
             ['GI', u'Diarr\xe9 Mindre'],
             ['Skin', u'Pruritus Mindre'],
             ['Skin', u'Eksem Mindre'],
             ['Skin', u'Hyperhidros Mindre'],
             ['Skin', u'Bl\xf6jeksem Mindre'],
             ['Investigations', u'Anti-faktor VIII-antikroppspositiv']]],
           ['Uncommon',
            [['General', u'Perifert \xf6dem'],
             ['Investigations', u'\xd6kad alaninaminotransferas'],
             ['Injury', u'Komplikationer efter behandling'],
             ['Injury',
              u'Bl\xf6dning efter behandling  Reaktion vid behandlingsst\xe4llet vid'],
             ['Injury', u'behandling']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk reaktion'],
             ['Immune system', u'\xd6verk\xe4nslighet']]]],
 '_pages': [4, 7],
 u'_rank': 20,
 u'_type': u'TSFU'}