{'_data': [['Common',
            [['Vascular', u'Hematom Mindre'],
             ['Vascular', u'Blodvallningar Mindre'],
             ['Vascular', u'Blekhet Mindre'],
             ['GI', u'Diarr\xe9 Mindre'],
             ['Skin', u'Pruritus Mindre'],
             ['Skin', u'Eksem Mindre'],
             ['Skin', u'Hyperhidros Mindre'],
             ['Skin', u'Bl\xf6jeksem Mindre'],
             ['Investigations', u'Anti-faktor VIII-antikroppspositiv']]],
           ['Uncommon',
            [['Infections', u'Influensa'],
             ['General', u'Perifert \xf6dem'],
             ['Investigations', u'\xd6kad alaninaminotransferas'],
             ['Injury',
              u'Komplikationer efter behandling  Reaktion vid behandlingsst\xe4llet vid'],
             ['Injury', u'behandling']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk reaktion'],
             ['Immune system', u'\xd6verk\xe4nslighet']]]],
 '_pages': [5, 7],
 u'_rank': 16,
 u'_type': u'TSFU'}