{'_data': [['Very common',
            [['Infections', u'Infektioner *'],
             ['Blood', u'Anemi, trombocytopeni'],
             ['Metabolism', u'Hyperglykemi, hyperkolesterolemi, hypertriglyceridemi, anorexi'],
             ['Nervous system', u'Dysgeusi, huvudv\xe4rk'],
             ['Respiratory', u'Mycket vanliga Pneumonit c , dyspn\xe9, n\xe4sblod, hosta'],
             ['GI',
              u'Mycket vanliga Stomatit d , diarr\xe9, slemhinneinflammation, kr\xe4kning, illam\xe5ende'],
             ['Skin', u'Utslag, torr hud, pruritus, nagelbesv\xe4r'],
             ['General', u'Tr\xf6tthet, asteni, perifert \xf6dem, feber'],
             ['Investigations', u'Minskad vikt']]],
           ['Common',
            [['Blood', u'Leukopeni, lymfopeni, neutropeni'],
             ['Metabolism',
              u'Diabetes mellitus, hypofosfatemi, hypokalemi, hyperlipidemi, hypokalcemi, dehydrering'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Eye', u'Konjunktivit, \xf6gonlocks\xf6dem'],
             ['Vascular', u'H\xf6gt blodtryck, hemorragi'],
             ['Respiratory', u'Lungemboli, hemoptys'],
             ['GI', u'Muntorrhet, buksm\xe4rta, oral sm\xe4rta, dysfagi, dyspepsi'],
             ['Hepato', u'F\xf6rh\xf6jt ALAT, f\xf6rh\xf6jt ASAT'],
             ['Skin',
              u'Hand-fotsyndrom (palmar-plantar erytrodysestesi), erytem, hudexfoliation, acneiform dermatit, onykoklas (brutna naglar), hudf\xf6r\xe4ndringar, lindrig alopeci'],
             ['Musculoskeletal', u'Ledv\xe4rk'],
             ['Renal',
              u'F\xf6rh\xf6jt serumkreatinin, njursvikt (inklusive akut njursvikt)*, proteinuri*'],
             ['General', u'Br\xf6stsm\xe4rta']]],
           ['Uncommon',
            [['Blood', u'Erytroblastopeni (PRCA)'],
             ['Nervous system', u'Ageusi'],
             ['Cardiac', u'Kronisk hj\xe4rtsvikt'],
             ['Vascular', u'Hudrodnad, djup ventrombos'],
             ['Respiratory', u'Andn\xf6dssyndrom (Acute Respiratory Distress Syndrome, ARDS)'],
             ['Skin', u'Angio\xf6dem'],
             ['General', u'F\xf6rs\xe4mrad s\xe5rl\xe4kning']]],
           ['Unknown', [['Immune system', u'\xd6verk\xe4nslighet']]]],
 '_pages': [9, 11],
 u'_rank': 29,
 u'_type': u'LSFU'}