{'_data': [['Unknown',
            [['Skin',
              u'v\xe4vnad Muskuloskeletala Myalgi, artralgi* systemet och bindv\xe4v Allm\xe4nna symtom Feber, och/eller symtom sjukdomsk\xe4nsla, vid frossa, tr\xf6tthet. administreringsst\xe4ll Lokala reaktioner: et rodnad, svullnad, \xf6mhet eller sm\xe4rta, ekkymos, induration.*'],
             ['Blood', u'\xd6verg\xe5ende trombocytopeni, \xf6verg\xe5ende lymfadenopati'],
             ['Immune system',
              u'Allergiska reaktioner, som i s\xe4llsynta fall kan leda till anafylaktisk chock, angio\xf6dem.'],
             ['Nervous system',
              u'Neuralgi, parestesi, kramper (inklusive feberkramper), neurologiska st\xf6rningar s\xe5som encefalomyelit, neurit och Guillain-Barr\xe9s syndrom.'],
             ['Vascular',
              u'Vaskulit (med \xf6verg\xe5ende renal p\xe5verkan i mycket s\xe4llsynta fall).'],
             ['Skin',
              u'Generaliserade hudreaktioner, t. ex. pruritus, urtikaria eller ospecifika utslag.'],
             ['General',
              u'Lokaliserad eller diffus inflammation i bindv\xe4v inklusive stor svullnad vid injektionsst\xe4llet (ofta rapporterad som cellulit).']]]],
 '_pages': [3, 4],
 u'_rank': 7,
 u'_type': u'LSFU'}