{'_data': [['Common',
            [['Vascular', u'  Palpitationer, takykardi  '],
             ['Musculoskeletal', u'  Skelettmuskeltremor  ']]],
           ['Uncommon', [['General', u'  Huvudv\xe4rk,  -\xd6verk\xe4nslighetsreaktion ']]],
           ['Rare',
            [['Respiratory', u'  Bronkospasm  -Mun- och halsirritation  '],
             ['Musculoskeletal', u'  Muskelkramp  '],
             ['Psychiatric', u'  Beteendest\xf6rningar  -S\xf6mnst\xf6rningar hos barn '],
             ['Metabolism', u'  Hypokalemi  ']]],
           ['Very rare', [['Vascular', u'  Myokardischemi  ']]]],
 '_pages': [2, 2],
 u'_rank': 8,
 u'_type': u'DFSU'}