{'_data': [['Common', [['Eye', u'Ackommodationsbesv\xe4r'], ['GI', u'Muntorrhet']]],
           ['Uncommon',
            [['Psychiatric',
              u'Irritation  Oro F\xf6rvirring Delirium Psykosliknande tillst\xe5nd \xc5ngest'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac', u'Takykardi'],
             ['GI', u'F\xf6rstoppning, Magbesv\xe4r'],
             ['Skin', u'Hypohidros'],
             ['Renal', u'Miktionsbesv\xe4r'],
             ['General', u'Tr\xf6tthet'],
             ['Investigations', u'Blodtryckss\xe4nkning (efter parenteral  tillf\xf6rsel)']]],
           ['Rare',
            [['Psychiatric', u'Minnesst\xf6rningar  Hallucinationer Talsv\xe5righeter'],
             ['Nervous system', u'Dyskinesi  Ataxi Kramper'],
             ['Skin', u'Allergiska hudutslag'],
             ['Renal', u'Urinretention']]],
           ['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighet, inklusive utslag'],
             ['Psychiatric', u'Onormal REM-s\xf6mn  Eufori Agitation'],
             ['Eye', u'Mydriasis'],
             ['Cardiac', u'Bradykardi']]]],
 '_pages': [2, 3],
 u'_rank': 18,
 u'_type': u'TSFU'}