{'_data': [['Rare',
            [['Immune system', u'anafylaktisk reaktion \xf6verk\xe4nslighet'],
             ['Vascular', u'hypotoni']]],
           ['Very rare',
            [['Immune system', u'anafylaktisk chock'],
             ['Psychiatric', u'f\xf6rvirringstillst\xe5nd'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Cardiac', u'takykardi bradykardi'],
             ['Vascular', u'hypertoni blodvallningar'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'illam\xe5ende'],
             ['Skin', u'urtikaria angioneurotiskt \xf6dem erytemat\xf6sa utslag hyperhidros'],
             ['General', u'pyrexi frossa']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'MSFU'}