{'_data': [['Common',
            [['GI', u' Dyspepsi, halsbr\xe4nna, illam\xe5ende.  '],
             ['Other', u' \xd6kad bl\xf6dningsben\xe4genhet.  ']]],
           ['Uncommon',
            [['General',
              u' Allergiska reaktioner (urtikaria, rinit och astma).  Tr\xf6tthet, yrsel.  '],
             ['GI', u' Mags\xe5r och magbl\xf6dning vid regelbunden anv\xe4ndning. '],
             ['Ear', u' \xd6ronsusningar. '],
             ['Other', u' Svettning. ']]],
           ['Rare',
            [['Blood',
              u' Trombocytopeni, hemolys vid \xe4rftlig glukos-6-fosfat-  dehydrogenasbrist.  '],
             ['GI', u' Sv\xe5r gastrointestinal bl\xf6dning. '],
             ['Hepato', u' Transaminasstegring. ']]]],
 '_pages': [3, 4],
 u'_rank': 9,
 u'_type': u'DFSU'}