{'_data': [[u'Unknown',
            [['Psychiatric', u'rastl\xf6shet   vanligt'],
             ['Nervous system', u'huvudv\xe4rk mycket   vanligt'],
             ['Vascular', u'hypotoni, blekhet, perifer kyla   vanligt'],
             ['GI', u'kr\xe4kningar, diarr\xe9   vanligt'],
             ['Skin', u'angioneurotiskt \xf6dem, svullet ansikte,'],
             ['Musculoskeletal', u'extremitetssm\xe4rta   mycket vanligt'],
             ['General',
              u'frossbrytningar, v\xe4rmek\xe4nsla,   k\xf6ldk\xe4nsla, tr\xf6tthet,   vanligt'],
             ['Investigations', u'syrgasm\xe4ttnad  vanligt'],
             ['General', u'pyrexi mycket   vanligt   frossbrytningar mycket   vanligt'],
             ['Investigations', u'minskad']]]],
 '_pages': [4, 6],
 u'_rank': 10,
 u'_type': u'LFSU'}