{'_data': [['Very common',
            [['Nervous system', u'rodnad'],
             ['Vascular', u'illam\xe5ende, buksm\xe4rta'],
             ['Musculoskeletal', u'extremitetssm\xe4rta'],
             ['Musculoskeletal', u'pyrexi, reaktion p\xe5 infusionsst\xe4llet']]],
           ['Common',
            [['Immune system', u'anafylaktiskreaktion'],
             ['Psychiatric', u'rastl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk mycket  parestesi, yrsel'],
             ['Vascular', u'hypotoni, blekhet, perifer kyla'],
             ['GI', u'kr\xe4kningar, diarr\xe9  utslag mycket'],
             ['Skin',
              u'urtikaria, kl\xe5da, kallsvett, alopeci,  hyperhidros artropati, artralgi, ryggsm\xe4rta,'],
             ['Musculoskeletal', u'muskuloskeletal sm\xe4rta'],
             ['General',
              u'k\xf6ldk\xe4nsla, tr\xf6tthet,  influensaliknande sjukdom f\xf6rh\xf6jd kroppstemperatur, minskad'],
             ['Investigations', u'syrgasm\xe4ttnad'],
             ['Cardiac', u'takykardimycket'],
             ['General', u'pyrexi mycket'],
             ['General', u'frossbrytningar mycket']]]],
 '_pages': [3, 5],
 u'_rank': 16,
 u'_type': u'TSFU'}