{'_data': [['Very common', [['GI', u'> 1/10']]],
           ['Common',
            [['GI', u'> 1/100 till < 1/10'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Buksm\xe4rta, dyspepsi, f\xf6rstoppning, diarr\xe9, flatulens, esofaguss\xe5r*, dysfagi*, buksp\xe4nning, sura uppst\xf6tningar.'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta (skelett, muskel eller led)']]],
           ['Uncommon',
            [['GI', u'> 1/1000 till < 1/100'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, gastrit, esofagit*, esofaguserosioner*, melena.'],
             ['Skin', u'hudutslag, pruritus, erythema.']]],
           ['Rare',
            [['GI', u'> 1/10 000 till < 1/1000'],
             ['Eye', u'uveit, sklerit, episklerit'],
             ['GI',
<<<<<<< HEAD
              u'Esofagusstriktur, s\xe5r i munh\xe5la/svalg, \xf6vre gastrointestinal PUB (perforationer, s\xe5r, bl\xf6dningar) (se avsnitt 4.4).'],
=======
              u'Esofagusstriktur, s\xe5r i munh\xe5la/svalg, \xf6vre gastrointestinal PUB (perforationer, s\xe5r, bl\xf6dningar) (se avsnitt 4.4). *se avsnitten 4.2 och 4.4.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Skin', u'hudutslag med fotosensitivitet.'],
             ['Musculoskeletal',
              u'Osteonekros i k\xe4ken har rapporterats hos patienter som behandlats med bisfosfonater. Majoriteten av rapporterna r\xf6r cancerpatienter, men s\xe5dana fall har \xe4ven rapporterats hos patienter som behandlas f\xf6r osteoporos. Osteonekros i k\xe4ken f\xf6rknippas i allm\xe4nhet med tandutdragning och/eller lokal infektion (inklusive osteomyelit). Cancerdiagnos, kemoterapi, str\xe5lningsterapi, kortikosteroider och d\xe5lig munhygien bed\xf6ms ocks\xe5 vara riskfaktorer; sv\xe5r muskuloskeletal (skelett, muskel eller led) sm\xe4rta (se avsnitt 4.4). Efter marknadsf\xf6ring har f\xf6ljande biverkningar rapporterats (frekvens: s\xe4llsynt): Atypiska subtrokant\xe4ra och diafys\xe4ra femurfrakturer (bisfosfonat klassbiverkning).'],
             ['Metabolism',
              u'Symtomatisk hypokalcemi, i allm\xe4nhet i samband med predisponerande tillst\xe5nd (se avsnitt 4.4).'],
             ['General',
              u'\xd6verg\xe5ende symtom som vid en akutfasreaktion (myalgi, allm\xe4n sjukdomsk\xe4nsla och i'],
             ['General', u'fall feber) oftast i samband med behandlingsstart.'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner inklusive urtikaria och angio\xf6dem. Erfarenhet efter marknadsf\xf6ring rapporterar om f\xf6ljande reaktioner (ok\xe4nd frekvens)']]],
           ['Very rare',
            [['GI', u'< 1/10 000, ok\xe4nd (kan inte uppskattas fr\xe5n tillg\xe4ngliga data)'],
             ['Skin',
              u'Enstaka fall av allvarliga hudreaktioner, d\xe4ribland Stevens-Johnsons syndrom och toxisk epidermal nekrolys.']]],
           ['Unknown',
            [['GI',
              u'Buksm\xe4rta 3 ,7 3 ,0 6 ,6 4 ,8 Dyspepsi 2 ,7 2 ,2 3 ,6 3 ,5 Sura uppst\xf6tningar 1 ,9 2 ,4 2 ,0 4 ,3 Illam\xe5ende 1 ,9 2 ,4 3 ,6 4 ,0 Ett\xe5rsstudien Tre\xe5rsstudierna Alendronat Alendronat Alendronat Placebo veckotablett 10 mg dagligen 10 mg (n=397) (n=519) (n=370) dagligen % % % (n=196) % Buksp\xe4nning 1 ,0 1 ,4 1 ,0 0,8 F\xf6rstoppning 0,8 1 ,6 3 ,1 1 ,8 Diar r\xe9 0,6 0,5 3 ,1 1 ,8 Dys fagi 0,4 0,5 1 ,0 0,0 Flatulen s0,4 1 ,6 2 ,6 0,5 Gastrit 0,2 1 ,1 0,5 1 ,3 Ventrikel s\xe5r 0,0 1 ,1 0,0 0,0 Esofaguss\xe5r 0,0 0,0 1.5 0,0 Mus kuloskeletala Muskuloskeletal sm\xe4rta 2 ,9 3 ,2 4 ,1 2 ,5 (skelett, muskel eller led) Muskelkramper 0,2 1 ,1 0,0 1 ,0 Neurologiska Huvudv\xe4rk 0,4 0,3 2 ,6 1 ,5 F\xf6ljande biverkningar har ocks\xe5 rapporterats vid kliniska studier och/eller efter marknadsf\xf6ring'],
             ['Nervous system', u'Yrsel'],
             ['Ear', u'Vertigo'],
             ['Musculoskeletal', u'Svullna leder'],
             ['General',
              u'Asteni, perifert \xf6dem Laboratoriev\xe4rden: I kliniska studier s\xe5gs asymtomatiska, l\xe4tta och \xf6verg\xe5ende s\xe4nkningar i serumkalcium och serumfosfat hos ungef\xe4r 18 respektive 10 % av patienterna som fick alendronat 10 mg/dag j\xe4mf\xf6rt med 12 respektive 3 % bland dem som fick placebo. Incidensen av s\xe4nkningar i serumkalcium till <8,0 mg/dl (2,0 mmol/L) och serumfosfat till \u2264 2,0 mg/dl (0,65 mmol/L) var emellertid j\xe4mf\xf6rbar i de tv\xe5 grupperna.']]]],
 '_pages': [4, 6],
 u'_rank': 24,
 u'_type': u'LSFU'}