{'_data': [['Very common',
            [['Musculoskeletal',
              u' muskuloskeletal sm\xe4rta (ben, muskel eller led) vilken ibland kan vara sv\xe5r \u2020\xa7']]],
           ['Common',
            [['Nervous system', u' huvudv\xe4rk, yrsel\u2020'],
             ['Ear', u' vertigo\u2020'],
             ['GI',
              u' buksm\xe4rta, dyspepsi, f\xf6rstoppning, diarr\xe9, buksp\xe4nning, esofaguss\xe5r *, dysfagi*, flatulens, sura uppst\xf6tningar'],
             ['Skin', u' h\xe5ravfall\u2020, kl\xe5da\u2020'],
             ['Musculoskeletal', u'svullnad i lederna\u2020'],
             ['General', u' asteni\u2020, perifert \xf6dem\u2020']]],
           ['Uncommon',
            [['Nervous system', u'smakf\xf6r\xe4ndringar \u2020'],
             ['Eye', u' \xf6gon inflammation (uveit, sklerit eller episklerit)'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning, gastrit, esofagit *, esofaguserosioner *, melena\u2020'],
             ['Skin', u'hudutslag, erytem'],
             ['General',
              u' \xf6verg\xe5ende symtom som vid en akutfasreaktion (muskelv\xe4rk, allm\xe4n sjukdomsk\xe4nsla och i']]],
           ['Rare',
            [['Immune system',
              u' \xf6verk\xe4nslighetsreaktioner inklusive urtikaria och angio\xf6dem'],
             ['Metabolism',
              u' symtomatisk hypokalcemi, oftai samband med predisponerande tillst\xe5nd \xa7'],
             ['GI', u'esofagusstriktur*, s\xe5r i munh\xe5la eller svalg*, \xf6vre'],
             ['Skin', u'hudutslag med fotosensitivitet, allvarliga'],
             ['Musculoskeletal',
              u'osteonekros i k\xe4ken\u2021\xa7; atypiska subtrokant\xe4ra och diafys\xe4ra femurfrakturer (bisfosfonat klassbiverkning)\u2534'],
             ['General', u'fall feber) vanligtvis i samband med behandlingsstart.\u2020 ']]]],
 '_pages': [5, 7],
 u'_rank': 18,
 u'_type': u'LSFU2'}