{'_data': [['Very common',
            [['Infections', u'Blodet och lymfsystemet  '],
             ['Eye', u'Bradykardi, kardiella arytmier'],
             ['Eye', u'Flush'],
             ['Eye', u'Bronkospasm'],
             ['Eye', u'Gallstas, hepatit, gulsot'],
             ['Eye', u'Alopeci, purpura, urtikaria'],
             ['Eye', u'Muskelkramper, muskelsvaghet'],
             ['Eye', u'miktionssv\xe5righeter, nokturi, polyuri, \xf6kad']]],
           ['Uncommon',
            [['Immune system', u'Metabolism och nutrition  '],
             ['Immune system', u'Psykiska st\xf6rningar  '],
             ['Eye', u'Tinnitus Hj\xe4rtat Vanlig Palpitation, takykardi'],
             ['Eye', u'Angina pectoris, myokardinfarkt'],
             ['Eye', u'Epistaxis'],
             ['Eye',
              u'F\xf6rstoppning, diarr\xe9, flatulens, kr\xe4kningar, gastroenterit Lever och gallv\xe4gar Mindre vanlig Onormala leverv\xe4rden'],
             ['Eye', u'Hudutslag'],
             ['Eye', u'Ledv\xe4rk'],
             ['Eye', u'Dysuri, hematuri, frekvent urinering']]],
           ['Rare',
            [['Eye', u's\xe4llsynt Blodk\xe4rl Vanlig Hypotension, postural hypotension'],
             ['Eye',
              u's\xe4llsynt Andningsv\xe4gar, br\xf6stkorg och Vanlig Bronkit, hosta, dyspn\xe9, rinit mediastinum'],
             ['Eye',
              u's\xe4llsynt Magtarmkanalen Vanlig Magsm\xe4rtor, dyspepsi, muntorrhet, illam\xe5ende'],
             ['Eye', u's\xe4llsynt Hud och subkutan v\xe4vnad Vanlig Kl\xe5da'],
             ['Eye',
              u's\xe4llsynt Muskuloskeletala systemet och Vanlig Ryggv\xe4rk, myalgi bindv\xe4v'],
             ['Eye', u's\xe4llsynt Njurar och urinv\xe4gar Vanlig Cystit, urininkontinens'],
             ['Eye',
              u'diures Reproduktionsorgan och Mindre vanlig Impotens br\xf6stk\xf6rtel Mycket gynekomasti, priapism'],
             ['Eye', u's\xe4llsynt']]],
           ['Unknown',
            [['Eye',
              u'IFIS (Intraoperative floppy iris syndrome, se frekvens avsnitt 4.4) \xd6ron och balansorgan Vanlig Vertigo']]]],
 '_pages': [4, 6],
 u'_rank': 26,
 u'_type': u'LSFU'}