{'_data': [['Very common',
            [['Infections', u'Blodet och lymfsystemet  '],
<<<<<<< HEAD
             ['Immune system', u'Postural yrsel, parestesi'],
             ['Immune system', u'Bradykardi, kardiella arytmier'],
             ['Immune system', u'Flush'],
             ['Immune system', u'Bronkospasm'],
             ['Immune system', u'Gallstas, hepatit, gulsot'],
             ['Immune system', u'Alopeci, purpura, urtikaria'],
             ['Immune system', u'Muskelkramper, muskelsvaghet'],
             ['Immune system', u'miktionssv\xe5righeter, nokturi, polyuri, \xf6kad'],
             ['Immune system', u'gynekomasti, priapism']]],
           ['Common',
            [['Immune system', u'Metabolism och nutrition Mindre Anorexi, gikt, \xf6kad aptit'],
             ['Immune system',
              u'Psykiska st\xf6rningar Mindre \xc5ngest, depression, s\xf6mnl\xf6shet'],
             ['Immune system', u'synkope, tremor'],
             ['Immune system',
              u'vanlig Hj\xe4rtat Vanlig Palpitation, takykardi Mindre Angina pectoris, myokardinfarkt'],
             ['Immune system', u'vanlig'],
             ['Immune system', u'vanlig'],
             ['Immune system',
              u'gastroenterit Lever och gallv\xe4gar Mindre Onormala leverv\xe4rden'],
             ['Immune system', u'vanlig'],
             ['Immune system', u'vanlig'],
             ['Immune system', u'vanlig'],
             ['Immune system', u'vanlig'],
             ['Investigations', u'vanlig']]],
           ['Rare',
            [['Immune system',
              u'Centrala och perifera Vanlig Yrsel, huvudv\xe4rk, s\xf6mnighet'],
             ['Immune system', u's\xe4llsynt \xd6gon Mycket Dimsyn'],
             ['Immune system', u's\xe4llsynt'],
             ['Immune system',
              u's\xe4llsynt Blodk\xe4rl Vanlig Hypotension, postural hypotension'],
             ['Immune system',
              u's\xe4llsynt Andningsv\xe4gar, br\xf6stkorg och Vanlig Bronkit, hosta, dyspn\xe9, rinit mediastinum Mindre Epistaxis'],
             ['Immune system',
              u's\xe4llsynt Magtarmkanalen Vanlig Magsm\xe4rtor, dyspepsi, muntorrhet, illam\xe5ende Mindre F\xf6rstoppning, diarr\xe9, flatulens, kr\xe4kningar,'],
             ['Immune system',
              u's\xe4llsynt Hud och subkutan v\xe4vnad Vanlig Kl\xe5da Mindre Hudutslag'],
             ['Immune system',
              u's\xe4llsynt Muskuloskeletala systemet och Vanlig Ryggv\xe4rk, myalgi bindv\xe4v Mindre Ledv\xe4rk'],
             ['Immune system',
              u's\xe4llsynt Njurar och urinv\xe4gar Vanlig Cystit, urininkontinens Mindre Dysuri, hematuri, frekvent urinering'],
             ['Immune system',
              u'diures Reproduktionsorgan och Mindre Impotens br\xf6stk\xf6rtel vanlig'],
             ['Immune system', u's\xe4llsynt']]],
           ['Unknown',
            [['Immune system',
              u'F\xf6r\xe4ndring av irismuskeln under kataraktoperation, p\xe5 engelska \u201dIntraoperative Floppy Iris Syndrome\u201d (se avnsitt 4.4) \xd6ron och balansorgan Vanlig Vertigo Mindre Tinnitus']]]],
 '_pages': [4, 5],
 u'_rank': 34,
=======
             ['Eye', u'Bradykardi, kardiella arytmier'],
             ['Eye', u'Flush'],
             ['Eye', u'Bronkospasm'],
             ['Eye', u'Gallstas, hepatit, gulsot'],
             ['Eye', u'Alopeci, purpura, urtikaria'],
             ['Eye', u'Muskelkramper, muskelsvaghet'],
             ['Eye', u'miktionssv\xe5righeter, nokturi, polyuri, \xf6kad'],
             ['Eye', u'gynekomasti, priapism']]],
           ['Uncommon',
            [['Immune system', u'Metabolism och nutrition  '],
             ['Immune system', u'Psykiska st\xf6rningar  '],
             ['Eye', u'Tinnitus Hj\xe4rtat Vanlig Palpitation, takykardi'],
             ['Eye', u'Angina pectoris, myokardinfarkt'],
             ['Eye', u'Epistaxis'],
             ['Eye',
              u'F\xf6rstoppning, diarr\xe9, flatulens, kr\xe4kningar, gastroenterit Lever och gallv\xe4gar Mindre vanlig Onormala leverv\xe4rden'],
             ['Eye', u'Hudutslag'],
             ['Eye', u'Ledv\xe4rk'],
             ['Eye', u'Dysuri, hematuri, frekvent urinering']]],
           ['Rare',
            [['Eye', u's\xe4llsynt Blodk\xe4rl Vanlig Hypotension, postural hypotension'],
             ['Eye',
              u's\xe4llsynt Andningsv\xe4gar, br\xf6stkorg och Vanlig Bronkit, hosta, dyspn\xe9, rinit mediastinum'],
             ['Eye',
              u's\xe4llsynt Magtarmkanalen Vanlig Magsm\xe4rtor, dyspepsi, muntorrhet, illam\xe5ende'],
             ['Eye', u's\xe4llsynt Hud och subkutan v\xe4vnad Vanlig Kl\xe5da'],
             ['Eye',
              u's\xe4llsynt Muskuloskeletala systemet och Vanlig Ryggv\xe4rk, myalgi bindv\xe4v'],
             ['Eye', u's\xe4llsynt Njurar och urinv\xe4gar Vanlig Cystit, urininkontinens'],
             ['Eye', u'diures Reproduktionsorgan och Mindre vanlig Impotens br\xf6stk\xf6rtel'],
             ['Eye', u's\xe4llsynt']]],
           ['Unknown',
            [['Eye',
              u'F\xf6r\xe4ndring av irismuskeln under kataraktoperation, p\xe5 engelska \u201dIntraoperative Floppy Iris Syndrome\u201d (se avnsitt 4.4) \xd6ron och balansorgan Vanlig Vertigo']]]],
 '_pages': [4, 5],
 u'_rank': 27,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}