{'_data': [['Common',
            [['Cardiac', u'Yrsel, huvudv\xe4rk.'],
             ['GI', u'Buksm\xe4rtor, illam\xe5ende, dyspepsi.'],
             ['General', u'Asteni.']]],
           ['Uncommon',
            [['Cardiac',
              u'Synkope (initialt, framf\xf6r allt vid f\xf6r h\xf6g dos, eller vid \xe5terupptagen terapi efter kortare avbrott), postural hypotension (initialt, framf\xf6r allt vid f\xf6r h\xf6g dos, eller vid \xe5terupptagen terapi efter kortare avbrott), takykardi.'],
             ['Cardiac', u'Svindel, d\xe5sighet.'],
             ['Eye', u'Rinit.'],
             ['GI', u'Kr\xe4kningar, diarr\xe9, muntorrhet.'],
             ['Skin', u'Hudutslag (urtikaria, exantem), pruritus.'],
             ['General', u'Br\xf6stsm\xe4rtor, \xf6dem, v\xe4rmevallningar.']]],
           ['Very rare',
            [['Cardiac',
              u'Angina pectoris, f\xf6retr\xe4desvis hos patienter med befintlig kransk\xe4rlssjukdom (se avsnitt 4.4).'],
             ['Skin', u'Angio\xf6dem.']]],
           ['Unknown',
            [['Blood', u'Neutropeni, trombocytopeni.'],
             ['Cardiac', u'F\xf6rmaksflimmer. Centrala och perifera'],
             ['Eye',
              u'Intraoperative Floppy Iris Syndrome (se avsnitt 4.4). Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['General', u'och/eller symtom p\xe5 administreringsst\xe4llet'],
             ['Hepato',
              u'Hepatocellul\xe4r skada, kolestatisk leversjukdom. Reproduktionsorgan och br\xf6stk\xf6rtel']]]],
 '_pages': [3, 4],
 u'_rank': 16,
 u'_type': u'LSFU'}