{'_data': [['Common',
            [['Nervous system', u'svindel/yrsel, huvudv\xe4rk'],
             ['GI', u'illam\xe5ende, buksm\xe4rtor'],
             ['General', u'asteni']]],
           ['Uncommon',
            [['Nervous system', u'synkop\xe9*, vertigo'],
             ['Cardiac', u'takykardi'],
             ['Vascular', u'postural hypotension*,  v\xe4rmevallningar'],
             ['Respiratory', u'rinit'],
             ['GI', u'dyspepsi, diarr\xe9'],
             ['Skin', u'hudutslag (urtikaria), exantem,  pruritus'],
             ['Renal', u'urininkontinens'],
             ['General', u'\xf6dem, br\xf6stsm\xe4rtor']]],
           ['Very rare',
            [['Cardiac', u'angina pectoris hos patienter med  befintlig kransk\xe4rlssjukdom'],
             ['Skin', u'angio\xf6dem']]],
           ['Unknown',
            [['Blood', u'neutropeni'],
             ['Eye', u'Intraoperative Floppy Iris  Syndrome'],
             ['Cardiac', u'f\xf6rmaksflimmer'],
             ['GI', u'kr\xe4kningar'],
             ['Hepato', u'hepatocellul\xe4r skada, kolestatisk  leversjukdom'],
             ['Reproductive system', u'priapism']]]],
 '_pages': [3, 3],
 u'_rank': 19,
 u'_type': u'TSFU'}