{'_data': [['Common',
            [['Blood', u'Anemi'],
             ['Nervous system', u'Huvudv\xe4rk Yrsel'],
             ['GI', u'Buksm\xe4rta Illam\xe5ende Halsbr\xe4nna Dyspepsi'],
             ['Renal', u'Dysuri'],
             ['Hepato', u'Hepatit']]],
           ['Uncommon',
            [['Cardiac', u'Palpitationer'],
             ['GI',
              u'Kr\xe4kningar F\xf6rstoppning Diarr\xe9 Stomatit Gastrointestinal Ulcus duodeni Ulcus ventriculi Gastrit Melaena Ulcerativ stomatit Muntorrhet'],
             ['Skin', u'Exantem Urtikaria Kl\xe5da'],
             ['Metabolism', u'Anorexi'],
             ['General', u'Tr\xf6tthet \xd6dem'],
             ['Psychiatric', u'S\xf6mnst\xf6rningar']]],
           ['Rare',
            [['Cardiac', u'Hj\xe4rtsvikt'],
             ['Blood',
              u'Leukopeni Agranulocytos Trombocytopeni trombocyt-aggregation med \xf6kad bl\xf6dningsben\xe4genhet'],
             ['Eye', u'Synst\xf6rningar'],
             ['Ear', u'\xd6ronsusningar'],
             ['GI',
              u'GI-perforering Hematemes Flatulens F\xf6rs\xe4mring av ulcer\xf6s kolit F\xf6rs\xe4mring av Crohns'],
             ['Skin',
              u'Fotosensibilitet Erythema multiforme Stevens-Johnsons syndrom Toxisk epidermal nekrolys (Lyells syndrom)'],
             ['Vascular',
              u'F\xf6rh\xf6jt blodtryck (fr\xe4mst hos patienter behandlade med kardiovaskul\xe4ra l\xe4kemedel)'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner (dyspn\xe9, astma, anafylaxi och angio\xf6dem)']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 19,
 u'_type': u'MSFU'}