{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk.'],
             ['GI', u'Dyspepsi, diarr\xe9, illam\xe5ende, kr\xe4kningar, buksm\xe4rtor.'],
             ['Skin', u'Hudutslag.'],
             ['General', u'Tr\xf6tthet.']]],
           ['Uncommon',
            [['Eye', u'Synrubbningar.'],
             ['Ear', u'H\xf6rselp\xe5verkan.'],
             ['Respiratory', u'Rinit, astma.'],
             ['GI',
              u'Bl\xf6dningar, melena, haematemesis, ulcus, ulcerativ stoatit, flatulens, f\xf6rstoppning, exacerbation av ulcer\xf6s colit och Crohns sjukdom (se 4.4), gastrit.'],
             ['Skin', u'Urtikaria, pruritus, purpura, angio\xf6dem.'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, l\xe4tt oro.']]],
           ['Rare',
            [['Cardiac', u'Hj\xe4rtsvikt.'],
             ['Blood', u'Leukopeni, trombocytopeni.'],
             ['Nervous system', u'Aseptisk meningit.'],
             ['Eye', u'Toxisk amblyopi.'],
             ['GI', u'Perforationer.'],
             ['Renal', u'Njurp\xe5verkan.'],
             ['Skin', u'Erythema multiforme, Stevens-Johnsons syndrom.'],
             ['Metabolism', u'\xd6dem.'],
             ['Vascular', u'Hypertension'],
             ['Immune system', u'Anafylaktisk reaktion.'],
             ['Hepato', u'Leverp\xe5verkan'],
             ['Psychiatric',
              u'Depression, konfusion. Gastrointestinala s\xe5r, perforation eller bl\xf6dning kan ibland vara d\xf6dlig, s\xe4rskilt hos \xe4ldre (se 4.4) Ibuprofen kan orsaka f\xf6rl\xe4ngning av bl\xf6dningstiden genom reversibel h\xe4mning av trombocytaggregationen. I de flesta fall d\xe4r aseptisk meningit rapporterats har n\xe5gon form av autoimmun grundsjukdom f\xf6relegat. \xd6dem, hypertension och hj\xe4rtsvikt har rapporterats i samband med NSAID-behandling. Kliniska pr\xf6vningar och epidermiologiska data tyder p\xe5 att anv\xe4ndning av ibuprofen, s\xe4rskilt i h\xf6ga doser (2400 mg dagligen) och l\xe5ngtidsbehandling, kan medf\xf6ra en liten \xf6kad risk f\xf6r arteriella trombotiska h\xe4ndelser (till exempel hj\xe4rtinfarkt eller stroke, se avsnitt 4.4). I s\xe4llsynta fall f\xf6rekommer allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor.']]],
           ['Very rare', [['Skin', u'Toxisk epidermal nekrolys.']]]],
 '_pages': [5, 7],
 u'_rank': 23,
 u'_type': u'LSFU'}