{'_data': [['Very common',
            [['Blood',
              u'leukopeni, trombocytopeni och anemi till f\xf6ljd av benm\xe4rgsdepression.'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning och diarr\xe9 (illam\xe5ende och kr\xe4kning har rapporterats hos upp till 30% av patienterna som fick Alkeran i normaldos). Stomatit vid h\xf6gdosbehandling.'],
             ['Skin', u'alopeci vid h\xf6gdosbehandling.'],
             ['Reproductive system', u'amenorr\xe9.']]],
           ['Common',
            [['Renal',
              u'tempor\xe4r signifikant h\xf6jning av blodurea har setts i tidiga stadier av Alkeranbehandling av myelompatienter med njurskada.'],
             ['Skin', u'alopeci vid normaldosbehandling.'],
             ['Neoplasms', u'sekund\xe4r malignitet, fr\xe4mst leukemi.']]],
           ['Rare',
            [['Blood', u'hemolytisk anemi.'],
             ['Respiratory',
              u'interstitiell pneumonit och pulmonell fibros (inkluderande fatala rapporter ).'],
             ['GI', u'stomatit vid normaldosering.'],
             ['Skin', u'makulopapul\xf6st exantem, pruritus.'],
             ['Immune system',
              u'allergiska reaktioner. Allergiska reaktioner mot melfalan s\xe5som urtikaria, \xf6dem, hudutslag och anafylaktisk chock har rapporterats som mindre vanliga reaktioner b\xe5de i b\xf6rjan av och under p\xe5g\xe5ende behandling (detta g\xe4ller s\xe4rskilt efter administrering av intraven\xf6s beredning). Hj\xe4rtstillest\xe5nd har ocks\xe5 rapporterats i s\xe4llsynta fall i samband med anafylaktisk chock.'],
             ['Hepato', u'f\xf6rh\xf6jda leverfunktionsv\xe4rden, hepatit, ikterus.']]]],
 '_pages': [3, 4],
 u'_rank': 13,
 u'_type': u'LSFU'}