{'_data': [['Common',
            [['Nervous system', u'yrsel, somnolens.'],
             ['GI', u'illam\xe5ende, kr\xe4kningar.'],
             ['General', u'tr\xf6tthet.']]],
           ['Uncommon',
            [['Nervous system', u'parestesi, huvudv\xe4rk.'],
             ['Ear', u'tinnitus.'],
             ['Cardiac', u'palpitation.'],
             ['Respiratory', u'\xe5tstramningsk\xe4nsla i halsen.'],
             ['GI', u'diarr\xe9, dyspepsi, muntorrhet.'],
             ['Musculoskeletal', u'muskelsm\xe4rta, skelettsm\xe4rta'],
             ['General', u'br\xf6stsm\xe4rta, asteni.']]],
           ['Very rare', [['Cardiac', u'kransk\xe4rlsvasospasm, hj\xe4rtinfarkt, takykardi.']]],
           ['Unknown', [['Nervous system', u'Krampanfall.']]]],
 '_pages': [4, 5],
 u'_rank': 12,
 u'_type': u'LSFU'}