{'_data': [[u'Unknown',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Hyperkalemi, metabola'],
             ['Psychiatric', u'\xc5ngest, euforisk'],
             ['Nervous system',
              u'Huvudv\xe4rk   D\xe5sighet, s\xf6mnl\xf6shet,   Yrsel   parestesier, hypersomni,'],
             ['Eye', u'\xd6gonirritation,   amblyopi'],
             ['Ear', u'R\xf6relsesjuka, tinnitus'],
             ['Cardiac', u'Takykardi,   bradykardi,'],
             ['Vascular', u'Hypotension,'],
             ['Respiratory', u'Hicka'],
             ['Hepato', u'Hyperbilirubinemi'],
             ['Skin', u'Allergisk dermatit, kliande'],
             ['Musculoskeletal', u'Ledv\xe4rk'],
             ['Renal', u'Urinretention, glukosuri'],
             ['General',
              u'Asteni, pyrexi, tr\xf6tthet,   Reaktioner vid   v\xe4rmek\xe4nsla,   injektionsst\xe4llet*   influensaliknande symtom'],
             ['Investigations', u'F\xf6rh\xf6jda   transaminaser,']]]],
 '_pages': [3, 4],
 u'_rank': 15,
 u'_type': u'LFSU'}