{'_data': [['Common', [['Nervous system', u'Huvudv\xe4rk']]],
           ['Uncommon',
            [['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Eye', u'\xd6gonsvullnad'],
             ['Cardiac',
              u'Atrioventrikul\xe4rt block, f\xf6rsta graden, atrioventrikul\xe4rt block, andra graden'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'F\xf6rstoppning,   illam\xe5ende'],
             ['Musculoskeletal', u'Myalgi'],
             ['Investigations', u'F\xf6rh\xf6jt bilirubin i blodet']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 8,
 u'_type': u'MSFU'}