{'_data': [['Very common',
            [['Blood', u'Leukocytopeni, trombocytopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system', u'Hypertoni, perifer neuropati'],
             ['Cardiac', u'Hj\xe4rtinfarkt, arytmi (inkl. bradykardi, ventrikul\xe4r'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Pankreatit, gastrit, gingival hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda leverenzymer*'],
             ['Skin', u'Angio\xf6dem, erythema multiforme, urtikaria,']]],
           ['Common',
            [['Nervous system',
              u'S\xf6mnighet, yrsel, huvudv\xe4rk (s\xe4rskilt i b\xf6rjan av  behandlingen)'],
             ['Cardiac', u'Palipitationer'],
             ['Vascular', u'Vallningar'],
             ['GI', u'Buksm\xe4rtor, illam\xe5ende'],
             ['Musculoskeletal', u'Ankelsvullnad'],
             ['Investigations', u'']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnsv\xe5righeter, hum\xf6rsv\xe4ngningar (\xe4ven  \xe5ngest), depression'],
             ['Nervous system', u'Tremor, dysgeusi, svimning, hypestesi, parestesi'],
             ['Eye', u'Synrubbningar (inklusive diplopi)'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9, rinit'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi, f\xf6r\xe4ndrade tarmvanor (inkl.  diarr\xe9 och f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura, hudmissf\xe4rgningar, hyperhidros,  kl\xe5da, hudutslag, exantem.'],
             ['Musculoskeletal', u'Artralgi, myalgi, muskelkramper, ryggsm\xe4rtor'],
             ['Renal', u'Miktionsst\xf6rningar, nokturi, \xf6kad  urineringsfrekvens'],
             ['Reproductive system', u'Impotens, gynekomasti'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare',
            [['Blood', u''],
             ['Immune system', u''],
             ['Metabolism', u''],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u''],
             ['Cardiac', u'takykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u''],
             ['Skin',
              u'exfoliativ dermatit, Stevens-Johnsons syndrom,  Quinckes \xf6dem, fotosensibilitet']]]],
 '_pages': [4, 5],
 u'_rank': 30,
 u'_type': u'TSFU'}