{'_data': [['Very common',
            [['Blood', u'Leukocytopeni, trombocytopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system', u'Hypertoni, perifer neuropati'],
             ['Cardiac', u'Hj\xe4rtinfarkt, arytmi (inkl. bradykardi,'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Pankreatit, gastrit, gingival hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda leverenzymer*'],
             ['Skin', u'Angio\xf6dem, erythema multiforme, urtikaria,']]],
           ['Common',
            [['Nervous system',
              u'S\xf6mnighet, yrsel,  huvudv\xe4rk (s\xe4rskilt i b\xf6rjan av behandlingen)'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Vallningar'],
             ['GI', u'Buksm\xe4rta, illam\xe5ende'],
             ['Musculoskeletal', u'Ankelsvullnad'],
             ['General', u'\xd6dem, tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnsv\xe5righeter, humh\xf6rsv\xe4ngningar (\xe4ven  \xe5ngest), depression'],
             ['Nervous system', u'Tremor, dysgeusi, svimning, hypoestesi,  parestesi'],
             ['Eye', u'Synrubbningar (inklusive diplopi)'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Hypoteni'],
             ['Respiratory', u'Dyspn\xe9, rinit'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi, f\xf6r\xe4ndrade tarmvanor  (inkl. diarr\xe9 och f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura, hudmissf\xe4rgningar,  hyperhidros, kl\xe5da, hudutslag, exantem  L\xe4kemedelsveket 2013-02-28'],
             ['Musculoskeletal', u'Artralgi, myalgi, muskelkramper,  ryggsm\xe4rtor'],
             ['Renal', u'Miktionsst\xf6rningar, nokturi, \xf6kad  urineringsfrekvens'],
             ['Reproductive system', u'Impotens, gynekomasti'],
             ['General', u'Br\xf6stsm\xe4rta, asteni, v\xe4rk, sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare',
            [['Blood', u''],
             ['Immune system', u''],
             ['Metabolism', u''],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u''],
             ['Cardiac', u'ventrikul\xe4r takykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u''],
             ['Skin',
              u'exfoliativ dermatit, Stevens-Johnson  syndrom, Quincke-\xf6dem, fotosensibilitet']]]],
 '_pages': [3, 5],
 u'_rank': 32,
 u'_type': u'TSFU'}