<<<<<<< HEAD
{'_data': [['Common',
            [['Nervous system',
              u'S\xf6mnighet, yrsel, huvudv\xe4rk  (s\xe4rskilt i b\xf6rjan av  behandlingen)'],
             ['Vascular', u'Vallningar'],
             ['GI', u'Buksm\xe4rtor, illam\xe5ende'],
             ['Musculoskeletal', u'Ankelsvullnad'],
             ['General', u'\xd6dem, tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnst\xf6rningar,  hum\xf6rsv\xe4ngningar (\xe4ven \xe5ngest), depression'],
             ['Nervous system', u'Tremor, dysgeusi, synkope,  hypestesi, parestesi'],
             ['Eye', u'Synrubbningar (inklusive  diplopi)'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9, rinit'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi,  f\xf6r\xe4ndrade tarmvanor (inklusive diarr\xe9 och f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura,  hudmissf\xe4rgningar, hyperhidros, kl\xe5da, hudutslag, exantem'],
             ['Musculoskeletal', u'Artralgi, myalgi,  muskelkramper, ryggsm\xe4rtor'],
             ['Renal', u'Miktionsst\xf6rningar, nokturi,  \xf6kad urineringsfrekvens'],
             ['Reproductive system', u'Impotens, gynekomasti'],
             ['General', u'Br\xf6stsm\xe4rtor, asteni, v\xe4rk,  sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare', [['Psychiatric', u'F\xf6rvirring']]],
=======
{'_data': [['Common', [['Vascular', u'Vallningar'], ['GI', u'Buksm\xe4rtor, illam\xe5ende']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnst\xf6rningar,  hum\xf6rsv\xe4ngningar (inklusive \xe5ngest), depression'],
             ['Psychiatric', u'Tremor, smakst\xf6rningar,  synkope, hypoestesi, parestesier'],
             ['Eye', u'Synrubbningar (inklusive  dubbelseende)'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotension'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi,  f\xf6r\xe4ndrade tarmr\xf6relser (inklusive diarr\xe9 och f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura,  f\xe4rgf\xf6r\xe4ndringar i huden, hyperhidros, pruritus, hudutslag, exantem'],
             ['Renal', u'Miktionsrubbningar, nokturi,  \xf6kad urineringsfrekvens'],
             ['Reproductive system', u'Impotens, gynekomasti  sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning eller viktminskning']]],
           ['Rare', [['Psychiatric', u'F\xf6rvirring  behandlingen)']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Very rare',
            [['Blood', u'Leukocytopeni, trombocytopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
<<<<<<< HEAD
             ['Nervous system', u'Hypertoni, perifer neuropati'],
             ['Cardiac',
              u'Hj\xe4rtinfarkt, arytmi (inklusive  bradykardi, ventrikul\xe4r takykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Pankreatit, gastrit, gingival  hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda  leverenzymer*'],
             ['Skin',
              u'Angio\xf6dem, erytema  multiforme, urtikaria, exfoliativ dermatit, Stevens-Johnson syndrom, Quinckes \xf6dem, fotosensibilitet']]]],
 '_pages': [4, 5],
 u'_rank': 30,
=======
             ['Psychiatric', u'Hypertoni, perifer neuropati'],
             ['Cardiac',
              u'Myokardinfarkt, arytmier  (inklusive bradykardi, ventrikul\xe4r takykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit, gastrit, gingival  hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda  leverenzymniv\xe5er*'],
             ['Skin',
              u'Angio\xf6dem, erytema  multiforme, urtikaria, exfoliativ dermatit, Stevens Johnson syndrom, Quincke\xf6dem, fotosensibilitet muskelkramper, ryggv\xe4rk']]]],
 '_pages': [3, 4],
 u'_rank': 23,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}