{'_data': [['Very common',
            [['Blood', u'Leukocytopeni, trombocytopeni.'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system', u'Hypertoni, perifer neuropati'],
             ['Cardiac', u'Hj\xe4rtinfarkt, arytmi (inklusive bradykardi,,'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Pankreatit, gastrit, gingival hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda* leverenzymer'],
             ['Skin', u'Angi\xf6dem, erythema multiforme, urtikaria,']]],
           ['Common',
            [['Nervous system',
              u'Somnolens, yrsel, huvudv\xe4rk (s\xe4rskilt i b\xf6rjan  av behandlingen)'],
             ['Vascular', u'V\xe4rmevallningar'],
             ['Musculoskeletal', u'Svullna fotleder'],
             ['General', u'\xd6dem, tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric',
              u'Insomni, st\xe4mningsf\xf6r\xe4ndringar, inklusive  \xe5ngest, depression'],
             ['Nervous system', u'Tremor, dysgeusi, synkope, hypoestesi,  parestesi'],
             ['Eye', u'Synrubbningar, inklusive diplopi'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9, rinit'],
             ['GI',
              u'Kr\xe4kning, dyspepsi, f\xf6r\xe4ndrade  tarmt\xf6mningsvanor (inklusive diarr\xe9 och  f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura, missf\xe4rgning av huden,  hyperhidros, pruritus, utslag, exantem'],
             ['Musculoskeletal', u'Muskelkramper, ryggv\xe4rk, muskelv\xe4rk och  ledv\xe4rk'],
             ['Renal', u'Miktionsrubbningar, nokturi, \xf6kad  bl\xe5st\xf6mningsfrekvens.'],
             ['Reproductive system', u'Impotens, gynekomasti'],
             ['General', u'Br\xf6stsm\xe4rta, asteni, sm\xe4rta, allm\xe4n  sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare',
            [['Blood', u''],
             ['Immune system', u''],
             ['Metabolism', u''],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u''],
             ['Cardiac', u'kammartakykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u''],
             ['Skin',
              u'exfoliativ dermatit, Stevens-Johnsons  syndrom, Quinckes \xf6dem , fotosensitivitet']]]],
 '_pages': [4, 5],
 u'_rank': 31,
 u'_type': u'TSFU'}