{'_data': [['Common', [['Vascular', u'Vallningar'], ['GI', u'Buksm\xe4rtor, illam\xe5ende']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnst\xf6rningar,  hum\xf6rsv\xe4ngningar (inklusive \xe5ngest), depression'],
             ['Psychiatric', u'Tremor, smakst\xf6rningar,  synkope, hypoestesi, parestesier'],
             ['Eye', u'Synrubbningar (inklusive  dubbelseende)'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotension'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi,  f\xf6r\xe4ndrade tarmr\xf6relser (inklusive diarr\xe9 och f\xf6rstoppning), muntorrhet'],
             ['Skin',
              u'Alopeci, purpura,  f\xe4rgf\xf6r\xe4ndringar i huden, hyperhidros, pruritus, hudutslag, exantem'],
             ['Renal', u'Miktionsrubbningar, nokturi,  \xf6kad urineringsfrekvens'],
             ['Reproductive system', u'Impotens, gynekomasti  sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning eller viktminskning']]],
           ['Rare', [['Psychiatric', u'F\xf6rvirring  behandlingen)']]],
           ['Very rare',
            [['Blood', u'Leukocytopeni, trombocytopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
             ['Psychiatric', u'Hypertoni, perifer neuropati'],
             ['Cardiac',
              u'Myokardinfarkt, arytmier  (inklusive bradykardi, ventrikul\xe4r takykardi och f\xf6rmaksflimmer)'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit, gastrit, gingival  hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda  leverenzymniv\xe5er*'],
             ['Skin',
              u'Angio\xf6dem, erytema  multiforme, urtikaria, exfoliativ dermatit, Stevens Johnson syndrom, Quincke\xf6dem, fotosensibilitet muskelkramper, ryggv\xe4rk']]]],
 '_pages': [3, 4],
 u'_rank': 23,
 u'_type': u'TSFU'}