{'_data': [['Very common',
            [['Blood', u'Leukocytopeni, trombocytopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system', u'Hypertoni,'],
             ['Cardiac', u'Hj\xe4rtinfarkt, arytmi (inkl.'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Pankreatit, gastrit, gingival hyperplasi'],
             ['Hepato', u'Hepatit, gulsot, f\xf6rh\xf6jda'],
             ['Skin', u'kl\xe5da, hudutslag, exantem. Angio\xf6dem, erythema multiforme,']]],
           ['Common',
            [['Nervous system',
              u'S\xf6mnighet, yrsel, huvudv\xe4rk  (s\xe4rskilt i b\xf6rjan av behandlingen)'],
             ['Cardiac', u'Palipitationer'],
             ['Vascular', u'Vallningar'],
             ['GI', u'Buksm\xe4rtor, illam\xe5ende'],
             ['Musculoskeletal', u'Ankelsvullnad'],
             ['General', u'\xd6dem, tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric',
              u'S\xf6mnsv\xe5righeter, hum\xf6rsv\xe4ngningar  (\xe4ven \xe5ngest), depression'],
             ['Nervous system', u'Tremor, dysgeusi, svimning,  hypestesi, parestesi'],
             ['Eye', u'Synrubbningar (inklusive diplopi)'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9, rinit'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi,  f\xf6r\xe4ndrade tarmvanor (inkl.  diarr\xe9 och f\xf6rstoppning),'],
             ['Skin', u'Alopeci, purpura,  hudmissf\xe4rgningar, hyperhidros,'],
             ['Musculoskeletal', u'Artralgi, myalgi,  muskelkramper, ryggsm\xe4rtor'],
             ['Renal', u'Miktionsst\xf6rningar, nokturi,  \xf6kad urineringsfrekvens'],
<<<<<<< HEAD
=======
             ['Reproductive system', u'Impotens, gynekomasti'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Br\xf6stsm\xe4rtor, asteni,  v\xe4rk, sjukdomsk\xe4nsla'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare',
            [['Blood', u''],
             ['Immune system', u''],
             ['Metabolism', u''],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u'perifer'],
             ['Cardiac', u'bradykardi, ventrikul\xe4r takykardi'],
             ['Vascular', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u'leverenzymer*'],
             ['Skin', u'urtikaria, exfoliativ dermatit,']]]],
 '_pages': [7, 8],
<<<<<<< HEAD
 u'_rank': 33,
=======
 u'_rank': 34,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}