{'_data': [['Common', [['Infections', u'Mukokutan candidiasis  ']]],
           ['Uncommon',
            [['Skin', u'Hudutslag  '], ['Skin', u'Kl\xe5da  '], ['Skin', u'Urticaria  ']]],
           ['Rare', [['Skin', u'Erythema multiforme  ']]],
           ['Unknown',
            [['Infections', u'\xd6verv\xe4xt av icke-k\xe4nsliga organismer  '],
             ['Blood', u'protrombintid'],
             ['Immune system', u'Angioneurotiskt \xf6dem  '],
             ['Immune system', u'Anafylaxi  '],
             ['Immune system', u'Syndrom liknande serumsjuka  '],
             ['Immune system', u'\xd6verk\xe4nslighetvaskulit  '],
             ['Nervous system', u'Krampanfall 2 Ingen k\xe4nd frekvens'],
             ['GI',
              u'Illam\xe5ende 3 Vanliga Kr\xe4kningar Vanliga Matsm\xe4ltningsbesv\xe4r Mindre vanliga Antibiotikautl\xf6st kolit 4 Ingen k\xe4nd frekvens Svart, h\xe5rig tunga Ingen k\xe4nd frekvens'],
             ['Hepato',
              u'\xd6kningar av ASAT och/eller ALAT 5 Mindre vanliga Hepatitis 6 Ingen k\xe4nd frekvens Kolestatisk gulsot 6 Ingen k\xe4nd frekvens'],
             ['Skin', u'Stevens-Johnsons syndrom  '],
             ['Skin', u'Toxisk epidermal nekrolys  '],
             ['Skin', u'Bull\xf6s exfoliativ dermatit  '],
             ['Renal',
              u'Kristalluri 8 Ingen k\xe4nd frekvens Se avsnitt 4.4 Se avsnitt 4.4. 3 Illam\xe5ende f\xf6rknippas oftare med h\xf6ga orala doser. Om gastrointestinala reaktioner \xe4r p\xe5tagliga kan de reduceras genom att Amoxicillin/Clavulanic acid BB tas i b\xf6rjan av en m\xe5ltid. Inklusive pseudomembran\xf6s kolit och bl\xf6dande kolit (se avsnitt 4.4) 5 En m\xe5ttlig \xf6kning av ASAT och/eller ALAT har noterats hos patienter behandlade med betalaktamantibiotika, men signifikansen av dessa resultat \xe4r']]]],
 '_pages': [5, 6],
 u'_rank': 18,
 u'_type': u'LSFU'}