{'_data': [['Very common', [['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Infections', u'Mukokutan candidiasis  '],
             ['GI', u'Kr\xe4kningar'],
             ['GI', u'Matsm\xe4ltningsbesv\xe4r']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel  '],
             ['Nervous system', u'Huvudv\xe4rk  '],
             ['GI', u'Antibiotikautl\xf6st kolit'],
             ['Hepato', u'\xd6kningar av ASAT och/eller ALAT  '],
             ['Skin', u'Hudutslag'],
             ['Skin', u'Pruritus'],
             ['Skin', u'Urticaria Erythema multiforme S\xe4llsynta']]],
           ['Rare', [['Blood', u'Trombocytopeni'], ['Blood', u'Reversibel agranulocytos']]],
           ['Unknown',
            [['Infections', u'\xd6verv\xe4xt av icke-k\xe4nsliga organismer  '],
             ['Blood', u'Reversibel leukopeni (inklusive neutropeni)'],
             ['Immune system', u'Angioneurotiskt \xf6dem'],
             ['GI', u'Diarr\xe9'],
             ['Hepato', u'Hepatit  '],
             ['Hepato', u'Kolestatisk gulsot  '],
             ['Skin', u'Stevens-Johnsons syndrom'],
             ['Renal', u'Interstitiell nefrit']]]],
 '_pages': [5, 7],
 u'_rank': 21,
 u'_type': u'LSFU'}