{'_data': [['Common', [['Nervous system', u'huvudv\xe4rk']]],
           ['Uncommon',
            [['Nervous system', u'dysgeusi'],
             ['Vascular', u'rodnad'],
             ['GI', u'illam\xe5ende'],
             ['Skin', u'kl\xe5da, n\xe4sselutslag'],
             ['General',
              u'utslag vid infusionsst\xe4llet. Exponering f\xf6r joniserande str\xe5lning \xe4r kopplat till cancerutveckling och en risk f\xf6r medf\xf6dda defekter. Eftersom den effektiva dosen \xe4r 7 mSv n\xe4r den rekommenderade radioaktiviteten om 370 MBq florbetapir (F) administreras, \xe4r sannolikheten l\xe5g f\xf6r att dessa biverkningar ska uppst\xe5.']]]],
 '_pages': [6, 6],
 u'_rank': 6,
 u'_type': u'LSFU'}