{'_data': [['Very common',
            [['Vascular', u'V\xe4rmevallningar'],
             ['GI', u'Illam\xe5ende'],
             ['General', u'Asteni']]],
           ['Common',
            [['Metabolism', u'Anorexi  Hyperkolesterolemi'],
             ['Nervous system', u'Somnolens  Karpaltunnelsyndrom*'],
             ['GI', u'Diarr\xe9  Kr\xe4kningar'],
             ['Hepato',
              u'F\xf6rh\xf6jt alkaliskt fosfatas,  alaninaminotransferas (ALAT) och aspartataminotransferas (ASAT)'],
             ['Hepato', u'H\xe5ravfall (alopeci)  Allergiska reaktioner'],
             ['Hepato', u'Sm\xe4rta i skelettbenen'],
             ['Reproductive system', u'Vaginal torrhet']]],
           ['Uncommon',
            [['Hepato', u'F\xf6rh\xf6jning av gamma-GT och bilirubin  Hepatit'],
             ['Hepato', u'Urtikaria'],
             ['Hepato', u'Triggerfinger']]],
           ['Rare',
            [['Hepato',
              u'Erythema multiforme  Anafylaktisk reaktion Kutan vaskulit (inklusive vissa rapporter om Henoch-Sch\xf6nleins purpura)**']]],
           ['Very rare', [['Hepato', u'Stevens-Johnsons syndrom  Angio\xf6dem Osteoporos']]]],
 '_pages': [3, 5],
 u'_rank': 15,
 u'_type': u'TSFU'}