{'_data': [['Very common',
            [['Vascular',
              u'  \u2022Blodvallningar, oftast lindriga till m\xe5ttliga till  ---']]],
           ['Common',
            [['General',
              u'och  \u2022Asteni, oftast lindrig till m\xe5ttlig till sin natur  symtom vid --']]],
           ['Uncommon',
            [['Hepato',
              u' ---\u2022F\xf6rh\xf6jt alkalinfosfatas, ALAT   --(Alaninaminotransferas) och ASAT --(Aspartataminotransferas) -'],
             ['Reproductive system',
              u'och  \u2022Vaginal bl\xf6dning, oftast lindrig till m\xe5ttlig till sin  br\xf6st:  -natur *  ']]],
           ['Very rare',
            [['Nervous system', u'  --'],
             ['Hepato', u' ---\u2022F\xf6rh\xf6jt gamma-GT och bilirubin  -\u2022Hepatit  '],
             ['Skin', u'  \u2022Erythema multiforme  ']]]],
 '_pages': [3, 5],
 u'_rank': 7,
 u'_type': u'DFSU'}