{'_data': [['Very common',
            [['Vascular', u'Blodvallningar, huvudsakligen l\xe4tta eller m\xe5ttliga']]],
           ['Common',
            [['Nervous system',
              u'Huvudv\xe4rk, huvudsakligen l\xe4tt till m\xe5ttlig, karpaltunnelsyndrom'],
             ['GI',
              u'Illam\xe5ende, huvudsakligen l\xe4tt eller m\xe5ttlig. Diarr\xe9, huvudsakligen l\xe4tt eller m\xe5ttlig'],
             ['Skin',
              u'Glesare h\xe5rv\xe4xt, huvudsakligen l\xe4tt eller m\xe5ttlig Utslag, huvudsakligen l\xe4tta eller m\xe5ttliga'],
             ['Musculoskeletal', u'Ledv\xe4rk/stelhet huvudsakligen l\xe4tt eller m\xe5ttlig'],
             ['General', u'Kraftl\xf6shet, huvudsakligen l\xe4tt eller m\xe5ttlig'],
             ['Hepato',
              u'F\xf6rh\xf6jt alkaliskt fosfatas, alanin-och aspartataminotransfera s'],
             ['Reproductive system',
              u'Vaginal torrhet, huvudsakligen l\xe4tt eller m\xe5ttlig']]],
           ['Uncommon',
            [['Nervous system', u'S\xf6mnighet, huvudsakligen l\xe4tt eller m\xe5ttlig'],
             ['GI', u'Kr\xe4kningar, huvudsakligen l\xe4tta eller m\xe5ttliga'],
             ['Metabolism',
              u'Anorexi, huvudsakligen l\xe4tt eller m\xe5ttlig Hyperkolesterolemi, huvudsakligen l\xe4tt eller m\xe5ttlig'],
             ['Hepato', u'F\xf6rh\xf6jt gamma-GT och bilirubin. Hepatit'],
             ['Reproductive system',
              u'Vaginalbl\xf6dning*, huvudsakligen l\xe4tt eller m\xe5ttlig']]],
           ['Very rare',
            [['Skin',
              u'Erythema multiforme Stevens-Johnson syndrom Allergiska reaktioner inklusive angio\xf6dem, urtikaria och anafylaxi']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 14,
 u'_type': u'MSFU'}