{'_data': [['Very common',
            [['Psychiatric', u'Minskad libido Erektil dysfunktion'],
<<<<<<< HEAD
             ['Reproductive system', u'Reversibel h\xe4mning av spermato-ge nesen']]],
           ['Common',
            [['Metabolism', u'Vikt\xf6kning, viktminsk-n ing'],
             ['Psychiatric', u'Depressiv f\xf6rst\xe4mning Rastl\xf6shet (tillf\xe4llig)'],
             ['Respiratory', u'Andf\xe5dd-he t*'],
             ['Hepato', u'Lever-toxici tet, inkl. gulsot, hepatit, leversvikt*'],
             ['Reproductive system', u'Gyneko-ma sti'],
             ['General', u'Tr\xf6tthet Blod-vallni ngar Svettningar']]],
           ['Uncommon', [['Skin', u'Utslag']]],
           ['Rare', [['Immune system', u'\xd6ver-k\xe4nslig hets-reaktion er']]],
           ['Very rare', [['Neoplasms', u'Benigna och maligna lever-tu m\xf6rer*']]],
           ['Unknown',
            [['Neoplasms', u'Meningeom'],
             ['Blood', u'Anemi*'],
             ['Vascular', u'Trombo-em boliska h\xe4ndelser* * *'],
             ['GI', u'Intra-abdom inell bl\xf6dning*'],
             ['Musculoskeletal', u'Osteoporos'],
             ['Neoplasms', u'Benigna och maligna lever-tum\xf6rer* Meningeom'],
             ['Immune system', u'\xd6ver-k\xe4nslighe ts-reaktion'],
             ['Metabolism', u'Vikt\xf6kning Viktminskning'],
             ['Psychiatric',
              u'Nedst\xe4mdhet Tillf\xe4llig rastl\xf6shet \xd6kad libido S\xe4nkt libido'],
             ['Vascular', u'Trombo-embol iska'],
             ['Respiratory', u'Andf\xe5ddhet*'],
             ['GI', u'Intra-abdomine ll bl\xf6dning*'],
             ['Hepato', u'Levertoxicitet, inkl. gulsot, hepatit, lever-svikt*'],
             ['Skin', u'Utslag'],
             ['Reproductive system',
              u'Utebliven \xe4gglossning \xd6mmande br\xf6st St\xe4nk-bl\xf6dning *'],
=======
             ['Reproductive system', u'Reversibel h\xe4mning av spermato-genesen']]],
           ['Common',
            [['Metabolism', u'Vikt\xf6kning, viktminsk-ning'],
             ['Psychiatric', u'Depressiv f\xf6rst\xe4mning Rastl\xf6shet (tillf\xe4llig)'],
             ['Respiratory', u'Andf\xe5dd-het*'],
             ['Hepato', u'Lever-toxicitet, inkl. gulsot, hepatit, leversvikt*'],
             ['Reproductive system', u'Gyneko-masti'],
             ['General', u'Tr\xf6tthet Blod-vallningar Svettningar']]],
           ['Uncommon', [['Skin', u'Utslag']]],
           ['Rare', [['Immune system', u'\xd6ver-k\xe4nslighets-reaktioner']]],
           ['Very rare', [['Neoplasms', u'Benigna och maligna lever-tum\xf6rer*']]],
           ['Unknown',
            [['Neoplasms', u'Meningeom'],
             ['Blood', u'Anemi*'],
             ['Vascular', u'Trombo-emboliska h\xe4ndelser* * *'],
             ['GI', u'Intra-abdominell bl\xf6dning*'],
             ['Musculoskeletal', u'Osteoporos'],
             ['Neoplasms', u'Benigna och maligna lever-tum\xf6rer* Meningeom'],
             ['Immune system', u'\xd6ver-k\xe4nslighets-reaktion'],
             ['Metabolism', u'Vikt\xf6kning Viktminskning'],
             ['Psychiatric',
              u'Nedst\xe4mdhet Tillf\xe4llig rastl\xf6shet \xd6kad libido S\xe4nkt libido'],
             ['Vascular', u'Trombo-emboliska'],
             ['Respiratory', u'Andf\xe5ddhet*'],
             ['GI', u'Intra-abdominell bl\xf6dning*'],
             ['Hepato', u'Levertoxicitet, inkl. gulsot, hepatit, lever-svikt*'],
             ['Skin', u'Utslag'],
             ['Reproductive system',
              u'Utebliven \xe4gglossning \xd6mmande br\xf6st St\xe4nk-bl\xf6dning*'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Tr\xf6tthet']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 9],
 u'_rank': 27,
 u'_type': u'MSFU'}