{'_data': [['Very common', [['Vascular', u'Mindre bl\xf6dning oavsett st\xe4lle']]],
           ['Common',
            [['Blood', u'Minskad niv\xe5 av hemoglobin'],
             ['General',
              u'Bl\xf6dning vid insticksst\xe4llet Hematom vid k\xe4rlpunktionsst \xe4llet som \xe4r > 5 cm Hematom vid k\xe4rlpunktionsst \xe4llet som \xe4r < 5 cm'],
             ['Skin', u'Ekkymos'],
             ['Vascular',
              u'St\xf6rre bl\xf6dning oavsett st\xe4lle inklusive rapporter om d\xf6dlig utg\xe5ng']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni Anemi'],
             ['GI',
              u'Gastrointestinal bl\xf6dning (inklusive hematemes, melena, esofageal bl\xf6dning och anal bl\xf6dning) Retroperitoneal bl\xf6dning Gingival bl\xf6dning Illam\xe5ende'],
             ['Immune system',
              u'\xd6verk\xe4nslighet inklusive anafylaktisk reaktion och chock, d\xe4ribland rapporter om d\xf6dlig utg\xe5ng'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Renal', u'Hematuri'],
             ['Respiratory', u'Epistaxis Hemoptys Faryngeal bl\xf6dning'],
             ['Vascular', u'Hematom Hypotoni']]],
           ['Rare',
            [['Blood', u'F\xf6rh\xf6jd INR'],
             ['Cardiac',
              u'Myokardinfarkt Hj\xe4rttamponad Perikardiell bl\xf6dning Trombos i kransart\xe4r Angina pectoris Bradykardi Kammartakykard i Br\xf6stsm\xe4rta'],
             ['Ear', u'\xd6ronbl\xf6dning'],
             ['Eye', u'Intraokul\xe4r bl\xf6dning'],
             ['GI', u'Peritoneal bl\xf6dning Retroperitonealt hematom Kr\xe4kning'],
             ['General',
              u'Reaktioner vid injektionsst\xe4llet (obehag och sm\xe4rta vid injektionsst\xe4llet, reaktion vid punktionsst\xe4llet)'],
             ['Injury',
              u'Reperfusionsska da (inget eller l\xe5ngsamt \xe5terfl\xf6de) Kontusion'],
             ['Musculoskeletal', u'Ryggsm\xe4rta Ljumsksm\xe4rta'],
             ['Nervous system', u'Intrakraniell bl\xf6dning'],
             ['Respiratory', u'Lungbl\xf6dning Dyspne'],
             ['Skin', u'Utslag Urtikaria'],
             ['Vascular',
              u'Trombos i koronarstent inklusive rapporter om d\xf6dlig utg\xe5ng Trombos inklusive rapporter om d\xf6dlig utg\xe5ng Arterioven\xf6s fistel Katetertrombos Vaskul\xe4rt pseudoaneurysm']]],
           ['Very rare', [['Vascular', u'Kompartment syndrom']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 10],
 u'_rank': 25,
 u'_type': u'MSFU'}