{'_data': [['Common',
            [['Psychiatric',
              u'mardr\xf6mmar, d\xe5sighet, s\xf6mnl\xf6shet, yrsel, nervositet, yrsel, nedsatt koncentrationsf\xf6rm\xe5ga, agitation, ilska, fientlighet, f\xf6rvirring, depression'],
             ['Nervous system', u'dimsyn'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'ospecifik br\xf6stsm\xe4rta'],
             ['Respiratory', u'halsont, t\xe4ppt n\xe4sa'],
             ['GI', u'illam\xe5ende, muntorrhet, gastrointestinala symtom, diarr\xe9'],
             ['General', u'huvudv\xe4rk, svaghet']]],
           ['Uncommon',
            [['Psychiatric',
              u'depersonalisation, hyperakusi, eufori, dysfori, behov av att r\xf6ra sig, \xe5ngest, f\xf6rlust av intresse, associationsst\xf6rningar, hallucinationer, sj\xe4lvmordstankar, kramper'],
             ['Nervous system',
              u'domningar, k\xe4nselrubbningar (t.ex. stickningar, stickningar), f\xf6rlust av koordination, tremor'],
             ['Nervous system', u'rodnad i \xf6gonen, kliande \xf6gon, konjunktivit'],
             ['Cardiac', u'takykardi / hj\xe4rtklappning'],
             ['Vascular', u'korta episoder av svimning, hypo-eller hypertoni'],
             ['Respiratory',
              u'\xf6kat betydligt andningsfrekvens, andf\xe5ddhet, tryck \xf6ver br\xf6stet, f\xf6r\xe4ndrad luktsinne'],
             ['GI',
              u'\xf6kad aptit, anorexi, dregling, rektal bl\xf6dning, f\xf6rstoppning, gasbildning, irritabel kolon, kr\xe4kningar'],
             ['Hepato', u'f\xf6rh\xf6jda leverenzymer'],
             ['Skin',
              u'\xf6dem, urtikaria, rodnad, tendens till bl\xe5m\xe4rken, h\xe5ravfall, torr hud, eksem, vesicula, ansikts\xf6dem'],
             ['Musculoskeletal',
              u'muskelkramper, muskelsm\xe4rta, muskelsp\xe4nningar, ledv\xe4rk'],
             ['Renal', u'nedre urinv\xe4garna symptom'],
             ['Reproductive system', u'menstruationsrubbningar, minskad eller \xf6kad libido'],
             ['General',
              u'vikt\xf6kning, feber, d\xe5n i huvudet, viktminskning, sjukdomsk\xe4nsla, tr\xf6tthet, f\xf6r\xe4ndrad smak, svettning, fuktig h\xe4nderna']]],
           ['Rare',
            [['Blood',
              u'f\xf6r\xe4ndrad blodbild (eosinofili, leukopeni, trombocytopeni) Endokrina st\xf6rningar'],
             ['Blood', u'galaktorr\xe9, gynekomasti, sk\xf6ldk\xf6rteldysfunktion'],
             ['Psychiatric',
              u'hum\xf6rsv\xe4ngningar, klaustrofobi, k\xf6ld intolerans, apati, sluddrigt tal, psykos, \xf6verg\xe5ende minnesluckor, serotonergt syndrom'],
             ['Nervous system',
              u'extrapyramidala symtom, inklusive tidiga och sena dyskinesier, dystoni och styvhet, parkinsonism, akatisi, restless legs syndrom, nedsatt reaktionsf\xf6rm\xe5ga, ofrivilliga r\xf6relser \xd6gonsjukdomar'],
             ['Nervous system',
              u'\xf6gonsm\xe4rta, fotofobi, k\xe4nsla av tryck p\xe5 \xf6gonen, tunnelseende'],
             ['Cardiac', u'hj\xe4rtsvikt, hj\xe4rtinfarkt, kardiomyopati, bradykardi'],
             ['Vascular', u'st\xf6rningar i cerebrala blodfl\xf6det'],
             ['Respiratory', u'n\xe4sblod'],
             ['Skin',
              u'allergiska reaktioner, sm\xe5 bl\xf6dningar i huden, akne, nagelf\xf6rtunning'],
             ['Musculoskeletal', u'muskelsvaghet'],
             ['Renal', u'enures, nokturi'],
             ['Reproductive system',
              u'amenorr\xe9, inflammatorisk sjukdom i b\xe4ckenben, onormal utl\xf6sning, impotens'],
             ['General',
              u'alkoholmissbruk, bl\xf6dningsrubbningar, r\xf6stf\xf6rlust, hicka, br\xe4nnande tunga']]]],
 '_pages': [6, 8],
 u'_rank': 33,
 u'_type': u'LSFU'}