{'_data': [['Very common', [['Blood', u'Leukopeni']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Immune system', u'Hudutslag'],
             ['GI', u'Illam\xe5ende, f\xf6r\xe4ndrat smaksinne'],
             ['General', u'Feber']]],
           ['Uncommon',
            [['Blood', u'Pancytopeni, trombocytopeni'],
             ['Immune system', u'Eosinofili'],
             ['GI', u'Kr\xe4kningar'],
             ['Hepato', u'Gulsot'],
             ['Skin', u'Missf\xe4rgning av huden'],
             ['Skin', u'Artralgi']]],
           ['Unknown',
            [['Blood', u'Agranulocytos, lymfopeni,'],
             ['Immune system', u'\xd6verk\xe4nslighet, bronkialspasm'],
             ['Eye', u'Uveiter, hornhinneprecipitat'],
             ['Hepato', u'Transaminasstegring']]]],
 '_pages': [4, 5],
 u'_rank': 15,
 u'_type': u'TSFU'}