{'_data': [['Common', [['General', u' D\xe5sighet.  ']]],
           ['Uncommon',
            [['General', u' Huvudv\xe4rk Yrsel.  '],
             ['Nervous system', u' Ataxi, koncentrationssv\xe5righeter.  '],
             ['Nervous system', u' Muskelsvaghet. '],
             ['Psychiatric', u' Minnesluckor. ']]],
           ['Rare',
            [['Nervous system', u' Respiratorisk depression.  '],
             ['Skin', u' Allergiska hudreaktioner. '],
             ['Psychiatric',
              u' Paradoxala reaktioner s\xe5som exitationstillst\xe5nd, aggressivitet, hallucinationer. '],
             ['Other', u' Hypersalivation, bronkial hypersekretion. ']]]],
 '_pages': [2, 3],
 u'_rank': 9,
 u'_type': u'DFSU'}