{'_data': [['Very common',
            [['General',
              u'De flesta patienter utvecklar reaktioner vid injektionsst\xe4llet, s\xe4rskilt vid kontinuerlig anv\xe4ndning. Dessa kan innefatta subkutana knutor, f\xf6rh\xe5rdnader, erytem, \xf6mhet och pannikulit. Ett flertal andra lokala reaktioner (s\xe5som irritation, kl\xe5da, bl\xe5m\xe4rken och sm\xe4rta) kan ocks\xe5 f\xf6rekomma.']]],
           ['Common',
            [['Psychiatric',
              u'Neuropsykiatriska symtom \xe4r vanliga hos patienter med Parkinsons sjukdom. Apomorfin PharmSwed b\xf6r anv\xe4ndas med s\xe4rskild f\xf6rsiktighet till dessa patienter. Neuropsykiatriska st\xf6rningar (inkluderande \xf6verg\xe5ende, lindrig konfusion och synhallucinationer) har f\xf6rekommit under behandling med apomorfinhydroklorid.'],
             ['Nervous system',
              u'I b\xf6rjan av behandlingen kan \xf6verg\xe5ende sedation f\xf6rekomma i anslutning till varje dos apomorfinhydroklorid. Denna f\xf6rsvinner dock vanligen under de f\xf6rsta behandlingsveckorna. Apomorfin associeras med somnolens. Yrsel/omt\xf6ckning har ocks\xe5 rapporterats.'],
             ['Respiratory', u'G\xe4spningar har rapporterats under apomorfinbehandling.'],
             ['GI',
              u'Illam\xe5ende och kr\xe4kningar, s\xe4rskilt i b\xf6rjan av behandlingen, vanligen p\xe5 grund av att domperidon inte anv\xe4nts (se avsnitt 4.2).']]],
           ['Uncommon',
            [['Blood',
              u'Hemolytisk anemi och trombocytopeni har rapporterats f\xf6r patienter som behandlas med apomorfin.'],
             ['Nervous system',
              u'Under \u201don\u201d-perioder kan apomorfin orsaka dyskinesi som i vissa fall kan vara sv\xe5r, och kan hos ett f\xe5tal fall leda till att behandlingen m\xe5ste uts\xe4ttas.'],
             ['Vascular',
              u'Postural hypotension kan f\xf6rekomma och \xe4r vanligen \xf6verg\xe5ende (se avsnitt 4.4).'],
             ['Respiratory', u'Andningssv\xe5righeter har rapporterats.'],
             ['Skin', u'Lokala eller allm\xe4nna hudutslag har rapporterats.'],
             ['General', u'Nekros och ulceration p\xe5 injektionsst\xe4llet har rapporterats.'],
             ['Investigations',
              u'Positivt Coombs test har rapporterats f\xf6r patienter som har behandlats med levodopa och apomorfin.']]],
           ['Rare',
            [['Blood',
              u'Eosinofili har i s\xe4llsynta fall upptr\xe4tt under behandling med apomorfinhydroklorid.'],
             ['Immune system',
              u'P\xe5 grund av inneh\xe5llet av natriummetabisulfit kan allergiska reaktioner (inklusive anafylaxi och bronkospasm) f\xf6rekomma.']]],
           ['Unknown',
            [['Psychiatric',
              u'St\xf6rd impulskontroll Patologiskt spelberoende, \xf6kad libido, hypersexualitet, tv\xe5ngsm\xe4ssigt spenderande av pengar och tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hets\xe4tning och tv\xe5ngsm\xe4ssigt \xe4tande kan f\xf6rekomma hos patienter som behandlas med dopaminagonister s\xe5som Apomorfin PharmSwed (Se avsnitt 4.4 \u201dvarningar och f\xf6rsiktighet\u201d).'],
             ['General', u'Perifera \xf6dem har rapporterats.']]]],
 '_pages': [4, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}