{'_data': [['Very common', [['GI', u'diarr\xe9, illam\xe5ende']]],
           ['Common',
            [['Metabolism', u'hyperlipidemi'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI',
              u'v\xe4dersp\xe4nningar, buksm\xe4rtor, utsp\xe4nd buk, l\xf6s avf\xf6ring, dyspepsi'],
             ['Skin', u'hudutslag'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Blood', u'neutropeni, anemi, trombocytopeni'],
             ['Immune system', u'\xf6verk\xe4nslighetsreaktioner'],
             ['Metabolism',
              u'anorexi, minskad aptit, minska vikt, hyperamylasemi, hyperkolesterolemi, diabetes mellitus, hyperglykemi'],
             ['Psychiatric', u'insomnia, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'yrsel, perifer neuropati, somnolens'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'gastroesofageal reflux sjukdom, pankreatit'],
             ['Hepato',
              u'\xf6kade leverenzymer (ALAT, ASAT), cytolytisk hepatit, avvikande leverfunktionsprover (ALAT, ASAT), toxisk hepatit'],
             ['Skin',
              u'kl\xe5da, lipohypertrofi, exantem, lipoatrofi, f\xf6rv\xe4rvad lipodystrofi'],
             ['Musculoskeletal', u'myalgi, muskelkramp'],
             ['Renal', u'njurinsufficiens'],
             ['General', u'pyrexi, influensaliknande sjukdom, sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Metabolism', u'ansiktslipoatrofi'],
             ['Nervous system', u'bl\xf6dning*'],
             ['GI', u'lipas'],
             ['Hepato',
              u'(inkluderande fatala fall), hepatit, leversteatos, hyperbilirubinemi']]]],
 '_pages': [24, 27],
 u'_rank': 22,
 u'_type': u'LSFU'}