{'_data': [['Common',
            [['Blood',
              u'(\uf0b3 1/100, <1/10) Anemi, megaloblastos, leukopeni, trombocytopeni.'],
             ['Eye',
              u'Reversibel hemorragisk konjunktivit. And ningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Eye',
              u'Anorexi, illam\xe5ende, kr\xe4kningar, diarr\xe9, anal inflammation och ulceration.'],
             ['Renal',
              u'Reversibla hudbiverkningar som erytem, utslag, pruritus, urtikaria, vaskulit, alopeci.'],
             ['General', u'Feber.'],
             ['General', u'Reversibel leverp\xe5verkan med enzymstegring.']]],
           ['Uncommon',
            [['Nervous system',
              u'Mindre v anliga (\uf0b3 1/1000, <1/100) Yrsel, neurit eller neural toxicitet och sm\xe4rta. Vid h\xf6gdos ses dosrelaterad ataxi, dysartri, dysdiadokokinesi, personlighetsf\xf6r\xe4ndringar, somnolens, koma.'],
             ['Eye',
              u'(\uf0b3 1/1000, <1/100) Buksm\xe4rta, halsont, esofagit, s\xe5rbildning i matstrupe och gastrointestinal bl\xf6dning .'],
             ['Renal', u'S\xe5rbildning.'],
             ['Renal', u'Mindre v anliga (\uf0b3 1/1000, <1/100) Myalgi.'],
             ['General', u'Tromboflebit, cellulit vid injektionsst\xe4llet.']]],
           ['Rare',
            [['Blood', u'(\uf0b31/10 000, <1/1 000) Minskat antal reticulocyter.'],
             ['Nervous system',
              u'S\xe4llsynta (\uf0b31/10 000, <1/1 000) Quadriplegi och paralysis, framf\xf6r allt i samband med intratekal administrering.'],
             ['Eye', u'Br\xf6stsm\xe4rta. Magtarmkanalen'],
             ['Renal', u'Njurfunktionsneds\xe4ttning. Hud och subkutan v\xe4vnad'],
             ['Renal',
              u'Utslag beroende p\xe5 neurit eller neural toxicitet, fr\xe4knar, bl\xf6dning fr\xe5n hudslemhinnor Muskuloskel etala systemet och bindv\xe4v'],
             ['Renal', u'Ledsm\xe4rta.'],
             ['Infections', u'S\xe4llsynta (\uf0b31/10 000, <1/1 000) Sepsis.'],
             ['General',
              u'S\xe4llsynta (\uf0b31/10 000, <1/1 000) Irritation vid injektionsst\xe4llet. Lever och gallv\xe4gar'],
             ['General',
              u'S\xe4llsynta (\uf0b31/10 000, <1/1 000) Ikterus. En cytarabinreaktion karakt\xe4riseras av feber, myalgi, bensm\xe4rta, ibland br\xf6stsm\xe4rta, makulopalul\xf6st utslag, konjunktivit och sjukdomsk\xe4nsla. Den uppkommer vanligtvis 6-12 timmar efter administrering. Kortikosteroider kan ges f\xf6r att behandla eller f\xf6rebygga detta syndrom. Om symtomen \xe4r kraftiga b\xf6r kortikosteroid ges i samband med fortsatt cytarabinbehandling. De gastrointestinala biverkningarna minskar om cytarabin ges som infusion. Lokala glukokortikoider rekommenderas som profylax f\xf6r hemorragisk konjunktivit. Hyperuremi kan f\xf6rekomma sekund\xe4rt till lys av neoplastiska celler. Serumniv\xe5er av urinsyra b\xf6r monitoreras. Anafylaxi har rapporterats.']]]],
 '_pages': [2, 4],
 u'_rank': 20,
 u'_type': u'LSFU'}