{'_data': [['Common',
            [['Blood', u'leukopeni (leukocyter >2 x 10 /l)'],
             ['Immune system', u'milda allergiska reaktioner'],
             ['Metabolism', u'f\xf6rh\xf6jt CK'],
             ['Nervous system', u'parestesi, huvudv\xe4rk, yrsel, perifer neuropati'],
             ['Cardiac', u'l\xe4tt f\xf6rh\xf6jt blodtryck'],
             ['GI',
              u'diarr\xe9, illam\xe5ende, kr\xe4kning, p\xe5verkad munslemhinna (t.ex. aft\xf6s stomatit, muns\xe5r), buksm\xe4rta'],
             ['Hepato',
              u'f\xf6rh\xf6jda leverv\xe4rden (transaminaser [speciellt ALAT], mindre ofta gamma-GT, alkaliska fosfataser, bilirubin)'],
             ['Skin',
              u'\xf6kat h\xe5ravfall, eksem, utslag (inklusive makulopapul\xf6sa), kl\xe5da, torr hud'],
             ['Musculoskeletal', u'tenosynovit'],
             ['General', u'anorexi, viktminskning (vanligen utan betydelse), asteni']]],
           ['Uncommon',
            [['Blood', u'anemi, l\xe4tt trombocytopeni (trombocyter <100 x 10 /l)'],
             ['Metabolism', u'hypokalemi, hyperlipidemi, hypofosfatemi'],
             ['Psychiatric', u'\xe5ngest'],
             ['GI', u'smakrubbningar'],
             ['Skin', u'urtikaria'],
             ['Musculoskeletal', u'senruptur']]],
           ['Rare',
            [['Infections',
              u'allvarliga infektioner inklusive sepsis som kan f\xe5 d\xf6dlig utg\xe5ng'],
             ['Blood',
              u'pancytopeni (troligen genom antiproliferationsmekanism), leukopeni (leukocyter <2 x 10 /l), eosinofili'],
             ['Metabolism', u'f\xf6rh\xf6jt LD'],
             ['Respiratory',
              u'interstitiell lungsjukdom (inkluderande interstitiell pneumoni), vilken kan vara fatal.'],
             ['Hepato', u'hepatit, gulsot/kolestas']]],
           ['Very rare',
            [['Blood',
              u'agranulocytos Nyligen genomg\xe5ngen, samtidig eller efterf\xf6ljande anv\xe4ndning av potentiellt myelotoxiska medel kan sammankopplas med en \xf6kad risk f\xf6r hematologiska effekter.'],
             ['Immune system',
              u'allvarliga anafylaktiska/anafylaktoida reaktioner, vaskulit, inklusive kutan nekrotiserande vaskulit'],
             ['GI', u'pankreatit'],
             ['Hepato',
              u'allvarlig leverskada s\xe5som leversvikt och akut levernekros vilka kan f\xe5 d\xf6dlig utg\xe5ng'],
             ['Skin',
              u'toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erytema multiforme']]],
           ['Unknown',
            [['Neoplasms',
              u'Risken f\xf6r malignitet, s\xe4rskilt lymfoproliferativa sjukdomar, \xf6kar vid anv\xe4ndning av vissa immunosuppressiva medel.'],
             ['Metabolism', u'hypouricemi'],
             ['Skin',
              u'kutan lupus erythematosus, pustul\xf6s psoriasis eller f\xf6rv\xe4rrad psoriasis'],
             ['Renal', u'njursvikt'],
             ['Reproductive system',
              u'Marginell (reversibel) minskning av spermiekoncentration, totalt spermieantal och snabb progressiv motilitet']]]],
 '_pages': [7, 9],
 u'_rank': 31,
 u'_type': u'LSFU'}