{'_data': [['Common',
            [['Blood',
              u' bl\xf6dning (gastrointestinal, hematuri, hematom, epistaxis, hemoptys, uterovaginal bl\xf6dning, hemartros, okul\xe4r, purpura, bl\xe5m\xe4rke)']]],
           ['Uncommon',
            [['Blood', u' anemi, trombocytopeni'],
             ['Nervous system', u' huvudv\xe4rk'],
             ['GI', u' illam\xe5ende, kr\xe4kning'],
             ['Hepato', u' onormal leverfunktion, f\xf6rh\xf6jda leverenzymer'],
             ['General', u' sm\xe4rta, \xf6dem ']]],
           ['Rare',
            [['Blood',
              u'annan bl\xf6dning (hepatisk, retroperitoneal, intrakranial/intracerebral), trombocytemi'],
             ['Immune system',
              u'allergisk reaktion (inklusive mycket s\xe4llsynta rapporter om angio\xf6dem, anafylaktoida/anafylaktiska reaktioner)'],
             ['Metabolism', u' \xf6kning av icke proteinbundet kv\xe4ve (Npn)'],
             ['Nervous system', u'yrsel'],
             ['GI', u'buksm\xe4rta'],
             ['Skin', u' erytemat\xf6st utslag, kl\xe5da'],
             ['General', u'reaktioner vid injektionsst\xe4llet']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'LSFU2'}