{'_data': [[u'Unknown',
            [['Blood', u'Leukopeni   Trombopeni'],
             ['Immune system', u'\xd6verk\xe4nslighets-'],
             ['Nervous system', u'Somnolens   Parestesi   Huvudv\xe4rk   Amnesi   Tinnitus'],
             ['Eye', u'Synst\xf6rningar'],
             ['Skin', u'Svettning   Ljusk\xe4nslighet   Utslag'],
             ['Renal', u'Startsv\xe5righeter   vid urinering']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'LFSU'}