{'_data': [['Common',
            [['Endocrine',
              u'menstruations-st\xf6rningar intermenstruella bl\xf6dningar br\xf6stsm\xe4rta'],
             ['Nervous system', u'huvudv\xe4rk deprimerat tillst\xe5nd'],
             ['Vascular', u'migr\xe4n'],
             ['GI', u'illam\xe5ende'],
             ['Reproductive system', u'leukorr\xe9 vaginal candida']]],
           ['Uncommon',
            [['Nervous system', u'f\xf6r\xe4ndrad sexuallust'],
             ['Vascular', u'hypertension hypotension'],
             ['GI', u'kr\xe4kningar'],
             ['Skin', u'acne eksem kl\xe5da'],
             ['Reproductive system', u'vaginit'],
             ['General', u'v\xe4tskeretention f\xf6r\xe4ndringar av kroppsvikten']]],
           ['Rare',
            [['Immune system', u'\xf6verk\xe4nslighet astma'],
             ['Endocrine', u'uts\xf6ndring fr\xe5n br\xf6sten'],
             ['Ear', u'hypakusi'],
             ['Vascular', u'tromboembolism'],
             ['Skin', u'erythema nodosum erythema multiforme']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 10],
 u'_rank': 16,
 u'_type': u'MSFU'}