{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['GI', u'Illam\xe5ende, diarr\xe9, dyspepsi, buksm\xe4rtor']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner som hudutslag, urtikaria, bronkospasm och angio\xf6dem'],
             ['Nervous system', u'Intrakraniell bl\xf6dning, migr\xe4nliknande huvudv\xe4rk'],
             ['Cardiac', u'F\xf6rv\xe4rrad koronarsjukdom, synkop\xe9'],
             ['Respiratory', u'Epistaxis'],
             ['GI', u'Kr\xe4kningar, gastrointestinal bl\xf6dning'],
             ['Musculoskeletal', u'Myalgi']]],
           ['Uncommon',
            [['Eye', u'Intraokul\xe4r bl\xf6dning'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotension, v\xe4rmevallningar'],
             ['GI', u'Ventrikels\xe5r, duodenals\xe5r']]],
           ['Rare', [['Blood', u'Trombocytopeni, j\xe4rnbrist'], ['GI', u'Erosiv gastrit']]],
           ['Unknown',
            [['Skin', u'Hudbl\xf6dningar inklusive kontusioner, ekkymos och hematom'],
             ['Investigations', u'F\xf6rl\xe4ngd bl\xf6dningstid'],
             ['Injury',
<<<<<<< HEAD
              u'Bl\xf6dningar efter behandlingar, bl\xf6dningar i samband med operation P\xe5 grund av klassificeringen av kodsystem, har bl\xf6dningar blivit f\xf6rdelade \xf6ver flera organsystemklasser, varf\xf6r en sammanfattande beskrivning av bl\xf6dningar finns i tabell 1 nedan.'],
             ['GI', u'bl\xf6dning (%)'],
             ['Blood',
              u"koagulopati Immunsystemet Anafylaktiska reaktioner (s\xe4rskilt hos patienter med astma) Metabolism och nutrition Hypoglykemi (barn), hyperglykemi, t\xf6rst, dehydrering, hyperkalemi, metabolisk acidos, respiratorisk alkalos Psykiska st\xf6rningar F\xf6rvirringstillst\xe5nd Organsystem Biverkning Centrala och perifera nervsystemet Agitation, hj\xe4rn\xf6dem, letargi, konvulsioner \xd6ron och balansorgan Tinnitus, d\xf6vhet Hj\xe4rtat Arytmi Andningsv\xe4gar, br\xf6stkorg och Dyspn\xe9, larynx\xf6dem, hyperventilation, mediastinum lung\xf6dem, takypn\xe9 Magtarmkanalen Pankreatit Lever och gallv\xe4gar Hepatit, Reye's syndrom Hud och subkutan v\xe4vnad Erythema exsudativum multiforme Muskuloskeletala systemet och bindv\xe4v Rabdomyolys Njurar och urinv\xe4gar Njurfunktionsst\xf6rningar Graviditet, puerperium och F\xf6rl\xe4ngd graviditet, f\xf6rl\xe4ngd f\xf6rlossning, perinatalperiod \u201dsmall for dates baby\u201d, d\xf6df\xf6dsel Allm\xe4nna symtom Feber, hypotermi Unders\xf6kningar Onormala leverv\xe4rden, f\xf6rh\xf6jd urinsyra i"]]]],
 '_pages': [4, 6],
 u'_rank': 20,
=======
              u"Bl\xf6dningar efter behandlingar, bl\xf6dningar i samband med operation P\xe5 grund av klassificeringen av kodsystem, har bl\xf6dningar blivit f\xf6rdelade \xf6ver flera organsystemklasser, varf\xf6r en sammanfattande beskrivning av bl\xf6dningar finns i tabell 1 nedan. Tabell 1. Bl\xf6dningsh\xe4ndelser f\xf6rdelade p\xe5 bl\xf6dning, st\xf6rre bl\xf6dning, intrakraniell bl\xf6dning och gastrointestinal bl\xf6dning ESPS-2 PRoFESS Asasantin Retard Placebo Asasantin Retard Behandlade patienter N 1650 (100) 1649 (100) 10055 (100) (%) Exponering, medel (\xe5r) 1,4 1,9 Bl\xf6dning (%) 8,7 4,5 5,3 St\xf6rre bl\xf6dning (%) 1,6 0,4 3,3 Intrakraniell bl\xf6dning 0,6 0,4 1,2* (%) Gastrointestinal 4,3 2,6 1,9 bl\xf6dning (%) * PRoFESS: intrakraniell bl\xf6dning (1,0%) och intraokul\xe4r bl\xf6dning (0,2%) F\xf6rutom de biverkningar som anges f\xf6r Asasantin Retard, har \xe4ven biverkningar listade nedan f\xf6r de enskilda verksamma \xe4mnena rapporterats. Dessa har dock \xe4nnu inte rapporterats f\xf6r Asasantin Retard. Dipyridamol: Ytterligare biverkningar som rapporterats med dipyridamol i monoterapi var f\xf6ljande: Dipyridamol har visat sig kunna inlagras i gallsten. Acetylsalicylsyra: Ytterligare biverkningar har rapporterats med acetylsalicylsyra i monoterapi. Dessa biverkningar har vanligen rapporterats vid behandling med h\xf6ga doser eller i samband med intoxikationer: Organsystem Biverkning Blodet och lymfsystemet Disseminerad intravaskul\xe4r koagulation, koagulopati Immunsystemet Anafylaktiska reaktioner (s\xe4rskilt hos patienter med astma) Metabolism och nutrition Hypoglykemi (barn), hyperglykemi, t\xf6rst, dehydrering, hyperkalemi, metabolisk acidos, respiratorisk alkalos Psykiska st\xf6rningar F\xf6rvirringstillst\xe5nd Organsystem Biverkning Centrala och perifera nervsystemet Agitation, hj\xe4rn\xf6dem, letargi, konvulsioner \xd6ron och balansorgan Tinnitus, d\xf6vhet Hj\xe4rtat Arytmi Andningsv\xe4gar, br\xf6stkorg och Dyspn\xe9, larynx\xf6dem, hyperventilation, mediastinum lung\xf6dem, takypn\xe9 Magtarmkanalen Pankreatit Lever och gallv\xe4gar Hepatit, Reye's syndrom Hud och subkutan v\xe4vnad Erythema exsudativum multiforme Muskuloskeletala systemet och bindv\xe4v Rabdomyolys Njurar och urinv\xe4gar Njurfunktionsst\xf6rningar Graviditet, puerperium och F\xf6rl\xe4ngd graviditet, f\xf6rl\xe4ngd f\xf6rlossning, perinatalperiod \u201dsmall for dates baby\u201d, d\xf6df\xf6dsel Allm\xe4nna symtom Feber, hypotermi Unders\xf6kningar Onormala leverv\xe4rden, f\xf6rh\xf6jd urinsyra i"]]]],
 '_pages': [4, 6],
 u'_rank': 18,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}