{'_data': [['Common',
            [['Cardiac', u'Bradykardi'],
             ['Vascular', u'Kalla och cyanotiska extremiteter'],
             ['GI',
              u'Gastrointestinala problem, illam\xe5ende, kr\xe4kningar, diarr\xe9 och f\xf6rstoppning']]],
           ['Uncommon',
            [['Psychiatric', u'S\xf6mnst\xf6rningar'],
             ['Hepato', u'F\xf6rh\xf6jda transaminaser']]],
           ['Rare',
            [['Blood', u'Trombocytopeni, leukopeni'],
             ['Psychiatric',
              u'Hallucinationer, psykoser, f\xf6rvirring, depression, mardr\xf6mmar, \xe5ngest'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, parestesi i extremiteter'],
             ['Eye', u'Synf\xf6rs\xe4mring, synf\xf6r\xe4ndring, torra \xf6gon'],
             ['Cardiac',
              u'L\xe5ngsam AV-\xf6verledning eller f\xf6rs\xe4mring av existerande AV-block, f\xf6rs\xe4mring av hj\xe4rtsvikt'],
             ['Vascular',
              u'Hypotoni (ibland associerad med svimning), Raynauds fenomen, \xf6kning av existerande claudicatio intermittens Andningsv\xe4gar, br\xf6stkorg och mediastinumS\xe4llsynta: Bronkospasm hos patienter med bronkial astma eller tidigare besv\xe4r med astma'],
             ['GI', u'Muntorrhet.'],
             ['Skin',
              u'Utslag, alopeci, psoriasis-liknande hudreaktioner, f\xf6rs\xe4mring av psoriasis, purpura'],
             ['Hepato', u'Hepatisk toxicitet, bland annat intrahepatisk kolestas'],
             ['Reproductive system', u'Impotens']]],
           ['Very rare',
            [['Investigations',
              u'En \xf6kning av antinukle\xe4ra antikroppar har observerats; dess kliniska relevans \xe4r oklar']]],
           ['Unknown',
            [['Endocrine',
              u'Betablockerare kan d\xf6lja symtom p\xe5 tyreotoxikos eller hypoglykemi'],
             ['Skin',
              u'Reaktioner till f\xf6ljd av \xf6verk\xe4nslighet, bland annat angio\xf6dem och urtikaria Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet Vanliga: Tr\xf6tthet, svettning']]]],
 '_pages': [7, 8],
 u'_rank': 18,
 u'_type': u'LSFU'}