{'_data': [['Very common',
            [['GI', u'Kr\xe4kning, illam\xe5ende, diarr\xe9, buksm\xe4rtor'],
             ['General', u'Feber**, frossbrytningar'],
             ['Infections', u'CMV-infektion*, urinv\xe4gsinfektion*'],
             ['Nervous system', u'Huvudv\xe4rk, tremor'],
             ['Renal', u'Dyspn\xe9'],
             ['Vascular', u'Blodvallningar']]],
           ['Common',
            [['Blood', u'Pancytopeni**, trombocytopeni, anemi, leukopeni'],
             ['Cardiac', u'Takykardi'],
             ['Eye', u'Fotofobi'],
             ['GI', u'Stomatit'],
             ['General',
              u'Asteni, br\xf6stsm\xe4rta, hypertermi, slemhinneinflammation, perifert \xf6dem'],
             ['Hepato', u'Hyperbilirubinemi'],
             ['Immune system',
              u'Anafylaktisk chock**, anafylaktisk reaktion, \xf6verk\xe4nslighet'],
             ['Infections',
              u'Bakteriell sepsis**, pneumoni**, pyelonefrit*, herpesinfektion, influensa, candidainfektion i munnen, bronkit, rinit, sinuit, nasofaryngit, hudinfektion'],
             ['Investigations',
              u'\xd6kad kreatininhalt i blodet*, positivt utslag vid cytomegalovirus antigentest, \xf6kad halt av C-reaktivt protein'],
             ['Metabolism', u'Hyperlipidemi'],
             ['Musculoskeletal', u'Myalgi, artralgi, ryggv\xe4rk, muskuloskeletal stelhet'],
             ['Neoplasms', u'Lymfoproliferativa sjukdomar*'],
             ['Nervous system', u'Parestesi'],
             ['Renal', u'Renal tubul\xe4r nekros*, hematuri'],
             ['Renal', u'Hosta, n\xe4sblod'],
             ['Skin', u'Erytem, kl\xe5da, utslag'],
             ['Vascular', u'Hypotension*, venocklusiv sjukdom, hypertension']]],
           ['Uncommon',
            [['Blood', u'Polycytemi'],
             ['GI', u'Ljumskbr\xe5ck*, refluxesofagit, dyspepsi'],
             ['General', u'\xd6dem'],
             ['Infections',
              u'Infektion i kateteromr\xe5det, Epstein-Barr-virusinfektion, gastrointestinal infektion, erysipelas, s\xe5rinfektion'],
             ['Investigations', u'F\xf6rh\xf6jda leverenzymv\xe4rden'],
             ['Metabolism', u'V\xe4tskeretention, hyperkolesterolemi'],
             ['Renal',
              u'Njursvikt**, njurnekros* Andningsv\xe4gar, br\xf6stkorg and mediastinum'],
             ['Skin', u'Hudutslag av l\xe4kemedel'],
             ['Vascular', u'Chock**, lymfocele']]]],
 '_pages': [3, 5],
 u'_rank': 32,
 u'_type': u'LSFU'}