{'_data': [['Common',
            [['Infections', u'nasofaryngit.'],
             ['Immune system', u'allergiska reaktioner.'],
             ['Metabolism', u'hyperglykemi.'],
             ['Psychiatric', u'mardr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk.'],
             ['Eye', u'dimsyn.'],
             ['Respiratory', u'faryngolaryngeal sm\xe4rta, epitaxis.'],
             ['GI', u'f\xf6rstoppning, flatulens, dyspepsi, illam\xe5ende, diarr\xe9.'],
             ['Skin', u'n\xe4sselutslag, hudutslag, kl\xe5da, alopeci.'],
             ['Musculoskeletal',
              u'myalgi, ledv\xe4rk, sm\xe4rta i armar och ben, muskelryckningar, ledsvullnad, ryggv\xe4rk.'],
             ['Investigations',
              u'Onormala leverfunktionstest, f\xf6rh\xf6jt kreatinkinas i blodet.'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Magsm\xe4rta'],
             ['Investigations',
              u'\xd6kade v\xe4rden f\xf6r alaninaminotransferas och kreatininfosfokinas i blodet. Baserat p\xe5 tillg\xe4ngliga data f\xf6rv\xe4ntas biverkningarna hos barn vara lika frekventa och av samma typ och sv\xe5righetsgrad som hos vuxna. Erfarenheten vad g\xe4ller l\xe5ngtidss\xe4kerheten hos barn \xe4r f\xf6r n\xe4rvarande begr\xe4nsad. F\xf6ljande biverkningar har rapporterats med vissa statiner: \u2022Sexuell dysfunktion. \u2022Depression.']]],
           ['Uncommon',
            [['Blood', u'trombocytopeni.'],
             ['Metabolism', u'hypoglykemi, vikt\xf6kning, anorexi.'],
             ['Nervous system', u'yrsel, parestesi, hypoestesi, smakrubbningar, amnesi.'],
             ['Ear', u'tinnitus.'],
             ['GI',
              u'kr\xe4kningar, sm\xe4rta i \xf6vre och nedre buken, rapningar, pankreatit.'],
             ['Hepato', u'hepatit.'],
             ['Musculoskeletal', u'nacksm\xe4rta, muskelsvaghet.'],
             ['General',
              u'olustk\xe4nsla, asteni, br\xf6stsm\xe4rtor, perifert \xf6dem, tr\xf6tthet, pyrexi'],
             ['Investigations',
              u'vita blodkroppar i urinen. Liksom f\xf6r andra HMG-CoA reduktash\xe4mmare har f\xf6rh\xf6jda serumtransaminasv\xe4rden rapporterats hos patienter som tagit Atorbir. Dessa f\xf6r\xe4ndringar var vanligen lindriga, \xf6verg\xe5ende och kr\xe4vde inte att behandlingen avbr\xf6ts. Kliniskt relevanta f\xf6rh\xf6jningar (>3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet) av serumtransaminaser upptr\xe4dde hos 0,8 % av de patienter som tagit Atorbir. Dessa f\xf6r\xe4ndringar var dosrelaterade och reversibla hos samtliga patienter. F\xf6rh\xf6jda serumniv\xe5er av kreatinkinas (CK), mer \xe4n 3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet, upptr\xe4dde hos 2,5 % av de patienter som behandlades med Atorbir, vilket motsvarar erfarenheten fr\xe5n kliniska pr\xf6vningar med andra HMG-CoA-reduktash\xe4mmare. Niv\xe5er \xf6ver 10 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet s\xe5gs hos 0,4 % av de patienter som behandlats med Atorbir (se avsnitt 4.4). Barn Den kliniska s\xe4kerhetsdatabasen omfattar s\xe4kerhetsdata f\xf6r 249 barnpatienter som behandlats med atorvastatin; 7 av dem var yngre \xe4n 6 \xe5r, 14 i \xe5ldrarna 6 \u22129 \xe5r och 228 i \xe5ldrarna 10 \u221217 \xe5r.']]],
           ['Rare',
            [['Eye', u'synrubbningar.'],
             ['Hepato', u'kolestas.'],
             ['Skin',
              u'angioneurotiskt \xf6dem, vesikul\xe4ra utslag inklusive erythema multiforme, Stevens-Johnsons syndrom och toxisk hudnekrolys.'],
             ['Musculoskeletal',
              u'myopati, myosit, rabdomyolys, tendonopati, ibland med ruptur som komplikation.']]],
           ['Very rare',
            [['Immune system', u'anafylaktisk reaktion.'],
             ['Nervous system', u'perifer neuropati.'],
             ['Ear', u'h\xf6rselneds\xe4ttning.'],
             ['Hepato', u'leversvikt.'],
             ['Reproductive system', u'gynekomasti.']]],
           ['Unknown',
            [['Investigations',
              u'S\xe4llsynta fall av interstitiell lungsjukdom, speciellt vid l\xe5ngtidsbehandling (se avsnitt 4.4). \u2022Diabetes Mellitus: Frekvensen \xe4r beroende av f\xf6rekomst eller avsaknad av riskfaktorer (fasteglukos > 5,6 mmol/l; BMI >30 kg/m ; f\xf6rh\xf6jda triglycerider; hypertension i anamnesen).']]]],
 '_pages': [9, 11],
 u'_rank': 33,
 u'_type': u'LSFU'}