{'_data': [['Common',
            [['Infections', u'nasofaryngit.'],
             ['Immune system', u'allergiska reaktioner.'],
             ['Metabolism', u'hyperglykemi.'],
             ['Psychiatric', u'mardr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk.'],
             ['Eye', u'dimsyn.'],
             ['Respiratory', u'faryngolaryngeal sm\xe4rta, epitaxis.'],
             ['GI', u'f\xf6rstoppning, flatulens, dyspepsi, illam\xe5ende, diarr\xe9.'],
             ['Skin', u'n\xe4sselutslag, hudutslag, kl\xe5da, alopeci.'],
             ['Musculoskeletal',
              u'myalgi, ledv\xe4rk, sm\xe4rta i armar och ben, muskelryckningar, ledsvullnad, ryggv\xe4rk.'],
             ['Investigations',
              u'Onormala leverfunktionstest, f\xf6rh\xf6jt kreatinkinas i blodet.'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Magsm\xe4rta'],
             ['Investigations',
              u'\xd6kade v\xe4rden f\xf6r alaninaminotransferas och kreatininfosfokinas i blodet. Baserat p\xe5 tillg\xe4ngliga data f\xf6rv\xe4ntas biverkningarna hos barn vara lika frekventa och av samma typ och sv\xe5righetsgrad som hos vuxna. Erfarenheten vad g\xe4ller l\xe5ngtidss\xe4kerheten hos barn \xe4r f\xf6r n\xe4rvarande begr\xe4nsad.']]],
           ['Uncommon',
            [['Blood', u'trombocytopeni.'],
             ['Metabolism', u'hypoglykemi, vikt\xf6kning, anorexi.'],
             ['Nervous system', u'yrsel, parestesi, hypoestesi, smakrubbningar, amnesi.'],
             ['Ear', u'tinnitus.'],
             ['GI',
              u'kr\xe4kningar, sm\xe4rta i \xf6vre och nedre buken, rapningar, pankreatit.'],
             ['Hepato', u'hepatit.'],
             ['Musculoskeletal', u'nacksm\xe4rta, muskelsvaghet.'],
             ['Reproductive system',
              u'olustk\xe4nsla, asteni, br\xf6stsm\xe4rtor, perifert \xf6dem, tr\xf6tthet, pyrexi'],
             ['Investigations',
              u'vita blodkroppar i urinen. Liksom f\xf6r andra HMG-CoA reduktash\xe4mmare har f\xf6rh\xf6jda serumtransaminasv\xe4rden rapporterats hos patienter som tagit Atorvastatin Actavis. Dessa f\xf6r\xe4ndringar var vanligen lindriga, \xf6verg\xe5ende och kr\xe4vde inte att behandlingen avbr\xf6ts. Kliniskt relevanta f\xf6rh\xf6jningar (>3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet) av serumtransaminaser upptr\xe4dde hos 0,8 % av de patienter som tagit Atorvastatin Actavis. Dessa f\xf6r\xe4ndringar var dosrelaterade och reversibla hos samtliga patienter. F\xf6rh\xf6jda serumniv\xe5er av kreatinkinas (CK), mer \xe4n 3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet, upptr\xe4dde hos 2,5 % av de patienter som behandlades med Atorvastatin Actavis, vilket motsvarar erfarenheten fr\xe5n kliniska pr\xf6vningar med andra HMG-CoA reduktash\xe4mmare. Niv\xe5er \xf6ver 10 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet s\xe5gs hos 0,4 % av de patienter som behandlats med Atorvastatin Actavis (se avsnitt 4.4). F\xf6ljande biverkningar har rapporterats med vissa statiner: \u2022Sexuell dysfunktion. \u2022Depression.']]],
           ['Rare',
            [['Eye', u'synrubbningar.'],
             ['Hepato', u'kolestas.'],
             ['Skin',
              u'angioneurotiskt \xf6dem, vesikul\xe4ra utslag inklusive erythema multiforme, Stevens-Johnsons syndrom och toxisk hudnekrolys.'],
             ['Musculoskeletal',
              u'myopati, myosit, rabdomyolys, tendonopati, ibland med ruptur som komplikation.']]],
           ['Very rare',
            [['Immune system', u'anafylaktisk reaktion.'],
             ['Nervous system', u'perifer neuropati.'],
             ['Ear', u'h\xf6rselneds\xe4ttning.'],
             ['Hepato', u'leversvikt.'],
             ['Reproductive system', u'gynekomasti. Allm\xe4nna  symtom']]],
           ['Unknown',
            [['Investigations',
              u'S\xe4llsynta fall av interstitiell lungsjukdom, speciellt vid l\xe5ngtidsbehandling (se avsnitt 4.4) \u2022Diabetes mellitus: Frekvensen beror p\xe5 n\xe4rvaron eller fr\xe5nvaron av riskfaktorer (fastande blodsocker > 5,6 mmol / L, BMI> 30kg/m2, upph\xf6jda triglycerider, hypertoni).']]]],
 '_pages': [10, 12],
 u'_rank': 33,
 u'_type': u'LSFU'}