{'_data': [['Common',
            [['Nervous system', u'(>1/100, <1/10) Konfusion, hallucinationer, excitation.'],
             ['Eye',
              u'(>1/100, <1/10) Sveda vid instillation, dimsyn, f\xf6rs\xe4mrat n\xe4rseende, ljusk\xe4nslighet.'],
             ['Cardiac', u'(>1/100, <1/10) Takykardi.'],
             ['GI', u'(>1/100, <1/10) Obstipation.'],
             ['General', u'(>1/100, <1/10) Ansiktsrodnad, feber.']]],
           ['Uncommon',
            [['Renal', u'(>1/1 000, <1/100) Miktionsbesv\xe4r.'],
             ['General',
              u'(>1/1 000, <1/100) Allergi vid l\xe4ngre tids anv\xe4ndning. Barn har \xf6kad risk f\xf6r systemeffekter p.g.a. \xf6verdosering.']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'LSFU'}