{'_data': [['Uncommon',
            [['Nervous system', u'-'],
             ['Respiratory',
              u'br\xf6stkorg och  n\xe4sblod, torrhet i n\xe4san.  mediastinum  halsirritation, obehag i n\xe4san  '],
             ['Immune system',
              u' anafylaktisk reaktion,  -\xf6verk\xe4nslighet  Centrala och perifera  yrsel  '],
             ['Nervous system', u'-'],
             ['Eye',
              u' ackommodationsst\xf6rning,  -mydriasis, \xf6kat intraokul\xe4rt -tryck, glaukom, \xf6gonsm\xe4rta, -dimsyn. synst\xf6rningar (halo), -konjunktival hyperemi, -korneal\xf6dem Hj\xe4rta  supraventrikul\xe4r takykardi,  -f\xf6rmaksflimmer, \xf6kad -hj\xe4rtfrekvens '],
             ['Respiratory',
              u'br\xf6stkorg och  halstorrhet, bronkospasm,  mediastinum  laryngospasm, farynx\xf6dem  '],
             ['GI', u' muntorrhet, illam\xe5ende,  '],
             ['GI', u'-motilitetsst\xf6rningar, mun\xf6dem, -stomatit '],
             ['Skin', u' hudutslag, angio\xf6dem  '],
             ['Renal', u' urinretention  ']]]],
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'DFSU'}