{'_data': [['Very common', [['Respiratory', u'*Epistaxis']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'], ['Respiratory', u'Nasal ulceration']]],
           ['Uncommon',
            [['Respiratory',
              u'Rinalgi, obehag i n\xe4san (d\xe4ribland sveda, irritation och \xf6mhet i n\xe4san), torrhet i n\xe4san. Muskuloskeletala systemet och bindv\xe4v (barn)']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner inklusive anafylaxi, angi\xf6dem, utslag och urtikaria.']]],
           ['Unknown',
            [['Eye',
              u'\xd6verg\xe5ende okul\xe4ra f\xf6r\xe4ndringar (se Klinisk erfarenhet).'],
             ['Respiratory', u'**H\xe4mmad l\xe4ngdtillv\xe4xt (se Klinisk erfarenhet).'],
             ['Systemic',
              u'under l\xe5nga perioder (se avsnitt 4.4). H\xe4mning av tillv\xe4xten har rapporterats hos barn som f\xe5tt nasala korikosteroider.']]]],
 '_pages': [4, 4],
 u'_rank': 8,
 u'_type': u'LSFU'}