{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['Vascular',
              u'mycket vanliga influensalika symtom, pyrexi , frossa , svettningar']]],
           ['Common',
            [['Investigations',
              u'minskat lymfocytantal, minskat antal vita blodkroppar, minskat neutrofilantal, minskat hematokritv\xe4rde, f\xf6rh\xf6jt kalium i blodet, f\xf6rh\xf6jt kv\xe4veurea i blodet'],
             ['Nervous system', u'muskelspasticitet, hypoestesi'],
             ['Respiratory', u'rinorr\xe9'],
             ['GI', u'kr\xe4kningar, diarr\xe9, illam\xe5ende'],
             ['Skin', u'utslag, \xf6kad svettning, kontusion'],
             ['Musculoskeletal',
              u'vanliga muskelkramp, nacksm\xe4rta, myalgi , artralgi, sm\xe4rta i extremiteter, ryggont, muskelstelhet, muskuloskeletal stelhet'],
             ['Metabolism', u'anorexi'],
             ['Vascular', u'rodnad'],
             ['Vascular',
              u'sm\xe4rta vid injektionsst\xe4llet, erytem vid injektionsst\xe4llet, bl\xe5m\xe4rke vid injektionsst\xe4llet, asteni , sm\xe4rta, tr\xf6tthet , olust, nattsvettning'],
             ['Psychiatric', u'depression, (se avsnitt 4.4), insomnia']]],
           ['Uncommon',
            [['Investigations', u'minskat antal trombocyter'],
             ['Skin', u'alopeci'],
             ['Vascular', u'sveda vid injektionsst\xe4llet'],
             ['Reproductive system', u'metrorragi, menorragi']]],
           ['Rare', [['Respiratory', u'dyspn\xe9']]],
           ['Unknown',
            [['Investigations', u'viktminskning, vikt\xf6kning, onormala leverfunktionstest'],
             ['Cardiac',
              u'kardiomyopati, kronisk hj\xe4rtinsufficiens (se avsnitt 4.4), palpitation, arytmi, takykardi'],
             ['Blood', u'pancytopeni, trombocytopeni'],
             ['Nervous system',
              u'inga k\xe4nda neurologiska symtom, synkope , hypertoni, yrsel, parestesi, kramper, migr\xe4n'],
             ['Skin',
              u'angio\xf6dem, pruritus, vesikul\xe4ra utslag, urtikaria, f\xf6rs\xe4mring av psoriasis'],
             ['Musculoskeletal', u'systemisk lupus erytematosus, muskelsvaghet, artrit'],
             ['Endocrine', u'hypotyreoidism, hypertyreoidism'],
             ['Infections', u'abcess vid injektionsst\xe4llet'],
             ['Vascular',
              u'vasodilatation Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Immune system',
              u'anafylaktisk reaktion, anafylaktisk chock, \xf6verk\xe4nslighet (angi\xf6dem, dyspn\xe9, urtikaria, utslag, kliande utslag)'],
             ['Hepato', u'leversvikt (se avsnitt 4.4), hepatit, autoimmun hepatit'],
             ['Psychiatric',
              u'sj\xe4lvmord, psykos, oro, f\xf6rvirring, emotionell labililitet']]]],
 '_pages': [4, 7],
 u'_rank': 29,
 u'_type': u'LSFU'}