{'_data': [[u'Unknown',
            [['Infections', u'Nasofaryngit, faryngit, sinuit, rinit'],
             ['Blood', u'Minskat antal r\xf6da blodkroppar, \xf6kad'],
             ['Immune system', u'Systemiska allergiska'],
             ['Metabolism', u'Hypoglykemi'],
             ['Psychiatric', u'Apati, depression, nedst\xe4mdhet,   Depression,'],
             ['Nervous system', u'Somnolens, motorisk dysfunktion,   Cerebral ischemi,'],
             ['Eye', u'Keratit, keratopati, \xf6kat cup/disc-   Tecken och symtom p\xe5'],
             ['Ear', u'Tinnitus, yrsel'],
             ['Cardiac',
              u'Hj\xe4rt-lungproblem, angina pectoris,   Bradykardi, br\xf6stsm\xe4rta,'],
             ['Vascular', u'Hypertension   Hypotension, Raynauds'],
             ['Respiratory',
              u'Dyspn\xe9, astma, bronkial   Bronkialspasm (fr\xe4mst   hyperaktivitet, epistaxi, irritation i   hos patienter med'],
             ['GI', u'Muntorrhet, esofagit, kr\xe4kning,   Illam\xe5ende, dyspepsi,'],
             ['Hepato', u'Onormala leverfunktionstest'],
             ['Skin', u'Urtikaria, makulo-papul\xe4ra utslag,   Alopeci,'],
             ['Musculoskeletal',
              u'Ryggsm\xe4rta, muskelspasmer, myalgi,   Myalgi   artralgi, extremitetssm\xe4rta'],
             ['Renal', u'Njursm\xe4rta, pollakiuri'],
             ['Reproductive system', u'Erektil dysfunktion   Sexuell dysfunktion,'],
             ['General',
              u'Sm\xe4rta, asteni, obehag i br\xf6st-   Asteni/utmattning   korgen, utmattning, onormal k\xe4nsla,'],
             ['Injury', u'K\xe4nsla av fr\xe4mmande kropp i \xf6gat']]]],
 '_pages': [5, 7],
 u'_rank': 19,
 u'_type': u'LFSU'}