{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk (14,1 % resp. 11,9 %)'],
             ['Nervous system', u'dyskinesi (10,5 % resp. 6,2 %)']]],
           ['Common',
            [['Infections', u'influensa (4,7 % resp. 0,7 %)'],
             ['Neoplasms', u'hudcarcinom (1,3 % resp. 0,7 %)'],
             ['Blood', u'leukopeni (1,3 % resp. 0 %)'],
             ['Immune system', u'allergi (1,3 % resp. 0,7 %)'],
             ['Psychiatric',
              u'depression (5,4 % resp. 2 %), hallucinationer (1,3 % resp. 0,7 %)'],
             ['Eye', u'konjunktivit (2,7 % resp. 0,7 %)'],
             ['Ear', u'yrsel (2.7 % resp. 1.3 %)'],
             ['Cardiac', u'angina pectoris (1,3 % resp. 0 %)'],
             ['Respiratory', u'rinit (3,4 % resp. 0,7 %)'],
             ['GI', u'flatulens (1,3 % resp.0 %)'],
             ['Skin', u'dermatit (2,0 % resp. 0 %)'],
             ['Musculoskeletal',
              u'muskuloskeletal sm\xe4rta (6,7 % resp. 2,6 %), nacksm\xe4rtor (2,7 % resp. 0 %), artrit (1,3 % resp. 0,7 %)'],
             ['Renal', u'urintr\xe4ngningar (1,3 % resp. 0,7 %).'],
             ['General',
              u'feber (2,7 % resp. 1,3 %), sjukdomsk\xe4nsla (2 % resp. 0 %) Till\xe4ggsbehandling Nedanst\xe5ende lista inkluderar biverkningar som rapporterades med en h\xf6gre incidens i placebokontrollerade studier hos patienter som fick rasagilin 1 mg/dag (rasagilingruppen n=380, placebogruppen n=388). Inom parentes finns incidensen av biverkningarna (% av patienterna) f\xf6r rasagilin respektive placebo. Biverkningar med \xe5tminstone 2 % skillnad mot placebo \xe4r markerade med kursivering. Biverkningarna \xe4r ordnade under frekvensrubriker som anv\xe4nder f\xf6ljande frekvenser: mycket vanliga (\u22651/10), vanliga (\u22651/100,<1/10), mindre vanliga (\u22651/1000, <1/100), s\xe4llsynta (\u22651/10 000, < 1/1000), mycket s\xe4llsynta (<1/10 000). Neoplasier; benigna, maligna och ospecificerade'],
             ['Metabolism', u'minskad aptit (2,4 % resp. 0,8 %) 5'],
             ['Psychiatric',
              u'hallucinationer (2,9 % resp. 2,1 %), onormala dr\xf6mmar (2,1 % resp. 0,8 %)'],
             ['Nervous system',
              u'dystoni (2,4 % resp. 0,8 %), karpaltunnelsyndrom (1,3 % resp. 0 %), balansst\xf6rningar (1,6 % resp. 0,3 %)'],
             ['Vascular', u'ortostatisk hypotension (3,9 % resp. 0,8 %)'],
             ['GI',
              u'buksm\xe4rtor (4,2 % resp. 1,3 %), f\xf6rstoppning (4,2 % resp. 2,1 %), illam\xe5ende och kr\xe4kningar (8,4 % resp. 6,2 %), muntorrhet (3,4 % resp. 1,8 %)'],
             ['Skin', u'utslag (1,1 % resp. 0,3 %)'],
             ['Musculoskeletal',
              u'artralgi (2,4 % resp. 2,1 %), nacksm\xe4rtor (1,3 % resp. 0,5 %)'],
             ['Investigations', u'viktminskning (4,5 % resp. 1,5 %)'],
             ['Injury',
              u'fall (4,7 % resp. 3,4 %) Parkinsons sjukdom \xe4r associerad med symtom som hallucinationer och konfusion. Fr\xe5n erfarenheter efter introduktion p\xe5 marknaden har dessa symtom ocks\xe5 observerats hos patienter med Parkinsons sjukdom som behandlats med rasagilin. Det \xe4r k\xe4nt att allvarliga biverkningar framtr\xe4der vid samtidig anv\xe4ndning av SSRI, SNRI, tricykliska och tetracykliska antidepressiva och MAO-h\xe4mmare. Efter marknadsintroduktion har fall med serotonergt syndrom associerade med agitation, konfusion, rigiditet, pyrexi och myokloni rapporterats av patienter behandlade med antidepressiva/SNRI samtidigt som rasagilin. Kliniska pr\xf6vningar med rasagilin till\xe4t inte samtidig anv\xe4ndning av fluoxetin eller fluvoxamin med rasagilin, men f\xf6ljande antidepressiva l\xe4kemedel och doser var till\xe5tna i kliniska pr\xf6vningar med rasagilin: amitriptylin \u2264 50 mg/dag, trazodon \u2264 100 mg/dag, citalopram \u2264 20 mg/dag, sertralin \u2264 100 mg/dag, och paroxetin \u2264 30 mg/dag. Det f\xf6rekom inga fall av serotonergt syndrom i det kliniska programmet f\xf6r rasagilin d\xe4r 115 patienter samtidigt exponerades f\xf6r rasagilin och tricykliska l\xe4kemedel och 141 patienter exponerades f\xf6r rasagilin och SSRI/SNRI. Efter marknadsintroduktion har fall av f\xf6rh\xf6jt blodtryck, inklusive s\xe4llsynta fall av hypertensiv kris associerad med intag av ok\xe4nd m\xe4ngd tyraminrik mat, rapporterats hos patienter som tar rasagilin. F\xf6r MAO-h\xe4mmare har rapporter om l\xe4kemedelsinteraktioner inkommit vid samtidig anv\xe4ndning av sympatomimetiska l\xe4kemedel. Efter marknadsintroduktion f\xf6rekom ett fall med f\xf6rh\xf6jt blodtryck hos en patient som anv\xe4nde den oftalmiska vasokonstriktorn tetrahydrozolinhydroklorid samtidigt med rasagilin.']]],
           ['Uncommon',
            [['Metabolism', u'minskad aptit (0,7 % resp. 0 %)'],
             ['Nervous system', u'cerebrovaskul\xe4r olycka (0,7 % resp. 0 %)'],
             ['Cardiac', u'hj\xe4rtinfarkt (0,7 % resp. 0 %)'],
             ['Skin', u'vesikul\xe4ra bull\xf6sa utslag (0,7 % resp. 0 %)'],
             ['General', u'hudmelanom (0,5 % resp. 0,3 %)'],
             ['Psychiatric', u'konfusion (0,8 % resp. 0,5 %)'],
             ['Nervous system', u'cerebrovaskul\xe4r olycka (0,5 % resp. 0,3 %)'],
             ['Cardiac', u'angina pectoris (0,5 % resp. 0 %)']]]],
 '_pages': [4, 6],
 u'_rank': 33,
 u'_type': u'LSFU'}