{'_data': [['Common',
            [['GI',
              u'Illam\xe5ende, diarr\xe9 (s\xe4llan resulterande i dehydrering), magknip/kramper, kr\xe4kningar, dyspepsi'],
             ['Hepato',
              u'F\xf6rh\xf6jda leverfunktionsv\xe4rden (ASAT, ALAT, alkaliskt fosfatas, bilirubin)'],
             ['General', u'Lokal sm\xe4rta och inflammation vid infusionsst\xe4llet']]],
           ['Uncommon',
            [['Infections', u'Moniliasis'],
             ['Nervous system', u'Huvudv\xe4rk, somnolens, smakf\xf6r\xe4ndringar'],
             ['GI', u'Flatulens'],
             ['Skin', u'Utslag, kl\xe5da, \xf6dem']]],
           ['Rare',
            [['Infections', u'Vaginit'],
             ['Blood', u'Neutropeni, trombocytopeni'],
             ['Psychiatric', u'Aggressivitet, nervositet, agitation, oro, rastl\xf6shet'],
             ['Nervous system', u'Parestesi, synkope, yrsel, kramper, hyperaktivitet'],
             ['Eye', u'Synst\xf6rningar'],
             ['Ear',
              u'H\xf6rselneds\xe4ttning inkluderande h\xf6rself\xf6rlust, d\xf6vhet, tinnitus, vertigo'],
             ['Cardiac',
              u'Arytmier inklusive ventrikul\xe4r takykardi, hj\xe4rtklappning, QT-f\xf6rl\xe4ngning, torsades de pointes*, hypotension'],
             ['GI',
              u'F\xf6rstoppning, l\xf6s avf\xf6ring, pankreatit, pseudomembran\xf6s kolit'],
             ['Hepato',
              u'Hepatit, kolestatisk ikterus, levernekros och leversvikt (s\xe4llan fatal).'],
             ['Skin',
              u'Urtikaria, allergiska reaktioner, angio\xf6dem, fotosensibilitet, allvarliga hudreaktioner inkluderande erytema multiforme, Stevens-Johnsons syndrom och toxisk epidermal nekrolys'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Interstitiell nefrit, akut njurinsuffciens'],
             ['General',
              u'Anafylaxi, inklusive anafylaktisk chock och \xf6dem, missf\xe4rgningar av tungan, tr\xf6tthet, asteni, olustk\xe4nsla, anorexi *Hj\xe4rtklappningar och arytmier inklusive ventrikul\xe4r takykardi (som setts vid behandling med andra makrolider) har rapporterats. S\xe4llsynta rapporter av QT f\xf6rl\xe4ngning och torsades de pointes har f\xf6rekommit. Ett orsakssamband mellan azitromycin och dessa effekter har inte kunnat uteslutas (se avsnitt 4.4 Varningar och f\xf6rsiktighetsm\xe5tt). H\xf6rselneds\xe4ttning inkluderande d\xf6vhet och/eller tinnitus har rapporterats vid l\xe5ngvarigt bruk med h\xf6ga doser i kliniska pr\xf6vningar. I de fall som varit m\xf6jliga att f\xf6lja upp har h\xf6rselneds\xe4ttningen i en majoritet av fallen varit reversibel.']]],
           ['Unknown', [['Nervous system', u'Hypoestesi']]]],
 '_pages': [4, 6],
 u'_rank': 21,
 u'_type': u'LSFU'}