{'_data': [['Unknown',
            [['Endocrine',
              u'Sekund\xe4r hyperparatyreoidism med potentiell st\xf6rning i benmetabolismen'],
             ['Metabolism',
              u'\xd6kade blodsockerniv\xe5er; hyperlipidemi; \xf6kad kroppsvikt p\xe5 grund av det st\xe4ndiga upptaget av glukos fr\xe5n dialysv\xe4tskan. Hj\xe4rtat och blodk\xe4rl Takykardi; hypotension; hypertension.'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Renal',
              u'Elektrolytrubbningar, t.ex. hypokalemi (mycket vanligt (>10%)); hypokalcemi,'],
             ['General',
              u'Yrsel; \xf6dem; rubbningar i v\xe4tskebalansen som visar sig som en snabb minskning (dehydrering) eller \xf6kning (\xf6verhydrering) av kroppsvikt. Sv\xe5r dehydrering kan uppkomma om man anv\xe4nder dialysv\xe4tskor med h\xf6gre glukoskoncentration. Eventuella biverkningar fr\xe5n behandlingsmetoden \xe4r'],
             ['Infections',
              u'Peritonit (mycket vanligt (>10%)); infektion vid kateterns utg\xe5ngsst\xe4lle och tunnel (mycket vanligt (>10%)); i mycket s\xe4llsynta fall, sepsis (\u2264 0.01%).'],
             ['Respiratory',
              u'Dyspn\xe9 orsakad av h\xf6jning av diafragma; sm\xe4rta i skuldrorna. Magtarmkanal Diarr\xe9; f\xf6rstoppning; hernia (mycket vanligt (>10%)); utvidgad buk och k\xe4nsla av uppk\xf6rdhet.'],
             ['General',
              u'Allm\xe4nt illam\xe5ende; rodnad, \xf6dem, exsudation, s\xe5rskorpor och sm\xe4rtor fr\xe5n kateterns utg\xe5ngsst\xe4lle Behandlingsrelaterade st\xf6rningar Grumligt utfl\xf6de; rubbningar i dialysv\xe4tskans in- och utfl\xf6de. Peritonit indikeras av grumligt utfl\xf6de. Senare kan buksm\xe4rtor, feber och allm\xe4n sjukdomsk\xe4nsla utvecklas, eller i mycket s\xe4llsynta fall, sepsis. Patienten m\xe5ste omedelbart upps\xf6ka l\xe4kare. P\xe5sen med den grumliga v\xe4tskan ska f\xf6rslutas med steril hylsa och genomg\xe5 en mikrobiologisk kontaminerings test samt vit blodkroppsr\xe4kning. Vid infektioner vid kateterns utg\xe5ngsst\xe4lle och tunnel skall behandlande l\xe4kare kontaktas snarast.']]]],
 '_pages': [5, 6],
 u'_rank': 8,
 u'_type': u'LSFU'}