{'_data': [['Uncommon',
            [['Blood',
              u'(> 1/1 000, < 1/100): makroskopisk hematuri, bl\xe5sretraktion, urinstopp, bl\xe5skontraktur Reproduktionsorgan och Mycket vanliga (> 1/10): br\xf6stk\xf6rtel asymtomatisk granulomat\xf6s prostatit'],
             ['Blood',
              u'(> 1/1 000, < 1/100): epididymit, symtomatisk granulomat\xf6s prostatit']]],
           ['Very rare',
            [['Blood',
              u'00): \xf6verk\xe4nslighetsreaktion (t.ex. svullna \xf6gonlock, hosta) \xd6gon Mycket s\xe4llsynta (< 1/10 000): chorioretinit, konjunktivit, uveit Blodk\xe4rl Mycket s\xe4llsynta (< 1/10 000): k\xe4rlfistel Andningsv\xe4gar, Mindre vanliga (> 1/1 000, < 1/100): br\xf6stkorg och lunggranulom mediastinum Magtarmkanalen Mycket vanliga (> 1/10): Klassificering av Frekvens och biverkning organsystem illam\xe5ende'],
             ['Blood',
              u'00): kr\xe4kning, tarmfistel, peritonit Lever och gallv\xe4gar Mindre vanliga (> 1/1 000, < 1/100): hepatit Hud och subkutan Mindre vanliga (> 1/1 000, < 1/100): v\xe4vnad hudutslag Muskuloskeletala Mindre vanliga (> 1/1 000, < 1/100): systemet och bindv\xe4v artrit, artralgi Njurar och urinv\xe4gar Mycket vanliga (> 1/10): frekvent miktion med obehag och sm\xe4rta']]],
           ['Unknown',
            [['Blood',
              u'cytopeni, anemi Immunsystemet Mycket vanliga (> 1/10): \xf6verg\xe5ende systemisk BCG-reaktion (feber < 38,5 \xb0C, influensaliknande symtom inklusive allm\xe4n sjukdomsk\xe4nsla, feber, frossa, allm\xe4nt obehag)']]]],
 '_pages': [4, 6],
 u'_rank': 5,
 u'_type': u'LSFU'}