{'_data': [['Very common',
            [['Cardiac', u'Arytmi'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['Hepato', u'Levertoxicitet'],
             ['Skin', u'Hudreaktioner'],
             ['General', u'Feber, frossa, sm\xe4rta, tr\xf6tthet']]],
           ['Common',
            [['Infections', u'Infektion, s\xe5rinfektion'],
             ['Blood', u'Leukopeni, trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Nervous system',
              u'Nervskador, perifer neurotoxicitet, f\xf6r\xe4ndrat medvetandetillst\xe5nd, huvudv\xe4rk'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['Vascular', u'Ventrombos, art\xe4riell trombos, chock, hypotension'],
             ['Respiratory', u'Andn\xf6dssyndrom hos vuxna (ARDS)'],
             ['GI', u'Diarr\xe9, f\xf6rstoppning'],
             ['Skin', u'Hudnekros, perifert \xf6dem'],
             ['Musculoskeletal', u'Kompartmentsyndrom, myalgi'],
             ['Renal', u'Proteinuri'],
             ['General', u'Nattliga svettningar,'],
             ['Investigations',
              u'Nekros i extremiteter, allvarliga nog att kr\xe4va amputation Beskrivning av utvalda biverkningar Nekros i extremiteter samt kompartmentssyndrom kan vara tillr\xe4ckligt allvarligt f\xf6r att kr\xe4va amputation. F\xf6rdr\xf6jd debut av perifer arteriell ocklusionssjukdom (PAOD, Peripheral arterial occlusive disease) i nedre extremiteterna har rapporterats hos patienter flera \xe5r efter ILP-behandling, framf\xf6rallt hos patienter med etablerade kardiovaskul\xe4ra riskfaktorer, eller hos patienter som genomg\xe5tt str\xe5lning av den drabbade extremiteten.']]],
           ['Uncommon',
            [['Infections', u'Sepsis'],
             ['Vascular', u'Perifer arteriell ocklusionssjukdom'],
             ['Respiratory', u'Lung\xf6dem'],
             ['GI', u'Sm\xe4rta fr\xe5n bukens \xf6vre del, eroderande gastrit'],
             ['Skin', u'Onychomadesis (f\xf6rlust av naglar)'],
             ['Renal', u'Akut njursvikt'],
             ['Investigations',
              u'F\xf6rh\xf6jt blodkreatinin Kirurgiska och medicinska ingrepp']]]],
 '_pages': [6, 7],
 u'_rank': 25,
 u'_type': u'LSFU'}