{'_data': [['Very common',
            [['Cardiac', u'Takykardi'],
             ['Endocrine', u'Hypotyroidism '],
             ['Hepato', u'F\xf6rh\xf6jt -bilirubin'],
             ['Metabolism', u'Vikt\xf6kning Viktminskning'],
             ['Musculoskeletal', u'Artralgi'],
             ['Psychiatric', u'F\xf6rvirring '],
             ['Reproductive system', u'Menorragi'],
             ['Skin', u'Urtikaria Pruritus']]],
           ['Common', [['Blood', u'Anemi'], ['Skin', u'Alopeci']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni'],
             ['Hepato', u'F\xf6rh\xf6jt gamma-glutamyl-transferas Hepatit'],
             ['Metabolism', u'F\xf6rh\xf6jda triglycerider i blodet'],
             ['Nervous system', u'Konvulsioner'],
             ['Psychiatric',
              u'Sj\xe4lvmordsf\xf6rs\xf6k (se \xe4ven avsnitt 4.4) Emotionell labilitet'],
             ['Skin', u'Missf\xe4rgning av huden']]],
           ['Rare',
            [['Cardiac', u'Kardiomyopati'],
             ['Endocrine', u'Hypertyroidism Sk\xf6ldk\xf6rtel-rubbning'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leverskada (inklusive hepatit) Leversvikt'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Metabolism', u'Anorexi'],
             ['Respiratory', u'Bronkospasm']]],
           ['Unknown',
            [['Immune system',
              u'Kapill\xe4rl\xe4ckage-syndrom vid tidigare konstaterad monoklonal gammopati']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 11],
 u'_rank': 24,
 u'_type': u'MSFU'}