{'_data': [['Common',
            [['Eye',
              u' Kortvarig sveda och t\xe5rfl\xf6de vid instillationen. \xd6verg\xe5ende  dimsyn ']]],
           ['Uncommon',
            [['Eye', u' Nedsatt kornealsensibilitet, keratit, anisokori, fotofobi.  ']]],
           ['Rare',
            [['General', u' Huvudv\xe4rk  '],
             ['Vascular', u' Bradykardi '],
             ['Nervous system', u' S\xf6mnl\xf6shet. '],
             ['Skin', u' Erytem. '],
             ['Respiratory',
              u' Dyspn\xe9 och bronkospasm hos riskpatienter med speciell k\xe4nslighet f\xf6r betablockerare. '],
             ['Psychiatric', u' Depressiva symtom. ']]]],
 '_pages': [2, 3],
 u'_rank': 8,
 u'_type': u'DFSU'}