{'_data': [['Very common',
            [['Metabolism', u'\xe4tst\xf6rningar'],
             ['Nervous system', u's\xf6mnighet, ovanligt skrikande'],
             ['GI', u'diarr\xe9, kr\xe4kningar (s\xe4llsynt efter boosterdosen)'],
             ['Skin', u'utslag (s\xe4llsynt efter boosterdosen)'],
             ['General',
              u'feber (>38 \xb0C), \xf6mhet p\xe5 injektionsst\xe4llet (inklusive allvarlig \xf6mhet p\xe5 injektionsst\xe4llet definierat som att barnet skriker n\xe4r man r\xf6r p\xe5 den injicerade extremiteten), erytem p\xe5 injektionsst\xe4llet, svullnad p\xe5 injektionsst\xe4llet, induration p\xe5 injektionsst\xe4llet, irritabilitet'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'illam\xe5ende'],
             ['General',
              u'sm\xe4rta p\xe5 injektionsst\xe4llet (inklusive sv\xe5r sm\xe4rta p\xe5 injektionsst\xe4llet definierat som of\xf6rm\xe5ga att utf\xf6ra normal daglig aktivitet), svullnad p\xe5 injektionsst\xe4llet, induration p\xe5 injektionsst\xe4llet, erytem p\xe5 injektionsst\xe4llet, sjukdomsk\xe4nsla'],
             ['Musculoskeletal', u'myalgi, artralgi']]],
           ['Uncommon',
            [['Nervous system', u'krampanfall (inklusive feberkramper)'],
             ['Vascular', u'blekhet (s\xe4llsynt efter boosterdos)'],
             ['Skin', u'eksem, n\xe4sselutslag'],
             ['General', u'feber (>40 \xb0C) Ungdomar (fr\xe5n 11 \xe5r) och vuxna']]],
           ['Rare', [['Vascular', u'Kawasakis syndrom']]]],
 '_pages': [5, 6],
 u'_rank': 14,
 u'_type': u'LSFU'}