{'_data': [['Common', [['GI', u' Dyspepsi, illam\xe5ende.  ']]],
           ['Uncommon',
            [['General', u' Impotens, anafylaktisk reaktion.  '],
             ['Nervous system', u' Huvudv\xe4rk, yrsel.  '],
             ['GI', u' Flatulens, diarr\xe9, obstipation, kr\xe4kningar.  '],
             ['Skin', u' Hudutslag, urtikaria, fotosensibilisering, kl\xe5da.  '],
             ['Hepato', u' F\xf6rh\xf6jda aminotransferaser, kolestas. '],
             ['Musculoskeletal',
              u' Muskelsvaghet, myalgi, muskelkramp, f\xf6rh\xf6jda v\xe4rden av CK. '],
             ['Reproductive system', u' Akut njursvikt. ']]],
           ['Rare',
            [['Blood', u' F\xf6r\xe4ndrade trombocytv\xe4rden, leukopeni, anemi.  '],
             ['Musculoskeletal', u' Myosit, rabdomyolys.  '],
             ['Other',
              u' Alopeci. mycket s\xe4llsynta  fall kan erythema multiforme, Stevens-Johnsons syndrom, toxisk epidermal  ']]]],
 '_pages': [3, 3],
 u'_rank': 11,
 u'_type': u'DFSU'}