{'_data': [['Very common',
            [['Vascular', u'V\xe4rmevallningar'],
             ['Skin', u'Utslag'],
             ['Reproductive system', u'Gynekomasti, \xf6mhet i br\xf6sten'],
             ['General', u'Asteni']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Minskad libido, depression'],
             ['Nervous system', u'Yrsel, somnolens'],
             ['GI', u'Buksm\xe4rtor, f\xf6rstoppning, dyspepsi, flatulens, illam\xe5ende'],
             ['Hepato',
              u'Leverf\xf6r\xe4ndringar (inklusive f\xf6rh\xf6jda niv\xe5er av transaminaser och ikterus)'],
             ['Skin', u'Alopeci, hirsutism/h\xe5r\xe5terv\xe4xt, torr hud, kl\xe5da'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Impotens'],
             ['General', u'Br\xf6stsm\xe4rtor, \xf6dem'],
             ['Investigations',
              u'Vikt\xf6kning Leverf\xf6r\xe4ndringarna \xe4r s\xe4llan allvarliga och mycket ofta \xf6verg\xe5ende. De f\xf6rsvinner eller f\xf6rb\xe4ttras med fortsatt behandling eller efter att behandlingen har upph\xf6rt. Leversvikt har mycket s\xe4llan f\xf6rekommit hos patienter som behandlats med bikalutamid, men ett orsakssamband har inte med s\xe4kerhet fastst\xe4llts. Regelbundet \xe5terkommande leverfunktionstester ska \xf6verv\xe4gas (se \xe4ven avsnitt 4.4). Majoriteten av patienterna som f\xe5tt bikalutamid 150 mg som monoterapi har drabbats av gynekomasti och/eller br\xf6stsm\xe4rta. I studier ans\xe5gs dessa symtom vara allvarliga i upp till 5 % av patienterna. Gynekomansti f\xf6rsvinner kanske inte spontant efter avslutad behandling, s\xe4rskilt inte efter l\xe5ngvarig behandling. Dessutom rapporterades hj\xe4rtsvikt i kliniska pr\xf6vningar (som en m\xf6jlig biverkning enligt studiel\xe4karnas \xe5sikt, med en frekvens p\xe5 > 1 %) under behandling med bikalutamid plus en LHRH-analog. Det finns inga bevis p\xe5 n\xe5got orsakssamband med l\xe4kemedelsbehandling.']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner, inklusive angioneurotiskt \xf6dem och urtikaria'],
             ['Respiratory', u'Interstitiell lungsjukdom']]],
           ['Rare', [['Hepato', u'Leversvikt']]]],
 '_pages': [3, 4],
 u'_rank': 18,
 u'_type': u'LSFU'}