{'_data': [['Very common',
            [['Skin', u'Hudutslag'],
             ['Reproductive system', u'Gynekomasti och \xf6mma br\xf6st']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Aptitl\xf6shet (anorexi)'],
             ['Psychiatric', u'Minskad libido, depression'],
             ['Vascular', u'V\xe4rmevallningar  rapporterats)'],
             ['GI', u'Bukm\xe4rtor, f\xf6rstoppning,  dyspepsi, flatulens, illam\xe5ende'],
             ['Hepato', u'Hepatotoxicitet, gulsot, f\xf6rh\xf6jda  transaminasv\xe4rden'],
             ['Skin', u'Alopeci, hirsutism/\xe5terv\xe4xt av h\xe5r,  torr hud, kl\xe5da'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Impotens'],
             ['General', u'Br\xf6stsm\xe4rta, \xf6dem'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner  (inklusive angioneurotiskt \xf6dem och urtikaria)']]],
           ['Rare', [['Hepato', u'Leversvikt. Fall med d\xf6dlig  utg\xe5ng har rapporterats.']]]],
 '_pages': [3, 4],
 u'_rank': 15,
 u'_type': u'TSFU'}