{'_data': [['Very common',
            [['General', u'blodvallningar , asteni'],
             ['Reproductive system', u'\xf6mmande br\xf6st , gynekomasti'],
             ['Reproductive system', u'nedsatt libido, erektil dysfunkion, impotens']]],
           ['Common',
            [['GI', u'diarr\xe9, illm\xe5ende'],
             ['Skin', u'pruritus, torr hud'],
             ['Hepato',
              u'leverf\xf6r\xe4ndringar (f\xf6rh\xf6jda niv\xe5er av transaminaser, bilirubinemi, leverf\xf6rstoring, kolestas och gulsot)'],
             ['Blood', u'anemi'],
             ['Nervous system', u'yrsel, somnolens'],
             ['GI', u'f\xf6rstoppning'],
             ['Skin', u'hudutslag, makulopapul\xe4rt utslag, svettningar, hirsutism, alopeci'],
             ['Metabolism', u'diabetes mellitus, vikt\xf6kning'],
             ['General',
              u'\xf6dem (ansikte, extremiteter, b\xe5l), allm\xe4n sm\xe4rta, b\xe4ckensm\xe4rta, frossbrytningar']]],
           ['Uncommon',
            [['Respiratory', u'interstitial lungsjukdom'],
             ['Renal', u'hematuri'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner, inklusive angioneurotiskt \xf6dem och urtikaria.'],
             ['Psychiatric',
              u'depression Leverf\xf6r\xe4ndringar \xe4r s\xe4llan allvarliga och var oftast \xf6verg\xe5ende och f\xf6rsvann eller f\xf6rb\xe4ttrades med fortsatt behandling eller efter behandlingens avbrytande (se avsnitt 4.4). 2 Leversvikt har intr\xe4ffat i mycket s\xe4llsynta fall hos patienter behandlade med bikalutamid, men inget orsakssamband har kunnat fastst\xe4llas med s\xe4kerhet. Periodiska leverfunktionsprover b\xf6r \xf6verv\xe4gas (se \xe4ven avsnitt 4.4). Kan minska vid samtidig kastrering.'],
             ['Nervous system', u'insomnia'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'muntorrhet, magtarmsjukdomar, dyspepsi, flatulens'],
             ['Renal', u'nokturi'],
             ['Metabolism', u'anorexi, hyperglukemi, viktminskning'],
             ['General',
              u'magsm\xe4rtor, br\xf6stsm\xe4rta, huvudv\xe4rk, ryggsm\xe4rta, nacksm\xe4rta']]],
           ['Rare',
            [['GI', u'kr\xe4kningar'],
             ['Hepato', u'sv\xe5rt nedsatt leverfunktion, leversvikt']]],
           ['Very rare',
            [['Cardiac',
              u'hj\xe4rtsvikt, angina pectoris, retledningsdefekter inklusive f\xf6rl\xe4ngning av PR- och QT-intervall, arytmier och icke-specifika EKG-f\xf6r\xe4ndringar.'],
             ['Blood', u'trombocytopeni']]]],
 '_pages': [3, 5],
 u'_rank': 26,
 u'_type': u'LSFU'}