{'_data': [['Very common', [['Vascular', u'Magtarmkanalen  ']]],
           ['Common',
            [['Renal',
              u'Erektil dysfunktion Allm\xe4nna symtom och Mycket vanliga Asteni, \xf6dem symtom vid administreringsst\xe4llet'],
             ['Renal', u'Br\xf6stsm\xe4rta, allm\xe4n sm\xe4rta, b\xe4ckensm\xe4rta, frossa']]],
           ['Uncommon',
            [['Renal',
              u'Nokturi Reproduktionsorgan Mycket vanliga Gynekomasti och \xf6mmande br\xf6st och br\xf6stk\xf6rtel Impotens'],
             ['Renal',
              u'Huvudv\xe4rk, ryggv\xe4rk, nacksm\xe4rta Metabolism och Vanliga Minskad aptit, diabetes mellitus nutrition'],
             ['Renal',
              u'Hyperglykemi, viktminskning Psykiatriska Vanliga Minskad libido, depression st\xf6rningar Hj\xe4rtat Vanliga Myokardinfarkt (d\xf6dsfall har rapporterats) hj\xe4rtsvikt d']]],
           ['Rare',
            [['Renal',
              u'S\xe4llsynta Leversvikt (d\xf6dsfall har rapporterats) Unders\xf6kningar Vanliga Vikt\xf6kning Immunsystemet Mindre vanliga \xd6verk\xe4nslighet, angio\xf6dem och urtikaria Andningsv\xe4gar, Mindre vanliga Interstitiell lungsjukdom (d\xf6dsfall har br\xf6stkorg och rapporterats), dyspn\xe9 mediastinum 1 a. Kan minskas med samtidig kastration. b. Leverf\xf6r\xe4ndringar \xe4r s\xe4llan allvarliga och var i m\xe5nga fall \xf6verg\xe5ende. De f\xf6rsvinner eller f\xf6rb\xe4ttras med fortsatt behandling eller efter uts\xe4ttande av behandlingen (se avsnitt 4.4). c. F\xf6rtecknad som biverkning efter genomg\xe5ng av data efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning. d. Observerade i en farmako-epidemiologisk studie av LHRH-agonister och antiandrogener som anv\xe4nds i behandlingen av prostatacancer. Risken f\xf6ref\xf6ll att \xf6ka n\xe4r bikalutamid 50 mg anv\xe4ndes i kombination med LHRH-agonister men ingen \xf6kad risk observerades n\xe4r bikalutamid 150 mg anv\xe4ndes som monoterapi f\xf6r att behandla prostatacancer. Dessutom rapporterades hj\xe4rtsvikt i kliniska pr\xf6vningar (som en m\xf6jlig biverkning enligt pr\xf6varnas bed\xf6mning, med en frekvens >1 %) under behandling med bikalutamid plus en LHRH-analog. Det fanns inga bel\xe4gg f\xf6r ett orsakssamband med l\xe4kemedelsbehandling.. 4']]],
           ['Very rare',
            [['Renal',
              u'Angina, \xf6verledningsrubbningar inklusive f\xf6rl\xe4ngning av PR- och QT-intervallet, arytmier och icke-specifika EKG-f\xf6r\xe4ndringar Lever och gallv\xe4gar Vanliga Levertoxicitet, gulsot, hypertransaminasemi']]]],
 '_pages': [3, 4],
 u'_rank': 8,
 u'_type': u'LSFU'}