{'_data': [['Very common',
            [['Skin', u'Hudutslag'],
             ['Reproductive system', u'Gynekomasti och \xf6mhet i br\xf6sten'],
             ['General', u'Asteni']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Minskad libido, depression'],
             ['Nervous system', u'Yrsel, s\xf6mnighet'],
             ['Vascular', u'V\xe4rmevallningar'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Impotens'],
             ['General', u'Sm\xe4rtor i br\xf6stkorgen, \xf6dem'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner som  angioneurotiskt \xf6dem och urtikaria']]]],
 '_pages': [3, 4],
 u'_rank': 13,
 u'_type': u'TSFU'}