{'_data': [['Very common',
            [['Blood', u'Anemi'],
             ['Nervous system', u'Yrsel'],
             ['Vascular', u'Blodvallningar'],
             ['GI', u'Buksm\xe4rtor, f\xf6rstoppning,  illam\xe5ende'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Gynekomasti och \xf6mmande  br\xf6st'],
             ['General', u'Asteni, \xf6dem  (+ LHRH-analog)']]],
           ['Common',
            [['Metabolism', u'Minskad aptit'],
             ['Psychiatric', u'Minskad libido, depression'],
             ['Cardiac', u'Hj\xe4rtinfarkt (fall med  d\xf6dlig utg\xe5ng har'],
             ['Nervous system', u'Somnolens'],
             ['GI', u'Dyspepsi, flatulens'],
             ['Hepato', u'Hepatotoxicitet, gulsot,  hypertransaminasemi'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General', u'Br\xf6stsm\xe4rtor'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet, angio\xf6dem  och urtikaria'],
             ['Respiratory',
              u'Interstitiell lungsjukdom  (fall med d\xf6dlig utg\xe5ng har  rapporterats)']]]],
 '_pages': [3, 4],
 u'_rank': 18,
 u'_type': u'TSFU'}