{'_data': [['Very common',
            [['Blood', u'Anemi'],
             ['Nervous system', u'Yrsel'],
             ['Vascular', u'V\xe4rmesvallning'],
             ['GI', u'Magsm\xe4rtor, f\xf6rstoppning, illam\xe5ende'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Gynekomasti, \xf6mmande br\xf6st e'],
             ['General', u'Asteni. \xf6dem']]],
           ['Common',
            [['Metabolism', u'Minskad aptit'],
             ['Cardiac', u'Hj\xe4rtinfarkt (d\xf6dsfall har rapporterats) a , hj\xe4rtsvikt'],
             ['Nervous system', u'Somnolens'],
             ['GI', u'Dyspepsi, flatulens'],
             ['Hepato', u'Hepatotoxicitet, gulsot, hypertransaminasami'],
             ['Skin',
              u'Alopecia, Hirsuitism/ h\xe5r-\xe5terv\xe4xt, torr hud, pruritis, utslag'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General', u'Br\xf6stsm\xe4rta'],
             ['Investigations',
              u'Viktuppg\xe5ng Observerat i en farmakoepidemiologistudie av LHRH-agonister och antiandrogener som anv\xe4nds vid behandling av prostatacancer. Risken verkade \xf6kas n\xe4r bikalutamid 50 mg gavs i kombination med LHRH-agonister, men ingen \xf6kad risk var uppenbar n\xe4r bikalutamid 150 mg anv\xe4ndes som monoterapibehandling av prostatacancer. B anges som en biverkning efter granskning av post-marknadsf\xf6rs data. Frekvens v\xe4l har best\xe4mts fr\xe5n incidensen av rapporterade biverkningar av interstitiell pneumoni I den randomiserade behandlingen under de 150 mg EPC studier. Listad som en biverkning efter granskning av data efter marknadsf\xf6ring. Frekvensen \xe4r best\xe4md utifr\xe5n incidensen av rapporterade biverkningar av interstitiell pneumoni i den randomiserade behandlingen i EPC-studien f\xf6r 150 mg. Leverf\xf6r\xe4ndringar \xe4r s\xe4llan allvarliga och var oftast \xf6verg\xe5ende och f\xf6rsvann eller f\xf6rb\xe4ttrades med fortsatt behandling eller efter behandlingens avbrytande. Listad som en biverkning efter granskning av data efter marknadsf\xf6ring. Frekvensen \xe4r best\xe4md utifr\xe5n incidensen av rapporterade biverkningar av leversvikt hos patienter som f\xe5tt bikalutamid-behandling med 150 mg i den \xf6ppna delen av EPC-studierna. Kan minska vid samtidig kastrering.']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighetsreaktioner, angio\xf6dem och urtikaria'],
             ['Psychiatric', u'Minskad libido, depression'],
             ['Respiratory', u'Interstitiell lungsjukdom (d\xf6dsfall har rapporterats)']]],
           ['Rare', [['Hepato', u'Leversvikt (d\xf6dsfall har rapporterats)']]]],
 '_pages': [3, 4],
 u'_rank': 20,
 u'_type': u'LSFU'}