{'_data': [['Common',
            [['Nervous system', u'yrsel'],
             ['Ear', u'vestibularisp\xe5verkan med  illam\xe5ende'],
             ['Renal', u'proteinuri, ureastegring']]],
           ['Uncommon',
            [['Infections',
              u'superinfektioner eller  kolonisation med resistenta bakterier eller j\xe4stsvamp'],
             ['GI', u'illam\xe5ende, kr\xe4kningar'],
             ['Hepato', u'transaminasstegringar'],
             ['Skin', u'utslag']]],
           ['Rare',
            [['Blood', u'anemi, eosinofili, leukopeni,  trombocytopeni'],
             ['Metabolism', u'hypomagnesemi'],
             ['Nervous system', u'tremor  parestesier  huvudv\xe4rk, balansrubbning'],
             ['Eye', u'blindhet, retinal infarkt'],
             ['Ear', u'tinnitus  h\xf6rselneds\xe4ttning'],
             ['Vascular', u'hypotension'],
             ['Skin', u'urticaria, kl\xe5da'],
             ['Musculoskeletal', u'arthralgi,  muskelsammandragningar'],
             ['Renal', u'oliguri  serumkreatininstegring'],
             ['General', u'feber']]],
           ['Unknown',
            [['Immune system',
              u'anafylaktiskt svar  (anafylaktisk reaktion, anafylaktisk shock och anafylaktoid reaktion), \xf6verk\xe4nslighet'],
             ['Nervous system', u'akut muskelparalys'],
             ['Ear', u'd\xf6vhet  neurosensorisk  d\xf6vhet'],
             ['Respiratory', u'apn\xe9, bronkospasm'],
             ['Renal', u'akut njursvikt, toxisk  nefropati, celler i urinen']]]],
 '_pages': [6, 8],
 u'_rank': 22,
 u'_type': u'TSFU'}