{'_data': [['Uncommon', [['GI', u'buksm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9']]],
           ['Rare',
            [['Immune system', u'(> 1/10 000, < 1/1 000): Allergiska reaktioner'],
             ['Skin', u'Hudutslag']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk reaktion, anafylaktisk chock'],
             ['Respiratory', u'Bronkospasm'],
             ['Skin', u'Angio\xf6dem, urtikaria, kl\xe5da']]]],
 '_pages': [2, 2],
 u'_rank': 6,
 u'_type': u'LSFU'}