{'_data': [['Very common', [['Cardiac', u'bradykardi']]],
           ['Common',
            [['Nervous system', u'yrsel, huvudv\xe4rk.'],
             ['Cardiac', u'f\xf6rv\xe4rrad hj\xe4rtsvikt.'],
             ['Vascular',
              u'k\xe4nsla av kyla eller domning i ben och armar, hypotoni s\xe4rskilt hos patienter med med hj\xe4rtsvikt.'],
             ['GI',
              u'mag-tarmbesv\xe4r som illam\xe5ende, kr\xe4kningar, diarr\xe9, f\xf6rstoppning.'],
             ['General', u'asteni, tr\xf6tthet.']]],
           ['Uncommon',
            [['Psychiatric', u'depression, s\xf6mnst\xf6rningar.'],
             ['Cardiac', u'AV-\xf6verledningsst\xf6rningar'],
             ['Respiratory',
              u'bronkospasm hos patienter med bronkialastma eller anamnes med obstruktiv sjukdom i andningsv\xe4garna.'],
             ['Musculoskeletal', u'muskelsvaghet och kramper.']]],
           ['Rare',
            [['Psychiatric', u'mardr\xf6mmar, hallucinationer.'],
             ['Nervous system', u'synkope'],
             ['Eye',
              u'F\xf6rs\xe4mrat t\xe5rfl\xf6de (b\xf6r beaktas om patienten b\xe4r kontaktlinser).'],
             ['Ear', u'H\xf6rselneds\xe4ttning'],
             ['Respiratory', u'Allergisk rinit.'],
             ['Hepato', u'hepatit.'],
             ['Skin', u'\xd6verk\xe4nslighetsreaktioner (kl\xe5da, rodnad, utslag).'],
             ['Reproductive system', u'potensst\xf6rningar.'],
             ['Investigations',
              u'f\xf6rh\xf6jda triglycerider, f\xf6rh\xf6jda leverenzymer (ALAT, ASAT)']]],
           ['Very rare',
            [['Eye', u'Konjunktivit.'],
             ['Skin',
              u'alopecia, \u03b2-blockerare kan provocera eller f\xf6rv\xe4rra psoriasis eller inducera psoriasis-liknande utslag.']]]],
 '_pages': [6, 8],
 u'_rank': 21,
 u'_type': u'LSFU'}