{'_data': [['Very common', [['Cardiac', u'bradykardi']]],
           ['Common',
            [['Nervous system', u'yrsel, huvudv\xe4rk'],
             ['Cardiac', u'f\xf6rv\xe4rrad hj\xe4rtsvikt'],
             ['Vascular',
              u'k\xe4nsla av kyla eller domning i armar och ben, hypotoni s\xe4rskilt hos patienter med hj\xe4rtsvikt.'],
             ['GI',
              u'gastrointestinala besv\xe4r som illam\xe5ende, kr\xe4kningar, diarr\xe9, f\xf6rstoppning.'],
             ['Reproductive system', u'asteni, tr\xf6tthet.']]],
           ['Uncommon',
            [['Psychiatric', u's\xf6mnrubbningar, depression.'],
             ['Cardiac', u'AV-\xf6verledningsst\xf6rningar'],
             ['Respiratory',
              u'bronkospasm hos patienter med bronkialastma eller anamnes p\xe5 obstruktiv luftv\xe4gssjukdom'],
             ['Musculoskeletal', u'muskelsvaghet, kramper.']]],
           ['Rare',
            [['Psychiatric', u'mardr\xf6mmar, hallucinationer.'],
             ['Nervous system', u'synkope'],
             ['Eye',
              u'minskat t\xe5rfl\xf6de (att beakta om patienten anv\xe4nder kontaktlinser).'],
             ['Ear', u'nedsatt h\xf6rsel.'],
             ['Respiratory', u'allergisk rinit.'],
             ['Hepato', u'hepatit.'],
             ['Skin', u'\xf6verk\xe4nslighetsreaktioner (kl\xe5da, rodnad, utslag).'],
             ['Reproductive system',
              u'potensst\xf6rningar. Allm\xe4nna symtom och symtom vid administreringsst\xe4llet'],
             ['Investigations',
              u'f\xf6rh\xf6jda triglycerider, f\xf6rh\xf6jda leverenzymer (ALT, AST).']]],
           ['Very rare',
            [['Eye', u'konjunktivit.'],
             ['Skin',
              u'betablockerare kan utl\xf6sa eller f\xf6rv\xe4rra psoriasis eller framkalla psoriasislika utslag, alopeci.']]]],
 '_pages': [6, 7],
 u'_rank': 21,
 u'_type': u'LSFU'}