{'_data': [['Common',
            [['Metabolism', u'Asymptomatisk hypokalcemi'],
             ['GI',
              u'Diarr\xe9**, illam\xe5ende**. kr\xe4kningar** F\xf6rh\xf6jda transminaser'],
             ['Hepato', u'vanligtvis inom normal-intervallet']]],
           ['Rare',
            [['Metabolism',
              u'Symtomatisk hypokalcemi, f\xf6rh\xf6jda v\xe4rden av serumparathormon med \xe5tf\xf6ljande minskad serumkalciumniv\xe5, f\xf6rh\xf6jt alkalisk fosfatas*'],
             ['GI', u'F\xf6rh\xf6jda transminaser, mer \xe4n dubbel s\xe5'],
             ['Hepato',
              u'mycket som normalv\xe4rdet, utan \xe5tf\xf6ljande abnormitet i leverfunktion'],
             ['Skin', u'\xd6verk\xe4nslighetsreaktion i form av hudreaktion']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 7,
 u'_type': u'MSFU'}