{'_data': [['Rare',
            [['Immune system',
              u'reaktion  reaktion/chock*  \u2020 Centrala och perifera  Huvudv\xe4rk'],
             ['Nervous system', u''],
             ['Eye', u'Okul\xe4ra   inflammationer*  \u2020'],
             ['Vascular', u'Flebit/tromboflebit'],
             ['GI', u'Dyspepsi,  Diarr\xe9,  Buksm\xe4rta,  Illam\xe5ende,  F\xf6rstoppning'],
             ['Skin',
              u'v\xe4vnad  Ansiktssvullnad/-   \xf6dem, Urtikaria  Muskuloskeletala  Artralgi,  Skelettsm\xe4rta Atypiska  Osteonekros i   systemet och bindv\xe4v  Myalgi,  subtrokant\xe4ra och  k\xe4ken*  \u2020 Muskulo-  diafys\xe4ra   skeletal  femurfrakturer  \u2020 sm\xe4rta,  Ryggsm\xe4rta'],
             ['General',
              u'och/eller symtom vid  liknande  injektionsst\xe4llet,   administreringsst\xe4llet  sjukdom*,  Asteni   Tr\xf6tthet  *Se ytterligare information nedan  \u2020Identifierad efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning.']]]],
 '_pages': [4, 6],
 u'_rank': 6,
 u'_type': u'LFSUR'}