{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk'], ['GI', u'Buksm\xe4rta']]],
           ['Common',
            [['Infections', u'Urinv\xe4gsinfektion, nasofaryngit'],
             ['Vascular', u'V\xe4rmevallning'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, utsp\xe4nd buk, obehagsk\xe4nsla i buken, diarr\xe9, f\xf6rstoppning'],
             ['Skin', u'Utslag'],
             ['Musculoskeletal', u'Muskelkramp'],
             ['Reproductive system',
              u'Vaginalbl\xf6dning, OHSS, sm\xe4rtor i b\xe4cken, \xf6mma br\xf6st, vaginalflytning'],
             ['General',
              u'Sm\xe4rta, sm\xe4rtor och reaktioner vid injektionsst\xe4llet (rodnad, bl\xe5m\xe4rken, svullnad och/eller kl\xe5da)']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 9,
 u'_type': u'MSFU'}