{'_data': [['Common',
            [['Psychiatric', u'konfusionstillst\xe5nd'],
             ['Nervous system', u'somnolens, yrsel, huvudv\xe4rk, sedering'],
             ['Eye', u'avvikande syn (dimsyn, diplopi)'],
             ['GI', u'illam\xe5ende, f\xf6rstoppning, kr\xe4kningar, muntorrhet'],
             ['Skin', u'pruritus'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Metabolism', u'anorexi'],
             ['Psychiatric',
              u'\xe5ngest, hallucination, vanf\xf6rest\xe4llning, avvikande dr\xf6mmar, nervositet, s\xf6mnl\xf6shet, rastl\xf6shet'],
             ['Nervous system', u'dysgeusi, letargi, amnesi, kognitiv sjukdom'],
             ['Vascular', u'blodvallning'],
             ['Respiratory', u'andningsdepression, n\xe4st\xe4ppa'],
             ['GI',
              u'diarr\xe9, stomatit, gingival bl\xf6dning, dyspepsi, s\xe5r i munnen, munsm\xe4rta, odynofagi'],
             ['Skin', u'hyperhidros, \xf6kad tendens till bl\xe5m\xe4rken'],
             ['Musculoskeletal',
              u'muskelryckningar, artralgi, muskelsvaghet, muskuloskeletal sm\xe4rta, sm\xe4rta i extremiteter, sm\xe4rta i k\xe4ken'],
             ['Renal', u'urininkontinens'],
             ['General', u'asteni, frossa, pyrexi, t\xf6rst'],
             ['Investigations', u'\xf6kat blodtryck'],
             ['Injury', u'oavsiktlig skada (t.ex. fall)']]],
           ['Very rare',
            [['Psychiatric',
              u'avvikande tankar, depersonalisering, depression, emotionell labilitet, eufori'],
             ['Nervous system',
              u'myoklonus, parestesi (inklusive hyperestesi/cirkumoral parestesi), avvikande g\xe5ng/inkoordination'],
             ['Vascular', u'vasodilatation'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'buksm\xe4rta, flatulens, f\xf6rstorad buk'],
             ['Skin', u'utslag'],
             ['Renal', u'urinretention'],
             ['General', u'olustk\xe4nsla']]]],
 '_pages': [7, 8],
 u'_rank': 26,
 u'_type': u'LSFU'}