{'_data': [['Very common', [['Nervous system', u' dysgeusi'], ['Respiratory', u' nysning']]],
           ['Common',
            [['Nervous system', u' parestesi, yrsel, huvudv\xe4rk, hypestesi'],
             ['Cardiac', u' bradykardi***, f\xf6rmaksfladder***'],
             ['Vascular', u' hypotension'],
             ['Respiratory', u' hosta, n\xe4sbesv\xe4r'],
             ['GI', u' illam\xe5ende, kr\xe4kningar, muntorrhet'],
             ['Skin', u' kl\xe5da, hyperhidros'],
             ['General',
              u' sm\xe4rta vid infusionsst\xe4llet, parestesi vid infusionsst\xe4llet, v\xe4rmek\xe4nsla, utmattning']]],
           ['Uncommon',
            [['Nervous system',
              u'br\xe4nnande k\xe4nsla, parosmi, somnolens, vasovagal synkope'],
             ['Eye', u' \xf6gonirritation, \xf6kat t\xe5rfl\xf6de, synrubbning'],
             ['Cardiac', u'sinusarrest, totalt AV-block, AV-block I, v\xe4nstersidigt'],
             ['Vascular', u'blodvallning, v\xe4rmevallning, blekhet'],
             ['Respiratory', u'dyspn\xe9, kv\xe4vningsk\xe4nsla, rinorr\xe9, halsirritation'],
             ['GI', u'diarr\xe9, tr\xe4ngning till defekation'],
             ['Skin', u'generaliserad kl\xe5da, kallsvettning'],
             ['Musculoskeletal', u' sm\xe4rta i extremiteter '],
             ['General',
              u' irritation vid infusionsst\xe4llet, \xf6verk\xe4nslighet vid infusionsst\xe4llet, sjukdomsk\xe4nsla, br\xf6stobehag']]]],
 '_pages': [6, 7],
 u'_rank': 18,
 u'_type': u'LSFU2'}