{'_data': [['Very common',
            [['GI', u'Pankreatit.'],
             ['Hepato', u'Leversvikt.'],
             ['Skin', u'Bull\xf6sa reaktioner s\xe5som']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['GI',
              u'Dyspepsi, diarr\xe9, illam\xe5ende,  kr\xe4kningar, buksm\xe4rtor, flatulens, f\xf6rstoppning, melena, hematemes, gastrointestinal bl\xf6dning'],
             ['Skin', u'Hudutslag'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Infections', u'Rinit'],
             ['Blood',
              u'Leukopeni, trombocytopeni,  agranulocytos, aplastisk anemi, hemolytisk anemi.'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, l\xe4tt oro'],
             ['Nervous system', u'Parestesi, somnolens.'],
             ['Eye', u'Synrubbningar'],
             ['Ear', u'H\xf6rselskador'],
             ['Respiratory', u'Astma, bronkospasm, dyspn\xe9.'],
             ['GI',
              u'Gastrit, ulcus (ventriculi et  duodeni), ulcerativ stomatit, gastrointestinal perforering.'],
             ['Hepato', u'Hepatit, gulsot, onormal  leverfunktion.'],
             ['Skin', u'Urtikaria, pruritus, purpura,  angio\xf6dem, fotosensitivitet'],
             ['Renal', u'Interstitiell nefrit, nefrotiskt  syndrom, njursvikt']]],
           ['Rare',
            [['Infections', u'Aseptisk meningit'],
             ['Immune system', u'Anafylaktisk reaktion.'],
             ['Psychiatric', u'Depression, konfusion'],
             ['Nervous system', u'Optikusneurit.'],
             ['Eye', u'Toxisk amblyopi'],
             ['Ear', u'Tinnitus, yrsel'],
             ['GI', u''],
             ['Hepato', u'Leverskador.'],
             ['Hepato', u''],
             ['Skin',
              u'Stevens-Johnsons syndrom och  toxisk epidermal nekrolys och erythema multiforme.'],
             ['General', u'\xd6dem.']]],
           ['Unknown', [['GI', u'Kolit, Crohns sjukdom.']]]],
 '_pages': [7, 8],
 u'_rank': 28,
 u'_type': u'TSFU'}