{'_data': [['Very common',
            [['Ear', u'Hj\xe4rtat  '],
             ['Vascular', u'Nedsatt leverfunktion, leverskada, speciellt vid'],
             ['Vascular', u'Sv\xe5ra former av hudreaktioner (erytema multiforme, exfoliativ'],
             ['Vascular',
              u'Renal papill\xe4r nekros vid l\xe5ngtidsbehandling (se avsnitt 4.4).']]],
           ['Common',
            [['Vascular',
              u'avsnitt 4.4), dold bl\xf6dning som kan leda till anemi, melena, hematemes, ulcerativ stomatit, kolit, f\xf6rv\xe4rrad inflammatorisk tarmsjukdom, komplikationer av kolon divertiklar (perforation, fistlar), gastrit Very rare Esofagit, pankreatit, intestinala strikturer. Lever och gallv\xe4gar S\xe4llsynta \xd6kning av urea i blodet, f\xf6rh\xf6jda transaminaser och alkaliska fosfataser.'],
             ['Vascular',
              u'nedsatt njurfunktion, nefrotiskt syndrom, interstitiell nefrit som kan vara associerad med njursvikt.']]],
           ['Rare',
            [['Ear', u'balansorgan  '],
             ['Vascular',
              u'Andningsv\xe4gar, Mindre Rinit, bronkospasm. br\xf6stkorg och vanliga mediastinum Organsystem Frekvens Biverkningar Magtarmkanalen Vanliga Gastrointestinala rubbningar s\xe5som halsbr\xe4nna, dyspepsi, buksm\xe4rta och illam\xe5ende, kr\xe4kningar, flatulens, diarr\xe9, f\xf6rstoppning. Mindre Gastrointestinala ulcer, ibland med bl\xf6dning och perforation (se'],
             ['Vascular',
              u'l\xe5ngtidsbehandling, leversvikt, akut hepatit, ikterus. Hud och subkutan Mindre Fotosensitivitet. v\xe4vnad vanliga'],
             ['Vascular',
              u'dermatit, bl\xe5sbildande reaktioner inklusive Stevens-Johnson syndrom och toxisk epidermal nekrolys, alopeci, nekrotiserande fascit). Njurar och urinv\xe4gar Mindre Utveckling av \xf6dem speciellt hos patienter med hypertoni eller'],
             ['Vascular',
              u's\xe4llsynta Unders\xf6kningar S\xe4llsynta Minskning av hemoglobin- och hematokritniv\xe5er, h\xe4mning av trombocytaggregationen, f\xf6rl\xe4ngning av bl\xf6dningstid, minskning av serumkalcium, \xf6kning av serumurinsyra.']]]],
 '_pages': [8, 10],
 u'_rank': 11,
 u'_type': u'LSFU'}