{'_data': [['Unknown',
            [['Immune system',
              u'St\xf6rningar i immunf\xf6rsvaret (t. ex. \xf6kad infektionsrisk). F\xf6rs\xe4mring eller \xe5terupptr\xe4dande av extraintestinala manifestationer (s\xe4rskilt i hud och leder) kan intr\xe4ffa n\xe4r patienten st\xe4lls om fr\xe5n systemisk glukokortikosteroidbehandling till lokalt verkande budesonid.'],
             ['Metabolism',
              u'natriumretention med \xf6dembildning, \xf6kad kaliumuts\xf6ndring, inaktivitet eller atrofi av binjurebarken, tillv\xe4xth\xe4mning hos barn, st\xf6rning i sexualhormonuts\xf6ndringen (t. ex. amenorr\xe9, hirsutism, impotens).'],
             ['Psychiatric',
              u'Depression, irritation, eufori. Samt flera olika typer av mycket s\xe4llsynta psykiatriska effekter och beteendef\xf6r\xe4ndringar kan uppst\xe5.'],
             ['Eye', u'Glaukom, katarakt.'],
             ['Vascular',
              u'Hypertoni, \xf6kad trombosrisk, vaskulit (uts\xe4ttningssyndrom efter l\xe5ngtidsbehandling).'],
             ['GI', u'Magbesv\xe4r, gastroduodenals\xe5r, pankreatit.'],
             ['Skin',
              u'Allergiskt exantem, r\xf6da striae, petekier, ekkymos, steroidakne, f\xf6rdr\xf6jd s\xe5rl\xe4kning, kontaktdermatit.'],
             ['Musculoskeletal',
              u'Aseptisk bennekros (femur och caput humeri). Biverkningar vid kliniska studier hos pediatriska patienter Crohns sjukdom Vid kliniska studier med Budenofalk 3 mg kapslar till 82 pediatriska patienter med Crohns sjukdom s\xe5 var h\xe4mmad binjurefunktion samt huvudv\xe4rk de mest frekventa biverkningarna. Biverkningar som \xe4r typiska f\xf6r steroider rapporterades s\xe5v\xe4l som andra s\xe4llsynta reaktioner t.ex.yrsel, illam\xe5ende, kr\xe4kning samt hyperakusi (se \xe4ven avsnitt 5.1). Autoimmun hepatit: Vid en autoimmun hepatit klinisk studie visade s\xe4kerhetsdata fr\xe5n en undergrupp av totalt 42 pediatriska patienter att rapporterade biverkningar ej skiljde sig eller f\xf6rekom mer frekvent i j\xe4mf\xf6relse med den vuxna populationen i denna studie (se \xe4ven avsnitt 5.1) .']]]],
 '_pages': [5, 6],
 u'_rank': 8,
 u'_type': u'LSFU'}