{'_data': [['Very common',
            [['Psychiatric', u's\xf6mnl\xf6shet'], ['Skin', u'asteni, abstinenssymtom']]],
           ['Common',
            [['Psychiatric', u'\xe5ngest, nervositet, d\xe5sighet'],
             ['Nervous system', u'yrsel, huvudv\xe4rk'],
             ['Eye', u'lakrimationsst\xf6rning'],
             ['Cardiac', u'QT-f\xf6rl\xe4ngning'],
             ['Vascular',
              u'svimning, ortostatisk hypotension Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'snuva'],
             ['GI', u'f\xf6rstoppning, diarr\xe9, illam\xe5ende, kr\xe4kning, buksm\xe4rta'],
             ['Skin', u'svettning Allm\xe4nna symtom och symtom vid administreringsst\xe4llet'],
             ['Skin', u'ryggv\xe4rk, frossbrytningar']]],
           ['Uncommon',
            [['Psychiatric', u'hallucinationer'],
             ['Vascular', u'andningsdepression'],
             ['Hepato', u'levernekros, hepatit*']]],
           ['Very rare',
            [['Immune system', u'anafylaktisk chock, angio\xf6dem'],
             ['Vascular', u'bronkospasm']]]],
 '_pages': [5, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}