{'_data': [['Common',
<<<<<<< HEAD
            [['Nervous system', u'Huvudv\xe4rk'],
=======
            [['Nervous system', u'Huvudv\xe4rk '],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI',
              u'Kr\xe4kning, diarr\xe9, buksm\xe4rta, dyspepsi, illam\xe5ende, f\xf6rstoppning'],
             ['Skin', u'Eksem'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric', u'S\xf6mnl\xf6shet, l\xe4tt oro'],
             ['Eye', u'Synrubbningar'],
             ['Ear', u'H\xf6rselp\xe5verkan'],
             ['Respiratory', u'Astma, rinit'],
             ['GI', u'Bl\xf6dning, ulcus, ulcerativ stomatit'],
             ['Skin', u'Angio\xf6dem, urtikaria, purpura, kl\xe5da.']]],
           ['Rare',
            [['Blood', u'Aplastisk anemi, leukopeni, trombocytopeni'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Psychiatric', u'Depression, f\xf6rvirring'],
             ['Nervous system', u'Aseptisk meningit, yrsel, optikusneurit'],
             ['Eye', u'Toxisk amblyopi'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['Vascular', u'Hypertoni'],
             ['GI',
              u'Perforation, pankreatit, hematemes, melena, kolit, f\xf6rs\xe4mring av ulcer\xf6s kolit och Crohns sjukdom, gastrit, flatulens'],
             ['Hepato', u'Leverp\xe5verkan, hepatit, gulsot och f\xf6rh\xf6jda leverenzymer'],
             ['Skin',
              u'Bull\xf6sa reaktioner som Stevens Johnsons syndrom, toxisk epidermal nekrolys, erytema multiforme, fotosensitivitet, alopeci'],
             ['Renal',
              u'Akut njursvikt och interstitiell nefrit, renal pappil\xe4r nekros nedsatt njurfunktion'],
             ['General', u'\xd6dem, v\xe4tskeretention']]]],
 '_note': u' ?MSFU',
<<<<<<< HEAD
 '_pages': [7, 8],
=======
 '_pages': [7, 9],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_rank': 23,
 u'_type': u'MSFU'}