{'_data': [['Unknown',
            [['Immune system',
              u'Anafylaktisk reaktion X Metabolism och nutrition Hypoglykemi (med en X sulfonureid) Minskad aptit X Centrala och perifera'],
             ['GI',
              u'Illam\xe5ende X Kr\xe4kningar X Diarr\xe9 X Dyspepsi X Buksm\xe4rta X Gastroesofagal X refluxsjukdom Utsp\xe4nd buk X Eruktation X F\xf6rstoppning X Flatulens X Hud och subkutan v\xe4vnad Makul\xe4ra och papul\xf6sa X utslag Kl\xe5da och/eller X n\xe4sselutslag Angioneurotiskt \xf6dem X'],
             ['General',
              u'och/eller symtom vid administreringsst\xe4llet Kl\xe5da vid X injektionsst\xe4llet Tr\xf6tthet X Erytem vid X injektionsst\xe4llet Utslag vid X injektionsst\xe4llet Somnolens X Frekvens baserad p\xe5 kliniska pr\xf6vningsdata f\xf6r BYDUREON, n=592 totalt (patienter som behandlades med sulfonureid n=135). Frekvens baserad p\xe5 data f\xf6r BYDUREON fr\xe5n spontanrapporter. Biverkningarna l\xe5g inom samma frekvensgruppering i gruppen som fick behandling med exenatid tv\xe5 g\xe5nger dagligen.'],
             ['Metabolism',
              u'vanligtvis i samband med illam\xe5ende, kr\xe4kningar och/eller diarr\xe9 Centrala och perifera'],
             ['GI', u'avsnitt 4.4) Hud och subkutan v\xe4vnad Hyperhidros X Alopeci X'],
             ['Renal',
              u'njurfunktion, omfattande akut njursvikt, f\xf6rs\xe4mrad kronisk njursvikt, nedsatt njurfunktion, f\xf6rh\xf6jt serumkreatinin (se avsnitt 4.4).'],
             ['General',
              u'och/eller symtom vid administreringsst\xe4llet Asteni X Nervositet X'],
             ['Investigations',
              u'normaliserad kvot \xf6kade vid samtidig anv\xe4ndning av warfarin, vissa rapporter hade samband med bl\xf6dningar (se avsnitt 4.4). Frekvens baserad p\xe5 data fr\xe5n kliniska studier p\xe5 exenatid tv\xe5 g\xe5nger dagligen. Frekvens baserad p\xe5 data fr\xe5n spontanrapporter om exenatid tv\xe5 g\xe5nger dagligen.']]]],
 '_pages': [5, 9],
 u'_rank': 8,
 u'_type': u'LSFU'}