{'_data': [['Very common',
            [['GI', u'Illam\xe5ende'],
             ['General', u'Perifera \xf6dem'],
             ['GI', u'Illam\xe5ende'],
             ['Cardiac', u'Hj\xe4rtklaffp\xe5verkan (including klaffl\xe4ckage)'],
             ['Respiratory', u'Fibros']]],
           ['Common',
            [['Psychiatric', u'Hallucinationer, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Yrsel, dyskinesi'],
             ['Vascular', u'Postural hypotension'],
             ['GI', u''],
             ['GI', u'F\xf6rstoppning, dyspepsi, gastrit, kr\xe4kning'],
             ['General', u''],
             ['Psychiatric', u'F\xf6rvirring, hallucinationer'],
             ['Nervous system', u'Yrsel, dyskinesi'],
             ['Cardiac', u'Angina'],
             ['Cardiac', u'Postural hypotension'],
             ['GI', u''],
             ['GI', u'Dyspepsi, gastrit, kr\xe4kning'],
             ['General', u'Perifera \xf6dem'],
             ['Investigations',
              u'Minskade v\xe4rden f\xf6r hemoglobin, hematokrit  och/eller r\xf6dablodkroppar (>15% vs baseline)'],
             ['Psychiatric', u'\xd6kat libido'],
             ['Nervous system', u'Huvudv\xe4rk, somnolens'],
             ['Cardiac',
              u'relaterade f\xf6r\xe4ndringar (perikardit, perikardiell  utgjutning)'],
             ['Respiratory', u'Dyspne'],
             ['General', u'Asteni'],
             ['General', u'Onormala leverv\xe4rden']]],
           ['Uncommon',
            [['Nervous system', u'Hyperkinesi'],
             ['Cardiac', u'Erythromelalgi'],
             ['Respiratory', u'Pleurautgjutning, lungfibros'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Psychiatric', u'Vanf\xf6rest\xe4llningar, psykotisk sjukdom'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Utslag'],
             ['General', u'\xd6dem, utmattning']]],
           ['Rare', [['Respiratory', u'']]],
           ['Unknown',
            [['Psychiatric', u'Aggression, hypersexualitet, spelmani'],
             ['Nervous system', u'Pl\xf6tsliga s\xf6mnattacker, synkope'],
             ['Vascular', u'Vasospasm i fingrar och t\xe5r'],
             ['Respiratory', u'Andningsbesv\xe4r, andningssvikt'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Benkramper'],
             ['General', u'\xd6kat v\xe4rde f\xf6r blodkreatininfosfokinas']]]],
 '_pages': [5, 7],
 u'_rank': 37,
 u'_type': u'TSFU'}