{'_data': [['Very common',
            [['GI', u'Illam\xe5ende'],
             ['General', u'Perifer svullnad'],
             ['GI', u'Illam\xe5ende'],
             ['Cardiac', u'Hj\xe4rtklaffp\xe5verkan (inklusive bak\xe5tfl\xf6de) och']]],
           ['Common',
            [['Psychiatric', u'Hallucinationer, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Yrsel, dyskinesier'],
             ['Vascular', u'L\xe4geshypotension'],
             ['GI', u''],
             ['GI', u'F\xf6rstoppning, dyspepsi, gastrit, kr\xe4kning'],
             ['General', u''],
             ['Psychiatric', u'F\xf6rvirring, hallucinationer'],
             ['Cardiac', u'Angina pectoris'],
             ['Vascular', u'L\xe4geshypotension'],
             ['GI', u''],
             ['GI', u'Dyspepsi, gastrit, kr\xe4kning'],
             ['General', u'Perifer svullnad'],
             ['Investigations',
              u'S\xe4nkt v\xe4rde f\xf6r hemoglobin, hematokrit och/eller  r\xf6da blodkroppar (> 15 % i f\xf6rh\xe5llande till ursprungsv\xe4rdet)'],
             ['Psychiatric', u'\xd6kad libido'],
             ['Nervous system', u'Huvudv\xe4rk, s\xf6mnighet'],
             ['Cardiac', u'liknande tillst\xe5nd (perikardit och perikardiell  utgjutning)'],
             ['General', u'Asteni'],
             ['Investigations', u'Avvikande resultat i leverfunktionstest']]],
           ['Uncommon',
            [['Vascular', u'Erytromelalgi'],
             ['Respiratory', u'Pleural v\xe4tskeutgjutning, lungfibros'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Psychiatric', u'Vanf\xf6rest\xe4llningar, psykotisk st\xf6rning'],
             ['Hepato', u'Avvikande leverfunktion'],
             ['Skin', u'Utslag'],
             ['General', u'Svullnad, utmattning']]],
           ['Unknown',
            [['Psychiatric', u'Aggression, st\xf6rd impulskontroll: Patologiskt'],
             ['Nervous system', u'Pl\xf6tslig insomning, synkope'],
             ['Vascular', u'Vasospasm i fingrar och t\xe5r'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Kramper i benen'],
             ['Investigations', u'\xd6kad halt av kreatininfosfokinas i blodet']]]],
 '_pages': [5, 7],
 u'_rank': 32,
 u'_type': u'TSFU'}