{'_data': [['Very common',
            [['Nervous system', u'Yrsel/svindel, huvudv\xe4rk'],
             ['GI', u'Buksm\xe4rta/dyspepsi/gastrit, illam\xe5ende'],
             ['General', u'Asteni/utmattning'],
             ['Cardiac', u'Hj\xe4rtklaffp\xe5verkan (inklusive bak\xe5tfl\xf6de) och']]],
           ['Common',
            [['Vascular',
              u'Kabergolin ut\xf6var i allm\xe4nhet en blodtryckss\xe4nkande  effekt hos patienter som l\xe5ngtidsbehandlas; postural hypotension'],
             ['Psychiatric', u'Depression, s\xf6mnst\xf6rningar'],
             ['Nervous system', u''],
             ['Vascular', u'Heta vallningar'],
             ['GI', u''],
             ['GI', u'F\xf6rstoppning, kr\xe4kning'],
             ['Reproductive system', u'Br\xf6stsm\xe4rta'],
             ['General', u''],
             ['Nervous system', u'Yrsel/svindel, huvudv\xe4rk, s\xf6mnighet'],
             ['Cardiac', u'liknande tillst\xe5nd (perikardit och perikardiell  utgjutning)'],
             ['GI', u'Buksm\xe4rta, illam\xe5ende'],
             ['Investigations', u'Asymtomatisk blodtryckss\xe4nkning (> 20 mmHg']]],
           ['Uncommon',
            [['Vascular', u'Vasospasm i fingrar och t\xe5r, svimning'],
             ['Investigations',
              u'Hemoglobinv\xe4rdena har sjunkit hos kvinnor med  amenorr\xe9 under de f\xf6rsta m\xe5naderna efter  menstruationsbl\xf6dningarna'],
             ['Nervous system', u'Parestesier'],
             ['Nervous system', u'\xd6verg\xe5ende hemianopsi, synkope'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['Vascular', u'Heta vallningar'],
             ['Respiratory', u'N\xe4sblod, pleural v\xe4tskeutgjutning, lungfibros'],
             ['GI', u'Kr\xe4kning'],
             ['General', u'Asteni']]],
           ['Rare', [['GI', u'Sm\xe4rtor i epigastriet']]],
           ['Unknown',
            [['Psychiatric', u'Aggressivitet, st\xf6rd impulskontroll: Patologiskt'],
             ['Nervous system', u'Pl\xf6tslig insomning, synkope'],
             ['Eye', u'Synst\xf6rningar']]]],
 '_pages': [6, 8],
 u'_rank': 26,
 u'_type': u'TSFU'}