{'_data': [['Very common',
            [['GI', u'kr\xe4kningar och illam\xe5ende'],
             ['General',
              u'(allvarlig) slemhinneskada Ingen f\xf6rst\xe4rkning av andra 5-fluorouracilinducerade f\xf6rgiftningssymtom (t ex neurotoxicitet). Veckovis behandling'],
             ['GI',
              u'diarr\xe9 med h\xf6gre grad av toxicitet och dehydrering, resulterande sjukhusinl\xe4ggning och \xe4ven d\xf6d.']]],
           ['Uncommon',
            [['General',
              u'feber har observerats efter administrering av kalciumfolinat som injektion. Kombinationsbehandling med 5-fluorouracil: I allm\xe4nhet \xe4r s\xe4kerhetsprofilen beroende av regimen f\xf6r 5-fluorouracil, p\xe5 grund av f\xf6rst\xe4rkt 5-fluorouracilinducerad toxicitet. M\xe5nadsvis behandling']]],
           ['Rare',
            [['Psychiatric', u'insomnia, agitation och depression efter h\xf6ga doser.'],
             ['GI', u'gastrointestina1a st\xf6rningar efter h\xf6ga doser.'],
             ['Nervous system', u'\xf6kad anfallsfrekvens hos epileptiker (se \xe4ven 4.5).']]],
           ['Very rare',
            [['Immune system',
              u'(<0,01%): allergiska reaktioner, inklusive anafylaktoida reaktioner och urtikaria.']]]],
 '_pages': [5, 6],
 u'_rank': 8,
 u'_type': u'LSFU'}