{'_data': [['Common',
            [['Skin',
<<<<<<< HEAD
              u'och <1/10) Kl\xe5da, br\xe4nnande k\xe4nsla i huden, stickande k\xe4nsla i huden, hudirritation, torr hud, erytem, utslag*']]],
           ['Uncommon',
            [['Skin',
              u'(>1/1000 och <1/100) Eksem, kontaktdermatit, f\xf6rs\xe4mrad psoriasis']]],
           ['Very rare',
            [['Metabolism',
              u'Mycket s\xe4llsynt (<1/10 000) Hyperkalcemi, hyperkalciuri F\xf6ljande biverkningar har rapporterats f\xf6r kalcipotriolkr\xe4m, salva och h\xe5rbottenl\xf6sning som erfarenheter efter marknadsintroduktion: \xf6verg\xe5ende f\xf6r\xe4ndringar i hudpigmentering, \xf6verg\xe5ende ljusk\xe4nslighet och \xf6verk\xe4nslighetsreaktion inklusive urtikaria, angio\xf6dem, periorbitalt eller facialt \xf6dem (mycket s\xe4llsynt). Perioral dermatit kan uppst\xe5 i s\xe4llsynta fall. Baserat p\xe5 data efter marknadsintroduktion \xe4r den totala \u201drapporterade andelen biverkningar\u201d mycket s\xe4llsynt, cirka 1 p\xe5 10 000 behandlingar.']]]],
 '_pages': [3, 3],
 u'_rank': 3,
=======
              u'(>1/100 och <1/10) Kl\xe5da, br\xe4nnande k\xe4nsla i huden, stickande k\xe4nsla i huden, hudirritation, torr hud, erytem, utslag*']]],
           ['Uncommon',
            [['Skin',
              u'(>1/1000 och <1/100) Eksem, kontaktdermatit, f\xf6rs\xe4mrad psoriasis *Olika typer av hudutslag har rapporterats, s\xe5som flagning, erytemat\xf6sa, makulopapul\xf6sa och pustul\xf6sa reaktioner.']]],
           ['Very rare',
            [['Metabolism',
              u'Mycket s\xe4llsynt (<1/10 000) Hyperkalcemi, hyperkalciuri F\xf6ljande biverkningar har rapporterats f\xf6r kalcipotriolkr\xe4m, salva och h\xe5rbottenl\xf6sning som erfarenheter efter marknadsintroduktion: \xf6verg\xe5ende f\xf6r\xe4ndringar i hudpigmentering, \xf6verg\xe5ende ljusk\xe4nslighet och \xf6verk\xe4nslighetsreaktion inklusive urtikaria, angio\xf6dem, periorbitalt eller facialt \xf6dem'],
             ['Metabolism',
              u'. Perioral dermatit kan uppst\xe5 i s\xe4llsynta fall. Baserat p\xe5 data efter marknadsintroduktion \xe4r den totala \u201drapporterade andelen biverkningar\u201d mycket s\xe4llsynt, cirka 1 p\xe5 10 000 behandlingar.']]]],
 '_pages': [3, 3],
 u'_rank': 4,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}