{'_data': [['Uncommon', [['Metabolism', u'Hyperkalcemi och hyperkalcuri.']]],
           ['Rare',
            [['GI', u'F\xf6rstoppning, flatulens, illam\xe5ende, buksm\xe4rtor och diarr\xe9.']]],
           ['Very rare',
            [['Metabolism',
              u'ses vanligen enbart vid \xf6verdosering (se avsnitt 4.9) mj\xf6lk-alkali syndrom'],
             ['Skin', u'Kl\xe5da, utslag och urtikaria.']]]],
 '_pages': [2, 3],
 u'_rank': 4,
 u'_type': u'LSFU'}