<<<<<<< HEAD
{'_data': [['Very common',
            [['Blood', u'Leukopeni, neutropeni och agranulocytos'],
             ['Metabolism', u'Hyperkalemi, hypernatremi'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer, onormal leverfunktion'],
             ['Skin', u'Angio\xf6dem, hudutslag, urtikaria, kl\xe5da'],
             ['Musculoskeletal', u'Ryggsm\xe4rtor, artralgi, myalgi'],
             ['Renal', u'Nedsatt njurfunktion, inklusive njursvikt hos']]],
           ['Common',
            [['Infections', u'Luftv\xe4gsinfektion'],
             ['Nervous system', u'Yrsel/vertigo, huvudv\xe4rk'],
             ['Metabolism',
              u'Hyperglykemi, hyperurikemi, elektrolytrubb-  ningar (inklusive hyponatremi och hypokalemi)'],
             ['Nervous system', u'Yrsel, vertigo'],
             ['Renal', u'Glykosuri'],
             ['Investigations', u'F\xf6rh\xf6jda kolesterol- och triglyceridv\xe4rden']]],
           ['Uncommon',
            [['Vascular', u'Postural hypotoni'],
             ['GI',
              u'Anorexi, aptitl\xf6shet, mags\xe4cksirritation, diarr\xe9,  f\xf6rstoppning'],
             ['Skin', u'Hudutslag, urtikaria, fotosensitivitetsreaktioner']]],
           ['Rare',
            [['Blood', u''],
             ['Metabolism', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u'eller hepatit'],
             ['Skin', u''],
             ['Musculoskeletal', u''],
             ['Renal', u'predisponerade patienter (se avsnitt 4.4)'],
             ['Blood',
              u'Leukopeni, neutropeni/agranulocytos,  trombocytopeni, aplastisk anemi, benm\xe4rgs- depression, hemolytisk anemi'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Psychiatric', u'S\xf6mnst\xf6rningar, depression, rastl\xf6shet'],
             ['Nervous system', u'Parestesi'],
             ['Eye', u'\xd6verg\xe5ende dimsyn'],
             ['Cardiac', u'Hj\xe4rtarytmier'],
             ['Vascular', u'Nekrotiserande angit (vaskulit, kutan vaskulit)'],
             ['Respiratory', u'Andningssv\xe5righeter (inklusive pneumonit och  lung\xf6dem)'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Ikterus (intrahepatisk kolestatisk ikterus)'],
             ['Skin',
              u'Toxisk epidermal nekrolys, kutana lupus  erythematosusliknande reaktioner, \xe5teraktivering av kutan lupus erythematosus'],
             ['Musculoskeletal', u'Muskelspasm'],
             ['Renal', u'Renal dysfunktion och interstitiell nefrit'],
             ['Investigations', u'F\xf6rh\xf6jda BUN- och serumkreatininv\xe4rden'],
             ['Investigations', u'']]],
           ['Unknown', [['Eye', u'Akut myopi, akut tr\xe5ngvinkelglaukom']]]],
 '_pages': [8, 10],
 u'_rank': 34,
 u'_type': u'TSFU'}
=======
{'_data': [['Very common', [['Respiratory', u'Magtarmkanalen  ']]],
           ['Common',
            [['Hepato', u'vanliga'], ['Hepato', u'f\xf6rstoppning'], ['Hepato', u'vanliga']]],
           ['Rare',
            [['Blood', u'Metabolism och nutrition Mycket Hyperkalemi, hypernatremi'],
             ['Blood', u'Centrala och perifera Vanliga Yrsel/vertigo, huvudv\xe4rk'],
             ['Respiratory', u'och mediastinum  '],
             ['Hepato',
              u'eller hepatit Hud och subkutan v\xe4vnad Mycket Angio\xf6dem, hudutslag, urtikaria, kl\xe5da'],
             ['Hepato',
              u's\xe4llsynta Muskuloskeletala systemet Mycket Ryggsm\xe4rtor, artralgi, myalgi och bindv\xe4v s\xe4llsynta Njurar och urinv\xe4gar Mycket Nedsatt njurfunktion, inklusive njursvikt hos'],
             ['Hepato',
              u'predisponerade patienter (se avsnitt 4.4) Tabellen nedan visar biverkningar med hydroklortiazid i monoterapi, vanligen med doser p\xe5 25 mg eller h\xf6gre. Organsystem Frekvens Biverkning Blodet och lymfsystemet S\xe4llsynta Leukopeni, neutropeni/agranulocytos, trombocytopeni, aplastisk anemi, benm\xe4rgs depression, hemolytisk anemi Immunsystemet S\xe4llsynta Anafylaktiska reaktioner Metabolism och nutrition Vanliga Hyperglykemi, hyperurikemi, elektrolytrubb ningar (inklusive hyponatremi och hypokalemi) Psykiska st\xf6rningar S\xe4llsynta S\xf6mnst\xf6rningar, depression, rastl\xf6shet Centrala och perifera Vanliga Yrsel, vertigo nervsystemet S\xe4llsynta Parestesi \xd6gon S\xe4llsynta \xd6verg\xe5ende dimsyn'],
             ['Hepato',
              u'Nekrotiserande angit (vaskulit, kutan vaskulit) Andningsv\xe4gar, br\xf6stkorg S\xe4llsynta Andningssv\xe5righeter (inklusive pneumonit och och mediastinum lung\xf6dem) Magtarmkanalen Mindre Anorexi, aptitl\xf6shet, mags\xe4cksirritation, diarr\xe9,'],
             ['Hepato',
              u'Pankreatit Lever och gallv\xe4gar S\xe4llsynta Ikterus (intrahepatisk kolestatisk ikterus) Hud och subkutan v\xe4vnad Mindre Hudutslag, urtikaria, fotosensitivitetsreaktioner'],
             ['Hepato',
              u'Toxisk epidermal nekrolys, kutana lupus erythematosusliknande reaktioner, \xe5teraktivering av kutan lupus erythematosus Muskuloskeletala systemet S\xe4llsynta Muskelspasm och bindv\xe4v Njurar och urinv\xe4gar Vanliga Glykosuri'],
             ['Hepato',
              u'Renal dysfunktion och interstitiell nefrit Allm\xe4nna symtom och/eller Vanliga Svaghet symtom vid S\xe4llsynta Feber administreringsst\xe4llet Unders\xf6kningar Vanliga F\xf6rh\xf6jda kolesterol- och triglyceridv\xe4rden'],
             ['Hepato', u'F\xf6rh\xf6jda BUN- och serumkreatininv\xe4rden'],
             ['Hepato', u'S\xe4llsynta']]],
           ['Unknown',
            [['Hepato',
              u'Akut myopi, akut tr\xe5ngvinkelglaukom Hj\xe4rtat S\xe4llsynta Hj\xe4rtarytmier Blodk\xe4rl Mindre Postural hypotoni']]]],
 '_pages': [8, 10],
 u'_rank': 17,
 u'_type': u'LSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
