{'_data': [['Common',
            [['Infections', u'Luftv\xe4gsinfektion'],
             ['Nervous system', u'Yrsel/svindel, huvudv\xe4rk'],
             ['Metabolism', u'Hyperkalemi'],
             ['Vascular', u'Hypotoni'],
             ['Renal',
              u'Njurfunktionsneds\xe4ttning  inklusive njursvikt hos predisponerade patienter (se avsnitt 4.4)']]],
           ['Very rare',
            [['Blood', u'Leukopeni, neutropeni och  agranulocytos'],
             ['Metabolism', u'Hyperkalemi, hyponatremi'],
             ['GI', u'Illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer,  onormal leverfunktion eller hepatit'],
             ['Skin', u'Angio\xf6dem, hudutslag,  urtikaria, pruritus'],
             ['Musculoskeletal', u'Ryggsm\xe4rta, artralgi,  myalgi'],
             ['Renal',
              u'Njurfunktionsneds\xe4ttning  inklusive njursvikt hos predisponerade patienter (se avsnitt 4.4)'],
             ['Blood', u'Leukopeni, neutropeni och  agranulocytos'],
             ['Metabolism', u'Hyponatremi'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer,  onormal leverfunktion eller hepatit'],
             ['Skin', u'Angio\xf6dem, hudutslag,  urtikaria, pruritus'],
             ['Musculoskeletal', u'Ryggont, artralgi, myalgi']]]],
 '_pages': [5, 7],
 u'_rank': 19,
 u'_type': u'TSFU'}