{'_data': [['Very common',
            [['Blood', u'Leukopeni, neutropeni och agranulocytos'],
             ['Metabolism', u'Hyperkalemi, hypernatremi'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer, onormal leverfunktion'],
             ['Skin', u'Angio\xf6dem, hudutslag, urtikaria, kl\xe5da'],
             ['Musculoskeletal', u'Ryggsm\xe4rtor, artralgi, myalgi'],
             ['Renal', u'Nedsatt njurfunktion, inklusive njursvikt hos']]],
           ['Common',
            [['Infections', u'Luftv\xe4gsinfektion'],
             ['Nervous system', u'Yrsel/vertigo, huvudv\xe4rk'],
             ['Metabolism',
              u'Hyperglykemi, hyperurikemi, elektrolytrubb-  ningar (inklusive hyponatremi och hypokalemi)'],
             ['Nervous system', u'Yrsel, vertigo'],
             ['Renal', u'Glykosuri'],
             ['Investigations', u'F\xf6rh\xf6jda kolesterol- och triglyceridv\xe4rden']]],
           ['Uncommon',
            [['Vascular', u'Postural hypotoni'],
             ['GI',
              u'Anorexi, aptitl\xf6shet, mags\xe4cksirritation, diarr\xe9,  f\xf6rstoppning'],
             ['Skin', u'Hudutslag, urtikaria, fotosensitivitetsreaktioner']]],
           ['Rare',
            [['Blood', u''],
             ['Metabolism', u''],
             ['Respiratory', u''],
             ['GI', u''],
             ['Hepato', u'eller hepatit'],
             ['Skin', u''],
             ['Musculoskeletal', u''],
             ['Renal', u'predisponerade patienter (se avsnitt 4.4)'],
             ['Blood',
              u'Leukopeni, neutropeni/agranulocytos,  trombocytopeni, aplastisk anemi, benm\xe4rgs- depression, hemolytisk anemi'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Psychiatric', u'S\xf6mnst\xf6rningar, depression, rastl\xf6shet'],
             ['Nervous system', u'Parestesi'],
             ['Eye', u'\xd6verg\xe5ende dimsyn'],
             ['Cardiac', u'Hj\xe4rtarytmier'],
             ['Vascular', u'Nekrotiserande angit (vaskulit, kutan vaskulit)'],
             ['Respiratory', u'Andningssv\xe5righeter (inklusive pneumonit och  lung\xf6dem)'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Ikterus (intrahepatisk kolestatisk ikterus)'],
             ['Skin',
              u'Toxisk epidermal nekrolys, kutana lupus  erythematosusliknande reaktioner, \xe5teraktivering av kutan lupus erythematosus'],
             ['Musculoskeletal', u'Muskelspasm'],
             ['Renal', u'Renal dysfunktion och interstitiell nefrit'],
             ['Investigations', u'F\xf6rh\xf6jda BUN- och serumkreatininv\xe4rden'],
             ['Investigations', u'']]],
           ['Unknown', [['Eye', u'Akut myopi, akut tr\xe5ngvinkelglaukom']]]],
 '_pages': [8, 10],
 u'_rank': 34,
 u'_type': u'TSFU'}