{'_data': [['Common', []],
           ['Uncommon',
            [['Reproductive system',
              u'Pruritus, utslag, br\xe4nnande k\xe4nsla, irritation, obehag/sm\xe4rta']]],
           ['Rare',
            [['Immune system',
              u'Allergisk reaktion (synkope, hypotension, dyspn\xe9, urtikaria)']]],
           ['Unknown',
            [['Reproductive system',
              u'Fj\xe4llande hud/exfoliering, bl\xe5sor p\xe5 huden, \xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 3,
 u'_type': u'MSFU'}