{'_data': [['Very common',
            [['Metabolism', u'Anorexi'],
             ['Respiratory', u'Alla grader'],
             ['GI', u'Diarr\xe9, Kr\xe4kningar, Illam\xe5ende, Stomatit, Buksm\xe4rta'],
             ['Skin', u'Palmar plantar erytrodysestesi'],
             ['General', u'Tr\xf6tthet, Asteni Feber, Letargi, Perifera \xf6dem,'],
             ['Blood', u'Neutropeni, Leukopeni, Anemi, Trombocytopeni'],
             ['Metabolism', u'Minskad aptit '],
             ['Nervous system',
              u'Smakrubbning, Parestesi och dysestesi, Perifer neuropati, Perifer k\xe4nselneuropati, Dysgeusi, Huvudv\xe4rk'],
             ['Eye', u'\xd6kad m\xe4ngd t\xe5rv\xe4tska'],
             ['Vascular', u'\xd6dem i nedre extremiteter, trombos'],
             ['Respiratory', u'Halsont, Farynx-dysestesi'],
             ['GI', u'F\xf6rstoppning, Dyspepsi'],
             ['Skin', u'Alopeci, Nagelp\xe5verkan'],
             ['Musculoskeletal', u'Myalgi, Artralgi, Sm\xe4rta i extremiteter'],
             ['General', u'Pyrexi, Svaghet, Letargi, Temperaturintolerans'],
             ['Injury',
              u'\u201d \xe4r frekvensen baserad p\xe5 biverkningar av grad 3-4. Biverkningar har adderats enligt den h\xf6gsta']]],
           ['Common',
            [['Infections', u'Herpesvirusinfektion, Nasofaryngit, Nedre luftv\xe4gsinfektion'],
             ['Blood', u'Neutropeni, Anemi'],
             ['Metabolism', u'Dehydrering, Minskad aptit, Viktnedg\xe5ng'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, Depression'],
             ['Nervous system', u'Huvudv\xe4rk, Letargi, Yrsel, Paraestesi, Dysgeusi'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de, Konjunktivit, \xd6gonirritation'],
             ['Vascular', u'Tromboflebit'],
             ['Respiratory', u'Dyspn\xe9, Epistaxis, Hosta, Rinorr\xe9 Alla grader'],
             ['GI',
              u'Gastrointestinal bl\xf6dning, F\xf6rstoppning, Sm\xe4rta i \xf6vre delen av buken, Dyspepsi, Flatulens, Muntorrhet'],
             ['Hepato', u'Hyperbilirubinemi, Avvikande leverfunktionsv\xe4rden'],
             ['Skin',
              u'Hudutslag, Alopeci, Erytem, Torr hud, Kl\xe5da, Hyperpigmentering, Makul\xf6sa utslag, Hudfj\xe4llning, Dermatit, Rubbning i pigmenteringen, Nagelf\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Sm\xe4rta i extremiteter, Ryggv\xe4rk, Artralgi'],
             ['General', u'Sjukdomsk\xe4nsla, Br\xf6stsm\xe4rta'],
             ['Infections',
              u'Herpes zoster, Urinv\xe4gsinfektion, Oral candidiasis, \xd6vre luftv\xe4gsinfektion, Rinit,'],
             ['Blood', u'Benm\xe4rgsdepression, Febril neutropeni Neutropen feber,'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'Hypokalemi, Hyponatremi, Hypomagnesemi, Hypokalcemi, Hyperglykemi'],
             ['Psychiatric', u'S\xf6mnrubbning, \xc5ngest'],
             ['Nervous system',
              u'Neurotoxicitet, Tremor, Neuralgi, \xd6verk\xe4nslighetsreaktioner, Hypestesi'],
             ['Eye',
              u'Synst\xf6rning, Torra \xf6gon, Sm\xe4rta i \xf6gonen, F\xf6rs\xe4mrad syn, Dimsyn'],
             ['Ear', u'Tinnitus, H\xf6rselneds\xe4ttning'],
             ['Cardiac', u'F\xf6rmaksflimmer, Kardiell ischemi/infarkt'],
             ['Vascular', u'Rodnad, Hypotoni, Hypertensiv kris,'],
             ['Respiratory', u'Hicka, Faryngolaryngeal sm\xe4rta, Dysfoni'],
             ['GI',
              u'\xd6vre gastrointestinal bl\xf6dning, Muns\xe5r, Gastrit, Utsp\xe4nd buk, Gastroesofageal refluxsjukdom, Oral sm\xe4rta, Dysfagi, Rektal bl\xf6dning, Sm\xe4rta i nedre delen av buken, Oral dysestesi, Oral parestesi, Oral hypestesi, Bukbesv\xe4r'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Hyperhidros, Erytemat\xf6sa utslag, Urtikaria, Nattliga svettningar'],
             ['Musculoskeletal',
              u'Sm\xe4rta i k\xe4karna, Muskelkramper, Trismus, Muskelsvaghet'],
             ['Renal', u'Hematuri, Proteinuri, S\xe4nkt kreatinin-clearance, Dysuri'],
             ['General',
              u'Slemhinneinflammation, Sm\xe4rta i extremiteter, V\xe4rk, Frossbrytningar, Br\xf6stsm\xe4rta, Influensaliknande sjukdom, Feber, Infusionsrelaterad reaktion, Reaktion vid injektionsst\xe4llet, Sm\xe4rta vid infusionsst\xe4llet, Sm\xe4rta vid injektionsst\xe4llet'],
             ['Injury', u'Kontusion']]],
           ['Uncommon',
            [['Infections',
              u'Sepsis, Urinv\xe4gsinfektion, Cellulit, Tonsillit, Faryngit, Oral candidos, Influensa, Gastroenterit, Svampinfektion, Infektion, Tandabscess'],
             ['Neoplasms', u'Lipom'],
             ['Blood',
              u'Febril neutropeni, Pancytopeni, Granulocytopeni, Trombocytopeni, Leukopeni, Hemolytisk anemi, F\xf6rh\xf6jt INR (internationellt normaliserat ratio)/f\xf6rl\xe4ngd protrombintid'],
             ['Immune system', u'Hypersensitivitet'],
             ['Metabolism',
              u'Diabetes, Hypokalemi, St\xf6rd aptit, Malnutrition, Hypertriglyceridemi'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, Panikattack, S\xe4nkt st\xe4mningsl\xe4ge, Minskad libido'],
             ['Nervous system',
              u'Afasi, F\xf6rs\xe4mrat minne, Ataxi, Synkop\xe9, Balansrubbning, K\xe4nselrubbning, Perifer neuropati'],
             ['Eye', u'F\xf6rs\xe4mrad synsk\xe4rpa, Diplopi'],
             ['Ear', u'Vertigo, \xd6ronv\xe4rk'],
             ['Cardiac',
              u'Instabil angina, Angina pectoris, Myokardischemi, F\xf6rmaksflimmer, Arytmi, Takykardi, Sinustakykardi, Hj\xe4rtklappning'],
             ['Vascular',
              u'Djup ventrombos, Hypertoni, Petekier, Hypotoni, Blodvallning, Perifer k\xf6ldk\xe4nsla'],
             ['Respiratory',
              u'Lungemboli, Pneumotorax, Hemoptys, Astma, Anstr\xe4ngningsutl\xf6st dyspn\xe9 Allvarlig och/eller livshotande (grad 3-4) eller bed\xf6md som medicinskt relevant'],
             ['GI',
              u'Tarmobstruktion, Ascites, Enterit, Gastrit, Dysfagi, Sm\xe4rta i nedre delen av buken, Esofagit, Bukbesv\xe4r, Gastro-esofageal reflux-sjukdom, Kolit, Blod i avf\xf6ringen'],
             ['Hepato', u'Gulsot'],
             ['Skin',
              u'Hudulceration, Hudutslag, Urtikaria, Fotosensitivitets-reaktioner, Palmarerytem, Svullet ansikte, Purpura'],
             ['Musculoskeletal',
              u'Ledsvullnad, Skelettsm\xe4rta, Ansiktssm\xe4rta, Muskuloskeletal stelhet, Muskelsvaghet'],
             ['Renal',
              u'Hydronefros, Urininkontinens, Hematuri, Nokturi, F\xf6rh\xf6jt blodkreatinin'],
             ['Reproductive system', u'Vaginal bl\xf6dning'],
             ['General',
              u'\xd6dem, Frossbrytningar, Influensaliknande sjukdom, Stelhet, F\xf6rh\xf6jd kroppstemperatur'],
             ['Injury', u'Bl\xe5sor, \xd6verdosering']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 13],
 u'_rank': 67,
 u'_type': u'MSFU'}