{'_data': [['Very common',
            [['Metabolism', u'Anorexi'],
             ['GI', u'Diarr\xe9, kr\xe4kningar, illam\xe5ende, stomatit, buksm\xe4rta'],
             ['Skin', u'Hand-fot-syndromet (palmar-plantar erytrodysestesi)'],
             ['General', u'Tr\xf6tthet, asteni'],
             ['Blood', u'Neutropeni, leukopeni, anemi, neutropen feber, trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Minskad aptit'],
             ['Nervous system',
              u'Smakrubbning, parestesi och dysestesi, perifer neuropati, perifer k\xe4nselneuropati, dysgeusi, huvudv\xe4rk'],
             ['Eye', u'\xd6kad m\xe4ngd t\xe5rv\xe4tska'],
             ['Vascular', u'\xd6dem i nedre extremiteter, trombos'],
             ['Respiratory', u'Halsont, farynx-dysestesi'],
             ['GI', u'F\xf6rstoppning, dyspepsi'],
             ['Skin', u'Alopeci, nagelp\xe5verkan'],
             ['Musculoskeletal', u'Myalgi, artralgi, sm\xe4rta i extremiteter  muskelsvaghet'],
             ['General', u'Pyrexi, svaghet, letargi, temperaturintolerans'],
             ['Injury', u'Kontusion']]],
           ['Common',
            [['Infections', u'Herpesvirus infektion, nasofaryngit, nedre luftv\xe4gsinfektion'],
             ['Blood', u'Neutropeni, anemi'],
             ['Metabolism', u'Dehydrering, minskad aptit, viktnedg\xe5ng'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, depression'],
             ['Nervous system',
              u'Huvudv\xe4rk, letargi, yrsel, paraestesi, dysgeusi (smakrubbning)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de, konjunktivit, \xf6gonirritation'],
             ['Vascular', u'Tromboflebit'],
             ['Respiratory', u'Dyspn\xe9, epistaxis, hosta, rinorr\xe9'],
             ['GI',
              u'Gastrointestinal bl\xf6dning, f\xf6rstoppning, sm\xe4rta i \xf6vre delen av buken, dyspepsi, flatulens, muntorrhet'],
             ['Hepato', u'Hyperbilirubinemi, avvikande leverfunktionsv\xe4rden'],
             ['Skin',
              u'Hudutslag, alopeci, erytem, torr hud, kl\xe5da, hyperpigmentering, makul\xf6sa utslag, hudfj\xe4llning, dermatit, rubbning i pigmenteringen, nagelf\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Sm\xe4rta i extremiteter, ryggv\xe4rk, artralgi'],
             ['General',
              u'Feber, letargi, perifera \xf6dem, sjukdomsk\xe4nsla, br\xf6stsm\xe4rta'],
             ['Infections',
              u'Herpes zoster, urinv\xe4gsinfektion, oral candidiasis, \xf6vre luftv\xe4gsinfektion, rinit, influensa,'],
             ['Blood', u'Benm\xe4rgsdepression, febril neutropeni'],
             ['Metabolism',
              u'Hypokalemi, hyponatremi, hypomagnesemi, hypokalcemi, hyperglykemi'],
             ['Psychiatric', u'S\xf6mnrubbning, \xe5ngest'],
             ['Nervous system',
              u'Neurotoxicitet, tremor, neuralgi, \xf6verk\xe4nslighetsreaktioner, hypestesi'],
             ['Eye',
              u'Synst\xf6rning, torra \xf6gon, sm\xe4rta i \xf6gonen, f\xf6rs\xe4mrad syn, dimsyn'],
             ['Cardiac', u'F\xf6rmaksflimmer, myokardischemi/infarkt'],
             ['Vascular', u'Rodnad, hypotoni, hypertensiv kris,'],
             ['Respiratory', u'Hicka, faryngolaryngeal sm\xe4rta, dysfoni'],
             ['GI',
              u'\xd6vre gastrointestinal bl\xf6dning, muns\xe5r, gastrit, utsp\xe4nd buk, gastroesofageal refluxsjukdom, oral sm\xe4rta, dysfagi, rektal bl\xf6dning, sm\xe4rta i nedre delen av buken, oral dysestesi, oral parestesi, oral hypestesi,'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Hyperhidros, erytemat\xf6sa utslag, urtikaria, nattliga svettningar'],
             ['Musculoskeletal', u'Sm\xe4rta i k\xe4karna, muskelkramper, trismus,'],
             ['Renal', u'Hematuri, proteinuri, s\xe4nkt kreatinin-clearance, dysuri'],
             ['General',
              u'Slemhinneinflammation, sm\xe4rta i extremiteter, v\xe4rk, frossbrytningar, br\xf6stsm\xe4rta, influensaliknande sjukdom, feber, infusionsrelaterad reaktion, reaktion vid injektionsst\xe4llet, sm\xe4rta vid infusionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Infections',
              u'Sepsis, urinv\xe4gsinfektion, cellulit, tonsillit, faryngit, oral candidiasis, influensa, gastroenterit, svampinfektion, infektion, tandabscess'],
             ['Neoplasms', u'Lipom'],
             ['Blood',
              u'Febril neutropeni, pancytopeni, granulocytopeni, trombocytopeni, leukopeni, hemolytisk anemi, f\xf6rh\xf6jt INR (internationellt normaliserat ratio)/f\xf6rl\xe4ngd protrombintid'],
             ['Immune system', u'Hypersensitivitet'],
             ['Metabolism',
              u'Diabetes, hypokalemi, st\xf6rd aptit, malnutrition, hypertriglyceridemi'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, panikattack, s\xe4nkt st\xe4mningsl\xe4ge, minskad libido'],
             ['Nervous system',
              u'Afasi, f\xf6rs\xe4mrat minne, ataxi, synkop\xe9, balansrubbning, k\xe4nselrubbning, perifer neuropati'],
             ['Eye', u'F\xf6rs\xe4mrad synsk\xe4rpa, diplopi'],
             ['Cardiac',
              u'Instabil angina, angina pectoris, myokardischemi, f\xf6rmaksflimmer, arytmi, takykardi, sinus-takykardi, hj\xe4rtklappning'],
             ['Vascular',
              u'Djup ventrombos, hypertoni, petekier, hypotoni, blodvallning, perifer k\xf6ldk\xe4nsla'],
             ['Respiratory',
              u'Lungemboli, pneumotorax, hemoptys, astma, anstr\xe4ngningsutl\xf6st dyspn\xe9'],
             ['GI',
              u'Tarmobstruktion, ascites, enterit, gastrit, dysfagi, sm\xe4rta i nedre delen av buken, esofagit, bukbesv\xe4r, gastro-esofageal refluxsjukdom, kolit, blod i avf\xf6ringen'],
             ['Hepato', u'Gulsot'],
             ['Skin',
              u'Hudulceration, hudutslag, urtikaria, fotosensitivitets-reaktion er, palmarerytem, svullet ansikte, purpura'],
             ['Musculoskeletal',
              u'Ledsvullnad, skelettsm\xe4rta, ansiktssm\xe4rta, muskuloskeletal stelhet, muskelsvaghet'],
             ['Renal',
              u'Hydronefros, urininkontinens, hematuri, nokturi, f\xf6rh\xf6jt blodkreatinin'],
             ['Reproductive system', u'Vaginal bl\xf6dning'],
             ['General',
              u'\xd6dem, frossbrytningar, influensaliknande sjukdom, stelhet, f\xf6rh\xf6jd kroppstemperatur'],
             ['Injury', u'Bl\xe5sor, \xf6verdosering']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 13],
 u'_rank': 63,
 u'_type': u'MSFU'}