{'_data': [['Very common',
            [['Metabolism', u'Anorexi'],
             ['Nervous system', u'Alla grader'],
             ['GI', u'Diarr\xe9, Kr\xe4kningar, Illam\xe5ende, Stomatit, Buksm\xe4rta'],
             ['Skin', u'Hand-fot-syndromet (palmar-plantar erytrodysestesi) Alla grader'],
             ['General', u'Tr\xf6tthet, Asteni'],
             ['Blood', u'+Neutropeni, +leukopeni, trombocytopeni'],
             ['Metabolism', u'Minskad aptit'],
             ['Nervous system',
              u'Smakrubbning, parestesi och dysestesi, perifer neuropati, dysgeusi, huvudv\xe4rk'],
             ['Eye', u'\xd6kad m\xe4ngd t\xe5rv\xe4tska'],
             ['Vascular', u'\xd6dem i nedre extremiteter, trombos'],
             ['GI', u'F\xf6rstoppning, dyspepsi'],
             ['Skin', u'Alopeci, nagelp\xe5verkan'],
             ['Musculoskeletal', u'Myalgi, artralgi, sm\xe4rta i extremiteter'],
             ['Renal', u'Alla grader'],
             ['General', u'Pyrexi, svaghet, +letargi, temperaturintolerans'],
             ['Injury', u'Kontusion']]],
           ['Common',
            [['Infections', u'Herpesvirus infektion, Nasofaryngit, Nedre luftv\xe4gsinfektion'],
             ['Metabolism', u'Dehydrering, Minskad aptit, Viktnedg\xe5ng'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, Depression'],
             ['Nervous system',
              u'Huvudv\xe4rk, Letargi, Yrsel, Paraestesi, Dysgeusi (smakrubbning) Alla grader'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de, Konjunktivit, \xd6gonirritation'],
             ['Vascular', u'Tromboflebit'],
             ['Respiratory', u'Dyspn\xe9, Epistaxis, Hosta, Rinorr\xe9'],
             ['GI',
              u'Gastrointestinal bl\xf6dning, F\xf6rstoppning, Sm\xe4rta i \xf6vre delen av buken, Dyspepsi, Flatulens, Muntorrhet'],
             ['Hepato', u'Hyperbilirubinemi, Avvikande leverfunktionsv\xe4rden'],
             ['Skin',
              u'Hudutslag, Alopeci, Erytem, Torr hud, Kl\xe5da, Hyperpigmentering, Makul\xf6sa utslag, Alla grader Hudfj\xe4llning, Dermatit, Rubbning i pigmenteringen, Nagelf\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Sm\xe4rta i extremiteter, Ryggv\xe4rk, Artralgi'],
             ['General',
              u'Feber, Letargi, Perifera \xf6dem, Sjukdomsk\xe4nsla, Br\xf6stsm\xe4rta'],
             ['Infections',
              u'Herpes zoster, urinv\xe4gsinfektion, oral candidiasis, \xf6vre luftv\xe4gsinfektion, rinit, influensa, +infektion, oral'],
             ['Blood', u'Benm\xe4rgsdepression, +febril'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Hypokalemi, hypomagnesemi, hypokalcemi, hyperglykemi'],
             ['Psychiatric', u'S\xf6mnrubbning, \xe5ngest'],
             ['Nervous system',
              u'Neurotoxicitet, tremor, neuralgi, \xf6verk\xe4nslighetsreaktioner,'],
             ['Eye',
              u'Synst\xf6rning, torra \xf6gon, sm\xe4rta i \xf6gonen, f\xf6rs\xe4mrad syn, dimsyn'],
             ['Ear', u'Tinnitus, h\xf6rselneds\xe4ttning'],
             ['Cardiac', u'F\xf6rmaksflimmer, hj\xe4rtinfarkt'],
             ['Vascular', u'Rodnad, hypotoni, hypertensiv kris,'],
             ['GI',
              u'\xd6vre gastrointestinal bl\xf6dning, muns\xe5r, gastrit, utsp\xe4nd buk, gastroesofageal refluxsjukdom, oral sm\xe4rta, dysfagi, rektal bl\xf6dning, sm\xe4rta i nedre delen av buken, oral dysestesi, oral parestesi, oral hypestesi, bukbesv\xe4r'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Hyperhidros, erytemat\xf6sa utslag, urtikaria, nattliga svettningar'],
             ['Musculoskeletal',
              u'Sm\xe4rta i k\xe4karna, muskelkramper, trismus, muskelsvaghet'],
             ['Renal',
              u'Hematuri, proteinuri, s\xe4nkt kreatinin-clearance, dysuri Alla grader'],
             ['General',
              u'Slemhinneinflammation, sm\xe4rta i extremiteter, v\xe4rk, frossbrytningar, br\xf6stsm\xe4rta, influensaliknande sjukdom, +feber, infusionsrelaterad reaktion, reaktion vid injektionsst\xe4llet, sm\xe4rta vid infusionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Infections',
              u'Sepsis, Urinv\xe4gsinfektion, Cellulit, Tonsillit, Faryngit, Oral candidiasis, Influensa, Gastroenterit, Svampinfektion, Infektion, Tandabscess'],
             ['Neoplasms', u'Lipom'],
             ['Immune system', u'Hypersensitivitet'],
             ['Metabolism',
              u'Diabetes, Hypokalemi, St\xf6rd aptit, Malnutrition, Hypertriglyceridemi'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, Panikattack, S\xe4nkt st\xe4mningsl\xe4ge, Minskad libido'],
             ['Nervous system',
              u'Afasi, F\xf6rs\xe4mrat minne, Ataxi, Synkop\xe9, Balansrubbning, K\xe4nselrubbning, Allvarlig och/eller livshotande (grad 3-4) eller bed\xf6md medicinskt relevant Perifer neuropati'],
             ['Eye', u'F\xf6rs\xe4mrad synsk\xe4rpa, Diplopi'],
             ['Ear', u'Vertigo, \xd6ronv\xe4rk'],
             ['Cardiac',
              u'Instabil angina, Angina pectoris, Myokardischemi, F\xf6rmaksflimmer, Arytmi, Takykardi, Sinus-takykardi, Hj\xe4rtklappning'],
             ['Vascular',
              u'Djup ventrombos, Hypertoni, Petekier, Hypotoni, Blodvallning, Perifer k\xf6ldk\xe4nsla'],
             ['Respiratory',
              u'Lungemboli, Pneumotorax, Hemoptys, Astma, Anstr\xe4ngningsutl\xf6st dyspn\xe9'],
             ['GI',
              u'Tarmobstruktion, Ascites, Enterit, Gastrit, Dysfagi, Sm\xe4rta i nedre delen av buken, Esofagit, Bukbesv\xe4r, Gastro-esofageal refluxsjukdom, Kolit, Blod i avf\xf6ringen'],
             ['Hepato', u'Gulsot'],
             ['Skin',
<<<<<<< HEAD
              u'Hudulceration, Hudutslag, Urtikaria, Fotosensitivitets-reakti oner, Palmarerytem, Svullet ansikte, Allvarlig och/eller livshotande (grad 3-4) eller bed\xf6md medicinskt relevant Purpura'],
=======
              u'Hudulceration, Hudutslag, Urtikaria, Fotosensitivitets-reaktioner, Palmarerytem, Svullet ansikte, Allvarlig och/eller livshotande (grad 3-4) eller bed\xf6md medicinskt relevant Purpura'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Musculoskeletal',
              u'Ledsvullnad, Skelettsm\xe4rta, Ansiktssm\xe4rta, Muskuloskeletal stelhet, Muskelsvaghet'],
             ['Renal',
              u'Hydronefros, Urininkontinens, Hematuri, Nokturi, F\xf6rh\xf6jt blodkreatinin'],
             ['Reproductive system', u'Vaginal bl\xf6dning'],
             ['General',
              u'\xd6dem, Frossbrytningar, Influensaliknande sjukdom, Stelhet, F\xf6rh\xf6jd kroppstemperatur'],
             ['Injury', u'Bl\xe5sor, \xd6verdosering']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 15],
 u'_rank': 63,
 u'_type': u'MSFU'}