{'_data': [['Very common',
            [['Infections',
              u'Nasofaryngit, bronkit, \xf6vre luftv\xe4gsinfektioner, urinv\xe4gsinfektioner'],
             ['Endocrine', u'Hypotyreos'],
             ['Metabolism', u'Minskad aptit, hypokalcemi'],
             ['Psychiatric', u'Insomni, depression'],
             ['Nervous system', u'Huvudv\xe4rk, parestesi, dysestesi, yrsel'],
             ['Eye',
              u'Dimsyn, korneala strukturf\xf6r\xe4ndringar (inklusive korneala avlagringar och kornealopacitet)'],
             ['Cardiac', u'F\xf6rl\xe4ngning av QTc-intervallet (*) (**)'],
             ['Vascular', u'Hypertoni Akut hypertoni,'],
             ['Respiratory', u'N\xe4sbl\xf6dning, hemoptys, pneumonit'],
             ['GI', u'Buksm\xe4rta, diarr\xe9, illam\xe5ende, kr\xe4kningar, dyspepsi'],
             ['Hepato', u'Kolelitiasis'],
             ['Skin',
              u'Ljusk\xe4nslighetsreaktion, utslag och andra hudreaktioner (inklusive akne, torr hud, dermatit, pruritus), nagelsjukdomar'],
             ['Renal', u'Proteinuri, nefrolitiasis'],
             ['General', u'Asteni, extrem tr\xf6tthet, sm\xe4rta, \xf6dem'],
             ['Investigations', u'F\xf6rl\xe4ngt QTc-intervall']]],
           ['Common',
            [['Infections',
              u'Pneumoni, sepsis, influensa, cystit, sinuit, laryngit, follikulit, furunkel, svampinfektion, pyelonefrit'],
             ['Metabolism',
              u'Hypokalemi, hyperkalcemi, hyperglykemi, dehydrering, hyponatremi'],
             ['Psychiatric', u'Oro'],
             ['Nervous system',
              u'Tremor, letargi, medvetsl\xf6shet, balansst\xf6rningar, dysgeusi'],
             ['Eye',
              u'Synf\xf6rs\xe4mring, haloeffekt, fotopsi, glaukom, konjunktivit, \xf6gontorrhet, keratopati'],
             ['Cardiac', u'Hj\xe4rtsvikt, akut'],
             ['Vascular', u'ischemiska cerebrovaskul\xe4ra tillst\xe5nd'],
             ['GI',
              u'Kolit, muntorrhet, stomatit, dysfagi, f\xf6rstoppning, gastrit, gastrointestinal bl\xf6dning'],
             ['Skin', u'Palmoplantar erytrodysestesisyndrom, alopeci'],
             ['Renal', u'Dysuri, hematuri, njursvikt, pollakuri, urintr\xe4ngningar'],
             ['General', u'Pyrexi F\xf6rs\xe4mrad'],
             ['Investigations',
              u'F\xf6rh\xf6jda serumkoncentrationer av ALAT och ASAT, viktminskning, f\xf6rh\xf6jt kreatinin i blod']]],
           ['Uncommon',
            [['Infections',
              u'Appendicit, stafylokockinfektion, divertikulit, cellulit, bukv\xe4ggsabscess'],
             ['Metabolism', u'Malnutrition'],
             ['Nervous system', u'V\xe5ldsamma muskelryckningar, klonus, hj\xe4rn\xf6dem'],
             ['Eye', u'Katarakt, ackommodationsst\xf6rnin gar'],
             ['Cardiac',
              u'hj\xe4rtsvikt, frekvens-och rytmst\xf6rningar, ledningsst\xf6rningar i hj\xe4rtat, ventrikul\xe4r arytmi och hj\xe4rtstillest\xe5nd'],
             ['Respiratory', u'Andningssvikt, aspirationspneumoni'],
             ['GI', u'Pankreatit, peritonit, ileus, tarmperforation, fekal inkontinens'],
             ['Skin', u'Bull\xf6s dermatit'],
             ['Renal', u'Kromaturi, anuri'],
             ['General', u's\xe5rl\xe4kning'],
             ['Investigations', u'Hemoglobin\xf6kning, \xf6kad serumamylas']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 9],
 u'_rank': 38,
 u'_type': u'MSFU'}