{'_data': [['Very common',
            [['Blood', u'Trombocytopeni, neutropeni,  leukopeni, anemi.'],
             ['GI', u'Kr\xe4kning, illam\xe5ende,  buksm\xe4rta.'],
             ['Investigations',
              u'Minskat kreatininclearance,  \xf6kat blodurea, \xf6kade alkaliska fosfataser, \xf6kat aspartataminotransferas, onormala leverfunktionstester, minskat natrium i blodet, minskat kalium, kalcium och magnesium i blodet,']]],
           ['Common',
            [['Infections', u'Infektioner*'],
             ['Blood', u'Hemorrage*'],
             ['Immune system', u'\xd6verk\xe4nslighet, anafylaktoid  reaktion.'],
             ['Nervous system',
              u'Perifer neuropati, parestesi,  minskade senreflexer,  sensoriskast\xf6rningar, dysgeusi.'],
             ['Eye', u'Synst\xf6rningar, s\xe4llsynta fall  av synf\xf6rlust.'],
             ['Ear', u'Ototoxicitet.'],
             ['Cardiac', u'Kardiovaskul\xe4r sjukdom*'],
             ['Respiratory', u'Andningsbesv\xe4r, interstitiell  lungsjukdom, bronkospasm.'],
             ['GI', u'Diarr\xe9, f\xf6rstoppning,  slemhinnebesv\xe4r.'],
             ['Skin', u'Alopeci, hudbesv\xe4r.'],
             ['Musculoskeletal', u'Muskuloskeletala sjukdom.'],
             ['Renal', u'Urogenital sjukdom.'],
             ['Investigations',
              u'\xd6kat bilirubin och kreatinin i  blodet, \xf6kad m\xe4ngd urinsyra i blodet.']]],
           ['Unknown',
            [['Neoplasms', u'Behandlingsrelaterade  sekund\xe4ra maligniteter.'],
             ['Blood', u'Benm\xe4rgssvikt, febril  neutropeni, hemolytiskt-uremiskt syndrom.'],
             ['Metabolism', u'Dehydrering, anorexi,  hyponatremi.'],
             ['Nervous system', u'Cerebrovaskul\xe4r h\xe4ndelse*'],
             ['Cardiac', u'Hj\xe4rtsvikt*'],
             ['Vascular', u'Emboli*, hyptertoni,  hypotoni.'],
             ['GI', u'Stomatit.'],
             ['Skin', u'Urtikaria, utslag, erytem,  pruritus.']]]],
 '_pages': [6, 9],
 u'_rank': 24,
 u'_type': u'TSFU'}