{'_data': [['Very common',
            [['Blood',
              u'Trombocyt-nadir under 50 x 10 /l och leukocyt-nadir under 2 x 10 /l. Anemi och s\xe4nkt Hb-v\xe4rde till <95 g/l. Fall av febril neutropeni har rapporterats. Trombocyt- och leukocyttal har vanligtvis \xe5terg\xe5tt till baslinjen efter 28 dagar. \xc5terh\xe4mtning av trombocyter och vita blodkroppar tar ibland upp till 5 respektive 6 veckor. I s\xe5dana fall b\xf6r behandlingen med karboplatin inte upprepas f\xf6rr\xe4n trombocyttalet \xe4r >100 x 10 /l och leukocyttalet \xe4r >4 x 10 Benm\xe4rgsh\xe4mningen \xe4r allvarligare och mer l\xe5ngvarig hos patienter med nedsatt njurfunktion, hos patienter som tidigare genomg\xe5tt intensivbehandling samt hos patienter som har ett nedsatt allm\xe4ntillst\xe5nd eller \xe4r \xf6ver 65 \xe5r, \xe4n hos patienter utan dessa riskfaktorer. Benm\xe4rgsh\xe4mningen \xe4r vanligtvis reversibel och icke-kumulativ, f\xf6rutsatt att karboplatin anv\xe4nds i enlighet med doseringsrekommendationerna. I vissa fall kan det bli n\xf6dv\xe4ndigt med erytrocyttransfusion.'],
             ['Ear',
              u'H\xf6rselst\xf6rningar utanf\xf6r frekvensomr\xe5det f\xf6r normal konversation, med h\xf6rself\xf6rlust inom h\xf6gfrekvensomr\xe5det (4000 - 8000 Hz).'],
             ['GI',
              u'Illam\xe5ende med eller utan kr\xe4kningar. Gastrointestinala sm\xe4rtor. Patienterna b\xf6rjade kr\xe4kas cirka sex timmar efter administreringen av karboplatin. Kr\xe4kningarna varade en relativt kort tid och avtog vanligtvis efter 24 timmar. Kr\xe4kningar verkar vara vanligare hos patienter som behandlats tidigare, s\xe4rskilt om de behandlats med cisplatin. Illam\xe5ende och kr\xe4kningar kan vanligtvis kontrolleras med antiemetika och kan ofta undvikas genom f\xf6rebyggande administrering av denna typ av l\xe4kemedel.'],
             ['Hepato',
              u'En vanligtvis reversibel f\xf6rh\xf6jning av leverenzymer (inklusive alkalisk fosfatas och aspartataminotransferas) efter administrering av karboplatin i de doser som rekommenderas h\xe4r och som inte klart har kunnat h\xe4nf\xf6ras till maligniteten. F\xf6r\xe4ndringarna som konstaterats i laboratorieresultat har emellertid inte lett till att behandlingen av n\xe5gon patient har avbrutits.'],
             ['Renal',
              u'St\xf6rd njurfunktion innefattande en vanligtvis reversibel \xf6kning av serumkreatinin och/eller \xf6kat ureakv\xe4ve i blodet, om karboplatin administreras utan hydrering. Hyperurikemi \u2013 f\xf6rh\xf6jd serumurinsyra \u2013 kan effektivt minskas med administrering av allopurinol.'],
             ['General',
              u'Asteni Elektrolytf\xf6rlust (magnesium, kalium, natrium, i mindre vanliga fall kalcium). Elektrolytf\xf6rlusterna \xe4r minimala och orsakar vanligtvis inte n\xe5gra kliniska symtom.']]],
           ['Common',
            [['Blood',
              u'Infektioner och/eller bl\xf6dningar, \xe4ven sepsis. I enskilda fall kan dessa komplikationer leda till ett livshotande tillst\xe5nd.'],
             ['Immune system',
              u'Allergiska reaktioner (ex. erytemat\xf6sa utslag, oklar feber, pruritus, urtikaria).'],
             ['Nervous system',
              u'Perifera polyneuropatier, vanligtvis i form av stickningar, domningar och/eller minskade djupa senreflexer. Dessa biverkningar \xe4r mer uttalade och vanligare hos patienter \xf6ver 65 \xe5r och hos patienter som tidigare behandlats med cisplatin. Parestesi till f\xf6ljd av behandling med cisplatin kan ibland ytterligare f\xf6rsv\xe5ras av efterf\xf6ljande behandling med karboplatin.'],
             ['Eye',
              u'Inflammation i synnerven med synrubbningar och \xe4ven blindhet som f\xf6ljd. Detta \xe4r vanligtvis associerat med h\xf6ga doser hos patienter med nedsatt njurfunktion.'],
             ['Ear',
              u'H\xf6rselst\xf6rningar inom frekvensomr\xe5det f\xf6r normal konversation, huvudsakligen orsakat av tinnitus. Hos patienter vars h\xf6rselorgan redan skadats av cisplatin kan behandling med karboplatin ibland orsaka ytterligare f\xf6rs\xe4mring av h\xf6rseln. Kliniskt signifikant neds\xe4ttning av h\xf6rseln har intr\xe4ffat hos barn som givits h\xf6gre karboplatindoser \xe4n de rekommenderade i kombination med andra ototoxiska l\xe4kemedel.'],
             ['GI', u'Diarr\xe9, f\xf6rstoppning.'],
             ['Hepato', u'F\xf6rh\xf6jt serumbilirubin.'],
             ['Renal',
              u'Minskad kreatininclearance till under 60 ml/min. Njurfunktionsst\xf6rningar var vanligare och mer uttalade hos patienter som redan hade f\xf6rs\xe4mrad njurfunktion d\xe5 behandlingen p\xe5b\xf6rjades \xe4n hos patienter med normal njurfunktion. F\xf6rs\xe4mrad njurfunktion \xe4r mer trolig hos patienter som tidigare upplevt nefrotoxicitet som resultat av behandling med cisplatin. Det \xe4r f\xf6r n\xe4rvarande os\xe4kert om ytterligare f\xf6rs\xe4mring av organfunktion kan undvikas genom hydreringsprogram n\xe4r det g\xe4ller patienter som redan har f\xf6rs\xe4mrad njurfunktion. Vid m\xe5ttliga st\xf6rningar av njurarnas funktion (kreatininclearance < 60 till 30 ml/min) m\xe5ste karboplatindosen minskas p\xe5 grund av en minskning i den glomerul\xe4ra filtrationen eller behandlingen med karboplatin avbrytas. (Se avsnitt 4.2 Dosering och administreringss\xe4tt.) Karboplatin kontraindikeras i de fall den glomerul\xe4ra filtrationshastigheten \xe4r < 30 ml/min.'],
             ['General',
              u'H\xe5ravfall, sjukdomsk\xe4nsla, feber och frossa, mukosit, kraftl\xf6shet och smakf\xf6r\xe4ndringar.']]],
           ['Uncommon',
            [['Blood',
              u'Myelodysplastiska syndrom och akut myeloid leukemi efter cytostatisk kombinationsbehandling d\xe4r karboplatin ing\xe5r.'],
             ['Nervous system',
              u'St\xf6rningar i det centrala nervsystemet som ofta kan h\xe4nf\xf6ras till behandling med antiemetika.'],
             ['GI', u'Kr\xe4kningar som inte kan kontrolleras med l\xe4kemedel.'],
             ['General',
              u'Influensaliknande symtom. Reaktioner vid injektionsst\xe4llet som svullnad, rodnad och sm\xe4rta.']]],
           ['Rare',
            [['Immune system',
              u'Anafylaxi (inklusive anafylaktisk chock), angio-\xf6dem och anafylaktoida reaktioner (inkluderande bronkospasm, urtikaria, rodnad, takykardi, hypotension, ansikts\xf6dem, dyspn\xe9 och v\xe4sljud). Dessa reaktioner kan kontrolleras med antihistaminer, adrenalin och/eller glukokortikoider. Reaktionerna \xe4r liknande de som observeras efter behandling med andra l\xe4kemedel inneh\xe5llande platina och kan uppkomma inom ett par minuter. Incidensen av allergiska reaktioner kan \xf6ka vid tidigare exponering av platinainneh\xe5llande l\xe4kemedel och det finns rapporter om korsallergi med andra platina l\xe4kemedel. Allergiska reaktioner har dock observerats vid initial behandling med karboplatin. Patienten b\xf6r noggrannt observeras f\xf6r eventuella allergiska reaktioner och behandlas med adekvat terapi.'],
             ['GI', u'Anorexi.']]],
           ['Very rare',
            [['Blood', u'Akut promyelocytisk leukemi.'],
             ['Hepato',
              u'Fulminant levernekros efter administrering av h\xf6ga doser av karboplatin (270 mg/m fem dagar i f\xf6ljd). Kraftigt f\xf6rh\xf6jda leverfunktionsv\xe4rden efter mycket h\xf6ga doser av karboplatin och efter autologa benm\xe4rgstransplantationer.'],
             ['General',
              u'Hemolytiskt uremiskt syndrom. Kardiovaskul\xe4ra (hj\xe4rtsvikt, emboli) och cerebrovaskul\xe4ra komplikationer (stroke); karboplatins p\xe5verkan \xe4r emellertid os\xe4ker. Fall av hypertoni har rapporterats. I djurstudier uppvisar karboplatin embryotoxiska och teratogena egenskaper. I cellkulturer p\xe5visades mutagenitet och kromosomavvikelser. Baserat p\xe5 dessa r\xf6n m\xe5ste antagandet bli att karboplatin har viss karcinogen potential. Lungfibros har rapporterats, manifesterad av tryck \xf6ver br\xf6stet och dyspn\xe9. Detta skall beaktas om tillst\xe5nd av pulmonell \xf6verk\xe4nslighet har uteslutits (se Immunsystemet ovan).']]],
           ['Unknown',
            [['Blood',
              u'Dosbegr\xe4nsande biverkning av karboplatin \xe4r den vanligtvis reversibla h\xe4mningen av benm\xe4rgsfunktionen.']]]],
 '_pages': [6, 9],
 u'_rank': 25,
 u'_type': u'LSFU'}