{'_data': [['Very common',
            [['Blood',
              u'Myelosuppression \xe4r karboplatins dosbegr\xe4nsande toxicitet. Myelosuppressionen kan vara sv\xe5rare och mer l\xe5ngvarig hos patienter med nedsatt njurfunktion, omfattande tidigare behandling, d\xe5ligt allm\xe4ntillst\xe5nd och en \xe5lder \xf6ver 65 \xe5r. Myelosuppressionen f\xf6rv\xe4rras ocks\xe5 av kombinationsbehandling med karboplatin och andra substanser som \xe4r myelosuppressiva. Myelosuppressionen \xe4r vanligtvis reversibel och inte kumulativ n\xe4r karboplatin anv\xe4nds som enda l\xe4kemedel och i de doser och administreringsfrekvenser som rekommenderas. Vid h\xf6gsta tolererade dos av karboplatin, administrerat som enda l\xe4kemedel, f\xf6rekommer trombocytopeni med ett nadir f\xf6r trombocytantal p\xe5 mindre \xe4n 50 x 10 /l hos omkring en tredjedel av patienterna. Nadir f\xf6rekommer normalt sett mellan dag 14 och 21, och normaliseras inom 35 dagar efter att behandlingen p\xe5b\xf6rjats. Dessutom har leukopeni f\xf6rekommit hos ca 20 % av patienterna, men dess normalisering fr\xe5n dagen f\xf6r nadir (dag 14 \u2013 28) kan ske l\xe5ngsammare och intr\xe4ffar vanligen inom 42 dagar efter att behandlingen har p\xe5b\xf6rjats. Neutropeni med granulocytantal under 1 x 10 /l f\xf6rekommer hos ungef\xe4r en femtedel av patienterna. Hemoglobinv\xe4rden under 9,5 mg/100 ml har observerats hos 48 % av patienterna med normala utg\xe5ngsv\xe4rden. Anemi f\xf6rekommer ofta och kan vara kumulativ.'],
             ['Blood',
              u'Njurtoxiciteten \xe4r vanligtvis inte dosbegr\xe4nsande hos patienter som f\xe5r karboplatin, inte heller kr\xe4ver den f\xf6rebyggande \xe5tg\xe4rder s\xe5som hydrering med h\xf6ga v\xe4tskevolymer eller forcerad diures. Trots det kan f\xf6rh\xf6jda niv\xe5er av urin\xe4mne i blodet eller kreatinin i serum f\xf6rekomma.'],
             ['Metabolism',
              u'S\xe4nkta niv\xe5er av serumelektrolyter (natrium, magnesium, kalium och kalcium) har rapporterats efter behandling med karboplatin, men har inte rapporterats vara tillr\xe4ckligt kraftiga f\xf6r att ge kliniska tecken eller symtom.'],
             ['GI',
              u'Illam\xe5ende utan kr\xe4kningar f\xf6rekommer hos omkring en fj\xe4rdedel av de patienter som f\xe5r karboplatin. Kr\xe4kningar har rapporterats hos \xf6ver h\xe4lften av patienterna och omkring en tredjedel av dessa lider av kraftigt illam\xe5ende. Illam\xe5endet och kr\xe4kningarna f\xf6rsvinner vanligtvis inom 24 timmar efter behandling och svarar vanligtvis p\xe5 (och kan f\xf6rbyggas med) antiemetisk medicinering. En fj\xe4rdedel av patienterna drabbas inte av illam\xe5ende eller kr\xe4kningar. Kr\xe4kningar som inte kunde kontrolleras med l\xe4kemedel observerades hos endast 1 % av patienterna. Kr\xe4kningar tycks f\xf6rekomma oftare hos tidigare behandlade patienter, s\xe4rskilt hos patienter som f\xf6rbehandlats med cisplatin. Sm\xe4rtsamma gastrointestinala st\xf6rningar f\xf6rekom hos 17 % av patienterna.'],
             ['Nervous system',
              u'Avvikande leverfunktionstester (vanligtvis lindriga till m\xe5ttliga) har rapporterats med karboplatin hos omkring en tredjedel av patienterna med normala utg\xe5ngsv\xe4rden. Niv\xe5n av alkaliskt fosfatas \xe4r oftare f\xf6rh\xf6jd \xe4n SGOT, SGPT eller totalbilirubin. Flertalet av dessa avvikelser normaliseras spontant under behandlingen.'],
             ['Nervous system',
              u'Hyperurikemi har observerats hos omkring en fj\xe4rdedel av patienterna. Niv\xe5erna av urinsyra i serum kan s\xe4nkas med hj\xe4lp av allopurinol. Asteni.']]],
           ['Common',
            [['Blood',
              u'Bl\xf6dningskomplikationer, vanligtvis mindre, har ocks\xe5 rapporterats.'],
             ['Blood',
              u'Nedsatt njurfunktion, definierad som en minskning av kreatininclearance till under 60 ml/min, kan ocks\xe5 observeras. Nefrotoxicitetens incidens och sv\xe5righetsgrad kan \xf6ka hos patienter som har nedsatt njurfunktion f\xf6re karboplatinbehandling. Det \xe4r inte klarlagt om ett l\xe4mpligt hydreringsprogram kan \xf6vervinna en s\xe5dan effekt, men dosreduktion eller avbrytande av behandlingen kr\xe4vs vid m\xe5ttlig f\xf6r\xe4ndring av njurfunktionen (kreatininclearance 30 \u2013 59 ml/min). Karboplatin \xe4r kontraindicerat hos patienter med en kreatininclearance p\xe5 < 30 ml/min.'],
             ['GI', u'Diarr\xe9 (6 %), f\xf6rstoppning (4 %), mukosit.'],
             ['Immune system',
              u'Allergiska reaktioner mot karboplatin har rapporterats hos mindre \xe4n 2 % av patienterna, t.ex. hudutslag, urtikaria, erytem, feber utan uppenbar orsak eller kl\xe5da.'],
             ['Nervous system',
              u'Incidensen av perifera neuropatier efter behandling med karboplatin \xe4r 6 %. Hos flertalet patienter \xe4r neurotoxiciteten begr\xe4nsad till parestesi och minskade djupa senreflexer. Dessa biverkningars frekvens och intensitet \xf6kar hos \xe4ldre patienter och hos dem som tidigare har behandlats med cisplatin. Parestesi som f\xf6rekommer innan karboplatinbehandlingen p\xe5b\xf6rjas, s\xe4rskilt om den har samband med tidigare cisplatinbehandling, kan kvarst\xe5 eller f\xf6rv\xe4rras under behandling med karboplatin.'],
             ['Nervous system',
              u'Alopeci. Allm \xe4 nna symtom och/eller symtom vid administreringsst \xe4 llet'],
             ['Nervous system', u'Sjukdomsk\xe4nsla.']]],
           ['Uncommon',
            [['Neoplasms',
              u'Sekund\xe4ra maligniteter har rapporterats efter administrering av karboplatin som enda l\xe4kemedel eller vid kombinationsbehandling (orsakssamband inte fastst\xe4llt).'],
             ['Blood', u'Infekti\xf6sa komplikationer har rapporterats enstaka g\xe5nger.'],
             ['Nervous system',
              u'Symtom fr\xe5n centrala nervsystemet har rapporterats, men de tycks dock ofta kunna h\xe4nf\xf6ras till samtidig antiemetisk behandling. gon \xd6'],
             ['Nervous system',
              u'Feber och frossbrytningar utan tecken p\xe5 infektion, reaktioner p\xe5 injektionsst\xe4llet s\xe5som sm\xe4rta, erytem, svullnad, urtikaria och nekros.']]],
           ['Rare',
            [['Blood',
              u'Fall av febril neutropeni har rapporterats. Enstaka fall av livshotande infektioner och bl\xf6dningar har f\xf6rekommit. Njurar och urinv \xe4 gar'],
             ['Metabolism', u'Fall av hyponatremi har rapporterats.'],
             ['GI', u'Smakf\xf6r\xe4ndring. Fall av anorexi har rapporterats.'],
             ['Immune system',
              u'Anafylaxi, anafylaktisk chock, angioneurotiskt \xf6dem och anafylaktoida reaktioner, inklusive bronkospasm, urtikaria och ansikts\xf6dem har f\xf6rekommit (se varningar).'],
             ['Nervous system',
              u'\xd6verg\xe5ende synst\xf6rningar, ibland inkluderande \xf6verg\xe5ende synf\xf6rlust, har i s\xe4llsynta fall rapporterats vid platinabehandling. Detta har vanligtvis samband med h\xf6gdosbehandling hos patienter med nedsatt njurfunktion. \xe4 rtat Hj'],
             ['Nervous system',
              u'Kraftigt nedsatt leverfunktion (inklusive akut levernekros) har rapporterats efter administrering av h\xf6gre karboplatindoser \xe4n de rekommenderade. Hud och subkutan v \xe4 vnad'],
             ['Nervous system', u'Hemolytiskt uremiskt syndrom.']]],
           ['Very rare',
            [['Neoplasms',
              u'F\xf6rekomst av akut promyelocytisk leukemi 6 \xe5r efter monoterapi med karboplatin och tidigare radioterapi har rapporterats.'],
             ['Nervous system',
              u'Kardiovaskul\xe4ra h\xe4ndelser (hj\xe4rtsvikt, emboli) liksom cerebrovaskul\xe4ra h\xe4ndelser (apoplexi) har rapporterats i enstaka fall (orsakssamband med karboplatin inte fastst\xe4llt). Enstaka fall av hypertoni har rapporterats. Lever och gallv \xe4 gar']]]],
 '_pages': [4, 7],
 u'_rank': 26,
 u'_type': u'LSFU'}