{'_data': [['Very common',
            [['Blood',
<<<<<<< HEAD
              u'Benm\xe4rgsh\xe4mning \xe4r den dosbegr\xe4nsande toxiciteten f\xf6r karboplatin. Benm\xe4rgsh\xe4mningen kan vara allvarligare eller mer l\xe5ngvarig hos patienter med nedsatt njurfunktion, patienter som tidigare genomg\xe5tt omfattande behandling, patienter med d\xe5ligt allm\xe4ntillst\xe5nd och som \xe4r \xe4ldre \xe4n 65 \xe5r. Benm\xe4rgsh\xe4mningen f\xf6rsv\xe5ras ocks\xe5 av samtidig behandling med karboplatin och andra benm\xe4rgsh\xe4mmande medel. Benm\xe4rgsh\xe4mningen \xe4r vanligen reversibel och inte kumulativ n\xe4r karboplatin anv\xe4nds som monoterapi i rekommenderade doser och rekommenderad administrationsfrekvens. Vid de h\xf6gsta tolererade doserna med karboplatin som monoterapi, f\xf6rekommer trombocytopeni, med nadir f\xf6r trombocytantalet p\xe5 under 50 x 10 /1iter, hos cirka en tredjedel av patienterna. Nadir ses normalt dag 14 till 21, med \xe5terh\xe4mning inom 35 dagar fr\xe5n behandlingsstart. Leukopeni har upptr\xe4tt hos ca 20 % av patienterna, men \xe5terh\xe4mtningen fr\xe5n nadir (dag 14-28) kan vara l\xe5ngsammare och intr\xe4der normalt inom 42 dagar fr\xe5n behandlingsstart. Neutropeni med granulocytantal under 1 x 10 /liter f\xf6rekommer hos ca 20 % av patienter. Hemoglobinv\xe4rden under 9,5 mg/100 ml har observerats hos 48 % av patienter med normala ursprungsv\xe4rden. Anemi f\xf6rekommer ofta och kan vara kumulativ.'],
             ['Ear',
              u'Subklinisk neds\xe4ttning av h\xf6rself\xf6rm\xe5gan inom h\xf6gfrekvensomr\xe5det (4 000-8 000 Hz). H\xf6rselneds\xe4ttning fastst\xe4lld genom audiogram har rapporterats hos 15 % av karboplatinbehandlade patienter.'],
=======
              u'Benm\xe4rgsh\xe4mning \xe4r den dosbegr\xe4nsande toxiciteten f\xf6r karboplatin. Benm\xe4rgsh\xe4mningen kan vara allvarligare eller mer l\xe5ngvarig hos patienter med nedsatt njurfunktion, patienter som tidigare genomg\xe5tt omfattande behandling, patienter med d\xe5ligt allm\xe4ntillst\xe5nd och som \xe4r \xe4ldre \xe4n 65 \xe5r. Benm\xe4rgsh\xe4mningen f\xf6rsv\xe5ras ocks\xe5 av samtidig behandling med karboplatin och andra benm\xe4rgsh\xe4mmande medel. Benm\xe4rgsh\xe4mningen \xe4r vanligen reversibel och inte kumulativ n\xe4r karboplatin anv\xe4nds som monoterapi i rekommenderade doser och rekommenderad administrationsfrekvens. Vid de h\xf6gsta tolererade doserna med karboplatin som monoterapi, f\xf6rekommer trombocytopeni, med nadir f\xf6r trombocytantalet p\xe5 under 50 x 10 /1iter, hos cirka en tredjedel av patienterna. Nadir ses normalt dag 14 till 21, med \xe5terh\xe4mning inom 35 dagar fr\xe5n behandlingsstart. Leukopeni har upptr\xe4tt hos ca 20 % av patienterna, men \xe5terh\xe4mtningen fr\xe5n nadir (dag 14 28) kan vara l\xe5ngsammare och intr\xe4der normalt inom 42 dagar fr\xe5n behandlingsstart. Neutropeni med granulocytantal under 1 x 10 /liter f\xf6rekommer hos ca 20 % av patienter. Hemoglobinv\xe4rden under 9,5 mg/100 ml har observerats hos 48 % av patienter med normala ursprungsv\xe4rden. Anemi f\xf6rekommer ofta och kan vara kumulativ.'],
             ['Ear',
              u'Subklinisk neds\xe4ttning av h\xf6rself\xf6rm\xe5gan inom h\xf6gfrekvensomr\xe5det (4 000- 8 000 Hz). H\xf6rselneds\xe4ttning fastst\xe4lld genom audiogram har rapporterats hos 15 % av karboplatinbehandlade patienter.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Ear',
              u'Illam\xe5ende utan kr\xe4kningar f\xf6rekommer hos ca 25 % av patienter som f\xe5r karboplatin. Kr\xe4kningar har rapporterats hos ca h\xe4lften av patienterna och ca 1/3 av dem drabbas av allvarlig emes. Illam\xe5ende och kr\xe4kningar uppkommer i allm\xe4nhet inte f\xf6rr\xe4n 6 till 12 timmar efter administrering av karboplatin och f\xf6rsvinner vanligen inom 24 timmar. Symtomen kan i normala fall behandlas (och f\xf6rebyggas) med antiemetika. Hos 25 % av patienterna f\xf6rekommer inte illam\xe5ende eller kr\xe4kningar. Kr\xe4kningar som inte kunde kontrolleras med mediciner f\xf6rekom endast hos 1 % av patienterna. Kr\xe4kningar verkar vara vanligare f\xf6rekommande hos tidigare behandlade patienter, s\xe4rskilt n\xe4r de behandlats med cisplatin. Sm\xe4rtsamma mag-tarmbesv\xe4r f\xf6rekom hos 17 % av patienterna.'],
             ['Renal',
              u'Njurtoxicitet begr\xe4nsar normalt inte doseringen hos patienter som f\xe5r karboplatin och kr\xe4ver inte heller f\xf6rebyggande \xe5tg\xe4rder som h\xf6gt v\xe4tskeintag eller forcerad diures. F\xf6rh\xf6jda niv\xe5er av urinsyra och ureakv\xe4ve i blodet samt serumkreatinin kan \xe4nd\xe5 f\xf6rekomma.'],
             ['Metabolism',
              u'S\xe4nkta serumelektrolytv\xe4rden (natrium, magnesium, kalium och kalcium) har rapporterats efter karboplatinbehandling, men har inte angetts vara allvarliga nog att orsaka kliniska tecken eller symtom.'],
             ['Metabolism',
              u'Hyperurikemi har observerats hos ca 25 % av patienterna. Urinsyrahalten i serum kan minskas med allopurinol. Asteni.'],
             ['Metabolism',
              u'F\xf6r\xe4ndringar i leverfunktionstester (vanligen milda till m\xe5ttliga) har rapporterats med karboplatin hos ca 1/3 av patienter med normala ursprungsv\xe4rden. F\xf6rh\xf6jda niv\xe5er av alkaliska fosfataser f\xf6rekommer oftare \xe4n SGOT, SGPT eller total bilirubin. Huvuddelen av dessa f\xf6r\xe4ndringar \xe5terg\xe5r spontant under behandlingen.']]],
           ['Common',
            [['Blood',
              u'Hemorragiska komplikationer, vanligen milda, har ocks\xe5 rapporterats.'],
             ['Nervous system',
              u'F\xf6rekomsten av perifer neuropati efter karboplatinbehandling uppg\xe5r till 6 %. Hos de flesta patienter begr\xe4nsas neurotoxiciteten till parestesier och f\xf6rs\xe4mrade djupa senreflexer. F\xf6rekomsten och intensiteten av dessa biverkningar \xf6kar hos \xe4ldre patienter och patienter som tidigare behandlats med cisplatin. Parestesier som upptr\xe4der f\xf6re karboplatinbehandling, s\xe4rskilt om de \xe4r kopplade till tidigare cisplatinbehandling, kan best\xe5 eller f\xf6rv\xe4rras under karboplatinbehandling (se avsnitt 4.4, Varningar och f\xf6rsiktighet).'],
             ['Ear',
              u'Klinisk ototoxicitet. Kliniska symtom f\xf6rekommer endast hos 1 % av patienterna, vilket i de flesta fall yttrar sig i form av tinnitus. H\xf6rselneds\xe4ttningen kan best\xe5 eller f\xf6rv\xe4rras hos patienter som utvecklat h\xf6rselsneds\xe4ttning p\xe5 grund av tidigare cisplatinbehandling. Kliniskt signifikant h\xf6rselneds\xe4ttning rapporteras ha intr\xe4ffat hos barn som f\xe5tt h\xf6gre karboplatindoser \xe4n rekommenderat i kombination med andra ototoxiska l\xe4kemedel. Mage och tarm'],
             ['Ear', u'Diarr\xe9 (6 %), f\xf6rstoppning (4 %), mukosit.'],
             ['Renal',
              u'Neds\xe4ttning av njurfunktionen, som visar sig genom att kreatininclearance minskar till v\xe4rden under 60 ml/min, kan ocks\xe5 f\xf6rekomma. F\xf6rekomsten och sv\xe5righetsgraden av nefrotoxicitet kan \xf6ka hos patienter som har nedsatt njurfunktion f\xf6re behandling. Risken f\xf6r nedsatt njurfunktion \xe4r st\xf6rre hos patienter som tidigare visat nefrotoxicitet vid cisplatinbehandling. Det \xe4r oklart om denna effekt kan \xf6vervinnas med l\xe4mplig hydratisering, men vid mild neds\xe4ttning av njurfunktionen (kreatininclearance 41-59 ml/min) eller allvarlig neds\xe4ttning (kreatininclearance 21-40 ml/min) m\xe5ste dosen justeras eller behandlingen avbrytas. Karboplatin kontraindiceras f\xf6r patienter med kreatininclearance p\xe5 eller under 20 ml/min.'],
             ['Skin', u'Alopeci.'],
             ['Metabolism',
              u'Sjukdomsk\xe4nsla, n\xe4sselutslag, influensaliknande symtom, erytemat\xf6sa utslag, pruritus (kl\xe5da).'],
             ['Metabolism',
              u'Allergiska reaktioner p\xe5 karboplatin har rapporterats hos f\xe4rre \xe4n 2 % av patienter, bl.a. utslag, urtikaria, erytemat\xf6sa utslag och feber utan p\xe5visad orsak eller pruritus. Dessa reaktioner liknar de reaktioner som har observerats efter administrering av andra l\xe4kemedel inneh\xe5llande platina och b\xf6r hanteras med l\xe4mplig st\xf6dbehandling.']]],
           ['Uncommon',
            [['Blood', u'Infektioner har rapporterats i enstaka fall.'],
             ['Nervous system',
              u'Centralnerv\xf6sa symtom har rapporterats, men de verkar ofta anses ha orsakats av konkomitant antiemetikabehandling.'],
             ['Metabolism',
              u'Sekund\xe4r malignitet (bl.a. promyelocytisk leukemi som uppkom sex \xe5r efter behandling med karboplatin som monoterapi och tidigare str\xe5lning) har rapporterats efter behandling med karboplatin som monoterapi eller i kombinationsbehandling (orsakssamband med karboplatin har inte p\xe5visats). Allm\xe4nna besv\xe4r och besv\xe4r vid administreringsomr\xe5det'],
             ['Metabolism',
              u'Feber och frossa utan tecken p\xe5 infektion, reaktioner vid injektionsomr\xe5det, bl.a. sm\xe4rta, erytem, svullnad, n\xe4sselutslag och nekros.']]],
           ['Rare',
            [['Blood',
              u'Febril neutropeni har rapporterats i n\xe5gra fall. I enstaka fall har livshotande infektioner och bl\xf6dningar f\xf6rekommit.'],
             ['Eye',
              u'\xd6verg\xe5ende synrubbningar i samband med platinabehandling, t.ex. \xf6verg\xe5ende synf\xf6rlust, rapporteras i s\xe4llsynta fall. Dessa besv\xe4r uppkommer vanligen vid h\xf6gdosbehandling av patienter med nedsatt njurfunktion. Inflammation i synnerven har rapporterats efter introduktion p\xe5 marknaden.'],
             ['Ear', u'Smakf\xf6r\xe4ndringar. Fall av anorexi har rapporterats.'],
             ['Metabolism',
              u'Fall av hyponatremi har rapporterats. Godartade, elakartade och ospecificerade tum\xf6rer (bl.a. cystor och polyper)'],
             ['Metabolism', u'Hemolytiskt uremiskt syndrom. Immunsystem'],
             ['Metabolism',
              u'Anafylaxi, anafylaktisk chock, angio\xf6dem och anafylaktoida reaktioner som bronkospasm, n\xe4sselutslag, ansikts\xf6dem och ansiktsrodnad, dyspn\xe9, hypotoni, yrsel, pipljud vid andning och takykardi har f\xf6rekommit (se avsnitt 4.4). Dessa reaktioner liknade de som observerats i samband med cisplatinbehandling, men i ett f\xe5tal fall s\xe5gs ingen korsreaktivitet. Hepatobili\xe4ra besv\xe4r'],
             ['Metabolism',
              u'Allvarlig leversvikt (bl.a. akut levernekros) har rapporterats efter administrering av doser som var h\xf6gre \xe4n de rekommenderade doserna.']]],
           ['Very rare',
            [['Respiratory',
              u'Pulmonell fibros som visar sig genom tryck \xf6ver br\xf6stet och dyspn\xe9, vilket b\xf6r beaktas om pulmonell \xf6verk\xe4nslighet har uteslutits (se Allm\xe4nna symtom nedan).']]]],
 '_pages': [6, 8],
 u'_rank': 27,
 u'_type': u'LSFU'}