{'_data': [['Common',
            [['Psychiatric', u'nedst\xe4mdhet f\xf6r\xe4ndrat hum\xf6r nedsatt libido'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'buksm\xe4rta illam\xe5ende'],
             ['Skin', u'Akne'],
             ['Reproductive system',
              u'sm\xe4rta i br\xf6sten \xf6mhet i br\xf6sten vaginalbl\xf6dning oregelbunden menstruation, amenorr\xe9'],
             ['Investigations', u'vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'vaginal'],
             ['Metabolism', u'v\xe4tske-retention'],
             ['Nervous system', u'migr\xe4n'],
             ['GI', u'kr\xe4kningar diarr\xe9'],
             ['Skin', u'alopeci'],
             ['Reproductive system', u'br\xf6stf\xf6r-storing dysmenorr\xe9, ovariecysta'],
             ['General', u'tr\xf6tthet'],
             ['Investigations', u'f\xf6rh\xf6jt blodtryck']]],
           ['Rare',
            [['Infections', u'fokal nodul\xe4r'],
             ['Immune system', u'hypersensitivitet'],
             ['Metabolism', u'nedsatt insulinuts\xf6ndring glukosintolerans'],
             ['Psychiatric', u'\xf6kad libido f\xf6rlust av libido'],
             ['Eye', u'intolerans mot kontaktlinser nedsatt t\xe5rfl\xf6de'],
             ['Cardiac', u'akut myokardinfarkt'],
             ['Vascular', u'ven\xf6s emboli lungemboli'],
             ['Hepato', u'gulsot, kolelitiasis, onormal leverfunktion'],
             ['Skin',
              u'utslag urtikaria erythema multiforme erythema nodusum kloasma kl\xe5da fotosensitivitets-reaktion.'],
             ['Reproductive system', u'br\xf6stsekretion vaginalflytning.'],
             ['Investigations', u'viktminskning, f\xf6rh\xf6jt blodsocker']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 11],
 u'_rank': 25,
 u'_type': u'MSFU'}