{'_data': [['Common', [['Nervous system', u'huvudv\xe4rk'], ['GI', u'illam\xe5ende, diarr\xe9']]],
           ['Uncommon',
            [['Infections', u'candidiasis (oral), underlivsinfektion'],
             ['Blood',
              u'eosinofili, falskt positivt Coombs test*, minskat hemoglobin, f\xf6rl\xe4ngd protrombintid, \xf6kat INR (International Normalized Ratio)'],
             ['Nervous system', u'dysguesi'],
             ['Metabolism', u'anorexi'],
             ['Respiratory', u'n\xe4st\xe4ppa, dyspn\xe9'],
             ['GI',
              u'gastrit, kr\xe4kning, buksm\xe4rta, f\xf6rstoppning, torr mun, dyspepsi, flatulens, avf\xf6ringsinkontinens'],
             ['Hepato', u'hyperbilirubinemi*, f\xf6rh\xf6jt ASAT, f\xf6rh\xf6jt ALAT'],
             ['Skin', u'hos barn bl\xf6jdermatit'],
             ['Renal',
              u'dysuri hos barn: hematuri nedsatt njurfunktion*, toxisk nefropati*, renal glukosuri*, ketonuri*']]],
           ['Rare',
            [['Infections', u'Clostridium difficile-kolit'],
             ['Blood',
              u'leukopeni, trombocytemi, aplastisk anemi, hemolytisk anemi, hemorragisk sjukdom, pancytopeni, neutropeni, agranulocytos'],
             ['Nervous system', u'konvulsioner'],
             ['Hepato', u'f\xf6rh\xf6jt LDH']]],
           ['Very rare',
            [['Nervous system', u'parestesier, somnolens hos barn: hyperkinesi'],
             ['Ear', u'vertigo'],
             ['Psychiatric', u'hos barn agitation, insomnia'],
             ['General', u'tr\xf6tthet hos barn: irritabilitet, frossa']]],
           ['Unknown',
            [['Infections', u'superinfektion'],
             ['Immune system',
              u'serumsjuka, \xf6verk\xe4nslighetsreaktioner inklusive anafylaktisk reaktion, bronkospasm, utslag, urtikaria, fotosensitivitetsreaktion, pruritus, angio\xf6dem, Stevens-Johnsons syndrom, erythema multiforme och toxisk epidermal nekrolys'],
             ['Nervous system', u'afasi'],
             ['Psychiatric', u'psykotiska tillst\xe5nd'],
             ['GI', u'melena'],
             ['Hepato', u'hepatobili\xe4r sjukdom, gulsot']]]],
 '_pages': [3, 5],
 u'_rank': 25,
 u'_type': u'LSFU'}