{'_data': [['Very common',
            [['Nervous system', u'och '],
             ['General', u'I.m. administ ration; Sm\xe4rta p\xe5 injektions st\xe4llet']]],
           ['Common',
            [['GI', u'Illam\xe5en Kr\xe4knin g Magont Diarr\xe9'],
             ['Renal',
              u'Tempor \xe4r \xf6kning av serumkr eatinin (speciell t n\xe4r det f\xf6rskrivs tillsam-mans med amino-gl ykosider ) och serumur ea'],
             ['General',
              u'Feber Inflam-mationer p\xe5 injektion s-st\xe4llet, inklusive flebiter/ trombo-f lebiter']]],
           ['Uncommon',
            [['Blood', u'Leukopeni Eusinofili Trombo-cy topeni (se avsnitt 4.4)'],
             ['Immune system', u'Jarisch-Her xheimer* reaktion'],
             ['Nervous system', u'Kramper (se avsnitt 4.4)'],
             ['GI', u'Aptitl\xf6shet'],
             ['Hepato',
              u'\xd6kning av lever-enzy mer (ASAT, ALAT, LDH, gamma-GT och /eller alkaliskt fosfatas) och/eller bilirubin'],
             ['Skin', u'Utslag Kl\xe5da N\xe4ssel-utsl ag']]],
           ['Rare',
            [['Blood',
              u'Granylocyto peni Agranulocyt os och neutropeni Hemolytisk anemi (se avsnitt 4.4)'],
             ['Nervous system',
              u'Encefalopati (dvs p\xe5verkan p\xe5 medvetandet, onormala r\xf6relser (se avsnitt 4.4) yrsel och tr\xf6tthet (efter administrerin g av h\xf6ga doser)']]],
           ['Very rare',
            [['GI', u'Pseudome kolit (se avsnitt 4.4)'],
             ['Renal', u'Akut interstitiell nefrit']]],
           ['Unknown',
            [['Immune system',
              u'Anafylaktisk chock (se avsnitt 4.4) Anafylaktiska reaktioner Angio\xf6dem Bronkospasm'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Arytmier (efter snabb bolusinfusion via en central venkateter)'],
             ['Hepato', u'Ikterus, hepatit*'],
             ['Skin',
              u'Erythema multiforme, exudativum Stevens Johnsons syndrom Toxisk epidermal nekrolys (se avsnitt 4.4)']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 20,
 u'_type': u'MSFU'}