{'_data': [['Very common', [['General', u'Sm\xe4rta vid injektionsst \xe4llet']]],
           ['Common', []],
           ['Uncommon',
            [['Blood', u'Leukopeni Eosinofili Trombo-cytopeni'],
             ['Immune system', u'Jarisch-Herxheimer s reaktion'],
             ['Nervous system', u'Kramper (se avsnitt 4.4)'],
             ['GI', u'Diarr\xe9'],
             ['Hepato',
              u'F\xf6rh\xf6jda niv\xe5er av leverenzym er (ALAT, ASAT, LDH, gamma-GT och/eller alkaliska fosfataser) och/eller bilirubin'],
             ['Skin', u'Utslag Kl\xe5da Urtikaria'],
             ['Renal',
              u'Minskad njurfunktio n/ Kreatinin-\xf6kning (s\xe4rskilt vid samtidig f\xf6rskrivnin g av aminoglyko sider)'],
             ['General',
              u'Feber Inflammato riska reaktioner vid injektions-st\xe4llet, inklusive flebit/ trombo-flebit']]],
           ['Rare', []],
           ['Very rare', []],
           ['Unknown',
            [['Infections', u'Super-infektion (se avsnitt 4.4)'],
             ['Blood', u'Neutropeni Agranulo-cytos (se avsnitt 4.4) Hemolytisk anemi'],
             ['Immune system',
              u'Anafylaktiska reaktioner Angio\xf6dem Bronkospasm Anafylaktisk chock'],
             ['Nervous system',
              u'Huvudv\xe4rk Yrsel Encefalopati (t.ex. f\xf6rs\xe4mrad medvetande-grad, onormala r\xf6relser) (se avsnitt 4.4)'],
             ['Cardiac', u'Arytmi efter snabb bolusinfusion genom central venkateter'],
             ['GI',
              u'Illam\xe5ende Kr\xe4kningar Buksm\xe4rta Pseudo-membran\xf6s kolit (se avsnitt 4.4)'],
             ['Hepato', u'Hepatit* (ibland med gulsot)'],
             ['Skin',
              u'Erythema multiforme Stevens-Johnsons syndrom Toxisk epidermal nekrolys* (se avsnitt 4.4)'],
             ['Renal', u'Interstitiell nefrit']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 18,
 u'_type': u'MSFU'}