{'_data': [['Common',
            [['Blood', u'Eosinofili Trombocytos'],
             ['Vascular', u'Flebit eller tromboflebit vid intraven\xf6s administrering'],
             ['GI', u'Diarr\xe9'],
             ['Hepato',
              u'\xd6verg\xe5ende f\xf6rh\xf6jda v\xe4rden av ett eller flera leverenzymer'],
             ['Skin', u'Makulopapul\xf6st eller urtikariellt utslag'],
             ['General', u'Sm\xe4rta och/eller inflammation efter intramuskul\xe4r injektion'],
             ['Investigations', u'Positivt Coombs-test']]],
           ['Uncommon',
            [['Infections', u'Candidiasis (inklusive vaginit och torsk i munh\xe5lan)'],
             ['Blood', u'Neutropeni Leukopeni Trombocytopeni'],
             ['Nervous system', u'Huvudv\xe4rk Yrsel'],
             ['GI',
              u'Antibiotika -associerad diarr\xe9 och kolit (se avsnitt 4.4) Buksm\xe4rta Illam\xe5ende Kr\xe4kningar'],
             ['Skin', u'Kl\xe5da'],
             ['Renal',
              u'\xd6verg\xe5ende f\xf6rh\xf6jda v\xe4rden av blodurea, blodureakv\xe4ve (BUN) och/eller serumkreatinin'],
             ['General', u'Feber']]],
           ['Very rare', [['Renal', u'Interstitiell nefrit Akut njursvikt']]],
           ['Unknown',
            [['Blood', u'Agranulocytos Hemolytisk anemi Lymfocytos'],
             ['Immune system',
              u'Anafylaxi (inklusive bronkialspasm och/eller hypotoni) (se avsnitt 4.4)'],
             ['Nervous system', u'Neurologiska sequelae Parestesi'],
             ['GI', u'Smakf\xf6r\xe4ndring'],
             ['Hepato', u'Gulsot'],
             ['Skin',
              u'Toxisk epidermal nekrolys Stevens-Johnsons syndrom Erythema multiforme Angio\xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 21,
 u'_type': u'MSFU'}