{'_data': [['Common',
            [['Respiratory', u'Dyspn\xe9*, hosta*'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner Anafylaktiska reaktioner'],
             ['Immune system', u'Urticaria/angio\xf6dem*, kl\xe5da*, hudutslag*']]],
           ['Uncommon',
            [['Cardiac', u'Takykardi*, cyanos*'],
             ['Vascular', u'Blodvallning*, hypotoni*'],
             ['GI', u'Kr\xe4kning, illam\xe5ende, magkramper, diarr\xe9'],
             ['Musculoskeletal',
              u'Artralgi, ryggv\xe4rk* Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Musculoskeletal',
              u'Obehag vid infusionsst\xe4llet, sveda vid infusionsst\xe4llet, svullnad vid infusionsst\xe4llet, steril abscess vid injektionsst\xe4llet, obehag i br\xf6stet*, feber, stelhet, tr\xf6tthet Symptom som tyder p\xe5 \xf6verk\xe4nslighet (markerade med * i ovanst\xe5ende tabell) har noterats hos ungef\xe4r 3% av patienterna. Dessa symptom har uppkommit under eller kort tid efter infusionerna.. Dessa symtom svarar i allm\xe4nhet p\xe5 behandling med antihistaminer och/eller kortikosteroider. Patienter b\xf6r r\xe5das att avbryta infusionen med medicinen och ta kontakt med l\xe4kare om dessa symptom intr\xe4ffar.']]]],
 '_pages': [4, 5],
 u'_rank': 8,
 u'_type': u'LSFU'}