{'_data': [['Very common',
            [['Psychiatric', u'Onormala dr\xf6mmar, insomnia.'],
             ['Nervous system', u'Huvudv\xe4rk.'],
             ['GI', u'Illam\xe5ende.']]],
           ['Common',
            [['Metabolism', u'aptit.'],
             ['Nervous system', u'Somnolens, yrsel, dysgeusi.'],
             ['GI',
              u'Kr\xe4kning, f\xf6rstoppning, diarr\xe9, uppsv\xe4lld buk, magbesv\xe4r, dyspepsi, flatulens, muntorrhet.'],
             ['General', u'Tr\xf6tthet.']]],
           ['Uncommon',
            [['Infections', u'Bronkit, nasofaryngit, sinuit, svampinfektion, virusinfektion.'],
             ['Metabolism', u'Anorexi, minskad aptit, polydipsi.'],
             ['Psychiatric',
              u'Panikreaktion, dysfori, bradyfreni, onormala tankar, rastl\xf6shet, hum\xf6rsv\xe4ngningar, depression*, \xe5ngest*, hallucinationer*, \xf6kad libido, minskad libido.'],
             ['Nervous system',
              u'Kramper, hypertoni, dysartri, tremor, onormal koordination, letargi, hypoestesi, hypogeusi, .'],
             ['Eye',
              u'Skotom, skleral missf\xe4rgning, \xf6gonv\xe4rk, mydriasis, fotofobi, myopi, \xf6kat t\xe5rfl\xf6de.'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac',
              u'F\xf6rmaksflimmer, hj\xe4rtklappning, s\xe4nkning av ST-v\xe5g (EKG), s\xe4nkning av T-v\xe5gsamplitud (EKG), \xf6kad hj\xe4rtfrekvens.'],
             ['Vascular', u'\xd6kat blodtryck.'],
             ['Respiratory',
              u'Dyspn\xe9, hosta, luftv\xe4gsobstruktion, heshet, sm\xe4rta i svalg och strupe, halsirritation, t\xe4ppta bih\xe5lor, baksnuva, rinorr\xe9, snarkning.'],
             ['GI',
              u'Hematemes, blodig avf\xf6ring, gastrit, gastroesofagal refluxsjukdom, buksm\xe4rta, f\xf6r\xe4ndrad avf\xf6ringsvana, onormal avf\xf6ring, rapningar, aft\xf6s stomatit, sm\xe4rta i tandk\xf6ttet, tungbel\xe4ggningar.'],
             ['Skin',
              u'Spridda utslag, erytem, kl\xe5da, akne, hyperhidros, nattliga svettningar.'],
             ['Musculoskeletal',
              u'Stelhet i lederna, muskelspasmer, sm\xe4rta i br\xf6stet, kostokondrit.'],
             ['Renal', u'Glukosuri, nokturi, polyuri.'],
             ['Reproductive system',
              u'Menorragi, vaginala flytningar, sexuella st\xf6rningar.'],
             ['General',
              u'Br\xf6stbesv\xe4r, br\xf6stsm\xe4rta, feber, f\xf6rkylningsk\xe4nsla, asteni, s\xf6mnst\xf6rning p\xe5 grund av st\xf6rd dygnsrytm, sjukdomsk\xe4nsla, cystor.'],
             ['Investigations',
              u'Onormala leverv\xe4rden, minskat antal blodpl\xe4ttar, onormal sperma, \xf6kad halt av C-reaktiva proteiner, minskat blodkalciumv\xe4rde, vikt\xf6kning.']]],
           ['Rare', [['Nervous system', u'h\xe4ndelse.']]],
           ['Unknown',
            [['Metabolism', u'Hyperglykemi, diabetes mellitus.'],
             ['Psychiatric',
              u'Sj\xe4lvmordstankar, psykos, aggression, onormalt beteende, somnambulism.'],
             ['Cardiac', u'Hj\xe4rtinfarkt'],
             ['Skin',
              u'Allvarliga hudreaktioner, inkluderande Stevens-Johnson syndrom och Erytema multiforme, angio\xf6dem']]]],
 '_pages': [5, 7],
 u'_rank': 28,
 u'_type': u'LSFU'}