{'_data': [['Very common', [['GI', u'Flatulens*, konstipation*']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Kr\xe4kningar, diarr\xe9*, dyspepsi*, buksm\xe4rtor, onormal avf\xf6ring, illam\xe5ende, utsp\xe4nd buk'],
             ['Investigations', u'\xd6kade serumtriglycerider']]],
           ['Uncommon',
            [['GI',
              u'(>1/1000 till <1/100), s\xe4llsynta (>1/10 000 till <1/1000), mycket s\xe4llsynta (<1/10 000)'],
             ['Musculoskeletal', u'Muskelv\xe4rk'],
             ['Investigations',
              u'\xd6kade serumtransaminaser *se nedanst\xe5ende avsnitt f\xf6r ytterligare information Beskrivning av utvalda biverkningar Bakgrundsincidensen f\xf6r flatulens och diarr\xe9 var h\xf6gre hos patienter som fick placebo i samma kontrollerade kliniska studier. Endast konstipation och dyspepsi rapporterades med h\xf6gre procentandel bland dem som fick Cholestagel, j\xe4mf\xf6rt med placebo. Cholestagel i kombination med statiner samt i kombination med ezetimib tolererades v\xe4l, och de biverkningar som observerades \xf6verensst\xe4mde med de k\xe4nda s\xe4kerhetsprofilerna hos statiner eller ezetimib som administreras ensamt.']]],
           ['Rare', [['GI', u'Dysfagi']]],
           ['Very rare', [['GI', u'Pankreatit']]],
           ['Unknown',
            [['GI',
              u'Lista \xf6ver biverkningar i tabellform I kontrollerade kliniska studier omfattande cirka 1400 patienter samt vid anv\xe4ndning efter godk\xe4nnandet har f\xf6ljande biverkningar rapporterats hos de patienter som f\xe5tt Cholestagel. Rapporteringsfrekvensen klassificeras som mycket vanliga (\u22651/10), vanliga (\u22651/100 till <1/10),']]]],
 '_pages': [6, 6],
 u'_rank': 10,
 u'_type': u'LSFU'}