{'_data': [['Very common',
            [['Immune system',
              u'\xd6verk\xe4nslighets-  Angioneurotiskt   reaktioner  \xf6dem'],
             ['Nervous system',
              u'Huvudv\xe4rk  Yrsel  1  Stroke   (inklusive   bl\xf6dningar), synkope,  transitoriska  ischemiska attacker  , migr\xe4n  , krampanfall,   transitorisk amnesi'],
             ['Eye',
              u'Dimsyn,  Synf\xe4ltsdefekter,   sm\xe4rtf\xf6rnimmelser  svullna \xf6gonlock,   i \xf6gonen,  konjunktival   hyperemi, icke-  arteritisk fr\xe4mre  ischemisk  optikusneuropati  (NAION)  ,2  retinalk\xe4rlsocklusion'],
             ['Ear',
              u'Tinnitus  Pl\xf6tslig d\xf6vhet   1  Hj\xe4rtat   Takykardi,  Hj\xe4rtinfarkt, instabil   hj\xe4rtklappning  angina pectoris  , ventrikul\xe4r arytmi 2'],
             ['Vascular', u'Blodvallning  Hypotoni  , hypertoni'],
             ['Respiratory', u'N\xe4st\xe4ppa  Dyspn\xe9, epistaxis'],
             ['GI', u'Dyspepsi,  Buksm\xe4rta   gastroesofagal  reflux'],
             ['Skin',
              u'Utslag,  Urtikaria, Stevens-   hyperhidros  Johnson syndrom  , (svettningar)  exfoliativ dermatit  2'],
             ['Musculoskeletal', u'Ryggsm\xe4rta,  myalgi, sm\xe4rta i  extremiteter'],
             ['Renal', u'Hematuri'],
             ['Reproductive system',
              u'8  penil hemorragi,  F\xf6rl\xe4ngd erektion,   hematospermi  priapism  2'],
             ['General',
              u'Br\xf6stsm\xe4rta  1  Ansikts\xf6dem  , pl\xf6tslig hj\xe4rtd\xf6d 1,2  (1) De flesta patienter hade sedan tidigare kardiovaskul\xe4ra riskfaktorer (se avsnitt 4.4).   (2) Biverkningar rapporterade efter marknadsf\xf6ring, inte observerade i placebokontrollerade kliniska   pr\xf6vningar.  (3) Oftare rapporterat n\xe4r tadalafil ges till patienter som redan tar blodtryckss\xe4nkande l\xe4kemedel.']]]],
 '_pages': [6, 8],
 u'_rank': 12,
 u'_type': u'LFSUR'}