{'_data': [['Common',
            [['Reproductive system',
              u'Mellanbl\xf6dning, st\xe4nkbl\xf6dning, amenorr\xe9, vaginal candidiasis'],
             ['GI', u'Magkramp, uppk\xf6rdhet'],
             ['Skin', u'Akne, utslag'],
             ['Nervous system', u'Migr\xe4n, hum\xf6rf\xf6r\xe4ndringar, depression'],
             ['Metabolism',
              u'V\xe4tskeretention, f\xf6r\xe4ndringar i kroppsvikt (\xf6kning eller minskning)']]],
           ['Uncommon',
            [['GI', u'Illam\xe5ende, kr\xe4kning, kolit'],
             ['Skin', u'Alopeci, hirsutism, kloasma'],
             ['Nervous system', u'Irritabilitet, f\xf6r\xe4ndringar i libido'],
             ['Metabolism', u'Aptitf\xf6r\xe4ndringar']]],
           ['Rare', [['Skin', u'Erythema (nodosum, multiforme)']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 11],
 u'_rank': 10,
 u'_type': u'MSFU'}