<<<<<<< HEAD
{'_data': [['Unknown',
            [['Immune system',
              u'liknande serumsjuka Metabolism och Anorexi Hyperglykemi nutrition Psykiatriska Psykomotorisk F\xf6rvirring och Psykotiska reaktioner st\xf6rningar hyperaktivitet / desorientering (se avsnitt 4.4) agitation Oro Onormala dr\xf6mmar Depression Hallucinationer Centrala och Huvudv\xe4rk Par- och Migr\xe4n Perifer perifera Yrsel dysestesi F\xf6rs\xe4mrad neuropati (se nervsystemet S\xf6mnrubbningar Hypoestesi koordinationsf\xf6rm\xe5g avsnitt 4.4) F\xf6r\xe4ndringar av Tremor a G\xe5ngrubbning smaksinnet Kramper (se F\xf6r\xe4ndringar av avsnitt 4.4) luktsinnet Yrsel Intrakraniell hypertoni \xd6gon Synrubbning F\xf6rvr\xe4ngt f\xe4rgseende'],
             ['Ear',
              u'Nedsatt h\xf6rsel Hj\xe4rtat Takykardi Ventrikul\xe4r arrytmi och Torsades de Pointes (har rapporterats \xf6verv\xe4gande f\xf6r patienter med k\xe4nda riskfaktorer f\xf6r QT-f\xf6rl\xe4ngni ng), EKG QT-f\xf6rl\xe4ngni ng (se avsnitt 4.4 och 4.9). Blodk\xe4rl Vasodilatation Vaskulit Hypotoni Svimning Andningsv\xe4gar, Dyspn\xe9 br\xf6stkorg och (inklusive mediastinum astmatiskt tillst\xe5nd) Organsystem Vanliga Mindre vanliga S\xe4llsynta Mycket s\xe4llsynta Frekvens > 1/100 till > 1/1 000 till < > 1/10 000 till < < 1/10 000 ok\xe4nd (kan < 1/10 1/100 1/1 000 inte ber\xe4knas fr\xe5n tillg\xe4ngliga data) Magtarmkanalen Illam\xe5ende Kr\xe4kning Pankreatit Diarr\xe9 Sm\xe4rta i']]]],
 '_pages': [10, 13],
 u'_rank': 2,
 u'_type': u'LSFU'}
=======
{'_data': [['Common', [['GI', u'Illam\xe5ende Diarr\xe9']]],
           ['Uncommon',
            [['Infections', u'Mykotiska superinfektioner'],
             ['Blood', u'Eosinofili'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system',
              u'Huvudv\xe4rk Yrsel S\xf6mnrubbningar F\xf6r\xe4ndringar av smaksinnet'],
             ['GI', u'Kr\xe4kning Sm\xe4rta i magtarmkanalen och buken, Dyspepsi Flatulens'],
             ['Hepato', u'F\xf6rh\xf6jda transaminaser F\xf6rh\xf6jt bilirubin'],
             ['Skin', u'Hudutslag Pruritus Urtikaria'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (t.ex. sm\xe4rta i extremiteter, ryggsm\xe4rta, br\xf6stsm\xe4rta) Artralgi'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['General', u'Asteni Feber'],
             ['Investigations', u'F\xf6rh\xf6jt alkaliskt fosfatas']]],
           ['Rare',
            [['Infections',
              u'Antibiotika associerad kolit (i mycket s\xe4llsynta fall m\xf6jligen med d\xf6dlig utg\xe5ng)'],
             ['Blood', u'Leukopeni Anemi Neutropeni Leukocytos Trombocytopeni Trombocytemi'],
             ['Immune system', u'Allergisk reaktion Allergiskt \xf6dem / angio\xf6dem'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system',
              u'Par-och dysestesi Hypoestesi Tremor Kramper (se avsnitt 4.4) Yrsel'],
             ['Eye', u'Synrubbning'],
             ['Ear', u'Tinnitus H\xf6rself\xf6rlust / Nedsatt h\xf6rsel'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Vasodilatation Hypotoni Svimning'],
             ['Respiratory', u'Dyspn\xe9 (inklusive astmatiskt tillst\xe5nd)'],
             ['Hepato', u'Nedsatt leverfunktion Kolestatisk ikterus Hepatit'],
             ['Skin', u'Ljusk\xe4nslighets-reaktioner (se avsnitt 4.4) Ospecifik sveda'],
             ['Musculoskeletal', u'Myalgi Artrit \xd6kad muskeltonus och kramper'],
             ['Renal',
              u'Njursvikt Hematuri Kristalluri (se avsnitt 4.4) Tubulointerstitiel l nefrit'],
             ['General', u'\xd6dem Svettning (hyperhidros)'],
             ['Investigations', u'Onormal protrombinniv\xe5 F\xf6rh\xf6jt amylas']]],
           ['Very rare',
            [['Blood',
              u'Hemolytsk anemi Agranulocytos Pancytopeni (livshotande) Benm\xe4rgsdepression (livshotande)'],
             ['Immune system',
              u'Anafylaktisk reaktion Anafylaktisk chock (livshotande) (se avsnitt 4.4) Reaktion liknande serumsjuka'],
             ['Nervous system',
              u'Migr\xe4n F\xf6rs\xe4mrad koordinationsf\xf6rm\xe5g a G\xe5ngrubbning F\xf6r\xe4ndringar av luktsinnet Intrakraniell hypertoni'],
             ['Eye', u'F\xf6rvr\xe4ngt f\xe4rgseende'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Levernekros (i mycket s\xe4llsynta fall \xf6verg\xe5ende till livshotande leversvikt) (se avsnitt 4.4)'],
             ['Skin',
              u'Petekier Erythema multiforme Erythema nodosum Stevens-Johnsons syndrom (kan vara livshotande) Toxisk epidermal nekrolys (kan vara livshotande)'],
             ['Musculoskeletal',
              u'Muskelsvaghet Tendinit Senruptur (fr\xe4mst h\xe4lsenan) (se avsnitt 4.4) Exacerbation av symptom p\xe5 myasthenia gravis (se avsnitt 4.4)']]],
           ['Unknown',
            [['Nervous system', u'Perifer neuropati (se avsnitt 4.4)'],
             ['Cardiac',
              u'Ventrikul\xe4r arrytmi och Torsades de Pointes (har rapporterats \xf6verv\xe4gande f\xf6r patienter med k\xe4nda riskfaktorer f\xf6r QT-f\xf6rl\xe4ngning), EKG QT-f\xf6rl\xe4ngning (se avsnitt 4.4 och 4.9).']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 13],
 u'_rank': 39,
 u'_type': u'MSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
