{'_data': [['Common', [['GI', u'Illa-m\xe5e nde Diarr\xe9']]],
           ['Uncommon',
            [['Infections', u'Mykotiska superinfektioner'],
             ['Blood', u'Eosinofili'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system',
              u'Huvudv\xe4rk Yrsel S\xf6mnst\xf6rningar Smak-f\xf6r\xe4ndring ar'],
             ['GI', u'Kr\xe4kning Sm\xe4rta i magtarmkanalen och buken Dyspepsi Flatulens'],
             ['Hepato', u'F\xf6rh\xf6jt transaminas F\xf6rh\xf6jt bilirubin'],
             ['Skin', u'Hudutslag Pruritus Urtikaria'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (t ex sm\xe4rta i extremiterna, ryggsm\xe4rta, br\xf6stsm\xe4rta) Artralgi'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['General', u'Asteni Feber'],
             ['Investigations', u'F\xf6rh\xf6jning av alkaliska fosfatv\xe4rdet']]],
           ['Rare',
            [['Infections',
              u'Antibiotika associerad kolit (i mycket s\xe4llsynta fall m\xf6jligen med d\xf6dlig utg\xe5ng) (se avsnitt 4.4)'],
             ['Blood', u'Leukopeni Anemi Neutropeni Leukocytos Trombocytopenia Trombocyaemi'],
             ['Immune system', u'Allergisk reaktion Allergiskt \xf6dem / angio\xf6dem'],
             ['Metabolism', u'Hyperglykemi'],
             ['Nervous system',
              u'Par-och dysestesi Hypoestesi Tremor Kramper (inkl. Status epileptikus se avsnitt 4.4) Yrsel'],
             ['Eye', u'Synrubbning (t.ex. diplopi)'],
             ['Ear', u'Tinnitus H\xf6rself\xf6rlust / Nedsatt h\xf6rsel'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Vasodilatation Hypotension Svimning'],
             ['Respiratory', u'Dyspn\xe9 (inklusive astmatiskt tillst\xe5nd)'],
             ['Hepato', u'Nedsatt leverfunktion Kolestatisk ikterus Hepatit'],
             ['Skin', u'Ljusk\xe4nslighetsreak tioner (se avsnitt 4.4)'],
             ['Musculoskeletal', u'Myalgi Artrit \xd6kad muskeltonus och kramper'],
             ['Renal',
              u'Njursvikt Hematuri Krystalluri (se avsnitt 4.4) Tubulointerstitial nefrit'],
             ['General', u'\xd6dem Svettning (hyperhidros)'],
             ['Investigations', u'F\xf6rh\xf6jt amylas']]],
           ['Very rare',
            [['Blood',
              u'Hemolytisk anemi Agranulocytos Pancytopeni (livshotande) Benm\xe4rgsdepres sion (livshotande)'],
             ['Immune system',
              u'Anafylaktisk reaktion Anafylaktisk chock (livshotande) (se avsnitt 4.4) Reaktion liknande serumsjuka'],
             ['Nervous system',
              u'Migr\xe4n F\xf6rs\xe4mrad koordinationsf\xf6r m\xe5ga G\xe5ngrubbning F\xf6r\xe4ndrat luktsinne Intrakraniell hypertension'],
             ['Eye', u'F\xf6rvr\xe4ngt f\xe4rgseende'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Levernekros (i mycket s\xe4llsynta fall \xf6verg\xe5ng till livshotande leversvikt) (se avsnitt 4.4)'],
             ['Skin',
              u'Petekier Erythema multiforme Erythema nodosum Stevens-Johnson syndrom (kan vara livshotande) Toxisk epidermal nekrolys (kan vara livshotande)'],
             ['Musculoskeletal',
              u'Muskelsvaghet Tendinit Senruptur (fr\xe4mst h\xe4lsenan) (se avsnitt 4.4) Exacerbation av symtomen av myasthenia gravis (se avsnitt 4.4)']]],
           ['Unknown',
            [['Nervous system', u'Perifer neuropati (se avsnitt 4.4)'],
             ['Cardiac',
              u'Ventrikul\xe4r arytmi och torsade de pointes*, EKG QT-f\xf6rl\xe4ngni ng (se avsnitt 4.4 och 4.9).'],
             ['Skin', u'Akut generaliserat exantemat\xf6s pustulos (AGEP).'],
             ['Investigations',
              u'\xd6kad INR (international normalised ratio, hos patienter med vitamin K antagonist)']]]],
 '_note': u' ?MSFU',
 '_pages': [11, 13],
 u'_rank': 41,
 u'_type': u'MSFU'}