{'_data': [['Common',
            [['GI', u'Illam\xe5ende Diarr\xe9'],
             ['General',
              u'Reaktioner vid injektions-/ infusions-st\xe4l let (endast vid intraven\xf6s admini-streri ng)'],
             ['Investigations',
              u'sekventiell (intraven\xf6s och oral) behandling: Vanliga Mindre vanliga S\xe4llsynta Pediatriska patienter:']]],
           ['Uncommon',
            [['Infections', u'Mykotiska superinfektioner'],
             ['Blood', u'Eosinofili'],
             ['Metabolism', u'Aptitl\xf6shet'],
             ['Psychiatric', u'Psykomotorisk hyperaktivitet / agitation'],
             ['Nervous system', u'Huvudv\xe4rk Yrsel S\xf6mnsv\xe5righeter Smakrubbningar'],
             ['GI',
              u'Kr\xe4kningar Gastro-intestinell a och abdominella sm\xe4rtor Dyspepsi Flatulens'],
             ['Hepato', u'F\xf6rh\xf6jd niv\xe5 av transaminaser F\xf6rh\xf6jt bilirubin'],
             ['Skin', u'Utslag Kl\xe5da N\xe4sselutslag'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (t.ex. sm\xe4rta i extremiteter, ryggsm\xe4rta, br\xf6stsm\xe4rta)'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['General', u'Asteni Feber'],
             ['Investigations',
              u'\xd6kad niv\xe5 av alkaliskt fosfatas i blodet Kr\xe4kning, \xf6verg\xe5ende \xf6kning av transaminaser, utslag Trombocytopeni, trombocytemi, f\xf6rvirring och desorientering, hallucinationer, par-och dysestesi, kramper, svindel, synrubbningar, h\xf6rself\xf6rlust, takykardi, vasodilatation, hypotoni, \xf6verg\xe5ende nedsatt leverfunktion, kolestatisk ikterus, njursvikt, \xf6dem Pancytopeni, benm\xe4rgsdepression, anafylaktisk chock, psykotiska reaktioner, migr\xe4n, f\xf6r\xe4ndrat luktsinne, nedsatt h\xf6rsel, vaskulit, pankreatit, levernekros, petekier, senruptur']]],
           ['Rare',
            [['Infections',
              u'Antibiotika-associera d kolit (ytterst s\xe4llan med potentiellt d\xf6dlig utg\xe5ng) (se avsnitt 4.4)'],
             ['Blood', u'Leukopeni Anemi Neutropeni Leukocytos Trombocytopeni Trombocytemi'],
             ['Immune system', u'Allergisk reaktion Allergiska \xf6dem / angio\xf6dem'],
             ['Metabolism', u'Hypoglykemi'],
             ['Psychiatric',
              u'F\xf6rvirring och desorientering \xc5ngestreaktion Onormala dr\xf6mmar Depression Hallucinationer'],
             ['Nervous system',
              u'Par-och dysestesi Hypoestesi Tremor Kramper (se avsnitt 4.4) Svindel'],
             ['Eye', u'Synst\xf6rningar'],
             ['Ear', u'Tinnitus F\xf6rlorad / nedsatt h\xf6rsel'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Vasodilatation Hypotension Synkope'],
             ['Respiratory', u'Dyspn\xe9 (inklusive astmatiskt tillst\xe5nd)'],
             ['Hepato', u'Nedsatt leverfunktion Kolestatisk ikterus Hepatit'],
             ['Skin', u'Ljusk\xe4nslighet (se avsnitt 4.4)'],
             ['Musculoskeletal', u'Myalgi Artrit \xd6kad muskeltonus och kramper'],
             ['Renal',
              u'Njursvikt Hematuri Kristalluri (se avsnitt 4.4) Tubulointerstitial nefrit'],
             ['General', u'\xd6dem Svettningar (hyperhidros)'],
             ['Investigations',
              u'Onormal protrombinniv\xe5 \xd6kad niv\xe5 av amylas * Dessa fall rapporterades under perioden efter marknadsf\xf6ring och observerades huvudsakligen bland']]],
           ['Very rare',
            [['Blood',
              u'Hemolytisk anemi Agranulocytos Pancytopeni (livshotande) Benm\xe4rgs-depress ion (livshotande)'],
             ['Immune system',
              u'Anafylaktisk reaktion Anafylaktisk chock (livshotande) (se avsnitt 4.4) Serumsjuke-liknan de reaktion'],
             ['Psychiatric', u'Psykotiska reaktioner (se avsnitt 4.4)'],
             ['Nervous system',
              u'Migr\xe4n Koordinations-rub bningar G\xe5ngst\xf6rning F\xf6r\xe4ndrat luktsinne Intrakraniell hypertension'],
             ['Eye', u'Rubbningar i f\xe4rgseendet'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Levernekros (som mycket s\xe4llan utvecklas till livshotande leversvikt) (se avsnitt 4.4)'],
             ['Skin',
              u'Petekier Erythema multiforme Erythema nodosum Stevens-Johnson-syndrom (potentiellt livshotande) Toxisk epidermal nekrolys (potentiellt livshotande)'],
             ['Musculoskeletal',
              u'Muskelsvaghet Tendinit Senruptur (s\xe4rskilt h\xe4lsenan) (se avsnitt 4.4) F\xf6rv\xe4rrade symtom p\xe5 myasthenia gravis (se avsnitt 4.4)']]],
           ['Unknown',
            [['Nervous system', u'Perifer neuropati (se avsnitt 4.4)'],
             ['Cardiac', u'Ventrikul\xe4r arytmi, QT-f\xf6rl\xe4ngning, torsades de pointes*']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 11],
 u'_rank': 44,
 u'_type': u'MSFU'}