{'_data': [['Uncommon', [['Endocrine', u'Hypomagnesemi']]],
           ['Rare',
            [['Endocrine', u'hyperkolesterolemi'],
             ['Cardiac', u'Myokardinfarkt, sv\xe5r koronarart\xe4rsjukdom'],
             ['Cardiac', u'Hypertoni']]],
           ['Very rare',
            [['Infections',
              u'Trombotisk mikroangiopati kombinerat med hemolytiskt uremiskt syndrom'],
             ['Endocrine', u'\xd6kade j\xe4rnniv\xe5er i blodet'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd']]],
           ['Unknown',
            [['Infections',
              u'Infektion Neoplasier; benigna, maligna S\xe4llsynta Akut leukemi och ospecificerade Blodet och lymfsystemet Mycket vanliga Benm\xe4rgssvikt, trombocytopeni, leukopeni, anemi'],
             ['Endocrine',
              u'sekretion av antidiuretiskt hormon Metabolism och nutrition Mycket vanliga Hyponatremi'],
             ['Eye', u'\xf6gonr\xf6relse'],
             ['Cardiac', u'Hj\xe4rtsjukdom Blodk\xe4rl Vanliga Flebit'],
             ['Hepato',
              u'bilirubinniv\xe5 i blodet Hud och subkutan v\xe4vnad Vanliga Erytem, huds\xe5r, lokalt \xf6dem och sm\xe4rta']]]],
 '_pages': [7, 8],
 u'_rank': 12,
 u'_type': u'LSFU'}