<<<<<<< HEAD
{'_data': [['Uncommon', [['Endocrine', u'Hypomagnesemi']]],
           ['Rare',
            [['Endocrine', u'hyperkolesterolemi'],
             ['Cardiac', u'Myokardinfarkt, sv\xe5r koronarart\xe4rsjukdom'],
             ['Cardiac', u'Hypertoni']]],
           ['Very rare',
            [['Infections',
              u'Trombotisk mikroangiopati kombinerat med hemolytiskt uremiskt syndrom'],
             ['Endocrine', u'\xd6kade j\xe4rnniv\xe5er i blodet'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd']]],
           ['Unknown',
            [['Infections',
              u'Infektion Neoplasier; benigna, maligna S\xe4llsynta Akut leukemi och ospecificerade Blodet och lymfsystemet Mycket vanliga Benm\xe4rgssvikt, trombocytopeni, leukopeni, anemi'],
             ['Endocrine',
              u'sekretion av antidiuretiskt hormon Metabolism och nutrition Mycket vanliga Hyponatremi'],
             ['Eye', u'\xf6gonr\xf6relse'],
             ['Cardiac', u'Hj\xe4rtsjukdom Blodk\xe4rl Vanliga Flebit'],
             ['Hepato',
              u'bilirubinniv\xe5 i blodet Hud och subkutan v\xe4vnad Vanliga Erytem, huds\xe5r, lokalt \xf6dem och sm\xe4rta']]]],
 '_pages': [7, 8],
 u'_rank': 12,
 u'_type': u'LSFU'}
=======
{'_data': [['Very common',
            [['Blood', u'Benm\xe4rgssvikt, trombocytopeni, leukopeni,  anemi'],
             ['Metabolism', u'Hyponatremi']]],
           ['Common',
            [['Infections', u'Sepsis'],
             ['Cardiac', u'Arytmi, bradykardi, takykardi'],
             ['Vascular', u'Flebit'],
             ['Skin', u'Erytem, huds\xe5r, lokalt \xf6dem och sm\xe4rta']]],
           ['Uncommon',
            [['Metabolism', u'Hypomagnesemi'],
             ['Ear', u'Ototoxicitet'],
             ['Reproductive system', u'Onormal spermatogenes och ovulation,']]],
           ['Rare',
            [['Blood', u'Immunsuppression'],
             ['Metabolism', u'hyperkolesterolemi'],
             ['Nervous system',
              u'Kramper, perifer neuropati,  leukoencefalopati, reversibelt bakre leukoencefalopatisyndrom'],
             ['Eye', u'Optisk retrobulb\xe4r neurit, f\xf6rs\xe4mrad  \xf6gonr\xf6relse'],
             ['Cardiac', u'Myokardinfarkt, sv\xe5r koronarart\xe4rsjukdom'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Stomatit'],
             ['Investigations', u'F\xf6rh\xf6jd albuminniv\xe5 i blodet']]],
           ['Very rare',
            [['Blood',
              u'Trombotisk mikroangiopati kombinerat  med hemolytiskt uremiskt syndrom'],
             ['Nervous system', u'Krampanfall']]],
           ['Unknown',
            [['Infections', u'Infektion'],
             ['Blood', u'Positivt Coombs test p\xe5 hemolytisk anemi'],
             ['Endocrine',
              u'F\xf6rh\xf6ja amylasniv\xe5er i blodet, otillr\xe4cklig  sekretion av antidiuretiskt hormon'],
             ['Ear', u'Tinnitus, d\xf6vhet'],
             ['Vascular', u'Trombotisk mikroangiopati (hemolytiskt'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende, anorexi, hicka,  diarr\xe9'],
             ['Hepato',
              u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jd  bilirubinniv\xe5 i blodet'],
             ['Skin', u'Utslag, alopeci']]]],
 '_pages': [7, 8],
 u'_rank': 27,
 u'_type': u'TSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
