{'_data': [['Very common',
            [['Blood', u'Benm\xe4rgssvikt, trombocytopeni,  leukopeni, anemi'],
             ['Metabolism', u'Hyponatremi, .'],
             ['Ear',
              u'Ototoxiska biverkningar hos ca 30 %  manifesterat som tinnitus eller h\xf6rselneds\xe4ttning (frekvensomr\xe5det  Hz)'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar  anorexi, diarr\xe9']]],
           ['Common',
            [['Infections', u'Sepsis'],
             ['Ear', u'Minskad f\xf6rm\xe5ga att h\xf6ra normala  konversationstoner.'],
             ['Cardiac', u'Arytmi, bradykardi, takykardi'],
             ['GI', u'Aptitf\xf6rlust.'],
             ['Renal', u'Tubul\xe4r nekros hos ca 30%.']]],
           ['Uncommon',
            [['Immune system',
              u'Anafylaktoida reaktioner (ansikts\xf6dem,  v\xe4sande andning, bronkospasm, takykardi, hypotension)'],
             ['Metabolism', u'Hypomagnesemi'],
             ['Nervous system',
              u'Neurotoxiska symtom (tremor,  muskelsvaghet, bakstr\xe4ngsmyelopati,  opticusneurit, smakf\xf6rlust)'],
             ['Eye', u'\xc4ndrat f\xe4rgseende.'],
             ['Hepato', u'Leverp\xe5verkan.'],
             ['Reproductive system', u'St\xf6rningar av spermatogenes']]],
           ['Rare',
            [['Neoplasms', u'Akut leukemi'],
             ['Nervous system',
              u'Kramper, perifer neuropati (med  parestesier), leukoencefalopati, reversibel posterior leukoencefalopati syndrom (RPLS), cerebral insult'],
             ['Eye', u'Olika grader av synf\xf6rlust.'],
             ['Ear', u'Vestibul\xe4r toxicitet.'],
             ['Cardiac', u'Myokardinfarkt'],
             ['GI', u'Stomatit.']]],
           ['Very rare', [['Cardiac', u'Hj\xe4rtstillest\xe5nd']]],
           ['Unknown',
            [['Infections', u'Infektioner (som kan leda till d\xf6den)'],
             ['Blood', u'Positivt Coombs test (hemolytisk'],
             ['Endocrine', u'\xd6kning av amylas i blodet,'],
             ['Metabolism', u'Dehydrering, hypokalemi,'],
             ['Nervous system', u'Cerebrovaskul\xe4r sjukdom, hemorragisk'],
             ['Eye', u'Papill\xf6dem, dimsyn, f\xf6rv\xe4rvad'],
             ['Ear', u'D\xf6vhet'],
             ['Cardiac', u'Hj\xe4rtsjukdom'],
             ['Vascular', u'Trombotisk microangiopati'],
             ['GI', u'Hicka,'],
             ['Hepato', u'\xd6kad m\xe4ngd av leverenzymer, f\xf6rh\xf6jda'],
             ['Respiratory', u'Lungemboli'],
             ['Skin', u'Hudutslag, alopeci'],
             ['Musculoskeletal', u'Muskelspasm'],
             ['Renal', u'Akut njursvikt, njursvikt (\xf6kning av'],
             ['General', u'Feber (mycket vanlig), asteni,']]]],
 '_pages': [5, 8],
 u'_rank': 38,
 u'_type': u'TSFU'}