{'_data': [['Very common',
            [['Nervous system', u'S\xf6mnighet, s\xf6mnl\xf6shet'],
             ['GI', u'Muntorrhet, illam\xe5ende'],
             ['Skin', u'\xd6kad s vettning']]],
           ['Common',
            [['Blood', u'Palpitationer'],
             ['Metabolism', u'Minskad aptit, viktminskning'],
             ['Psychiatric',
              u'Nervositet, \xe5ngest, sv\xe5righeter, agitation, dr\xf6m-st\xf6rning ar, minskad libido, apati, f\xf6rvirrings-till st\xe5nd, onormal orgasm (kvinnor)'],
             ['Nervous system', u'Tremor, parestesi, yrsel, st\xf6rd uppm\xe4rk-samh et'],
             ['Eye', u'Ackomodation sst\xf6rningar'],
             ['Ear', u'Tinnitus'],
             ['Respiratory', u'Rinit. g\xe4spningar'],
             ['GI',
              u'F\xf6rstoppning, diarr\xe9, kr\xe4kning, buksm\xe4rta, dyspepsi, salivation, flatulens'],
             ['Skin', u'Kl\xe5da'],
             ['Musculoskeletal', u'Myalgi , artralgi'],
             ['Reproductive system',
              u'Miktions-st\xf6rn ingar, ejakulations-st \xf6rningar, oregelbunden menstruation, ejakulations-sv ikt, impotens'],
             ['General',
              u'Anorexi, huvudv\xe4rk, hyperhidros, asteni, allm\xe4n sjukdoms-k\xe4ns']]],
           ['Uncommon',
            [['Metabolism', u'\xd6kad aptit, vikt\xf6kning'],
             ['Psychiatric', u'Eufori, aggression, \xf6r\xe4ndring, hallucinationer , mani'],
             ['Nervous system', u'Synkope'],
             ['Eye', u'Mydriasis'],
             ['Cardiac', u'Bradykardi, takykardi'],
             ['Respiratory', u'Hosta, dyspn\xe9'],
             ['Skin',
              u'Ljusk\xe4nslighet sreaktioner, urtikaria, h\xe5ravfall, utslag, purpura'],
             ['Renal', u'Urinretention'],
             ['Reproductive system', u'Kvinnor: Menorragi, anorgasmi'],
             ['General', u'\xd6dem']]],
           ['Rare',
            [['Metabolism', u'Hyponatremi'],
             ['Nervous system', u'Grand mal-kramper, dyskinesi, smakst\xf6rningar'],
             ['Vascular', u'Bl\xf6dningar'],
             ['Hepato', u'Hepatit'],
             ['General', u'Pyrexi']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet, anafylaktisk reaktion'],
             ['Endocrine', u'Onormal ADH-sekretion'],
             ['Metabolism', u'Hypokalemi'],
             ['Psychiatric',
              u'Fall av suicidtankar och suicidalt rapporterats under behandling med citalopram eller direkt efter avslutad behandling (se avsnitt 4.4), panikattacker, tandgnissling, rastl\xf6shet'],
             ['Nervous system',
              u'Kramper, serotonergt syndrom, extrapyramidala st\xf6rningar, akatisi, st\xf6rt r\xf6relsem\xf6nster'],
             ['Eye', u'Synst\xf6rningar'],
             ['Cardiac',
              u'QT-f\xf6rl\xe4ngning Ventrikul\xe4r arytmi inklusive torsade de pointes'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['Respiratory', u'N\xe4sbl\xf6dning'],
             ['GI', u'Gastrointestinal bl\xf6dning (inklusive rektal bl\xf6dning)'],
             ['Hepato', u'Onormala leverfunktionstest'],
             ['Skin', u'Ekkymoser, angio\xf6dem'],
             ['Reproductive system', u'M\xe4n: Priapism, galaktorr\xe9 Kvinnor: Metorragi']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 44,
 u'_type': u'MSFU'}