{'_data': [['Rare',
            [['General',
              u'Allergiska reaktioner, i allvarligaste fall anafylaktisk chock  Angio\xf6dem'],
             ['Nervous system',
              u'Nervp\xe5verkan, t ex domningsk\xe4nsla, kvarst\xe5ende parestesi och andra sensoriska st\xf6rningar har  observerats i s\xe4llsynta fall. Huruvida dessa symtom betingas av tekniska faktorer (t ex  intraneural injektion) eller av anestesimedlet har inte med s\xe4kerhet fastst\xe4llts.'],
             ['Blood',
              u'Methemoglobinv\xe4rdet p\xe5verkas normalt inte av de doser som rekommenderas vid rutinm\xe4ssig  tandl\xe4karpraxis. Kliniskt synlig methemoglobinemi (cyanos) kan dock f\xf6rekomma efter h\xf6ga  doser av prilokain samt vid upprepad dosering av relativt sm\xe5 doser. En dos p\xe5 600 mg  prilokainhydroklorid (motsvarande ca elva cylinderampuller) kan ge en stegring i  methemo-globin fr\xe5n ca 1% (fysiologiskt normalv\xe4rde) till ca 4-6%, vilket oftast \xe4r  symtomfritt. Stegringen \xe5tf\xf6ljs inte av hemolys. Methemoglobinemi kan f\xf6rhindras med  metyltionin.']]]],
 '_pages': [3, 3],
 u'_rank': 3,
 u'_type': u'LFSUR'}