{'_data': [[u'Unknown',
            [['Blood', u'Trombocytope   ni'],
             ['Immune system', u'\xd6verk\xe4nslighe'],
             ['Endocrine', u'onormal ADH'],
             ['Metabolism', u'Minskad aptit,   \xd6kad aptit,   Hypo-   Hypokalemi'],
             ['Psychiatric',
              u'S\xf6mnst\xf6rningar,   Aggression,   Panikattacker,   koncentrations-   depersonalis   bruxism,'],
             ['Nervous system',
              u'Somnolens,   Migr\xe4n, tremor   Konvulsio   Konvulsioner,   insomnia   parestesi, yrsel,   Synkop\xe9   n grand   serotonin   vaksamhets-   mal,   syndrom,'],
             ['Eye', u'Ackommoda-   Mydriasis   Synst\xf6rningar'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer   Bradykardi,   Supraventrikul\xe4r   QT-'],
             ['Vascular', u'Hypotoni,hyperto   Bl\xf6dningar   Ortostatisk'],
             ['Respiratory', u'G\xe4spningar,   Hosta   Epistaxis'],
             ['GI',
              u'Illam\xe5ende,   Diarr\xe9,   Gastrointesti-   muntorrhet,   f\xf6rstoppning,   nal bl\xf6dning'],
             ['Hepato', u'\xd6kad lever-   Hepatit   Onormala   enzymaktivit   leverfunktions'],
             ['Skin',
              u'\xd6kad svettning Kl\xe5da   Urticaria,   Angio\xf6dem,   alopeci,   ekkymos och   hudutslag,   \xf6vriga'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['Renal', u'Urineringsprob-   Urinretentio   lem,polyuri   n'],
             ['Reproductive system',
              u'Impotens,   Kvinnor:   Galaktorr\xe9   Kvinnor:   ejakulationsprobl   menorragi   metrorragi   em,   M\xe4n: priapism'],
             ['General', u'Svaghet   Tr\xf6tthet   Pyrexi'],
             ['General', u'sjukdomsk\xe4n   sla']]]],
 '_pages': [9, 10],
 u'_rank': 19,
 u'_type': u'LFSU'}