{'_data': [['Very common',
            [['Vascular', u'Illam\xe5 e n d e ,  muntorrh e t  '],
             ['Vascular', u'\xd6kad  svett ning  '],
             ['Vascular', u'Asteni  ']]],
           ['Common',
            [['Vascular', u'G\xe4spning ar  '],
             ['Vascular',
              u'F\xf6rstop p ning,  diarr\xe9,  dysp e p si,  kr\xe4kning a r,  buks m \xe4 r t a ,  flatulen s,  \xf6kad  salivering '],
             ['Vascular', u'Miktionsst\xf6rning  '],
             ['Vascular',
              u'Of\xf6rm\xe5 g a  att  ejakuler a,  ejakulationss t \xf6r ning a r,  impot e n s '],
             ['Vascular', u'Kl\xe5da  '],
             ['Vascular', u'Myalgi,  artralgi  '],
             ['Vascular', u'Tr\xf6tth e t  ']]],
           ['Uncommon',
            [['Vascular', u'Hosta  '],
             ['Vascular', u'Sv\xe5righ e t e r  att  t\xf6m m a  bl\xe5sa n  '],
             ['Vascular', u'Kvinnor:  kraftig  mens tr u a tion  '],
             ['Vascular',
              u'N\xe4sselutsla g,  alopeci,  utslag,  purpur a,  fotose n sitivitet '],
             ['Vascular', u'\xd6de m,  allm\xe4n  sjukdo m sk \xe4 n sl a  ']]],
           ['Rare',
            [['Vascular', u'Bl\xf6dning  '],
             ['Vascular', u'Hepatit  '],
             ['Vascular', u'Feber  ']]],
           ['Unknown',
            [['Vascular', u' s: Ortost a tisk  hypot e n sion  '],
             ['Vascular', u' s: N\xe4sbl\xf6dning  '],
             ['Vascular', u' s: Bl\xf6dning  i magt a r m k a n a l e n  (inklusive  '],
             ['Vascular', u' s: Onorm ala  leverfunktionsv \xe4 r d e n  '],
             ['Vascular',
              u' s: Kvinnor:  metrorr a gi,  m\xe4n:  priapis m,  galaktorr \xe9  '],
             ['Vascular', u' s: Ekkymos,  angio\xf6d e m  ']]]],
 '_pages': [11, 14],
 u'_rank': 24,
 u'_type': u'LSFU3'}