{'_data': [['Common',
            [['General', u' Tr\xf6tthet.  '],
             ['GI', u' Illam\xe5ende, f\xf6rstoppning.  '],
             ['Other', u' Rodnad av rektalslemhinnan ']]],
           ['Uncommon', [['Hepato', u' Gallv\xe4gsdyskinesi.  ']]],
           ['Rare',
            [['General', u' Allergisk reaktion, angio\xf6dem.  '],
             ['Skin', u' Exantem, urtikaria.  '],
             ['Hepato', u' Leverskada  1 '],
             ['Reproductive system', u' Kreatininstegring  -']]],
           ['Very rare', [['GI', u' Pankreatit.  ']]]],
 '_pages': [3, 4],
 u'_rank': 9,
 u'_type': u'DFSU'}