{'_data': [['Very common', [['GI', u'buksm\xe4rta']]],
           ['Common',
            [['Psychiatric', u's\xf6mnst\xf6rningar'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'muntorrhet, illam\xe5ende, buksp\xe4nning, anala besv\xe4r, proktalgi'],
             ['General', u't\xf6rst, tr\xf6tthet']]],
           ['Uncommon',
            [['Nervous system', u'yrsel'],
             ['Vascular', u'ortostatisk hypotoni'],
             ['GI', u'kr\xe4kningar, avf\xf6ringsinkontinens']]],
           ['Unknown',
            [['Immune system', u'anafylaktiska reaktioner, \xf6verk\xe4nslighet'],
             ['Metabolism', u'hyponatremi'],
             ['Nervous system',
              u'epilepsi, grand mal-anfall, krampanfall, f\xf6rvirringstillst\xe5nd'],
             ['GI',
              u'diarr\xe9*, flatulens *Diarr\xe9 \xe4r den fr\xe4msta kliniska effekten av CitraFleet.'],
             ['Skin',
              u'hudutslag (inklusive erytemat\xf6sa och makulopapul\xf6sa utslag), urtikaria, kl\xe5da och purpura'],
             ['General',
              u'sm\xe4rta Hyponatremi har rapporterats med eller utan \xe5tf\xf6ljande konvulsioner (se avsnitt 4.4). Hos epileptiska patienter har det f\xf6rekommit rapporter om krampanfall/grand mal-anfall utan \xe5tf\xf6ljande hyponatremi (se avsnitt 4.4 och 4.5).']]]],
 '_pages': [3, 4],
 u'_rank': 14,
 u'_type': u'LSFU'}