{'_data': [['Very common', [['GI', u'Buksm\xe4rtor, illam\xe5ende, kr\xe4kning och diarr\xe9']]],
           ['Common', []],
           ['Uncommon',
            [['Nervous system',
              u'Neuro-musk ul\xe4rt blockerande effekt (se avsnitt 4.4 och 4.5)'],
             ['Hepato', u'L\xe4tt \xf6kning av serumtransaminaser'],
             ['Skin',
              u'Allergier i form av morbilli-for ma exantem samt kl\xe5da och n\xe4sselfeber'],
             ['General',
              u'Lokal irritation, sm\xe4rta, indurationer och sterila abscesser vid injektions-st \xe4llet (vid i.m injektion). Sm\xe4rta och trombofle-b iter (efter i.v. infusion)']]],
           ['Rare',
            [['Blood',
              u'Reversibla effekter p\xe5 blodbilden av toxisk eller allergisk natur, i form av trombo-cyt openi, leukopeni, eosinofili, neutropeni och granulo-cy topeni.'],
             ['Immune system',
              u'L\xe4keme-de lsfeber \xd6verk\xe4ns-l ighet mot bensyl-alk ohol'],
             ['Skin',
              u'Svullnad (t.ex. Quinckes \xf6dem) Erytema exuda-tivu m multiforme (t.ex. Stevens-Jo hnson syndrom) samt Lyells syndrom. Kl\xe5da, vaginit samt fj\xe4llande och bull\xf6sa kutana inflamma-t ioner'],
             ['Musculoskeletal', u'Ledsvull-n ader']]],
           ['Very rare',
            [['Immune system',
              u'Anafylak-tis k chock (med svullnad i ansikte, k\xe4rl eller larynx, sv\xe5righet att andas till cirkula-tion skollaps se avsnitt 4.4)'],
             ['Nervous system', u'F\xf6r\xe4ndring av smak och lukt'],
             ['GI', u'Pseudo-me mbran\xf6s enterokolit (se avsnitt 4.4)'],
             ['Hepato', u'\xd6verg\xe5ende hepatit med kolestatisk gulsot'],
             ['Musculoskeletal', u'Polyartrit']]],
           ['Unknown',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI', u'Esofagit, glossit och stomatit'],
             ['General',
              u'Snabb intraven\xf6s injektion kan leda till \xf6verk\xe4nslig hetsreaktion er som v\xe4rmek\xe4nsla illam\xe5ende eller i s\xe4llsynta fall allvarliga kardiovas-k ul\xe4ra st\xf6rningar (t.ex. blodtrycks-f all och hj\xe4rtstopp)*']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 17,
 u'_type': u'MSFU'}