{'_data': [['Common',
            [['Vascular', u'Hematom'],
             ['Respiratory', u'Epistaxis'],
             ['GI', u'Gastointestinal bl\xf6dning, diarr\xe9, buksm\xe4rta, dyspepsi'],
             ['Skin', u'Bl\xe5m\xe4rken'],
             ['General', u'Bl\xf6dning vid punktionsst\xe4llet']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, leukopeni, eosinofili'],
             ['Nervous system',
              u'Intrakraniell bl\xf6dning (vissa fall rapporterades med d\xf6dlig utg\xe5ng), huvudv\xe4rk, parestesier, svindel'],
             ['Eye', u'\xd6gonbl\xf6dning (konjunktival, okul\xe4r, retinal)'],
             ['GI',
              u'Ventrikel-och duodenals\xe5r, gastrit, kr\xe4kning, illam\xe5ende, f\xf6rstoppning, flatulens'],
             ['Skin', u'Hudutslag, kl\xe5da, hudbl\xf6dning (purpura)'],
             ['Renal', u'Hematuri'],
             ['Investigations',
              u'\xd6kad bl\xf6dningstid, minskning av neutrofiler, minskning av blodpl\xe4ttar']]],
           ['Rare',
            [['Blood', u'Neutropeni, inklusive allvarlig neutropeni'],
             ['Ear', u'Vertigo'],
             ['GI', u'Retroperitoneal bl\xf6dning']]],
           ['Very rare',
            [['Blood',
              u'Trombotisk Trombocytopen Purpura (TTP) (se avsnitt 4.4), aplastisk anemi, pancytopeni, agranulocytos, allvarlig trombocytopeni, granulocytopeni, anemi'],
             ['Immune system', u'Serumsjuka, anafylaktoida reaktioner'],
             ['Psychiatric', u'Hallucinationer, konfusion'],
             ['Nervous system', u'Smakf\xf6r\xe4ndringar'],
             ['Vascular',
              u'Allvarlig bl\xf6dning, bl\xf6dning i operationss\xe5r, vaskulit, hypotension'],
             ['Respiratory',
              u'Bl\xf6dning i luftv\xe4gar (blodiga upphostningar, bl\xf6dning i lungan), bronkospasm, interstitiell pneumonit'],
             ['GI',
              u'Gastrintestinal och retroperitoneal bl\xf6dning med d\xf6dlig utg\xe5ng, pankreatit, kolit (inklusive ulcer\xf6s eller lymfocyt\xe4r kolit), stomatit'],
             ['Hepato', u'Akut leversvikt, hepatit, onormala leverfunktions-v\xe4rden'],
             ['Skin',
              u'Bull\xf6s dermatit, (toxisk epidermal nekrolys, Stevens Johnsons syndrom, erythema multiforme) angio\xf6dem, erytemat\xf6sa utslag, urtikaria, eksem, lichen planus'],
             ['Musculoskeletal',
              u'Muskuloskeletal bl\xf6dning (hemartros), artrit, atralgi, myalgi'],
             ['Renal', u'Glomerulonefrit, \xf6kning av blodkreatinin'],
             ['General', u'Feber']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 7],
 u'_rank': 27,
 u'_type': u'MSFU'}