{'_data': [['Common',
            [['GI',
              u' F\xf6rstoppning, illam\xe5ende och kr\xe4kningar, gallv\xe4gsdyskinesi.  ']]],
           ['Uncommon',
            [['Nervous system', u' Omt\xf6ckning och dysfori, speciellt vid h\xf6ga doser.  ']]],
           ['Unknown',
            [['General', u' Angio\xf6dem, anafylaktisk reaktion, tr\xf6tthet, d\xe5sighet.  '],
             ['Nervous system', u' Hallucinationer.  '],
             ['Skin', u' Exantem, urtikaria.  '],
             ['Hepato', u' Leverreaktion som transaminasstegring. '],
             ['Reproductive system', u' Urinretention. ']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'DFSU'}