{'_data': [['Common', [['GI', u'Illam\xe5ende, f\xf6rstoppning'], ['Skin', u'Tr\xf6tthet']]],
           ['Uncommon', [['Hepato', u'Gallv\xe4gsdyskinesi']]],
           ['Rare',
            [['Immune system', u'Allergisk reaktion, angio\xf6dem'],
             ['Hepato', u'Leverskada'],
             ['Skin',
              u'Exantem, urtikaria Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Investigations',
              u'Kreatininstegring Leverskada vid anv\xe4ndning av paracetamol har upptr\xe4tt i samband med alkoholmissbruk. Vid l\xe5ngtidsanv\xe4ndning kan risken f\xf6r njurskador inte helt uteslutas. Gallv\xe4gsdyskinesi kan f\xf6rekomma hos predisponerade patienter.']]],
           ['Very rare', [['GI', u'Pankreatit']]]],
 '_pages': [3, 4],
 u'_rank': 8,
 u'_type': u'LSFU'}