{'_data': [[u'Unknown',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Myokardit'],
             ['GI', u'Buksm\xe4rta'],
             ['Hepato', u'Hepatit, kolelitiasis'],
             ['Musculoskeletal',
              u'Alopeci   Angio\xf6dem  Hudutslag  Systemisk lupus erytematosus-lika syndrom   Atralgi   Myalgi'],
             ['Renal', u'Interstitiell nefrit'],
             ['Immune system', u'Hypersensitivitet']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'LFSU'}