{'_data': [['Very common',
            [['Vascular', u'V\xe4rmevallningar'],
             ['Musculoskeletal', u'Muskelkramper (inkluderande benkramper)']]],
           ['Common',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'S\xf6mnighet'],
             ['GI', u'Muntorrhet'],
             ['Skin', u'Urtikaria'],
             ['General', u'Perifert \xf6dem'],
             ['Investigations',
              u'F\xf6rh\xf6jd triglyceridhalt i blodet, f\xf6rh\xf6jt alaninaminotransferas (ALAT), f\xf6rh\xf6jt aspartataminotransferas (ASAT) Beskrivning av valda biverkningar *Av 7 492 bed\xf6mbara kvinnor (medel\xe5lder = 66 \xe5r) i osteoporosbehandlingsstudien hade kvinnor som behandlades med bazedoxifen en \xf6kad risk f\xf6r ven\xf6s tromboemboli (djup ventrombos, lungemboli och retinal ventrombos). Frekvensen per 1 000 kvinno\xe5r under den 3 \xe5r l\xe5nga studieperioden var 2,86 i gruppen som fick bazedoxifen 20 mg och 1,76 i placebogruppen och under den 5-\xe5riga studieperioden var den 2,34 i gruppen som fick bazedoxifen 20 mg och 1,56 i placebogruppen. Frekvensen per 1 000 kvinno\xe5r under den 7 \xe5r l\xe5nga studieperioden var 2,06 i gruppen som fick bazedoxifen 20 mg och 1,36 i placebogruppen. Frekvensen av VTE var h\xf6gst under det f\xf6rsta \xe5ret med en relativ risk p\xe5 2,69. Efter 3 \xe5r var den relativa risken 1,63 och efter en studieperiod om 5 \xe5r var den relativa risken 1,50. Efter den 7 \xe5r l\xe5nga studieperioden var den relativa risken 1,51 (se avsnitt 5.1). Andra ven\xf6sa tromboemboliska h\xe4ndelser f\xf6rekom ocks\xe5. Erfarenheter efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning Efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning har andra \xf6gonbiverkningar \xe4n retinal ventrombos rapporterats. Dessa har g\xe4llt f\xf6rs\xe4mrad synsk\xe4rpa, dimsyn, fotopsi, synf\xe4ltsdefekter, nedsatt syn, torra \xf6gon, \xf6gonlocks\xf6dem, blefarospasm, \xf6gonsm\xe4rta och \xf6gonsvullnad. De underliggande orsakerna till dessa h\xe4ndelser \xe4r oklara. Om \xf6gonsymtom upptr\xe4der ska patienten rekommenderas att s\xf6ka v\xe5rd.']]],
           ['Uncommon',
            [['Vascular', u'Djup ventrombos* Ytlig tromboflebit'],
             ['Respiratory', u'Lungemboli*']]],
           ['Rare', [['Eye', u'Retinal ventrombos*']]]],
 '_pages': [5, 6],
 u'_rank': 11,
 u'_type': u'LSFU'}