{'_data': [['Very common', [['GI', u'Diarr\xe9']]],
           ['Common',
            [['Infections', u'Gastroenterit, viral Buksm\xe4rta'],
             ['GI', u'Gasbildning Utsp\xe4ndhet av buken'],
             ['Nervous system', u'Yrsel']]],
           ['Uncommon',
            [['Infections', u'Fekal inkontinens'],
             ['GI', u'Tarmt\xf6mnings-tr\xe4ngningar Hypokalemi'],
             ['Metabolism', u'Uttorkning Minskad aptit'],
             ['Vascular', u'Ortostatisk hypotoni']]],
           ['Rare',
            [['Vascular', u'S\xe4nkning av'], ['Investigations', u'bikarbonatniv\xe5 i blodet']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 10,
 u'_type': u'MSFU'}