{'_data': [['Very common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Depression, insomnia'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, koncentra-tio ns-sv\xe5righete'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Diarr\xe9, illam\xe5ende, buksm\xe4rta'],
             ['Skin', u'Alopeci, dermatit, kl\xe5da, torr hud'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['General',
              u'Feber, stelhet, sm\xe4rta, asteni, tr\xf6tthet, reaktion p\xe5 injektions-st\xe4 llet, irritabilitet']]],
           ['Common',
            [['Infections',
              u'\xd6vre luftv\xe4gs-infek tion, bronkit, candida-infek tion i munnen, herpes simplex'],
             ['Blood', u'Trombocyto-peni, lymfadeno-pa ti'],
             ['Endocrine', u'Hypotyroid-is m, hypertyroid-i sm'],
             ['Psychiatric',
              u'Hum\xf6rf\xf6r-\xe4n dringar, k\xe4nslo-m\xe4ssi ga st\xf6rningar, \xe5ngest, aggression, nervositet, s\xe4nkt libido'],
             ['Nervous system',
              u'Minnesf\xf6r-s\xe4 mring synkope, svaghet, migr\xe4n, hypoestesi, hyperestesi, parestesier, tremor, smakf\xf6r-\xe4ndr ing, mardr\xf6mmar, somnolens'],
             ['Eye', u'Dimsyn, \xf6gonsm\xe4rta, \xf6goninflamm ation, xeroftalmi'],
             ['Ear', u'Vertigo, \xf6ronsm\xe4rta'],
             ['Cardiac', u'Takykardi, palpitationer, perifera \xf6dem'],
             ['Vascular', u'Blodvallning'],
             ['Respiratory',
              u'Anstr\xe4ngning sutl\xf6st dyspn\xe9, epistaxis, nasofaryngit, t\xe4ppta bih\xe5lor, n\xe4st\xe4ppa, rinit, halsont'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi, dysfagi, muns\xe5r, gingival bl\xf6dning, glossit, stomatit, flatulens, f\xf6rstoppning, muntorrhet'],
             ['Skin',
              u'Utslag, \xf6kad svettning, psoriasis, urtikaria, eksem, hudsjuk-dom ar, fotosensitivi-t etsreaktion, nattliga svettningar'],
             ['Musculoskeletal',
              u'Ryggsm\xe4rta, artrit, muskelsvag-h et, bensm\xe4rta, nacksm\xe4rta, muskulo-skel etal sm\xe4rta, muskel-kram per'],
             ['Reproductive system', u'Impotens'],
             ['General',
              u'Br\xf6stsm\xe4rta, influensalik-n ande symtom, sjukdoms-k\xe4n sla, letargi, blodvallning-ar, t\xf6rst'],
             ['Investigations', u'Viktminsk-ni ng']]],
           ['Uncommon',
            [['Infections',
              u'Nedre luftv\xe4gsinfek-tion, urinv\xe4gsin-fe ktion, hudinfektion,'],
             ['Neoplasms', u'Levertum\xf6r'],
             ['Immune system', u'Sarkoidos, tyroidit'],
             ['Endocrine', u'Diabetes'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Sj\xe4lvmords-ta nkar, hallucina-tion er, ilska'],
             ['Nervous system', u'Perifer neuropati'],
             ['Eye', u'Retinal bl\xf6dning'],
             ['Ear', u'H\xf6rselned-s\xe4t tning'],
             ['Vascular', u'Hypertension Cerebral'],
             ['Respiratory', u'V\xe4sande andning'],
             ['GI', u'Gastrointesti-nal bl\xf6dning, keilit, gingivit'],
             ['Hepato', u'Nedsatt leverfunktion']]],
           ['Rare',
            [['Infections', u'Endokardit, extern otit'],
             ['Blood', u'Pancytopeni'],
             ['Immune system', u'Anafylaxi, systemisk lupus erythematosus, reumatoid artrit'],
             ['Psychiatric', u'Sj\xe4lvmord, psykotisk st\xf6rning'],
             ['Nervous system', u'Koma, konvulsioner, ansiktsf\xf6r-lamn ing'],
             ['Eye',
              u'Optisk neuropati, papill\xf6dem, retinal k\xe4rlf\xf6r\xe4ndring, retinopati, korneals\xe5r'],
             ['Cardiac',
              u'Hj\xe4rtinfarkt, kronisk hj\xe4rtinsuffici-e ns, angina, supraventriku-l \xe4r takykardi, arrytmi, f\xf6rmaks-flimm er, perikardit'],
             ['Vascular', u'bl\xf6dning'],
             ['Respiratory', u'Interstitiell pneumonit med d\xf6dlig utg\xe5ng, lungemboli'],
             ['GI', u'Peptiskt s\xe5r, pankreatit'],
             ['Hepato', u'Leversvikt, kolangit, fettlever'],
             ['Musculoskeletal', u'Myosit']]],
           ['Very rare',
            [['Blood', u'Aplastisk anemi'],
             ['Immune system', u'Idiopatisk eller trombotisk trombocyto-p en purpura'],
             ['Eye', u'Synf\xf6rlust'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-John son syndrom, angio\xf6dem, erythema multiforme']]],
           ['Unknown',
            [['Blood', u'Ren erytrocyt-apla'],
             ['Immune system',
              u'Transplan-tat avst\xf6tning av lever och njure, Vogt-Koyana gi-Harada-sy ndrom'],
             ['Psychiatric', u'Mani, bipol\xe4ra sjukdomar, mordtankar'],
             ['Eye', u'Allvarlig n\xe4thinne-avlo ssning'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Renal', u'Njursvikt, nefrotiskt syndrom']]]],
 '_note': u' ?MSFU',
 '_pages': [12, 15],
 u'_rank': 60,
 u'_type': u'MSFU'}