{'_data': [['Very common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Depression, insomnia'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, koncentrations-sv\xe5righeter'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Diarr\xe9, illam\xe5ende, buksm\xe4rta'],
             ['Skin', u'Alopeci, dermatit, kl\xe5da, torr hud'],
             ['General',
              u'Feber, stelhet, sm\xe4rta, asteni, tr\xf6tthet, reaktion p\xe5 injektions-st\xe4llet, irritabilitet']]],
           ['Common',
            [['Infections',
              u'\xd6vre luftv\xe4gsinfektion, bronkit, candidainfektion i munnen, herpes simplex'],
             ['Blood', u'Trombocytopeni, lymfadenopati'],
             ['Endocrine', u'Hypotyroidism, hypertyroidism'],
             ['Psychiatric',
              u'Hum\xf6rf\xf6r\xe4ndringar, k\xe4nslom\xe4ssiga st\xf6rningar, \xe5ngest, aggression, nervositet, s\xe4nkt libido'],
             ['Nervous system',
              u'Minnesf\xf6rs\xe4mring synkope, svaghet, migr\xe4n, hypoestesi, hyperestesi, parestesier, tremor, smakf\xf6r\xe4ndring, mardr\xf6mmar, somnolens'],
             ['Eye', u'Dimsyn, \xf6gonsm\xe4rta, \xf6goninflammation, xeroftalmi'],
             ['Ear', u'Vertigo, \xf6ronsm\xe4rta'],
             ['Cardiac', u'Takykardi, palpitationer, perifera \xf6dem'],
             ['Vascular', u'Blodvallning'],
             ['Respiratory',
              u'Anstr\xe4ngningsutl\xf6st dyspn\xe9, epistaxis, nasofaryngit, t\xe4ppta bih\xe5lor, n\xe4st\xe4ppa, rinit, halsont'],
             ['GI',
              u'Kr\xe4kningar, dyspepsi, dysfagi, muns\xe5r, gingival bl\xf6dning, glossit, stomatit, flatulens, f\xf6rstoppning, muntorrhet'],
             ['Skin',
              u'Utslag, \xf6kad svettning, psoriasis, urtikaria, eksem, hudsjukdomar, fotosensitivitets-reaktion, nattliga svettningar'],
             ['Reproductive system', u'Impotens'],
             ['General',
              u'Br\xf6stsm\xe4rta, influensaliknande symtom, sjukdomsk\xe4nsla, letargi, blodvallningar, t\xf6rst'],
             ['Investigations', u'Viktminskning']]],
           ['Uncommon',
            [['Infections', u'Nedre luftv\xe4gsinfektion, urinv\xe4gsinfektion, hudinfektion,'],
             ['Neoplasms', u'Levertum\xf6r'],
             ['Immune system', u'Sarkoidos, tyroidit Idiopatisk eller'],
             ['Endocrine', u'Diabetes'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Sj\xe4lvmordstankar, hallucinationer, ilska'],
             ['Nervous system', u'Perifer neuropati'],
             ['Eye', u'Retinal bl\xf6dning'],
             ['Ear', u'H\xf6rselneds\xe4ttning'],
             ['Vascular', u'Hypertension'],
             ['Respiratory', u'V\xe4sande andning'],
             ['GI', u'Gastrointestinal bl\xf6dning, keilit, gingivit'],
             ['Hepato', u'Nedsatt leverfunktion'],
             ['Skin', u'angio\xf6dem,']]],
           ['Rare',
            [['Infections', u'Endokardit, extern'],
             ['Blood', u'Pancytopeni'],
             ['Immune system', u'Anafylaxi, systemisk lupus erythematosus, reumatoid artrit'],
             ['Psychiatric', u'Sj\xe4lvmord, psykotisk st\xf6rning'],
             ['Nervous system', u'Koma, konvulsioner, ansiktsf\xf6rlamning'],
             ['Eye',
              u'Optisk neuropati, papill\xf6dem, retinal k\xe4rlf\xf6r\xe4ndring, retinopati, korneals\xe5r'],
             ['Cardiac',
              u'Hj\xe4rtinfarkt, kronisk hj\xe4rtinsufficiens, angina, supraventrikul\xe4r takykardi, arrytmi, f\xf6rmaksflimmer, perikardit'],
             ['Vascular', u'Cerebral bl\xf6dning'],
             ['Respiratory', u'Interstitiell pneumonit med d\xf6dlig utg\xe5ng, lungemboli'],
             ['GI', u'Peptiskt s\xe5r, pankreatit'],
             ['Hepato', u'Leversvikt, kolangit, fettlever']]],
           ['Very rare',
            [['Blood', u'Aplastisk anemi'],
             ['Immune system', u'trombotisk trombocytopen purpura'],
             ['Eye', u'Synf\xf6rlust'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnson syndrom, erythema multiforme']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 13],
 u'_rank': 52,
 u'_type': u'MSFU'}