{'_data': [['Common',
            [['Cardiac', u' Bradykardi (vanligen m\xe5ttlig).'],
             ['Vascular',
              u' Hypotension (vanligen m\xe5ttlig och \xf6verg\xe5ende). Fall av sv\xe5r hypotension eller kollaps har rapporterats efter \xf6verdosering eller f\xf6r snabb injektion.'],
             ['General',
              u' Reaktioner p\xe5 injektionsst\xe4llet som sm\xe4rta, erytem, \xf6dem, nekros, extravasation, infiltration, induration, tromboflebit, flebit, cellulit, infektion, pigmentf\xf6r\xe4ndringar.']]],
           ['Very rare',
            [['Immune system', u' Anafylaktisk chock.'],
             ['Nervous system',
              u' F\xf6rh\xf6jt benignt intrakraniellt tryck (pseudo-tumor cerebri), huvudv\xe4rk. '],
             ['Cardiac', u' Uttalad bradykardi, sinusarrest som kr\xe4ver att'],
             ['Respiratory',
              u' Interstitiell pneumonit (se avsnitt 4.4), sv\xe5ra respiratoriska komplikationer (ARDS), ibland fatala (se avsnitt 4.4 och 4.5), bronkospasm och/eller apn\xe9 hos patienter med sv\xe5r respirationssvikt, speciellt hos astmapatienter.'],
             ['GI', u' Illam\xe5ende.'],
             ['Hepato',
              u' Isolerad f\xf6rh\xf6jning av serumtransaminaser som vanligen \xe4r m\xe5ttlig (1,5 till 3 g\xe5nger det normala) i b\xf6rjan av behandlingen. V\xe4rdena kan normaliseras vid dosreduktion eller till och med spontant. Akut leverp\xe5verkan med f\xf6rh\xf6jda serumtransaminaser och/eller ikterus, n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4).'],
             ['General', u' Flush/v\xe4rmek\xe4nsla, svettning. ']]],
           ['Unknown',
            [['Endocrine', u' Hypertyreoidism. '],
             ['Cardiac', u' torsade de pointes (se avsnitt 4.4 och 4.5)'],
             ['Musculoskeletal', u' Ryggsm\xe4rta.  ']]]],
 '_pages': [7, 8],
 u'_rank': 13,
 u'_type': u'LSFU2'}