{'_data': [['Very common',
            [['Eye',
              u' Mikroavlagringar i cornea, vanligtvis begr\xe4nsade till omr\xe5det under pupillen. De \xe4r i s\xe4llsynta fall f\xf6rknippade med f\xe4rgade halos i bl\xe4ndande ljus eller dimsyn. Mikroavlagringar i cornea best\xe5r av komplexa lipidavlagringar och \xe4r reversibla efter att behandlingen upph\xf6rt.'],
             ['GI',
              u' Milda gastrointestinala st\xf6rningar (illam\xe5ende, kr\xe4kningar, smakrubbbningar) som vanligen upptr\xe4der under uppladdningsfasen och avtar vid dosreduktion.'],
             ['Hepato',
              u' Isolerad f\xf6rh\xf6jning av serumtransaminaser som vanligen \xe4r m\xe5ttlig (1,5 till 3 g\xe5nger det normala) i b\xf6rjan av behandlingen (se avsnitt 4.4). V\xe4rdena kan normaliseras vid dosreduktion eller till och med spontant.'],
             ['Skin', u' Fotosensivitet (se avsnitt 4.4).']]],
           ['Common',
            [['Endocrine',
              u' Hypotyreoidism, hypertyreoidism i n\xe5gra fall d\xf6dlig (se avsnitt 4.4).'],
             ['Metabolism', u' Anorexi. '],
             ['Nervous system',
              u' Extrapyramidal tremor, mardr\xf6mmar, s\xf6mnst\xf6rningar.'],
             ['Cardiac', u' Bradykardi, vanligtvis m\xe5ttlig och dosrelaterad.'],
             ['Respiratory',
              u' Lungtoxicitet (alveol\xe4r/interstitiell pneumonit eller fibros, pleurit, bronchiolitis obliterans/BOOP) i n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4).'],
             ['Hepato',
              u'Akut leverp\xe5verkan med f\xf6rh\xf6jda serumtransaminaser och/eller'],
             ['Skin',
              u' Skiffergr\xe5 eller bl\xe5aktig missf\xe4rgning av huden vid l\xe5ngtidsbehandling med h\xf6ga dagliga doser. S\xe5dana pigmenteringar f\xf6rsvinner sakta efter att behandlingen upph\xf6rt.'],
             ['Musculoskeletal', u' Proximal muskelsvaghet.  '],
             ['General', u' Tr\xf6tthet, yrsel.    ']]],
           ['Uncommon',
            [['Nervous system',
              u' Perifer sensorisk/motorisk neuropati och/eller myopati, vanligen reversibel efter uts\xe4ttande av preparatet (se avsnitt 4.4).'],
             ['Cardiac', u'Upptr\xe4dande av ny eller f\xf6rv\xe4rrande av existerande']]],
           ['Very rare',
            [['Blood', u' Trombocytopeni, hemolytisk anemi, aplastisk anemi. '],
             ['Endocrine', u'SIADH (inadekvat ADH-produktion).'],
             ['Nervous system',
              u'Cerebellar ataxi, f\xf6rh\xf6jt benignt intrakranialt tryck (pseudo-tumor cerebri), huvudv\xe4rk.'],
             ['Eye', u'Optikusneuropati/neurit som kan leda till blindhet (se avsnitt 4.4).'],
             ['Cardiac', u'Uttalad bradykardi eller sinusarrest hos patienter med'],
             ['Vascular', u' Vaskulit.'],
             ['Respiratory',
              u'Bronkialspasm hos patienter med sv\xe5r respirationssvikt och s\xe4rskilt hos patienter med astma. Akut adult'],
             ['Hepato',
              u'Kronisk leverp\xe5verkan (pseudoalkoholhepatit, cirrhos), ibland med d\xf6dlig utg\xe5ng (se avsnitt 4.4).'],
             ['Skin',
              u'Alopeci, erytem vid r\xf6ntgenbehandling, hudutslag vanligtvis ospecifik, exfoliativ dermatit.'],
             ['Renal', u' Kreatininf\xf6rh\xf6jning. '],
             ['Reproductive system', u' Epididymit, impotens.  ']]],
           ['Unknown',
            [['Cardiac', u'torsade de pointes (se avsnitt 4.4 och 4.5)'],
             ['Respiratory', u'Lungbl\xf6dning.']]]],
 '_pages': [8, 10],
 u'_rank': 28,
 u'_type': u'LSFU2'}