{'_data': [['Very common',
            [['Eye', u': br\xe4nnande och stickande k\xe4nsla  '],
             ['GI', u': smakf\xf6r\xe4ndringar  ']]],
           ['Common',
            [['Eye',
              u': konjunktival injektion, dimsyn, korneal erosion, \xf6gonkl\xe5da, \xf6kat t\xe5rfl\xf6de  '],
             ['Eye', u': \xf6gonlocksinflammation*, \xf6gonlocksirritation*  '],
             ['Eye',
              u': tecken och symtom p\xe5 okul\xe4r irritation inkluderande blefarit*, keratit*, minskad korneal  '],
             ['Respiratory', u': sinuit  '],
             ['GI', u': illam\xe5ende*  '],
             ['Reproductive system', u': asteni/tr\xf6tthet*  ']]],
           ['Uncommon',
            [['Eye', u': iridocyklit*  '], ['Reproductive system', u': asteni/tr\xf6tthet*  ']]],
           ['Rare',
            [['Eye',
              u': irritation med rodnad*, sm\xe4rta*, bel\xe4ggningar p\xe5 \xf6gonlocken*, \xf6verg\xe5ende myopati (f\xf6rsvann  '],
             ['Ear', u': tinnitus*  '],
             ['Respiratory', u': andn\xf6d, respiratorisk insufficiens, rinit  '],
             ['Skin', u': kontaktdermatit  '],
             ['Reproductive system', u': Peyronies sjukdom*  '],
             ['Reproductive system',
              u': tecken och symtom p\xe5 systemiska allergiska reaktioner inklusive angio\xf6dem, urtikaria,  ']]],
           ['Unknown', [['Reproductive system', u': Sexuell dysfunktion.  ']]]],
 '_pages': [5, 8],
 u'_rank': 17,
 u'_type': u'LSFU3'}