{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk, yrsel, vertigo, parestesier'],
             ['Eye', u'synrubbningar'],
             ['Ear', u'tinnitus'],
             ['Vascular', u'hypotoni och effekter relaterade till hypotoni'],
             ['Respiratory', u'hosta, dyspn\xe9'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning, buksm\xe4rta, dysgeusi, dyspepsi, diarr\xe9, f\xf6rstoppning'],
             ['Skin', u'utslag, kl\xe5da'],
             ['Musculoskeletal', u'muskelkramper'],
             ['General', u'asteni']]],
           ['Uncommon',
            [['Psychiatric', u'hum\xf6r- eller s\xf6mnst\xf6rningar'],
             ['Respiratory', u'bronkialspasm'],
             ['GI', u'muntorrhet'],
             ['Skin',
              u'angio\xf6dem i ansikte, extremiteter, l\xe4ppar, slemhinnor, tunga, glottis och/eller larynx, urtikaria (se avsnitt 4.4).'],
             ['Renal', u'njurinsufficiens'],
             ['Reproductive system', u'impotens'],
             ['General', u'svettning']]],
           ['Very rare',
            [['Blood',
              u'rapporter om nedg\xe5ng av hemoglobin och hematokrit, trombocytopeni, leukopeni/neutropeni och fall av agranulocytos eller pancytopeni. Hos patienter med en medf\xf6dd brist p\xe5 G-6PDH har mycket s\xe4llsynta fall av hemolytisk anemi rapporterats (se avsnitt 4.4).'],
             ['Nervous system', u'f\xf6rvirring'],
             ['Vascular',
<<<<<<< HEAD
              u'stroke, m\xf6jligen sekund\xe4rt till kraftig hypotoni hos h\xf6griskpatienter (se avsnitt 4.4).'],
=======
              u'stroke, m\xf6jligen sekund\xe4rt till kraftig hypotoni hos h\xf6griskpatienter (se avsnitt 4.4). : vaskulit'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Cardiac',
              u'arytmi, angina pectoris och myokardinfarkt, m\xf6jligen sekund\xe4rt till kraftig hypotoni hos h\xf6griskpatienter (se avsnitt 4.4).'],
             ['Respiratory', u'eosinofil pneumoni, rinit'],
             ['GI', u'pankreatit'],
             ['Hepato', u'hepatit, antingen cytolytisk eller kolestatisk (se avsnitt 4.4).'],
             ['Skin', u'erytema multiforme'],
             ['Renal', u'akut njursvikt']]],
           ['Unknown',
            [['Metabolism', u'hypoglykemi (se avsnitten 4.4 och 4.5)'],
<<<<<<< HEAD
             ['Vascular', u'vaskulit'],
             ['Investigations',
              u'\xd6kningar av blodurea och plasmakreatinin, hyperkalemi som \xe4r reversibel vid avbrott kan f\xf6rekomma, s\xe4rskilt vid njurinsufficiens, allvarlig hj\xe4rtsvikt och renovaskul\xe4r hypertoni. F\xf6rh\xf6jning av leverenzymer och serumbilirubin har rapporterats i s\xe4llsynta fall. Kliniska pr\xf6vningar: Under Europastudiens randomiserade period registrerades endast allvarliga biverkningar. F\xe5 patienter fick allvarliga biverkningar: 16 (0,3%) av de 6122 perindoprilpatienterna och 12 (0,2%) av de 6107 placebopatienterna. Hos perindoprilbehandlade patienter observerades hypotension hos 6 patienter, angio\xf6dem hos 3 patienter och pl\xf6tsligt hj\xe4rtstillest\xe5nd hos 1 patient. Fler patienter som fick perindopril avbr\xf6t studien p\xe5 grund av hosta, hypotension eller annan intolerans j\xe4mf\xf6rt med placebopatienter, 6,0% (n=366) respektive 2,1% (n=129).']]]],
 '_pages': [7, 9],
 u'_rank': 28,
=======
             ['Investigations',
              u'\xd6kningar av blodurea och plasmakreatinin, hyperkalemi som \xe4r reversibel vid avbrott kan f\xf6rekomma, s\xe4rskilt vid njurinsufficiens, allvarlig hj\xe4rtsvikt och renovaskul\xe4r hypertoni. F\xf6rh\xf6jning av leverenzymer och serumbilirubin har rapporterats i s\xe4llsynta fall. Kliniska pr\xf6vningar: Under Europastudiens randomiserade period registrerades endast allvarliga biverkningar. F\xe5 patienter fick allvarliga biverkningar: 16 (0,3%) av de 6122 perindoprilpatienterna och 12 (0,2%) av de 6107 placebopatienterna. Hos perindoprilbehandlade patienter observerades hypotension hos 6 patienter, angio\xf6dem hos 3 patienter och pl\xf6tsligt hj\xe4rtstillest\xe5nd hos 1 patient. Fler patienter som fick perindopril avbr\xf6t studien p\xe5 grund av hosta, hypotension eller annan intolerans j\xe4mf\xf6rt med placebopatienter, 6,0% (n=366) respektive 2,1% (n=129).']]]],
 '_pages': [7, 9],
 u'_rank': 27,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}