{'_data': [['Unknown',
            [['Blood', u'Minskad procentandel lymfocyter.'],
             ['Immune system',
              u'Allergiska reaktioner omfattande angioneurotiskt \xf6dem, hudutslag, urtikaria och kl\xe5da.'],
             ['Psychiatric', u'Rastl\xf6shet.'],
             ['Nervous system', u'F\xf6rs\xe4mrat minne; yrsel.'],
             ['Eye', u'Svullnad, irritation, r\xf6dhet.'],
             ['Cardiac',
              u'Ventrikul\xe4r extrasystole. En \xf6kad hj\xe4rtfrekvens observerades hos cyanidf\xf6rgiftade patienter.'],
             ['Vascular',
              u'\xd6verg\xe5ende h\xf6jning av blodtrycket som vanligen normaliseras efter n\xe5gra timmar; v\xe4rmevallning. En s\xe4nkning av blodtrycket observerades hos cyanidf\xf6rgiftade patienter.'],
             ['Respiratory',
              u'Pleurautgjutning, dyspn\xe9, tr\xe5nghetsk\xe4nsla i strupen, halstorrhet, obehag i br\xf6stet.'],
             ['GI',
              u'Obehag i buken, dyspepsi, diarr\xe9, kr\xe4kningar, illam\xe5ende, dysfagi.'],
             ['Skin',
              u'Reversibel r\xf6df\xe4rgning av hud och slemhinnor (se ovan). Pustul\xf6sa hudutslag som kan kvarst\xe5 i flera veckor och som fr\xe4mst drabbar ansikte och hals.'],
             ['Renal', u'Kromaturi (se ovan).'],
             ['General', u'Huvudv\xe4rk; reaktion vid injektionsst\xe4llet; perifert \xf6dem.'],
             ['Investigations',
              u'Cyanokit kan orsaka r\xf6d missf\xe4rgning av plasman, vilken kan orsaka artificiell h\xf6jning eller s\xe4nkning av niv\xe5erna f\xf6r vissa laboratorieparametrar (se avsnitt 4.4).']]]],
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'LSFU'}