{'_data': [['Common',
            [['General', u' Feber.  '],
             ['Vascular', u' Takykardi.  '],
             ['Nervous system', u' Konfusion, hallucinationer, excitation. '],
             ['GI', u' Obstipation. '],
             ['Skin', u' Ansiktsrodnad. '],
             ['Eye',
              u' Sveda vid instillation, f\xf6rs\xe4mrat n\xe4rseende, ljusk\xe4nslighet. ']]],
           ['Uncommon',
            [['General', u' Allergiska reaktioner.  '],
             ['GI', u' Muntorrhet.  '],
             ['Reproductive system', u' Miktionsbesv\xe4r. ']]],
           ['Rare', [['Eye', u' Akut glaukom.  ']]]],
 '_pages': [2, 2],
 u'_rank': 10,
 u'_type': u'DFSU'}