{'_data': [['Very common', [['General', u'Pyrexi']]],
           ['Common',
            [['Metabolism', u'Hypokalcemi**'],
             ['Musculoskeletal', u'Skelettsm\xe4rta'],
             ['Infections', u'Infektion'],
             ['Endocrine', u'Parathyreoideas t\xf6rning'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, dysgeusi (smakrubbning)'],
             ['Eye', u'Katarakt'],
             ['Cardiac', u'Grenblock'],
             ['Respiratory', u'Faryngit Diarr\xe9, kr\xe4kningar,'],
             ['GI', u'dyspepsi, gastrointestinal sm\xe4rta, tandp\xe5verkan'],
             ['Skin', u'Hudp\xe5verkan, ekkymos'],
             ['Musculoskeletal', u'Artros, myalgi, artralgi, ledbesv\xe4r'],
             ['General',
              u'Influensaliknan de sjukdom, perifert \xf6dem, asteni, \xf6verdriven t\xf6rst F\xf6rh\xf6jt']]],
           ['Uncommon',
            [['Musculoskeletal', u'Myalgi'],
             ['General', u'Influenslikna nde sjukdom**, rigor'],
             ['Infections', u'Cystit, vaginit, oral candidainfektion'],
             ['Neoplasms', u'Benign hudneoplasm'],
             ['Blood', u'Anemi, bloddyskrasi'],
             ['Metabolism', u'Hypofosfatemi'],
             ['Psychiatric',
              u'S\xf6mnrubbningar, oro, k\xe4nslom\xe4ssig instabilitet Cerebrovaskul\xe4r sjukdom, nervrotsskada,'],
             ['Nervous system',
              u'amnesi, migr\xe4n, neuralgi, hypertoni, hyperestesi, parestesi runt munnen, onormal luktf\xf6rnimmelse'],
             ['Ear', u'D\xf6vhet Myokardiell ischemi,'],
             ['Cardiac', u'kardiovaskul\xe4r sjukdom, palpitationer'],
             ['Respiratory',
              u'Lung\xf6dem, v\xe4sande andningsljud (stridor) Gastroenterit, gastrit,'],
             ['GI', u'muns\xe5r, dysfagi, keilit'],
             ['Hepato', u'Gallsten (kolelitiasis)'],
             ['Skin', u'Utslag, alopeci'],
             ['Renal', u'Urinretention, renal cysta'],
             ['Reproductive system', u'Sm\xe4rta i b\xe4ckenet'],
             ['General', u'Hypotermi F\xf6rh\xf6jt alkaliskt']]],
           ['Rare',
            [['Skin', u'Angio\xf6dem'],
             ['Nervous system', u'Okul\xe4ra'],
             ['Eye', u'inflammationer\u2020* *']]],
           ['Very rare',
            [['Infections', u'L\xe4kemedelsverket 2011-12-09'],
             ['Musculoskeletal', u'Osteonekros i k\xe4ken\u2020**']]]],
 '_note': u' ANOMALI in Headers ?MSFU',
 '_pages': [5, 8],
 u'_rank': 35,
 u'_type': u'MSFU'}