{'_data': [['Very common', [['Blood', u'DepoCyte  '], ['Blood', u'Cytarabin  ']]],
           ['Common',
            [['Nervous system', u'f\xf6rvirring'],
             ['GI', u'tr\xf6tthet Cytarabin Mycket vanliga: svaghet, pyrexi, tr\xf6tthet'],
             ['Renal', u'sm\xe4rta Cytarabin Mycket vanliga: svaghet'],
             ['Renal', u'sm\xe4rta'],
             ['Nervous system',
              u'konvulsioner, f\xf6rv\xe4rvad hydrocephalus, pleocytos i cerebrospinalv\xe4tskan'],
             ['Nervous system',
              u'konvulsioner, f\xf6rv\xe4rvad hydrocephalus, meningism Cytarabin (n = 99 behandlingscykler) Mycket vanliga: huvudv\xe4rk'],
             ['Nervous system', u'konvulsioner, meningism']]],
           ['Uncommon',
            [['Nervous system',
              u'(\u2265 1/1 000 till < 1/100). Inom varje frekvensintervall anges biverkningarna efter fallande allvarlighetsgrad.'],
             ['Nervous system',
              u'meningism Metotrexat (n = 258 behandlingscykler) Mycket vanliga: huvudv\xe4rk'],
             ['Musculoskeletal',
              u'nackstelhet Cytarabin (n = 99 behandlingscykler) Vanliga: ryggsm\xe4rta, nacksm\xe4rta, nackstelhet Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet DepoCyte (n = 929 behandlingscykler) Mycket vanliga: pyrexi Metotrexat (n = 258 behandlingscykler) Vanliga: pyrexi Cytarabin (n = 99 behandlingscykler) Mycket vanliga: pyrexi']]],
           ['Unknown',
            [['GI',
              u'diarr\xe9, kr\xe4kningar, illam\xe5ende Cytarabin Mycket vanliga: diarr\xe9, kr\xe4kningar, illam\xe5ende Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet DepoCyte Mycket vanliga: svaghet, pyrexi'],
             ['Nervous system',
              u'DepoCyte kan orsaka allvarlig neurologisk toxicitet. Intratekal administrering av cytarabin kan orsaka myelopati (3 %) och annan neurologisk toxicitet, vilket ibland leder till best\xe5ende neurologiskt bortfallssymtom. Allvarlig toxicitet i centrala nervsystemet, inklusive ih\xe5llande konvulsioner (7 %), extrem somnolens (3 %), hemiplegi (1 %), synrubbningar inklusive blindhet (1 %), d\xf6vhet (3 %) och kranialnervspareser (3 %) har rapporterats efter intratekal administrering av DepoCyte. Symptom och tecken p\xe5 perifer neuropati, s\xe5som sm\xe4rta (1 %), domning (3 %), parestesi (3 %), hypoestesi (2 %), svaghet (13 %) och f\xf6rs\xe4mrad tarm- (3 %) och bl\xe5skontroll (inkontinens) (1 %) har ocks\xe5 observerats. I vissa fall har denna kombination av neurologiska tecken och symptom rapporterats som cauda equina-syndrom (3 %). Biverkningar som eventuellt \xe5terspeglar neurotoxicitet listas i tabell 2 enligt MedDRAs organsystemklass och frekvensindelning: Mycket vanliga (\u22651/10), Vanliga (\u22651/100 till < 1/10),'],
             ['Psychiatric', u'somnolens Cytarabin Vanliga: somnolens'],
             ['Nervous system',
              u'cauda equina-syndrom, konvulsioner, kranialnervspareser, hypoestesi, myelopati, parestesi, hemiplegi, domning Cytarabin Vanliga: cauda equina-syndrom, konvulsioner, kranialnervspareser, hypoestesi, myelopati, parestesi, hemiplegi, domning'],
             ['Eye', u'synrubbningar, blindhet Cytarabin Vanliga: synrubbningar, blindhet'],
             ['Ear', u'd\xf6vhet Cytarabin Vanliga: d\xf6vhet'],
             ['GI',
              u'f\xf6rs\xe4mrad tarmkontroll Cytarabin Vanliga: f\xf6rs\xe4mrad tarmkontroll'],
             ['Renal',
              u'urininkontinens Cytarabin Vanliga: urininkontinens Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet DepoCyte Mycket vanliga: svaghet'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI',
              u'kr\xe4kningar, illam\xe5ende Metotrexat (n = 258 behandlingscykler) Mycket vanliga: kr\xe4kningar, illam\xe5ende Cytarabin (n = 99 behandlingscykler) Mycket vanliga: kr\xe4kningar, illam\xe5ende'],
             ['Musculoskeletal',
              u'ryggsm\xe4rta, nacksm\xe4rta, nackstelhet Metotrexat (n = 258 behandlingscykler) Vanliga: ryggsm\xe4rta, nacksm\xe4rta']]]],
 '_pages': [4, 6],
 u'_rank': 23,
 u'_type': u'LSFU'}