{'_data': [['Common',
            [['Nervous system', u'Nedst\xe4mdhet, huvudv\xe4rk, oro'],
             ['GI', u'Illam\xe5ende, buksm\xe4rtor eller -obehag'],
             ['Skin', u'Acne, alopeci, exantem'],
             ['Musculoskeletal', u'Ben- eller ryggsm\xe4rtor, artralgi'],
             ['Metabolism', u'Viktuppg\xe5ng'],
             ['General', u'Kraftl\xf6shet'],
             ['Reproductive system',
              u'Oregelbundna bl\xf6dningar, amenorr\xe9, br\xf6stsp\xe4nningar'],
             ['Psychiatric',
              u'P\xe5verkan p\xe5 libido, s\xf6mnl\xf6shet Cancer De vanligaste biverkningarna \xe4r svettningar, "m\xe5nansikte" och tremor. Dessa biverkningar upptr\xe4der fr\xe4mst d\xe5 Depo-Provera ges i h\xf6ga doser.'],
             ['Nervous system', u'Svettningar, tremor'],
             ['Endocrine', u'\u201dM\xe5nansikte\u201d'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['General',
              u'\xd6demtendens, feber, lokala reaktioner p\xe5 injektionsst\xe4llet']]],
           ['Uncommon',
            [['General', u'Feber'],
             ['Vascular', u'Tromboflebiter'],
             ['Reproductive system', u'Vaginala bl\xf6dningar']]],
           ['Rare',
            [['Musculoskeletal',
              u'Osteoporos inklusive bensk\xf6rhetsfrakturer (hos patienter som f\xe5tt MPA intramuskul\xe4rt)']]],
           ['Unknown',
            [['General', u'Anafylaktiska reaktioner'], ['Hepato', u'\xd6kade leverv\xe4rden']]]],
 '_pages': [4, 5],
 u'_rank': 18,
 u'_type': u'LSFU'}