{'_data': [[u'Unknown',
            [['Psychiatric', u'Hallucinationer'],
             ['Nervous system', u'Yrsel, somnolens, insomni, psykomotorisk'],
             ['Cardiac', u'Takykardi, palpitationer'],
             ['GI', u'Buksm\xe4rtor, nausea, kr\xe4kningar, dyspepsi, diarr\xe9'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jt bilirubin, hepatit'],
             ['Musculoskeletal', u'Myalgi'],
             ['General', u'angio\xf6dem, dyspn\xe9, pruritus, hudutslag och']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'LFSU'}