{'_data': [['Common',
            [['Psychiatric', u'Hum\xf6rsv\xe4ngningar, minskad libido'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Acne'],
             ['Reproductive system',
              u'Sm\xe4rtor i br\xf6sten, oregelbundna bl\xf6dningar, amenorr\xe9'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'Vaginal infektion'],
             ['Eye', u'Kontaktlins intolerans'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'Alopecia'],
             ['Reproductive system', u'Dysmenorr\xe9, ovariecystor'],
             ['General', u'Tr\xf6tthet']]],
           ['Rare', [['Skin', u'Utslag, urticaria, erythema nodosum']]]],
 '_note': u' ?MSFU ANOMALI in Headers ANOMALI in Headers',
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'MSFU'}