{'_data': [['Common',
            [['Psychiatric', u'Hum\xf6rsv\xe4ngningar, nedst\xe4mdhet, nedsatt libido'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Akne'],
             ['Reproductive system',
              u'Sm\xe4rtor i br\xf6sten, oregelbundna bl\xf6dningar, amenorr\xe9'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'Vaginal infektion'],
             ['Eye', u'Kontaktlins intolerans'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'Alopeci'],
             ['Reproductive system', u'Dysmenorr\xe9, ovariecystor'],
             ['General', u'Tr\xf6tthet']]],
           ['Rare', [['Skin', u'Utslag, urtikaria, erythema nodosum']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 13,
 u'_type': u'MSFU'}