{'_data': [['Very common',
            [['Cardiac', u'Bradykardi *'], ['Vascular', u'Hypotension *, hypertoni *']]],
           ['Common',
            [['Metabolism', u'Hyperglykemi, hypoglykemi'],
             ['Psychiatric', u'Agitation'],
             ['Cardiac', u'Myokard ischemi eller hj\xe4rtinfarkt, takykardi'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, muntorrhet'],
             ['General', u'Abstinenssyndrom, hypertermi']]],
           ['Uncommon',
            [['Metabolism', u'Metabolisk acidos, hypoalbuminemi 5'],
             ['Psychiatric', u'Hallucination'],
             ['Cardiac', u'AV-Block I, minskad hj\xe4rtminutvolym'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Svullen buk'],
             ['General', u'L\xe4kemedlet ineffektivt, t\xf6rst']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'LSFU'}