{'_data': [['Common',
            [['Metabolism', u'metabolisk acidos'],
             ['Nervous system', u'yrsel'],
             ['GI', u'smak-st\xf6rningar'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Metabolism', u'urinsyra-stegring'],
             ['Nervous system', u'parestesier kramper'],
             ['GI', u'illam\xe5-ende kr\xe4kningar'],
             ['Skin', u'kl\xe5da'],
             ['Renal', u'njursten'],
             ['General', u'feber asteni']]],
           ['Rare',
            [['Blood', u'aplastisk anemi agranulocytos leukopeni trombocytopeni'],
             ['Immune system', u'anafylaktisk chock'],
             ['Metabolism', u'hypokalemi'],
             ['Nervous system', u'f\xf6rslappad paralys'],
             ['Eye', u'myopi'],
             ['Ear', u'tinnitus'],
             ['GI', u'diarr\xe9'],
             ['Hepato', u'hepatit gulsot fulminant levernekros'],
             ['Skin',
              u'erythema multiformae Stevens-Johnsons syndrom toxisk epidermal nekrolys ljusk\xe4nslighet hirsutism']]],
           ['Unknown',
            [['Blood', u'trombocytopenisk purpura benm\xe4rgsdepression pancytopeni'],
             ['Immune system', u'anafylaxi'],
             ['Endocrine', u'hyperglykemi hypoglykemi osteomalaci'],
             ['Metabolism', u'hyponatremi'],
             ['Psychiatric', u'depression'],
             ['Nervous system',
              u'f\xf6rvirring irritation upphetsning huvudv\xe4rk ataxi d\xe5sighet s\xf6mnighet'],
             ['Ear', u'f\xf6rs\xe4mrad h\xf6rsel'],
             ['GI', u'malaena'],
             ['Hepato', u'onormal leverfunktion'],
             ['Skin', u'urtikaria'],
             ['Renal',
              u'njursvikt kristalluri stenbildning hematuri glukosuri polyuri njur-och uret\xe4r kolik njurskador'],
             ['General', u'rodnad minskad libido t\xf6rst']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 31,
 u'_type': u'MSFU'}