{'_data': [['Very common', [['Eye', u'Synst\xf6rningar, dimsyn, dubbelseende.']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['Ear', u'Svindelk\xe4nsla.'],
             ['GI',
              u'Epigastrisk sm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta, dyspepsi, flatulens, anorexi.'],
             ['Hepato', u'Transaminasstegringar (ASAT, ALAT).'],
             ['Skin', u'Utslag']]],
           ['Uncommon', [['Respiratory', u'Bronkospasm.'], ['General', u'Tr\xf6tthet']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighet, anafylaktiska och anafylaktoida reaktioner (inklusive hypotoni och chock).'],
             ['Nervous system', u'Somnolens.'],
             ['Respiratory', u'Astma (inklusive dyspn\xe9).'],
             ['GI',
              u'Gastrit, gastrointestinal bl\xf6dning, hematemes, melaena, gastrointestinalt s\xe5r (med eller utan bl\xf6dning eller perforation), blodiga diarr\xe9er.'],
             ['Hepato',
              u'Leverfunktionsst\xf6rningar inklusive hepatit med eller utan ikterus.'],
             ['Skin', u'Urtikaria.'],
             ['General',
              u'\xf6dem, impotens (samband med diklofenak tveksamt). Kliniska pr\xf6vningar och epidemiologiska data tyder p\xe5 att anv\xe4ndning av diklofenak, s\xe4rskilt i h\xf6ga doser (150 mg dagligen) och vid l\xe5ngtidsbehandling, kan medf\xf6ra en liten \xf6kad risk f\xf6r arteriella trombotiska h\xe4ndelser (till exempel hj\xe4rtinfarkt eller stroke, se avsnitt 4.4).']]],
           ['Very rare',
            [['Blood',
              u'Trombocytopeni, leukopeni, agranulocytos, (inklusive hemolytisk- och aplastisk anemi).'],
             ['Immune system',
              u'Angioneurotiskt \xf6dem (inklusive ansikts\xf6dem). Psykiatriska st\xf6rningar'],
             ['Immune system',
              u'Desorientering, depression, insomni, mardr\xf6mmar, l\xe4ttretlighet, oro,'],
             ['Nervous system',
              u'Parestesier, minnesst\xf6rningar, kramper, tremor, smakf\xf6r\xe4ndringar, aseptisk meningit, cerebrovaskul\xe4r h\xe4ndelser.'],
             ['Ear', u'Tinnitus, nedsatt h\xf6rsel.'],
             ['Cardiac', u'Palpitationer. br\xf6stsm\xe4rta, hj\xe4rtsvikt, myokardinfarkt.'],
             ['Vascular', u'Hypertoni, vaskulit.'],
             ['Respiratory', u'Pneumonit.'],
             ['GI',
              u'Diafragmaliknande tarmrestrikturer, kolit (inklusive hemorragisk kolit och exacerbationer av ulcer\xf6s kolit eller Crohns sjukdom), stomatit (inklusive ulcerativ stomatit), glossit, esofagusst\xf6rningar, constipation, pankreatit.'],
             ['Hepato', u'Fulminant hepatit, levernekros, leversvikt.'],
             ['Skin',
              u'eksem, erytema, erytema multiforme, erytrodermi (exfoliativ dermatit), h\xe5ravfall, ljus\xf6verk\xe4nslighetsreaktioner, purpura (inklusive allergisk purpura), pruritus, bull\xf6sa eruptioner som Steven Johnsons syndrom och toxisk epidermal nekrolys. I s\xe4llsynta fall f\xf6rekommer allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor.'],
             ['Renal',
              u'Akut njurinsufficiens, hematuri, proteinuri, interstitiell nefrit, nefrotiskt syndrom, papillarnekros.']]]],
 '_pages': [8, 10],
 u'_rank': 27,
 u'_type': u'LSFU'}