{'_data': [['Common',
            [['GI',
              u'epigastrisk sm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta, dyspepsi, flatulens, anorexi.'],
             ['Hepato', u'Transaminasstegringar (ASAT, ALAT).'],
             ['Skin', u'utslag'],
             ['General', u'huvudv\xe4rk, yrsel eller vertigo.']]],
           ['Uncommon',
            [['Respiratory', u'bronkospasm.'],
             ['GI',
              u'gastrit, gastrointestinal bl\xf6dning, hematemes, melaena, peptiska s\xe5r eller tarms\xe5r med eller utan bl\xf6dning eller perforation, blodiga diarr\xe9er.'],
             ['Hepato',
              u'leverfunktionsst\xf6rningar inklusive hepatit med eller utan ikterus.'],
             ['Skin', u'urtikaria.'],
             ['General',
              u'tr\xf6tthet, \xf6dem, \xf6verk\xe4nslighetsreaktioner (t ex bronkospasm, anafylaktiska reaktioner inklusive hypotension).']]],
           ['Rare',
            [['Blood',
              u'trombocytopeni, leukopeni, agranulocytos, hemolytisk anemi, aplastisk anemi.'],
             ['Nervous system',
              u'parestesier, minnesst\xf6rningar, desorientering, nedsatt h\xf6rsel och synst\xf6rningar (dimsyn, dubbelseende), tinnitus, s\xf6mnsv\xe5righeter, irritabilitet, kramper, depression, \xe4ngslan, mardr\xf6mmar, tremor, psykotiska reaktioner, smakf\xf6r\xe4ndringar, aseptisk meningit, k\xe4nselst\xf6rningar.'],
             ['Cardiac', u'palpitationer, hj\xe4rtsvikt'],
             ['Vascular', u'hypertoni'],
             ['GI',
              u'tarmstrikturer, tjocktarmsbesv\xe4r (ospecifik hemorragisk kolit och excerbationer av ulcer\xf6s kolit eller Crohns proktokolit), aft\xf6s stomatit, ulcerativ stomatit, glossit, esofaguslesioner, obstipation, pankreatit.'],
             ['Hepato', u'Fulminant hepatit.'],
             ['Skin',
              u'eksem, erytema multiforme, erytrodermi (exfoliativ dermatit), h\xe5ravfall, ljus\xf6verk\xe4nslighetsreaktioner, purpura (inklusive allergisk purpura).'],
             ['Skin',
              u'fall f\xf6rekommer allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor.'],
             ['Renal',
              u'akut njurinsufficiens, hematuri, proteinuri, interstitiell nefrit, nefrotiskt syndrom, papillarnekros.'],
             ['General', u'impotens (samband med diklofenak oklart), br\xf6stsm\xe4rta.']]],
           ['Very rare',
            [['Skin',
              u'bull\xf6sa eruptioner som Steven Johnsons syndrom och toxisk epidermal nekrolys, i']]]],
 '_pages': [7, 8],
 u'_rank': 20,
 u'_type': u'LSFU'}