{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Ear', u'Vertigo'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kningar, diarr\xe9, dyspepsi, buksm\xe4rta, flatulens, minskad aptit'],
             ['Hepato', u'F\xf6rh\xf6jda aminotransferasniv\xe5er'],
             ['Skin', u'Hudutslag']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighet, anafylaktiska och anafylaktoida reaktioner (inklusive blodtryckfall och chock)'],
             ['Nervous system', u'Somnolens'],
             ['Respiratory', u'Astma (inklusive dyspn\xe9)'],
             ['GI',
              u'Gastrit, gastrointestinal bl\xf6dning, hematemes, blodig diarr\xe9, melaena, gastrointestinala s\xe5r (med eller utan bl\xf6dning eller perforation)'],
             ['Hepato', u'Hepatit, gulsot, leversvikt'],
             ['Skin', u'Urtikaria'],
             ['General', u'\xd6dem']]],
           ['Very rare',
            [['Blood',
              u'Trombocytopeni, leukopeni, anemi (inklusive hemolytisk och aplastisk anemi), agranulocytos'],
             ['Immune system', u'Angio\xf6dem (inklusive ansikts\xf6dem)'],
             ['Psychiatric',
              u'Desorientering, depression, insomningssv\xe5righeter, mardr\xf6mmar, irritabilitet, psykotiska st\xf6rningar, oro'],
             ['Nervous system',
              u'Parestesier, minnesst\xf6rningar, kramper, tremor, aseptisk meningit, smakf\xf6r\xe4ndringar, cerebrovaskul\xe4r h\xe4ndelse'],
             ['Eye', u'Synst\xf6rningar, dimsyn, dubbelseende'],
             ['Ear', u'Tinnitus, nedsatt h\xf6rsel'],
             ['Cardiac', u'Palpitationer, br\xf6stsm\xe4rta, hj\xe4rtsvikt, hj\xe4rtinfarkt'],
             ['Vascular', u'Hypertoni, vaskulit'],
             ['Respiratory', u'Pneumonit'],
             ['GI',
              u"Kolit (s\xe5som hemorragisk kolit och exacerbationer av ulcer\xf6s kolit eller Crohn's sjukdom), f\xf6rstoppning, stomatit, glossit, esofaguslesioner, diafragma-liknande intestinala strikturer, pankreatit"],
             ['Hepato', u'Fulminant hepatit, levernekros, leversvikt'],
             ['Skin',
              u"Bull\xf6sa eruptioner, eksem, erytema multiforme, Stevens-Johnson's syndrom, toxisk epidermolys nekrolys (Lyells syndrom), exfoliativ dermatit, h\xe5ravfall, fotosensitivitet, purpura (inklusive Henoch-Schonlein purpura), pruritus."],
             ['Renal',
              u'Akut njursvikt, hematuri, proteinuri, nefrotiskt syndrom, interstitiell nefrit, papillarnekros']]]],
 '_pages': [8, 9],
 u'_rank': 25,
 u'_type': u'LSFU'}