{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk och yrsel'],
             ['Ear', u'Svindel (vertigo)'],
             ['GI',
              u'Epigastrisk sm\xe4rta och andra gastrointestinala sjukdomar (t.ex. illam\xe5ende, kr\xe4kningar, diarr\xe9 magkramp, dyspepsi, flatulens, anorexi)'],
             ['Skin', u'Utslag eller kl\xe5da'],
             ['Hepato', u'F\xf6rh\xf6jning av serum transaminaser (S-ALAT, S-ASAT)']]],
           ['Uncommon',
            [['Immune system',
<<<<<<< HEAD
              u'\xd6verk\xe4nslighetsreaktioner, s\xe5som astma, anafylaktiska reaktioner (inklusive hypotension och chock)'],
=======
              u'\xd6verk\xe4nslighetsreaktioner , s\xe5som astma, anafylaktiska reaktioner (inklusive hypotension och chock)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Gastrointestinal bl\xf6dning (hematemes, melena, blodiga diarr\xe9er)'],
             ['Skin', u'Urtikaria'],
             ['Hepato', u'Hepatit med eller utan ikterus'],
             ['General', u'\xd6dem.']]],
           ['Rare',
            [['Cardiac', u'Palpitationer, br\xf6stsm\xe4rta och kongestiv hj\xe4rtsvikt.'],
             ['Blood',
              u'Trombocytopeni, leukopeni, agranulocytos, anemi (inklusive hemolytisk och aplastisk anemi)'],
             ['Nervous system', u'D\xe5sighet'],
             ['Respiratory', u'Pneumonit, astma (inklusive dyspn\xe9)'],
             ['GI',
              u'Gastrit, gastrointestinala s\xe5r (med eller utan bl\xf6dningar och perforation), tarmbesv\xe4r (s\xe5som ospecifik hemorragisk kolit eller exacerbationer av ulcer\xf6s kolit eller Crohns sjukdom), stomatit (inklusive aft\xf6s stomatit), glossit, esofaguslesioner, tarmstenos och obstipation'],
             ['Skin',
<<<<<<< HEAD
              u'Bull\xf6s eruption, eksem, erytema multiforme, Stevens-Johnsons syndrom, toxisk epidermal nekrolys (Lyells syndrom), exfoliativ dermatit, h\xe5ravfall, ljus\xf6verk\xe4nslighets-r eaktioner, purpura, (inklusive allergisk purpura)'],
=======
              u'Bull\xf6s eruption, eksem, erytema multiforme, Stevens-Johnsons syndrom, toxisk epidermal nekrolys (Lyells syndrom), exfoliativ dermatit, h\xe5ravfall, ljus\xf6verk\xe4nslighets-reaktioner, purpura, (inklusive allergisk purpura)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Vascular', u'Hypertension, vaskulit'],
             ['Hepato', u'Fatal fulminant hepatit, gulsot, leversjukdom']]],
           ['Very rare',
            [['Cardiac', u'Hj\xe4rtinfarkt'],
             ['Immune system', u'Angioneurotiskt \xf6dem (inklusive ansikts\xf6dem)'],
             ['Nervous system',
              u'F\xf6rnimmelsest\xf6rnin gar inkluderande parestesier, minnesst\xf6rningar, kramper, \xe5ngest, tremor, smakf\xf6r\xe4ndringar, cerebrovaskul\xe4ra h\xe4ndelser och aseptisk meningit'],
             ['Eye', u'Synst\xf6rningar, dimsyn, dubbelseende'],
             ['Ear', u'H\xf6rselneds\xe4ttning, tinnitus'],
             ['GI', u'Pankreatit'],
             ['Renal',
              u'Akut njurinsufficiens, njursjukdomar s\xe5som hematuri, proteinuri, interstitiell nefrit, nefrotiskt syndrom och papillarnekros i njure.'],
             ['Hepato', u'Levernekros, leversvikt'],
             ['Reproductive system',
              u'Impotens (kausalsamband med diklofenak \xe4r os\xe4kert)'],
             ['Psychiatric',
              u'Disorientering, depression, insomni, mardr\xf6mmar, irritabilitet, psykotiska reaktioner']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 28,
 u'_type': u'MSFU'}