{'_data': [['Very common',
            [['Metabolism', u'Hypokalemi, h\xf6jda blodfetter (fr\xe4mst vid h\xf6gre doser)']]],
           ['Common',
            [['Metabolism', u'Hyponatremi, hypomagnesemi, hyperurikemi'],
             ['Vascular', u'Postural hypotoni'],
             ['GI', u'Aptitl\xf6shet, l\xe4tt illam\xe5ende och kr\xe4kningar'],
             ['Skin', u'Urtikaria och andra former av utslag'],
             ['Reproductive system', u'Impotens']]],
           ['Uncommon',
            [['Metabolism', u'Dehydrering'],
             ['Nervous system', u'Parestesier'],
             ['Eye', u'Dimsyn'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Hosta'],
             ['Musculoskeletal', u'Myalgi'],
             ['General', u'Tr\xf6tthet'],
             ['Ear', u'Svindel'],
             ['GI', u'Buksm\xe4rta']]],
           ['Rare',
            [['Blood', u'Trombocytopeni, ibland med purpura'],
             ['Metabolism',
              u'Hyperkalcemi, hyperglykemi, glukosuri och f\xf6rs\xe4mring av metabolt diabetestillst\xe5nd'],
             ['Psychiatric', u'Depression, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, parestesi'],
             ['Eye', u'Synneds\xe4ttning'],
             ['Cardiac', u'Hj\xe4rtarytmier'],
             ['GI', u'F\xf6rstoppning, besv\xe4r fr\xe5n magtarmkanalen, diarr\xe9'],
             ['Hepato', u'Intrahepatisk kolestas eller gulsot'],
             ['Skin', u'Fotosensibilisering']]],
           ['Very rare',
            [['Nervous system', u'Yrsel'],
             ['GI', u'Diarr\xe9'],
             ['Musculoskeletal', u'Artralgi'],
             ['Blood', u'Agranulocytos, leukopeni, hemolytisk anemi, benm\xe4rgssvikt'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
             ['Metabolism', u'Hypokloremisk alkalos'],
             ['Respiratory', u'Andn\xf6dssyndrom, inkluderande pneumonit och lung\xf6dem'],
             ['GI', u'Pankreatit'],
             ['Skin',
              u'Nekrotiserande vaskulit och toxisk epidermal nekrolys, kutana lupus erythematosus-lika reaktioner, reaktivering av kutan lupus erythematosus']]],
           ['Unknown',
            [['Nervous system', u'Synkope'],
             ['Respiratory', u'Icke-kardiogent lung\xf6dem'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['Investigations',
              u'\xd6kad halt urinsyra i serum, \xf6kat bilirubin och kreatinin i serum, hypokalemi, hyponatremi, stegring av ureakv\xe4ve i blod, neutropeni Till\xe4ggsinformation om de enskilda komponenterna Biverkningar som tidigare rapporterats f\xf6r en av de enskilda komponenterna kan potentiellt \xe4ven upptr\xe4da med Diovan Comp, \xe4ven om de inte observerats i de kliniska studierna eller efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning.'],
             ['Blood', u'S\xe4nkt hemoglobin, s\xe4nkt hematokrit, trombocytopeni'],
             ['Immune system',
              u'Andra \xf6verk\xe4nslighets-/allergiska reaktioner, inkluderande serumsjuka'],
             ['Metabolism', u'\xd6kning av serumkalium, hyponatremi'],
             ['Vascular', u'Vaskulit'],
             ['Hepato', u'F\xf6rh\xf6jda leverfunktionsv\xe4rden'],
             ['Skin', u'Angioneurotiskt \xf6dem, utslag, kl\xe5da'],
             ['Renal', u'Njursvikt'],
             ['Blood', u'Aplastisk anemi'],
             ['Eye', u'Akut tr\xe5ngvinkelglaukom'],
             ['Renal', u'Nedsatt njurfunktion, akut njursvikt'],
             ['Skin', u'Erythema multiforme'],
             ['Musculoskeletal', u'Muskelkramp']]]],
 '_pages': [8, 10],
 u'_rank': 50,
 u'_type': u'LSFU'}