{'_data': [['Uncommon',
            [['Skin',
              u'Atrofi, striae, sekund\xe4rinfektion, papul\xf6s rosacealiknande dermatit (ansiktshud), kapill\xe4rsk\xf6rhet (ekkymoser), sensibilisering (konserveringsmedel).']]],
           ['Rare',
            [['Skin',
              u'Hypo- eller hyperpigmentering, hypertrikos, sensibilisering (betametason).'],
             ['Endocrine', u'Binjurebarksh\xe4mning.']]]],
 '_pages': [2, 3],
 u'_rank': 3,
 u'_type': u'LSFU'}