{'_data': [[u'Unknown',
            [['Infections',
              u'Infektioner   Infektion associerad   (G3/4: 5,7 %; inklusive   med G4 neutropeni'],
             ['Blood', u'Neutropeni   Trombocytopeni (G4:   (G4: 76,4 %)   0,2 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet   (G3/4:'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system', u'Perifer sensorisk   neuropati(G3: 4,1 %)'],
             ['Cardiac', u'Arytmi (G3/4: 0,7 %)   Hj\xe4rtsvikt'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9 (sv\xe5r 2,7 %)'],
             ['GI',
              u'Stomatit (G3/4: 5,3 %)   F\xf6rstoppning (sv\xe5r 0,2   Esofagit (sv\xe5r 0,4 %)'],
             ['Skin', u'Alopeci;   Hudreaktioner (G3/4:'],
             ['Musculoskeletal', u'Myalgi (sv\xe5r 1,4 %)   Artralgi'],
             ['General', u'V\xe4skeretention (sv\xe5r   Reaktion p\xe5'],
             ['Investigations', u'G3/4 bilirubin stegring'],
             ['Infections', u'Infektioner (G3/4: 5 %)'],
             ['Blood', u'Neutropeni (G4: 54,2 %)   Febril neutropeni'],
             ['Immune system', u'\xd6verk\xe4nslighet (ej sv\xe5r)'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system',
              u'Perifer sensorisk neuropati   Perifer motorisk neuropati   (G3/4: 0,8 %)   (G3/4: 2,5 %)'],
             ['Cardiac', u'Arytmi (ej sv\xe5r)'],
             ['Vascular', u'Hypotoni'],
             ['GI', u'Illam\xe5ende (G3/4: 3,3 %)   F\xf6rstoppning'],
             ['Skin', u'Alopeci   Nagelf\xf6r\xe4ndringar (sv\xe5ra 0,8 %)'],
             ['Musculoskeletal', u'Myalgi'],
             ['General',
              u'Asteni (sv\xe5r 12,4 %)   V\xe4skeretention (sv\xe5r 0,8 %)   Sm\xe4rta'],
             ['Investigations', u'G3/4 bilirubin stegring (< 2 %)'],
             ['Infections', u'Infektioner (G3/4: 7,8   %)'],
             ['Blood', u'Anemi (G3/4: 9,4 %)  Trombocytopeni (G4:'],
             ['Immune system', u'1,2 %)'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system',
              u'Perifer sensorisk   neuropati(G3: 0,4 %)    neuropati (G3/4: 0,4'],
             ['Cardiac', u'Arytmi (ej sv\xe5r)'],
             ['Vascular', u'Hypotoni'],
             ['GI', u'Diarr\xe9 (G3/4: 6,2 %)'],
             ['Skin', u'Nagelf\xf6r\xe4ndringar   (sv\xe5ra 0,4 %)'],
             ['Musculoskeletal', u'Myalgi'],
             ['General', u'V\xe4skeretention (sv\xe5r   Reaktion p\xe5'],
             ['Investigations', u'G3/4 stegring av   1 %);'],
             ['Infections', u'Infektioner  (G3/4: 5,7 %)'],
             ['Blood', u'Anemi (G3/4: 6,9 %)   Febril neutropeni   Trombocytopeni'],
             ['Immune system', u'2,5 %)'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system', u'neuropati (G3: 3,7 %)   Perifer motorisk'],
             ['Cardiac', u'Arytmi (G3/4: 0,7 %)   Hj\xe4rtsvikt'],
             ['Vascular', u'Hypotoni (G3/4: 0,7 %)'],
             ['GI', u'%)  F\xf6rstoppning'],
             ['Skin', u'Nagelf\xf6r\xe4ndringar  (sv\xe5ra 0,7 %)  Hudreaktioner (G3/4:'],
             ['Musculoskeletal', u'Myalgi (sv\xe5r 0,5 %)'],
             ['General', u'V\xe4skeretention (sv\xe5r  Reaktion p\xe5'],
             ['Investigations', u'(2,1 %);  G3/4 stegring av'],
             ['Blood', u'neutropeni associerad med feber'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk   f\xf6r\xe4ndring av smakk\xe4nsla'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['Vascular', u'Lymf\xf6dem'],
             ['Respiratory', u'nasofaryngit   dyspn\xe9'],
             ['GI', u'F\xf6rstoppning'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'Artralgi  Sm\xe4rta i extremiteterna  Skelettsm\xe4rta'],
             ['General', u'Tr\xf6tthet   Slemhinneinflammation   Letargi   Sm\xe4rta'],
             ['Investigations', u'Vikt\xf6kning'],
             ['Infections', u'Oral candidiasis (G3/4: <1 %)'],
             ['Blood', u'Anemi (G3/4: 10 %)  Trombocytopeni (G3/4: 3 %)'],
             ['Metabolism', u'Minskad aptit  Dehydrering (G3/4: 2 %)'],
             ['Nervous system',
              u'Smakf\xf6r\xe4ndringar (G3/4: <1 %)   Huvudv\xe4rk (G3/4: <1 %)  Parestesi (G3/4: <1 %)   Perifer neuropati'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['Respiratory',
              u'Halsont (G3/4: 2 %)   Hosta (G3/4: <1 %)   Epistaxis (G3/4: <1 %)'],
             ['GI', u'Kr\xe4kning (G3/4: 4 %)   \xd6vre buksm\xe4rta'],
             ['Skin', u'Alopeci (G3/4: 6 %)   %)'],
             ['Musculoskeletal', u'Myalgi (G3/4: 2 %) Artralgi   (G3/4: 1 %)    <1 %);'],
             ['General',
              u'Pyrexi (G3/4: 1 %)   Letargi   Tr\xf6tthet/svaghet (G3/4: 5 %)   Sm\xe4rta   Perifert \xf6dem (G3/4: 1 %)'],
             ['Investigations', u'G3/4 bilirubin stegring (9 %)'],
             ['Infections', u'Infektioner (G3/4: 3,3 %)'],
             ['Blood', u'Neutropeni (G3/4: 32 %)   Trombocytopeni; (G3/4: 0,6 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 0,6 %)'],
             ['Metabolism', u'Anorexi (G3/4: 0,6 %)'],
             ['Nervous system',
              u'Perifer sensorisk neuropati   Perifer motorisk neuropati   (G3/4: 1,2 %);   (G3/4: 0 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de (G3/4: 0,6 %)'],
             ['Cardiac', u'Minskning av v\xe4nster'],
             ['Respiratory', u'Epistaxis (G3/4: 0 %)   Dyspn\xe9 (G3/4: 0,6 %)'],
             ['GI', u'Illam\xe5ende (G3/4: 2,4 %)'],
             ['Skin', u'Alopeci   Exfoliativt utslag (G3/4: 0,3 %)'],
             ['Musculoskeletal', u'Artralgi (G3/4: 0,3 %)   Myalgi (G3/4: 0,3 %)'],
             ['General', u'Tr\xf6tthet (G3/4: 3,9 %)   V\xe4skeretention (sv\xe5r 0,6 %)'],
             ['Infections', u'\xd6verk\xe4nslighet (G3/4:   1,1 %)'],
             ['Blood', u'Anemi (G3/4: 4,3 %)   Neutropeni (G3/4: 59,2'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4:'],
             ['Metabolism', u'Anorexi (G3/4: 1,5 %)'],
             ['Nervous system',
              u'Smakf\xf6r\xe4ndringar   Perifer motorisk   Synkope (G3/4: 0 %)   (G3/4: 0,6 %);   neuropati (G3/4: 0 %);   Neurotoxicitet (G3/4: 0'],
             ['Eye', u'Konjunktivit (G3/4: <   \xd6kat t\xe5rfl\xf6de (G3/4: <'],
             ['Cardiac', u'Arytmi (G3/4: 0,2 %);'],
             ['Vascular',
              u'Vasodilatation (G3/4:   Hypotoni (G3/4: 0 %)   Lymf\xf6dem (G3/4: 0 %)'],
             ['Respiratory', u'Hosta (G3/4: 0 %)'],
             ['GI', u'Illam\xe5ende (G3/4: 5,0   Buksm\xe4rta (G3/4: 0,4'],
             ['Skin', u'Alopeci (G3/4: < 0,1   %)'],
             ['Musculoskeletal', u'Myalgi (G3/4: 0,7 %)   Artralgi (G3/4: 0,2 %)'],
             ['Reproductive system', u'Amenorr\xe9 (G3/4: ej'],
             ['General', u'Asteni (G3/4:  %)'],
             ['Investigations', u'Vikt\xf6kning (G3/4: 0'],
             ['Infections', u'Infektioner (G3/4: 11,7 %)'],
             ['Blood', u'Trombocytopeni (G3/4: 8,8 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 1,7)'],
             ['Metabolism', u'Anorexi (G3/4: 11,7 %)'],
             ['Nervous system',
              u'Perifer sensorisk neuropati   Perifer motorisk neuropati   (G3/4: 8,7 %)   (G3/4: 1,3 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de (G3/4: 0 %)'],
             ['Ear', u'Nedsatt h\xf6rsel (G3/4: 0 %)'],
             ['Cardiac', u'Arytmi (G3/4:  %)'],
             ['GI', u'Stomatit (G3/4: 23,7 %)    %)'],
             ['Skin', u'Alopeci (G3/4: 4,0 %)   Nagelf\xf6r\xe4ndringar (G3/4: 0,7'],
             ['General',
              u'Letargi (G3/4: 19,0 %)  Pyrexi (G3/4: 2,3 %)  V\xe4tskeretention  (sv\xe5r/livshotande: 1 %)'],
             ['Infections', u'Infektion (G3/4:6,3 %)   Neutropen infektion'],
             ['Blood', u'Anemi (G3/4: 9,2)   Febril neutropeni'],
             ['Immune system', u'\xd6verk\xe4nslighet (ej sv\xe5r)'],
             ['Metabolism', u'Anorexi (G3/4:0,6 %)'],
             ['Nervous system',
              u'Dysgeusi/Parosmi;  Perifer sensorisk   Yrsel   neuropati (G3/4:0,6%)'],
             ['Eye', u'Konjunktivit'],
             ['Ear', u'Nedsatt h\xf6rsel'],
             ['Cardiac', u'(G3/4:1,7 %)  Arytmi (G3/4: 0,6 %)'],
             ['Vascular', u'Ven\xf6sa sjukdomar'],
             ['GI', u'Gastrointestinal sm\xe4rta'],
             ['Skin', u'Alopeci (G3/4:10,9 %)  Torr hud   Hudexfoliering (G3/4:0,6'],
             ['Musculoskeletal', u'Myalgi (G3/4:0,6 %)'],
             ['General', u'Pyrexi (G3/4:0,6 %)  V\xe4tskeretention  \xd6dem'],
             ['Investigations', u'Vikt\xf6kning'],
             ['Infections', u'Infektioner (G3/4: 3,6 %)   Neutropen infektion'],
             ['Blood', u'Trombocytopeni (G3/4: 4,0   Febril neutropeni   %)'],
             ['Immune system', u'\xd6verk\xe4nslighets-'],
             ['Metabolism', u'Anorexi (G3/4: 12,0 %)'],
             ['Nervous system',
              u'0,4 %)   Perifer motorisk   Perifer sensorisk neuropati   neuropati (G3/4: 0,4'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de   Konjunktivit'],
             ['Ear', u'%)'],
             ['Cardiac', u'Arytmi (G3/4: 2,0 %)   Hj\xe4rtmuskelischemi'],
             ['Vascular', u'Ven\xf6sa sjukdomar'],
             ['GI', u'Diarr\xe9 (G3/4: 6,8 %)   sm\xe4rta (G3/4: 1,2 %)'],
             ['Skin', u'Utslag/kl\xe5da  Torr hud   Deskvamation'],
             ['Musculoskeletal', u'Myalgi (G3/4: 0,4 %)'],
             ['General', u'Pyrexi (G3/4: 3,6 %)'],
             ['Investigations', u'Viktminskning   Vikt\xf6kning']]]],
 '_pages': [9, 21],
 u'_rank': 139,
 u'_type': u'LFSU'}