{'_data': [['Very common',
            [['Blood', u'Neutropeni (G4: 76,4 %) Anemi (G3/4: 8,9 %) Febril neutropeni'],
             ['Nervous system',
              u'Perifer sensorisk neuropati(G3: 4,1 %) Perifer motorisk neuropati (G3/4: 4 %) Smakf\xf6r\xe4ndring (sv\xe5r 0,07 %)'],
             ['Respiratory', u'Dyspn\xe9 (sv\xe5r 2,7 %)'],
             ['GI',
              u'Stomatit (G3/4: 5,3 %) Diarr\xe9 (G3/4: 4 %) Illam\xe5ende (G3/4: 4 %) Kr\xe4kning (G3/4: 3 %)'],
             ['Skin',
              u'Alopeci Hudreaktioner (G3/4: 5,9 %) Nagelf\xf6r\xe4ndringar (sv\xe5ra 2,6 %)'],
             ['Musculoskeletal', u'Myalgi (sv\xe5r 1,4 %)'],
             ['Metabolism', u'Anorexi'],
             ['Infections',
              u'Infektioner (G3/4: 5,7 %; inklusive sepsis och pneumoni, d\xf6dlig utg\xe5ng hos 1,7 %)'],
             ['General',
              u'V\xe4skeretention (sv\xe5r 6,5 %) Asteni (sv\xe5r 11,2 %); Sm\xe4rta'],
             ['Immune system', u'\xd6verk\xe4nslighet  (G3/4: 5,3 %)'],
             ['Blood',
              u'Neutropeni (G4: 54,2 %) Anemi (G3/4: 10,8 %); Trombocytopeni (G4: 1,7 %)'],
             ['Nervous system', u'Perifer sensorisk neuropati (G3/4: 0,8 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 3,3%) Stomatit (G3/4: 1,7%) Kr\xe4kning (G3/4: 0,8%) Diarr\xe9 (G3/4: 1,7 %)'],
             ['Skin', u'Alopeci Hudreaktioner (G3/4: 0,8 %)'],
             ['Metabolism', u'Anorexi'],
             ['General',
              u'Asteni (sv\xe5r 12,4 %) V\xe4skeretention (sv\xe5r 0,8 %) Sm\xe4rta'],
             ['Blood',
              u'Neutropeni (G4: 91,7 %) Anemi (G3/4: 9,4 %) Febril neutropeni Trombocytopeni (G4: 0,8 %)'],
             ['Nervous system', u'Perifer sensorisk neuropati(G3: 0,4 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 5 %) Stomatit (G3/4: 7,8 %) Diarr\xe9 (G3/4: 6,2 %) Kr\xe4kning (G3/4: 5 %) F\xf6rstoppning'],
             ['Skin',
              u'Alopeci Nagelf\xf6r\xe4ndringar (sv\xe5ra 0,4 %) Hudreaktion (ej sv\xe5r)'],
             ['Infections', u'Infektioner (G3/4: 7,8 %)'],
             ['General', u'Asteni (sv\xe5r 8,1 %) V\xe4skeretention (sv\xe5r 1,2 %) Sm\xe4rta'],
             ['Blood',
              u'Neutropeni (G4: 51,5 %) Anemi (G3/4: 6,9 %) Trombocytopeni (G4:0,5 %)'],
             ['Nervous system',
              u'Perifer sensorisk neuropati(G3: 3,7 %) Perifer motorisk neuropati (G3/4: 2 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 9,6 %) Kr\xe4kning (G3/4: 7,6 %) Diarr\xe9 (G3/4: 6,4 %) Stomatit (G3/4: 2 %)'],
             ['Skin',
              u'Alopeci Nagelf\xf6r\xe4ndringar (sv\xe5ra 0,7 %) Hudreaktioner (G3/4: 0,2 %)'],
             ['Musculoskeletal', u'Myalgi (sv\xe5r 0,5 %)'],
             ['Metabolism', u'Anorexi'],
             ['Infections', u'Infektioner (G3/4: 5,7 %)'],
             ['General',
              u'Asteni (sv\xe5r 9,9 %); V\xe4skeretention (sv\xe5r 0,7 %) Pyrexi (G3/4: 1,2 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 2,5 %)'],
             ['Investigations', u'Vikt\xf6kning'],
             ['Blood',
              u'Neutropeni (G3/4: 32 %) Febril neutropeni (omfattande neutropeni associerad med feber och behandling med antibiotika) eller neutropen sepsis'],
             ['Nervous system',
              u'Parestesi huvudv\xe4rk f\xf6r\xe4ndring av smakk\xe4nsla hypestesi'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de Konjunktivit'],
             ['Respiratory',
              u'Epistaxis faryngolaryngeal sm\xe4rta nasofaryngit dyspn\xe9 hosta rinorr\xe9'],
             ['GI',
              u'Illam\xe5ende Diarr\xe9 Kr\xe4kning F\xf6rstoppning Stomatit Dyspepsi Buksm\xe4rta'],
             ['Skin', u'Alopeci Erytem Hudutslag Nagelf\xf6r\xe4ndringar'],
             ['Musculoskeletal',
              u'Myalgi Artralgi Sm\xe4rta i extremiteterna Skelettsm\xe4rta Ryggsm\xe4rta'],
             ['Metabolism', u'Anorexi'],
             ['Vascular', u'Lymf\xf6dem'],
             ['General',
              u'Asteni Perifert \xf6dem Pyrexi Tr\xf6tthet Slemhinneinflammation Sm\xe4rta Influensaliknande symtom Br\xf6stsm\xe4rta Frossa'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Blood', u'Neutropeni (G3/4: 63 %); Anemi (G3/4: 10 %)'],
             ['Nervous system', u'Smakf\xf6r\xe4ndringar (G3/4: <1 %) Parestesi (G3/4: <1 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['Respiratory', u'Halsont (G3/4: 2 %)'],
             ['GI',
              u'Stomatit (G3/4: 18 %) Diarr\xe9 (G3/4: 14 %) Illam\xe5ende (G3/4: 6 %) Kr\xe4kning (G3/4: 4 %) F\xf6rstoppning (G3/4: 1 %) Buksm\xe4rta (G3/4: 2 %) Dyspepsi'],
             ['Skin',
              u'Hand-fotsyndrom (G3/4: 24 %) Alopeci (G3/4: 6 %) Nagelf\xf6r\xe4ndringar (G3/4: 2 %)'],
             ['Musculoskeletal', u'Myalgi (G3/4: 2 %) Artralgi (G3/4: 1 %)'],
             ['Metabolism', u'Anorexi (G3/4: 1 %) Minskad aptit'],
             ['General',
              u'Asteni (G3/4: 3 %) Pyrexi (G3/4: 1 %) Tr\xf6tthet/svaghet (G3/4: 5 %) Perifert \xf6dem (G3/4: 1 %)'],
             ['Blood', u'Neutropeni (G3/4: 32 %) Anemi (G3/4: 4,9 %)'],
             ['Nervous system',
              u'Perifer sensorisk neuropati (G3/4: 1,2 %); Smakf\xf6r\xe4ndringar (G3/4: 0 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 2,4 %) Diarr\xe9 (G3/4: 1,2 %) Stomatit/faryngit (G3/4: 0,9 %) Kr\xe4kning (G3/4: 1,2 %)'],
             ['Skin', u'Alopeci Nagelf\xf6r\xe4ndringar (ej sv\xe5ra)'],
             ['Metabolism', u'Anorexi (G3/4: 0,6 %)'],
             ['General', u'Tr\xf6tthet (G3/4: 3,9 %) V\xe4skeretention (sv\xe5r 0,6 %)'],
             ['Investigations', u'\xd6kning eller minskning av vikt (G3/4: 0,3 %)'],
             ['Blood',
              u'Anemi (G3/4: 4,3 %) Neutropeni (G3/4: 65,5 %) Trombocytopeni (G3/4: 2,0 %) Febril neutropeni'],
             ['Nervous system',
              u'Smakf\xf6r\xe4ndringar (G3/4: 0,7 %); Perifer sensorisk neuropati (G3/4: 0 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 5,1 %) Stomatit (G3/4: 7,1 %) Kr\xe4kning (G3/4: 4,3 %) Diarr\xe9 (G3/4: 3,2 %) F\xf6rstoppning (G3/4: 0,4 %)'],
             ['Skin',
              u'Alopeci Hudtoxicitet (G3/4: 0,7 %) Nagelf\xf6r\xe4ndringar (G3/4: 0,4 %)'],
             ['Musculoskeletal', u'Myalgi (G3/4: 0,8 %) Artralgi (G3/4: 0,4 %)'],
             ['Metabolism', u'Anorexi (G3/4: 2,2 %)'],
             ['Infections',
              u'Infektioner (G3/4: 3,2 %) Neutropen infektion. Inga fall av d\xf6d till f\xf6ljd av sepsis'],
             ['Vascular', u'Vasodilatation (G3/4: 0,9 %)'],
             ['General',
              u'Asteni (G3/4: 11 %) Pyrexi (G3/4: 1,2 %) Perifert \xf6dem (G3/4: 0,4 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 1,1 %)'],
             ['Reproductive system', u'Amenorr\xe9'],
             ['Reproductive system', u'br\xf6stk\xf6rtel: '],
             ['Blood',
              u'Anemi (G3/4: 20,9 %) Neutropeni (G3/4: 83,2 %) Trombocytopeni (G3/4: 8,8 %) Febril neutropeni'],
             ['Nervous system', u'Perifer sensorisk neuropati (G3/4: 8,7 %)'],
             ['GI',
              u'Diarr\xe9 (G3/4: 19,7 %) Illam\xe5ende (G3/4: 16 %) Stomatit (G3/4: 23,7 %) Kr\xe4kning (G3/4: 14,3 %)'],
             ['Skin', u'Alopeci (G3/4: 4,0 %)'],
             ['Metabolism', u'Anorexi (G3/4: 11,7 %)'],
             ['Infections', u'Neutropen infektion; Infektioner (G3/4: 11,7 %)'],
             ['General',
              u'Letargi (G3/4: 19,0 %) Pyrexi (G3/4: 2,3 %) V\xe4tskeretention (sv\xe5r/livshotande: 1 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 1,7)'],
             ['Blood',
              u'Neutropeni (G3/4:76,3 %) Anemi (G3/4: 9,2) Trombocytopeni (G3/4:5,2 %)'],
             ['Nervous system', u'Dysgeusi/Parosmi; Perifer sensorisk neuropati (G3/4:0,6%)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 0,6%) Stomatit (G3/4:4,0%) Diarr\xe9 (G3/4:2,9 %) Kr\xe4kning (G3/4:0,6 %)'],
             ['Skin', u'Alopeci (G3/4:10,9 %) Utslag/kl\xe5da'],
             ['Metabolism', u'Anorexi (G3/4:0,6 %)'],
             ['Infections', u'Infektion (G3/4:6,3 %) Neutropen infektion'],
             ['General',
              u'Letargi (G3/4: 3,4 %) Pyrexi (G3/4:0,6 %) V\xe4tskeretention \xd6dem'],
             ['Investigations', u'Viktminskning'],
             ['Blood',
              u'Neutropeni (G3/4:83,5 %) Anemi (G3/4:12,4 %) Trombocytopeni (G3/4: 4,0 %) Febril neutropeni'],
             ['Nervous system',
              u'Dysgeusi/Parosmi (G3/4: 0,4 %) Perifer sensorisk neuropati (G3/4: 1,2 %)'],
             ['Ear', u'Nedsatt h\xf6rsel (G3/4: -1,2 %)'],
             ['GI',
              u'Illam\xe5ende (G3/4: 13,9 %) Stomatit (G3/4:20,7 %) Kr\xe4kning (G3/4: 8,4 %) Diarr\xe9 (G3/4: 6,8 %) Esofagit/dysfagit/odyno fagi (G3/4: 12,0 %) F\xf6rstoppning (G3/4: 0,4 %)'],
             ['Skin', u'Alopeci (G3/4: 4,0 %) Utslag/kl\xe5da'],
             ['Metabolism', u'Anorexi (G3/4: 12,0 %)'],
             ['Infections', u'Infektioner (G3/4: 3,6 %)'],
             ['General',
              u'Letargi (G3/4: 4,0 %) Pyrexi (G3/4: 3,6 %) V\xe4tskeretention (G3/4: 1,2 %) \xd6dem (G3/4: 1,2 %)']]],
           ['Common',
            [['Investigations',
              u'G3/4 bilirubin stegring (< 5 %) G3/4 stegring av alkaliska fosfataser (< 4 %) G3/4 ASAT stegring (< 3 %); G3/4 ALAT stegring (< 2 %)'],
             ['Cardiac', u'Arytmi (G3/4: 0,7 %) Hj\xe4rtsvikt (0,5 %)'],
             ['Blood', u'Trombocytopeni (G4: 0,2 %)'],
             ['GI',
              u'F\xf6rstoppning (sv\xe5r 0,2 %); Buksm\xe4rta (sv\xe5r 1 %) Gastrointestinal bl\xf6dning (sv\xe5r 0,3 %)'],
             ['Musculoskeletal', u'Artralgi'],
             ['Infections', u'Infektion associerad med G4 neutropeni (G3/4: 4,6 %)'],
             ['Vascular', u'Hypotoni Hypertension Bl\xf6dning'],
             ['General',
              u'Reaktion p\xe5 infusionsst\xe4llet Br\xf6stsm\xe4rta utan hj\xe4rtp\xe5verkan (sv\xe5r 0,4 %)'],
             ['Investigations', u'G3/4 bilirubin stegring (< 2 %)'],
             ['Cardiac', u'Arytmi (ej sv\xe5r)'],
             ['Blood', u'Febril neutropeni'],
             ['Nervous system', u'Perifer motorisk neuropati (G3/4: 2,5 %)'],
             ['GI', u'F\xf6rstoppning'],
             ['Skin', u'Nagelf\xf6r\xe4ndringar (sv\xe5ra 0,8 %)'],
             ['Musculoskeletal', u'Myalgi'],
             ['Vascular', u'Hypotoni'],
             ['Immune system', u'\xd6verk\xe4nslighet (ej sv\xe5r)'],
             ['Investigations',
              u'G3/4 bilirubin stegring (< 2,5 %) G3/4 stegring av alkaliska fosfataser (< 2,5 %)'],
             ['Cardiac', u'Hj\xe4rtsvikt Arytmi (ej sv\xe5r)'],
             ['Nervous system', u'Perifer motorisk neuropati (G3/4: 0,4 %)'],
             ['Musculoskeletal', u'Myalgi'],
             ['Metabolism', u'Anorexi'],
             ['General', u'Reaktion p\xe5 infusionsst\xe4llet'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 1,2 %)'],
             ['Investigations', u'G3/4 bilirubin stegring (2,1 %); G3/4 ALAT stegring (1,3 %)'],
             ['Cardiac', u'Arytmi (G3/4: 0,7 %)'],
             ['Blood', u'Febril neutropeni'],
             ['GI', u'F\xf6rstoppning'],
             ['Vascular', u'Hypotoni (G3/4: 0,7 %)'],
             ['General', u'Reaktion p\xe5 infusionsst\xe4llet Sm\xe4rta'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['General', u'Letargi'],
             ['Investigations', u'Viktminskning G3/4 bilirubin stegring (9 %)'],
             ['Blood', u'Trombocytopeni (G3/4: 3 %)'],
             ['Nervous system', u'Yrsel Huvudv\xe4rk (G3/4: <1 %) Perifer neuropati'],
             ['Respiratory',
              u'Dyspn\xe9 (G3/4: 1 %) Hosta (G3/4: <1 %) Epistaxis (G3/4: <1 %)'],
             ['GI', u'\xd6vre buksm\xe4rta Torr mun'],
             ['Skin',
              u'Dermatit; Erytemat\xf6sa utslag (G3/4: <1 %) Nagelf\xe4rgf\xf6r\xe4ndring Onykolys (G3/4: 1 %)'],
             ['Musculoskeletal',
              u'Sm\xe4rta i extremiteterna (G3/4: <1 %); Ryggsm\xe4rta (G3/4: 1 %)'],
             ['Metabolism', u'Dehydrering (G3/4: 2 %)'],
             ['Infections', u'Oral candidiasis (G3/4: <1 %)'],
             ['General', u'Letargi Sm\xe4rta'],
             ['Cardiac', u'Minskning av v\xe4nster hj\xe4rtkammarfunktion (G3/4: 0,3 %)'],
             ['Blood', u'Trombocytopeni; (G3/4: 0,6 %) Febril neutropeni'],
             ['Nervous system', u'Perifer motorisk neuropati (G3/4: 0 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de (G3/4: 0,6 %)'],
             ['Respiratory',
              u'Epistaxis (G3/4: 0 %) Dyspn\xe9 (G3/4: 0,6 %) Hosta (G3/4: 0 %)'],
             ['Skin', u'Exfoliativt utslag (G3/4: 0,3 %)'],
             ['Musculoskeletal', u'Artralgi (G3/4: 0,3 %) Myalgi (G3/4: 0,3 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (G3/4: 0,6 %)'],
             ['Cardiac', u'Arytmi (G3/4: 0,1 %); Kronisk hj\xe4rtinsufficiens'],
             ['Nervous system',
              u'Perifer motorisk neuropati (G3/4: 0 %); Neurokortikal (G3/4: 0,3 %) Neurocerebell\xe4r (G3/4: 0,1 %)'],
             ['Eye', u'Rubbningar i t\xe5rfl\xf6det (G3/4: 0,1 %) Konjunktivit (G3/4: 0,3 %)'],
             ['Respiratory', u'Hosta (G3/4: 0 %)'],
             ['GI', u'Buksm\xe4rta (G3/4: 0,5 %)'],
             ['Vascular', u'Hypotoni (G3/4: 0 %)'],
             ['Cardiac', u'Arytmi (G3/4:  %)'],
             ['Nervous system',
              u'Yrsel (G3/4: 2,3 %) Perifer motorisk neuropati (G3/4: 1,3 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de (G3/4: 0 %)'],
             ['Ear', u'Nedsatt h\xf6rsel (G3/4: 0 %)'],
             ['GI',
              u'F\xf6rstoppning (G3/4: %) Gastrointestinal sm\xe4rta (G3/4: %) Esofagit/dysfagit/odynofagi (G3/4: 0,7 %)'],
             ['Skin',
              u'Utslag/kl\xe5da (G3/4: 0,7 %) Nagelf\xf6r\xe4ndringar (G3/4: 0,7 %) Hudexfoliering (G3/4: 0 %)'],
             ['Investigations', u'Vikt\xf6kning'],
             ['Cardiac', u'Hj\xe4rtmuskelischemi (G3/4:1,7 %)'],
             ['Blood', u'Febril neutropeni'],
             ['Nervous system', u'Yrsel'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de Konjunktivit'],
             ['Ear', u'Nedsatt h\xf6rsel'],
             ['GI',
              u'F\xf6rstoppning Esofagit/dysfagit/odynof agi (G3/4:0,6 %) Gastrointestinal sm\xe4rta Dyspepsi Gastrointestinal bl\xf6dning (G3/4:0,6 %)'],
             ['Skin', u'Torr hud Hudexfoliering (G3/4:0,6 %)'],
             ['Musculoskeletal', u'Myalgi (G3/4:0,6 %)'],
             ['Vascular', u'Ven\xf6sa sjukdomar (G3/4:0,6 %)'],
             ['Immune system', u'\xd6verk\xe4nslighet (ej sv\xe5r)'],
             ['Cardiac', u'Arytmi (G3/4: 2,0 %) Hj\xe4rtmuskelischemi'],
             ['Blood', u'Febril neutropeni'],
             ['Nervous system',
              u'Yrsel (G3/4: 2,0 %) Perifer motorisk neuropati (G3/4: 0,4 %)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['GI',
              u'Dyspepsi (G3/4: 0,8 %) Gastrointestinal sm\xe4rta (G3/4: 1,2 %) Gastrointestinal bl\xf6dning (G3/4:0,4 %)'],
             ['Skin', u'Torr hud Deskvamation'],
             ['Musculoskeletal', u'Myalgi (G3/4: 0,4 %)'],
             ['Infections', u'Neutropen infektion']]],
           ['Uncommon',
            [['GI', u'Esofagit (sv\xe5r 0,4 %)'],
             ['Investigations', u'G3/4 ASAT stegring (< 1 %); G3/4 ALAT stegring (< 1 %)'],
             ['Vascular', u'Hypotoni'],
             ['Investigations',
              u'G3/4 ASAT stegring (0,5 %); G3/4 stegring av alkaliska fosfataser (0,3 %)'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['Nervous system', u'Synkope (G3/4: 0 %)'],
             ['GI', u'Kolit/enterit/perfora tion av tjocktarmen'],
             ['Vascular', u'Flebit (G3/4: 0 %) Lymf\xf6dem (G3/4: 0 %)'],
             ['Cardiac', u'Arytmi (G3/4: 0,6 %)'],
             ['Investigations', u'Vikt\xf6kning'],
             ['Eye', u'Konjunktivit'],
             ['Vascular', u'Ven\xf6sa sjukdomar'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktio ner']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 26],
 u'_rank': 189,
 u'_type': u'MSFU'}