{'_data': [['Unknown',
            [['Immune system',
<<<<<<< HEAD
              u'nutrition Psykiska Nedst\xe4mdhet Nedsatt libido \xd6kad libido st\xf6rningar Hum\xf6r-f\xf6r\xe4ndri ngar Centrala och Huvudv\xe4rk Migr\xe4n perifera Yrsel nervsystemet Nervositet \xd6gon Intolerans mot kontaktlinser \xd6ron och Otoskleros balansorgan Blodk\xe4rl Hypertension Tromboemboli Magtarmkanalen Illam\xe5ende Diarr\xe9, kr\xe4kningar Buksm\xe4rta Hud och Akne Utslag Erythema subkutan v\xe4vnad Urtikaria nodosum, erythema multiforme, pruritus, alopeci Reproduktionsor Oregelbunden Amenorr\xe9 Br\xf6sthypertrofi Vaginal gan och bl\xf6dning \xd6mhet i br\xf6sten flytning, br\xf6stk\xf6rtel Br\xf6stsm\xe4rta uts\xf6ndring fr\xe5n Metrorragi br\xf6sten Allm\xe4nna Vikt\xf6kning symtom och/eller symtom vid administreringsst \xe4llet F\xf6ljande allvarliga biverkningar har rapporterats hos kvinnor som tar kombinerade p-piller. Detta diskuteras i avsnitt 4.4: ven\xf6s tromboemboli arteriell tromboemboli hypertension levertum\xf6rer f\xf6rekomst eller f\xf6rs\xe4mring av tillst\xe5nd f\xf6r vilka ett samband med anv\xe4ndning av kombinerade p-piller inte har fastst\xe4llts. Crohns sjukdom, ulcer\xf6s kolit, epilepsi, migr\xe4n, endometrios, uterusmyom, porfyri, generaliserad lupus erythematosus, herpes gestationis, Sydenhams korea, hemolytiskt uremiskt syndrom, kolestatisk ikterus kloasma.']]]],
=======
              u'nutrition Psykiska Nedst\xe4mdhet Nedsatt libido \xd6kad libido st\xf6rningar Hum\xf6r f\xf6r\xe4ndringar Centrala och Huvudv\xe4rk Migr\xe4n perifera Yrsel nervsystemet Nervositet \xd6gon Intolerans mot kontaktlinser \xd6ron och Otoskleros balansorgan Blodk\xe4rl Hypertension Tromboemboli Magtarmkanalen Illam\xe5ende Diarr\xe9, kr\xe4kningar Buksm\xe4rta Hud och Akne Utslag Erythema subkutan v\xe4vnad Urtikaria nodosum, erythema multiforme, pruritus, alopeci Reproduktionsor Oregelbunden Amenorr\xe9 Br\xf6sthypertrofi Vaginal gan och bl\xf6dning \xd6mhet i br\xf6sten flytning, br\xf6stk\xf6rtel Br\xf6stsm\xe4rta uts\xf6ndring fr\xe5n Metrorragi br\xf6sten Allm\xe4nna Vikt\xf6kning symtom och/eller symtom vid administreringsst \xe4llet F\xf6ljande allvarliga biverkningar har rapporterats hos kvinnor som tar kombinerade p-piller. Detta diskuteras i avsnitt 4.4: ven\xf6s tromboemboli arteriell tromboemboli hypertension levertum\xf6rer f\xf6rekomst eller f\xf6rs\xe4mring av tillst\xe5nd f\xf6r vilka ett samband med anv\xe4ndning av kombinerade p piller inte har fastst\xe4llts. Crohns sjukdom, ulcer\xf6s kolit, epilepsi, migr\xe4n, endometrios, uterusmyom, porfyri, generaliserad lupus erythematosus, herpes gestationis, Sydenhams korea, hemolytiskt uremiskt syndrom, kolestatisk ikterus kloasma.']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_pages': [9, 10],
 u'_rank': 1,
 u'_type': u'LSFU'}