{'_data': [[u'Unknown',
            [['Cardiac', u'Hj\xe4rtklappning   S\xe4nkning av'],
             ['Nervous system',
              u'Huvudv\xe4rk,   Konvulsioner,   Synkope   ofrivilliga   muskelhyperaktivitet,'],
             ['Eye', u'Mios   Dimsyn,'],
             ['Respiratory', u'Bronkospasm,   Lung\xf6dem,   Astmaattacker hos'],
             ['GI', u'Buksm\xe4rtor,   Kolik, tarmvred,'],
             ['Skin', u'Svettning, hudutslag   Urticaria'],
             ['Vascular', u'Flush'],
             ['General', u'Asteni, pruritus   Perifert \xf6dem'],
             ['Hepato', u'Gallv\xe4gsspasm, f\xf6rh\xf6jda'],
             ['Reproductive system', u'Amenorr\xe9, s\xe4nkt libido,'],
             ['Psychiatric', u'Konfusion, insomnia Hallucinationer,']]]],
 '_pages': [3, 5],
 u'_rank': 11,
 u'_type': u'LFSU'}