{'_data': [['Common', [['General', u'(>1/100, <1/10): Sveda p\xe5 appliceringsst\xe4llet.']]],
           ['Uncommon',
            [['General',
              u'Irritation p\xe5 appliceringsst\xe4llet. Efter l\xe4ngre tids behandling med Doloproct suppositorier (mer \xe4n fyra veckor) finns risk f\xf6r lokala hudf\xf6r\xe4ndringar som atrofi eller telangiektasier. Den l\xe4mpligaste MedDRA-termen (MedDRA version 13.1) anv\xe4ndes f\xf6r att beskriva en viss reaktion och dess synonymer och relaterade tillst\xe5nd.']]],
           ['Unknown',
            [['Skin',
              u'Allergiska hudreaktioner mot n\xe5got av inneh\xe5lls\xe4mnena i Doloproct suppositorier kan inte uteslutas.']]]],
 '_pages': [2, 3],
 u'_rank': 3,
 u'_type': u'LSFU'}