{'_data': [['Very common', []],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk Somnole n s Tr\xf6tth e t'],
             ['GI', u'Illam\xe5ende Buksm\xe4rta Dyspepsi Flatulens Diarr\xe9 F\xf6rstoppning']]],
           ['Uncommon', [['Skin', u'Hudutslag Kl\xe5da Erytem Rodna d']]],
           ['Rare', []],
           ['Very rare', []],
           ['Unknown',
            [['Immune system', u'Allergiska reaktion e r'],
             ['Nervous system', u'Yrsel'],
             ['Eye', u'Synst\xf6rninga r'],
             ['GI', u'Kr\xe4kning a r'],
             ['Skin', u'H\xe5rf\xf6rlust Angio\xf6dem N\xe4sselutslag'],
             ['General', u'\xd6dem Perifera \xf6dem'],
             ['Hepato', u'\xd6kade m\xe4ngder av leverenzymer och gulsot']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 10,
 u'_type': u'MSFU'}