{'_data': [['Very common',
            [['GI', u'Diarr\xe9 Illam\xe5ende'],
             ['General', u'Huvudv\xe4rk'],
             ['Injury',
              u'Vid utredning av patienter med synkope och krampanfall b\xf6r risken f\xf6r hj\xe4rtblock eller']]],
           ['Common',
            [['Infections', u'F\xf6rkylning'],
             ['Metabolism', u'Aptitl\xf6shet'],
             ['Psychiatric', u'Hallucinatio ner** Agitation** Aggressivite t**'],
             ['Nervous system', u'Synkope* Yrsel Insomnia'],
             ['GI', u'Kr\xe4kningar Magtarmbes v\xe4r'],
             ['Skin', u'Utslag Pruritus'],
             ['Musculoskeletal', u'Muskelkram per'],
             ['Renal', u'Urininkontin ens'],
             ['General', u'Tr\xf6tthet Sm\xe4rta'],
             ['Injury', u'Olycksfall']]],
           ['Uncommon',
            [['Nervous system', u'Kramper*'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Gastrointesti nala bl\xf6dningar Mags\xe5r och duodenals\xe5r'],
             ['Investigations',
              u'Liten \xf6kning av serumkonce ntrationen av muskul\xe4rt kreatinkinas']]],
           ['Rare',
            [['Nervous system', u'Extrapyrami dala symtom'],
             ['Cardiac', u'Sinoatriellt block Atrioventrik ul\xe4rt block'],
             ['Hepato', u'Leverp\xe5verk an inklusive hepatit***']]],
           ['Very rare', [['Nervous system', u'Neuroleptisk t malignt syndrom']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 21,
 u'_type': u'MSFU'}