{'_data': [['Very common', [['GI', u'Diarr\xe9 Illam\xe5ende'], ['General', u'Huvudv\xe4rk']]],
           ['Common',
            [['Infections', u'F\xf6rkylning'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric',
<<<<<<< HEAD
              u'Hallucination er** Agitation** Aggressivitet ** Onormala dr\xf6mmar och mardr\xf6mmar **'],
             ['Nervous system', u'Synkope* Yrsel S\xf6mnl\xf6shet'],
             ['GI', u'Kr\xe4kningar Magtarmrub bningar'],
             ['Skin', u'Hudutslag Pruritus'],
             ['Musculoskeletal', u'Muskelkram p'],
             ['Renal', u'Urininkontin ens'],
             ['General', u'Tr\xf6tthet Sm\xe4rta'],
             ['Injury', u'Olycksfall']]],
           ['Uncommon',
            [['Nervous system', u'Krampanfall *'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Gastrointesti nal bl\xf6dning Ventrikel-och duodenals\xe5r'],
             ['Investigations', u'L\xe4ttare stegring av muskul\xe4rt kreatinkinas i serum']]],
           ['Rare',
            [['Nervous system', u'Extrapyrami dala symptom'],
             ['Cardiac', u'Sinoatriellt block Atrioventrik ul\xe4rt block'],
             ['Hepato', u'Leverp\xe5verk an inklusive hepatit***']]],
           ['Very rare', [['Nervous system', u'neuroleptiskt malignt syndrom']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 20,
=======
              u'Hallucinationer** Agitation** Aggressivitet** Onormala dr\xf6mmar och mardr\xf6mmar**'],
             ['Nervous system', u'Synkope* Yrsel S\xf6mnl\xf6shet'],
             ['GI', u'Kr\xe4kningar Magtarmrubbningar'],
             ['Skin', u'Hudutslag Pruritus'],
             ['Musculoskeletal', u'Muskelkramp'],
             ['Renal', u'Urininkontinens'],
             ['General', u'Tr\xf6tthet Sm\xe4rta'],
             ['Injury', u'Olycksfall']]],
           ['Uncommon',
            [['Nervous system', u'Krampanfall*'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Gastrointestinal bl\xf6dning Ventrikel-och duodenals\xe5r'],
             ['Investigations', u'L\xe4ttare stegring av muskul\xe4rt kreatinkinas i serum']]],
           ['Rare',
            [['Nervous system', u'Extrapyramidala symptom'],
             ['Cardiac', u'Sinoatriellt block Atrioventrikul\xe4rt block'],
             ['Hepato', u'Leverp\xe5verkan inklusive hepatit***']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 19,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}