{'_data': [['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighet, anafylaktisk chock'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, eufori, hallucinationer Agitation*, fientlighet*, raseriutbrott*, aggressivitet*, uppr\xf6rdhet* Fysiskt l\xe4kemedelsberoende och abstinenssyndrom'],
             ['Nervous system',
              u'Ofrivilliga r\xf6relser (inklusive toniska/kloniska kramper och muskeltremor)*, hyperaktivitet* Sedering (f\xf6rl\xe4ngd och postoperativ), minskad vakenhet, somnolens, huvudv\xe4rk, yrsel, ataxi, anterograd amnesi**, vars durationer \xe4r direkt relaterade till den administrerade dosen Krampanfall har rapporterats hos prematura barn och nyf\xf6dda barn Konvulsioner vid uts\xe4ttandet av l\xe4kemedlet'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, bradykardi'],
             ['Vascular', u'Hypotension, vasodilatation, tromboflebit, trombos'],
             ['Respiratory',
              u'Andningsdepression, apn\xe9, andningsstillest\xe5nd, dyspn\xe9, laryngospasm, hicka'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, f\xf6rstoppning, muntorrhet'],
             ['Skin',
              u'Hudutslag, urtikaria, kl\xe5da Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]]],
 '_pages': [11, 12],
 u'_rank': 8,
 u'_type': u'LSFU'}