{'_data': [['Very common',
            [['Eye', u'br\xe4nnande och stickande k\xe4nsla'],
             ['GI', u'smakrubbningar \xd6gondroppar med dorzolamidhydroklorid']]],
           ['Common',
            [['Nervous system', u'huvudv\xe4rk*'],
             ['Nervous system', u'huvudv\xe4rk*'],
             ['Eye',
              u'konjunktival injektion, dimsyn, hornhinneerosion, \xf6gonkl\xe5da, t\xe5ravs\xf6ndring \xd6gondroppar med dorzolamidhydroklorid'],
             ['Eye', u'inflammerade \xf6gonlock*, irriterade \xf6gonlock*'],
             ['Eye',
              u'tecken och symtom p\xe5 \xf6gonirritation (t.ex. br\xe4nnande och stickande k\xe4nsla, rinnande \xf6gon, rodnad) inklusive blefarit*, keratit*, nedsatt hornhinnek\xe4nslighet och torra \xf6gon*'],
             ['Respiratory', u'sinuit'],
             ['GI', u'illam\xe5ende*'],
             ['General', u'asteni/utmattning* \xd6gondroppar med timololmaleat']]],
           ['Uncommon',
            [['Nervous system', u'yrsel*'],
             ['Psychiatric', u'depression*'],
             ['Eye', u'iridocyklit*'],
             ['Eye',
              u'irritation inklusive rodnad*, sm\xe4rta*, skorvbildning p\xe5 \xf6gonlocken*, \xf6verg\xe5ende myopi (som upph\xf6rde d\xe5 behandlingen avslutades), svullen hornhinna*, nedsatt intraokul\xe4rt tryck*, avlossning av \xe5derhinnan (efter filtrationskirurgi)* \xd6gondroppar med timololmaleat'],
             ['Eye',
              u'synst\xf6rningar inklusive \xe4ndrad refraktion (p\xe5 grund av avbruten miotisk terapi hos en del patienter)*'],
             ['Cardiac', u'bradykardi*, synkope*'],
             ['Respiratory', u'dyspn\xe9*'],
             ['GI', u'illam\xe5ende*, dyspepsi*'],
             ['Renal', u'njursten'],
             ['General', u'asteni/utmattning*']]],
           ['Rare',
            [['Musculoskeletal', u'systemisk lupus erythematosus'],
             ['Nervous system', u'yrsel*, parestesier* \xd6gondroppar med timololmaleat'],
             ['Nervous system',
              u's\xf6mnl\xf6shet*, minnesf\xf6rlust, parestesier*, f\xf6rsv\xe5rade symtom och fynd vid myastenia gravis, cerebrovaskul\xe4r sjukdom*'],
             ['Psychiatric', u'mardr\xf6mmar*, nedsatt libido*'],
             ['Eye',
              u'ptos, diplopi, \xe5derhinneavlossning efter filtrationskirurgi* (se 4.4 Varningar och f\xf6rsiktighet).'],
             ['Ear', u'tinnitus*'],
             ['Cardiac',
              u'palpitationer*, \xf6dem*, arytmi*, hj\xe4rtblock*, hj\xe4rtstillest\xe5nd*'],
             ['Vascular',
              u'hypotension*, br\xf6stsm\xe4rta*, kongestiv hj\xe4rtsvikt*, cerebral ischemi, klaudikation, Raynauds fenomen*, kalla h\xe4nder och f\xf6tter*'],
             ['Respiratory',
              u'andt\xe4ppa, andningssvikt, snuva \xd6gondroppar med dorzolamidhydroklorid'],
             ['Respiratory', u'n\xe4sblod* \xd6gondroppar med timololmaleat'],
             ['Respiratory',
              u'bronkospasm (i huvudsak hos patienter med bronkospastisk sjukdom)*, hosta*'],
             ['GI', u'svalgirritation, muntorrhet* \xd6gondroppar med timololmaleat'],
             ['GI', u'diarr\xe9, torr mun*'],
             ['Skin', u'kontaktdermatit \xd6gondroppar med dorzolamidhydroklorid'],
             ['Skin', u'utslag* \xd6gondroppar med timololmaleat'],
             ['Skin',
              u'alopeci*, utslag p\xe5minnande om psoriasis eller f\xf6rsv\xe5rad psoriasis*'],
             ['Reproductive system', u'Peyronies sjukdom*'],
             ['General',
              u'symtom och fynd vid systemiska allergiska reaktioner, inklusive angio\xf6dem, n\xe4sselutslag, kl\xe5da, hudutslag, anafylaxi, s\xe4llan bronkospasm \xd6gondroppar med dorzolamidhydroklorid']]],
           ['Unknown',
            [['Musculoskeletal', u'\xd6gondroppar med timololmaleat'],
             ['Nervous system', u'\xd6gondroppar med dorzolamidhydroklorid'],
             ['Psychiatric', u'\xd6gondroppar med timololmaleat'],
             ['Ear', u'\xd6gondroppar med timololmaleat'],
             ['Cardiac', u'\xd6gondroppar med timololmaleat'],
             ['Reproductive system', u'\xd6gondroppar med timololmaleat'],
             ['Metabolism', u'Hypoglykemi'],
             ['Cardiac', u'Atrioventrikul\xe4rt block, hj\xe4rtsvikt'],
             ['GI', u'Smakrubbningar, buksm\xe4rta, kr\xe4kning'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'Myalgi'],
             ['Reproductive system', u'Sexuell dysfunktion']]]],
 '_pages': [5, 7],
 u'_rank': 50,
 u'_type': u'LSFU'}