{'_data': [['Very common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Cardiac',
              u'Hj\xe4rtklaffsp\xe5verkan (inklusive  asymptomatiskt klaffl\xe4ckage) och relaterade f\xf6r\xe4ndringar (perikardit, perikardiell utgjutning)'],
             ['GI', u'Illam\xe5ende, dyspepsi,  magsm\xe4rtor, gastrit'],
             ['General', u'Asteni/tr\xf6tthet']]],
           ['Common',
            [['Psychiatric', u'Depression'],
             ['Nervous system', u'Somnolens'],
             ['Vascular',
              u'Dostinex ger i allm\xe4nhet en  hypotensiv effekt hos patienter under l\xe5ngtidsbehandling, postural hypotension, ansiktsrodnad'],
             ['GI', u'F\xf6rstoppning, kr\xe4kningar'],
             ['Reproductive system', u'Br\xf6stsm\xe4rta'],
             ['Investigations', u'Asymptomatisk minskning av']]],
           ['Uncommon',
            [['Psychiatric', u'\xd6kad libido'],
             ['Nervous system', u'Synkope, parestesi,  \xf6verg\xe5ende hemianopsi'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['Vascular', u'Digital vasospasm, svimning'],
             ['Respiratory', u'N\xe4sbl\xf6dning, dyspn\xe9'],
             ['Skin', u'Alopecia, utslag'],
             ['Musculoskeletal', u'Kramp i fingrar och vader'],
             ['General', u'\xd6dem'],
             ['Investigations',
              u'S\xe4nkta hemoglobinv\xe4rden har  observerats hos kvinnor under de f\xf6rsta mensfria m\xe5naderna.']]],
           ['Very rare', [['Respiratory', u'Fibros']]],
           ['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
             ['Psychiatric',
              u'Aggression,  vanf\xf6rest\xe4llningar, hypersexualitet, patologiskt hasardspel, psykotisk sjukdom.'],
             ['Eye', u'Synst\xf6rningar'],
             ['Respiratory', u'St\xf6rningar i andningsv\xe4garna,  andningssvikt'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Investigations',
              u'\xd6kat blodkreatininfosfokinas,  onormala leverfunktionstester']]]],
 '_pages': [5, 7],
 u'_rank': 26,
 u'_type': u'TSFU'}