{'_data': [['Very common', [['Nervous system', u' parestesi,huvudv\xe4rk']]],
           ['Common',
            [['GI', u' illam\xe5ende, kr\xe4kningar'],
             ['Skin', u' kl\xe5da, erytem, utslag'],
             ['General',
              u' v\xe4rmek\xe4nsla, k\xf6ldk\xe4nsla, sm\xe4rta p\xe5 injektionsst\xe4llet']]],
           ['Uncommon',
            [['Immune system',
              u' \xf6verk\xe4nslighet, anafylaktisk reaktion, anafylaktoid reaktion']]],
           ['Rare', [['Nervous system', u' dysgeusi'], ['Skin', u' urticaria, hyperhidros']]],
           ['Very rare',
            [['Psychiatric', u' agitation, \xe5ngest'],
             ['Nervous system', u' koma, kramp, syncope, presyncope, yrsel, parosmi, tremor'],
             ['Eye',
              u' konjunktivit, okul\xe4r hyperemi, dimsyn, \xf6kat t\xe5rfl\xf6de, \xf6gonlocks\xf6dem'],
             ['Cardiac',
              u' hj\xe4rtstillest\xe5nd, bradykardi, takykardi, arytmi, palpitationer'],
             ['Vascular', u' hypotoni, hypertoni, vasodilatation, blekhet'],
             ['Respiratory',
              u' andningsstillest\xe5nd, lung\xf6dem, bronkospasm, laryngospasm, farynx\xf6dem, dyspn\xe9, n\xe4st\xe4ppa, nysningar, hosta, torr strupe'],
             ['GI', u' diarr\xe9, buksm\xe4rta, hypersekretion av saliv'],
             ['Skin', u' eksem, angio\xf6dem'],
             ['Musculoskeletal', u' muskelkontraktur, muskelsvaghet, ryggsm\xe4rta'],
             ['General',
              u' sjukdomsk\xe4nsla, sm\xe4rta i br\xf6stkorgen, obehag i br\xf6stkorgen, feber, frossa, ansikts\xf6dem, asteni, obehag p\xe5'],
             ['Investigations', u' minskad syrgasm\xe4ttnad']]],
           ['Unknown', [['Skin', u' nefrogen systemisk fibros']]]],
 '_pages': [5, 7],
 u'_rank': 19,
 u'_type': u'LSFU2'}