{'_data': [['Common',
            [['Infections', u'Luftv\xe4gsinfektion,  urinv\xe4gsinfektion'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Palpitationer, takykardi'],
             ['Vascular', u'Hypotension, postural'],
             ['GI', u'Magsm\xe4rtor, dyspepsi,  muntorrhet, illam\xe5ende'],
             ['Skin', u'Pruritus'],
             ['Renal', u'Cystit, urininkontinens']]],
           ['Uncommon',
            [['Immune system', u'Allergiska reaktioner mot  l\xe4kemedlet'],
             ['Metabolism', u'Anorexi, gikt, \xf6kad aptit'],
             ['Psychiatric', u'\xc5ngest, depression, insomnia'],
             ['Nervous system', u'Stroke, hypoestesi, svimning,  tremor'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Angina pectoris, myokardinfarkt'],
             ['GI', u'F\xf6rstoppning, diarr\xe9, flatulens,  kr\xe4kningar, gastroenterit'],
             ['Hepato', u'Onormala leverfunktionstester'],
             ['Skin', u'Hudutslag'],
             ['Renal', u'Dysuri, hematuri, \xf6kad  urineringsfrekvens'],
             ['Reproductive system', u'Impotens'],
             ['Reproductive system', u'Sm\xe4rta, ansikts\xf6dem'],
             ['Investigations', u'Vikt \xf6kning']]],
           ['Very rare',
            [['Blood', u'Leukopeni, trombocytopeni'],
             ['Psychiatric', u'Agitation, oro'],
             ['Nervous system', u'Postural yrsel, parestesier'],
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Bradykardi, hj\xe4rtarytmi'],
             ['Vascular', u'Rodnad'],
             ['Vascular', u'Bronkospasm'],
             ['Hepato', u'Kolestas, hepatit, gulsot'],
             ['Skin', u'Alopeci, purpura, urtikaria'],
             ['Skin', u'Muskelkramper, muskelsvaghet'],
             ['Renal', u'Urineringsst\xf6rningar, nocturi,  polyuri, \xf6kad diures'],
             ['Reproductive system', u'Tr\xf6tthet, sjukdomsk\xe4nsla']]],
           ['Unknown',
            [['Eye', u'\u201dIntraoperative Floppy Iris  Syndrome\u201d (se avsnitt 4.4)'],
             ['GI', u'Smakf\xf6r\xe4ndringar'],
             ['Reproductive system', u'Minskad ejakulation']]]],
 '_pages': [4, 5],
 u'_rank': 35,
 u'_type': u'TSFU'}