{'_data': [['Common',
            [['Endocrine',
              u'menstruations-rubbnin gar, mellanbl\xf6dningar, \xf6mmande br\xf6st'],
             ['Nervous system', u'huvudv\xe4rk, nedst\xe4mdhet'],
             ['Vascular', u'migr\xe4n'],
             ['GI', u'illam\xe5ende'],
             ['Reproductive system', u'leukorr\xe9,']]],
           ['Uncommon',
            [['Nervous system', u'f\xf6r\xe4ndringar i libido'],
             ['Vascular', u'h\xf6gt blodtryck, l\xe5gt blodtryck'],
             ['GI', u'kr\xe4kningar'],
             ['Skin', u'akne, eksem, kl\xe5da'],
             ['Reproductive system', u'vaginit'],
             ['General', u'v\xe4tskeretention, f\xf6r\xe4ndringar i kroppsvikten']]],
           ['Rare',
            [['Immune system', u'\xf6verk\xe4nslighet, astma'],
             ['Endocrine', u'v\xe4tskande br\xf6st'],
             ['Ear', u'hypakusi'],
             ['Vascular', u'tromboembolism'],
             ['Skin', u'erytema nodosum, erytema multiforme']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 10],
 u'_rank': 16,
 u'_type': u'MSFU'}