{'_data': [[u'Unknown',
            [['Blood', u'Bloddyskrasi'],
             ['Immune system', u'Anafylaktisk'],
             ['Metabolism', u'Inadekvat'],
             ['Psychiatric', u'F\xf6rvirringstill   Dysfori   Hallucination   st\xe5nd;   er'],
             ['Nervous system',
              u'D\xe5sighet   Extrapyramid   Epileptiska   ala symtom;   anfall;   Krampanfall;   Parkinsons'],
             ['Cardiac', u'Hj\xe4rtarytmier,   Hj\xe4rtstillest\xe5n   Torsade de'],
             ['Vascular', u'Blodtrycksfall   Svimning'],
             ['Respiratory', u'Bronkospasm'],
             ['Skin', u'Hudutslag'],
             ['General', u'Malignt   Pl\xf6tslig d\xf6d'],
             ['General', u'(NMS)']]]],
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'LFSU'}