{'_data': [['Very common',
            [['Nervous system', u'Muntorrhet %), huvudv\xe4rk (30,3 %)*'],
             ['GI', u'Illam\xe5ende (20,0 %)'],
             ['Skin', u'Svettning (inklusive nattsvettning ) [12,2 %]'],
             ['General', u'placebo. *** Se avsnitt 4.4 4.2 och 4.4). Barn och ungdomar']]],
           ['Common',
            [['Metabolism', u'F\xf6rh\xf6jt serumkolesterol, viktminskning'],
             ['Nervous system',
<<<<<<< HEAD
              u'Onormala dr\xf6mmar, s\xe4nkt libido, yrsel, \xf6kad muskeltonus (hypertoni), insomnia, nervositet, parestesier, sedation, tremor, f\xf6rvirring, personlighets-f\xf6r\xe4n dring'],
=======
              u'Onormala dr\xf6mmar, s\xe4nkt libido, yrsel, \xf6kad muskeltonus (hypertoni), insomnia, nervositet, parestesier, sedation, tremor, f\xf6rvirring, personlighets-f\xf6r\xe4ndring'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Eye', u'Onormal ackommodation, mydriasis, synst\xf6rning'],
             ['Cardiac',
              u'Hypertoni, vasodilatation (mest v\xe4rmevallningar/ blodvallningar), hj\xe4rtklappning'],
             ['Respiratory', u'G\xe4spning'],
             ['GI', u'Minskad aptit (anorexi), f\xf6rstoppning, kr\xe4kning'],
             ['Renal',
<<<<<<< HEAD
              u'Onormal ejakulation/orgasm (m\xe4n), anorgasmi, erektil dysfunktion (impotens), f\xf6rs\xe4mrad urinering (mest sv\xe5righeter att komma ig\xe5ng), menstruations-st\xf6rn ingar s\xe5som \xf6kad bl\xf6dning eller mer oregelbunden bl\xf6dning (t.ex. menorragi, metrorragi), pollakisuri'],
=======
              u'Onormal ejakulation/orgasm (m\xe4n), anorgasmi, erektil dysfunktion (impotens), f\xf6rs\xe4mrad urinering (mest sv\xe5righeter att komma ig\xe5ng), menstruations-st\xf6rningar s\xe5som \xf6kad bl\xf6dning eller mer oregelbunden bl\xf6dning (t.ex. menorragi, metrorragi), pollakisuri'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Asteni (tr\xf6tthet), frossbrytningar']]],
           ['Uncommon',
            [['Blood', u'Ekkymos, gastrointestinal bl\xf6dning'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['Nervous system',
              u'Apati, hallucinationer, myoklonus, agitation, f\xf6rs\xe4mrad koordination och balans'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'Postural hypotoni, synkope, takykardi'],
             ['GI', u'Bruxism, diarr\xe9, f\xf6r\xe4ndrad smakupplevelse'],
             ['Skin', u'Hudutslag, alopeci'],
             ['Renal', u'Onormal orgasm (kvinnor), urinretention'],
             ['General',
<<<<<<< HEAD
              u'Angio\xf6dem, Ljusk\xe4nslighets-reakt ion * F\xf6rekomsten av huvudv\xe4rk i poolade kliniska studier var 30,3 % med venlafaxin och 31.3 % med']]],
           ['Rare',
            [['Nervous system',
              u'Akatisi/psyko-m otorisk rastl\xf6shet, kramper, manisk reaktion'],
=======
              u'Angio\xf6dem, Ljusk\xe4nslighets-reaktion * F\xf6rekomsten av huvudv\xe4rk i poolade kliniska studier var 30,3 % med venlafaxin och 31.3 % med']]],
           ['Rare',
            [['Nervous system',
              u'Akatisi/psyko-motorisk rastl\xf6shet, kramper, manisk reaktion'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Renal', u'Urininkontinens']]],
           ['Unknown',
            [['Blood',
              u'Slemhinnebl\xf6dning, f\xf6rl\xe4ngd bl\xf6dningstid, trombocytopeni, bloddyskrasier (inklusive agranulocytos, aplastisk anemi, neutropeni och pancytopeni)'],
             ['Metabolism',
              u'Onormala leverfunktionsprover, hyponatremi, hepatit, inadekvat ADH-sekretion (SIADH), f\xf6rh\xf6jt prolaktin'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom (NMS), serotonergt syndrom, delirium, extrapyramidala reaktioner (inklusive dystoni och dyskinesi), tardiv dyskinesi, suicidalt beteende, suicidtankar** Vertigo Aggression***'],
             ['Eye', u'Tr\xe5ngvinkelglaukom'],
             ['Cardiac',
              u'Hypotoni, QT-f\xf6rl\xe4gning, kammarflimmer, kammartakykardi (inklusive torsade de pointes)'],
             ['Respiratory', u'Pulmonell eosionofili'],
             ['GI', u'Pankreatit'],
             ['Skin',
              u'Erythema multiforme, toxisk epidermal nekrolys, Stevens-Johnsons syndrom, kl\xe5da, n\xe4sselutlag'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['General', u'Anafylaxi']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 33,
 u'_type': u'MSFU'}