{'_data': [['Very common',
            [['GI',
              u'Minskad aptit, illam\xe5ende, kr\xe4kningar, buksm\xe4rta, inflammation och s\xe5r i slemhinnan i mun och hals (s\xe4rskilt under de f\xf6rsta 24-48 timmarna efter administrering av metotrexat). Stomatit, dyspepsi Mycket vanliga'],
             ['Hepato',
<<<<<<< HEAD
              u'\xd6kning av leverenzymer (ALAT, ASAT, alkalisk fosfatas och bilirubin).']]],
=======
              u'\xd6kning av leverenzymer (ALAT, ASAT, alkalisk fosfatas och bilirubin).'],
             ['General', u'Mycket vanliga']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Common',
            [['Blood', u'Leukopeni, trombocytopeni, anemi'],
             ['Nervous system', u'Huvudv\xe4rk, tr\xf6tthet, d\xe5sighet'],
             ['Respiratory',
<<<<<<< HEAD
              u'Lungkompli-kati oner pga interstitiell alveolit/ pneumonit och relaterade d\xf6dsfall (oberoende av dos och duration av metotrexat-beha ndling). Typiska symptom kan vara: allm\xe4n sjukdomsk\xe4nsla; torr, irriterande hosta; andn\xf6d progredierande andnings-stillest \xe5nd, br\xf6stsm\xe4rta, feber. Om s\xe5dana komplikationer misst\xe4nks m\xe5ste metotrexatbehan dling avbrytas omedelbart och infektion (inklusive lung-inflammati on) uteslutas.'],
             ['GI',
              u'Diarr\xe9 (s\xe4rskilt under de f\xf6rsta 24-48 timmarna efter administrering av metotrexat). Vanliga'],
             ['Skin', u'Exantem, erytem, kl\xe5da']]],
           ['Uncommon',
            [['Blood', u'Pancytopeni, agranulocytos, hematopoetiska rubbningar.'],
             ['Nervous system', u'Yrsel, f\xf6rvirrings-tillst\xe5 nd, depression, kramper'],
=======
              u'Lungkomplikationer pga interstitiell alveolit/pneumonit och relaterade d\xf6dsfall (oberoende av dos och duration av metotrexat-behandling). Typiska symptom kan vara: allm\xe4n sjukdomsk\xe4nsla; torr, irriterande hosta; andn\xf6d progredierande till andningsstillest\xe5nd, br\xf6stsm\xe4rta, feber. Om s\xe5dana komplikationer misst\xe4nks m\xe5ste metotrexatbehandling avbrytas omedelbart och infektion (inklusive lunginflammation) uteslutas.'],
             ['GI',
              u'Diarr\xe9 (s\xe4rskilt under de f\xf6rsta 24-48 timmarna efter administrering av metotrexat). Vanliga'],
             ['Skin', u'Exantem, erytem, kl\xe5da'],
             ['General', u'Vanliga']]],
           ['Uncommon',
            [['Blood', u'Pancytopeni, agranulocytos, hematopoetiska rubbningar.'],
             ['Nervous system', u'Yrsel, f\xf6rvirringstillst\xe5 nd, depression, kramper'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Neoplasms',
              u'Enstaka fall av lymfom, som i ett antal fall gick i regress efter avbrytande av behandlingen med metotrexat. I en nyligen genomf\xf6rd studie kunde det inte fastst\xe4llas att behandling med metotrexat ger \xf6kad incidens av lymfom'],
             ['Respiratory', u'Lungfibros'],
             ['GI', u'Gastrointestinala s\xe5r och bl\xf6dningar. Mindre vanliga'],
             ['Hepato',
<<<<<<< HEAD
              u'Utveckling av fettlever, fibros och cirrhos (upptr\xe4der frekvent trots regelbundet kontrollerade normala leverenzym-v\xe4rd en); diabetes-metabolism; minskning av serumalbumin.'],
             ['Skin',
              u'Urtikaria, fotosensibilitet, \xf6kad hud-pigmenterin g, h\xe5ravfall, \xf6kning av reumatiska noduli, herpes zoster, sm\xe4rtsamma lesioner av psoriasisplack; sv\xe5ra toxiska reaktioner: vaskulit, herpetiforma hudutslag, Stevens-Johnson s syndrom, toxisk epidermal nekrolys (Lyells syndrom).'],
=======
              u'Utveckling av fettlever, fibros och cirrhos (upptr\xe4der frekvent trots regelbundet kontrollerade normala leverenzym-v\xe4rden); diabetes-metabolism; minskning av serumalbumin.'],
             ['Skin',
              u'Urtikaria, fotosensibilitet, \xf6kad hud-pigmentering, h\xe5ravfall, \xf6kning av reumatiska noduli, herpes zoster, sm\xe4rtsamma lesioner av psoriasisplack; sv\xe5ra toxiska reaktioner: vaskulit, herpetiforma hudutslag, Stevens-Johnsons syndrom, toxisk epidermal nekrolys (Lyells syndrom).'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Musculoskeletal', u'Artralgi, myalgi, osteoporos'],
             ['Renal',
              u'Inflammation och s\xe5r i urinbl\xe5san (eventuellt med hematuri), dysuri.'],
             ['General',
<<<<<<< HEAD
              u'Sv\xe5ra allergiska reaktioner progredierande till anafylaktisk chock'],
=======
              u'Sv\xe5ra allergiska reaktioner progredierande till anafylaktisk chock Mindre vanliga'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Reproductive system', u'Inflammation och s\xe5r i vagina']]],
           ['Rare',
            [['Cardiac', u'Perikardit, exsudat i perikardiet, hj\xe4rttamponad'],
             ['Blood', u'Megaloblastisk anemi'],
<<<<<<< HEAD
             ['Nervous system', u'Sv\xe5r synp\xe5verkan, hum\xf6r-sv\xe4ngnin gar'],
             ['Eye', u'Synrubbningar'],
             ['Vascular',
              u'Hypotension, trombo-embolis ka h\xe4ndelser (inklusive arteriella och cerebrala tromboser, tromboflebit, djupa ventromboser, retinala ventromboser, lungemboli).'],
=======
             ['Nervous system', u'Sv\xe5r synp\xe5verkan, hum\xf6rsv\xe4ngning ar'],
             ['Eye', u'Synrubbningar'],
             ['Vascular',
              u'Hypotension, tromboembolisk a h\xe4ndelser (inklusive arteriella och cerebrala tromboser, tromboflebit, djupa ventromboser, retinala ventromboser, lungemboli).'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Respiratory', u'Faryngit, apn\xe9, bronkialastma'],
             ['GI', u'Enterit, melena. Gingivit, malabsorption S\xe4llsynta'],
             ['Hepato', u'Akut hepatit och hepatotoxicitet'],
             ['Skin',
              u'\xd6kad pigmentering i naglar, akne, petekier, ekkymos, erythema multiforme, erytemat\xf6sa huderuptioner.'],
             ['Musculoskeletal', u'Stressfraktur'],
<<<<<<< HEAD
             ['Renal', u'Njursvikt, oliguri, anuri, azotemi']]],
=======
             ['Renal', u'Njursvikt, oliguri, anuri, azotemi'],
             ['General', u'S\xe4llsynta']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Very rare',
            [['Infections',
              u'Sepsis, opportunistiska infektioner (kan vara fatala i vissa fall), infektioner orsakade av cytomegalovirus'],
             ['Blood',
<<<<<<< HEAD
              u'Sv\xe5ra fall av benm\xe4rgs-depres sion, aplastisk anemi. Lymfadenopati, lymfo-proliferati va rubbningar (delvis reversibla), eosinofili och neutropeni'],
             ['Immune system', u'Immuno-suppres sion, hypogamma-glo bulinaemi'],
             ['Psychiatric', u'Insomnia'],
             ['Nervous system',
              u'Sm\xe4rta, minskad muskelstyrka eller parestesier i extremiteterna, smak-f\xf6r\xe4ndring ar (metallsmak), meningism (paralys, kr\xe4kningar), akut aseptisk meningit'],
             ['Eye', u'Konjunktivit, retinopati'],
             ['Respiratory',
              u'Pneumocystis carinii-pneumon i, andn\xf6d, kronisk obstruktiv lungsjukdom. Infektioner inkluderande lung-inflammati on har ocks\xe5 observerats. Pleuraexsudat'],
             ['GI', u'Hematemes, toxisk megakolon Mycket s\xe4llsynta'],
             ['Hepato',
              u'Reaktivering av kronisk hepatit, akut lever-degenereri ng. Dessutom har herpes simplex hepatit och nedsatt leverfunktion observerats (se \xe4ven avsnitt 4.4 betr\xe4ffande leverbiopsi).'],
             ['Skin',
              u'Akut paronyki, furunkulos, telangiektasier. Dessutom har nocardios, histoplasma och kryptokockos samt spridd herpes simplex rapporterats. Allergisk vaskulit, hidradenit'],
             ['Renal', u'Proteinuri'],
             ['General', u'Feber, f\xf6rs\xe4mrad s\xe5rl\xe4kning'],
             ['Reproductive system',
              u'Minskad libido, impotens, oligospermi, menstruationsru bbning, vaginal flytning, infertilitet']]]],
 '_note': u' ANOMALI in Headers ?MSFU ANOMALI in Headers ANOMALI in Headers',
 '_pages': [6, 9],
 u'_rank': 42,
=======
              u'Sv\xe5ra fall av benm\xe4rgsdepressi on, aplastisk anemi. Lymfadenopati, lymfoproliferativa rubbningar (delvis reversibla), eosinofili och neutropeni'],
             ['Immune system', u'Immunosuppressi on, hypogammaglobul inaemi'],
             ['Psychiatric', u'Insomnia'],
             ['Nervous system',
              u'Sm\xe4rta, minskad muskelstyrka eller parestesier i extremiteterna, smakf\xf6r\xe4ndringar (metallsmak), meningism (paralys, kr\xe4kningar), akut aseptisk meningit'],
             ['Eye', u'Konjunktivit, retinopati'],
             ['Respiratory',
              u'Pneumocystis carinii-pneumoni, andn\xf6d, kronisk obstruktiv lungsjukdom. Infektioner inkluderande lunginflammation har ocks\xe5 observerats. Pleuraexsudat'],
             ['GI', u'Hematemes, toxisk megakolon Mycket s\xe4llsynta'],
             ['Hepato',
              u'Reaktivering av kronisk hepatit, akut lever-degenerering. Dessutom har herpes simplex hepatit och nedsatt leverfunktion observerats (se \xe4ven avsnitt 4.4 betr\xe4ffande leverbiopsi).'],
             ['Skin',
              u'Akut paronyki, furunkulos, telangiektasier. Dessutom har nocardios, histoplasma och kryptokockos samt spridd herpes simplex rapporterats. Allergisk vaskulit, hidradenit'],
             ['Renal', u'Proteinuri'],
             ['General', u'Feber, f\xf6rs\xe4mrad s\xe5rl\xe4kning Mycket s\xe4llsynta'],
             ['Reproductive system',
              u'Minskad libido, impotens, oligospermi, menstruationsrubb ning, vaginal flytning, infertilitet']]]],
 '_note': u' ANOMALI in Headers ?MSFU ANOMALI in Headers ANOMALI in Headers ANOMALI in Headers',
 '_pages': [6, 10],
 u'_rank': 45,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}