{'_data': [['Very common',
            [['GI',
              u'Minskad aptit, illam\xe5ende, kr\xe4kningar, buksm\xe4rta, inflammation och s\xe5r i slemhinnan i mun och hals (s\xe4rskilt under de f\xf6rsta 24-48 timmarna efter administrering av Ebetrex). Stomatit, dyspepsi.'],
             ['Hepato',
              u'\xd6kning av leverenzymer (ALAT, [GPT], ASAT, [GOT), alkalisk fosfatas och bilirubin). Mycket vanliga']]],
           ['Common',
            [['Blood', u'Leukopeni, trombocytopeni , anemi.'],
             ['Nervous system', u'Huvudv\xe4rk, tr\xf6tthet, d\xe5sighet.'],
             ['Respiratory',
              u'Lungkomplikat ioner pga interstitiell alveolit/pneum onit och relaterade d\xf6dsfall (oberoende av dos och duration av metotrexatbeha ndling). Typiska symtom kan vara: allm\xe4n sjukdomsk\xe4nsl a; torr, irriterande hosta; andn\xf6d progredierande till andningsstillest \xe5nd, br\xf6stsm\xe4rta, feber. Om s\xe5dana komplikationer misst\xe4nks m\xe5ste Ebetrex-behand ling avbrytas omedelbart och infektion (inklusive lunginflammati on) uteslutas.'],
             ['GI',
              u'Diarr\xe9 (s\xe4rskilt under de f\xf6rsta 24-48 timmarna efter administrering av Ebetrex).'],
             ['Hepato', u'Vanliga'],
             ['Skin', u'Exantem, erytem, kl\xe5da.']]],
           ['Uncommon',
            [['Blood', u'Pancytopeni, agranulocytos, hematopoetiska rubbningar.'],
             ['Immune system', u'Allergiska reaktioner, anafylaktisk chock.'],
             ['Metabolism', u'Diabetes mellitus.'],
             ['Psychiatric', u'Depression.'],
             ['Nervous system', u'Yrsel, f\xf6rvirringstillst \xe5nd, kramper.'],
             ['Neoplasms',
              u'Enstaka fall av lymfom, som i ett antal fall gick i regress efter avbrytande av behandlingen med metotrexat. I en nyligen genomf\xf6rd studie kunde det inte fastst\xe4llas att behandling med metotrexat ger \xf6kad incidens av lymfom.'],
             ['Vascular', u'Vaskulit (som sv\xe5ra toxiska symtom).'],
             ['Respiratory', u'Lungfibros.'],
             ['GI', u'Gastrointestinal a s\xe5r och bl\xf6dningar.'],
             ['Hepato',
              u'Utveckling av fettlever, fibros och cirrhos (upptr\xe4der frekvent trots regelbundet kontrollerade normala leverenzym-v\xe4r den); minskning av serumalbumin. Mindre vanliga'],
             ['Skin',
              u'Urtikaria, fotosensibilitet, \xf6kad hud-pigmenteri ng, h\xe5ravfall, onormal s\xe5rl\xe4kning, \xf6kning av reumatiska noduli, herpes zoster, sm\xe4rtsamma lesioner av psoriasisplack. (Psoriatiska lesioner som f\xf6rv\xe4rras pga UV-str\xe5lning under samtidig behandling med metotrexat (se \xe4ven avsnitt 4.4)); sv\xe5ra toxiska reaktioner: vaskulit, herpetiforma hudutslag, Stevens-Johnso ns syndrom, toxisk epidermal nekrolys (Lyells syndrom).'],
             ['Musculoskeletal', u'Artralgi, myalgi, osteoporos.'],
             ['Renal',
              u'Inflammation och s\xe5r i urinbl\xe5san (eventuellt med hematuri), dysuri.'],
             ['General',
              u'Efter intramuskul\xe4r anv\xe4ndning av metotrexat kan lokala biverkningar (br\xe4nnande k\xe4nsla) eller skada (bildande av steril abscess, nedbrytning av fettv\xe4vnad) uppst\xe5 vid injektionsst\xe4llet'],
             ['Reproductive system', u'Inflammation och s\xe5r i vagina.']]],
           ['Rare',
            [['Cardiac', u'Perikardit, exsudat i perikardiet, hj\xe4rttamponad'],
             ['Blood', u'Megaloblastisk anemi.'],
             ['Psychiatric', u'Hum\xf6rsv\xe4ngni ngar.'],
             ['Eye', u'Allvarliga synrubbningar.'],
             ['Vascular',
              u'Hypotension, tromboembolis ka h\xe4ndelser (inklusive arteriella och cerebrala tromboser, tromboflebit, djupa ventromboser, retinala ventromboser, lungemboli).'],
             ['Respiratory',
              u'Faryngit, apn\xe9, bronkialastmali knande reaktioner med hosta, dyspn\xe9 och patologiska fynd i lungfunktionste'],
             ['GI', u'Enterit, melena. Gingivit, malabsorption.'],
             ['Hepato', u'Akut hepatit och hepatotoxicitet. S\xe4llsynta'],
             ['Skin',
              u'\xd6kad pigmentering i naglar, onykolys, akne, petekier, ekkymos, erythema multiforme, erytemat\xf6sa huderuptioner.'],
             ['Musculoskeletal', u'Stressfraktur.'],
             ['Renal', u'Njursvikt, oliguri, anuri, azotemi.'],
             ['Reproductive system', u'Oligospermi, menstruationsst \xf6rning.']]],
           ['Very rare',
            [['Blood',
              u'Sv\xe5ra fall av benm\xe4rgsdepre ssion, aplastisk anemi. Lymfadenopati, lymfoproliferati va rubbningar (delvis reversibla), eosinofili och neutropeni. De f\xf6rsta tecknen p\xe5 dessa livshotande komplikationer kan vara: feber, ont i halsen, s\xe5r i munnens slemhinna, influensaliknan de besv\xe4r, kraftig utmattning, epistaxis och dermatorrhagia. Anv\xe4ndning av metotrexat ska genast avbrytas om antalet blodkroppar sjunker signifikant.'],
             ['Immune system',
              u'Immunosuppre ssion. Hypogammagl obulinaemi. Allergisk vaskulit'],
             ['Psychiatric', u'Insomnia.'],
             ['Nervous system',
              u'Sm\xe4rta, minskad muskelstyrka eller parestesier i extremiteterna, smakf\xf6r\xe4ndring ar (metallsmak), akut aseptisk meningit med meningism (paralys, kr\xe4kningar).'],
             ['Eye', u'Konjunktivit, retinopati.'],
             ['Respiratory',
              u'Pneumocystis carinii-pneumo ni, och andra pulmonella infektioner, kronisk obstruktiv lungsjukdom. Pleuraexsudat.'],
             ['GI', u'Hematemes, toxisk megakolon.'],
             ['Hepato',
              u'Reaktivering av kronisk hepatit, akut lever-degenerer ing. leversvikt. Dessutom har, herpes simplex hepatit och nedsatt leverfunktion observerats (se \xe4ven avsnitt 4.4 betr\xe4ffande leverbiopsi). Mycket s\xe4llsynta'],
             ['Skin', u'Akut paronyki, furunkulos, telangiektasier, hidradenit.'],
             ['Renal', u'Proteinuri.'],
             ['General',
              u'Feber. Subkutan administrering av metotrexat visar god tolerans. Endast lindriga lokala hudreaktioner, av vilka antalet minskade under behandlingens g\xe5ng, har hitills observerats.'],
             ['Reproductive system',
              u'Minskad libido, impotens, vaginal flytning, infertilitet, gynekomasti.']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 15],
 u'_rank': 47,
 u'_type': u'MSFU'}