{'_data': [[u'Unknown',
            [['Blood', u'Koagulopati - -'],
             ['Immune system', u'Anafylaktisk'],
             ['Metabolism', u'Hypokalemi Hyperglykemi -'],
             ['Nervous system', u'Kramp, huvudv\xe4rk'],
             ['Vascular', u'Vallningar Hypertoni,   Hypotoni'],
             ['Respiratory', u'- -   Bronkospasm,   dyspn\xe9'],
             ['GI', u'Diarr\xe9, kr\xe4kningar,   Sm\xe4rta i \xf6vre delen'],
             ['Hepato', u'\xd6kade v\xe4rden av   Kolestas -'],
             ['Skin', u'Utslag, pruritus   Urtikaria'],
             ['Renal', u'Stegrat serumkreatinin'],
             ['General', u'- Sm\xe4rta   p\xe5   infusionsst\xe4llet']]]],
 '_pages': [4, 5],
 u'_rank': 11,
 u'_type': u'LFSU'}