{'_data': [['Common',
            [['Infections', u'Candidainfektioner i munh\xe5la och svalg'],
             ['Nervous system', u'Huvudv\xe4rk, tremor'],
             ['Cardiac', u'Palpitationer'],
             ['Respiratory', u'L\xe4tt halsirritation, hosta, heshet']]],
           ['Uncommon',
            [['Psychiatric',
              u'Aggression, psykomotorisk hyperaktivitet,  oro, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac', u'Takykardi'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Muskelkramper']]],
           ['Rare',
            [['Immune system',
              u'Omedelbara eller f\xf6rsenade  \xf6verk\xe4nslighetsreaktioner, t.ex. exantem, urtikaria, pruritus, dermatit, angio\xf6dem och anafylaktisk reaktion'],
             ['Metabolism', u'Hypokalemi'],
             ['Cardiac',
              u'Hj\xe4rtarytmier, t.ex. f\xf6rmaksflimmer,  supraventrikul\xe4r takykardi, extrasystoli'],
             ['Respiratory', u'Bronkospasm']]],
           ['Very rare',
            [['Endocrine',
              u'Cushings syndrom, binjuresuppression,  h\xe4mmad l\xe4ngdtillv\xe4xt, minskad bent\xe4thet'],
             ['Metabolism', u'Hyperglukemi'],
             ['Psychiatric', u'Depression, beteendest\xf6rningar (fr\xe4mst hos  barn)'],
             ['Nervous system', u'Smakf\xf6r\xe4ndringar'],
             ['Eye', u'Katarakt och glaukom'],
             ['Cardiac', u'Angina pectoris. F\xf6rl\xe4ngning av  QTc-intervallet'],
             ['Vascular', u'Variationer i blodtryck']]]],
 '_pages': [7, 8],
 u'_rank': 21,
 u'_type': u'TSFU'}