{'_data': [['Very common',
            [['Metabolism',
              u'f\xf6rh\xf6jt totalkolesterol (fastande)  f\xf6rh\xf6jt LDL-kolesterol (fastande)'],
             ['Psychiatric', u's\xf6mnl\xf6shet*'],
             ['Nervous system', u'huvudv\xe4rk*  yrsel'],
             ['GI', u'illam\xe5ende  f\xf6rh\xf6jt pankreasamylas'],
             ['Hepato', u'f\xf6rh\xf6jda transaminaser']]],
           ['Common',
            [['Blood',
              u'minskat antal vita blodkroppar  s\xe4nkt hemoglobin  minskat antal blodpl\xe4ttar'],
             ['Metabolism', u'minskad aptit  f\xf6rh\xf6jda triglycerider (fastande)'],
             ['Psychiatric',
              u'onormala dr\xf6mmar  depression* s\xf6mnst\xf6rningar s\xe4nkt st\xe4mningsl\xe4ge'],
             ['Nervous system', u's\xf6mnighet'],
             ['GI',
              u'buksm\xe4rta*  kr\xe4kning f\xf6rh\xf6jt lipas obehagsk\xe4nsla i buken muntorrhet'],
             ['Hepato', u'f\xf6rh\xf6jt bilirubin'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon', [['Immune system', u'immunreaktiveringssyndrom']]]],
 '_pages': [9, 11],
 u'_rank': 13,
 u'_type': u'TSFU'}