{'_data': [['Very common',
            [['Psychiatric', u's\xf6mnl\xf6shet*'],
             ['GI', u'illam\xe5ende  f\xf6rh\xf6jt pankreasamylas'],
             ['Hepato', u'f\xf6rh\xf6jda transaminaser']]],
           ['Common',
            [['Immune system', u'minskad aptit  f\xf6rh\xf6jda triglycerider (fastande)'],
             ['Psychiatric',
              u'onormala dr\xf6mmar  depression* s\xf6mnst\xf6rningar s\xe4nkt st\xe4mningsl\xe4ge'],
             ['Nervous system', u's\xf6mnighet'],
             ['GI',
              u'buksm\xe4rta*  kr\xe4kning f\xf6rh\xf6jt lipas obehagsk\xe4nsla i buken muntorrhet'],
             ['Hepato', u'f\xf6rh\xf6jt bilirubin'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon', [['Immune system', u'immunreaktiveringssyndrom']]]],
 '_pages': [10, 12],
 u'_rank': 10,
 u'_type': u'TSFU'}