{'_data': [['Very common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk ***'],
             ['GI', u'Illam\xe5ende, muntorrhet'],
             ['Skin', u'Hyperhidros (inklusive nattliga svettningar)']]],
           ['Common',
            [['Metabolism', u'Minskad aptit'],
             ['Psychiatric',
<<<<<<< HEAD
              u'F\xf6rvirrings-tills t\xe5nd, personlighets-f\xf6 r\xe4ndring, anorgasmi, minskad libido, nervositet, s\xf6mnl\xf6shet, onormala dr\xf6mmar'],
=======
              u'F\xf6rvirrings-tillst\xe5nd, personlighets-f\xf6r\xe4ndring, anorgasmi, minskad libido, nervositet, s\xf6mnl\xf6shet, onormala dr\xf6mmar'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Somnolens, tremor, parestesi, hypertoni'],
             ['Eye', u'Synst\xf6rningar inklusive dimsyn, mydriasis, onormal ackommodation'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['Vascular', u'Hypertoni, vasodilatation (mest blodvallning)'],
             ['Respiratory', u'G\xe4spning'],
             ['GI', u'Kr\xe4kning, diarr\xe9, f\xf6rstoppning'],
             ['Renal', u'Dysuri (mest sv\xe5righeter att komma ig\xe5ng), pollakisuri'],
             ['Reproductive system',
<<<<<<< HEAD
              u'Menstruations-s t\xf6rningar s\xe5som \xf6kad bl\xf6dning eller oregelbunden bl\xf6dning (t ex menorragi, metrorragi), ejakulations-st\xf6 rningar, erektil dysfunktion'],
=======
              u'Menstruations-st\xf6rningar s\xe5som \xf6kad bl\xf6dning eller oregelbunden bl\xf6dning (t ex menorragi, metrorragi), ejakulations-st\xf6rningar, erektil dysfunktion'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Asteni, tr\xf6tthet, frossbrytningar'],
             ['Investigations', u'F\xf6rh\xf6jt kolesterolv\xe4rde']]],
           ['Uncommon',
            [['Psychiatric',
<<<<<<< HEAD
              u'Hallucinationer, overklighets-up pfattning, uppr\xf6rdhet, onormal orgasm (hos kvinnor), apati, hypomani, bruxism,'],
=======
              u'Hallucinationer, overklighets-uppfattning, uppr\xf6rdhet, onormal orgasm (hos kvinnor), apati, hypomani, bruxism,'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system',
              u'Akatisi/psykom otorisk rastl\xf6shet, synkope, myoklonus, f\xf6rs\xe4mrad koordination, balansrubbning, dysgeusi'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Ortostatisk, hypotoni'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Magtarmbl\xf6dni ng'],
             ['Skin',
              u'Angio\xf6dem, ljusk\xe4nslighets-reaktion, ekkymos, hudutslag, alopeci'],
             ['Renal', u'Urinretention'],
             ['Investigations', u'Vikt\xf6kning, viktminskning']]],
           ['Rare',
            [['Psychiatric', u'Mani'],
             ['Nervous system', u'Kramper'],
<<<<<<< HEAD
             ['Renal', u'Urin-inkonti nens']]],
=======
             ['Renal', u'Urin-inkontinens']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Blood',
              u'Trombocytopeni, blodsjukdomar inklusive agranulocytos, aplastisk anemi, neutropeni, pancytopeni'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Endocrine', u'Inadekvat ADH-sekretion (SIADH)'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Suicidtankar och suicidalt beteende*, delirium, aggression**'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom (NMS), serotonergt syndrom, extrapyramidala sjukdomar inklusive dystoni och dyskinesi, tardiv dyskinesi'],
             ['Eye', u'Tr\xe5ngvinkelglaukom'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Ventrikelflimmer, ventrikeltakykardi inklusive torsade de pointes'],
             ['Vascular', u'Hypotoni, bl\xf6dning (slemhinnebl\xf6dning)'],
             ['Respiratory', u'Pulmonell eosinofili'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit, onormala leverfunktionsv\xe4rden'],
             ['Skin',
              u'Steven-Johnsons syndrom, erythema multiforme, toxisk epidermal nekrolys, kl\xe5da, n\xe4sselutslag'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Investigations',
              u'F\xf6rl\xe4ngd QT-tid, f\xf6rl\xe4ngd bl\xf6dningstid, \xf6kade prolaktiniv\xe5er i blodet']]]],
 '_note': u' ?MSFU ANOMALI in Headers ANOMALI in Headers ANOMALI in Headers',
 '_pages': [9, 12],
 u'_rank': 44,
 u'_type': u'MSFU'}