{'_data': [['Common',
            [['Blood', u'Anemi'],
             ['Immune system', u'\xd6verk\xe4nslighet inklusive'],
             ['Vascular', u'Hematom'],
             ['Respiratory', u'Epistaxis Hemoptys'],
             ['GI', u'Bl\xf6dning fr\xe5n magtarmkanalen'],
             ['Skin', u'Utslag Ekkymos'],
             ['Renal', u'Hematuri'],
             ['General',
              u'Hematom vid k\xe4rlpunktionsst\xe4llet Bl\xf6dning vid punktionsst\xe4llet'],
             ['Injury', u'Kontusion Bl\xf6dning efter']]],
           ['Uncommon',
            [['Immune system', u'angio\xf6dem'],
             ['Eye', u'Bl\xf6dning i \xf6gat'],
             ['GI',
              u'Retroperitoneal bl\xf6dning Rektal bl\xf6dning Hematochezi Bl\xf6dning fr\xe5n tandk\xf6ttet'],
             ['Injury', u'ingrepp']]],
           ['Rare', [['Blood', u'Trombocyto-peni'], ['Injury', u'Subkutant hematom']]],
           ['Unknown', [['Blood', u'Trombotisk trombocyto-pen purpura (TTP)']]]],
 '_note': u' ANOMALI in Headers ?MSFU',
 '_pages': [5, 7],
 u'_rank': 16,
 u'_type': u'MSFU'}