{'_data': [['Common',
            [['GI', u' Illam\xe5ende, diarr\xe9.  '],
             ['Skin', u' Exantem.  '],
             ['Vascular', u' Tromboflebit (vid intraven\xf6s injektion). ']]],
           ['Uncommon', [['Blood', u' Eosinofili.  '], ['Skin', u' Urtikaria.  ']]],
           ['Rare',
            [['Immune system', u' Anafylaktiska reaktioner.  '],
             ['Blood', u' Agranulocytos, leukopeni,  trombocytopeni. '],
             ['Infections', u' Pseudomembran\xf6s kolit. '],
             ['Hepato', u' Kolestatisk leverp\xe5verkan. '],
             ['Investigations', u' Njurp\xe5verkan med kreatininstegring. ']]]],
 '_pages': [3, 3],
 u'_rank': 10,
 u'_type': u'DFSU'}