{'_data': [['Common',
            [['General', u' Anorexi, sm\xe4rta p\xe5 tum\xf6rst\xe4llet, feber och frossa.  '],
             ['Blood',
              u' Granulocytopeni med maximal s\xe4nkning 7:e - 11:e dagen och viss  p\xe5verkan p\xe5 trombocyter och r\xf6da blodkroppar. '],
             ['GI', u' F\xf6rstoppning, ileus, buksm\xe4rtor. '],
             ['Skin', u' Alopeci, lokala reaktioner p\xe5 injektionsst\xe4llet. '],
             ['Nervous system',
              u' Bortfall av djupa senreflexer, domningar och parestesier i fingrar och t\xe5r, myalgi. ']]],
           ['Uncommon',
            [['General', u' Muskelsvaghet.  '],
             ['Blood', u' Trombocytopeni. '],
             ['GI', u' Illam\xe5ende, kr\xe4kningar. '],
             ['Respiratory', u' Bronkospasm. '],
             ['Nervous system', u' Huvudv\xe4rk. ']]],
           ['Rare',
            [['Endocrine', u' SIADH (f\xf6rh\xf6jd ADH-sekretion)  '],
             ['GI', u' Stomatit, diarr\xe9.  '],
             ['Skin', u' Makulopapul\xf6st utslag. '],
             ['Nervous system', u' Konvulsioner, depression. '],
             ['Eye', u' Synf\xf6rlust (vid kombinationsbehandling). '],
             ['Ear', u' Partiell eller total d\xf6vhet. ']]]],
 '_pages': [3, 3],
 u'_rank': 16,
 u'_type': u'DFSU'}