{'_data': [['Common',
            [['Eye', u'Okul\xe4r bl\xf6dning (inkl. konjunktival bl\xf6dning)  '],
             ['Vascular', u'\xd6vrig bl\xf6dning, hematom  '],
             ['GI', u'Gastrointestinal bl\xf6dning (inkl. hematemes och melena),  ']]],
           ['Uncommon',
            [['Vascular', u'Intraabdominal bl\xf6dning  '],
             ['Reproductive system', u'Onormal vaginal bl\xf6dning, urogenital bl\xf6dning  '],
             ['General', u'Bl\xf6dning vid appliceringsst\xe4lle  '],
             ['Investigations', u'Ockult tarmbl\xf6dning  ']]],
           ['Unknown',
            [['Immune system', u'allergiskt \xf6dem)'],
             ['Nervous system',
              u'bl\xf6dningar (inkl. subduralt hematom, subarachnoidal bl\xf6dning och ryggradshematom)'],
             ['Respiratory',
              u'N\xe4sbl\xf6dning Vanliga Bl\xf6dning fr\xe5n andningsv\xe4gar (inkl. lungalveolbl\xf6dning, S\xe4llsynta larynxbl\xf6dning och farynxbl\xf6dning)'],
             ['Renal', u'Hematuri Vanliga'],
             ['Injury',
              u'Kontusion Vanliga Traumatisk bl\xf6dning, bl\xf6dning efter ingreppet, bl\xf6dning p\xe5 Mindre vanliga incisionsst\xe4llet Behandling med Eliquis kan inneb\xe4ra en \xf6kad risk f\xf6r ockult eller synlig bl\xf6dning fr\xe5n vilken v\xe4vnad eller vilket organ som helst, vilket kan leda till posthemorragisk anemi. Tecken, symtom och sv\xe5righetsgrad varierar med var bl\xf6dningen \xe4r lokaliserad och bl\xf6dningens omfattning (se avsnitt 4.4 och avsnitt 5.1).']]]],
 '_pages': [7, 8],
 u'_rank': 12,
 u'_type': u'LSFU'}