{'_data': [['Common', [['Investigations', u'f\xf6rh\xf6jt ALAT']]],
           ['Uncommon',
            [['Psychiatric', u'Insomnia'],
             ['Nervous system', u'dysartri, hypestesi, sensorisk st\xf6rning'],
             ['Eye', u'mios, nedsatt synsk\xe4rpa'],
             ['Cardiac', u'Bradykardi'],
             ['Respiratory', u'dyspn\xe9, v\xe4sande andning'],
             ['GI',
              u'\xf6vre buksm\xe4rtor, onormala tarmljud,  muntorrhet, illam\xe5ende, magbesv\xe4r, f\xf6rstoppning*, sub-ileus*']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inkluderande  anafylaktiska reaktioner'],
             ['Skin',
              u'kl\xe5da, hudutslag, urtikaria, Stevens-Johnsons  syndrom/toxisk epidermal nekrolys']]]],
 '_pages': [4, 5],
 u'_rank': 9,
 u'_type': u'TSFU'}