{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'diarr\xe9, illam\xe5ende'],
             ['Musculoskeletal', u'f\xf6rh\xf6jt kreatinkinas']]],
           ['Common',
            [['Blood', u'Neutropeni'],
             ['Immune system', u'allergiska reaktioner'],
             ['Metabolism', u'hypertriglyceridemi, hyperglykemi'],
             ['Psychiatric', u's\xf6mnl\xf6shet, onormala dr\xf6mmar'],
             ['Nervous system', u'Yrsel'],
             ['GI',
              u'f\xf6rh\xf6jt amylas inklusive f\xf6rh\xf6jt pankreasamylas, f\xf6rh\xf6jt serumlipas, kr\xe4kning, buksm\xe4rta, dyspepsi'],
             ['Hepato',
              u'f\xf6rh\xf6jt serumaspartataminotransferas (ASAT) och/eller f\xf6rh\xf6jt serumalaninaminotransferas (ALAT), hyperbilirubinemi'],
             ['Skin',
              u'vesikulobull\xf6sa hudutslag, pustul\xf6sa hudutslag, makulopapul\xf6sa hudutslag, hudutslag, pruritus, urtikaria, missf\xe4rgning av huden (\xf6kad pigmentering)'],
             ['General',
              u'sm\xe4rta, asteni 1 Se avsnitt c. Beskrivning av valda biverkningar f\xf6r mer information. Anemi var vanlig och missf\xe4rgning av huden (\xf6kad pigmentering) var mycket vanlig n\xe4r emtricitabin administrerades till pediatriska patienter (se avsnitt d.). Denna biverkning, vilken identifierades genom s\xe4kerhetsuppf\xf6ljning efter introduktionen p\xe5 marknaden, observerades inte i randomiserade kontrollerade kliniska studier p\xe5 vuxna eller i pediatriska kliniska hiv-studier med emtricitabin. Frekvenskategorin mindre vanliga bed\xf6mdes utg\xe5ende fr\xe5n en statistisk ber\xe4kning baserad p\xe5 det totala antalet patienter som exponerats f\xf6r emtricitabin i dessa kliniska studier (n = 1 563). c. Beskrivning av valda biverkningar Missf\xe4rgning av huden (\xf6kad pigmentering): Missf\xe4rgning av huden som manifesteras av hyperpigmentering fr\xe4mst i handflator och/eller fotsulor, var i allm\xe4nhet lindriga, asymtomatiska och av ringa klinisk betydelse. Mekanismen \xe4r inte k\xe4nd. Lipider, lipodystrofi och metabola st\xf6rningar: Antiretroviral kombinationsterapi har associerats med metabola avvikelser som hypertriglyceridemi, hyperkolesterolemi, insulinresistens, hyperglykemi och hyperlaktatemi (se avsnitt 4.4). Antiretroviral kombinationsterapi har associerats med omf\xf6rdelning av kroppsfett (lipodystrofi) hos hiv-patienter inklusive f\xf6rlust av perifert och facialt subkutant fett, \xf6kat intraabdominalt och visceralt fett, br\xf6sthypertrofi och dorsocervikal fettansamling (\u201dbuffalo hump\u201d) (se avsnitt 4.4). Immunreaktiveringssyndrom: Hos hiv-infekterade patienter med sv\xe5r immunbrist vid tidpunkten f\xf6r ins\xe4ttande av antiretroviral kombinationsterapi, kan en inflammatorisk reaktion mot asymtomatiska eller kvarvarande opportunistiska infektioner uppst\xe5 (se avsnitt 4.4). Osteonekros: Fall av osteonekros har rapporterats, speciellt hos patienter med k\xe4nda riskfaktorer, framskriden hiv-sjukdom eller l\xe5ngvarig exponering f\xf6r antiretroviral kombinationsterapi (CART). Frekvensen av detta \xe4r ok\xe4nd (se avsnitt 4.4). Laktacidos och sv\xe5r hepatomegali med steatos: Laktacidos, vanligtvis f\xf6renad med leversteatos, har rapporterats vid anv\xe4ndning av nukleosidanaloger (se avsnitt 4.4).']]],
           ['Uncommon', [['Blood', u'anemi 19'], ['Skin', u'angio\xf6dem']]]],
 '_pages': [6, 8],
 u'_rank': 14,
 u'_type': u'LSFU'}