{'_data': [['Very common',
            [['Eye', u'dimsyn'],
             ['Cardiac', u'yrsel'],
             ['Respiratory', u'hosta'],
             ['GI', u'illam\xe5en de'],
<<<<<<< HEAD
             ['General', u'asteni'],
             ['Investigations', u'Mycket vanliga']]],
=======
             ['General', u'asteni']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Common',
            [['Metabolism',
              u'hypokalemi, f\xf6rh\xf6jt kolesterol, f\xf6rh\xf6jda triglycerider, hyperurikemi'],
             ['Nervous system', u'huvudv\xe4rk, depression, synkope, smakrubbning'],
             ['Cardiac', u'hypotension,'],
             ['Vascular', u'hypotension, rytmrubbning ar, angina pectoris, takykardi'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, buksm\xe4rtor, dysgeusi'],
             ['Skin',
<<<<<<< HEAD
              u'utslag (exantem), \xf6verk\xe4nslighe t/angio-neurot iskt \xf6dem: angioneurotis kt \xf6dem i ansikte, extremiteter, l\xe4ppar, tunga, glottis och/eller struphuvud har rapporterats (se avsnitt 4.4).'],
             ['Musculoskeletal', u'muskelkramp er'],
             ['General', u'fatigue'],
             ['Investigations', u'hyperkalemi, f\xf6rh\xf6jt serumkreatini n Vanliga']]],
=======
              u'utslag (exantem), \xf6verk\xe4nslighet /angio-neurotiskt \xf6dem: angioneurotis kt \xf6dem i ansikte, extremiteter, l\xe4ppar, tunga, glottis och/eller struphuvud har rapporterats (se avsnitt 4.4).'],
             ['Musculoskeletal', u'muskelkrampe'],
             ['General', u'fatigue'],
             ['Investigations', u'hyperkalemi, f\xf6rh\xf6jt serumkreatini n']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Blood', u'anemi (inklusive aplastisk och hemolytisk)'],
             ['Metabolism', u'hypoglykemi (se avsnitt 4.4), hypomagnese mi, gikt'],
             ['Nervous system', u'f\xf6rvirring, somnolens, insomnia, nervositet,'],
             ['Psychiatric', u'yrsel, nedsatt libido'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'v\xe4rmevallning'],
             ['Vascular',
              u'palpitationer, hj\xe4rtinfarkt eller stroke, m\xf6jligen sekund\xe4rt till uttalad hypotension hos riskpatienter (se avsnitt 4.4)'],
             ['Respiratory', u'rinorr\xe9, halsont och heshet, bronkospasm/ astma'],
             ['GI',
              u'ileus, pankreatit, kr\xe4kningar, dyspepsi, f\xf6rstoppning, anorexi, magirritation, muntorrhet, mags\xe5r, flatulens'],
             ['Skin', u'diafores, pruritus, urtikaria, alopeci'],
             ['Musculoskeletal', u'artralgi'],
             ['Renal', u'renal dysfunktion, njursvikt, proteinuri'],
             ['Reproductive system', u'impotens'],
             ['General', u'sjukdomsk\xe4ns la, feber'],
<<<<<<< HEAD
             ['Investigations', u'f\xf6rh\xf6jt blodurea, hyponatremi Mindre vanliga']]],
=======
             ['Investigations', u'f\xf6rh\xf6jt blodurea, hyponatremi']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Rare',
            [['Blood',
              u'neutropeni, minskning av hemoglobin, minskning av hematokrit, trombocytop eni, agranulocyto s, myelosuppre ssion, leukopeni, pancytopeni, lymfadenopa ti, autoimmuna sjukdomar'],
             ['Metabolism', u'f\xf6rh\xf6jt blodglukos'],
<<<<<<< HEAD
             ['Nervous system', u'onormala dr\xf6mmar, s\xf6mnst\xf6rnin gar, pares'],
=======
             ['Nervous system', u'onormala dr\xf6mmar, s\xf6mnst\xf6rning ar, pares (p\xe5'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Psychiatric', u'hypokalemi)'],
             ['Cardiac', u'Raynauds'],
             ['Respiratory', u'pulmonella infiltrat, andn\xf6d (inklusive pneumonit'],
             ['GI', u'stomatit/aft\xf6 sa s\xe5r, glossit'],
             ['Hepato',
<<<<<<< HEAD
              u'leversvikt, hepatisk nekros (kan vara d\xf6dlig), hepatit --antingen hepatocellul \xe4r eller kolestatisk, gulsot, kolecystit (s\xe4rskilt hos patienter med befintlig kolelitiasis)'],
             ['Skin',
              u'erytema multiforme, Stevens-Joh nson syndrom, exfoliativ dermatit, toxisk epidermal nekrolys, purpura, kutan lupus erythematos us, erytrodermi, pemfigus Ett symtomkom plex har rapporterats som kan innefatta visst eller allt av f\xf6ljande: feber, serosit, vaskulit, myalgi/myos it, artralgi/artrit , ett positivt ANA, f\xf6rh\xf6jt ESR, eosinofili och leukocytos. Utslag, fotosensitivit et eller andra dermatologis ka symtom kan f\xf6rekomma'],
             ['Renal', u'oliguri, interstitiell nefrit'],
             ['Reproductive system', u'gynekomasti'],
             ['Investigations',
              u'f\xf6rh\xf6jda leverenzyme r, f\xf6rh\xf6jt serumbilirub S\xe4llsynta in']]],
           ['Very rare',
            [['Metabolism', u'hyperka lcemi (se avsnitt 4.4)'],
             ['GI', u'intestina lt angio\xf6d em'],
             ['Investigations', u'Mycket s\xe4llsynt a']]],
           ['Unknown',
            [['Infections', u'Sialoadenit'],
             ['Immune system', u'anafylaktiska reaktioner'],
             ['Endocrine', u'syndrom p\xe5 inadekvat antidiuretisk hormonsekretio n (SIADH)'],
=======
              u'leversvikt, hepatisk nekros (kan vara d\xf6dlig), hepatit --antingen hepatocellul\xe4 r eller kolestatisk, gulsot, kolecystit (s\xe4rskilt hos patienter med befintlig kolelitiasis)'],
             ['Skin',
              u'erytema multiforme, Stevens-Johnson syndrom, exfoliativ dermatit, toxisk epidermal nekrolys, purpura, kutan lupus erythematosu s, erytrodermi, pemfigus Ett symtomkom plex har rapporterats som kan innefatta visst eller allt av f\xf6ljande: feber, serosit, vaskulit, myalgi/myos it, artralgi/artrit , ett positivt ANA, f\xf6rh\xf6jt ESR, eosinofili och leukocytos. Utslag, fotosensitivit et eller andra dermatologis ka symtom kan f\xf6rekomma'],
             ['Renal', u'oliguri, interstitiell nefrit'],
             ['Reproductive system', u'gynekomasti'],
             ['Investigations', u'f\xf6rh\xf6jda leverenzymer , f\xf6rh\xf6jt serumbilirubi n']]],
           ['Very rare',
            [['Metabolism', u'hyperkal cemi (se avsnitt 4.4)'],
             ['GI', u'intestina lt angio\xf6d em']]],
           ['Unknown',
            [['Immune system', u'anafylaktiska reaktioner'],
             ['Endocrine', u'syndrom p\xe5 inadekvat antidiuretisk hormonsekretion (SIADH)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Metabolism', u'glykosuri'],
             ['Nervous system', u'rastl\xf6shet, svindel'],
             ['Eye', u'xantopsi'],
             ['Cardiac', u'nekrotiserande'],
<<<<<<< HEAD
             ['Vascular', u'kutan vaskulit)'],
             ['Investigations', u'Ingen k\xe4nd frekvens']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 14],
 u'_rank': 55,
=======
             ['Vascular', u'kutan vaskulit)']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 12],
 u'_rank': 51,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}