{'_data': [['Common',
            [['General', u' Yrsel, huvudv\xe4rk, tr\xf6tthet, br\xf6stsm\xe4rtor, synkope.  '],
             ['Vascular', u' Ortostatiska effekter inklusive hypotension. '],
             ['GI', u' Diarr\xe9, illam\xe5ende. '],
             ['Respiratory', u' Hosta. ']]],
           ['Uncommon',
            [['General', u' Asteni, somnolens, impotens.  '],
             ['Vascular', u' Palpitationer. '],
             ['GI', u' Buksm\xe4rtor, dyspepsi. '],
             ['Skin', u' Exantem, kl\xe5da, rodnad, urtikaria. '],
             ['Respiratory', u' Dyspn\xe9, sv\xe4ljningssm\xe4rta. ']]],
           ['Rare',
            [['General', u' Aptitl\xf6shet, hyperhidros.   '],
             ['Vascular', u'Rytmst\xf6rningar, vaskulit, Raynauds fenomen. '],
             ['GI',
              u' Kr\xe4kningar, obstipation, ileus, glossit, stomatit, smakf\xf6r\xe4ndring. '],
             ['Skin',
<<<<<<< HEAD
              u' H\xe5ravfall, fotosensibilisering, angio\xf6dem med svullnad av ansikte, extremiteter, l\xe4ppar, tunga, glottis och/eller larynx, erytema multiforme, exfoliativ dermatit, pemfigus, Stevens-Johnson\xb4s syndrom, toxisk epidermal nekrolys. '],
=======
              u' H\xe5ravfall, fotosensibilisering, angio\xf6dem med svullnad av ansikte, extremiteter, l\xe4ppar, tunga, glottis och/eller larynx, erytema multiforme, exfoliativ dermatit, pemfigus, Stevens- Johnson\xb4s syndrom, toxisk epidermal nekrolys. '],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Hepato',
              u' Gulsot (gallstas), hepatocellul\xe4r eller kolestatisk hepatit, leversvikt, pankreatit. '],
             ['Respiratory',
              u' Bronkospasm, f\xf6rv\xe4rrad astma, lunginfiltrat, rinorr\xe9, heshet. '],
             ['Musculoskeletal', u' Myalgi, artralgi, artrit. '],
             ['Nervous system', u' Parestesier. '],
             ['Psychiatric',
              u' S\xf6mnl\xf6shet, nervositet, f\xf6r\xe4ndrat st\xe4mningsl\xe4ge, depression, f\xf6rvirring, f\xf6r\xe4ndrat dr\xf6mm\xf6nster. '],
             ['Reproductive system',
              u' Nedsatt njurfunktion inklusive oliguri och njursvikt. '],
             ['Eye', u' Dimsyn. '],
             ['Ear', u' Tinnitus. ']]]],
 '_pages': [5, 6],
 u'_rank': 21,
 u'_type': u'DFSU'}