{'_data': [['Very common',
            [['Eye', u'dimsyn'],
             ['Cardiac', u'yrsel'],
             ['Respiratory', u'hosta'],
             ['GI', u'illam\xe5ende'],
             ['General', u'asteni']]],
           ['Common',
            [['Metabolism',
              u'hypokalemi, f\xf6rh\xf6jt kolesterol, f\xf6rh\xf6jda triglycerider, hyperurikemi'],
             ['Psychiatric', u'depression'],
             ['Nervous system', u'huvudv\xe4rk, synkope, smakrubbningar'],
             ['Cardiac', u'rytmrubbningar, k\xe4rlkramp, takykardi'],
             ['Vascular', u'hypotoni, ortostatisk hypotoni'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, buksm\xe4rta'],
             ['Skin',
              u'utslag (exantem), \xf6verk\xe4nslighet/angioneurotiskt \xf6dem angioneurotiskt \xf6dem i ansiktet, extremiteter, l\xe4ppar, tunga, glottis och/eller larynx har rapporterats (se avsnitt 4.4)'],
             ['Musculoskeletal', u'muskelkramper **'],
             ['General', u'br\xf6stsm\xe4rta, tr\xf6tthet'],
             ['Investigations', u'hyperkalemi, \xf6kningar av serumkreatinin']]],
           ['Uncommon',
            [['Blood', u'anemi (inklusive aplastisk och hemolytisk)'],
             ['Metabolism', u'hypoglycemi (se avsnitt 4.4), hypomagnesemi, gikt*'],
             ['Psychiatric', u'f\xf6rvirring, s\xf6mnl\xf6shet, nervositet, nedsatt libido*'],
             ['Nervous system', u'somnolens, parestesi, svindel'],
             ['Ear', u'tinnitus'],
             ['Cardiac',
              u'hj\xe4rtklappning, hj\xe4rtinfarkt eller stroke, eventuellt sekund\xe4rt till kraftig hypotoni hos riskpatienter (se avsnitt 4.4)'],
             ['Vascular', u'blodvallning'],
             ['Respiratory', u'rinorr\xe9, halsont och heshet, bronkospasm/astma'],
             ['GI',
              u'ileus, pankreatit, kr\xe4kningar, dyspepsi, f\xf6rstoppning, anorexi, gastrisk irritation, muntorrhet, peptiskt mags\xe5r, flatulens *'],
             ['Skin', u'diafores, pruritus, urtikaria, alopeci'],
             ['Musculoskeletal', u'artralgi *'],
             ['Renal', u'njurdysfunktion, njursvikt, proteinuri'],
             ['Reproductive system', u'impotens'],
             ['General', u'olustk\xe4nsla, feber'],
             ['Investigations', u'f\xf6rh\xf6jt blodurea, hyponatremi']]],
           ['Rare',
            [['Blood',
              u'neutropeni, minskat hemoglobin, minskat hematokrit, trombocytopeni, agranulocytos, benm\xe4rgsdepression, pancytopeni, lymfadenopati, autoimmuna sjukdomar'],
             ['Metabolism', u'f\xf6rh\xf6jt blodglukos'],
             ['Psychiatric', u'onormala dr\xf6mmar, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'pares (p\xe5 grund av hypokalemi)'],
             ['Vascular', u'Raynauds syndrom'],
             ['Respiratory',
              u'pulmon\xe4ra infiltrat, andn\xf6d (inklusive pneumonit och pulmonellt \xf6dem), rinit, allergisk alveolit/eosinofil pneumoni'],
             ['GI', u'stomatit/aft\xf6sa ulcerationer, glossit'],
             ['Hepato',
              u'leversvikt, hepatit \u2013 antingen hepatocellul\xe4r eller kolestatisk, hepatisk nekros (kan vara d\xf6dlig), gulsot, kolestas (s\xe4rskilt hos patienter med befintlig kolelitiasis)'],
             ['Skin',
              u'erythema multiforme, Stevens-Johnson syndrom, exfoliativ dermatit, toxisk epidermal nekrolys, purpura, kutan lupus erythematosus pemfigus, erytrodermi En upps\xe4ttning symptom har rapporterats som kan inkludera en del eller alla av f\xf6ljande: feber, serosit, vaskulit, myalgi/myosit, artralgi/artrit, positivt ANA, f\xf6rh\xf6jt ESR, eosinofili samt leukocytos. Utslag, ljusk\xe4nslighet eller andra dermatologiska manifestationer kan uppst\xe5.'],
             ['Renal', u'oliguri, interstitiell nefrit'],
             ['Reproductive system', u'gynekomasti'],
             ['Investigations',
              u'\xf6kningar i leverenzymer, \xf6kningar i serumbilirubin *Dessa biverkningar \xe4r endast relevanta f\xf6r hydroklortiaziddoser om 12,5 mg och 25 mg **Frekvensen av muskelkramper som vanligen g\xe4ller f\xf6r doser av hydroklortiazid om 12,5 mg och 25 mg, medan frekvensen av h\xe4ndelsen \xe4r mindre vanlig f\xf6r doser om 6 mg av hydroklortiazid.']]],
           ['Very rare',
            [['Metabolism', u'hyperkalcemi (se avsnitt 4.4)'],
             ['GI', u'intestinalt angio\xf6dem']]],
           ['Unknown',
            [['Endocrine',
              u'syndrom p\xe5 otillb\xf6rlig sekretion av antidiuretiskt hormon (SIADH)']]]],
 '_pages': [10, 13],
 u'_rank': 46,
 u'_type': u'LSFU'}