{'_data': [['Common',
            [['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndringar, depression'],
             ['Vascular', u'Blodvallningar'],
             ['Hepato', u'F\xf6rh\xf6jt LD'],
             ['Skin', u'Svettning'],
             ['Reproductive system', u'Minskad libido, impotens, testikelatrofi'],
             ['General', u'Reaktion vid injektionsst\xe4llet**, v\xe4rmek\xe4nsla']]],
           ['Uncommon',
            [['Blood', u'Anemi, trombocytopeni'],
             ['Metabolism',
              u'Viktf\xf6r\xe4ndringar, anorexi, f\xf6rh\xf6jt totalkolesterol och triglycerider, hyperkalemi, \xf6kad koncentration av glukos i blodet, f\xf6rh\xf6jda niv\xe5er av urinsyra'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, parestesier'],
             ['Ear', u'D\xf6vhet, tinnitus'],
             ['Cardiac', u'EKG-f\xf6r\xe4ndringar, \xf6kad kardiothorakal kvot'],
             ['Vascular', u'Blodvallning i ansiktet  Trombos'],
             ['GI', u'Illam\xe5ende, kr\xe4kning'],
             ['Hepato',
              u'F\xf6rh\xf6jda v\xe4rden av ASAT, ALAT, gamma-glutamyltranspeptidas, alkaliskt fosfatas och bilirubin, gulsot'],
             ['Skin', u'Dermatit, h\xe5rv\xe4xt p\xe5 huvudet, utslag, kl\xe5da'],
             ['Musculoskeletal',
              u'Artralgi, bensm\xe4rta, sm\xe4rta i skuldra, nedre rygg eller extremiteter'],
             ['Renal', u'Pollakisuri, hematuri, f\xf6rh\xf6jda niv\xe5er av urea'],
             ['Reproductive system', u'Gynekomasti, obehag i perinealregionen'],
             ['General',
              u'Sv\xe5righeter att g\xe5, \xf6dem, tryckk\xe4nsla \xf6ver br\xf6stet, stelhet, sjukdomsk\xe4nsla, tr\xf6tthet, feber. Sm\xe4rta, induration eller rodnad vid injektionsst\xe4llet']]],
           ['Rare',
            [['Immune system',
              u'Anafylaktisk reaktion (\xf6dem i l\xe4ppar och larynx, dyspn\xe9, urtikaria)'],
             ['Nervous system', u'Hypofys\xe4r apoplexi*'],
             ['Respiratory', u'Interstitiell pneumoni, lungemboli'],
             ['GI', u'Diarr\xe9'],
             ['Musculoskeletal', u'Myalgi, minskad benmassa'],
             ['General', u'Abcess vid injektionsst\xe4llet']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 25,
 u'_type': u'MSFU'}