{'_data': [['Very common',
            [['Nervous system', u'Dyskinesi'],
             ['GI', u'Illam\xe5ende'],
             ['Renal', u'Missf\xe4rgning av urin']]],
           ['Common',
            [['Psychiatric',
              u'Insomnia, hallucinationer, f\xf6rvirring, paroniria (mardr\xf6mmar)'],
             ['Nervous system', u'F\xf6rv\xe4rrad parkinsonism, yrsel, dystoni, hyperkinesi'],
             ['Cardiac',
              u'Ischemisk hj\xe4rtsjukdom annat \xe4n hj\xe4rtinfarkt (t.ex. angina pectoris)'],
             ['GI', u'Diarr\xe9, buksm\xe4rta, muntorrhet, f\xf6rstoppning, kr\xe4kning'],
             ['General', u'Tr\xf6tthet, \xf6kad svettning, fall']]],
           ['Uncommon', [['Cardiac', u'Hj\xe4rtinfarkt']]],
           ['Rare',
            [['Hepato', u'Avvikande resultat vid leverfunktionstest'],
             ['Skin', u'Erytemat\xf6st eller makulopapul\xf6st hudutslag']]],
           ['Very rare',
            [['Psychiatric', u'Agitation'],
             ['GI', u'Anorexi'],
             ['Skin', u'Urtikaria'],
             ['General', u'Viktminskning']]],
           ['Unknown',
            [['GI', u'Kolit'],
             ['Hepato', u'Hepatit huvudsakligen med kolestatiska drag (se avsnitt 4.4)'],
             ['Skin', u'Missf\xe4rgning av hud, h\xe5r, sk\xe4gg och naglar']]]],
 '_pages': [4, 6],
 u'_rank': 18,
 u'_type': u'LSFU'}