{'_data': [['Very common',
            [['Nervous system', u'Dyskinesi'],
             ['GI', u'Illam\xe5ende'],
             ['Renal', u'Missf\xe4rgning av urin']]],
           ['Common',
            [['Psychiatric',
              u'Insomnia, hallucinationer, f\xf6rvirring, paroniria (mardr\xf6mmar)'],
             ['Nervous system',
              u'F\xf6rv\xe4rrad parkinsonism, yrsel, dystoni, hyperkinesi Hj\xe4rtat**'],
             ['Nervous system',
              u'Ischemisk hj\xe4rtsjukdom annat \xe4n hj\xe4rtinfarkt (t.ex. angina pectoris)'],
             ['GI', u'Diarr\xe9, buksm\xe4rta, muntorrhet, f\xf6rstoppning, kr\xe4kning'],
             ['General', u'Tr\xf6tthet, \xf6kad svettning, fall']]],
           ['Uncommon', [['Nervous system', u'Hj\xe4rtinfarkt']]],
           ['Rare',
            [['Hepato', u'Avvikande resultat vid leverfunktionstest'],
             ['Skin', u'Erytemat\xf6st eller makulopapul\xf6st hudutslag']]],
           ['Very rare',
            [['Psychiatric', u'Agitation'],
             ['GI', u'Anorexi'],
             ['Skin', u'Urtikaria'],
             ['General',
              u'Viktminskning *Biverkningarna \xe4r ordnade under frekvensrubriker, de mest frekventa f\xf6rst, enligt f\xf6ljande indelning: Mycket vanliga (\u22651/10); vanliga (\u22651/100,<1/10); mindre vanliga (\u22651/1 000, <1/100); s\xe4llsynta (\u22651/10 000, <1/1 000); mycket s\xe4llsynta (<1/10 000), ingen k\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data, eftersom ingen v\xe4lgrundad bed\xf6mning har kunnat ber\xe4knas i kliniska eller epidemiologiska studier. ** Incidensen av hj\xe4rtinfarkt och andra ischemiska hj\xe4rtsjukdomar (0,43% respektive 1,54%) h\xe4rr\xf6r fr\xe5n en analys av 13 dubbelblinda studier omfattande 2082 patienter med motoriska end-of-dose-fluktuationer som fick entakapon. Beskrivning av utvalda biverkningar Entakapon tillsammans med levodopa har associerats med enskilda fall av sv\xe5r somnolens dagtid och pl\xf6tsligt intr\xe4dande s\xf6mnepisoder. Impulskontrollst\xf6rningar: Patologiskt spelberoende, \xf6kad libido, hypersexualitet, tv\xe5ngsm\xe4ssigt spenderande eller k\xf6pande, hets\xe4tning och tv\xe5ngsm\xe4ssigt \xe4tande kan f\xf6rekomma hos patienter behandlade med dopaminagonister och/eller andra dopaminerga behandlingar s\xe5som Entacapone Orion tillsammans med levodopa (se avsnitt 4.4). Enskilda fall av NMS har rapporterats efter abrupt reducering eller uts\xe4ttning av entakapon och andra dopaminerga behandlingar. 6 Enskilda fall av rabdomyolys har rapporterats.']]],
           ['Unknown',
            [['GI', u'Kolit'],
             ['Hepato', u'Hepatit huvudsakligen med kolestatiska drag (se avsnitt 4.4)'],
             ['Skin', u'Missf\xe4rgning av hud, h\xe5r, sk\xe4gg och naglar']]]],
 '_pages': [5, 7],
 u'_rank': 18,
 u'_type': u'LSFU'}