{'_data': [['Common',
            [['General', u' D\xe5sighet, yrsel.  '],
             ['Blood', u' L\xe5ga serumfolsyrav\xe4rden.  '],
             ['Nervous system', u' Ataxi, nystagmus, tremor. '],
             ['Endocrine', u' Hirsutism '],
             ['GI', u' Gingivahyperplasi. '],
             ['Skin', u' Exanthem, urtikaria,. '],
             ['Hepato', u' Transaminasstegring. '],
             ['Eye', u' Synrubbningar. ']]],
           ['Uncommon',
            [['GI', u' Dyspepsi, illam\xe5ende och kr\xe4kningar.  '],
             ['Other', u' Lymfadenopati (feber, exanthem och lymfk\xf6rtelf\xf6rstoring).  ']]],
           ['Rare',
            [['General',
              u' \xd6verk\xe4nslighetssyndrom, anafylaktoid reaktion, analylaxi,   SLE. '],
             ['Blood',
              u' Agranulocytos, aplastisk anemi, eosinofili, leukopeni, megaloblastisk anemi, trombocytopeni. '],
             ['Vascular', u' AV-block. '],
             ['Nervous system', u' Parestesi, somnolens '],
             ['Skin',
              u' Toxisk epidermal nekrolys (TEN), Stevens-Johnsons syndrom (SJS) (se avsnitt 4.4). L\xe4kemedelsutl\xf6sta utslag med eosinofili och systemiska symtom (DRESS). '],
             ['Hepato', u' Hepatit, akut leverskada, leverf\xf6rstoring. '],
             ['Metabolism', u' Hyperglykemi, osteomalaci. Muskuloskeletal: Artralgi '],
             ['Nervous system', u' Huvudv\xe4rk '],
             ['Psychiatric', u' F\xf6rvirring. '],
             ['Other', u' Smakf\xf6r\xe4ndringar ']]]],
 '_pages': [6, 6],
 u'_rank': 20,
 u'_type': u'DFSU'}