{'_data': [['Very common',
            [['Blood',
              u'Myelosuppression* (leukopeni, granulocytopeni, neutropeni, anemi, febril neutropeni)'],
             ['Skin', u'Alopeci'],
             ['Renal', u'R\xf6df\xe4rgad urin under 1-2 dagar efter administrering']]],
           ['Common',
            [['Infections', u'Infektioner'],
             ['Metabolism', u'Anorexi, dehydrering'],
             ['Vascular', u'Rodnad'],
             ['GI',
              u'Mukosit kan upptr\xe4da 5-10 dagar efter behandlingsstart och inneb\xe4r vanligtvis stomatit med sm\xe4rtfulla erosioner, ulceration och bl\xf6dningar mestadels p\xe5 sidan av tungan och i sublinguala slemhinnan; esofagit, kr\xe4kning, diarr\xe9, illam\xe5ende'],
             ['General',
              u'Rodnad l\xe4ngs venen d\xe4r injektionen getts. Fleboskleros. Lokal sm\xe4rta och v\xe4vnadsnekros kan intr\xe4ffa (efter oavsiktlig extravasal injektion).'],
             ['Injury',
              u'Kemisk cystit, ibland bl\xf6dande, har observerats efter intravesikal administrering (se avsnitt 4.4). Intravesikal administrering: Eftersom endast en liten m\xe4ngd aktiv substans \xe5terresorberas efter intravesikal instillation \xe4r allvarliga systematiska biverkningar och allergiska reaktioner s\xe4llsynta. Vanligt f\xf6rekommande \xe4r lokala reaktioner som t ex en br\xe4nnande k\xe4nsla och frekvent urinering (pollakisuri). Enstaka fall av bakteriell eller kemisk cystit har rapporterats (se avsnitt 4.4). Dessa biverkningar \xe4r oftast reversibla.']]],
           ['Uncommon', [['Blood', u'Trombocytopeni'], ['Vascular', u'Flebit, tromboflebit']]],
           ['Rare',
            [['Neoplasms',
              u'Akut lymfatisk leukemi,sekund\xe4r akut myeloisk leukemi med eller utan pre-leukemisk fas hos patienter som behandlats med epirubicin i kombination med DNA-skadande cancerl\xe4kemedel. Dessa leukemier har kort (1-3 \xe5r) latens.'],
             ['Immune system', u'Anafylaxi'],
             ['Metabolism',
              u'Hyperurikemi (till f\xf6ljd av snabb lys av neoplastiska celler) (se avsnitt 4.4)'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac',
              u'Kardiotoxicitet (t ex EKG-f\xf6r\xe4ndringar, arytmi, kardiomyopati), hj\xe4rtsvikt (dyspn\xe9, \xf6dem, leverf\xf6rstoring, ascites, lung\xf6dem, pleurautgjutning, snabb hj\xe4rtrytm), ventrikul\xe4r takykardi, bradykardi, AV-block, grenblock (se avsnitt 4.4)'],
             ['Skin', u'Urtikaria'],
             ['Reproductive system', u'Amenorr\xe9, azoospermi'],
             ['General', u'Feber, frossa, hyperpyrexi, sjukdomsk\xe4nsla, asteni, svaghet'],
             ['Investigations', u'\xd6kade transaminasniv\xe5er']]],
           ['Unknown',
            [['Infections',
              u'pneumoni, sepsis, septisk chock (kan intr\xe4ffa som en f\xf6ljd av myelosupression)'],
<<<<<<< HEAD
             ['Blood', u'Bl\xf6dning och v\xe4vnadshypoxi orsakad av myelosuppression'],
=======
             ['Blood',
              u'Bl\xf6dning och v\xe4vnadshypoxi orsakad av myelosuppression * H\xf6ga doser av epirubicin har administrerats till ett stort antal tidigare obehandlade patienter med olika solida tum\xf6rer, och denna behandling har orsakat biverkningar som inte skiljer sig fr\xe5n dem som har setts vid konventionella doser, med undantag f\xf6r reversibel allvarlig neutropeni (< 500 neutrofiler/mm under < 7 dagar), vilket uppkom hos flertalet patienter. Endast ett f\xe5tal patienter beh\xf6vde sjukhusv\xe5rd och st\xf6djande terapi f\xf6r sv\xe5ra infekti\xf6sa komplikationer vid h\xf6ga doser av epirubicin.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Eye', u'Konjunktivit, keratit'],
             ['Vascular',
              u'Chock, samtidiga fall av tromboembolism (inklusive lungembolism, i enstaka fall med d\xf6dlig utg\xe5ng) har f\xf6rekommit.'],
             ['Skin',
              u'Lokal toxicitet, hudutslag, kl\xe5da, hudf\xf6r\xe4ndringar, erytem, v\xe4rmevallningar, hyperpigmentering av hud och naglar, fotosensitivitet, str\xe5lningsinducerad hudreaktion (\u2019radiation recall\u2019-reaktion)'],
             ['Investigations',
              u'Asymtomatisk minskning av v\xe4nstra ventrikul\xe4ra ejektionsfraktionen']]]],
 '_pages': [8, 9],
 u'_rank': 26,
 u'_type': u'LSFU'}