{'_data': [['Very common',
            [['Blood',
              u'Myelosuppression  (leukopeni, granulocytopeni, neutropeni, anemi och febril neutropeni)'],
             ['Skin',
              u'Alopeci  (hos  60-90 %  av  behandlade  patienter.  Det \xe5tf\xf6ljs  av  d\xe5lig  sk\xe4ggv\xe4xt hos m\xe4n. Alopeci \xe4r dosberoende och vanligtvis reversibel)'],
             ['Renal', u'R\xf6df\xe4rgad urin under 1 till  dagar efter administrering']]],
           ['Common',
            [['Metabolism', u'Anorexi, dehydrering'],
             ['Vascular', u'V\xe4rmevallningar,  fleblskleros'],
             ['GI', u'Mukosit  (kan  upptr\xe4da'],
             ['General', u'Erytem vid infusionsst\xe4llet']]],
           ['Uncommon', [['Blood', u'Trombocytopeni'], ['Vascular', u'Flebit, tromboflebit']]],
           ['Rare',
            [['Neoplasms',
              u'Akut lymfatisk leukemi,  akut myeloid leukemi med  eller utan preleukemisk fas  hos patienter behandlade  med epirubicin i kombination med DNA-'],
             ['Immune system',
              u'Anafylaxi  (anafylaktiska/anafylaktoida reaktioner  med  eller  utan'],
             ['Metabolism', u'Hyperurikemi  (se  avsnitt  .4).'],
             ['Cardiac',
              u'Hj\xe4rtsvikt (se avsnitt 4.4),  (dyspn\xe9, \xf6dem, leverf\xf6rstoring, ascites, lung\xf6dem, pleurautgjutning, hj\xe4rtklappning) kardiotoxicitet (t.ex. EKG- f\xf6r\xe4ndringar, arytmi, kardiomyopati), ventrikul\xe4r takykardi, bradykardi, AV- block, grenblock'],
             ['Skin', u'Urtikaria,  pruritus,  lokala'],
             ['Reproductive system', u'Amenorr\xe9, asoospermi'],
             ['General', u'Sjukdomsk\xe4nsla,  asteni,  feber, frossa, hyperpyrexi'],
             ['Investigations', u'F\xf6r\xe4ndrade  transaminasniv\xe5er']]],
           ['Unknown',
            [['Blood', u'Bl\xf6dning och  v\xe4vnadshypoxi orsakad av myelosuppression'],
             ['Nervous system', u'Perifer neuropati (med h\xf6ga  doser), huvudv\xe4rk'],
             ['Eye', u'Konjuktivit, keratit'],
             ['Vascular',
              u'Chock,  tromboembolism  inklusive  lungembolism  (i enstaka  fall  med  d\xf6dlig utg\xe5ng)'],
             ['Skin', u'Lokal  toxicitet,  hudutslag,'],
             ['Renal', u'Proteinuri hos patienter som  behandlats med en h\xf6g dos'],
             ['Investigations', u'Asymtomatiska']]]],
 '_pages': [10, 13],
 u'_rank': 24,
 u'_type': u'TSFU'}