{'_data': [['Very common',
            [['Blood',
              u'Myelosuppression  (leukopeni, granulocytopeni, neutropeni, anemi, febril neutropeni)'],
             ['Skin',
              u'Alopeci (upptr\xe4der hos  % av behandlade fall. Det medf\xf6r d\xe5lig sk\xe4ggv\xe4xt hos m\xe4n. Alopeci \xe4r dosberoende och vanligtvis reversibel)'],
             ['Renal', u'R\xf6df\xe4rgad urin under  dagar efter administrering']]],
           ['Common',
            [['Infections', u'Infektioner'],
             ['Metabolism', u'Anorexi, dehydrering'],
             ['Vascular', u'Rodnad, fleboskleros'],
             ['GI',
              u'Mukosit (kan upptr\xe4da  dagar efter behandlingsstart), esofagit, stomatit, kr\xe4kningar, diarr\xe9 som kan orsaka dehydrering, illam\xe5ende (illam\xe5ende och kr\xe4kningar upptr\xe4der ofta inom de 24 f\xf6rsta timmarna hos n\xe4stan alla patienter)'],
             ['General', u'Erytem vid infusionsst\xe4llet'],
             ['Injury',
              u'Kemisk cystit, ibland  bl\xf6dande, har observerats  efter intravesikal administrering (se avsnitt .4).']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni'],
             ['Metabolism', u'Hyperuricemi (se avsnitt 4.4)'],
             ['Vascular', u'Flebit, tromboflebit']]],
           ['Rare',
            [['Neoplasms',
              u'Akut lymfatisk leukemi, akut  myeloisk leukemi med eller  utan pre-leukemisk fas hos  patienter behandlade med epirubicin i kombination med DNA-skadande anticancermedel. Dessa leukemier har kort (1-3 \xe5r) latens.'],
             ['Immune system',
              u'Anafylaxi  (anafylaktisk/anafylaktoida reaktioner med eller utan chock inkluderat hudutslag, pruritus, feber och frossa)'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac',
              u'Hj\xe4rtsvikt (se avsnitt 4.4),  (dyspn\xe9, \xf6dem, leverf\xf6rstoring, ascites, lung\xf6dem, pleurautgjutning, snabb hj\xe4rtrytm) kardiotoxicitet (t ex EKG- f\xf6r\xe4ndringar, arytmi, kardiomyopati), ventrikul\xe4r takykardi, bradykardi, AV- block, grenblock'],
             ['Skin',
              u'Urtikaria, pruritus, lokal  erytemat\xf6sa reaktioner l\xe4ngs venen som anv\xe4nts f\xf6r injektion'],
             ['Reproductive system', u'Amenorr\xe9, azoospermi'],
             ['General', u'Sjukdomsk\xe4nsla, asteni,  feber, frossa, hyperpyrexi'],
             ['Investigations', u'\xd6kade transaminasniv\xe5er']]],
           ['Unknown',
            [['Infections',
              u'Septisk chock (kan intr\xe4ffa  som ett resultat av myelosupression), sepsis, pneumoni'],
             ['Blood', u'Bl\xf6dning och v\xe4vnadshypoxi  orsakad av myelosuppression'],
             ['Nervous system', u'Perifer neuropati (med h\xf6ga  doser), huvudv\xe4rk'],
             ['Eye', u'Konjunktivit, keratitis'],
             ['Vascular',
              u'Chock, tromboembolism  inklusive lungembolism (i enstaka fall med d\xf6dlig utg\xe5ng)'],
             ['Skin',
              u'Lokal toxicitet, hudutslag,  kl\xe5da, hudf\xf6r\xe4ndringar, erytem, v\xe4rmevallningar, f\xf6r\xe4ndringar i hud och naglar (hyperpigmentering), fotosensitivitet, str\xe5lningsinducerad hudreaktion (\u201dradiation recall\u201d-reaktion)'],
             ['Renal', u'Proteinuri hos patienter som  behandlats med en h\xf6g dos.'],
             ['Investigations',
              u'Asymtomatiska minksningar  av v\xe4nstra ventrikul\xe4ra ejektionsfraktionen']]]],
 '_pages': [10, 12],
 u'_rank': 28,
 u'_type': u'TSFU'}