{'_data': [['Very common',
            [['Blood',
              u'myelosuppression* (leukopeni,  granulocytopeni och neutropeni, anemi och febril neutropeni)'],
             ['Skin',
              u'alopeci, vanligtvis reversibel,  f\xf6rekommer i 60-90 % av behandlade fall; det \xe5tf\xf6ljs av minskad sk\xe4ggv\xe4xt hos m\xe4n'],
             ['Renal', u'r\xf6df\xe4rgad urin under 1-2 dagar efter  administrering']]],
           ['Common',
            [['Infections', u'infektion'],
             ['Immune system', u'allergiska reaktioner efter intravesikal  anv\xe4ndning'],
             ['Metabolism', u'anorexi, dehydrering'],
             ['Vascular', u'rodnad'],
             ['GI',
              u'illam\xe5ende, kr\xe4kningar, diarr\xe9, vilket  kan resultera i uttorkning,aptitl\xf6shet och buksm\xe4rtor Mukosit, (kan upptr\xe4da 5-10 dagar efter behandlingsstart och inneb\xe4r vanligtvis stomatit med omr\xe5den av sm\xe4rtsamma erosioner, s\xe5r och bl\xf6dningar, huvudsakligen l\xe4ngs sidan av tungan och munslemhinnan), stomatit, esofagit och hyperpigmentering av munslemhinnan kan ocks\xe5 f\xf6rekomma.'],
             ['General',
              u'Rodnad l\xe4ngs infusionsvenen.  lokal flebit, fleboskleros  Lokal sm\xe4rta och v\xe4vnadsd\xf6d kan  f\xf6rekomma (efter oavsiktlig extravasal injektion).'],
             ['Injury',
              u'kemisk cystit, i vissa fall bl\xf6dande, har  observerats efter intravesikal  administrering (se avsnitt 4.4)']]],
           ['Uncommon',
            [['Blood', u'trombocytopeni'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Vascular', u'flebit, tromboflebit'],
             ['Skin',
              u'hyperpigmentering i hud och naglar,  erytem, fotosensivitet, \xf6verk\xe4nslighet i bestr\xe5lad hud (\u201dradiation recall\u201d-reaktion)']]],
           ['Rare',
            [['Neoplasms',
              u'akut lymfatisk leukemi, akut myeloisk  leukemi  Sekund\xe4r akut myeloisk leukemi med  eller utan en pre-leukemisk fas hos patienter behandlade med epirubicin i kombination med DNA-skadande antineoplastiska l\xe4kemedel. Dessa har kort (1-3 \xe5r) latens.'],
             ['Immune system',
              u'anafylaxi (anafylaxi/anafylaktoida  reaktioner med eller utan chock inklusive hudutslag, pruritus, feber och frossa)'],
             ['Metabolism',
              u'hyperurikemi (som en f\xf6ljd av snabb  lysis av neoplastiska celler) (se avsnitt 4.4)'],
             ['Nervous system', u'yrsel'],
             ['Cardiac',
              u'Hj\xe4rttoxicitet (EKG-f\xf6r\xe4ndringar,  takykardi, arytmi, kardiomyopati, hj\xe4rtsvikt (dyspn\xe9, \xf6dem, leverf\xf6rstoring, ascites, lung\xf6dem, pleurautgjutning, snabb hj\xe4rtrytm), kammartakykardi, bradykardi, AV- block, grenblock) (se avsnitt 4.4)'],
             ['Skin', u'urtikaria'],
             ['Reproductive system', u'amenorr\xe9, azoospermi'],
             ['General', u'feber, frossa, hyperpyrexi,  sjukdomsk\xe4nsla, svaghet'],
             ['Investigations', u'f\xf6r\xe4ndringar i transaminasniv\xe5er']]],
           ['Unknown',
            [['Infections',
              u'pneumoni, sepsis och septisk chock  kan f\xf6rekomma som en f\xf6ljd av myelosuppression'],
             ['Blood',
              u'bl\xf6dning och v\xe4vnadshypoxi (som en  f\xf6ljd av myelosuppression) kan f\xf6rekomma'],
             ['Eye', u'konjunktivit, keratitis'],
             ['Vascular',
              u'chock, tillf\xe4lligt fall av  tromboemboliska h\xe4ndelser har intr\xe4ffat (inklusive lungemboli (i enstaka fall med d\xf6dlig utg\xe5ng))'],
             ['Skin', u'lokal toxicitet, hudutslag, kl\xe5da,  hudf\xf6r\xe4ndringar, rodnad'],
             ['Investigations',
              u'asymtomatiska minskningar av v\xe4nstra  ventrikul\xe4ra ejektionsfraktionen']]]],
 '_pages': [9, 10],
 u'_rank': 29,
 u'_type': u'TSFU'}