<<<<<<< HEAD
{'_data': [['Very common', [['Psychiatric', u'nervositet'], ['Reproductive system', u'och ']]],
=======
{'_data': [['Very common',
            [['Psychiatric', u'S\xf6mnl\xf6shet,'], ['General', u'ringsst\xe4llet ']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Common',
            [['Infections', u'Nasofaryngit'],
             ['Metabolism',
              u'Anorexi, minskad aptit, m\xe5ttligt reducerad viktuppg\xe5ng och l\xe4ngdtillv\xe4xt under l\xe5ngvarig anv\xe4ndning hos barn'],
<<<<<<< HEAD
             ['Psychiatric', u'affektlabilitet, aggression'],
             ['Nervous system', u'dyskinesi, psykomotorisk hyperaktivitet, somnolens'],
             ['Cardiac', u'Arrytmi, takydardi, hj\xe4rtklappning'],
             ['Vascular', u'Hypertoni'],
             ['Respiratory', u'Hosta, sm\xe4rta i svalg/strupe Buksm\xe4rta,'],
             ['GI', u'diarr\xe9, illam\xe5ende, magbesv\xe4r och kr\xe4kningar. Muntorrhet.'],
             ['Hepato', u'Alopeci, kl\xe5da,'],
             ['Skin', u'utslag, urtikaria'],
             ['Musculoskeletal', u'Artralgi'],
             ['Reproductive system', u'Pyrexi,'],
             ['General',
              u'tillv\xe4xtf\xf6rdr\xf6jni -ng under l\xe5ngvarig anv\xe4ndning hos barn* F\xf6r\xe4ndringar i blodtryck och']]],
=======
             ['Psychiatric', u'Anorexi, aggression irritabilitet, onormalt beteende'],
             ['Nervous system', u'dyskinesi, psykomotorisk hyperaktivitet, somnolens'],
             ['Cardiac', u'Arrytmi, takydardi, hj\xe4rtklappning Hypertoni'],
             ['Respiratory', u'Hosta, sm\xe4rta i svalg/strupe'],
             ['GI',
              u'Buksm\xe4rta, diarr\xe9, illam\xe5ende, magbesv\xe4r och kr\xe4kningar. Muntorrhet.'],
             ['Skin', u'Alopeci, kl\xe5da, utslag, urtikaria'],
             ['Musculoskeletal', u'Artralgi'],
             ['General',
              u'Pyrexi, tillv\xe4xtf\xf6rdr\xf6jni -ng under l\xe5ngvarig anv\xe4ndning hos barn* F\xf6r\xe4ndringar i']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Blood', u'\xd6verk\xe4nslighetsreaktio'],
             ['Immune system',
              u'ner som angioneurotiskt \xf6dem, anafylaktiska reaktioner, \xf6ronsvullnad, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd, urtikaria, pruritus och utslag'],
<<<<<<< HEAD
             ['Psychiatric', u'h\xf6rsel-, syn-och k\xe4nselhallucinationer  ,'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Cardiac', u'Br\xf6stsm\xe4rta'],
             ['Respiratory', u'Dyspn\xe9 F\xf6rstoppning'],
             ['Hepato', u'leverenzymer Angioneurotiskt \xf6dem,'],
             ['Skin', u'vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd'],
             ['Musculoskeletal', u'Myalgi, muskelryckningar'],
             ['Renal', u'Hematuri'],
             ['Reproductive system', u'Br\xf6stsm\xe4rta, tr\xf6tthet'],
             ['General', u'Bl\xe5sljud p\xe5 hj\xe4rtat , \xf6kning av leverenzymer']]],
           ['Rare',
            [['Psychiatric', u'desorienterin-g,  ,'],
             ['Cardiac', u'Angina pectoris'],
             ['Hepato', u'Hyperhidros,'],
             ['Skin', u'makul\xe4ra utslag, erytem'],
             ['Reproductive system', u'Gynekomasti']]],
           ['Very rare',
            [['Infections', u'Anemi, leukopeni,'],
             ['Blood', u'trombocytopeni, trombocytopenisk purpura'],
             ['Psychiatric', u'(inklusive fullbordat'],
             ['Nervous system',
              u'koreoatetoida r\xf6relser, reversibla ischemiska bortfallssymtom, malignt neuroleptikasyndr-om (NMS; rapporterna var d\xe5ligt dokumenterade och i de flesta fall fick patienterna \xe4ven andra l\xe4kemedel. \xe4r d\xe4rf\xf6r oklar.)'],
             ['Eye', u'Sv\xe5righeter att ackommodera, mydriasis, synst\xf6rningar'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, hj\xe4rtinfarkt'],
             ['Vascular',
              u'Cerebral arterit och/eller ocklusion, perifer kyla, Raynauds fenomen'],
             ['Hepato', u'leverfunktion inklusive leverkoma Erythema'],
             ['Skin', u'multiforme, exfoliativ dermatit, fixt l\xe4kemedelsutslag'],
             ['Musculoskeletal', u'Muskelkramper'],
             ['Reproductive system', u'Pl\xf6tslig kardiell'],
             ['General', u'd\xf6d \xd6kning av alkaliska fosfater']]],
           ['Unknown',
            [['Infections', u'Pancytope'],
             ['Psychiatric', u'llningar  , tankest\xf6rn'],
             ['Nervous system',
              u'skul\xe4ra st\xf6rningar (inklusive vaskulit, cerebral bl\xf6dning, cerebrovas -kul\xe4ra h\xe4ndelser, cerebral artrit, cerebral ocklusion), grand migr\xe4n'],
             ['Cardiac',
              u'Supraventr -ikul\xe4r takykardi, bradykardi, ventrikul\xe4r -a extrasystol -ier, extrasystol'],
             ['Reproductive system', u'Erektil dysfunktio n Obehagsk\xe4'],
             ['General', u'nsla i br\xf6stet, hyperpyre']]]],
 '_note': u' ?MSFU ANOMALI in Headers',
 '_pages': [9, 11],
 u'_rank': 50,
=======
             ['Psychiatric',
              u'Psykotiska tillst\xe5nd k\xe4nselhallucinationer , hum\xf6rsv\xe4ngningar, rastl\xf6shet, gr\xe5tmildhet, , f\xf6rv\xe4rring av befintliga tics eller Tourettes syndrom*, sp\xe4nd vaksamhet, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Diplopi, dimsyn'],
             ['Cardiac', u'Br\xf6stsm\xe4rta'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'F\xf6rstoppning \xd6kning av'],
             ['Hepato', u'leverenzymer'],
             ['Skin',
              u'Angioneurotiskt \xf6dem, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd'],
             ['Musculoskeletal', u'Myalgi, muskelryckningar'],
             ['Renal', u'Hematuri'],
             ['General', u'Br\xf6stsm\xe4rta, tr\xf6tthet Bl\xe5sljud p\xe5 hj\xe4rtat  ,']]],
           ['Rare',
            [['Psychiatric', u'Mani* , -g, ,'],
             ['Cardiac', u'Angina pectoris'],
             ['Skin', u'Hyperhidros, makul\xe4ra utslag, erytem'],
             ['Reproductive system', u'Gynekomasti']]],
           ['Very rare',
            [['Blood', u'Anemi, leukopeni, trombocytopeni, trombocytopenisk purpura'],
             ['Psychiatric',
              u'Sj\xe4lvmordsf\xf6rs\xf6k , fullbordat sinnesst\xe4mning onormala tankar, apati, repetitiva beteenden, \xf6verfokusering'],
             ['Nervous system',
              u'koreoatetoida r\xf6relser, reversibla ischemiska bortfallssymtom, malignt neuroleptikasyndr-om (NMS; rapporterna var d\xe5ligt dokumenterade och i de flesta fall fick patienterna \xe4ven andra l\xe4kemedel. \xe4r d\xe4rf\xf6r oklar.) Sv\xe5righeter att'],
             ['Eye', u'ackommodera, mydriasis, synst\xf6rningar'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, hj\xe4rtinfarkt Cerebral arterit'],
             ['Vascular', u'och/eller ocklusion, perifer kyla, Raynauds fenomen'],
             ['GI', u'Onormal'],
             ['Hepato', u'leverfunktion inklusive leverkoma'],
             ['Skin', u'Erythema multiforme, exfoliativ dermatit, fixt l\xe4kemedelsutslag'],
             ['Musculoskeletal', u'Muskelkramper'],
             ['General', u'Pl\xf6tslig kardiell d\xf6d \xd6kning av']]],
           ['Unknown',
            [['Blood', u'Pancytope'],
             ['Psychiatric',
              u'Vanf\xf6rest\xe4 tankest\xf6rn-, fall av missbruk och beroende har beskrivits, oftare med formulerin-gar med'],
             ['Nervous system',
              u'skul\xe4ra st\xf6rningar (inklusive vaskulit, cerebral bl\xf6dning, cerebrovas-kul\xe4ra h\xe4ndelser, cerebral artrit, cerebral ocklusion), grand mal-migr\xe4n'],
             ['Cardiac',
              u'Supraventr -ikul\xe4r takykardi, bradykardi, ventrikul\xe4r -a extrasystol -ier, extrasystol'],
             ['General', u'Obehagsk\xe4 -nsla i br\xf6stet, hyperpyre']]]],
 '_note': u' ?MSFU ANOMALI in Headers',
 '_pages': [8, 11],
 u'_rank': 44,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}