{'_data': [['Very common',
            [['Metabolism', u'Hypomagnesemi (se avsnitt 4.4).'],
             ['Hepato',
              u'F\xf6rh\xf6jning av leverenzymniv\xe5er (ASAT, ALAT, alkalisk fosfatas).'],
             ['Skin', u'Hudreaktioner*.'],
             ['General',
              u'L\xe4tta eller m\xe5ttliga infusionsrelaterade reaktioner*; mukosit, ibland allvarlig. Mukosit kan leda till epistaxis.']]],
           ['Common',
            [['Metabolism',
              u'Uttorkning, i synnerhet sekund\xe4rt till diarr\xe9 eller mukosit; hypokalcemi (se avsnitt 4.4); anorexia som kan leda till viktminskning.'],
             ['Nervous system', u'Huvudv\xe4rk.'],
             ['Eye', u'Konjunktivit.'],
             ['GI', u'Diarr\xe9, illam\xe5ende, kr\xe4kning.'],
             ['General', u'Allvarliga infusionsrelaterade reaktioner*, tr\xf6tthet.']]],
           ['Uncommon',
            [['Eye', u'Blefarit, keratit.'],
             ['Vascular', u'Djup ventrombos.'],
             ['Respiratory', u'Lungembolism, interstitiell lungsjukdom.']]],
           ['Very rare', [['Skin', u'Stevens-Johnson syndrom/toxiskt epidermal nekrolys.']]],
           ['Unknown',
            [['Nervous system', u'Aseptisk meningit.'],
             ['Skin', u'Superinfektioner av hudlesioner*.']]]],
 '_pages': [6, 8],
 u'_rank': 15,
 u'_type': u'LSFU'}