{'_data': [['Very common', [['Nervous system', u'tremor'], ['GI', u'illam\xe5ende']]],
           ['Common',
            [['Blood',
              u'anemi, trombocytopeni, nedsatt trombocytadhesivi-t et, f\xf6rl\xe4ngd bl\xf6dningstid'],
             ['Metabolism', u'hyponatremi'],
             ['Psychiatric',
              u'f\xf6rvirringstillst\xe5nd, aggressivitet, agitation, uppm\xe4rksamhets-st \xf6rning'],
             ['Nervous system',
              u'extrapyramidala symtom, stupor somnolens, kramper , f\xf6rs\xe4mrat minne, huvudv\xe4rk, nystagmus, yrsel som kan uppkomma n\xe5gra minuter efter en intraven\xf6s injektion (f\xf6rsvinner spontant inom n\xe5gra minuter)'],
             ['Ear', u'd\xf6vhet'],
             ['Vascular', u'bl\xf6dningar'],
             ['GI', u'sm\xe4rtor i \xf6vre magtrakten, kr\xe4kningar, diarr\xe9'],
             ['Hepato',
              u'leverskada, f\xf6r\xe4ndringar i leverv\xe4rden s\xe5som f\xf6rh\xf6jda transaminas-och fosfatasv\xe4rden.'],
             ['Skin',
              u'\xf6verk\xe4nslighets-rea ktioner, \xf6verg\xe5ende och/eller dosberoende h\xe5ravfall'],
             ['Reproductive system', u'dysmenorr\xe9'],
             ['General', u'\xf6kad aptit, anorexi och viktf\xf6rlust'],
             ['Investigations', u'vikt\xf6kning']]],
           ['Uncommon',
            [['Blood', u'pancytopeni, leukopeni'],
             ['Endocrine', u'SIADH (Syndrome of Inappropriate Secretion of ADH)'],
             ['Psychiatric', u'insomningssv\xe5rig-heter'],
             ['Nervous system',
              u'ataxi, koma , , encefalopati , letargi , reversibel parkinsonism, parestesier'],
             ['Respiratory', u'pleurautgjutning'],
             ['Vascular', u'vaskulit'],
             ['GI', u'pankreatit (ibland letal)'],
             ['Hepato',
              u'sv\xe5r leverp\xe5verkan (ibland med letal levernekros) hos barn under 3 \xe5rs \xe5lder, vilka st\xe5tt p\xe5 kombinationsbe-h andling'],
             ['Skin', u'\xe4ndrad h\xe5rf\xe4rg, angio\xf6dem, hudutslag'],
             ['Musculoskeletal',
              u's\xe4nkt bent\xe4thet, osteopeni, osteoporos och frakturer hos patienter som st\xe5r p\xe5 l\xe5ngtids-behandlin g med Ergenyl. (Mekanismen, genom vilken Ergenyl p\xe5verkar skelett-metabolis men, har inte identifierats.)'],
             ['Renal', u'\xf6kad miktionsfrekvens'],
             ['Reproductive system', u'amenorr\xe9'],
             ['General', u'tr\xf6tthet, perifert \xf6dem']]],
           ['Rare',
            [['Neoplasms', u'myelodysplastiskt syndrom'],
             ['Blood',
              u'eosinofili, benm\xe4rgsdepression inkluderande erytrocytaplasi (pure red cell aplasia), agranulocytos, makrocyt\xe4r anemi, makrocytos'],
             ['Endocrine', u'hypotyreos'],
             ['Metabolism', u'hyperammonemi**'],
             ['Psychiatric',
              u'psykos, beteendeavvikelser, psykomotorisk hyperaktivitet, inl\xe4rningssv\xe5righeter'],
             ['Nervous system',
              u'reversibel demens associerad med reversibel hj\xe4rnatrofi, kognitiv st\xf6rning'],
             ['GI', u'obstipation'],
             ['Hepato', u'sv\xe5r leverp\xe5verkan hos barn \xf6ver 3 \xe5r'],
             ['Skin',
              u'toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme, DRESS (Drug Rash with Eosinophilia and Systemic Symptoms)'],
             ['Musculoskeletal', u'systemisk lupus erythematosus (SLE)'],
             ['Renal', u'enures, reversibelt Fanconis syndrom'],
             ['Reproductive system', u'manlig infertilitet, polycystiska ovarier'],
             ['General', u'hypotermi'],
             ['Investigations',
              u'minskning av koagulationsfaktorer (minst en), onormala koagulationstester (s\xe5som f\xf6rl\xe4ngd protrombintid, f\xf6rl\xe4ngd aktiverad partiell tromboplastintid, f\xf6rl\xe4ngd trombintid, f\xf6rh\xf6jt INR-v\xe4rde)']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 41,
 u'_type': u'MSFU'}