{'_data': [['Common',
            [['General', u' Feber och allergiska reaktioner.  '],
             ['Blood', u' Sepsis, reduktion av fibrinogen och andra koagulationsfaktorer.  '],
             ['Nervous system',
              u' Depressioner, tr\xf6tthet, f\xf6rvirring, f\xf6rlust av n\xe4rminne. '],
             ['GI', u' Illam\xe5ende och kr\xe4kningar, pankreatit. '],
             ['Hepato',
              u' \xd6kade niv\xe5er bilirubin, ASAT, BSP och alkaliskt fosfatas, reduktion av albumin. '],
             ['Metabolism', u' \xd6kade niv\xe5er kolesterol. ']]],
           ['Uncommon',
            [['General', u' Anafylaktisk reaktion.  '],
             ['Metabolism', u' \xd6kade niv\xe5er insulin. ']]],
           ['Rare', [['GI', u' Haemorragisk pankreatit.  ']]]],
 '_pages': [2, 2],
 u'_rank': 9,
 u'_type': u'DFSU'}