{'_data': [['Very common',
            [['GI', u'Dyspepsi, illam\xe5ende, diarr\xe9'],
             ['Skin', u'Fotosensitivitetsreaktion och hudutslag'],
             ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Infections', u'\xd6vre luftv\xe4gsinfektion, urinv\xe4gsinfektion'],
             ['Metabolism', u'Viktminskning, anorexi, aptitl\xf6shet'],
             ['Psychiatric', u'S\xf6mnsv\xe5righeter'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk, s\xf6mnighet, smakrubbningar'],
             ['Vascular', u'Blodvallningar'],
             ['Respiratory', u'Dyspn\xe9, hosta, slemhosta'],
             ['GI',
              u'Gastroesofageal reflux, kr\xe4kningar, sp\xe4nd buk, obehagsk\xe4nslor i buken, magsm\xe4rtor, sm\xe4rtor i bukens \xf6vre del, magbesv\xe4r, gastrit, f\xf6rstoppning, flatulens Tabell 1 Biverkningar enligt organsystemklass och MedDRA-frekvens'],
             ['Hepato',
              u'F\xf6rh\xf6jt ALAT, f\xf6rh\xf6jt ASAT, f\xf6rh\xf6jt glutamyltransferas'],
             ['Skin',
              u'Kl\xe5da, erytem, torr hud, erytemat\xf6sa utslag, makul\xe4ra utslag, kliande utslag'],
             ['Musculoskeletal', u'Muskelv\xe4rk, ledv\xe4rk'],
             ['General', u'Asteni, icke-kardiell br\xf6stsm\xe4rta'],
             ['Injury', u'Solskador']]]],
 '_pages': [6, 7],
 u'_rank': 15,
 u'_type': u'LSFU'}