{'_data': [[u'Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Anafylaktisk'],
             ['Endocrine', u'Inadekvat ADH-'],
             ['Metabolism', u'Minskad aptit, \xf6kad   Hyponatremi,   aptit   anorexi'],
             ['Psychiatric',
              u'\xc5ngest, rastl\xf6shet,   Bruxism,   Aggression,   Mani, suicidtankar,'],
             ['Nervous system',
              u'Insomnia,   Smakf\xf6r\xe4ndringar   Serotonergt   Dyskinesi,   somnolens, yrsel,   , s\xf6mnst\xf6rningar,   syndrom   koordinations-'],
             ['Eye', u'Mydriasis,'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Takykardi   Bradykardi   Elektrokardiogram'],
             ['Vascular', u'Ortostatisk'],
             ['Respiratory', u'Sinuit, g\xe4spning   Epistaxis'],
             ['GI', u'Illam\xe5end   Diarr\xe9,   Gastrointestinal'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'\xd6kad svettning   Urtikaria, alopeci,   Ekkymoser,   rash, pruritus   angio\xf6dem'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Renal', u'Urinretention'],
             ['Reproductive system', u'M\xe4n:   Kvinnor:   Galaktorr\xe9'],
             ['General', u'Utmattning, feber   \xd6dem'],
             ['Investigations', u'Vikt\xf6kning   Viktminskning   Onormala']]]],
 '_pages': [9, 11],
 u'_rank': 19,
 u'_type': u'LFSU'}