{'_data': [['Common',
            [['GI',
              u'Buksm\xe4rtor, diarr\xe9, gasbildning, illam\xe5ende/kr\xe4k nin, f\xf6rstoppning'],
             ['General', u'id']]],
           ['Uncommon',
            [['GI', u'Muntorrhet'],
             ['Hepato', u'F\xf6rh\xf6jning av leverenzymer'],
             ['Skin', u'Dermatit, kl\xe5da, n\xe4sselutslag'],
             ['Musculoskeletal', u'H\xf6ft-, handleds-eller kotfrakturer (se avsnitt 4.4)']]],
           ['Rare',
            [['GI', u'Stomatit, gastrointestinal candidiasis'],
             ['Hepato', u'Hepatit med eller utan gulsot'],
             ['Skin', u'H\xe5ravfall, fotosensitivitet'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['General', u'Allm\xe4n'],
             ['General', u'sjukdomsk\xe4nsla, \xf6kad svettning'],
             ['Hepato', u'Leversvikt, encefalopat i hos leversjuka patienter'],
             ['Skin',
              u'Stevens-Jo hnsons syndrom, erytema multiforme, toxisk epidermal nekrolys (TEN)'],
             ['Musculoskeletal', u'Muskelsva ghet'],
             ['Renal', u'Interstitiell nefrit'],
             ['Reproductive system', u'Gynekomas']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 17,
 u'_type': u'MSFU'}