{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Skin', u'Reaktioner p\xe5 applikations-st\xe4llet'],
             ['Reproductive system',
              u'Br\xf6stsm\xe4rta , \xf6mma br\xf6st, menstruations-rubbningar']]],
           ['Common',
            [['Psychiatric', u'Depression*, nervositet*, affektlabilitet'],
             ['Nervous system', u'Yrsel , s\xf6mnsv\xe5righeter'],
             ['GI', u'Illam\xe5ende, diarr\xe9 , buksm\xe4rta'],
             ['Skin', u'Akne pruritus hud'],
             ['Musculoskeletal', u'Ryggsm\xe4rta , extremitets-* sm\xe4rta'],
             ['Reproductive system',
              u'Br\xf6stf\xf6rstoring menorragi * , oregelbunden * vaginal bl\xf6dning, uterinspasm, vaginal infektion, endometrie-hyperplasi'],
             ['General', u'Sm\xe4rta, asteni, perifert \xf6dem*, vikt\xf6kning*']]],
           ['Uncommon',
            [['Nervous system', u'Migr\xe4n, vertigo'],
             ['Vascular', u'Hypertension, \xe5derbr\xe5ck'],
             ['GI', u'Kr\xe4kning'],
             ['Skin', u', utslag, av huden'],
             ['Reproductive system', u','],
             ['Investigations', u'Transaminas-\xf6kning']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'Libido-f\xf6r\xe4ndringar'],
             ['Nervous system', u'Parestesi'],
             ['Vascular', u'Ven\xf6s emboli'],
             ['Hepato', u'Gallbl\xe5se-sjukdom, kolelitiasis'],
             ['Skin', u'Missf\xe4rgning'],
             ['Musculoskeletal', u'Myasteni'],
             ['Reproductive system', u'Br\xf6stcancer p\xe5 \xe4ggledare,']]],
           ['Very rare',
            [['Hepato', u'Kolestatisk gulsot'], ['Reproductive system', u'Myom, cystor']]],
           ['Unknown', [['Skin', u'Alopeci']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 27,
 u'_type': u'MSFU'}