{'_data': [['Very common', [['Metabolism', u'Hyperkalemi.']]],
           ['Common',
            [['Infections', u'Candida-infektion'],
             ['Nervous system', u'Huvudv\xe4rk.'],
             ['GI', u'Illam\xe5ende, diarr\xe9.'],
             ['Skin', u'Hudutslag.']]],
           ['Uncommon', [['GI', u'Kr\xe4kningar.']]],
           ['Very rare',
            [['Blood',
              u'Leukopeni, neutropeni, trombocytopeni, agranulocytos, megaloblastisk anemi, aplastisk anemi, hemolytisk anemi, methemoglobinemi, eosinofili, purpura, hemolys hos vissa k\xe4nsliga patienter med G-6-PD brist.'],
             ['Immune system',
              u'Serumsjuka, anafylaxi, allergisk myokardit, angio\xf6dem, feber, allergisk vaskulit liknande Henoch-Schoenlein purpura, periarteritis nodosa, SLE.'],
             ['Metabolism', u'Hypoglykemi, hyponatremi, anorexi.'],
             ['Psychiatric', u'Depression, hallucinationer.'],
             ['Nervous system',
              u'Aseptisk meningit, konvulsioner, perifer neurit, ataxi, yrsel, tinnitus. Aseptisk meningit var snabbt reversibel vid uts\xe4ttande av l\xe4kemedlet, men \xe5terkom i ett antal fall n\xe4r trimetoprim/sulfametoxazol eller enbart trimetoprim sattes in p\xe5 nytt.'],
             ['Respiratory',
              u'Hosta, andn\xf6d, lunginfiltrat. Hosta, andn\xf6d och lunginfiltrat kan vara en tidig indikation p\xe5 \xf6verk\xe4nslighet i andningsv\xe4garna som i enstaka fall orsakat d\xf6dsfall.'],
             ['GI', u'Glossit, stomatit, pseudomemban\xf6s kolit, pankreatit.'],
             ['Eye', u'Uveit'],
             ['Hepato',
              u'F\xf6rh\xf6jning av serumtransaminaser och bilirubinv\xe4rden, kolestatisk gulsot, levernekros. Leverf\xf6r\xe4ndringar inkluderande s\xe5dana med d\xf6dlig utg\xe5ng har registrerats hos riskpatienter. Kolestatisk gulsot och levernekros kan leda till d\xf6den.'],
             ['Skin',
              u'Fotosensitivitet, exfoliativ dermatit, fixt l\xe4kemedelsutslag, erythema multiforme. Allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs); Stevens-Johnson syndrome (SJS) och toxisk epidermal nekrolys (TEN) har rapporterats (se 4.4).'],
             ['Musculoskeletal', u'Artralgi, myalgi.'],
             ['Renal',
              u'Nedsatt njurfunktion (ibland rapporterat som njursvikt), interstitiell nefrit. Effekter associerade med behandling av Pneumocystis jiroveci -pneumoni (PCP)'],
             ['Renal',
              u'Allvarliga \xf6verk\xe4nslighetsreaktioner, hudutslag, feber, neutropeni, trombocytopeni, f\xf6rh\xf6jda leverv\xe4rden, rabdomyolys, hyperkalemi, hyponatremi. Vid de h\xf6ga doser som anv\xe4nds vid behandling av PCP har allvarliga \xf6verk\xe4nslighetsreaktioner rapporterats vilket kr\xe4vt uts\xe4ttande av behandlingen. Vid tecken p\xe5 nedsatt benm\xe4rgsfunktion skall patienten f\xe5 tillskott av kalciumfolat (5-10 mg/dag). Allvarliga \xf6verk\xe4nslighetsreaktioner har rapporterats hos PCP-patienter som exponerats p\xe5 nytt f\xf6r trimetoprim/sulfametoxazol, ibland efter bara n\xe5gra f\xe5 dagars behandling. Rabdomyolys har rapporterats hos hivpositiva patienter som erh\xe5llits trimetoprim/sulfametoxazol som profylax eller behandling av PCP.']]]],
 '_pages': [6, 7],
 u'_rank': 19,
 u'_type': u'LSFU'}