{'_data': [['Very common',
            [['Infections', u'Vulvovaginal svampinfektion,'],
             ['Psychiatric', u'Hum\xf6rp\xe5verkan  och'],
             ['Nervous system', u'Huvud-v\xe4rk'],
             ['GI', u'Illam\xe5-ende'],
             ['Skin', u'Akne,'],
             ['Musculoskeletal', u'Muskelspasmer'],
             ['Reproductive system', u'\xd6mhet i br\xf6sten'],
             ['General', u'Sjukdomsk\xe4nsla,'],
             ['Investigations', u'Vikt\xf6kning F\xf6rh\xf6jt']]],
           ['Common',
            [['Infections', u'vaginal candidiasis'],
             ['Psychiatric', u'\xe5ngestsjukdomar'],
             ['Nervous system', u'Migr\xe4n, yrsel'],
             ['GI', u'Buksm\xe4rta, kr\xe4kningar, diarr\xe9, bukdistension,'],
             ['Skin', u'utslag, kl\xe5da, hudreaktioner, hudirritation'],
             ['Reproductive system',
              u'Dysmenorr\xe9, vaginal bl\xf6dning och menstruations-uterin spasm, br\xf6stsjukdomar, vaginal flytning'],
             ['General',
              u'tr\xf6tthet, symtom vid administrerings-st\xe4llet (erytem, irritation, kl\xe5da, utslag)']]],
           ['Uncommon',
            [['Infections', u'Pustul\xf6sa pustler p\xe5'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Hyperkolesterolemi, v\xe4tskeretention, \xf6kad aptit'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, minskad libido'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Kolit*'],
             ['Skin',
              u'Alopeci, allergisk dermatit, eksem, ljusk\xe4nslighets-reaktion, kontaktdermatit, urtikaria, erytem'],
             ['Reproductive system', u'Galaktorr\xe9, premenstruellt syndrom,'],
             ['General',
              u'Generaliserat \xf6dem, perifert \xf6dem, reaktioner p\xe5 administrerings-st\xe4llet**'],
             ['Investigations', u'blodtryck, blodfettsjukdomar**']]],
           ['Rare',
            [['Infections', u'utslag*, applikationsst\xe4llet'],
             ['Neoplasms',
              u'Leverneoplasi* , br\xf6stcancer* , cervixcancer* , leveradenom* , uterusleiomyom, fibroadenom i br\xf6sten'],
             ['Metabolism', u'Hyperglykemi*, insulinresistens*'],
             ['Psychiatric', u'Ilska*, frustration*, \xf6kad libido'],
             ['Nervous system',
              u'Cerebrovaskul\xe4ra h\xe4ndelser** , hj\xe4rnbl\xf6dning* onormal smakupplevelse*'],
             ['Eye', u'Kontaktlinsintolerans*'],
             ['Cardiac', u'(Akut)  hj\xe4rtinfarkt*'],
             ['Vascular', u'Hypertensiv  kris*, trombos*'],
             ['Respiratory', u'Lung(art\xe4r)trombos* , lungemboli'],
             ['Hepato',
              u'Kolecystit, gallsten , leverskada*, kolestatisk gulsot*  , gallstas*'],
             ['Skin',
              u'Angio\xf6dem*, erythema (multiforme, nodosum)*, kloasma , exfoliativa utslag*, generaliserad kl\xe5da, utslag (erytemat\xf6sa, kliande), seborroisk dermatit*'],
             ['Reproductive system',
              u'Cervikal dysplasi*, h\xe4mmad laktation*, genital flytning'],
             ['General',
              u'Ansikts\xf6dem*, pitting\xf6dem*, svullnad, reaktioner p\xe5 administreringsst\xe4llet* (t ex abscess, erosion), lokaliserat \xf6dem*'],
             ['Investigations', u'S\xe4nkt blodglukos*  , avvikande blodglukos*']]]],
 '_note': u' ?MSFU',
 '_pages': [11, 13],
 u'_rank': 40,
 u'_type': u'MSFU'}