{'_data': [['Very common',
            [['Metabolism', u'Anorexi'],
             ['Nervous system', u'Yrsel'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['GI', u'Diarr\xe9'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['General', u'Fall']]],
           ['Common',
            [['Psychiatric', u'Agitation'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Psychiatric', u'Oro'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'S\xf6mnighet'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['Skin', u'Hyperhidros'],
             ['General', u'Tr\xf6tthet och asteni'],
             ['General', u'Olustk\xe4nsla'],
             ['Investigations',
              u'Viktminskning F\xf6ljande ytterligare biverkningar har observerats med Exelon depotpl\xe5ster: delirium, pyrexi, minskad aptit, urininkontinens (vanliga), psykomotorisk hyperaktivitet (mindre vanliga), erytem, urtikaria, vesikler, allergisk dermatit (ingen k\xe4nd frekvens).'],
             ['Metabolism', u'Minskad aptit'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Psychiatric', u'Oro'],
             ['Psychiatric', u'Rastl\xf6shet'],
             ['Psychiatric', u'Hallucination, visuell'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'S\xf6mnighet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'F\xf6rs\xe4mring av Parkinsons sjukdom'],
             ['Nervous system', u'Bradykinesi'],
             ['Nervous system', u'Dyskinesi'],
             ['Nervous system', u'Hypokinesi'],
             ['Nervous system', u'Kugghjulsstelhet'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Diarr\xe9'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['GI', u'Saliv hypersekretion'],
             ['Skin', u'Hyperhidros'],
             ['General', u'Tr\xf6tthet och asteni'],
             ['General', u'G\xe5ngrubbning'],
             ['General',
              u'Parkinsonliknande g\xe5ng F\xf6ljande ytterligare biverkning har observerats i en studie med patienter med Parkinson-patienter med demens som behandlats med Exelon depotpl\xe5ster: agitation (vanlig).']]],
           ['Uncommon',
            [['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Synkope'],
             ['Hepato', u'F\xf6rh\xf6jda leverv\xe4rden'],
             ['General', u'Fall'],
             ['Nervous system', u'Dystoni'],
             ['Cardiac', u'F\xf6rmaksflimmer'],
             ['Cardiac', u'Atrioventrikul\xe4rblock'],
             ['Vascular', u'Hypotension']]],
           ['Rare',
            [['Nervous system', u'Krampanfall'],
             ['Cardiac', u'Angina pectoris'],
             ['GI', u'Mag- och duodenal s\xe5r'],
             ['Skin', u'Hudutslag']]],
           ['Very rare',
            [['Infections', u'Urinv\xe4gsinfektion'],
             ['Psychiatric', u'Hallucinationer'],
             ['Nervous system',
              u'Extrapyramidala symtom (inklusive f\xf6rs\xe4mring av Parkinsons sjukdom)'],
             ['Cardiac',
              u'Hj\xe4rtarytmier (t ex bradykardi, atrioventrikul\xe4rblock, f\xf6rmaksflimmer and takykardi)'],
             ['Vascular', u'H\xf6gt blodtryck'],
             ['GI', u'Gastrointestinala bl\xf6dningar'],
             ['GI', u'Pankreatit']]],
           ['Unknown',
            [['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Ingen k\xe4nd frekvens Aggression, rastl\xf6shet'],
             ['Cardiac', u'Sjuk sinusknuta (sick sinus syndrome)'],
             ['GI',
              u'Vissa fall med kraftig kr\xe4kning var f\xf6renade med esofagusruptur (se avsnitt 4.4).'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Pruritus, utbredda kutana \xf6verk\xe4nslighetsrektioner'],
             ['Psychiatric', u'Aggression'],
             ['Cardiac', u'Sjuk sinusknuta (sick sinus syndrome)'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Utbredda kutana \xf6verk\xe4nslighetsrektioner']]]],
 '_pages': [5, 8],
 u'_rank': 74,
 u'_type': u'LSFU'}