{'_data': [['Very common',
            [['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Blodvallaningar'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'\xd6kad svettning'],
             ['Musculoskeletal', u'Led- och muskuloskeletal sm\xe4rta*'],
             ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Metabolism', u'Anorexia'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Yrsel, karpaltunnelsyndrom'],
             ['GI', u'Buksm\xe4rta, kr\xe4kningar, f\xf6rstoppning, dyspepsi, diarr\xe9'],
             ['Skin', u'Hudutslag, h\xe5ravfall'],
             ['Musculoskeletal', u'Osteoporos, frakturer'],
             ['General', u'Sm\xe4rta, perifert \xf6dem']]],
<<<<<<< HEAD
           ['Uncommon', [['Nervous system', u'S\xf6mnighet'], ['General', u'Asteni']]],
=======
           ['Uncommon',
            [['Nervous system', u'S\xf6mnighet'],
             ['General',
              u'Asteni *Omfattar artralgi och mindre ofta sm\xe4rta i armar och ben, osteoartrit, ryggsm\xe4rta, artrit, myalgi och ledstyvhet.']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Blood',
              u'Hos patienter med avancerad br\xf6stcancer har trombocytopeni och leukopeni rapporterats i s\xe4llsynta fall. En tillf\xe4llig minskning i lymfocyter har observerats hos ungef\xe4r 20 % av patienterna som st\xe5r p\xe5 exemestan, s\xe4rskilt hos patienter med redan existerande lymfopeni. De genomsnittliga lymfocytniv\xe5erna hos dessa patienter f\xf6r\xe4ndrades emellertid inte signifikant \xf6ver tiden och ingen motsvarande \xf6kning i virusinfektioner observerades. Dessa effekter observerades i studierna med patienter som behandlades f\xf6r tidig br\xf6stcancer.'],
             ['Hepato',
<<<<<<< HEAD
              u'F\xf6rh\xf6jda v\xe4rden f\xf6r parametrar i leverfunktionstester inklusive enzymer, bilirubin och alkalinfosfatas har observerats.'],
             ['Hepato',
              u'Eftersom biverkningar rapporteras frivilligt fr\xe5n en population av ok\xe4nd storlek, \xe4r det inte alltid m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt uppskatta frekvens eller att s\xe4kerst\xe4lla ett orsakssamband till exponering av l\xe4kemedel.']]]],
 '_pages': [3, 5],
 u'_rank': 19,
=======
              u'F\xf6rh\xf6jda v\xe4rden f\xf6r parametrar i leverfunktionstester inklusive enzymer, bilirubin och alkalinfosfatas har observerats. Tabellen nedan visar frekvensen av pre-specificerade biverkningar och sjukdomar i den tidiga br\xf6stcancerstudien (IES), oberoende av orsak, och som rapporterats hos patienter som fick f\xf6rs\xf6ksbehandling och upp till 30 dagar efter avbruten f\xf6rs\xf6ksbehandling. Biverkningar samt sjukdomar Exemestan Tamoxifen (N = 2249) (N = 2279) Blodvallningar 491 (21,8%) 457(20,1%) Tr\xf6tthet 367 (16,3%) 344 (15,1%) Huvudv\xe4rk 305 (13,6%) 255 (11,2%) S\xf6mnl\xf6shet 290 (12,9%) 204 (9,0%) \xd6kad svettning 270 (12,0%) 242 (10,6%) Gynekologiska 235 (10,5%) 340 (14,9%) Yrsel 224 (10,0%) 200 (8,8%) Illam\xe5ende 200 (8,9%) 208 (9,1%) Osteoporos 116(5,2%) 66 (2,9%) Vaginal bl\xf6dning 90 (4,0%) 121 (5,3%) Annan prim\xe4r cancer 84 (3,6%) 125 (5,3%) Kr\xe4kningar 50 (2,2%) 54 (2,4%) Synst\xf6rningar 45 (2,0%) 53 (2,3%) Tromboembolism 16 (0,7%) 42 (1,8%) Osteoporotisk fraktur 14 (0,6%) 12 (0,5%) Biverkningar samt sjukdomar Exemestan Tamoxifen (N = 2249) (N = 2279) Hj\xe4rtinfarkt 13 (0,6%) 4 (0,2%) I IES-studien var frekvensen ischemiska hj\xe4rtbiverkningar 4,5 % och 4,2 % i exemestan- respektive tamoxifenarmen. Ingen signifikant skillnad noterades f\xf6r enskilda kardiovaskul\xe4ra biverkningar, inklusive hypertension (9,9 % respektive 8,4 %), hj\xe4rtinfarkt (0,6 respektive 0,2 %) och hj\xe4rtsvikt (1,1 % respektive 0,7 %). I IES-studien associerades exemestan med h\xf6gre incidens av hyperkolesterolemi j\xe4mf\xf6rt med tamoxifen (3,7 % j\xe4mf\xf6rt med 2,1 %). I en separat, dubbel-blind och randomiserad studie, d\xe4r postmenopausala kvinnor med tidig br\xf6stcancer, l\xe5grisk, behandlades med exemestan (N=73) eller placebo (N=73) i 24 m\xe5nader, var den genomsnittliga s\xe4nkningen av plasma-HDL-kolesterol 7-9 % vid behandling med exemestan, j\xe4mf\xf6rt med en \xf6kning med 1 % vid placebo. Det blev ocks\xe5 en minskning med 5-6 % av apolipoprotein A1 hos exemestangruppen j\xe4mf\xf6rt med 0-2 % f\xf6r placebo. Effekten p\xe5 andra analyserade lipidparametrar (totalkolesterol, LDL-kolesterol, triglycerider, apolipidoprotein-B och lopoprotein-a) var likv\xe4rdig f\xf6r de tv\xe5 behandlingsgrupperna. Den kliniska signifikansen av dessa resultat \xe4r oklar. I IES-studien observerades att mags\xe5r intr\xe4ffande i h\xf6gre grad vid behandling med exemestan j\xe4mf\xf6rt med tamoxifen (0,7 % respektive <0,1 %). Majoriteten av patienterna som behandlades med exemestan och som fick mags\xe5r behandlades samtidigt med NSAID och/eller hade gjort det tidigare. Biverkningar rapporterade efter marknadsintroduktion Lever och gallv\xe4gar: Hepatit, kolestatisk hepatit. Eftersom biverkningar rapporteras frivilligt fr\xe5n en population av ok\xe4nd storlek, \xe4r det inte alltid m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt uppskatta frekvens eller att s\xe4kerst\xe4lla ett orsakssamband till exponering av l\xe4kemedel.']]]],
 '_pages': [3, 5],
 u'_rank': 18,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}