{'_data': [['Very common',
            [['Psychiatric', u'insomni'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Vascular', u'blodvallningar'],
             ['GI', u'illam\xe5ende'],
             ['Skin', u'\xf6kad svettning'],
             ['Musculoskeletal',
              u'ledsm\xe4rta och muskuloskeletal sm\xe4rta (inklusive artralgi och mer s\xe4llan sm\xe4rta i extremiteter, osteoartrit, ryggsm\xe4rta, artrit, myalgi och stelhet i leder)'],
             ['General', u'tr\xf6tthet']]],
           ['Common',
            [['Metabolism', u'anorexi'],
             ['Psychiatric', u'depression'],
             ['Nervous system', u'yrsel, karpaltunnelsyndrom'],
             ['GI', u'buksm\xe4rta. kr\xe4kningar, f\xf6rstoppning, dyspepsi, diarr\xe9'],
             ['Skin', u'utslag, alopeci'],
             ['Musculoskeletal', u'osteoporos, frakturer'],
             ['General', u'sm\xe4rta, perifert \xf6dem']]],
           ['Uncommon', [['Nervous system', u'somnolens'], ['General', u'asteni']]],
           ['Unknown',
            [['Blood',
              u'Hos patienter med avancerad br\xf6stcancer har trombocytopeni och leukopeni rapporterats i s\xe4llsynta fall. En tillf\xe4llig minskning av lymfocyter har observerats hos ungef\xe4r 20 % av de patienter som f\xe5tt exemestan, s\xe4rskilt hos patienter som tidigare haft lymfopeni. Medelv\xe4rdet av antalet lymfocyter hos dessa patienter f\xf6r\xe4ndrades emellertid inte signifikant \xf6ver tiden och ingen motsvarande \xf6kning av virusinfektioner observerades. Dessa effekter har inte observerats i studier hos patienter som behandlades f\xf6r tidig br\xf6stcancer.'],
             ['Hepato',
              u'F\xf6rh\xf6jning av leverfunktionsv\xe4rden inklusive enzymer, bilirubin och alkaliskt fosfatas har observerats. Tabellen nedan visar den rapporterade frekvensen av i f\xf6rv\xe4g specificerade biverkningar och sjukdomar i studien p\xe5 tidig br\xf6stcancer (IES), oberoende av orsak, hos patienter under behandling i studien och upp till 30 dagar efter avslutad behandling. Biverkningar samt sjukdomar Exemestan Tamoxifen (N = 2249) (N = 2279)'],
             ['Hepato',
              u'Eftersom biverkningar rapporteras frivilligt fr\xe5n en population av ok\xe4nd storlek, \xe4r det inte alltid m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt uppskatta frekvens eller s\xe4kerst\xe4lla ett kausalt samband till exponering av l\xe4kemedel.']]]],
 '_pages': [3, 5],
 u'_rank': 19,
 u'_type': u'LSFU'}