{'_data': [['Very common',
            [['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Blodvallaningar'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'\xd6kad svettning'],
             ['Musculoskeletal', u'Led- och muskuloskeletal sm\xe4rta*'],
             ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Metabolism', u'Anorexia'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Yrsel, karpaltunnelsyndrom'],
             ['GI', u'Buksm\xe4rta, kr\xe4kningar, f\xf6rstoppning, dyspepsi, diarr\xe9'],
             ['Skin', u'Hudutslag, h\xe5ravfall'],
             ['Musculoskeletal', u'Osteoporos, frakturer'],
             ['General', u'Sm\xe4rta, perifert \xf6dem']]],
           ['Uncommon', [['Nervous system', u'S\xf6mnighet'], ['General', u'Asteni']]],
           ['Unknown',
            [['Blood',
              u'Hos patienter med avancerad br\xf6stcancer har trombocytopeni och leukopeni rapporterats i s\xe4llsynta fall. En tillf\xe4llig minskning i lymfocyter har observerats hos ungef\xe4r 20 % av patienterna som st\xe5r p\xe5 exemestan, s\xe4rskilt hos patienter med redan existerande lymfopeni. De genomsnittliga lymfocytniv\xe5erna hos dessa patienter f\xf6r\xe4ndrades emellertid inte signifikant \xf6ver tiden och ingen motsvarande \xf6kning i virusinfektioner observerades. Dessa effekter observerades i studierna med patienter som behandlades f\xf6r tidig br\xf6stcancer.'],
             ['Hepato',
              u'F\xf6rh\xf6jda v\xe4rden f\xf6r parametrar i leverfunktionstester inklusive enzymer, bilirubin och alkalinfosfatas har observerats.'],
             ['Hepato',
              u'Eftersom biverkningar rapporteras frivilligt fr\xe5n en population av ok\xe4nd storlek, \xe4r det inte alltid m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt uppskatta frekvens eller att s\xe4kerst\xe4lla ett orsakssamband till exponering av l\xe4kemedel.']]]],
 '_pages': [3, 5],
 u'_rank': 19,
 u'_type': u'LSFU'}