{'_data': [['Common',
            [['Immune system', u'vanliga Hyperglykemi -- Mycket'],
             ['Immune system', u'vanliga Hyperurikemi Mindre --'],
             ['Immune system', u'vanliga Hypokalemi Vanliga -- Hyponatremi Mindre --'],
             ['Immune system', u'vanliga Psykiska st\xf6rningar Depression -- Mindre'],
             ['Immune system',
              u'vanliga Oro S\xe4llsynta -- S\xf6mnl\xf6shet/s\xf6mnst\xf6rningar -- Mindre'],
             ['Immune system', u'vanliga Hum\xf6rf\xf6r\xe4ndringar -- Mindre'],
             ['Immune system', u'vanliga F\xf6rvirring -- S\xe4llsynta'],
             ['Eye', u'vanliga Synneds\xe4ttning Mindre Mindre'],
             ['Eye', u'vanliga \xd6ron och balansorgan Tinnitus S\xe4llsynta Mindre'],
             ['Eye', u'vanliga Vertigo Mindre -- Mindre'],
             ['Eye', u'vanliga Hj\xe4rtat Hj\xe4rtklappning Mindre Vanliga'],
             ['Eye', u'vanliga Synkope S\xe4llsynta -- Takykardi Mindre --'],
             ['Eye',
              u'vanliga Arytmier (inklusive -- Mycket bradykardi, ventrikul\xe4r s\xe4llsynta takycardi, och f\xf6rmaksflimmer) Hj\xe4rtinfarkt -- Mycket'],
             ['Eye', u'vanliga Ortostatisk hypotoni Mindre --'],
             ['Eye', u'vanliga Vaskulit -- Mycket Ingen k\xe4nd'],
             ['Respiratory', u'vanliga Sm\xe4rta i svalg Mindre --'],
             ['Respiratory', u'vanliga Rinit -- Mindre'],
             ['Respiratory',
              u'vanliga Magtarmkanalen Magbesv\xe4r, \xf6vre buksm\xe4rta Mindre Vanliga Mindre'],
             ['Respiratory', u'vanliga F\xf6r\xe4ndrade tarmvanor -- Mindre'],
             ['Respiratory', u'vanliga F\xf6rstoppning Mindre --'],
             ['Respiratory', u'vanliga Diarr\xe9 Mindre Mindre'],
             ['Respiratory', u'vanliga Muntorrhet Mindre Mindre'],
             ['Respiratory', u'vanliga Dyspepsi -- Mindre'],
             ['Respiratory', u'vanliga Gastrit -- Mycket'],
             ['Respiratory', u'vanliga Pankreatit -- Mycket'],
             ['Respiratory',
              u'vanliga Lever och gallv\xe4gar F\xf6rh\xf6jda leverenzymv\xe4rden, -- Mycket Ingen k\xe4nd inkluderande \xf6kning av s\xe4llsynta* frekvens serumbilirubin Hepatit -- Mycket'],
             ['Skin', u'vanliga Erythema multiforme -- Mycket'],
             ['Skin', u'vanliga Hyperhidros S\xe4llsynta Mindre'],
             ['Skin', u'vanliga Fotosensitivitetsreaktion -- Mycket'],
             ['Skin', u'frekvens Purpura -- Mindre'],
             ['Skin', u'vanliga Utslag Mindre Mindre Ingen k\xe4nd'],
             ['Skin', u'vanliga vanliga frekvens Missf\xe4rgning av huden -- Mindre'],
             ['Skin',
              u'vanliga Urtikaria och andra former -- Mycket av hudutslag s\xe4llsynta Exfoliativ dermatit -- Mycket'],
             ['Skin', u'vanliga Svullna leder Vanliga Muskelkramp S\xe4llsynta Mindre'],
             ['Skin', u'vanliga Myalgi -- Mindre Ingen k\xe4nd'],
             ['Skin', u'frekvens Ankelsvullnad -- Vanliga Tyngdk\xe4nsla S\xe4llsynta --'],
             ['Renal', u'vanliga Nokturi -- Mindre'],
             ['Renal', u'vanliga Pollakisuri S\xe4llsynta Mindre'],
             ['Renal',
              u'vanliga Polyuri S\xe4llsynta -- Njursvikt och nedsatt -- -- Ingen k\xe4nd njurfunktion frekvens Reproduktionsorgan Impotens -- Mindre och br\xf6stk\xf6rtel vanliga Erektil dysfunktion S\xe4llsynta -- Gynekomasti -- Mindre'],
             ['Renal',
              u'vanliga Allm\xe4nna symtom Asteni Vanliga Mindre och/eller symtom vid vanliga administreringsst\xe4llet Obehag, sjukdomsk\xe4nsla -- Mindre'],
             ['Renal', u'vanliga Tr\xf6tthet Vanliga Vanliga Mindre'],
             ['Renal',
              u'vanliga Ansikts\xf6dem Vanliga -- Rodnad, v\xe4rmevallningar Vanliga -- Icke kardiell br\xf6stsm\xe4rta -- Mindre'],
             ['Renal',
              u'vanliga \xd6dem Vanliga Vanliga Perifert \xf6dem Vanliga -- Sm\xe4rta -- Mindre'],
             ['Renal',
              u'vanliga Pitting\xf6dem Vanliga -- Unders\xf6kningar Serumkalium \xf6kade -- -- Ingen k\xe4nd frekvens Vikt\xf6kning -- Mindre'],
             ['Renal', u'vanliga Viktminskning -- Mindre'],
             ['Renal', u'vanliga']]],
           ['Rare',
            [['Immune system',
              u'frekvens Metabolism och Anorexi Mindre -- nutrition vanliga Hyperkalcemi Mindre --'],
             ['Immune system', u's\xe4llsynta Hyperlipidemi Mindre --'],
             ['Eye',
              u's\xe4llsynta Blodk\xe4rl Rodnad -- Vanliga Hypotoni S\xe4llsynta Mindre'],
             ['Eye', u'frekvens'],
             ['Respiratory', u's\xe4llsynta Gingivalhyperplasi -- Mycket'],
             ['Respiratory', u's\xe4llsynta Illam\xe5ende Mindre Vanliga'],
             ['Respiratory', u's\xe4llsynta Kr\xe4kning -- Mindre'],
             ['Respiratory',
              u's\xe4llsynta Intrahepatisk kolestas, -- Mycket gulsot s\xe4llsynta'],
             ['Skin', u'frekvens Erythema Mindre --'],
             ['Skin', u's\xe4llsynta Exantem S\xe4llsynta Mindre'],
             ['Skin', u's\xe4llsynta Kl\xe5da S\xe4llsynta Mindre Ingen k\xe4nd'],
             ['Skin', u's\xe4llsynta Stevens-Johnson syndrom -- Mycket'],
             ['Skin', u's\xe4llsynta Quincke-\xf6dem -- Mycket'],
             ['Skin',
              u's\xe4llsynta Muskuloskeletala Artralgi Mindre Mindre systemet och bindv\xe4v vanliga vanliga Ryggsm\xe4rta Mindre Mindre']]],
           ['Unknown',
            [['Respiratory',
              u'br\xf6stkorg och vanliga s\xe4llsynta vanliga mediastinum Dyspne -- Mindre'],
             ['Skin', u'vanliga Angioneurotiskt \xf6dem -- Mycket Ingen k\xe4nd'],
             ['Renal', u'frekvens Urineringsst\xf6rningar Mindre']]]],
 '_pages': [6, 12],
 u'_rank': 63,
 u'_type': u'LSFU'}