{'_data': [['Common',
            [['Metabolism', u'Dehydrering'],
             ['Metabolism', u'Hypovolemi'],
<<<<<<< HEAD
             ['Nervous system', u'Yrsel'],
=======
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Hypotension'],
             ['Vascular', u'Hypertension'],
             ['GI', u'Buksm\xe4rta'],
             ['Skin', u'Utslag (inklusive makul\xe4ra,  papul\xf6sa, erytemat\xf6sa)'],
             ['Skin', u'Kl\xe5da'],
<<<<<<< HEAD
             ['Skin', u'Exfoliation'],
             ['General', u'Perifert \xf6dem'],
             ['General', u'Asteni']]],
=======
             ['Skin', u'Exfoliation']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Infections', u'Influensasyndrom'],
             ['Infections', u'Furunkel'],
             ['Blood', u'Anemi'],
             ['Blood', u'Leukocytos'],
             ['Blood', u'Eosinofili'],
             ['Metabolism', u'Hypoglykemi'],
             ['Metabolism', u'Hyponatremi'],
             ['Metabolism', u'Hyperglykemi'],
             ['Metabolism', u'Hypervolemi'],
             ['Metabolism', u'Aptitl\xf6shet'],
             ['Metabolism', u'Hypokloremi'],
             ['Metabolism', u'Hypomagnesemi'],
             ['Metabolism', u'Hypoproteinemi'],
             ['Psychiatric', u'Onormala tankar'],
             ['Psychiatric', u'\xc5ngest'],
             ['Psychiatric', u'Nervositet'],
             ['Nervous system', u'Hyperkinesi'],
             ['Nervous system', u'Parestesi'],
             ['Nervous system', u'Ageusi'],
             ['Cardiac', u'Kardiovaskul\xe4ra rubbningar'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Ortostatisk  hypotension'],
<<<<<<< HEAD
             ['Respiratory', u'Lung\xf6dem'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Respiratory', u'Hosta'],
             ['Respiratory', u'Hicka'],
=======
             ['Vascular', u'Hosta'],
             ['Vascular', u'Hicka'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Ileus'],
             ['GI', u'Peritonit'],
             ['GI', u'Blodigt peritonealdialysat'],
             ['GI', u'Diarr\xe9'],
             ['GI', u'Mags\xe5r'],
             ['GI', u'Gastrit'],
             ['GI', u'Kr\xe4kningar'],
             ['GI', u'F\xf6rstoppning'],
             ['GI', u'Dyspepsi'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Muntorrhet'],
             ['GI', u'Gasbildning'],
             ['Skin', u'Urtikaria'],
             ['Skin', u'Bull\xf6s dermatit'],
             ['Skin', u'Psoriasis'],
             ['Skin', u'Huds\xe5r'],
             ['Skin', u'Eksem'],
             ['Skin', u'Nagelproblem'],
             ['Skin', u'Torr hud'],
             ['Skin', u'Hudmissf\xe4rgning'],
<<<<<<< HEAD
             ['Musculoskeletal', u'V\xe4rk i skelettet'],
             ['Musculoskeletal', u'Muskelspasmer'],
             ['Musculoskeletal', u'Myalgi'],
             ['Musculoskeletal', u'Nackv\xe4rk'],
             ['Renal', u'V\xe4rk i njurarna'],
             ['General', u'Br\xf6stsm\xe4rtor'],
             ['General', u'Ansikts\xf6dem'],
             ['General', u'\xd6dem'],
             ['General', u'V\xe4rk'],
=======
             ['Skin', u'Myalgi'],
             ['Skin', u'Nackv\xe4rk'],
             ['Renal', u'V\xe4rk i njurarna'],
             ['Renal', u'Ansikts\xf6dem'],
             ['Renal', u'\xd6dem'],
             ['Renal', u'V\xe4rk'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Investigations', u'F\xf6rh\xf6jt ALAT'],
             ['Investigations', u'F\xf6rh\xf6jt ASAT'],
             ['Investigations', u'F\xf6rh\xf6jda alkaliska fosfataser'],
             ['Investigations', u'Onormala resultat vid kontroll  av leverns funktion'],
             ['Investigations', u'Viktminskning'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Blood', u'Leukopeni'],
             ['Immune system', u'Vaskulit'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Hypoglykemisk chock'],
             ['Metabolism', u'Rubbad v\xe4tskebalans'],
             ['Nervous system', u'Hypoglykemisk koma'],
             ['Nervous system', u'Br\xe4nnande k\xe4nsla'],
             ['Eye', u'Suddig syn'],
<<<<<<< HEAD
             ['Respiratory', u'Bronkospasm'],
=======
             ['Vascular', u'Bronkospasm'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Ascites'],
             ['GI', u'Ljumskbr\xe5ck'],
             ['GI', u'Magbesv\xe4r'],
             ['Skin', u'Toxisk epidermal nekrolys'],
             ['Skin', u'Erythema multiforme'],
             ['Skin', u'Angio\xf6dem'],
             ['Skin', u'Utbredd urtikaria'],
             ['Skin', u'Toxiska hudutslag'],
             ['Skin', u'Periorbitalt \xf6dem'],
             ['Skin', u'Dermatit (d\xe4ribland allergisk  och kontakt-)'],
             ['Skin', u'Erythema'],
             ['Skin', u'Bl\xe5sor'],
<<<<<<< HEAD
             ['Musculoskeletal', u'Artralgi'],
             ['Musculoskeletal', u'Ryggv\xe4rk'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta'],
             ['General', u'Feber'],
             ['General', u'Frossa'],
             ['General', u'Sjukdomsk\xe4nsla'],
             ['General', u'Erytem runt katetern'],
             ['General', u'Inflammation runt katetern'],
             ['General',
              u'Infusionsrelaterad reaktion  (exempelvis sm\xe4rta vid infusionsst\xe4llet, sm\xe4rta vid instillationsst\xe4llet)']]]],
 '_pages': [6, 9],
 u'_rank': 105,
=======
             ['Skin', u'Artralgi'],
             ['Skin', u'Ryggv\xe4rk'],
             ['Skin', u'Muskuloskeletal sm\xe4rta'],
             ['Renal', u'Feber'],
             ['Renal', u'Frossa'],
             ['Renal', u'Sjukdomsk\xe4nsla'],
             ['Renal', u'Erytem runt katetern'],
             ['Renal', u'Inflammation runt katetern'],
             ['Renal',
              u'Infusionsrelaterad reaktion  (exempelvis sm\xe4rta vid infusionsst\xe4llet, sm\xe4rta vid instillationsst\xe4llet)']]]],
 '_pages': [6, 9],
 u'_rank': 97,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}