{'_data': [['Common',
            [['GI', u'buksm\xe4rta, diarr\xe9, flatulens'],
             ['Investigations', u'F\xf6rh\xf6jda v\xe4rden av ALAT  och/eller ASAT'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Musculoskeletal', u'myalgi']]],
           ['Uncommon',
            [['Investigations',
              u'F\xf6rh\xf6jda v\xe4rden av ALAT  och/eller ASAT, \xf6kat CPK, f\xf6rh\xf6jda v\xe4rden av \u03b3-glutamyltransferas, onormalt leverfunktionstest'],
             ['Respiratory', u'hosta'],
             ['GI', u'dyspepsi, gastroesofagal  reflux, illam\xe5ende'],
             ['Musculoskeletal', u'artralgi, muskelkramper,  nacksm\xe4rta'],
             ['Metabolism', u'minskad aptit'],
             ['Vascular', u'blodvallning, hypertoni'],
             ['Nervous system', u'parestesi'],
             ['GI', u'torr mun, gastrit'],
             ['Skin', u'kl\xe5da, utslag, urtikaria'],
             ['Musculoskeletal', u'ryggv\xe4rk, muskelsvaghet,  sm\xe4rta i extremiteter'],
             ['General', u'asteni, perifert \xf6dem']]]],
 '_pages': [5, 7],
 u'_rank': 15,
 u'_type': u'TSFU'}