{'_data': [['Common',
            [['Infections', u' Nasofaryngit'],
             ['Nervous system', u'Huvudv\xe4rk , parestesi'],
             ['Eye', u'\xd6kat'],
             ['Ear', u'Tinnitus,'],
             ['Cardiac', u'Takykardi, palpitationer,'],
             ['Vascular', u'Rodnad,'],
             ['Respiratory', u'Dyspn\xe9,'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'Pruritus,'],
             ['General', u'Frossa, pyrexi, k\xf6ldk\xe4nsla'],
             ['Nervous system',
              u'Yrsel, somnolens, hypoestesi, br\xe4nnande k\xe4nsla, letargi, synkope'],
             ['Eye', u't\xe5rfl\xf6de'],
             ['Ear', u'vertigo'],
             ['Cardiac', u'bradykardi'],
             ['Vascular',
              u'blodtrycksh\xf6jning , blekhet, blodtrycksfall, v\xe4rmevallningar'],
             ['Respiratory',
              u'n\xe4st\xe4ppa, tr\xe5nghetsk\xe4nsla i svalget, v\xe4sande andning, hosta, f\xf6rv\xe4rrad dyspn\xe9'],
             ['GI',
              u'Buksm\xe4rta, sm\xe4rta i \xf6vre delen av buken, magbesv\xe4r, oral hypoestesi, diarr\xe9'],
             ['Skin',
              u'urtikaria, huduslag, erytem, generaliserad kl\xe5da, angio-neurotiskt \xf6dem, svullnad i ansiktet, makulopapyl\xf6st utslag'],
             ['Musculoskeletal',
              u'Sm\xe4rta i armar eller ben, myalgi, ryggsm\xe4rta, muskelkramp, artralgi, muskelsp\xe4nning, muskuloskeletal stelhet'],
             ['General',
              u'Tr\xf6tthet, br\xf6stbesv\xe4r, v\xe4rmek\xe4nsla, perifera \xf6dem, sm\xe4rta, asteni, br\xf6stsm\xe4rta, ansikts\xf6dem, hypertermi']]],
           ['Uncommon',
            [['Infections', u'Rinit'],
             ['Nervous system', u'Hyperestesi, tremor'],
             ['Eye', u'\xd6gonkl\xe5da, okul\xe4r hyperemi'],
             ['Ear', u'\xd6ronsvullnad, \xf6ronsm\xe4rta'],
             ['Cardiac', u'Sinusbradykardi '],
             ['Vascular', u'Perifer kyla'],
             ['Respiratory',
              u'Bronkialspasm, faryngolaryngeal sm\xe4rta, rinorr\xe9, takypn\xe9, t\xe4ppt i \xf6vre luftv\xe4garna'],
             ['GI', u'Dyspepsi, dysfagi'],
             ['Skin',
              u'Livedo reticularis, erytemat\xf6st hudutslag, hudutslag med kl\xe5da, hudmissf\xe4rgning, hudbesv\xe4r'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta'],
             ['General',
              u'V\xe4rme-och k\xf6ld-k\xe4nsla, influensa-liknande sjukdom, sm\xe4rta vid infusionsst\xe4llet, reaktion vid infusionsst\xe4llet, trombos vid injektionsst\xe4llet, malaise, \xf6dem']]],
           ['Unknown',
            [['Immune system', u'Anafylaktoid reaktion'],
             ['Respiratory', u'hypoxi'],
             ['Skin', u'Leukocytoklastisk vaskulit'],
             ['Investigations', u'S\xe4nkt syrgasm\xe4ttnad']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 7],
 u'_rank': 35,
 u'_type': u'MSFU'}