{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk, yrsel'], ['GI', u'f\xf6rstoppning, diarr\xe9']]],
           ['Uncommon',
            [['Metabolism', u'aptitl\xf6shet'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning, magobehag eller distension, flatulens, muntorrhet, dysgeusi'],
             ['Skin', u'utslag, pruritus, urtikatia'],
             ['General', u'tr\xf6tthet Biverkningar \u2013 ok\xe4nt orsakssamband']]],
           ['Rare',
            [['General',
              u'fall av gynekomasti har rapporterats, men i kontrollerade kliniska pr\xf6vningar var incidensen inte h\xf6gre \xe4n vad som s\xe5gs med placebo.']]],
           ['Very rare',
            [['Blood', u'trombocytopeni, leukopeni, agranulocytos, pancytopeni, neutropeni'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner (angioneurotiskt \xf6dem, anafylaxi, bronkospasm)'],
             ['Psychiatric',
              u'reversibla psykiska st\xf6rningar, s\xe5som hallucinationer, desorientering, f\xf6rvirring, \xe5ngesttillst\xe5nd, upphetsning, depression'],
             ['Nervous system',
              u'parestesi, somnolens, s\xf6mnl\xf6shet, grand mal anfall (s\xe4rskilt hos patienter med nedsatt njurfunktion)'],
             ['Cardiac',
              u'AV-block vid intraven\xf6s administrering av H2-receptorantagonister'],
             ['Respiratory', u'Andn\xf6d, interstitiell pneumoni ibland d\xf6dlig'],
             ['Hepato',
              u'f\xf6rh\xf6jda v\xe4rden av leverenzymer (transaminaser, gamma GT, alkalinfosfatas, bilirubin), intrahepatisk kolestas (synligt tecken: gulsot), hepatit'],
             ['Skin',
              u'alopeci, allvarliga hudreaktioner (Stevens Johnson Syndrom/toxisk epidermal nekrolys, ibland d\xf6dliga)'],
             ['Musculoskeletal', u'artralgi, muskelkramper'],
             ['Reproductive system', u'impotens, minskad sexualdrift']]]],
 '_pages': [5, 6],
 u'_rank': 17,
 u'_type': u'LSFU'}