{'_data': [['Very common',
            [['Psychiatric', u'depression'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'v\xe4rmevallningar'],
             ['Skin', u'svettning hudutslag, kl\xe5da'],
             ['Reproductive system', u'uterin'],
             ['General', u'tr\xf6tthet, \xf6dem'],
             ['Metabolism', u'aptitl\xf6shet'],
             ['Psychiatric', u's\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Ear', u'vertigo'],
             ['Vascular', u'tromboemboli-ska h\xe4ndelser'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'f\xf6rstoppning'],
             ['Hepato', u'transaminas'],
             ['Reproductive system', u'endometrie-hypertrofi'],
             ['General', u'vikt\xf6kning']]],
           ['Common',
            [['GI', u'illam\xe5ende, kr\xe4kning'],
             ['Reproductive system', u'bl\xf6dning, leukorr\xe9']]],
           ['Rare',
            [['Eye', u'\xf6verg\xe5ende grumling av'],
             ['Hepato', u'stegring'],
             ['Reproductive system', u'endometrie-polyper']]],
           ['Very rare',
            [['Neoplasms', u'endometriecancer'],
             ['Eye', u'hornhinnan'],
             ['Hepato', u'gulsot'],
             ['Skin', u'h\xe5ravfall'],
             ['Reproductive system', u'endometrie-hyperplasi']]]],
 '_note': u' ANOMALI in Headers ?MSFU',
 '_pages': [3, 4],
 u'_rank': 26,
 u'_type': u'MSFU'}