{'_data': [['Common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI',
              u'Illam\xe5ende, nedsatt aptit, magknip, \xf6verg\xe5ende smakf\xf6r\xe4ndringar (metallsmak, bitter smak)']]],
           ['Uncommon', [['GI', u'Kr\xe4kningar, diarr\xe9']]],
           ['Rare',
            [['Blood', u'Reversibel leukopeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Nervous system', u'Perifer neuropati'],
             ['GI', u'Stomatit'],
             ['Hepato', u'Onormala leverfunktionsv\xe4rden, kolestatisk hepatit, gulsot'],
             ['Skin', u'Exantem, kl\xe5da, utslag'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'M\xf6rkf\xe4rgning av urinen'],
             ['General',
              u'Feber Allergiska reaktioner (exanthem, urtikaria) kan f\xf6rekomma i ett syndromliknande tillst\xe5nd tillsammans med feber och sm\xe4rtsam ledsvullnad.']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk chock'],
             ['Metabolism', u'Antabuseffekt'],
             ['Nervous system', u'Ataxi, konvulsion']]]],
 '_pages': [2, 3],
 u'_rank': 15,
 u'_type': u'LSFU'}