{'_data': [['Very common',
            [['GI', u'Illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jda niv\xe5er av leverenzymer (ALAT,']]],
           ['Common',
            [['Infections', u'Urinv\xe4gsinfektioner'],
             ['Metabolism', u'Aptitl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Skin', u'Hudutslag']]],
           ['Uncommon',
            [['Reproductive system',
              u'Vaginal moniliasis, vaginal flytning, vaginal  bl\xf6dning']]]],
 '_pages': [4, 5],
 u'_rank': 7,
 u'_type': u'TSFU'}