{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk.'],
             ['Ear', u'tinnitus*'],
             ['Vascular', u'rodnad.'],
             ['General', u'perifert \xf6dem']]],
           ['Common', [['Cardiac', u'angina pectoris **']]],
           ['Uncommon',
            [['Nervous system', u'parestesier, yrsel, synkope, rastl\xf6shet'],
             ['Cardiac', u'palpitationer, takykardi, hypotoni'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning, diarr\xe9, f\xf6rstoppning, buksm\xe4rta, gingival hyperplasi och gingivit.'],
             ['Skin',
              u'hud- och \xf6verk\xe4nslighetsreaktioner s\xe5som kl\xe5da, urtikaria, exantem och fotosensitivitet.'],
             ['Renal', u'pollakisuri'],
             ['General', u'vikt\xf6kning, tr\xf6tthet, svettning']]],
           ['Rare', [['Skin', u'Leukocytoklastisk vaskulit.']]],
           ['Very rare',
            [['Cardiac', u'myokardinfarkt'],
             ['Hepato', u'leverfunktionst\xf6rningar (transaminasf\xf6rh\xf6jning)'],
             ['Skin', u'exfoliativ dermatit'],
             ['Reproductive system', u'impotens, gynekomasti, menorragi'],
<<<<<<< HEAD
             ['General', u'angio\xf6dem, feber']]],
=======
             ['General',
              u'angio\xf6dem, feber * S\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js eller n\xe4r h\xf6ga doser administreras. Vanligtvis avtar dessa effekter vid fortsatt behandling. ** S\xe4rskilt i b\xf6rjan av behandlingen kan angina pectoris-attacker f\xf6rekomma, eller hos patienter med befintlig angina pectoris kan det vara en \xf6kning i frekvens, duration och sv\xe5righetsgrad av attackerna.']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown', [['Musculoskeletal', u'myalgi, artralgi, tremor']]]],
 '_pages': [4, 5],
 u'_rank': 19,
 u'_type': u'LSFU'}