{'_data': [['Very common',
            [['Nervous system',
              u'Huvudv\xe4rk (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar denna effekt vid fortsatt behandling).'],
             ['Ear',
              u'Tinnitus (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar denna effekt vid fortsatt behandling).'],
             ['Vascular',
              u'Rodnad (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar denna effekt vid fortsatt behandling).'],
             ['General', u'Perifert \xf6dem (graden av ankelsvullnad \xe4r dosrelaterad).']]],
           ['Common',
            [['Cardiac',
              u'Angina pectoris (s\xe4rskilt i b\xf6rjan av behandlingen); patienter som tidigare haft angina pectoris kan drabbas av en \xf6kning i frekvens, duration och sv\xe5righetsgrad p\xe5 attackerna.']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel, parestesier, tremor, rastl\xf6shet.'],
             ['Cardiac', u'Palpitationer, takykardi.'],
             ['Vascular', u'Hypotoni, synkope'],
             ['Respiratory', u'Dyspn\xe9.'],
             ['GI',
              u'Gastrointestinala besv\xe4r (t ex illam\xe5ende, buksm\xe4rtor, kr\xe4kning, diarr\xe9, f\xf6rstoppning), gingival hyperplasi och gingivit.'],
             ['Skin',
              u'Hud- och \xf6verk\xe4nslighetsreaktioner s\xe5som hudutslag, kl\xe5da, urtikaria, exantem och fotosensitivitet.'],
             ['Musculoskeletal', u'Myalgi, artralgi.'],
             ['Renal', u'Pollakisuri.'],
             ['General', u'Tr\xf6tthet, vikt\xf6kning, svettning.']]],
           ['Rare',
            [['Skin', u'Leucocytoclastic vaskulit'],
             ['Reproductive system', u'Erektionsproblem/ sexuell dysfunktion']]],
           ['Very rare',
            [['Cardiac', u'Hj\xe4rtinfarkt.'],
             ['Hepato',
              u'Leverfunktionst\xf6rningar, f\xf6rh\xf6jda leverenzymer (t.ex. transaminasf\xf6rh\xf6jning).'],
             ['Skin', u'Exfoliativ dermatit.'],
             ['Reproductive system', u'Gynekomasti, menorragi.'],
             ['General', u'\xd6verk\xe4nslighetsreaktioner t.ex. angio\xf6dem, feber.']]]],
 '_pages': [4, 5],
 u'_rank': 21,
 u'_type': u'LSFU'}