{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Ear',
              u'Tinnitus (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js eller n\xe4r h\xf6ga doser intas). Vanligtvis avtar dessa effekter vid fortsatt behandling.']]],
           ['Common',
            [['Cardiac',
              u'S\xe4rskilt i b\xf6rjan av behandlingen kan angina pectoris attacker f\xf6rekomma, eller hos patienter med pre-existerande angina pectoris kan frekvensen, durationen eller sv\xe5righetsgraden av attackerna \xf6ka.'],
             ['Vascular', u'Rodnad'],
             ['General', u'Perifert \xf6dem']]],
           ['Uncommon',
            [['Nervous system', u'Parestesi, yrsel, rastl\xf6shet.'],
             ['Cardiac', u'Palpitationer, takykardi, hypotension.'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Iillam\xe5ende, magsm\xe4rtor, diarr\xe9, f\xf6rstoppning'],
             ['Skin', u'Utslag, kl\xe5da,'],
             ['Musculoskeletal', u'Tremor'],
             ['General', u'Tr\xf6tthet, vikt\xf6kning, svettning.']]],
           ['Rare',
            [['Vascular', u'Synkop\xe9'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'N\xe4sselutslag'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Reproductive system', u'Impotens/sexuell dysfunktion']]],
           ['Very rare',
            [['Cardiac', u'Hj\xe4rtinfarkt'],
             ['GI', u'Gingival hyperplasi, gingivit'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymniv\xe5er'],
             ['Skin',
              u'Exfoliativ dermatit, ljusk\xe4nslighetsreaktioner, leukocytoklastisk vaskulit'],
             ['Renal', u'Pollakisuri'],
             ['Reproductive system', u'Gynekomasti, menorragi'],
             ['General', u'\xd6verk\xe4nslighetsreaktioner t.ex. angio\xf6dem, feber.']]]],
 '_pages': [4, 5],
 u'_rank': 24,
 u'_type': u'LSFU'}