{'_data': [['Very common',
            [['Nervous system',
              u'eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar dessa effekter vid fortsatt behandling). Tinnitus (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js'],
             ['Ear',
              u'eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar dessa effekter vid fortsatt behandling).'],
             ['Hepato',
              u'Rodnad (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen h\xf6js'],
             ['Skin',
              u'eller n\xe4r h\xf6ga doser intas. Vanligtvis avtar dessa effekter vid fortsatt behandling).']]],
           ['Common',
            [['Ear',
              u'Angina Pectoris (S\xe4rskilt i b\xf6rjan av behandlingen kan attacker av angina pectoris upptr\xe4da.'],
             ['Cardiac',
              u'Patienter som tidigare haft angina pectoris kan drabbas av en \xf6kning i frekvens, duration och sv\xe5righetsgrad p\xe5 attackerna..)'],
             ['General', u'Perifert \xf6dem (graden av']]],
           ['Uncommon',
            [['Ear', u'Tackykardi, palpitationer, hypertension'],
             ['Respiratory', u'Dyspne\xb4 Illam\xe5ende, kr\xe4kningar,'],
             ['GI', u'diarr\xe9, f\xf6rstoppning'],
             ['Hepato',
              u'Hud-och \xf6verk\xe4nslighetsreaktioner s\xe5som kl\xe5da, urtikaria, exantem och fotosensitivitet har'],
             ['Skin', u'observerats Gingival hyperplasi och gingivit'],
             ['Musculoskeletal', u'Artralgi, myalgi, tremor'],
             ['Renal', u'Pollakisuri'],
             ['General', u'Vikt\xf6kning, svettningar']]],
           ['Rare', [['Vascular', u'Leukocytoklastisk vasculit']]],
           ['Very rare',
            [['Ear', u'Myocardiell infarkt'],
             ['Hepato',
              u'leverfunktionst\xf6rningar (transaminasf\xf6rh\xf6jning) Exfoliativ dermatit'],
             ['Reproductive system', u'Impotens, gynekomasti, menorragi'],
             ['General', u'Angio\xf6dem, feber']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 5],
 u'_rank': 20,
 u'_type': u'MSFU'}