{'_data': [['Very common',
            [['Nervous system',
              u'Huvudv\xe4rk (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen \xf6kas eller n\xe4r h\xf6ga doser ges). Denna effekt klingar vanligtvis av vid fortsatt behandling.'],
             ['Ear',
              u'Tinnitus (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen \xf6kas eller n\xe4r h\xf6ga doser ges). Denna effekt klingar vanligtvis av vid fortsatt behandling.'],
             ['Skin',
              u'Ansiktsrodnad (s\xe4rskilt i b\xf6rjan av behandlingen, n\xe4r dosen \xf6kas eller n\xe4r h\xf6ga doser ges). Denna effekt klingar vanligtvis av vid fortsatt behandling.']]],
           ['Common',
            [['Cardiac',
              u'S\xe4rskilt i b\xf6rjan av behandlingen kan angina pectoris-attacker uppkomma. Hos patienter med redan existerande angina kan det ske en \xf6kning i attackernas frekvens, duration och allvarlighetsgrad.'],
             ['General', u'Perifert \xf6dem (graden av ankelsvullnad \xe4r dosrelaterad)']]],
           ['Uncommon',
            [['Cardiac', u'Palpitationer, takykardi, hypotension.'],
             ['Nervous system', u'Parestesi, yrsel, tr\xf6tthet, synkope, rastl\xf6shet'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9, f\xf6rstoppning'],
             ['Renal', u'Pollakisuri (\xf6kad urineringsfrekvens)'],
             ['Skin',
              u'Hud- och \xf6verk\xe4nslighetsreaktioner som pruritus, urtikaria, exantem, fotosensitivitet, gingival hyperplasi och gingivit'],
             ['Musculoskeletal', u'Myalgi, artralgi, tremor'],
             ['General', u'Vikt\xf6kning, svettning']]],
           ['Rare', [['Vascular', u'Leukocytoklastisk vaskulit 2011-04-29']]],
           ['Very rare',
            [['Cardiac', u'Myokardinfarkt'],
             ['Skin', u'Exfoliativ dermatit'],
             ['General', u'Angio\xf6dem, feber'],
             ['Hepato', u'St\xf6rningar i leverfunktionen (f\xf6rh\xf6jda transaminaser)'],
             ['Reproductive system', u'Erektionsst\xf6rningar, gynekomasti, menorragi']]]],
 '_pages': [4, 5],
 u'_rank': 19,
 u'_type': u'LSFU'}