{'_data': [['Very common',
            [['Reproductive system', u'Sm\xe4rta/\xf6mhet i br\xf6sten, vaginal-bl\xf6dning']]],
           ['Common',
            [['Infections', u'Genital candida-infektion, vaginit'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['Psychiatric', u'Depression, f\xf6rv\xe4rrad depression'],
             ['Nervous system', u'Huvudv\xe4rk Migr\xe4n, f\xf6rv\xe4rrad migr\xe4n'],
             ['GI', u'Illam\xe5ende Sm\xe4rtor, sp\xe4ndhet, obehagsk\xe4nslor i buken'],
             ['Musculoskeletal', u'Ryggsm\xe4rtor, benkramper'],
             ['Reproductive system',
              u'Br\xf6stf\xf6rstoring/\xf6de m, uterusmyom, f\xf6rv\xe4rrning/\xe5terko mmande uterusmyom'],
             ['General', u'Perifera \xf6dem'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Neoplasms', u'Br\xf6stcancer, se nedan*'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'Nervositet'],
             ['Vascular', u'Ytlig tromboflebit'],
             ['Skin', u'Alopecia, hirsutism, acne, kl\xe5da, urtikaria']]],
           ['Rare', [['Vascular', u'Lungemboli Djup ventrombos']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 9],
 u'_rank': 16,
 u'_type': u'MSFU'}