{'_data': [['Very common',
            [['Metabolism', u'Hyperkolesterolemi'],
             ['Vascular', u'Blodvallningar'],
             ['Skin', u'\xd6kad svettning'],
             ['Musculoskeletal', u'Artralgi'],
             ['General', u'Tr\xf6tthet (inklusive asteni, sjukdomsk\xe4nsla)']]],
           ['Common',
            [['Metabolism', u'Anorexi, \xf6kad aptit'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Vascular', u'Hypertoni'],
             ['GI',
              u'Vanliga Illam\xe5ende, dyspepsi , f\xf6rstoppning, buksm\xe4rta, diarr\xe9, kr\xe4kning'],
             ['Skin',
              u'Alopeci, hudutslag (inklusive erytemiskt, makulopapul\xf6st, psoriasisliknande och vesikul\xe4rt utslag), torr hud'],
             ['Musculoskeletal', u'Vanliga Myalgi, skelettsm\xe4rta , osteoporos, frakturer'],
             ['Reproductive system', u'Vaginalbl\xf6dning'],
             ['General', u'Perifert \xf6dem'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'Urinv\xe4gsinfektion'],
             ['Neoplasms', u'Tum\xf6rsm\xe4rta'],
             ['Blood', u'Leukopeni'],
             ['Psychiatric', u'\xc5ngest /inklusive nervositet), irritabilitet'],
             ['Nervous system',
              u'S\xf6mnighet, s\xf6mnl\xf6shet, minnesf\xf6rs\xe4mring, dysestesi (inklusive parestesi, hypoestesi), smakf\xf6r\xe4ndring, cerebrovaskul\xe4r sjukdom'],
             ['Eye', u'Katarakt, \xf6gonirritation, dimsyn'],
             ['Cardiac',
              u'Mindre vanliga Palpitationer takykardi, ischemisk hj\xe4rtsjukdom (inklusive debut av eller f\xf6rv\xe4rrad k\xe4rlkramp, k\xe4rlkramp som kr\xe4ver kirurgi, hj\xe4rtinfarkt och ischemi)'],
             ['Vascular', u'Tromboflebit (inklusive ytlig och djup tromboflebit)'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Muntorrhet, stomatit'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer'],
             ['Skin', u'Kl\xe5da, urtikaria'],
             ['Musculoskeletal', u'Artrit'],
             ['Renal', u'\xd6kad miktionsfrekvens'],
             ['Reproductive system', u'Vaginalflytning, vaginaltorrhet, br\xf6stsm\xe4rta'],
             ['General', u'Generaliserat \xf6dem, torra slemhinnor, t\xf6rst, feber'],
             ['Investigations',
<<<<<<< HEAD
              u'Viktminskning F\xf6r vissa biverkningar har p\xe5tagliga skillnader i den rapporterade frekvensen observerats vid adjuvant behandling. F\xf6ljande tabeller inneh\xe5ller information om signifikanta skillnader vid monoterapi med Femar kontra tamoxifen och vid sekventiell behandling med Femar och tamoxifen']]],
           ['Rare', [['Vascular', u'Lungemboli, arteriell trombos, cerebrovaskul\xe4r infarkt']]],
           ['Unknown',
            [['Other',
              u's\xe5som bensk\xf6rhet och/eller benfrakturer och kardiovaskul\xe4ra biverkningar (inklusive cerebrovaskul\xe4ra och tromboemboliska). F\xf6rekomsten av dessa biverkningar anges i tabell 1. Biverkningar i tabellform Biverkningsfrekvenserna f\xf6r Femar baseras huvudsakligen p\xe5 data fr\xe5n kliniska studier. L\xe4kemedelsbiverkningarna i tabell 1 har rapporterats vid kliniska pr\xf6vningar och efter f\xf6rs\xe4ljningsgodk\xe4nnande av Femar.'],
=======
              u'Viktminskning Biverkningar som enbart rapporterats vid metastaserad sjukdom. F\xf6r vissa biverkningar har p\xe5tagliga skillnader i den rapporterade frekvensen observerats vid adjuvant behandling. F\xf6ljande tabeller inneh\xe5ller information om signifikanta skillnader vid monoterapi med Femar kontra tamoxifen och vid sekventiell behandling med Femar och tamoxifen: Tabell 2 Adjuvant behandling med Femar i monoterapi mot tamoxifen i monoterapi biverkningar med signifikanta skillnader Femar, incidens Tamoxifen, incidens Benfraktur 10,1% (13,8%) 7,1% (10,5%) Bensk\xf6rhet 5,1% (5,1%) 2,7% (2,7%) Tromboemboliska biverkningar 2,1 % (2,9%) 3,6 % (4,5%) Hj\xe4rtinfarkt 1,0 % (1,5%) 0,5 % (1,0%) Endometriell hyperplasi / 0,2 % (0,4%) 2,3 % (2,9%) endometriecancer Obs! Behandlingstiden var 60 m\xe5nader i median. Rapportperioden inkluderar behandlingstiden plus 30 dagar efter avslutad behandling. Procentandelen inom parentes anger biverkningsfrekvenser n\xe4r som helst efter randomisering, inklusive efter perioden med studiebehandling. Mediantiden f\xf6r uppf\xf6ljning var 73 m\xe5nader. Tabell 3 Sekventiell behandling mot Femar i monoterapi \u2013 biverkningar med signifikanta skillnader Femar monoterapi Femar->tamoxifen Tamoxifen-> Femar Benfrakturer 9,9% 7,6%* 9,6% Proliferativ 0,7% 3,4%** 1,7%** endometriesjukdom Hyperkolesterolemi 52,5% 44,2%* 40,8%* Blodvallningar 37,7% 41,7%** 43,9%** Vaginalbl\xf6dning 6,3% 9,6%** 12,7%** *Signifikant f\xe4rre med Femar i monoterapi ** Signifikant fler med Femar i monoterapi Obs! Rapportperioden \xe4r behandlingstiden eller inom 30 dagar fr\xe5n avslutad behandling Beskrivning av valda biverkningar']]],
           ['Rare',
            [['Other',
              u'>0,01% till <0,1%, mycket s\xe4llsynta <0,01%, ingen k\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data).'],
             ['Vascular', u'Lungemboli, arteriell trombos, cerebrovaskul\xe4r infarkt']]],
           ['Unknown',
            [['Other',
              u's\xe5som bensk\xf6rhet och/eller benfrakturer och kardiovaskul\xe4ra biverkningar (inklusive cerebrovaskul\xe4ra och tromboemboliska). F\xf6rekomsten av dessa biverkningar anges i tabell 1. Biverkningar i tabellform Biverkningsfrekvenserna f\xf6r Femar baseras huvudsakligen p\xe5 data fr\xe5n kliniska studier. L\xe4kemedelsbiverkningarna i tabell 1 har rapporterats vid kliniska pr\xf6vningar och efter f\xf6rs\xe4ljningsgodk\xe4nnande av Femar. Tabell 1 Biverkningarna \xe4r rangordnade efter frekvens, med de vanligast f\xf6rekommande f\xf6rst, enligt f\xf6ljande: mycket vanliga >10%, vanliga >1% till 10%, mindre vanliga >0,1% till <1%,'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Ingen k\xe4nd frekvens Angio\xf6dem, toxisk epidermal nekrolys, erythema multiforme'],
             ['Cardiac',
              u'Vid adjuvant behandling har f\xf6ljande biverkningar, ut\xf6ver de data som presenteras i tabell 2, rapporterats f\xf6r Femar respektive tamoxifen (under en behandlingstid p\xe5 60 m\xe5nader i median plus 30 dagar): k\xe4rlkramp som kr\xe4ver kirurgi (1,0% mot 1,0%), hj\xe4rtsvikt (1,1% mot 0,6%), hypertoni (5,6% mot 5,7%), cerebrovaskul\xe4r sjukdom/transient ischemisk attack (2,1% mot 1,9%). Vid f\xf6rl\xe4ngd adjuvant behandling har f\xf6ljande biverkningar rapporterats f\xf6r Femar (behandlingstid 5 \xe5r i median) respektive placebo (behandlingstid 3 \xe5r i median): k\xe4rlkramp som kr\xe4ver kirurgi (0,8% mot 0,6%), debut av, eller f\xf6rv\xe4rrad, k\xe4rlkramp (1,4% mot 1,0%), hj\xe4rtinfarkt (1,0% mot 0,7%), tromboemboliska biverkningar * (0,9% mot 0,3%), stroke/transitorisk ischemisk attack* (1,5% mot 0,8%). F\xf6r biverkningar markerade med * var skillnaden mellan de tv\xe5 behandlingsgrupperna statistiskt signifikant. Skeletala systemet Se tabell 2 f\xf6r data om skelettrelaterade biverkningar vid adjuvant behandling. Vid f\xf6rl\xe4ngd adjuvant behandling intr\xe4ffade frakturer eller osteoporos hos signifikant fler patienter som behandlades med Femar (benfrakturer 10,4% och osteoporos 12,2%) j\xe4mf\xf6rt med placebo (5,8% och 6,4%). Behandlingstiden var i median 5 \xe5r f\xf6r Femar och 3 \xe5r f\xf6r placebo.']]]],
 '_pages': [4, 7],
<<<<<<< HEAD
 u'_rank': 38,
=======
 u'_rank': 39,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}