{'_data': [['Very common', [['Respiratory', u'Vanlig Mindre vanlig S\xe4llsynt Ej k\xe4nd']]],
           ['Common',
            [['Respiratory',
              u'Eksem, allergisk Hud och Svettning, dermatit, subkutan Pruritus, Utslag, hudproblem, v\xe4vnad Erytem dermatit kontaktdermatit Muskulo-skeleta la systemet och Muskelspasmer Muskelryckningar bindv\xe4v Njurar och urinv\xe4gar Urinretention Erektil Reproduktionso rgan och dysfunktion, br\xf6stk\xf6rtel Sexuell dysfunktion Reaktioner vid appliceringsst\xe4llet, Allm\xe4nna influensaliknande symtom och/eller Tr\xf6tthet, perifera sjukdom, k\xe4nsla av Dermatit vid symtom vid \xf6dem peripheral, att applikations-st\xe4ll administrerings- Asteni, kropps-temperatur et, eksem vid sjukdomsk\xe4nsla en \xe4ndras, applikations-st\xe4ll st\xe4llet k\xe4nsla av kyla \xf6verk\xe4nslighet vid et appliceringsst\xe4llet, l\xe4kemedelsabstine nssymtom']]],
           ['Unknown',
            [['Immune system',
              u'Anafylaktoid reaktion Metabolism och nutrition Anorexi S\xf6mnl\xf6shet, Psykiska depression, Agitation, st\xf6rningar \xe5ngest, f\xf6rvirring desorientering, hallucinationer eufori Hypoestesi, Centrala och S\xf6mnighet, krampanfall perifera yrsel, Tremor, parestesi (inklusive kloniska nervsystemet huvudv\xe4rk anfall och grand mal-anfall), amnesi \xd6gon Mios \xd6ron och balansorgan Svindel Palpitationer, Bradykardi, Hj\xe4rtat Tackykardi Cyanos Blodk\xe4rl Hypertoni Hypotoni'],
             ['Respiratory',
              u'br\xf6stkorg och Andnings-depressi Apn\xe9, mediastinum Dyspn\xe9 on, andn\xf6d Hypoventilering Bradypn\xe9, Diarr\xe9, Magtarm-kanal Illam\xe5ende, muntorrhet, en kr\xe4kningar, magsm\xe4rtor, \xf6vre Ileus Subileus f\xf6rstoppning magsm\xe4rtor , dyspesi. Organsystem- Biverkningar klass Frekvenskategori']]]],
 '_pages': [9, 11],
 u'_rank': 4,
 u'_type': u'LSFU'}