{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk, yrsel, somnolens'],
             ['GI', u'illam\xe5ende, kr\xe4kningar, f\xf6rstoppning']]],
           ['Common',
            [['Cardiac', u'takykardi, palpitationer'],
             ['Nervous system', u'tremor, parestesi'],
             ['Ear', u'yrsel'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, muntorrhet, magsm\xe4rta, \xf6vre magsm\xe4rta, dyspepsi'],
             ['Renal', u'urinretention'],
             ['Skin', u'svettning, pruritus, hudutslag, erytem'],
             ['Musculoskeletal', u'muskelspasmer'],
             ['Vascular', u'hypertoni'],
             ['General',
              u'Tr\xf6tthet, perifert \xf6dem, asteni, sjukdomsk\xe4nsla, k\xe4nsla av kyla'],
             ['Immune system', u'\xf6verk\xe4nslighet'],
             ['Psychiatric',
              u's\xf6mnl\xf6shet, depression, oro, f\xf6rvirringstillst\xe5nd, hallucination']]],
           ['Uncommon',
            [['Cardiac', u'bradykardi, cyanos'],
             ['Nervous system',
              u'hypoestesi, krampanfall (inklusive kloniska och grand mal anfall), amnesi'],
             ['Respiratory', u'andningsdepression, andn\xf6d'],
             ['GI', u'ileus'],
             ['Reproductive system', u'erektil dysfunktion, sexuell dysfunktion'],
             ['Skin',
              u'eksem, allergisk dermatit, hudproblem, dermatit, kontaktdermatit Utslag, erytem och pruritus f\xf6rsvinner normalt inom ett dygn efter att pl\xe5stret tagits bort.'],
             ['Musculoskeletal', u'muskelryckningar'],
             ['Vascular', u'hypotoni'],
             ['General',
              u'Reaktioner vid appliceringsst\xe4llet, influensaliknande sjukdom, k\xe4nsla av f\xf6r\xe4ndrad kroppstemperatur, \xf6verk\xe4nslighet vid appliceringsst\xe4llet, uts\xe4ttningssyndrom'],
             ['Psychiatric',
              u'agitation, disorientering, euforiskt tillst\xe5nd Liksom med andra opioida analgetika kan tolerans, fysiskt och psykiskt beroende utvecklas vid upprepad anv\xe4ndning av Fentanyl Sandoz depotpl\xe5ster (se avsnitt 4.4). Uts\xe4ttningssyndrom av opioider (s\xe5som illam\xe5ende, kr\xe4kningar, diarr\xe9, oro och skakningar) \xe4r m\xf6jliga hos vissa patienter efter byte fr\xe5n deras tidigare opioida analgetikum till Fentanyl Sandoz depotpl\xe5ster om behandlingen avbryts pl\xf6tsligt (se avsnitt 4.2). Det har i mycket s\xe4llsynta fall f\xf6rekommit rapporter om nyf\xf6dda barn som upplevt neonatala uts\xe4ttningssyndrom n\xe4r m\xf6drarna kroniskt anv\xe4nt Fentanyl Sandoz depotpl\xe5ster under graviditet (se avsnitt 4.6). Barn Biverkningsprofilen hos barn och ungdomar som behandlats med Fentanyl depotpl\xe5ster liknade den som observerades hos vuxna. Ingen risk identifierades i den pediatriska populationen f\xf6rutom den som f\xf6rv\xe4ntades vid anv\xe4ndning av opioider f\xf6r sm\xe4rtlindring f\xf6rknippat med allvarlig sjukdom och det verkar inte vara n\xe5gon specifik pediatrisk risk f\xf6rknippad med Fentanyl Sandoz depotpl\xe5ster vid anv\xe4ndning hos barn s\xe5 unga som 2 \xe5r, vid anv\xe4ndning enligt anvisningen. Mycket vanliga biverkningar som rapporterats under kliniska pr\xf6vningar var feber, kr\xe4kningar och illam\xe5ende.']]],
           ['Rare',
            [['Eye', u'mios'],
             ['Respiratory', u'apn\xe9, hypoventilering'],
             ['GI', u'subileus'],
             ['General',
              u'dermatit vid appliceringsst\xe4llet, eksem vid appliceringsst\xe4llet']]],
           ['Unknown',
            [['Respiratory', u'bradypn\xe9'],
             ['Immune system',
              u'anafylaktisk chock, anafylaktisk reaktion, anafylaktoid reaktion']]]],
 '_pages': [9, 10],
 u'_rank': 30,
 u'_type': u'LSFU'}