{'_data': [['Very common',
            [['Nervous system', u'somnolens, yrsel, huvudv\xe4rk'],
             ['GI', u'illam\xe5ende, kr\xe4kningar, f\xf6rstopp-ni ng'],
             ['Pregnancy', u'(seavsnitt 4.6). ']]],
           ['Common',
            [['Immune system', u'\xf6verk\xe4ns-li ghets-reakti oner'],
             ['Metabolism', u'aptitl\xf6shet'],
             ['Psychiatric',
              u's\xf6mnl\xf6shet, depression, \xe5ngest, f\xf6rvirrings-tillst\xe5nd, hallucina-ti oner, sedering, nervositet'],
             ['Nervous system', u'tremor, parestesier'],
             ['Ear', u'svindel'],
             ['Cardiac', u'palpita-tion er, takykardi'],
             ['Vascular', u'hypertoni'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI',
              u'diarr\xe9, muntorrhet, mag-sm\xe4rto r, sm\xe4rtor i bukens \xf6vre del, dyspepsi'],
             ['Skin',
              u'hyper-hidro s, kl\xe5da, hudutslag, hudrodnad, hudreak-tio ner vid administre-ringsst\xe4llet'],
             ['Musculoskeletal', u'muskel-spa smer'],
             ['Renal', u'urinreten-ti on'],
             ['General',
              u'tr\xf6tthet, perifert \xf6dem, asteni, sjukdoms-k \xe4nsla, k\xf6ldk\xe4nsla']]],
           ['Uncommon',
            [['Psychiatric', u'agitation, desorien-teri ng, eufori'],
             ['Nervous system',
              u'hypestesi, kramper (inklusive kloniska anfall och grand mal-episoder ), amnesi, talsv\xe5rig-hete'],
             ['Cardiac', u'bradykardi, cyanos'],
             ['Vascular', u'hypotoni'],
             ['Respiratory', u'andnings-dep ression, andings-sv\xe5ri gheter'],
             ['GI', u'ileus'],
             ['Skin',
              u'eksem, allergisk dermatit, hudreaktio-n er, dermatit, kontakt-derm atit, exantem'],
             ['Musculoskeletal', u'muskel-sam man-dragnin gar'],
             ['Reproductive system', u'erektions-st\xf6 rningar, sexuell dysfunktion'],
             ['General',
              u'reaktioner vid administre-ri ngsst\xe4llet, influensa-lik nande symtom, k\xe4nsla av f\xf6r\xe4ndringar i kroppstem-p eraturen, \xf6verk\xe4nslig-hetsreak-tion er vid administre-ri ngssst\xe4llet, uts\xe4ttnings-s ymtom']]],
           ['Rare',
            [['Eye', u'mios'],
             ['Cardiac', u'rytmrubb-ni ngar'],
             ['Vascular', u'vasodilation'],
             ['Respiratory', u'apn\xe9, hypoventi-la tion'],
             ['GI', u'subileus, hicka'],
             ['General',
              u'dermatit vid administre-ri ngsst\xe4llet, eksem vid administre-ri ngsst\xe4llet']]],
           ['Very rare',
            [['Psychiatric', u'vanf\xf6re-st\xe4ll ningar, tillst\xe5nd av upprymdhet'],
             ['Nervous system', u'ataxi'],
             ['Eye', u'amblyopi'],
             ['GI', u'sm\xe4rtsam flatulens'],
             ['Renal', u'sm\xe4rta i urinbl\xe5san, oliguri']]],
           ['Unknown',
            [['Immune system',
              u'anafylaktisk chock, anafylaktiska reaktioner, anafylaktoida reaktioner'],
             ['Respiratory', u'bradypn\xe9']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 39,
 u'_type': u'MSFU'}