{'_data': [['Very common', []],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI', u'Illam\xe5ende, buksm\xe4rta, f\xf6rstoppning, diarr\xe9'],
             ['Skin', u'Hudutslag'],
             ['General', u'Reaktioner p\xe5 injektionsst\xe4llet'],
             ['Investigations',
              u'\xd6verg\xe5ende minskning av fosfor i blodet, f\xf6rh\xf6jd koncentration av alaninaminotransferas.']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet inklusive anafylaktoid reaktion'],
             ['Nervous system', u'Parestesier'],
             ['Vascular', u'Hypotoni, hypertoni, blodvallningar'],
             ['GI', u'Dysgeusi, kr\xe4kningar, dyspepsi, flatulens'],
             ['Skin', u'Kl\xe5da, urtikaria'],
             ['Musculoskeletal', u'Myalgi, ryggsm\xe4rta, artralgi'],
             ['General',
              u'Pyrexi, tr\xf6tthet, br\xf6stsm\xe4rta, frossbrytningar, sjukdomsk\xe4nsla, perifert \xf6dem'],
             ['Investigations',
              u'\xd6kning av aspartat-aminotransferas, \xf6kad halt gammaglutamyl-transferas, \xf6kning av laktatdehydrogenas i blodet.']]],
           ['Rare', [['Respiratory', u'Dyspn\xe9']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 4],
 u'_rank': 14,
 u'_type': u'MSFU'}