{'_data': [[u'Unknown',
            [['Blood', u'Neutropeni'],
             ['Immune system', u'\xd6verk\xe4nslighets-'],
             ['Metabolism', u'\xd6kad aptit'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende   Diarr\xe9'],
             ['Skin', u'Utslag'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Kromaturi'],
             ['General', u'Tr\xf6tthet'],
             ['Investigations', u'F\xf6rh\xf6jda']]]],
 '_pages': [4, 6],
 u'_rank': 10,
 u'_type': u'LFSU'}