{'_data': [['Common',
            [['Nervous system', u'\xf6verg\xe5ende smakrubbningar (speciellt metallsmak).']]],
           ['Uncommon',
            [['Nervous system', u'huvudv\xe4rk; yrsel.'],
             ['Nervous system',
              u'hypotension och kollaps; hypertension, takykardi och hj\xe4rtklappning.'],
             ['Respiratory', u'bronkospasm, dyspn\xe9.'],
             ['GI', u'illam\xe5ende; kr\xe4kningar; buksm\xe4rtor; diarr\xe9.'],
             ['Skin', u'pruritus; urtikaria; hudutslag, exantem, erytem.'],
             ['Musculoskeletal', u'muskelkramper, myalgi.'],
             ['General',
              u'feber, frossa, blodvallning; br\xf6stsm\xe4rtor och andn\xf6d. Reaktioner p\xe5 injektionsst\xe4llet s\xe5som ytliga flebiter, br\xe4nnande k\xe4nsla, svullnad.']]],
           ['Rare',
            [['Nervous system', u'parestesier.'],
             ['General',
              u'anafylaktoida reaktioner (i s\xe4llsynta fall med artralgi); perifert \xf6dem; tr\xf6tthet, asteni; sjukdomsk\xe4nsla. Dessutom har f\xf6ljande biverkningar rapporterats spontant']]],
           ['Very rare',
            [['Nervous system',
              u'krampanfall (i samband med hypersensitivitetsreaktioner) Hj\xe4rt- och k\xe4rlsjukdomar']]],
           ['Unknown',
            [['General',
              u's\xe4nkt medvetandegrad, omt\xf6ckning, f\xf6rvirring, angio\xf6dem, ledsvullnad, hyperhidros, ryggsm\xe4rta.']]]],
 '_pages': [5, 6],
 u'_rank': 12,
 u'_type': u'LSFU'}