{'_data': [['Uncommon',
            [['Psychiatric', u' Minskad libido'],
             ['Psychiatric', u'Nedst\xe4mdhet\u2020'],
             ['Reproductive system',
              u' Erektil dysfunktion, ejakulationst\xf6rningar (inklusive minskad m\xe4ngd ejakulat).']]],
           ['Unknown',
            [['Immune system',
              u' \xd6verk\xe4nslighetsreaktioner inklusive hudutslag, kl\xe5da, n\xe4sselutslag och svullnad av l\xe4ppar och ansikte.'],
             ['Cardiac', u' Hj\xe4rtklappning'],
             ['Hepato', u' F\xf6rh\xf6jda leverenzymv\xe4rden'],
             ['Reproductive system',
              u'Br\xf6st\xf6mhet och f\xf6rstoring, testikelsm\xe4rta, infertilitet** *Incidenser presenterade som skillnaden mellan aktiv behandling och placebo i kliniska studier efter 12 m\xe5nader. ** Se avsnitt 4.4']]]],
 '_pages': [3, 4],
 u'_rank': 7,
 u'_type': u'LSFU2'}