{'_data': [['Common',
            [['Reproductive system', u'Impotens.'],
             ['Investigations', u'Minskad m\xe4ngd ejakulat.']]],
           ['Uncommon',
            [['Skin', u'Hudutslag.'], ['Reproductive system', u'\xd6mma br\xf6st/br\xf6st']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nsli ghetsreakti oner inklusive svullnad av l\xe4ppar och ansikte.'],
             ['Skin', u'Pruritus, urtikaria.'],
             ['Reproductive system', u'Testikel-sm\xe4rta.']]],
           ['Very rare', [['Reproductive system', u'Br\xf6st-sekretion,']]],
           ['Unknown',
            [['Cardiac', u'Hj\xe4rtklap pning.'],
             ['Hepato', u'\xd6kade leverenzy mer.'],
             ['Reproductive system', u'Manlig br\xf6st']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 11,
 u'_type': u'MSFU'}