{'_data': [['Very common',
            [['Vascular', u'V\xe4rmevallningar*'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Musculoskeletal', u'Muskuloskeletal'],
             ['Reproductive system', u'Gynekomasti*,'],
             ['General', u'Biverkningar vid injektionsst\xe4llet']]],
           ['Common',
            [['Blood', u'Anemi*'],
             ['Metabolism', u'Vikt\xf6kning* Hyperglykemi/diabetes blodet'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI', u'Diarr\xe9,'],
             ['Hepato', u'\xd6kning av lever-transaminaser'],
             ['Skin', u'\xd6kad svettning (inkl. nattliga svettningar)*, utslag'],
             ['Musculoskeletal', u'sm\xe4rta och obehag'],
             ['Reproductive system', u'testikelatrofi*, erektil dysfunktion*'],
             ['General', u'Frossa, feber, tr\xf6tthet*, influensaliknande symtom']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'mellitus, kolesterol\xf6kning, viktminskning, nedsatt aptit, f\xf6r\xe4ndringar av kalcium i'],
             ['Psychiatric', u'Depression, nedsatt libido*'],
             ['Nervous system', u'Mental f\xf6rs\xe4mring, hypoestesi'],
             ['Eye', u'Dimsyn'],
             ['Cardiac',
              u'Hj\xe4rtarytmi (inklusive f\xf6rmaksflimmer), palpitationer, QT f\xf6rl\xe4ngning* (se avsnitt 4.4 och 4.5)'],
             ['Vascular', u'Hypertoni, vasovagal reaktion (inklusive hypotoni)'],
             ['GI',
              u'illam\xe5ende F\xf6rstoppning, kr\xe4kningar, buksm\xe4rta, bukobehag, muntorrhet'],
             ['Hepato', u'\xd6kning av bilirubin och alkalisk fosfatas'],
             ['Skin', u'N\xe4sselfeber, knutor i huden, alopeci, kl\xe5da, erytem'],
             ['Musculoskeletal',
              u'Osteoporos/osteopeni, artralgi, muskelsvaghet, muskelryckningar, svullna/stela leder'],
             ['Renal',
              u'Pollakisuri, urintr\xe4ngningar, dysuri, nokturi, nedsatt njurfunktion, inkontinens'],
             ['Reproductive system',
              u'Testikelsm\xe4rta, br\xf6stsm\xe4rta, b\xe4ckensm\xe4rta, genital irritation, ejakulationssvikt'],
             ['General', u'Sjukdomsk\xe4nsla, perifert \xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 29,
 u'_type': u'MSFU'}