{'_data': [['Common',
            [['Nervous system', u'Yrsel Mindre'],
             ['General', u'Pyrexi, reaktion vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Respiratory', u'Bronkit, hosta, rosslingar'],
             ['GI',
              u'Diarr\xe9, illam\xe5ende, kr\xe4kning, buksm\xe4rta,  \xf6vre buksm\xe4rta'],
             ['Skin', u'Urtikaria, pruritus, kontaktdermatit'],
             ['General',
              u'Stelhet, asteni, sm\xe4rta, inflammation vid  injektionsst\xe4llet, \xf6dem vid injektionsst\xe4llet,  pruritus vid injektionsst\xe4llet, svullnad vid injektionsst\xe4llet, f\xf6rflyttning av implantat'],
             ['Investigations',
              u'Coombs test positivt, blodtryck systolisk  s\xe4nkning, blodtryck systolisk \xf6kning, kroppstemperatur f\xf6rh\xf6jd']]]],
 '_pages': [7, 8],
 u'_rank': 7,
 u'_type': u'TSFU'}