{'_data': [['Very common',
            [['Nervous system', u'Somnolens, akatisi, hyperkinesi,  hypokinesi.'],
             ['GI', u'Muntorrhet.']]],
           ['Common',
            [['Metabolism', u'\xd6kad aptit, \xf6kad vikt.'],
             ['Psychiatric', u'Insomnia, depression, nervositet,  agitation, minskad libido.'],
             ['Nervous system', u'Tremor, dystoni, yrsel,  huvudv\xe4rk.'],
             ['Eye', u'Ackommodationsst\xf6rningar,  synst\xf6rningar.'],
             ['Cardiac', u'Takykardi, palpitationer.'],
             ['Respiratory', u'Dyspn\xe9.'],
             ['GI', u'Salivhypersekretion,  konstipation, kr\xe4kningar, dyspepsi, diarr\xe9.'],
             ['Skin', u'Hyperhidros, pruritus.'],
             ['Musculoskeletal', u'Myalgi.'],
             ['Renal', u'Miktionsst\xf6rningar,  urinretention.'],
             ['General', u'Asteni, tr\xf6tthet.']]],
           ['Uncommon',
            [['Metabolism', u'Minskad aptit.'],
             ['Psychiatric', u'Konfusionstills\xe5nd.'],
             ['Eye', u'Okulogyration.'],
             ['Vascular', u'Hypotension, v\xe4rmevallningar.'],
             ['GI', u'Magsm\xe4rtor, illam\xe5ende,  flatulens'],
             ['Hepato', u'Abnormalt leverfunktionstest.'],
             ['Skin', u'Rash, fotosensibilisering,  dermatit.'],
             ['Musculoskeletal', u'Muskelrigiditet.'],
             ['Reproductive system', u'Utebliven ejakulation, erektil  dysfunktion.']]],
           ['Rare',
            [['Blood', u'Trombocytopeni, neutropeni,  leukopeni, agranulocytos.'],
             ['Immune system', u'Hypersensitivitet, anafylaktisk  reaktion.'],
             ['Endocrine', u'Hyperprolaktinemi.'],
             ['Metabolism', u'Hyperglykemi, abnormal  glukostolerans.'],
             ['Nervous system', u'parkinsonism, talsv\xe5righeter,  konvulsion.'],
             ['Cardiac', u'QT-f\xf6rl\xe4ngning.'],
             ['Reproductive system', u'Gynekomasti, galaktorr\xe9,  amenorr\xe9.']]],
           ['Very rare',
            [['Nervous system', u'Malignt neuroleptikasyndrom.'],
             ['Vascular', u'Ven\xf6s trombo-embolisk  sjukdom.'],
             ['Hepato', u'Gulsot.']]],
           ['Unknown', [['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom  (se 4.6)']]]],
 '_pages': [4, 6],
 u'_rank': 33,
 u'_type': u'TSFU'}