{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Magsm\xe4rtor, diarr\xe9, illam\xe5ende,  kr\xe4kningar'],
             ['Hepato',
              u'\xd6kning av ALAT (se avsnitt  .4), \xf6kning av ASAT (se avsnitt 4.4), \xf6kning av alkaliska fosfataser (se avsnitt 4.4)'],
             ['Skin', u'Utslag (se avsnitt 4.4)']]],
           ['Uncommon',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Hypokalemi, minskad aptit'],
             ['Psychiatric', u'Insomni, somnolens'],
             ['Nervous system',
              u'Konvulsioner, kramper, yrsel,  parestesier, smakf\xf6r\xe4ndringar, tremor'],
             ['Ear', u'Vertigo'],
             ['GI', u'Dyspepsi, flatulens, muntorrhet,  anorexi, obstipation'],
             ['Hepato',
              u'Kolestas (se avsnitt 4.4), ikterus  (se avsnitt 4.4), \xf6kning av bilirubin (se avsnitt 4.4), hepatocellul\xe4r skada (se avsnitt .4)'],
             ['Skin',
              u'Pruritus, urtikaria (se avsnitt  .4), \xf6kad svettning, l\xe4kemedelsutl\xf6st utslag (se avsnitt 4.4)'],
             ['Musculoskeletal', u'Myalgi'],
             ['General', u'Tr\xf6tthet, sjukdomsk\xe4nsla,  asteni, feber']]],
           ['Rare',
            [['Blood', u'Agranulocytos, leukopeni,  neutropeni, trombocytopeni'],
             ['Immune system', u'Anafylaxi'],
             ['Metabolism', u'Hypertriglyceridemi,  hyperkolesterolemi'],
             ['Cardiac',
              u'Torsade de pointes (se avsnitt  .4), QT-f\xf6rl\xe4ngning (se avsnitt .4)'],
             ['Hepato',
              u'Leversvikt (se avsnitt 4.4),  levernekros (se avsnitt 4.4), hepatit (se avsnitt 4.4)'],
             ['Skin',
              u'Toxisk epidermal nekrolys (se  avsnitt 4.4), Stevens-Johnsons syndrom (se avsnitt 4.4), akut generaliserad exantematisk pustulos (se avsnitt 4.4), exfoliativ dermatit, angio\xf6dem, ansikts\xf6dem, alopeci']]]],
 '_pages': [11, 13],
 u'_rank': 20,
 u'_type': u'TSFU'}