{'_data': [[u'Unknown',
            [['Blood', u'anemi'],
             ['Nervous system', u'huvudv\xe4rk   Krmapanfall, yrsel,  parestesi, tremor,'],
             ['Nervous system', u'\xf6kad svettning'],
             ['GI', u'illam\xe5ende   anorexi,'],
             ['Skin', u'hudutslag   pruritus   exfoliativ   hudreaktion'],
             ['Musculoskeletal', u'myalgi'],
             ['General', u'tr\xf6tthet,'],
             ['Immune system', u'anafylaxi'],
             ['Hepato', u'kliniskt   kolestas,   hepatisk'],
             ['Psychiatric', u's\xf6mnl\xf6shet,']]]],
 '_pages': [8, 10],
 u'_rank': 10,
 u'_type': u'LFSU'}