{'_data': [['Common',
            [['Psychiatric', u'Huvudv\xe4rk'],
             ['GI', u'Magsm\xe4rtor, diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Hepato',
              u'\xd6kning av ALAT, \xf6kning av ASAT, \xf6kning av alkaliska fosfataser'],
             ['Skin', u'Utslag']]],
           ['Uncommon',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Anorexi, hypokalemi'],
             ['Psychiatric', u'Insomni Centrala och perifera'],
             ['Psychiatric',
              u'Konvulsioner, kramper, yrsel, parestesier, smakf\xf6r\xe4ndringar, tremor, svindel, somnolens'],
             ['GI', u'Dyspepsi, flatulens, muntorrhet, obstipation'],
             ['Hepato', u'Kolestas, ikterus, \xf6kning av bilirubin, hepatocellul\xe4r skada'],
             ['Skin', u'Pruritus, urtikaria, \xf6kad svettning Toxisk epidermal nekrolys,'],
             ['Skin',
              u'Myalgi Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Skin',
              u'Tr\xf6tthet, sjukdomsk\xe4nsla, asteni, feber Barn Biverkningar hos barn f\xf6ljer m\xf6nstret som setts hos vuxna.']]],
           ['Rare',
            [['Blood', u'Agranulocytos, leukopeni neutropeni, trombocytopeni'],
             ['Immune system', u'Anafylaxi'],
             ['Metabolism', u'Hypertriglyceridemi, hyperkolesterolemi'],
             ['Cardiac', u'Torsade de pointes (se avsnitt 4.4), QT-f\xf6rl\xe4ngning'],
             ['Hepato', u'S\xe4llsynta Levertoxicitet, leversvikt, levernekros, hepatit'],
             ['Skin',
              u'Stevens-Johnsons syndrom, exfoliativ dermatit inklusive erythema multiforme, angio\xf6dem, ansikts\xf6dem, alopeci Muskuloskeletala systemet och bindv\xe4v']]]],
 '_pages': [12, 13],
 u'_rank': 19,
 u'_type': u'LSFU'}