{'_data': [['Very common', []],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende Kr\xe4kningar Magsm\xe4rtor Diarr\xe9'],
             ['Hepato', u'Kliniskt signifikant \xf6kning av ASAT, ALAT och alkaliskt fosfatas'],
             ['Skin', u'Hudutslag'],
             ['Infections', u'Infektion p\xe5 grund av resistenta mikroorganismer'],
             ['Blood',
              u'Leukopeni, inklusive neutropeni och agranulocytos, trombocytopeni, eosinofili.'],
             ['Immune system', u'Angio\xf6dem, ansikts\xf6dem, kl\xe5da, urtikaria'],
             ['Metabolism', u'Hyperkolesterolemi, hypertriglyceridemi, hypokalemi'],
             ['Nervous system', u'Kramper'],
             ['Cardiac',
              u'QT-f\xf6rl\xe4ngning, torsades de pointes (Se avsnitt 4.4 Varningar och f\xf6rsiktighet)'],
             ['Hepato', u'Leversvikt, hepatit']]],
           ['Uncommon',
            [['Blood', u'Anemi'],
             ['Psychiatric', u'Insomnia Somnolens'],
             ['Nervous system', u'Kramper Yrsel Parestesier Tremor Vertigo'],
             ['Nervous system', u'\xd6kad svettning'],
             ['Special Senses', u'Smakf\xf6r\xe4ndring'],
             ['GI', u'Anorexi F\xf6rstoppning Dyspepsi Flatulens'],
             ['Hepato',
              u'Kolestas Hepatocellul\xe4r skada Ikterus Kliniskt signifikant \xf6kning av total -bilirubin'],
             ['Skin', u'Pruritus'],
             ['General', u'Tr\xf6tthet Sjukdomsk\xe4nsla Asteni Feber']]],
           ['Rare',
            [['Immune system', u'Anafylaxi'],
             ['Hepato', u'Levernekros'],
             ['Skin', u'Exfoliativa hudsjukdomar (Stevens-Johnsons syndrom)']]],
           ['Very rare',
            [['Psychiatric', u'Frekvens ej k\xe4nd (kan ej uppskattas tillg\xe4ngliga data)']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 12],
 u'_rank': 24,
 u'_type': u'MSFU'}