<<<<<<< HEAD
{'_data': [[u'Unknown',
            [['Infections', u'Infektioner/   Lymfproliferativ   opportunistiska   sjukdom'],
             ['Neoplasms',
              u'Myelodysplastiskt   syndrom och Akut   Myeloid Leukemi   (huvudsakligen i   samband med'],
             ['Blood', u'Neutropeni,   Myelosuppression   Anemi,'],
             ['Immune system', u'Autoimmun sjukdom'],
             ['Metabolism', u'Anorexi   Tum\xf6rlyssyndrom   (inklusive njursvikt,'],
             ['Nervous system',
              u'Perifer neuropati   F\xf6rvirring   Koma,   Hj\xe4rnbl\xf6dning   Krampanfall,   Agitation'],
             ['Eye', u'Synrubbningar   Blindhet,'],
             ['Cardiac', u'Hj\xe4rtsvikt,'],
             ['Respiratory', u'Hosta   Pulmonell toxicitet   Bl\xf6dningar i'],
             ['GI', u'Kr\xe4kningar,   Stomatit   Mag-tarmbl\xf6dningar,'],
             ['Hepato', u'Onormala   leverenzymer'],
             ['Skin', u'Hudutslag   Hudcancer,   Toxisk   epidermal'],
             ['Renal', u'Hemorragisk   cystit'],
             ['General', u'Feber,   \xd6dem'],
             ['General', u'Sjukdomsk\xe4nsla']]]],
 '_pages': [6, 7],
 u'_rank': 15,
 u'_type': u'LFSU'}
=======
{'_data': [['Very common',
            [['Infections',
              u'Infektioner/ opportunistiska infektioner (s\xe5som reaktivering av latenta virus, t.ex. progressiv multifokal leukoencefalopati, Herpes zoster-virus, Epstein-Barr-virus), Pneumoni'],
             ['Blood', u'Neutropeni, Anemi, Trombocytopeni'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Kr\xe4kningar, Diarr\xe9, Illam\xe5ende'],
             ['General', u'Feber, Tr\xf6tthet, Svaghet']]],
           ['Common',
            [['Neoplasms',
              u'Myelodysplastiskt syndrom och Akut Myeloid Leukemi (huvudsakligen i samband med tidigare, samtidig eller senare behandling med alkylerande medel, topoisomeras-h\xe4mmare eller str\xe5lning)'],
             ['Blood', u'Myelosuppression'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system', u'Perifer neuropati'],
             ['Eye', u'Synrubbningar'],
             ['GI', u'Stomatit'],
             ['Skin', u'Hudutslag'],
             ['General', u'\xd6dem Mukosit, Frossbrytningar, Sjukdomsk\xe4nsla']]],
           ['Uncommon',
            [['Immune system',
              u'Autoimmun sjukdom (inklusive autoimmun hemolytisk anemi, Evans syndrom, trombocytopen purpura, f\xf6rv\xe4rvad hemofili, pemfigus)'],
             ['Metabolism',
              u'Tum\xf6rlyssyndrom (inklusive njursvikt, metabolisk acidos, hyperkalemi, hypokalcemi, hyperurikemi, hematuri, uratkristalluri, hyperfosfatemi)'],
             ['Nervous system', u'F\xf6rvirring'],
             ['Respiratory',
              u'Pulmonell toxicitet (inklusive lungfibros, pneumonit, dyspn\xe9)'],
             ['GI', u'Mag-tarmbl\xf6dningar, Onormala pankreasenzymer'],
             ['Hepato', u'Onormala leverenzymer']]],
           ['Rare',
            [['Infections', u'Lymfproliferativ sjukdom (EBV-associerad)'],
             ['Nervous system', u'Koma, Krampanfall, Agitation'],
             ['Eye', u'Blindhet, Opticusneurit, Opticusneuropati'],
             ['Cardiac', u'Hj\xe4rtsvikt, Arytmi'],
             ['Skin',
              u'Hudcancer, Toxisk epidermal nekrolys (Lyells syndrom), Stevens-Johnsons syndrom']]],
           ['Unknown',
            [['Nervous system', u'Hj\xe4rnbl\xf6dning'],
             ['Respiratory', u'Bl\xf6dningar i lungorna'],
             ['Renal', u'Hemorragisk cystit']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 8],
 u'_rank': 27,
 u'_type': u'MSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
