{'_data': [['Very common', [['GI', u'Illam\xe5ende (under anestesi).']]],
           ['Common',
            [['Immune system', u'Allergiska reaktioner.'],
             ['Psychiatric',
              u'\xc5ngest*, emotionell labilitet,  s\xf6mnl\xf6shet, s\xf6mnighet.'],
             ['Eye', u'Dubbelseende, skelning, \xf6kat  t\xe5rfl\xf6de.'],
             ['Cardiac', u'Palpitationer*.'],
             ['Vascular',
              u'Blodvallning, hypotoni,  ortostatism, kortvarig h\xf6jning av blodtrycket (vid uppvaknandet).'],
             ['GI', u'Kr\xe4kningar (under anestesi), hicka.'],
             ['General', u'Tr\xf6tthet, sm\xe4rta p\xe5']]],
           ['Uncommon',
            [['Nervous system',
              u'Kramper (hos patienter som lider  av epilepsi eller sv\xe5r leverinsufficiens, huvudsakligen efter l\xe5ngvarig behandling med benzodiazepiner eller missbruk av flera l\xe4kemedel).'],
             ['Cardiac', u'Takykardi eller bradykardi,  extrasystole.'],
             ['Respiratory', u'Andn\xf6d, hosta, n\xe4st\xe4ppa,']]]],
 '_pages': [4, 5],
 u'_rank': 11,
 u'_type': u'TSFU'}