{'_data': [['Common',
            [['Immune system', u'Allergiska reaktioner'],
             ['Psychiatric', u'Emotionell labilitet, s\xf6mnl\xf6shet, s\xf6mnighet.'],
             ['Nervous system',
              u'Yrsel, huvudv\xe4rk, agitation* tremor, muntorrhet, hyperventilation, talrubbning, parestesi.'],
             ['Eye', u'Dubbelseende, skelning, \xf6kat t\xe5rfl\xf6de.'],
             ['Vascular', u'Hypotoni, ortostatisk hypotoni'],
             ['GI', u'Illam\xe5ende och kr\xe4kningar (under anestesi), hicka.'],
             ['Skin', u'Svettning.'],
             ['General', u'Tr\xf6tthet, sm\xe4rta vid injektionsst\xe4llet.']]],
           ['Uncommon',
            [['Psychiatric', u'\xc5ngest*, r\xe4dsla*'],
             ['Ear', u'Onormal h\xf6rsel'],
             ['Cardiac', u'Palpitationer*, takykardi eller bradykardi, extrasystole.'],
             ['Respiratory', u'Andn\xf6d, hosta, n\xe4st\xe4ppa, br\xf6stsm\xe4rta.'],
<<<<<<< HEAD
             ['General', u'Frossa']]],
=======
             ['General', u'Frossa *: efter snabb injektion; kr\xe4ver ingen behandling']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Psychiatric',
              u'Abstinenssymtom (t.ex. agitation, \xe5ngest, emotionell labilitet, f\xf6rvirring, sensoriska st\xf6rningar) efter snabb injektion av doser p\xe5 1 mg eller mer hos patienter som behandlats med bensodiazepiner i h\xf6ga doser och/eller under l\xe5ng tid och som satts ut vid n\xe5gon tidpunkt under veckorna f\xf6re flumazeniladministrering (se avsnitt 4.4); panikattacker (hos patienter som tidigare drabbats av panikst\xf6rningar); abnormt gr\xe5tande, agitation och aggressiva reaktioner'],
             ['Nervous system',
              u'Kramper, s\xe4rskilt hos patienter med k\xe4nd epilepsi eller gravt nedsatt leverfunktion, fr\xe4mst efter l\xe5ngvarig behandling med bensodiazepiner eller vid \xf6verdosering av flera l\xe4kemedel (se avsnitt 4.4).'],
             ['Vascular',
              u'Blodvallningar, tillf\xe4llig blodtrycksh\xf6jning (vid uppvaknande).']]]],
 '_pages': [4, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}