{'_data': [['Very common', [['Respiratory', u'Illam\xe5ende (under anestesi).']]],
           ['Common',
            [['Immune system', u'Allergiska reaktioner.'],
             ['Psychiatric',
              u'\xc5ngest*, emotionell labilitet,  s\xf6mnl\xf6shet, s\xf6mnighet.'],
             ['Nervous system',
              u'Yrsel, huvudv\xe4rk, agitation*,  tremor, muntorrhet,  hyperventilering, talrubbning, parestesier.'],
             ['Eye', u'Dubbelseende, skelning, \xf6kat  t\xe5rfl\xf6de.'],
             ['Eye', u'Palpitationer*.'],
             ['Vascular',
              u'Blodvallning, hypotoni,  ortostatisk hypotoni, tillf\xe4llig h\xf6jning av blodtrycket (vid uppvaknandet).'],
             ['Respiratory', u'Kr\xe4kningar (under anestesi),  hicka.'],
             ['Skin', u'Svettning.'],
             ['General', u'Tr\xf6tthet, sm\xe4rta p\xe5  injektionsst\xe4llet.']]],
           ['Uncommon',
            [['Nervous system', u'Kramper (hos patienter som'],
             ['Ear', u'Onormal h\xf6rsel'],
             ['Eye', u'Takykardi eller bradykardi,'],
             ['Respiratory', u'Andn\xf6d, hosta, n\xe4st\xe4ppa,'],
             ['General', u'Frossa.']]]],
 '_pages': [4, 5],
 u'_rank': 15,
 u'_type': u'TSFU'}