{'_data': [['Very common',
<<<<<<< HEAD
            [['Metabolism', u'ing'],
             ['Psychiatric', u'Insomni'],
             ['Nervous system', u'Huvud-v \xe4rk'],
             ['GI', u'Blodk\xe4rl'],
             ['GI', u'Diarr\xe9 Illam\xe5-e nde'],
             ['Skin', u'Utslag'],
             ['Reproductive system', u'Tr\xf6tthet'],
             ['Investigations',
              u'Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar ejakulation, bl\xf6dning 12 Inkluderar syndrom) Benfrakturer (se avsnitt Barn och ungdomar av hypomani/mani. 5.1).']]],
           ['Common',
            [['Metabolism', u'Aptitneds\xe4tt-n'],
             ['Psychiatric',
              u'\xc5ngest Nervositet Rastl\xf6shet Ansp\xe4nning Minskad libido S\xf6mnproblem Abnorma dr\xf6mmar'],
             ['Nervous system',
              u'Uppm\xe4rksam--hetsst\xf6rning Yrsel Dysgeusi Letargi Somnolens Tremor'],
=======
            [['Metabolism', u'ning'],
             ['Psychiatric', u'Insomni'],
             ['Nervous system', u'Huvud-Uppm\xe4rksam-v\xe4rk'],
             ['GI', u'Blodk\xe4rl'],
             ['GI', u'Diarr\xe9 Illam\xe5-ende'],
             ['Skin', u'Utslag'],
             ['GI', u'Muskuloskeletala'],
             ['Reproductive system', u'Gynekologisk Tr\xf6tthet'],
             ['Investigations',
              u'Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar Inkluderar ejakulation, bl\xf6dning Inkluderar Benfrakturer (se avsnitt Barn och ungdomar hypomani/mani. 5.1).']]],
           ['Common',
            [['Metabolism', u'Aptitneds\xe4tt'],
             ['Psychiatric',
              u'\xc5ngest Nervositet Rastl\xf6shet Ansp\xe4nning Minskad libido S\xf6mnproblem Abnorma dr\xf6mmar'],
             ['Nervous system', u'hetsst\xf6rning Yrsel Dysgeusi Letargi Somnolens Tremor'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Hj\xe4rtklappnin'],
             ['Vascular', u'Rodnad'],
             ['Respiratory', u'G\xe4spningar'],
             ['GI', u'Kr\xe4kningar Dyspepsi Muntorrhet'],
<<<<<<< HEAD
             ['Skin', u'Kl\xe5da Hyperhidros'],
             ['GI', u'Muskuloskeletala systemet och bindv\xe4v'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Frekvent urinering'],
             ['Reproductive system',
              u'Gynekologisk bl\xf6dning 11 Erektil dysfunktion Ejakulations-s t\xf6rningar 10 Nervositet Frossa'],
             ['Investigations',
              u'Viktminsknin g anorexi -mardr\xf6mmar -f\xf6rlust av libido -utebliven orgasm -hypersomni, sedation -v\xe4rmevallningar -pollakisuri -retrograd ejakulation -asteni -4.2 och 4.4). -(se avsnitt 4.4 och 5.1): ']]],
           ['Uncommon',
            [['Psychiatric',
              u'Depersonali -sation F\xf6rh\xf6jd sinnes-st\xe4m ning Euforisk sinnes-st\xe4m ning Onormala tankar Onormal orgasm Bruxism'],
=======
             ['Skin', u'Urtikaria Kl\xe5da Hyperhidros'],
             ['GI', u'systemet och bindv\xe4v '],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Frekvent urinering'],
             ['Reproductive system',
              u'bl\xf6dning Erektil dysfunktion Ejakulations-st\xf6rningar Nervositet Frossa'],
             ['Investigations',
              u'Viktminskning anorexi -mardr\xf6mmar -f\xf6rlust av libido -utebliven orgasm -hypersomni, sedation -v\xe4rmevallningar -pollakisuri -retrograd ejakulation -asteni -4.2 och 4.4). -(se avsnitt 4.4 och 5.1): ']]],
           ['Uncommon',
            [['Psychiatric',
              u'Depersonali -sation F\xf6rh\xf6jd sinnes-st\xe4mning Euforisk sinnes-st\xe4mning Onormala tankar Onormal orgasm Bruxism'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system',
              u'Psykomotor isk oro Dyskinesi Ataxi Balansst\xf6r-ning Myoklonus'],
             ['Eye', u'Mydriasis'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Dysfagi'],
<<<<<<< HEAD
             ['Skin', u'Alopeci ben\xe4genhet att f\xe5 bl\xe5m\xe4rken Kallsvettnin'],
             ['Musculoskeletal', u'Muskelryck -ningar'],
             ['Renal', u'Dysuri'],
             ['Reproductive system',
              u'Sexuell funktions-st \xf6rning Sjukdoms-k \xe4nsla K\xe4nna sig onormal K\xe4nna sig kall K\xe4nna sig varm']]],
           ['Rare',
            [['Immune system', u'Anafylaktisk reaktion Serumsjuke-li knande reaktion'],
=======
             ['Skin', u'Alopeci \xd6kad ben\xe4genhet att f\xe5 bl\xe5m\xe4rken Kallsvettnin'],
             ['Musculoskeletal', u'Muskelryck -ningar'],
             ['Renal', u'Dysuri'],
             ['Reproductive system',
              u'Sexuell funktions-st\xf6rning Sjukdoms-k\xe4nsla K\xe4nna sig onormal K\xe4nna sig kall K\xe4nna sig varm']]],
           ['Rare',
            [['Immune system', u'Anafylaktisk reaktion Serumsjuke-liknande reaktion'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Hypomani Mani Hallucinatione r Agitation Panikattacker'],
             ['Nervous system', u'Kramper Akatisi Tardiv dyskinesi'],
             ['Vascular', u'Vaskulit Vasodilation'],
             ['Respiratory', u'Faryngit'],
             ['GI', u'Esofageal sm\xe4rta'],
<<<<<<< HEAD
             ['Skin', u'Angio\xf6dem Fotosensitivite ts reaktion Purpura'],
=======
             ['Skin', u'Angio\xf6dem Ekkymos Fotosensitivite ts reaktion Purpura'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Renal', u'Urinretention'],
             ['Reproductive system', u'Galaktorr\xe9']]],
           ['Very rare', [['Blood', u'Trombo cytopen']]],
           ['Unknown',
            [['Endocrine', u'Inadekvat ins\xf6ndring av ADH'],
             ['Psychiatric',
<<<<<<< HEAD
              u'Sj\xe4lvmords-tan kar och sj\xe4lvmords-bete 14 ende F\xf6rvirring Dysfemism'],
=======
              u'Sj\xe4lvmords-tankar och sj\xe4lvmords-beteende F\xf6rvirring Dysfemism'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Serotonergt syndrom Minnes-f\xf6rs\xe4mring'],
             ['Ear', u'Tinnitus'],
             ['Respiratory',
              u'Pulmonella komplikationer (inflammatorisk a processer av varierande histopatologi och/eller fibros) N\xe4sbl\xf6dning'],
             ['GI', u'Gastrointestinal bl\xf6dning'],
             ['Hepato', u'Mycket s\xe4llsynt idiosynkratisk hepatit'],
<<<<<<< HEAD
             ['Skin', u'Erythema'],
             ['Musculoskeletal', u'Myalgi'],
             ['Renal', u'Bl\xe5st\xf6mnings-s v\xe5righeter'],
             ['Reproductive system', u'Priapism Slemhinne-bl\xf6d ning'],
             ['Investigations', u'Onormala leverfunktions-v\xe4rden']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 11],
 u'_rank': 55,
=======
             ['Skin', u'Erythema multiforme'],
             ['Musculoskeletal', u'Myalgi'],
             ['Renal', u'Bl\xe5st\xf6mnings-sv\xe5righeter'],
             ['Reproductive system', u'Priapism Slemhinne-bl\xf6dning'],
             ['Investigations', u'Onormala leverfunktions-v\xe4rden']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 11],
 u'_rank': 56,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}