{'_data': [['Very common', [['GI', u' illam\xe5ende']]],
           ['Common',
            [['Nervous system', u' synkope'],
<<<<<<< HEAD
             ['GI', u'obehag fr\xe5n buken och kr\xe4kning'],
=======
             ['GI', u' obehag fr\xe5n buken och kr\xe4kning'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Skin', u' pruritus'],
             ['General', u' extravasering']]],
           ['Uncommon',
            [['Immune system', u' \xf6verk\xe4nslighet'],
<<<<<<< HEAD
             ['Nervous system', u'dysfasi, parestesi, yrsel och huvudv\xe4rk'],
             ['Vascular', u' tromboflebit'],
             ['Respiratory', u' hosta, k\xe4nsla av tr\xe5ng strupe'],
             ['GI', u'buksm\xe4rta'],
             ['Skin', u'urtikaria'],
             ['General', u' sm\xe4rta och v\xe4rmek\xe4nsla']]],
           ['Rare',
            [['Immune system', u'anafylaktisk reaktion'],
             ['Cardiac', u' hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'hypotension och chock'],
             ['Respiratory', u' bronkospasm']]],
           ['Very rare',
            [['Immune system', u'anafylaktisk chock'],
             ['Nervous system', u'konvulsioner'],
             ['Cardiac', u'angina pectoris, bradykardi och takykardi'],
             ['Vascular',
              u'hypertension, vasospasm, vasodilatation, blekhet och v\xe4rmevallning'],
             ['Respiratory',
              u'andningsstillest\xe5nd, lung\xf6dem, astma, larynx\xf6dem, dyspn\xe9, nysningar och n\xe4s\xf6dem']]],
           ['Unknown',
            [['Nervous system',
              u'vertebrobasil\xe4r insufficiens, medvetsl\xf6shet, tremor, hypoestesi och dysgeusi'],
             ['Cardiac', u'myokardinfarkt'],
             ['GI', u'ulkning'],
             ['Skin', u'utslag, kallsvettning, eksem, erytem och hyperhidros'],
             ['General', u'\xf6dem, allm\xe4n sjukdomsk\xe4nsla och asteni']]]],
=======
             ['Nervous system', u' dysfasi, parestesi, yrsel och huvudv\xe4rk'],
             ['Vascular', u' tromboflebit'],
             ['Respiratory', u' hosta, k\xe4nsla av tr\xe5ng strupe'],
             ['GI', u' buksm\xe4rta'],
             ['Skin', u' urtikaria'],
             ['General', u' sm\xe4rta och v\xe4rmek\xe4nsla']]],
           ['Rare',
            [['Immune system', u' anafylaktisk reaktion'],
             ['Cardiac', u' hj\xe4rtstillest\xe5nd'],
             ['Vascular', u' hypotension och chock'],
             ['Respiratory', u' bronkospasm']]],
           ['Very rare',
            [['Immune system', u' anafylaktisk chock'],
             ['Nervous system', u' konvulsioner'],
             ['Cardiac', u' angina pectoris, bradykardi och takykardi'],
             ['Vascular',
              u' hypertension, vasospasm, vasodilatation, blekhet och v\xe4rmevallning'],
             ['Respiratory',
              u' andningsstillest\xe5nd, lung\xf6dem, astma, larynx\xf6dem, dyspn\xe9, nysningar och n\xe4s\xf6dem']]],
           ['Unknown',
            [['Nervous system',
              u' vertebrobasil\xe4r insufficiens, medvetsl\xf6shet, tremor, hypoestesi och dysgeusi'],
             ['Cardiac', u' myokardinfarkt'],
             ['GI', u' ulkning'],
             ['Skin', u' utslag, kallsvettning, eksem, erytem och hyperhidros'],
             ['General', u' \xf6dem, allm\xe4n sjukdomsk\xe4nsla och asteni']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_pages': [3, 4],
 u'_rank': 26,
 u'_type': u'LSFU2'}