{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'], ['Respiratory', u'Nasofaryngit']]],
           ['Common',
            [['Infections', u'Candidainfektion i munh\xe5la och svalg'],
             ['Infections', u'Bronkit  \xd6verk\xe4nslighetsreaktioner i form av:'],
             ['Metabolism', u'Hypokalemi'],
             ['Respiratory', u'Heshet/dysfoni'],
             ['Respiratory', u'Sinuit'],
             ['Skin', u'Bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Traumatiska frakturer'],
             ['Musculoskeletal', u'Artralgi'],
             ['Musculoskeletal', u'Myalgi']]],
           ['Uncommon',
            [['Immune system', u'Andningssymtom (dyspn\xe9)'],
             ['Psychiatric', u'Oro'],
             ['Nervous system', u'Tremor'],
             ['Cardiac', u'Palpitationer'],
             ['Cardiac', u'Takykardi'],
             ['Cardiac', u'Angina pectoris'],
             ['Respiratory', u'Halsirritation'],
             ['Musculoskeletal', u'Muskelkramp']]],
           ['Rare',
            [['Immune system', u'Kutana \xf6verk\xe4nslighetsreaktioner'],
             ['Immune system',
              u'Angio\xf6dem (huvudsakligen i ansikte,  munh\xe5la och svalg)'],
             ['Immune system', u'Andningssymtom (bronkospasm)'],
             ['Immune system', u'Anafylaktiska reaktioner inkl.  anafylaktisk chock'],
             ['Endocrine',
              u'Cushings syndrom, Cushingliknande  symtombild, binjurebarksuppression, h\xe4mmad l\xe4ngdtillv\xe4xt hos barn och ungdomar, minskad bent\xe4thet'],
             ['Metabolism', u'F\xf6rh\xf6jda blodglukosniv\xe5er'],
             ['Psychiatric',
              u'S\xf6mnsv\xe5righeter och  beteendest\xf6rningar, inklusive psykomotorisk hyperaktivitet och irritabilitet (fr\xe4mst hos barn)'],
             ['Eye', u'Katarakt, glaukom'],
             ['Cardiac',
              u'Hj\xe4rtarytmi (inklusive f\xf6rmaksflimmer,  supraventrikul\xe4r takykardi och extrasystolier)'],
             ['Respiratory', u'Paradoxal bronkospasm']]],
           ['Unknown', [['Psychiatric', u'Depression, aggression (fr\xe4mst hos']]]],
 '_pages': [8, 10],
 u'_rank': 30,
 u'_type': u'TSFU'}