{'_data': [['Very common', [['Respiratory', u'N\xe4sbl\xf6dning']]],
           ['Common', [['Respiratory', u'*Torrhet och irritation i n\xe4sa och svalg.']]],
           ['Very rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner, anafylaxi/anafylaktiska reaktioner, bronkospasm, utslag, \xf6dem i ansikte och mun'],
             ['Eye', u'***Glaukom, f\xf6rh\xf6jt intraokul\xe4rt tryck, katarakt'],
             ['Respiratory', u'**Nasal septumperforation']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 5,
 u'_type': u'MSFU'}