{'_data': [['Very common',
            [['GI', u'Diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Vascular', u'V\xe4rmevallningar'],
             ['Reproductive system',
              u'Gynekomasti och/eller Minskad libido, impotens br\xf6stsm\xe4rta, galaktorr\xe9']]],
           ['Common',
            [['Investigations', u'\xd6verg\xe5ende onormal leverfunktion'],
             ['GI', u'Diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Metabolism', u'\xd6kad aptit'],
             ['General', u'Tr\xf6tthet'],
             ['Hepato', u'Hepatit'],
             ['Psychiatric', u'S\xf6mnl\xf6shet']]],
           ['Uncommon', [['Hepato', u'Hepatit'], ['Reproductive system', u'Gynekomasti']]],
           ['Rare',
            [['Investigations',
              u'F\xf6rh\xf6jda blod-ureaniv\xe5er, f\xf6rh\xf6jda serumkreatininniv\xe5er'],
             ['Blood', u'Lymf\xf6dem Anemi, leukopeni, trombocytopeni'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk Domningar, f\xf6rvirring, nervositet'],
             ['Eye', u'Dimsyn'],
             ['GI',
              u'Ospecifika rubbningar i Ospecifika rubbningar i buken, halsbr\xe4nna, buken f\xf6rstoppning'],
             ['Renal', u'Urogenitala symtom'],
             ['Skin', u'Pruritus, Hudutslag ekkymos'],
             ['Musculoskeletal', u'Neuromuskul\xe4ra symtom'],
             ['Metabolism', u'Anorexi Anorexi'],
             ['Metabolism', u'B\xe4ltros'],
             ['Vascular', u'V\xe4rmevallningar H\xf6gt blodtryck'],
             ['General',
              u'\xd6dem, svaghet, \xd6dem sjukdomsk\xe4nsla, t\xf6rst, br\xf6stsm\xe4rtor'],
             ['Immune system', u'Lupusliknande syndrom'],
             ['Hepato', u'Leverdysfunktion, gulsot'],
             ['Reproductive system', u'Minskad libido, nedsatt spermieproduktion'],
             ['Psychiatric', u'\xc5ngest, depression Depression, \xe5ngest']]],
           ['Very rare',
            [['Blood',
              u'Hemolytisk anemi, megalocyt\xe4r anemi, methemoglobinemi, sulfhemoglobinemi'],
             ['Respiratory', u'Lungsymtom (t.ex. dyspn\xe9), interstitiell lungsjukdom'],
             ['Renal', u'M\xf6rkgul eller gr\xf6naktig missf\xe4rgning av urinen'],
             ['Skin',
              u'Fotosensibilitetsreaktione Fotosensibilitetsreaktioner, rerytem, s\xe5r, epidermal nekrolys'],
             ['Metabolism',
              u'Hyperglykemi, f\xf6rv\xe4rrande av diabetes mellitus Infektioner and infestationer'],
             ['Neoplasms', u'Neoplasm i br\xf6sten hos m\xe4n*'],
             ['Hepato',
              u'Kolestatisk ikterus, hepatisk encefalopati, levercellsnekros, d\xf6dlig hepatotoxicitet']]],
           ['Unknown', [['Vascular', u'Tromboembolism']]]],
 '_pages': [3, 6],
 u'_rank': 35,
 u'_type': u'LSFU'}