{'_data': [['Common', [['Skin', u'Kl\xe5da.']]],
           ['Uncommon',
            [['Skin',
              u'Lokalt br\xe4nnande k\xe4nsla. Papul\xf6s rosacealiknande dermatit (ansiktshud).']]],
           ['Very rare',
            [['Infections',
              u'Sekund\xe4rinfektion. Immunsystemet \xd6verk\xe4nslighetsreaktioner (sensibilisering f\xf6r'],
             ['Infections', u'imidurea, konserveringsmedel i kr\xe4m).'],
             ['Endocrine', u'Binjurebarkh\xe4mning.'],
             ['Vascular', u'Kapill\xe4rsk\xf6rhet (ekkymoser).'],
             ['Skin',
              u'Atrofi, striae. Hypertrikos. Hypopigmentering. Hyperpigmentering. Allergisk kontaktdermatit. Exacerbation av dermatosen. Pustul\xf6s psoriasis.']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'LSFU'}