{'_data': [['Common',
            [['Psychiatric', u'S\xf6mnsv\xe5righeter'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Dyspepsi, buksm\xe4rtor, illam\xe5ende']]],
           ['Rare',
            [['Skin', u'\xd6verk\xe4nslighetsreaktioner, s\xe5som hudutslag, urtikaria'],
             ['Musculoskeletal', u'Myalgi, muskelsvaghet, myopati']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Nervous system',
              u'Parestesi, dysestesi och hypestesi, \xe4ven k\xe4nda f\xf6r att ha samband med de underliggande hyperlipidemisjukdomarna'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Andra hudreaktioner (t.ex. eksem, dermatit, bull\xf6st exantem), ansikts\xf6dem, angio\xf6dem'],
             ['Musculoskeletal',
              u'Rabdomyolys, myosit, lupus erytematosus-liknande reaktioner F\xf6ljande biverkningar har rapporterats f\xf6r vissa statiner: \u2212s\xf6mnst\xf6rningar, inklusive insomningssv\xe5righeter och mardr\xf6mmar \u2212minnesf\xf6rlust \u2212nedsatt sexuell f\xf6rm\xe5ga \u2212depression \u2212interstitiell lungsjukdom har rapporterats i enstaka fall, s\xe4rskilt vid l\xe5ngtidsbehandling (se avsnitt 4.4).']]]],
 '_pages': [8, 10],
 u'_rank': 13,
 u'_type': u'LSFU'}