{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['Skin', u'myalgi'],
             ['General',
              u'svullnad vid injektionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet, induration vid injektionsst\xe4llet, rodnad vid injektionsst\xe4llet, tr\xf6tthet, allm\xe4n sjukdomsk\xe4nsla och frossa.'],
             ['Systemic',
              u'Sm\xe4rta, induration och hudrodnad, allm\xe4n sjukdomsk\xe4nsla, myalgi, huvudv\xe4rk och tr\xf6tthet. Biverkningar under veckan efter vaccinationen hos 80 sp\xe4dbarn 6-11 m\xe5nader gamla och 82 sm\xe5barn 12-35 m\xe5nader gamla som f\xe5tt 7,5 \xb5g- formuleringen rapporterades enligt nedanst\xe5ende tabell'],
             ['Systemic',
              u'reaktioner som rapporterades hos233 sp\xe4dbarn och sm\xe5barn i \xe5ldrarna 6 till 35 m\xe5nader: \xd6mhet, hudrodnad, irritabilitet, onormalt gr\xe5tande, s\xf6mnighet, diarr\xe9 och f\xf6r\xe4ndrade \xe4tvanor. Induration var en vanlig reaktion hos sm\xe5barn men var mindre vanlig hos sp\xe4dbarn. Uppf\xf6ljning efter marknadsintroduktion Focetria H1N1v Ut\xf6ver biverkningarna som har rapporterats under de kliniska pr\xf6vningarna, har f\xf6ljande rapporterats under uppf\xf6ljning efter marknadsintroduktion f\xf6r Focetria H1N1v']]],
           ['Common',
            [['Skin', u'svettning'],
             ['Skin', u'artralgi'],
             ['GI', u'Illam\xe5ende'],
             ['General', u'ekkymos vid injektionsst\xe4llet och feber']]],
           ['Uncommon', [['Skin', u'urticaria'], ['General', u'influensaliknande sjukdom']]],
           ['Rare',
            [['Nervous system', u'konvulsioner'],
             ['Skin', u'\xf6gonsvullnad Muskuloskeletala systemet, bindv\xe4v och ben'],
             ['General',
              u'anafylaxi De vanliga reaktionerna f\xf6rsvinner vanligen inom 1\u20132 dagar utan behandling.'],
             ['Immune system', u'S\xe4llsynta \xd6verg\xe5ende trombocytopeni.']]],
           ['Very rare',
            [['Immune system',
              u'Mycket s\xe4llsynta Vaskulit med \xf6verg\xe5ende njurp\xe5verkan och erythema exsudativum multiforme. Neurologiska sjukdomar som encefalomyelit och Guillain-Barr\xe9s syndrom. Tiomersal Detta l\xe4kemedel inneh\xe5ller tiomersal (en kvicksilverf\xf6rening) som konserveringsmedel och det \xe4r d\xe4rf\xf6r m\xf6jligt att sensibiliseringsreaktioner upptr\xe4der (se avsnitt 4.4).']]],
           ['Unknown',
            [['Systemic',
              u'3% 1% Feber 39\xb0C till 39,9\xb0C 0% 1% Feber > 40\xb0 C 0% 0% Andra biverkningar 13% 15% Ungdomar (9 till 17 \xe5r) N=95 N=94 N\xe5gon biverkning 67% 55% Lokala 60% 49% Systemiska 38% 26% Feber > 38\xb0C till 38,9\xb0C 2% 1% Feber 39\xb0C to 39,9\xb0C 0% 0% Feber > 40\xb0C 0% 0% Andra biverkningar 11% 9% Data hos barn och ungdomar i \xe5ldrarna 3-17 \xe5r antyder en liten minskning av reaktogeniciteten efter den andra dosen, utan \xf6kningar av feberfrekvensen.'],
             ['Systemic',
              u'Feber >38\xb0C till 38,9\xb0C 9% 6% Feber 39\xb0C till 39,9\xb0C 2% 4% Feber > 40\xb0C 0% 0% Andra biverkningar 29% 28% Sm\xe5barn (12 till 35 m\xe5nader) N=82 N=81 N\xe5gon biverkning 70% 70% Lokala 50% 48% Systemiska 55% 44% Feber >38\xb0C till 38,9\xb0C 10% 11% Feber 39\xb0C till 39,9\xb0C 4% 1% Feber > 40\xb0C 1% 0% Andra biverkningar 21% 22% Data fr\xe5n sp\xe4dbarn och sm\xe5barn i \xe5ldrarna 6-35 m\xe5nader tyder p\xe5 en liten minskning i reaktogenicitet efter den andra dosen, och ingen \xf6kning av feberfrekvensen.'],
             ['Blood', u'Lymfadenopati.'],
             ['Cardiac',
              u'Hj\xe4rtklappning, takykardi. Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet Asteni'],
             ['Musculoskeletal', u'Muskelsvaghet, sm\xe4rtor i extremiteter.'],
             ['Respiratory', u'Hosta.'],
             ['Skin',
              u'Generaliserade hudreaktioner i form av pruritus, urtikaria eller icke-specifika utslag; angio\xf6dem.'],
             ['GI',
              u'St\xf6rningar i magtarmkanalen som illam\xe5ende, kr\xe4kningar, buksm\xe4rtor och diarr\xe9.'],
             ['Nervous system',
              u'18 Huvudv\xe4rk, yrsel, s\xf6mnighet, synkope. Neurologiska sjukdomarsom neuralgi, parestesi, konvulsioner och neurit.'],
             ['Immune system',
              u'Allergiska reaktioner, anafylaxi inklusive dyspn\xe9, bronkospasm, laryngealt \xf6dem, som i s\xe4llsynta fall leder till chock. Dessutom har f\xf6ljande biverkningar rapporterats vid uppf\xf6ljning efter marknadsintroduktion av s\xe4songsbundna trivalenta vacciner i alla \xe5ldersgrupper och med det MF59-adjuvanterade, s\xe4songsbundna trivalenta vaccinet med liknande sammans\xe4ttning som Focetria (ytantigen, inaktiverat, adjuvanterat med MF59C.1), licensierade f\xf6r anv\xe4ndning till \xe4ldre patienter \xf6ver 65 \xe5r']]]],
 '_pages': [4, 7],
 u'_rank': 26,
 u'_type': u'LSFU'}