{'_data': [['Common', [['GI', u'ledsvullnad']]],
           ['Uncommon',
            [['GI',
              u'illam\xe5ende, kr\xe4kningar, gastrit, esofagit*, esofaguserosioner*, melena']]],
           ['Rare',
            [['Immune system', u'Metabolism och   '],
             ['GI',
              u'esofagusstriktur*, s\xe5r i munh\xe5la/svalg*, \xf6vre gastrointestinala PUB (perforation, s\xe5r, bl\xf6dning) Hud och subkutan Vanliga: alopeci , kl\xe5da v\xe4vnad: Mindre vanliga: hudutslag, erytem'],
             ['GI',
              u'hudutslag med fotosensitivitet, allvarliga hudreaktioner inkluderande Stevens-Johnsons syndrom och toxisk epidermal nekrolys Muskuloskeletala Mycket vanliga: muskuloskeletal sm\xe4rta (ben, muskel eller led) vilken systemet och bindv\xe4v: ibland kan vara sv\xe5r'],
             ['GI',
              u'osteonekros i k\xe4ken , atypiska subtrokant\xe4ra och diafys\xe4ra femurfrakturer (bisfosfonat klassbiverkning) \u2534 Allm\xe4nna symtom Vanliga: asteni , perifert \xf6dem och/eller symtom vid Mindre vanliga: \xf6verg\xe5ende symtom som vid en akutfasreaktion (myalgi, administreringsst\xe4llet: sjukdomsk\xe4nsla och i s\xe4llsynta fall feber), vanligtvis i samband med behandlingsstart Se avsnitt 4.4 Frekvensen i kliniska studier var likv\xe4rdig i den aktiva kontrollgruppen respektive placebogruppen. * Se avsnitt 4.2 och 4.4 Denna biverkning har rapporterats vid uppf\xf6ljning efter marknadsintroduktionen. Frekvensen s\xe4llsynt ber\xe4knades fr\xe5n relevanta kliniska studier. \u2534 Rapporterade efter marknadsf\xf6ring.']]],
           ['Unknown',
            [['GI',
              u'Buksm\xe4rta 3,7 3,0 6,6 4,8 Dyspepsi 2,7 2,2 3,6 3,5 Sura uppst\xf6tningar 1,9 2,4 2,0 4,3 Illam\xe5ende 1,9 2,4 3,6 4,0 Buksp\xe4nning 1,0 1,4 1,0 0,8 F\xf6rstoppning 0,8 1,6 3,1 1,8 Diarr\xe9 0,6 0,5 3,1 1,8 Dysfagi 0,4 0,5 1,0 0,0 Flatulens 0,4 1,6 2,6 0,5 Gastrit 0,2 1,1 0,5 1,3 Mags\xe5r 0,0 1,1 0,0 0,0 Esofaguss\xe5r 0,0 0,0 1,5 0,0 Muskuloskeletala Muskuloskeletal 2,9 3,2 4,1 2,5 sm\xe4rta (ben, muskel eller led) Muskelkramp 0,2 1,1 0,0 1,0 Neurologiska Huvudv\xe4rk 0,4 0,3 2,6 1,5'],
             ['GI', u'esofaguss\xe5r*, dysfagi*, buksp\xe4nning, sura uppst\xf6tningar']]]],
 '_pages': [5, 6],
 u'_rank': 8,
 u'_type': u'LSFU'}