{'_data': [['Very common',
            [['Vascular', u'bl\xf6dning'],
             ['GI', u'f\xf6rstoppning, nekrotiserande stomatit, dysfagi'],
             ['General',
              u'sm\xe4rta, sm\xe4rta vid injektionsst\xe4llet, ansiktssm\xe4rta, ansikts\xf6dem'],
             ['Injury', u'\xe4rr']]],
           ['Common',
            [['Infections', u'lokala infektioner'],
             ['Blood', u'anemi'],
             ['Nervous system', u'yrsel, br\xe4nnande k\xe4nsla'],
             ['GI', u'kr\xe4kningar, illam\xe5ende, muns\xe5r'],
             ['Skin',
              u'bl\xe5sor, erytem, hyperpigmenteringar, ljusk\xe4nslighetsreaktioner, hudnekros'],
             ['Musculoskeletal', u'trismus'],
             ['General', u'feber, reaktion vid injektionsst\xe4llet, \xf6dem'],
             ['Injury', u'v\xe4rmebr\xe4nnskada, solsveda']]]],
 '_pages': [6, 6],
 u'_rank': 12,
 u'_type': u'LSFU2'}