{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Buksm\xe4rta, diarr\xe9, illam\xe5ende, kr\xe4kningar']]],
           ['Common',
            [['Metabolism', u'Hypokalcemi'], ['GI', u'F\xf6rstoppning, dyspepsi, flatulens']]],
           ['Uncommon',
            [['Infections', u'Gastroenterit, laryngit'],
             ['Blood', u'Eosinofili'],
             ['Endocrine', u'Hyperparatyreoidism'],
             ['Metabolism',
              u'Hyperkalcemi, hyperglykemi, hyperfosfatemi, hypofosfatemi, anorexi, \xf6kad aptit'],
             ['Nervous system', u'Yrsel, smakf\xf6r\xe4ndringar'],
             ['Ear', u'Svindel'],
             ['GI',
              u'Rapningar, matsm\xe4ltningsbesv\xe4r, irritabel tarm (IBS), muntorrhet, esofagit, stomatit, l\xf6s avf\xf6ring, tandbesv\xe4r, gastrointestinala st\xf6rningar UNS (utan n\xe4rmare specifikation)'],
             ['Skin', u'Alopeci, \xf6kad svettning'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, osteoporos Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Musculoskeletal',
              u'Asteni, br\xf6stsm\xe4rtor, tr\xf6tthet, sjukdomsk\xe4nsla, perifert \xf6dem, sm\xe4rtor, t\xf6rst'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er av aluminium i blodet, f\xf6rh\xf6jd GGT-niv\xe5, f\xf6rh\xf6jda levertransaminaser, f\xf6rh\xf6jt alkaliskt fosfatas, viktminskning']]]],
 '_pages': [4, 5],
 u'_rank': 15,
 u'_type': u'LSFU'}