{'_data': [['Common',
            [['Blood',
              u'Mild trombocytopeni (typ I), som vanligen \xe4r reversibel  under behandlingen.'],
             ['Vascular', u'Bl\xf6dning'],
             ['Hepato', u'\xd6verg\xe5ende transaminasstegring'],
             ['General', u'Subkutant hematom vid injektionsst\xe4llet, sm\xe4rta vid']]],
           ['Uncommon', [['Immune system', u'\xd6verk\xe4nslighet']]],
           ['Unknown',
            [['Blood', u'Immunologiskt medierad heparin-inducerad trombocytopeni'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['GI', u'Retroperitoneala bl\xf6dningar, i n\xe5got fall fatal'],
             ['Injury', u'Spinalt eller epiduralt hematom']]]],
 '_pages': [9, 10],
 u'_rank': 9,
 u'_type': u'TSFU'}