<<<<<<< HEAD
{'_data': [['Unknown',
            [['Ear',
              u'balansorgan Immunsystemet \xd6verk\xe4nslighet F\xf6rs\xe4mring av autoimmuna sjukdomar Centrala och Huvudv\xe4rk Somnolens Meningism perifera Yrsel nervsystemet Neurit av olika grad Krampanfall Encefalit \xd6gon Synst\xf6rningar Fotofobi \xd6gonsm\xe4rta Hj\xe4rtat Takykardi Magtarmkanale Illam\xe5ende Kr\xe4kningar Diarr\xe9 n Magont Hud och Utslag subkutan (erytemat\xf6sa, v\xe4vnad makulopapul \xf6sa, vesikul\xe4ra) Pruritus Exantem Urticaria Erytem Muskuloskeletal Myalgi Nacksm\xe4rta a systemet och Artalgi bindv\xe4v Allm\xe4nna Reaktioner Tr\xf6tthet Frossbrytning symptom vid Sjukdoms Pyrexi ar och/eller injektions / k\xe4nsla Influensalikn symptom vid infusionsst\xe4 ande sjukdom administreringss llet Asteni t\xe4llet \xd6dem G\xe5ngrubbnin g']]]],
 '_pages': [3, 4],
 u'_rank': 1,
 u'_type': u'LSFU'}
=======
{'_data': [['Very common', [['General', u'Reaktioner vid injektions / infusionsst\xe4 llet']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Musculoskeletal', u'Myalgi Artalgi'],
             ['General', u'Tr\xf6tthet Sjukdoms k\xe4nsla']]],
           ['Uncommon',
            [['Blood', u'Lymfadenopati'],
             ['Ear', u'Svindel'],
             ['GI', u'Kr\xe4kningar'],
             ['General', u'Pyrexi ar']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'Somnolens'],
             ['GI', u'Diarr\xe9 Magont']]],
           ['Unknown',
            [['Immune system', u'F\xf6rs\xe4mring av autoimmuna sjukdomar'],
             ['Nervous system', u'Meningism Yrsel Neurit av olika grad Krampanfall Encefalit'],
             ['Eye', u'Synst\xf6rningar Fotofobi \xd6gonsm\xe4rta'],
             ['Cardiac', u'Takykardi'],
             ['Skin',
              u'Utslag (erytemat\xf6sa, makulopapul \xf6sa, vesikul\xe4ra) Pruritus Exantem Urticaria Erytem'],
             ['Musculoskeletal', u'Nacksm\xe4rta'],
             ['General', u'Frossbrytning Influensalikna nde sjukdom Asteni']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 19,
 u'_type': u'MSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
