{'_data': [['Common',
            [['GI', u'Kr\xe4kningar'],
             ['General', u'Venintolerans, tromboflebit'],
             ['Hepato', u'Hyperbilirubinemi, ikterus, \xf6kade v\xe4rden p\xe5 leverenzymer']]],
           ['Uncommon',
            [['GI', u'Diarr\xe9, illam\xe5ende, buksm\xe4rtor'],
             ['Skin',
              u'Utslag (erytemat\xf6sa, makulopapul\xf6sa och pustul\xf6sa), urtikaria, pruritus'],
             ['General', u'Asteni, tr\xf6tthet, sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Nervous system', u'D\xe5sighet'],
             ['Metabolism', u'Anorexia'],
             ['Immune system', u'Allergiska reaktioner']]],
           ['Very rare',
            [['Blood', u'Pancytopeni, leukopeni, trombocytopeni, anemi (se avsnitt 4.4).'],
             ['Renal',
              u'Njursvikt Akut njursvikt har beskrivits hos patienter med ikterus, speciellt i samband med andra faktorer som \xe4r predisponerande f\xf6r njursvikt.'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Hepato',
              u'Hepatorenalt syndrom, abnorm leverfunktion, s\xe5som hyperbilirubinemi med eller utan ikterus, och \xf6kade v\xe4rden p\xe5 leverenzymer, s\xe5som alkaliska fosfataser och transaminaser (se avsnitt 4.4).']]],
           ['Unknown',
            [['Blood', u'Agranulocytos (se avsnitt 4.4).'],
             ['Musculoskeletal', u'rhabdomyolys, se avsnitt 4.5.'],
             ['Hepato', u'gallstas']]]],
 '_pages': [3, 4],
 u'_rank': 16,
 u'_type': u'LSFU'}