{'_data': [['Very common',
            [['Vascular', u'Hypotension'],
             ['Vascular', u'Dyspn\xe9'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['Renal', u'uremi, hypostenuria, tubul\xe4r njuracidos och nefrokalcinos'],
             ['Renal', u'Frossa, pyrexi'],
             ['Investigations', u'Hypokalemi, f\xf6rh\xf6jt blodkreatinin']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Hypomagnesemi'],
             ['Hepato', u'Leverfunktionsrubbning'],
             ['Skin', u'Utslag']]],
           ['Uncommon', [['Renal', u'Flush']]],
           ['Unknown',
            [['Blood',
              u'Agranulocytos, koagulationsrubbningar, eosinofili, leukocytos, leukopeni och trombocytopeni'],
             ['Immune system', u'Anafylaxliknande/anafylaktiska reaktioner'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system',
              u'Kramper, huvudv\xe4rk, encefalopati, neurologiska symptom och perifer neuropati'],
             ['Eye', u'Dimsyn, diplopi'],
             ['Ear', u'D\xf6vhet, tinnitus och vertigo'],
             ['Cardiac',
              u'Arytmier inklusive ventrikul\xe4r fibrillation, hj\xe4rtstillest\xe5nd och hj\xe4rtsvikt'],
             ['Vascular',
              u'Hypertension, chock Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['GI',
              u'Dyspepsi, hemorragisk gastroenterit, \xf6vre buksm\xe4rtor, diarr\xe9, melena'],
             ['Hepato', u'Akut leversvikt, gulsot'],
             ['Skin',
              u'Maculopapul\xf6st utslag, kl\xe5da, hudexfoliation, toxisk epidermal nekrolys, Stevens-Johnsons syndrom'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Renal',
              u'Akut njursvikt, anuri, nefrogen diabetes insipidus, oliguri och nedsatt njurfunktion Allm\xe4nna symptom och/eller symptom vid administreringsst\xe4llet'],
             ['Investigations',
              u'Hyperkalemi, viktminskning De flesta patienter f\xe5r feberfrossbrytningar, huvudv\xe4rk, myalgi och/eller artralgi, olustk\xe4nslor, anorexi, illam\xe5ende, kr\xe4kningar och hypotension under de f\xf6rsta dagarnas behandling, men dessa reaktioner upph\xf6r vanligen under fortsatt behandling. Symptomen kan lindras genom administrering av antipyretika, antihistaminer, antiemetika, eller analgetika (t ex Petidin), genom reduktion av infusionshastigheten eller genom varannandagsdosering av amfotericin B. Injektion av l\xe5ga doser av kortikosteroider intraven\xf6st strax f\xf6re eller under amfotericin B infusion kan minska uppkomsten av feberreaktioner. Dos och duration f\xf6r s\xe5dan kortikosteroidterapi b\xf6r minimeras. Parenterala kortikosteroider b\xf6r bara ges vid speciellt sv\xe5ra biverkningar. Administrering av elektrolyter (natrium, kalium, magnesium) \xe4r ofta n\xf6dv\xe4ndig f\xf6r att motverka tubul\xe4r acidos och korrigera t ex hypokalemi. Risken f\xf6r tromboflebit kan minskas genom att s\xe4nka koncentrationen amfotericin B i infusionsl\xf6sningen, reducera infusionshastigheten, variera injektionsst\xe4llet, ge l\xe4kemedlet varannan dag, anv\xe4nda en kanyl med mindre diameter eller genom samtidig administrering av heparin (1000 enheter per infusion). Extravasering kan orsaka kemisk irritation. Allvarlig, best\xe5ende njurskada har rapporterats efter h\xf6ga doser. Risken f\xf6refaller \xf6ka n\xe4r den totala dosen \xf6verstiger 5 g. Samtidig diuretikabehandling kan vara en predisponerande faktor f\xf6r njurskada, medan natriumtillskott skulle kunna minska njurtoxiciteten. Leukoencefalopati har rapporterats hos patienter som f\xe5r helkroppsstr\xe5lning. Normocyt\xe4r, normokrom anemi kan utvecklas efter flera veckors behandling och kan n\xf6dv\xe4ndigg\xf6ra blodtransfusion.']]]],
 '_pages': [3, 5],
 u'_rank': 25,
 u'_type': u'LSFU'}