{'_data': [['Common',
            [['Metabolism',
              u'Hypokalemi, hypokloremisk alkalos, hyponatremi, hypomagnesemi, hypokalcemi, hyperurikemi.'],
             ['Blood', u'Hypovolemi vid intensiv terapi.']]],
           ['Uncommon', [['Metabolism', u'Illam\xe5ende, kr\xe4kningar.']]],
           ['Rare',
            [['Metabolism', u'Hyperglykemi'],
             ['Skin',
              u'Hudreaktioner, t ex kl\xe5da, urtikaria, erytema multiforme, exfoliativ dermatit och purpura. Vaskulit.'],
             ['Blood', u'Trombocytopeni, leukopeni, agranulocytos.'],
             ['Ear',
              u'Reversibel h\xf6rselneds\xe4ttning och tinnitus. (Vid h\xf6ga plasmakoncentrationer).'],
             ['Renal', u'Interstitiell nefrit']]],
           ['Unknown', [['Skin', u'Bull\xf6s pemfigoid']]]],
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'LSFU'}