{'_data': [['Very common',
            [['Nervous system', u'Perifer neuropati.'], ['Investigations', u'Viktminskningar.']]],
           ['Common',
            [['Infections', u'Sinuit, hudpapillom, influensa, pneumoni, \xf6roninfektion.'],
             ['Blood', u'Lymfadenopati.'],
             ['Metabolism',
              u'Aptitneds\xe4ttning, anorexi, hypertriglyceridemi, diabetes mellitus.'],
             ['Psychiatric', u'\xc5ngest, mardr\xf6mmar, irritabilitet.'],
             ['Nervous system', u'Hypoestesi, st\xf6rd uppm\xe4rksamhet, tremor.'],
             ['Eye', u'Konjunktivit.'],
             ['Ear', u'Vertigo.'],
             ['Respiratory', u'N\xe4st\xe4ppa.'],
             ['GI', u'Pankreatit, gastroesofageal refluxsjukdom.'],
             ['Skin', u'Torr hud, eksem, seborr\xe9, erytem, akne.'],
             ['Musculoskeletal', u'Myalgi.'],
             ['Renal', u'Njursten.'],
             ['General', u'Influensaliknande symtom, svaghet.'],
             ['Investigations',
              u'\xd6kning av triglycerider i blodet, hematuri. Dessutom har det f\xf6rekommit ett f\xe5tal \xf6verk\xe4nslighetsreaktioner f\xf6rknippat med enfuvirtid och i n\xe5gra fall har \xe5terfall av \xf6verk\xe4nsligheten intr\xe4ffat vid f\xf6rnyad exponering (se avsnitt 4.4). Hos HIV-infekterade patienter med sv\xe5r immunbrist vid tidpunkten f\xf6r ins\xe4ttande av antiretroviral kombinationsterapi, kan en inflammatorisk reaktion mot asymtomatiska eller kvarvarande opportunistiska infektioner uppst\xe5 (se avsnitt 4.4). Fall av osteonekros har rapporterats, speciellt hos patienter med k\xe4nda riskfaktorer, framskriden HIV sjukdom eller l\xe5ngvarig exponering f\xf6r antiretroviral kombinationsbehandling (CART). Frekvensen av detta \xe4r ok\xe4nd (se avsnitt 4.4). 19 Avvikande laboratoriev\xe4rden Majoriteten av patienterna hade ingen f\xf6r\xe4ndring i toxicitetsgrad av n\xe5gon laboratorieparameter under studien f\xf6rutom de som listas i tabell 3. Till och med vecka 48 intr\xe4ffade eosinofili [h\xf6gre \xe4n \xf6vre normalv\xe4rdet av > 0,7 x 10 /l] med en h\xf6gre frekvens bland patienter i gruppen som fick behandling med Fuzeon (12,4 patienter med biverkan per 100 patient\xe5r) j\xe4mf\xf6rt med enbart OB-behandling (5,6 patienter med biverkan per 100 patient\xe5r). D\xe5 ett h\xf6gre gr\xe4nsv\xe4rde f\xf6r eosinofili anv\xe4ndes (> 1,4 x 10 /l) var den exponeringsanpassade frekvensen av eosinofili lika i b\xe5da grupperna (1,8 patienter med biverkan per 100 patient\xe5r).']]]],
 '_pages': [4, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}