{'_data': [['Very common',
            [['General',
              u'000) vid behandling med gabapentin. Fall av hemorragisk pankreatit (se avsnitt 4.4), hypotoni, bradykardi, synkope, f\xf6rmaksflimmer, onormalt EKG och makulopapul\xf6sa utslag har rapporterats hos patienter som erh\xe5llit gabapentin. Laboratoriev\xe4rden \u2013 Kliniska manifestationer F\xf6rh\xf6jd aktivitet av leverenzymer har rapporterats i kombination med andra antiepileptika. En m\xf6jligen dosberoende \xf6kning av anfallsfrekvensen har observerats hos ett f\xe5tal patienter. Dosrelaterade upprepade anfall av okarakt\xe4ristisk typ har \xe4ven rapporterats.']]],
           ['Common',
            [['Blood', u'leukopeni'],
             ['Psychiatric',
              u'nervositet, depressiv sinnesst\xe4mning, desorientering, f\xf6rvirring och k\xe4nslom\xe4ssig labilitet, oro. Dessutom har aggressivt beteende och hyperkinesi rapporterats i kliniska studier p\xe5 barn under 12 \xe5r.'],
             ['Nervous system',
              u'ataxi, nystagmus, tremor, amnesi, onormala k\xe4nself\xf6rnimmelser s\xe5som parestesier, ryckningar, f\xf6rst\xe4rkta eller nedsatta reflexer, bortfall av reflexer, nedsatt vakenhet, nedsatt koncentrationsf\xf6rm\xe5ga, tankest\xf6rningar, talrubbningar, f\xf6rs\xe4mrat minne, dysartri, g\xe5ngrubbning'],
             ['Eye', u'synst\xf6rningar som amblyopi, diplopi, nedsatt syn'],
             ['Cardiac', u'vasodilatation, hypertoni'],
             ['Respiratory', u'rinit, faryngit, hosta'],
             ['GI',
              u'kr\xe4kningar, illam\xe5ende, diarr\xe9, muntorrhet, dyspepsi, f\xf6rstoppning, buksm\xe4rta, dental anomali, gingivit, sjukdomsk\xe4nsla'],
             ['Skin', u'kl\xe5da, purpura, utslag'],
             ['Musculoskeletal', u'artralgi, myalgi, l\xe4ndryggssm\xe4rta, benfraktur'],
             ['Renal', u'inkontinens, urinv\xe4gsinfektion'],
             ['Reproductive system', u'impotens'],
             ['General',
              u'd\xe5sighet, tr\xf6tthet, s\xf6mnighet, somnolens, utmattning, yrsel, huvudv\xe4rk, s\xf6mnl\xf6shet, vikt\xf6kning, anorexi, perifert eller generellt \xf6dem, asteni, \xf6kad aptit']]],
           ['Uncommon',
            [['Blood', u'blodglukossv\xe4ngningar'],
             ['Psychiatric', u'depression, psykoser/hallucinationer, fientlighet'],
             ['Nervous system', u'f\xf6rvirring, hypestesi'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'flatulens'],
             ['General', u'olycksfall, svindel']]],
           ['Rare',
            [['Blood',
              u'trombocytopeni, f\xf6r\xe4ndringar i glukosv\xe4rdet hos diabetespatienter'],
             ['Nervous system',
              u'r\xf6relserubbningar (t.ex. koreoatetos, dyskinesi, dystoni)'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'hj\xe4rtklappning'],
             ['Respiratory', u'\xf6vre luftv\xe4gsinfektion'],
             ['Skin', u'urtikaria, alopeci, angio\xf6dem'],
             ['Renal', u'akut njursvikt'],
             ['General',
              u'uts\xe4ttningsreaktion (sm\xe4rta, svettningar, br\xf6stsm\xe4rta) Allergiska reaktioner (Stevens-Johnsons syndrom och erythema multiforme) \xe4r mycket s\xe4llsynta (<']]],
           ['Unknown',
            [['Skin',
              u'l\xe4kemedelsrelaterade utslag med eosinofili och systemiska symtom (se avsnitt 4.4)']]]],
 '_pages': [5, 7],
 u'_rank': 28,
 u'_type': u'LSFU'}