{'_data': [['Very common',
            [['Infections', u'Virusinfektion'],
             ['Nervous system', u'Somnolens, yrsel, ataxi'],
             ['General', u'Utmattning, feber']]],
           ['Common',
            [['Infections',
              u'Pneumoni, luftv\xe4gsinfektion, urinv\xe4gsinfektion, infektion, otitis media'],
             ['Blood', u'Leukopeni'],
             ['Metabolism', u'Anorexi, \xf6kad aptit'],
             ['Psychiatric',
              u'Fientlighet, f\xf6rvirring och k\xe4nslom\xe4ssig labilitet, depression, oro, nervositet, onormala tankar'],
             ['Nervous system',
              u'Kramper, hyperkinesi, dysartri, amnesi, tremor, insomnia, huvudv\xe4rk, k\xe4nself\xf6rnimmelser som parestesi, hypestesi, onormal koordinationsf\xf6rm\xe5ga, nystagmus, \xf6kade/minskade eller fr\xe5nvaro av reflexer.'],
             ['Eye', u'Synst\xf6rningar som amblyopi, diplopi'],
             ['Ear', u'Vertigo'],
             ['Vascular', u'Hypertoni, vasodilatation'],
             ['Respiratory', u'Dyspn\xe9, bronkit, faryngit, hosta, rinit'],
             ['GI',
              u'Kr\xe4kningar, illam\xe5ende, dental anomali, gingivit, diarr\xe9, buksm\xe4rta, dyspepsi, f\xf6rstoppning, muntorrhet eller halstorrhet, flatulens'],
             ['Skin',
              u'Ansikts\xf6dem, purpura oftast beskrivet som bl\xe5m\xe4rken efter fysiskt trauma, hudutslag, pruritus, akne.'],
             ['Musculoskeletal', u'Artralgi, myalgi, ryggsm\xe4rta, ryckningar'],
             ['Reproductive system', u'Impotens'],
             ['General',
              u'Perifert \xf6dem, onormal g\xe5ng, asteni, sm\xe4rta, sjukdomsk\xe4nsla, influensasymtom'],
             ['Investigations', u'Minskat antal vita blodkroppar, vikt\xf6kning'],
             ['Investigations',
              u'Olycksfall, fraktur, skrubbs\xe5r Under behandling med gabapentin har fall av akut pankreatit rapporterats. Orsakssambandet med gabapentin \xe4r oklart (se avsnitt 4.4) Hos patienter p\xe5 hemodialys p\xe5 grund av njursvikt i terminalfas har myopati med f\xf6rh\xf6jda kreatinkinasniv\xe5er rapporterats. Infektioner i andningsv\xe4garna, otitis media, kramper och bronkit rapporterades endast i kliniska studier p\xe5 barn. Dessutom var aggressivt beteende och hyperkinesi vanligen rapporterade biverkningar i kliniska studier p\xe5 barn.']]],
           ['Uncommon',
            [['Immune system', u'Allergiska reaktioner (t.ex. urtikaria)'],
             ['Nervous system', u'Hypokinesi'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['General', u'generaliserat \xf6dem'],
             ['Investigations',
              u'F\xf6rh\xf6jda v\xe4rden vid leverfunktionstester, SGOT (ASAT), SGPT (ALAT) och bilirubin']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system',
              u'\xd6verk\xe4nslighetssyndrom, en systemisk reaktion med varierande presentation som kan inkludera feber, utslag, hepatit, lymfadenopati, eosinofili och ibland andra tecken och symtom'],
             ['Psychiatric', u'Hallucinationer'],
             ['Nervous system',
              u'Andra r\xf6relserubbningar (t.ex. koreoatetos, dyskinesi, dystoni).'],
             ['Ear', u'Tinnitus'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit, gulsot'],
             ['Skin',
              u'Stevens-Johnsons syndrom, angio\xf6dem, erytema multiforme, alopeci, l\xe4kemedelsutslag med eosinofili och systemiska symtom (se avsnitt 4.4)'],
             ['Musculoskeletal', u'Myoklonus'],
             ['Renal', u'Akut njursvikt, inkontinens'],
             ['Reproductive system', u'Br\xf6sthypertrofi, gynekomasti'],
             ['General',
              u'Uts\xe4ttningsreaktioner (oftast oro, insomnia, illam\xe5ende, sm\xe4rta, svettningar), br\xf6stsm\xe4rta. Pl\xf6tslig of\xf6rklarlig d\xf6d har rapporterats men ett orsakssamband med gabapentinbehandling har inte fastst\xe4llts.'],
             ['Investigations',
              u'Fluktuerande blodglukosv\xe4rden hos patienter med diabetes Skada och f\xf6rgiftning']]]],
 '_pages': [6, 8],
 u'_rank': 37,
 u'_type': u'LSFU'}