{'_data': [['Very common', [['GI', u'Illam\xe5ende; Kr\xe4kningar']]],
           ['Common',
            [['Metabolism', u'Minskad aptit; Anorexi'],
             ['Psychiatric', u'Halluci-nationer; Depression'],
             ['Nervous system', u'Syncope; Yrsel; Tremor; Huvudv\xe4rk; D\xe5sighet; Letargi'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Hypertension'],
             ['GI',
              u'Buksm\xe4rtor; Buksm\xe4rtor i \xf6vre magtarm-kanalen; Diarr\xe9; Dyspepsi; Obehagsk\xe4nsl a i magen; Obehagsk\xe4nsl a i buken'],
             ['Skin', u'Hyperhidros'],
             ['Musculoskeletal', u'Muskel-spasmer'],
             ['General', u'Tr\xf6tthet; Asteni; Sjukdoms-k\xe4nsla'],
             ['Investigations', u'Viktminsknin g'],
             ['Injury', u'Fall']]],
           ['Uncommon',
            [['Metabolism', u'Uttorkning'],
             ['Psychiatric', u'Synhalluci-nationer; H\xf6rselhalluci-nationer'],
             ['Nervous system', u'Parestesi; Dysgeusi; Hypersomni'],
             ['Eye', u'Dimsyn'],
             ['Ear', u'Tinnitus'],
             ['Cardiac',
              u'Supraventrikul\xe4r extrasystole; Atrioventrikul\xe4r block grad 1; Sinus-bradykardi; Palpitationer'],
             ['Vascular', u'Hypotension; Flushing'],
             ['GI', u'Ulkningar'],
             ['Musculoskeletal', u'Muskelsvaghet'],
             ['Investigations', u'F\xf6rh\xf6jda leverenzym-v\xe4rden']]],
           ['Rare', [['Hepato', u'Hepatit']]],
           ['Very rare', []]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 23,
 u'_type': u'MSFU'}