{'_data': [['Very common', [['GI', u'illam\xe5ende; kr\xe4kningar']]],
           ['Common',
            [['Metabolism', u'minskad aptit; anorexi'],
             ['Psychiatric', u'halluci-nationer; depression'],
             ['Nervous system', u'synkope; yrsel; tremor; huvudv\xe4rk; d\xe5sighet; letargi'],
             ['Cardiac', u'bradykardi'],
             ['Vascular', u'hypertension'],
             ['GI',
              u'buksm\xe4rtor; buksm\xe4rtor i \xf6vre magtarm-kanalen; diarr\xe9; dyspepsi; obehags-k\xe4nsla i magen; obehagsk\xe4nsl a i buken'],
             ['Skin', u'hyperhidros'],
             ['Musculoskeletal', u'muskel-spasmer'],
             ['General', u'tr\xf6tthet; asteni; sjukdoms-k\xe4nsla'],
             ['Investigations', u'vikt-minskning'],
             ['Injury', u'fall']]],
           ['Uncommon',
            [['Metabolism', u'uttorkning'],
             ['Psychiatric', u'synhalluci-nationer; h\xf6rselhalluci-nationer'],
             ['Nervous system', u'parestesi; dysgeusi; hypersomni'],
             ['Eye', u'dimsyn'],
             ['Ear', u'tinnitus'],
             ['Cardiac',
              u'supraventriku-l\xe4r extrasystole; atrioventrikul\xe4r block grad 1; sinus-bradykardi; palpitationer'],
             ['Vascular', u'hypotension; flushing'],
             ['GI', u'hulkningar'],
             ['Musculoskeletal', u'muskelsvaghet'],
             ['Investigations', u'f\xf6rh\xf6jda leverenzym-v\xe4rden']]],
           ['Rare', [['Hepato', u'hepatit']]],
           ['Very rare', []]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 23,
 u'_type': u'MSFU'}