{'_data': [['Common',
            [['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Tremor'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Yrsel'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Tremor'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'Asteni'],
             ['Metabolism', u'Viktuppg\xe5ng'],
             ['Vascular',
              u'Perifert \xf6dem Beskrivning av valda biverkningar I kontrollerade kliniska studier med kombinationen 100 mg vildagliptin + tiazolidindion rapporterades inga patienter som avbr\xf6t studien pga biverkningar i varken vildagliptin 100 mg dagligen + tiazolidindion eller i placebo + tiazolidindion behandlingsgruppen. I kliniska studier var f\xf6rekomsten av hypoglykemi mindre vanlig hos patienter som fick vildagliptin + pioglitazon (0,6 %) men vanlig hos patienter som fick placebo + pioglitazon (1,9 %). Inga sv\xe5ra h\xe4ndelser av hypoglykemi rapporterades i vildagliptingrupperna. I pioglitazon till\xe4ggstudien var den absoluta viktuppg\xe5ngen f\xf6r placebo och Galvus 100 mg dagligen, 1,4 kg respektive 2,7 kg. F\xf6rekomsten av perifera \xf6dem n\xe4r vildagliptin 100 mg om dagen gavs som till\xe4gg till maximal basdos av pioglitazon (45 mg en g\xe5ng dagligen) var 7,0 %, j\xe4mf\xf6rt med 2,5 % vid enbart basdosen pioglitazon. Monoterapi'],
             ['Nervous system', u'Yrsel'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Yrsel, tremor'],
             ['Skin', u'Hyperhidros'],
             ['General',
              u'Asteni Beskrivning av valda biverkningar I behandlingsgruppen med vildagliptin + metformin + glimepirid rapporterades ingen avbruten behandling p\xe5 grund av biverkningar mot 0,6 % i behandlingsgruppen med placebo + metformin + glimepirid. F\xf6rekomsten av hypoglykemi var vanlig i b\xe5da behandlingsgrupperna (5,1 % f\xf6r gruppen med vildagliptin + metformin + glimepirid mot 1,9 % f\xf6r gruppen med placebo + metformin + glimepirid gruppen). Ett fall av allvarlig hypoglykemi rapporterades i vildagliptingruppen. Vid slutet av studien s\xe5 var effekten p\xe5 medelkroppsvikten neutral (+0,6 kg i vildagliptingruppen och 0,1 kg i placebogruppen).'],
             ['Metabolism', u'Minskat blodglukos'],
             ['Nervous system', u'Huvudv\xe4rk, frossa'],
             ['GI', u'Illam\xe5ende, gastroesofageal refluxsjukdom']]],
           ['Uncommon',
            [['Nervous system', u'Tr\xf6tthet'],
             ['GI', u'Illam\xe5ende'],
             ['GI',
              u'F\xf6rstoppning Beskrivning av valda biverkningar I kontrollerade kliniska studier med kombinationen 50 mg vildagliptin + en sulfonureid var f\xf6rekomsten av patienter som avbr\xf6t studien pga biverkningar 0,6 % i behandlingsgruppen vildagliptin 50 mg + sulfonureid j\xe4mf\xf6rd med 0 % i behandlingsgruppen placebo + sulfonureid. I kliniska studier var f\xf6rekomsten av hypoglykemi n\xe4r vildagliptin 50 mg gavs en g\xe5ng dagligen som till\xe4gg till glimepirid 1,2 % j\xe4mf\xf6rd med 0,6 % f\xf6r placebo + glimepirid. Inga sv\xe5ra h\xe4ndelser av hypoglykemi rapporterades i vildagliptingrupperna. I kliniska studier f\xf6r\xe4ndrades inte kroppsvikten fr\xe5n utg\xe5ngsv\xe4rdet d\xe5 vildagliptin 50 mg en g\xe5ng dagligen gavs som till\xe4gg till glimepirid (-0,1 kg och -0,4 kg f\xf6r vildagliptin respektive placebo).'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Asteni'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Perifert \xf6dem'],
             ['GI', u'F\xf6rstoppning'],
             ['Musculoskeletal', u'Ledv\xe4rk'],
             ['GI',
              u'Diarr\xe9, gasbildning Beskrivning av valda biverkningar I kontrollerade kliniska studier med vildagliptin 50 mg tv\xe5 g\xe5nger dagligen i kombination med insulin, med eller utan samtidigt anv\xe4ndning av metformin, var den totala f\xf6rekomsten av patienter som avbr\xf6t studien p\xe5 grund av biverkningar 0,3 % i vildagliptingruppen och inga som avbr\xf6t studien i placebogruppen. F\xf6rekomsten av hypoglykemi var likartad i b\xe5da behandlingsgrupperna (14,0 % i vildagliptingruppen mot 16,4 % i placebogruppen). Tv\xe5 patienter rapporterade allvarliga hypoglykemiska h\xe4ndelser i vildagliptingruppen och 6 patienter i placebogruppen. Vid slutet av studien var effekten p\xe5 medelkroppsvikten neutral (+0,6 kg \xe4ndring fr\xe5n studiestart i vildagliptingruppen och ingen vikt\xe4ndring i placebogruppen). Erfarenheter efter att l\xe4kemedlet godk\xe4nts f\xf6r f\xf6rs\xe4ljning']]],
           ['Very rare',
            [['Infections', u'Nasofaryngit'],
             ['Infections', u'\xd6vre luftv\xe4gsinfektion'],
             ['Infections', u'Nasofaryngit']]],
           ['Unknown',
            [['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (reversibelt vid uts\xe4ttning av l\xe4kemedlet) Onormala leverfunktionstester (reversibelt vid uts\xe4ttning av l\xe4kemedlet)'],
             ['Skin', u'Urtikaria Bull\xf6sa eller exfoliativa hudlesioner']]]],
 '_pages': [5, 9],
 u'_rank': 37,
 u'_type': u'LSFU'}