{'_data': [[u'Unknown',
            [['Infections', u'Influensa   Mindre vanlig'],
             ['Blood',
              u'Hemolys, anemi, trombocytopeni, lymfadenopati   Ingen k\xe4nd frekvens'],
             ['Immune system',
              u'\xd6verk\xe4nslighet, anafylaktisk eller anafylaktoid   Ingen k\xe4nd frekvens'],
             ['Metabolism', u'Minskad aptit   Mindre vanlig'],
             ['Psychiatric', u'\xc5ngest, agitation   Mindre vanlig'],
             ['Nervous system', u'Huvudv\xe4rk   Vanlig   Letargi   Mindre vanlig'],
             ['Eye', u'Dimsyn   Mindre vanlig'],
             ['Cardiac', u'Palpitation   Mindre vanlig'],
             ['Vascular', u'Rodnad   Vanlig'],
             ['Respiratory', u'Dyspn\xe9, n\xe4sblod   Mindre vanlig'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar   Vanlig'],
             ['Hepato', u'Hepatit (icke-infekti\xf6s)   Ingen k\xe4nd frekvens'],
             ['Skin',
              u'Pruritus, urticaria, kallsvettning, hyperhidros   Mindre vanlig   Erytem, utslag, dermatit, angio\xf6dem   Ingen k\xe4nd frekvens'],
             ['Musculoskeletal', u'Artralgi, myalgi   Ingen k\xe4nd frekvens'],
             ['Renal', u'Njursvikt   Ingen k\xe4nd frekvens'],
             ['General', u'Tr\xf6tthet, frossa, pyrexi   Vanlig'],
             ['Investigations', u'Positivt Coombs test   Ingen k\xe4nd frekvens']]]],
 '_pages': [7, 9],
 u'_rank': 17,
 u'_type': u'LFSU'}