{'_data': [['Very common',
            [['Blood', u'\u2212Leukopeni (neutropeni grad 3 = 19,3 % grad 4 = 6 %).'],
             ['Respiratory',
              u'\u2212Dyspn\xe9 -- vanligen l\xe4tt och f\xf6rsvinner snabbt utan behandling.'],
             ['GI', u'\u2212Kr\xe4kningar. \u2212Illam\xe5ende'],
             ['Hepato',
              u'\u2212F\xf6rh\xf6jda  levertransaminasv\xe4rden  (ASAT  och ALAT) och alkalisk fosfatas.'],
             ['Skin', u'\u2212Allergiska hudutslag ofta med kl\xe5da. \u2212Alopeci.'],
             ['Renal',
              u'\u2212Hematuri. \u2212Mild proteinuri. symtomoch/ellersymtomvidMycket vanliga \u2212Influensaliknande  symptom  --  de  vanligaste symptomen  \xe4r  feber,  huvudv\xe4rk,  frossa,  myalgi, asteni  och  anorexi.  Hosta,  rinit,  sjukdomsk\xe4nsla, svettningar  och  s\xf6mnsv\xe5righeter  har  \xe4ven rapporterats. \u2212\xd6dem/perifert \xf6dem -- inkluderande ansikts\xf6dem. \xd6dem  \xe4r  vanligen  reversibelt  efter  det  att behandlingen avbrutits.']]],
           ['Common',
            [['Blood', u'\u2212Neutropeni med feber. Frekvens'],
             ['Metabolism', u'\u2212Anorexi.'],
             ['Nervous system',
              u'\u2212Huvudv\xe4rk. \u2212S\xf6mnl\xf6shet. \u2212S\xf6mnighet.'],
             ['Respiratory', u'\u2212Hosta. \u2212Rinit.'],
             ['GI',
              u'\u2212Diarr\xe9. \u2212Stomatit och s\xe5r i munnen. \u2212F\xf6rstoppning.'],
             ['Hepato', u'\u2212\xd6kat bilirubin.'],
             ['Skin', u'\u2212Kl\xe5da. \u2212Svettningar.'],
             ['Musculoskeletal', u'\u2212Ryggsm\xe4rta. \u2212Myalgi.']]],
           ['Uncommon',
            [['Respiratory',
              u'\u2212Interstitiell pneumonit (se avsnitt 4.4). \u2212Bronkospasm  --  vanligen  l\xe4tt  och   \xf6verg\xe5ende men kan kr\xe4va parenteral behandling.']]],
           ['Rare',
            [['Cardiac', u'\u2212Hj\xe4rtinfarkt.'],
             ['Vascular', u'\u2212Hypotension.'],
             ['Hepato', u'\u2212F\xf6rh\xf6jt gamma-glutamyltransferas (g- GT).'],
             ['Skin',
              u'\u2212Ulceration. Frekvens \u2212Bl\xe5s- och s\xe5rbildning. \u2212Hudfj\xe4llning.']]],
           ['Very rare',
            [['Immune system', u'\u2212Trombocytos.'],
             ['Immune system', u'\u2212Anafylaktoid reaktion.'],
             ['Musculoskeletal',
              u'\u2212Allvarligahudreaktionerinkluderande deskvamation och bull\xf6sa hudutslag.']]]],
 '_pages': [6, 10],
 u'_rank': 22,
 u'_type': u'LSFU2'}