{'_data': [['Common',
            [['Respiratory', u'\u2022Hosta \u2022Rinit'],
             ['Respiratory',
              u'\u2022Diarr\xe9 \u2022Stomatit och s\xe5r i munnen \u2022F\xf6rstoppning Lever och gallv\xe4gar Mycket vanliga: \u2022F\xf6rh\xf6jda levertransaminasv\xe4rden (ASAT och ALAT) och alkalisk fosfatas'],
             ['Respiratory', u'\u2022\xd6kat bilirubin'],
             ['Respiratory', u'\u2022Kl\xe5da \u2022Svettningar'],
             ['Respiratory', u'\u2022Feber \u2022Asteni \u2022Frossa']]],
           ['Uncommon',
            [['Respiratory',
              u'\u2022Interstitiell pneumoni (se avsnitt 4.4) \u2022Bronkospasm \u2013 vanligen l\xe4tt och \xf6verg\xe5ende men kan kr\xe4va parenteral behandling Magtarmkanalen Mycket vanliga: \u2022Illam\xe5ende \u2022Kr\xe4kningar']]],
           ['Rare',
            [['Respiratory',
              u'\u2022F\xf6rh\xf6jt gamma-glutamyltransferas (g-GT) Hud och subkutan Mycket vanliga: v\xe4vnad \u2022Allergiska hudutslag ofta med kl\xe5da \u2022Alopeci'],
             ['Respiratory',
              u'\u2022Ulceration \u2022Bl\xe5s- och s\xe5rbildning \u2022Hudfj\xe4llning'],
             ['Respiratory',
              u'\u2022Reaktioner vid injektionsst\xe4llet \u2013 huvudsakligen av mild karakt\xe4r) Skador och \u2022Toxiska effekter av str\xe5lning (se avsnitt 4.5) f\xf6rgiftningar och behandlings-komplikat ioner Spontanrapporter efter marknadsf\xf6ringen med ok\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data)']]],
           ['Very rare',
            [['Respiratory',
              u'\u2022Allvarliga hudreaktioner inkluderande deskvamation och bull\xf6sa hudutslag Muskuloskeletala Vanliga: systemet och bindv\xe4v \u2022Ryggsm\xe4rta \u2022Myalgi Njurar och urinv\xe4gar Mycket vanliga: \u2022Hematuri \u2022Mild proteinuri Allm\xe4nna symtom Mycket vanliga: och/eller symtom vid \u2022Influensaliknande symptom - de vanligaste symptomen \xe4r administreringsst\xe4llet feber, huvudv\xe4rk, frossa, myalgi, asteni och anorexi. Hosta, rinit, sjukdomsk\xe4nsla, svettningar och s\xf6mnsv\xe5righeter har \xe4ven rapporterats \u2022\xd6dem/perifert \xf6dem \u2013 inkluderande ansikts\xf6dem. \xd6dem \xe4r vanligen reversibelt efter det att behandlingen avbrutits.']]],
           ['Unknown',
            [['Respiratory',
              u'br\xf6stkorg och \u2022Dyspn\xe9 \u2013 vanligen l\xe4tt och f\xf6rsvinner snabbt utan mediastinum behandling.'],
             ['Nervous system', u'Cerebrovaskul\xe4r skada'],
             ['Cardiac', u'Arytmi, f\xf6retr\xe4desvis supraventrikul\xe4r. Hj\xe4rtsvikt'],
             ['Vascular', u'Kliniska tecken p\xe5 perifer vaskulit och gangr\xe4n'],
             ['Respiratory',
              u'Pulmonellt \xf6dem Respiratoriskt distress-syndrom hos vuxna (se avsnitt 4.4)'],
             ['GI', u'Ischemisk kolit'],
             ['Hepato', u'Allvarlig hepatotoxicitet, inkluderande leversvikt och d\xf6d'],
             ['Skin',
              u'Allvarliga hudreaktioner, inkluderande deskvamation och bull\xf6sa hudutslag, Lyells syndrom (toxisk epidermal nekros), Stevens-Johnson syndrom'],
             ['Renal',
              u'Njursvikt (se avsnitt 4.4) Hemolytiskt uremiskt syndrom (se avsnitt 4.4)'],
             ['Injury',
              u'Str\xe5lningsinducerad hudreaktion (radiation recall) Kombinationsbehandling vid br\xf6stcancer Frekvensen av grad 3 och 4 hematologisk toxicitet \xf6kar, s\xe4rskilt neutropeni, n\xe4r gemcitabin anv\xe4nds i kombination med paklitaxel. \xd6kningen av dessa biverkningar \xe5tf\xf6ljs dock inte av en \xf6kad incidens infektioner eller bl\xf6dningsepisoder. Tr\xf6tthet och neutropeni med feber f\xf6rekommer mer frekvent n\xe4r gemcitabin anv\xe4nds tillsammans med paklitaxel. Tr\xf6tthet, som inte har samband med anemi, f\xf6rsvinner vanligtvis efter den f\xf6rsta behandlingscykeln. Biverkningar grad 3 och 4. Paklitaxel j\xe4mf\xf6rt med gemcitabin plus paklitaxel Antal patienter (%) Paklitaxel Gemcitabin plus (n=259) paklitaxel (n=262) Grad 3 Grad 4 Grad 3 Grad 4 Laboratorietest Anemi 5 (1,9) 1 (0,4) 15 (5,7) 3 (1,1)']]]],
 '_pages': [7, 12],
 u'_rank': 20,
 u'_type': u'LSFU'}