<<<<<<< HEAD
{'_data': [['Common',
            [['Blood', u'\u2022Neutropeni med feber.'],
             ['Respiratory', u'\u2022Hosta. \u2022Rinit.'],
             ['GI',
              u'\u2022Diarr\xe9. \u2022Stomatit och s\xe5r i munnen. \u2022F\xf6rstoppning Lever och gallv\xe4gar Mycket vanliga \u2022F\xf6rh\xf6jda levertransaminasv\xe4rden (ASAT och ALAT) och alkalisk fosfatas.'],
             ['GI', u'\u2022\xd6kat bilirubin.'],
             ['GI', u'\u2022Kl\xe5da. \u2022Svettningar.'],
             ['General', u'\u2022Feber \u2022Asteni \u2022Frossa.']]],
           ['Uncommon',
            [['Respiratory',
              u'\u2022Interstitiell pneumonit (se avsnitt 4.4). \u2022Bronkospasm \u2013 vanligen l\xe4tt och \xf6verg\xe5ende men kan kr\xe4va parenteral behandling.']]],
           ['Rare',
            [['GI',
              u'\u2022F\xf6rh\xf6jt gamma-glutamyltransferas (g-GT). Hud och subkutan v\xe4vnad Mycket vanliga \u2022Allergiska hudutslag ofta med kl\xe5da. \u2022Alopeci.'],
             ['GI',
              u'\u2022Ulceration. \u2022Bl\xe5s- och s\xe5rbildning. \u2022Hudfj\xe4llning.'],
             ['General',
              u'\u2022Reaktioner p\xe5 injektionsst\xe4llet \u2013 huvudsakligen av mild karakt\xe4r. Skador och f\xf6rgiftningar och \u2022Toxiska effekter av str\xe5lning (se avsnitt behandlingskomplikationer 4.5). Spontanrapporter efter marknadsf\xf6ringen med ok\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data)']]],
           ['Very rare',
            [['Blood',
              u'\u2022Trombocytos. Immunsystemet Mycket s\xe4llsynta \u2022Anafylaktoid reaktion. Metabolism och nutrition Vanliga \u2022Anorexi. Centrala och perifera nervsystemet Vanliga \u2022Huvudv\xe4rk. \u2022S\xf6mnl\xf6shet. \u2022S\xf6mnighet. Hj\xe4rtat S\xe4llsynta Hj\xe4rtinfarkt. Blodk\xe4rl S\xe4llsynta \u2022Hypotension.'],
             ['GI',
              u'\u2022Allvarliga hudreaktioner inkluderande deskvamation och bull\xf6sa hudutslag. Muskuloskeletala systemet och bindv\xe4v Vanliga \u2022Ryggsm\xe4rta. \u2022Myalgi. Njurar och urinv\xe4gar Mycket vanliga \u2022Hematuri. \u2022Mild proteinuri.']]],
           ['Unknown',
            [['Blood',
              u'(Neutropeni grad 3 = 19,3 %; grad 4 = 6 %) Benm\xe4rgssuppression \xe4r vanligen l\xe4tt till m\xe5ttlig och p\xe5verkar framf\xf6rallt antal granulocyter (se avsnitt 4.2). \u2022Trombocytopeni. \u2022Anemi.'],
             ['Respiratory', u'snabbt utan behandling.'],
             ['General',
              u'administreringsst\xe4llet \u2022Influensaliknande symptom \u2013 de vanligaste symptomen \xe4r feber, huvudv\xe4rk, frossa, myalgi, asteni och anorexi. Hosta, rinit, sjukdomsk\xe4nsla, svettningar och s\xf6mnsv\xe5righeter har \xe4ven rapporterats. \u2022\xd6dem/perifert \xf6dem \u2013 inkluderande ansikts\xf6dem. \xd6dem \xe4r vanligen reversibelt efter det att behandlingen avbrutits.'],
             ['Nervous system', u'Cerebrovaskul\xe4r skada.'],
             ['Cardiac', u'Arytmi, f\xf6retr\xe4desvis supraventrikul\xe4r. Hj\xe4rtsvikt.'],
             ['Vascular', u'Kliniska tecken p\xe5 perifer vaskulit och gangr\xe4n.'],
             ['Respiratory',
              u'Pulmonellt \xf6dem. Respiratoriskt distress-syndrom hos vuxna (se avsnitt 4.4).'],
             ['GI', u'Ischemisk kolit.'],
             ['Hepato', u'Allvarlig hepatotoxicitet, inkluderande leversvikt och d\xf6d.'],
             ['Skin',
              u'Allvarliga hudreaktioner, inkluderande deskvamation och bull\xf6sa hudutslag, Lyells syndrom, Stevens-Johnson syndrom.'],
             ['Renal',
              u'Njursvikt (se avsnitt 4.4). Hemolytiskt uremiskt syndrom (se avsnitt 4.4).'],
             ['Injury', u'Str\xe5lningsinducerad hudreaktion (radiation recall).']]]],
 '_pages': [6, 10],
 u'_rank': 24,
 u'_type': u'LSFU'}
=======
{'_data': [['Very common',
            [['Blood', u'\u2022Leukopeni. (Neutropeni grad 3 = 19,3 %; grad 4 = 6 %)'],
             ['Respiratory',
              u'\u2022Dyspn\xe9 -- vanligen l\xe4tt och f\xf6rsvinner snabbt utan behandling.'],
             ['GI', u'\u2022Illam\xe5ende. \u2022Kr\xe4kningar.'],
             ['Hepato',
              u'\u2022F\xf6rh\xf6jda levertransaminasv\xe4rden (ASAT och ALAT) och alkalisk fosfatas.'],
             ['Skin', u'\u2022Allergiska hudutslag ofta med kl\xe5da. \u2022Alopeci.'],
             ['Renal', u'\u2022Hematuri. \u2022Mild proteinuri.'],
             ['General',
              u'\u2022Influensaliknande symptom -- de vanligaste symptomen \xe4r feber, huvudv\xe4rk, frossa, myalgi, asteni och anorexi. Hosta, rinit, sjukdomsk\xe4nsla, svettningar och s\xf6mnsv\xe5righeter har \xe4ven rapporterats. \u2022\xd6dem/perifert \xf6dem -- inkluderande ansikts\xf6dem. \xd6dem \xe4r vanligen reversibelt efter det att behandlingen avbrutits.']]],
           ['Common',
            [['Blood', u'\u2022Neutropeni med feber.'],
             ['Metabolism', u'\u2022Anorexi.'],
             ['Nervous system',
              u'\u2022Huvudv\xe4rk. \u2022S\xf6mnl\xf6shet. \u2022S\xf6mnighet.'],
             ['Respiratory', u'\u2022Hosta. \u2022Rinit.'],
             ['GI',
              u'\u2022Diarr\xe9. \u2022Stomatit och s\xe5r i munnen. \u2022F\xf6rstoppning'],
             ['Hepato', u'\u2022\xd6kat bilirubin.'],
             ['Skin', u'\u2022Kl\xe5da. \u2022Svettningar.'],
             ['Musculoskeletal', u'\u2022Ryggsm\xe4rta. \u2022Myalgi.'],
             ['General', u'\u2022Feber \u2022Asteni \u2022Frossa.']]],
           ['Uncommon',
            [['Respiratory',
              u'\u2022Interstitiell pneumonit (se avsnitt 4.4). \u2022Bronkospasm -- vanligen l\xe4tt och \xf6verg\xe5ende men kan kr\xe4va parenteral behandling.']]],
           ['Rare',
            [['Cardiac', u'Hj\xe4rtinfarkt.'],
             ['Vascular', u'\u2022Hypotension.'],
             ['Hepato', u'\u2022F\xf6rh\xf6jt gamma-glutamyltransferas (g-GT).'],
             ['Skin',
              u'\u2022Ulceration. \u2022Bl\xe5s- och s\xe5rbildning. \u2022Hudfj\xe4llning.'],
             ['General',
              u'\u2022Reaktioner p\xe5 injektionsst\xe4llet --huvudsakligen av mild karakt\xe4r. \u2022Toxiska effekter av str\xe5lning (se avsnitt 4.5).']]],
           ['Very rare',
            [['Blood', u'\u2022Trombocytos.'],
             ['Immune system', u'\u2022Anafylaktoid reaktion.'],
             ['Skin',
              u'\u2022Allvarliga hudreaktioner inkluderande deskvamation och bull\xf6sa hudutslag.']]]],
 '_pages': [6, 10],
 u'_rank': 25,
 u'_type': u'LSFU2'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
