{'_data': [['Very common',
            [['Blood', u'\u2022Leukopeni (Neutropeni grad 3 = 19,3 %; grad 4 = 6 %).'],
             ['Respiratory',
              u'\u2022Dyspn\xe9 -- oftast l\xe4tt och snabbt \xf6verg\xe5ende utan behandling.'],
             ['GI', u'\u2022Kr\xe4kningar. \u2022Illam\xe5ende.'],
             ['Hepato',
              u'\u2022F\xf6rh\xf6jda levertransaminasv\xe4rden (ASAT och ALAT) och alkaliskt fosfatas.'],
             ['Skin', u'\u2022Allergiska hudutslag ofta med kl\xe5da. \u2022Alopeci.'],
             ['Renal', u'\u2022Hematuri. \u2022Mild proteinuri.'],
             ['General',
              u'\u2022Influensaliknande symtom -- de vanligaste symtomen \xe4r feber, huvudv\xe4rk, frossa, myalgi, asteni och anorexi. Hosta, rinit, sjukdomsk\xe4nsla, svettningar och s\xf6mnsv\xe5righeter har ocks\xe5 rapporterats. \u2022\xd6dem/perifert \xf6dem -- inkluderande ansikts\xf6dem. \xd6dem \xe4r vanligen reversibelt efter att behandlingen avbrutits.']]],
           ['Common',
            [['Blood', u'\u2022Neutropeni med feber.'],
             ['Metabolism', u'\u2022Anorexi.'],
             ['Nervous system',
              u'\u2022Huvudv\xe4rk. \u2022S\xf6mnl\xf6shet. \u2022S\xf6mnighet.'],
             ['Respiratory', u'\u2022Hosta. \u2022Rinit.'],
             ['Hepato', u'\u2022\xd6kat bilirubin.'],
             ['Skin', u'\u2022Kl\xe5da. \u2022Svettningar.'],
             ['Musculoskeletal', u'\u2022Ryggsm\xe4rta. \u2022Myalgi.'],
             ['General', u'\u2022Feber. \u2022Asteni. \u2022Frossa.']]],
           ['Uncommon',
            [['Respiratory',
              u'\u2022Interstitiell pneumonit (se avsnitt 4.4). \u2022Bronkospasm - vanligen l\xe4tt och \xf6verg\xe5ende, men kan kr\xe4va parenteral behandling.']]],
           ['Rare',
            [['Cardiac', u'\u2022Hj\xe4rtinfarkt.'],
             ['Vascular',
              u'\u2022Kliniska tecken p\xe5 perifer vaskulit och gangr\xe4n. \u2022Hypotension.'],
             ['Respiratory',
              u'\u2022Lung\xf6dem. \u2022Respiratoriskt distress-syndrom hos vuxna (ARDS) (se avsnitt 4.4). Frekvens'],
             ['Hepato', u'\u2022\xd6kad gamma-glutamyltransferas (\u03b3-GT)'],
             ['Skin',
              u'\u2022Allvarliga hudreaktioner inklusive deskvamation och bull\xf6sa hudutslag. \u2022Ulceration. \u2022Bl\xe5s- och s\xe5rbildning. \u2022Hudfj\xe4llning.'],
             ['General',
              u'\u2022Reaktioner p\xe5 injektionsst\xe4llet -- huvudsakligen av mild karakt\xe4r.'],
             ['Injury',
              u'\u2022Str\xe5lningstoxicitet (se avsnitt 4.5). \u2022Str\xe5lningsinducerad hudreaktion (radiation recall).']]],
           ['Very rare', [['Immune system', u'\u2022Anafylaktoid reaktion.']]]],
 '_pages': [6, 10],
 u'_rank': 24,
 u'_type': u'LSFU2'}