{'_data': [['Very common',
            [['Blood', u'\u2022Leukopeni. (Neutropeni grad 3 = 19,3 %; grad 4 = 6 %)'],
             ['Respiratory',
              u'\u2022Dyspn\xe9 -- vanligen l\xe4tt och f\xf6rsvinner snabbt utan behandling.'],
             ['GI', u'\u2022Illam\xe5ende. \u2022Kr\xe4kningar.'],
             ['Hepato',
              u'\u2022F\xf6rh\xf6jda levertransaminasv\xe4rden (ASAT och ALAT) och alkalisk fosfatas.'],
             ['Skin', u'\u2022Allergiska hudutslag ofta med kl\xe5da. \u2022Alopeci.'],
             ['Renal', u'\u2022Hematuri. \u2022Mild proteinuri.'],
             ['General',
              u'\u2022Influensaliknande symptom -- de vanligaste symptomen \xe4r feber, huvudv\xe4rk, frossa, myalgi, asteni och anorexi. Hosta, rinit, sjukdomsk\xe4nsla, svettningar och s\xf6mnsv\xe5righeter har \xe4ven rapporterats. \u2022\xd6dem/perifert \xf6dem -- inkluderande ansikts\xf6dem. \xd6dem \xe4r vanligen reversibelt efter det att behandlingen avbrutits.']]],
           ['Common',
            [['Blood', u'\u2022Neutropeni med feber.'],
             ['Metabolism', u'\u2022Anorexi.'],
             ['Nervous system',
              u'\u2022Huvudv\xe4rk. \u2022S\xf6mnl\xf6shet. \u2022S\xf6mnighet.'],
             ['Respiratory', u'\u2022Hosta. \u2022Rinit.'],
             ['GI',
              u'\u2022Diarr\xe9. \u2022Stomatit och s\xe5r i munnen. \u2022F\xf6rstoppning'],
             ['Hepato', u'\u2022\xd6kat bilirubin.'],
             ['Skin', u'\u2022Kl\xe5da. \u2022Svettningar.'],
             ['Musculoskeletal', u'\u2022Ryggsm\xe4rta. \u2022Myalgi.'],
             ['General', u'\u2022Feber \u2022Asteni \u2022Frossa.']]],
           ['Uncommon',
            [['Nervous system', u'\u2022Cerebrovaskul\xe4r skada.'],
             ['Cardiac', u'\u2022Arytmi (fr\xe4mst supraventrikul\xe4r) \u2022Hj\xe4rtsvikt.'],
             ['Respiratory',
              u'\u2022Interstitiell pneumonit (se avsnitt 4.4). \u2022Bronkospasm -- vanligen l\xe4tt och \xf6verg\xe5ende men kan kr\xe4va parenteral behandling.'],
             ['Hepato',
              u'\u2022Allvarlig hepatotoxicitet, inkluderande leversvikt och d\xf6d.']]],
           ['Rare',
            [['Cardiac', u'\u2022Hj\xe4rtinfarkt.'],
             ['Vascular',
              u'\u2022Hypotension. \u2022Kliniska tecken p\xe5 perifer vaskulit och gangr\xe4n'],
             ['Respiratory', u'\u2022Lung\xf6dem \u2022ARDS (se avsnitt 4.4).'],
             ['Hepato', u'\u2022F\xf6rh\xf6jt gamma-glutamyltransferas (g-GT).'],
             ['Skin',
              u'\u2022Allvarliga hudreaktioner inkluderande deskvamation och bull\xf6sa hudutslag. \u2022Ulceration. \u2022Bl\xe5s- och s\xe5rbildning. \u2022Hudfj\xe4llning.'],
             ['Renal',
              u'\u2022Akut njursvikt (se avsnitt 4.4). \u2022Hemolytiskt uremiskt syndrom (se avsnitt 4.4).'],
             ['General',
              u'\u2022Reaktioner p\xe5 injektionsst\xe4llet --huvudsakligen av mild karakt\xe4r.'],
             ['Injury',
              u'\u2022Toxiska effekter av str\xe5lning (se avsnitt 4.5). \u2022Str\xe5lningsinducerad hudreaktion (radiation recall).']]],
           ['Very rare',
            [['Blood', u'\u2022Trombocytos.'],
             ['Immune system', u'\u2022Anafylaktoid reaktion.'],
             ['GI', u'\u2022Ischemisk kolit.'],
             ['Skin', u'\u2022Toxisk epidermal nekrolys. \u2022Stevens-Johnsons syndrom']]]],
 '_pages': [6, 10],
 u'_rank': 32,
 u'_type': u'LSFU2'}