{'_data': [['Common',
            [['Immune system', u'Antikroppsbildning'],
             ['Nervous system', u'Hos vuxna parestesier'],
             ['Skin', u'Hos barn \xf6verg\xe5ende reaktioner vid injektionsst\xe4llet'],
             ['Musculoskeletal', u'Hos vuxna muskuloskeletal stelhet, ledv\xe4rk, myalgi'],
             ['General', u'Hos vuxna perifert \xf6dem']]],
           ['Uncommon',
            [['Nervous system', u'Hos vuxna karpaltunnelsyndrom. Hos barn parestesier'],
             ['Musculoskeletal', u'Hos barnmuskuloskeletal stelhet, ledv\xe4rk, myalgi'],
             ['General',
              u'Hos barn perifert \xf6dem Det har rapporterats att somatropin reducerar kortisolniv\xe5erna i serum, troligen genom att p\xe5verka b\xe4rarproteiner eller genom \xf6kat leverclearance. Den kliniska relevansen av dessa uppt\xe4ckter tycks begr\xe4nsad. Kortisonterapi b\xf6r dock optimeras innan behandling med Genotropin p\xe5b\xf6rjas. Efter att Genotropin godk\xe4nts f\xf6r f\xf6rs\xe4ljning har s\xe4llsynta d\xf6dsfall rapporterats i samband med behandling med somatropin hos patienter med Prader-Willi syndrom. N\xe5got samband har dock inte p\xe5visats. *Mycket f\xe5 fall av leukemi har rapporterats hos barn med tillv\xe4xthormonbrist som behandlats med somatropin, men omfattningen synes vara densamma som hos barn utan tillv\xe4xthormonbrist, se 4.4.']]],
           ['Rare',
            [['Endocrine', u'Diabetes mellitus typ II'],
             ['Nervous system', u'Benign intrakraniell hypertension']]],
           ['Very rare', [['Neoplasms', u'Leukemi*']]]],
 '_pages': [7, 8],
 u'_rank': 11,
 u'_type': u'LSFU'}