{'_data': [['Very common', [['Eye', u'\xf6kad irispigmentering.']]],
           ['Common',
            [['Eye',
              u'\xf6gonirritation (inklusive sveda, br\xe4nnande k\xe4nsla och kl\xe5da), \xf6gonsm\xe4rta.']]],
           ['Uncommon',
            [['Nervous system', u'huvudv\xe4rk.'],
             ['Eye',
              u'hyperemi i \xf6gat, konjunktivit, dimsyn, \xf6kad lakrimation, blefarit, korneala st\xf6rningar.'],
             ['Skin',
              u'hudutslag, kl\xe5da. Ytterligare biverkningar har rapporterats i samband med anv\xe4ndning av de individuella komponenterna i latanoprost/timolol \xf6gondroppar antingen i kliniska studier, spontanrapporter eller i tillg\xe4nglig litteratur. F\xf6r latanoprost \xe4r dessa']]],
           ['Unknown',
            [['Infections', u'Herpetisk keratit.'],
             ['Nervous system', u'Yrsel.'],
             ['Eye',
              u'\xd6gonfrans och vellush\xe5rf\xf6r\xe4ndringar (\xf6kad l\xe4ngd, tjocklek, pigmentering och antal), punktata epiteliala erosioner, periorbitalt \xf6dem, irit/uveit, makula\xf6dem (vid afaki, pseudofaki med brusten bakre linskapsel eller med f\xf6r makula\xf6dem k\xe4nda riskfaktorer), torra \xf6gon, keratit, kornealt \xf6dem och erosioner, felriktade \xf6gonfransar som ibland resulterar i \xf6gonirritation, iriscysta.'],
             ['Cardiac',
              u'F\xf6rv\xe4rrad k\xe4rlkramp hos patienter med tidigare sjukdom, palpitationer.'],
             ['Respiratory', u'Astma, f\xf6rv\xe4rrad astma, dyspn\xe9.'],
             ['Skin', u'M\xf6rkf\xe4rgning av \xf6gonlockshuden.'],
             ['Musculoskeletal', u'Ledv\xe4rk, muskelv\xe4rk.'],
             ['General', u'Br\xf6stsm\xe4rtor. F\xf6r timolol \xe4r dessa'],
             ['Immune system',
              u'Tecken och symptom p\xe5 allergiska reaktioner inklusive angio\xf6dem, urticaria, lokalt och generellt exantem, pruritus, anafylakitsk reaktion.'],
             ['Metabolism', u'Hypoglykemi.'],
             ['Psychiatric',
              u'Depression, minnesf\xf6rlust, minskad libido, s\xf6mnsv\xe5righeter, mardr\xf6mmar.'],
             ['Nervous system',
              u'Yrsel, parestesier, cerebral ischemi, cerebrovaskul\xe4r lesion, \xf6kade tecken och symptom p\xe5 myastenia gravis, synkope och huvudv\xe4rk.'],
             ['Eye',
              u'Tecken och symptom p\xe5 \xf6gonirritation (t ex br\xe4nnande, stickande k\xe4nsla, kl\xe5da, t\xe5rande \xf6gon, r\xf6da \xf6gon), blefarit, keratit, dimsyn och koroidalavlossning efter filtrationskirurgi (se avsnitt 4.4), nedsatt kornealsensibilitet och torra \xf6gon, synrubbningar inklusive refraktionsf\xf6r\xe4ndringar (i vissa fall p.g.a av uts\xe4ttande av miotika), diplopi, ptos,'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac',
              u'Palpitation, arytmi, bradykardi, br\xf6stsm\xe4rta, hj\xe4rtstillest\xe5nd, \xf6dem, hj\xe4rtblock, kronisk hj\xe4rtinsufficiens, atrioventrikul\xe4r blockad, hj\xe4rtsvikt.'],
             ['Vascular', u'Hypotoni, Raynauds fenomen, kalla h\xe4nder och f\xf6tter.'],
             ['Respiratory',
              u'Bronkospasm (framf\xf6r allt hos patienter med tidigare bronkospastisk sjukdom), dyspn\xe9, hosta.'],
             ['GI',
              u'Illam\xe5ende, diarr\xe9, dyspepsi, muntorrhet, buksm\xe4rta, kr\xe4kningar.'],
             ['Skin',
              u'Alopeci, psoriasisliknande hudutslag eller f\xf6rs\xe4mring av psoriasis, hudutslag.'],
             ['Musculoskeletal', u'Myalgi.'],
             ['Reproductive system', u'Sexuell dysfunktion, minskat libido.'],
             ['General', u'Asteni/tr\xf6tthet.']]]],
 '_pages': [5, 7],
 u'_rank': 27,
 u'_type': u'LSFU'}