{'_data': [['Common',
            [['Blood', u'anemi  '],
             ['Metabolism', u'vanlig \xf6kad aptit mindre'],
             ['Metabolism', u'vanlig Centrala och perifera'],
             ['Eye', u'vanlig makula\xf6dem 2 ok\xe4nd ok\xe4nd ok\xe4nd ok\xe4nd ok\xe4nd'],
             ['Ear', u'vanlig'],
             ['Cardiac', u'vanlig vanlig vanlig vanlig 7'],
             ['GI', u'vanlig Hud och subkutan v\xe4vnad svettning mindre'],
             ['GI',
              u'vanlig Muskuloskeletala systemet och bindv\xe4v benbrott 4 vanlig vanlig vanlig vanlig vanlig artralgi vanlig vanlig vanlig ryggv\xe4rk vanlig'],
             ['Renal', u'vanlig proteinuri mindre'],
             ['Renal', u'vanlig'],
             ['General', u'vanlig tr\xf6tthet mindre'],
             ['General', u'vanlig']]],
           ['Unknown',
            [['Metabolism', u'hypoglykemi mindre mycket vanlig'],
             ['Eye', u'synrubbningar vanlig vanlig mindre'],
             ['Ear', u'mindre'],
             ['Cardiac',
              u'hj\xe4rtsvikt 3 vanlig Neoplasier; benigna, maligna och ospecificerade (samt cystor och polyper) Bl\xe5scancer mindre vanlig mindre mindre mindre mindre'],
             ['Respiratory', u'br\xf6stkorg och mediastinum dyspn\xe9 vanlig'],
             ['GI', u'v\xe4dersp\xe4nning mindre vanlig'],
             ['Renal', u'vanlig glykosuri mindre'],
             ['Reproductive system', u'vanlig'],
             ['General', u'och/eller symtom vid administreringsst\xe4llet \xf6dem mycket'],
             ['Investigations',
              u'vikt\xf6kning 5 vanlig vanlig vanlig vanlig vanlig f\xf6rh\xf6jt kreatinfosfokinas vanlig i blodet \xf6kning av mindre laktatdehydrogenas vanlig \xf6kning av ok\xe4nd ok\xe4nd ok\xe4nd ok\xe4nd ok\xe4nd alaninaminitransferas 6 Synrubbningar har framf\xf6rallt rapporterats under b\xf6rjan av behandlingen, och dessa har samband med f\xf6r\xe4ndringar i blodglukosniv\xe5er p\xe5 grund av tempor\xe4r f\xf6r\xe4ndring av linsens v\xe4tskefyllnad och brytningsindex, som \xe4ven ses med andra diabetesmedel.']]]],
 '_pages': [6, 9],
 u'_rank': 22,
 u'_type': u'LSFU'}