{'_data': [['Uncommon',
            [['Eye', u'\xd6verg\xe5ende synrubbningar'],
             ['Skin',
              u'\xd6verk\xe4nslighetsreakt ioner i huden som kl\xe5da, utslag och urtikaria']]],
           ['Rare',
            [['Blood',
              u'F\xf6r\xe4ndringar i blodbilden , inklusive: Trombocytopeni Leukopeni Granulocytopeni Agranulocytos Erytrocytopeni Hemolytisk anemi Pancytopeni'],
             ['Metabolism', u'Hypoglykemi'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymv\xe4rden']]],
           ['Very rare',
            [['Immune system',
              u'Leukocytoklastisk vaskulit. L\xe4tta \xf6verk\xe4nslighets-reaktioner som kan utvecklas till allvarliga reaktioner med dyspn\xe9, blodtrycksfall och ibland chock. Korsallergi med andra sulfonureider, sulfonamider eller besl\xe4ktade substanser.'],
             ['GI',
              u'Gastrointestinala biverkningar s\xe5som illam\xe5ende, kr\xe4kning, diarr\xe9, tryck eller k\xe4nsla av uppsv\xe4lld mage och magsm\xe4rta'],
             ['Hepato',
              u'Nedsatt leverfunktion som kolestas, gulsot och hepatit och leversvikt.'],
             ['Skin', u'Ljus\xf6verk\xe4nslighet'],
             ['Investigations', u'Minskade serumnatrium-koncentratione']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 10,
 u'_type': u'MSFU'}