{'_data': [['Rare',
            [['Blood',
              u'trombocytopeni, leukopeni, granulocytopeni, agranalucytos, erytrocytopeni, hemolytisk anemi och pancytopeni. Dessa \xe4r i allm\xe4nhet reversibla vid uts\xe4ttning av l\xe4kemedlet.'],
             ['Metabolism',
              u'Hypoglykemi. Dessa hypoglykemiske reaktioner intr\xe4ffar i allm\xe4nhet omedelbart, kan vara allvarliga och \xe4r inte alltid l\xe4tta att avhj\xe4lpa. Liksom \xe4r fallet med all annan hypoglykemisk behandling beror frekvensen av s\xe5dana reaktioner p\xe5 individuella faktorer som kostvanor och dosering (se ytterligare information i avsnitt 4.4).']]],
           ['Very rare',
            [['Immune system',
              u'Leukocytoklastisk vaskulit, milda \xf6verk\xe4nslighetsreaktioner som kan utvecklas till allvarliga s\xe5dana med dyspn\xe9, blodtrycksfall och ibland chock.'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, diarr\xe9, k\xe4nsla av uppbl\xe5sthet, bukbesv\xe4r samt magsm\xe4rta som s\xe4llan leder till att behandlingen avbryts.'],
             ['Hepato',
              u'Rubbning av leverfunktionen (t.ex. med kolestas och gulsot), hepatit och leversvikt.'],
             ['Investigations', u'Minskning av natrium i blodet.']]],
           ['Unknown',
            [['Immune system',
              u'Korsallergi med sulfonureider, sulfonamider eller liknande substanser \xe4r m\xf6jlig.'],
             ['Eye',
              u'\xd6verg\xe5ende synst\xf6rningar kan upptr\xe4da, speciellt i b\xf6rjan av behandlingen, pga. f\xf6r\xe4ndringar i blodglukosniv\xe5erna.'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymv\xe4rden.'],
             ['Skin',
              u'\xd6verk\xe4nslighetsreaktioner i huden som kl\xe5da, utslag, urtikaria och ljus\xf6verk\xe4nslighet.']]]],
 '_pages': [6, 7],
 u'_rank': 10,
 u'_type': u'LSFU'}