{'_data': [['Very common', []],
           ['Common',
            [['Respiratory', u'Feber, infektion vid injektionsst\xe4llet,'],
             ['General',
              u'lokal sm\xe4rta eller reaktion, venirritation, ventrombos eller flebit som utg\xe5r fr\xe5n injektions-st\xe4llet, extravasation']]],
           ['Uncommon', [['Metabolism', u'Hyperhydrering, hyperglykemi']]],
           ['Rare',
            [['Metabolism', u'Elektrolytrubbningar '],
             ['Nervous system', u'Hj\xe4rtsvikt hos'],
             ['Cardiac', u'patienter med hj\xe4rtrubbning'],
             ['Respiratory', u'Pulmonellt \xf6dem']]],
           ['Very rare',
            [['Nervous system', u'Krampanfall som utl\xf6ses pga acetatinducerad alkalos']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 4],
 u'_rank': 8,
 u'_type': u'MSFU'}