{'_data': [['Common',
            [['Nervous system', u'Tr\xf6tthet'],
             ['Respiratory', u'rg'],
             ['GI', u'Illam\xe5ende Magont Matsm\xe4ltningsprob lem Diarr\xe9 F\xf6rstoppning']]],
           ['Uncommon', [['Skin', u'Utslag Kl\xe5da Rodnad']]],
           ['Rare', []],
           ['Unknown',
            [['Respiratory', u'Astma / f\xf6rv\xe4rrade astmatiska symptom'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'Angio\xf6dem Urtikaria'],
             ['Metabolism', u'Sv\xe5rkontrollerad Diabetes mellitus Hyperkolesterol emi'],
             ['General', u'\xd6dem/perifert \xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 9,
 u'_type': u'MSFU'}