{'_data': [['Common',
            [['Blood', u'anemi  '],
             ['Immune system', u'vanlig \xf6kad aptit mindre'],
             ['Immune system', u'vanlig Centrala och perifera'],
             ['Eye',
              u'vanlig makula\xf6dem 3 ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen frekvens frekvens frekvens frekvens k\xe4nd frekvens'],
             ['Ear', u'vanlig'],
             ['Cardiac', u'vanlig vanlig vanlig vanlig vanlig'],
             ['GI', u'vanlig Hud och subkutan v\xe4vnad svettning mindre'],
             ['GI',
              u'vanlig Muskuloskeletala systemet och bindv\xe4v benbrott 5 vanlig vanlig vanlig vanlig vanlig artralgi vanlig vanlig vanlig ryggv\xe4rk vanlig'],
             ['Renal', u'vanlig proteinuri mindre'],
             ['Renal', u'vanlig'],
             ['General', u'vanlig tr\xf6tthet mindre'],
             ['General', u'vanlig']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighets- och ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen allergiska reaktioner frekvens frekvens frekvens frekvens k\xe4nd frekvens Metabolism och nutrition hypoglykemi mindre mycket vanlig'],
             ['Eye', u'synrubbningar 2 vanlig vanlig mindre'],
             ['Ear', u'mindre'],
             ['Cardiac',
              u'vanlig Neoplasier; benigna, maligna och ospecificerade (samt cystor och polyper) bl\xe5scancer mindre mindre mindre mindre mindre'],
             ['Respiratory', u'br\xf6stkorg och mediastinum dyspn\xe9 vanlig'],
             ['GI', u'v\xe4dersp\xe4nning mindre vanlig'],
             ['Renal', u'vanlig glykosuri mindre'],
             ['Reproductive system', u'vanlig'],
             ['General', u'och/eller symtom vid administreringsst\xe4llet \xf6dem mycket'],
             ['Investigations',
              u'8 Biverkningsfrekvens av pioglitazon efter behandlingsterapi kombination Biverkning med Monoterapi med med metformin med metformin sulfonylurea och insulin sulfonylurea vikt\xf6kning 6 vanlig vanlig vanlig vanlig vanlig f\xf6rh\xf6jt kreatinfosfokinas vanlig i blodet \xf6kning av mindre laktatdehydrogenas vanlig \xf6kning av 7 ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen k\xe4nd ingen alaninaminotransferas frekvens frekvens frekvens frekvens k\xe4nd frekvens 1 Efter marknadsintroduktion har \xf6verk\xe4nslighetsreaktioner rapporterats hos patienter som har behandlats med pioglitazon. Dessa reaktioner omfattar anafylaxi, angio\xf6dem och urtikaria. Synrubbningar har framf\xf6rallt rapporterats under b\xf6rjan av behandlingen, och dessa har samband med f\xf6r\xe4ndringar i blodglukosniv\xe5er p\xe5 grund av tempor\xe4r f\xf6r\xe4ndring av linsens v\xe4tskefyllnad och brytningsindex, som \xe4ven ses med andra diabetesmedel. 3 \xd6dem rapporterades av 6\u20139% av patienterna som behandlats med pioglitazon under ett \xe5r i kontrollerade kliniska pr\xf6vningar. Frekvensen av \xf6dem f\xf6r j\xe4mf\xf6relsepreparat (sulfonureid, metformin) var 2\u20135%. De rapporterade \xf6demfallen var av mild till m\xe5ttlig karakt\xe4r och kr\xe4vde ingen uts\xe4ttning av behandlingen. 4 Frekvensen rapporterade fall av hj\xe4rtsvikt i kontrollerade kliniska studier med pioglitazon var densamma som i kontrollgrupperna som fick placebo, metformin respektive sulfonureid, men var f\xf6rh\xf6jd vid kombinationsbehandling med insulin. I en studie p\xe5 patienter med redan befintlig, st\xf6rre makrovaskul\xe4r sjukdom var incidensen allvarlig hj\xe4rtsvikt 1,6% h\xf6gre f\xf6r pioglitazon j\xe4mf\xf6rt med placebo n\xe4r det gavs som till\xe4ggsbehandling till insulin. Emellertid ledde inte detta till en \xf6kad mortalitet i denna studie. Hj\xe4rtsvikt har rapporterats s\xe4llsynt efter marknadsf\xf6ring av pioglitazon, men rapporterades oftare vid kombinationsbehandling med insulin eller hos patienter med tidigare hj\xe4rtsvikt. 5 En sammanslagen analys gjordes av biverkningar avseende benfrakturer fr\xe5n randomiserade, kontrollerade, dubbelblinda kliniska pr\xf6vningar med j\xe4mf\xf6relsepreparat p\xe5 \xf6ver 8100 patienter behandlade med pioglitazon och 7400 patienter behandlade med j\xe4mf\xf6relsepreparat, i upp till 3,5 \xe5r. En h\xf6gre frakturincidens observerades hos kvinnor som behandlades med pioglitazon (2,6%) j\xe4mf\xf6rt med kvinnor som behandlades med j\xe4mf\xf6relsepreparat (1,7%). N\xe5gon \xf6kning i frakturincidens observerades inte hos m\xe4n som behandlades med pioglitazon (1,3%) j\xe4mf\xf6rt med j\xe4mf\xf6relsepreparat (1,5%). I den 3,5-\xe5riga PROactive-studien hade 44/870 (5,1 %) av de pioglitazonbehandlade kvinnliga patienterna frakturer j\xe4mf\xf6rt med 23/905 frakturer (2,5 %) av de kvinnliga patienter som behandlades med j\xe4mf\xf6relsepreparat. N\xe5gon \xf6kning i frakturincidens observerades inte hos m\xe4n som behandlades med pioglitazon (1,7 %) j\xe4mf\xf6rt med j\xe4mf\xf6relsepreparat (2,1 %). 6 I kontrollerade f\xf6rs\xf6k med aktivt j\xe4mf\xf6relsepreparat var vikt\xf6kningen med pioglitazon som monoterapi i genomsnitt 2\u20133 kg under ett \xe5r. Liknande vikt\xf6kning erh\xf6lls i j\xe4mf\xf6relsegruppen som behandlades med sulfonureid. I kombinationsf\xf6rs\xf6k med pioglitazon och metformin erh\xf6lls en genomsnittlig vikt\xf6kning under ett \xe5r p\xe5 1,5 kg, och d\xe5 pioglitazon gavs i kombination med sulfonureid erh\xf6lls en vikt\xf6kning p\xe5 2,8 kg. I kontrollgrupperna gav till\xe4gg av en sulfonureid till metformin en genomsnittlig vikt\xf6kning p\xe5 1,3 kg och till\xe4gg av metformin till sulfonureid en genomsnittlig viktminskning p\xe5 1,0 kg.']]]],
 '_pages': [6, 9],
 u'_rank': 22,
 u'_type': u'LSFU'}