{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Perifer vasokonstrikti on Perifer blekhet Hypertoni'],
             ['Respiratory', u'\xd6verg\xe5ende'],
             ['GI', u'kramp i buken \xd6verg\xe5ende diarr\xe9']]],
           ['Uncommon',
            [['Metabolism', u'Hyponatremi om inte v\xe4tska monitoreras'],
             ['Cardiac',
              u'F\xf6rmaksflimmer Ventrikul\xe4r extrasystole Takykardi Br\xf6stsm\xe4rta Myokardinfarkt Lung\xf6dem p\xe5 grund av v\xe4tske-\xf6verbelastning'],
             ['Vascular', u'Intestinal ischemi Perifer cyanos V\xe4rmevallningar'],
             ['Respiratory', u'Andn\xf6d Andningsinsufficiens \xd6verg\xe5ende'],
             ['GI', u'illam\xe5ende \xd6verg\xe5ende kr\xe4kning'],
             ['General', u'Nekros vid injektionsst\xe4llet']]],
           ['Rare', [['Respiratory', u'Dyspn\xe9']]],
           ['Unknown',
            [['Cardiac', u'Torsades de pointes Hj\xe4rtsvikt'],
             ['Skin', u'Hudnekros'],
             ['Pregnancy', u'Livmodersam-mandragningar Minskat blodfl\xf6de genom livmodern']]]],
 '_note': u' ?MSFU',
 '_pages': [2, 3],
 u'_rank': 15,
 u'_type': u'MSFU'}