{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk']]],
           ['Common',
            [['Nervous system', u'Vertigo'],
             ['Skin', u'Ansiktsrodnad'],
             ['Vascular', u'Yrsel'],
             ['General', u'Matthetsk\xe4nsl a'],
             ['GI', u'Illam\xe5ende']]],
           ['Uncommon',
            [['General', u'Br\xe4nnande k\xe4nsla, svidande k\xe4nsla, bl\xe5sor p\xe5 tungan']]],
           ['Rare',
            [['Vascular', u'Postural hypotension'],
             ['Cardiac', u'Takykardi, Bradykardi'],
             ['Skin', u'Allergiska hudreaktioner']]],
           ['Very rare', [['Skin', u'Exfoliativ dermatit']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 11,
 u'_type': u'MSFU'}