{'_data': [['Common',
            [['Ear', u' yrsel'],
             ['GI', u' diarr\xe9, f\xf6rstoppning, anorexi'],
             ['Vascular', u' hypertension'],
             ['General', u' feber, asteni  ']]],
           ['Uncommon', [['Eye', u' synrubbningar']]],
           ['Rare',
            [['Cardiac',
              u' arytmier s\xe5 som sinusbradykardi, f\xf6rmaksflimmer, varierande grader av AV-blockering, ventrikul\xe4r ektopi (inklusive icke-ih\xe5llande takykardi), onormalt EKG'],
             ['Eye',
              u'dystoni och dyskinesi har rapporterats med l\xe4kemedel bland 5HT3-antagonisterna'],
             ['Vascular', u'hypotension'],
             ['Immune system',
              u' \xf6verk\xe4nslighetsreaktioner, ibland sv\xe5ra (t.ex. anafylaxi, andn\xf6d, hypotension, urtikaria)']]],
           ['Very rare', [['Immune system', u'\xf6dem (inklusive ansikts\xf6dem)']]]],
 '_pages': [3, 4],
 u'_rank': 10,
 u'_type': u'LSFU2'}