{'_data': [['Common', [['GI', u'Illam\xe5ende, diarr\xe9.'], ['Skin', u'Exantem.']]],
           ['Uncommon', [['Blood', u'Eosinofili.'], ['Skin', u'Urtikaria.']]],
           ['Rare',
            [['Blood', u'Agranulocytos.'],
             ['Immune system', u'Anafylaktiska reaktioner.'],
             ['Hepato',
              u'Leverp\xe5verkan av oftast blandad  kolestatisk-hepatocellull\xe4r typ.']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'TSFU'}