{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk']]],
           ['Common',
            [['Immune system',
              u'\xd6verk\xe4nslighet mot sp\xe4dningsv\xe4tskan (metakresol/glycerol)'],
             ['Endocrine', u'Hypotyreos'],
             ['Nervous system', u'Karpaltunnelsydrom'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Respiratory', u'S\xf6mnapn\xe9'],
             ['General', u'Sm\xe4rta (reaktion) vid injektionsst\xe4llet'],
             ['General', u'\xd6dem (lokalt och allm\xe4nt)']]],
           ['Uncommon', [['General', u'Svaghet']]],
           ['Rare',
            [['Nervous system', u'Benign intrakraniell tryckstegring'],
             ['Nervous system', u'Parestesier']]],
           ['Very rare',
            [['Reproductive system', u'Gynekomasti'],
             ['Nervous system', u'S\xf6mnl\xf6shet'],
             ['Vascular', u'Hypertension'],
             ['Investigations', u'Glykosuri']]],
           ['Unknown',
            [['Metabolism', u'spontant med ok\xe4nd frekvens Insulinresistens'],
             ['Musculoskeletal', u'<1/1000)']]]],
 '_pages': [6, 7],
 u'_rank': 17,
 u'_type': u'LSFU'}