{'_data': [['Common',
            [['Blood', u'Leukocytos, trombocytopeni'],
             ['Metabolism',
              u'Hypokalemi, f\xf6rh\xf6jda urinsyror, avvikande natrium i blod, hypokalcemi, hyperglykemi, hypofosfatemi, dehydrering Psykiska st\xf6rningar Vanliga Hum\xf6rsv\xe4ngningar (inklusive depression), \xe5ngest, s\xf6mnl\xf6shet Centrala och perifera Mycket vanliga Huvudv\xe4rk'],
             ['Metabolism',
              u'Parestesi (inklusive hypoastesi), migr\xe4n, nervrotskompression'],
             ['Metabolism',
              u'Gastrointestinal bl\xf6dning, dyspepsi, Gastroesofageal reflux sjukdom, Sicca syndrom'],
             ['Metabolism',
              u'Nytt utbrott av eller f\xf6rv\xe4rrande av psoriasis (inklusive palmoplantar pustular psoriasis) , urtikaria, bl\xe5m\xe4rken (inklusive purpura), dermatit (inklusive eksem), sk\xf6ra naglar, hyperhidros, alopeci , pruritus,'],
             ['Metabolism', u'Muskelspasmer (inklusive f\xf6rh\xf6jt blodkreatininfosfokinas)'],
             ['Metabolism', u'Vanliga Br\xf6stsm\xe4rta, \xf6dem, feber 1)']]],
           ['Uncommon',
            [['Blood', u'Idiopatisk tromobytopen purpura'],
             ['Blood', u'mindre vanliga Sarkoidos 1)'],
             ['Metabolism', u', tremor, neuropati'],
             ['Metabolism', u'Diplopi \xd6ron och balansorgan Vanliga Yrsel'],
             ['Metabolism', u'D\xf6vhet, tinnitus Hj\xe4rtat* Vanliga Takykardi'],
             ['Metabolism', u', arytmi, kronisk hj\xe4rtsvikt'],
             ['Metabolism',
              u'Aortaaneurysm, vaskul\xe4r art\xe4rocklusion, tromboflebit Andningsv\xe4gar, br\xf6stkorg Vanliga Astma, dyspn\xe9, hosta och mediastinum*'],
             ['Metabolism',
              u', interstitiell lungsjukdom, kronisk obstruktiv lungsjukdom, intersitiell lungsjukdom, pneumonit, pleural effusion'],
             ['Metabolism',
              u'Pankreatit, dysfagi, ansikts\xf6dem 79 Organklass Frekvens Biverkningar'],
             ['Metabolism',
              u'Kolecystit och kolelitias, leversteatos, f\xf6rh\xf6jt bilirubin, leversteatos'],
             ['Metabolism', u'Nattsvettningar, \xe4rr'],
             ['Metabolism', u'Rabdomyolys, Systemisk lupus erytematos'],
             ['Metabolism',
              u'Nokturi Reproduktionsorgan och Mindre vanliga Erektil dysfunktion br\xf6stk\xf6rtel Allm\xe4nna symtom och/eller Mycket vanliga Reaktion vid injektionsst\xe4llet (inklusive erytem vid symtom vid injektionsst\xe4llet) administreringsst\xe4llet*'],
             ['Metabolism',
              u'Inflammation Unders\xf6kningar* Vanliga Koagulations och bl\xf6dningsst\xf6rningar (inklusive f\xf6rl\xe4ngd aktiverad partiell tromboplastintid), Positivt autoantikroppstest (inklusive dubbelstr\xe4ngad DNA), f\xf6rh\xf6jt blodlaktatdehydrogenas 80 Organklass Frekvens Biverkningar Skador, f\xf6rgiftningar och Vanliga F\xf6rs\xe4mrad l\xe4kning behandlingskomplikationer']]],
           ['Rare',
            [['Blood',
              u'Pancytopeni Immunsystemet* Vanliga Hypersensitivitet, allergier (inklusive s\xe4songsallergi)'],
             ['Metabolism',
              u'Multipel skleros, demyelinerande sjukdomar (t.ex. optisk neurit, Guillain-Barr\xe9 syndrom) 1) \xd6gon Vanliga Synneds\xe4ttning, konjunktivit, blefarit, \xf6gonsvullnad'],
             ['Metabolism',
              u'Hj\xe4rtstillest\xe5nd Blodk\xe4rl Vanliga Hypertension, rodnad, hematom'],
             ['Metabolism',
              u'1) fibros Magtarmkanalen Mycket vanliga Buksm\xe4rta, illam\xe5ende och kr\xe4kning'],
             ['Metabolism',
              u'S\xe4llsynta Intestinal perforation 1) Lever och gallv\xe4gar* Mycket vanliga F\xf6rh\xf6jda leverenzymer'],
             ['Metabolism',
              u'S\xe4llsynta Hepatit, reaktivering av hepatit B , autoimmun hepatit'],
             ['Metabolism',
              u'S\xe4llsynta Erytema multiforme , Stevens-Johnson syndrom , angio\xf6dem , kutan vaskulit 1) Muskuloskeletala systemet Mycket vanliga Muskuloskeletal sm\xe4rta och bindv\xe4v'],
             ['Metabolism',
              u'syndrom Njurar och urinv\xe4gar Vanliga F\xf6rs\xe4mrad njurfunktion, hematuri']]],
           ['Unknown',
            [['Blood', u'agranulocytos), anemi'],
             ['Metabolism',
              u'Leversvikt Hud och subkutan v\xe4vnad Mycket vanliga Hudutslag (inklusive exfoliativa hudutslag)'],
             ['Hepato',
              u'I kontrollerade fas-3 pr\xf6vningar med Humira hos patienter med reumatoid artrit och psoriasis artrit med en kontrollperiod mellan 4 till 104 veckor s\xe5 uppstod ALT \xf6kningar \u2265 3 x ULN hos 3,7% av Humira-behandlade patienter och 1,6% av kontroll-behandlade patienter. I kontrollerade fas-3 pr\xf6vningar med Humira hos patienter med plack psoriasis med en kontrollperiod p\xe5 mellan 12 och 24 veckor, s\xe5 uppstod ALT \xf6kningar \u2265 3 x ULN hos 1,8% av Humira-behandlade patienter och 1,8% av kontroll-behandlade patienter. I JIA studien var transaminas\xf6kningarna f\xe5 och sm\xe5, likv\xe4rdiga f\xf6r de placebo- och adalimumab behandlande patienterna och s\xe5gs oftast i kombination med metotrexat. I kontrollerade fas-3 pr\xf6vningar med Humira hos patienter med Crohn\u2019s sjukdom och ulcer\xf6s kolit med en varierande kontrollperiod p\xe5 mellan 4 och 52 veckor, s\xe5 uppstod ALT \xf6kningar \u2265 3 x ULN hos 0,9% av Humira-behandlade patienter och 0,9% av kontroll-behandlade patienter. \xd6ver alla indikationer i kliniska pr\xf6vningar var patienter med f\xf6rh\xf6jt ALT asymptomatiska och i de flesta fall var \xf6kningarna \xf6verg\xe5ende och upph\xf6rde med fortsatt behandling. Det finns dock rapporter efter marknadsf\xf6ring om leversvikt liksom mindre allvarliga leverrubbningar som kan f\xf6reg\xe5 leversvikt, s\xe5som hepatit inklusive autoimmun hepatit, hos patienter som f\xe5r adalimumab. Samtidig behandling med azatioprin/6-merkaptopurin H\xf6gre incidenser av maligna och allvarliga infektionsrelaterade biverkningar s\xe5gs i studier med Crohns sjukdom hos vuxna d\xe5 Humira kombinerades med azatioprin/6-merkaptopurin j\xe4mf\xf6rt med Humira ensamt.']]]],
 '_pages': [12, 17],
 u'_rank': 32,
 u'_type': u'LSFU'}