{'_data': [['Very common',
            [['Cardiac',
              u'hj\xe4rtklaff\xf6r\xe4ndringar (inklusive \xe5terfl\xf6de) och relaterade'],
             ['GI', u'Mycket']]],
           ['Rare',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Cardiac', u'Bradykardi'],
             ['Cardiac', u'st\xf6rningar (perikardit och perikardiell utgjutning).'],
             ['Vascular', u'Hypotension (s\xe4rskilt efter parenteral administrering)'],
             ['Respiratory', u'N\xe4st\xe4ppa'],
             ['GI', u'Illam\xe5ende, sura uppst\xf6tningar, kr\xe4kningar, diarr\xe9'],
             ['GI', u'Retroperitoneal fibros'],
             ['Skin',
              u'Hudutslag De gastrointestinala biverkningarna kan i allm\xe4nhet undvikas om preparatet tas tillsammans med m\xe5ltid.']]]],
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'LSFU'}