{'_data': [['Unknown',
            [['Infections',
              u'Aktivering av infektioner (tuberkulos, svamp- herpesinfektioner och cytomegalovirus).'],
             ['Endocrine',
              u'F\xf6rs\xe4mring av latent eller manifest diabetes mellitus. Tillv\xe4xth\xe4mning hos barn. Relativ binjurebarkinsufficiens efter uts\xe4ttande. Cushingliknande symptombild.'],
             ['Metabolism', u'Natriumretention med \xf6demtendens. Hypokalemi.'],
             ['Psychiatric', u'Eufori och psykoser, s\xf6mnl\xf6shet.'],
             ['Nervous system', u'Pseudotum\xf6r cerebri hos barn.'],
             ['Eye', u'\xd6kat intraokul\xe4rt tryck och katarakt.'],
             ['Vascular', u'Hypertension.'],
             ['GI', u'Dyspepsi och f\xf6rs\xe4mring av best\xe5ende ulcus ventriculi.'],
             ['Skin',
              u'Striae och ekymoser, acne och hirsutism. F\xf6rs\xe4mrad s\xe5rl\xe4kning.'],
             ['Musculoskeletal', u'Osteoporos med spontan fraktur.']]]],
 '_pages': [3, 3],
 u'_rank': 10,
 u'_type': u'LSFU'}