{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Esofagit, gastrit, gastroesofageal refluxsjukdom, dyspepsi, diarr\xe9, buksm\xe4rta, illam\xe5ende'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, muskuloskeletal sm\xe4rta, muskelkramper, muskuloskeletal stelhet'],
             ['General', u'Influensaliknande sjukdom*']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel'],
             ['GI',
              u'Esofagit inkluderande esofaguss\xe5r eller esofagusstriktur och dysfagi, kr\xe4kningar, flatulens'],
             ['Musculoskeletal', u'Ryggsm\xe4rta'],
             ['General', u'Tr\xf6tthet']]],
           ['Rare',
<<<<<<< HEAD
            [['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
=======
            [['Immune system', u'\xd6verk\xe4nslighetsreaktione'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Eye', u'Okul\xe4ra inflammationer*'],
             ['GI', u'Duodenit'],
             ['Skin', u'Angio\xf6dem, ansikts\xf6dem, urtikaria'],
             ['Musculoskeletal',
              u'Atypiska subtrokant\xe4ra och diafys\xe4ra femurfrakturer\u2020 (bisfosfonat klassbiverkning)']]],
           ['Very rare', []]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 14,
 u'_type': u'MSFU'}