{'_data': [['Uncommon',
            [['Blood', u'anemi'],
             ['Nervous system', u'parestesi, dysgeusi'],
             ['GI',
              u'bl\xf6dning, ulcus duodeni, gastrit, dysfagi,   buksm\xe4rta, muntorrhet'],
             ['Skin', u'kl\xe5da'],
             ['Renal', u'azotemi (uremi)'],
             ['General',
              u'br\xf6stsm\xe4rta, influensa-liknande sjukdom,   sjukdomsk\xe4nsla, sm\xe4rta'],
             ['Investigations', u'f\xf6rh\xf6jt parathormon']]]],
 '_pages': [4, 5],
 u'_rank': 7,
 u'_type': u'LFSUR'}