{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Dyspepsi, diarr\xe9, illam\xe5ende,  kr\xe4kningar, buksm\xe4rtor, flatulens, f\xf6rstoppning, melena, hematemes, gastrointestinal bl\xf6dning'],
             ['Skin', u'Hudutslag'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Infections', u'Rinit'],
             ['Psychiatric', u'S\xf6mnl\xf6shet, l\xe4tt oro'],
             ['Eye', u'Synrubbningar'],
             ['Ear', u'H\xf6rselskador'],
             ['Respiratory', u'Astma, f\xf6rv\xe4rrad astma,  bronkospasm, dyspn\xe9'],
             ['GI', u'Gastrit, ulcus (ventriculi et  duodeni), ulcerativ stomatit'],
             ['Hepato', u'Hepatit, gulsot'],
             ['Renal', u'Interstitiell nefrit, nefrotiskt  syndrom, njursvikt'],
             ['Skin', u'Urtikaria, pruritus, purpura,  angio\xf6dem, fotosensitivitet'],
             ['Renal', u'Interstitiell nefrit, nefrotiskt  syndrom, njursvikt']]],
           ['Rare',
            [['Infections', u'Aseptisk meningit'],
             ['Blood', u'Leukopeni, trombocytopeni,  aplastisk anemi'],
             ['Immune system', u'Anafylaktisk reaktion.'],
             ['Psychiatric', u'Depression, konfusion'],
             ['Nervous system', u'Optikusneurit, somnolens'],
             ['Eye', u'Toxisk amblyopi'],
             ['Ear', u'Tinnitus, yrsel'],
             ['GI', u'Perforationer.'],
             ['Hepato', u'Leverskador'],
             ['Skin',
              u'Bull\xf6sa reaktioner  inklusive Stevens-Johnsons syndrom, toxisk epidermal nekrolys, erythema multiforme'],
             ['General', u'\xd6dem']]]],
 '_pages': [7, 8],
 u'_rank': 25,
 u'_type': u'TSFU'}