{'_data': [['Common',
            [['GI',
              u'besv\xe4r fr\xe5n mag-tarmkanalen s\xe5 som halsbr\xe4nna, buksm\xe4rta, illam\xe5ende, kr\xe4kningar, flatulens, diarr\xe9, f\xf6rstoppning och sm\xe5 gastrointestinala bl\xf6dningar som i exceptionella fall kan orsaka anemi.']]],
           ['Uncommon',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner med hudutslag och kl\xe5da s\xe5 v\xe4l som astmaanfall (eventuellt med blodtrycksfall). Patienten m\xe5ste instrueras att informera en l\xe4kare genast och att inte l\xe4ngre ta Ibuprofen ratiopharm i detta fall.'],
             ['Nervous system',
              u'huvudv\xe4rk, yrsel, s\xf6mnl\xf6shet, uppr\xf6rdhet, retlighet eller tr\xf6tthet.'],
             ['Eye',
              u'synst\xf6rningar. I detta fall b\xf6r patienten instrueras att informera en l\xe4kare genast och att sluta ta ibuprofen.'],
             ['GI',
              u'gastrointestinala s\xe5r, eventuellt med bl\xf6dning och perforation. Ulcer\xf6s stomatit, f\xf6rs\xe4mring av kolit och Crohns sjukdom (se avsnitt 4.4), gastrit.']]],
           ['Rare', [['Ear', u'tinnitus.']]],
           ['Very rare',
            [['Infections',
              u'ta fall har f\xf6rs\xe4mring av infektionsrelaterade inflammationer (t.ex. utveckling av nekrotiserande fasciit) beskrivits i samband med anv\xe4ndning av icke-steroida antiinflammatoriska l\xe4kemedel. Detta har eventuellt ett samband med verkningsmekanismen f\xf6r icke-steroida antiinflammatoriska l\xe4kemedel. Om tecken p\xe5 infektion f\xf6rekommer eller f\xf6rv\xe4rras under anv\xe4ndning av Ibuprofen ratiopharm rekommenderas patienterna att utan dr\xf6jsm\xe5l upps\xf6ka l\xe4kare. Det m\xe5ste utredas om det finns indikationer f\xf6r antiinfektiv behandling eller antibiotikabehandling.'],
             ['Infections',
              u'fall har symtom p\xe5 aseptisk meningit med nackstyvhet, huvudv\xe4rk, illam\xe5ende, kr\xe4kningar, feber eller nedsatt medvetandegrad observerats under ibuprofenbehandling. Patienter med autoimmuna sjukdomar (SLE, blandade bindv\xe4vssjukdomar) f\xf6refaller vara predisponerade.'],
             ['Blood',
              u'hematopoetiska st\xf6rningar (anemi, leukopeni, trombocytopeni, pancytopeni, agranulocytos). Det f\xf6rsta tecknet kan vara: feber, ont i halsen, ytliga lesioner i munnen, influensaliknande symtom, sv\xe5r utmattning, bl\xf6dning fr\xe5n n\xe4san och huden. I s\xe5dana fall b\xf6r patienterna tillr\xe5das att sluta ta l\xe4kemedlet omedelbart, att undvika egenv\xe5rd med analgetika eller antipyretika och att kontakta en l\xe4kare.'],
             ['Immune system',
              u'sv\xe5ra allm\xe4nna \xf6verk\xe4nslighetsreaktioner. Dessa kan yttra sig som ansikts\xf6dem, svullnad av tungan, svullnad av struphuvudet med luftv\xe4gssammandragning, andningssvikt, skenande hj\xe4rta, blodtrycksfall och \xe4ven livshotande chock. Om ett av dessa symtom f\xf6rekommer, vilket \xe4ven kan intr\xe4ffa vid f\xf6rsta intaget, kr\xe4vs omedelbar l\xe4karhj\xe4lp.'],
             ['Psychiatric', u'psykotiska reaktioner, depression.'],
             ['Cardiac', u'hj\xe4rtklappningar, hj\xe4rtsvikt, hj\xe4rtinfarkt.'],
             ['Vascular', u'arteriell hypertoni.'],
             ['GI',
              u'esofagit, pankreatit, bildning av intestinala, diafragmaliknande strikturer. Patienten m\xe5ste instrueras att sluta ta l\xe4kemedlet och upps\xf6ka l\xe4kare genast om sv\xe5r sm\xe4rta i \xf6vre buken eller melena eller hematemes intr\xe4ffar.'],
             ['Hepato',
              u'leverdysfunktion, leverskada, s\xe4rskilt vid l\xe5ngtidsbehandling, leversvikt, akut hepatit.'],
             ['Skin',
              u'bull\xf6sa reaktioner inklusive Stevens-Johnsons syndrom och toxisk epidermal nekrolys i enstaka fall kan sv\xe5ra hudinfektioner med mjukv\xe4vnadskomplikationer f\xf6rekomma vid en vattkoppsinfektion (se \xe4ven \u201cInfektioner och infestationer\u201d).'],
             ['Renal',
              u'reducerad urinuts\xf6ndring och \xf6dem. Dessa tecken kan tyda p\xe5 njursjukdom som ibland kan inkludera njursvikt. Om s\xe5dana symtom f\xf6rekommer eller f\xf6rv\xe4rras b\xf6r patienterna tillr\xe5das att sluta ta ibuprofen och att kontakta en l\xe4kare omedelbart skador i njurv\xe4vnaden (papill\xe4r nekros), s\xe4rskilt vid l\xe5ngtidsbehandling f\xf6rh\xf6jd koncentration av urinsyra i serum.']]]],
 '_pages': [6, 8],
 u'_rank': 17,
 u'_type': u'LSFU'}