{'_data': [['Common',
            [['Blood', u'eosinofili'],
             ['Vascular', u'tromboflebit'],
             ['GI',
              u'diarr\xe9, kr\xe4kningar, illam\xe5ende.  L\xe4kemedelsrelaterat illam\xe5ende och/eller kr\xe4kningar verkar f\xf6rekomma mer frekvent hos patienter med granulocytopeni j\xe4mf\xf6rt med patienter som inte har granulocytopeni och som behandlas med imipenem/cilastatin'],
             ['Skin', u'hudutslag (t.ex. exantemat\xf6sa )'],
             ['Investigations',
              u'f\xf6rh\xf6jda serumtransaminaser, f\xf6rh\xf6jda  alkaliska fosfataser i serum']]],
           ['Uncommon',
            [['Blood', u'pancytopeni, neutropeni, leukopeni,  trombocytopeni, trombocytos'],
             ['Psychiatric',
              u'psykiska st\xf6rningar inklusive  hallucinationer och f\xf6rvirringstillst\xe5nd'],
             ['Nervous system', u'krampanfall, myoklonisk aktivitet,  yrsel, somnolens'],
             ['Vascular', u'hypotoni'],
             ['Skin', u'n\xe4sselfeber, pruritus'],
             ['General',
              u'feber, lokal sm\xe4rta och induration vid  injektionsst\xe4llet, erytem vid  injektionsst\xe4llet'],
             ['Investigations',
              u'positivt provsvar vid direkt Coombs  test, f\xf6rl\xe4ngd protrombintid, minskat hemoglobin, f\xf6rh\xf6jt serumbilirubin, f\xf6rh\xf6jt serumkreatinin, f\xf6rh\xf6jt ureakv\xe4ve i blod']]],
           ['Rare',
            [['Infections', u'pseudomembran\xf6s kolit, candidiasis'],
             ['Blood', u'agranulocytos'],
             ['Immune system', u'anafylaktiska reaktioner'],
             ['Nervous system',
              u'encefalopati, parestesi, fokal tremor,  smakf\xf6r\xe4ndringar'],
             ['Ear', u'h\xf6rselneds\xe4ttning'],
             ['GI', u'missf\xe4rgning av t\xe4nder och/eller tunga'],
             ['Hepato', u'leversvikt, hepatit'],
             ['Skin',
              u'toxisk epidermal nekrolys, angio\xf6dem,  Stevens-Johnsons syndrom, erythema multiforme, exfoliativ dermatit'],
             ['Renal',
              u'akut njursvikt, oliguri/anuri, polyuri,  missf\xe4rgning av urin (ofarligt och ska inte f\xf6rv\xe4xlas med hematuri). Imipenem/cilastatins roll vid p\xe5verkan av njurfunktionen \xe4r sv\xe5r att bed\xf6ma, eftersom faktorer som predisponerar f\xf6r prerenal azotemi eller nedsatt njurfunktion ofta f\xf6rekommit.']]],
           ['Very rare',
            [['Infections', u'gastroenterit'],
             ['Blood', u'hemolytisk anemi,  benm\xe4rgsdepression'],
             ['Nervous system', u'f\xf6rv\xe4rrad myastenia gravis, huvudv\xe4rk'],
             ['Ear', u'yrsel, tinnitus'],
             ['Cardiac', u'cyanos, takykardi, palpitationer'],
             ['Vascular', u'rodnad'],
             ['Respiratory', u'dyspn\xe9, hyperventilation, faryngeal  sm\xe4rta'],
             ['GI',
              u'hemorragisk kolit, buksm\xe4rta,  halsbr\xe4nna, glossit, tungpapillhypertrofi, \xf6kad salivuts\xf6ndring'],
             ['Hepato', u'fulminant hepatit'],
             ['Skin', u'hyperhidros, f\xf6r\xe4ndringar i hudens  struktur'],
             ['Musculoskeletal', u'polyartralgi, thorakal ryggradssm\xe4rta'],
             ['Reproductive system', u'pruritus vulvae'],
             ['General', u'obehag fr\xe5n br\xf6stet, asteni/svaghet']]]],
 '_pages': [6, 8],
 u'_rank': 34,
 u'_type': u'TSFU'}