{'_data': [['Uncommon', [['Respiratory', u'Halsirritation'], ['Skin', u'Utslag']]],
           ['Rare',
            [['Respiratory', u'Orofaryngeal sm\xe4rta'],
             ['Respiratory', u'Torrhosta'],
             ['Skin', u'Pruritus'],
             ['General', u'Feber']]],
           ['Unknown',
            [['Blood', u'Utveckling av inhibitorer'],
             ['Blood', u'Disseminerad intravaskul\xe4r  koagulation'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Immune system', u'Angio\xf6dem'],
             ['Immune system', u'N\xe4sselfeber  Vid f\xf6rekomst av inhibitorer'],
             ['Immune system', u'Serumsjuka'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Rastl\xf6shet'],
             ['Nervous system', u'Stickningar'],
             ['Cardiac', u'Myokardiell infarkt'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotension'],
             ['Vascular', u'Tromboembolism'],
             ['Vascular', u'Lungemboli'],
             ['Vascular', u'Ventrombos'],
             ['Vascular', u'Rodnad'],
             ['Respiratory', u'V\xe4sande andning'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['Skin', u'Urtikaria'],
             ['Renal', u'Nefrotiskt syndrom'],
             ['General', u'Frossa'],
             ['General', u'Br\xe4nnande och sveda p\xe5  infusionsst\xe4llet'],
             ['General', u'Letargi'],
             ['General', u'Tr\xe5nghetsk\xe4nsla i br\xf6stet']]]],
 '_pages': [4, 6],
 u'_rank': 34,
 u'_type': u'TSFU'}