{'_data': [['Uncommon', [['Immune system', u'\xd6verk\xe4nslighet']]],
           ['Unknown',
            [['Blood', u'Faktor VIII inhibering'],
             ['Psychiatric', u'Rastl\xf6shet'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'\xd6gonlocks\xf6dem'],
             ['Cardiac', u'Takykardi'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotoni'],
             ['Vascular', u'V\xe4rmevallning'],
             ['Vascular', u'Blekhet'],
             ['Vascular', u'Hosta'],
             ['GI', u'Kr\xe4kning'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Urtikaria'],
             ['Skin', u'Utslag (inklusive  erytemat\xf6st och papul\xf6st utslag)'],
             ['Skin', u'Pruritus'],
             ['Skin', u'Erytem'],
             ['Skin', u'Hyperhidros'],
             ['Skin', u'Obehagsk\xe4nsla i br\xf6stet'],
             ['Skin', u'\xd6dem (inklusive perifert  \xf6dem och ansikts\xf6dem)'],
             ['Skin', u'Pyrexi'],
             ['Skin', u'Frossa'],
             ['Skin',
              u'Reaktion p\xe5  injektionsst\xe4llet (inklusive br\xe4nnande k\xe4nsla)']]]],
 '_pages': [5, 6],
 u'_rank': 24,
 u'_type': u'TSFU'}