{'_data': [['Rare', [['Eye', u'Mios  '], ['Renal', u'Urinretention  ']]],
           ['Unknown',
            [['Immune system',
              u'anafylaktisk reaktion (inkluderande anafylaktisk S\xe4llsynta chock) , anafylaktoid reaktion Centrala och perifera'],
             ['GI',
              u'F\xf6rstoppning, illam\xe5ende, Vanliga Vanliga Vanliga flatulens Buksm\xe4rtor, obehag i buken, Mindre vanliga Mindre vanliga Mindre vanliga muntorrhet Buksm\xe4rtor i \xf6vre del, kr\xe4kningar Mindre vanliga Mindre vanliga Dyspepsi Mindre vanliga Mindre vanliga Ileus (inkluderande paralytisk ileus), megakolon (inkluderande S\xe4llsynta toxisk megakolon ), glossodyni Uppsp\xe4nd buk S\xe4llsynta S\xe4llsynta'],
             ['Skin', u'Utslag Mindre vanliga Mindre vanliga'],
             ['Skin',
              u'Stevens-Johnsons syndrom, toxisk epidermal nekrolys och S\xe4llsynta erythema multiforme) angio\xf6dem , urtikaria , pruritus'],
             ['General',
              u'symtom vid administreringsst\xe4llet Tr\xf6tthet S\xe4llsynta a: Inkludering av denna term baseras p\xe5 rapporter efter marknadsf\xf6ring f\xf6r lopermidhydroklorid. Eftersom processen f\xf6r att best\xe4mma biverkningar efter marknadsf\xf6ring inte skiljer mellan kroniska och akuta indikationer eller vuxna och barn s\xe5 \xe4r frekvensen en uppskattning fr\xe5n alla kliniska pr\xf6vningar med loperamidhydroklorid, inklusive pr\xf6vningar p\xe5 barn \u2264 12 \xe5r (N=3683). b: se avsnitt 4.4 Varningar och f\xf6rsiktighet. c. Rapporterat f\xf6r muns\xf6nderfallande tablett enbart. Biverkningar i kliniska pr\xf6vningar angivna utan frekvens blev inte observerade eller v\xe4rderade som biverkan f\xf6r denna indikation.']]]],
 '_pages': [4, 6],
 u'_rank': 7,
 u'_type': u'LSFU'}