{'_data': [['Very common',
            [['GI', u'Illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Hepato', u'\xd6kade leverenzymer +'],
             ['Skin', u'Hudutslag'],
             ['Renal',
              u'Feber, huvudv\xe4rk, frossa, utmattning, sm\xe4rta vid injektionsst\xe4llet']]],
           ['Common',
            [['Psychiatric', u'Depression'],
             ['GI', u'Magsm\xe4rta'],
             ['Musculoskeletal', u'Myalgi, artralgi, ryggsm\xe4rta']]],
           ['Unknown',
            [['Blood', u'Neutropeni #, trombocytopeni #'],
             ['Metabolism', u'Hyponatremi*, hyperglykemi*, hypertriglyceridemi*'],
             ['Psychiatric', u'F\xf6rvirringstillst\xe5nd*, desorientering*, hallucinationer*'],
             ['Nervous system',
              u'Konvulsioner*, Parkinsonliknande g\xe5ngst\xf6rningar*, Parkinsonliknande vilotremor*, g\xe5ngst\xf6rningar*'],
             ['Cardiac',
              u'Hj\xe4rtsvikt*, hj\xe4rtinfarkt*, takyartymi*, AV-block* Blodk\xe4rl: Transitoriska ischemiska attacker*, djup'],
             ['GI', u'Pankreatit (inkluderande fatal utg\xe5ng)*, mag-tarm hemorragi*.'],
             ['Hepato', u'Leversvikt*'],
             ['Skin', u'(exacerbationer av) Dermatomyosit*'],
             ['Musculoskeletal', u'Systemisk lupus erytematosus*'],
             ['Renal',
              u'(reversibel) Njursvikt*, proteinuri# Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Investigations',
<<<<<<< HEAD
              u'Positiva autoantikroppar* + Frekvensen h\xf6gre i placebogruppen \xe4n i verumgruppen.']]]],
=======
              u'Positiva autoantikroppar* + Frekvensen h\xf6gre i placebogruppen \xe4n i verumgruppen. *Biverkningarna som s\xe5gs i kliniska studier p\xe5 andra indikationer \xe4n de godk\xe4nda CGD och osteopetros. I dessa studier var dosen interferon gamma-lb vanligen h\xf6gre \xe4n den som rekommenderas f\xf6r de godk\xe4nda indikationerna (se \xe4ven avsnitt 4.9). c) Information om individuella allvarliga och/eller ofta f\xf6rekommande biverkningar De influensaliknande symtomen kan minska i sv\xe5righetsgrad vid fortsatt behandling. Genom att administrera Imukin p\xe5 kv\xe4llen f\xf6re s\xe4ngg\xe5ende, minimeras upplevelsen av vissa av dessa symtom. F\xf6r att lindra de influensaliknande symtomen kan paracetamol ges. Illam\xe5ende, kr\xe4kningar, artralgi och \xf6mhet vid injektionsst\xe4llet har rapporterats hos vissa patienter. \xd6verg\xe5ende hudutslag, t ex dermatit, makulopapul\xf6sa utslag, pustul\xf6sa eller vesikul\xf6sa utslag samt erytem p\xe5 injektionsst\xe4llet har f\xf6rekommit hos vissa patienter, men detta har s\xe4llan lett till uts\xe4ttning av behandlingen. Produktion av autoantikroppar och systemisk lupus erytematosus finns i biverkningslistan pga litteraturrapporter. \xc4ven \u201df\xf6rvirring\u201d baseras p\xe5 en publicerad fallrapport.']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_pages': [3, 5],
 u'_rank': 18,
 u'_type': u'LSFU'}