{'_data': [['Very common',
            [['Infections', u'\xd6kad infektions-k\xe4nsligh et'],
             ['Blood', u'Benm\xe4rgsh\xe4mning , leukopeni']]],
           ['Common', [['Blood', u'Trombocyto-pen'], ['GI', u'Illam\xe5ende']]],
           ['Uncommon',
            [['Neoplasms', u'Mutagenicitet'],
             ['Blood', u'Anemi'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['GI', u'Kr\xe4kning, pankreatit'],
             ['Hepato', u'Gallstas, st\xf6rd leverfunktion'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['General', u'Feber, aptitl\xf6shet, olustk\xe4nsla']]],
           ['Rare',
            [['Neoplasms',
              u'Lymfom (non-Hodgkins) , hudcancer (melanom, non-melanom) sarkom (Kaposis, non-Kaposis) livmoderhals-ca akut myeloisk leukemi, myelodys-plasi'],
             ['Blood',
              u'Agranulocytos, pancytopeni, aplastisk anemi, megaloblastisk anemi, erytroid hypoplasi'],
             ['Cardiac', u'Hypotoni'],
             ['GI', u'Tarmperfo-ratio n, bl\xf6dning i tarmen'],
             ['Hepato', u'Hepatisk venocklusion'],
             ['Skin', u'Alopeci , hudutslag']]],
           ['Very rare',
            [['Neoplasms', u','],
             ['Immune system', u'Stevens-Johnso ns syndrom, toxisk epidermal nekrolys'],
             ['Nervous system', u'Yrsel'],
             ['Respiratory', u'Interstitiell pneumonit'],
             ['GI', u'Kolit , divertikulit , diarr\xe9'],
             ['Skin', u'Kl\xe5da, vaskulit'],
             ['Musculoskeletal', u'Muskelstelhet'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['General', u'Allm\xe4n sjukdomsk\xe4nsla']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 7],
 u'_rank': 26,
 u'_type': u'MSFU'}