{'_data': [['Very common',
            [['Infections', u'Blodet och lymfsystemet  '],
             ['Eye', u'Magtarmkanalen  '],
             ['Hepato', u'Hud och subkutan v\xe4vnad  ']]],
           ['Common',
            [['Endocrine', u'Metabolism och nutrition  '],
             ['Renal', u'Allm\xe4nna symtom och/eller  ']]]],
 '_pages': [18, 21],
 u'_rank': 5,
 u'_type': u'LSFU'}