{'_data': [['Very common',
            [['Nervous system',
              u'somnolens huvudv\xe4rk (inom \xe5ldersintervallet 6-13 \xe5r)'],
             ['Metabolism', u'aptitil\xf6shet'],
             ['General',
              u'feber > 38.0\xb0C sm\xe4rta, rodnad och svullnad p\xe5 injektionsst\xe4llet*,'],
             ['Psychiatric', u'otr\xf6stlig gr\xe5t, irritabilitet, rastl\xf6shet']]],
           ['Common',
            [['GI', u'diarr\xe9, kr\xe4kning, illam\xe5ende'],
             ['General',
              u'feber > 39.5\xb0C, sjukdomsk\xe4nsla, reaktioner vid injektionsst\xe4llet inklusive induration, asteni']]],
           ['Uncommon', [['Skin', u'allergisk dermatit, hudutslag']]],
           ['Rare',
            [['Blood', u'lymfadenopati'],
             ['Respiratory', u'bronkit , hosta'],
             ['Skin', u'kl\xe5da, urticaria']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Nervous system',
              u'Kollaps eller chockliknande tillst\xe5nd (hypotonisk-hyporesponsiv episod), konvulsioner (med eller utan feber) inom 2 till 3 dagar efter vaccination.'],
             ['Respiratory', u'Apn\xe9'],
             ['Skin', u'Angioneurotiskt \xf6dem'],
             ['General', u'Bl\xe5sor vid injektionsst\xe4llet'],
             ['Immune system',
              u'och anafylaktoida reaktioner rapporterade med GSKs DTPa-inneh\xe5llande vacciner. rapporterade med D och T vacciner']]]],
 '_pages': [3, 4],
 u'_rank': 16,
 u'_type': u'LSFU'}