{'_data': [['Common',
            [['Nervous system', u'Somnolens, yrsel, huvudv\xe4rk'],
             ['Ear', u'Svindel'],
             ['Vascular', u'Vallning, blodvallning'],
             ['Respiratory', u'Halsirritation'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar F\xf6rstoppning,'],
             ['Skin', u'Hyperhidros']]],
           ['Uncommon',
            [['Psychiatric', u'Beroende, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Sedering, myoklonus, parestesi, dysestesi, dysgeusi'],
             ['Ear', u'R\xf6relsesjuka'],
             ['Cardiac', u'Hypotension'],
             ['Respiratory', u'Andningsdepression, n\xe4sblod, n\xe4ss\xe5r, rinorr\xe9'],
             ['GI', u'stomatit, muntorrhet'],
             ['Skin', u'Sm\xe4rta i huden, pruritus'],
             ['General', u'Pyrexi']]],
           ['Unknown', [['Psychiatric', u'Hallucination']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 15,
 u'_type': u'MSFU'}