{'_data': [['Common',
            [['Metabolism', u'\xd6dem'],
             ['Eye', u'Proliferativ'],
             ['Skin', u'Lipodystrofi'],
             ['General', u'Reaktioner p\xe5 injektionsst\xe4llet']]],
           ['Uncommon',
            [['Immune system', u'Chock'], ['General', u'Urtikaria p\xe5 injektionsst\xe4llet']]],
           ['Unknown',
            [['Immune system',
              u'Omedelbar allergisk reaktion (hypotension, angio\xf6dem, bronkospasm, allm\xe4nna hudreaktioner); Antikroppar mot insulin'],
             ['Metabolism', u'Hypoglykemi; Natriumretention'],
             ['Eye', u'retinopati; Diabetesretinopati; Synneds\xe4ttning'],
             ['General',
              u'Inflammation p\xe5 injektionsst\xe4llet; Sm\xe4rta p\xe5 injektionsst\xe4llet; Kl\xe5da p\xe5 injektionsst\xe4llet; Erytem p\xe5 injektionsst\xe4llet; Svullnad p\xe5 injektionsst\xe4llet;']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 10,
 u'_type': u'MSFU'}