{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Musculoskeletal', u'Myalgi Artralgi'],
             ['General',
              u'Sjukdomsk\xe4nsla, Lokala reaktioner: rodnad*, svullnad, induration, sm\xe4rta, pruritus']]],
           ['Common', [['General', u'Frossa, feber, Lokala reaktioner: ekkymos']]],
           ['Uncommon',
            [['Blood', u'Lymf-adenopati'],
             ['Nervous system', u'Parestesi'],
             ['Skin', u'Pruritus, utslag'],
             ['General', u'Asteni']]],
           ['Rare', [['Skin', u'Svett-ningar']]],
           ['Very rare', []],
           ['Unknown',
            [['Immune system',
              u'Allergiska reaktioner inklusive allm\xe4nna hudreaktioner som exempelvis n\xe4sselfeber, anafylaktiska reaktioner, angio\xf6dem, chock.']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 10,
 u'_type': u'MSFU'}