{'_data': [['Uncommon',
            [['Blood', u'Hemolys (lindrig)'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, gastrointestinal sm\xe4rta'],
             ['Nervous system',
              u'\xd6kad kroppstemperatur, positivt Coombs test  (indirekt och direkt)'],
             ['Nervous system', u'Smakrubbning'],
             ['Skin', u'Papul\xf6sa utslag'],
             ['Vascular', u'Hypertoni, ytlig tromboflebit']]]],
 '_pages': [6, 7],
 u'_rank': 6,
 u'_type': u'TSFU'}