{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['GI', u'Diarr\xe9, buksm\xe4rta'],
             ['General', u'Obehag, matthet, frossa'],
             ['Immune system', u'Infusionsrelaterad reaktion, \xf6verk\xe4nslighet'],
             ['Nervous system', u'Huvudv\xe4rk, k\xe4nslorubbning'],
             ['Musculoskeletal', u'Ledv\xe4rk, ryggv\xe4rk, benv\xe4rk, muskelv\xe4rk'],
             ['Skin', u'Sm\xe4rta i huden'],
             ['Vascular', u'Hyperemi, hypertension']]],
           ['Uncommon',
            [['Blood', u'Hemolys (lindrig)'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, gastrointestinal sm\xe4rta'],
             ['General', u'Pyrexi, frossa, v\xe4rmek\xe4nsla'],
             ['Investigations',
              u'\xd6kad kroppstemperatur, positivt Coombs test  (indirekt och direkt)'],
             ['Skin', u'Papul\xf6sa utslag'],
             ['Vascular', u'Hypertoni, ytlig tromboflebit']]]],
 '_pages': [6, 8],
 u'_rank': 15,
 u'_type': u'TSFU'}