{'_data': [[u'Unknown',
            [['Infections',
              u'bronkit,   \xf6vre   lung-   \xf6goninfektion,   luftv\xe4gsinfektion,   inflammation,   onykomykos,'],
             ['Blood', u'anemi,   agranulocytos   , minskning av   neutropeni, minskat'],
             ['Immune system', u'anafylaktisk'],
             ['Endocrine', u'inadekvat   sekretion'],
             ['Metabolism',
              u'vikt\xf6kning,   diabetes   vattenf\xf6rgiftning,   hyperinsulinemi   aptit\xf6kning,   mellitus   , diabetisk'],
             ['Psychiatric',
              u'insomni   mani,   agitation,   s\xf6mnproblem,   k\xe4nslom\xe4ssig   depression, \xe5ngest   f\xf6rvirrings-   avtrubbning'],
             ['Nervous system',
              u'parkinson-   dystoni   , yrsel,   krampanfall   , malignt   ism   , dyskinesi   , svimning,   neuroleptika-   akatisi   , tremor   psykomotorisk   syndrom, tardiv'],
             ['Ear', u'vertigo,   tinnitus,   \xf6ronsm\xe4rta'],
             ['Vascular', u'ortostatisk   Hypotension ven\xf6s   trombos,'],
             ['Respiratory',
              u'faryngolaryngeal   dyspn\xe9, pipande   s\xf6mnapn\xe9syndrom,   lungstas'],
             ['GI', u'buksm\xe4rta,   svullen tunga,   pankreatit   ,'],
             ['Hepato', u'transaminas-   gamma-   gulsot   \xf6kning   glutamyl-'],
             ['Skin',
              u'pruritus,   utslag   urtikaria,   angio\xf6dem,   alopeci, akne   l\xe4kemedelsutslag   , hyperkeratos,'],
             ['Renal', u'urininkontines,   pollakisuri,'],
             ['Pregnancy', u'neonatalt'],
             ['Reproductive system',
              u'amenorr\xe9   erektil   priapism   , f\xf6rdr\xf6jd   dysfunktion,   menstruation   , ejakulations-   gynekomasti,'],
             ['General', u'pyrexi,   asteni,   ansikts\xf6dem,   hypotermi   ,'],
             ['General',
              u'temperatur,   obehag i   onormal g\xe5ng,   br\xf6stkorgen,   \xf6kad t\xf6rst,   induration   ,'],
             ['Injury', u'fall']]]],
 '_pages': [7, 12],
 u'_rank': 19,
 u'_type': u'LFSU'}