{'_data': [['Common',
            [['Eye', u'Ackommodationsst\xf6rningar'],
             ['Cardiac', u'Palpitationer, takykardi'],
             ['GI', u'Muntorrhet, illam\xe5ende']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel, nervositet'],
             ['Cardiac', u'\xd6kat systoliskt blodtryck, arytmi'],
             ['GI', u'Kr\xe4kningar'],
             ['Renal', u'Urinretention']]],
           ['Rare',
            [['Immune system',
              u'Anafylaktisk reaktion, angio\xf6dem  i ansikte, p\xe5 l\xe4ppar och i hals'],
             ['Metabolism', u'Hypokalemi'],
             ['Psychiatric',
              u'Rastl\xf6shet, minnesst\xf6rningar,  \xe5ngest, hyperaktivitet hos barn'],
             ['Nervous system', u'Svettningar, depression'],
             ['Eye',
              u'Sm\xe4rta i \xf6gonen, mydriasis, \xf6kat  intraokul\xe4rt tryck, glaukom med st\xe4ngd kammarvinkel'],
             ['Cardiac',
              u'Reducerat diastoliskt blodtryck,  perifer vasodilation, arytmier (inklusive f\xf6rmaksflimmer, supraventrikul\xe4r takykardi, extrasystole) och koronar ischemisk sjukdom'],
             ['Cardiac',
              u'Bronkospasm, laryngospasm,  dyspn\xe9, paradoxal bronkospasm (d.v.s. inhaleringsinducerad bronkospasm)'],
             ['GI', u'Munirritation,  motilitetsst\xf6rningar'],
             ['Skin', u'Utslag, kl\xe5da, urticaria'],
             ['Skin', u'Myalgi, muskelkramp och  muskelsvaghet']]],
           ['Unknown', [['Cardiac', u'Myokardial ischemi (se avsnitt  4.4)']]]],
 '_pages': [4, 5],
 u'_rank': 18,
 u'_type': u'TSFU'}