{'_data': [['Very common',
            [['Investigations',
              u'hyperkalemi* upptr\xe4dde mer frekvent hos diabetespatienter behandlade med irbesartan \xe4n med placebo. Hos hypertonipatienter med diabetes och med mikroalbuminuri och normal njurfunktion upptr\xe4dde hyperkalemi (\u2265 5,5 mekv/l) hos 29,4% av patienterna i irbesartan 300 mg-gruppen och hos 22% av patienterna i placebogruppen. Hos hypertonipatienter med diabetes och med kronisk njurinsufficiens och overt proteinuri upptr\xe4dde hyperkalemi (\u2265 5,5 mekv/l) hos 46,3% av patienterna i irbesartangruppen och hos 26,3% av patienterna i placebogruppen.']]],
           ['Common',
            [['Nervous system', u'yrsel, ortostatisk yrsel*'],
             ['Vascular', u'ortostatisk hypotoni*'],
             ['GI', u'illam\xe5ende/kr\xe4kningar'],
             ['Musculoskeletal', u'muskuloskeletal sm\xe4rta*'],
             ['General', u'tr\xf6tthet'],
             ['Investigations',
              u'signifikanta \xf6kningar av kreatinkinas i plasma s\xe5gs ofta (1,7%) hos irbesartanbehandlade personer. Ingen av dessa \xf6kningar hade samband med identifierbara, kliniska, muskuloskeletala h\xe4ndelser. Hos 1,7% av hypertonipatienter med framskriden diabetesrelaterad njursjukdom behandlad med irbesartan har en s\xe4nkning i hemoglobin*, som inte var kliniskt signifikant, observerats.']]],
           ['Uncommon',
            [['Cardiac', u'takykardi'],
             ['Vascular', u'rodnad'],
             ['Respiratory', u'hosta'],
             ['GI', u'diarr\xe9, dyspepsi/halsbr\xe4nna'],
             ['Hepato', u'gulsot'],
             ['Reproductive system', u'sexuell dysfunktion'],
             ['General', u'br\xf6stsm\xe4rta']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner s\xe5som angio\xf6dem, hudutslag och urtikaria'],
             ['Metabolism', u'hyperkalemi'],
             ['Nervous system', u'vertigo, huvudv\xe4rk'],
             ['Ear', u'tinnitus'],
             ['GI', u'dysgeusi'],
             ['Hepato', u'hepatit, st\xf6rd leverfunktion'],
             ['Skin', u'leukocytoklastisk vaskulit'],
             ['Musculoskeletal',
              u'artralgi, myalgi (i n\xe5gra fall \xe5tf\xf6ljt av \xf6kade plasmaniv\xe5er av kreatinkinas), muskelkramper'],
             ['Renal',
              u'nedsatt njurfunktion, inklusive fall av njursvikt hos riskpatienter (se avsnitt 4.4)']]]],
 '_pages': [5, 6],
 u'_rank': 23,
 u'_type': u'LSFU'}