{'_data': [['Very common',
            [['Investigations',
              u'hyperkalemi* upptr\xe4dde mer frekvent hos diabetespatienter behandlade med irbesartan \xe4n med placebo. Hos hypertonipatienter med diabetes och med mikroalbuminuri och normal njurfunktion upptr\xe4dde hyperkalemi (\u22655,5 mekv/l) hos 29,4% av patienterna i irbesartan 300 mg-gruppen och hos 22% av patienterna i placebogruppen. Hos hypertonipatienter med diabetes och med kronisk njurinsufficiens och overt proteinuri upptr\xe4dde hyperkalemi (\u22655,5 mekv/l) hos 46,3% av patienterna i irbesartangruppen och hos 26,3% av patienterna i placebogruppen.']]],
           ['Common',
            [['Investigations',
              u'signifikanta \xf6kningar av kreatinkinas i plasma s\xe5gs ofta (1,7%) hos irbesartanbehandlade personer. Ingen av dessa \xf6kningar hade samband med identifierbara, kliniska, muskuloskeletala h\xe4ndelser. Hos 1,7% av hypertonipatienter med framskriden diabetesrelaterad njursjukdom behandlad med irbesartan har en s\xe4nkning i hemoglobin*, som inte var kliniskt signifikant, observerats.'],
             ['Nervous system', u'yrsel, ortostatisk yrsel*'],
             ['GI', u'illam\xe5ende/kr\xe4kningar'],
             ['Musculoskeletal', u'muskuloskeletal sm\xe4rta*'],
             ['Vascular', u'ortostatisk hypotoni*'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Cardiac', u'takykardi'],
             ['Respiratory', u'hosta'],
             ['GI', u'diarr\xe9, dyspepsi/halsbr\xe4nna'],
             ['Vascular', u'rodnad'],
             ['General', u'br\xf6stsm\xe4rta'],
             ['Reproductive system',
              u'sexuell dysfunktion F\xf6ljande ytterligare biverkningar har rapporterats sedan irbesartan introducerades p\xe5 marknaden; de baseras p\xe5 spontana rapporter, varf\xf6r frekvensen av dessa biverkningar inte \xe4r k\xe4nd']]],
           ['Unknown',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Ear', u'Tinnitus'],
             ['GI', u'Dysgeusi'],
             ['Renal',
              u'Nedsatt njurfunktion, inklusive fall av njursvikt hos riskpatienter (se avsnitt 4.4)'],
             ['Skin', u'Leukocytoklastisk vaskulit'],
             ['Musculoskeletal',
              u'Artralgi, myalgi (i n\xe5gra fall \xe5tf\xf6ljt av \xf6kade plasmaniv\xe5er av kreatinkinas), muskelkramper'],
             ['Metabolism', u'Hyperkalemi'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner s\xe5som angio\xf6dem, hudutslag och urtikaria'],
             ['Hepato', u'Hepatit, st\xf6rd leverfunktion']]]],
 '_pages': [4, 6],
 u'_rank': 22,
 u'_type': u'LSFU'}