{'_data': [['Very common',
            [['Metabolism', u'Anorexi, l\xe4tt eller m\xe5ttlig (CTC  grad 1 eller 2)'],
             ['GI',
              u'Diarr\xe9, huvudsakligen l\xe4tt eller  m\xe5ttlig (CTC grad 1 eller 2) Kr\xe4kningar, huvudsakligen l\xe4tta eller m\xe5ttliga (CTC grad 1 eller 2) Illam\xe5ende, huvudsakligen l\xe4tt (CTC grad 1). Stomatit, huvudsakligen l\xe4tt (CTC grad 1).'],
             ['Hepato',
              u'Huvudsakligen l\xe4tta till m\xe5ttliga  stegringar i alaninaminotransferas'],
             ['Skin',
              u'Hudreaktioner huvudsakligen l\xe4tta  till m\xe5ttliga (CTC grad 1 eller 2)  pustul\xe4ra utslag, ibland kl\xe5da med torr hud, inklusive hudsprickor, p\xe5 erytemat\xf6s bas'],
             ['General', u'Asteni, huvudsakligen l\xe4tt (CTC  grad 1).']]],
           ['Common',
            [['Eye',
              u'Konjunktivit, blefarit och torra  \xf6gon*, huvudsakligen l\xe4tt (CTC grad 1)'],
             ['Vascular', u'Bl\xf6dning, s\xe5som n\xe4sblod och blod  i urinen'],
             ['Respiratory',
              u'Interstitiell lungsjukdom (1,3 %),  ofta sv\xe5r (CTC grad 3-4). Fall med  d\xf6dlig utg\xe5ng har rapporterats'],
             ['GI',
              u'Dehydrering, till f\xf6ljd av diarr\xe9,  illam\xe5ende, kr\xe4kningar eller anorexi. Muntorrhet *, huvudsakligen l\xe4tt (CTC grad 1).'],
             ['Hepato',
              u'Huvudsakligen l\xe4tta till m\xe5ttliga  stegringar i aspartataminotrans- feras Huvudsakligen l\xe4tta till m\xe5ttliga stegringar i totalt bilirubin'],
             ['Skin', u'Nagelproblem  H\xe5ravfall'],
             ['Renal',
              u'Asymptomatiska h\xf6jningar av  laboratoriev\xe4rden f\xf6r blod- kreatinin Proteinuri Cystit'],
             ['General', u'Feber']]],
           ['Uncommon',
            [['Eye',
              u'Korneaerosion, reversibel och  ibland i kombination med in\xe5tv\xe4xande \xf6gonfransar Keratit (0,12 %)'],
             ['GI', u'Pankreatit, gastrointestinal  perforation'],
             ['Hepato', u'Hepatit***'],
             ['Skin', u'Allergiska reaktioner** inklusive  angi\xf6dem och urtikaria']]],
           ['Rare',
            [['Skin',
              u'Bull\xf6sa sjukdomar, inklusive  toxisk epidermal nekrolys, Stevens Johnson syndrom och erythema multiforme Kutan vaskulit']]]],
 '_pages': [5, 7],
 u'_rank': 18,
 u'_type': u'TSFU'}