{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk'], ['GI', u'Dyspepsi*']]],
           ['Common',
            [['Nervous system', u''],
             ['Nervous system', u'Yrsel, s\xf6mnighet'],
             ['General', u'Svaghetsk\xe4nsla'],
             ['General', u'Hypotension'],
             ['Cardiac', u'Takykardi'],
             ['GI', u'Illam\xe5ende']]],
           ['Uncommon',
            [['General',
              u'Cirkulationssvikt med  f\xf6rv\xe4rrande av anginasymtom  (ibland tillsammans med bradyarytmi och svimning); \xd6verg\xe5ende hypoxemi med myokardiell hypoxi hos patienter med kransk\xe4rlssjukdom.'],
             ['GI', u'Kr\xe4kningar, diarr\xe9']]],
           ['Rare',
            [['Nervous system', u'Svimning'], ['GI', u''], ['Skin', u'Utslag, kl\xe5da']]],
           ['Unknown',
            [['Cardiac', u'Paroxysmal bradyk ardi'],
             ['Skin', u'Exfoliativ dermatit  rodnad,  allergiska hudreaktioner**']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'TSFU'}