{'_data': [['Common',
            [['Metabolism', u'nedsatt aptit'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Respiratory', u'hicka'],
             ['GI', u'f\xf6rstoppning, dyspepsi'],
             ['General', u'tr\xf6tthet'],
             ['Investigations', u'f\xf6rh\xf6jt ALAT']]],
           ['Uncommon',
            [['Blood', u'febril neutropeni, anemi'],
             ['Psychiatric', u'\xe5ngest'],
             ['Nervous system', u'yrsel, s\xf6mnighet'],
             ['Cardiac', u'palpitationer'],
             ['Vascular', u'vallningar'],
             ['Skin', u'utslag, acne'],
             ['Renal', u'dysuri'],
             ['General', u'asteni, sjukdomsk\xe4nsla'],
             ['Investigations',
              u'f\xf6rh\xf6jt ASAT, f\xf6rh\xf6jt alkaliskt fosfatas i  blodet'],
             ['Vascular',
              u'blodvallningar, tromboflebit  (\xf6verv\xe4gande tromboflebit vid infusionsst\xe4llet)'],
             ['Skin', u'erytem'],
             ['General',
              u'erytem vid infusionsst\xe4llet,  sm\xe4rta vid infusionsst\xe4llet,  kl\xe5da vid infusionsst\xe4llet'],
             ['Investigations', u'f\xf6rh\xf6jt blodtryck']]],
           ['Rare',
            [['Infections', u'candidiasis, stafylokockinfektion'],
             ['Metabolism', u'polydipsi'],
             ['Psychiatric', u'desorientering, euforisk k\xe4nsla'],
             ['Nervous system', u'kognitiv st\xf6rning, letargi, dysguesi'],
             ['Eye', u'konjunktivit'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'bradykardi, hj\xe4rt-k\xe4rlsjukdom'],
             ['Respiratory',
              u'orofaryngeal sm\xe4rta, nysning, hosta,  baksnuva, svalgirritation'],
             ['Skin',
              u'fotosensitivitet, hyperhidros, seborr\xe9,  hudf\xf6r\xe4ndring, kliande utslag, Stevens-Johnsons syndrom/toxisk epidermal nekrolys'],
             ['Musculoskeletal', u'muskelsvaghet, muskelspasmer'],
             ['Renal', u'pollakisuri'],
             ['General', u'\xf6dem, obehagsk\xe4nsla i br\xf6stet, g\xe5ngst\xf6rning'],
             ['Investigations',
              u'positivt test f\xf6r r\xf6da blodkroppar i urin,  minskat natrium i blodet, viktminskning, minskat neutrofilantal, glukos i urinen, \xf6kad urinproduktion'],
             ['General', u'induration vid infusionsst\xe4llet']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inkluderande  anafylaktiska reaktioner'],
             ['Skin', u'kl\xe5da, urtikaria'],
             ['General',
              u'omedelbar  \xf6verk\xe4nslighetsreaktion inkluderande blodvallningar, erytem, dyspn\xe9']]]],
 '_pages': [7, 9],
 u'_rank': 36,
 u'_type': u'TSFU'}