{'_data': [['Very common', [['GI', u'gastrointestinala biverkningar  ']]],
           ['Common',
            [['General', u'perifert \xf6dem  '], ['Nervous system', u'metallsmak i munnen  ']]],
           ['Uncommon',
            [['Nervous system', u'huvudv\xe4rk  '], ['Nervous system', u'somnolens ']]],
           ['Very rare',
            [['Hepato', u'onormal leverfunktion, hepatit  '],
             ['Skin',
              u'ta fall kan resultera i en kliniskt signifikant vitamin B -brist (t ex megaloblastisk anemi). b Gastrointestinala biverkningar som illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta och aptitf\xf6rlust \xe4r vanligt f\xf6rekommande i b\xf6rjan av behandlingen men f\xf6rsvinner i de flesta fall utan \xe5tg\xe4rd.']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inkluderande anafylaxi Ingen k\xe4nd frekvens'],
             ['Metabolism', u'hypoglykemi Vanliga Mycket vanliga Vanliga Mycket vanliga'],
             ['Respiratory', u'interstitiell lungsjukdom  '],
             ['GI',
              u'f\xf6rstoppning Mindre vanliga Vanliga \xf6vre buksm\xe4rta Mindre vanliga kr\xe4kningar Vanliga Ingen k\xe4nd Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens frekvens muntorrhet Mindre vanliga akut pankreatit Ingen k\xe4nd frekvens fatal och icke-fatal hemorragisk och nekrotiserande Ingen k\xe4nd frekvens pankreatit'],
             ['Skin',
              u'exfoliativa hudtillst\xe5nd inkluderande Stevens- Ingen k\xe4nd frekvens Johnsons syndrom'],
             ['Musculoskeletal',
              u'sm\xe4rta i extremiteter *Ingen k\xe4nd frekvens ryggsm\xe4rta Ingen k\xe4nd frekvens'],
             ['Renal', u'nedsatt njurfunktion  '],
             ['Renal', u'akut njursvikt  '],
             ['Investigations',
              u'blodglukos- s\xe4nkning Mindre vanliga Biverkningar rapporterade efter marknadsf\xf6ring. Se avsnitt 4.4. Ytterligare information om de enskilda aktiva substanserna i den fasta doskombinationen Sitagliptin I monoterapistudier d\xe4r sitagliptin 100 mg en g\xe5ng dagligen j\xe4mf\xf6rdes med placebo, rapporterades f\xf6ljande biverkningar: huvudv\xe4rk, hypoglykemi, f\xf6rstoppning och yrsel. Hos dessa patienter f\xf6rekom biverkningar, oavsett om ett samband med l\xe4kemedelsbehandling f\xf6rel\xe5g eller ej, hos minst 5% och innefattade \xf6vre luftv\xe4gsinfektion och nasofaryngit. Artros och sm\xe4rta i armar eller ben rapporterades med frekvensen mindre vanliga (>0,5% h\xf6gre hos patienter som behandlades med sitagliptin \xe4n den i kontrollgruppen). Sammantaget i de olika kliniska studierna observerades en liten \xf6kning av antalet vita blodkroppar till f\xf6ljd av \xf6kad m\xe4ngd neutrofila granulocyter (skillnaden i LPK j\xe4mf\xf6rt med placebo var ca 0,2 celler x10 /l; medelutg\xe5ngsv\xe4rdet f\xf6r LPK var i genomsnitt 6,6 celler x10 /l). Detta observerades i de flesta studier men inte i alla. Denna f\xf6r\xe4ndring av laboratoriev\xe4rden anses inte kliniskt relevant. Metformin'],
             ['Metabolism', u'vitamin B a -brist Mycket s\xe4llsynta'],
             ['Skin',
              u'L\xe5ngtidsbehandling med metformin har associerats med en minskad absorption av vitamin B 12 vilket']]]],
 '_pages': [6, 9],
 u'_rank': 18,
 u'_type': u'LSFU'}