{'_data': [['Common',
            [['Vascular', u'Tromboflebit'], ['General', u'F\xf6rh\xf6jd kroppstemperatur']]],
           ['Uncommon',
            [['GI', u'Buksm\xe4rta, illam\xe5ende, kr\xe4kningar'],
             ['Investigations', u'H\xf6jning av leverenzymv\xe4rden'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['General', u'Frysningar, tr\xf6tthet']]],
           ['Very rare',
            [['Blood', u'Hemolys, retikulocytos'],
             ['Respiratory', u'Andningsbesv\xe4r (tachypn\xe9)'],
             ['Immune system',
              u'Allergiska reaktioner (anafylaktiska reaktioner, hudutslag, n\xe4sselfeber)'],
             ['Reproductive system', u'Priapism'],
             ['Vascular', u'Hypotension, hypertension']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 11,
 u'_type': u'MSFU'}