{'_data': [['Uncommon', [['Metabolism', u'Hypercalcemi och hyperkalciuri.']]],
           ['Rare',
            [['GI', u'F\xf6rstoppning, flatulens, illam\xe5ende, buksm\xe4rtor och diarr\xe9.'],
             ['Skin', u'Kl\xe5da, utslag och urtikaria.']]],
           ['Very rare',
            [['Metabolism',
              u'ses vanligen enbart vid \xf6verdosering (se avsnitt 4.9) mj\xf6lk-alkalisyndrom.']]]],
 '_pages': [3, 3],
 u'_rank': 4,
 u'_type': u'LSFU'}