{'_data': [['Very common',
            [['Infections', u'\xd6vre luftv\xe4gsinfektion'],
             ['GI', u'Diarr\xe9, illam\xe5ende']]],
           ['Common',
            [['Infections',
              u'Nedre luftv\xe4gsinfektion, hudinfektioner  inklusive celluliter, follikulit och furunkulos'],
             ['Blood', u'Anemi, leukopeni, neutropeni, lymfadenopati'],
             ['Immune system', u'Hypersensitivitet inklusive urtikaria och  angio\xf6dem'],
             ['Metabolism',
              u'Blodglukosrubbningar inklusive diabetes  mellitus, hypertriglyceridemi, hyperkolesterolemi, viktnedg\xe5ng, minskad aptit'],
             ['Psychiatric', u'\xc5ngest'],
             ['Nervous system',
              u'Huvudv\xe4rk (inklusive migr\xe4n), neuropati  (inklusive perifer neuropati), yrsel, insomnia'],
             ['Vascular', u'Hypertension'],
             ['Hepato', u'Hepatit inklusive f\xf6rh\xf6jt AST, ALT och GGT'],
             ['Skin',
              u'F\xf6rv\xe4rvad lipodystrofi, inklusive ansikte, utslag  inklusive makulopapul\xf6sa utslag, dermatit/utslag inklusive eksem och seborroisk dermatit, nattliga svettningar, pruritis'],
             ['Musculoskeletal',
              u'Myalgi, muskuloskeletal sm\xe4rta inklusive  artralgi och ryggsm\xe4rta, muskelrubbningar  s\xe5som svaghet och spasmer'],
             ['Reproductive system',
              u'Erektil dysfunktion, menstruationsrubbningar,  amenorr\xe9, menorrhagi'],
             ['General', u'Tr\xf6tthet inklusive asteni']]],
           ['Uncommon',
            [['Immune system', u'Immunrekonstitutionssyndrom'],
             ['Endocrine', u'Hypogonadism'],
             ['Metabolism', u'Viktuppg\xe5ng, \xf6kad aptit'],
             ['Psychiatric', u'Avvikande dr\xf6mmar, s\xe4nkt libido'],
             ['Nervous system',
              u'Cerebrovaskul\xe4r h\xe4ndelse, konvulsion,  dysgeusi, ageusi, tremor'],
             ['Eye', u'Nedsatt syn'],
             ['Cardiac',
              u'Ateroskleros s\xe5som hj\xe4rtinfarkt,  atrioventrikul\xe4rblock, trikuspidalisinsufficiens'],
             ['Vascular', u'Djup ventrombos'],
             ['Hepato', u'Leversteatos, hepatomegali, kolangit,  hyperbilirubinemi'],
             ['Skin', u'Alopeci, kapillarit, vaskulit'],
             ['Musculoskeletal', u'Rhabdomyolys, osteonekros'],
             ['Renal', u'S\xe4nkt kreatininclearance, nefrit, hematuri']]],
           ['Unknown', [['Hepato', u'Gulsot'], ['Skin', u'Stevens-Johnsons syndrom, erythema']]]],
 '_pages': [18, 20],
 u'_rank': 28,
 u'_type': u'TSFU'}