{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['Ear', u'Vertigo.'],
             ['GI',
              u'Epigastrisk sm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta, dyspepsi, flatulens, anorexi. Gastrit, gastrointestinal bl\xf6dning, hematemes,'],
             ['Hepato', u'Transaminasstegringar (ASAT, ALAT).'],
             ['Skin', u'Utslag.']]],
           ['Uncommon', [['Vascular', u'Bronkospasm']]],
           ['Rare',
<<<<<<< HEAD
            [['GI', u'), inklusive enstaka rapporter.'],
=======
            [['GI',
              u'(<1/10000), inklusive enstaka rapporter. Tabellen inkluderar biverkningar b\xe5de fr\xe5n l\xe5ngtids- och korttidsanv\xe4ndning.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner inklusive anafylaktiska och anafylaktoida reaktioner (inklusive hypotoni och chock).'],
             ['Nervous system', u'Somnolens.'],
             ['Vascular', u'Astma (inklusive dyspn\xe9).'],
             ['GI',
              u'blodiga diarr\xe9er, melaena, peptiska s\xe5r eller tarms\xe5r med eller utan bl\xf6dning eller perforation. Diafragmaliknande tarmrestrikturer.'],
             ['Hepato',
              u'Leverfunktionst\xf6rningar inklusive hepatit med eller utan ikterus.'],
             ['Skin', u'Urtikaria.'],
             ['Reproductive system', u'Impotens (samband tveksamt)'],
             ['General', u'\xd6dem']]],
           ['Very rare',
            [['Blood',
              u'Trombocytopeni, leukopeni, anemi (inklusive hemolytisk och aplastisk anemi), agranulocytos.'],
             ['Immune system', u'Angioneurotiskt \xf6dem (inklusive ansikts\xf6dem).'],
             ['Psychiatric',
              u'Desorientering, depression, insomningssv\xe5righeter, mardr\xf6mmar, irritabilitet, psykotiska st\xf6rningar.'],
             ['Nervous system',
              u'K\xe4nselbortfall s\xe5som parestesi, minnesst\xf6rningar, kramper, \xe4ngslan, tremor, aseptisk meningit, smakf\xf6r\xe4ndringar, cerebrovaskul\xe4r h\xe4ndelse.'],
             ['Eye', u'Synst\xf6rningar, dimsyn, dubbelseende.'],
             ['Ear', u'\xd6ronsusning, nedsatt h\xf6rsel.'],
             ['Cardiac', u'Palpitationer, br\xf6stsm\xe4rta, hj\xe4rtsvikt, hj\xe4rtinfarkt.'],
             ['Vascular',
              u'Hypertoni, vaskulit. Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Pneumonit.'],
             ['GI',
              u'Tjocktarmsbesv\xe4r (ospecifik hemorragisk kolit och exacerbationer av ulcer\xf6s kolit eller Crohns proktokolit), obstipation. Stomatit (inklusive ulcerativ stomatit), glossit, esofagusst\xf6rningar. Pankreatit.'],
             ['Hepato', u'Fulminant hepatit, levernekros, leversvikt.'],
             ['Skin',
              u"Bull\xf6sa eruptioner, eksem, erytema, erytema multiforme, Stevens-Johnsons syndrom, akut toxisk epidermal nekrolys (Lyell's syndrome), exfoliativ dermatit, h\xe5ravfall, ljusk\xe4nslighetsreaktioner, purpura, allergisk purpura, pruritus."],
             ['Renal',
              u'Akut njurinsufficiens, hematuri, proteinuri, nefrotiskt syndrom, interstitiell nefrit, papillar nekros.']]],
           ['Unknown',
            [['GI',
              u'vanligen inom n\xe5gra dagar, \xe4ven under fortsatt terapi. Gastroduodenals\xe5r, perforation eller gastrointestinal bl\xf6dning kan ibland vara livshotande, s\xe4rskilt hos \xe4ldre (se avsnitt 4.4). Detta kan intr\xe4ffa n\xe4r som helst under behandlingen med eller utan varningssymtom eller tidigare sjukdomshistoria. Diklofenak h\xe4mmar tempor\xe4rt trombocytaggregationen, vilket kan leda till \xf6kad risk hos patienter med olika bl\xf6dningssjukdomar. I s\xe4llsynta fall f\xf6rekommer allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor. Biverkningarna i tabellen \xe4r ordnade efter frekvens, med de vanligast f\xf6rekommande biverkningarna f\xf6rst, enligt f\xf6ljande frekvensangivelse: mycket vanliga (>1/10), vanliga (>1/100, <1/10), mindre vanliga (>1/1000, <1/100), s\xe4llsynta (>1/10000, <1/1000), mycket']]]],
 '_pages': [8, 10],
 u'_rank': 29,
 u'_type': u'LSFU'}