{'_data': [['Very common', [['Nervous system', u'ga Mindre S\xe4llsynta Ok\xe4nd frekvens']]],
           ['Common',
            [['Nervous system',
              u') vanliga (>1/10 000, (Erfarenheter efter (>1/10) (>1/1000, <1/1000) lansering) <1/100)']]],
           ['Unknown',
            [['Nervous system', u'Biverkningsfrekvens'],
             ['Immune system', u'Anafylaktisk reaktion*'],
             ['Metabolism', u'Anorexia'],
             ['Psychiatric',
              u'Hallucinationer, \xc5ngest, oro Delirium* onormala dr\xf6mmar, flashback*, mardr\xf6mmar, dysfori*, f\xf6rvirring, s\xf6mnl\xf6shet, agitation, onormalt desorientering beteende'],
             ['Nervous system', u'Nystagmus, tonisk kloniska r\xf6relser'],
             ['Eye', u'intraokul\xe4rt tryck'],
             ['Vascular', u'Hypotension'],
             ['Respiratory',
              u'\xd6kad Andnings-depre Obstruktiv andningsfrekvens ssion, lungsjukdom*, laryngospasm apn\xe9*'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, Hypersalivation*'],
             ['Skin', u'morbilliforma utslag'],
             ['Musculoskeletal', u'\xd6kad muskeltonus'],
             ['General',
              u'Sm\xe4rta vid injektions-st\xe4ll et, utslag vid injektions-st\xe4ll et']]]],
 '_pages': [4, 6],
 u'_rank': 14,
 u'_type': u'LSFU'}