{'_data': [['Uncommon',
            [['Infections', u'Follikulit'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['Skin',
              u'Alopeci Torr hud F\xf6r\xe4ndringar i h\xe5rets struktur Utslag Br\xe4nnande k\xe4nsla i huden'],
             ['General',
              u'Rodnad p\xe5 applikationsst\xe4llet Irritation p\xe5 applikationsst\xe4llet Kl\xe5da p\xe5 applikationsst\xe4llet Hudreaktioner vid applikationsst\xe4llet']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'F\xf6r\xe4ndringar i smaksinnet'],
             ['Eye', u'Irritation i \xf6gonen'],
             ['Skin', u'Akne Kontaktdermatit Hudreaktioner Peeling'],
             ['General',
              u'\xd6verk\xe4nslighet p\xe5 applikationsst\xe4llet Pustler p\xe5 applikationsst\xe4llet']]],
           ['Unknown', [['Skin', u'Angio\xf6dem Urtikari Missf\xe4rgning av h\xe5ret']]]],
 '_note': u' ?MSFU',
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'MSFU'}