{'_data': [['Common',
            [['Psychiatric', u'Eufori'],
             ['Nervous system', u'Sedering, yrsel'],
             ['Cardiac', u'Bradykardi'],
             ['Respiratory', u'Andningsdepression'],
             ['GI', u'Muntorrhet'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, obstipation'],
             ['Renal', u'Urinretention'],
             ['Investigations', u'Blodtrycksfall']]],
           ['Uncommon', [['Eye', u'Dimsyn']]],
           ['Rare',
            [['Immune system', u'/ Mycket s\xe4llsynta (<1/1 000)'],
             ['Skin', u'Angio\xf6dem, urtikaria, utslag']]],
           ['Unknown',
            [['Psychiatric', u'F\xf6rvirring, beroende, abstinensbesv\xe4r'],
             ['Nervous system', u'Huvudv\xe4rk']]]],
 '_pages': [3, 3],
 u'_rank': 13,
 u'_type': u'LSFU'}