{'_data': [['Common',
            [['Metabolism', u'Hyperkalemi##'],
             ['Psychiatric', u'Insomni#'],
             ['Nervous system', u'Yrsel#, huvudv\xe4rk#,  somnolens#'],
             ['Cardiac', u'Hj\xe4rtinfarkt#'],
             ['Vascular', u'Vasodilation#'],
             ['Respiratory',
              u'Bronkit#, hosta#, faryngit#, rinit#,  \xf6vre luftv\xe4gsinfektion'],
             ['GI', u'Buksm\xe4rta#, diarr\xe9#,  dyspepsi#, illam\xe5ende#, kr\xe4kningar#'],
             ['Musculoskeletal', u'Ryggsm\xe4rta#, myalgi#  hyperurikemi#, gikt#'],
             ['General', u'Asteni#, br\xf6stsm\xe4rta#,  tr\xf6tthet#'],
             ['Investigations',
              u'F\xf6rh\xf6jt serumkreatinin#,  f\xf6rh\xf6jt blodureakv\xe4ve#*']]],
           ['Uncommon',
            [['Psychiatric', u'F\xf6rvirring#, depression#, nervositet#'],
             ['Nervous system', u'Parestesi#,  \xd6verg\xe5ende ischemisk attack#'],
             ['Nervous system', u'Amblyopi#'],
             ['Ear', u'Tinnitus#, vertigo#'],
             ['Cardiac', u'Angina pectoris##,  takykardi#, palpitationer#'],
             ['Vascular', u'Hypotoni#, syncope#'],
             ['Respiratory', u'Dyspn\xe9#, sinusit'],
             ['GI', u'Flatulens#, muntorrhet eller  torrt svalg#, smakf\xf6r\xe4ndringar#'],
             ['Skin',
              u'Alopeci#, ljusk\xe4nslighet#  pruritus#, utslag#, angio\xf6dem##, \xf6kad transpiration##'],
             ['Musculoskeletal', u'Artralgi#'],
             ['Renal', u'Njurdysfunktion#, proteinuri  urinv\xe4gsinfektion'],
             ['Reproductive system', u'Impotens#'],
             ['General', u'Feber#, generaliserat \xf6dem##,  perifert \xf6dem#'],
             ['Infections', u'Virusinfektion'],
             ['Endocrine',
              u'Insulinbehovet hos diabetespatienter  kan f\xf6r\xe4ndras av tiazider och latent diabetes mellitus kan f\xf6rekomma#']]],
           ['Rare',
            [['Nervous system', u'Balansst\xf6rningar'],
             ['Respiratory', u'Eosinofil pneumonit##  angionekrotiskt \xf6dem#'],
             ['GI', u'F\xf6rstoppning, glossit'],
             ['Skin',
              u'Hudf\xf6r\xe4ndringar kan f\xf6rekomma  tillsammans med feber, muskel- och ledsm\xe4rta (myalgi, artralgi, artrit), k\xe4rlinflammation (vaskulit), psoriasis- liknande hudf\xf6r\xe4ndringar#']]],
           ['Very rare',
            [['Nervous system', u'Dimsyn#'],
             ['GI', u'Ileus#, intestinalt angio\xf6dem'],
             ['Skin', u'Urtikaria#']]],
           ['Unknown',
            [['Blood', u'Agranulocytos##,  hemolytisk anemi#, neutropeni##, trombocytopeni#'],
             ['Immune system', u'Anafylaktoid reaktion#'],
             ['Nervous system', u'Hj\xe4rnbl\xf6dning#'],
             ['Cardiac', u'Arytmi'],
             ['Vascular', u'Postural hypotoni#'],
             ['Respiratory', u'Bronkospasm#'],
             ['GI', u'Pankreatit#'],
             ['Hepato', u'Hepatit#, kolestatisk gulsot#'],
             ['Skin',
              u'Toxisk epidermal nekrolys#  erythema multiforme#, exfoliativ dermatit#, pemfigus#, purpura, Stevens-Johnsons syndrom#, inflammation i serr\xf6s v\xe4vnad och vissa f\xf6r\xe4ndringar i laboratoriev\xe4rden (eosinofili# och/eller f\xf6rh\xf6jda ANA-titrer#, f\xf6rh\xf6jt ESR)'],
             ['Renal', u'Interstitiell nefrit'],
             ['Investigations',
              u'F\xf6rh\xf6jda kolesterol-# och  triglyceridv\xe4rden# Minskade v\xe4rden av hematokriter# och vita blodkroppar# samt f\xf6rh\xf6jda leverenzymer och serumbilirubin. Hos patienter med en medf\xf6dd G-6- PDH-brist har enstaka fall av hemolytisk anemi# rapporterats.']]]],
 '_pages': [8, 10],
 u'_rank': 43,
 u'_type': u'TSFU'}