{'_data': [['Very common',
            [['Cardiac', u'Mycket'],
             ['Vascular', u'Mycket'],
             ['GI', u'Mycket'],
             ['Skin', u'Mycket']]],
           ['Common',
            [['Psychiatric',
              u'Nervositet, s\xf6mnl\xf6shet, tr\xf6tthet, d\xe5sighet, nedst\xe4mdhet.'],
             ['Nervous system',
              u'Yrsel, balansst\xf6rningar, s\xf6mnst\xf6rningar, s\xf6mnighet.'],
             ['Vascular', u'Hypotoni.'],
             ['Respiratory', u'Hosta.'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, diarr\xe9.'],
             ['Skin', u'Exantem. Mindre'],
             ['Skin',
              u'Pruritus, urtikaria, pemfigus, exfoliativ dermatit, diafores, alopeci, ljusk\xe4nslighet.'],
             ['General', u'Huvudv\xe4rk, tr\xf6tthet, br\xf6stsm\xe4rtor.']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni'],
             ['Nervous system', u'Parestesier.'],
             ['Cardiac', u'Palpitationer, angina pectoris, takykardi, vasodilatation.'],
             ['GI',
              u'Dyspepsi, buksm\xe4rtor, anorexi, muntorrhet, flatulens, matsm\xe4ltningsbesv\xe4r.'],
             ['General', u'Asteni.']]],
           ['Rare',
            [['Psychiatric', u'Depression, f\xf6rvirring.'],
             ['Nervous system', u'Neuropati.'],
             ['Eye', u'Amblyopi, synst\xf6rning.'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac', u'Arytmier.'],
             ['Vascular',
              u'Hj\xe4rtinfarkt eller cerebrovaskul\xe4ra h\xe4ndelser, m\xf6jligen sekund\xe4rt till uttalad hypotoni hos h\xf6griskpatienter, syncope, Raynauds fenomen.'],
             ['Respiratory', u'Bronkospasm, f\xf6rv\xe4rrad astma, rinit.'],
             ['GI', u'Smakf\xf6r\xe4ndring, f\xf6rstoppning.'],
             ['GI', u'Ileus.'],
             ['Hepato', u'Pankreatit, leverp\xe5verkan.'],
             ['Skin',
              u'Erythema multiforme, psoriasis, onykolys. Vid allvarliga hudreaktioner skall behandlingen avbrytas omedelbart och \xf6vervakning av l\xe4kare \xe4r obligatorisk. Muskuloskeletala systemet, bindv\xe4v och benv\xe4vnad'],
             ['Skin', u'Myalgi, artralgi. Njur- och urinv\xe4gar'],
             ['Skin', u'Nedsatt njurfunktion, hyperkalemi.'],
             ['General',
              u'Angio\xf6dem (med svullnad av ansikte, l\xe4ppar, tunga, svalg). Risken f\xf6r angioneurotiskt \xf6dem \xe4r f\xf6rh\xf6jd hos svarta patienter. Agranulocytos har rapporterats i s\xe4llsynta fall, liksom \xe4ven ett syndrom inkluderande feber, serosit, vaskulit, myalgi, artralgi/artrit, positiv ANA, SR-stegring, eosinofili och leukocytos. F\xf6r andra ACE-h\xe4mmare har \xe4ven gynekomasti och vaskulit rapporterats och det kan inte uteslutas att dessa biverkningar \xe4r gruppspecifika. Laboratoriev\xe4rden: \xd6verg\xe5ende f\xf6rh\xf6jda serumkreatinin- och ureav\xe4rden har iakttagits, speciellt vid samtidig diuretikaterapi. L\xe4tt s\xe4nkta v\xe4rden av hemoglobin och hematokrit har rapporterats f\xf6r andra ACE-h\xe4mmare. Det kan inte uteslutas att dessa observationer \xe4r gruppspecifika.']]]],
 '_pages': [8, 9],
 u'_rank': 31,
 u'_type': u'LSFU'}