{'_data': [[u'Unknown',
            [['Infections',
              u'Candida,   Pseudomembran\xf6s   vaginalinfektion   kolit (se avsnitt 4.4),'],
             ['Blood', u'Leukopeni,   Agranulocytos,   neutropeni,   trombocytopeni'],
             ['Immune system', u'Hypersensitivitet   Anafylaktisk reaktion'],
             ['Metabolism', u'Anorexi, minskad   Hypoglykemi (se   aptit   avsnitt 4.4)'],
             ['Psychiatric', u'Insomni   Oro   Psykos, f\xf6rvirring,'],
             ['Nervous system',
              u'Smakf\xf6r\xe4ndring,   Yrsel, somnolens,   Kramper, ageusi,   huvudv\xe4rk,   tremor   parosmi, anosmi,'],
             ['Ear', u'Vertigo, nedsatt   H\xf6rself\xf6rlust   h\xf6rsel, tinnitus'],
<<<<<<< HEAD
             ['Cardiac', u'EKG   Torsade de pointes (se'],
=======
             ['Cardiac', u'EKG QT-   Torsade de pointes (se'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Vascular', u'Hemorragi   (se avsnitt'],
             ['GI', u'Diarr\xe9, kr\xe4kningar,   gastrit, stomatit,   Akut pankreatit,'],
             ['Hepato', u'Onormala   Kolestas, hepatit,   Leversvikt, gulsot (se'],
             ['Skin',
              u'Hudutslag,   Kl\xe5da, urtikaria   Stevens-Johnsons   hyperhidros   syndrom, toxisk'],
             ['Musculoskeletal', u'Muskelspasm,   Rabdomyolys,   myopati'],
             ['Renal', u'Njursvikt, interstitiell'],
             ['General', u'Sjukdomsk\xe4nsla,'],
             ['Investigations', u'\xf6kning av   \xd6kning i INR,']]]],
 '_pages': [9, 12],
 u'_rank': 16,
 u'_type': u'LFSU'}