{'_data': [['Common',
<<<<<<< HEAD
            [['Blood', u'Minskad libido och potens, galaktorr\xe9, gynekomasti'],
             ['Blood',
              u'Oro, \xf6kad \xe5ngest, agitation, aggressivitet, delirium, konfusion, desorientering, hallucinationer (ofta hos \xe4ldre med Parkinsons sjukdom), s\xf6mnst\xf6rningar, mani, hypomani, depersonalisering, insomnia, mardr\xf6mmar, f\xf6rv\xe4rrad depression, f\xf6rs\xe4mrat minne, nedsatt koncentrationsf\xf6rm\xe5ga'],
             ['Nervous system',
              u'Tremor, yrsel, huvudv\xe4rk, talsv\xe5righeter, parestesier, muskelsvaghet, myoklonier, muskul\xe4r hypertoni'],
             ['Nervous system', u'Ackommodationssv\xe5righeter, otydlig syn, pupillvidgning'],
             ['Ear', u'Tinnitus Hj\xe4rtat \xa0och \xa0blodk\xe4rl'],
             ['Ear',
              u'Postural hypotension, sinustakykardi, palpitationer, EKG-f\xf6r\xe4ndringar utan klinisk symptomatik (T-v\xe5g, ST-segment), blodvallningar'],
             ['Ear',
              u'Illam\xe5ende, kr\xe4kning, muntorrhet, obstipation, diarr\xe9, smakf\xf6r\xe4ndringar'],
             ['Ear', u'Transaminasstegringar'],
             ['Ear', u'Exantem, urtikaria, fotosensibilitet'],
=======
            [['Endocrine', u'Minskad libido och potens, galaktorr\xe9, gynekomasti'],
             ['Psychiatric',
              u'Oro, \xf6kad \xe5ngest, agitation, aggressivitet, delirium, konfusion, desorientering, hallucinationer (ofta hos \xe4ldre med Parkinsons sjukdom), s\xf6mnst\xf6rningar, mani, hypomani, depersonalisering, insomnia, mardr\xf6mmar, f\xf6rv\xe4rrad depression, f\xf6rs\xe4mrat minne, nedsatt koncentrationsf\xf6rm\xe5ga'],
             ['Psychiatric',
              u'Tremor, yrsel, huvudv\xe4rk, talsv\xe5righeter, parestesier, muskelsvaghet, myoklonier, muskul\xe4r hypertoni'],
             ['Eye', u'Ackommodationssv\xe5righeter, otydlig syn, pupillvidgning'],
             ['Ear', u'Tinnitus Hj\xe4rtat \xa0och \xa0blodk\xe4rl'],
             ['Ear',
              u'Postural hypotension, sinustakykardi, palpitationer, EKG-f\xf6r\xe4ndringar utan klinisk symptomatik (T-v\xe5g, ST-segment), blodvallningar'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, muntorrhet, obstipation, diarr\xe9, smakf\xf6r\xe4ndringar'],
             ['Hepato', u'Transaminasstegringar'],
             ['Skin', u'Exantem, urtikaria, fotosensibilitet'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Renal', u'Miktionssv\xe5righeter'],
             ['Renal',
              u'Svettningar, tr\xf6tthet, aptit\xf6kning, vikt\xf6kning, aptitl\xf6shet, g\xe4spningar']]],
           ['Uncommon',
<<<<<<< HEAD
            [['Blood', u'Aktivering av psykotiska symptom'],
             ['Nervous system', u'Krampanfall, ataxi'],
             ['Ear', u'Arytmier, \xf6kat blodtryck']]],
           ['Rare',
            [['Blood', u'Agranulocytos, leukopeni, trombocytopeni, eosinofili'],
             ['Blood', u'St\xf6rd ADH-ins\xf6ndring (SIADH)'],
             ['Nervous system', u'EEG-f\xf6r\xe4ndringar, serotonergt syndrom'],
             ['Nervous system', u'Glaukom'],
             ['Ear',
              u'Retledningsrubbningar, torsade de pointes (s\xe4rskilt hos patienter med hypokalemi) Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Ear', u'Allergisk alveolit (pneumoni) med eller utan eosinofili'],
             ['Ear', u'Mag-tarmbl\xf6dningar'],
             ['Ear', u'Hepatit med eller utan gulsot, intrahepatisk kolestas'],
             ['Ear',
              u'\xd6dem (lokala eller generella), miss-f\xe4rgning av hud eller tunga, h\xe5ravfall, purpura, hud- eller slemhinnebl\xf6dningar, ekkymos. L\xe4kemedelsveket 2010-07-02'],
             ['Renal', u'Urinretention Reproduktionsorgan och br\xf6stk\xf6rtel'],
             ['Renal', u'Vaginalbl\xf6dning'],
             ['Renal',
              u'Anafylaktiska/anafylaktoida reaktioner med hypotension, h\xf6g feber En initial \xf6kning av \xe5ngest kan erfaras av patienter med \xe5ngesttillst\xe5nd. Dessa symptom f\xf6rsvinner inom 1-2 veckor. \xc4ldre patienter \xe4r speciellt k\xe4nsliga f\xf6r antikolinerga effekter och f\xf6r neurologiska, psykiska och kardiovaskul\xe4ra reaktioner. F\xf6rekomsten av kramper tycks vara dosrelaterad. I h\xe4ndelse av allvarliga biverkningar, t ex av neurologisk eller psykiatrisk art eller allergiska hudreaktioner skall behandling med Klomipramin Mylan uts\xe4ttas. Fall av suicidtankar och suicidalt beteende har rapporterats under behandling med klomipramin eller direkt efter avslutad behandling (se avsnitt 4.4).']]],
           ['Unknown',
            [['Blood', u'Suicidalt beteende, suicidtankar L\xe4kemedelsveket 2010-07-02']]]],
 '_pages': [7, 9],
=======
            [['Psychiatric', u'Aktivering av psykotiska symptom'],
             ['Psychiatric', u'Krampanfall, ataxi'],
             ['Ear', u'Arytmier, \xf6kat blodtryck']]],
           ['Rare',
            [['Blood', u'Agranulocytos, leukopeni, trombocytopeni, eosinofili'],
             ['Endocrine', u'St\xf6rd ADH-ins\xf6ndring (SIADH) L\xe4kemedelsveket 2010-07-02'],
             ['Psychiatric', u'EEG-f\xf6r\xe4ndringar, serotonergt syndrom'],
             ['Eye', u'Glaukom'],
             ['Ear',
              u'Retledningsrubbningar, torsade de pointes (s\xe4rskilt hos patienter med hypokalemi) Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Ear', u'Allergisk alveolit (pneumoni) med eller utan eosinofili'],
             ['GI', u'Mag-tarmbl\xf6dningar L\xe4kemedelsveket 2010-07-02'],
             ['Hepato', u'Hepatit med eller utan gulsot, intrahepatisk kolestas'],
             ['Skin',
              u'\xd6dem (lokala eller generella), miss- f\xe4rgning av hud eller tunga, h\xe5ravfall, purpura, hud- eller slemhinnebl\xf6dningar, ekkymos.'],
             ['Renal', u'Urinretention Reproduktionsorgan och br\xf6stk\xf6rtel'],
             ['Renal',
              u'Vaginalbl\xf6dning Allm\xe4nna symtom och/eller symtom vid administrationsst\xe4llet'],
             ['Renal',
              u'Anafylaktiska/anafylaktoida reaktioner med hypotension, h\xf6g feber En initial \xf6kning av \xe5ngest kan erfaras av patienter med \xe5ngesttillst\xe5nd. Dessa symptom f\xf6rsvinner inom 1-2 veckor. \xc4ldre patienter \xe4r speciellt k\xe4nsliga f\xf6r antikolinerga effekter och f\xf6r neurologiska, psykiska och kardiovaskul\xe4ra reaktioner. F\xf6rekomsten av kramper tycks vara dosrelaterad. I h\xe4ndelse av allvarliga biverkningar, t ex av neurologisk eller psykiatrisk art eller allergiska hudreaktioner skall behandling med Klomipramin Mylan uts\xe4ttas. Fall av suicidtankar och suicidalt beteende har rapporterats under behandling med klomipramin eller direkt efter avslutad behandling (se avsnitt 4.4).']]],
           ['Unknown',
            [['Psychiatric', u'Suicidalt beteende, suicidtankar Centrala och perifera']]]],
 '_pages': [7, 10],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_rank': 27,
 u'_type': u'LSFU'}