{'_data': [['Very common', [['GI', u'Gastrointestinala symtom  ']]],
           ['Common',
            [['GI', u'Illam\xe5ende  '],
             ['Skin',
              u') och erektil dysfunktion (mindre vanliga). Som till\xe4ggsbehandling till metformin och en sulfonureid: yrsel (vanlig), tr\xf6tthet (vanlig) och flatulens (vanlig). Hypoglykemi Biverkningarna vid hypoglykemi baserades p\xe5 alla rapporter om hypoglykemi; samtidig glukosm\xe4tning beh\xf6vdes inte. Incidensen av rapporterad hypoglykemi f\xf6r saxagliptin 5 mg j\xe4mf\xf6rt med placebo givet som till\xe4ggsbehandling till metformin var 5,8 % mot 5 %. Incidensen av rapporterad hypoglykemi var 3,4 % hos behandlingsnaiva patienter som fick saxagliptin 5 mg plus metformin och 4,0 % hos patienter som fick enbart metformin. Vid anv\xe4ndning som till\xe4gg till insulin (med eller utan metformin) var den totala incidensen av rapporterad hypoglykemi 18,4 % f\xf6r saxagliptin 5 mg och 19,9 % f\xf6r placebo. Vid anv\xe4ndning som till\xe4gg till behandling med metformin plus sulfonureid, var den totala incidensen rapporterad hypoglykemi 10,2 % f\xf6r saxagliptin 5 mg och 6,3 % f\xf6r placebo.'],
             ['Nervous system', u'Metallisk smak  ']]],
           ['Uncommon', [['GI', u'Pankreatit  ']]],
           ['Very rare', [['Hepato', u'Leverfunktionsst\xf6rningar, hepatit  ']]],
           ['Unknown',
            [['Infections',
              u'Urinv\xe4gsinfektion Vanliga Gastroenterit Vanliga Sinuit Vanliga Nasofaryngit Vanliga Centrala och perifera'],
             ['GI',
              u'Kr\xe4kningar Vanliga Inkluderar saxagliptin i till\xe4gg till metformin och initial kombination med metformin. Endast i den initiala kombinationsbehandlingen. Erfarenhet fr\xe5n kliniska pr\xf6vningar efter marknadsgodk\xe4nnande och spontana rapporter'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner (se Mindre vanliga avsnitt 4.3 och 4.4) Anafylaktiska reaktioner inklusive S\xe4llsynta anafylaktisk chock (se avsnitt 4.3 och 4.4)'],
             ['Skin',
              u'Frekvensuppskattningarna baseras p\xe5 den poolade analysen av kliniska pr\xf6vningar med saxagliptin som monoterapi, till\xe4gg till metformin och initial kombination med metformin, till\xe4gg till sulfonureid och till\xe4gg till tiazolidindion. 2 Dessa reaktioner identifierades ocks\xe5 i kliniska pr\xf6vningar f\xf6re godk\xe4nnandet, men uppfyllde inte kriterierna f\xf6r tabell 1. Beskrivning av utvalda biverkningar Biverkningar som enligt pr\xf6varen m\xf6jligen var l\xe4kemedelsrelaterade och som rapporterades hos minst tv\xe5 fler patienter som behandlats med 5 mg saxagliptin j\xe4mf\xf6rt med kontroll beskrivs nedan per behandlingsregim. Som monoterapi: yrsel (vanliga) och tr\xf6tthet (vanliga). Som till\xe4gg till metformin: dyspepsi (vanliga) och myalgi (vanliga). 8 Som initial kombination med metformin: gastrit (vanliga), artralgi (mindre vanliga), myalgi (mindre'],
             ['Investigations',
              u'I kliniska studier har incidensen av biverkningar i laboratorietester genomg\xe5ende varit likartad hos patienter som behandlats med 5 mg saxagliptin j\xe4mf\xf6rt med patienter som behandlats med placebo. En liten minskning i absolut antal lymfocyter observerades. Fr\xe5n en utg\xe5ngsniv\xe5 av absolut antal lymfocyter p\xe5 i genomsnitt ungef\xe4r 2 200 celler/\xb5l, observerades en minskning med ungef\xe4r 100 celler/\xb5l j\xe4mf\xf6rt med placebo i den placebokontrollerade poolade analysen. Det genomsnittliga absoluta antalet lymfocyter var stabilt vid daglig dosering i upp till 102 veckor. Minskningen av lymfocytantalet var inte f\xf6rknippad med kliniskt relevanta biverkningar. Den kliniska signifikansen f\xf6r denna minskning av lymfocytantalet j\xe4mf\xf6rt med placebo \xe4r inte k\xe4nd. Metformin Kliniska pr\xf6vningsdata och data efter godk\xe4nnandet'],
             ['Metabolism', u'Vitamin B -brist Mycket s\xe4llsynta'],
             ['Skin',
              u'2 Gastrointestinala symtom s\xe5som illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rtor och nedsatt aptit f\xf6rekommer oftast n\xe4r behandling p\xe5b\xf6rjas och upph\xf6r i de flesta fall spontant.']]]],
 '_pages': [6, 8],
 u'_rank': 13,
 u'_type': u'LSFU'}