{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk.'],
             ['Nervous system', u's\xf6mnighet, ataxi, yrsel, huvudv\xe4rk.'],
             ['Eye', u'dubbelseende, dimsyn.'],
             ['GI', u'illam\xe5ende, kr\xe4kning.'],
             ['Skin',
              u'hudutslag. Allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs)'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Skin',
              u'hudutslag. Allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs)']]],
           ['Common',
            [['Psychiatric', u'aggressivitet, irritabilitet.'],
             ['Nervous system', u's\xf6mnighet, yrsel, tremor, s\xf6mnl\xf6shet.'],
             ['Nervous system', u'nystagmus, tremor, s\xf6mnl\xf6shet.'],
             ['GI', u'illam\xe5ende, kr\xe4kning, diarr\xe9. Under annan klinisk erfarenhet'],
             ['GI', u'diarr\xe9.'],
             ['General',
              u'tr\xf6tthet. Bipol\xe4r sjukdom Nedanst\xe5ende biverkningar b\xf6r beaktas tillsammans med biverkningarna f\xf6r epilepsi f\xf6r en total s\xe4kerhetsprofil f\xf6r lamotrigin.'],
             ['Nervous system', u'agitation, s\xf6mnighet, yrsel.'],
             ['GI', u'torr mun'],
             ['Musculoskeletal', u'artralgi.'],
             ['General', u'v\xe4rk, ryggv\xe4rk.']]],
           ['Uncommon',
            [['Nervous system', u'ataxi.'],
             ['Eye', u'dubbelseende, dimsyn. Under annan klinisk erfarenhet']]],
           ['Rare',
            [['Nervous system', u'nystagmus. Under annan klinisk erfarenhet'],
             ['Eye', u'konjunktivit.'],
             ['Skin', u'Stevens-Johnson syndrome (SJS)'],
             ['Skin', u'Stevens-Johnson syndrome (SJS)']]],
           ['Very rare',
            [['Blood',
              u'hematologiska avvikelser s\xe5som neutropeni, leukopeni, anemi, trombocytopeni, pancytopeni, aplastisk anemi, agranulocytos'],
             ['Immune system',
              u'\xf6verk\xe4nslighetssyndrom** (inkluderande symtom som feber, lymfadenopati, ansikts\xf6dem, blod- och leverabnormiteter, disseminerad intravasal koagulation, multipel organsvikt). **Hudutslag har \xe4ven rapporterats som delsymtom i ett \xf6verk\xe4nslighetssyndrom med ett varierande m\xf6nster av systemiska symtom med bland annat feber, lymfadenopati, ansikts\xf6dem samt blod- och leverabnormiteter. Syndromet uppvisar mycket varierande klinisk sv\xe5righetsgrad och kan i s\xe4llsynta fall leda till disseminerad intravasal koagulation och multiorgansvikt. Det \xe4r viktigt att notera att tidiga tecken p\xe5 \xf6verk\xe4nslighet (t.ex. feber, lymfadenopati) kan upptr\xe4da utan tecken p\xe5 samtidiga hudreaktioner. Om patienten uppvisar s\xe5dana statusfynd och symtom ska patienten omedelbart utv\xe4rderas och Lamotrigin 1A Farma uts\xe4ttas om inte en annan orsak kan fastst\xe4llas.'],
             ['Psychiatric', u'konfusion, hallucinationer, tics.'],
             ['Nervous system',
              u'agitation, ostadighet, motorikst\xf6rningar, f\xf6rs\xe4mring av Parkinsons sjukdom, extrapyramidala'],
             ['Hepato',
              u'leversvikt, leverdysfunktion, f\xf6rh\xf6jda leverfunktionsv\xe4rden. Leverdysfunktion upptr\xe4der vanligtvis i samband med \xf6verk\xe4nslighetsreaktioner men enstaka fall har rapporterats utan tydliga tecken p\xe5 \xf6verk\xe4nslighet.'],
             ['Skin',
              u'toxisk epidermal nekrolys (TEN) I dubbelblindade kliniska studier d\xe4r lamotrigin gavs som till\xe4ggsmedicinering f\xf6rekom hudutslag hos upp till 10 % av patienterna som fick lamotrigin och hos 5 % av patienterna som fick placebo. Hudutslagen ledde till att lamotrigin sattes ut hos 2 % av patienterna. Utslagen \xe4r vanligtvis makulopapul\xe4ra, upptr\xe4der i allm\xe4nhet inom \xe5tta veckor fr\xe5n behandlingsstart och f\xf6rsvinner vid uts\xe4ttning av Lamotrigin 1A Farma (se avsnitt 4.4). Allvarliga och potentiellt livshotande hudutslag har rapporterats, inkluderande Stevens-Johnsons syndrom (SJS) och toxisk epidermal nekrolys (TEN). Fast\xe4n majoriteten av patienterna \xe5terh\xe4mtar sig d\xe5 lamotriginbehandlingen s\xe4tts ut har vissa patienter f\xe5tt irreversibel \xe4rrbildning och s\xe4llsynta associerade d\xf6dsfall har f\xf6rekommit (se avsnitt 4.4). Risken f\xf6r hudutslag f\xf6refaller generellt vara starkt kopplad till: h\xf6ga initialdoser av lamotrigin och \xf6verskridande av den rekommenderade dosupptrappningen av lamotriginbehandlingen (se avsnitt 4.2) samtidig anv\xe4ndning av valproat (se avsnitt 4.2). Hudutslag har \xe4ven rapporterats som del av ett \xf6verk\xe4nslighetssyndrom som s\xe4tts i samband med ett varierande m\xf6nster av systemiska symtom (se Immunsystemet**).'],
             ['Musculoskeletal', u'lupusliknande reaktioner.'],
             ['Skin',
              u'toxisk epidermal nekrolys (TEN) har rapporterats (se 4.4). Vid sammanst\xe4llning av alla studier med bipol\xe4r sjukdom (kontrollerade och okontrollerade) som utf\xf6rts med lamotrigin har hudutslag rapporterats hos 12 % av de patienter som behandlats med lamotrigin. I de kontrollerade kliniska studierna med bipol\xe4r sjukdom rapporterades hudutslag d\xe4remot hos 8 % av patienterna som fick lamotrigin respektive 6 % av de patienter som fick placebo.']]],
           ['Unknown',
            [['Blood',
              u'lymfadenopati Hematologiska avvikelser och lymfadenopati \xe4r m\xf6jligen kopplade till \xf6verk\xe4nslighetssyndromet (se Immunsystemet**).'],
             ['Nervous system',
              u'aseptisk meningit (se avsnitt 4.4). Det finns rapporter om att lamotrigin kan f\xf6rv\xe4rra Parkinson-symtom hos patienter med Parkinsons sjukdom samt enstaka rapporter om extrapyramidala biverkningar och koreoatetos hos patienter utan denna bakomliggande sjukdom.']]]],
 '_pages': [19, 22],
 u'_rank': 33,
 u'_type': u'LSFU'}