{'_data': [['Common',
            [['GI',
              u'Illam\xe5ende och kr\xe4kningar vid postoperativ anv\xe4ndning, s\xe4rskilt om opiater ocks\xe5 har anv\xe4nts. I samband med upph\xe4vandet av bensodiazepinp\xe5verkan vid terapeutisk dosering, t ex vid anestesi, har ca 10% av patienterna f\xe5tt illam\xe5ende och kr\xe4kningar.']]],
           ['Uncommon',
            [['Psychiatric',
              u'\xc5ngest, oro och r\xe4dsla efter snabb injektion, kr\xe4ver i allm\xe4nhet inte behandling.'],
             ['Cardiac',
              u'Palpitationer efter snabb injektion, kr\xe4ver i allm\xe4nhet inte behandling.']]],
           ['Unknown',
            [['Psychiatric',
              u'Abstinenssymtom (t ex agitation, \xe5ngest, emotionell labilitet, f\xf6rvirring, k\xe4nslost\xf6rningar) efter snabb injektion av doser p\xe5 1 mg eller hos patienter med h\xf6g dos och/eller l\xe5ngtidsbehandling med bensodiazepiner som avslutats veckorna innan de fick injektion med flumazenil (se avsnitt 4.4). Panikattacker (hos patienter med panikreaktioner i anamnesen), ih\xe5llande gr\xe5t, agitation och aggressiva reaktioner. Biverkningsprofilen hos barn liknar i allm\xe4nhet den hos vuxna. N\xe4r flumazenil har anv\xe4nts f\xf6r h\xe4vande av sedering har ih\xe5llande gr\xe5t, agitation och aggressiva reaktioner rapporterats. Det kan ibland vara sv\xe5rt att skilja p\xe5 l\xe4kemedelsbiverkningar och m\xf6jliga abstinenssymtom av bensodiazepiner i form av \xe5ngest, r\xe4dsla eller f\xf6rvirring.'],
             ['Nervous system',
              u'Kramper har rapporterats hos patienter som har epilepsi eller allvarligt nedsatt leverfunktion, s\xe4rskilt efter l\xe5ngtidsbehandling med bensodiazepiner eller vid blandf\xf6rgiftningar (se avsnitt 4.4).'],
             ['Vascular', u'\xd6verg\xe5ende h\xf6gt blodtryck (vid uppvaknande).'],
             ['Skin', u'Urtikaria, hudrodnad.'],
             ['General',
              u'Frossa efter snabb injektion, kr\xe4ver i allm\xe4nhet inte behandling.']]]],
 '_pages': [4, 5],
 u'_rank': 8,
 u'_type': u'LSFU'}