{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI',
              u'Illam\xe5ende, diarr\xe9, magsm\xe4rtor, f\xf6rstoppning, kr\xe4kningar, flatulens, torr mun eller hals'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymniv\xe5 er'],
             ['Skin', u'Urticaria, kl\xe5da, hudutslag'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni , eosinofili, leukopeni'],
             ['Psychiatric', u'Depression'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, fraktur p\xe5 h\xf6ft, handled eller ryggrad (se avsnitt varningar och f\xf6rsiktighet)'],
             ['General', u'\xd6dem']]],
           ['Rare',
            [['Blood', u'Anemi'],
             ['Psychiatric', u'Somnolens, hallucinationer, f\xf6rvirring'],
             ['Nervous system', u'Rastl\xf6shet, svindel, parestesi, s\xf6mnighet, tremor'],
             ['Eye', u'Synst\xf6rningar'],
             ['GI', u'Glossit, candidiasis i esofagus, pankreatit, smakst\xf6rningar'],
             ['Hepato', u'Hepatit, ikterus'],
             ['Skin',
              u'Petekier, purpura, h\xe5ravfall, erythema multiforme, ljusk\xe4nslighet'],
             ['Renal', u'Interstitiell nefrit'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'Feber, hyperhidros, angio\xf6dem, anorexi, impotens']]],
           ['Very rare',
            [['Blood', u'Agranul ocytos, pancyto peni'],
             ['GI', u'Kolit, stomatit'],
             ['Skin', u'Stevens-Johns ons syndrom, toxisk epidermal nekrolys'],
             ['General', u'Anafylaktisk chock'],
             ['Investigations',
              u'F\xf6rh\xf6jda kolesterol-och triglyceridniv\xe5 er, hyponatremi']]],
           ['Unknown',
            [['Metabolism', u'Hypomagnes emi (se varningar och f\xf6rsiktighet, 4.4)']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 8],
 u'_rank': 25,
 u'_type': u'MSFU'}