{'_data': [['Very common',
            [['Metabolism',
              u' Elektrolytst\xf6rningar (inklusive symtomatiska), dehydrering och hypovolemi, s\xe4rskilt hos \xe4ldre patienter, \xf6kat blodkreatinin, \xf6kade blodtriglycerider.']]],
           ['Common',
            [['Blood', u' Hemokoncentration'],
             ['Metabolism',
              u' Hyponatremi, hypokloremi, hypokalemi, \xf6kat blodkolesterol, hyperurikemi.'],
             ['Nervous system',
              u' Leverencefalopati hos patienter med hepatocellul\xe4r insufficiens.']]],
           ['Uncommon',
            [['Blood', u' Trombocytopeni.'],
             ['Metabolism',
              u' F\xf6rs\xe4mrad glukostolerans. Latent diabetes mellitus kan bli manifest.'],
             ['Ear',
              u' Vanligen reversibel h\xf6rselneds\xe4ttning (vid h\xf6ga plasmakoncentrationer), s\xe4rskilt hos patienter med njursvikt eller hypoproteinemi (t ex vid nefrotiskt syndrom)'],
             ['GI', u' Illam\xe5ende'],
             ['Skin',
              u' Hudreaktioner t ex kl\xe5da, urtikaria, andra utslag eller bl\xe5sor, bull\xf6s dermatit, erythema multiforme, pemfigoid, exfoliativ dermatit, purpura, fotosensitivitet.']]],
           ['Rare',
            [['Blood', u'Leukopeni, eosinofili.'],
             ['Immune system',
              u' Allvarliga anafylaktiska eller anafylaktoida reaktioner (ex. chock).'],
             ['Nervous system', u' Parestesi.'],
             ['Ear', u'Tinnitus.'],
             ['Vascular', u' Vaskulit.'],
             ['GI', u'Kr\xe4kningar, diarr\xe9.'],
             ['General', u'Tubulointerstitiell nefrit.'],
             ['General', u' Feber.   ']]],
           ['Very rare',
            [['Blood', u'Agranulocytos, aplastisk anemi eller haemolytisk anemi.'],
             ['GI', u'Akut pankreatit'],
             ['Hepato', u' Kolestas, transaminasstegring.']]],
           ['Unknown',
            [['Metabolism',
              u'Hypokalcemi, hypomagnesemi, \xf6kad blodurea, metabolisk alkalos och giktattacker.'],
             ['Vascular', u'Trombos.'],
             ['Skin', u'Stevens-Johnsons syndrom, toxisk epidermal'],
             ['General', u'\xd6kat urinnatrium, \xf6kat urinklorid, urinretention']]]],
 '_pages': [4, 5],
 u'_rank': 24,
 u'_type': u'LSFU2'}