{'_data': [['Very common',
            [['Eye',
              u'\xd6kad irispigmentering. Lindrig till m\xe5ttlig konjunktival hyperemi, \xf6gonirritation (br\xe4nnande k\xe4nsla, grusighet, kl\xe5da, sveda och k\xe4nsla av fr\xe4mmande f\xf6rem\xe5l i \xf6gat). F\xf6r\xe4ndrade \xf6gonfransar och vellush\xe5r (\xf6kad l\xe4ngd, tjocklek, pigmentering och \xf6kat antal) (de allra flesta rapporter g\xe4ller japansk population).']]],
           ['Common',
            [['Eye',
              u'\xd6verg\xe5ende punktformiga epitelerosioner, vanligen utan symtom. Blefarit. \xd6gonsm\xe4rta.']]],
           ['Uncommon',
            [['Eye', u'\xd6gonlocks\xf6dem. Torra \xf6gon. Keratit. Dimsyn. Konjunktivit.'],
             ['Skin', u'Hudutslag.']]],
           ['Rare',
            [['Eye',
              u'Irit/uveit (de flesta rapporter hos patienter med samtidiga predisponerande faktorer). Makula\xf6dem. Symtomatiskt kornea\xf6dem och erosioner. Periorbitalt \xf6dem. Felriktade \xf6gonfransar som ibland orsakar \xf6gonirritation. En extra rad cilier vid mynningen av Meiboms k\xf6rtlar (distichiasis).'],
             ['Respiratory', u'Astma. F\xf6rv\xe4rrad astma. Dyspn\xe9.'],
             ['Skin',
              u'Lokal hudreaktion p\xe5 \xf6gonlocken. M\xf6rkf\xe4rgning av \xf6gonlockshuden']]],
           ['Very rare',
            [['Cardiac', u'F\xf6rv\xe4rrad angina hos patienter med tidigare sjukdom'],
             ['General',
              u'Br\xf6stsm\xe4rta. Det har varit ytterligare spontana rapporter efter marknadsintroduktion enligt f\xf6ljande']]],
           ['Unknown',
            [['Nervous system', u'Huvudv\xe4rk. Yrsel.'],
             ['Cardiac', u'Hj\xe4rtklappning.'],
             ['Musculoskeletal', u'Myalgi. Artralgi']]]],
 '_pages': [4, 4],
 u'_rank': 12,
 u'_type': u'LSFU'}