{'_data': [['Very common',
            [['Eye',
              u'\xf6kad irispigmentering; mild till m\xe5ttlig konjunktival hyperemi; \xf6gonirritation (svidande grusk\xe4nsla, kl\xe5da, stickningar och k\xe4nsla av fr\xe4mmande kropp); f\xf6r\xe4ndrade \xf6gonfransar och vellush\xe5r (l\xe4ngre, t\xe4tare, mer pigmenterade och \xf6kat antal)(majoriteten av rapporterna hos japansk befolkning)']]],
           ['Common',
            [['Eye',
              u'\xf6verg\xe5ende punktformiga epiteliala erosioner, oftast utan symtom; blefarit; \xf6gonsm\xe4rta']]],
           ['Uncommon',
            [['Eye', u'\xf6gonlocks\xf6dem, \xf6gontorrhet, keratit, dimsyn, konjunktivit'],
             ['Skin', u'hudutslag']]],
           ['Rare',
            [['Eye',
              u'irit/uveit (majoriteten av rapporterna hos patienter med samtidiga predisponerande faktorer); makula\xf6dem; symtomatiskt kornealt \xf6dem och erosioner; periorbitalt \xf6dem; felriktade \xf6gonfransar som ibland resulterar i \xf6gonirritation; extra rad av cilier vid k\xf6rtelmynningarna p\xe5 \xf6gonlocken (distichiasis)'],
             ['Respiratory', u'astma, f\xf6rv\xe4rrad astma, dyspn\xe9'],
             ['Skin',
              u'lokal hudreaktion p\xe5 \xf6gonlocket, m\xf6rkf\xe4rgning av \xf6gonlocks-huden']]],
           ['Very rare',
            [['Cardiac', u'f\xf6rv\xe4rrad k\xe4rlkramp hos patienter med tidigare sjukdom'],
             ['General', u'br\xf6stsm\xe4rta']]],
           ['Unknown',
            [['Cardiac',
              u'hos patienter med tidigare sjukdom Centrala och huvudv\xe4rk, perifera yrsel'],
             ['Eye',
              u'irispigmen-teri punktformiga em, (majoriteten av ng; mild till epiteliala \xf6gontorrhet, rapporterna m\xe5ttlig erosioner, keratit, hos patienter konjunktival oftast utan dimsyn, med samtidiga hyperemi; symtom; konjunktivit predispone-ran \xf6gonirritation blefarit; de faktorer); (svidande \xf6gonsm\xe4rta makula\xf6dem; grusk\xe4nsla, symtomatiskt kl\xe5da, kornealt \xf6dem stickningar och erosioner; och k\xe4nsla av periorbitalt fr\xe4mmande \xf6dem; kropp); felriktade f\xf6r\xe4ndrade \xf6gonfransar \xf6gonfransar som ibland och vellush\xe5r resulterar i (l\xe4ngre, t\xe4tare, \xf6gonirritation; mer extra rad av pigmenterade cilier vid och \xf6kat antal) k\xf6rtelmyn-nin (majoriteten av garna p\xe5 rapporterna \xf6gonlocken hos japansk (distichiasis) befolkning) Andnings-v\xe4g astma, ar, br\xf6stkorg f\xf6rv\xe4rrad och astma, dyspn\xe9 mediastinum Hud och hudutslag lokal subkutan hudreaktion p\xe5 v\xe4vnad \xf6gonlocket, m\xf6rkf\xe4rgning av \xf6gonlocks-hud en Muskuloske-l myalgi, etala artralgi systemet och bindv\xe4v Allm\xe4nna br\xf6stsm\xe4rta symtom och/eller symtom vid administre-ri ngsst\xe4llet'],
             ['Eye', u'cysta i iris'],
             ['Nervous system', u'huvudv\xe4rk, yrsel Infektioner'],
             ['Cardiac', u'hj\xe4rtklappning'],
             ['Musculoskeletal', u'myalgi, artralgi']]]],
 '_pages': [4, 6],
 u'_rank': 15,
 u'_type': u'LSFU'}