{'_data': [['Very common',
            [['Nervous system', u'Somnolens, yrsel, huvudv\xe4rk'],
             ['Respiratory', u'Hicka'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['General',
              u'Reaktioner p\xe5 applikations-och instillationsst\xe4llet (inklusive erytem, pruritus, irritation, utslag, dermatit, vesikler, sm\xe4rta, eksem, inflammation, svullnad, missf\xe4rgning, papler, exkoriation, urtikaria, \xf6verk\xe4nslighet)']]],
           ['Common',
            [['Psychiatric',
              u'Perceptions-rubbningar (inklusive hallucinationer, syn-hallucinationer, h\xf6rsel-hallucinationer, illusion), s\xf6mnst\xf6rningar, mardr\xf6mmar, abnorma dr\xf6mmar'],
             ['Nervous system',
              u'Medvetandest\xf6rningar, ospecificerade (inklusive synkope, vasovagal synkope, medvetsl\xf6shet),dyskinesi, postural yrsel, letargi'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Ortostatisk hypotension, hypertension'],
             ['GI', u'F\xf6rstoppning, muntorrhet, dyspepsi'],
             ['Skin', u'Erytem, hyperhidros, pruritus'],
             ['General',
              u'Perifert \xf6dem, asteniska tillst\xe5nd (inklusive sjukdomsk\xe4nsla)'],
             ['Investigations', u'Viktminskning'],
             ['Injury', u'Falltendens']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'insomning, paranoia, sexuella st\xf6rningar (inklusive hypersexualitet, \xf6kad impulskontroll (inklusive patologiskt spelberoende, tv\xe5ngsbeteende), konfusion'],
             ['Eye', u'Dimsyn, synrubbningar, fotopsi'],
             ['Cardiac', u'F\xf6rmaksflimmer'],
             ['Vascular', u'Hypotension'],
             ['GI', u'Buksm\xe4rtor'],
             ['Skin', u'Generaliserad pruritus, hudirritation, kontaktdermatit'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['Investigations',
              u'\xd6kning av leverenzymer (inklusive ASAT, ALAT, GGT), vikt\xf6kning, \xf6kad hj\xe4rtfrekvens']]],
           ['Rare',
            [['Psychiatric',
              u'Psykotiska rubbningar, tv\xe5ngssyndrom, aggressivt beteende/ hets\xe4tning och tv\xe5ngsm\xe4ssigt \xe4tande'],
             ['Nervous system', u'Krampanfall'],
             ['Cardiac', u'Supraventrikul\xe4r takykardi'],
             ['Skin', u'Generaliserat hudutslag'],
             ['General', u'Irritabilitet']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 28,
 u'_type': u'MSFU'}