{'_data': [['Common',
            [['Blood', u'L\xe5ga serumfolsyrav\xe4rden'],
             ['Nervous system', u'Ataxi, nystagmus, tremor'],
             ['Eye', u'Synrubbningar'],
             ['GI', u'Gingival hyperplasi'],
             ['Skin', u'Exantem, urtikaria, hirsutism'],
             ['General', u'D\xe5sighet, yrsel'],
<<<<<<< HEAD
             ['Hepato', u'Transaminasstegrin g']]],
           ['Uncommon',
            [['Blood', u'Lymfadenopati (feber, exantem och lymfk\xf6rtelf\xf6rstoring )'],
=======
             ['Hepato', u'Transaminasstegring']]],
           ['Uncommon',
            [['Blood', u'Lymfadenopati (feber, exantem och lymfk\xf6rtelf\xf6rstoring)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Dyspepsi, illam\xe5ende och kr\xe4kningar']]],
           ['Rare',
            [['Cardiac', u'AV-block'],
             ['Blood',
              u'Agranulocytos, aplastisk anemi, leukopeni, megaloblastisk anemi, trombocytopeni'],
             ['Musculoskeletal', u'SLE'],
             ['Metabolism', u'Hyperglykemi, osteomalaci'],
             ['General', u'\xd6verk\xe4nslighetssyndrom'],
             ['Hepato', u'Hepatit'],
             ['Psychiatric', u'F\xf6rvirring']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 9],
 u'_rank': 16,
 u'_type': u'MSFU'}