{'_data': [['Very common',
            [['GI', u'Illam\xe5ende, kr\xe4kning'], ['Musculoskeletal', u'Muskelrigidtet']]],
           ['Common',
            [['Nervous system', u'Dyskinesi, sedation, yrsel'],
             ['Eye', u'Synst\xf6rning'],
             ['Cardiac', u'Bradykardi, takykardi, arytmi'],
             ['Vascular', u'Hypotoni, hypertoni, vensm\xe4rta'],
             ['Respiratory', u'Laryngospasm, bronkospasm, apn\xe9'],
             ['Skin', u'Allergisk dermatit']]],
           ['Uncommon',
            [['Psychiatric', u'Euforisk sinnest\xe4mmning'],
             ['Nervous system', u'Huvudv\xe4rk'],
<<<<<<< HEAD
             ['Vascular', u'Flebit, blodtrycks-fluktu ation'],
             ['Respiratory', u'Hyperventilering , hicka'],
=======
             ['Vascular', u'Flebit, blodtrycks-fluktuation'],
             ['Respiratory', u'Hyperventilering, hicka'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Frossa, hypotermi']]],
           ['Unknown',
            [['Immune system',
              u'Hypersensitivitet (s\xe5som anafylaktisk chock, anafylaktisk reaktion, urtikaria)'],
             ['Nervous system', u'Kramper, medvetande-f\xf6rlust, myokloni'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd'],
             ['Respiratory', u'Andnings-depression'],
             ['Skin', u'Pruritus']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 18,
 u'_type': u'MSFU'}