{'_data': [['Common',
            [['Psychiatric', u'S\xf6mnsv\xe5righeter'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende, buksm\xe4rtor, dyspepsi.'],
             ['Investigations',
              u'\xd6kning av kreatinfosfokinas i blodet, \xf6kning av transaminas i blodet. * Baserat p\xe5 erfarenhet av Lescol via spontana fallrapporter och litteraturstudier, efter marknadsf\xf6ring. Eftersom dessa reaktioner rapporterats frivilligt ur en population med ok\xe4nd storlek, \xe4r det inte m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt ber\xe4kna frekvensen, som d\xe4rf\xf6r kategoriseras som ok\xe4nd. F\xf6ljande biverkningar har rapporterats f\xf6r vissa statiner: \u2022s\xf6mnst\xf6rningar, inklusive insomningssv\xe5righeter och mardr\xf6mmar \u2022minnesf\xf6rlust \u2022nedsatt sexuell f\xf6rm\xe5ga \u2022depression \u2022interstitiell lungsjukdom har rapporterats i enstaka fall, s\xe4rskilt vid l\xe5ngtidsbehandling (se avsnitt 4.4) \u2022Diabetes Mellitus: Frekvensen \xe4r beroende av f\xf6rekomst eller avsaknad av riskfaktorer (fasteglukos > 5,6 mmol/l; BMI >30 kg/m ; f\xf6rh\xf6jda triglycerider; hypertension i anamnesen).']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighetsreaktioner (hudutslag, urtikaria)'],
             ['Musculoskeletal', u'Myalgi, muskelsvaghet, myopati.']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Nervous system',
              u'Parestesi, dysestesi och hypestesi, \xe4ven k\xe4nda f\xf6r att ha samband med de underliggande hyperlipidemisjukdomarna.'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Angio\xf6dem, ansikts\xf6dem och andra hudreaktioner (t.ex. eksem, dermatit, bull\xf6st exantem).'],
             ['Musculoskeletal', u'Rabdomyolys, lupusliknande symtom, myosit.']]],
           ['Unknown', [['Reproductive system', u'Erektil dysfunktion.']]]],
 '_pages': [6, 7],
 u'_rank': 15,
 u'_type': u'LSFU'}