{'_data': [['Very common',
            [['Skin', u'\xd6kad svettning'],
             ['Musculoskeletal', u'Artralgi'],
             ['General', u'Blodvallning, tr\xf6tthet inklusive asteni']]],
           ['Common',
            [['Metabolism', u'Anorexi, \xf6kad aptit, hyperkolesterolemi'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, dyspepsi, f\xf6rstoppning, diarr\xe9'],
             ['Skin',
              u'Alopeci, utslag inklusive erytemiskt, makulopapul\xf6st, psoriasisliknande och vesikul\xe4rt utslag'],
             ['Musculoskeletal', u'Myalgi, skelettsm\xe4rta, osteoporos, frakturer'],
             ['General', u'Sjukdomsk\xe4nsla, perifera \xf6dem'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'Urinv\xe4gsinfektion'],
             ['Neoplasms',
              u'Tum\xf6rsm\xe4rta (g\xe4ller ej vid adjuvant eller f\xf6rl\xe4ngd adjuvant behandling)'],
             ['Blood', u'Leukopeni'],
             ['Metabolism', u'Generaliserat \xf6dem'],
             ['Psychiatric', u'\xc5ngest inklusive nervositet, irritabilitet'],
             ['Nervous system',
              u'S\xf6mnighet, s\xf6mnl\xf6shet, minnesf\xf6rs\xe4mring, dysestesi inklusive parestesi, hypoestesi, smakf\xf6r\xe4ndring, cerebrovaskul\xe4r sjukdom'],
             ['Eye', u'Katarakt, irritation i \xf6gat, dimsyn'],
             ['Cardiac', u'Palpitationer, takykardi'],
             ['Vascular',
              u'Tromboflebit inklusive ytlig och djup tromboflebit, hypertoni, ischemisk hj\xe4rtsjukdom'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Buksm\xe4rta, stomatit, muntorrhet'],
             ['Hepato', u'\xd6kning av leverenzymer'],
             ['Skin', u'Kl\xe5da, torr hud, urtikaria'],
             ['Musculoskeletal', u'Artrit'],
             ['Renal', u'\xd6kad urinfrekvens'],
             ['Reproductive system',
              u'Vaginalbl\xf6dning, vaginalflytning, vaginal torrhet, br\xf6stsm\xe4rta'],
             ['General', u'Feber, torra slemhinnor, t\xf6rst'],
             ['Investigations', u'Viktf\xf6rlust']]],
           ['Rare', [['Vascular', u'Lungemboli, arteriell trombos, cerebrovaskul\xe4r infarkt']]],
           ['Unknown',
            [['Hepato', u'Hepatit'],
             ['Skin',
              u'Anafylaktisk reaktion, angio\xf6dem, toxisk epidermal nekrolys, erythema multiforme']]]],
 '_pages': [3, 5],
 u'_rank': 32,
 u'_type': u'LSFU'}