{'_data': [['Very common',
            [['Blood',
              u'Benm\xe4rgs-h\xe4mn ing, leukopeni, neutropeni, trombocytopeni, pancytopeni']]],
           ['Common',
            [['Neoplasms',
              u'Akuta sekund\xe4ra hematologiska maligniteter (framf\xf6rallt leukemi och myelodysplastisk t syndrom) s\xe4rskilt efter l\xe5ngtids-behandli ng.'],
             ['Blood', u'Anemi'],
             ['Nervous system', u'Kramper hos barn med nefrotiskt syndrom.'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9, muns\xe5r.']]],
           ['Uncommon', [['Immune system', u'Hudutslag']]],
           ['Rare',
            [['Immune system',
              u'Allergiska reaktioner (urtikaria, angioneurotiskt \xf6dem). Stevens-Johnso ns syndrom, toxisk epidermal nekrolys.'],
             ['Nervous system', u'Kramper'],
             ['Hepato', u'Levertoxicitet, ikterus.'],
             ['General', u'Feber.']]],
           ['Very rare',
            [['Blood', u'Irreversibel benm\xe4rgssvikt'],
             ['Nervous system',
              u'Motorikst\xf6rningar inkl. tremor, muskelryckningar och muskelkramper i fr\xe5nvaro av krampanfall. Perifer neuropati.'],
             ['Respiratory', u'Interstitiell pulmonell fibros , interstitiell pneumoni.'],
             ['Renal', u'Steril cystit.']]]],
 '_note': u' ANOMALI in Headers ?MSFU',
 '_pages': [3, 4],
 u'_rank': 14,
 u'_type': u'MSFU'}