{'_data': [['Very common',
            [['Vascular', u'heta vallningar med svettskov'],
             ['Reproductive system', u'f\xf6rsvagad libido och potens'],
             ['General', u'\xf6kad transpiration']]],
           ['Common', [['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndringar, depression']]],
           ['Uncommon',
            [['Endocrine', u'gynekomasti'],
             ['Metabolism',
              u'nedsatt aptit, f\xf6r\xe4ndrat metaboliskt status hos diabetiker (f\xf6rh\xf6jda eller l\xe5ga blodglukosv\xe4rden)'],
             ['Psychiatric', u'nedst\xe4mdhet eller tidigare symtom f\xf6rv\xe4rrade'],
             ['Nervous system', u'huvudv\xe4rk, yrsel'],
             ['Vascular', u'f\xf6r\xe4ndrat blodtryck (hypertoni eller hypotoni)'],
             ['Respiratory', u'andningssv\xe5righeter'],
             ['Skin', u'h\xe5ravfall'],
             ['Reproductive system', u'minskad testikelstorlek'],
             ['General', u'vikt\xf6kning'],
             ['Investigations',
              u'\xf6kad aktivitet av vissa enzymer, bl.a. laktatdehydrogenas (LDH), alkaliskt fosfatas (AFOS) eller transaminaser, t.ex. ALAT, ASAT eller GGT. I ett enskilt fall f\xf6rekom trombos i den centrala retinalart\xe4ren. Hos en patient av de 120 000 patienter som hittills har behandlats med leuprorelinacetat har hypofysdysfunktion f\xf6rekommit p.g.a. en expansiv f\xf6r\xe4ndring. Patienten stod p\xe5 l\xe5ngtidsbehandling med leuprorelinacetat (\xe0 7,5 mg depot). B\xe4gge dessa h\xe4ndelser avklingade efter adekvat behandling utan att behandlingen med 7,5 mg leuprorelinacetat depot beh\xf6vde avbrytas.']]],
           ['Rare',
            [['Vascular', u'trombos'], ['Respiratory', u'lungemboli'], ['GI', u'diarr\xe9']]],
           ['Very rare',
            [['Immune system',
              u'generaliserade allergiska reaktioner (feber, utslag, kl\xe5da, anafylaktiska reaktioner)'],
             ['Nervous system',
              u'\xf6verg\xe5ende smakst\xf6rning, hypofys\xe4r apoplexi efter initial administration av leuprorelin hos patienter med hypofysadenom*'],
             ['GI', u'illam\xe5ende/kr\xe4kning'],
             ['Musculoskeletal', u'led- och muskelbesv\xe4r'],
             ['General',
              u'svullnad, tr\xf6tthet; lokala hudreaktioner, t.ex. rodnad vid injektionsst\xe4llet; dessa har vanligen avklingat trots fortsatt behandling. \xd6vrigt']]]],
 '_pages': [4, 5],
 u'_rank': 22,
 u'_type': u'LSFU'}