{'_data': [['Very common', [['Eye', u'a:  ast e ni/tr\xf6tt h e t  ']]],
           ['Common',
            [['Eye', u':  diplopi,  dimsyn  \xd6ron  och  bala n s o r g a n  '],
             ['Eye', u':  vertigo  '],
             ['Eye', u':  \xf6kad  host a  Magt ar m k a n a l e n  '],
             ['Eye',
              u':  buks m \xe4 r t a ,  diarr\xe9,  dysp e p si,  illam\xe5 e n d e ,  kr\xe4kninga r  '],
             ['Eye', u':  utslag,  ekse m,  kl\xe5da  '],
             ['Eye', u':  myalgi  '],
             ['Eye', u':  skada  f\xf6rorsaka d  av  olycka  ']]]],
 '_pages': [8, 10],
 u'_rank': 8,
 u'_type': u'LSFU3'}