{'_data': [['Very common',
            [['Infections', u'Nasofaryngit'], ['Nervous system', u'Somnolens, huvudv\xe4rk']]],
           ['Common',
            [['Metabolism', u'Anorexi'],
<<<<<<< HEAD
             ['Psychiatric',
              u'Depression, fientlighet/aggression, \xe5ngest, insomni, nervositet/irritabilitet'],
=======
             ['Psychiatric', u'Depression,'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Konvulsion, balansrubbning, yrsel, letargi, tremor'],
             ['Ear', u'Vertigo'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Buksm\xe4rta, diarr\xe9, dyspepsi, kr\xe4kningar, illam\xe5ende'],
             ['Skin', u'Utslag'],
             ['General', u'Asteni/utmattning']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, leukopeni'],
<<<<<<< HEAD
             ['Metabolism', u'Viktminskning, vikt\xf6kning'],
             ['Psychiatric',
              u'sj\xe4lvmordsf\xf6rs\xf6k, sj\xe4lvmordstankar, psykotisk st\xf6rning, onormalt uppf\xf6rande, hallucination, ilska, f\xf6rvirring, panikattack, emotionell labilitet/hum\xf6rsv\xe4ngni ngar, agitation'],
             ['Nervous system',
              u'Amnesi, f\xf6rs\xe4mring av minnet, onormal koordination/ataxi, parestesi, st\xf6rning i uppm\xe4rksamheten'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Hepato', u'Onormalt leverfunktionstest'],
             ['Skin', u'Alopeci, eksem, kl\xe5da,'],
=======
             ['Metabolism', u'Viktminskning  , vikt\xf6kning'],
             ['Psychiatric',
              u'sj\xe4lvmordsf\xf6rs\xf6k , f\xf6rvirring labilitet/hum\xf6rsv\xe4ngni ngar, agitation'],
             ['Nervous system',
              u'Amnesi, f\xf6rs\xe4mring av minnet, onormal koordination/ataxi, parestesi uppm\xe4rksamheten'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Hepato', u'Onormalt leverfunktionstest'],
             ['Skin', u'Alopeci , eksem, kl\xe5da,'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Musculoskeletal', u'Muskelsvaghet, myalgi'],
             ['Injury', u'Skada']]],
           ['Rare',
            [['Infections', u'Infektion'],
<<<<<<< HEAD
             ['Blood', u'Pancytopeni, neutropeni'],
             ['Psychiatric', u'Sj\xe4lvmord, personlighetsst\xf6rningar, onormalt t\xe4nkande'],
             ['Nervous system', u'Koreoatetos, dyskinesi, hyperkinesi'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt, hepatit'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme']]]],
=======
             ['Blood', u'Pancytopeni  , neutropeni'],
             ['Psychiatric', u'Sj\xe4lvmord , , emotionell'],
             ['Nervous system', u'Koreoatetos , dyskinesi , hyperkinesi , st\xf6rning i'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt  , hepatit'],
             ['Skin', u'Toxisk epidermal nekrolys , Stevens-erythema multiforme']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 26,
 u'_type': u'MSFU'}