{'_data': [['Very common',
<<<<<<< HEAD
            [['Infections', u'Nasofaryngit'], ['Nervous system', u'Somnolens, huvudv\xe4rk']]],
           ['Common',
            [['Metabolism', u'Anorexi'],
             ['Psychiatric',
              u'Depression, fientlighet/ aggression, \xe5ngest, insomni, nervositet/ irritabilitet'],
             ['Nervous system', u'Konvulsion, balansrubbning, yrsel, letargi, tremor'],
             ['Ear', u'Vertigo'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Buksm\xe4rta, diarr\xe9, dyspepsi, kr\xe4kningar, illam\xe5ende'],
             ['Skin', u'Utslag'],
             ['General', u'Asteni/utmattning']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, leukopeni'],
             ['Metabolism', u'Viktminskning, vikt\xf6kning'],
             ['Psychiatric',
              u'sj\xe4lvmordsf\xf6rs\xf6k, sj\xe4lvmordstankar, psykotisk st\xf6rning, onormalt uppf\xf6rande, hallucination, ilska, f\xf6rvirring, panikattack, emotionell labilitet/ hum\xf6rsv\xe4ngningar, agitation'],
             ['Nervous system',
              u'Amnesi, f\xf6rs\xe4mring av minnet, onormal koordination/ataxi, parestesi, st\xf6rning i uppm\xe4rksamheten'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Hepato', u'Onormalt leverfunktionstest'],
             ['Skin', u'Alopeci, eksem, kl\xe5da'],
             ['Musculoskeletal', u'Muskelsvaghet, myalgi'],
             ['Injury', u'Skada']]],
           ['Rare',
            [['Infections', u'Infektion'],
             ['Blood', u'Pancytopeni neutropeni'],
             ['Psychiatric',
              u'Sj\xe4lvmord, personlighets-st\xf6r ningar, onormalt t\xe4nkande'],
             ['Nervous system', u'Koreoatetos, dyskinesi, hyperkinesi'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt, hepatit'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 26,
 u'_type': u'MSFU'}
=======
            [['Nervous system', u'somnolens'], ['General', u'asteni/tr\xf6tthet']]],
           ['Common',
            [['Infections', u'infektion, nasofaryngit'],
             ['Blood', u'trombocytopeni'],
             ['Metabolism', u'aptitl\xf6shet, vikt\xf6kning'],
             ['Psychiatric',
              u'agitation, depression, emotionell labilitet/hum\xf6rsv\xe4ngningar, fientlighet/aggression, insomnia, nervositet/irritabilitet, personlighetsst\xf6rningar, avvikande t\xe4nkande'],
             ['Nervous system',
              u'amnesi, ataxi, kramper, yrsel, huvudv\xe4rk, hyperkinesi, tremor, balansrubbning, st\xf6rning i uppm\xe4rksamheten, f\xf6rs\xe4mring av minnet'],
             ['Eye', u'diplopi, dimsyn'],
             ['Ear', u'vertigo'],
             ['Respiratory', u'\xf6kad hosta'],
             ['GI', u'buksm\xe4rta, diarr\xe9, dyspepsi, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'utslag, eksem, kl\xe5da'],
             ['Musculoskeletal', u'myalgi'],
             ['Injury',
              u'skada f\xf6rorsakad av olycka Beskrivning av utvalda biverkningar Risken f\xf6r aptitl\xf6shet \xe4r h\xf6gre n\xe4r topiramat administreras samtidigt med levetiracetam. I flera fall av alopeci s\xe5gs \xe5terh\xe4mtning n\xe4r levetiracetam sattes ut.']]],
           ['Unknown',
            [['Blood',
              u'leukopeni, neutropeni, pancytopeni (med benm\xe4rgssuppression konstaterad i n\xe5gra av fallen)'],
             ['Metabolism', u'viktminskning'],
             ['Psychiatric',
              u'avvikande beteende, ilska, \xe5ngest, f\xf6rvirring, hallucination, psykotisk st\xf6rning, sj\xe4lvmord, sj\xe4lvmordsf\xf6rs\xf6k, sj\xe4lvmordstankar'],
             ['Nervous system', u'parestesi, koreoatetos, dyskinesi'],
             ['GI', u'pankreatit'],
             ['Hepato', u'leversvikt, hepatit, avvikande resultat i leverfunktionstest'],
             ['Skin',
              u'toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme, alopeci']]]],
 '_pages': [7, 9],
 u'_rank': 21,
 u'_type': u'LSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
