<<<<<<< HEAD
{'_data': [['Very common',
            [['Infections', u'Nasofaryngit'], ['Nervous system', u'Somnolens, huvudv\xe4rk']]],
           ['Common',
            [['Metabolism', u'Anorexi'],
             ['Psychiatric',
              u'Depression, fientlighet/ aggression, \xe5ngest, insomni, nervositet/ irritabilitet'],
             ['Nervous system', u'Konvulsion, balansrubbning, yrsel, letargi, tremor'],
             ['Ear', u'Vertigo'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Buksm\xe4rta, diarr\xe9, dyspepsi, kr\xe4kningar, illam\xe5ende'],
             ['Skin', u'Utslag'],
             ['General', u'Asteni/utmattning']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, leukopeni'],
             ['Metabolism', u'Viktminskning, vikt\xf6kning'],
             ['Psychiatric',
              u'Sj\xe4lvmordsf\xf6rs\xf6k, sj\xe4lvmordstankar, psykotisk st\xf6rning, onormalt uppf\xf6rande, hallucination, ilska, f\xf6rvirring, panikattack, emotionell labilitet/ hum\xf6r-sv\xe4ngning ar, agitation'],
             ['Nervous system',
              u'Amnesi, f\xf6rs\xe4mring av minnet, onormal koordination/ataxi parestesi, st\xf6rning i uppm\xe4rksamheten'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Hepato', u'Onormalt leverfunktionstest'],
             ['Skin', u'Alopeci, eksem, kl\xe5da'],
             ['Musculoskeletal', u'Muskelsvaghet, Myalgi'],
             ['Injury', u'Skada']]],
           ['Rare',
            [['Infections', u'Infektion'],
             ['Blood', u'Pancytopeni, neutropeni'],
             ['Psychiatric',
              u'Sj\xe4lvmord, personlighets-st\xf6r ningar, onormalt t\xe4nkande'],
             ['Nervous system', u'Koreoatetos, dyskinesi, hyperkinesi'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt, hepatit'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 8],
 u'_rank': 26,
 u'_type': u'MSFU'}
=======
{'_data': [['Very common', [['Eye', u'a:  ast e ni/tr\xf6tt h e t  ']]],
           ['Common',
            [['Eye', u':  diplopi,  dimsyn  \xd6ron  och  bala n s o r g a n  '],
             ['Eye', u':  vertigo  '],
             ['Eye', u':  \xf6kad  host a  Magt ar m k a n a l e n  '],
             ['Eye',
              u':  buks m \xe4 r t a ,  diarr\xe9,  dysp e p si,  illam\xe5 e n d e ,  kr\xe4kninga r  '],
             ['Eye', u':  utslag,  ekse m,  kl\xe5da  '],
             ['Eye', u':  myalgi  '],
             ['Eye', u':  skada  f\xf6rorsaka d  av  olycka  ']]]],
 '_pages': [8, 10],
 u'_rank': 8,
 u'_type': u'LSFU3'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
