{'_data': [['Common',
            [['Cardiac', u'Hypotension, hypertension, bradykardi'],
             ['Nervous system', u'Epileptiska anfall, parestesi, sluddrigt tal'],
             ['Eye', u'Suddigt seende, dubbelseende'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, f\xf6rstoppning'],
             ['General', u'D\xe5sighet, yrsel, huvudv\xe4rk,letargi']]],
           ['Uncommon',
            [['Cardiac', u'Djup ventrombos, blekhet, dyspn\xe9'],
             ['Nervous system',
              u'Sv\xe4ljningssv\xe5righeter, koordinationssv\xe5righeter, smakrubbning'],
             ['Eye', u'Nystagmus Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Eye', u'Andningsdepression, nedsatt andningsfrekvens'],
             ['GI', u'Diarr\xe9, ileus'],
             ['Renal', u'Urininkontinens (slappbl\xe5sa, bl\xe5sspasm), sexuell st\xf6rning'],
             ['Skin', u'Hudrodnad, urtikaria, alopeci'],
             ['General', u'Hypotermi, nedsatt aptit, dehydrering, ansikts\xf6dem, muntorrhet'],
             ['Psychiatric',
              u'Insomningssv\xe5righeter, minnesst\xf6rning, f\xf6rvirringstillst\xe5nd, \xe5ngest, depression, suicidtankar och f\xf6rs\xf6k, eufori, dysfori, hallucinationer, paranoia. Biverkningar associerade med infusionssystemet (inflammatorisk h\xe4rd p\xe5 spetsen av katetern med m\xf6jliga komplikationer) har rapporterats, d\xe4r orsakssamband i vissa fall inte kunnat uteslutas (se avsnitt 4.4). Ovarialcystor har uppt\xe4ckts vid palpation hos omkring 5 % av de multipel sklerospatienter som behandlats med peroralt Lioresal upp till ett \xe5r. I de flesta fall har dessa cystor f\xf6rsvunnit spontant medan patienterna fortsatt att ta l\xe4kemedlet.']]],
           ['Rare',
            [['General',
              u'Livshotande uts\xe4ttningssymptom p\xe5 grund av pl\xf6tsligt avbrytande av intratekal Lioresal behandling (se avsnitt 4.4 - Pl\xf6tsligt avbrytande av intratekal Lioresaltillf\xf6rsel.)'],
             ['Psychiatric',
              u'fall av f\xf6rh\xf6jt ASAT, alkaliskt fosfatas och glukosniv\xe5er i serum har rapporterats under anv\xe4ndning av peroralt givet Lioresal. \xc4ldre patienter kan vara mer k\xe4nsliga f\xf6r biverkningar.']]]],
 '_pages': [6, 7],
 u'_rank': 16,
 u'_type': u'LSFU'}