{'_data': [['Very common', [['Skin', u'D\xe5sighet']]],
           ['Common',
            [['Cardiac', u'Hypotension'],
             ['Eye', u'Andningsdepression'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, f\xf6rstoppning, diarr\xe9'],
             ['Skin', u'Tr\xf6tthet, huvudv\xe4rk, yrsel'],
             ['Psychiatric', u'F\xf6rvirringstillst\xe5nd, insomningssv\xe5righeter,']]],
           ['Uncommon',
            [['Nervous system', u'Muskelsvaghet'],
             ['Renal', u'T\xe4ta urintr\xe4ngningar, sexuell st\xf6rning'],
             ['Skin', u'Hudutslag, kl\xe5da'],
             ['Skin', u'Svettning, vikt\xf6kning, ankel\xf6dem'],
             ['Psychiatric', u'Mardr\xf6mmar']]],
           ['Rare',
            [['Investigations', u'F\xf6rh\xf6jda blodglukosniv\xe5er'],
             ['Cardiac', u'Dyspn\xe9, palpationer, br\xf6stsm\xe4rtor, synkop\xe9'],
             ['Nervous system',
              u'Epileptiska kramper, parestesier, sluddrigt tal, koordinationssv\xe5righeter, tremor, stelhet, dystoni, ataxi, \xf6kad spasticitet, smakrubbning, muntorrhet'],
             ['Eye',
              u'Nedsatt syn, nystagmus, strabism, mios Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Renal', u'Dysuri, enures'],
             ['Skin', u'Myalgi'],
             ['Hepato', u'Transaminas- och ALP-stegring'],
             ['Psychiatric',
              u'Eufori, exaltering, depression, hallucinationer (speciellt hos \xe4ldre) Hos patienter med anamnes p\xe5 psykiatrisk sjukdom eller kardiovaskul\xe4r sjukdom (t ex stroke) liksom hos \xe4ldre patienter kan man f\xf6rmoda en allvarligare form av biverkan. Det \xe4r ofta sv\xe5rt att skilja de neuropsykiatriska besv\xe4ren fr\xe5n sjukdomen som behandlas.']]],
<<<<<<< HEAD
           ['Very rare', [['Skin', u'Hypotermi']]],
=======
           ['Very rare', [['Skin', u'Hypotermi Abstinenssyndrom']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Cardiac', u'Bradykardi'],
             ['Skin',
              u'Urtikaria Allm\xe4nna symptom och/eller symtom vid administreringsst\xe4llet']]]],
 '_pages': [5, 6],
 u'_rank': 22,
 u'_type': u'LSFU'}