{'_data': [['Common',
            [['Vascular', u'Gastrointestinala tecken och symtom (buksm\xe4rtor,'],
             ['GI',
              u'illam\xe5ende, kr\xe4kning, diarr\xe9 och gasbildning ) F\xf6rh\xf6jda transaminasv\xe4rden (se'],
             ['Hepato', u'avsnitt 4.4).'],
             ['Reproductive system', u'och br\xf6stk\xf6rtel ']]],
           ['Uncommon',
            [['Nervous system', u'Huvudv\xe4rk Tromboembolism (pulmon\xe4r'],
             ['Vascular', u'embolism, djup ventrombos)*'],
             ['GI', u'Pankreatit* Gallstenssjukdom'],
             ['Hepato', u'(se avsnitt 4.4) \xd6verk\xe4nslighets-r eaktioner i huden'],
             ['Skin', u'(t.ex. utslag, kl\xe5da, urtikaria) Muskelsjukdom (t.ex. myalgi,'],
             ['Musculoskeletal', u'myosit, muskelspasmer och svaghet) Sexuell'],
             ['Reproductive system', u'dysfunktion \xd6kning av'],
             ['Investigations', u'kreatinin i blodet']]],
           ['Rare',
            [['Blood', u'Minskat antal av leukocyter'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'Tr\xf6tthet och vertigo'],
             ['Hepato', u'Hepatit Alopeci'],
             ['Skin', u'Fotosensibilitets reaktioner'],
             ['Investigations', u'\xd6kning av urea']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 5],
 u'_rank': 18,
 u'_type': u'MSFU'}