{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'f\xf6rstoppning, diarr\xe9, dyspepsi och illam\xe5ende'],
             ['Musculoskeletal', u'myalgi och artralgi']]],
           ['Uncommon',
            [['Blood', u'anemi'],
             ['Metabolism', u'anorexi'],
             ['Psychiatric', u's\xf6mnl\xf6shet'],
             ['Nervous system', u'yrsel, dysgeusi och s\xf6mnighet'],
             ['Ear', u'tinnitus'],
             ['GI', u'buksm\xe4rta, muntorrhet och kr\xe4kningar'],
             ['Hepato',
              u'\xf6kad niv\xe5 av transaminaser (aspartataminotransferas, alaninaminotransferas)'],
             ['Skin', u'kl\xe5da och utslag'],
             ['Musculoskeletal', u'muskelspasmer'],
             ['Renal', u'pollakisuri'],
             ['General',
              u'asteni, allm\xe4n sjukdomsk\xe4nsla, tr\xf6tthet och perifera \xf6dem F\xf6rh\xf6jda kreatininkinasniv\xe5er i blod p\xe5 >3 g\xe5nger den \xf6vre normalgr\xe4nsen (ULN) intr\xe4ffade hos 49 av 2 800 (1,8 %) patienter som fick Livazo i kontrollerade kliniska pr\xf6vningar. Niv\xe5er p\xe5 \u226510 g\xe5nger ULN med samtidiga muskelsymtom var s\xe4llsynta och observerades endast hos en patient av 2 406 som behandlades med 4mg Livazo (0,04 %) i det kliniska pr\xf6vningsprogrammet. Erfarenhet efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning En prospektiv, tv\xe5\xe5rig unders\xf6kningsstudie efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning utf\xf6rdes p\xe5 n\xe4stan 20 000 patienter i Japan. Den \xf6verv\xe4gande majoriteten av de 20 000 patienterna i studien behandlades med 1 eller 2mg pitavastatin och inte 4mg. Av patienterna rapporterade 10,4 % biverkningar f\xf6r vilka ett orsakssamband till pitavastatin inte kunde uteslutas och 7,4 % av patienterna avbr\xf6t behandlingen p\xe5 grund av biverkningar. Frekvensen av myalgi var 1,08 %. De flesta biverkningarna var lindriga. Frekvensen av biverkningar var h\xf6gre under de 2 \xe5ren hos patienter med l\xe4kemedelsallergi (20,4 %) eller lever- eller njursjukdom (13,5 %). Biverkningar och frekvenser som observerats i den prospektiva unders\xf6kningsstudien efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning, men inte i kontrollerade kliniska pr\xf6vningar \xf6ver hela v\xe4rlden, vid rekommenderade doser, anges nedan.'],
             ['Nervous system', u'hypoestesi']]],
           ['Rare',
            [['Eye', u'nedsatt synsk\xe4rpa'],
             ['GI', u'glossodyni och akut pankreatit'],
             ['Hepato', u'kolestatisk gulsot'],
             ['Skin', u'urticaria och erytem'],
             ['Hepato', u'onormal leverfunktion och leversjukdom'],
             ['Musculoskeletal',
              u'myopati och rabdomyolys I unders\xf6kningsstudien efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning f\xf6rekom tv\xe5 rapporter om rabdomyolys som kr\xe4vde inl\xe4ggning p\xe5 sjukhus (0,01 % av patienterna). Dessutom f\xf6rekom spontana rapporter efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning om skelettmuskeleffekter, inklusive myalgi och myopati, hos patienter som behandlats med Livazo vid alla rekommenderade doser. Rapporter om rabdomyolys, med eller utan akut njursvikt, inklusive fatal rabdomyolys har ocks\xe5 mottagits. Spontana rapporter om f\xf6ljande biverkningar har \xe4ven f\xf6rekommit (frekvensen har baserats p\xe5 observationer under studier efter godk\xe4nnande)'],
             ['GI',
              u'bukobehag Statinklasseffekter F\xf6ljande biverkningar har rapporterats med vissa statiner: \u2022s\xf6mnst\xf6rningar, inklusive mardr\xf6mmar \u2022minnesf\xf6rlust \u2022sexuell dysfunktion \u2022depression \u2022enstaka fall av interstitiell lungsjukdom, s\xe4rskilt vid l\xe5ngtidsbehandling (se avsnitt 4.4). \u2022diabetes mellitus: frevensen beror p\xe5 f\xf6rekomst eller avsaknad av riskfaktorer (fastande blodglukos \u22655,6 mmol/l, BMI >30 kg/m2, f\xf6rh\xf6jda triglycerider, hypertension i anamnes).']]]],
 '_pages': [4, 6],
 u'_rank': 22,
 u'_type': u'LSFU'}