{'_data': [['Common',
            [['Blood', u'M\xe5ttlig leukocytos, lymfopeni, eosinopeni, polycytemi'],
             ['Immune system',
              u'Nedsatt immunf\xf6rsvar, maskering av infektioner, f\xf6rv\xe4rrande av latenta infektioner'],
             ['Endocrine',
              u'Binjuresuppression och induktion av Cushings syndrom (typiska symtom m\xe5nformat ansikte, fetma p\xe5 \xf6verkroppen, plethora)'],
             ['Metabolism',
              u'Natriumretention med \xf6dem, \xf6kad kaliumuts\xf6ndring (f\xf6rsiktighet arytmier), \xf6kad aptit och vikt\xf6kning, minskad glukostolerans, diabetes mellitus, hyperkolesterolemi och hypertriglyceridemi'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk.'],
             ['Eye', u'Katarakt, i synnerhet med bakre subkapsul\xe4r grumling, glaukom'],
             ['Skin',
              u'Striae rubrae, atrofi, telangiektasi, \xf6kad kapill\xe4rsk\xf6rhet, petekier, ekkymoser'],
             ['Musculoskeletal',
              u'Muskelatrofi och muskelsvaghet, osteoporos (dosrelaterat, kan f\xf6rekomma \xe4ven vid korttidsanv\xe4ndning)']]],
           ['Uncommon',
            [['Vascular',
              u'Hypertoni, \xf6kad risk f\xf6r arterioskleros och trombos, vaskulit (\xe4ven uts\xe4ttningssyndrom efter l\xe5ngvarig terapi)'],
             ['GI', u'Gastrointestinala s\xe5r, gastrointestinala bl\xf6dningar'],
             ['Skin',
              u'Hypertrikos, steroid acne, f\xf6rdr\xf6jd s\xe5rl\xe4kning, rosacealiknande (perioral) dermatit, f\xf6r\xe4ndrad hudpigmentering']]],
           ['Rare',
            [['Immune system', u'Allergiska reaktioner'],
             ['Endocrine',
              u'St\xf6rd ins\xf6ndring av k\xf6nshormon (amenorr\xe9, impotens), st\xf6rning av sk\xf6ldk\xf6rtelfunktionen'],
             ['Psychiatric',
              u'Depression, irritabilitet, eufori, \xf6kad impulsivitet, psykos'],
             ['Nervous system',
              u'Pseudotum\xf6r cerebri, manifestation av en latent epilepsi och \xf6kad predisponering f\xf6r att utveckla anfall vid manifest epilepsi.'],
             ['Eye',
              u'Aggravation av symtom i samband med hornhinnes\xe5r, fr\xe4mjande av virus-, svamp- och bakterieinflammationer i \xf6gat'],
             ['GI', u'Pankreatit'],
             ['Skin', u'\xd6verk\xe4nslighetsreaktioner, t.ex. l\xe4kemedelsexantem'],
             ['Musculoskeletal',
<<<<<<< HEAD
              u'Aseptisk osteonekros (\xf6verarmsbenets huvud och l\xe5rbenshuvudet)']]],
           ['Unknown',
            [['Metabolism', u'Reversibel epidural, epikardiell eller mediastinal lipomatos']]]],
 '_pages': [5, 6],
 u'_rank': 21,
=======
              u'Aseptisk osteonekros (\xf6verarmsbenets huvud och l\xe5rbenshuvudet)']]]],
 '_pages': [5, 6],
 u'_rank': 20,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}