{'_data': [['Very common', [['Nervous system', u'Tr\xf6tthet']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Perifert \xf6dem'],
             ['Cardiac',
              u'Bradykardi, posturala  symtom (mycket s\xe4llan med synkope), perifer kyla i extremiteter, palpitationer'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende, buksm\xe4rtor,  diarr\xe9, f\xf6rstoppning'],
             ['Respiratory', u'Andf\xe5ddhet vid anstr\xe4ngning']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel, parestesier'],
             ['Cardiac', u'Takykardi, palpitationer'],
             ['GI', u'Illam\xe5ende, magsm\xe4rtor'],
             ['General', u'Tr\xf6tthet.'],
             ['Cardiac',
              u'\xd6verg\xe5ende f\xf6rs\xe4mring av  hj\xe4rtsvikt, AV-block I, \xf6dem, br\xf6stsm\xe4rtor.'],
             ['Nervous system', u'Parestesier, muskelkramper'],
             ['GI', u'Kr\xe4kningar'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['Psychiatric',
              u'Depression,  koncentrationssv\xe5righeter, s\xf6mnst\xf6rningar, mardr\xf6mmar'],
             ['Respiratory', u'Bronkospasm'],
             ['Skin',
              u'\xd6verk\xe4nslighetsreaktioner (t  ex urtikaria, psoriasiforma  och dystrofiska hudskador), hyperhidros']]],
           ['Rare',
            [['Cardiac', u'Synkope'],
             ['GI', u'Kr\xe4kningar'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['Psychiatric', u'Impotens/sexuell  funktions-st\xf6rning'],
             ['Cardiac', u'\xd6verledningsst\xf6rningar,  hj\xe4rtarytmier'],
             ['GI', u'Muntorrhet'],
             ['Hepato', u'Onormala  leverfunktionsv\xe4rden'],
             ['Psychiatric', u'Nervositet, oro, impotens/  libidost\xf6rning'],
             ['Respiratory', u'Rinit'],
             ['Skin', u'H\xe5ravfall,']]],
           ['Very rare',
            [['GI', u'Gingival hyperplasi, gingivit'],
             ['Hepato', u'F\xf6rh\xf6jning av leverenzymer'],
             ['Renal', u'Pollakisuri'],
             ['General', u'\xd6verk\xe4nslighetsreaktioner,  till exempel angio\xf6dem, feber'],
             ['Cardiac', u'Gangr\xe4n hos patienter med  sv\xe5r perifer k\xe4rlsjukdom'],
             ['Blood', u'Trombocytopeni'],
             ['Hepato', u'Hepatit'],
             ['Musculoskeletal', u'Artralgi'],
             ['Psychiatric', u'Amnesi/minnesst\xf6rning,  konfusion, hallucinationer'],
             ['Skin', u'Fotosensitivitet, f\xf6rv\xe4rrad  psoriasis']]]],
 '_pages': [6, 9],
 u'_rank': 38,
 u'_type': u'TSFU'}