{'_data': [[u'Unknown',
            [['Immune system', u'Anafylaxi'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac', u'Takykardi, hj\xe4rtklappning'],
             ['GI', u'Illam\xe5ende, muntorrhet, gastrit'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Utslag, alopeci'],
             ['General', u'Tr\xf6tthet']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'LFSU'}