{'_data': [['Very common',
            [['Metabolism', u'Anorexi Alla grader'],
             ['GI',
              u'Diarr\xe9, Kr\xe4kningar, Illam\xe5ende, Stomatit, Buksm\xe4rta Alla grader'],
             ['Skin', u'Hand-fot-syndromet (palmar-plantar erytrodysestesi)'],
             ['General', u'Tr\xf6tthet, Asteni']]],
           ['Common',
<<<<<<< HEAD
            [['Infections', u'Herpesvirusinfektion, Nedre luftv\xe4gsinfektion'],
             ['Metabolism', u'Alla grader'],
=======
            [['Infections', u'Herpesvirusinfektion, Nasofaryngit, Nedre luftv\xe4gsinfektion'],
             ['Blood', u'Neutropeni, Anemi'],
             ['Metabolism', u'Dehydrering, Minskad aptit, Viktnedg\xe5ng Alla grader'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Psychiatric', u'S\xf6mnl\xf6shet, Depression'],
             ['Nervous system',
              u'Huvudv\xe4rk, Letargi, Yrsel, Paraestesi, Dysgeusi (smakrubbning)'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de, Konjunktivit, \xd6gonirritation'],
             ['Vascular', u'Tromboflebit'],
             ['Respiratory', u'Dyspn\xe9, Epistaxis, Hosta, Rinorr\xe9'],
             ['GI',
              u'Gastrointestinal bl\xf6dning, F\xf6rstoppning, Sm\xe4rta i \xf6vre delen av buken, Dyspepsi, Flatulens, Muntorrhet Alla grader'],
             ['Hepato', u'Hyperbilirubinemi, Avvikande leverfunktionsv\xe4rden'],
             ['Skin',
              u'Hudutslag, Alopeci, Erytem, Torr hud, Kl\xe5da, Hyperpigmentering, Makul\xf6sa utslag, Hudfj\xe4llning, Dermatit, Rubbning i pigmenteringen, Nagelf\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Sm\xe4rta i extremiteter, Ryggv\xe4rk, Artralgi'],
             ['General',
              u'Feber, Letargi, Perifera \xf6dem, Sjukdomsk\xe4nsla, Br\xf6stsm\xe4rta']]],
           ['Uncommon',
            [['Infections',
              u'Sepsis, Urinv\xe4gsinfektion, Cellulit, Tonsillit, Faryngit, Oral candidiasis, Influensa, Gastroenterit, Svampinfektion, Infektion, Tandabscess'],
             ['Neoplasms', u'Lipom'],
             ['Blood',
              u'Febril neutropeni, Pancytopeni, Granulocytopeni, Trombocytopeni, Leukopeni, Hemolytisk anemi, F\xf6rh\xf6jd INR (internationellt normaliserad kvot)/f\xf6rl\xe4ngd protrombintid'],
             ['Immune system', u'Hypersensitivitet'],
             ['Metabolism',
              u'Diabetes, Hypokalemi, St\xf6rd aptit, Malnutrition, Hypertriglyceridemi Allvarliga och/eller livshotande (grad 3-4) eller bed\xf6mda medicinskt relevanta'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, Panikattack, S\xe4nkt st\xe4mningsl\xe4ge, Minskad libido'],
             ['Nervous system',
              u'Afasi, F\xf6rs\xe4mrat minne, Ataxi, Synkop\xe9, Balansrubbning, K\xe4nselrubbning, Perifer neuropati'],
             ['Eye', u'F\xf6rs\xe4mrad synsk\xe4rpa, Diplopi'],
             ['Ear', u'Vertigo, \xd6ronv\xe4rk'],
             ['Cardiac',
              u'Instabil angina, Angina pectoris, Myokardischemi, F\xf6rmaksflimmer, Arytmi, Takykardi, Sinus-takykardi, Hj\xe4rtklappning'],
             ['Vascular',
              u'Djup ventrombos, Hypertoni, Petekier, Hypotoni, Blodvallning, Perifer k\xf6ldk\xe4nsla'],
             ['Respiratory',
              u'Lungemboli, Pneumotorax, Hemoptys, Astma, Anstr\xe4ngningsutl\xf6st dyspn\xe9'],
             ['GI',
              u'Tarmobstruktion, Ascites, Enterit, Gastrit, Dysfagi, Sm\xe4rta i nedre delen av buken, Esofagit, Bukbesv\xe4r, Gastro-esofageal refluxsjukdom, Kolit, Blod i avf\xf6ringen Allvarliga och/eller livshotande (grad 3-4) eller bed\xf6mda medicinskt relevanta'],
             ['Hepato', u'Gulsot'],
             ['Skin',
              u'Hudulceration, Hudutslag, Urtikaria, Fotosensitivitets-reaktioner, Palmarerytem, Svullet ansikte, Purpura'],
             ['Musculoskeletal',
              u'Ledsvullnad, Skelettsm\xe4rta, Ansiktssm\xe4rta, Muskuloskeletal stelhet, Muskelsvaghet'],
             ['Renal',
              u'Hydronefros, Urininkontinens, Hematuri, Nokturi, F\xf6rh\xf6jt blodkreatinin'],
             ['Reproductive system', u'Vaginal bl\xf6dning'],
             ['General',
              u'\xd6dem, Frossbrytningar, Influensaliknande sjukdom, Stelhet, F\xf6rh\xf6jd kroppstemperatur'],
             ['Injury', u'Bl\xe5sor,']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 12],
<<<<<<< HEAD
 u'_rank': 36,
=======
 u'_rank': 37,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}