{'_data': [['Common',
            [['Psychiatric', u'Insomni'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Respiratory',
              u'Hosta, \xf6vre luftv\xe4gsinfektion, n\xe4st\xe4ppa, sinusit, bih\xe5lebesv\xe4r'],
             ['GI', u'Buksm\xe4rta, illam\xe5ende, diarr\xe9, dyspepsi'],
             ['Musculoskeletal', u'Muskelkramp, ryggv\xe4rk, benv\xe4rk, myalgi'],
             ['General', u'Asteni, tr\xf6tthet, br\xf6stsm\xe4rta'],
             ['Investigations', u'Hyperkalemi, liten s\xe4nkning av hematokrit och hemoglobin'],
             ['Nervous system', u'Cefalalgi']]],
           ['Uncommon',
            [['Blood', u'Anemi, Henoch-Sch\xf6nleins purpura, ekkymos, hemolys'],
             ['Metabolism', u'Anorexi, gikt'],
             ['Psychiatric',
              u'\xc4ngslan, \xe5ngestsyndrom, paniksyndrom, f\xf6rvirring, depression, f\xf6r\xe4ndrat dr\xf6mm\xf6nster, s\xf6mnst\xf6rningar, somnolens, nedsatt minnesf\xf6rm\xe5ga'],
             ['Nervous system',
              u'Nervositet, parestesi, perifer neuropati, tremor, migr\xe4n, synkope'],
             ['Eye',
              u'Dimsyn, br\xe4nnande/svidande \xf6gonsm\xe4rta, konjunktivit, nedsatt synsk\xe4rpa'],
             ['Ear', u'Svindel, tinnitus'],
             ['Cardiac',
              u'Hypotoni, ortostatisk hypotoni, sternalgi, angina pectoris, AV-block grad II, cerebrovaskul\xe4r h\xe4ndelse, hj\xe4rtinfarkt, palpitation, arytmier (f\xf6rmaksflimmer, sinusbradykardi, takykardi, ventrikul\xe4r takykardi, ventrikelflimmer)'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory',
              u'Svalgbesv\xe4r, faryngit, laryngit, dyspn\xe9, bronkit, epistaxis, rinit, andn\xf6d'],
             ['GI',
              u'F\xf6rstoppning, tandv\xe4rk, muntorrhet, flatulens, gastrit, kr\xe4kning Levern och gallv\xe4garna'],
             ['Skin',
              u'Alopeci, dermatit, torr hud, erytem, rodnad, ljusk\xe4nslighet, pruritus, hudutslag, urtikaria, svettning'],
             ['Musculoskeletal',
              u'Armv\xe4rk, ledsvullnad, kn\xe4v\xe4rk, muskuloskeletal v\xe4rk, axelv\xe4rk, stelhet, artralgi, artrit, coxalgi, fibromyalgi, muskelsvaghet'],
             ['Renal', u'Nokturi, frekventa urint\xf6mningar, urinv\xe4gsinfektion'],
             ['Reproductive system', u'Minskad k\xf6nsdrift, impotens'],
             ['General', u'Ansikts\xf6dem, feber'],
             ['Investigations', u'Liten h\xf6jning av serumhalterna av urea och kreatinin'],
             ['Blood',
              u'Agranulocytos, aplastisk anemi, hemolytisk anemi, leukopeni, purpura, trombocytopeni'],
             ['Metabolism', u'Anorexi, hyperglykemi, hyperurikemi, hypokalemi, hyponatremi'],
             ['Psychiatric', u'Insomni'],
             ['Eye', u'\xd6verg\xe5ende dimsyn, xantopsi'],
             ['Vascular', u'Nekrotiserande angit (vaskulit, kutan vaskulit)'],
             ['Respiratory', u'Respiratorisk distress, inklusive pneumoni och lung\xf6dem'],
             ['GI',
              u'Sialoadenit, spasmer, irritation i mags\xe4cken, illam\xe5ende, kr\xe4kning, diarr\xe9, f\xf6rstoppning Levern och gallv\xe4garna'],
             ['GI', u'Ikterus (intrahepatisk kolestas), pankreatit'],
             ['Skin', u'Ljusk\xe4nslighet, urtikaria, toxisk epidermal nekrolys'],
             ['Musculoskeletal', u'Muskelkramper'],
             ['Renal', u'Glukosuri, interstitiell nefrit, nedsatt njurfunktion, njursvikt'],
             ['General', u'Feber, yrsel']]],
           ['Rare',
            [['Investigations',
              u'Hyperkalemi, f\xf6rh\xf6jt ALAT Ytterligare biverkningar som har observerats med en av de enskilda komponenterna och som kan upptr\xe4da som biverkningar av losartankalium/hydroklortiazid \xe4r f\xf6ljande: Losartan'],
             ['Immune system', u'Anafylaktiska reaktioner, angio\xf6dem, urtikaria'],
             ['Immune system', u'Anafylaktisk reaktion']]],
           ['Very rare',
            [['Investigations',
              u'F\xf6rh\xf6jda v\xe4rden f\xf6r leverenzymer och bilirubin Hydroklortiazid']]],
           ['Unknown', [['GI', u'Onormal leverfunktion'], ['Musculoskeletal', u'Rhabdomyolys']]]],
 '_pages': [7, 10],
 u'_rank': 42,
 u'_type': u'LSFU'}