{'_data': [['Common',
            [['Nervous system', u'yrsel, vertigo'],
             ['Investigations', u'hyperkalemi'],
             ['Nervous system', u'yrsel'],
             ['Ear', u'vertigo'],
             ['General',
              u'asteni, tr\xf6tthet Kronisk hj\xe4rtsvikt I en kontrollerad klinisk studie p\xe5 patienter med hj\xe4rtsvikt hj\xe4rtsvikt (se ELITE I, ELITE II-studierna och HEAAL-studien, avsnitt 5.1) rapporterades f\xf6ljande biverkningar'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'hypotoni inkluderande ortostatisk hypotoni'],
             ['Blood', u'anemi'],
             ['Investigations',
              u'f\xf6rh\xf6jda v\xe4rden av urea i blodet, serumkreatinin och serumkalium'],
             ['Renal',
              u'nedsatt njurfunktion, njursvikt **vanliga hos patienter som fick 150 mg losartan ist\xe4llet f\xf6r 50 mg losartan Hypertensiva patienter med typ 2 - diabetes och njursjukdom I en kontrollerad klinisk studie p\xe5 1513 patienter 31 \xe5r och \xe4ldre med typ 2-diabetes och proteinuri (RENAAL-studien, se avsnitt 5.1) var de vanligast rapporterade l\xe4kemedelsrelaterade biverkningarna f\xf6r losartan f\xf6ljande'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'hypotoni'],
             ['General', u'asteni, tr\xf6tthet'],
             ['Investigations',
              u'hypoglykemi, hyperkalemi*** * I en klinisk studie p\xe5 patienter med typ 2-diabetes och nefropati utvecklades hyperkalemi >5,5 mmol/l hos 9,9% av patienterna som behandlades med losartantabletter och hos 3,4% av patienterna som behandlades med placebo. F\xf6ljande biverkningar f\xf6rekom oftare hos patienter som fick losartan \xe4n hos patienter som fick placebo']]],
           ['Uncommon',
            [['Nervous system', u'somnolens, huvudv\xe4rk, s\xf6mnst\xf6rningar'],
             ['Cardiac', u'palpitationer, angina pectoris'],
             ['Vascular',
              u'symtomatisk hypotoni (s\xe4rskilt hos patienter med minskad blodvolym t ex patienter med sv\xe5r hj\xe4rtsvikt eller kraftigt diuretikabehandlade patienter), dosrelaterade ortostatiska effekter, utslag'],
             ['GI', u'buksm\xe4rta, f\xf6rstoppning'],
             ['General', u'asteni, tr\xf6tthet, \xf6dem'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Respiratory', u'dyspn\xe9, hosta'],
             ['GI', u'diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'urtikaria, pruritus, utslag'],
             ['General', u'asteni, tr\xf6tthet'],
             ['Metabolism', u'hyperkalemi**']]],
           ['Rare',
            [['Investigations',
              u'f\xf6rh\xf6jt alaninaminotransferas (ALAT)* * (vanligen reversibla efter uts\xe4ttande) Hypertensiva patienter med v\xe4nsterkammarhypertrofi I en kontrollerad klinisk studie p\xe5 9193 hypertensiva patienter i \xe5ldern 55 till 80 \xe5r med v\xe4nsterkammarhypertrofi rapporterades f\xf6ljande biverkningar'],
             ['Nervous system', u'parestesier'],
             ['Cardiac', u'synkope, f\xf6rmaksflimmer, cerebrovaskul\xe4r h\xe4ndelse'],
             ['Immune system',
              u'\xf6verk\xe4nslighet anafylaktiska reaktioner, angio\xf6dem inkluderande svullnad av larynx och glottis orsakande luftv\xe4gsobstruktion och/eller svullnad av ansikte, l\xe4ppar, svalg och/eller tunga (vissa av patienterna som upplevde angio\xf6dem hade tidigare haft denna biverkning vid behandling med andra l\xe4kemedel inklusive ACE-h\xe4mmare), vaskulit inkluderande Henoch-Sch\xf6nleins purpura.'],
             ['Hepato', u'hepatit']]],
           ['Unknown',
            [['Blood', u'anemi'],
             ['Cardiac', u'synkope, palpitationer'],
             ['Vascular', u'ortostatisk hypotoni'],
             ['GI', u'diarr\xe9'],
             ['Musculoskeletal', u'ryggv\xe4rk'],
             ['Renal', u'urinv\xe4gsinfektion'],
             ['General',
              u'influensaliknande symtom Uppf\xf6ljning efter godk\xe4nnandet F\xf6ljande biverkningar har rapporterats efter godk\xe4nnandet'],
             ['Blood', u'anemi, trombocytopeni'],
             ['Ear', u'tinnitus'],
             ['Nervous system', u'migr\xe4n'],
             ['Respiratory', u'hosta'],
             ['GI', u'diarr\xe9, pankreatit'],
             ['General', u'sjukdomsk\xe4nsla'],
             ['Hepato', u'onormal leverfunktion'],
             ['Skin', u'urtikaria, pruritus, utslag, ljusk\xe4nslighet'],
             ['Musculoskeletal', u'myalgi, artralgi, rabdomyolys'],
             ['Reproductive system', u'erektil dysfunktion/impotens'],
             ['Psychiatric', u'depression'],
             ['Investigations', u'hyponatremi'],
             ['Renal',
              u'Som en f\xf6ljd av att man h\xe4mmar renin-angiotensin-aldosteronsystemet har f\xf6r\xe4ndringar i njurfunktionen inklusive njursvikt rapporterats hos riskpatienter, dessa njurfunktionsf\xf6r\xe4ndringar kan vara reversibla efter uts\xe4ttande av behandlingen (se avsnitt 4.4).']]]],
 '_pages': [6, 9],
 u'_rank': 50,
 u'_type': u'LSFU'}