{'_data': [['Common',
            [['Nervous system', u'yrsel, vertigo'],
             ['Nervous system', u'yrsel'],
             ['Ear', u'vertigo'],
             ['General',
              u'asteni/tr\xf6tthet Kronisk hj\xe4rtsvikt I en kontrollerad klinisk studie p\xe5 cirka 3900 patienter 20 \xe5r och \xe4ldre med hj\xe4rtsvikt rapporterades f\xf6ljande biverkningar'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'hypotoni'],
             ['General', u'asteni/tr\xf6tthet'],
             ['Investigations',
              u'hypoglykemi, hyperkalemi F\xf6ljande biverkningar f\xf6rekom oftare hos patienter som fick losartan \xe4n hos patienter som fick placebo']]],
           ['Uncommon',
            [['Nervous system', u'somnolens, huvudv\xe4rk, s\xf6mnst\xf6rningar'],
             ['Cardiac', u'palpitationer, angina pectoris'],
             ['Vascular',
              u'symtomatisk hypotoni (s\xe4rskilt hos patienter med minskad blodvolym t ex patienter med sv\xe5r hj\xe4rtsvikt eller kraftigt diuretikabehandlade patienter), dosrelaterade ortostatiska effekter, utslag'],
             ['GI', u'buksm\xe4rta, f\xf6rstoppning'],
             ['General', u'asteni, tr\xf6tthet, \xf6dem'],
             ['Nervous system', u'yrsel, huvudv\xe4rk'],
             ['Vascular', u'hypotoni inkluderande ortostatisk hypotoni'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'urtikaria, pruritus, utslag'],
             ['General', u'asteni/tr\xf6tthet'],
             ['Investigations',
              u'f\xf6rh\xf6jda v\xe4rden av urea i blodet, serumkreatinin och serumkalium har rapporterats. Hypertensiva patienter med typ 2-diabetes och njursjukdom I en kontrollerad klinisk studie p\xe5 1513 patienter 31 \xe5r och \xe4ldre med typ 2-diabetes och proteinuri (RENAAL-studien, se avsnitt 5.1) var de vanligast rapporterade l\xe4kemedelsrelaterade biverkningarna f\xf6r losartan f\xf6ljande']]],
           ['Rare',
            [['Nervous system', u'parestesier'],
             ['Cardiac', u'synkope, f\xf6rmaksflimmer, cerebrovaskul\xe4r h\xe4ndelse'],
             ['Immune system',
              u'\xf6verk\xe4nslighet anafylaktiska reaktioner, angio\xf6dem inkluderande svullnad av larynx och glottis orsakande luftv\xe4gsobstruktion och/eller svullnad av ansikte, l\xe4ppar, svalg och/eller tunga (vissa av patienterna som upplevde angio\xf6dem hade tidigare haft denna biverkning vid behandling med andra l\xe4kemedel inklusive ACE-h\xe4mmare); vaskulit inkluderande Henoch-Sch\xf6nleins purpura'],
             ['Hepato', u'hepatit']]],
           ['Unknown',
            [['Investigations',
              u'I kontrollerade kliniska studier var kliniskt betydelsefulla f\xf6r\xe4ndringar av standardparametrar s\xe4llan f\xf6renade med administrering av losartantabletter. F\xf6rh\xf6jda v\xe4rden av ALAT f\xf6rekom s\xe4llan och var vanligen reversibla efter uts\xe4ttande av behandling. Hyperkalemi (serumkalium >5,5 mmol/l) f\xf6rekom hos 1,5% av patienter som deltog i hypertonistudier. Hypertensiva patienter med v\xe4nsterkammarhypertrofi I en kontrollerad klinisk studie p\xe5 9193 hypertensiva patienter i \xe5ldern 55 till 80 \xe5r med v\xe4nsterkammarhypertrofi rapporterades f\xf6ljande biverkningar'],
             ['Blood', u'anemi'],
             ['Cardiac', u'synkope, palpitationer'],
             ['Vascular', u'ortostatisk hypotoni'],
             ['GI', u'diarr\xe9'],
             ['Musculoskeletal', u'ryggv\xe4rk'],
             ['Renal', u'urinv\xe4gsinfektion'],
<<<<<<< HEAD
=======
             ['General', u'influensaliknande symtom'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Investigations',
              u'I en klinisk studie p\xe5 patienter med typ 2-diabetes och nefropati utvecklades hyperkalemi >5,5 mmol/l hos 9,9% av patienterna som behandlades med losartantabletter och hos 3,4% av patienterna som behandlades med placebo. Uppf\xf6ljning efter godk\xe4nnandet F\xf6ljande biverkningar har rapporterats efter godk\xe4nnandet'],
             ['Blood', u'anemi, trombocytopeni'],
             ['Ear', u'tinnitus'],
             ['Nervous system', u'migr\xe4n'],
             ['Respiratory', u'hosta'],
             ['GI', u'diarr\xe9, pankreatit'],
<<<<<<< HEAD
=======
             ['General', u'sjukdomsk\xe4nsla'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Hepato', u'onormal leverfunktion'],
             ['Skin', u'urtikaria, pruritus, utslag, ljusk\xe4nslighet'],
             ['Musculoskeletal', u'myalgi, artralgi, rabdomyolys'],
             ['Reproductive system', u'erektil dysfunktion/impotens'],
             ['Renal',
              u'Som en f\xf6ljd av att man h\xe4mmar renin-angiotensin-aldosteronsystemet har f\xf6r\xe4ndringar i njurfunktionen inklusive njursvikt rapporterats hos riskpatienter, dessa njurfunktionsf\xf6r\xe4ndringar kan vara reversibla efter uts\xe4ttande av behandlingen (se avsnitt 4.4).'],
             ['Psychiatric', u'depression'],
             ['Investigations',
              u'hyponatremi Barn Biverkningsprofilen hos barn liknar biverkningsprofilen hos vuxna patienter. Data p\xe5 barn \xe4r begr\xe4nsad.']]]],
 '_pages': [5, 9],
<<<<<<< HEAD
 u'_rank': 44,
=======
 u'_rank': 46,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}