{'_data': [[u'Unknown',
            [['Investigations', u'\xd6kade leverenzymer   Nedsatt urinsyra i blodet'],
             ['Nervous system', u'Ataxi   Mental neds\xe4ttning   Parestesi   Polyneuropati'],
             ['Eye', u'Makulopati'],
             ['GI', u'Mukosit   Hypersekretion av saliv'],
             ['Renal', u'Hemorragisk cystit'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'Myasteni'],
             ['Endocrine', u'Binjureinsufficiens   Nedsatt'],
             ['Metabolism', u'Anorexia   Hypouricemi   Hyperkolesterolemi'],
             ['Infections', u'Opportunistisk mykos'],
             ['Vascular', u'Hypertension'],
             ['General', u'Asteni   Hyperpyrexi'],
             ['Hepato', u'Autoimmun hepatit   Leverskada'],
             ['Reproductive system', u'Gynekomasti'],
             ['Psychiatric', u'F\xf6rvirring']]]],
 '_pages': [5, 6],
 u'_rank': 15,
 u'_type': u'LFSU'}