{'_data': [['Very common',
            [['Eye',
              u'Inflammation i fr\xe4mre kammaren, \xf6gonsm\xe4rta, \xf6kat intraokul\xe4rt tryck, punktuell keratit, glaskroppsgrumlingar.']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk.'],
             ['Eye',
              u'Onormal k\xe4nsla i \xf6gat, katarakt, konjunktival bl\xf6dning, konjunktival hyperemi, konjunktivalt \xf6dem, konjunktivit, korneal dystrofi, korneal epiteldefekt, korneal epitelst\xf6rning, kornealt \xf6dem, torra \xf6gon, endoftalmit, rinnande \xf6ga, \xf6goninflammation, \xf6gonirritation, \xf6gonkl\xe5da, \xf6gonrodnad, \xf6gonsvullnad, \xf6gonlocks\xf6dem, \xf6kat t\xe5rfl\xf6de, makuladegeneration, mydriasis, okul\xe4ra besv\xe4r, okul\xe4r hypertoni, periorbitalt hematom, fotofobi, fotopsi, retinal bl\xf6dning, dimsyn, minskad synsk\xe4rpa, synst\xf6rning, glaskroppsavlossning och glaskroppsf\xf6r\xe4ndring.'],
             ['Vascular', u'Rinorr\xe9.']]],
           ['Uncommon',
            [['Psychiatric', u'Mardr\xf6mmar, depression.'],
             ['Eye',
              u'Astenopi, blefarit, allergisk konjunktivit, korneala inlagringar, \xf6gonbl\xf6dning, \xf6gonlockskl\xe5da, keratit, glaskroppsbl\xf6dning, nedsatt pupillreflex, kornealabrasion, retinala exsudat, \xf6gonlocksptos, retinalt \xe4rr, chalazion, kornealerosion, minskat intraokul\xe4rt tryck, reaktion vid injektionsst\xe4llet, bl\xe5sbildning p\xe5 injektionsst\xe4llet, n\xe4thinneavlossning, retinal art\xe4rocklusion, retinal ruptur, ektropion, st\xf6rning i \xf6gonr\xf6relserna, \xf6gonlocksirritation, hyphema, f\xf6r\xe4ndringar i hornhinnan, pupillen eller iris, okul\xe4r ikterus, fr\xe4mre uveit, skr\xe4p p\xe5 \xf6gats yta, irit, papillexkavation, pupilldeformitet, retinal venocklusion och glaskroppsprolaps.'],
             ['Ear', u'D\xf6vhet, f\xf6rs\xe4mring av M\xe9ni\xe8res sjukdom, yrsel.'],
             ['Cardiac', u'Palpitationer.'],
             ['Vascular',
              u'Hypertoni, aortaaneurysm. Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Nasofaryngit.'],
             ['GI', u'Kr\xe4kningar, dyspepsi.'],
             ['Skin',
              u'Kontaktdermatit, eksem, f\xf6r\xe4ndrad h\xe5rf\xe4rg, utslag, pruritus, nattsvettningar.'],
             ['Skin',
              u'Ryggont. Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Skin',
              u'Tr\xf6tthet, stelhet, \xf6mhet, br\xf6stsm\xe4rta, influensaliknande sjukdom.'],
             ['Investigations',
              u'\xd6kad gammaglutamyltransferasaktivitet. Skador, f\xf6rgiftningar och behandlingskomplikationer'],
             ['Investigations',
              u'abrasion * Erfarenheter efter lanseringen: Fall av anafylaxi/anafylaktiska reaktioner, inklusive angio\xf6dem, har rapporterats hos patienter inom flera timmar efter administrering av pegaptanib tillsammans med de olika medicinska produkter som getts under f\xf6rberedelserna f\xf6r injektionen (se avsnitt 4.2 och 4.4). Fall av betydande \xf6kat intraokul\xe4ra tryck har rapporterats d\xe5 \xf6verskottsvolymen i den f\xf6rfyllda sprutan inte var avl\xe4gsnat f\xf6re injektion.']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk reaktion.*'],
             ['Skin', u'Angio\xf6dem.* Muskuloskeletala systemet och bindv\xe4v']]]],
 '_pages': [4, 6],
 u'_rank': 18,
 u'_type': u'LSFU'}