{'_data': [['Uncommon',
            [['Nervous system', u'Yrsel Huvudv\xe4rk Dysgeusi'],
             ['GI', u'Kr\xe4kningar Illam\xe5ende'],
             ['General',
              u'Sm\xe4rta V\xe4rmek\xe4nsla Frusenhet Reaktioner vid injektionsst\xe4llet (t.ex. k\xe4nsla av frusenhet, parestesi, svullnad, v\xe4rmek\xe4nsla, sm\xe4rta, \xf6dem, irriation, bl\xf6dning, erytem, olustk\xe4nsla, nekros\xa7, tromboflebit\xa7, flebit\xa7, inflammation\xa7, extravasation\xa7)']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreak-tioner /anafylaktisk reaktion (t.ex. anafylaktisk chock*), anafylaktoid reaktion\xa7*, \xd6verk\xe4nslighetsreak-tioner\xa7*, chock\xa7*, hypotension\xa7*, konjunktivit, medvetandef\xf6rlust\xa7*, tr\xe4ngda andningsv\xe4gar*, nysningar, urtikaria, pruritus, utslag, erytem, dyspn\xe9,*, andningsuppeh\xe5ll*, bronkospasm\xa7*, pipande andning, laryngospasm\xa7*, laryngealt \xf6dem,\xa7*, paryngealt \xf6dem\xa7*, cyanos\xa7*, rinit\xa7. angio\xf6dem\xa7*, ansikts\xf6dem*, reflextakykardi\xa7)'],
             ['Psychiatric', u'Desorientering'],
             ['Nervous system', u'Kramper* Parestesi Br\xe4nnande k\xe4nsla Tremor'],
             ['Cardiac', u'Takykardi* Arrytmi'],
             ['Vascular', u'Tromboflebit Rodnad Vasodilatation'],
             ['Respiratory', u'Halsirritation Faryngolaryngeal sm\xe4rta/Svalgbesv\xe4r Hosta'],
             ['GI',
              u'Buksm\xe4rta Magbesv\xe4r Diarr\xe9 Tandv\xe4rk Muntorrhet Sm\xe4rta i orala mjukdelar och parestesi'],
             ['Musculoskeletal', u'Sm\xe4rta i extremitet'],
             ['General',
              u'Br\xf6stsm\xe4rta Pyrexi Perifert \xf6dem Obehagsk\xe4nsla Tr\xf6tthet T\xf6rst Asteni']]],
           ['Unknown',
            [['Blood', u'\xd6kade niv\xe5er av serumj\xe4rn*'],
             ['Psychiatric', u'Agitation F\xf6rvirring'],
             ['Nervous system', u'Koma* Somnolens* Problem med talet Parosmi'],
             ['Ear', u'Nedsatt h\xf6rsel \xd6ronsm\xe4rta'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd* Minskad hj\xe4rtfrekvens/bradykardi'],
             ['Vascular', u'Synkope* Vasovagal reaktion F\xf6rh\xf6jt blodtryck'],
             ['Respiratory',
              u'Andn\xf6d \xd6kad eller minskad andningsfrekvens Pulmonellt \xf6dem/lung\xf6dem'],
             ['GI', u'Salivavs\xf6ndring'],
             ['Skin', u'Nefrogen systemisk fibros (NSF)*'],
             ['Musculoskeletal', u'Ryggsm\xe4rta Artralgi'],
             ['Renal',
              u'Akut njursvikt*, ** \xd6kat serumkreatinin** Urin\xe4r inkontinens T\xe4ta tr\xe4ngningar'],
             ['General', u'Rysningar Svettningar \xd6kad eller s\xe4nkt kroppstemperatur']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 9],
 u'_rank': 24,
 u'_type': u'MSFU'}