{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende Kr\xe4kningar Diarr\xe9 Magsm\xe4rtor']]],
           ['Common',
            [['Blood', u'Anemi Neutropeni'],
             ['Immune system', u'Allergiska reaktioner'],
             ['Metabolism', u'Hyponatremi Anorexi'],
             ['Psychiatric', u'Onormala dr\xf6mmar Depression'],
             ['Nervous system', u'Insomni Yrsel'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzym-niv\xe5er'],
             ['Skin', u'Kl\xe5da Utslag'],
             ['General', u'Feber'],
             ['Respiratory', u'Hosta']]],
           ['Uncommon',
            [['Metabolism', u'F\xf6rh\xf6jda amylasniv\xe5er'],
             ['Psychiatric', u'\xc5ngest'],
             ['Cardiac', u'Hj\xe4rtklappning Takykardi'],
             ['GI', u'Stomatit'],
             ['Skin', u'H\xe5ravfall Urtikaria']]],
           ['Unknown',
            [['Blood', u'Pancytopeni'],
             ['Immune system', u'Angio\xf6dem Anafylaxi (se avsnitt 4.4) Vaskulit'],
             ['Psychiatric', u'Panikattack Gr\xe5t Hallucinationer Mardr\xf6mmar'],
             ['Nervous system', u'Kramper'],
             ['GI', u'Gastrointestinal intolerans S\xe5r i munh\xe5lan'],
             ['Hepato', u'Hepatit Kolestas'],
             ['Skin',
              u'Steven-Johnsons syndrom Erythema multiforme Bl\xe5sa Hudexfoliation Fotosensitivitetsreaktioner']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 23,
 u'_type': u'MSFU'}