{'_data': [['Very common',
            [['Nervous system', u'Somnolens, yrsel, huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, f\xf6rstoppning']]],
           ['Common',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'Insomni, depression, \xe5ngest, f\xf6rvirring, hallucination'],
             ['Nervous system', u'Tremor, parestesier'],
             ['Ear', u'Svindel'],
             ['Cardiac', u'Palpitationer, takykardi'],
             ['Vascular', u'Hypertension'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI',
              u'Diarr\xe9, muntorrhet, buksm\xe4rta, sm\xe4rtor i \xf6vre delen av buken, dyspepsi'],
             ['Skin', u'Hyperhidros, pruritus, hudutslag, erytem'],
             ['Musculoskeletal', u'Muskelkramper'],
             ['Renal', u'Urinretention'],
             ['General',
              u'Tr\xf6tthet, perifera \xf6dem, asteni, sjukdomsk\xe4nsla, k\xf6ldk\xe4nsla']]],
           ['Uncommon',
            [['Psychiatric', u'Agitation, desorientering, eufori'],
             ['Nervous system',
              u'Hypestesi, kramper (inklusive kloniska kramper och grand mal), amnesi'],
             ['Cardiac', u'Bradykardi, cyanos'],
             ['Vascular', u'Hypotension'],
             ['Respiratory', u'Andnings-depression, andnings-sv\xe5righeter'],
             ['GI', u'Ileus'],
             ['Skin', u'Eksem, allergisk dermatit, hud\xe5komma, dermatit, kontaktdermatit'],
             ['Musculoskeletal', u'Muskel-samman-dragningar'],
             ['Reproductive system', u'Erektil dysfunktion, sexuell dysfunktion'],
             ['General',
              u'Reaktion vid administreringss t\xe4llet, influensa-liknande sjukdom, k\xe4nsla av \xe4ndring i kropps-temperatur, \xf6verk\xe4nslighet Biverkningar']]],
           ['Rare',
            [['Eye', u'Mios'],
             ['Respiratory', u'Apn\xe9, hypo-ventilation'],
             ['GI', u'Subileus'],
             ['General',
              u'Dermatit vid administrerings-st\xe4llet, eksem vid admini-streringsst\xe4llet']]],
           ['Unknown',
            [['Immune system',
              u'Anafylaktisk chock, anafylaktisk reaktion, anafylaktoid reaktion'],
             ['Respiratory', u'Bradypn\xe9']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 30,
 u'_type': u'MSFU'}