{'_data': [['Very common', []],
           ['Common',
            [['Nervous system', u'Yrsel eufori Uttalad'], ['GI', u'Illam\xe5ende, kr\xe4kning']]],
           ['Uncommon',
            [['Nervous system', u'tr\xf6tthet'],
             ['Ear', u'Tryckk\xe4nsla i mellan\xf6rat'],
             ['GI', u'Uppbl\xe5sthet, \xf6kad gasvolym i tarmarna']]],
           ['Rare', []],
           ['Very rare', [['Nervous system', u'Polyneuropati parapares och myelopati,']]],
           ['Unknown',
            [['Blood', u'Megaloblastisk anemi leukopeni,'],
             ['Psychiatric', u'Psykos, f\xf6rvirring, oro'],
             ['Nervous system', u'Andningsdepre ssion, huvudv\xe4rk'],
             ['Respiratory', u'Andningsdepre ssion,']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 10,
 u'_type': u'MSFU'}