{'_data': [['Common',
            [['Infections',
              u'Infektionsf\xf6rsvaret h\xe4mmas, infektioner, t ex tuberkulos, kan aktiveras'],
             ['Endocrine',
              u'H\xe4mning av endogen ACTH- och kortisoluts\xf6ndring, Cushing-liknande symtombild, amenorr\xe9, tillv\xe4xth\xe4mning hos barn, osteoporos, muskel- och hudatrofi med f\xf6rs\xe4mrad s\xe5rl\xe4kning. Diabetes mellitus kan f\xf6rs\xe4mras och latent diabetes bli manifest.'],
             ['Metabolism', u'Hypokalemi, natriumretention med \xe5tf\xf6ljande \xf6dem']]],
           ['Uncommon',
            [['Blood', u'\xd6kad koagulationsben\xe4genhet kan ge tromboskomplikationer'],
             ['Psychiatric', u'Psykiska rubbningar kan aktiveras'],
             ['Eye', u'Katarakt, glaukom'],
             ['Vascular', u'Hypertension']]],
           ['Rare',
            [['Immune system', u'Anafylaxiliknande reaktioner'],
             ['Nervous system',
              u'\xd6kat intrakraniellt tryck (med papill\xf6dem, benign intrakraniell hypertension)'],
             ['GI', u'Ulcus pepticum (med m\xf6jlig performation och bl\xf6dning)'],
             ['Skin', u'Allergisk dermatit, kontaktdermatit, angio\xf6dem'],
             ['Musculoskeletal', u'Aseptisk bennekros, senruptur (speciellt h\xe4lsenan)']]],
           ['Unknown',
            [['Infections', u'Opportunistiska infektioner'],
             ['Immune system',
              u'L\xe4kemedelsreaktion (inkluderande anafylatisk chock), nedsatt reaktion p\xe5 hudtest'],
             ['Metabolism', u'Hypokalemiskt alkalos,'],
             ['Psychiatric',
              u'Beteendest\xf6rningar, k\xe4nslom\xe4ssiga symtom (inklusive affektlabilitet, nedst\xe4mdhet, eufori, psykiskt beroende, sj\xe4lvmordstankar), oro, f\xf6rvirring, kognitiv dysfunktion, amnesi, Systemorganklass Biverkningar s\xf6mnst\xf6rningar, irritabilitet, hum\xf6rsv\xe4ngningar, personlighetsf\xf6r\xe4ndring, psykotisk st\xf6rning, (inklusive mani, vanf\xf6rest\xe4llningar, hallucination och f\xf6rv\xe4rrad schizofreni)'],
             ['Nervous system', u'Kramp, yrsel, huvudv\xe4rk'],
             ['Eye', u'Exoftalmus'],
             ['Cardiac', u'Hj\xe4rtsvikt (k\xe4nsliga patienter)'],
             ['Respiratory', u'Hicka'],
             ['GI',
              u'Uppsv\xe4lldhet, dyspepsi, tarm performation, illam\xe5ende, (ulcerativ) esofagit, pankreatit'],
             ['Skin',
              u'Acne, erytem, hirsutism, hyperhidros, petekier, ekkymoser, pruritus, hudatrofi, striae, utikaria'],
             ['Musculoskeletal',
              u'Muskelsvaghet, myopati, patologiska frakturer, kompressionsfrakturer.'],
             ['Reproductive system',
              u'Oregelbunden menstruation Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Investigations',
              u'\xd6kning av kalcium i urinen Abstinens symtom kan uppkomma vid abrupt uts\xe4ttande av glukokortikoider utan relation till binjurebarkssvikt. Symtom s\xe5 som anorexi, illam\xe5ende, kr\xe4kning, letargi, huvudv\xe4rk, feber, ledsm\xe4rta, fj\xe4llning av huden, myalgi, viktminskning, och/eller hypotension kan uppkomma. Dessa effekter anses vara beroende av pl\xf6tslig f\xf6r\xe4ndring i glukokortikoidkoncentration snarare \xe4n av l\xe5ga kortikosteroid niv\xe5er.']]]],
 '_pages': [5, 6],
 u'_rank': 25,
 u'_type': u'LSFU'}