{'_data': [['Common',
            [['Skin', u'ill \xd6verg\xe5ende'], ['Skin', u'hypopigmentering/hyperpigmentering']]],
           ['Uncommon', [['Skin', u'Uppflammande dermatit till \u22641/100)']]],
           ['Rare',
            [['Skin',
              u'Sensibilisering \u2264 1/1000) Irritation orsakad av klistret i pl\xe5stret upph\xf6r snabbt. En positiv testreaktion f\xf6rsvinner vanligtvis inom 1-2 veckor. L\xe5ngvariga reaktioner \xe4r positiva reaktioner som kan kvarst\xe5 i flera veckor eller m\xe5nader. En positiv testreaktion kan efterl\xe4mna ett omr\xe5de med \xf6verg\xe5ende hypopigmentering/hyperpigmentering vid appliceringsst\xe4llet. Uppflammande dermatit kan observeras om testet utf\xf6rs under dermatitens aktiva fas. Sensibilisering, se avsnitt 4.4 (Varningar och f\xf6rsiktighet).']]],
           ['Unknown', [['Skin', u'irritation orsakad av klistret i pl\xe5stret']]]],
 '_pages': [4, 4],
 u'_rank': 5,
 u'_type': u'LSFU'}