{'_data': [['Very common',
            [['GI',
              u'Dyspepsi, illam\xe5ende, kr\xe4kningar, magsm\xe4rtor, f\xf6rstoppning, uppk\xf6rdhet, diarr\xe9.']]],
           ['Common', [['Blood', u'Anemi'], ['Nervous system', u'Yrsel, huvudv\xe4rk']]],
           ['Uncommon',
            [['Immune system',
              u'allergiska reaktioner, f\xf6rutom anafylaktiska eller anafylaktoida reaktioner.'],
             ['Nervous system', u'tr\xf6tthet, somnolens.'],
             ['Ear', u'Vertigo.'],
             ['Vascular',
              u'F\xf6rh\xf6jt blodtryck (se avsnitt 4.4), v\xe4rmevallningar med rodnad'],
             ['GI',
              u'Ockult eller makroskopisk gastrointestinal bl\xf6dning, stomatit, gastrit, rapningar.'],
             ['Hepato',
              u'Leverfunktionst\xf6rning (t ex f\xf6rh\xf6jda niv\xe5er av transaminaser eller bilirubin).'],
             ['Skin', u'Angio\xf6dem, kl\xe5da, hudutslag.'],
             ['Renal',
              u'Natrium- och v\xe4tskeretention, hyperkalemi (se avsnitt 4.4 och avsnitt 4.5)'],
             ['General', u'\xd6dem inklusive ankel\xf6dem.'],
             ['Investigations',
              u'\xd6verg\xe5ende st\xf6rning i leverfunktionsv\xe4rden (t.ex. f\xf6rh\xf6jda transaminaser eller bilirubin). Avvikelser i laboratoriev\xe4rden som m\xe4ter njurfunktion (t.ex. f\xf6rh\xf6jt kreatinin eller urea). c) Information betr\xe4ffande allvarliga och/eller ofta f\xf6rekommande biverkningar']]],
           ['Rare',
            [['Blood',
              u'F\xf6r\xe4ndringar av blodkropparna (inklusive differentialr\xe4kning av vita blodkroppar), leukopeni, trombocytopeni.'],
             ['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndring, s\xf6mnl\xf6shet och mardr\xf6mmar'],
             ['Eye', u'Synst\xf6rningar inklusive dimsyn, konjunktivit.'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac', u'Palpitationer'],
             ['Respiratory',
              u'Astma hos individer som \xe4r allergiska mot acetylsalicylsyra eller andra NSAID.'],
             ['GI', u'Kolit, gastroduodenals\xe5r, esofagit.'],
             ['Skin', u'Stevens-Johnsons syndrom, toxisk epidermal nekrolys, urtikaria.']]],
           ['Very rare',
            [['Blood', u'fall av agranulocytos har rapporterats (se avsnitt c).'],
             ['GI',
              u'Gastrointestinal perforation. Gastrointestinal bl\xf6dning, ulceration eller perforation kan ibland vara allvarliga och potentiellt livshotande, s\xe4rskilt hos \xe4ldre (se avsnitt 4.4).'],
             ['Hepato', u'Hepatit'],
<<<<<<< HEAD
             ['Skin', u'Bull\xf6sa utslag, erythema multiforme.'],
             ['Renal', u'Akut njursvikt hos patienter med riskfaktorer (se avsnitt 4.4)']]],
           ['Unknown',
            [['Immune system', u'anafylaktiska/anafylaktoida reaktioner.'],
             ['Psychiatric', u'f\xf6rvirringstillst\xe5nd, desorientering.'],
             ['Skin', u'Fotosensibilisering.']]]],
 '_pages': [7, 9],
 u'_rank': 29,
=======
             ['Skin', u'Bull\xf6sa utslag, erythema multiforme. Fotosensibilisering.'],
             ['Renal', u'Akut njursvikt hos patienter med riskfaktorer (se avsnitt 4.4)']]],
           ['Unknown',
            [['Immune system', u'anafylaktiska/anafylaktoida reaktioner.'],
             ['Psychiatric', u'f\xf6rvirringstillst\xe5nd, desorientering.']]]],
 '_pages': [7, 9],
 u'_rank': 28,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}