{'_data': [['Common',
            [['Blood', u'Anemi'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI',
              u'Dyspepsi, illam\xe5ende och kr\xe4kningar, buksm\xe4rta, f\xf6rstoppning, flatulens, diarr\xe9.'],
             ['Skin', u'Kl\xe5da, utslag'],
             ['General', u'\xd6dem inklusive ankel\xf6dem']]],
           ['Uncommon',
            [['Blood',
              u'F\xf6r\xe4ndrad differentialblodbild leukocytopeni; trombocytopeni; agranulocytos (se avsnitt c)'],
             ['Nervous system', u'Vertigo, tinnitus, d\xe5sighet'],
             ['Cardiac', u'Hj\xe4rtklappning, hj\xe4rtsvikt'],
             ['Vascular', u'H\xf6gt blodtryck (se avsnitt 4.4), flush'],
             ['GI',
              u'Gastrointestinal bl\xf6dning, gastroduodenala s\xe5r, esofagit, stomatit, .'],
             ['Skin', u'Urtikaria'],
             ['Renal',
              u'Natrium och v\xe4tskeretention, hyperkalemi (se avsnitt 4.4 och avsnitt 4.5)'],
             ['Investigations',
              u'\xd6verg\xe5ende f\xf6rh\xf6jning av leverfunktionsv\xe4rden (t ex transaminaser eller bilirubin). Avvikande njurfunktionsv\xe4rden (t ex f\xf6rh\xf6jda serumkreatinin- eller serumureav\xe4rden). c) Information betr\xe4ffande allvarliga och/eller ofta f\xf6rekommande biverkningar']]],
           ['Rare',
            [['Immune system', u'Anafylaktisk/anafylaktoid reaktion'],
             ['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndring, s\xf6mnl\xf6shet, mardr\xf6mmar'],
             ['Nervous system', u'F\xf6rvirring'],
             ['Eye', u'Synst\xf6rningar inklusive dimsyn'],
             ['Respiratory',
              u'Akut astma hos vissa individer med allergi mot acetylsalicylsyra eller andra NSAID.'],
             ['GI',
              u'Gastrointestinal perforation, gastrit, kolit Gastrointestinals\xe5r, perforation eller gastrointestinal bl\xf6dning kan ibland vara sv\xe5r, i synnerhet hos \xe4ldre (se avsnitt 4.4).'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Stevens-Johnsons syndrom, toxisk epidermal nekrolys, angio\xf6dem, bull\xf6sa reaktioner s\xe5som erythema multiforme, fotosensibilisering'],
             ['Renal', u'Akut njursvikt hos patienter med riskfaktorer (se avsnitt 4.4)']]]],
 '_pages': [7, 9],
 u'_rank': 22,
 u'_type': u'LSFU'}