{'_data': [['Common',
            [['GI', u'Magsm\xe4rta, illam\xe5ende, uppsv\xe4lld buk'],
             ['General', u'Reaktioner/sm\xe4rta vid injektionsst\xe4llet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Reproductive system', u'OHSS, b\xe4ckensm\xe4rta']]],
           ['Uncommon', [['Vascular', u'Djup ventrombos']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 5],
 u'_rank': 5,
 u'_type': u'MSFU'}