{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'illam\xe5ende'],
             ['Musculoskeletal', u'myalgi'],
             ['General',
              u'sm\xe4rta vid injiceringsst\xe4llet, erytem vid injiceringsst\xe4llet (<50 mm), induration vid injiceringsst\xe4llet (\u226450 mm), olustk\xe4nslor']]],
           ['Common',
            [['Skin', u'utslag'],
             ['Musculoskeletal', u'artralgi'],
             ['General',
              u'erytem vid injiceringsst\xe4llet (>50 mm), induration vid injiceringsst\xe4llet (>50 mm), feber \u226538\xb0C, frossa']]],
           ['Uncommon',
            [['Nervous system', u'yrsel'], ['General', u'kl\xe5da vid injiceringsst\xe4llet']]],
           ['Rare',
            [['Immune system', u'hypersensitivitet*'],
             ['Nervous system', u'synkope*'],
             ['Ear', u'yrsel*'],
             ['General',
              u'cellulit vid injiceringsst\xe4llet* population av ok\xe4nd storlek har frekvensen ber\xe4knats utifr\xe5n data fr\xe5n kliniska pr\xf6vningar) I \xe5ldersgruppen ungdomar, var s\xe4kerheten och toleransen f\xf6r vaccinet gynnsamt relativt Tdap, och \xe4ndrades inte i n\xe5gon h\xf6gre grad med samtidig eller efterf\xf6ljande administrering av andra vacciner.']]]],
 '_pages': [5, 6],
 u'_rank': 13,
 u'_type': u'LSFU'}