{'_data': [['Common',
            [['Cardiac', u'(>1/100, <1/10) Bradykardi, men hos vissa patienter takykardi.'],
             ['Eye',
              u'Mios, \xf6kad t\xe5rsekretion, dimsyn, konjuktivit. Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Eye', u'Vanlig (>1/100, <1/10) Hypersekretion, bronkospasm, rinit.'],
             ['GI',
              u'Vanlig (>1/100, <1/10 )Illa m\xe5ende, uppst\xf6tningar, kr\xe4kningar, diarr\xe9, \xf6kad peristaltik, buksm\xe4rtor,\xf6kad salivation.'],
             ['Vascular', u'(\u22651/100, <1/10)']]],
           ['Uncommon',
            [['Cardiac', u'>1/1 000, <1/100)'],
             ['Vascular',
              u'Hyper- eller hypotension Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet Hyperhidros, anorexi'],
             ['Vascular', u'mindre vanlig (>1/1 000, <1/100) Yrsel']]],
           ['Rare', [['Skin', u'Exantem, h\xe5ravfall, vid l\xe5ngvarig anv\xe4ndning.']]],
           ['Very rare',
            [['Cardiac',
              u'AV-block. Centrala och perifera nervsystemet Muskelsvaghet, muskelpares, kramper, anlig (>1/1 000, <1/100) V fascikulationer Rastl\xf6shet, insomnia.'],
             ['Immune system', u'Mycket s\xe4llsynt (< 1/10 000) Urtikaria']]],
           ['Unknown', [['Renal', u'Inkontinens']]]],
 '_pages': [2, 4],
 u'_rank': 12,
 u'_type': u'LSFU'}