{'_data': [['Very common', [['GI', u'illam\xe5ende, kr\xe4kningar']]],
           ['Common',
            [['Metabolism', u'v\xe4tskeretention'],
             ['Psychiatric', u'eufori, hallucinationer'],
             ['Eye', u'dimsyn, mios'],
             ['Ear', u'svindel'],
             ['GI', u'f\xf6rstoppning'],
             ['General', u'tr\xf6tthet  \xf6dem'],
             ['Investigations', u'viktuppg\xe5ng']]],
           ['Uncommon',
            [['Metabolism', u'anorexi'],
             ['Psychiatric',
              u'dysfori, agitation, insomnia,  f\xf6rvirring, nedsatt libido beroende,'],
             ['Nervous system', u'huvudv\xe4rk,syncope'],
             ['Vascular', u'ansiktsrodnad, hypotension'],
             ['GI', u'muntorrhet, inflammation  av tungan'],
             ['Hepato', u'gallv\xe4gsdyskinesi,'],
             ['Hepato',
              u'kl\xe5da, urtikaria, andra utslag  och i mycket s\xe4llsynta fall bl\xf6dande urtikaria'],
             ['Renal', u'urinretention, antidiuretisk  effekt'],
             ['Reproductive system', u'minskad potens och']]],
           ['Rare',
            [['Cardiac',
              u'ventrikul\xe4r arytmi - VF, VT,  bradykardi,, hj\xe4rtklappning med fall av f\xf6rl\xe4ngt QT- intervall och "torsade de pointes" har rapporterats vid behandling med metadon, speciellt vid h\xf6ga doser']]],
           ['Unknown',
            [['Blood',
              u'reversibel tromocytpeni har  rapporterats hos opiodbehandlade patienter med kronisk hepatit'],
             ['Metabolism', u'hyopkalemi, hypomagnesi'],
             ['Psychiatric', u'hum\xf6rssv\xe4ngningar'],
             ['Cardiac', u'pl\xf6tslig of\xf6rklarlig d\xf6d och  hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'postural hypotension'],
             ['GI', u'smakst\xf6rningar'],
             ['General', u'hypotermi']]]],
 '_pages': [5, 7],
 u'_rank': 25,
 u'_type': u'TSFU'}