{'_data': [['Very common', [['GI', u'Illam\xe5ende, kr\xe4kningar']]],
           ['Common',
            [['Investigations', u'Vikt\xf6kning'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['GI', u'F\xf6rstoppning'],
             ['Psychiatric', u'Eufori, hallucinationer'],
             ['Ear', u'Vertigo'],
             ['Eye', u'Dimsyn, mios'],
             ['Nervous system', u'Sedation'],
             ['Skin', u'\xd6verg\xe5ende hudutslag, svettningar'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Metabolism', u'Anorexi'],
             ['Respiratory', u'Lung\xf6dem, andningssvikt'],
             ['GI', u'Munntorrhet, glossit'],
             ['Psychiatric', u'Dysfori, agitation, insomni, desorientering,  reducerad libido'],
             ['Nervous system', u'Huvudv\xe4rk, synkope'],
             ['Skin', u'Pruritus, urtikari, andra hudutslag och i'],
             ['General', u'\xd6dem i nedre extremiteter, asteni, \xf6dem'],
             ['Hepato', u'Gallv\xe4gsdyskinesi'],
             ['Vascular', u'Ansiktsrodnad, hypotoni'],
             ['Renal', u'Urinretention och antidiuretisk effekt'],
             ['Reproductive system', u'Reducerad potens och ammenorr\xe9']]],
           ['Rare',
            [['Cardiac',
              u'Bradykardi, palpitationer, fall av f\xf6rl\xe4ngt  QT-intervall och torsades de pointes har rapporterats vid metadonbehandling, s\xe4rskilt med h\xf6ga doser.']]],
           ['Unknown',
            [['Metabolism', u'Hypokalemi, hypomagnesemi'],
             ['Blood', u'Reversibel trombocytopeni har rapportertas']]]],
 '_pages': [6, 7],
 u'_rank': 24,
 u'_type': u'TSFU'}