{'_data': [['Common', [['GI', u'Illam\xe5ende, kr\xe4kningar.   (>1/100)']]],
           ['Uncommon',
            [['General',
              u'Minskad libido, sedering, s\xf6mn- och aptitl\xf6shet, svettning,   (1/100-1/1000) yrsel.'],
             ['Nervous system', u'Andningsdepression, eufori.'],
             ['GI', u'Obstipation.'],
             ['Respiratory', u'Lung\xf6dem (efter h\xf6ga doser).'],
             ['Other', u'Gallv\xe4gsdyskinesi.']]],
           ['Rare', [['Vascular', u'QT-f\xf6rl\xe4ngning, torsades de pointes   (<1/1000)']]]],
 '_pages': [4, 4],
 u'_rank': 7,
 u'_type': u'LFSUR'}