{'_data': [['Very common',
            [['GI',
<<<<<<< HEAD
              u'Gastrointestinala symtom som till exempel illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rtor och aptitl\xf6shet. Dessa biverkningar upptr\xe4der oftast vid start av behandlingen och upph\xf6r spontant i de flesta fallen. F\xf6r att f\xf6rebygga dessa gastrointestinala symtom rekommenderas det att metformin tas tv\xe5 till tre g\xe5nger dagligen i samband med eller efter m\xe5ltid. En gradvis \xf6kning av dosen kan ocks\xe5 f\xf6rb\xe4ttra den gastrointestinala toleransen.']]],
           ['Common', [['Nervous system', u'Smakf\xf6r\xe4ndringar']]],
           ['Very rare',
            [['Skin', u'Hudreaktioner s\xe5som erytem, pruritus, urtikaria.'],
             ['Metabolism',
              u'Laktatacidos (se avsnitt 4.4). En minskning av absorptionen av vitamin B12 med s\xe4nkta serumniv\xe5er har setts hos patienter som behandlats med metformin under l\xe5ng tid. B12-brist b\xf6r \xf6verv\xe4gas vid fynd av megaloblastisk anemi.'],
             ['Hepato',
              u'Enskilda rapporter visar st\xf6rda leverfunktionsv\xe4rden eller hepatit som normaliserats vid uts\xe4ttande av metforminhydroklorid.']]]],
 '_pages': [4, 5],
=======
              u'Gastrointestinala st\xf6rningar s\xe5som illam\xe5ende, kr\xe4kning, diarre, buksm\xe4rta och aptitl\xf6shet. Dessa biverkningar \xe4r mest frekvent f\xf6rekommande vid behandlingsstart och \xe4r spontant \xf6verg\xe5ende i de flesta fall. F\xf6r att f\xf6rebygga dessa symtom rekommenderas att metformin administreras 2 eller 3 g\xe5nger dagligen under eller efter m\xe5ltid. L\xe5ngsam dos\xf6kning kan ocks\xe5 \xf6ka den gastrointestinala tolerabiliteten.']]],
           ['Common', [['Nervous system', u'Smakf\xf6r\xe4ndring.']]],
           ['Very rare',
            [['Metabolism',
              u'Minskning av B12 absorptionen och s\xe4nkta serumniv\xe5er under l\xe5ngtidsbehandling med metformin. Detta b\xf6r beaktas om patienten uppvisar tecken p\xe5 megaloblastisk anemi. Laktacidos (se avsnitt 4.4. Varningar och f\xf6rsiktighet)'],
             ['Skin', u'Hudreaktioner s\xe5som erytem, pruritus och urtikaria.']]],
           ['Unknown',
            [['Hepato',
              u'Onormala leverfunktionsprover eller hepatit som \xe4r \xf6verg\xe5ende vid uts\xe4ttande av metformin.']]]],
 '_pages': [4, 4],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_rank': 5,
 u'_type': u'LSFU'}