{'_data': [['Very common',
            [['GI',
              u'gastrointestinala symtom som till exempel illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rtor och aptitl\xf6shet. Dessa biverkningar upptr\xe4der oftast vid start av behandlingen och upph\xf6r spontant i de flesta fallen. F\xf6r att f\xf6rebygga dessa gastrointestinala symtom rekommenderas det att metforminhydroklorid tas tv\xe5 till tre g\xe5nger dagligen i samband med eller efter m\xe5ltid. En gradvis \xf6kning av dosen kan ocks\xe5 f\xf6rb\xe4ttra den gastrointestinala toleransen.']]],
           ['Common', [['Nervous system', u'smakf\xf6r\xe4ndring']]],
           ['Very rare',
            [['Metabolism',
              u'Laktatacidos (se avsnitt 4.4) En minskning av absorptionen av vitamin B 12 med s\xe4nkta serumniv\xe5er har setts hos patienter som behandlats av metforminhydroklorid under l\xe5ng tid. B 12-brist b\xf6r \xf6verv\xe4gas vid fynd av megaloblastisk anemi.'],
             ['Hepato',
              u'enskilda rapporter visar onormala leverfunktionsv\xe4rden eller hepatit som normaliserats vid uts\xe4ttande av metforminhydroklorid.'],
             ['Skin', u'hudreaktioner s\xe5som erytem, pruritus, urtikaria']]]],
 '_pages': [4, 5],
 u'_rank': 5,
 u'_type': u'LSFU'}