{'_data': [['Very common',
            [['GI',
              u'Gastrointestinala st\xf6rningar som illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta och aptitl\xf6shet. Dessa biverkningar upptr\xe4der oftast vid behandlingens b\xf6rjan och upph\xf6r spontant i de flesta fall. F\xf6r att f\xf6rebygga dessa gastrointestinala symtom rekommenderas att metformin tas tv\xe5 till tre g\xe5nger dagligen i samband med eller efter m\xe5ltid. En gradvis \xf6kning av dosen kan ocks\xe5 f\xf6rb\xe4ttra den gastrointestinala toleransen.']]],
           ['Common', [['Nervous system', u'Smakf\xf6r\xe4ndring']]],
           ['Very rare',
            [['Metabolism',
              u'Minskning av absorptionen av vitamin B12 med s\xe4nkta serumniv\xe5er har setts hos patienter som behandlats med metformin under l\xe5ng tid. \xd6verv\xe4gande av s\xe5dan etiologi rekommenderas om en patient uppvisar megaloblastisk anemi. Laktatacidos (se avsnitt 4.4).'],
             ['Hepato',
              u'Enstaka rapporter om onormala leverfunktionsv\xe4rden eller hepatit, vilket f\xf6rsvunnit vid uts\xe4ttning av metformin.'],
             ['Skin',
              u'Hudreaktioner som erythema, pruritus, urtikaria. I publicerade data samt data efter marknadsf\xf6ring och i kontrollerade kliniska studier p\xe5 en begr\xe4nsad grupp barn och ungdomar i \xe5ldrarna 10-16 \xe5r, vilka behandlades under 1 \xe5r, var rapporteringen av biverkningar liknande till sin natur och sv\xe5righetsgrad som de som rapporterades f\xf6r vuxna.']]]],
 '_pages': [4, 5],
 u'_rank': 5,
 u'_type': u'LSFU'}