{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk.'],
             ['Vascular', u'Hypertoni.'],
             ['Skin', u'Hudutslag.'],
             ['Pregnancy',
              u'Buksm\xe4rtor (orsakade av uteruskontraktioner). frekvens) F\xf6ljande biverkningar \xe4r fr\xe5n spontana fallrapporter och litteraturfall tiden efter marknadsf\xf6ring av Methergin. D\xe5 dessa biverkningar har rapporterats frivilligt fr\xe5n en population av ok\xe4nd storlek \xe4r det inte m\xf6jligt att p\xe5 ett tillf\xf6rlitligt s\xe4tt ber\xe4kna frekvens och kategoriseras d\xe4rf\xf6r som ej k\xe4nd frekvens. Biverkningarna \xe4r listade enligt organsystemklasser i MedDRA. Inom varje organsystemklass \xe4r biverkningarna presenterade enligt fallande allvarlighetsgrad.']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel, krampanfall.'],
             ['Cardiac', u'Br\xf6stsm\xe4rtor.'],
             ['Vascular', u'Hypotension.'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende.'],
             ['Skin', u'Hyperhidros.']]],
           ['Rare',
            [['Cardiac', u'Bradykardi, takykardi, hj\xe4rtklappning.'],
             ['Vascular',
              u'Vasokonstriktion, vasospasm, vasospastiska reaktioner i perifera k\xe4rl.']]],
           ['Very rare',
            [['Immune system', u'Anafylaktiska \xf6verk\xe4nslighetsreaktioner.'],
             ['Nervous system', u'Hallucinationer.'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac', u'Hj\xe4rtinfarkt, koronar arteriospasm.'],
             ['Vascular', u'Tromboflebit.'],
             ['Respiratory', u'N\xe4st\xe4ppa.'],
             ['GI', u'Diarr\xe9.'],
             ['Musculoskeletal', u'Muskelspasmer.']]],
           ['Unknown',
            [['Nervous system', u'Cerebrovaskul\xe4r h\xe4ndelse, parestesi.'],
             ['Cardiac',
              u'Ventrikelflimmer, ventrikul\xe4r takykardi, angina pectoris, atrioventrikul\xe4rblock.']]]],
 '_pages': [4, 6],
 u'_rank': 21,
 u'_type': u'LSFU'}