{'_data': [[u'Unknown',
            [['Infections',
              u'Opportunistiska   Sepsis, Herpes    infektioner, inkl   zoster   d\xf6dliga infektioner'],
             ['Neoplasms', u'Lymfom, inkl   Tumor-lysis   reversibelt lymfom   syndrom'],
             ['Blood', u'Benm\xe4rgs-h\xe4m   Aplastisk anemi   ning i form av'],
             ['Immune system', u'Allergiska   Hypogamma-glob'],
             ['Metabolism', u'Diabetes'],
             ['Psychiatric', u'Depression och   konfusion,'],
             ['Nervous system',
              u'Parestesi   Huvudv\xe4rk,   D\xe5sighet, pares,  Onormala   hemipares,   p\xe5verkan p\xe5   sinnesf\xf6rnimmel-   konvulsioner,   talet inkl   ser'],
             ['Eye', u'Konjunktivit   Dimsyn,   \xd6verg\xe5ende'],
             ['Cardiac', u'Hypotension   Perikardiell'],
             ['Vascular', u'Vaskulit i   Vaskulit'],
             ['Respiratory', u'Interstitiell   Lungfibros,   Kronisk'],
             ['GI',
              u'Anorexi,   Pankreatit,   Gingivit,   Hematemes   stomatit,   gastrointestinala   faryngit,   (blodiga'],
             ['Hepato',
              u'Hepatit,   Fibros och cirrhos   Akut hepatit,   Minskning av   \xf6verg\xe5ende   vid l\xe5ga doser givna   Levertoxicitet,   serumalbumin'],
             ['Skin',
              u'Hudutslag vid   Hudutslag vid   Sm\xe4rtsam   Furunkulos,   h\xf6gdosbehand   konventionella   erosion av   teleangiektasier   -ling i form av   doser i form av   psoriasis'],
             ['Musculoskeletal', u'Osteoporos   Artralgi/myalgi,'],
             ['Renal',
              u'Nedsatt   Nedsatt   Dysuri   Azotemi, cystit,   njurfunktion,   njurfunktion, inkl   hematuri'],
             ['Reproductive system',
              u'Fertilitetsst\xf6rningar   Minskad libido,   Vaginala   i form av defekt   impotens   flytningar   oogenes och'],
             ['General', u'Tr\xf6tthet, yrsel   Aggravering av   Pl\xf6tslig d\xf6d'],
             ['Nervous system', u'Huvudv\xe4rk, kemisk araknoidit, subakut'],
             ['GI', u'Illam\xe5ende och kr\xe4kning.'],
             ['General', u'Feber.']]]],
 '_pages': [8, 11],
 u'_rank': 21,
 u'_type': u'LFSU'}