{'_data': [['Very common', [['Blood', u'Uttalad'], ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Cardiac',
              u'Bradykardi, balans-st\xf6rningar (mycket s\xe4llan med \xe5tf\xf6ljande synkop\xe9), hj\xe4rtklapp-ning'],
             ['Blood', u'Kalla'],
             ['Respiratory', u'Funktionell dyspn\xe9'],
             ['GI', u'Illam\xe5ende, buksm\xe4rta, diarr\xe9, f\xf6rstoppning']]],
           ['Uncommon',
            [['Metabolism', u'Vikt\xf6kning'],
             ['Psychiatric',
              u'Depression, koncentrations-sv\xe5righeter, s\xf6mnighet eller s\xf6mnl\xf6shet, mardr\xf6mmar'],
             ['Nervous system', u'Parestesi'],
             ['Cardiac',
              u'Tillf\xe4llig f\xf6rs\xe4mring av symtom p\xe5 hj\xe4rtsvikt, AV-block grad br\xf6stsm\xe4rta'],
             ['Respiratory', u'Bronkospasm'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin',
              u'Utslag (psoriasis-liknande urtikaria och dystrofiska kutana lesioner), \xf6kad svettning'],
             ['Musculoskeletal', u'Muskel-kramper'],
             ['General', u'\xd6dem']]],
           ['Rare',
            [['Endocrine', u'F\xf6rs\xe4mring av latent diabetes mellitus'],
             ['Psychiatric', u'Oro, \xe5ngest'],
             ['Eye', u'Syn-st\xf6rningar, torra eller irriterade \xf6gon, konjunktivit'],
             ['Cardiac',
              u'Funktionella hj\xe4rt-symtom, hj\xe4rt-arytmi, lednings-st\xf6rningar'],
             ['Respiratory', u'Rinit'],
             ['GI', u'Muntorrhet'],
             ['Hepato', u'Onormala lever-funktions-v\xe4rden'],
             ['Skin', u'H\xe5ravfall'],
             ['Reproductive system',
              u'Impotens och andra sexuella dys-funktioner, induratio penis plastica (Peyronies sjukdom)']]],
           ['Very rare',
            [['Blood', u'Trombocyto-peni, leukopeni'],
             ['Psychiatric',
              u'Gl\xf6mska eller f\xf6rs\xe4mrat minne, f\xf6rvirring, hallucinationer, personlighets-f\xf6r\xe4ndringar (t.ex. hum\xf6rf\xf6r\xe4nd-ringar)'],
             ['Ear', u'Tinnitus, h\xf6rsel-besv\xe4r'],
             ['Blood', u'Nekros hos'],
             ['GI', u'Smak-f\xf6r\xe4ndringar'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Ljus-\xf6verk\xe4nslighets-reaktioner, f\xf6rs\xe4mring av psoriasis, debuterande psoriasis, psoriasis-liknande dermatologiska f\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Artralgi, muskel-svaghet']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 33,
 u'_type': u'MSFU'}