<<<<<<< HEAD
{'_data': [['Very common',
            [['Vascular',
              u'Uttalad s\xe4nkning av blodtrycket och ortostatisk hypotension, i mycket s\xe4llsynta fall med synkope'],
             ['Reproductive system', u'och '],
             ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Cardiac',
              u'Bradykardi, balansst\xf6rningar (i isolerade fall med associerad synkope), palpitationer'],
             ['Vascular', u'Kalla h\xe4nder och'],
             ['GI', u'Illam\xe5ende, magsm\xe4rta, diarr\xe9, f\xf6rstoppning']]],
           ['Uncommon',
            [['Metabolism', u'Vikt\xf6kning'],
             ['Psychiatric',
              u'Depression, nedsatt koncentration, d\xe5sighet eller s\xf6mnl\xf6shet,  mardr\xf6mmar'],
             ['Cardiac',
              u'Tempor\xe4rt f\xf6rv\xe4rrande av symptom p\xe5 hj\xe4rtsvikt, AV-block I, prekordial sm\xe4rta'],
             ['GI', u'Kr\xe4kning'],
             ['Skin',
              u'Utslag (urtikaria av psoriasistyp och dystrofiska, kutana lesioner), \xf6kad  svettning'],
             ['General', u'\xd6dem']]],
           ['Rare',
            [['Endocrine', u'F\xf6rv\xe4rrande av  latent diabetes mellitus'],
             ['Psychiatric', u'Nervositet, ansp\xe4nning'],
             ['Eye', u'Synrubbningar, torrhet eller irritation i \xf6gonen, konjunktivit'],
             ['Cardiac',
              u'Funktionella hj\xe4rtsymptom, hj\xe4rtarytmier, hj\xe4rt\xf6verlednings-st\xf6r ningar'],
             ['GI', u'Muntorrhet'],
             ['Hepato', u'Onormala v\xe4rden vid leverfunktionstest'],
             ['Skin', u'H\xe5ravfall'],
             ['Reproductive system',
              u'Impotens och andra sexuella st\xf6rningar, Induratio penis plastica (Peyronies sjukdom)']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni,   leukopeni'],
             ['Psychiatric',
              u'Gl\xf6mska eller nedsatt minnesf\xf6rm\xe5ga, f\xf6rvirring, hallucination, personlighetsf\xf6r\xe4ndringar  (t.ex. hum\xf6rsv\xe4ngningar)'],
             ['Ear', u'Tinnitus,   h\xf6rselsrubbningar'],
             ['Vascular',
              u'Nekros hos patienter med allvarlig perifer k\xe4rlst\xf6rning f\xf6re behandlingen, F\xf6rs\xe4mring av intermittent claudicatio  eller Raynaud\u2019s syndrom'],
             ['GI',
              u'Smakf\xf6r\xe4ndringar, retriperitoneal fibros (sambandet med metoprolol har inte fastst\xe4llts slutgiltigt)'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Ljusk\xe4nslighets-reaktioner , f\xf6rv\xe4rrad psoriasis, nytt utbrott av psoriasis, psoriasisliknande kutana  f\xf6r\xe4ndringar']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 27,
 u'_type': u'MSFU'}
=======
{'_data': [[u'Unknown',
            [['Blood', u'Trombocytopeni,   leukopeni'],
             ['Endocrine', u'F\xf6rv\xe4rrande av latent   diabetes mellitus'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['Psychiatric',
              u'Depression, nedsatt   Nervositet, ansp\xe4nning Gl\xf6mska eller nedsatt'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk   Parestesi'],
             ['Eye', u'Synrubbningar, torrhet'],
             ['Ear', u'Tinnitus,   h\xf6rselsrubbningar'],
             ['Cardiac',
              u'Bradykardi,   balansst\xf6rningar (i    Tempor\xe4rt f\xf6rv\xe4rrande   av symptom p\xe5    Funktionella   hj\xe4rtsymptom,'],
             ['Vascular',
              u'Uttalad s\xe4nkning   Kalla h\xe4nder och f\xf6tter   Nekros hos patienter med'],
             ['Respiratory', u'Andn\xf6d vid   anstr\xe4ngning    Bronkospasm'],
             ['GI', u'Illam\xe5ende,   Kr\xe4kning   Muntorrhet   Smakf\xf6r\xe4ndringar,'],
             ['Hepato', u'Onormala v\xe4rden vid   Hepatit'],
             ['Skin', u'Utslag (urtikaria av   H\xe5ravfall   Ljusk\xe4nslighets-reaktioner,'],
             ['Musculoskeletal', u'Muskelspasmer   Artralgi, muskelsvaghet,'],
             ['Reproductive system', u'Impotens och andra'],
             ['General', u'Tr\xf6tthet   \xd6dem']]]],
 '_pages': [7, 9],
 u'_rank': 16,
 u'_type': u'LFSU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
