{'_data': [['Very common',
            [['Vascular',
              u'Uttalad s\xe4nkning av blodtrycket och ortostatisk hypotoni, i mycket s\xe4llsynta fall med synkope'],
             ['General', u'Tr\xf6tthet']]],
           ['Common',
            [['Cardiac',
              u'Bradykardi, balansst\xf6rningar (i isolerade fall med associerad synkope), palpitationer'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Respiratory', u'Andn\xf6d vid anstr\xe4ngning'],
             ['GI', u'Illam\xe5ende, magsm\xe4rta, diarr\xe9, f\xf6rstoppning'],
             ['Vascular', u'Kalla h\xe4nder och f\xf6tter']]],
           ['Uncommon',
            [['Cardiac',
              u'Tillf\xe4lligt f\xf6rv\xe4rrade symtom p\xe5 hj\xe4rtsvikt, AV-block I, prekordial sm\xe4rta'],
             ['Nervous system', u'Parestesi'],
             ['Respiratory', u'Bronkospasm'],
             ['GI', u'Kr\xe4kning'],
             ['Skin',
              u'Utslag (urtikaria av psoriasistyp och dystrofiska hudlesioner), \xf6kad svettning'],
             ['Musculoskeletal', u'Muskelspasmer'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['General', u'\xd6dem'],
             ['Psychiatric',
              u'Depression, nedsatt koncentration, d\xe5sighet eller s\xf6mnl\xf6shet, mardr\xf6mmar']]],
           ['Rare',
            [['Cardiac',
              u'Funktionella hj\xe4rtsymtom, hj\xe4rtarytmier, hj\xe4rt\xf6verledningsst\xf6rningar'],
             ['Eye', u'Synrubbningar, torrhet eller irritation i \xf6gonen, konjunktivit'],
             ['Respiratory', u'Rinit'],
             ['GI', u'Muntorrhet'],
             ['Skin', u'H\xe5ravfall'],
             ['Endocrine', u'F\xf6rv\xe4rrande av latent diabetes mellitus'],
             ['Hepato', u'Onormala v\xe4rden vid leverfunktionstest'],
             ['Reproductive system',
              u'Impotens och andra sexuella st\xf6rningar, induratio penis plastica (Peyronies sjukdom)'],
             ['Psychiatric', u'Nervositet, \xe5ngest']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni, leukopeni'],
             ['Ear', u'Tinnitus, h\xf6rselrubbningar'],
             ['GI', u'Smakf\xf6r\xe4ndringar'],
             ['Skin',
              u'Ljusk\xe4nslighet, f\xf6rv\xe4rrad psoriasis, nytt utbrott av psoriasis, psoriasisliknande hudf\xf6r\xe4ndringar'],
             ['Musculoskeletal', u'Artralgi, muskelsvaghet'],
             ['Vascular',
              u'Nekros hos patienter med allvarlig perifer cirkulationsrubbning f\xf6re behandling, f\xf6rs\xe4mring av claudicatio intermittens eller Raynauds syndrom'],
             ['Hepato', u'Hepatit'],
             ['Psychiatric',
              u'Gl\xf6mska eller nedsatt minnesf\xf6rm\xe5ga, f\xf6rvirring, hallucinationer, personlighetsf\xf6r\xe4ndringar (t.ex. hum\xf6rsv\xe4ngningar)']]]],
<<<<<<< HEAD
 '_pages': [6, 7],
=======
 '_pages': [6, 8],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_rank': 33,
 u'_type': u'LSFU'}