{'_data': [['Very common',
            [['Infections', u'och'],
             ['Respiratory', u'och'],
             ['GI', u'Minskad   aptit,'],
             ['Hepato',
              u'\xd6kning av leverenzymer (ALAT, ASAT, alkalisk fosfatas och bilirubin).']]],
           ['Common',
            [['Infections', u'Herpes zoster'],
             ['Blood', u'Leukopeni, anemi, trombocytope'],
             ['Nervous system', u'Huvudv\xe4rk, fatigue, d\xe5sighet'],
             ['Respiratory',
              u'Lungkomplika tioner p.g.a. interstitiell alveolit/pneu monit och relaterade d\xf6dsfall (oberoende av dos duration av metotrexat-be handling). Typiska symtom vara: sjukdomsk\xe4ns irriterande hosta; progredierand e andningsstille st\xe5nd, br\xf6stsm\xe4rta, feber. Om s\xe5dana komplikatione r misst\xe4nks ska metotrexatbeh andlingen omedelbart uts\xe4ttas infektion (inklusive lunginflammat ion) uteslutas.'],
             ['GI', u'Diarr\xe9'],
             ['Skin', u'Exantem, erytem, kl\xe5da.']]],
           ['Uncommon',
            [['Blood', u'Pancytopeni, agranulocytos, hematopoetiska tillst\xe5nd'],
             ['Immune system', u'Anafylaktoida reaktioner,allergisk vaskulit'],
             ['Nervous system',
              u'Vertigo, f\xf6rvirring, depression, kramper, konvulsioner, encefalopati'],
             ['Neoplasms',
              u'Enstaka fall av lymfom, som i flera fall avtog d\xe5 behandlingen med metotrexat avbrutits. Ingen \xf6kad incidens av lymfom under behandling med metotrexat uppt\xe4cktes i en mer nyligen genomf\xf6rd studie.'],
             ['Vascular', u'Vaskulit'],
             ['Respiratory', u'Lungfibros och kan torr, andn\xf6d och'],
             ['GI', u'Gastrointestinala   s\xe5r'],
             ['Hepato',
              u'Utveckling fettlever, fibros och cirrhos (upptr\xe4der frekvent regelbundet kontrollerade normala leverenzym-v\xe4rden); diabetes-metabolism; minskning serumalbumin.'],
             ['Skin',
              u'Urtikaria, fotosensibilitet, \xf6kad hudpigmentering, h\xe5ravfall, \xf6kning av reumatiska noduli, herpes sm\xe4rtsamma lesioner av psoriasisplack; sv\xe5ra reaktioner: vaskulit, herpetiforma hud-utslag, Stevens-Johnsons syndrom, epidermal (Lyells syndrom).'],
             ['Musculoskeletal', u'Osteoporos,  artralgi, myalgi'],
             ['Renal',
              u'Inflammation och s\xe5r i urinbl\xe5san (eventuellt med hematuri), dysuri'],
             ['Reproductive system', u'Inflammation och s\xe5r i slidan.'],
             ['General',
              u'Sv\xe5ra allergiska reaktioner progredierande till anafylaktisk chock.']]],
           ['Rare',
            [['Cardiac', u'Perikardit, perikardiell utgjutning, perikardiell tamponad'],
             ['Blood', u'Megaloblastisk anemi'],
             ['Nervous system',
              u'Dimsyn, allvarliga synf\xf6r\xe4ndringa r, hum\xf6rf\xf6r\xe4ndri ngar, pares, p\xe5verkan p\xe5 talet inklusive dysartri och afasi, myelopati'],
             ['Eye', u'Dimsyn, allvarliga synf\xf6r\xe4ndringa'],
             ['Vascular',
              u'Hypotension, tromboembolis ka h\xe4ndelser (s\xe5som arteriell trombos, cerebral trombos, tromboflebit, djup ventrombos, retinalventrom bos, lungemboli)'],
             ['Respiratory', u'Faryngit, apn\xe9, bronkialastma'],
             ['GI', u'Gingivit,'],
             ['Hepato', u'av och hepatotoxicitet. trots av'],
             ['Skin',
              u'\xd6kad pigmentering i naglar, akne, petekier, ekkymoser, zoster, erytema multiforme, erytemat\xf6sa toxiska toxisk nekrolys'],
             ['Musculoskeletal', u'Stressfraktur'],
             ['Renal',
              u'Njursvikt, oliguri, anuri, azotemi., hyperuricemi, f\xf6rh\xf6jda niv\xe5er av serumkreatinin och urea']]],
           ['Very rare',
            [['Infections',
              u'Sepsis, opportunistiska infektioner (ibland med d\xf6dlig utg\xe5ng), infektioner orsakade av cytomegalovirus'],
             ['Blood',
              u'Allvarliga f\xf6rlopp av benm\xe4rgsh\xe4mni ng, aplastisk anemi,lymfaden pati, lymfoproliferati va sjukdomar (reversibla), eosinofili och neutropeni'],
             ['Immune system', u'Immunosuppres sion, hypogammaglob ulemi'],
             ['Psychiatric', u'Insomni'],
             ['Nervous system',
              u'Sm\xe4rta, muskul\xe4r asteni eller parestesi i h\xe4nder och f\xf6tter, myasteni, onormala smakf\xf6r\xe4ndringa r (metallsmak), meningit (f\xf6rlamning, kr\xe4kningar), akut meningit'],
             ['Eye',
              u'Konjunktivit, retinopati, \xf6verg\xe5ende blindhet/synf\xf6rl ust, periorbitalt \xf6dem, blefarit, epifora, fotofobi'],
             ['Neoplasms', u'Tum\xf6r-lys-syndr om'],
             ['Respiratory',
              u'Pneumocystis carinii-pneumon kronisk obstruktiv lungsjukdom. Infektioner inkluderande lunginflammatio n har ocks\xe5 observerats. Pleuraexsudat.'],
             ['GI', u'Hematemes'],
             ['Hepato',
              u'Akut hepatit kronisk hepatit, akut lever-degenereri ng. Dessutom har, herpes simplex, hepatit nedsatt leverfunktion observerats (se \xe4ven avsnitt 4.4 betr\xe4ffande leverbiopsi).'],
             ['Skin',
              u'Akut paronyki, furunkulos, telangiektasier. Dessutom har nocardios, histoplasma och kryptokockos mykos samt huderuptioner simplex rapporterats. Allergisk vaskulit, hidradenit.'],
             ['Renal', u'Proteinuri'],
             ['Reproductive system',
              u'Minskad libido, impotens, oligospermi, menstruationsru bbning, vaginala flytningar, infertilitet. gynekomasti'],
             ['General', u'Feber, f\xf6rs\xe4mrad s\xe5rl\xe4kning.']]],
           ['Unknown',
            [['Blood', u'Bl\xf6dningar, hematom'],
             ['Psychiatric', u'Psykos'],
             ['Vascular', u'Cerebralt \xf6dem, petekier'],
             ['Respiratory', u'Akut lung\xf6dem'],
             ['GI', u'Toxisk'],
             ['Hepato', u'Reaktivering av sjukdomar och'],
             ['Skin', u'Exfoliativ dermatit, hudnekros spridd herpes'],
             ['GI', u'Illam\xe5ende och kr\xe4kningar']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 13],
 u'_rank': 56,
 u'_type': u'MSFU'}