{'_data': [['Common', [['GI', u'Diffusa intoleranssymtom, metallisk smak']]],
           ['Uncommon', [['Blood', u'Leukopeni']]],
           ['Rare',
            [['Blood', u'Agranulocytos, neutropeni, trombocytopeni, pancytopeni'],
             ['Nervous system',
              u'Yrsel, ataxi, perifer sensorisk neuropati, parestesi, krampanfall'],
             ['Eye', u'Synf\xf6r\xe4ndringar s\xe5som diplopi, myopi.'],
             ['GI',
              u'Munmukosit, epigastralgi, illam\xe5ende, kr\xe4kningar, diarr\xe9, anorexi, pankreatit, smakf\xf6r\xe4ndringar.'],
             ['Renal', u'M\xf6rkf\xe4rgning av urinen'],
             ['Skin',
              u'Pustul\xf6sa hudutslag, urtikaria, exantem, kl\xe5da, erytema multiforme, angio\xf6dem'],
             ['General', u'Feber, anafylaktisk chock'],
             ['Hepato', u'Onormala leverfunktionsv\xe4rden, kolestatisk hepatit, gulsot'],
             ['Psychiatric',
              u'Psykiatriska tillst\xe5nd s\xe5som konfusion och hallucinationer']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'MSFU'}