{'_data': [['Common',
            [['GI',
              u' Diffusa intoleranssymtom (illam\xe5ende, aptitl\xf6shet, kr\xe4kningar,  magsm\xe4rtor, diarr\xe9), metallisk smak.  ']]],
           ['Uncommon', [['Blood', u' Leukopeni.  ']]],
           ['Rare',
            [['General', u' Feber, anafylaktisk chock.  '],
             ['Blood', u' Agranulocytos, neutropeni, trombocytopeni, pancytopeni.  '],
             ['GI',
              u' Munmukosit, epigastralgi, illam\xe5ende, kr\xe4kningar, diarr\xe9, anorexi, pankreatit, smakf\xf6r\xe4ndringar. '],
             ['Skin',
              u' Pustul\xf6sa hudutslag, urtikaria, exantem, kl\xe5da, erytema multiforme, angio\xf6dem. '],
             ['Hepato', u' Onormala leverfunktionsv\xe4rden, kolestatisk hepatit, gulsot. '],
             ['Nervous system',
              u' Yrsel, ataxi, perifer sensorisk neuropati, parestesi, krampanfall. '],
             ['Psychiatric',
              u' Psykiatriska tillst\xe5nd s\xe5som konfusion och hallucinationer. '],
             ['Reproductive system', u' M\xf6rkf\xe4rgning av urinen. '],
             ['Eye', u' Synf\xf6r\xe4ndringar som diplopi, myopi. ']]],
           ['Unknown',
            [['Skin', u' Stevens-Johnson syndrom, toxisk epidermal nekrolys.  '],
             ['Nervous system', u' Encefalopati, optisk neuropati, aseptisk meningit.  ']]]],
 '_pages': [3, 3],
 u'_rank': 13,
 u'_type': u'DFSU'}