{'_data': [['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighetsreaktioner, anafylaktisk chock.'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, eufori, hallucinationer Agitation*, fientlighet*, raseriutbrott*, aggressivitet*, upphetsning* Fysiskt beroende och abstinenssymtom'],
             ['Nervous system',
              u'Ofrivilliga r\xf6relser (inklusive toniska/kloniska kramper och muskeltremor)*, hyperaktivitet* Sedering (f\xf6rl\xe4ngd och postoperativ), minskad vakenhet, somnolens, huvudv\xe4rk, yrsel, ataxi, anterograd amnesi**, vars duration \xe4r direkt relaterad till den administrerade dosen Krampanfall har rapporterats hos prematura barn och nyf\xf6dda barn Konvulsioner vid abstinens'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, bradykardi'],
             ['Vascular',
              u'Ingen k\xe4nd frekvens Hypotension, vasodilation, tromboflebit, trombos'],
             ['Respiratory',
              u'Andningsdepression, apn\xe9, andningsstillest\xe5nd, dyspn\xe9, laryngospasm, hicka'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, f\xf6rstoppning, muntorrhet'],
             ['Skin',
              u'Hudutslag, urtikaria, kl\xe5da. Allm\xe4nna symtom och symtom vid administreringsst\xe4llet']]]],
 '_pages': [12, 13],
 u'_rank': 8,
 u'_type': u'LSFU'}