{'_data': [['Very common',
            [['GI',
              u'Illam\xe5ende, kr\xe4kningar, diarr\xe9 (dessa biverkningar relaterade till prostaglandinanv\xe4ndning rapporteras ofta).'],
             ['Reproductive system',
              u'Sida 6 av 10 Livmodersammandragningar eller kramper \xe4r mycket vanligt f\xf6rekommande (hos 10 till 45%) timmarna efter tillf\xf6rsel av prostaglandin.']]],
           ['Common',
            [['GI', u'Kramper, l\xe4tta eller m\xe5ttliga.'],
             ['Infections',
              u'Infektion efter abort. Misst\xe4nkta eller bekr\xe4ftade infektioner (endometrit, b\xe4ckeninflammation (PID)) har rapporterats hos f\xe4rre \xe4n 5 % av kvinnorna.'],
             ['Reproductive system',
              u'Rikliga bl\xf6dning f\xf6rekommer i cirka 5% av fallen och kan kr\xe4va exeres, d v s skrapning i upp till 1,4% av fallen.']]],
           ['Uncommon',
            [['Skin', u'\xd6verk\xe4nslighet: hudutslag (ovanliga, 0.2 %).'],
             ['Vascular', u'L\xe5gt blodtryck (0,25%).']]],
           ['Rare',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Skin',
              u'Enstaka fall av urtikaria, erythrodermi, erythema nodosum, toxisk epidermal nekrolys har ocks\xe5 rapporterats.'],
             ['General',
              u'Sjukdomsk\xe4nsla, vagala symtom (blodvallningar, yrsel, frossa), feber.'],
             ['Reproductive system',
              u'Vid abortinduktion under andra trimestern, eller vid f\xf6rlossningsinduktion p g a intrauterin fosterd\xf6d under tredje trimestern, har enstaka fall av uterusruptur rapporterats efter tillf\xf6rsel av prostaglandin. Dessa har speciellt f\xf6rekommit hos mulitpara kvinnor eller hos kvinnor som tidigare genomg\xe5tt kejsarsnitt.']]],
           ['Very rare',
            [['Skin', u'Angi\xf6dem'],
             ['Infections', u''],
             ['Infections',
              u'a fall av allvarlig eller d\xf6dlig toxisk chock orsakad av patogener som Clostridium sordellii endometritis eller Escherichia coli, med eller utan feber eller andra uppenbara symtom p\xe5 infektion, har rapporterats efter medicinsk abort d\xe4r man anv\xe4nt 200 mg mifepriston f\xf6ljt av icke godk\xe4nd vaginal administrering av orala misoprostoltabletter. L\xe4karna ska vara medvetna om denna potentiellt d\xf6dliga komplikation (se avsnitt 4.4 Varningar och f\xf6rsiktighet).']]]],
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'LSFU'}