{'_data': [['Very common', [['Skin', u'Ankelsvullnad.']]],
           ['Common',
            [['Cardiac', u'Palpitation'],
             ['Nervous system',
              u'Huvudv\xe4rk (speciellt i b\xf6rjan av behandlingen), tr\xf6tthet, yrsel, asteni.'],
             ['Respiratory', u'Dyspn\xe9, rinit.'],
             ['GI', u'Illam\xe5ende, dyspepsi, magknip.'],
             ['Skin',
              u'Ansiktsrodnad med v\xe4rmek\xe4nsla, speciellt i b\xf6rjan av behandlingen.'],
             ['Musculoskeletal', u'Muskelkramper.']]],
           ['Uncommon',
            [['Cardiac',
              u'Synkope, takykardi, br\xf6stsm\xe4rta. F\xf6rs\xe4mring av angina pectoris kan uppst\xe5 i b\xf6rjan av behandlingen.'],
             ['Blood', u'Leukopeni, trombocytopeni.'],
             ['Nervous system',
              u'Sjukdomsk\xe4nsla, perifer neuropati, muntorrhet, parestesier, \xf6kad svettning.'],
             ['Eye', u'Synst\xf6rningar.'],
             ['Ear', u'Tinnitus'],
             ['Respiratory', u'Hosta.'],
             ['GI', u'Kr\xe4kningar, diarr\xe9, obstipation, gingivalhyperplasi.'],
             ['Renal', u'\xd6kad vattenkastningsfrekvens.'],
             ['Skin', u'Exantem, kl\xe5da, urtikaria, alopeci, purpura, hudmissf\xe4rgning.'],
             ['Musculoskeletal', u'Ryggsm\xe4rtor, myalgi och artralgi.'],
             ['Endocrine', u'Gynekomasti.'],
             ['Vascular', u'Hypotension, vaskulit.'],
             ['General', u'\xd6kning eller minskning i vikt.'],
             ['Hepato', u'Pankreatit.'],
             ['Reproductive system', u'Impotens.'],
             ['Psychiatric', u'S\xf6mnrubbning, irritabilitet, nedst\xe4mdhet.']]],
           ['Rare',
            [['Hepato', u'F\xf6rh\xf6jda leverenzymer, gulsot, hepatit.'],
             ['Psychiatric', u'F\xf6rvirring, hum\xf6rsv\xe4ngningar inklusvie \xe5ngest.']]],
           ['Very rare',
            [['Nervous system', u'Tremor, smakf\xf6r\xe4ndringar.'],
             ['GI', u'Gastrit.'],
             ['Skin', u'Angio\xf6dem.'],
             ['Metabolism', u'Hyperglykemi.']]]],
 '_pages': [3, 5],
 u'_rank': 29,
 u'_type': u'LSFU'}