{'_data': [['Common',
            [['Metabolism', u'Hypoglykemi'],
             ['GI', u'Vanliga Illam\xe5ende , diarr\xe9 , magsm\xe4rta. Kr\xe4kningar'],
             ['Hepato', u'Leverenzymstegring']]],
           ['Uncommon',
            [['Nervous system', u'Mindre vanliga Yrsel , tremor'],
             ['GI', u'F\xf6rstoppning'],
             ['Hepato', u'Kolestatisk ikterus']]],
           ['Unknown',
            [['Blood',
              u'Trombocytopeni, leukopeni, agranulocytos, hemolytisk anemi, pancytopeni'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'F\xf6rvirringstillst\xe5nd'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'Nedsatt syn'],
             ['GI', u'Ingen k\xe4nd frekvens'],
             ['Hepato', u'Hepatit'],
             ['Skin',
              u'Utslag, urticaria, kl\xe5da, fotosensitivitesreaktion 1 Dessa \xe4r vanligen \xf6verg\xe5ende och kr\xe4ver inte att behandlingen avbryts. De kan dock \xe4ven vara symptom p\xe5 hypoglykemi. 2 Tycks vara dosrelaterade och f\xf6rsvinner vanligen n\xe4r dosen delas upp eller reduceras. 3 Avbryt behandlingen om kolestatisk ikterus uppst\xe5r.']]]],
 '_pages': [3, 3],
 u'_rank': 14,
 u'_type': u'LSFU'}