{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Magsm\xe4rtor, illam\xe5ende'],
             ['Metabolism', u'Hyponatremi'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI', u'Magsm\xe4rtor, illam\xe5ende,  muntorrhet, vikt\xf6kning']]],
           ['Very rare',
            [['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Emotionella st\xf6rningar hos  barn, t ex mardr\xf6mmar'],
             ['Skin', u'Allergiska hudreaktioner']]]],
 '_pages': [4, 5],
 u'_rank': 8,
 u'_type': u'TSFU'}