{'_data': [['Very common',
            [['Metabolism', u'\xd6kad aptit Vikt\xf6kning'],
             ['Nervous system', u'Tr\xf6tthet Sedering Huvudv\xe4rk'],
             ['GI', u'Muntorrhet Illam\xe5ende']]],
           ['Common',
            [['Psychiatric', u'Onormala dr\xf6mmar F\xf6rvirring \xc5ngest Insomnia'],
             ['Nervous system', u'\uf020Letargi Yrsel \uf020Tremor'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['GI', u'Diarre \uf020Kr\xe4kningar'],
             ['Skin', u'Exantem'],
             ['Musculoskeletal', u'Artralgi Myalgi Ryggont'],
             ['General', u'Perifera \xf6dem Tr\xf6tthet']]],
           ['Uncommon',
            [['Psychiatric',
              u'Mardr\xf6mmar Mani Agitation Hallucinationer Psykomotorisk oro (inkl. akatisi, hyperkinesi)'],
             ['Nervous system', u'Parestesi Restless legs Synkope'],
             ['Vascular', u'Hypotension'],
             ['GI', u'Oral hypoestesi']]],
           ['Rare',
            [['Psychiatric', u'Aggression'],
             ['Nervous system', u'Myoklonus'],
<<<<<<< HEAD
             ['Hepato', u'F\xf6rh\xf6jda transaminaser i serum']]],
=======
             ['Hepato', u'F\xf6rh\xf6jda transaminase r i serum']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Blood',
              u'Benm\xe4rgsdepression (granulocytopeni, agranulocytos, aplastisk anemi trombocytopeni) Eosinofili'],
             ['Endocrine', u'Felaktig sekretion av antidiuretiskt hormon'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Suicidtankar Suicidalt beteende'],
             ['Nervous system', u'Kramper (anfall) Serotoninsyndrom Oral parestesi Dysartri'],
             ['GI', u'\xd6dem i munnen \xd6kad salivering'],
             ['Skin',
<<<<<<< HEAD
              u'Stevens-Johnson-syn drom Bull\xf6s dermatit Erythema multiforme Toxisk epidermal nekrolys'],
=======
              u'Stevens-Johnson-syndrom Bull\xf6s dermatit Erythema multiforme Toxisk epidermal nekrolys'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['General', u'Somnambulism']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 25,
 u'_type': u'MSFU'}