{'_data': [['Very common',
            [['Investigations', u'Vikt\xf6kning'],
             ['Nervous system', u'Tr\xf6tthet Sedering Huvudv\xe4rk'],
             ['GI', u'Muntorrhet'],
             ['Metabolism', u'\xd6kad aptit']]],
           ['Common',
            [['Nervous system', u'Letargi Yrsel Tremor'],
             ['GI', u'Illam\xe5ende Diarr\xe9 Kr\xe4kningar'],
             ['Skin', u'Exantem'],
             ['Musculoskeletal', u'Artralgi Myalgi Ryggont'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['General', u'Perifera \xf6dem Tr\xf6tthet'],
             ['Psychiatric', u'Livliga dr\xf6mmar F\xf6rvirring \xc5ngest Insomnia']]],
           ['Uncommon',
            [['Nervous system', u'Paraestesi Restless legs Synkope'],
             ['GI', u'Oral hypoestesi'],
             ['Vascular', u'Hypotension'],
             ['Psychiatric',
              u'Mardr\xf6mmar Mani Agitation Hallucinatione r Psykomotoris k oro (inkl. akatisi, hyperkinesi)']]],
           ['Rare',
            [['Nervous system', u'Myoklonus'],
             ['Hepato', u'F\xf6rh\xf6jda transaminaser i serum'],
             ['Psychiatric', u'Aggression']]],
           ['Unknown',
            [['Blood',
              u'Benm\xe4rgs-depression (granulocytop eni, agranulocytos , aplastisk anemi, trombocytope ni) Eosinofili'],
             ['Nervous system', u'Kramper (anfall) Serotonin syndrom Oral parestesi Dysartri'],
             ['GI', u'\xd6dem i munnen \xd6kad salivuts\xf6ndrin g'],
             ['Skin',
              u'Stevens Johnsons syndrom Toxisk epidermal nekrolys Erythema multiforme Bull\xf6s dermatit'],
             ['Metabolism', u'Hyponatremi'],
             ['General', u'S\xf6mng\xe5ng'],
             ['Psychiatric', u'Suicidtankar Suicidalt beteende'],
             ['Endocrine', u'Felaktig sekretion av antidiuretiskt hormon']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 8],
 u'_rank': 26,
 u'_type': u'MSFU'}