{'_data': [['Very common',
            [['Investigations', u'Vikt\xf6kning'],
             ['Nervous system', u'Tr\xf6tthet Sedering Huvudv\xe4rk'],
             ['GI', u'Muntorrhet'],
             ['Metabolism', u'\xd6kad aptit']]],
           ['Common',
            [['Nervous system', u'Letargi Yrsel Tremor'],
             ['GI', u'Illam\xe5ende Diarre Kr\xe4kningar'],
             ['Skin', u'Exantem'],
             ['Musculoskeletal', u'Artralgi Myalgi Ryggont'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['General', u'Perifera \xf6dem Tr\xf6tthet'],
             ['Psychiatric', u'Livliga dr\xf6mmar F\xf6rvirring \xc5ngest Insomnia']]],
           ['Uncommon',
            [['Nervous system', u'Paraestesi Restless legs Synkope'],
             ['GI', u'Oral hypoestesi'],
             ['Vascular', u'Hypo-tension'],
             ['Psychiatric',
              u'Mar-dr\xf6mmar Mani Agitation Hallucinati oner Psykomot orisk oro (inkl. akatisi, hyper-kinesi)']]],
           ['Rare',
            [['Nervous system', u'Myoklonus Kramper (anfall)'],
             ['Hepato', u'F\xf6rh\xf6jda trans-aminaser i serum']]],
           ['Unknown',
            [['Blood',
              u'Benm\xe4rgsdepression (granulocytopeni, agranulocytos, aplastisk anemi trombocytopeni) Eosinofili'],
             ['Nervous system', u'Serotoninsyndrom Oral parestesi'],
             ['GI', u'\xd6dem i munnen'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Suicidtankar Suicidalt beteende'],
             ['Endocrine', u'Felaktig sekretion av antidiuretiskt hormon']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 8],
 u'_rank': 23,
 u'_type': u'MSFU'}