{'_data': [['Very common',
            [['Investigations', u'Vikt\xf6kning'],
             ['Nervous system', u'Tr\xf6tthet -Sedering -Huvudv\xe4rk'],
             ['GI', u'Muntorrhet '],
             ['Metabolism', u'\xd6kad aptit']]],
           ['Common',
            [['Nervous system', u'Letargi -Yrsel -Tremor'],
             ['GI', u'Illam\xe5ende -Diarre -Kr\xe4kningar'],
             ['Skin', u'Exantem'],
             ['Musculoskeletal', u'Artralgi -Myalgi -Ryggont'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['General', u'Perifera \xf6dem -Tr\xf6tthet'],
             ['Psychiatric', u'Livliga dr\xf6mmar -F\xf6rvirring -\xc5ngest -Insomnia']]],
           ['Uncommon',
            [['Nervous system', u'Paraestesi -Restless legs -Synkope'],
             ['GI', u'Oral hypoestesi'],
             ['Vascular', u'Hypotension'],
             ['General', u'1'],
             ['Psychiatric',
              u'Mardr\xf6mmar -Mani Agitation -Hallucinationer -Psykomotorisk oro (inkl. akatisi, hyperkinesi)']]],
           ['Rare',
            [['Nervous system', u'Myoklonus'],
             ['Hepato', u'F\xf6rh\xf6jda transaminaser i serum'],
             ['Psychiatric', u'2']]],
           ['Unknown',
            [['Blood',
              u'Benm\xe4rgsdepression (granulocytopeni, agranulocytos, aplastisk anemi trombocytopeni) -Eosinofili'],
             ['Nervous system', u'Kramper (anfall) -Serotoninsyndrom -Oral parestesi'],
             ['GI', u'\xd6dem i munnen'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Suicidtankar -Suicidalt beteende 6'],
             ['Endocrine', u'Felaktig sekretion av antidiuretiskt hormon']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 25,
 u'_type': u'MSFU'}