{'_data': [['Very common',
            [['Cardiac',
              u'\xd6verg\xe5ende EKG-f\xf6r\xe4ndringar efter l\xe5ngtidsbehandling. Arrytmi.'],
             ['Blood',
              u'Neutropeni. En \xf6kning av dosen p\xe5 grund av hematologiska fenomen kring nadir ledde till neutropeni av 4:e graden hos 54 % av patienterna. Neutropenisk feber f\xf6rekom hos 14 % av patienterna. Myelosuppression, benm\xe4rgshypoplasier. \xd6verg\xe5ende leukopeni med l\xe4gsta v\xe4rde 10-13 dagar efter behandling (allvarlig leukopeni hos 6%), anemi, granulocytopeni, abnormala m\xe4ngder av leukocyter.'],
             ['GI',
              u'Milt illam\xe5ende och kr\xe4kningar hos ca 50% av patienterna (allvarligt hos 1%), stomatit, diarr\xe9, buksm\xe4rtor och anorexi. F\xf6rstoppning, mukosit, smakf\xf6r\xe4ndringar.'],
             ['Renal', u'\xd6kad ureakoncentration i blodet.'],
             ['Skin',
              u'Alopeci grad I-II hos ca 50% av patienterna (allvarlig alopeci \xe4r ovanlig).'],
             ['Infections', u'Infektioner, \xf6vre luftv\xe4gsinfektion, urinv\xe4gsinfektion'],
             ['General', u'Feber.'],
             ['Reproductive system',
              u'Amenorr\xe9 (kan vara f\xf6rl\xe4ngd och motsvara prematur menopaus)']]],
           ['Common',
            [['Cardiac',
              u'Asymptomatisk reduktion av v\xe4nster kammares ejektionsfraktion (2,6% med en kumulativ dos av 140 mg/m ), hj\xe4rtinsufficiens, br\xf6stsm\xe4rta, hj\xe4rtsvikt efter l\xe5ngtidsbehandling (2,6% med en kumulativ dos av 140 mg/m ). Sinus bradykardi. Hj\xe4rtfunktionen ska \xf6vervakas hos patienter som f\xe5tt kumulativa doser >160 mg/m mitoxantron. Patienter som tidigare har f\xe5tt antracyklin eller andra kardiotoxiska onkologiska l\xe4kemedel och/eller mediastinal str\xe5lterapi och som \xe4ven lider av underliggande kardiovaskul\xe4r sjukdom, har en h\xf6gre risk f\xf6r hj\xe4rtp\xe5verkan. Kardiotoxicitet vid behandling med mitoxantron i kumulativa doser l\xe4gre \xe4n 100 mg/m har rapporterats.'],
             ['Blood', u'Trombocytopeni (<50x109/l) f\xf6rekom hos 4 % av patienterna.'],
             ['Nervous system',
              u'Icke-specifika neurologiska biverkningar s\xe5som yrsel, somnolens, neurit, konvulsion och mild parestesi har rapporterats. Huvudv\xe4rk.'],
             ['Respiratory', u'Rhinit'],
             ['GI', u'Gastrointestinala bl\xf6dningar.'],
             ['Renal',
              u'Missf\xe4rgning av urinen inom 24 timmar efter administrering. Nefrotoxicitet, \xf6kat serumkreatinin och \xf6kat kv\xe4veinneh\xe5ll i plasma.'],
             ['Skin', u'utslag, erytem'],
             ['Metabolism', u'Anorexi (f\xf6rlorad aptit)'],
             ['Infections', u'lunginflammation, sepsis, rhinit.'],
             ['General', u'Tr\xf6tthet, \xf6dem.'],
             ['Hepato', u'Levertoxicitet. F\xf6rh\xf6jda leverenzym-v\xe4rden (ALAT).']]],
           ['Uncommon',
            [['Eye', u'Reversibel bl\xe5f\xe4rgning av sklera har rapporterats.'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Skin', u'Bl\xe5 missf\xe4rgning av hud och naglar.'],
             ['General', u'. Allergiska reaktioner (dvs.. exantem, dyspn\xe9, hypotension).'],
             ['Psychiatric',
              u'oro, f\xf6rvirring Tum\xf6rlys-syndrom (karakteriserat av hyperurikemi, hyperkalemi, hyperfosfatemi och hyperkalcemi) har observerats i s\xe4llsynta fall under monoterapi med mitoxantron, liksom under kombinationsbehandling. Hos patienter med leukemi \xe4r biverkningsm\xf6nstret i allm\xe4nhet likartat, men biverkningar f\xf6rekommer mer frekvent och med \xf6kad sv\xe5righetsgrad. Detta g\xe4ller s\xe4rskilt stomatit och mukosit. Tv\xe5 fall av pl\xf6tslig d\xf6d har rapporterats hos patienter med Multipel skleros som behandlas med mitoxantron. Det \xe4r ok\xe4nt om det finns ett samband med anv\xe4ndningen av mitoxantron.']]],
           ['Very rare', [['Investigations', u'Viktf\xf6r\xe4ndringar']]],
           ['Unknown',
            [['Cardiac',
              u'; Kardiomyopati och hj\xe4rtinfarkt (myokardinfarkt) har rapporterats.'],
             ['Eye', u'Konjunktivit.'],
             ['GI', u'Pankreatit.'],
             ['Skin',
              u'Nagelrubbningar (t ex onykolys, nageldystrofi), extravasering vid infusionsomr\xe5det har rapporterats vilket kan leda till erytem, svullnad, sm\xe4rta, br\xe4nnande k\xe4nsla och/eller bl\xe5 missf\xe4rgning av hud. Extravasering kan leda till v\xe4vnadsd\xf6d som kan kr\xe4va debridering och hudtransplantation.'],
             ['Metabolism', u'Hyperuricaemia.'],
             ['Infections', u'Opportunistisk infektion.'],
             ['Injury', u'Bl\xe5m\xe4rken.'],
             ['Neoplasms',
              u'Akut leukemi. Topoisomeras II-h\xe4mmare, inklusive mitoxantron, i kombination med andra onkologiska l\xe4kemedel och/eller str\xe5lning har f\xf6rknippats med utveckling av akut myeloisk leukemi (AML) eller myelodysplastiskt syndrom (MDS) (se \xe4ven avsnitt 4.5 Interaktioner med andra l\xe4kemedel och \xf6vriga interaktioner).'],
             ['General', u'Flebit har rapporterats vid infusionsomr\xe5det. Svaghet.'],
             ['Immune system', u'Anafylaktisk reaktion (inklusive anafylaktisk chock).']]]],
 '_pages': [6, 9],
 u'_rank': 35,
 u'_type': u'LSFU'}