{'_data': [[u'Unknown',
            [['Infections', u'Blindtarmsinflammation, bakteriemi, intestinal abscess,'],
             ['Blood', u'Lymfadenopati.'],
             ['Immune system', u'\xd6verk\xe4nslighet med en l\xe5ng rad symtom, bland annat'],
             ['Metabolism', u'Hyperglykemi har rapporterats hos diabetespatienter.'],
             ['Psychiatric', u'\xc5ngest, f\xf6rvirring, nervositet och relaterade symtom har'],
             ['Nervous system',
              u'F\xf6rlust av medvetande, synkope, vasovagal synkope, yrsel, en   br\xe4nnande k\xe4nsla, huvudv\xe4rk, dysartri, hypotoni.'],
             ['Eye', u'\xd6gonsjukdomar, inklusive svullnad i \xf6gon, vanligtvis'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac', u'Bradykardi, cyanos, takykardi,  onormalt EKG.'],
             ['Vascular', u'Hypotoni, blekhet, vasodilatation.'],
             ['Respiratory',
              u'Bronkialspasm, dyspn\xe9, larynx\xf6dem, faryngealt \xf6dem och   sm\xe4rta, irritation eller svullnad i halsen, hosta.   Vid oral administrering: aspirering,  aspirationspneumonit.'],
             ['GI', u'Magtarmkanalssymtom rapporteras ofta; emellertid \xe4r det inte'],
             ['Skin', u'Hudreaktioner varierar och \xe4r sannolikt f\xf6rknippade med'],
             ['Renal', u'Dysuri.'],
             ['General',
              u'Obehag, sm\xe4rta, svullnad, kraftl\xf6shet, pyrexi, ansikts\xf6dem.'],
             ['Injury', u'Oavsiktlig intravasal administration av bariumsulfat, f\xf6rknippat']]]],
 '_pages': [6, 7],
 u'_rank': 16,
 u'_type': u'LFSU'}