{'_data': [['Very common',
            [['General', u'Asteni och/'],
             ['Nervous system', u'Parestesier i de nedre extremi-teterna'],
             ['Skin', u'Hyperhidros'],
             ['Vascular', u'V\xe4rme-vallningar']]],
           ['Common',
            [['GI', u'Illam\xe5ende'],
             ['General',
              u'Tr\xf6tthet, erytem vid injektions-st\xe4llet, inflammation vid injektions-st\xe4llet, sm\xe4rta vid injektions-st\xe4llet, reaktion vid injektions-st\xe4llet, \xf6dem'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Psychiatric', u'F\xf6rlust av libido, depression*, hum\xf6r-sv\xe4ngningar*'],
             ['Reproductive system', u'Erektil dysfunktion']]],
           ['Uncommon',
            [['Ear', u'Tinnitus'],
             ['GI', u'Buksm\xe4rta, f\xf6rstoppning, diarr\xe9, kr\xe4kningar'],
             ['General', u'Letargi, sm\xe4rta, stelhet, somnolens'],
             ['Investigations',
              u'\xd6kning i ALAT, ASAT, \xf6kning i blodkreatinin, \xf6kning i blodurea, vikt\xf6kning'],
             ['Metabolism', u'Anorexi, gikt, aptit\xf6kning'],
             ['Nervous system', u'Parestesier'],
             ['Psychiatric', u'Insomnia, irritabilitet'],
             ['Reproductive system',
              u'Gynekomasti, br\xf6stsm\xe4rta, testikelatrofi, testikelsm\xe4rta'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Skin', u'Akne, alopeci, pruritus, hudutslag'],
             ['Vascular', u'Hypertoni']]],
           ['Rare',
            [['Blood', u'Purpura'],
             ['Ear', u'Yrsel'],
             ['Endocrine', u'Diabetes mellitus'],
             ['Eye', u'Onormal k\xe4nsla i \xf6gonen, synrubb-ningar'],
             ['GI', u'Buk-sp\xe4nningar, muntorrhet, dysgeusi, flatulens'],
             ['General',
              u'Br\xf6stsm\xe4rta, Sjukdomsk\xe4nsla dysstasi (sv\xe5righet att st\xe5), influensa-liknande symtom, br\xe4nnande k\xe4nsla'],
             ['Immune system', u'Anafylaktisk reaktion, \xf6verk\xe4ns-lighet'],
             ['Infections', u'Nasofaryngit'],
             ['Investigations',
              u'\xd6kning i alkalisk fosfatas i blodet, \xf6kad kropps-temperatur, viktminsk-ning'],
             ['Nervous system', u'Minnes-f\xf6rs\xe4mring'],
             ['Psychiatric', u'F\xf6rvirring, minskad aktivitet, eufori'],
             ['Reproductive system', u'Utebliven ejakulation'],
             ['Respiratory', u'Ortopn\xe9 N\xe4sblod'],
             ['Skin', u'Bl\xe5sor'],
             ['Vascular', u'Hypotoni']]],
           ['Unknown',
            [['Eye', u'Dimsyn'],
             ['Investigations', u'F\xf6rh\xf6jt blodtryck'],
             ['Psychiatric', u'Oro'],
             ['Skin', u'Angioneurotiskt \xf6dem, urtikaria']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 5],
 u'_rank': 39,
 u'_type': u'MSFU'}