{'_data': [['Very common', [['Nervous system', u'huvudv\xe4rk']]],
           ['Common',
            [['Metabolism', u'minskad aptit'],
             ['Psychiatric',
              u'nervositet, insomnia, \xe5ngest, depression, onormala tankar, f\xf6rvirring, irritabilitet'],
             ['Nervous system', u'yrsel, somnolens, parestesier'],
             ['Eye', u'dimsyn'],
             ['Cardiac', u'takykardi, palpitation'],
             ['Vascular', u'vasodilatation'],
             ['GI',
              u'buksm\xe4rta, illam\xe5ende, muntorrhet, diarr\xe9, dyspepsi, f\xf6rstoppning'],
             ['General', u'asteni, br\xf6stsm\xe4rtor'],
             ['Investigations',
              u'onormala leverfunktionstester, dosrelaterad f\xf6rh\xf6jning av alkalinfosfatas och gammaglutamyltransferas har observerats']]],
           ['Uncommon',
            [['Infections', u'faryngit, sinuit'],
             ['Blood', u'eosinofili, leukopeni'],
             ['Immune system', u'lindrig allergisk reaktion (t ex h\xf6snuvesymtom)'],
             ['Metabolism',
              u'hyperkolesterolemi, hyperglykemi, diabetes mellitus, \xf6kad aptit'],
             ['Psychiatric',
              u's\xf6mnst\xf6rning, emotionell labilitet, minskad libido, fientlighet, depersonalisation, personlighetsst\xf6rning, onormala dr\xf6mmar, agitation, aggression, sj\xe4lvmordstankar, psykomotorisk hyperaktivitet'],
             ['Nervous system',
              u'dyskinesi, hypertoni, hyperkinesi, amnesi, migr\xe4n, tremor, vertigo, CNS stimulering, hypoastesi, inkoordination, r\xf6relsest\xf6rning, talst\xf6rning, smakperversion'],
             ['Eye', u'synst\xf6rning, torra \xf6gon'],
             ['Cardiac', u'extrasystole, arytmi, bradykardi'],
             ['Vascular', u'hypertension, hypotension'],
             ['Respiratory', u'dyspn\xe9, \xf6kad hosta, astma, epistaxis, rinit'],
             ['GI', u'flatulens, reflux, kr\xe4kning, dysfagi, glossit, muns\xe5r'],
             ['Skin', u'svettning, utslag, akne, pruritus'],
             ['Musculoskeletal',
              u'ryggv\xe4rk, nackv\xe4rk, myalgi, myasteni, benkramper, artralgi, ryckningar'],
             ['Renal', u'onormal urin, frekventa urint\xf6mningar'],
             ['Reproductive system', u'menstruationsrubbningar'],
             ['General', u'perifera \xf6dem, t\xf6rst'],
             ['Investigations', u'onormalt EKG, vikt\xf6kning, viktminskning']]],
           ['Rare', [['Psychiatric', u'hallucinationer, mani, psykos']]],
           ['Unknown',
            [['Immune system',
              u'angio\xf6dem, urtikaria (n\xe4sselutslag), allergiska reaktioner (med feber, hudutslag, lymfadenopati och tecken p\xe5 samtidig p\xe5verkan p\xe5 andra organ), anafylaxi'],
             ['Psychiatric', u'vanf\xf6rest\xe4llningar'],
             ['Skin',
              u'allvarliga hudreaktioner, inklusive erythema multiforme, Steven-Johnsson syndrom, toxisk epidermal nekrolys och l\xe4kemedelsutl\xf6st utslag med eosinofili och systemiska symtom (DRESS)']]]],
 '_pages': [5, 7],
 u'_rank': 31,
 u'_type': u'LSFU'}