{'_data': [['Common', [['Nervous system', u'D\xe5sighet (ca 3\u201310%)']]],
           ['Uncommon',
            [['Nervous system',
              u'Ataxi, koncentrationssv\xe5righeter, nedsatt reaktionsf\xf6rm\xe5ga, muskelsvaghet, domningar'],
             ['Skin', u'Mindre vanlig (>1/1 000, <1/100) Yrsel, huvudv\xe4rk']]],
           ['Very rare',
            [['Nervous system', u'Depression'],
             ['Eye', u'Dubbelseende'],
             ['GI', u'Magbesv\xe4r'],
             ['Skin',
              u'Allergiska hudreaktioner Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Psychiatric',
              u'Paradoxala reaktioner s\xe5som excitationstillst\xe5nd, aggressivitet, hallucinationer, mardr\xf6mmar, f\xf6rvirring, rastl\xf6shet, agitation, irritabilitet, psykoser \xd6vrigt'],
             ['Psychiatric',
              u'Hypersalivation, bronkial hypersekretion, anterograd amnesi, f\xf6r\xe4ndrad libido Magbesv\xe4r, bl a i form av diarr\xe9, har i s\xe4llsynta fall observerats. D\xe5sighet, domningar, nedsatt reaktionsf\xf6rm\xe5ga, f\xf6rvirring, huvudv\xe4rk, yrsel, muskelsvaghet, ataxi och synst\xf6rningar kan upptr\xe4da initialt, men minskar vanligen efter n\xe5gra dagar. Hos \xe4ldre kan f\xf6rvirringstillst\xe5nd upptr\xe4da vid f\xf6r h\xf6g dosering. F\xf6r att minska risken f\xf6r anterograd amnesi b\xf6r patienten sova ost\xf6rt i 7\u20138 timmar efter intaget. En underliggande depression kan maskeras av bensodiazepiner.']]]],
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'LSFU'}