{'_data': [['Common',
            [['Skin', u'Pruritus och lokal hudatrofi.'],
             ['Skin', u'V\xe4rmek\xe4nsla p\xe5 det behandlade hudomr\xe5det.']]],
           ['Uncommon',
            [['Skin', u'Striae, rosacealiknande dermatit, ekkymoser, follikuliter.'],
             ['Infections', u'Infektion.']]],
           ['Rare',
            [['Endocrine', u'Binjuresuppression.'],
             ['Skin', u'Hypertrikos, hypopigmentering.'],
             ['Immune system', u'\xd6verk\xe4nslighet.']]],
           ['Unknown',
            [['Skin',
              u'Hudirritation, uppmjukning av huden, torr hud, akneiform dermatit, dermatit, kontaktdermatit, hudavflagning, telangiektasi, miliaria. Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]]],
 '_pages': [2, 3],
 u'_rank': 8,
 u'_type': u'LSFU'}