{'_data': [['Common',
            [['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndringar Nedsatt libido'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Akne'],
             ['Reproductive system',
              u'Br\xf6stsm\xe4rta, oregelbunden bl\xf6dning, amenorr\xe9'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'Vaginal infektion'],
             ['Eye', u'Intolerans mot kontaktlinser'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'Alopeci'],
             ['Reproductive system', u'Dysmenorr\xe9, ovariecysta'],
             ['General', u'Tr\xf6tthet']]],
           ['Rare', [['Skin', u'Utslag, urtikaria, erythema nodosum']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 13,
 u'_type': u'MSFU'}