{'_data': [['Very common', [['Infections', u'\xf6vre luftv\xe4gsinfektion']]],
           ['Common',
            [['GI', u'diarr\xe9  illam\xe5ende  kr\xe4kningar .'],
             ['Hepato', u'f\xf6rh\xf6jda leverenzymer (ALAT  och ASAT)'],
             ['Skin', u'utslag']]],
           ['Uncommon',
            [['Immune system', u'\xf6verk\xe4nslighetsreaktioner  inkluderande anafylaxi och'],
             ['Psychiatric',
              u'f\xf6r\xe4ndrat dr\xf6mm\xf6nster  inklusive mardr\xf6mmar, s\xf6mnl\xf6shet, s\xf6mng\xe5ng, irritabilitet, \xe5ngest, rastl\xf6shet, agitation inkluderande aggressivt beteende eller fientlighet, depression'],
             ['Nervous system', u'yrsel, d\xe5sighet,  parestesi/hypestesi, krampanfall'],
             ['Respiratory', u'epistaxis'],
             ['GI', u'muntorrhet, dyspepsi,'],
             ['Skin', u'bl\xe5m\xe4rken, urtikaria, pruritus'],
             ['Musculoskeletal', u'artralgi, myalgi inkluderande  muskelkramper']]],
           ['Rare',
            [['Blood', u'\xf6kad bl\xf6dningstendens'],
             ['Psychiatric', u'tremor'],
             ['Cardiac', u'palpitationer'],
             ['Skin', u'angio\xf6dem']]],
           ['Very rare',
            [['Immune system', u'hepatisk eosinofilinfiltration'],
             ['Psychiatric', u'hallucinationer, desorientering  suicidala tankar och beteende'],
             ['Respiratory', u'Churg-Strauss syndrome (CSS)  (se avsnitt 4.4)'],
             ['Hepato',
              u'hepatit (inkluderande  kolestatisk, hepatocellul\xe4r och leverskada av blandform).'],
             ['Skin', u'erythema nodosum, erythema  multiforme']]]],
 '_pages': [3, 5],
 u'_rank': 20,
 u'_type': u'TSFU'}