{'_data': [['Very rare',
            [['General',
              u'fall av Churg-Strauss syndrom (CSS) har rapporterats under montelukastbehandlingen hos astmapatienter. (se avsnitt 4.4).']]],
           ['Unknown',
            [['GI',
              u'Vid l\xe5ngtidsbehandling i kliniska studier med ett begr\xe4nsat antal patienter, upp till 2 \xe5r f\xf6r vuxna och upp till 6 m\xe5nader f\xf6r barn mellan 6-14 \xe5rs \xe5lder, \xe4ndrades inte s\xe4kerhetsprofilen. F\xf6ljande biverkningar har rapporterats med frekvensen mycket s\xe4llsynta efter godk\xe4nnandet'],
             ['Infections', u'\xf6vre luftv\xe4gsinfektion'],
             ['Blood', u'\xf6kad bl\xf6dningstendens.'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inkluderande anafylaxi och hepatisk eosinofilinfiltration.'],
             ['Psychiatric',
              u'f\xf6r\xe4ndrat dr\xf6mm\xf6nster inklusive mardr\xf6mmar, hallucinationer, s\xf6mnl\xf6shet, s\xf6mng\xe5ng, irritabilitet, \xe5ngest, rastl\xf6shet, agitation inkluderande aggressivt beteende eller fientlighet, tremor, depression, suicidala tankar och beteende i mycket s\xe4llsynta fall.'],
             ['Nervous system', u'yrsel, d\xe5sighet, parestesi/hypestesi, krampanfall.'],
             ['Cardiac', u'palpitationer'],
             ['Respiratory', u'epistaxis.'],
             ['GI',
              u'dyspepsi, diarr\xe9, muntorrhet, illam\xe5ende, kr\xe4kningar. Lever och gallv\xe4gar : f\xf6rh\xf6jda niv\xe5er av transaminaser (ALAT och ASAT), hepatit (inkluderande kolestatisk, hepatocellul\xe4r och leverskada av blandform).'],
             ['Skin',
              u'angio\xf6dem, bl\xe5m\xe4rken, urtikaria, pruritus, utslag, erythema nodosum. Muskuloskeletala systemet och bindv\xe4v : artralgi, myalgi inkluderande muskelkramper.'],
             ['General', u'asteni/tr\xf6tthet, allm\xe4n sjukdomsk\xe4nsla, \xf6dem, feber.']]]],
 '_pages': [3, 4],
 u'_rank': 12,
 u'_type': u'LSFU'}