{'_data': [['Common',
            [['Endocrine', u'\xf6kad ADH-fris\xe4ttning.'],
             ['Nervous system', u'sedering.'],
             ['Eye', u'mios.'],
             ['GI', u'opstipation, illam\xe5ende, kr\xe4kningar.'],
             ['Renal', u'urinretention.']]],
           ['Uncommon',
            [['Psychiatric', u'dysfori.'],
             ['Nervous system', u'andningsdepression.'],
             ['Respiratory', u'bronkokonstriktion.'],
             ['Hepato', u'gallv\xe4gsspasm.'],
             ['Skin', u'kl\xe5da'],
             ['Renal', u'urinv\xe4gsspasm.'],
             ['General',
              u'omt\xf6ckning. Sederingen avtar som regel efter n\xe5gra dagars tillf\xf6rsel. Illam\xe5ende och kr\xe4kningar avtar ofta vid l\xe4ngre tids bruk. Spasm i gall- och urinv\xe4gar kan upptr\xe4da hos disponerade personer. Den andningsdepressiva effekten \xe4r dosberoende och utg\xf6r s\xe4llan n\xe5got kliniskt problem. Tillv\xe4njning och tolerans brukar ej medf\xf6ra n\xe5gra problem vid behandling av sv\xe5ra cancersm\xe4rtor.']]],
           ['Rare', [['Vascular', u'ortostatisk hypotension.']]]],
 '_pages': [2, 3],
 u'_rank': 13,
 u'_type': u'LSFU'}