{'_data': [['Common',
            [['Eye', u'ackommodationsbesv\xe4r (skopolamin i h\xf6g dos).'],
             ['Cardiac', u'\xf6kad hj\xe4rtfrekvens (skopolamin).'],
             ['GI', u'muntorrhet (skopolamin).']]],
           ['Uncommon',
            [['Nervous system',
              u'andningsdepression (morfin), omt\xf6ckning (morfin), dysfori (morfin).'],
             ['GI', u'illam\xe5ende och kr\xe4kningar (morfin), obstipation (morfin).'],
             ['Renal',
              u'miktionsbesv\xe4r (skopolamin). Muntorrhet inneb\xe4r risk f\xf6r tand- och slemhinneskador vid l\xe4ngre tids bruk. Tillv\xe4njningsrisken och euforiserande effekt b\xf6r beaktas.']]],
           ['Rare', [['Nervous system', u'excitation (skopolamin i h\xf6g dos).']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'LSFU'}