{'_data': [['Very common',
            [['GI', u'Buksm\xe4rta, illam\xe5ende,  buksp\xe4nningar, anala besv\xe4r.'],
             ['General', u'Sjukdomsk\xe4nsla.']]],
           ['Common',
            [['Psychiatric', u'S\xf6mnst\xf6rningar.'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk.'],
             ['GI', u'Kr\xe4kningar, dyspepsi.'],
             ['General', u'Stelhet, t\xf6rst, hunger.']]],
           ['Uncommon',
            [['GI', u'Dysfagi.'],
             ['Hepato', u'Avvikande  leverfunktionsv\xe4rden.'],
             ['General', u'Obehagsk\xe4nsla.']]],
           ['Unknown',
            [['Nervous system', u'Konvulsioner i samband med  sv\xe5r hyponatremi.'],
             ['GI', u'']]]],
 '_pages': [4, 5],
 u'_rank': 10,
 u'_type': u'TSFU'}