{'_data': [['Very common',
            [['GI', u'Buksm\xe4rta, illam\xe5ende,  buksp\xe4nningar, anala besv\xe4r.'],
             ['General', u'Sjukdomsk\xe4nsla.']]],
           ['Common',
            [['Psychiatric', u'S\xf6mnst\xf6rningar.'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk.'],
             ['GI', u'Kr\xe4kningar, dyspepsi.'],
             ['General', u'Stelhet, t\xf6rst, hunger.']]],
           ['Uncommon',
            [['GI', u'Dysfagi.'],
             ['Hepato', u'Avvikande  leverfunktionsv\xe4rden.'],
             ['General', u'Obehagsk\xe4nsla.']]],
           ['Unknown',
            [['Immune system', u'Anafylaxi.'],
             ['Nervous system', u'Konvulsioner i samband med  sv\xe5r hyponatremi.'],
             ['Cardiac', u'\xd6verg\xe5ende f\xf6rh\xf6jt blodtryck.'],
             ['GI', u'Flatulens, kv\xe4ljningar.'],
             ['Skin', u'Pruritus, urtikaria, kl\xe5da.'],
             ['Investigations',
              u'Elektrolytrubbningar inklusive  minskning av bikarbonat i blodet, hyper- och hypokalcemi, hypofosfatemi, hypokalaemia och hyponatremi (de senare tv\xe5 rubbningarna mer vanligt f\xf6rekommande hos patienter som samtidigt tar mediciner som p\xe5verkar njurarna, s\xe5som ACE-h\xe4mmare och diuretika) och f\xf6r\xe4ndringar av kloridniv\xe5er i blodet.']]]],
 '_pages': [3, 4],
 u'_rank': 15,
 u'_type': u'TSFU'}