{'_data': [['Very common',
            [['GI',
              u'Buksm\xe4rta, diarr\xe9, kr\xe4kning,  illam\xe5ende, borborygmi, gasbildning och obehag']]],
           ['Common',
            [['Immune system', u'Kl\xe5da'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['General', u'Perifert \xf6dem']]],
           ['Uncommon', [['Immune system', u'Utslag'], ['GI', u'Dyspepsi, bukdistension']]],
           ['Very rare',
            [['Immune system',
              u'Allergiska reaktioner, inklusive  anafylaxi, angio\xf6dem, dyspn\xe9, erytem, urtikaria och rinit'],
             ['Metabolism', u'Elektrolytrubbningar, s\xe4rskilt  hyperkalemi och hypokalemi'],
             ['GI', u'Analt obehag']]]],
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'TSFU'}