{'_data': [['Very common', [['GI', u'muntorrhet']]],
           ['Common',
            [['Nervous system', u'huvudv\xe4rk , yrsel/vertigo, somnolens, d\xe5sighet'],
             ['Vascular', u'vasodilatation'],
             ['GI',
<<<<<<< HEAD
              u'diarr\xe9, f\xf6rstoppning, illam\xe5ende/kr\xe4kningar st\xf6rningar i magtarmkanalen'],
=======
              u'diarr\xe9, f\xf6rstoppning, illam\xe5ende/kr\xe4kningar, st\xf6rningar i magtarmkanalen'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Skin', u'utslag/kl\xe5da'],
             ['General', u'asteni'],
             ['Musculoskeletal', u'ryggsm\xe4rta'],
             ['Psychiatric',
              u'kognitiv p\xe5verkan, s\xf6mnst\xf6rningar inklusive s\xf6mnl\xf6shet']]],
           ['Uncommon',
            [['Metabolism', u'v\xe4tskeretention, anorexi'],
             ['Cardiac', u'bradykardi'],
             ['Ear', u'tinnitus'],
             ['Nervous system', u'synkope , sedation, parestesi i extremiteterna'],
             ['Eye', u'torr, kliande eller br\xe4nnande k\xe4nsla i \xf6gat'],
             ['Vascular',
              u'Hypotension* (inklusive ortostatisk hypotension), perifera cirkulationsst\xf6rningar'],
             ['GI', u'sm\xe4rta i \xf6ronspottk\xf6rteln'],
             ['Skin', u'allergiska hudreaktioner, angio\xf6dem'],
             ['General', u'\xf6dem'],
             ['Musculoskeletal', u'nacksm\xe4rta'],
             ['Reproductive system', u'gynekomasti, impotens'],
             ['Psychiatric', u'oro, depression, \xe5ngest, minskad libido']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 20,
 u'_type': u'MSFU'}