{'_data': [['Common',
            [['Cardiac', u'Hj\xe4rtsvikt (se stycke c)'],
             ['GI', u'Diarr\xe9 Kr\xe4kningar'],
             ['Hepato', u'Avvikande'],
             ['Skin', u'Utslag'],
             ['General', u'Tr\xf6tthet'],
             ['Investigations', u'Stegring av kreatinin i blodet* F\xf6rl\xe4ngd QTc (Bazett)'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Illam\xe5ende Buksm\xe4rtor Dyspepsi'],
             ['Hepato', u'leverfunktionsv\xe4rd en'],
             ['Skin',
              u'(inklusive generaliserade, makul\xf6sa, makulopapul\xf6sa) Kl\xe5da (pruritus)'],
             ['General', u'Asteni']]],
           ['Uncommon',
            [['Immune system', u'Anafylaktiska reaktioner'],
             ['Nervous system', u'Smakrubbningar'],
             ['Respiratory',
              u'Interstitiell lungsjukdom inklusive pneumonit och pulmonell fibros (se stycke c)'],
             ['Hepato', u'Hepatocellul\xe4r'],
             ['Skin',
              u'Erytem (inklusive erytem och erytemat\xf6sa utslag) Eksem Fotosensitivitets-reaktioner Allergisk dermatit Dermatit']]],
           ['Rare',
            [['Immune system', u'inklusive angio\xf6dem'],
             ['Nervous system', u'Smakf\xf6rlust'],
             ['Hepato', u'leverskada, inklusive livshotande akut leversvikt (se avsnitt 4.4)']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 11],
 u'_rank': 19,
 u'_type': u'MSFU'}