{'_data': [['Very common',
            [['Blood', u'Leukopeni.'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Diarr\xe9'],
             ['Skin',
              u'Alopeci (reversibel efter avslutad behandling; \xf6kat h\xe5ravfall kan forts\xe4tta i flera veckor efter att behandlingen avslutats), \xf6kad svettning.'],
             ['Musculoskeletal', u'Myalgi, artralgi.'],
             ['Metabolism', u'Anorexi, illam\xe5ende, hypokalcemi utan klinisk betydelse.'],
             ['General',
              u'Influensaliknande symtom, tr\xf6tthet, feber, stelhet, minskad aptit.']]],
           ['Common',
            [['Blood', u'Trombocytopeni, anemi.'], ['GI', u'Illam\xe5nde/kr\xe4kning']]],
           ['Uncommon',
            [['Investigations',
              u'): \xd6kningar av ALAT, alkaliskt fosfatas i blodet samt transaminaser, viktnedg\xe5ng.'],
             ['Cardiac', u'Arytmier, inklusive atrioventrikul\xe4rblock, palpitationer.'],
             ['Nervous system',
              u'Neuropati, yrsel, somnolens, dysgeusi, parestesi, hypoestesi, tremor.'],
             ['Eye', u'Konjunktivitit, synst\xf6rningar.'],
             ['Ear', u'Vertigo.'],
             ['GI', u'Buksm\xe4rta, muntorrhet.'],
             ['Renal', u'Proteinuri och \xf6kat antal celler i urinen.'],
             ['Skin', u'Exacerbation av eller provokation av psoriasis, pruritus.'],
             ['Metabolism', u'Rubbad elektrolytbalans, dehydrering.'],
             ['Vascular', u'Hypertension, hypotension.'],
             ['General', u'Br\xf6stsm\xe4rta, \xf6dem.'],
             ['Psychiatric',
              u'Depression, \xe5ngest, f\xf6r\xe4ndrad mental status, f\xf6rvirringstillst\xe5nd, beteendest\xf6rningar, nervositet, f\xf6rs\xe4mrat minne, s\xf6mnst\xf6rningar.']]],
           ['Rare',
            [['Investigations',
              u'\xd6kningar i blodet av LDH, bilirubin, kreatinin, urinsyra, urea.'],
             ['Cardiac',
              u'Hj\xe4rtstillest\xe5nd, hj\xe4rtinfarkt, kronisk hj\xe4rtsvikt, pulmonella \xf6dem och cyanos.'],
             ['Blood', u'Agranulocytos, hemolytisk anemi.'],
             ['Nervous system',
              u'Koma, cerebrovaskul\xe4r h\xe4ndelse, konvulsioner, \xf6verg\xe5ende erektil dysfunktion.'],
             ['Eye', u'Ischemisk retinopati.'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Hypermotilitet, f\xf6rstoppning, dyspepsi, flatulens, pankreatit.'],
             ['Renal',
              u'Akut njursvikt (fr\xe4mst hos cancerpatienter med njursjukdom), nedsatt njurfunktion.'],
             ['Skin', u'Hudutslag, torr hud och slemhinnor, epistaxis, rinorr\xe9.'],
             ['Musculoskeletal', u'Systemisk lupus erytematosus, artrit.'],
             ['Endocrine', u'Hypertyroidism, hypotyroidism, tyroideast\xf6rning.'],
             ['Metabolism', u'Hyperglykemi.'],
             ['Infections',
              u'Pneumoni, herpes simplex (inklusive exacerbation av herpes labialis).'],
             ['Vascular', u'Vaskulit.'],
             ['Immune system',
              u'Autoimmun sjukdom, akuta \xf6verk\xe4nslighetsreaktioner (t.ex. urtikaria, angio\xf6dem, bronkospasm och anafylaxi).'],
             ['Hepato', u'Leversvikt, leverp\xe5verkan, nedsatt leverfunktion.'],
             ['Psychiatric',
              u'Sj\xe4lvmord, sj\xe4lvmordsf\xf6rs\xf6k, sj\xe4lvmordstankar. Betr\xe4ffande viruss\xe4kerhet se avsnitt 4.4. Dentala och periodontala \xe5kommor (som kan leda till tandavlossning) och h\xf6rselbortfall har betraktats s\xe5som eventuella klasseffekter av alfainterferonbehandling.']]],
           ['Very rare',
            [['Blood', u'Idiopatisk trombocytopen purpura.'],
             ['Eye',
              u'Optisk neuropati, obstruktion i retinal art\xe4r eller ven, retinopati, retinalbl\xf6dning, papill\xf6dem, retinalexudat.'],
             ['GI', u'Recidiv av mags\xe5r, icke livshotande gastrointestinal bl\xf6dning.'],
             ['Metabolism', u'Diabetes mellitus, hypertriglyceridemi.'],
             ['General',
              u'Nekrotiska reaktioner vid injektionsst\xe4llet, reaktioner vid injektionsst\xe4llet.'],
             ['Immune system', u'Sarkoidos.']]],
           ['Unknown', [['Musculoskeletal', u'Rabdomyolys']]]],
 '_pages': [6, 8],
 u'_rank': 45,
 u'_type': u'LSFU'}