<<<<<<< HEAD
{'_data': [['Very common', [['Other', u')']]],
           ['Common',
            [['Blood', u'Pancytopeni, leukocytos Metabolism och nutrition Mycket vanliga'],
             ['Blood',
              u'Acidos, hyperkalemi, hypokalemi, hyperglykemi, hypomagnesemi, hypokalcemi, hyperkolesterolemi, hyperlipidemi, hypofosfatemi, hyperurikemi, gikt, anorexi Psykiska st\xf6rningar Mycket vanliga'],
             ['Blood',
              u'Agitation, f\xf6rvirringstillst\xe5nd, depression, \xe5ngest, onormala tankar, s\xf6mnl\xf6shet Centrala och perifera Mycket vanliga nervsystemet Vanliga Krampanfall, hypertension, darrningar, s\xf6mnighet, muskelsvaghetssyndrom, yrsel, huvudv\xe4rk, parestesi, smakst\xf6rning Hj\xe4rtat Mycket vanliga'],
             ['Blood', u'Takykardi Blodk\xe4rl Mycket vanliga'],
             ['Blood',
              u'Hypotension, hypertension, vasodilatation Andningsv\xe4gar, br\xf6stkorg och Mycket vanliga mediastinum'],
             ['Blood',
              u'Utgjutning i lungs\xe4cken, dyspn\xe9, hosta Gastrointestinal disorders Mycket vanliga Kr\xe4kning, magsm\xe4rta, diarr\xe9, illam\xe5ende'],
             ['Blood',
              u'Gastrointestinal bl\xf6dning, peritonit, ileus, kolit, mags\xe5r, duodenals\xe5r, gastrit, esofagit, stomatit, f\xf6rstoppning, dyspepsi, flatulens, rapning Lever och gallv\xe4gar Mycket vanliga'],
             ['Blood',
              u'Hepatit, gulsot, hyperbilirubinemi Hud och subkutan v\xe4vnad Mycket vanliga'],
             ['Blood',
              u'Hudhypertrofi, hudutslag, akne, alopeci Muskuloskeletala systemet och Mycket vanliga bindv\xe4v'],
             ['Blood', u'Artralgi Njurar och urinv\xe4gar Mycket vanliga'],
             ['Blood',
              u'Nedsatt njurfunktion Allm\xe4nna symtom och symtom Mycket vanliga vid administreringsst\xe4llet'],
             ['Blood',
              u'\xd6dem, feber, frossbrytningar, sm\xe4rta, sjukdomsk\xe4nsla, asteni Unders\xf6kningar Mycket vanliga'],
             ['Blood',
              u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jt blodkreatinin, f\xf6rh\xf6jt LDH (laktatdehydrogenas) i blodet, f\xf6rh\xf6jd blodurea, \xf6kning av alkaliska fosfataser i blodet, viktminskning Observera: 501 (2 g mykofenolatmofetil dagligen), 289 (3 g mykofenolatmofetil dagligen) och 277 (2 g i.v./3 g oralt mykofenolatmofetil dagligen) patienter behandlades i Fas III studier f\xf6r profylax mot avst\xf6tning vid njur-, hj\xe4rt- respektive levertransplantation. F\xf6ljande biverkningar avser erfarenheter av biverkningar efter marknadsintroduktion: De typer av biverkningar som rapporterats efter marknadsintroduktionen av mykofenolatmofetil \xe4r de samma som setts i de kontrollerade njur-, hj\xe4rt- och levertransplantationsstudierna. Ytterligare biverkningar som rapporterats efter marknadsintroduktionen beskrivs nedan med frekvensen angiven i parentes om den \xe4r k\xe4nd. Gastrointestinala: Gingivalhyperplasi (\u22651/100 till <1/10), kolit inklusive cytomegaloviruskolit (\u22651/100, <1/10), pankreatit (\u22651/100, <1/10) och tarmluddsatrofi. Sjukdomar relaterade till immunsuppressiv behandling: Allvarliga och livshotande infektioner inkluderande meningit, endokardit, tuberkulos och atypisk mykobakterieinfektion. Fall av BK-virus-associerad nefropati, liksom fall av JC-virus-associerad progressiv multifokal leukoencefalopati (PML) har rapporterats hos patienter behandlade med immunsuppressiva l\xe4kemedel, inklusive mykofenolatmofetil. Agranulocytos (\u22651/1000, <1/100) och neutropeni har rapporterats, och d\xe4rf\xf6r rekommenderas regelbunden kontroll av patienter som f\xe5r mykofenolatmofetil (se avsnitt 4.4). Fall av aplastisk anemi och benm\xe4rgssuppression har rapporterats hos patienter som behandlats med mykofenolatmofetil, i n\xe5gra fall med d\xf6dligt f\xf6rlopp.']]],
           ['Rare', [['Other', u')']]],
=======
{'_data': [['Very common', [['Other', u'0)']]],
           ['Common',
            [['Other', u'(\u22651/100, <1/10)'],
             ['Other',
              u'Pneumoni, influensa, luftv\xe4gsinfektion, candidainfektion i luftv\xe4garna, gastrointestinal infektion, candidainfektion, gastroenterit, infektion, bronkit, faryngit, sinuit, hudsvamp, candidainfektion i huden, vaginal candidainfektion, rinit Neoplasier; benigna, maligna Mycket vanliga och ospecificerade (samt cystor och polyper) Vanliga Hudcancer, godartad hudtum\xf6r Blodet och lymfsystemet Mycket vanliga Leukopeni, trombocytopeni, anemi'],
             ['Other', u'Pancytopeni, leukocytos Metabolism och nutrition Mycket vanliga'],
             ['Other',
              u'Acidos, hyperkalemi, hypokalemi, hyperglykemi, hypomagnesemi, hypokalcemi, hyperkolesterolemi, hyperlipidemi, hypofosfatemi, hyperurikemi, gikt, anorexi Psykiska st\xf6rningar Mycket vanliga'],
             ['Other',
              u'Agitation, f\xf6rvirringstillst\xe5nd, depression, \xe5ngest, onormala tankar, s\xf6mnl\xf6shet Centrala och perifera Mycket vanliga'],
             ['Other',
              u'Krampanfall, hypertension, darrningar, s\xf6mnighet, muskelsvaghetssyndrom, yrsel, huvudv\xe4rk, parestesi, smakst\xf6rning Hj\xe4rtat Mycket vanliga'],
             ['Other', u'Takykardi Blodk\xe4rl Mycket vanliga'],
             ['Other',
              u'Hypotension, hypertension, vasodilatation Andningsv\xe4gar, br\xf6stkorg och Mycket vanliga mediastinum'],
             ['Other',
              u'Utgjutning i lungs\xe4cken, dyspn\xe9, hosta Gastrointestinal disorders Mycket vanliga Kr\xe4kning, magsm\xe4rta, diarr\xe9, illam\xe5ende'],
             ['Other',
              u'Gastrointestinal bl\xf6dning, peritonit, ileus, kolit, mags\xe5r, duodenals\xe5r, gastrit, esofagit, stomatit, f\xf6rstoppning, dyspepsi, flatulens, rapning Lever och gallv\xe4gar Mycket vanliga'],
             ['Other',
              u'Hepatit, gulsot, hyperbilirubinemi Hud och subkutan v\xe4vnad Mycket vanliga'],
             ['Other',
              u'Hudhypertrofi, hudutslag, akne, alopeci Muskuloskeletala systemet och Mycket vanliga bindv\xe4v Vanliga Artralgi Njurar och urinv\xe4gar Mycket vanliga'],
             ['Other',
              u'Nedsatt njurfunktion Allm\xe4nna symtom och symtom Mycket vanliga vid administreringsst\xe4llet'],
             ['Other',
              u'\xd6dem, feber, frossbrytningar, sm\xe4rta, sjukdomsk\xe4nsla, asteni Unders\xf6kningar Mycket vanliga'],
             ['Other',
              u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jt blodkreatinin, f\xf6rh\xf6jt LDH (laktatdehydrogenas) i blodet, f\xf6rh\xf6jd blodurea, \xf6kning av alkaliska fosfataser i blodet, viktminskning Observera: 501 (2 g mykofenolatmofetil dagligen), 289 (3 g mykofenolatmofetil dagligen) och 277 (2 g i.v./3 g oralt mykofenolatmofetil dagligen) patienter behandlades i Fas III studier f\xf6r profylax mot avst\xf6tning vid njur-, hj\xe4rt- respektive levertransplantation. F\xf6ljande biverkningar avser erfarenheter av biverkningar efter marknadsintroduktion: De typer av biverkningar som rapporterats efter marknadsintroduktionen av mykofenolatmofetil \xe4r de samma som setts i de kontrollerade njur-, hj\xe4rt- och levertransplantationsstudierna. Ytterligare biverkningar som rapporterats efter marknadsintroduktionen beskrivs nedan med frekvensen angiven i parentes om den \xe4r k\xe4nd. Gastrointestinala: Gingivalhyperplasi (\u22651/100 till <1/10), kolit inklusive cytomegaloviruskolit (\u22651/100, <1/10), pankreatit (\u22651/100, <1/10) och tarmluddsatrofi. Sjukdomar relaterade till immunsuppressiv behandling: Allvarliga och livshotande infektioner inkluderande meningit, endokardit, tuberkulos och atypisk mykobakterieinfektion. Fall av BK-virus associerad nefropati, liksom fall av JC-virus-associerad progressiv multifokal leukoencefalopati (PML) har rapporterats hos patienter behandlade med immunsuppressiva l\xe4kemedel, inklusive mykofenolatmofetil. Agranulocytos (\u22651/1000, <1/100) och neutropeni har rapporterats, och d\xe4rf\xf6r rekommenderas regelbunden kontroll av patienter som f\xe5r mykofenolatmofetil (se avsnitt 4.4). Fall av aplastisk anemi och benm\xe4rgssuppression har rapporterats hos patienter som behandlats med mykofenolatmofetil, i n\xe5gra fall med d\xf6dligt f\xf6rlopp.']]],
           ['Uncommon', [['Other', u'(\u22651/1 000, <1/100)']]],
           ['Rare', [['Other', u'(\u22651/10 000, <1/1 000)']]],
           ['Very rare',
            [['Other',
              u'Mycket s\xe4llsynta (<1/10 000) Biverkningarna presenteras inom varje frekvensomr\xe5de efter fallande allvarlighetsgrad. Klassificering av organsystem Biverkningar Infektioner och infestationer Mycket vanliga Blodf\xf6rgiftning, gastrointestinal candidainfektion, urinv\xe4gsinfektion, herpes simplex, herpes zoster']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Other',
              u'I tabellen nedan redovisas de biverkningar, troligen eller m\xf6jligen relaterade till mykofenolatmofetil, som rapporterats hos \u2265 1/10 och hos \u22651/100 till <1/10 av patienterna som behandlats med mykofenolatmofetil i kontrollerade njur- (data p\xe5 2 g), hj\xe4rt- eller levertransplantationsstudier. Biverkningar, troligen eller m\xf6jligen relaterade till mykofenolatmofetil, som rapporterats hos patienter som behandlats med mykofenolatmofetil i kliniska njur-, hj\xe4rt- eller levertransplantationsstudier i kombination med ciklosporin och kortikosteroider Inom klassificeringen av organsystem redovisas biverkningarna under rubriker som anger frekvensomr\xe5de med f\xf6ljande kategorier'],
             ['Blood',
              u'Fall av ren erytrocytaplasi (PRCA) har rapporterats hos patienter som behandlats med mykofenolatmofetil (se avsnitt 4.4). Isolerade fall av onormal neutrofil morfologi, inklusive f\xf6rv\xe4rvad Pelger-Huet anomali, har observerats hos patienter som behandlats med mykofenolatmofetil. Dessa f\xf6r\xe4ndringar \xe4r inte f\xf6rknippade med f\xf6rs\xe4mrad neutrofil funktion. Dessa f\xf6r\xe4ndringar kan tyda p\xe5 en \u201dv\xe4nsterf\xf6rskjutning\u201d (\u201dleft shift\u201d) i mognaden av neutrofiler vid hematologiska unders\xf6kningar, vilket kan misstolkas som ett tecken p\xe5 infektion hos immunsupprimerade patienter s\xe5som patienter som f\xe5r mykofenolatmofetil. \xd6verk\xe4nslighet: \xd6verk\xe4nslighetsreaktioner inklusive angioneurotiskt \xf6dem och anafylaktisk reaktion har rapporterats. Medf\xf6dda st\xf6rningar: Se avsnitt 4.6 f\xf6r ytterligare information.'],
             ['Respiratory',
              u'Det har f\xf6rekommit enstaka rapporter om interstitiell lungsjukdom och pulmonell fibros hos patienter som behandlats med mykofenolatmofetil i kombination med andra immunsupprimerande l\xe4kemedel, i n\xe5gra fall med d\xf6dligt f\xf6rlopp.']]]],
 '_pages': [6, 9],
<<<<<<< HEAD
 u'_rank': 18,
=======
 u'_rank': 22,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}