<<<<<<< HEAD
{'_data': [['Common',
            [['Other',
              u'(> 1/1000, < 1/100), s\xe4llsynta (> 1/10 000, < 1/1000), mycket s\xe4llsynta (< 1/10 000), ingen'],
             ['Blood', u'Pancytopeni, leukocytos Metabolism och nutrition Mycket vanliga'],
             ['Blood',
              u'Acidos, hyperkalemi, hypokalemi, hyperglykemi, hypomagnesemi, hypokalcemi, hyperkolesterolemi, hyperlipidemi, hypofosfatemi, hyperurikemi, gikt, anorexi Psykiska st\xf6rningar Mycket vanliga'],
             ['Blood',
              u'Agitation, f\xf6rvirringstillst\xe5nd, depression, oro, onormala tankar, s\xf6mnl\xf6shet Centrala och perifera Mycket vanliga nervsystemet Vanliga Krampanfall, \xf6kad muskelsp\xe4nning, tremor, s\xf6mnighet, muskelsvaghetssyndrom, yrsel, huvudv\xe4rk, parestesi, smakst\xf6rning Hj\xe4rtat Mycket vanliga'],
             ['Blood', u'Takykardi Blodk\xe4rl Mycket vanliga'],
             ['Blood',
              u'Hypotoni, hypertoni, vasodilatation Andningsv\xe4gar, br\xf6stkorg och Mycket vanliga'],
             ['Blood',
              u'Utgjutning i lungs\xe4cken, dyspn\xe9, hosta Mag-tarmkanalen Mycket vanliga Kr\xe4kning, magsm\xe4rta, diarr\xe9, illam\xe5ende'],
             ['Blood',
              u'Gastrointestinal bl\xf6dning, peritonit, ileus, kolit, mags\xe5r, duodenals\xe5r, gastrit, esofagit, stomatit, f\xf6rstoppning, dyspepsi, flatulens, rapning Lever och gallv\xe4gar Mycket vanliga'],
             ['Blood',
              u'Hepatit, ikterus, hyperbilirubinemi Hud och subkutan v\xe4vnad Mycket vanliga'],
             ['Blood',
              u'Hudhypertrofi, hudutslag, akne, alopeci Muskuloskeletala systemet och Mycket vanliga'],
             ['Blood', u'Artralgi Njurar och urinv\xe4gar Mycket vanliga'],
             ['Blood', u'Nedsatt njurfunktion Allm\xe4nna symtom och/eller Mycket vanliga'],
             ['Blood',
              u'\xd6dem, feber, frossbrytningar, sm\xe4rta, sjukdomsk\xe4nsla, asteni Unders\xf6kningar Mycket vanliga'],
             ['Blood',
              u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jt blodkreatinin, f\xf6rh\xf6jt LDH (laktatdehydrogenas) i blodet, f\xf6rh\xf6jd blodurea, \xf6kning av alkaliska fosfataser i blodet, viktminskning Observera: 501 (2 g mykofenolatmofetil per dag), 289 (3 g mykofenolatmofetil per dag) och 277 (2 g iv/3 g oralt mykofenolatmofetil per dag) patienter behandlades i fas III-studier f\xf6r profylax mot avst\xf6tning vid njur-, hj\xe4rt- respektive levertransplantation. F\xf6ljande biverkningar avser erfarenheter av biverkningar efter marknadsintroduktion De typer av biverkningar som rapporterats efter marknadsintroduktionen av mykofenolatmofetil \xe4r desamma som setts i de kontrollerade njur-, hj\xe4rt- eller levertransplantationsstudierna. Tillkomna biverkningar som rapporterats efter marknadsintroduktionen beskrivs nedan med frekvensen angiven i parentes om den \xe4r k\xe4nd.']]],
           ['Unknown',
            [['Other',
              u'Biverkningar, troligen eller m\xf6jligen relaterade till mykofenolatmofetil, som rapporterats hos > 1/10 och hos \u2265 1/100, < 1/10 av patienterna som behandlats med mykofenolatmofetil i kontrollerade njur (data p\xe5 2 g), hj\xe4rt- eller levertransplantationsstudier, redovisas i tabellen nedan: Biverkningar, troligen eller m\xf6jligen relaterade till mykofenolatmofetil, som rapporterats hos patienter som behandlats med mykofenolatmofetil i kliniska njur-, hj\xe4rt- eller levertransplantationsstudier i kombination med ciklosporin och kortikosteroider. Inom klassificeringen av organsystem redovisas biverkningarna under rubriker som anger frekvensomr\xe5de med f\xf6ljande kategorier: mycket vanliga (\u2265 1/10), vanliga (\u2265 1/100, < 1/10), mindre'],
             ['Blood', u'anemi'],
             ['GI',
              u'Gingivalhyperplasi (> 1/100, < 1/10), kolit inklusive cytomegaloviruskolit (> 1/100, < 1/10), pankreatit (\u2265 1/100, < 1/10) och villi intestinales-atrofi. Sjukdomar relaterade till immunsuppressiv behandling: Allvarliga och livshotande infektioner inkluderande meningit, endokardit, tuberkulos och atypisk mykobakterieinfektion. Fall av BK-virusassocierad nefropati, liksom fall av JC-virusassocierad progressiv multifokal leukoencefalopati (PML), har rapporterats hos patienter behandlade med immunsuppressiva l\xe4kemedel, inklusive mykofenolatmofetil. Agranulocytos (\u2265 1/1000, < 1/100) och neutropeni har rapporterats, d\xe4rf\xf6r rekommenderas regelbunden kontroll av patienter som f\xe5r Mycophenolate mofetil Arrow (se avsnitt 4.4). Fall av aplastisk anemi och benm\xe4rgsdepression har rapporterats hos patienter som behandlats med mykofenolatmofetil, i n\xe5gra fall med d\xf6dligt f\xf6rlopp.'],
             ['Blood',
              u'Fall av ren erytrocytaplasi (PRCA) har rapporterats hos patienter som behandlats med mykofenolatmofetil (se avsnitt 4.4). Isolerade fall av onormal neutrofil morfologi, inklusive f\xf6rv\xe4rvad Pelger-Huet anomali, har observerats hos patienter som behandlats med mykofenolatmofetil. Dessa f\xf6r\xe4ndringar \xe4r inte f\xf6rknippade med f\xf6rs\xe4mrad neutrofilfunktion. Dessa f\xf6r\xe4ndringar kan tyda p\xe5 en \u201dv\xe4nsterf\xf6rskjutning\u201d (\u201dleft shift\u201d) i mognaden av neutrofiler vid hematologiska unders\xf6kningar, vilket av misstag kan tolkas som ett tecken p\xe5 infektion hos immunsupprimerade patienter s\xe5som patienter som f\xe5r mykofenolatmofetil. \xd6verk\xe4nslighet: \xd6verk\xe4nslighetsreaktioner inklusive angioneurotiskt \xf6dem och anafylaktisk reaktion har rapporterats. Medf\xf6dda st\xf6rningar: Se avsnitt 4.6 f\xf6r ytterligare information.'],
             ['Respiratory',
              u'Det har f\xf6rekommit isolerade rapporter om interstitiell lungsjukdom och pulmonell fibros hos patienter som behandlats med mykofenolatmofetil i kombination med andra immunsupprimerande l\xe4kemedel, i n\xe5gra fall med d\xf6dligt f\xf6rlopp.']]]],
 '_pages': [6, 9],
 u'_rank': 19,
 u'_type': u'LSFU'}
=======
{'_data': [['Very common',
            [['Infections',
              u'Sepsis, gastrointestinal  candidasinfektion, urinv\xe4gsinfektion, herpes simplex, herpes zoster'],
             ['Neoplasms', u''],
             ['Blood', u'Leukopeni, trombocytopeni,  anemi'],
             ['Metabolism', u''],
             ['Psychiatric', u''],
             ['Nervous system', u''],
             ['Cardiac', u''],
             ['Vascular', u''],
             ['Respiratory', u''],
             ['GI', u'Kr\xe4kning, magsm\xe4rta, diarr\xe9,  illam\xe5ende'],
             ['Hepato', u''],
             ['Skin', u''],
             ['Musculoskeletal', u''],
             ['Renal', u''],
             ['General', u''],
             ['Investigations', u'']]],
           ['Common',
            [['Infections',
              u'Pneumoni, influensa,  luftv\xe4gsinfektion, candidainfektion i luftv\xe4garna, gastrointestinal infektion, candidainfektion, gastroenterit, infektion, bronkit, faryngit, sinuit, hudsvamp, candidainfektion i huden, vaginal candidainfektion, rinit'],
             ['Neoplasms', u'Hudcancer, godartad hudtum\xf6r'],
             ['Blood', u'Pancytopeni, leukocytos'],
             ['Metabolism',
              u'Acidos, hyperkalemi,  hypokalemi, hyperglykemi, hypomagnesemi, hypokalcemi, hyperkolesterolemi, hyperlipidemi, hypofosfatemi, hyperurikemi, gikt, anorexi'],
             ['Psychiatric',
              u'Agitation, f\xf6rvirringstillst\xe5nd,  depression, oro, onormala tankar, s\xf6mnl\xf6shet'],
             ['Nervous system',
              u'Krampanfall, \xf6kad  muskelsp\xe4nning, tremor, s\xf6mnighet, muskelsvaghetssyndrom, yrsel, huvudv\xe4rk, parestesi, smakst\xf6rning'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotoni, hypertoni,  vasodilatation'],
             ['Respiratory', u'Utgjutning i lungs\xe4cken, dyspn\xe9,  hosta'],
             ['GI',
              u'Gastrointestinal bl\xf6dning,  peritonit, ileus, kolit, mags\xe5r, duodenals\xe5r, gastrit, esofagit, stomatit, f\xf6rstoppning, dyspepsi, flatulens, rapning'],
             ['Hepato', u'Hepatit, ikterus,  hyperbilirubinemi'],
             ['Skin', u'Hudhypertrofi, hudutslag, akne,  alopeci'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Nedsatt njurfunktion'],
             ['General',
              u'\xd6dem, feber, frossbrytningar,  sm\xe4rta, sjukdomsk\xe4nsla, asteni'],
             ['Investigations',
              u'F\xf6rh\xf6jda leverenzymer, f\xf6rh\xf6jt  blodkreatinin, f\xf6rh\xf6jt LDH (laktatdehydrogenas) i blodet, f\xf6rh\xf6jd blodurea, \xf6kning av alkaliska fosfataser i blodet, viktminskning']]]],
 '_pages': [6, 9],
 u'_rank': 19,
 u'_type': u'TSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
