{'_data': [['Very common',
            [['Blood',
              u'Dosrelaterad benm\xe4rgsneds\xe4ttning som yttrar sig som leukopeni och trombo-cytopeni.'],
             ['Respiratory', u'Idiopatiskt pneumonisyndrom (h\xf6gdosbehandl.)'],
             ['GI', u'Illam\xe5ende,kr\xe4kning, -diarr\xe9 och muns\xe5r (h\xf6gdosbeh.).'],
             ['Hepato',
              u'Hyperbilirubinemi, ikterus, hepatisk venocklusiv sjukdom, centrilobul\xe4r sinusoidal fibros med hepatocellul\xe4r atrofi av leverceller och nekros (h\xf6gdosbeh.).'],
             ['Reproductive system',
              u'Nedsatt ovariefunktion och amenorr\xe9 med klimakteriska symtom hos premenopausala kvinnor Sterilitet, azospermi, testikul\xe4r atrofi.']]],
           ['Common',
            [['Neoplasms', u'Sekund\xe4r akut leukemi.'],
             ['Cardiac',
              u'Hj\xe4rttamponad hos patienter med thalassemi som f\xe5tt h\xf6gdosbehandl.'],
<<<<<<< HEAD
             ['Respiratory', u'Interstitiell pneumonit (l\xe5ngtidsbeh. med'],
             ['Skin', u'Alopeci (h\xf6gdosbeh.), hyperpigmen-te ring.'],
=======
             ['Respiratory', u'Interstitiell pneumonit (l\xe5ngtidsbeh. med normal-1 dos)'],
             ['Skin', u'Alopeci (h\xf6gdosbeh.), hyperpigmen-tering.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Renal', u'Hemorragisk cystit (h\xf6gdosbeh. i komb. med cyklofosfamid).']]],
           ['Uncommon',
            [['Reproductive system',
              u'Nedsatt ovariefunktion och amenorr\xe9 med klimakteriska symtom hos kvinnor.']]],
           ['Rare',
            [['Blood',
              u'Aplastisk anemi ibland irreversibel (efter h\xf6gdosbeh. eller efter l\xe5ngtidsbeh. med normaldos).'],
             ['Nervous system', u'Kramper (h\xf6gdosbeh.).'],
             ['Eye',
              u'Linsf\xf6r\xe4ndringar, katarakt (kan vara bilateral), f\xf6rtunnad hornhinna efter benm\xe4rgstrans-plantation f\xf6reg\xe5nget av h\xf6gdos busulfan.'],
             ['Respiratory', u'Interstitiell pulmonell fibros med pulmonell benbildning'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9 och muns\xe5r'],
             ['Hepato',
              u'Ikterus pga gallstas. Leverenzym-stegring. Centrilobul\xe4r sinusoidal fibros'],
             ['Skin',
              u'Alopeci (normal dos), urtikaria, erythema multiforme, erythema nodosum, porfyria cutanea tarda, anhidros med torr och sk\xf6r hud, torra munslem-hinnor och s\xe5rbildning p\xe5 l\xe4pparna. Sj\xf6grens syndrom.'],
             ['General', u'Spridd epiteldysplasi']]],
           ['Very rare',
            [['Nervous system', u'Myastenia gravis.'],
             ['Cardiac', u'Endokardiell fibros.'],
             ['Reproductive system', u'Gynekomasti.'],
<<<<<<< HEAD
             ['General', u'Addison-liknand e syndrom']]]],
=======
             ['General', u'Addison-liknande syndrom']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_note': u' ?MSFU',
 '_pages': [3, 6],
 u'_rank': 23,
 u'_type': u'MSFU'}