{'_data': [['Unknown',
            [['Infections',
              u'Neutropen feber Mycket vanliga Mycket vanliga Infektioner Mycket vanliga Vanliga Herpes zoster Mindre vanliga Mindre vanliga Sepsis Mindre vanliga Mindre vanliga Infektion p\xe5 injektionsst\xe4llet Mindre vanliga Ingen k\xe4nd frekvens'],
             ['Blood',
              u'Neutropeni Mycket vanliga Mycket vanliga Trombocytopeni Mycket vanliga Mycket vanliga Anemi Mycket vanliga Mycket vanliga Leukopeni Mycket vanliga Mycket vanliga Lymfopeni Vanliga Vanliga Pancytopeni Vanliga Mindre vanliga Neuropen sepsis Mindre vanliga Mindre vanliga Purpura Mindre vanliga Mindre vanliga'],
             ['Metabolism',
              u'Anorexi Mycket vanliga Mycket vanliga Dehydrering Vanliga Mycket vanliga Hypokalemi Vanliga Mindre vanliga 6 Alla grader Grader > 3 Hyperglykemi Mindre vanliga Mindre vanliga'],
             ['Psychiatric', u'Agitation Mindre vanliga Ingen k\xe4nd frekvens'],
             ['Nervous system',
              u'Insomnia Vanliga Mindre vanliga G\xe5ngrubbningar Mindre vanliga Mindre vanliga Dysfoni Mindre vanliga Ingen k\xe4nd frekvens Somnolens Mindre vanliga Ingen k\xe4nd frekvens'],
             ['Cardiac',
              u'Arytmi Vanliga Mindre vanliga Kardiomyopati Vanliga Vanliga Hj\xe4rtsvikt Vanliga Vanliga Perikardit Mindre vanliga Mindre vanliga'],
             ['Vascular',
              u'V\xe4rmevallningar Vanliga Mindre vanliga Hypotension Mindre vanliga Mindre vanliga'],
             ['Respiratory',
              u'Br\xf6stsm\xe4rtor Vanliga Mindre vanliga Dyspn\xe9 Vanliga Mindre vanliga Epistaxis Vanliga Mindre vanliga Hemoptys Mindre vanliga Ingen k\xe4nd frekvens Faryngit Mindre vanliga Ingen k\xe4nd frekvens Pleurautgjutning Mindre vanliga Mindre vanliga Pneumonit Mindre vanliga Mindre vanliga'],
             ['GI',
              u'Illam\xe5ende/kr\xe4kningar Mycket vanliga Mycket vanliga Stomatit/mukosit Mycket vanliga Vanliga Diarr\xe9 Mycket vanliga Vanliga F\xf6rstoppning Vanliga Mindre vanliga Esofagit Vanliga Mindre vanliga Ulcus ventriculi Mindre vanliga Mindre vanliga'],
             ['Hepato',
              u'F\xf6rh\xf6jda levertransaminaser Vanliga Mindre vanliga F\xf6rh\xf6jt alkaliskt fosfatas Mindre vanliga Mindre vanliga Ikterus Mindre vanliga Mindre vanliga F\xf6rh\xf6jt bilirubin i serum Mindre vanliga Ingen k\xe4nd frekvens'],
             ['Skin',
              u'Alopeci Mycket vanliga Vanliga Utslag Vanliga Ingen k\xe4nd frekvens Nagelproblem Vanliga Mindre vanliga Pruritus Mindre vanliga Mindre vanliga Follikulit Mindre vanliga Mindre vanliga Torr hud Mindre vanliga Ingen k\xe4nd frekvens'],
             ['Musculoskeletal',
              u'Ryggsm\xe4rtor Vanliga Mindre vanliga Myalgi Vanliga Mindre vanliga Muskelsvaghet Mindre vanliga Mindre vanliga'],
             ['Renal',
              u'Hemorrhagisk cystit Mindre vanliga Mindre vanliga Oliguri Mindre vanliga Mindre vanliga'],
             ['General',
              u'Asteni/tr\xf6tthet Mycket vanliga Vanliga Feber Mycket vanliga Vanliga Sm\xe4rta Mycket vanliga Vanliga Stelhet Mycket vanliga Mindre vanliga Yrsel Vanliga Mindre vanliga 7 Alla grader Grader > 3 Huvudv\xe4rk Vanliga Mindre vanliga Viktminskning Vanliga Mindre vanliga Reaktion p\xe5 injektionsst\xe4llet Mindre vanliga Mindre vanliga Olustk\xe4nsla Mindre vanliga Ingen k\xe4nd frekvens']]]],
 '_pages': [5, 7],
 u'_rank': 14,
 u'_type': u'LSFU'}