{'_data': [['Common',
            [['Blood', u' Trombocytopeni, eosinofili, leukopeni'],
             ['GI', u' Stomatit,  metallisk smak,.'],
             ['Renal', u' Albuminuri, hematuri.'],
             ['Skin', u' Hudutslag ("Gold rash"), kl\xe5da.'],
             ['Immune system', u' Anafylaktoid-liknande reaktioner efter injektion.']]],
           ['Uncommon', [['Renal', u' Glomerulonefrit, nefrotiskt syndrom.']]],
           ['Rare',
            [['Blood', u'  Aplastisk anemi, agranulocytos, pancytopeni.'],
             ['Nervous system',
              u' Polyneurit, encefalit, perifer neuropati, Guillain-Barr\xe9s syndrom och encefalopati.'],
             ['Respiratory', u' Pneumoni, lungfibros.'],
             ['GI', u' Kolit.'],
             ['Skin', u' Exfoliativ dermatit, alopeci.'],
             ['Hepato', u' Leverskada.']]]],
 '_pages': [2, 3],
 u'_rank': 12,
 u'_type': u'LSFU2'}