{'_data': [['Common',
            [['General', u' Salivation, svettningar.  '],
             ['Vascular', u' Flush, bradykardi.  '],
             ['Respiratory', u' Bronkokonstriktion. '],
             ['Eye', u' Mios, \xf6kat t\xe5rfl\xf6de. ']]],
           ['Uncommon',
            [['General', u' Huvudv\xe4rk.  '],
             ['Nervous system', u' Irritation, \xe5ngest, f\xf6rvirring.  '],
             ['GI', u' Diarr\xe9, magknip, illam\xe5ende, kr\xe4kning. '],
             ['Musculoskeletal', u' Muskelsvaghet, muskelryckningar, kramper. '],
             ['Respiratory', u' \xf6kad bronkial sekretion. ']]]],
 '_pages': [2, 2],
 u'_rank': 9,
 u'_type': u'DFSU'}