{'_data': [[u'Unknown',
            [['Immune system', u'Anafylaxi, chock   Ok\xe4nd'],
             ['Infections', u'Faryngit   , gastroenterit   Mycket vanliga'],
             ['Nervous system', u'Areflexi   , huvudv\xe4rk   Mycket vanliga'],
             ['Eye', u'Konjunktivit   , korneaopacitet   Mycket vanliga'],
             ['Cardiac', u'Bradykardi, takykardi, cyanos   Ok\xe4nd'],
             ['Ear', u'\xd6ronv\xe4rk   , f\xf6rs\xe4mrad h\xf6rsel   Mycket vanliga'],
             ['Vascular', u'Hypertoni   Mycket vanliga'],
             ['Respiratory', u'Dyspn\xe9   , n\xe4st\xe4ppa   Mycket vanliga'],
             ['GI', u'Buksm\xe4rta   , navelbr\xe5ck   , kr\xe4kningar,   Mycket vanliga'],
             ['Skin', u'Angio\xf6dem   , utslag   , urticaria, kl\xe5da   Mycket vanliga'],
             ['General',
              u'Sm\xe4rta   , br\xf6stsm\xe4rta   , rigor   , Mycket vanliga   sjukdomsk\xe4nsla   , feber'],
             ['Musculoskeletal', u'Artralgi   Mycket vanliga']]]],
 '_pages': [5, 7],
 u'_rank': 12,
 u'_type': u'LFSU'}