{'_data': [['Common',
            [['Cardiac', u'Palpitationer'],
             ['Nervous system', u'D\xe5sighet Huvudv\xe4rk Yrsel'],
             ['Eye', u'Synst\xf6rningar'],
             ['Ear', u'\xd6ronsusningar'],
             ['GI',
              u'Dyspepsi Buksm\xe4rta Illam\xe5ende Diarr\xe9 F\xf6rstoppning Halsbr\xe4nna Stomatit'],
             ['Skin', u'Exantem Svettningar Huderosioner'],
             ['General', u'T\xf6rst \xd6dem V\xe4tskeretention']]],
           ['Uncommon',
            [['Ear', u'H\xf6rselneds\xe4ttning'],
             ['Respiratory', u'Astma Dyspn\xe9'],
             ['GI', u'Gastrointestinal bl\xf6dning Kolit Mags\xe5r Ulcerativ stomatit Gastrit'],
             ['Renal', u'Njurp\xe5verkan'],
             ['Skin', u'Urtikaria Fotosensitivitet inklusive psuedoporfyri H\xe5ravfall'],
             ['General', u'Feber'],
             ['Hepato', u'Leverp\xe5verkan'],
             ['Psychiatric', u'Insomningssv\xe5righeter Koncentrationssv\xe5righeter']]],
           ['Rare',
            [['Cardiac', u'Hj\xe4rtsvikt'],
             ['Blood',
              u'Trombocytopeni Granulocytopeni Leukopeni Aplastisk och hemolytisk anemi Agranulocytos'],
             ['Nervous system', u'Kramper'],
             ['Respiratory', u'Eosinofil pneumonit Pulmon\xe4rt \xf6dem'],
             ['GI',
              u'Perforation Kr\xe4kningar Melena Esofagit Pankreatit Hematemes Flatulens F\xf6rs\xe4mring av ulcer\xf6s F\xf6rs\xe4mring av Crohns sjukdom'],
             ['Renal', u'Hematuri'],
             ['Skin',
              u'Sv\xe5ra mucocutana hudreaktioner t ex Stevens Johnsons syndrom Erythema multiforme Toxisk epidermal nekrolys'],
             ['Musculoskeletal', u'Muskelsvaghet Myalgi'],
             ['Metabolism', u'Hyperkalemi'],
             ['Infections', u'Aseptisk meningit'],
             ['Vascular', u'Hypertoni, Vaskulit'],
             ['Immune system', u'Anafylaktisk reaktion Angioneurotiskt \xf6dem'],
             ['Hepato', u'Toxisk, i isolerade fall fatal hepatit'],
             ['Psychiatric', u'Kognitiva st\xf6rningar Depression Mardr\xf6mmar L\xe4tt oro']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 8],
 u'_rank': 29,
 u'_type': u'MSFU'}