{'_data': [['Common',
            [['Infections', u'   influensasyndrom, faryngit, rinit  '],
             ['GI', u'   dyspepsi, tandbesv\xe4r  ']]],
           ['Unknown',
            [['Immune system',
              u'   \xf6verk\xe4nslighet (inkluderande hudutslag, urtikaria, kl\xe5da och  '],
             ['Nervous system', u' '],
             ['Eye', u'   katarakt, glaukom, \xf6kat intraokul\xe4rt tryck  '],
             ['Respiratory', u' '],
             ['General', u'   tr\xf6tthet  '],
             ['Investigations', u' ']]]],
 '_pages': [4, 4],
 u'_rank': 8,
 u'_type': u'DFSU'}