{'_data': [['Very common',
            [['Blood',
              u'Benm\xe4rgsdepression som huvudsakligen ger neutropeni (G3 24,3%; G4 27,8%), reversibel inom 5 till 7 dagar och icke-kumulativ \xf6ver tid. Anemi (G3-4: 7,4%),'],
             ['Nervous system',
              u'Neurologiska biverkningar (G3-4 2,7%) inkluderande upph\xe4vande av djupa senreflexer. Svaghet i de nedre extremiteterna har rapporterats efter l\xe5ngvarig kemoterapibehandling.'],
             ['GI',
              u'Stomatit (G1-4 15% med Navelbine i monoterapi). Illam\xe5ende och kr\xe4kningar (G1-2: 30,4% och G3-4: 2,2%). Antiemetika kan reducera f\xf6rekomsten. F\xf6rstoppning \xe4r det huvudsakliga symtomet (G3-4: 2,7%) som s\xe4llan utvecklas till paralytisk ileus med Navelbine i monoterapi samt i kombination med annan kemoterapi (G3-4: 4,1%).'],
             ['Hepato',
              u'\xd6verg\xe5ende f\xf6rh\xf6jningar av leverfunktionstester (G1-2) utan kliniska symtom har rapporterats (ASAT hos 27,6% och ALAT hos 29,3%).'],
             ['Skin',
              u'Alopeci, vanligen mild kan f\xf6rekomma (G3-4 4,1% med Navelbine i monoterapi).'],
             ['General',
              u'Reaktioner p\xe5 injektionsst\xe4llet kan inkludera erytem, br\xe4nnande sm\xe4rta, missf\xe4rgning av venen och lokal flebit (G3-4: 3,7% med Navelbine i monoterapi).']]],
           ['Common',
            [['Infections',
              u'Bakteriella-, virala- och svampinfektioner med olika lokalisering (andningsv\xe4gar, urinv\xe4gar, magtarmkanalen) som \xe4r milda till m\xe5ttliga och vanligtvis reversibla med l\xe4mplig behandling.'],
             ['Blood',
              u'Trombocytopeni (G3-4 2,5%) kan f\xf6rekomma men \xe4r s\xe4llan allvarlig.'],
             ['GI', u'Diarr\xe9, vanligen mild till m\xe5ttlig.'],
             ['Musculoskeletal', u'Artralgi inkluderande k\xe4ksm\xe4rta och myalgi.'],
             ['General',
              u'Asteni, tr\xf6tthet, feber, sm\xe4rta vid olika st\xe4llen inkluderande br\xf6stsm\xe4rta och sm\xe4rta vid tum\xf6rst\xe4llet har upplevts av patienter som behandlats med Navelbine.']]],
           ['Uncommon',
            [['Infections', u'Sv\xe5r sepsis med viscerala organsvikter. Septikemi.'],
             ['Nervous system',
              u'Allvarliga parestesier med sensoriska och motoriska symtom (G3-4 <3%). Dessa symtom \xe4r vanligen reversibla n\xe4r behandlingen avslutas.'],
             ['Vascular', u'Hypotension, hypertension, flush och perifer kyla.'],
             ['Respiratory',
              u'Dyspn\xe9 och bronkospasm kan f\xf6rekomma vid behandling med Navelbine, liksom med andra vincaalkaloider.']]],
           ['Rare',
            [['Metabolism', u'Allvarlig hyponatremi.'],
             ['Cardiac', u'Ischemisk hj\xe4rtsjukdom (angina pectoris, hj\xe4rtinfarkt).'],
             ['Vascular', u'Allvarlig hypotension, kollaps.'],
             ['Respiratory',
              u'Interstitiell pneumopati har rapporterats, s\xe4rskilt hos patienter som behandlats med Navelbine i kombination med mitomycin.'],
             ['GI',
              u'Paralytisk ileus. Behandlingen kan \xe5terupptas vid \xe5terst\xe4lld normal tarmfunktion. Pankreatit har rapporterats.'],
             ['Skin', u'Allm\xe4nna hudreaktioner.'],
             ['General',
              u'Lokal nekros har observerats. R\xe4tt positionering av den intraven\xf6sa kanylen eller katetern och bolusinjektion f\xf6ljd av riklig sk\xf6ljning av venen kan begr\xe4nsa dessa effekter.']]],
           ['Very rare',
            [['Infections',
              u'Komplicerad septikemi och i vissa fall fatal septikemi. Neutropen sepsis.'],
             ['Cardiac', u'Takykardi, palpitation och hj\xe4rtrytmrubbningar.']]],
           ['Unknown',
            [['Blood', u'Febril neutropeni.'],
             ['Immune system',
              u'Systemiska allergiska reaktioner som rapporterats \xe4r anafylaksi, anafylaktisk chock eller anafylaktoida reaktioner.'],
             ['Endocrine',
              u'Onormal uts\xf6ndring av antidiuretiskt hormon (SIADH) har rapporterats.'],
             ['Metabolism', u'Anorexi.'],
             ['Skin', u'Erytem p\xe5 h\xe4nder och f\xf6tter.']]]],
 '_pages': [4, 6],
 u'_rank': 29,
 u'_type': u'LSFU'}