{'_data': [[u'Unknown',
            [['Blood',
              u'Polycytemi   F\xf6rh\xf6jd hematokrit   F\xf6rh\xf6jt antal r\xf6da blodkroppar'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'Vikt\xf6kning   \xd6kad aptit   \xd6kning av glykosylerat hemoglobin'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Huvudv\xe4rk   Migr\xe4n'],
             ['Vascular', u'V\xe4rmevallning   Kardiovaskul\xe4r sjukdom'],
             ['Respiratory', u'Bronkit'],
             ['GI', u'Diarr\xe9'],
             ['Hepato', u'Onormalt leverfunktionstest'],
             ['Skin', u'Acne   Alopeci   Erytem'],
             ['Musculoskeletal', u'Artralgi   V\xe4rk i extremiteter'],
             ['Renal', u'S\xe4nkt urinfl\xf6de'],
             ['Reproductive system',
              u'F\xf6rh\xf6jt prostataspecifikt   Prostatisk intraepitelial neoplasi'],
             ['General', u'Olika slags reaktioner vid   Tr\xf6tthet']]]],
 '_pages': [5, 7],
 u'_rank': 14,
 u'_type': u'LFSU'}