{'_data': [['Very common',
            [['Metabolism',
              u'F\xf6rh\xf6jd niv\xe5 av alkaliskt fosfatas i  blodet F\xf6rh\xf6jd niv\xe5 av laktatdehydrogenas i blodet F\xf6rh\xf6jd niv\xe5 av urinsyra i blodet'],
             ['GI', u'Illam\xe5ende  Kr\xe4kning'],
             ['Hepato', u'F\xf6rh\xf6jd niv\xe5 av  gammaglutamyltransferas i blodet'],
             ['Blood', u'Leukocytos  Trombocytopeni'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta'],
             ['Blood', u'Anemi  Splenomegali'],
             ['Metabolism',
              u'F\xf6rh\xf6jd niv\xe5 av alkaliskt fosfatas i  blodet F\xf6rh\xf6jd niv\xe5 av laktatdehydrogenas i blodet S\xe4nkt blodsocker Hyperurikemi'],
             ['Respiratory', u'Epistaxis'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta']]],
           ['Common',
            [['Metabolism', u'Anorexi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Respiratory', u'Hosta  Faryngolaryngeal sm\xe4rta'],
             ['GI', u'F\xf6rstoppning  Diarr\xe9'],
             ['Skin', u'Alopeci  Utslag'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta'],
             ['General', u'Tr\xf6tthet  Asteni  Slemhinneinflammation  Br\xf6stsm\xe4rta'],
             ['Metabolism',
              u'F\xf6rh\xf6jd niv\xe5 av alkaliskt fosfatas i  blodet F\xf6rh\xf6jd niv\xe5 av laktatdehydrogenas i blodet'],
             ['Blood', u'Trombocytopeni'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Diarr\xe9'],
             ['Hepato', u'Hepatomegali'],
             ['Skin', u'Alopeci  Kutan vaskulit Utslag'],
             ['Musculoskeletal', u'Osteoporos'],
             ['General', u'Sm\xe4rta vid injektionsst\xe4llet'],
             ['Blood', u'Mj\xe4ltrubbningar']]],
           ['Uncommon',
            [['General', u'Sm\xe4rta'],
             ['Blood', u'Mj\xe4ltrubbning'],
             ['Metabolism', u'F\xf6rh\xf6jd niv\xe5 av  aspartataminotransferas Hyperurikemi'],
             ['Musculoskeletal', u'F\xf6rv\xe4rrad reumatoid artrit'],
             ['Blood', u'Mj\xe4ltrubbning'],
             ['Renal', u'Hematuri  Proteinuri'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta']]],
           ['Rare', [['Vascular', u'Angiopati']]],
           ['Very rare', [['Respiratory', u'Lunginfiltrat'], ['Renal', u'Onormal urin']]]],
 '_pages': [9, 12],
 u'_rank': 36,
 u'_type': u'TSFU'}