{'_data': [['Very common',
            [['Blood', u'lymfopeni'],
             ['Metabolism', u'hypofosfatemi'],
             ['Vascular',
              u'bl\xf6dning (inkl. bl\xf6dning i gastrointestinalka nalen*, luftv\xe4garna* och cerebral bl\xf6dning*) hypertension'],
             ['GI', u'diarr\xe9 illam\xe5ende kr\xe4kning'],
             ['Skin', u'hudutslag alopeci hand-fotsyndrom** erytem kl\xe5da'],
             ['General',
              u'tr\xf6tthet sm\xe4rta (inkluderar mun, buken, skelett, tum\xf6rsm\xe4rta och huvudv\xe4rk)'],
             ['Investigations', u'f\xf6rh\xf6jt amylas f\xf6rh\xf6jt lipas']]],
           ['Common',
            [['Blood', u'leukopeni neutropeni anemi trombocytopeni'],
             ['Metabolism', u'anorexi hypokalcemi'],
             ['Psychiatric', u'depression'],
             ['Nervous system', u'perifer sensorisk neuropati'],
             ['Ear', u'tinnitus'],
             ['Cardiac', u'kronisk hj\xe4rtsvikt* myokardiell ischemi och infarkt*'],
             ['Respiratory', u'heshet'],
             ['GI',
              u'f\xf6rstoppning stomatit (inkluderar torr mun och glossodyni) dyspepsi dysfagi'],
             ['Skin', u'torr hud exfoliativ dermatit akne hudfj\xe4llning'],
             ['Musculoskeletal', u'artralgi myalgi'],
             ['Renal', u'njursvikt'],
             ['Reproductive system', u'erektil dysfunktion gynekomasti'],
             ['General', u'asteni feber influensaliknande sjukdom'],
             ['Investigations', u'viktminskning \xf6verg\xe5ende f\xf6rh\xf6jda transaminaser']]],
           ['Uncommon',
            [['Infections', u'follikulit infektion'],
             ['Immune system',
              u'\xf6verk\xe4nslighets-reaktioner (inklusive hudreaktioner och urtikaria)'],
             ['Endocrine', u'hypotyroidism hypertyroidism'],
             ['Metabolism', u'hyponatremi dehydrering'],
             ['Nervous system', u'reversibel posterior leukoencefalopati*'],
             ['Vascular', u'hypertensiv kris*'],
             ['Respiratory',
              u'snuva h\xe4ndelser liknande interstitiell lungsjukdom (pneumonit, str\xe5lningspneumonit, akut andn\xf6d etc.)'],
             ['GI', u'gastroesofageal reflux pankreatit gastrit gastrointestinal perforation*'],
             ['Hepato', u'\xf6kning av bilirubin och ikterus kolecystit kolangit'],
             ['Skin', u'eksem erytema multiforme keratoakantom/ skiv-epitelcancer i huden'],
             ['Investigations',
              u'\xf6verg\xe5ende f\xf6rh\xf6jning av alkaliska fosfataser i blod onormalt INR-v\xe4rde onormal protrombinniv\xe5']]],
           ['Rare',
            [['Immune system', u'angio\xf6dem anafylaktisk reaktion'],
             ['Cardiac', u'QT-f\xf6rl\xe4ngning'],
             ['Hepato', u'l\xe4kemedelsinduce rad hepatit*'],
             ['Skin',
              u'\u201dradiation-recall\u201d-dermatit Stevens-Johnson syndrom leukocytoklastisk vaskulit toxisk epidermial nekrolys*'],
             ['Musculoskeletal', u'rabdomyolys']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 37,
 u'_type': u'MSFU'}