{'_data': [['Very common',
            [['Cardiac', u'Arytmi, f\xf6rl\xe4ngt QT-intervall,'],
             ['Renal', u'Interstitiell nefrit**'],
             ['Skin', u'Hudutslag'],
             ['Immune system', u'Toxisk epidermal nekrolys'],
             ['Psychiatric', u'Psykos, hallucinationer,']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Buksm\xe4rtor, diarr\xe9, gasbildning,  illam\xe5ende/kr\xe4kning, f\xf6rstoppning'],
             ['GI', u'Kr\xe4kningar, l\xf6s avf\xf6ring, illam\xe5ende.'],
             ['Skin', u'Exantem'],
             ['Investigations', u'Transaminasstegringar.'],
             ['Nervous system', u'Huvudv\xe4rk. Smakf\xf6r\xe4ndring.'],
             ['GI', u'Illam\xe5ende, magknip, diarr\xe9,  dyspepsi och kr\xe4kningar.'],
             ['Nervous system', u'F\xf6r\xe4ndrat smaksinne*, F\xf6r\xe4ndrat  luktsinne*'],
             ['Ear', u'Reversibel h\xf6rself\xf6rlust. Yrsel **'],
             ['GI', u'Illam\xe5ende, magknip, diarr\xe9,  dyspepsi och kr\xe4kningar.'],
             ['Infections', u'Moniliasis']]],
           ['Uncommon',
            [['Nervous system', u'D\xe5sighet, parestesier, s\xf6mnighet'],
             ['Eye', u'Dimsyn'],
             ['Ear', u'Yrsel'],
             ['GI', u'Muntorrhet'],
             ['Skin', u'Dermatit, kl\xe5da, hudutslag, n\xe4sselutslag'],
             ['Musculoskeletal', u'H\xf6ft-, handleds- eller kotfrakturer (se avsnitt  .4)'],
             ['Metabolism', u'Perifert \xf6dem'],
             ['Hepato', u'F\xf6rh\xf6jning av leverenzymer'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Blood', u'Eosinofili'],
             ['Skin', u'Urtikaria'],
             ['Metabolism', u'Hypoglykemi'],
             ['Immune system',
              u'Exantem, urtikaria, anafylaktisk  reaktion, Stevens-Johnsons syndrom'],
             ['Hepato', u'Hepatocellul\xe4r reaktion, kolestas.  Hepatit, gulsot']]],
           ['Rare',
            [['Blood', u'Leukopeni, trombocytopeni'],
             ['Nervous system', u'Smakf\xf6r\xe4ndringar'],
             ['Respiratory', u'Bronkospasm'],
             ['GI', u'Stomatit, gastrointestinal candidiasis'],
             ['Skin', u'H\xe5ravfall, fotosensitivitet'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Metabolism', u'Hyponatremi'],
             ['General', u'Allm\xe4n sjukdomsk\xe4nsla, \xf6kad svettning'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner s\xe5som feber, angio\xf6dem  och anafylaktisk reaktion'],
             ['Hepato', u'Hepatit med eller utan gulsot'],
             ['Psychiatric', u'Agitation, f\xf6rvirring, depression'],
             ['Blood', u'Trombocytos'],
             ['Renal', u'Interstitiell nefrit, kristalluri.'],
             ['Skin', u'Erytema multiforme, exfoliativ dermatit,  angio\xf6dem.'],
             ['Infections', u'Pseudomembran\xf6s kolit.'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Investigations', u'F\xf6rh\xf6jt serumkreatinin'],
             ['Cardiac', u'ventrikeltakykardi, torsades de  pointes'],
             ['Blood', u'Leukopeni, trombocytopeni.'],
             ['Nervous system', u'Kramper, svindel**'],
             ['Ear', u'Tinnitus'],
             ['GI', u'Glossit, stomatit, missf\xe4rgning av  tunga och t\xe4nder  Pankreatit'],
             ['Renal', u''],
             ['Immune system', u''],
             ['Hepato', u'Leverskador'],
             ['Psychiatric',
              u'desorientering, konfusion  personlighetsf\xf6r\xe4ndring, oro, s\xf6mnl\xf6shet, mardr\xf6mmar']]],
           ['Very rare',
            [['Blood', u'Agranulocytos, pancytopeni'],
             ['Renal', u'Interstitiell nefrit'],
             ['Skin',
              u'Stevens-Johnsons syndrom, erytema multiforme,  toxisk epidermal nekrolys (TEN)'],
             ['Musculoskeletal', u'Muskelsvaghet'],
             ['Hepato', u'Leversvikt, encefalopati hos leversjuka patienter'],
             ['Reproductive system', u'Gynekomasti'],
             ['Psychiatric', u'']]],
           ['Unknown',
            [['Metabolism', u'Hypomagnesemi (se avsnitt'],
             ['Musculoskeletal', u'Muskelsm\xe4rta']]]],
 '_pages': [9, 12],
 u'_rank': 62,
 u'_type': u'TSFU'}