{'_data': [['Very common',
            [['Infections', u'vaginal infektion'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Skin', u'akne'],
             ['Reproductive system',
              u'\xf6mma br\xf6st, sm\xe4rta i br\xf6sten, oregelbundna bl\xf6dningar'],
             ['Investigations', u'vikt\xf6kning']]],
           ['Common',
            [['Metabolism', u'\xf6kad aptit'],
             ['Psychiatric', u'affektiv labilitet, nedst\xe4mdhet, nervositet, minskad libido'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'v\xe4rmevallningar'],
             ['GI', u'buksm\xe4rta, illam\xe5ende, flatulens'],
             ['Skin', u'alopeci'],
             ['Reproductive system', u'dysmenorr\xe9, ovarialcystor'],
             ['General',
              u'sm\xe4rta vid ins\xe4ttningsst\xe4llet, reaktion vid ins\xe4ttningsst\xe4llet, tr\xf6tthet, influensaliknande sjukdom, sm\xe4rta'],
             ['Investigations', u'viktminskning']]],
           ['Uncommon',
            [['Infections', u'faryngit, rinit, urinv\xe4gsinfektion'],
             ['Immune system', u'hypersensitivitet'],
             ['Psychiatric', u'\xe5ngest, insomnia'],
             ['Nervous system', u'migr\xe4n, somnolens'],
             ['GI', u'kr\xe4kningar, f\xf6rstoppning, diarr\xe9'],
             ['Skin', u'hypertrikos, utslag, kl\xe5da'],
             ['Musculoskeletal', u'ryggont, artralgi, myalgi, muskuloskeletal sm\xe4rta'],
             ['Renal', u'dysuri'],
             ['Reproductive system',
              u'flytningar, obehagsk\xe4nsla i underlivet, galaktorr\xe9, f\xf6rstorade br\xf6st, genital kl\xe5da'],
             ['General', u'pyrexi, \xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [12, 14],
 u'_rank': 24,
 u'_type': u'MSFU'}