{'_data': [['Very common', []],
           ['Common',
            [['GI', u'Illam\xe5ende, kr\xe4kning'],
             ['General', u'Yrsel, berusningsk \xe4nsla *']]],
           ['Uncommon',
            [['Ear', u'Tryckk\xe4nsla i mellan\xf6rat'],
             ['GI', u'Uppbl\xe5sthet, \xf6kad gasvolym i tarmarna']]],
           ['Rare', []],
           ['Very rare', [['Nervous system', u'Myelopati, polyneuropati']]],
           ['Unknown',
            [['Blood', u'Leukopeni, megaloblastisk anemi'], ['Psychiatric', u'Psykos']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 7,
 u'_type': u'MSFU'}