{'_data': [['Very common', [['GI', u'Hicka.']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk.'],
             ['Respiratory', u'Faryngolaryngeal sm\xe4rta.'],
             ['GI', u'Illam\xe5ende, dyspepsi, stomatitis och flatulens.']]],
           ['Uncommon',
            [['Respiratory', u'Dyspn\xe9.'],
             ['GI', u'Kr\xe4kningar, sv\xe4ljsv\xe5righeter, diarr\xe9 och uppst\xf6tning.'],
             ['Psychiatric',
              u'S\xf6mnsv\xe5righeter. Vissa symtom som har rapporterats, s\xe5som depression, irritabilitet, \xe5ngest och s\xf6mnsv\xe5righeter kan utg\xf6ra abstinenssymtom i samband med r\xf6kavv\xe4njningen. Personer som slutar r\xf6ka kan oavsett metod riskera att drabbas av huvudv\xe4rk, yrsel, \xf6kad hosta eller f\xf6rkylning.']]],
           ['Very rare', [['Immune system', u'Anafylaktisk chock']]]],
 '_pages': [3, 4],
 u'_rank': 8,
 u'_type': u'LSFU'}