{'_data': [['Very common',
            [['Immune system', u's\xe4llsynta(<1/10000): anafylaktisk chock'],
             ['GI', u'illam\xe5ende, irritation i mun/hals och tunga']]],
           ['Common',
            [['Psychiatric',
              u'irritabilitet, \xe5ngest, s\xf6mnst\xf6rningar inklusive onormala dr\xf6mmar'],
             ['Nervous system', u'yrsel, huvudv\xe4rk'],
             ['Respiratory', u'hosta, halsont'],
             ['GI',
              u'kr\xe4kning, diarr\xe9, magtarmbesv\xe4r, flatulens, hicka, halsbr\xe4nna, dyspepsi']]],
           ['Uncommon',
            [['Psychiatric', u'nervositet, depression'],
             ['Cardiac', u'hj\xe4rtklappning, puls\xf6kning'],
             ['Skin', u'utslag'],
             ['General', u'tr\xf6tthet, allm\xe4n sjukdomsk\xe4nsla, br\xf6stsm\xe4rtor']]]],
 '_pages': [3, 4],
 u'_rank': 10,
 u'_type': u'LSFU'}