{'_data': [['Common',
            [['Psychiatric', u'Nervositet'],
             ['Nervous system', u'Hyperkinesi'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Psychiatric', u'Depression'],
             ['Nervous system', u'Somnolens'],
             ['General', u'Asteni']]],
           ['Unknown',
            [['Blood', u'Bl\xf6dningar'],
             ['Immune system', u'Anafylaktisk reaktion, \xf6verk\xe4nslighet'],
             ['Psychiatric', u'Agitation, oro, f\xf6rvirring, hallucinationer'],
             ['Nervous system',
              u'Ataxi, f\xf6rs\xe4mrad balans, f\xf6rsv\xe5rad epilepsi, huvudv\xe4rk, insomni'],
             ['Ear', u'Vertigo'],
             ['GI',
              u'Buksm\xe4rta, sm\xe4rta i \xf6vre delen av buken, diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'Angioneurotiskt \xf6dem, dermatit, kl\xe5da, urtikaria']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'LSFU'}