{'_data': [['Very common', [['General', u'Vuxna: Perifera']]],
           ['Common',
            [['Nervous system', u'Vuxna: Huvud-v\xe4rk och parestesier'],
             ['Musculoskeletal', u'Vuxna: Ledv\xe4rk, ledstelhet och muskelv\xe4rk']]],
           ['Uncommon',
            [['Metabolism', u'Vuxna: Diabetes mellitus typ 2'],
             ['Nervous system', u'Vuxna: Karpal-tunnelsyndr om Barn: Huvudv\xe4rk'],
             ['Skin', u'Vuxna: Kl\xe5da'],
             ['Musculoskeletal', u'Vuxna: Muskelstelhet'],
             ['General', u'Vuxna och barn:']]],
           ['Rare',
            [['Skin', u'Barn: Hudutslag'],
             ['Musculoskeletal', u'Barn: Led-och muskelv\xe4rk'],
             ['General', u'Barn: Perifera']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 11,
 u'_type': u'MSFU'}