{'_data': [['Common',
            [['Eye', u'Dimsyn'],
             ['GI', u'Illam\xe5ende, muntorrhet'],
             ['General', u'Tr\xf6tthet, yrsel']]],
           ['Very rare',
            [['Psychiatric', u'Hallucinationer, f\xf6rvirring'],
             ['Nervous system', u'Tremor'],
             ['Eye', u'Ackommodationsrubbningar'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['GI', u'F\xf6rstoppning'],
             ['Renal', u'Urinretention']]]],
 '_note': u' ?MSFU',
 '_pages': [2, 2],
 u'_rank': 9,
 u'_type': u'MSFU'}