{'_data': [['Very common',
            [['Vascular',
              u'Lokala k\xe4rlf\xf6r\xe4ndringar med f\xf6rs\xe4mrad ven\xf6s access.']]],
           ['Common', [['General', u'Sm\xe4rta, svullnad och flebit vid infusionsst\xe4llet']]],
           ['Uncommon',
            [['Investigations',
              u'\xd6kad halt av ferritin i serum \xd6kade koncentrationer av ferritin i serum har rapporterats efter flera \xe5rs behandling med upprepade infusioner, vilket kan tyda p\xe5 j\xe4rn\xf6verbelastning (se avsnitt 4.4. Varningar och f\xf6rsiktighet).']]],
           ['Rare',
            [['Immune system',
              u'Anafylaktisk reaktion, \xf6verk\xe4nslighet(s\xe5som dermatit och tung\xf6dem).'],
             ['General', u'Feber']]],
           ['Unknown', [['Nervous system', u'huvudv\xe4rk']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'LSFU'}