{'_data': [['Very common',
            [['Infections', u'Infektion'],
             ['Blood',
              u'Myelosuppression, benm\xe4rgshypoplasi, trombocytopeni, leukopeni, granulocytopeni, neutropeni, anemi, hemorragi, onormalt antal leukocyter'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, diarr\xe9, f\xf6rstoppning, stomatit, mukosit.'],
             ['Skin', u'Alopeci'],
             ['General', u'Feber, buksm\xe4rtor']]],
           ['Common',
            [['Infections', u'\xd6vre luftv\xe4gsinfektion, pneumoni, sepsis'],
             ['Blood', u'Bl\xf6dning'],
             ['Cardiac', u'Hj\xe4rtsvikt, sinusbradykardi, EKG-f\xf6r\xe4ndringar, hypotoni.'],
             ['GI', u'Gastrointestinal bl\xf6dning.'],
             ['Hepato', u'Levertoxicitet'],
             ['Skin', u'Hudutslag, erytem.'],
             ['Nervous system', u'Anorexi, huvudv\xe4rk'],
             ['Renal', u'Njurtoxicitet'],
             ['General', u'Tr\xf6tthet, \xf6dem']]],
           ['Uncommon',
            [['Skin', u'Bl\xe5f\xe4rgning av hud och \xf6gonvitor.'],
             ['Nervous system', u'\xc5ngest, f\xf6rvirring']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 16,
 u'_type': u'MSFU'}