{'_data': [['Common',
            [['Blood', u'neutropeni'],
             ['Metabolism', u'elektrolytrubbningar, anorexi'],
             ['Nervous system', u'parestesi, yrsel, somnolens, huvudv\xe4rk'],
             ['GI',
              u'kr\xe4kningar, illam\xe5ende, buksm\xe4rta, diarr\xe9, dyspepsi, muntorrhet, flatulens'],
             ['Hepato',
              u'f\xf6rh\xf6jda leverfunktionstester (\xf6kat ALAT, \xf6kat ASAT, \xf6kat bilirubin, \xf6kat alkalisk fosfatas, \xf6kat GGT)'],
             ['Skin', u'utslag'],
             ['Reproductive system', u'pyrexi (feber), asteni, tr\xf6tthet']]],
           ['Uncommon',
            [['Blood', u'trombocytopeni, leukopeni, anemi, eosinofili, lymfadenopati'],
             ['Immune system', u'allergisk reaktion'],
             ['Metabolism', u'hyperglykaemi'],
             ['Nervous system', u'konvulsioner, neuropati, hypoestesi, tremor'],
             ['Eye', u'dimsyn'],
             ['Cardiac', u'l\xe5ngt QT-syndrom , onormalt EKG , palpitationer'],
             ['Vascular', u'hypertension, hypotension'],
             ['GI', u'pankreatit'],
             ['Hepato', u'hepatocellul\xe4r skada, hepatit, gulsot, leverf\xf6rstoring'],
             ['Skin', u'muns\xe5r, alopeci'],
             ['Skin', u'Ryggv\xe4rk'],
             ['Renal', u'akut njursvikt, njursvikt, \xf6kad niv\xe5 av kreatinin i blodet'],
             ['Reproductive system', u'\xf6dem, sm\xe4rta, frossa, olustk\xe4nsla'],
             ['Investigations',
              u'\xe4ndrade niv\xe5er av l\xe4kemedel i blodet Se avsnitt 4.4']]],
           ['Rare',
            [['Blood',
              u'hemolytiskt uremiskt syndrom, trombotisk trombocytopenipurpura, pancytopeni, koagulopati, bl\xf6dning'],
             ['Immune system', u'\xf6verk\xe4nslighetsreaktion'],
             ['Endocrine', u'binjureinsufficiens, minskade niv\xe5er av gonadotropin i blodet'],
             ['Psychiatric', u'psykotiska tillst\xe5nd, depression'],
             ['Nervous system',
              u'cerebrovaskul\xe4r h\xe4ndelse, encefalopati, perifer neuropati, synkope'],
             ['Eye', u'diplopi, skotom'],
             ['Ear', u'h\xf6rselneds\xe4ttning'],
             ['Cardiac',
              u'torsade de pointes, pl\xf6tslig d\xf6d, ventrikul\xe4r takykardi, hj\xe4rtstillest\xe5nd, hj\xe4rtsvikt, hj\xe4rtinfarkt'],
             ['Vascular',
              u'lungemboli, djup ventrombos Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'pulmon\xe4r hypertension, interstitiell pneumoni, pneumonit'],
             ['GI', u'gastrointestinalbl\xf6dning, ileus'],
             ['Hepato',
              u'leversvikt, kolestatisk hepatit, kolestas, hepatosplenomegali, \xf6mhet i levern, asterixis'],
             ['Skin',
              u'Stevens-Johnsons syndrom, vesikul\xe4ra utslag Muskuloskeletala systemet och bindv\xe4v'],
             ['Renal', u'acidos i njurtubuli, interstitiell nefrit'],
             ['Reproductive system',
              u'menstruationsrubbningar sm\xe4rta i br\xf6sten Allm\xe4nna symtom och/eller symtom vid administrationsst\xe4llet'],
             ['Reproductive system', u'tung\xf6dem, ansikts\xf6dem']]],
           ['Unknown',
            [['Psychiatric', u'f\xf6rvirringstillst\xe5nd'],
             ['Hepato',
              u'Vid s\xe4kerhetsuppf\xf6ljning efter marknadsf\xf6ring har allvarlig leverskada med d\xf6dlig utg\xe5ng rapporterats (se avsnitt 4.4).']]]],
 '_pages': [8, 10],
 u'_rank': 39,
 u'_type': u'LSFU'}