{'_data': [[u'Unknown',
            [['Immune system', u'Systemisk allergisk reaktion'],
             ['Psychiatric', u'Oro, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Eye', u'\xd6verg\xe5ende synst\xf6rningar'],
             ['Cardiac', u'Hj\xe4rtklappning'],
             ['Vascular', u'H\xf6gt blodtryck'],
             ['Respiratory',
              u'Stickande eller br\xe4nnande   k\xe4nsla i n\xe4sa och svalg, torr']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'LFSU'}