{'_data': [['Common',
            [['General', u'Tr\xf6tthet. Yrsel.'],
             ['Nervous system',
              u'Tardiv dyskinesi (l\xe5ngtidsbehandling), parkinsonism, akatisi.'],
             ['Cardiac', u'Blodtrycksfall, takykardi.'],
             ['Skin', u'Hudallergier.'],
             ['GI', u'Muntorrhet.'],
             ['Metabolism', u'Vikt\xf6kning.']]],
           ['Uncommon',
            [['Endocrine', u'Gynekomasti, galaktorr\xe9.'],
             ['GI', u'Obstipation.'],
             ['Renal', u'Urinretention.'],
             ['Eye', u'Ackommodationsst\xf6rningar.']]],
           ['Rare',
            [['Blood', u'Agranulocytos, leukopeni.'],
             ['Nervous system', u'Akut dystoni, malignt neuroleptikasyndrom.'],
             ['Hepato', u'Hepatit med ikterus av stastyp.'],
             ['GI', u'Paralytisk ileus.'],
             ['Eye',
              u'Lins- och corneagrumlingar (h\xf6gdos/l\xe5ngtidsbehandling). Fentiaziner har rapporterats kunna s\xe4nka kramptr\xf6skeln hos predisponerade individer. Fentiaziner kan dosberoende f\xf6rl\xe4nga QT-intervallet med risk f\xf6r allvarliga hj\xe4rtarytmier s\xe5som Torsades de Pointes. Fall av pl\xf6tslig d\xf6d med misst\xe4nkt kardiell orsak har rapporterats vid behandling med fentiaziner. I h\xf6ga doser och hos predisponerade patienter kan dessa biverkningar upptr\xe4da i h\xf6gre frekvens (se \xe4ven 4.4 Varningar och f\xf6rsiktighetsm\xe5tt). Sexuell dysfunktion och hyperprolaktinemi har rapporterats. Fall av ven\xf6s trombo-embolisk sjukdom, inkluderat fall av lungemboli och fall av djup ventrombos, har rapporterats med antipsykotiska l\xe4kemedel \u2013 Ok\xe4nd frekvens.']]],
           ['Very rare',
            [['Cardiac', u'QT-intervallf\xf6rl\xe4ngning, Torsade de Pointes.'],
             ['GI', u'Nekrotiserande enterokolit (kan vara fatal).'],
             ['Renal', u'Priapism.']]],
           ['Unknown',
            [['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom (se 4.6).'],
             ['Metabolism', u'Glukosintolerans, hyperglykemi (se 4.4).']]]],
 '_pages': [4, 6],
 u'_rank': 20,
 u'_type': u'LSFU'}