{'_data': [['Very common',
            [['Infections',
              u'urinv\xe4gsinfektion, \xf6vre luftv\xe4gsinfektion, cytomegalovirusinfektion*, bronkit'],
             ['Blood', u'anemi, leukopeni'],
             ['Metabolism',
              u'hypofosfatemi, hypokalemi, dyslipidemi, hyperkalemi, hyperglykemi, hypokalcemi'],
             ['Psychiatric', u's\xf6mnl\xf6shet, \xe5ngest'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Vascular', u'hypertension, hypotension'],
             ['Respiratory', u'dyspn\xe9, hosta'],
             ['GI', u'diarr\xe9, f\xf6rstoppning, illam\xe5ende, kr\xe4kningar, buksm\xe4rta'],
             ['Musculoskeletal', u'artralgi, ryggsm\xe4rta, sm\xe4rta i extremiteter'],
             ['Renal', u'proteinuri, f\xf6rh\xf6jt blodkreatinin, dysuri, hematuri'],
             ['General', u'perifert \xf6dem, feber'],
             ['Injury', u'nedsatt funktion hos transplantat']]],
           ['Common',
            [['Infections',
              u'sepsis, pneumoni, influensa, gastroenterit, herpes zoster, sinusit, herpes simplex, oral candidiasis, pyelonefrit, onykomykos, BK-virusinfektion, infektion i andningsv\xe4garna, candidiasis, rinit, cellulit, s\xe5rinfektion, lokal infektion, herpesvirusinfektion, svampinfektion, svampinfektion i huden'],
             ['Neoplasms', u'skivepitelcancer i huden, basaliom, hudpapillom'],
             ['Blood', u'trombocytopeni, neutropeni, leukocytos, polycytemi, lymfopeni'],
             ['Immune system',
              u'minskat immunglobulin G i blod, minskat immunglobulin M i blod'],
             ['Endocrine', u'syndrom'],
             ['Metabolism',
              u'viktuppg\xe5ng, diabetes mellitus, dehydrering, viktnedg\xe5ng, acidos, v\xe4tskeretention, hypercalcemi, hyperproteinemi'],
             ['Psychiatric', u'depression'],
             ['Nervous system',
              u'tremor, parestesi, kardiovaskul\xe4r h\xe4ndelse, yrsel, synkope, letargi, perifer neuropati'],
             ['Eye', u'katarakt, okul\xe4r hyperemi, dimsyn'],
             ['Ear', u'vertigo, \xf6ronsm\xe4rta, tinnitus'],
             ['Cardiac',
              u'takykardi, bradykardi, f\xf6rmaksflimmer, hj\xe4rtsvikt, k\xe4rlkramp, v\xe4nsterkammarhypertrofi'],
             ['Vascular', u'chock, infarkt, hematom, lymfocele, angiopati, arteriell fibros'],
             ['Respiratory',
              u'lung\xf6dem, v\xe4sande andning, hypokapni, ortopn\xe9, n\xe4sblod, orofaryngeal sm\xe4rta'],
             ['GI', u'dyspepsi, aft\xf6s stomatit, bukbr\xe5ck'],
             ['Hepato', u'cytolytisk hepatit, onormala leverfunktionstester'],
             ['Skin',
              u'acne, kl\xe5da, alopeci, hudlesion, utslag, nattliga svettningar, hyperhidros'],
             ['Musculoskeletal',
              u'myalgi, muskelsvaghet, sm\xe4rta i benv\xe4vnad, svullna leder, mellankotsf\xf6rskjutning, l\xe5sning av leden, muskelspasm, osteoartrit'],
             ['Renal',
              u'tubul\xe4r nekros, ven\xf6s njurtrombos*, arteriell njurstenos, glukosuri, vattennjure, vesikouterisk reflux, urininkontinens, urinretention, nokturi'],
             ['Reproductive system', u'vattenbr\xe5ck Mindra vanliga hypofosfatasi'],
             ['General',
              u'br\xf6stsm\xe4rta, tr\xf6tthet, sjukdomsk\xe4nsla, f\xf6rs\xe4mrad l\xe4kning Mindra vanliga infusionsrelaterade reaktioner*, irriabilitet, fibros, imflammation, \xe5terfall i sjukdom, v\xe4rmek\xe4nsla, s\xe5r'],
             ['Investigations',
              u'f\xf6rh\xf6jt c-reaktivt protein, f\xf6rh\xf6jt paratyroideahormon i blod Mindra vanliga f\xf6rh\xf6jda pankreasenzymer, f\xf6rh\xf6jt troponin, obalans i elektrolyter, f\xf6rhj\xf6t prostataspecifikt antigen, f\xf6rh\xf6jd urinsyra i blod, minskad m\xe4ngd urin, minskad blodglukos, minskat antal CD4-lymfocyter'],
             ['Injury', u'kronisk allograft nefropati (CAN), \xe4rrbr\xe5ck']]],
           ['Uncommon',
            [['Infections',
              u'progressive multifocal leukoencefalopati*, cerebral svampinfektion, cytomegalovirus(CMV)-kolit, polyomavirus-associerad nefropati, genital herpes, stafylokockinfektion, endokardit, tuberkulos*, bronkiektasi, osteomyelit, strongyloidiasis, blastocytinfektion, giardiasis, lymfk\xe4rlsinflammation'],
             ['Neoplasms',
              u'EBV-associerad lymfoproliferativ rubbning**, lungcancer, rektalcancer, br\xf6stcancer, sarkom, Kaposis sarkom, prostatacancer, cervixkarcinom, laryngealcancer, lymfom, multipelt myelom, \xf6verg\xe5ende cellkarcinom'],
             ['Blood',
              u'monocytopeni, erytroblastopeni (pure red cell aplasia), agranulocytos, hemolys, hyperkoagulation'],
             ['Immune system', u'hypogammaglobulinemi, s\xe4songsastma'],
             ['Endocrine', u'binjureinsufficiens'],
             ['Metabolism',
              u'diabetesketoacidos, diabetesfot, alkalos, minskad aptit, vitamin-D-brist'],
             ['Psychiatric',
              u'onormala dr\xf6mmar, hum\xf6rsv\xe4ngningar, nedsatt koncentrationsf\xf6rm\xe5ga/hyperaktivitet, \xf6kad libido'],
             ['Nervous system',
              u'encefalit, Guillain-Barr\xe9s syndrom, hj\xe4rn\xf6dem, \xf6kat intrakraniellt tryck, encefalopati, krampanfall, hemipares, demyelinisering, ansiktsf\xf6rlamning, dysgeusi, kognitiv st\xf6rning, f\xf6rs\xe4mrat minne, migr\xe4n, br\xe4nnande k\xe4nsla, diabetesnefropati, rastl\xf6sa ben syndrom'],
             ['Eye',
              u'retinit, konjunktivit, \xf6goninflammation, keratit, ljuskygghet, \xf6gonlocks\xf6dem'],
             ['Ear', u'nedsatt h\xf6rsel'],
             ['Cardiac',
              u'akut koronark\xe4rlssjukdom, atrioventrikul\xe4rblock (andra graden), sjukdom i aortaklaffen, supraventrikul\xe4r arrytmi'],
             ['Vascular',
              u'ven\xf6s trombos, arteriell trombos, tromboflebit, arteriell stenos, f\xf6nstertittarsjuka, blodvallning'],
             ['Respiratory',
              u'akut andn\xf6dssyndrom, pulmonell hypertoni, pneumonit, hemoptys, bronkopneumopati, sm\xe4rtsam andning, pleurautgjutning, s\xf6mnapn\xe9, dysfoni, orofaryngeala bl\xe5sor'],
             ['GI',
              u'gastrointestinal rubbning, pankreatit, stort tarms\xe5r, melena, gastroduodenalt s\xe5r, rektal bl\xf6dning, liten tarmobstruktion, l\xe4ppinflammation, gingivahyperplasi, sm\xe4rta i spottk\xf6rtlarna, missf\xe4rgad avf\xf6ring'],
             ['Hepato', u'gallstenslidande, levercysta, leversteatos'],
             ['Skin',
              u'psoriasis, onormal h\xe5rv\xe4xt, onychoclasi, penilt s\xe5r, svullet ansikte, trikorrexi'],
             ['Musculoskeletal',
              u'f\xf6r\xe4ndringar i benmetabolismen, beninflammation, osteolys, synovit'],
             ['Renal',
              u'arteriell njurtrombos*, nefrit, nefroskleros, tubul\xe4r atrofi, bl\xf6dande cystit, njurfibros'],
             ['Reproductive system',
              u'epididymit, priapism, cervixdysplasi, br\xf6stmassa, testikelsm\xe4rta, vulvas\xe5r, atrofisk vulvovaginit, infertilitet, skrotal\xf6dem Medf\xf6dda och/eller genetiska st\xf6rningar'],
             ['Injury',
              u'f\xf6rlust av transplantatfunktion, transfusionsreaktion, s\xe5rruptur, fraktur, senruptur, hypotoni vid procedur, hypertoni vid procedur, hematom efter procedur, sm\xe4rta vid procedur, huvudv\xe4rk vid procedur, f\xf6rvirring *Se avsnitt "Beskrivning av utvalda biverkningar" **Inkluderar alla rapporterade h\xe4ndelser \xf6ver en median p\xe5 3,3 \xe5r i fas III-studierna och en median p\xe5 ungef\xe4r 7 \xe5r i fas II studierna. 9 Beskrivning av utvalda biverkningar Maligniteter och lymfoproliferativ sjukdom efter transplantation (PTLD) Frekvensen av malignitet vid \xe5r 1 och \xe5r 3, med undantag av fall av PTLD som visas vid \xe5r 1 och > 3 \xe5r, visas i tabell 3 (medianen f\xf6r antalet uppf\xf6ljningsdagar var 1199 dagar f\xf6r belatacept MI, 1206 dagar f\xf6r belatacept LI och 1139 dagar f\xf6r ciklosporin). Frekvensen av maligna neoplasier, exklusive icke-melanoma hudcancerformer, vid \xe5r 3 var likv\xe4rdig i belatacept LI-gruppen och ciklosporingruppen men h\xf6gre i belatacept MI-gruppen. PTLD f\xf6rekom mer frekvent i de b\xe5da belataceptbehandlade grupperna i j\xe4mf\xf6relse med ciklosporin (se avsnitt 4.4). Icke-melanoma hudcancerformer f\xf6rekom mindre frekvent med belatacept LI-regimen \xe4n med ciklosporin eller belatacept MI-regimen. I de tre studierna (en fas II och tv\xe5 fas III studier, studie 1 och 2) var den kumulativa frekvensen av PTLD h\xf6gre i den belataceptbehandlade patientgruppen som fick den rekommenderade doseringsregimen (LI) (1,3%; 6/472) \xe4n hos ciklosporingruppen (0,6%; 3/476) och h\xf6gst i belatacept MI-gruppen (1,7%; 8/477). Nio av 14 fall av PTLD hos belataceptbehandlade patienter var lokaliserade i CNS och inom observationsperioden hade 8 av 14 fall d\xf6dlig utg\xe5ng (6 av fallen med d\xf6lig utg\xe5ng involverade CNS). Av de 6 PTLD-fallen som f\xf6rekom i LI-gruppen, involverade 3 fall CNS och hade d\xf6dlig utg\xe5ng. EBV-seronegativa patienter som f\xe5r immunsuppressiva medel har en s\xe4rskilt h\xf6g risk att drabbas av PTLD. I de kliniska studierna hade de belataceptbehandlade mottagarna med EBV-seronegativt status en f\xf6rh\xf6jd risk att drabbas av PTLD j\xe4mf\xf6rt med de EBV-positiva mottagarna (7,7%; 7/91 respektive 0,7%; 6/810). I den rekommenderade doseringsregimen av belatacept fanns 404 EBV-positiva mottagare och 4 fall av PTLD intr\xe4ffade (1,0%). Tv\xe5 av dessa PTLD-fall uppstod i CNS. Tabell 3: F\xf6rekomst av maligniteter per behandlingsgrupp (%) Upp till \xe5r 1 Upp till \xe5r 3* Belatacept Belatacept Ciklosporin Belatacept Belatacept Ciklosporin MI LI N= 476 MI LI N= 476 N= 477 N= 472 N= 477 N= 472 Samtliga 3,4 1,9 3,4 8,6 5,7 7,1 maligna neoplasier Icke-melanom 1,0 0,2 1,5 4,2 1,5 3,6 hudcancer Maligna 2,3 1,7 1,9 4,4 4,2 3,6 neoplasier exklusive icke melanom hudcancer PTLD** 0,8 0,8 0,2 1,7 1,3 0,6 Maligniteter 1,5 0,8 1,7 2,7 3,2 3,4 exklusive icke melanom hudcancer och PTLD *Medianuppf\xf6ljningstid, exklusive PTLD, f\xf6r sammanslagna studier \xe4r 1092 dagar f\xf6r varje behandlingsgrupp. **Medianuppf\xf6ljningstid f\xf6r PTLD f\xf6r sammanslagna studier \xe4r 1199 dagar f\xf6r MI, 1206 dagar f\xf6r LI och 1139 dagar f\xf6r ciklosporin. Infektioner 10 Infektionsfrekvenser vid \xe5r 1 och \xe5r 3 med f\xf6rekomst per behandlingsgrupp visas i tabell 4. Den sammanslagna f\xf6rekomsten av tuberkulosinfektioner och icke-allvarliga herpesinfektioner var h\xf6gre i belataceptregimerna \xe4n i ciklosporinregimen. Majoriteten av tuberkulosfallen f\xf6rekom hos patienter som bodde eller tidigare hade bott i l\xe4nder med en h\xf6g prevalens av tuberkulos (se avsnitt 4.4). Sammanslagen frekvens av polyomavirusinfektioner och svampinfektioner var l\xe4gre i belatacept LI gruppen \xe4n i belatacept MI- och ciklosporingruppen. I det kliniska belataceptprogrammet diagnostiserades tv\xe5 patienter med PML. Ett fall av PML med d\xf6dlig utg\xe5ng rapporterades hos en njurtransplantatsmottagare behandlad med belatacept MI-regimen, en IL-2-receptorantagonist, MMF och kortikosteroider under tv\xe5 \xe5r i en fas III-studie. Det andra fallet av PML rapporterades i en fas II studie hos en levertransplantatsmottagare som fick sex m\xe5naders behandling med en ut\xf6kad belatacept MI-regim, MMF i h\xf6gre doser \xe4n rekommenderat och kortikosteroider (se avsnitt 4.4). Infektioner som innefattade CNS f\xf6rekom mer frekvent i belatacept MI-gruppen (8 fall inklusive PML-fallet ovan; 1,7%) \xe4n i belatacept LI-gruppen (2 fall; 0,4%) och ciklosporingruppen (1 fall; 0,2%). Den vanligaste CNS-infektionen var kryptokockmeningit. Tabell 4: F\xf6rekomst av infektioner per behandlingsgrupp (%) Upp till \xe5r 1 Upp till \xe5r 3* Belatacep Belatacep Ciklospori Belatacep Belatacep Ciklospori t MI t LI n N= 476 t MI t LI n N= 476 N= 477 N= 472 N= 477 N= 472 Infektioner och 70,7 71,8 73,7 79,2 82,0 80,6 infestationer Allvarliga 26,8 23,3 27,3 35,8 33,5 37,8 infektioner Virala 26,4 25,0 27,7 38,8 39,0 36,1 infektioner CMV 11,1 11,9 13,7 13,8 13,8 14,7 Polyomavirus 4,8 2,3 4,8 6,3 3,8 5,7 Herpes 8,0 6,6 6,1 15,5 14,2 10,7 Svampinfektione 13,8 11,0 15,1 22,9 16,7 20,6 r Tuberkulos 0,4 0,4 0,2 1,3 1,3 0,2 *Medianf\xf6rekomst f\xf6r poolade studier \xe4r 1092 dagar f\xf6r varje behandlingsgrupp. Ttransplantattrombos I en fas III studie med mottagare av njurar fr\xe5n avlidna donatorer med ut\xf6kade riskkriterier (expanded criteria donor, ECD) (studie 2), f\xf6rekom transplantattrombos mer frekvent i belataceptgrupperna (4,3% f\xf6r LI-regimen respektive 5,1% f\xf6r MI-regimen) \xe4n i ciklosporingruppen (2,2%). I en annan fas III studie med mottagare av njurar fr\xe5n levande donator och fr\xe5n avliden donator med standard riskkriterier (studie 1) var incidensen av transplantattrombos 2,3% f\xf6r MI-regimen respektive 0,4% f\xf6r LI-regimen, j\xe4mf\xf6rt med 1,8% i ciklosporingruppen. I en fas II studie f\xf6rekom 2 fall av transplantattrombos, 1 fall i vardera MI- och LI-gruppen (incidens 1,4% i b\xe5da grupperna) mot 0 fall i ciklosporingruppen. Generellt sett uppkom dessa h\xe4ndelser i b\xf6rjan av behandlingen och majoriteten av fallen resulterade i f\xf6rlust av transplantatet. Infusionsrelaterade reaktioner Upp till \xe5r 3 rapporterades inga h\xe4ndelser av anafylaxi eller \xf6verk\xe4nslighet relaterade till l\xe4kemedlet.']]]],
 '_pages': [7, 12],
 u'_rank': 54,
 u'_type': u'LSFU'}