{'_data': [['Very common',
            [['Infections',
              u'urinv\xe4gsinfektion, \xf6vre luftv\xe4gsinfektion, cytomegalovirusinfektion*, bronkit'],
             ['Blood', u'anemi, leukopeni'],
             ['Metabolism',
              u'hypofosfatemi, hypokalemi, dyslipidemi, hyperkalemi, hyperglykemi, hypokalcemi'],
             ['Psychiatric', u's\xf6mnl\xf6shet, \xe5ngest'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Vascular', u'hypertension, hypotension'],
             ['Respiratory', u'dyspn\xe9, hosta'],
             ['GI', u'diarr\xe9, f\xf6rstoppning, illam\xe5ende, kr\xe4kningar, buksm\xe4rta'],
             ['Musculoskeletal', u'artralgi, ryggsm\xe4rta, sm\xe4rta i extremiteter'],
             ['Renal', u'proteinuri, f\xf6rh\xf6jt blodkreatinin, dysuri, hematuri'],
             ['General', u'perifert \xf6dem, feber'],
             ['Injury', u'nedsatt funktion hos transplantat']]],
           ['Common',
            [['Infections',
              u'sepsis, pneumoni, influensa, gastroenterit, herpes zoster, sinusit, herpes simplex, oral candidiasis, pyelonefrit, onykomykos, BK-virusinfektion, infektion i andningsv\xe4garna, candidiasis, rinit, cellulit, s\xe5rinfektion, lokal infektion, herpesvirusinfektion, svampinfektion, svampinfektion i huden'],
             ['Neoplasms', u'skivepitelcancer i huden, basaliom, hudpapillom'],
             ['Blood', u'trombocytopeni, neutropeni, leukocytos, polycytemi, lymfopeni'],
             ['Immune system',
              u'minskat immunglobulin G i blod, minskat immunglobulin M i blod'],
             ['Endocrine', u'syndrom'],
             ['Metabolism',
              u'viktuppg\xe5ng, diabetes mellitus, dehydrering, viktnedg\xe5ng, acidos, v\xe4tskeretention, hypercalcemi, hyperproteinemi'],
             ['Psychiatric', u'depression'],
             ['Nervous system',
              u'tremor, parestesi, kardiovaskul\xe4r h\xe4ndelse, yrsel, synkope, letargi, perifer neuropati'],
             ['Eye', u'katarakt, okul\xe4r hyperemi, dimsyn'],
             ['Ear', u'vertigo, \xf6ronsm\xe4rta, tinnitus'],
             ['Cardiac',
              u'takykardi, bradykardi, f\xf6rmaksflimmer, hj\xe4rtsvikt, k\xe4rlkramp, v\xe4nsterkammarhypertrofi'],
             ['Vascular', u'chock, infarkt, hematom, lymfocele, angiopati, arteriell fibros 8'],
             ['Respiratory',
              u'lung\xf6dem, v\xe4sande andning, hypokapni, ortopn\xe9, n\xe4sblod, orofaryngeal sm\xe4rta'],
             ['GI', u'dyspepsi, aft\xf6s stomatit, bukbr\xe5ck'],
             ['Hepato', u'cytolytisk hepatit, onormala leverfunktionstester'],
             ['Skin',
              u'acne, kl\xe5da, alopeci, hudlesion, utslag, nattliga svettningar, hyperhidros'],
             ['Musculoskeletal',
              u'myalgi, muskelsvaghet, sm\xe4rta i benv\xe4vnad, svullna leder, mellankotsf\xf6rskjutning, l\xe5sning av leden, muskelspasm, osteoartrit'],
             ['Renal',
              u'tubul\xe4r nekros, ven\xf6s njurtrombos*, arteriell njurstenos, glukosuri, vattennjure, vesikouterisk reflux, urininkontinens, urinretention, nokturi'],
             ['Reproductive system', u'vattenbr\xe5ck Mindra vanliga hypofosfatasi'],
             ['General',
              u'br\xf6stsm\xe4rta, tr\xf6tthet, sjukdomsk\xe4nsla, f\xf6rs\xe4mrad l\xe4kning Mindra vanliga infusionsrelaterade reaktioner*, irriabilitet, fibros, imflammation, \xe5terfall i sjukdom, v\xe4rmek\xe4nsla, s\xe5r'],
             ['Investigations',
              u'f\xf6rh\xf6jt c-reaktivt protein, f\xf6rh\xf6jt paratyroideahormon i blod Mindra vanliga f\xf6rh\xf6jda pankreasenzymer, f\xf6rh\xf6jt troponin, obalans i elektrolyter, f\xf6rhj\xf6t prostataspecifikt antigen, f\xf6rh\xf6jd urinsyra i blod, minskad m\xe4ngd urin, 9 minskad blodglukos, minskat antal CD4-lymfocyter'],
             ['Injury', u'kronisk allograft nefropati (CAN), \xe4rrbr\xe5ck']]],
           ['Uncommon',
            [['Infections',
              u'progressive multifocal leukoencefalopati*, cerebral svampinfektion, cytomegalovirus(CMV)-kolit, polyomavirus-associerad nefropati, genital herpes, stafylokockinfektion, endokardit, tuberkulos*, bronkiektasi, osteomyelit, strongyloidiasis, blastocytinfektion, giardiasis, lymfk\xe4rlsinflammation'],
             ['Neoplasms',
              u'EBV-associerad lymfoproliferativ rubbning**, lungcancer, rektalcancer, 7 br\xf6stcancer, sarkom, Kaposis sarkom, prostatacancer, cervixkarcinom, laryngealcancer, lymfom, multipelt myelom, \xf6verg\xe5ende cellkarcinom'],
             ['Blood',
              u'monocytopeni, erytroblastopeni (pure red cell aplasia), agranulocytos, hemolys, hyperkoagulation'],
             ['Immune system', u'hypogammaglobulinemi, s\xe4songsastma'],
             ['Endocrine', u'binjureinsufficiens'],
             ['Metabolism',
              u'diabetesketoacidos, diabetesfot, alkalos, minskad aptit, vitamin-D-brist'],
             ['Psychiatric',
              u'onormala dr\xf6mmar, hum\xf6rsv\xe4ngningar, nedsatt koncentrationsf\xf6rm\xe5ga/hyperaktivitet, \xf6kad libido'],
             ['Nervous system',
              u'encefalit, Guillain-Barr\xe9s syndrom, hj\xe4rn\xf6dem, \xf6kat intrakraniellt tryck, encefalopati, krampanfall, hemipares, demyelinisering, ansiktsf\xf6rlamning, dysgeusi, kognitiv st\xf6rning, f\xf6rs\xe4mrat minne, migr\xe4n, br\xe4nnande k\xe4nsla, diabetesnefropati, rastl\xf6sa ben syndrom'],
             ['Eye',
              u'retinit, konjunktivit, \xf6goninflammation, keratit, ljuskygghet, \xf6gonlocks\xf6dem'],
             ['Ear', u'nedsatt h\xf6rsel'],
             ['Cardiac',
              u'akut koronark\xe4rlssjukdom, atrioventrikul\xe4rblock (andra graden), sjukdom i aortaklaffen, supraventrikul\xe4r arrytmi'],
             ['Vascular',
              u'ven\xf6s trombos, arteriell trombos, tromboflebit, arteriell stenos, f\xf6nstertittarsjuka, blodvallning'],
             ['Respiratory',
              u'akut andn\xf6dssyndrom, pulmonell hypertoni, pneumonit, hemoptys, bronkopneumopati, sm\xe4rtsam andning, pleurautgjutning, s\xf6mnapn\xe9, dysfoni, orofaryngeala bl\xe5sor'],
             ['GI',
              u'gastrointestinal rubbning, pankreatit, stort tarms\xe5r, melena, gastroduodenalt s\xe5r, rektal bl\xf6dning, liten tarmobstruktion, l\xe4ppinflammation, gingivahyperplasi, sm\xe4rta i spottk\xf6rtlarna, missf\xe4rgad avf\xf6ring'],
             ['Hepato', u'gallstenslidande, levercysta, leversteatos'],
             ['Skin',
              u'psoriasis, onormal h\xe5rv\xe4xt, onychoclasi, penilt s\xe5r, svullet ansikte, trikorrexi'],
             ['Musculoskeletal',
              u'f\xf6r\xe4ndringar i benmetabolismen, beninflammation, osteolys, synovit'],
             ['Renal',
              u'arteriell njurtrombos*, nefrit, nefroskleros, tubul\xe4r atrofi, bl\xf6dande cystit, njurfibros'],
             ['Reproductive system',
              u'epididymit, priapism, cervixdysplasi, br\xf6stmassa, testikelsm\xe4rta, vulvas\xe5r, atrofisk vulvovaginit, infertilitet, skrotal\xf6dem Medf\xf6dda och/eller genetiska st\xf6rningar'],
             ['Injury',
              u'f\xf6rlust av transplantatfunktion, transfusionsreaktion, s\xe5rruptur, fraktur, senruptur, hypotoni vid procedur, hypertoni vid procedur, hematom efter procedur, sm\xe4rta vid procedur, huvudv\xe4rk vid procedur, f\xf6rvirring']]],
           ['Unknown',
            [['Nervous system',
              u'EBV-seronegativa patienter som f\xe5r immunsuppressiva medel har en s\xe4rskilt h\xf6g risk att drabbas av PTLD. I de kliniska studierna hade de belataceptbehandlade mottagarna med EBV-seronegativt status en f\xf6rh\xf6jd risk att drabbas av PTLD j\xe4mf\xf6rt med de EBV-positiva mottagarna (7,7%; 7/91 respektive 0,7%; 6/810). I den rekommenderade doseringsregimen av belatacept fanns 404 EBV-positiva mottagare och 4 fall av PTLD intr\xe4ffade (1,0%). Tv\xe5 av dessa PTLD-fall uppstod i CNS.']]]],
 '_pages': [6, 12],
 u'_rank': 55,
 u'_type': u'LSFU'}