{'_data': [['Very common',
            [['Blood', u'Acidos'],
             ['Blood', u'Hypervolemi'],
             ['Metabolism', u'Anorexi'],
<<<<<<< HEAD
             ['Respiratory', u'Kr\xe4kningar'],
             ['Respiratory', u'Illam\xe5ende'],
             ['Respiratory', u'Gastrit'],
             ['GI', u'Asteni'],
             ['General', u'\xd6kad urea i blod']]],
           ['Common',
            [['Infections', u'Infektion'],
             ['Blood', u'Anemi'],
             ['Metabolism', u'Hypokalemi'],
             ['Metabolism', u'Hypovolemi'],
             ['Psychiatric', u'Depression'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Respiratory', u'Buksm\xe4rtor']]],
           ['Unknown',
            [['Infections', u''],
             ['Respiratory', u''],
             ['GI', u'Skleroserande peritonit  Obehag fr\xe5n buken'],
             ['GI', u'Peritonit'],
             ['GI', u'Grumligt dialysat fr\xe5n peritoneum'],
             ['General', u'Pyrexi'],
             ['General', u'Sjukdomsk\xe4nsla'],
             ['Investigations', u''],
             ['Investigations', u'Onormal peritonealv\xe4tskeanalys Kl\xe5da'],
             ['Skin', u'Angio\xf6dem']]]],
 '_pages': [4, 6],
 u'_rank': 22,
=======
             ['Psychiatric', u'Kr\xe4kningar'],
             ['Psychiatric', u'Illam\xe5ende'],
             ['Psychiatric', u'Gastrit'],
             ['GI', u'Asteni'],
             ['GI', u'\xd6kad urea i blod']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Hypokalemi'],
             ['Metabolism', u'Hypovolemi'],
             ['Psychiatric', u'Depression'],
             ['Psychiatric', u'Buksm\xe4rtor']]],
           ['Unknown',
            [['Psychiatric', u''],
             ['GI', u'Skleroserande peritonit  Obehag fr\xe5n buken'],
             ['GI', u'Peritonit'],
             ['GI', u'Grumligt dialysat fr\xe5n peritoneum'],
             ['GI', u'Sjukdomsk\xe4nsla'],
             ['Investigations', u'Onormal peritonealv\xe4tskeanalys'],
             ['Investigations', u'Kl\xe5da'],
             ['Skin', u'Angio\xf6dem']]]],
 '_pages': [4, 6],
 u'_rank': 20,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}