{'_data': [['Very common',
            [['Blood', u'Acidos'],
             ['Blood', u'Hypervolemi'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Kr\xe4kningar'],
             ['Psychiatric', u'Illam\xe5ende'],
             ['Psychiatric', u'Gastrit'],
             ['GI', u'Asteni'],
             ['GI', u'\xd6kad urea i blod']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Metabolism', u'Hypokalemi'],
             ['Metabolism', u'Hypovolemi'],
             ['Psychiatric', u'Depression'],
             ['Psychiatric', u'Buksm\xe4rtor']]],
           ['Unknown',
            [['Psychiatric', u''],
             ['GI', u'Skleroserande peritonit  Obehag fr\xe5n buken'],
             ['GI', u'Peritonit'],
             ['GI', u'Grumligt dialysat fr\xe5n peritoneum'],
             ['GI', u'Sjukdomsk\xe4nsla'],
             ['Investigations', u'Onormal peritonealv\xe4tskeanalys'],
             ['Investigations', u'Kl\xe5da'],
             ['Skin', u'Angio\xf6dem']]]],
 '_pages': [4, 6],
 u'_rank': 20,
 u'_type': u'TSFU'}