{'_data': [['Uncommon',
            [['Eye', u'\xd6ron och balansorgan  '],
             ['Renal',
              u'Muskelatrofi, S\xe4llsynta: Onormal benutveckling, bensm\xe4rta osteokondros, muskelsvaghet, sm\xe4rta i extremiteter Endokrina systemet Vanliga: Hypotyreoidism S\xe4llsynta: Hypotyreoidism Metabolism och Vanliga: Nedsatt glukostolerans S\xe4llsynta: Diabetes mellitus, nutrition Mindre vanliga: Hypoglykemi, hyperglykemi, hypoglykemi, hyperfosfatemi nedsatt glukostolerans Neoplasier; benigna, Mindre vanliga: Malign neoplasm, S\xe4llsynta: \xc5terfall av malign maligna och benign neoplasm neoplasm, melanocytnevus ospecificerade (samt cystor och polyper) Blodk\xe4rl Mindre vanliga: Hypertension S\xe4llsynta: Hypertension Allm\xe4nna symtom Mycket vanliga hos vuxna, vanliga Mindre vanliga: Perifert \xf6dem, och/eller symtom vid hos barn: Perifert \xf6dem, \xf6dem \xf6dem, reaktion vid injektionsst\xe4llet administreringsst\xe4llet Vanliga: Asteni, reaktion vid (irritation, sm\xe4rta) injektionsst\xe4llet S\xe4llsynta: Asteni, ansikts\xf6dem,'],
             ['Renal',
              u'Bl\xf6dning vid tr\xf6tthet, irritabilitet, sm\xe4rta, pyrexi, injektionsst\xe4llet, atrofi vid reaktion vid injektionsst\xe4llet injektionsst\xe4llet, kn\xf6l vid (bl\xf6dning, hematom, atrofi, injektionsst\xe4llet, hypertrofi urtikaria, kl\xe5da, svullnad, erytem)']]],
           ['Rare', [['Eye', u'Andningsv\xe4gar,  ']]],
           ['Unknown',
            [['Cardiac', u'lymfsystemet'],
             ['Renal',
              u'pollakiuri, polyuri, onormal urin Hud och subkutan Mindre vanliga: Exfoliativ dermatit, S\xe4llsynta: Generaliserad pruritus, v\xe4vnad hudatrofi, hudhypertrofi, hirsutism, urtikaria, utslag lipodystrofi, urtikaria Muskuloskeletala Mycket vanliga hos vuxna, vanliga Mindre vanliga: Epifysiolys, systemet och bindv\xe4v hos barn: Artralgi, myalgi skoliosprogression, artralgi'],
             ['Reproductive system',
              u'flytning fr\xe5n k\xf6nsorgan Psykiska st\xf6rningar Mindre vanliga: S\xe4llsynta: Avvikande beteende, Personlighetsst\xf6rning depression, s\xf6mnl\xf6shet']]]],
 '_pages': [4, 6],
 u'_rank': 7,
 u'_type': u'LSFU'}