{'_data': [['Very common',
            [['Metabolism', u'Hyperglykemi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Diarr\xe9, buksm\xe4rta, illam\xe5ende, f\xf6rstoppning, uppk\xf6rdhet (flatulens)'],
             ['Hepato', u'Kolelitiasis'],
             ['General', u'Lokal sm\xe4rta vid injektionsst\xe4llet']]],
           ['Common',
            [['Endocrine',
              u'Hypotyroidism, sk\xf6ldk\xf6rteldysfunktion (t.ex. minskade niv\xe5er av TSH, totalt T4 och fritt T4)'],
             ['Metabolism', u'Hypoglykemi, f\xf6rs\xe4mrad glukostolerans, anorexi'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac', u'Bradykardi'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI',
              u'Dyspepsi, kr\xe4kning, v\xe4dersp\xe4nning, steatorr\xe9, l\xf6s avf\xf6ring, missf\xe4rgning av avf\xf6ring'],
             ['Hepato', u'Kolecystit, gallbl\xe5seslam, hyperbilirubinemi'],
             ['Skin', u'Kl\xe5da, utslag, alopeci'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er av transaminas Efter f\xf6rs\xe4ljning Spontant rapporterade biverkningar anges i tabell 2 och har rapporterats frivilligt. Det \xe4r inte alltid m\xf6jligt att fastst\xe4lla frekvens eller orsakssamband betr\xe4ffande l\xe4kemedelsexponering.']]],
           ['Uncommon', [['Metabolism', u'Uttorkning'], ['Cardiac', u'Takykardi']]],
           ['Rare',
            [['GI',
              u'Akut tarmobstruktion, sv\xe5r epigastrisk sm\xe4rta, \xf6m och sp\xe4nd buk, akut pankreatit, kolelitiasisinducerad pankreatit']]],
           ['Unknown',
            [['Hepato',
              u'kolestas, gulsot, kolestatisk gulsot Hud och subkutan v\xe4vnad Urticaria Unders\xf6kningar F\xf6rh\xf6jda niv\xe5er av alkalisk fosfatas och gammaglutamyltransferas']]]],
 '_pages': [5, 6],
 u'_rank': 18,
 u'_type': u'LSFU'}