{'_data': [['Very common', []],
           ['Common',
            [['GI',
              u'Diarr\xe9, steatorr\xe9, gasbildning, l\xf6s avf\xf6ring, illam\xe5ende, magsm\xe4rta och sp\xe4nd buk'],
             ['Endocrine',
              u'Hyperglykemi, f\xf6rs\xe4mrad glukostolerans efter m\xe5ltid och i vissa fall ih\xe5llande hyperglykemi. Hypoglykemi'],
             ['General',
              u'Sm\xe4rta vid injektionsst\xe4llet, svidande, bultande eller br\xe4nnande']]],
           ['Uncommon',
            [['Cardiac', u'Bradykardi Takykardi'],
             ['GI', u'Aptitl\xf6shet, illam\xe5ende, kr\xe4kningar, epigastrala sm\xe4rtor'],
             ['Skin', u'\xd6verg\xe5ende h\xe5ravfall']]],
           ['Rare',
            [['GI',
              u'Akut tarmobstruktion, Allvarliga epigastrala sm\xe4rtor, \xf6mhet och kramper i magen. Akut pankreatit. Fall av gallstensinducerad pankreatit (2).'],
             ['Skin', u'\xd6verk\xe4nslighets-reaktioner, hudutslag'],
             ['Immune system', u'Hypersensitivitet, hudutslag']]],
           ['Very rare',
            [['Respiratory', u'Dyspn\xe9'], ['Immune system', u'Anafylaktisk reaktion']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 11,
 u'_type': u'MSFU'}