{'_data': [['Very common',
            [['Metabolism', u'Viktuppg\xe5ng'],
             ['Nervous system', u'Somnolens'],
             ['Investigations', u'F\xf6rh\xf6jd Plasma-prolaktinniv\xe5']]],
           ['Common',
            [['Blood', u'Eosinofili'],
             ['Metabolism',
              u'F\xf6rh\xf6jd Kolesterolniv\xe5 F\xf6rh\xf6jd Glukosniv\xe5 F\xf6rh\xf6jd Triglyceridniv\xe5 Glykosuri \xd6kad aptit'],
             ['Nervous system', u'Yrsel Akatisi Parkinsonism Dyskinesi'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['GI',
              u'Milda, \xf6verg\xe5ende antikolinerga effekter, inklusive f\xf6rstoppning och muntorrhet'],
             ['Hepato',
              u'\xd6verg\xe5ende, asymtomatiska f\xf6rh\xf6jningar av levertrans-aminaser (ALAT, ASAT), s\xe4rskilt i b\xf6rjan av behandlingen (se avsnitt 4.4)'],
             ['Skin', u'Utslag'],
             ['General', u'Asteni Tr\xf6tthet \xd6dem']]],
           ['Uncommon',
            [['Blood', u'Leukopeni Neutropeni'],
             ['Cardiac', u'Bradykardi QTc-f\xf6rl\xe4ngning (se avsnitt 4.4)'],
             ['Skin', u'Fotosensitivitets-reaktioner Alopeci'],
             ['Renal', u'Urininkontinens'],
             ['Investigations',
              u'H\xf6g kreatinfosfokinas -niv\xe5 \xd6kad total bilirubinniv\xe5']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Allergisk reaktion'],
             ['Metabolism',
              u'Utveckling eller f\xf6rs\xe4mring av diabetes-sjukdomen, ibland associerat med ketoacidos eller koma, inklusive n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4) Hypotermi'],
             ['Nervous system',
              u'Kramper, d\xe4r det i de flesta fall finns kramper eller riskfaktorer f\xf6r kramper i anamnesen. Malignt neuroleptika syndrom (se avsnitt 4.4) Dystoni (inklusive okulogyration) Tardiv dyskinesi Uts\xe4ttnings-symtom'],
             ['Cardiac',
              u'Ventrikul\xe4r takykardi/ flimmer, pl\xf6tsligt d\xf6dsfall (se avsnitt 4.4)'],
             ['Vascular', u'Tromboemboli (inklusive lungemboli och djup ventrombos)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (inklusive hepatocellul\xe4r, kolestatisk eller blandad leverskada)'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Renal', u'Urintr\xe4ngningar'],
             ['Pregnancy', u'Neonatalt uts\xe4ttnings-syndrom (se avsnitt 4.6)'],
             ['Reproductive system', u'Priapism'],
             ['Investigations', u'\xd6kat alkaliskt fosfatas']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 11],
 u'_rank': 29,
 u'_type': u'MSFU'}