{'_data': [['Very common',
            [['Metabolism', u'Viktuppg\xe5ng'],
             ['Nervous system', u'Somnolens'],
             ['Investigations',
              u'F\xf6rh\xf6jd plasmaprolaktinniv\xe5 var mycket vanliga. vid abrupt uts\xe4ttande av olanzapin. med olanzapin (upp till 12 m\xe5nader) Pediatrisk population data fr\xe5n studier p\xe5 vuxna. vanlig   och <.'],
             ['Metabolism', u'Mycket vanlig: vikt\xf6kning vanlig'],
             ['Nervous system', u'mycket vanlig'],
             ['GI', u'vanlig  : muntorrhet.'],
             ['Hepato', u'mycket vanlig 4.4).'],
             ['Investigations',
              u'mycket vanlig plas ma p r ol aktinniv\xe5 av kroppsvikten fr\xe5n studiens b\xf6rjan till h\xf6ga (>1,467 mmol/l).']]],
           ['Common',
            [['Blood', u'Eosinofili'],
             ['Metabolism',
              u'F\xf6h\xf6jd Kolesterolniv\xe5 F\xf6rh\xf6jd glukosniv\xe5 F\xf6rh\xf6jd Triglyceridniv\xe5 Glykosuri \xd6kad aptit'],
             ['Nervous system', u'Yrsel Akatisi Parkinsonism Dyskinesi'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['GI',
              u'Milda, \xf6verg\xe5ende antikolinerga effekter, inklusive f\xf6rstoppning och muntorrhet'],
             ['Hepato',
              u'\xd6verg\xe5ende, asymtomatiska f\xf6rh\xf6jningar av levertransaminaser (ALAT, ASAT), s\xe4rskilt i b\xf6rjan av behandlingen (se avsnitt 4.4)'],
             ['Skin', u'Utslag'],
             ['Reproductive system',
              u'Erektil dysfunktion hos m\xe4n Minskad libido hos b\xe5da k\xf6nen Asteni Tr\xf6tthet \xd6dem'],
             ['Investigations', u'vid profylax av \xe5terfall i bipol\xe4r sjukdom, gav en '],
             ['Metabolism',
              u', f\xf6rh\xf6jd triglyceridniv\xe5 : f\xf6rh\xf6jt kolesterolv\xe4rde'],
             ['Nervous system',
              u': sedering  (inklusive  hyperso m ni,  letargi,  somnol e n s).'],
             ['Hepato',
              u': f\xf6rh\xf6jda niv\xe5er av levertra n s a mi n a s e r (ALAT/ASAT, se avsnitt'],
             ['Investigations',
              u': minska t totalbilirubin, \xf6kat GGT, f\xf6rh\xf6jd b\xf6rjan. ']]],
           ['Uncommon',
            [['Blood', u'Leukopeni Neutropeni'],
             ['Cardiac', u'Bradykardi QTc-f\xf6rl\xe4ngning (se avsnitt 4.4)'],
             ['Vascular',
              u'Tromboemboli (inklusive lungemboli och djup ventrombos) (se avsnitt 4.4)'],
             ['Skin', u'Fotosensitivitets-reaktioner Alopeci'],
             ['Renal', u'Urininkontinens Urinretention'],
             ['Reproductive system',
              u'Amenorr\xe9 Br\xf6stf\xf6rstoring Galaktorr\xe9 hos kvinnor Gynekomasti/br\xf6stf\xf6rstoring hos m\xe4n'],
             ['Investigations',
              u'H\xf6g kreatinfosfokinasniv\xe5 \xd6kad total bilirubinniv\xe5'],
             ['Metabolism', u', \xf6kad aptit']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Allergisk reaktion'],
             ['Metabolism',
              u'Utveckling eller f\xf6rs\xe4mring av diabetessjukdomen, ibland associerat med ketoacidos eller koma, inklusive n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4) Hypotermi'],
             ['Nervous system',
              u'Kramper, d\xe4r det i de flesta fall finns kramper eller riskfaktorer f\xf6r kramper i anamnesen. Malignt neuroleptikasyndrom (se avsnitt 4.4) Dystoni (inklusive okulogyration Tardiv dyskinesi Uts\xe4ttningssymtom'],
             ['Cardiac',
              u'Ventrikul\xe4r takykardi/flimmer, pl\xf6tsligt d\xf6dsfall (se avsnitt 4.4)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (inklusive hepatocellul\xe4r, kolestatisk eller blandad leverskada)'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Renal', u'Urintr\xe4ngningar'],
             ['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom (se avsnitt 4.6)'],
             ['Reproductive system', u'Priapism'],
             ['Investigations', u'\xd6kat alkaliskt fosfatas >7% \xf6kning i']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 41,
 u'_type': u'MSFU'}