{'_data': [['Common',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['GI', u'Diarr\xe9'],
             ['Renal', u'Azotemi'],
             ['Skin', u''],
             ['Skin', u'Sm\xe4rta vid infusionsst\xe4llet'],
             ['Investigations', u'\xd6kning av leverenzym'],
             ['Investigations', u''],
             ['Investigations', u'\xd6kning av gammaglutamyltransferas'],
             ['Investigations', u'']]],
           ['Unknown',
            [['Nervous system', u'Tremor'],
             ['GI', u''],
             ['GI', u'Buksm\xe4rtor  Kr\xe4kningar'],
             ['GI', u''],
             ['Hepato', u'Kolestatisk hepatit'],
             ['Hepato', u'Kolestas'],
             ['Hepato', u'Gulsot'],
             ['Skin', u'Erytem'],
             ['Skin', u'Hyperhidros'],
             ['Skin', u'Ryggsm\xe4rtor'],
             ['Skin', u'Br\xf6stsm\xe4rtor'],
             ['Skin', u'Sm\xe4rtor i extremiteter'],
             ['Skin', u'Muskelspasmer'],
             ['Skin', u''],
             ['Skin', u'Svullnad vid infusionsst\xe4llet  Vesiklar vid infusionsst\xe4llet'],
             ['Skin', u''],
             ['Skin', u''],
             ['Investigations', u'\xd6kning av bilirubin i blodet'],
             ['Investigations', u'\xd6kning av triglycerider i blodet'],
             ['Investigations',
              u'\xd6kning av alkalinfosfatas i blodet  \xd6kning av blodglukos Hyperglukemi a: Frekvensen anges som mycket vanliga (, vanliga , mindre vanliga']]]],
 '_pages': [7, 9],
 u'_rank': 21,
 u'_type': u'TSFU'}