{'_data': [['Common',
            [['Immune system', u'Antikroppsbildning'],
             ['Nervous system', u'Hos vuxna parestesi'],
             ['Skin', u'Hos barn \xf6verg\xe5ende lokala hudreaktioner'],
             ['Musculoskeletal', u'Hos vuxna stelhet i extremiteter, artralgi, myalgi'],
             ['General', u'Hos vuxna perifert \xf6dem']]],
           ['Uncommon',
            [['Nervous system', u'Hos vuxna karpaltunnelsyndrom. Hos barn parestesi'],
             ['Musculoskeletal', u'Hos barn stelhet i extremiteter, artralgi, myalgi'],
             ['General',
              u'Hos barn perifert \xf6dem Det har rapporterats att somatropin reducerar kortisolniv\xe5erna i serum, troligen genom att p\xe5verka b\xe4rarproteiner eller genom \xf6kat leverclearance. Den kliniska relevansen av dessa fynd kan vara begr\xe4nsad. Kortikosteroidterapi b\xf6r dock optimeras innan behandling med Omnitrope p\xe5b\xf6rjas.']]],
           ['Rare',
            [['Endocrine', u'Diabetes mellitus typ II'],
             ['Nervous system', u'Benign intrakraniell hypertension']]],
           ['Very rare',
            [['Neoplasms', u'Leukemi*'],
             ['General',
              u'fall av leukemi har rapporterats hos barn med tillv\xe4xthormonbrist som behandlats med Omnitrope, men incidensen f\xf6refaller vara likartad den hos barn utan tillv\xe4xthormonbrist, se avsnitt 4.4.']]]],
 '_pages': [6, 7],
 u'_rank': 12,
 u'_type': u'LSFU'}