{'_data': [['Very common',
            [['Renal', u' Cystit, dysuri, pollakisuri,  -hematuri  '],
             ['General',
              u'och/eller symtom  Influensaliknande symtom,  vid administreringsst\xe4llet  pyrexi, allm\xe4n  -sjukdomsk\xe4nsla, tr\xf6tthet ']]],
           ['Common',
            [['Infections', u' Urinv\xe4gsinfektion  '],
             ['Blood', u' Anemi  '],
<<<<<<< HEAD
             ['Respiratory', u'br\xf6stkorg och  Pneumonit  mediastinum -'],
=======
             ['Respiratory', u' br\xf6stkorg och  Pneumonit  mediastinum -'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI',
              u' Buksm\xe4rta, illam\xe5ende,  -kr\xe4kningar, diarr\xe9 Muskuloskeletala systemet och  Artralgi, artrit, myalgi  bindv\xe4v -'],
             ['Renal', u' Urininkontinens,  -miktionstr\xe4ngningar, onormala -urinv\xe4rden '],
             ['General', u'och/eller symtom  Stelhet  vid administreringsst\xe4llet -']]],
           ['Uncommon',
            [['Infections', u' Tuberkulosinfektion  '],
             ['Blood', u' Pancytopeni, trombocytopeni  '],
             ['Hepato', u' Hepatit  '],
             ['Skin', u' Rodnad, hudutslag och  -exantem '],
             ['Renal', u' Bl\xe5skonstriktion, pyuri,  -urinretention, -ureterobstruktion '],
             ['Investigations', u' \xd6kning av leverenzymer  ']]],
           ['Rare',
<<<<<<< HEAD
            [['Respiratory', u'br\xf6stkorg och  Hosta  mediastinum  -'],
=======
            [['Respiratory', u' br\xf6stkorg och  Hosta  mediastinum  -'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Reproductive system', u'Epididymit -']]],
           ['Very rare',
            [['Infections', u' Faryngit, orkit, Reiters  -sjukdom, Lupus vulgaris  '],
             ['Blood', u' Lymfadenopati  '],
             ['Metabolism', u' Anorexi  '],
             ['Psychiatric', u' Oklarhetstillst\xe5nd  '],
             ['Nervous system',
              u' Yrsel, dysestesi\xb9,  -hyperestesi\xb9, parestesi\xb9, -somnolens, huvudv\xe4rk, -hypertoni, neuralgi\xb9 '],
             ['Eye', u' Konjunktivit  '],
             ['Ear', u' Vertigo\xb9  '],
             ['Vascular', u' Hypotension  '],
<<<<<<< HEAD
             ['Respiratory', u'br\xf6stkorg och  Bronkit, dyspn\xe9, rinit  mediastinum -'],
=======
             ['Respiratory', u' br\xf6stkorg och  Bronkit, dyspn\xe9, rinit  mediastinum -'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u' Dyspepsi\xb9, flatulens\xb9  '],
             ['Skin',
              u' Alopeci, hyperhidros  Muskuloskeletala systemet och  Ryggont  bindv\xe4v -'],
             ['Renal', u' Akut njursvikt  '],
             ['Reproductive system', u'Balanopostit, prostatit, --vulvovaginalt obehag\xb9 '],
             ['General',
              u'och/eller symtom  Br\xf6stsm\xe4rta, perifert \xf6dem,  vid administreringsst\xe4llet  granulom\xb2  '],
             ['Investigations', u' \xd6kning av prostataspecifikt  -antigen, vikt\xf6kning ']]]],
 '_pages': [3, 5],
 u'_rank': 31,
 u'_type': u'DFSU'}