{'_data': [['Very common', [['Nervous system', u'huvudv\xe4rk']]],
           ['Common',
            [['Vascular', u'v\xe4rmek\xe4nsla och hudrodnad.'],
             ['GI', u'f\xf6rstoppning.'],
             ['General',
              u'lokala reaktioner p\xe5 injektionsst\xe4llet vid intraven\xf6s administrering. Har observerats utan definitiva tecken p\xe5 best\xe5ende kliniska f\xf6ljdtillst\xe5nd. I de flesta fall d\xe4r det rapporterades blindhet, gick det \xf6ver p\xe5 20 minuter. De flesta av patienterna hade f\xe5tt cytostatika, inklusive cisplatin. N\xe5gra av fallen av \xf6verg\xe5ende blindhet rapporterades ha kortikalt ursprung. Detta har huvudsakligen observerats hos patienter som f\xe5tt kemoterapibehandling med cisplatin.']]],
           ['Uncommon',
            [['Nervous system',
              u'krampanfall, r\xf6relsest\xf6rningar (inklusive extrapyramidala reaktioner s\xe5som dystoni, okulogyr kris och dyskinesi) 1'],
             ['Cardiac',
              u'br\xf6stsm\xe4rta (med eller utan ST- s\xe4nkning), hj\xe4rtarytmier, bradykardi.'],
             ['Vascular', u'hypotension.'],
             ['Respiratory', u'hicka.'],
             ['Hepato', u'asymtomatiska f\xf6rh\xf6jda leverfunktionsv\xe4rden']]],
           ['Rare',
            [['Immune system',
              u'omedelbara \xf6verk\xe4nslighetsreaktioner, ibland allvarliga inkluderande anafylaxi. Anafylaxi kan vara fatalt. \xd6verk\xe4nslighetsreaktioner har \xe4ven observerats hos patienter som reagerat p\xe5 andra selektiva 5-HT -antagonister.'],
             ['Nervous system', u'yrsel vid snabb intraven\xf6s administrering.'],
             ['Eye',
              u'\xf6verg\xe5ende visuella f\xf6r\xe4ndringar (t ex dimsyn) huvudsakligen vid intraven\xf6s administrering.']]],
           ['Very rare',
            [['Eye',
              u'\xf6verg\xe5ende blindhet, huvudsakligen vid intraven\xf6s administrering']]]],
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'LSFU'}