{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk.']]],
           ['Common',
            [['Vascular', u'Upplevelse av flush ellerv\xe4rmek\xe4nsla.'],
             ['GI', u'F\xf6rstoppning,']]],
           ['Uncommon',
            [['Nervous system',
              u'Krampanfall R\xf6relsest\xf6rningar (inklusive extrapyramidala reaktioner s\xe5som dystoniska reaktioneroculogyr kris och dyskinesi)'],
             ['Cardiac',
              u'Arytmier, br\xf6stsm\xe4rtor med eller utan ST-s\xe4nkning, bradykardi.'],
             ['Vascular', u'Hypotoni. Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Hicka.'],
             ['Hepato',
              u'Asymtomatiska f\xf6rh\xf6jda leverfunktionsv\xe4rden observerades utan definitiva tecken p\xe5 ih\xe5llande kliniska f\xf6ljdtillst\xe5nd. De flesta blindhetsfall som rapporterats var \xf6ver inom 20 minuter. De flesta patienterna hade genomg\xe5tt kemoterapi, som inkluderade cisplatin. N\xe5gra fall av \xf6verg\xe5ende blindhet rapporterades som kortikal ursprung. Dessa h\xe4ndelser var vanligt hos patienter som fick kemoterapi med cisplatin.']]],
           ['Rare',
            [['Immune system',
              u'Omedelbara \xf6verk\xe4nslighetsreaktioner, ibland allvarliga inkluderande anafylaxi.'],
             ['Nervous system', u'Yrsel vid snabb intraven\xf6s administrering.'],
             ['Eye',
              u'\xd6verg\xe5ende synst\xf6rningar (t.ex. dimsyn) framf\xf6r allt vid snabb intraven\xf6s administrering.'],
             ['Cardiac', u'S\xe4llsynta OTc-f\xf6rl\xe4ngning (inklusive Torsade de Pointes)']]],
           ['Very rare',
            [['Eye',
              u'\xd6verg\xe5ende blindhet huvudsakligen vid intraven\xf6s administrering .']]]],
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'LSFU'}