{'_data': [['Very common', [['Nervous system', u'Huvudv\xe4rk.']]],
           ['Common',
            [['Vascular', u'Upplevelse av rodnad eller vallningar.'],
             ['GI',
              u'F\xf6rstoppning, br\xe4nnande k\xe4nsla lokalt till f\xf6ljd av inf\xf6rande av suppositorium.']]],
           ['Uncommon',
            [['Nervous system',
              u'Kramper (har observerats utan definitiva bel\xe4gg f\xf6r best\xe5ende kliniska f\xf6ljdtillst\xe5nd). R\xf6relsest\xf6rningar (inklusive extrapyramidala reaktioner, t.ex. dystoniska reaktioner, okulogyr kris och dyskinesi).'],
             ['Cardiac',
              u'Arytmier, br\xf6stsm\xe4rtor med eller utan ST-s\xe4nkning, bradykardi.'],
             ['Vascular', u'Hypotoni. Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Hicka.'],
             ['Hepato',
              u'Asymtomatiska h\xf6jningar i leverfunktionstester (dessa h\xe4ndelser observerades ofta hos patienter som fick kemoterapi med cisplatin).']]],
           ['Rare',
            [['Immune system',
              u'Omedelbara \xf6verk\xe4nslighetsreaktioner, ibland allvarliga, inklusive anafylaxi.'],
             ['Nervous system', u'S\xe4llsynta Yrsel vid snabb intraven\xf6s administrering.'],
             ['Eye',
              u'\xd6verg\xe5ende synst\xf6rningar (t.ex. dimsyn) framf\xf6r allt vid snabb intraven\xf6s administrering.']]],
           ['Very rare',
            [['Eye',
              u'\xd6verg\xe5ende blindhet framf\xf6r allt vid intraven\xf6s administrering. Majoriteten av dessa fall av blindhet rapporterades vara \xf6ver inom 20 minuter. De flesta patienter hade f\xe5tt kemoterapeutika som inkluderade cisplatin. Vissa fall av \xf6verg\xe5ende blindhet rapporterades ha kortikalt ursprung.']]]],
 '_pages': [4, 5],
 u'_rank': 12,
 u'_type': u'LSFU'}