{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk*'],
             ['General', u'Erytem*, sm\xe4rta* Allm\xe4n sjukdoms-k\xe4nsla*, tr\xf6tthet*']]],
           ['Common',
            [['Musculoskeletal', u'Myalgi*, artralgi*'],
             ['General',
              u'Svullnad*, ekkymos*, induration* Feber*, frossa* Magtarm-rubbningar som buksm\xe4rta, diarr\xe9 eller matsm\xe4ltnings -besv\xe4r*'],
             ['Skin', u'Svettning*']]],
           ['Uncommon',
            [['Skin',
              u'Generaliserade hudreaktioner, inkl. pruritus, urtikaria eller ospecifika utslag']]],
           ['Rare', [['General', u'Lokal lymfadenopati Feber \xf6ver 39,0\xb0C']]],
           ['Very rare',
            [['Nervous system',
              u'Neurologiska sjukdomar, som Guillain-Barr\xe9s syndrom, encefalomyelit och neurit'],
             ['Vascular',
              u'Vaskulit, m\xf6jligen f\xf6renad med \xf6verg\xe5ende njurp\xe5verkan'],
             ['Immune system', u'Allergiska reaktioner, som i mycket lett till chock'],
             ['Blood', u'**Trombocyto peni']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 6],
 u'_rank': 11,
 u'_type': u'MSFU'}