{'_data': [['Very common', [['General', u'blodvallningar']]],
           ['Common', [['General', u'sm\xe4rta']]],
           ['Uncommon',
            [['GI', u'illam\xe5ende, kr\xe4kningar 1 %)'], ['Skin', u'urtikaria 1 %)']]],
           ['Rare',
            [['Nervous system', u'yrsel, parestesi, darrningar'],
             ['Cardiac', u'takykardi'],
             ['Vascular', u'hypotension'],
             ['Respiratory', u'hosta, dyspn\xe9, rinit'],
             ['GI', u'smakf\xf6r\xe4ndringar, muntorrhet'],
             ['Skin', u'erytem, kl\xe5da, utslag'],
             ['Renal', u'sm\xe4rtsam/sv\xe5r urinering'],
             ['General', u'svalgsvullnad, frossbrytningar, huvudv\xe4rk']]],
           ['Very rare',
            [['Psychiatric', u'amnesi, \xe5ngest, s\xf6mnighet. (< 0,01 %)'],
             ['Nervous system',
              u'agitation, f\xf6rvirrning, konvulsioner, desorientering, dyskinesi, (< 0,01 %) dysfasi, hypestesi, muskelkramper, f\xf6rlamning, talrubbningar, stupor'],
             ['Eye',
              u'konjunktivit, \xf6verg\xe5ende kortikal synf\xf6rlust, synrubbningar (< 0,01 %)'],
             ['Ear', u'tinnitus (< 0,01 %)'],
             ['Cardiac',
              u'hj\xe4rtklappningar, arytmi, f\xf6rmaksflimmer, bradykardi, (< 0,01 %) hj\xe4rtstillest\xe5nd, cirkulationssvikt, EKG-f\xf6r\xe4ndringar, extrasystole, hj\xe4rtblock, kammarflimmer'],
             ['Vascular',
              u'cerebrovaskul\xe4ra sjukdomar, cyanos, hypertension, synkope, (< 0,01 %) tromboflebit, vasodilatation, vasospasm'],
             ['Respiratory',
              u'apn\xe9, bronkospasm, hypoxi, larynx\xf6dem, faryngit, lung\xf6dem, (< 0,01 %) stridor'],
             ['GI',
              u'sialadenit, hypersalivation, tungsvullnad, dysfagi, diarr\xe9 (< 0,01 %)'],
             ['Skin', u'angio\xf6dem, toxisk epidermal nekrolys (< 0,01 %)'],
             ['Renal',
              u'inkontinens, akut njursvikt, f\xf6rh\xf6jda ureav\xe4rden, onormal (< 0,01 %) njurfunktion, nedsatt kreatininclearance, hematuri, oliguri'],
             ['General',
              u'anafylaktisk chock, ansiktssvullnad, periorbital svullnad, feber, (< 0,01 %) \xf6dem, blekhet, br\xf6stsm\xe4rta, buksm\xe4rta, asteni/tr\xf6tthet, onormal gr\xe5t, reaktioner p\xe5 injektionsst\xe4llet, \xf6kad svettning']]],
           ['Unknown',
            [['Local',
              u'inflammation. g. Extravasation kan orsaka allvarliga v\xe4vnadsreaktioner inklusive bl\xe5sbildning och exfoliering av huden, vilkas omfattning beror p\xe5 m\xe4ngden och styrkan av kontrastmedlet i v\xe4vnaderna. Ikliniska pr\xf6vningar observerades lindrigt obehag, inklusive v\xe4rme- och k\xf6ldf\xf6rnimmelser, sm\xe4rta under injektionen, och/eller \xf6verg\xe5ende smakf\xf6r\xe4ndringar, hos 10\u201350 % av patienterna. Under en omfattande pr\xf6vning efter preparatet godk\xe4nts f\xf6r f\xf6rs\xe4ljning f\xf6rekom det andra biverkningar hos 1,1 % av patienterna. De vanligaste biverkningarna var illam\xe5ende (0,4 %), hudreaktioner s\xe5som urtikaria eller erytem (0,3 %), och kr\xe4kningar (0,1 %). \xd6vriga biverkningar f\xf6rekom hos mindre \xe4n 0,1 % av patienterna.']]]],
 '_pages': [5, 7],
 u'_rank': 24,
 u'_type': u'LSFU'}