{'_data': [['Uncommon',
            [['Renal', u'Urinretention'],
             ['Skin', u'Kl\xe5da'],
             ['Endocrine', u'\xd6kad ADH fris\xe4ttning'],
             ['Vascular', u'Ortostatisk hypotension'],
             ['General', u'Sedering   vid administreringsst\xe4llet'],
             ['Psychiatric', u'Omt\xf6ckning, dysfori']]],
           ['Very rare',
            [['Nervous system', u'Andningsdepression'],
             ['Eye', u'Mios'],
             ['Respiratory', u'Bronkokonstriktion   mediastinum'],
             ['GI', u'Obstipation, illam\xe5ende, kr\xe4kningar']]]],
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'LFSUR'}