{'_data': [['Common',
            [['Blood', u'Leukopeni'],
             ['Ear', u'Konjunktivit'],
             ['Vascular', u'Hypertoni, flush (ansiktsrodnad),  blodtrycks\xf6kning'],
             ['GI',
              u'Buksm\xe4rtor, diarr\xe9, illam\xe5ende, dyspepsi,  muns\xe5r, aft\xf6s stomatit, kr\xe4kningar'],
             ['Hepato', u'Avvikande leverfunktionstest (inklusive  transaminasstegring)'],
             ['Skin', u'Utslag (inklusive dermatit), alopeci, kl\xe5da'],
             ['Musculoskeletal', u'Sm\xe4rta i extremitet'],
             ['General', u'Tr\xf6tthet, asteni, reaktioner vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'Depression, \xe5ngest, s\xf6mnst\xf6rning (inklusive  insomnia)'],
             ['Nervous system', u'Migr\xe4n'],
             ['Ear', u'Torra \xf6gon, minskad synsk\xe4rpa'],
             ['Ear', u'Yrsel'],
             ['Cardiac', u'Hj\xe4rtklappning, takykardi, bradykardi'],
             ['Vascular', u'Hypotoni, blodvallningar, vaskulit,  blodtryckss\xe4nkning'],
             ['Respiratory', u'Bronkospasm, pipande andning, dyspn\xe9'],
             ['Skin',
              u'\xd6kad ben\xe4genhet f\xf6r bl\xe5m\xe4rken, torr hud,  urtikaria, psoriasis, erytem, hyperhidros'],
             ['Musculoskeletal', u'Artralgi'],
             ['Reproductive system', u'Amenorr\xe9, menorragi'],
             ['General', u'Influensaliknande sjukdom, vikt\xf6kning']]],
           ['Rare', [['Respiratory', u'Tr\xe5nghetsk\xe4nsla i halsen']]]],
 '_pages': [5, 9],
 u'_rank': 21,
 u'_type': u'TSFU'}