{'_data': [['Very common',
            [['Metabolism', u'\xd6verg\xe5ende h\xf6jning av ammoniak i blodet.'],
             ['Psychiatric', u'Hum\xf6r- och emotionella rubbningar.'],
             ['Hepato', u'F\xf6r\xe4ndringar i leverv\xe4rden.']]],
           ['Common',
            [['Blood',
              u'Lindrig trombocytopeni, nedsatt trombocytadhesivitet, f\xf6rl\xe4ngd bl\xf6dningstid.'],
             ['Metabolism',
              u'Onormalt \xf6kad vikt eller minskad vikt, \xf6kad aptit, anorexi.'],
             ['Nervous system', u'Tremor, yrsel, dysartri.'],
             ['Eye', u'Dubbelseende.'],
             ['GI', u'Sm\xe4rta, sugningar, illam\xe5ende, kr\xe4kningar, diarr\xe9.'],
             ['Skin',
              u'\xd6verg\xe5ende h\xe5ravfall, f\xf6r\xe4ndringar i h\xe5rkvalitet eller h\xe5rf\xe4rg.']]],
           ['Uncommon',
            [['Psychiatric', u'Beteendeavvikelser, insomningssv\xe5righeter.'],
             ['Nervous system', u'Nystagmus.'],
             ['Hepato',
              u'Sv\xe5r leverp\xe5verkan (ibland med letal levernekros) hos barn under 3 \xe5r vilka st\xe5tt p\xe5 kombinationsbehandling.'],
             ['Renal', u'Enures, \xf6kad miktionsfrekvens.'],
             ['Reproductive system', u'Sekund\xe4r amenorr\xe9, oregelbundna menstruationer.'],
             ['General', u'Tr\xf6tthet.']]],
           ['Rare',
            [['Blood',
              u'Sv\xe5r trombocytopeni, sv\xe5r leukopeni, bl\xf6dningar, anemi, pancytopeni, eosinofili, s\xe4nkt fibrinogenhalt.'],
             ['Immune system', u'Lupus erythematosus.'],
             ['Metabolism', u'\xd6dem.'],
             ['Psychiatric', u'Psykos, konfusion.'],
             ['Nervous system',
              u'Huvudv\xe4rk, parestesi, ataxi, encefalopati* , stupor, extrapyramidala symtom (t.ex. parkinsonism).'],
             ['GI', u'Pankreatit, obstipation.'],
             ['Hepato', u'Sv\xe5r leverp\xe5verkan hos barn \xf6ver 3 \xe5r.'],
             ['Skin', u'Hudutslag.'],
             ['General', u'Hypotermi.']]],
           ['Very rare',
            [['Metabolism',
              u'Uttalad hyperammonemi associerad med encefalopati, f\xf6rvirring, illam\xe5ende, kr\xe4kning, ataxi.'],
             ['Nervous system', u'Demens associerad med hj\xe4rnatrofi.'],
             ['Skin', u'Stevens-Johnson syndrom, Lyells syndrom.'],
             ['Renal', u'Fanconis syndrom.'],
             ['Reproductive system', u'Polycystiska ovarier.']]],
           ['Unknown',
            [['Immune system',
              u'Allergiska reaktioner har rapporterats (se \xe4ven Hud och subkutan v\xe4vnad).'],
             ['Endocrine', u'\xd6kad niv\xe5 av testosteron (hyperandrogenism)'],
             ['GI',
              u'ofta dosberoende och kan undvikas med dosreduktion. Detsamma g\xe4ller h\xe5ravfall och \xe4ndrad h\xe5rf\xe4rg. Tr\xf6tthet \xe4r vanligt f\xf6rekommande vid kombination med andra antiepileptika och uppkommer ofta till f\xf6ljd av en interaktion.']]]],
 '_pages': [8, 10],
 u'_rank': 32,
 u'_type': u'LSFU'}