{'_data': [['Common',
            [['Nervous system',
              u'Myrkrypningar, yrsel, d\xe5sighet, k\xe4nselst\xf6rningar som parestesi och hypoestesi.'],
             ['Vascular',
              u'\xd6verg\xe5ende blodtrycksh\xf6jning strax efter behandling. Blodvallning.'],
             ['Respiratory', u'Dyspn\xe9.'],
             ['GI',
              u'Illam\xe5ende och kr\xe4kningar har f\xf6rekommit hos en del patienter men det \xe4r oklart om detta \xe4r relaterat till sumatriptan eller det underliggande tillst\xe5ndet.'],
             ['Musculoskeletal',
              u'Tyngdk\xe4nsla (vanligtvis \xf6verg\xe5ende men kan vara intensiv och p\xe5verka olika delar av kroppen inklusive br\xf6stkorgen och svalget). Myalgi.'],
             ['General',
              u'Sm\xe4rta, v\xe4rme- eller k\xf6ldk\xe4nsla, tryck- eller \xe5tstramningsk\xe4nsla (dessa \xe4r vanligtvis \xf6verg\xe5ende men kan vara intensiva och p\xe5verka olika delar av kroppen inklusive br\xf6stkorgen och svalget). K\xe4nsla av svaghet, tr\xf6tthet (b\xe5da dessa biverkningar \xe4r vanligtvis milda till m\xe5ttliga i intensitet och \xf6verg\xe5ende).']]],
           ['Very rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner som varierar fr\xe5n kutan \xf6verk\xe4nslighetsreaktion (s\xe5som urtikaria) till s\xe4llsynta fall av anafylaxi.'],
             ['Nervous system',
              u'Krampanfall, \xe4ven om en del av dessa har f\xf6rekommit hos patienter som antingen har anamnes p\xe5 kramper eller samverkande sjukdomstillst\xe5nd som predisponerar f\xf6r krampanfall. Det finns \xe4ven rapporter om patienter d\xe4r predisponerande faktorer inte f\xf6religger. Nystagmus, skotom, tremor, dystoni.'],
             ['Eye',
              u'Flimmer, diplopi, nedsatt syn. Synbortfall inklusive rapporter om permanenta syndefekter. Emellertid kan synst\xf6rningar \xe4ven uppkomma under sj\xe4lva migr\xe4nanfallet.'],
             ['Cardiac',
              u'Bradykardi, takykardi, palpitationer, hj\xe4rtarytmier, \xf6verg\xe5ende ischemiska EKG-f\xf6r\xe4ndringar, spasm i hj\xe4rtats koronark\xe4rl, angina, hj\xe4rtinfarkt (se avsnitt 4.3 och 4.4).'],
             ['Vascular', u'Hypotension, Raynauds fenomen.'],
<<<<<<< HEAD
             ['GI', u'Ischemisk kolit.'],
             ['Musculoskeletal', u'Nackstelhet.'],
             ['Investigations',
              u'Mindre f\xf6r\xe4ndringar i leverfunktionstester har i enstaka fall observerats.']]],
           ['Unknown',
            [['Psychiatric', u'Oro'],
             ['GI', u'Diarr\xe9.'],
             ['Skin', u'Hyperhidros.'],
             ['Musculoskeletal', u'Artralgi.']]]],
 '_pages': [4, 5],
 u'_rank': 18,
=======
             ['GI', u'Ischemisk kolit. Diarr\xe9.'],
             ['Musculoskeletal', u'Nackstelhet. Artralgi.'],
             ['Investigations',
              u'Mindre f\xf6r\xe4ndringar i leverfunktionstester har i enstaka fall observerats.']]],
           ['Unknown', [['Psychiatric', u'Oro'], ['Skin', u'Hyperhidros.']]]],
 '_pages': [4, 5],
 u'_rank': 16,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}