{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Respiratory', u'\xd6vre luftv\xe4gsinfektion'],
             ['GI',
              u'Buksm\xe4rtor/obehag Oljig flytning fr\xe5n rektum Gaser med tarmt\xf6mning Tr\xe4ngning vid tarmt\xf6mning Fettrik/oljig avf\xf6ring Gasbildning Flytande avf\xf6ring Oljig tarmt\xf6mning \xd6kad defekation'],
             ['Metabolism', u'Hypoglykemi*'],
             ['Infections',
              u'Influensa Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Common',
            [['Respiratory', u'Nedre luftv\xe4gsinfektion'],
             ['GI',
              u'Rektala sm\xe4rtor/obehag Mjuk avf\xf6ring Avf\xf6ringsinkontinens Utsp\xe4nd buk* Tandproblem Tandk\xf6ttsproblem'],
             ['Renal', u'Urinv\xe4gsinfektion'],
             ['Infections', u'Tr\xf6tthet'],
             ['Reproductive system', u'Oregelbundna menstruationsbl\xf6dningar'],
             ['Psychiatric',
              u'Oro * biverkning som endast intr\xe4ffade hos obesa patienter med typ 2-diabetes i storleksordningen > 2 % med en incidens av \u22651 % \xf6ver placebo. I en 4-\xe5rig klinisk pr\xf6vning var det allm\xe4nna biverkningsm\xf6nstret likv\xe4rdigt med det som rapporterats f\xf6r de 1- och 2-\xe5riga studierna. Den totala incidensen av mag-tarmrelaterade biverkningar minskade successivt \xe5r efter \xe5r under den fyra \xe5r l\xe5nga perioden. F\xf6ljande tabell \xe4r baserad p\xe5 spontana biverkningsrapporter efter marknadsintroduktion, och d\xe4rf\xf6r f\xf6rblir frekvensen ok\xe4nd: KLASSIFICERING AV ORGANSYSTEM BIVERKNING Unders\xf6kningar F\xf6rh\xf6jda levertransaminaser och alkaliskt fosfatas. Minskat protrombin, \xf6kad INR och obalanserad antikoagulantiabehandling som resulterat i varierande hemostatiska parametrar har rapporterats hos patienter som behandlats med antikoagulantia i samband med orlistatbehandling (se avsnitt 4.4 och 4.5) Mag-tarmkanalen Rektal bl\xf6dning (se avsnitt 4.4) Divertikulit Pankreatit Hud och subkutan v\xe4vnad Bull\xf6sa hudutslag Immunsystemet \xd6verk\xe4nslighet (t.ex. kl\xe5da, hudutslag, urtikaria, angio\xf6dem, bronkospasm och anafylaxi) Lever och gallv\xe4gar Kolelitiasis Hepatit som kan vara allvarlig Njurar och urinv\xe4gar Oxalatnefropati']]]],
 '_pages': [4, 5],
 u'_rank': 11,
 u'_type': u'LSFU'}