{'_data': [['Common',
            [['Vascular', u'\xd6dem'],
             ['Reproductive system',
              u'Mellanbl\xf6dning, amenorr\xe9, vaginal candidiasis, \xf6mhet i br\xf6stk\xf6rtel'],
             ['GI', u'Magkramp, uppk\xf6rdhet'],
             ['Skin', u'Akne'],
             ['Nervous system', u'Stark huvudv\xe4rk, irritabilitet, depression'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['Cardiac', u'hj\xe4rtinfarkt.'],
             ['GI', u'kolit.'],
             ['Nervous system', u'korea. '],
             ['Metabolism', u'minskad glukostolerans ']]],
           ['Uncommon',
            [['Reproductive system', u'Sm\xe4rta i br\xf6stk\xf6rtel'],
             ['GI', u'Illam\xe5ende, kr\xe4kning'],
             ['Skin', u'Alopeci, hirsutism, kloasma, utslag'],
             ['Nervous system',
              u'Migr\xe4n, f\xf6r\xe4ndringar i libido, hum\xf6rf\xf6r\xe4ndringar'],
             ['Metabolism',
              u'F\xf6r\xe4ndringar i kroppsvikt (\xf6kning eller minskning), aptitf\xf6r\xe4ndringar']]],
           ['Rare', [['Vascular', u'Ven\xf6s tromboembolism']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 9],
 u'_rank': 16,
 u'_type': u'MSFU'}