{'_data': [['Common',
            [['Nervous system',
              u'Huvudv\xe4rk 3,3% 2,7% St\xf6rningar i medvetandet 2,6% 2,1% Minnesf\xf6rlust 2,5% 2,0%'],
             ['Vascular', u'Ven\xf6s tromboembolism (VTE) 2,7% 1,9%'],
             ['GI',
              u'Illam\xe5ende 7,1% 4,6% Diarr\xe9 7,0% 5,0% L\xf6s avf\xf6ring 1,0% 0,2%'],
             ['Skin', u'Dermatit 2,3% 2,0% Eksem 1,8% 1,4%'],
             ['Investigations',
              u'F\xf6rh\xf6jt blodkreatinfosfokinas (CPK) 1,4% 0,6% Erfarenhet efter introduktion p\xe5 marknaden Muskuloskeletal fraktion > 3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet. I de flesta fall \xe5terg\xe5r dessa v\xe4rden spontant till det normala utan f\xf6r\xe4ndring av behandlingen. * I Asiatiska l\xe4nder rapporterad som s\xe4llsynta']]],
           ['Uncommon', [['Nervous system', u'Kramper 0,4% 0,1%']]],
           ['Rare', [['Skin', u'DRESS (se avsnitt 4.4)']]],
           ['Very rare',
            [['Skin',
              u'Allvarliga hudreaktioner (SCARs): Stevens-Johnson syndrom och toxisk epidermal nekrolys* (se avsnitt 4.4)']]],
           ['Unknown',
            [['Psychiatric', u'F\xf6rvirringstillst\xe5nd - S\xf6mnl\xf6shet -'],
             ['Nervous system', u'Parestesier Yrsel Vertigo'],
             ['Respiratory', u'Bronkial hyperreaktivitet -'],
             ['GI',
              u'Kr\xe4kningar Buksm\xe4rtor Irritation av munslemhinnan (stomatit och/eller muns\xe5r) Gastroesofagal reflux Dyspepsi F\xf6rstoppning Flatulens Muntorrhet'],
             ['Hepato',
              u'F\xf6rh\xf6jda serumtransaminaser (f\xf6renat med - \xf6verk\xe4nslighetsreaktioner i huden) Hepatit -'],
             ['Skin',
              u'\xd6verk\xe4nslighetsreaktioner i huden (hudutslag, kl\xe5da, urticaria, angio\xf6dem) 6 Procentandel patienter som upplevt Organsystemklassificering biverkningen Behandling Frekvenskategori Strontiumranelat Placebo Biverkning (n=3352) (n=3317) Alopeci -'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (muskelspasm, myalgi, bensm\xe4rta, artralgi samt sm\xe4rta i extremiteter) Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Blood',
              u'Benm\xe4rgssvikt - Eosinofili (f\xf6renat med \xf6verk\xe4nslighetsreaktioner i - huden) Lymfadenopati (f\xf6renat med \xf6verk\xe4nslighetsreaktioner i - huden)']]]],
 '_pages': [5, 7],
 u'_rank': 16,
 u'_type': u'LSFU'}