<<<<<<< HEAD
{'_data': [['Very rare',
=======
{'_data': [['Common',
            [['Eye',
              u'anafylaktiska reaktioner, d\xe4ribland bronkospasm, angio\xf6dem, hypotoni och anafylaktisk chock. ++ Mycket vanligt med feber, antingen p\xe5 grund av infektion (med eller utan febril neutropeni) eller m\xf6jligen orsakad av en immunologisk mekanism. +++ Extravasation kan leda till lokal sm\xe4rta och inflammation som kan vara sv\xe5r och leda till komplikationer, inklusive nekros, s\xe4rskilt n\xe4r oxaliplatin infunderas via en perifer ven (se avsnitt 4.4).']]],
           ['Very rare',
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
            [['Hepato',
              u'Leversinusoidalt obstruktionssyndrom, \xe4ven kallat veno-ocklusiv leversjukdom, eller patologiska manifestationer i samband med s\xe5dan leversjukdom, inklusive peliosis hepatis, nodul\xe4r regenerativ hyperplasi, perisinusoidal fibros. Kliniska manifestationer kan vara portal hypertoni och/eller f\xf6rh\xf6jda transaminaser.'],
             ['Renal',
              u'Akut tubulointerstitiell nefropati som leder till akut njursvikt. Hematologisk toxicitet Incidens per patient (%) per grad Oxaliplatin och 5-FU/FA Behandling av Adjuvant behandling 85 mg/m varannan metastaserande cancer vecka Alla Gr 3 Gr 4 Alla Gr 3 Gr 4 grader grader Anemi 82,2 3 <1 75,6 0,7 0,1 Neutropeni 71,4 28 14 78,9 28,8 12,3 Trombocytopeni 71,6 4 <1 77,4 1,5 0,2 Febril neutropeni 5,0 3,6 1,4 0,7 0,7 0,0 Neutropen sepsis 1,1 0,7 0,4 1,1 0,6 0,4']]],
           ['Unknown',
            [['Eye',
<<<<<<< HEAD
              u'- Synf\xe4lts-st\xf6rninga r Optisk neurit \xd6verg\xe5ende synf\xf6rlust, reversibel efter avslutad behandling \xd6ron och - Ototoxicitet - D\xf6vhet balansorgan Blodk\xe4rl - Epistaxis - Bl\xf6dning Flush Djup ven-trombos Lungemboli Rektalbl\xf6dning Andnings-v\xe4g - Dyspn\xe9 - Hicka - Interstitiell ar, br\xf6stkorg - Hosta - Br\xf6stsm\xe4rta lungsjukdom och - Lungfibros** mediastinum Magtarm-kan - Illam\xe5ende - Dyspepsi - Ileus - Kolit inkl. alen* - Diarr\xe9 - Gastroesofagal - Clostridium Kr\xe4kning reflux Tarm-obstruktion difficile-orsakad Stomatit/ diarr\xe9'],
=======
              u'- Synf\xe4lts- st\xf6rningar Optisk neurit \xd6verg\xe5ende synf\xf6rlust, reversibel efter avslutad behandling \xd6ron och - Ototoxicitet - D\xf6vhet balansorgan Blodk\xe4rl - Epistaxis - Bl\xf6dning Flush Djup ven trombos Lungemboli Rektalbl\xf6dning Andnings- - Dyspn\xe9 - Hicka - Interstitiell v\xe4gar, - Hosta - Br\xf6stsm\xe4rta lungsjukdom br\xf6stkorg och - Lungfibros** mediastinum Magtarm- - Illam\xe5ende - Dyspepsi - Ileus - Kolit inkl. kanalen* - Diarr\xe9 - Gastroesofagal - Tarm- Clostridium Kr\xe4kning reflux obstruktion difficile-orsakad Stomatit/ diarr\xe9 mukosit Buksm\xe4rtor F\xf6rstoppning * Se detaljerat avsnitt nedan. ** Se avsnitt 4.4. + Vanliga allergiska reaktioner som hudutslag (s\xe4rskilt urtikaria), konjunktivit, rinit.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI',
              u'Incidens per patient (%) per grad Oxaliplatin och 5-FU/FA Behandling av Adjuvant behandling 85 mg/m varannan metastaserande cancer vecka Alla Gr 3 Gr 4 Alla Gr 3 Gr 4 grader grader Illam\xe5ende 69,9 8 <1 73,7 4,8 0,3 Diarr\xe9 60,8 9 2 56,3 8,3 2,5 Kr\xe4kning 49,0 6 1 47,2 5,3 0,5 Mukosit/stomatit 39,9 4 <1 42,1 2,8 0,1 Profylax och/eller behandling med potenta antiemetiska medel \xe4r indicerat. Sv\xe5r diarr\xe9/kr\xe4kning kan orsaka uttorkning, paralytisk ileus, tarmobstruktion, hypokalemi, metabol acidos och njurfunktionsneds\xe4ttning, s\xe4rskilt n\xe4r oxaliplatin kombineras med 5-fluorouracil (se avsnitt 4.4).'],
             ['Nervous system',
              u'Oxaliplatins dosbegr\xe4nsande toxicitet \xe4r neurologisk. Den omfattar sensorisk perifer neuropati som k\xe4nnetecknas av dysestesi och/eller parestesi i extremiteterna med eller utan kramper, ofta utl\xf6st av exponering f\xf6r kyla. Dessa symtom f\xf6rekommer hos upp till 95 % av de behandlade patienterna. Varaktigheten av symtomen, som vanligen g\xe5r tillbaka mellan behandlingarna, \xf6kar med antalet behandlingscykler. Vid debut av sm\xe4rta och/eller funktionsst\xf6rning ska dosen justeras eller behandlingen rentav s\xe4ttas ut, beroende p\xe5 symtomens varaktighet (se avsnitt 4.4). En s\xe5dan funktionsst\xf6rning inkluderar sv\xe5righeter att utf\xf6ra finmotoriska r\xf6relser och \xe4r en m\xf6jlig f\xf6ljd av sensorisk neds\xe4ttning. Risken f\xf6r uppkomst av kvarst\xe5ende symtom \xe4r ca 10 % vid en kumulativ dos p\xe5 850 mg/m (10 cykler) och 20 % vid en kumulativ dos p\xe5 1 020 mg/m (12 cykler). I de flesta fall f\xf6rb\xe4ttras de neurologiska tecknen och symtomen eller f\xf6rsvinner helt efter avslutad behandling. Vid adjuvant behandling av koloncancer hade 87 % av patienterna inga eller lindriga symtom 6 m\xe5nader efter behandlingens slut. Vid uppf\xf6ljning i upp till 3 \xe5r hade ca 3 % av patienterna antingen kvarst\xe5ende lokala parestesier av m\xe5ttlig intensitet (2,3 %) eller funktionsneds\xe4ttande parestesier (0,5 %). Akuta neurosensoriska manifestationer (se avsnitt 5.3) har rapporterats. De b\xf6rjar inom n\xe5gra timmar efter administrering och upptr\xe4der ofta vid exponering f\xf6r kyla. De yttrar sig vanligen som \xf6verg\xe5ende parestesi, dysestesi och hypoestesi. Akut syndrom med faryngolaryngeal dysestesi upptr\xe4der hos 1-2 % av patienterna och karakteriseras av en subjektiv k\xe4nsla av dysfagi eller dyspn\xe9/kv\xe4vningsk\xe4nsla utan n\xe5gra objektiva tecken p\xe5 andn\xf6d (ingen cyanos eller hypoxi) eller laryngospasm eller bronkospasm (ingen stridor eller v\xe4sande andning; k\xe4kkramp, onormal k\xe4nsla i tungan, dysartri och en k\xe4nsla av tr\xe5nghet i br\xf6stet har \xe4ven observerats. \xc4ven om antihistaminer och bronkvidgande medel har givits i s\xe5dana fall, \xe4r symtomen snabbt reversibla \xe4ven utan behandling. F\xf6rl\xe4ngning av infusionen bidrar till att minska incidensen av detta syndrom (se avsnitt 4.4). Andra neurologiska symtom som dysartri, f\xf6rlust av djupa senreflexer och Lhermittes tecken rapporterades under behandling med oxaliplatin. Enstaka fall av optisk neurit har rapporterats. Allergiska reaktioner Incidens per patient (%) per grad Oxaliplatin och 5-FU/FA Behandling av Adjuvant behandling 85 mg/m varannan metastaserande cancer vecka Alla Gr 3 Gr 4 Alla Gr 3 Gr 4 grader grader Allergiska 9,1 1 <1 10,3 2,3 0,6 reaktioner/allergi']]]],
 '_pages': [5, 10],
<<<<<<< HEAD
 u'_rank': 5,
=======
 u'_rank': 6,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}