{'_data': [['Very common',
            [['Infections', u'Infektion'],
             ['Blood', u'Anemi -Neutropeni -Trombocyto-peni -Leukopeni -Lymfopeni'],
             ['Immune system', u'Allergi allergiska reaktioner'],
             ['Metabolism', u'Anorexi Hyperglykemi -Hypokalemi -Hypernatremi'],
             ['Nervous system',
              u'Perifer -Yrsel sensorisk neuropati -K\xe4nsel-bortfa -Smak-f\xf6r\xe4ndr ingar -Huvudv\xe4rk'],
             ['Respiratory', u'Dyspn\xe9 -Hosta Epistaxis'],
             ['GI',
              u'Illam\xe5ende -Diarr\xe9 -Kr\xe4kningar -Stomatit/ mucosit -Magsm\xe4rtor -F\xf6rstoppning'],
             ['Skin', u'Hudbesv\xe4r -Alopeci'],
             ['Musculoskeletal', u'Ryggsm\xe4rta -Artralgi'],
             ['Renal',
              u'Utmattning ++ -Feber -Asteni -Sm\xe4rta -Reaktion vid injektions-st\xe4l +++ let'],
             ['Investigations',
              u'F\xf6rh\xf6jda leverenzymv\xe4r den -F\xf6rh\xf6jda alkaliska fosfataser -F\xf6rh\xf6jt bilirubin -F\xf6rh\xf6jt laktat dehydrogenas -Vikt\xf6kning (adjuvant behandling) *Se detaljerad tabell ** Se avsnitt 4.4 infusion, ibland vanliga angio\xf6dem, hypotension ++ Mycket vanligt: ven (se avsnitt'],
             ['Blood',
              u'Oxaliplatin och FU/FA 85 mg/ m varann a n vecka Anemi Neutrop e ni Tromboc yt o p Febril neutrop Neutrop e nisk sepsis'],
             ['Immune system',
              u'Oxaliplatin och 5-FU/FA 85 mg/ varann a n vecka Allergiska reaktioner/ Allergi'],
             ['Nervous system',
              u'antalet behandlingar. 850 mg/m synsk\xe4rpa, synf\xe4ltsrubbningar. Erfarenheter efter kramper'],
             ['GI',
              u'Oxaliplatin och 5-FU/FA 85 mg/ varann a n vecka Illam\xe5 e n d e Diarr\xe9 Kr\xe4kningar Mukosit/sto m a kombineras. (se'],
             ['Hepato', u'Mycket s\xe4llsynta f\xf6rh\xf6jda transaminaser.'],
             ['Renal', u'Mycket s\xe4llsynta']]],
           ['Common',
            [['Infections', u'Rinit -Infektion i \xf6vre'],
             ['Respiratory', u'/Neutropen sepsis'],
             ['Blood', u'Febril neutropeni'],
             ['Immune system', u'/'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Depression -Insomnia'],
             ['Nervous system', u'Neurit i moto-riska nerver -Meningism'],
             ['Eye', u'Konjunktivit -Synrubbning'],
             ['Vascular', u'Bl\xf6dning -Rodnad -Djup ventrombos -Hypertoni'],
             ['Respiratory', u'Hicka Lungemboli'],
             ['GI',
              u'Dyspepsi -Gastro-esofag al reflux -Gastro-intesti nal bl\xf6dning -Rektal-bl\xf6dni ng'],
             ['Skin',
              u'Hud-exfoliati on (hand och fotsyndrom) -Erytemat\xf6sa utslag -Utslag -\xd6kad svettning -Nagelbesv\xe4r'],
             ['Musculoskeletal', u'Skelettsm\xe4rta'],
             ['Renal', u'Hematuri -Dysuri -Abnormal miktions-frekv ens'],
             ['Investigations',
              u'F\xf6rh\xf6jt kreatinin -Vikt-minskni ng (behandling av metastas-eran de cancer) nedan -med d\xf6dligt resultat. -anafylaktiska reaktioner, inkluderande bronkospasm, f\xf6rnimmelse av br\xf6stsm\xe4rta, och anafylaktisk chock. -feber, stelhet (tremor) antingen orsakad av infektioner (med eller utan febril 4.4) '],
             ['Blood', u'5--e ni -e ni '],
             ['Immune system', u'm '],
             ['Nervous system', u'cykler) och 1020 mg/m med frekvens ok\xe4nd '],
             ['GI', u'm -tit -avsnitt 4.4). '],
             ['Hepato', u': '],
             ['Renal', u': ']]],
           ['Uncommon',
            [['Metabolism', u'Metabolisk acidos'],
             ['Psychiatric', u'Nervositet'],
             ['Ear', u'Ototoxicitet'],
             ['GI', u'Ileus -Intestinal obstruktion'],
             ['Blood',
              u'Incidens per patient (%) per grad Beha ndling av met a s t a s e r a n d e canc er 82,2 3 71,4 28 71,6 4 5,0 3,6 1,1 0,7'],
             ['Immune system', u'Beha ndling av met a s t a s e r a n d e canc er 9,1 1'],
             ['Nervous system', u'(12 cykler) \xe4r cirka 10% respektive 20%. Efter avslutad'],
             ['GI',
              u'Incidens per patient (%) per grad Beha ndling av met a s t a s e r a n d e canc er 69,9 8 60,8 9 49,0 6 39,9 4']]],
           ['Rare',
            [['Blood', u'Immuno-aller gisk trombocyto-pe ni -Hemolytisk anemi'],
             ['Nervous system',
              u'Dysartri Reversibelt posteriort leukoencefalo patisyndrom (RPLS) (se avsnitt 4,4)'],
             ['Eye',
              u'\xd6verg\xe5ende nedsatt synsk\xe4rpa -Synf\xe4lts st\xf6rningar -Optisk neurit -\xd6verg\xe5ende synned-s\xe4ttnin g, (reversibel efter behandlingen)'],
             ['Ear', u'D\xf6vhet'],
             ['Respiratory', u'Interstitiell lungsjukdom ibland fatal -Lungfibros'],
             ['GI',
              u'Kolitis inkluderande Clostridium difficile-orsak ad diarr\xe9 Pankreatit'],
             ['Blood', u'<1 14 <1 1,4 0,4'],
             ['Immune system', u'<1'],
             ['GI', u'<1 2 1 <1']]],
           ['Very rare',
            [['Blood',
              u'Adjuvant beha n dling 75,6 0,7 0,1 78,9 28,8 77,4 1,5 0,2 0,7 0,7 0,0 1,1 0,6 0,4'],
             ['Immune system', u'beha n dling 10,3 2,3 0,6'],
             ['GI',
              u'Adjuvant beha n dling 73,7 4,8 0,3 56,3 8,3 2,5 47,2 5,3 0,5 42,1 2,8 0,1']]],
           ['Unknown', [['Blood', u'12,3'], ['Immune system', u'Adjuvant']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 9],
 u'_rank': 60,
 u'_type': u'MSFU'}