{'_data': [['Very common',
            [['Infections', u'Infektion'],
             ['Blood', u'Anemi, neutropeni, trombocytopeni* Leukopeni, lymfopeni*'],
             ['Immune system', u'Allergi/allergisk reaktion'],
             ['Metabolism', u'Anorexi Glykemiska avvikelser, hypokalemi, rubbad natriumbalans'],
             ['Nervous system',
              u'Perifer sensorisk neuropati, huvudv\xe4rk Sensorisk st\xf6rning Smakf\xf6r\xe4ndring'],
             ['Vascular', u'Epistaxis'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI',
              u'Diarr\xe9, illam\xe5ende, kr\xe4kningar, stomatit/mukosit, buksm\xe4rta, f\xf6rstoppning'],
             ['Hepato',
              u'\xd6kade alkaliska fosfataser, \xf6kat bilirubin, \xf6kat LDH, \xf6kade leverenzymv\xe4rde n (ALAT, ASAT)'],
             ['Skin', u'Hudbesv\xe4r, alopeci'],
             ['Musculoskeletal', u'Ryggsm\xe4rta'],
             ['General',
              u'Feber asteni, sm\xe4rta, vikt\xf6kning (adjuvant behandling) Reaktion p\xe5 injektionsst\xe4llet'],
             ['GI', u'toxicitet ']]],
           ['Common',
            [['Infections',
              u'Febril neutropeni/ neutropen sepsis (neutropeni grad 3 eller 4 samt dokumenterade infektioner)* Rinit, infektion i \xf6vre luftv\xe4garna'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Depression, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Yrsel, motorisk neurit, meningism'],
             ['Eye', u'Konjunktivit, synrubbning'],
             ['Vascular',
              u'Bl\xf6dning, djup tromboflebit, lungemboli, rektalbl\xf6dning Rodnad'],
             ['Respiratory', u'Br\xf6stsm\xe4rta, hicka'],
             ['GI', u'Dyspepsi, gastroesofagal reflux'],
             ['Skin',
              u'Hudexfoliation (dvs. hand-och fotsyndrom), erytemat\xf6sa utslag, hudutslag, \xf6kad svettning, nagelbesv\xe4r'],
             ['Musculoskeletal', u'Artralgi, skelettsm\xe4rta'],
             ['Renal', u'Dysuri, onormal miktions-frekvens, \xf6kat kreatinin, hematuri'],
             ['General', u', tr\xf6tthet, Viktminskning (behandling av metastaserande cancer)']]],
           ['Uncommon',
            [['Metabolism', u'Metabolisk acidos'],
             ['Psychiatric', u'Nervositet'],
             ['Ear', u'Ototoxicitet'],
             ['GI', u'Ileus, intestinal obstruktion']]],
           ['Rare',
            [['Blood', u'Autoimmun trombocytopeni, hemolytisk anemi'],
             ['Nervous system', u'Dysartri, reversibelt posteriort leukoencefalopati syndrom'],
             ['Eye',
              u'\xd6verg\xe5ende nedsatt synsk\xe4rpa, synf\xe4ltsst\xf6rningar Optisk neurit'],
             ['Ear', u'D\xf6vhet'],
             ['Respiratory', u'Interstitiell lungsjukdom, lungfibros**'],
             ['GI', u'Kolit inkluderande Clostridium difficile-orsakad diarr\xe9']]],
           ['Very rare',
            [['GI', u'Pankreatit'],
             ['Hepato', u'Leversinusoidalt obstruktionssyn drom'],
             ['Renal',
              u'Akut tubulointerstitiel l nefropati. tubul\xe4r nekros som leder till akut njursvikt']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 9],
 u'_rank': 38,
 u'_type': u'MSFU'}