{'_data': [['Very common',
            [['Investigations',
              u'F\xf6rh\xf6jda leverenzymer -F\xf6rh\xf6jt alkaliskt fosfatas i blodet -F\xf6rh\xf6jt bilirubin i blodet -F\xf6rh\xf6jt laktatdehydrogenas i blodet -Vikt\xf6kning (adjuvant behandling)'],
             ['Blood', u'Anemi -Neutropeni -Trombocytopeni -Leukopeni -Lymfopeni'],
             ['Nervous system',
              u'Perifer sensorisk neuropati -Sensorisk rubbning -Dysgeusi -Huvudv\xe4rk'],
             ['Respiratory', u'Andn\xf6d -Hosta -Epistaxis'],
             ['GI',
              u'Illam\xe5ende -Diarr\xe9 -Kr\xe4kning -Stomatit/mukosit -Buksm\xe4rta -F\xf6rstoppning'],
             ['Skin', u'Hudbesv\xe4r -Alopeci'],
             ['Musculoskeletal', u'Ryggv\xe4rk'],
             ['Metabolism',
              u'Anorexi -Glykemiska avvikelser -Hypokalemi -Rubbad natriumbalans'],
             ['Infections', u'Infektion'],
             ['Vascular', u'Epistaxis'],
             ['General',
              u'Utmattning -Feber++ -Kraftl\xf6shet -Sm\xe4rta -Reaktion vid injektionsst\xe4llet+++'],
             ['Immune system', u'Allergi/allergisk reaktion+']]],
           ['Common',
            [['Investigations',
              u'F\xf6rh\xf6jd kreatininhalt i blodet -Viktminskning (behandling mot metastaserande kolorektalcancer)'],
             ['Blood', u'Febril neutropeni'],
             ['Nervous system', u'Yrsel -Neurit i motoriska nerver -Meningism'],
             ['Eye', u'Konjunktivit -Synrubbning'],
             ['Respiratory', u'Hicka -Lungembolism'],
             ['GI',
              u'Dyspepsi -Gastroesofagal reflux -Gastrointestinal bl\xf6dning -Rektal bl\xf6dning'],
             ['Renal', u'Hematuri -Dysuri -Onormal bl\xe5st\xf6mnings-frekvens'],
             ['Skin',
              u'Hudavflagning (dvs hand-och fotsyndrom) -Erytemat\xf6sa utslag -Utslag -Hyperhidros -Nagelbesv\xe4r'],
             ['Musculoskeletal', u'Artralgi -Skelettsm\xe4rta'],
             ['Metabolism', u'Dehydrering'],
             ['Infections',
              u'Rinit -\xd6vre luftv\xe4gsinfektion -Febril neutropeni/neutropen sepsis'],
             ['Vascular',
              u'Bl\xf6dning -V\xe4rmevallning -Djup ventrombos -Lungemboli -Hypertoni'],
             ['Psychiatric', u'Depression -Insomni']]],
           ['Uncommon',
            [['Ear', u'Ototoxicitet'],
             ['GI', u'Ileus -Tarm-obstruktion'],
             ['Metabolism', u'Metabol acidos'],
             ['Psychiatric', u'Nervositet']]],
           ['Rare',
            [['Blood', u'Immunoallergisk trombocytopeni -Hemolytisk anemi'],
             ['Nervous system',
              u'Dysartri -Reversibel Posterior Leukoencefalopati syndrom (RPLS, ocks\xe5 k\xe4nt som PRES, Posterior Reversibel Encefalopati Syndrom)** (se avsnitt 4.4)'],
             ['Eye',
              u'\xd6verg\xe5ende nedsatt synsk\xe4rpa -Synf\xe4ltsrubbningar -Optisk neurit -\xd6verg\xe5ende synneds\xe4ttning, reversibel efter uts\xe4ttande av behandling'],
             ['Ear', u'D\xf6vhet'],
             ['Respiratory',
              u'Interstitiell lungsjukdom, ibland med d\xf6dlig utg\xe5ng -Lungfibros**'],
             ['GI', u'Kolit inklusive Clostridium difficile-orsakad diarr\xe9 -Pankreatit']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 9],
 u'_rank': 35,
 u'_type': u'MSFU'}