{'_data': [['Common', [['General', u'  D\xe5sighet.  ']]],
           ['Uncommon',
            [['General', u'  Yrsel, huvudv\xe4rk.  '],
             ['Nervous system', u' Ataxi, muskelsvaghet. '],
             ['Psychiatric', u' Anterograd amnesi vid h\xf6ga doser. ']]],
           ['Rare',
            [['Skin', u' Allergiska hudreaktioner.  '],
             ['Nervous system', u' Respiratorisk depression.  '],
             ['Psychiatric',
              u' Insomnia, mardr\xf6mmar, paradoxala reaktioner som excitationstillst\xe5nd, aggressivitet, hallucinationer. ']]]],
 '_pages': [3, 3],
 u'_rank': 7,
 u'_type': u'DFSU'}