{'_data': [['Very common',
            [['Nervous system', u'somnolens, yrsel, huvudv\xe4rk'],
             ['GI', u'f\xf6rstoppning, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'kl\xe5da']]],
           ['Common',
            [['Metabolism', u'anorexi, nedsatt aptit'],
             ['Psychiatric',
              u'olika psykologiska biverkningar inklusive hum\xf6rsv\xe4ngningar (t.ex. \xe5ngest, depression, eufori), f\xf6r\xe4ndringar i aktivitetsgrad (oftast neds\xe4ttning, ibland associerad med letargi, i n\xe5gra fall \xf6kning med uppr\xf6rdhet, nervositet och s\xf6mnl\xf6shet) och f\xf6r\xe4ndringar i kognitiv f\xf6rm\xe5ga (onormala tankar, f\xf6rvirring)'],
             ['Nervous system', u'svimning, parestesi'],
             ['Vascular', u'hypotoni'],
             ['Respiratory', u'andningsdepression, bronkospasm, andn\xf6d, hicka'],
             ['GI', u'muntorrhet, buksm\xe4rtor, diarr\xe9, rapning, dyspepsi'],
             ['Skin', u'hudsymtom s\xe5 som utslag'],
             ['Renal',
              u'urineringsst\xf6rningar (urinretention, men \xe4ven \xf6kat urineringsbehov)'],
             ['General', u'asteni, svettningar, men \xe4ven frossa']]],
           ['Uncommon',
            [['Immune system', u'allergiska reaktioner'],
             ['Endocrine',
              u'syndrom med otillr\xe4cklig uts\xf6ndring av antidiuretiskt hormon'],
             ['Psychiatric',
              u'f\xf6r\xe4ndringar i perception som personlighetsf\xf6r\xe4ndring, hallucinationer, nedsatt libido'],
             ['Nervous system',
              u'\xf6kad eller minskad muskeltonus, tremor, ofrivilliga muskelsammandragningar, hypestesi, koordinationssv\xe5righeter, smakf\xf6r\xe4ndringar, migr\xe4n, svindel'],
             ['Eye', u'rubbning i produktionen av t\xe5rv\xe4tska, mios, synrubbningar'],
             ['Ear', u'hyperakusi'],
             ['Cardiac', u'supraventrikul\xe4r takykardi'],
             ['Vascular', u'vasodilatation'],
             ['Respiratory', u'hosta, faryngit, rinit, r\xf6stf\xf6r\xe4ndring'],
             ['GI', u'gallv\xe4gskolik, muns\xe5r, gingivit, stomatit, flatulens'],
             ['Reproductive system', u'impotens'],
             ['General',
              u'sm\xe4rta (t.ex. br\xf6stsm\xe4rta), \xf6dem, allm\xe4n sjukdomsk\xe4nsla, fysiskt beroende med uts\xe4ttningssymtom'],
             ['Injury',
              u'oavsiktliga skador F\xf6rebyggande \xe5tg\xe4rder: Eftersom f\xf6rstoppning \xe4r en mycket vanlig biverkning kan det vara till hj\xe4lp att instruera patienten att detta kan f\xf6rebyggas genom en fiberberikad diet och \xf6kat v\xe4tskeintag. Vid illam\xe5ende och kr\xe4kningar kan f\xf6rskrivning av antiemetika \xf6verv\xe4gas.']]],
           ['Rare',
            [['Infections', u'herpes simplex'],
             ['Blood', u'lymfadenopati'],
             ['Metabolism', u'dehydrering, \xf6kad aptit'],
             ['Nervous system',
              u'kramper, s\xe4rskilt hos patienter med epilepsi eller med tendens till krampanfall, amnesi'],
             ['Cardiac', u'hj\xe4rtklappning'],
             ['GI',
              u'ileus, bl\xf6dande tandk\xf6tt, dysfagi, t\xf6rst, tj\xe4rliknande avf\xf6ring, fl\xe4ckar och skador p\xe5 t\xe4nderna'],
             ['Skin', u'torr hud, ljusk\xe4nslighet'],
             ['Musculoskeletal', u'muskelspasmer'],
             ['Renal', u'hematuri'],
             ['Reproductive system', u'amenorr\xe9'],
             ['General', u'viktf\xf6r\xe4ndringar (\xf6kning eller minskning), cellulit']]],
           ['Very rare',
            [['Immune system', u'anafylaktiska reaktioner'],
             ['Nervous system', u'talsv\xe5righeter'],
             ['Skin', u'urtikaria, exfoliativ dermatit']]]],
 '_pages': [4, 6],
 u'_rank': 39,
 u'_type': u'LSFU'}