{'_data': [['Very common', [['GI', u'muntorrh et']]],
           ['Common',
            [['Eye', u'dimsyn'],
             ['GI', u'illam\xe5ende, abdominalt obehag/sm\xe4rta, dyspepsi,'],
             ['Skin', u'ansiktsrodnad']]],
           ['Uncommon',
            [['Metabolism', u'minskad aptit/anorexi'],
             ['Nervous system', u'huvudv\xe4rk, yrsel, somnolens/tr\xf6t thet, d\xe5sighet'],
             ['Eye', u'Mild \xf6verk\xe4nslighet'],
             ['Cardiac', u'takykardi, hj\xe4rtarytmier'],
             ['GI', u'Diarr\xe9, kr\xe4kningar'],
             ['Skin', u'minskad svettning/torr hud'],
             ['Renal', u'urinretention']]],
           ['Rare',
            [['Psychiatric',
              u'hallucinationer, excitation/agitation*, mardr\xf6mmar*, f\xf6rvirring, \xe5ngest*, paranoia*,rastl\xf6shet* , desorientering, koncentrationssv\xe5rig heter'],
             ['Nervous system', u'konvulsioner*, kognitiva st\xf6rningar*'],
             ['Eye',
              u'minskat t\xe5rfl\xf6de/torra \xf6gon, mydriasis, tr\xe5ngvinkelglaukom* , h\xf6gt intraokul\xe4rttryck'],
             ['GI', u'gastroesofageal reflux'],
             ['Skin',
              u'fototoxicitet*, allergiska reaktioner s\xe5som hudutslag, urtikaria och angio\xf6dem'],
             ['Reproductive system', u'erektil dysfunktion*'],
             ['General', u'v\xe4rmeslag']]],
           ['Unknown', []]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 18,
 u'_type': u'MSFU'}