{'_data': [['Very common',
            [['Nervous system', u'somnolens, yrsel, huvudv\xe4rk.'],
             ['GI', u'f\xf6rstoppning, illam\xe5ende, kr\xe4kningar.'],
             ['Skin', u'kl\xe5da.']]],
           ['Common',
            [['Metabolism', u'anorexi.'],
             ['Psychiatric',
              u'olika psykiska st\xf6rningar inklusive \xe4ndrad sinnest\xe4mning (t.ex. \xe5ngest, depression, eufori), \xe4ndrat aktivitetstillst\xe5nd (oftast supression ibland med letargi, ibland \xf6kning med agitation, nervositet och s\xf6mnl\xf6shet) och \xe4ndrad kognitiv prestationsf\xf6rm\xe5ga (abnorma tankar, f\xf6rvirring, amnesi, enstaka fall av talst\xf6rningar).'],
             ['Nervous system', u'asteni, parestesi.'],
             ['Eye',
              u's\xe4nkt blodtryck, i s\xe4llsynta fall med sekund\xe4ra symptom s\xe5 som palpitationer, synkop\xe9, bronkospasm.'],
             ['Respiratory', u'andningsdepression.'],
             ['GI',
              u'muntorrhet, i s\xe4llsynta fall med t\xf6rst och sv\xe4ljningssv\xe5righeter, st\xf6rningar i magtarmkanalen s\xe5 som buksm\xe4rtor, diarr\xe9, eruktation, dyspepsi, aptitf\xf6rlust.'],
             ['Skin',
              u'hudsymtom s\xe5 som utslag, i s\xe4llsynta fall \xf6kad ljusk\xe4nslighet, i enstaka fall urtikaria eller exfolitaiv dermatit.'],
             ['Renal',
              u'urineringsst\xf6rningar (urinretention, men \xe4ven \xf6kat urineringsbehov).'],
             ['General', u'svettning och \xe4ven frossbrytningar.']]],
           ['Uncommon',
            [['Endocrine', u'inadekvat ADH-sekretion (SIADH).'],
             ['Psychiatric',
              u'\xe4ndrad perception s\xe5 som depersonalisering, hallucinationer, smakf\xf6r\xe4ndringar, synst\xf6rningar, hyperakusi.'],
             ['Nervous system',
              u'b\xe5de \xf6kad och minskad muskeltonus, tremor, ofrivilliga muskelryckningar, hypestesi, koordinationsst\xf6rningar, malaise, vertigo.'],
             ['Eye', u'st\xf6rd lakrimation, mios. Hj\xe4rtat och blodk\xe4rl'],
             ['Eye', u'supraventrikul\xe4r takykardi, vasodilatation.'],
             ['Respiratory', u'\xf6kad hosta, faryngit, rinit, r\xf6stf\xf6r\xe4ndringar.'],
             ['GI', u'gallv\xe4gskolik, muns\xe5r, gingivit, stomatit, flatulens.'],
             ['Reproductive system', u'minskad libido; impotens.'],
             ['General',
              u'olycksrelaterade skador, sm\xe4rta (t.ex. br\xf6stsm\xe4rta), \xf6dem, migr\xe4n, fysiskt beroende med uts\xe4ttningssymtom, allergiska reaktioner, l\xe4kemedelstolerans.']]],
           ['Rare',
            [['Blood', u'lymfadenopati.'],
             ['Metabolism', u'dehydrering.'],
             ['Nervous system',
              u'krampanfall, s\xe4rskilt hos epileptiska patienter eller patienter med tendens till kramper; muskelkramp.'],
             ['GI',
              u'tandk\xf6ttsbl\xf6dning, \xf6kad aptit, tj\xe4rliknande avf\xf6ring, missf\xe4rgade och skadade t\xe4nder, ileus.'],
             ['Skin', u'torr hud; herpes simplex.'],
             ['Renal', u'hematuri.'],
             ['Reproductive system', u'amenorr\xe9.'],
             ['General', u'viktf\xf6r\xe4ndringar (\xf6kning eller minskning); celluliter.']]],
           ['Very rare', [['General', u'anafylaktiska reaktioner.']]]],
 '_pages': [5, 7],
 u'_rank': 30,
 u'_type': u'LSFU'}