{'_data': [['Very common',
            [['Psychiatric', u'Yrsel, somnolens'],
             ['GI', u'F\xf6rstoppning, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'Pruritus']]],
           ['Common',
            [['Metabolism', u'Anorexi'],
             ['Psychiatric',
              u'\xc5ngest, f\xf6rvirring, s\xf6mnl\xf6shet, nervositet, depression, onormal tankeverksamhet'],
             ['Psychiatric', u'Huvudv\xe4rk'],
             ['Vascular', u'Dyspn\xe9'],
             ['GI', u'Buksm\xe4rtor, diarr\xe9, dyspepsi, muntorrhet'],
             ['Skin', u'Utslag, svettning'],
             ['Renal', u'\xd6dem, asteni, frossbrytningar']]],
           ['Uncommon',
            [['Metabolism', u'Dehydrering'],
             ['Psychiatric',
              u'Agitation, hallucinationer, emotionell labilitet, eufori, beorende*, minskad libido Centrala och perifera'],
             ['Psychiatric',
              u'Krampanfall, ofrivilliga muskelr\xf6relser, hypertoni, hypestesi, parestesi, talst\xf6rningar, tremor, vertigo, amnesi, smakf\xf6r\xe4ndring'],
             ['Eye', u'Synrubbningar, mios'],
             ['Cardiac', u'Palpitationer (i samband med abstinenssyndrom)'],
             ['Vascular',
              u'Hypotension, vasodilation, ortostatisk hypotension Andningsv\xe4gar br\xf6stkorg och mediastinum'],
             ['Vascular', u'Andningsdepression'],
             ['GI', u'Gastrointestinala st\xf6rningar, flatulens, dysfagi, ileus, rapning'],
             ['Hepato', u'Gallv\xe4gsspasm'],
             ['Skin', u'Urtikaria, torr hud'],
             ['Renal', u'Urinretention Reproduktionsorgan och br\xf6stk\xf6rtel'],
             ['Renal',
              u'Amenorr\xe9, impotens Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Renal', u'Perifert \xf6dem, t\xf6rst, abstinenssyndrom, sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Immune system',
              u'Allergiska reaktioner, anafylaktoida reaktioner, anafylaktiska reaktioner']]],
           ['Very rare', [['Hepato', u'F\xf6rh\xf6jda leverenzymv\xe4rden']]]],
 '_pages': [5, 6],
 u'_rank': 25,
 u'_type': u'LSFU'}