{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Takykardi, bradykardi'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar.']]],
           ['Uncommon',
            [['Metabolism',
              u'Antidiuretisk effekt vilket kan orsaka vatte nint oxika tion med huvudv\xe4 rk och illam\xe5 e n d e .']]],
           ['Rare',
            [['Immune system',
              u'Anafylaktoida reaktioner tillsammans med hypotension, andn\xf6d och chock.'],
             ['Cardiac', u'Hj\xe4rtarytmier'],
             ['Skin',
              u'Hudrodnad, urtikaria. Andningsv \xe4 gar, br\xf6stkorg och me diastinu m'],
             ['Skin',
              u'Larynx\xf6d e m L\xe5ngvarig anv\xe4 nd ning eller snabb infusion kan f\xf6rorsaka biverkning ar. En \xf6kad risk f\xf6r utbre d d intrava sk ul \xe4r koagulation post- partu m har beskrivits hos patient e r vars v\xe4rkarb e t e induc er a t s me d l\xe4ke me d e l, antinge n med dinoprosto n eller me d oxytocin (se 4.4). Frekve ns e n f\xf6r denna biverkning verkar dock vara'],
             ['Skin', u'(<1 av 1000 v\xe4rkarb e t e n).']]]],
 '_pages': [3, 4],
 u'_rank': 9,
 u'_type': u'LSFU'}