{'_data': [['Very common',
            [['Infections',
              u' Infektioner (huvudsakligen urinv\xe4gs- och \xf6vre luftv\xe4gsinfektioner), \xe4ven fall med d\xf6dlig utg\xe5ng'],
             ['Blood',
              u' Myelosuppression, neutropeni, anemi, trombocytopeni, leukopeni, bl\xf6dningar'],
             ['Immune system',
              u' L\xe4ttare \xf6verk\xe4nslighetsreaktioner (huvudsakligen flush och hudutslag)'],
             ['Nervous system', u' Neurotoxicitet (huvudsakligen perifer neuropati)'],
             ['Vascular', u' Hypotension'],
             ['GI', u' Diarr\xe9, kr\xe4kning, illam\xe5ende, mukosit'],
             ['Skin', u' Alopeci'],
             ['Musculoskeletal', u' Artralgi, myalgi']]],
           ['Common',
            [['Cardiac', u' Bradykardi'],
             ['Skin', u'\xd6verg\xe5ende l\xe4tta nagel- och hudf\xf6r\xe4ndringar'],
             ['General',
              u' Reaktioner vid injektionsst\xe4llet (lokaliserat \xf6dem, sm\xe4rta, rodnad, induration, i enstaka fall kan extravasering ge upphov till cellulit, hudfibros och hudnekros)'],
             ['Investigations', u' Kraftig \xf6kning av ASAT och alkaliska fosfataser']]],
           ['Uncommon',
            [['Infections', u' Septisk chock'],
             ['Immune system',
              u' Behandlingskr\xe4vande sv\xe5r \xf6verk\xe4nslighetsreaktion (t.ex. hypotension angioneurotiskt \xf6dem, andningssv\xe5righeter, generaliserad urtikaria, frossa, ryggsm\xe4rtor, br\xf6stsm\xe4rtor, takykardi, buksm\xe4rtor, sm\xe4rtor i'],
             ['Cardiac',
              u' Myokardinfarkt, AV-block och synkope, kardiomyopati, asymtomatisk ventrikul\xe4r takykardi, takykardi med bigemini, ,'],
             ['Vascular', u' Trombos, hypertension, tromboflebit'],
             ['Investigations', u' Kraftig \xf6kning av bilirubin']]],
           ['Rare',
            [['Infections', u' Sepsis, peritonit, pneumoni'],
             ['Blood', u' Febril neutropeni'],
             ['Immune system', u' Anafylaktisk reaktion'],
             ['Nervous system', u' Motorisk neuropati (med l\xe4ttare distal svaghet)'],
             ['Cardiac', u' Hj\xe4rtsvikt'],
             ['Respiratory',
              u' Andningssvikt, lungemboli, lungfibros, interstitiell pneumoni, dyspn\xe9, pleurautgjutning'],
             ['GI', u' Tarmobstruktion, tarmperforation, ischemisk kolit, pankreatit'],
             ['Skin', u' Pruritus, hudutslag och rodnad'],
             ['General', u' Pyrexi, dehydrering, asteni, \xf6dem, sjukdomsk\xe4nsla'],
             ['Investigations', u' \xd6kning av kreatinin i blodet']]],
           ['Very rare',
            [['Blood', u'Akut myelotisk leukemi, myelodysplastiskt syndrom'],
             ['Immune system', u'Anafylaktisk chock'],
             ['Metabolism', u' Anorexi'],
             ['Psychiatric', u' Konfusionstillst\xe5nd'],
             ['Nervous system',
              u'Grandmal-anfall, autonom neuropati (med paralytisk ileus och ortostatisk hypertension som f\xf6ljd), encefalopati, konvulsioner, yrsel, ataxi, huvudv\xe4rk'],
             ['Eye',
              u' Synnervsp\xe5verkan och/eller synst\xf6rningar (flimmerskotom), speciellt hos patienter som erh\xe5llit h\xf6gre doser \xe4n de rekommenderade'],
             ['Ear', u' H\xf6rself\xf6rlust, ototoxicitet, tinnitus och vertigo'],
             ['Cardiac', u'F\xf6rmaksflimmer , supraventrikul\xe4r takykardi'],
             ['Vascular', u'Chock'],
             ['Respiratory', u'Hosta'],
             ['GI',
              u'Mesenteritrombos, pseudomembran\xf6s kolit, neutropen kolit, ascites, esofagit, f\xf6rstoppning'],
             ['Hepato',
              u' Levernekros, leverencefalopati (b\xe5da med rapporterade fall med d\xf6dlig utg\xe5ng)'],
             ['Skin',
              u'Steven -Johnsons syndrom, epidermal nekrolys, erythema multiforme, exfoliativ dermatit, urtikaria, oncholys (patienterna b\xf6r anv\xe4nda solskydd p\xe5 h\xe4nder och f\xf6tter under behandlingen)']]],
           ['Unknown',
            [['Metabolism', u'Tum\xf6rlyssyndrom'],
             ['Eye', u'Makula\xf6dem, fotopsi, flugseende'],
             ['Vascular', u'Flebit'],
             ['Skin', u'Scleroderma'],
             ['Musculoskeletal', u'Systemisk lupus erythematosus']]]],
 '_pages': [6, 10],
 u'_rank': 45,
 u'_type': u'LSFU2'}