{'_data': [['Very common',
            [['Metabolism', u'Hypokalcemi, hypofosfatemi.'],
             ['General',
              u'Feber och influensaliknande symtom, ibland \xe5tf\xf6ljt av sjukdomsk\xe4nsla, stelhet, tr\xf6tthet och blodvallningar.']]],
           ['Common',
            [['Blood', u'Lymfocytopeni.'],
             ['Metabolism', u'Hypomagnesemi.'],
             ['Nervous system', u'Huvudv\xe4rk.'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar.'],
             ['Musculoskeletal',
              u'\xd6verg\xe5ende bensm\xe4rta, artralgi, myalgi, generaliserad sm\xe4rta.'],
             ['General',
              u'Reaktioner p\xe5 infusionsst\xe4llet sm\xe4rta, rodnad, svullnad, induration, flebit, tromboflebit.']]],
           ['Rare',
            [['Blood', u'Anemi, leukopeni.'],
             ['Immune system',
              u'Allergisk reaktion, anafylaktiska reaktioner, bronkialspasm (dyspn\xe9) och Quinckes \xf6dem.'],
             ['Metabolism', u'Hyperkalemi, hypokalemi, hypernatremi'],
             ['Nervous system',
              u'Symtomatisk hypokalcemi (parestesi, tetani), agitation, f\xf6rvirring, yrsel, s\xf6mnl\xf6shet, s\xf6mnighet, letargi.'],
             ['Cardiac',
              u'Kronisk hj\xe4rtinsufficiens (\xf6dem) p\xe5 grund av v\xe4tske\xf6verbelastning.'],
             ['Vascular', u'Hypotoni, hypertoni.'],
             ['Respiratory', u'Dyspn\xe9, lung\xf6dem.'],
             ['GI', u'Anorexi, buksm\xe4rta, diarr\xe9, f\xf6rstoppning, dyspepsi.'],
             ['Musculoskeletal', u'Muskelkramper'],
             ['Renal',
              u'F\xf6rs\xe4mring av njurfunktion (se 4.4 Varningar och f\xf6rsiktighet). Fokal segmental glomeruloskleros inklusive den kollapsande varianten, nefrotiskt syndrom, glomerulonefropati. Dessa biverkningar har i allm\xe4nhet rapporterats i samband med h\xf6gdosbehandling (h\xf6gre \xe4n den rekommenderade dosen eller med reducerat doseringsintervall) och/eller l\xe5ngtidsbehandling.']]],
           ['Very rare',
            [['Infections', u'Reaktivering av herpes simplex och herpes zoster.'],
             ['Blood', u'Trombocytopeni'],
             ['Immune system', u'Anafylaktisk chock.'],
             ['Nervous system', u'Krampanfall, synhallucinationer.'],
             ['Eye',
              u'Uveit (irit, iridocyklit), sklerit, episklerit, konjunktivit, xantopsi.'],
             ['Respiratory', u'ARDS, interstitiell pneumoni.'],
             ['GI', u'Gastrit.'],
             ['Skin', u'Utslag, kl\xe5da.'],
             ['Musculoskeletal', u'Osteonekros'],
             ['Renal',
              u'Hematuri, akut njurinsufficiens, f\xf6rs\xe4mring av redan existerande njursjukdom, sjukdom i njurtubuli, tubulointerstitiell nefrit.'],
             ['Investigations',
              u'Onormala v\xe4rden vid leverfunktionstest, \xf6kade serumhalter av kreatinin och urea. M\xe5nga av dessa biverkningar kan ha varit relaterade till den bakomliggande sjukdomen. N\xe4r effekten av zoledronsyra (4 mg) och pamidronat (90 mg) j\xe4mf\xf6rdes i en klinisk pr\xf6vning, var frekvensen f\xf6rmaksflimmer som biverkan h\xf6gre i pamidronatgruppen (12/556; 2,2 %) \xe4n i zoledronsyragruppen (3/563; 0,5 %). Tidigare har det observerats i en klinisk pr\xf6vning med patienter med postmenopausal osteoporos att zoledronsyrabehandlade patienter (5 mg) hade en \xf6kad frekvens av f\xf6rmaksflimmer som allvarlig biverkan j\xe4mf\xf6rt med placebo (1,3 % j\xe4mf\xf6rt med 0,6 %). Mekanismen bakom den \xf6kade incidensen av f\xf6rmaksflimmer i samband med zoledronsyra och pamidronatbehandling \xe4r ok\xe4nd. Efter marknadsf\xf6ringen: Mycket s\xe4llsynta fall av osteonekros (fr\xe4mst i k\xe4ken) har rapporterats hos patienter som behandlats med bisfosfonater. M\xe5nga av dessa patienter hade tecken p\xe5 lokal infektion inklusive osteomyelit. Huvudparten av rapporterna g\xe4ller patienter med cancer som genomg\xe5tt tandutdragning eller annan oralkirurgi. Det finns m\xe5nga v\xe4ldokumenterade riskfaktorer f\xf6r osteonekros i k\xe4ken bl a cancerdiagnos, samtidig l\xe4kemedelsbehandling (t ex cytostatika, str\xe5lbehandling, kortikosteroider) och sjukdomstillst\xe5nd (t ex anemi, koagulationsrubbningar, infektion, tidigare sjukdom i munh\xe5lan). \xc4ven om orsakssambandet inte \xe4r s\xe4kerst\xe4llt b\xf6r oral kirurgi undvikas, eftersom l\xe4kningen kan bli f\xf6rdr\xf6jd (se avsnitt 4.4). Efter marknadsf\xf6ring har f\xf6ljande biverkningar rapporterats (frekvens: s\xe4llsynt): Atypiska subtrokant\xe4ra och diafys\xe4ra femurfrakturer (bisfosfonat klassbiverkning).']]]],
 '_pages': [5, 7],
 u'_rank': 29,
 u'_type': u'LSFU'}