{'_data': [['Very common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['Musculoskeletal', u'artralgi, myalgi'],
             ['General',
              u'induration, svullnad, sm\xe4rta och rodnad vid injektionsst\xe4llet, feber, tr\xf6tthet']]],
           ['Common',
            [['Blood', u'lymfadenopati'],
             ['Skin', u'ekkymos vid injektionsst\xe4llet, \xf6kad svettning'],
             ['General',
              u'frossa, influensaliknande sjukdom, reaktioner vid injektionsst\xe4llet (t ex v\xe4rmek\xe4nsla, kl\xe5da)']]],
           ['Uncommon',
            [['Psychiatric', u's\xf6mnl\xf6shet'],
             ['Nervous system', u'parestesier, somnolens, yrsel'],
             ['GI',
              u'gastrointestinala symtom (t ex diarr\xe9, kr\xe4kningar, buksm\xe4rta, illam\xe5ende)'],
             ['Skin', u'kl\xe5da, utslag'],
             ['General',
              u'sjukdomsk\xe4nsla Barn i \xe5ldrarna 3-9 \xe5r I en klinisk studie utv\xe4rderades reaktogeniciteten hos barn 3-5 \xe5r och 6-9 \xe5r, som fick antingen tv\xe5 vuxendoser (dvs 0,5 ml) eller tv\xe5 halva vuxendoser (dvs 0,25 ml) av Adjupanrix (med 21 dagars mellanrum). En skillnad i biverkningsfrekvensen mellan en halv och en full vuxendos s\xe5gs efter varje dos. Emellertid observerades ingen \xf6kad reaktogenicitet efter vare sig den andra halva eller fulla vuxendosen, utom vad g\xe4ller frekvens av allm\xe4nna symtom, vilka var h\xf6gre efter den andra vuxendosen. Frekvensen per dos av f\xf6ljande biverkningar var: Biverkning 3-5 \xe5r 6-9 \xe5r Halv vuxendos Vuxendos Halv vuxendos Vuxendos Induration 9,9% 18,6% 12,0% 12,2% Sm\xe4rta 48,5% 62,9% 68,0% 73,5% 5 Rodnad 10,9% 19,6% 13,0% 6,1% Svullnad 11,9% 24,7% 14,0% 20,4% Feber (>38\xb0C) 4,0% 11,3% 2,0% 17,3% Feber (>39\xb0C) frekvens per dos 2,0% 5,2% 0% 7,1% frekvens per individ 3,9% 10,2% 0% 14,3% D\xe5sighet 7,9% 13,4% NA NA Irritabilitet 7,9% 18,6% NA NA Aptitl\xf6shet 6,9% 16,5% NA NA Frossa 1,0% 12,4% 4,0% 14,3% NA=Ej tillg\xe4ngligt \u2022Uppf\xf6ljning efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning Inga uppf\xf6ljningsdata fr\xe5n administrering av Adjupanrix efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning finns tillg\xe4ngliga. Vaccin inneh\xe5llande adjuvans AS03 och 3,75 \xb5g HA fr\xe5n A/California/7/2009 (H1N1) F\xf6ljande biverkningar har rapporterats f\xf6r vaccin inneh\xe5llande adjuvans AS03 och 3,75 \xb5g HA fr\xe5n A/California/7/2009 (H1N1) efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning']]],
           ['Rare', [['Skin', u'Neuralgi, \xf6verg\xe5ende trombocytopeni']]],
           ['Very rare',
            [['Skin',
              u'Vaskulit med \xf6verg\xe5ende njurp\xe5verkan Neurologiska st\xf6rningar s\xe5som encefalomyelit, neurit och Guillain-Barr\xe9s syndrom Detta l\xe4kemedel inneh\xe5ller tiomersal (en organisk kvicksilverf\xf6rening) som konserveringsmedel, och d\xe4rf\xf6r kan m\xf6jligen en \xf6verk\xe4nslighetsreaktion intr\xe4ffa (se avsnitt 4.4).']]],
           ['Unknown',
            [['Immune system', u'Anafylaxi, allergiska reaktioner'],
             ['Nervous system', u'Feberkramper'],
             ['Skin',
              u'Angio\xf6dem, generella hudreaktioner, urtikaria Interpandemiska trivalenta vacciner Ut\xf6ver biverkningar som setts under uppf\xf6ljning efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning av interpandemiska trivalenta s\xe4songsvacciner mot influensa har f\xf6ljande biverkningar rapporterats']]]],
 '_pages': [3, 5],
 u'_rank': 16,
 u'_type': u'LSFU'}