{'_data': [[u'Unknown',
            [['Blood', u'Trombo-   cytopeni,'],
             ['Immune system', u'\xd6verk\xe4nslighet   (inklusive'],
             ['Metabolism', u'Hyperlipidemi   Hyponatremi'],
             ['Psychiatric',
              u'S\xf6mn-   Depression (och   Desoriente-   Hallucina-   st\xf6rningar   alla   ring (och alla   tioner,'],
             ['Nervous system', u'Huvudv\xe4rk,   yrsel'],
             ['Eye', u'Synrubbningar/'],
             ['GI', u'Diarr\xe9,   illam\xe5ende/'],
             ['Hepato',
              u'F\xf6rh\xf6jda   \xd6kad   Hepato-   leverenzymer   bilirubinhalt   cellul\xe4r'],
             ['Skin',
              u'och   Hudutslag/   Urtikaria,   Stevens-   exantem/   angio\xf6dem   Johnsons   eruption,   syndrom,   pruritus   Lyells   syndrom,  erythema  multiforme,  ljusk\xe4ns-  lighet'],
             ['Musculoskeletal', u'Artralgi,   myalgi    och'],
             ['Renal', u'Interstitiell   nefrit'],
             ['Reproductive system', u'Gynekomasti    och'],
             ['General', u'Trombo-   Asteni,   \xd6kad']]]],
 '_pages': [4, 6],
 u'_rank': 13,
 u'_type': u'LFSU'}