{'_data': [[u'Unknown',
            [['Blood', u'Agranulocytos   Trombocytopeni,   leukopeni,'],
             ['Nervous system', u'Huvudv\xe4rk,   F\xf6r\xe4ndrad   yrsel   smakupplevelse'],
             ['Eye', u'Synst\xf6rningar /'],
             ['GI', u'Diarr\xe9,'],
             ['Renal', u'Interstitiell   nefrit'],
             ['Skin',
              u'Hudutslag /   Urtikaria, angio\xf6dem   Stevens-   exantem /   Johnsons'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Metabolism',
              u'Hyperlipidemi och   Hyponatremi,   lipid\xf6kningar   hypomagnesemi'],
             ['General', u'Asteni, tr\xf6tthet   \xd6kad'],
             ['Immune system', u'\xd6verk\xe4nslighet (inkl.'],
             ['Hepato',
              u'Leverenzym\xf6kn   Bilirubin\xf6kning   Hepatocellul\xe4r   ingar   skada, gulsot,'],
             ['Psychiatric',
              u'S\xf6mnst\xf6rningar   Depression (och   Desorientering   Hallucination,   alla f\xf6rs\xe4mringar)   (och alla   f\xf6rvirring'],
             ['Reproductive system', u'Gynekomasti']]]],
 '_pages': [3, 6],
 u'_rank': 13,
 u'_type': u'LFSU'}