{'_data': [[u'Unknown',
            [['Blood', u'Trombocytopeni,   leukopeni,'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'Hyperlipidemi och   Hyponatremi,   lipid\xf6kning   hypomagnesemi'],
             ['Psychiatric',
              u'S\xf6mnst\xf6rningar   Depression (och alla   Desorientering   Hallucinationer,'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Eye', u'Synrubbningar /'],
             ['GI', u'Diarr\xe9, illam\xe5ende /'],
             ['Hepato', u'F\xf6rh\xf6jda   F\xf6rh\xf6jt bilirubin   Hepatocellul\xe4r'],
             ['Skin',
              u'Hudutslag/   Urticaria, angio\xf6dem   Stevens-Johnsons   exantem/   syndrom, Lyells'],
             ['Musculoskeletal',
              u'H\xf6ft-, handleds- eller   Artralgi, myalgi   kotfrakturer (se'],
             ['Renal', u'Interstitiell nefrit'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'Asteni, tr\xf6tthet och   F\xf6rh\xf6jd']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'LFSU'}