{'_data': [['Uncommon',
            [['Psychiatric', u'S\xf6mnst\xf6rningar'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI',
              u'Diarr\xe9, illam\xe5ende / kr\xe4kningar, uppbl\xe5sthet och gasbildning, f\xf6rstoppning, muntorrhet, buksm\xe4rta och obehag'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer (transaminaser, gamma-GT)'],
             ['Skin', u'Hudutslag/ exantem/ eruption, pruritus'],
             ['Musculoskeletal', u'H\xf6ft-, handleds-eller kotfrakturer (se avsnitt 4.4)'],
             ['General', u'Asteni, tr\xf6tthet och sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighet (inklusive anafylaktiska reaktioner och anafylaktisk chock)'],
             ['Metabolism',
              u'Hyperlipidemi och lipid\xf6kning (triglycerider, kolesterol), viktf\xf6r\xe4ndringar'],
             ['Psychiatric', u'Depression (och alla f\xf6rs\xe4mringar)'],
             ['Nervous system', u'F\xf6r\xe4ndrad smakupplevelse'],
             ['Eye', u'Synrubbning/ dimsyn'],
             ['Hepato', u'F\xf6rh\xf6jt bilirubin'],
             ['Skin', u'Urticaria, angio\xf6dem'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'F\xf6rh\xf6jd kroppstemperatur, perifera \xf6dem']]],
           ['Very rare',
            [['Blood', u'Tromocyto-pe ni, leukopeni, pancytopeni'],
             ['Psychiatric', u'Desorien-terin g (och alla f\xf6rs\xe4mringar)']]],
           ['Unknown',
            [['Metabolism', u'Hyponatremi, hypomagnesemi (se avsnitt 4.4)'],
             ['Psychiatric',
              u'Hallucinationer, f\xf6rvirring (s\xe4rskilt hos predispo-nerade patienter, och som f\xf6rs\xe4mring hos patienter med befintliga symtom av denna typ)'],
             ['Hepato', u'Hepatocellul\xe4r skada, gulsot, leversvikt'],
             ['Skin',
              u'Stevens-Johnsons syndrom, Lyells syndrom, erytema multiforme, ljusk\xe4nslighet'],
             ['Renal', u'Interstitiell nefrit']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 24,
 u'_type': u'MSFU'}