<<<<<<< HEAD
{'_data': [[u'Unknown',
            [['Blood', u'Trombocytopeni,   leukopeni,'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'Hyperlipidemi och   Hyponatremi,   lipid\xf6kning   hypomagnesemi'],
             ['Psychiatric',
              u'S\xf6mnst\xf6rningar   Depression (och alla   Desorientering   Hallucinationer,'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Eye', u'Synrubbningar /'],
             ['GI', u'Diarr\xe9, illam\xe5ende /'],
             ['Hepato', u'F\xf6rh\xf6jda   F\xf6rh\xf6jt bilirubin   Hepatocellul\xe4r'],
             ['Skin',
              u'Hudutslag/   Urticaria, angio\xf6dem   Stevens-Johnsons   exantem/   syndrom, Lyells'],
             ['Musculoskeletal',
              u'H\xf6ft-, handleds- eller   Artralgi, myalgi   kotfrakturer (se'],
             ['Renal', u'Interstitiell nefrit'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'Asteni, tr\xf6tthet och   F\xf6rh\xf6jd']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'LFSU'}
=======
{'_data': [['Uncommon',
            [['Psychiatric', u'S\xf6mnst\xf6rningar'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI',
              u'Diarr\xe9, illam\xe5ende / kr\xe4kningar, uppbl\xe5sthet och gasbildning, f\xf6rstoppning, muntorrhet, buksm\xe4rta och obehag'],
             ['Hepato', u'F\xf6rh\xf6jda gamma-GT)'],
             ['Skin', u'Hudutslag/ exantem/ syndrom, Lyells eruption, pruritus'],
             ['General', u'Asteni, tr\xf6tthet och sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighet (inklusive anafylaktiska reaktioner och anafylaktisk chock)'],
             ['Metabolism',
              u'Hyperlipidemi och Hyponatremi lipid\xf6kning (triglycerider, kolesterol), viktf\xf6r\xe4ndringar'],
             ['Psychiatric', u'Depression (och alla'],
             ['Eye', u'Synrubbningar / dimsyn'],
             ['Hepato', u'F\xf6rh\xf6jt bilirubin  Hepatocellul\xe4r'],
             ['Skin', u'Urticaria, angio\xf6dem'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'F\xf6rh\xf6jd kroppstemperatur, perifera \xf6dem']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni, leukopeni,'],
             ['Psychiatric',
              u'Desorientering Hallucinationer, nerade patienter, befintliga symtom'],
             ['Skin', u'Stevens-Johnsons syndrom, erytema'],
             ['Renal', u'Interstitiell nefrit']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 19,
 u'_type': u'MSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
