{'_data': [['Rare',
            [['Blood', u' St\xf6rningar i trombocyt- och  -stamcellsv\xe4rden.  '],
             ['Immune system', u' Allergier (exklusive angio\xf6dem).  '],
             ['Psychiatric',
              u' Depression NOS, f\xf6rvirring,  -hallucinationer. Centrala och perifera  Tremor NOS, huvudv\xe4rk NOS.  '],
             ['Nervous system', u'-'],
             ['Eye', u' Synrubbningar.  '],
             ['Cardiac', u' \xd6dem.  '],
             ['GI',
              u' Bl\xf6dning NOS, buksm\xe4rta NOS, diarr\xe9  -NOS, illam\xe5ende, kr\xe4kningar. '],
             ['Hepato', u' Onormal leverfunktion, leversvikt,  -levernekros, gulsot. '],
             ['Skin', u'Pruritus, utslag, svettningar, purpura,  angio\xf6dem, urtikaria. '],
             ['General',
              u'och/eller  Yrsel (exklusive vertigo), sjukdomsk\xe4nsla,  symtom vid  feber, sedering, l\xe4kemedelsinteraktion NOS.  administreringsst\xe4llet -'],
             ['Injury',
              u' \xd6verdosering och f\xf6rgiftning.  och -behandlingskomplikationer -']]],
           ['Very rare',
            [['Hepato', u' Levertoxicitet.  '],
             ['General',
              u'och/eller  \xd6verk\xe4nslighetsreaktion (som kr\xe4ver  symtom vid  uts\xe4ttande av behandlingen).  administreringsst\xe4llet -'],
             ['Blood', u' Trombocytopeni, leukopeni, neutropeni,  -hemolytisk anemi. '],
             ['Metabolism', u' Hypoglykemi.  '],
             ['Renal', u' Steril pyuri (grumlig urin) och  -njurbiverkningar. ']]]],
 '_pages': [4, 5],
 u'_rank': 16,
 u'_type': u'DFSU'}