{'_data': [['Rare',
            [['Blood', u'Trombocytrubbningar, st\xf6rningar i  stamcellernas funktion.'],
             ['Immune system', u'\xd6verk\xe4nslighet (exklusive angio\xf6dem).'],
             ['Psychiatric', u'Depression, f\xf6rvirring, hallucinationer.'],
             ['Nervous system', u'Tremor, huvudv\xe4rk.'],
             ['Eye', u'Synst\xf6rningar.'],
             ['Cardiac', u'\xd6dem.'],
             ['GI', u'Bl\xf6dning, buksm\xe4rtor, diarr\xe9, illam\xe5ende,  kr\xe4kningar.'],
             ['Hepato', u'St\xf6rningar av leverfunktionen, leversvikt,  levernekros, gulsot.'],
             ['Skin', u'Kl\xe5da, utslag, svettningar, purpura,  angio\xf6dem, urtikaria.'],
             ['General',
              u'Yrsel (ej svindel), sjukdomsk\xe4nsla, pyrexi,  sedering, l\xe4kemedelsinteraktioner.'],
             ['Injury', u'\xd6verdosering och f\xf6rgiftning']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni, leukopeni, neutropeni  och hemolytisk anemi.'],
             ['Metabolism', u'Hypoglykemi.'],
             ['Hepato', u'Levertoxicitet.'],
             ['Renal', u'Steril pyuri (grumlig urin) och  njurbiverkningar'],
             ['General',
              u'\xd6verk\xe4nslighetsreaktioner (som kr\xe4ver  uts\xe4ttning av l\xe4kemedlet)']]]],
 '_pages': [4, 5],
 u'_rank': 16,
 u'_type': u'TSFU'}