{'_data': [['Common',
            [['Nervous system', u'tr\xf6tthet'],
             ['GI', u'illam\xe5end, kr\xe4kning'],
             ['General', u'om']]],
           ['Uncommon',
            [['Nervous system', u'yrsel, nervositet'],
             ['Respiratory', u'halsbr\xe4nna'],
             ['GI',
              u'diarr\xe9, magsm\xe4rta (inklusive kramp och br\xe4nnande k\xe4nsla), f\xf6rstoppnin g'],
             ['General', u'huvudv\xe4rk, svettning, hypotermi']]],
           ['Rare', [['General', u'exantem']]],
           ['Very rare',
            [['Blood',
              u'hematopoetiska st\xf6rningar (trombocytopeni, leukopeni, sporadiska fall av agranylocytos, pancytopeni)'],
             ['Immune system',
              u'kraftiga \xf6verk\xe4nslighetsreaktioner mot paracetamol (Quinke\u2019s \xf6dem, dyspn\xe9, minskat blodtryck och chock)'],
             ['Respiratory', u'bronkospasm']]],
           ['Unknown', []]],
 '_note': u' ?MSFU',
 '_pages': [2, 3],
 u'_rank': 11,
 u'_type': u'MSFU'}