{'_data': [['Very common',
            [['Nervous system', u'f\xf6rs\xe4mrad koncentrationsf\xf6rm\xe5ga.'],
             ['GI', u'illam\xe5ende'],
             ['Reproductive system', u'sexuell funktionsst\xf6rning']]],
           ['Common',
            [['Metabolism', u'f\xf6rh\xf6jda kolesterolv\xe4rden, minskad aptit'],
             ['Psychiatric',
              u'somnolens, s\xf6mnl\xf6shet, agitation, onormala dr\xf6mmar (inklusive mardr\xf6mmar)'],
             ['Nervous system', u'yrsel, tremor, huvudv\xe4rk.'],
             ['Eye', u'dimsyn'],
             ['Respiratory', u'g\xe4spningar'],
             ['GI', u'f\xf6rstoppning, diarr\xe9, kr\xe4kningar, muntorrhet'],
             ['Skin', u'svettning'],
             ['General', u'asteni, vikt\xf6kning']]],
           ['Uncommon',
            [['Blood',
              u'onormal bl\xf6dning, framf\xf6rallt i huden och slemhinnorna (oftast ekkymos)'],
             ['Psychiatric', u'f\xf6rvirring, hallucinationer'],
             ['Nervous system', u'extrapyramidala st\xf6rningar'],
             ['Eye', u'mydriasis (se avsnitt 4.4)'],
             ['Cardiac', u'sinustakykardi'],
             ['Vascular',
              u'\xf6verg\xe5ende f\xf6rh\xf6jt eller s\xe4nkt blodtryck, postural hypotension. \xd6verg\xe5ende blodtrycksf\xf6rh\xf6jning eller blodtryckss\xe4nkning har rapporterats efter behandling med paroxetin, vanligtvis hos patienter med k\xe4nd hypertoni eller \xe5ngest.'],
             ['Skin', u'hudutslag, kl\xe5da'],
             ['Renal', u'urinretention, urininkontinens']]],
           ['Rare',
            [['Metabolism',
              u'hyponatremi Hyponatremi har rapporterats f\xf6retr\xe4desvis hos \xe4ldre patienter och beror ibland p\xe5 inadekvat ADH-ins\xf6ndring (SIADH).'],
             ['Psychiatric',
              u'maniska reaktioner, \xe5ngest, depersonalisation, panikattacker, akatisi (se avsnitt 4.4).'],
             ['Nervous system', u'kramper, restless legs (RLS)'],
             ['Cardiac', u'bradykardi'],
             ['Hepato', u'f\xf6rh\xf6jning av leverenzymer'],
             ['Reproductive system', u'hyperprolaktinemi/galaktorr\xe9'],
             ['Musculoskeletal',
              u'artralgi, myalgi Epidemiologiska studier som fr\xe4mst har utf\xf6rts p\xe5 patienter 50 \xe5r och \xe4ldre, visar en \xf6kad risk f\xf6r benfraktur hos patienter som behandlas med SSRI och TCA. Mekanismen \xe4r ok\xe4nd.']]],
           ['Very rare',
            [['Blood', u'trombocytopeni'],
             ['Immune system',
              u'allergiska reaktioner (inklusive n\xe4sselutslag, angi\xf6dem)'],
             ['Endocrine', u'inadekvat ADH-ins\xf6ndring (SIADH)'],
             ['Nervous system',
              u'serotonergt syndrom (symtom som agitation, f\xf6rvirring, diafores, hallucinationer, hyperreflexi, myoklonus, skakningar, takykardi och tremor). Det finns rapporter om extrapyramidal st\xf6rning med orofacial dystoni bland annat hos patienter med underliggande r\xf6relsesjukdomar eller under anv\xe4ndning av neuroleptika.'],
             ['Eye', u'akut glaukom'],
             ['GI', u'gastrointestinal bl\xf6dning'],
             ['Hepato',
              u'leverp\xe5verkan (s\xe5som hepatit, ibland f\xf6renad med ikterus och/eller leversvikt). F\xf6rh\xf6jda leverenzymv\xe4rden har rapporterats. Rapporter efter lansering om leverp\xe5verkan (s\xe5som hepatit, ibland f\xf6renad med ikterus och/eller leversvikt) har ocks\xe5 mottagits mycket s\xe4llsynt. Avbrytande av paroxetinbehandling b\xf6r \xf6verv\xe4gas vid kvarst\xe5ende f\xf6rh\xf6jning av leverfunktionsv\xe4rden.'],
             ['Skin',
              u'allvarliga hudbiverkningar (inkluderande erythema multiforme, Stevens-Johnsons syndrom och toxisk epidermal nekrolys), fotosensitivitetsreaktioner'],
             ['Reproductive system', u'priapism'],
             ['General', u'perifert \xf6dem']]],
           ['Unknown',
            [['Psychiatric', u'suicidtankar och suicidalt beteende*'], ['Ear', u'tinnitus.']]]],
 '_pages': [9, 11],
 u'_rank': 38,
 u'_type': u'LSFU'}