{'_data': [['Very common',
            [['Nervous system', u'F\xf6rs\xe4mrad koncentrationsf\xf6rm\xe5ga'],
             ['GI', u'Illam\xe5ende.'],
             ['Reproductive system', u'Sexuell funktionsst\xf6rning.']]],
           ['Common',
            [['Metabolism', u'Minskad aptit, f\xf6rh\xf6jda kolesterolniv\xe5er.'],
             ['Psychiatric',
              u'Somnolens, s\xf6mnl\xf6shet, agitation, onormala dr\xf6mmar (inklusive mardr\xf6mmar).'],
             ['Nervous system', u'Yrsel, tremor, huvudv\xe4rk'],
             ['Eye', u'Dimsyn.'],
             ['Respiratory', u'G\xe4spningar.'],
             ['GI', u'F\xf6rstoppning, diarr\xe9, kr\xe4kningar, muntorrhet.'],
             ['Skin', u'Svettningar.'],
             ['General', u'Asteni, vikt\xf6kning'],
             ['General',
              u'Yrsel, k\xe4nselst\xf6rningar, s\xf6mnst\xf6rningar, \xe5ngest, huvudv\xe4rk.']]],
           ['Uncommon',
            [['Blood',
              u'Onormal bl\xf6dning, framf\xf6r allt i hud och slemhinnor (mestadels ekkymos).'],
             ['Psychiatric', u'Konfusion, hallucinationer.'],
             ['Nervous system', u'Extrapyramidala st\xf6rningar'],
             ['Eye', u'mydriasis (se avsnitt 4.4 Varningar och f\xf6rsiktighet).'],
             ['Cardiac', u'Sinustakykardi.'],
             ['Vascular',
              u'\xd6verg\xe5ende blodtrycksf\xf6rh\xf6jning eller blodtryckss\xe4nkning, postural hypotension. \xd6verg\xe5ende blodtrycksf\xf6rh\xf6jning eller blodtryckss\xe4nkning har rapporterats efter behandling med paroxetin, vanligtvis hos patienter med k\xe4nd hypertoni respektive \xe5ngest.'],
             ['Skin', u'Hudutslag, kl\xe5da'],
             ['Renal', u'Urinretention, urininkontinens'],
             ['General',
              u'Agitation, illam\xe5ende, tremor, konfusion, svettningar, emotionell instabilitet, synst\xf6rningar, palpitationer, diarr\xe9, irritabilitet. Avbrytande av paroxetin (s\xe4rskilt n\xe4r det sker abrupt) medf\xf6r ofta uts\xe4ttningssymtom. Yrsel, k\xe4nselst\xf6rningar (inklusive parestesier och k\xe4nsla av elektriska st\xf6tar och tinnitus), s\xf6mnst\xf6rningar (inklusive s\xf6mnl\xf6shet och intensiva dr\xf6mmar), agitation eller \xe5ngest, illam\xe5ende och eller kr\xe4kningar, tremor, konfusion, svettningar, huvudv\xe4rk, diarr\xe9, palpitationer, emotionell instabilitet, irritabilitet och synst\xf6rningar har rapporterats. I allm\xe4nhet \xe4r dessa symtom milda till moderata och upph\xf6r spontant, men hos vissa patienter kan de vara sv\xe5ra och/eller ha f\xf6rl\xe4ngd duration. D\xe4rf\xf6r rekommenderas ett stegvis uts\xe4ttande n\xe4r behandling med paroxetin ska avslutas, se avsnitt 4.2 Dosering och administreringss\xe4tt och avsnitt 4.4 Varningar och f\xf6rsiktighet. Biverkningar i kliniska studier hos barn och ungdomar F\xf6ljande biverkningar observerades: \xd6kning av suicidrelaterat beteende (inklusive suicidf\xf6rs\xf6k och suicidtankar), sj\xe4lvskadebeteende och \xf6kad fientlighet. Suicidtankar och suicidf\xf6rs\xf6k observerades huvudsakligen i studier hos ungdomar med egentlig depression. \xd6kad fientlighet upptr\xe4dde s\xe4rskilt hos barn med tv\xe5ngssyndrom, s\xe4rskilt hos barn under 12 \xe5r. Ytterligare h\xe4ndelser som f\xf6rekom var: minskad aptit, tremor, svettningar, hyperkinesi, agitation, emotionell labilitet (inklusive gr\xe5t och hum\xf6rsv\xe4ngningar), bl\xf6dningsrelaterade biverkningar, framf\xf6r allt i hud och slemhinnor. H\xe4ndelser som f\xf6rekom efter uts\xe4ttande/nedtrappning av paroxetin var: emotionell labilitet (inklusive gr\xe5t, hum\xf6rsv\xe4ngningar, sj\xe4lvskada, suicidtankar och suicidf\xf6rs\xf6k), nervositet, yrsel, illam\xe5ende och buksm\xe4rta, se avsnitt 4.4 Varningar och f\xf6rsiktighet. Se avsnitt 5.1 f\xf6r mer information om pediatriska kliniska pr\xf6vningar.']]],
           ['Rare',
            [['Metabolism',
              u'Hyponatremi. Hyponatremi har rapporterats f\xf6retr\xe4desvis hos \xe4ldre patienter och beror ibland p\xe5 inadekvat ADH-ins\xf6ndring (SIADH).'],
             ['Psychiatric',
              u'Maniska reaktioner, \xe5ngest, depersonalisation, panikattacker, psykomotorisk rastl\xf6shet/akatisi, (se avsnitt 4.4 Varningar och f\xf6rsiktighet). Dessa symtom kan ocks\xe5 bero p\xe5 den bakomliggande sjukdomen'],
             ['Nervous system', u'Krampanfall, restless legs syndrom (RLS).'],
             ['Cardiac', u'Bradykardi.'],
             ['Hepato', u'F\xf6rh\xf6jning av leverenzymer.'],
             ['Hepato',
              u'Avbrytande av paroxetin b\xf6r \xf6verv\xe4gas vid kvarst\xe5ende f\xf6rh\xf6jning av leverfunktionsv\xe4rden.'],
             ['Reproductive system', u'Hyperprolaktinemi/galaktorr\xe9.'],
             ['Musculoskeletal',
              u'Ledsm\xe4rta, muskelsm\xe4rta Epidemiologiska studier som fr\xe4mst har utf\xf6rts p\xe5 patienter 50 \xe5r och \xe4ldre, visar en \xf6kad risk f\xf6r benfraktur hos patienter som behandlas med SSRI och TCA. Mekanismen \xe4r ok\xe4nd.']]],
           ['Very rare',
            [['Blood', u'Trombocytopeni.'],
             ['Immune system',
              u'Allergiska reaktioner (inklusive urtikaria och angio\xf6dem).'],
             ['Endocrine', u'Inadekvat ADH-ins\xf6ndring (SIADH).'],
             ['Nervous system',
              u'Serotonergt syndrom (symtom kan innefatta agitation, konfusion, kraftig svettning, hallucinationer, hyperreflexi, myoklonus, rysningar, takykardi och tremor). Extrapyramidala st\xf6rningar, inklusive orofacial dystoni har rapporterats, bland annat hos patienter med underliggande r\xf6relsesjukdomar eller under anv\xe4ndning av neuroleptika.'],
             ['Eye', u'Akut glaukom.'],
             ['GI', u'Gastrointestinal bl\xf6dning.'],
             ['Hepato',
              u'Leverp\xe5verkan (s\xe5som hepatit, ibland f\xf6renad med ikterus och/eller leversvikt). F\xf6rh\xf6jda leverenzym har rapporterats. Rapporter efter lansering om leverp\xe5verkan (s\xe5som hepatit, ibland f\xf6renad med ikterus och/eller leversvikt) har ocks\xe5 mottagits mycket'],
             ['Skin',
              u'Allvarliga hudbiverkningar (inklusive erythema multiforme, Stevens-Johnson syndrom och toxisk epidermal nekrolys), fotosensitivitetsreaktioner.'],
             ['Reproductive system', u'Priapism.'],
             ['General',
              u'Perifert \xf6dem. Uts\xe4ttningssymtom vid avbrytande av behandling med paroxetin']]],
           ['Unknown',
            [['Psychiatric',
              u'suicidtankar och suicidalt beteende. Fall av suicidtankar och suicidalt beteende har rapporterats under behandling med paroxetin eller direkt efter avslutad behandling (se avsnitt 4.4).'],
             ['Ear', u'Tinnitus.']]]],
 '_pages': [9, 11],
 u'_rank': 41,
 u'_type': u'LSFU'}