{'_data': [['Common',
            [['GI', u' L\xf6s avf\xf6ring och illam\xe5ende.  '], ['Skin', u' Exantem ']]],
           ['Uncommon',
            [['General',
              u' Generaliserad \xf6verk\xe4nslighetsreaktion med feber och/eller  ledv\xe4rk. '],
             ['Blood', u' Eosinofili '],
             ['Skin', u' Urtikaria ']]],
           ['Rare', [['General', u' Anafylaktisk reaktion  ']]]],
 '_pages': [3, 3],
 u'_rank': 6,
 u'_type': u'DFSU'}