{'_data': [[u'Unknown',
            [['Infections', u'Lunginflammation'],
             ['Blood', u'Neutropeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Desorientering   Drogmissbruk'],
             ['Nervous system',
              u'Dysgeusi   F\xf6rlust av medvetande   Yrsel   Nedsatt medvetandegrad'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Cyanos'],
             ['Vascular', u'Kardiovaskul\xe4r insufficiens'],
             ['Respiratory',
              u'Epistaxis   Obstruktion i \xf6vre luftv\xe4garna   Rinorr\xe9   Sm\xe4rta i svalg och struphuvud'],
             ['GI', u'Kr\xe4kningar   Tarmperforation'],
             ['Skin', u'Pruritus   Hyperhidros'],
             ['Musculoskeletal', u'Artralgi   Muskelryckningar'],
             ['Renal', u'Anuri'],
             ['Reproductive system', u'Vaginal bl\xf6dning'],
             ['General', u'Icke hj\xe4rtrelaterad br\xf6stsm\xe4rta   Asteni'],
             ['Investigations', u'Minskat trombocytantal'],
             ['Injury', u'Fall']]]],
 '_pages': [7, 9],
 u'_rank': 18,
 u'_type': u'LFSU'}