{'_data': [['Common', [['Blood', u'Centrala och perifera nervsystemet  ']]],
           ['Uncommon',
            [['Respiratory',
              u'Hypoxemi Magtarmkanalen Vanlig: Nekrotiserande enterokolit, Intestinal perforering'],
             ['Respiratory',
              u'Gastrointestinal bl\xf6dning Njurar och urinv\xe4gar Vanlig: Oliguri, v\xe4tskeretention, Hematuri'],
             ['Respiratory',
              u'Akut njursvikt Unders\xf6kningar Mycket vanlig: \xd6kat kreatinin i blodet, minskat natrium i blodet se nedan']]]],
 '_pages': [4, 4],
 u'_rank': 4,
 u'_type': u'LSFU'}