{'_data': [[u'Unknown',
            [['Infections',
              u'Bronkit,   \xf6vre   Pneumoni,   Endokardit,   Sepsis   luftv\xe4gsinfektion,   hudinfektion,   extern otit'],
             ['Neoplasms', u'Levertum\xf6r'],
             ['Blood',
              u'Trombocytopeni,   Pancytopeni   Aplastisk   Ren   anemi,   anemi   erytrocyt-'],
             ['Immune system', u'Sarkoidos,   Anafylaxi,   Idiopatisk   Transplan-'],
             ['Endocrine', u'Hypotyroidism,   Diabetes Diabetes-'],
             ['Metabolism', u'Anorexi   Dehydrering'],
             ['Psychiatric',
              u'Depression*,   Aggression,   Sj\xe4lvmords-   Sj\xe4lvmord,   Mani,   \xe5ngest,   hum\xf6rf\xf6r\xe4nd-   tankar,   psykotisk   bipol\xe4ra'],
             ['Nervous system',
              u'Huvudv\xe4rk,   Synkope, migr\xe4n,   Perifer   Koma,   Cerebral   yrsel*,   minnesf\xf6rs\xe4mring,   neuropati   konvulsioner,   ischemi   koncentrations-   svaghet, hypestesi,   ansiktsf\xf6rlam-'],
             ['Eye', u'Dimsyn,   Retinal   Optisk   Synf\xf6rlust   Allvarlig'],
             ['Ear', u'Vertigo,   H\xf6rselneds\xe4tt-   \xf6ronsm\xe4rta   ning'],
             ['Cardiac', u'Takykardi,   perifera   Hj\xe4rtinfarkt,'],
             ['Vascular', u'Blodvallning Hypertension   Cerebral   Perifer'],
             ['Respiratory',
              u'Dyspn\xe9, hosta   Anstr\xe4ngningsut-   V\xe4sande   Interstitiell'],
             ['GI',
              u'Diarr\xe9*,   Kr\xe4kningar,   Gastrointestinal   Peptiskt s\xe5r,   Ischemisk   illam\xe5ende*,   dyspepsi, dysfagi,   bl\xf6dning   pankreatit   kolit'],
             ['Hepato', u'Nedsatt   Leversvikt,   leverfunktion   kolangit,'],
             ['Skin',
              u'Alopeci,   Psoriasis, urtikaria,   Stevens-   dermatit, kl\xe5da,   eksem, utslag,   Johnson   torr hud   \xf6kad svettning,   syndrom,'],
             ['Renal', u'Njurinsuffi-   ciens'],
             ['Reproductive system', u'Impotens'],
             ['General', u'Feber, stelhet*,   Br\xf6stsm\xe4rta,'],
             ['Investigations', u'Viktminskning']]]],
 '_pages': [15, 19],
 u'_rank': 20,
 u'_type': u'LFSU'}