{'_data': [['Very common', [['Vascular', u' flush']]],
           ['Common',
            [['Nervous system', u' huvudv\xe4rk, parestesi'],
             ['GI', u' buksm\xe4rta, diarr\xe9, dyspepsi, illam\xe5ende, kr\xe4kningf\xf6r'],
             ['Skin', u' erytem, kl\xe5da, utslag, urticaria'],
             ['General',
              u' v\xe4rmek\xe4nsla inteMindre vanliga: frossa, sm\xe4rta, perifert \xf6dem']]],
           ['Uncommon',
            [['Immune system', u' \xf6verk\xe4nslighetsreaktion (se nedan)'],
             ['Metabolism', u' gikt'],
             ['Psychiatric', u' insomni'],
             ['Nervous system', u'yrsel'],
             ['Cardiac', u' palpitationer'],
             ['Vascular', u'hypotension'],
             ['Respiratory', u' dyspn\xe9 f\xf6rs\xe4ljning'],
             ['Skin', u'torr hud, makul\xe4ra utslag']]],
           ['Rare',
            [['Infections', u' rinit'],
             ['Immune system', u'angio\xf6dem, typ-1 \xf6verk\xe4nslighet'],
             ['Metabolism', u'nedsatt glukostolerans'],
             ['Psychiatric', u'\xe5ngest'],
             ['Nervous system', u'migr\xe4n, synkope'],
             ['Cardiac', u'f\xf6rmaksflimmer och andra hj\xe4rtarytmier, takykardi'],
             ['Vascular', u'ortostatisk hypotension'],
             ['GI', u'mun\xf6dem, rapningar, peptiskt s\xe5r'],
             ['Skin',
              u' acanthosis nigricans, hyperpigmentering,godk\xe4nt svettningar (nattliga- eller kallsvettningar)'],
             ['General', u'muskelsvaghet'],
             ['General',
              u'asteni, ansikts\xf6dem, generaliserat \xf6dem \xe4rVanliga: stegringar av ALAT och/eller ASAT (>3 X ULN i f\xf6ljd), fasteglukos (se nedan)']]],
           ['Unknown',
            [['Immune system', u'anafylaktisk chock'],
             ['Hepato', u' ikterus'],
             ['Skin',
              u'vesikul\xe4ra eller vesikulobull\xf6sa utslag l\xe4ngreMindre vanliga: myalgi']]]],
 '_pages': [6, 8],
 u'_rank': 27,
 u'_type': u'LSFU2'}