{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'diarr\xe9, buksm\xe4rta, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'hudutslag (inkl. urtikaria, erytemat\xf6st utslag)']]],
           ['Rare',
            [['Nervous system', u'yrsel'],
             ['Cardiac', u'myokardit*, perikardit*'],
             ['GI',
              u'akut pankreatit*, f\xf6rh\xf6jt amylas (blod och/eller urin), gasbesv\xe4r']]],
           ['Very rare',
            [['Blood',
              u'eosinofili (som del av en allergisk reaktion), f\xf6r\xe4ndringar i blodv\xe4rden (anemi, aplastisk anemi, leukopeni (inkl. granulocytopeni och neutropeni), trombocytopeni, agranulocytos, pancytopeni'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktion s\xe5som allergiskt exantem, pankolit'],
             ['Nervous system',
              u'perifer neuropati, benign intrakraniell hypertension hos ungdomar'],
             ['Cardiac', u'perikardexsudat'],
             ['Respiratory',
              u'allergiska och fibrotiska lungreaktioner (inkl. dyspn\xe9, hosta, bronkspasmer, allergisk alveolit, lungeosinofili, interstitiell lungsjukdom, lunginfiltration, pneumonit, pleurit)'],
             ['Hepato',
              u'f\xf6rh\xf6jda leverenzymv\xe4rden, kolestasv\xe4rden och bilirubin, levertoxicitet (inkl. hepatit*, kolestatisk hepatit, cirros, leversvikt)'],
             ['Skin', u'(reversibel) alopeci, Quinckes \xf6dem'],
             ['Musculoskeletal', u'myalgi, artralgi, SLE-liknande reaktioner'],
             ['Renal',
              u'nedsatt njurfunktion (inkl. interstitiell nefrit* (akut och kronisk), nefrotiskt syndrom, renal insufficiens (akut/kronisk), missf\xe4rgad urin'],
             ['Reproductive system', u'oligospermi (reversibel)'],
             ['General', u'l\xe4kemedelsinducerad feber']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 17,
 u'_type': u'MSFU'}