{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Reproductive system', u'Ovariella cystor'],
             ['General',
              u'Milda till sv\xe5ra reaktioner p\xe5 injektionsst\xe4llet (t.ex. sm\xe4rta, erytem, hematom, bl\xe5m\xe4rke, svullnad och/eller irritation p\xe5 injektionsst\xe4llet)']]],
           ['Common',
            [['GI',
              u'Buksm\xe4rtor, utsp\xe4nd buk, bukobehag, illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Reproductive system',
              u'Br\xf6stsm\xe4rtor, b\xe4ckensm\xe4rtor, mild eller m\xe5ttlig OHSS (inklusive \xe5tf\xf6ljande symtomatologi)']]],
           ['Uncommon',
            [['Reproductive system',
              u'sv\xe5r OHSS (inklusive \xe5tf\xf6ljande symtomatologi) (se avsnitt 4.4)']]],
           ['Rare', [['Reproductive system', u'Komplikationer av sv\xe5r OHSS']]],
           ['Very rare',
            [['Immune system',
              u'Milda till sv\xe5ra \xf6verk\xe4nslighetsreaktioner inklusive anafylaktiska reaktioner och chock.'],
             ['Vascular', u'Tromboembolism, oftast i samband med uttalat OHSS'],
             ['Respiratory', u'F\xf6rv\xe4rring av astma']]]],
 '_pages': [5, 6],
 u'_rank': 10,
 u'_type': u'LSFU'}