{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'], ['GI', u'Diarr\xe9, illam\xe5ende']]],
           ['Common',
            [['Cardiac', u'Angina pectoris'],
             ['GI', u'Kr\xe4kningar'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'Myalgi']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner, angio\xf6dem'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotension, flush'],
             ['Respiratory', u'Bronkospasm'],
             ['Skin', u'Urtikaria'],
             ['Injury',
              u'Bl\xf6dning under eller efter operation Dipyridamol kan byggas in i gallstenar (se avsnitt 4.4).']]]],
 '_pages': [3, 3],
 u'_rank': 13,
 u'_type': u'LSFU'}