{'_data': [['Common',
            [['Metabolism', u'Alkalos'],
             ['Metabolism', u'Hypokalemi'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['Metabolism', u'Hyperkalcemi'],
             ['Vascular', u'Hypertension'],
             ['GI', u'Peritonit'],
             ['General', u'\xd6dem'],
             ['General', u'Asteni'],
             ['Investigations', u'Vikt\xf6kning']]],
           ['Uncommon',
            [['Metabolism', u'Hypervolemi'],
             ['Metabolism', u'Anorexi'],
             ['Metabolism', u'Dehydrering'],
             ['Metabolism', u'Hyperglykemi'],
             ['Metabolism', u'Laktatacidos'],
             ['Psychiatric', u'Insomnia'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Hypotension'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Nedsatt funktion av  bukhinnan'],
             ['GI', u'Buksm\xe4rta'],
             ['GI', u'Dyspepsi'],
             ['GI', u'Flatulens'],
             ['GI', u'Illam\xe5ende'],
             ['General', u'Frossbrytningar'],
             ['General', u'Ansikts\xf6dem'],
             ['General', u'Br\xe5ck'],
             ['General', u'Sjukdomsk\xe4nsla'],
<<<<<<< HEAD
             ['General', u'T\xf6rst']]],
=======
             ['General', u'T\xf6rst'],
             ['Investigations', u'PCO \xf6kning']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Blood', u'Eosinofili'],
             ['GI', u'Inkapslande peritoneal  skleros'],
             ['GI', u'Grumligt dialysat'],
             ['Skin', u'Angio\xf6dem'],
             ['Skin', u'Utslag'],
             ['Musculoskeletal', u'Muskuloskeletal sm\xe4rta'],
             ['General', u'Pyrexi']]]],
 '_pages': [5, 6],
<<<<<<< HEAD
 u'_rank': 37,
=======
 u'_rank': 38,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}