{'_data': [['Rare',
            [['Blood',
              u'Anemi, icke-hemolys och benm\xe4rgsdepression: benm\xe4rgsdepression, trombocytopeni'],
             ['Cardiac', u'\xd6dem'],
             ['GI',
              u'Exokrina pankreastillst\xe5nd - akut och kronisk pankreatit: Bl\xf6dning NOS*, buksm\xe4rta NOS, diarr\xe9 NOS, illam\xe5ende, kr\xe4kningar, leversvikt, levernekros, gulsot.'],
             ['Skin',
              u'Allergiska tillst\xe5nd - urtikaria, anafylaktisk reaktioner och f\xf6do\xe4mnesallergi, l\xe4kemedelsallergi: Pruritus, utslag, svettningar, purpura, angio\xf6dem, urtikaria.'],
             ['Renal',
              u'Nefropati \u2013 nefropati och tubul\xe4ra st\xf6rningar * NOS = "not otherwise specified", utan n\xe4rmare specifikation. Paracetamol \xe4r v\xe4lbepr\xf6vat och rapporter om biverkningar \xe4r s\xe4llsynta. Dessa \xe4r generellt f\xf6rknippade']]]],
 '_pages': [5, 5],
 u'_rank': 5,
 u'_type': u'LSFU'}