{'_data': [['Common',
            [['GI', u'Diarr\xe9, illam\xe5ende, kr\xe4kning'],
             ['Skin', u'Utslag inklusive makulopapul \xe4rt']]],
           ['Uncommon',
            [['Infections', u'Candida superinfektion'],
             ['Blood', u'Leukopeni, neutropeni, trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'Huvudv\xe4rk, s\xf6mnl\xf6shet'],
             ['Vascular', u'hypotoni tromboflebit'],
             ['GI', u'F\xf6rstoppning, dyspepsi, gulsot, stomatit'],
             ['Hepato',
              u'f\xf6rh\xf6jt alaninamino-transfe ras, f\xf6rh\xf6jt aspartatamino-trans feras'],
             ['Skin', u'n\xe4sselfeber, kl\xe5da'],
             ['Renal', u'f\xf6rh\xf6jt blodkreatinin'],
             ['General', u'Feber, reaktion vid injektionsst\xe4llet']]],
           ['Rare',
            [['Blood',
              u'Anemi, purpura, epistaxis, f\xf6rl\xe4ngd bl\xf6dningstid eosinofili, hemolytisk anemi'],
             ['Immune system', u'Anafylaktisk/ anafylaktoid reaktion (inklusive chock)'],
             ['Vascular', u', flebit,  blodvallning'],
             ['GI', u'pseudomembran\xf6s kolit, buksm\xe4rta'],
             ['Hepato',
              u'f\xf6rh\xf6jt blodbilirubin, f\xf6rh\xf6jt alkalinfosfatas i blodet, f\xf6rh\xf6jt gammaglutamyl-tr ansferas, Hepatit'],
             ['Skin', u'Bull\xf6s dermatit, erythema multiforme, exantem,'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Renal', u'Tubuloi nefrit, njursvikt'],
             ['General', u'frossa']]],
           ['Very rare',
            [['Blood',
              u'Agranulocytos, pancytopeni, f\xf6rl\xe4ngd aktiverad partiell tromboplastintid, f\xf6rl\xe4ngd protrombintid, positivt direkt Coombs test, trombocytemi'],
             ['Metabolism',
              u's\xe4nkt blodglukos, s\xe4nkt blodalbumin, s\xe4nkt totalt blodprotein, hypokalemi'],
             ['Skin', u'Stevens-Johnsons syndrom, toxisk epidermal nekrolys'],
             ['Renal', u'nterstitiell']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 25,
 u'_type': u'MSFU'}