{'_data': [['Very common',
            [['Blood', u'Agranulocytos, positivt direkt'],
             ['Metabolism', u'Hypoalbuminemi, hypoglycemi,'],
             ['Skin', u'Stevens-Johnsons syndrom, toxisk'],
             ['Renal', u'Ureastegring']]],
           ['Common',
            [['GI', u'Diarr\xe9, illam\xe5ende, kr\xe4kning.'],
             ['Skin', u'Utslag inklusive makulopapul\xf6st  utslag.']]],
           ['Uncommon',
            [['Infections', u'Candidasuperinfektion.'],
             ['Blood', u'Leukopeni, neutropeni,  trombocytopeni.'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion.'],
             ['Nervous system', u'Huvudv\xe4rk, s\xf6mnl\xf6shet.'],
             ['Vascular', u'Hypotension, flebit, tromboflebit.'],
             ['GI', u'F\xf6rstoppning, dyspepsi, gulsot,  stomatit.'],
             ['Hepato',
              u'F\xf6rh\xf6jda niv\xe5er av  alaninaminotransferas och aspartataminotransferas.'],
             ['Skin', u'Pruritus, urtikaria, erytem.'],
             ['Renal', u'F\xf6rh\xf6jda niv\xe5er av serumkreatinin'],
             ['General', u'Feber, reaktion vid injektionsst\xe4llet']]],
           ['Rare',
            [['Blood',
              u'Anemi, tecken p\xe5 bl\xf6dning  (inklusive purpura, epistaxis, f\xf6rl\xe4ngd bl\xf6dningstid), eosinofili, hemolytisk anemi.'],
             ['Blood',
              u'Coombs test, pancytopeni, f\xf6rl\xe4ngd  partiell tromboplastintid, f\xf6rl\xe4ngd protrombintid, trombocytos.'],
             ['Immune system', u'Anafylaktisk/anafylaktoid reaktion  (inklusive chock).'],
             ['Metabolism', u'hypoproteinemi, hypokalemi.'],
             ['Nervous system', u'Svaghet i musklerna, hallucination,  kramper.'],
             ['Vascular', u'Rodnad.'],
             ['GI', u'Magsm\xe4rtor, pseudomembran\xf6s  kolit, muntorrhet.'],
             ['Hepato',
              u'F\xf6rh\xf6jda niv\xe5er av bilirubin,  f\xf6rh\xf6jda niv\xe5er av alkaliskt fosfatas, f\xf6rh\xf6jda niv\xe5er av gamma- glutamyltransferas. Hepatit.'],
             ['Skin',
              u'Bull\xf6s dermatit, erythema  multiforme, \xf6kad svettning, eksem, exantem'],
             ['Skin', u'epidermal nekrolys'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['Renal', u'Interstitiell nefrit, njursvikt'],
             ['Renal', u''],
             ['General', u'Stelhet, tr\xf6tthet, \xf6dem']]]],
 '_pages': [5, 6],
 u'_rank': 29,
 u'_type': u'TSFU'}