{'_data': [['Very common',
            [['Neoplasms', u'Neutropeni, leukopeni, lymfopeni, anemi,'],
             ['Respiratory', u'Illam\xe5ende, kr\xe4kningar'],
             ['Hepato', u'Hudmissf\xe4rgning, alopeci'],
             ['Musculoskeletal', u'Urinmissf\xe4rgning'],
             ['Reproductive system', u'Asteni']]],
           ['Common',
            [['Infections',
              u'Neutropen infektion, luftv\xe4gsinfektion, infektion  Bronkit, candidainfektion, cellulit, herpes zoster,'],
             ['Neoplasms', u'trombocytopeni'],
             ['Blood', u'Febril neutropeni, blodp\xe5verkan'],
             ['Immune system', u'Anorexi, hypofosfatemi'],
             ['Nervous system', u'somnolens'],
             ['Nervous system', u'Konjunktivit'],
             ['Cardiac', u'hj\xe4rtinsufficiens, v\xe4nstergrenblock, takykardi'],
             ['Cardiac', u'Blekhet, k\xe4rlmissf\xe4rgning, hypotoni'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['Respiratory', u''],
             ['GI',
              u'Stomatit, diarr\xe9, f\xf6rstoppning, buksm\xe4rta, muntorrhet, dyspepsi,'],
             ['Hepato', u''],
             ['Skin', u'Erytem, nagelp\xe5verkan, pruritus'],
             ['Skin', u'V\xe4rk i skelettet'],
             ['Musculoskeletal', u''],
             ['Renal', u'Proteinuri, hematuri'],
             ['General', u''],
             ['General',
              u'Tr\xf6tthet, slemhinneinflammation, pyrexi, br\xf6stsm\xe4rta, \xf6dem'],
             ['General',
              u'niv\xe5er av aspartataminotransferas, f\xf6rh\xf6jda niv\xe5er av  alkalisk fosfatas i blodet, \xf6kat kreatinin i blodet']]],
           ['Uncommon',
            [['Infections',
              u'meningit, nagelinfektion, oral svampinfektion, oral  herpes, pneumoni, salmonella-gastroenterit, septisk  chock'],
             ['Neoplasms', u'Neoplasmautveckling'],
             ['Blood',
              u'Benm\xe4rgssvikt, eosinofili  Tabell 3 Rapporterade biverkningar i samband med'],
             ['Immune system', u'\xd6verk\xe4nslighet mot l\xe4kemedlet'],
             ['Metabolism', u'Hyperurikemi, hypokalcemi, hyponatremi'],
             ['Psychiatric',
              u'\xc5ngest, s\xf6mnl\xf6shet, s\xf6mnst\xf6rningar  F\xf6r\xe4ndrad smakupplevelse, parestesier, huvudv\xe4rk,'],
             ['Nervous system', u'Yrsel, letargi'],
             ['Eye', u'Torra \xf6gon, keratit'],
             ['Ear', u'Svindel  V\xe4nsterkammardysfunktion, hj\xe4rtp\xe5verkan, kronisk'],
             ['Cardiac', u'Arytmi'],
             ['Vascular', u'K\xe4rlproblem'],
             ['Respiratory', u'Pleural effusion, pneumonit, rinorr\xe9'],
             ['GI', u'Esofagit, orala parestesier, rektalbl\xf6dning'],
             ['Hepato', u'Hyperbilirubinemi'],
             ['Skin', u'Nattliga svettningar, petekier, fl\xe4ckiga hudutslag'],
             ['Musculoskeletal',
              u'muskuloskeletal br\xf6stsm\xe4rta, muskuloskeletal stelhet, nacksm\xe4rta, sm\xe4rta i extremiteter'],
             ['Renal', u'Oliguri  Tabell 3 Rapporterade biverkningar i samband med'],
             ['Reproductive system', u'Spontan penil erektion'],
             ['General',
              u'Frossa, k\xf6ldk\xe4nsla vid injektionsst\xe4llet, lokal reaktion  F\xf6rh\xf6jda niv\xe5er av alaninaminotransferas, f\xf6rh\xf6jda'],
             ['Investigations',
              u'f\xf6rh\xf6jda niv\xe5er av urea i blodet, f\xf6rh\xf6jda niv\xe5er av  gamma-glutamyltransferas, \xf6kat antal neutrofiler,  viktminskning']]]],
 '_pages': [6, 8],
 u'_rank': 40,
 u'_type': u'TSFU'}