{'_data': [['Unknown',
            [['Blood',
              u'Hemolytisk anemi Leukocytos Lymfadenit Ingen k\xe4nd Lymfadenopati frekvens Trombocytopeni **'],
             ['Immune system',
              u'Anafylaktoida reaktioner Angioneurotisk \xf6dem Ingen k\xe4nd Serumsjuka frekvens'],
             ['Nervous system',
              u'Feberkramp Guillain-Barr\xe9s syndrom Huvudv\xe4rk Ingen k\xe4nd Parestesier frekvens Radikul\xe4r neuropati'],
             ['GI', u'Illam\xe5ende  '],
             ['Skin', u'Utslag  '],
             ['Musculoskeletal', u'Artralgi Artrit Ingen k\xe4nd Myalgi frekvens'],
             ['Local',
              u'\u2022sm\xe4rta Mycket vanliga \u2022\xf6mhet \u2022svullnad \u2022v\xe4rmek\xe4nsla'],
             ['Investigations',
              u'\xd6kat C-reaktivt protein frekvens hos patienter som haft andra hematologiska sjukdomar']]]],
 '_pages': [4, 6],
 u'_rank': 8,
 u'_type': u'LSFU'}