{'_data': [['Very common', [['Vascular', u'Blodvallningar']]],
           ['Common',
            [['Metabolism', u'\xd6kad aptit'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Skin', u'Hyperhidros, nattsvettning, kallsvettning'],
             ['Musculoskeletal', u'Ryggont'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General', u'Tr\xf6tthet, asteni, feber, lokala biverkningar (se tabell 2)'],
             ['Local',
              u'rapporterade biverkningar var reaktioner, svullnad, skada och bl\xf6dning vid injektionsst\xe4llet (tabell 2).'],
             ['General',
              u'Vanliga Sm\xe4rta vid injektionsst\xe4llet. 8,1 Irritation vid injektionsst\xe4llet. 4,4 Obehag vid injektionsst\xe4llet. 1,9 Erytem vid injektionsst\xe4llet. 1,3 Bl\xe5m\xe4rke vid injektionsst\xe4llet. 1,3']]],
           ['Uncommon',
            [['Metabolism', u'Anorexi, hyperkolesterolemi, hyperlipidemi'],
             ['Psychiatric',
              u'S\xf6mnst\xf6rningar, insomnia, minskad libido, hum\xf6rf\xf6r\xe4ndringar och depression*'],
             ['Nervous system', u'Somnolens'],
             ['Ear', u'Vertigo'],
             ['GI', u'Buksm\xe4rta i nedre delen, diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Hepato', u'Hyperbilirubinemi'],
             ['Skin', u'Periorbitalt \xf6dem, urtikaria, kl\xe5da,'],
             ['Musculoskeletal', u'Artralgi, muskelkramper, sm\xe4rta i extremiteterna'],
             ['Renal', u'Urinretention, urininkontinens, pollakisuri'],
             ['Reproductive system',
              u'Svullna br\xf6st, \xf6mhet i br\xf6sten, of\xf6rm\xe5ga till ejakulation'],
             ['General',
              u'Svaghet, k\xe4nsla av f\xf6r\xe4ndring i kroppstemperatur, nervositet'],
             ['Investigations',
              u'F\xf6rh\xf6jt ASAT, f\xf6rh\xf6jt ALAT, f\xf6rh\xf6jt blodbilirubin, f\xf6rh\xf6jt gammaglutamyltransferas'],
             ['General',
              u'Mindre vanliga Reaktion vid injektionsst\xe4llet. 0,6 Svullnad vid injektionsst\xe4llet. 0,6 Skada vid injektionsst\xe4llet. 0,6 Bl\xf6dning vid injektionsst\xe4llet. 0,6']]],
           ['Unknown',
            [['Local',
              u'produkter som administreras via intramuskul\xe4r injektion. Sm\xe4rta, irritation, obehag och bl\xe5m\xe4rken vid administreringsst\xe4llet och erytem var de som oftast rapporterades. Mindre']]]],
 '_pages': [5, 7],
 u'_rank': 23,
 u'_type': u'LSFU'}