{'_data': [['Common',
            [['Metabolism', u'Hyperurikemi'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u'Intrakraniell  bl\xf6dning  , yrsel, huvudv\xe4rk'],
             ['Eye', u'\xd6gonbl\xf6dning'],
             ['Ear', u'\xd6ronbl\xf6dning,   vertigo'],
             ['Respiratory', u'Dyspn\xe9   , epistaxis'],
             ['GI', u'Gastrointestinal bl\xf6dning'],
             ['Skin', u'Subkutan bl\xf6dning eller hudbl\xf6dning  , bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Hemartros'],
             ['Renal', u'Urinv\xe4gsbl\xf6dning'],
             ['Investigations', u'F\xf6rh\xf6jt Bl\xf6dning p\xe5 ingreppsst\xe4lle'],
             ['Immune system',
              u'\xd6verk\xe4nslighet inklusive angio\xf6dem begrepp som beskrivs nedan: peptiskt s\xe5r Hematuri, blod i urinen, urinv\xe4gsbl\xf6dning Beskrivning av utvalda biverkningar Bl\xf6dning PLATO totalt st\xf6rre 11,6 PLATO st\xf6rre fatala/livshotande Icke-CABG-relaterad PLATO st\xf6rre Icke-procedurrelaterad PLATO PLATO totalt st\xf6rre + mindre Icke-procedurrelaterad PLATO st\xf6rre + mindre 5,9 4,3 <0,000 TIMI-definierad st\xf6rre 7,9 TIMI-definierad st\xf6rre + mindre Definitioner av bl\xf6dningskategorier: blodtrycksh\xf6jande medel eller kirurgi. funktionsneds\xe4ttning. klopidogrel (se avsnitt 4.4). avsnitt 4.4). totala antalet fatala bl\xf6dningar. Dyspn\xe9 och/eller KOL i anamnesen (se avsnitt p\xe5verkar inte lungfunktionstester.'],
             ['Investigations', u'klopidogrel.']]],
           ['Uncommon',
            [['Eye', u'(intraokul\xe4r, konjunktival, retinal)'],
             ['Respiratory', u'Hemoptys'],
             ['GI',
              u'Hematemes, gastrointestinal hemorrojdbl\xf6dning, gastrit, oral bl\xf6dning (inklusive tandk\xf6ttsbl\xf6dning), kr\xe4kningar, diarr\xe9, buksm\xe4rta, illam\xe5ende, dyspepsi'],
             ['Skin', u'Hudutslag, pruritus'],
             ['Reproductive system', u'Vaginal bl\xf6dning (inklusive metrorragi)'],
             ['Investigations', u'Bl\xf6dning efter ingrepp, bl\xf6dning'],
             ['Immune system',
              u'Hyperurikemi, f\xf6rh\xf6jt urinsyrav\xe4rde i blodet 5,8 -4,5 -st\xf6rre 3,1 -11,4 -4.4). ']]],
           ['Rare',
            [['Nervous system', u'Parestesier'],
             ['GI', u'Retroperitoneal bl\xf6dning,'],
             ['Investigations', u'blodkreatinin S\xe5rbl\xf6dning, traumatisk bl\xf6dning'],
             ['Immune system',
              u'11,2 0,4336 5,8 0,6988 3,8 0,0264 2,3 0,0058 7,7 ,5669 10,9 0,3272']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 11],
 u'_rank': 24,
 u'_type': u'MSFU'}