{'_data': [['Very common',
            [['Reproductive system', u'Bl\xf6dning ej relaterad till menstruation*'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende, sm\xe4rta i nedre delen av buken'],
             ['General',
              u'Tr\xf6tthet Bl\xf6dningsm\xf6nstret kan tillf\xe4lligt rubbas, men de flesta kvinnor f\xe5r sin n\xe4sta menstruation inom 7 dagar fr\xe5n f\xf6rv\xe4ntad tidpunkt. Om n\xe4sta menstruation \xe4r mer \xe4n 5 dagar f\xf6rsenad b\xf6r graviditet uteslutas. Task Force on post-ovulatory Methods of Fertility Regulation. Randomised controlled trial of levonorgestrel versus Yuzpe regimen of combined oral contraceptives for emergency contraception. Lancet, 1998;352:428-433 (n=977; data f\xf6r intag av tv\xe5 tabletter 0,75 mg levonorgestrel med ett 12-timmars intervall) Hertzen et al. Low dose mifepristone and two regimens of levonorgestrel for emergency contraception: a WHO multicentre randomised trial. Lancet, 2002; 360:1803-1810 (n=1359; data f\xf6r Postinor 1,5 mg tablett intaget som en singeldos p\xe5 1,5 mg) n=1011 utav 1359 n=1334 utav 1359 F\xf6ljande biverkningar har dessutom rapporterats efter marknadsf\xf6ring']]],
           ['Common',
            [['Reproductive system',
              u'Br\xf6stsp\xe4nningar F\xf6rsening av menstruation i mer \xe4n 7 dagar , oregelbunden bl\xf6dning samt st\xe4nkbl\xf6dning'],
             ['Nervous system', u'Yrsel'],
             ['GI', u'Diarr\xe9, kr\xe4kningar']]],
           ['Very rare', [['Skin', u'utslag, urtikaria, pruritus, ansikts\xf6dem']]]],
 '_pages': [3, 3],
 u'_rank': 8,
 u'_type': u'LSFU'}