{'_data': [['Common',
            [['GI', u'Gastrointestinal bl\xf6dning  '],
             ['GI', u'Buksm\xe4rta Vanliga  '],
             ['GI', u'Diarr\xe9 Vanliga  '],
             ['GI', u'Dyspepsi  '],
             ['GI', u'Illam\xe5ende Vanliga  '],
             ['Renal', u'Urogenital bl\xf6dning  ']]],
           ['Uncommon',
            [['GI', u'Rektalbl\xf6dning  '],
             ['GI', u'Hemorrojdbl\xf6dning  '],
             ['GI', u'Mags\xe5r  '],
             ['GI', u'Gastroesofagit  '],
             ['Renal', u'Hematuri  ']]],
           ['Rare', [['Musculoskeletal', u'Hemartros S\xe4llsynta  ']]],
           ['Unknown',
            [['Blood',
              u'Minskat hemoglobin Mindre vanliga Mindre vanliga Trombocytopeni Mindre vanliga Mindre vanliga Minskat hematokrit S\xe4llsynta S\xe4llsynta'],
             ['Immune system',
              u'\xd6verk\xe4nslighet Mindre vanliga Mindre vanliga Utslag Mindre vanliga Mindre vanliga Pruritus Mindre vanliga Mindre vanliga Anafylaktisk reaktion S\xe4llsynta S\xe4llsynta Angio\xf6dem S\xe4llsynta S\xe4llsynta Urticaria S\xe4llsynta S\xe4llsynta Bronkialspasm Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Nervous system', u'Intrakraniell bl\xf6dning Mindre vanliga Mindre vanliga'],
             ['Vascular',
              u'Hematom Mindre vanliga Mindre vanliga Bl\xf6dning Mindre vanliga Mindre vanliga'],
             ['Respiratory', u'Hemoptys Mindre vanliga Mindre vanliga'],
             ['Hepato',
              u'leverfunktionstest F\xf6rh\xf6jt ALAT Mindre vanliga Mindre vanliga F\xf6rh\xf6jt ASAT Mindre vanliga Mindre vanliga F\xf6rh\xf6jda leverenzymer S\xe4llsynta S\xe4llsynta Hyperbilirubinemi S\xe4llsynta S\xe4llsynta'],
             ['Skin', u'Hudbl\xf6dning Mindre vanliga Mindre vanliga'],
             ['General',
              u'injektionsst\xe4llet Bl\xf6dning vid kateter S\xe4llsynta S\xe4llsynta'],
             ['Injury',
              u'Traumatisk bl\xf6dning Mindre vanliga Mindre vanliga Bl\xf6dning vid incisionsst\xe4lle Mindre vanliga Mindre vanliga Bl\xf6dning'],
             ['GI',
              u'Fatal bl\xf6dning 23 (0,19 %) 28 (0,23 %) 39 (0,33 %) Mindre bl\xf6dning 1 566 (13,16 %) 1 787 (14,85%) 1 931 (16,37%) Bl\xf6dning av n\xe5got slag 1 754 (14,74 %) 1 993 (16,56 %) 2 166 (18,37 %) St\xf6rre bl\xf6dning definierades till att uppfylla ett eller fler av f\xf6ljande kriterier: Bl\xf6dning associerat med en minskning av hemoglobin p\xe5 minst 20 g/l eller som medf\xf6r ett transfusionsbehov p\xe5 minst 2 enheter blod eller packade celler. Symtomatisk bl\xf6dning i kritiska omr\xe5den eller organ: intraokul\xe4r, intrakraniell, intraspinal eller intramuskul\xe4r med kompartmentsyndrom, retroperitoneal bl\xf6dning, intraartikul\xe4r bl\xf6dning eller perikardiell bl\xf6dning. St\xf6rre bl\xf6dningar klassificerades som livshotande om de uppfyllde ett eller flera av f\xf6ljande kriterier']]]],
 '_pages': [11, 14],
 u'_rank': 22,
 u'_type': u'LSFU'}