{'_data': [['Very common',
            [['Nervous system', u'yrsel, dyskinesier, d\xe5sighet'],
             ['Vascular', u'hypotension'],
             ['GI', u'illam\xe5ende'],
             ['GI', u'illam\xe5ende']]],
           ['Common',
            [['Psychiatric',
              u'onormala dr\xf6mmar, beteendest\xf6rningar p.g.a. st\xf6rd impulskontroll och tv\xe5ngshandlingar; konfusion, hallucinationer, s\xf6mnl\xf6shet, rastl\xf6shet Organsystem Biverkning'],
             ['Nervous system', u'amnesi, huvudv\xe4rk'],
             ['Eye', u'synst\xf6rning inklusive dimsyn och nedsatt synsk\xe4rpa'],
             ['GI', u'f\xf6rstoppning, kr\xe4kning'],
             ['Skin', u'utmattning, perifera svullnader'],
             ['Investigations', u'viktnedg\xe5ng'],
             ['Psychiatric', u'onormala dr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'yrsel, huvudv\xe4rk, d\xe5sighet'],
             ['GI', u'f\xf6rstoppning, kr\xe4kning'],
             ['Skin', u'utmattning']]],
           ['Uncommon',
            [['Infections', u'pneumoni'],
             ['Psychiatric',
              u'k\xf6pberoende, vanf\xf6rest\xe4llningar (delusion), hypersexualitet, st\xf6rd libido, paranoia, spelberoende Ok\xe4nda hets\xe4tning, hyperfagi'],
             ['Nervous system', u'hyperkinesi, pl\xf6tslig insomning, svimning (synkope)'],
             ['Respiratory', u'andn\xf6d'],
             ['Skin',
              u'\xf6verk\xe4nslighet, kl\xe5da, utslag Allm\xe4nna symptom och symptom vid administrationsst\xe4llet'],
             ['Investigations',
              u'vikt\xf6kning Andra indikationer, de vanligaste biverkningarna De vanligaste (\u2265 5 %) rapporterade biverkningarna hos pramipexolbehandlade patienter med andra indikationer var illam\xe5ende, huvudv\xe4rk, yrsel och utmattning. Illam\xe5ende och utmattning rapporterades oftare av kvinnliga patienter som behandlats med pramipexol (20,8 % respektive 10,5 %) \xe4n av manliga patienter (6,7 % respektive 7,3 %). Tabell 2: Andra indikationer Organsystem Biverkning'],
             ['Psychiatric',
              u'konfusion, hallucinationer, st\xf6rd libido, rastl\xf6shet Ok\xe4nda beteendesymtom som tecken p\xe5 st\xf6rd impulskontroll och tv\xe5ngshandlingar, bl.a. hets\xe4tning, k\xf6pberoende, hypersexualitet och spelberoende; vanf\xf6rest\xe4llningar (delusioner), hyperfagi, paranoia'],
             ['Nervous system',
              u'pl\xf6tsligt insomnande, synkope Ok\xe4nda amnesi, dyskinesier, hyperkinesi'],
             ['Eye', u'synst\xf6rning inklusive dimsyn och nedsatt synsk\xe4rpa'],
             ['Vascular', u'hypotension'],
             ['Respiratory', u'andn\xf6d'],
             ['Skin',
              u'\xf6verk\xe4nslighet, kl\xe5da, utslag Allm\xe4nna symptom och symptom vid administrationsst\xe4llet Organsystem Biverkning'],
             ['Skin', u'perifera svullnader'],
             ['Investigations',
              u'viktnedg\xe5ng, vikt\xf6kning Pramipexol associeras med d\xe5sighet (8,6 %) och \xe4r mer s\xe4llan associerat med kraftig d\xe5sighet dagtid och episoder av pl\xf6tslig insomning (0,1 %). Se ocks\xe5 avsnitt 4.4. Pramipexol kan associeras med biverkningar som g\xe4ller libido (\xf6kad libido [0,1 %] eller minskad libido [0,4 %]). St\xf6rd impulskontroll och tv\xe5ngshandlingar Patienter som behandlats med dopaminagonister f\xf6r Parkinsons sjukdom, inklusive pramipexol, s\xe4rskilt med h\xf6ga doser, har rapporterats uppvisa tecken p\xe5 spelberoende, \xf6kad libido och \xf6kad sexualitet, vilket vanligen \xe4r reversibelt n\xe4r dosen reducerats eller behandlingen avslutats. Se ocks\xe5 avsnitt 4.4. I en retrospektiv tv\xe4rsnittsunders\xf6kning och fallkontrollstudie som omfattade 3 090 patienter med Parkinsons sjukdom hade 13,6 % av alla patienter som fick dopaminerg eller icke-dopaminerg behandling symtom p\xe5 en st\xf6rd impulskontroll under de sex senaste m\xe5naderna. De manifestationer som d\xe5 iakttogs omfattar spelberoende, k\xf6pberoende, bulimi och kompulsivt sexuellt beteende (hypersexualitet). Eventuella sj\xe4lvst\xe4ndiga riskfaktorer f\xf6r st\xf6rd impulskontroll omfattade behandling med dopaminerga l\xe4kemedel samt h\xf6gre doser av dessa l\xe4kemedel, yngre \xe5lder (\u2264 65 \xe5r), ensamst\xe5ende och enligt egenuppgift spelberoende i sl\xe4kten.']]],
           ['Unknown', [['Infections', u'pneumoni']]]],
 '_pages': [5, 7],
 u'_rank': 29,
 u'_type': u'LSFU'}