{'_data': [['Very common',
            [['Nervous system', u'Yrsel, dyskinesi, somnolens'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Psychiatric',
              u'Onormala dr\xf6mmar, beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende, f\xf6rvirring, hallucinationer, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'Synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Vascular', u'Hypotension Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['GI', u'F\xf6rstoppning, kr\xe4kningar'],
             ['Skin', u'Tr\xf6tthet, perifert \xf6dem'],
             ['Investigations', u'Viktminskning inklusive minskad aptit'],
             ['Psychiatric', u'Onormala dr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk, somnolens'],
             ['GI', u'F\xf6rstoppning, kr\xe4kningar'],
             ['Skin', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Infections', u'Pneumoni'],
             ['Psychiatric',
              u'Hets\xe4tning, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, vanf\xf6rest\xe4llningar, hyperfagi, hypersexualitet, st\xf6rningar av libido, paranoia, patologiskt spelberoende, rastl\xf6shet'],
             ['Nervous system',
              u'Minnesf\xf6rlust, hyperkinesi, episoder av pl\xf6tsligt insomnande, synkope'],
             ['Vascular', u'Dyspn\xe9, hicka'],
             ['Skin',
              u'\xd6verk\xe4nslighet, pruritus, hudutslag Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Investigations',
              u'Vikt\xf6kning Andra indikationer, de vanligaste biverkningarna De vanligaste biverkningar (\u2265 5 %) som rapporterades hos patienter med andra indikationer vid behandling med pramipexol var illam\xe5ende, huvudv\xe4rk, yrsel och tr\xf6tthet. Illam\xe5ende och tr\xf6tthet f\xf6rekom oftare hos kvinnliga patienter som behandlades med pramipexol (20,8 % respektive 10,5 %) j\xe4mf\xf6rt med manliga (6,7 % respektive 7,3 %). Tabell 2: Andra indikationer Organsystem Biverkan'],
             ['Infections', u'Pneumoni'],
             ['Psychiatric',
              u'Beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende s\xe5som hets\xe4tning, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hypersexualitet och patologiskt spelberoende; f\xf6rvirring, vanf\xf6rest\xe4llningar, hallucinationer, hyperfagi, st\xf6rningar av libido, paranoia, rastl\xf6shet'],
             ['Nervous system',
              u'Minnesf\xf6rlust, dyskinesi, hyperkinesi, episoder av pl\xf6tsligt insomnande, synkope'],
             ['Eye', u'Synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Vascular', u'Hypotension Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Dyspn\xe9, hicka'],
             ['Skin',
              u'\xd6verk\xe4nslighet, pruritus, hudutslag Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Skin', u'Perifert \xf6dem'],
             ['Investigations',
              u'Viktminskning inklusive minskad aptit, vikt\xf6kning Somnolens Pramipexol \xe4r vanligen associerat med somnolens och har \xe4ven associerats med en mindre vanlig biverkan, \xf6verdriven somnolens under dagtid och episoder av pl\xf6tsligt insomnande (se \xe4ven avsnitt 4.4). St\xf6rningar av libido Pramipexol kan i mindre vanliga fall ha samband med st\xf6rningar av libido (\xf6kning eller minskning). St\xf6rd impulskontroll Patologiskt spelberoende, \xf6kad libido, hypersexualitet, tv\xe5ngsm\xe4ssigt spenderande av pengar och tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hets\xe4tning och tv\xe5ngsm\xe4ssigt \xe4tande kan f\xf6rekomma hos patienter som behandlas med dopaminagonister s\xe5som pramipexol (se \xe4ven avsnitt 4.4). I en retrospektiv tv\xe4rsnittsunders\xf6kning (cross sectional) och fall-kontroll-studie med 3 090 patienter med Parkinsons sjukdom, hade 13,6 % av alla patienter som fick dopaminerg eller ickedopaminerg behandling symtom p\xe5 en st\xf6rd impulskontroll under de senaste sex m\xe5naderna. Symtomen som observerats inkluderar spelberoende, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hets\xe4tning, och tv\xe5ngsm\xe4ssigt sexuellt beteende (hypersexualitet). T\xe4nkbara oberoende riskfaktorer f\xf6r st\xf6rningar i impulskontrollen omfattade dopaminerg behandling och h\xf6gre doser av dopaminerg behandling, \xe5lder (\u2264 65 \xe5r), ensamst\xe5ende och enligt egen uppgift spelberoende i sl\xe4kten.']]]],
 '_pages': [5, 7],
 u'_rank': 29,
 u'_type': u'LSFU'}