{'_data': [['Very common',
            [['Nervous system', u'yrsel, dyskinesi, somnolens'],
             ['GI', u'Mycket vanliga illam\xe5ende'],
             ['GI', u'Mycket vanliga illam\xe5ende']]],
           ['Common',
            [['Psychiatric',
              u'onormala dr\xf6mmar, beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende, f\xf6rvirring, hallucinationer, s\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Eye', u'synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Vascular', u'hypotension'],
             ['GI', u'Vanliga f\xf6rstoppning, kr\xe4kningar'],
             ['General', u'tr\xf6tthet, perifert \xf6dem'],
             ['Investigations', u'viktminskning inklusive minskad aptit'],
             ['Psychiatric', u'onormala dr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'yrsel, huvudv\xe4rk, somnolens'],
             ['GI', u'Vanliga f\xf6rstoppning, kr\xe4kningar'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Infections', u'a pneumoni'],
             ['Endocrine', u'inadekvat sekretion av antidiuretiskt hormon1'],
             ['Psychiatric',
              u'hets\xe4tning, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, vanf\xf6rest\xe4llningar, hyperfagi, hypersexualitet, st\xf6rningar av libido, paranoia, patologiskt spelberoende, rastl\xf6shet'],
             ['Nervous system',
              u'minnesf\xf6rlust, hyperkinesi, episoder av pl\xf6tsligt insomnande, synkope'],
             ['Cardiac', u'hj\xe4rtsvikt'],
             ['Respiratory', u'dyspn\xe9, hicka'],
             ['Skin', u'\xf6verk\xe4nslighet, pruritus, hudutslag'],
             ['Investigations',
              u'Mindre vanliga vikt\xf6kning En biverkan som observerats efter att produkten kommit ut p\xe5 marknaden. Med 95 % s\xe4kerhet \xe4r frekvensen inte h\xf6gre \xe4n f\xf6r mindre vanliga, men den kan vara l\xe4gre. En exakt frekvensuppskattning \xe4r inte m\xf6jlig eftersom biverkan inte f\xf6rekom i den kliniska databasen d\xe4r 2 762 patienter med Parkinsons sjukdom som behandlades med pramipexol ingick.'],
             ['Infections', u'pneumoni'],
             ['Endocrine', u'ol\xe4mplig uts\xf6ndring av antidiuretiskt hormon'],
             ['Psychiatric',
              u'beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende s\xe5som hets\xe4tning, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hypersexualitet och patologiskt spelberoende ; f\xf6rvirring, vanf\xf6rest\xe4llningar , hallucinationer, hyperfagi , st\xf6rningar av libido, paranoia , rastl\xf6shet'],
             ['Nervous system',
              u'Mindre vanliga minnesf\xf6rlust , dyskinesi, hyperkinesi, episoder av pl\xf6tsligt insomnande, synkope'],
             ['Eye', u'synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Cardiac', u'hj\xe4rtsvikt'],
             ['Vascular', u'Mindre vanliga hypotension'],
             ['Respiratory', u'dyspn\xe9, hicka'],
             ['Skin', u'\xf6verk\xe4nslighet, pruritus, hudutslag'],
             ['General', u'perifert \xf6dem'],
             ['Investigations',
              u'viktminskning inklusive minskad aptit, vikt\xf6kning En biverkan som observerats efter att produkten kommit ut p\xe5 marknaden. Med 95 % s\xe4kerhet \xe4r frekvensen inte h\xf6gre \xe4n f\xf6r mindre vanliga, men den kan vara l\xe4gre. En exakt frekvensuppskattning \xe4r inte m\xf6jlig eftersom biverkan inte f\xf6rekom i den kliniska databasen d\xe4r 1395 patienter med annan indikation som behandlades med pramipexol ingick. Somnolens Pramipexol \xe4r vanligen associerat med somnolens och har \xe4ven associerats med en mindre vanlig biverkan, \xf6verdriven somnolens under dagtid och episoder av pl\xf6tsligt insomnande (se \xe4ven avsnitt 4.4).']]]],
 '_pages': [5, 8],
 u'_rank': 33,
 u'_type': u'LSFU'}