{'_data': [['Common', []],
           ['Uncommon',
            [['Nervous system', u'yrsel, huvudv\xe4rk, s\xf6mnst\xf6rning, insomnia'],
             ['Eye', u'synst\xf6rning (inklusive dimsyn och diplopi)'],
             ['GI',
              u'dyspepsi/halsbr\xe4nna, buksm\xe4rta, illam\xe5ende/kr\xe4kningar, obstipation, diarr\xe9, flatulens'],
             ['Hepato', u'f\xf6rh\xf6jda serum-transaminaser (se avsnitt 4.4)'],
             ['Skin',
              u'pruritus, utslag, urtikaria, h\xe5rbotten/h\xe5rf\xf6r\xe4ndring ar (inklusive alopeci)'],
             ['Musculoskeletal',
              u'muskuloskeletal sm\xe4rta inklusive artralgi, muskelkramper, myalgi, muskelsvaghet och f\xf6rh\xf6jda CK-niv\xe5er (se avsnitt 4.4)'],
             ['Renal',
              u'miktionsst\xf6rningar (inklusive dysuri, t\xe4ta urint\xf6mningar, nykturi)'],
             ['General', u'tr\xf6tthet']]],
           ['Rare', []],
           ['Very rare',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktion er: anafylaxi, angio\xf6dem, lupus erythematosus-liknande syndrom'],
             ['Nervous system',
              u'perifer polyneuropati, s\xe4rskilt vid l\xe4ngre tids bruk, parestesier'],
             ['GI', u'pankreatit'],
             ['Hepato', u'ikterus, hepatit, fulminant levernekros'],
             ['Musculoskeletal',
              u'rabdomyolys, som kan vara f\xf6renad med akut njursvikt sekund\xe4rt till myoglobinuri, myopati (se avsnitt 4.4), myosit, polymyositis. Enstaka fall av senp\xe5verkan, n\xe5gon g\xe5ng med ruptur som komplikation.']]],
           ['Unknown', []]],
 '_note': u' ?MSFU',
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'MSFU'}