{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk*'],
             ['Musculoskeletal', u'Myalgi'],
             ['General',
              u'Reaktion vid injektionsst\xe4llet: Sm\xe4rta* Systemiska reaktioner: Tr\xf6tthet, sjukdomsk\xe4nsla']]],
           ['Common',
            [['Respiratory', u'Hosta, orofaryngeal sm\xe4rta, rinorr\xe9'],
             ['GI', u'Illam\xe5ende*, kr\xe4kning*'],
             ['Skin', u'Hyperhidros'],
             ['Investigations', u'\xd6kat blodtryck'],
             ['Musculoskeletal', u'Artralgi*'],
             ['General',
              u'Reaktioner vid injektionsst\xe4llet: Svullnad, erytem, induration* Systemiska reaktioner: Frossa, pyrexi']]],
           ['Uncommon',
            [['Nervous system',
              u'F\xf6r\xe4ndrad k\xe4nsel* (hypestesi, hyperestesi, parestesi)'],
             ['Eye', u'Okul\xe4r hyperemi \xd6gonirritation,'],
             ['Respiratory', u'Halsirritation Faryngealt \xf6dem'],
             ['GI', u'Magsm\xe4rta'],
             ['Skin', u'Kl\xe5da'],
             ['General',
              u'Reaktion vid injektionsst\xe4llet: Kl\xe5da, ekkymos Systemiska reaktioner: Obehag i br\xf6stet']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighet/ anafylaktisk reaktion'],
             ['Nervous system', u'Dysgeusi'],
             ['Eye', u'\xd6kad t\xe5rbildning*'],
             ['GI', u'Dysfagi'],
             ['Skin', u'Erytem, urtikaria'],
             ['General', u'Reaktion vid injektionsst\xe4llet: v\xe4rme*']]]],
 '_note': u' ?MSFU',
 '_pages': [2, 3],
 u'_rank': 21,
 u'_type': u'MSFU'}