{'_data': [['Very common',
            [['Local', u'(> 1/10)'],
             ['GI', u'Kr\xe4kningar, diarr\xe9, minskad aptit'],
             ['General',
              u'Reaktioner vid injektionsst\xe4llet (t.ex. erytem, induration/svullnad, sm\xe4rta/\xf6mhet), feber > 38\xb0C, irritabilitet, ih\xe5llande gr\xe5t, s\xf6mnighet, orolig s\xf6mn']]],
           ['Common',
            [['Local', u'> 1/100 till < 1/10)'],
             ['General',
              u'Svullnad/induration vid injektionsst\xe4llet och erytem > 2,4 cm, \xf6mhet som p\xe5verkar r\xf6relser, feber > 39 \xb0C']]],
           ['Uncommon', [['Local', u'> 1/1 000 till < 1/100)'], ['Skin', u'Utslag/urtikaria']]],
           ['Rare',
            [['Local', u'> 1/10 000 till < 1/1 000)'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner som t.ex. anafylaktiska/anafylaktoida reaktioner inklusive chock, angioneurotiskt \xf6dem, bronkospasm, dyspn\xe9, ansikts\xf6dem'],
             ['Nervous system', u'Kramper, inklusive feberkramper'],
             ['General',
              u'Hypoton-hyporesponsiva episoder, \xf6verk\xe4nslighetsreaktioner vid injektionsst\xe4llet (t.ex. dermatit, kl\xe5da, urtikaria), flush Apn\xe9 hos mycket prematura barn (f\xf6dda < 28 graviditetsveckan) (se avsnitt 4.4).']]],
           ['Very rare',
            [['Local',
              u'Mycket s\xe4llsynta (< 1/10 000) Biverkningarna presenteras inom varje frekvensomr\xe5de efter fallande allvarlighetsgrad. 5'],
             ['Blood', u'Lymfadenopati vid injektionsst\xe4llet'],
             ['Skin', u'Erythema multiforme']]],
           ['Unknown',
            [['Local',
              u'Ingen konsekvent \xf6kning av lokala eller systemiska reaktioner vid upprepade doser s\xe5gs vid prim\xe4r immuniseringen eller med boosterdosen, med undantag av att en h\xf6gre frekvens av \xf6verg\xe5ende \xf6mhet (36,5%) och \xf6mhet som p\xe5verkade r\xf6relsef\xf6rm\xe5gan i extremiteterna (18,5 %) iakttogs efter boosterdosen. Bland \xe4ldre barn som erh\xf6ll en singeldos vaccinering observerades en h\xf6gre frekvens av lokala reaktioner, \xe4n som tidigare har observerats bland sp\xe4dbarn. Dessa reaktioner var huvudsakligen av \xf6verg\xe5ende natur. I en klinisk studie (efter lanseringen av produkten) med 115 barn mellan 2 till 5 \xe5r, rapporterades \xf6mhet bland 39,1 % av barnen, bland 15,7 % av barnen p\xe5verkade \xf6mheten r\xf6rligheten i extremiteterna. Rodnad rapporterades hos 40,0 % av barnen och induration rapporterades hos 32,2 % av patienterna. Rodnad eller induration \u22652 cm i diameter rapporterades bland 22,6 % respektive 13,9 % av barnen. N\xe4r Prevenar gavs tillsammans med hexavalenta vacciner (DtaP/Hib/PRP-T/IPV/HepB), rapporterades feber > 38 \xbaC hos 28,3 till 48,3% av de barn som fick Prevenar samtidigt med det hexavalenta vaccinet, j\xe4mf\xf6rt med 15,6 till 23,4% i gruppen som fick hexavalent vaccin enbart. Feber \xf6ver 39,5 \xbaC rapporterades hos 0,6 till 2,8% av barnen som fick Prevenar och hexavalenta vacciner (se sektion 4.4). Biverkningar f\xf6rekommer i h\xf6gre grad hos barn som samtidigt f\xe5r helcellsvaccin mot kikhosta. I en studie, inkluderande 1662 barn, rapporterades feber > 38 \xb0C hos 41,2% av de barn som fick Prevenar samtidigt med DTP, j\xe4mf\xf6rt med 27,9% i kontrollgruppen. Feber > 39 \xb0C rapporterades hos 3,3% av barnen j\xe4mf\xf6rt med 1,2% i kontrollgruppen. Biverkningar rapporterade i kliniska pr\xf6vningar eller fr\xe5n spontanrapportering, f\xf6r alla \xe5ldersgrupper, \xe4r listade nedan. Biverkningarna \xe4r indelade efter organ och frekvens. Frekvensen definieras som f\xf6ljande']]]],
 '_pages': [5, 6],
 u'_rank': 15,
 u'_type': u'LSFU'}