{'_data': [['Very common',
            [['Psychiatric', u'f\xf6rvirringstillst\xe5nd'],
             ['Nervous system',
              u'yrsel, nystagmus, minnesneds\xe4ttning, huvudv\xe4rk, somnolens'],
             ['Eye', u'dimsyn'],
             ['GI', u'illam\xe5ende, kr\xe4kningar'],
             ['General', u'onormal g\xe5ng, asteni']]],
           ['Common',
            [['Metabolism', u'nedsatt aptit, anorexi'],
             ['Psychiatric',
              u'\xe5ngest, h\xf6rselhallucinationer, insomnia, agitation, desorientering, hallucinationer, synhallucinationer, depression, paranoia, irritabilitet, f\xf6rv\xe4rrad depression, nervositet, affeklabilitet, f\xf6r\xe4ndringar av mental status, f\xf6rv\xe4rrad \xe5ngest, f\xf6rv\xe4rrad f\xf6rvirring'],
             ['Nervous system',
              u'dysartri, amnesi, smakrubbning, tremor, f\xf6rs\xe4mrad balans, ataxi, afasi, br\xe4nnande k\xe4nsla, sedation, parestesi, hypoestesi, uppm\xe4rksamhetsst\xf6rning, talrubbning, areflexi, koordinationsrubbning, postural yrsel, kognitiv rubbning, hyperestesi, hyporeflexi, smakf\xf6rlust, s\xe4nkt medvetandegrad, dysestesi, luktrubbning, nedsatt mental funktion'],
             ['Eye', u'diplopi, synrubbning, fotofobi'],
             ['Ear', u'vertigo, tinnitus'],
             ['Vascular', u'ortostatisk hypotension, hypotension'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI',
              u'diarr\xe9, muntorrhet, f\xf6rstoppning, f\xf6rv\xe4rrat illam\xe5ende, \xf6vre buksm\xe4rta'],
             ['Skin', u'pruritus, \xf6kad svettning'],
             ['Musculoskeletal',
              u'extremitetssm\xe4rta, myalgi, muskelspasmer, muskelkramp, muskelsvaghet, artralgi, perifer svullnad'],
             ['Renal', u'urinretention, urineringssv\xe5righeter, dysuri, urininkontinens'],
             ['General',
              u'matthet, pyrexi, letargi, perifert \xf6dem, frossbrytningar, fall, br\xf6stsm\xe4rta, k\xf6ldk\xe4nsla, sm\xe4rta, nervositet, f\xf6rv\xe4rrad sm\xe4rta'],
             ['Investigations', u'f\xf6rh\xf6jt blodkreatinfosfokinas, viktnedg\xe5ng']]],
           ['Uncommon',
            [['Infections', u'sepsis, meningit'],
             ['Psychiatric',
              u'delirium, psykotisk st\xf6rning, suicidtankar, suicidf\xf6rs\xf6k, tankeblockering, onormala dr\xf6mmar, aggressivitet'],
             ['Nervous system',
              u'tankest\xf6rning, medvetsl\xf6shet, koma, stupor, konvulsioner, cerebrovaskul\xe4r incident, encefalopati'],
             ['Cardiac', u'f\xf6rmaksflimmer'],
             ['Respiratory', u'respiratorisk distress'],
             ['GI', u'dyspepsi'],
             ['Skin', u'hudutslag'],
             ['Musculoskeletal',
              u'rabdomyolys, myosit, ryggsm\xe4rta, muskelryckningar, nacksm\xe4rta'],
             ['Renal', u'akut njursvikt'],
             ['General', u'g\xe5ngsv\xe5righeter'],
             ['Investigations',
              u'onormalt EKG, f\xf6rh\xf6jt aspartataminotransferas, f\xf6rh\xf6jt kreatinfosfokinas, f\xf6rh\xf6jd kroppstemperatur.']]]],
 '_pages': [5, 8],
 u'_rank': 29,
 u'_type': u'LSFU'}