{'_data': [['Very common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'], ['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Psychiatric',
              u'\xc5ngest, agitation, rastl\xf6shet, insomni, onormala dr\xf6mmar, minskad libido'],
             ['Nervous system', u'Somnolens, st\xf6rd uppm\xe4rksamhet, tremor, parestesi'],
             ['Eye', u'Dimsyn'],
             ['Ear', u'Tinnitus'],
             ['Vascular', u'Rodnad'],
             ['Respiratory', u'T\xe4ppta bih\xe5lor, g\xe4spningar'],
             ['GI',
              u'Diarr\xe9, kr\xe4kningar, f\xf6rstoppning, buksm\xe4rta, \xf6vre buksm\xe4rta, dyspepsi, flatulens, magbesv\xe4r, utsp\xe4nd buk, muntorrhet'],
             ['Skin', u'Hyperhidros'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General', u'Tr\xf6tthet, irritabilitet'],
             ['Investigations', u'F\xf6rh\xf6jt blodtryck']]],
           ['Uncommon',
            [['Psychiatric',
              u'Depression, nedst\xe4mdhet, euforisk sinnesst\xe4mning, hum\xf6rf\xf6r\xe4ndringar, nervositet, likgiltighet, apati, f\xf6rvirringstillst\xe5nd, desorientering, onormala tankar, sp\xe4nd vaksamhet, s\xf6mnst\xf6rningar, insomningssv\xe5righeter, sv\xe5righeter att bibeh\xe5lla s\xf6mnen, mardr\xf6mmar, bruxism, f\xf6rlust av libido, anorgasmi'],
             ['Nervous system',
              u'Synkope, vasovagal synkope, postural yrsel, akatisi, dysgeusi, hypersomni, letargi, sedering, s\xe4nkt medvetandegrad'],
             ['Eye', u'Mydriasis (se avsnitt 4.4), \xf6gonsm\xe4rta, synst\xf6rning'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Sinusarrest, sinusbradykardi, takykardi'],
             ['Vascular', u'Hypotoni, systolisk hypertoni, blodvallningar'],
             ['GI', u'Bukobehag, epigastriskt obehag'],
             ['Skin', u'Kl\xe5da, kallsvettning'],
             ['Reproductive system',
              u'Misslyckad ejakulation, orgasmst\xf6rningar hos m\xe4n, parestesi i genitalierna hos'],
             ['General',
              u'Asteni, v\xe4rmek\xe4nsla, k\xe4nsla av att vara stirrig, k\xe4nsla av att vara onormal, k\xe4nsla av berusning'],
             ['Investigations',
              u'\xd6kad hj\xe4rtfrekvens, f\xf6rh\xf6jt diastoliskt blodtryck, f\xf6rh\xf6jt ortostatiskt blodtryck']]],
           ['Rare',
            [['Nervous system', u'Yrsel vid anstr\xe4ngning, pl\xf6tsliga s\xf6mnattacker'],
             ['GI', u'Br\xe5dskande tarm-t\xf6mningar']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 12],
 u'_rank': 26,
 u'_type': u'MSFU'}