{'_data': [['Common',
            [['Infections', u'Urinv\xe4gsinfektion'],
             ['Infections', u'\xd6vre luftv\xe4gsinfektion'],
             ['Eye', u'Katarakt'],
             ['GI', u'F\xf6rstoppning'],
             ['Skin', u'Hudutslag']]],
           ['Uncommon', [['Skin', u'Eksem']]],
           ['Rare',
            [['Immune system', u'L\xe4kemedels\xf6verk\xe4nslighet'],
             ['Metabolism', u'Hypokalcemi']]]],
 '_pages': [5, 6],
 u'_rank': 8,
 u'_type': u'TSFU'}