{'_data': [['Common',
            [['Psychiatric', u'Huvudv\xe4rk, d\xe5sighet, yrsel.'],
             ['Eye', u'Synst\xf6rningar. \xd6ron och balansorgan'],
             ['Eye', u'\xd6ronsusningar.'],
             ['Cardiac', u'Palpitationer.'],
             ['Vascular', u'V\xe4tskeretention, \xf6dem.'],
             ['GI',
              u'Dyspepsi, buksm\xe4rta, illam\xe5ende, diarr\xe9, f\xf6rstoppning, halsbr\xe4nna, stomatit.'],
             ['Hepato', u'Svettningar, exantem och huderosioner.'],
             ['General', u'T\xf6rst.']]],
           ['Uncommon',
            [['Psychiatric', u'Insomningssv\xe5righeter, koncentrationssv\xe5righeter.'],
             ['Eye', u'H\xf6rselneds\xe4ttning.'],
             ['Respiratory', u'Astma, dyspn\xe9.'],
             ['GI', u'Gastrointestinal bl\xf6dning, mags\xe5r, ulcerativ stomatit.'],
             ['Hepato', u'Leverp\xe5verkan.'],
             ['Hepato', u'H\xe5ravfall, urtikaria, fotosensitivitet inklusive pseudoporfyri.'],
             ['Hepato', u'Njurp\xe5verkan.'],
             ['General',
              u'Feber. Vid tecken p\xe5 pseudoporfyri b\xf6r behandlingen avslutas och patienten f\xf6ljas upp. F\xf6rh\xf6jda leverfunktionsv\xe4rden har i vissa fall rapporterats f\xf6r icke-steroida antiinflammatoriska l\xe4kemedel. Natriumretention har ej rapporterats i metaboliska studier, men det \xe4r m\xf6jligt att patienter med misst\xe4nkt eller verifierad hj\xe4rtsvikt l\xf6per st\xf6rre risk vid medicinering med naproxen. Naproxen h\xe4mmar trombocytaggregationen och f\xf6rl\xe4nger bl\xf6dningstiden. Gastroduodenals\xe5r, perforation eller gastrointestinal bl\xf6dning kan ibland vara d\xf6dlig, s\xe4rskilt hos \xe4ldre (se avsnitt 4.4). Kliniska pr\xf6vningar och epidemiologiska data tyder p\xe5 att anv\xe4ndning av vissa NSAID (s\xe4rskilt i h\xf6ga doser och vid l\xe5ngtidsbehandling) kan medf\xf6ra en liten \xf6kad risk f\xf6r arteriella trombotiska h\xe4ndelser (t.ex. hj\xe4rtinfarkt och stroke, se avsnitt 4.4). I s\xe4llsynta fall f\xf6rekommer allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor.']]],
           ['Rare',
            [['GI', u'och mycket s\xe4llsynta (<1/10000 inkluderande enskilda fallrapporter).'],
             ['Blood',
              u'Trombocytopeni, granulocytopeni, leukopeni, aplastisk och hemolytisk anemi, agranulocytos.'],
             ['Immune system', u'Angioneurotiskt \xf6dem.'],
             ['Endocrine', u'Hyperglykemi. Metabolism och nutrition'],
             ['Endocrine', u'Hyperkalemi.'],
             ['Psychiatric',
              u'Kognitiva st\xf6rningar, depression, mardr\xf6mmar, l\xe4tt oro. Centrala och perifera'],
             ['Psychiatric', u'Aseptisk meningit.'],
             ['Cardiac', u'Hj\xe4rtsvikt, pulmon\xe4rt \xf6dem.'],
             ['Vascular', u'Vaskulit, hypertoni.'],
             ['Respiratory', u'Eosinofil pneumonit.'],
             ['GI',
              u'Kolit, perforation, kr\xe4kningar, melena, esofagit, hematemes, flatulens, gastrit, f\xf6rs\xe4mring av ulcer\xf6s kolit, f\xf6rs\xe4mring av Chrons sjukdom.'],
             ['Hepato', u'Toxisk, i isolerade fall fatal, hepatit. Hud och subkutan v\xe4vnad'],
             ['Hepato', u'Kramper, muskelsvaghet, myalgi. Njurar och urinv\xe4gar'],
             ['Hepato', u'Hematuri.']]],
           ['Very rare',
            [['Immune system',
              u'Sv\xe5ra \xf6verk\xe4nslighetsreaktioner inklusive anafylaxi.'],
             ['GI', u'Pankreatit.'],
             ['Hepato',
              u'Sv\xe5ra mukokutana hudreaktioner, t.ex. Stevens-Johnsons syndrom, erythema multiforme och toxisk epidermal nekrolys. Muskuloskeletala systemet och bindv\xe4v']]],
           ['Unknown',
            [['GI',
              u'rapporterade biverkningarna. Biverkningar associerade med behandling med Pronaxen \xe4r presenterade enligt organsystemklass i tabellen nedan. Biverkningarna \xe4r ordnade under frekvensrubriker, de mest frekventa f\xf6rst, enligt f\xf6ljande indelning: vanliga (>1/100), mindre vanliga (>1/1000, <1/100),'],
             ['Respiratory', u'br\xf6stkorg och mediastinum'],
             ['General', u'och/eller symtom vid administeringsst\xe4llet']]]],
 '_pages': [7, 9],
 u'_rank': 36,
 u'_type': u'LSFU'}