{'_data': [['Common',
            [['Psychiatric', u'S\xf6mnst\xf6rningar, mardr\xf6mmar.'],
             ['Cardiac', u'bradykardi.'],
             ['Vascular', u'kalla extremiteter, Raynauds fenomen'],
             ['Respiratory', u'andf\xe5ddhet.'],
             ['General', u'tr\xf6tthet och/eller matthet (ofta \xf6verg\xe5ende)']]],
           ['Uncommon', [['GI', u'diarr\xe9, illam\xe5ende, kr\xe4kningar']]],
           ['Rare',
            [['Blood', u'trombocytopeni.'],
             ['Immune system', u'angio\xf6dem.'],
             ['Psychiatric', u'Hallucinationer, psykoser, hum\xf6rsv\xe4ngningar.'],
             ['Nervous system', u'f\xf6rvirring, minnesf\xf6rlust, yrsel, parestesi.'],
             ['Eye', u'synst\xf6rningar, torra \xf6gon.'],
             ['Cardiac',
              u'F\xf6rs\xe4mring av hj\xe4rtsvikt, precipitation av hj\xe4rtblock, postural hypotension som kan associeras med synkope.'],
             ['Vascular', u'exacerbation av claudicatiointermittens.'],
             ['Respiratory',
              u'bronkospasmer kan intr\xe4ffa hos patienter med bronkialastma eller astma i anamnesen, ibland med d\xf6dlig utg\xe5ng.'],
             ['Skin',
              u'alopeci, purpura, psoriasisliknande hudutslag eller f\xf6rv\xe4rrande av psoriasis, utslag.']]],
           ['Very rare',
            [['Nervous system',
              u'Isolerade rapporter av myastenia gravis-liknande syndrom eller exacerbation av myastenia gravis har rapporterats.'],
             ['Skin', u'Enstaka fall av hyperhidros har rapporterats.'],
             ['Investigations',
              u'En \xf6kad halt av antinukle\xe4ra antikroppar(ANA) har setts, men denkliniska relevansen av detta \xe4r oklar. Om en klinisk bed\xf6mning indikerar att en patients v\xe4lm\xe5ende p\xe5verkas negativt av n\xe5gon av ovanst\xe5ende reaktioner ska ett uts\xe4ttande av l\xe4kemedlet \xf6verv\xe4gas. Ett avbrott av behandling med betablockerare b\xf6r ske gradvis (se avsnitt 4.4). I de s\xe4llsynta fall d\xe4r intolerans utvecklas som bradykardi och hypotoni ska l\xe4kemedlet s\xe4ttas ut och, vid behov, behandling f\xf6r \xf6verdosering s\xe4ttas in (se avsnitt 4.9).']]],
           ['Unknown',
            [['Blood', u'agranulocytos.'],
             ['Endocrine', u'maskerande tecken p\xe5 tyretoxikos.'],
             ['Metabolism',
              u'hypoglykemi hos nyf\xf6dda, sp\xe4dbarn,barn, \xe4ldre, patienter i hemodialys,patienter med samtidig annan antidiabetisk behandling, patienter som fastar l\xe5ngvarigt och patienter med kronisk leversjukdom. F\xf6r\xe4ndringar i lipid metabolism (f\xf6r\xe4ndringar i koncentrationer av triglycerider och kolesterol i blodet). Allvarlig hypoglykemi har i s\xe4llsynta fall givit krampanfall och/eller koma.'],
             ['Psychiatric', u'depression.'],
             ['Nervous system', u'huvudv\xe4rk, krampanfall kopplat till hypoglykemi.'],
             ['Eye', u'konjunktivit.'],
             ['Cardiac', u'f\xf6rv\xe4rrade k\xe4rlkrampsanfall'],
             ['Respiratory', u'dyspn\xe9.'],
             ['GI', u'f\xf6rstoppning, muntorrhet'],
             ['Musculoskeletal', u'artralgi'],
             ['Renal', u'minskat blodfl\xf6de till njurar och GFR'],
             ['Reproductive system', u'impotens.']]]],
 '_pages': [7, 9],
 u'_rank': 30,
 u'_type': u'LSFU'}