{'_data': [['Common',
            [['Pregnancy',
              u'  Fosterp\xe5verkan till f\xf6ljd av onormalt  och perinatalperiod  v\xe4rkarbete  -P\xe5verkan p\xe5 fostrets hj\xe4rtfrekvens -Fetalt distress syndrom -Hyperton uterus ']]],
           ['Uncommon', [['GI', u' Illam\xe5ende, kr\xe4kningar, diarr\xe9  ']]],
           ['Rare',
            [['Blood', u' Disseminerad intravaskul\xe4r koagulation  '],
             ['Pregnancy', u'och perinatalperiod  Uterusruptur  ']]],
           ['Very rare',
            [['Immune system', u' Anafylaktisk reaktion  --'],
             ['Reproductive system',
              u'och  Genitalt \xf6dem  br\xf6stk\xf6rtel -n\xe4r vaginalinl\xe4gget avl\xe4gsnats. (se avsnitt 4.3 och 4.4). avsnitt 4.4). ']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'DFSU'}