{'_data': [['Very common',
            [['General',
              u'Lokal sm\xe4rta under f\xf6rsta injektionen. Profylax eller behandlingsmetoder beskrivs nedan.']]],
           ['Common',
            [['Cardiac', u'Lindrig eller m\xe5ttlig hypotoni'],
             ['Nervous system',
              u'Under induktion av anestesin kan troligen ofrivilliga r\xf6relser och myokloniska r\xf6relser observeras.'],
             ['Respiratory',
              u'Under induktion av anestesin kan hyperventilering, tillf\xe4llig apn\xe9 och hosta f\xf6rekomma.'],
             ['GI', u'Hicka under induktion av anestesin.'],
             ['General', u'V\xe4rmevallningar under induktion av anestesin.']]],
           ['Uncommon',
            [['Cardiac',
              u'Tydlig hypotoni. Detta kan leda till behov av intraven\xf6s v\xe4tsketillf\xf6rsel, vid behov vasokonstringerande medel samt s\xe4nkt administreringshastighet av Propofol Claris 10 mg/ml. Det \xe4r viktigt att vara medveten om risken f\xf6r allvarligt s\xe4nkt blodtryck hos patienter med nedsatt perfusion till hj\xe4rta eller hj\xe4rna eller med hypervolemi.'],
             ['Respiratory', u'Hosta under underh\xe5ll av anestesin.']]],
           ['Rare',
            [['Cardiac',
              u'Hj\xe4rtarrytmi under \xe5terh\xe4mtningstiden. Under allm\xe4n anestesi kan enstaka fall av progressiv bradykardi (asystole) intr\xe4ffa. \xd6verv\xe4g intraven\xf6s administrering av antikolinergika f\xf6re induktion eller under underh\xe5ll (se \xe4ven avsnitt 4.4).'],
             ['Nervous system',
              u'Under \xe5terh\xe4mtningstiden kan huvudv\xe4rk, yrsel, frossbrytningar och k\xf6ldk\xe4nsla upplevas samt epileptiforma krampanfall inklusive opistotonus.'],
             ['Respiratory', u'Hosta under \xe5terh\xe4mtningstiden.'],
             ['GI', u'Illam\xe5ende eller kr\xe4kningar under \xe5terh\xe4mtningstiden.'],
             ['Renal',
              u'S\xe4llsynta fall av missf\xe4rgningar av urinen har f\xf6rekommit efter l\xe5ngvarig behandling med Propofol Claris 10 mg/ml.'],
             ['General', u'Feber efter ingreppet.'],
             ['General', u'Trombos och flebit.'],
             ['Immune system',
              u'Allvarliga \xf6verk\xe4nslighetsreaktioner (anafylaxi) inklusive Quincke-\xf6dem, bronkospasmer, erythema och hypotoni.'],
             ['Psychiatric',
              u'Eufori och sexuell h\xe4mningsl\xf6shet under \xe5terh\xe4mtningstiden.']]],
           ['Very rare',
            [['Nervous system',
              u'F\xf6rdr\xf6jda epileptiska anfall med en f\xf6rdr\xf6jning p\xe5 allt fr\xe5n n\xe5gra timmar till flera dagar. Krampanfall har observerats (i enstaka fall) efter administrering av propofol till patienter med epilepsi. Fall av postoperativ medvetsl\xf6shet (se avsnitt 4.4).'],
             ['Respiratory',
              u'Enstaka fall av lung\xf6dem har rapporterats efter administrering av propofol.'],
             ['GI',
              u'Pankreatit har rapporterats efter administrering av propofol. Det gick dock inte att s\xe4kerst\xe4lla den bakomliggande orsaken till detta.'],
             ['General',
              u'I s\xe4llsynta fall har rabdomyolys, metabolisk acidos, hyperkalemi och hj\xe4rtsvikt, i vissa fall med d\xf6dlig utg\xe5ng, rapporterats efter administrering av propofol vid doser h\xf6gre \xe4n 4 mg/kg kroppsvikt per timme vid sedering i samband med intensivv\xe5rd (se \xe4ven avsnitt 4.4).'],
             ['General',
              u'Enstaka fall av allvarliga v\xe4vnadsreaktioner efter oavsiktlig extravasal administrering. Lokal sm\xe4rta som kan f\xf6rekomma vid den inledande injektionen av Propofol Claris 10 mg/ml kan lindras genom samtidig administrering av lidokain (se \xe4ven avsnitt 4.2.3) samt genom anv\xe4ndning av st\xf6rre vener i underarmen eller armvecket. Efter samtidig administrering av lidokain kan f\xf6ljande biverkningar f\xf6rekomma: Yrsel, kr\xe4kningar, ostadighet, krampanfall, bradykardi, hj\xe4rtarytmi och chock.']]]],
 '_pages': [7, 9],
 u'_rank': 22,
 u'_type': u'LSFU'}