{'_data': [['Very common', [['Blood', u'Benm\xe4rgssuppression; leukopeni och trombocytopeni.']]],
           ['Common',
            [['GI',
              u'Illam\xe5ende, kr\xe4kningar. Pankreatit hos patienter med inflammatorisk tarmsjukdom (IBD)*'],
             ['Hepato', u'Bili\xe4r stas, hepatotoxicitet (se 4.2).']]],
           ['Uncommon', [['Metabolism', u'Anorexi.'], ['Other', u'Carcinogenicitet.']]],
           ['Rare',
            [['Immune system',
              u'Allergiska reaktioner inkl. artralgi, hudutslag, drogrelaterad feber.'],
             ['GI',
              u'Oral ulceration, pankreatit vid behandling inom godk\xe4nda indikationer..'],
             ['Hepato', u'Levernekros.'],
             ['Skin', u'Alopeci.']]],
           ['Very rare',
            [['Neoplasms',
              u'Sekund\xe4r leukemi och myelodysplasi. Hepatosplen\xe4rt T-cellslymfom hos patienter med inflammatorisk tarmsjukdom (IBD)* (se 4.4)'],
             ['Immune system', u'Ansikts\xf6dem.'],
             ['GI', u'Intestinal ulceration.'],
             ['Reproductive system', u'\xd6verg\xe5ende oligospermi.']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 13,
 u'_type': u'MSFU'}