{'_data': [['Unknown',
            [['Investigations',
              u' f\xf6rkortad protrombin tid, f\xf6rl\xe4ngd protrombin tid, vikt\xf6kning, viktminskning.'],
             ['Blood',
              u' Bl\xf6dningsben\xe4genhet, hypoprotrombinemi, anemi, lymfadenopati, ekkymos.'],
             ['Nervous system',
              u' huvudv\xe4rk, yrsel, synkop\xe9, s\xf6mnighet, neuralgi, parestesier, dysgeusi.'],
             ['Eye', u' nattblindhet (med vitamin A brist), uveit.'],
             ['Ear', u' tinnitus, yrsel.'],
             ['Respiratory', u' astma, v\xe4sning, dyspn\xe9, hicka.'],
             ['GI',
              u' f\xf6rstoppning, pankreatit, abdominal obehagsk\xe4nsla, flatulens, illam\xe5ende, kr\xe4kningar, diarr\xe9, dyspepsi, steatorr\xe9, glossit, anorektalt besv\xe4r, gastrointestinal bl\xf6dning, rektal bl\xf6dning, missf\xe4rgning av faeces, hemorroidal bl\xf6dning, duodenal ulcer bl\xf6dning, dysfagi, ulcus, proktalgi, rapning, akut buk, karies, bl\xf6dningar i munnen och intestinal obstruktion (inklusive 2 d\xf6dsfall i pediatriska patienter), divertikulit.'],
             ['Renal', u' hematuri, dysuri, onormal urinod\xf6r, polyuri.'],
             ['Skin', u'   rodnad,   hudirritation, n\xe4sselutslag.'],
             ['Musculoskeletal', u' osteoporos, ryggont, myalgi, artralgi, artrit.'],
             ['Metabolism',
              u' vitamin A brist, vitamin K brist, vitamin D brist, acidos, hyperkloremi (hos barn) anorexi.'],
             ['General', u' tr\xf6tthet, \xf6dem. '],
             ['Hepato',
              u' kolelitiasis, kalcifiering av   gallbl\xe5san,   gallkolik,   onormala leverfunktionsv\xe4rden'],
             ['Psychiatric', u' \xf6kat libido, \xe5ngest.']]]],
 '_pages': [3, 4],
 u'_rank': 14,
 u'_type': u'LSFU2'}