{'_data': [['Very common',
            [['Blood', u'Minskat hemoglobin'],
             ['Metabolism',
              u'F\xf6rh\xf6jda serumniv\xe5er triglycerider , f\xf6rh\xf6jt totalkolestero l (framf\xf6rallt LDL kolesterol) , minskat HDL kolesterol Viktuppg\xe5ng'],
             ['Nervous system', u'Yrsel , somnolens huvudv\xe4rk'],
             ['GI', u'Muntorrhet'],
             ['General', u'Uts\xe4ttningssy mtom'],
             ['Investigations',
              u'Se avsnitt 4.4 fortsatt quetiapinbehandling. marknadsintroduktion. (7) Fasteblodglukos p\xe5 >126 mg/dl (>11,1 mmol/l) veckor hos vuxna. F\xf6ljande uts\xe4ttningssymtom s\xe5gs mest frekvent i akuta placebokontrollerade kliniska Triglycerider >200 mg/dl (>2,258 mmol/l) vid \xe5tminstone ett tillf\xe4lle(patienter >18 \xe5r) (12) 7 mmol/l). (13) (14) Trombocytantal \uf0a3 x 10 associerat till malignt neuroleptika-syndrom (16) (>1304,34 pmol/l) kvinnor oberoende av tidpunkt (17) (18) kvinnor oberoende av tidpunkt. (19) f\xf6r\xe4ndring j\xe4mf\xf6rbar med placebo. (20) (21) (22) (23) g/dl. (24) underliggande hj\xe4rt/luftv\xe4gssjukdom. (25) och fritt T definieras som (27) (28) som Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normala utg\xe5ngsv\xe4rden till potentiellt kliniskt v\xe4rdefulla som quetiapin. (32) (33) h\xe4ndelser i alla kliniska studier med quetiapin. Barn och ungdomar 17 identifierats i den vuxna populationen. Metabolism och nutrition mycket vanliga: Unders\xf6kningar Mycket vanliga: F\xf6rh\xf6jda prolaktinv\xe4rden Centrala och perifera nervsystemet mycket vanliga:'],
             ['Endocrine', u'Inadekvat sekretion av antidiuretiskt hormon'],
             ['Hepato', u', hepatit'],
             ['Skin', u'Angio\xf6dem Stevens-Johns on syndrom'],
             ['Musculoskeletal', u'Rabdomyolys']]],
           ['Common',
            [['Blood', u'Leukopeni minskat neutrofilantal, \xf6kad m\xe4ngd eosinofiler'],
             ['Endocrine',
              u'Hyperprolaktine ,minskad 16 mi m\xe4ngd total T , minskad m\xe4ngd fritt T minskad m\xe4ngd total T f\xf6rh\xf6jning av TSH'],
             ['Metabolism',
              u'\xd6kad aptit, f\xf6rh\xf6jd blodglukosniv\xe5 till hyperglykemi ,'],
             ['Psychiatric',
              u'Onormala dr\xf6mmar och mardr\xf6mmar, sj\xe4lvmordstanka r och suicidalt beteende'],
             ['Nervous system', u'Synkope , extrapyramidala , symtom dysartri'],
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Takykardi palpitationer'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['Respiratory', u', dyspn\xe9 Rinit'],
             ['GI', u'F\xf6rstoppning, dyspepsi , kr\xe4kningar'],
             ['Hepato', u'F\xf6rh\xf6jda serumtransamin aser (ALAT, gamma-GT-stegri ng'],
             ['General', u'Mild asteni, perifert \xf6dem, irritabilitet'],
             ['Investigations',
              u'vid \xe5tminstone ett tillf\xe4lle. Kolesterol >240 mg/dl (>6,2064 mmol/l) (patienter >18 \xe5r) eller >200 mg/dl Se nedanst\xe5ende text Prolaktinniv\xe5er (patienter med \xe5lder>18 \xe5r): >20 \xb5g/l (>869,56 pmol/l) m\xe4n; >30 \xb5g/l Kan leda till fall HDL-kolesterol: <40 mg/dl 25 mmol/l) f\xf6r m\xe4n; <50 mg/dl (1,282 mmol/l) f\xf6r F\xf6rekomst av patienter som f\xe5tt QTc-f\xf6r\xe4ndring fr\xe5n <450 msek till >450 msek med en F\xf6rskjutning fr\xe5n >132 mmol/l till <132 mmol/l vid minst ett tillf\xe4lle. Fall av sj\xe4lvmordstankar och suicidalt beteende har rapporterats under Se sektion 5.1 En s\xe4nkning av hemoglobinv\xe4rdet till <13 g/dl (8,07 mmol/l) hos m\xe4n, <12 g/dl (7,45 Dessa rapporter intr\xe4ffade ofta vid takykardi, yrsel, ortostatisk hypotension och/eller Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normala utg\xe5ngsv\xe4rden till potentiellt kliniskt v\xe4rdefulla 3 F\xf6r\xe4ndringar i neutrofiler fr\xe5n Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normala utg\xe5ngsv\xe4rden till potentiellt kliniskt v\xe4rdefulla >1 x 10 >1 x 10 Se avsnitt 4.6. Kan ske vid eller n\xe4ra b\xf6rjan av behandlingen och vara f\xf6rknippad med hypotoni \xe5r) \xd6kad aptit Extrapyramidala symtom3']]],
           ['Uncommon',
            [['Blood', u'Thrombocytope ni, anemi, minskat antal blodpl\xe4ttar'],
             ['Endocrine', u'Minskad m\xe4ngd fritt T , hypothyroidism ,'],
             ['Metabolism', u'Hyponatremi diabetes mellitus'],
             ['Nervous system', u'Kramper legs syndrom, tardiv dyskinesi ,'],
             ['Cardiac', u'4 , QT f\xf6rl\xe4ngning bradykardi'],
             ['GI', u'Dysfagi'],
             ['Reproductive system', u'Sexuell dysfunktion'],
             ['General', u', feber'],
             ['Investigations',
              u'(>7,0 mmol/l) /l vid \xe5tminstone ett tillf\xe4lle. <0.8 x LLN (pmol/l) och variationer i TSH \xe4r > 5 mIU/l n\xe4r som helst. >1.5 x 10 cells/l n\xe4r som helst. cells/l n\xe4r som helst. , blodtrycksh\xf6jningar']]],
           ['Rare',
            [['Blood', u'Agranulocytos'],
             ['Metabolism', u'Metaboliskt 20 , syndrom'],
             ['Psychiatric',
              u'Somnambulism och relaterade reaktioner som att tala i s\xf6mnen och s\xf6mnrelaterad \xe4tst\xf6rning'],
             ['Nervous system', u', restless'],
             ['Cardiac', u'1,13,19 ,'],
             ['Vascular', u'Ven\xf6s tromboembolism'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Gulsot'],
             ['Reproductive system',
              u'Priapism, galaktorr\xe9, br\xf6stsvullnad, menstruationsrubb ning'],
             ['General', u'Malignt neuroleptika-syndr , hypotermi om'],
             ['Investigations',
              u'F\xf6rh\xf6jt kreatinfosfokinas i blod eller icke fastande blodglukos p\xe5 >200 mg/dl /l som utg\xe5ngsv\xe4rde till <0.5 x 10']]],
           ['Unknown', [['Blood', u'Neutropeni'], ['Skin', u'Toxisk , Epidermal nekrolys,']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 12],
 u'_rank': 45,
 u'_type': u'MSFU'}