{'_data': [['Very common',
            [['Nervous system', u'Yrsel , somnolens , huvudv\xe4rk'],
             ['GI', u'Muntorrhet'],
             ['General', u'Uts\xe4ttnings-symtom'],
             ['Investigations',
              u'F\xf6rh\xf6jd triglyceridhalt f\xf6rh\xf6jt kolesterolv\xe4rde kolesterol) s\xe4nkt HDL-kolesterol vikt\xf6kning'],
             ['Metabolism', u'\xd6kad aptit'],
             ['Investigations', u'Stegrade prolaktinniv\xe5er blodtrycks-\xf6kningar'],
             ['Nervous system', u'Extrapyramidala symtom'],
             ['General', u'vid ']]],
           ['Common',
            [['Blood', u'Leukopeni'],
             ['Endocrine', u'Hyperpro-laktinemi'],
             ['Metabolism', u'\xd6kad aptit'],
             ['Psychiatric', u'Abnorma dr\xf6mmar och mardr\xf6mmar'],
             ['Nervous system', u'Synkope Extra-pyramidala dysartri'],
             ['Cardiac', u'Takykardi'],
             ['Eye', u'Dimsyn'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['Respiratory', u'Rinit'],
             ['GI', u'F\xf6rstoppning, dyspepsi'],
             ['General', u'Mild asteni, perifert \xf6dem, irritabilitet'],
             ['Investigations',
              u'F\xf6rh\xf6jda serum-transaminaser (ALAT, neutrofilantal, f\xf6rh\xf6jd blodglukos-, niv\xe5 till hyperglykemi'],
             ['Investigations', u','],
             ['General', u'Irritabilitet']]],
           ['Uncommon',
            [['Blood', u'Eosinofili, trombo-cytopeni'],
             ['Immune system', u'\xd6ver-k\xe4nslighet'],
             ['Metabolism', u'Hypo-natremi'],
             ['Nervous system', u'Kramper , restless legs syndrom, dyskinesi'],
             ['GI', u'Dysfagi'],
             ['Reproductive system', u'Sexuell dysfunktion'],
             ['Investigations', u'gamma-GT-stegring minskat QT-f\xf6rl\xe4ng-1,13,19 ning']]],
           ['Rare',
            [['Vascular', u'Ven\xf6s trombo-embolism'],
             ['Hepato', u'Gulsot'],
             ['Reproductive system',
              u'Priapism, galaktorr\xe9, br\xf6st-svullnad, menstruella st\xf6rningar'],
             ['General', u'Malignt neuroleptika syndrom'],
             ['Investigations', u'F\xf6rh\xf6jt kreatin-fosfokinas i , blod']]],
           ['Very rare',
            [['Immune system', u'Anafyl-aktisk reaktion'],
             ['Endocrine', u'St\xf6rningar i sekre-tionen av anti-diuretiskt hormon'],
             ['Metabolism', u'Diabetes mellitus'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Angio-\xf6dem , Stevens-Johnsons syndrom'],
             ['Musculoskeletal', u'Rabdo-myolys']]],
           ['Unknown', [['Blood', u'Neu-tro-peni']]]],
 '_note': u' ?MSFU ANOMALI in Headers',
 '_pages': [8, 11],
 u'_rank': 41,
 u'_type': u'MSFU'}