{'_data': [['Very common',
            [['Blood', u'S\xe4nkt hemoglobinniv\xe5'],
             ['Metabolism',
              u'F\xf6rh\xf6jda triglyceridniv\xe5er i serum F\xf6rh\xf6jda totalkolesterolniv\xe5er (fr\xe4mst LDL kolesterol) S\xe4nkta HDL kolesterolniv\xe5er , vikt\xf6kning'],
             ['Nervous system', u'Mycket vanliga Yrsel , somnolens , huvudv\xe4rk'],
             ['GI', u'Muntorrhet'],
             ['General', u'Uts\xe4ttningssymtom'],
             ['Metabolism', u'\xd6kad aptit'],
             ['Investigations',
              u'Mycket vanliga Stegrade prolaktinniv\xe5er , blodtrycks\xf6kningar'],
             ['Nervous system',
              u'Extrapyramidala symtom Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Common',
            [['Blood', u'Vanliga Leukopeni , minskat neutrofilantal, \xf6kat eosinofilantal'],
             ['Immune system',
              u'Vanliga Hyperprolaktinemi , minskning av totalt T , minskning av fritt T , minskning av totalt T , \xf6kning av TSH'],
             ['Metabolism',
              u'\xd6kad aptit, blodglukosniv\xe5 f\xf6rh\xf6jd till hyperglykemi'],
             ['Psychiatric',
              u'Abnorma dr\xf6mmar och mardr\xf6mmar, Suicidtankar och suicidbeteende'],
             ['Nervous system', u'Vanliga Synkope , extrapyramidala symtom , dysartri'],
             ['Cardiac', u'Vanliga Takykardi , palpitationer'],
             ['Eye', u'Dimsyn'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['Respiratory', u'Rinit, dyspn\xe9'],
             ['GI', u'F\xf6rstoppning, dyspepsi, kr\xe4kningar'],
             ['Hepato',
              u'Vanliga F\xf6rh\xf6jda transaminasniv\xe5er i serum (ALAT, ASAT) , f\xf6rh\xf6jda gamma-GT-niv\xe5er'],
             ['General', u'Mild asteni, perifert \xf6dem, irritabilitet, pyrexia'],
             ['Nervous system',
              u'Irritabilitet Prolaktinniv\xe5er (patienter <18 \xe5r): >20 \xb5g/l (>869,56 pmol/l) m\xe4n; >26 \xb5g/l (>1130,428 pmol/l) kvinnor oberoende av tidpunkt. Mindre \xe4n 1 % av patienterna fick en h\xf6jning till en prolaktinniv\xe5 >100 \xb5g/l. Baserat p\xe5 f\xf6r\xe4ndringar \xf6ver kliniskt signifikanta tr\xf6skelv\xe4rden (anpassade fr\xe5n kriterierna fr\xe5n amerikanska National Institutes of Health) eller h\xf6jningar p\xe5 >20 mmHg i systoliskt eller >10 mmHg f\xf6r diastoliskt blodtryck oberoende av tidpunkt i tv\xe5 akuta (3-6 veckor l\xe5nga) placebokontrollerade studier p\xe5 barn och ungdomar. Se avsnitt 5.1 Kommentar: Frekvensen \xf6verensst\xe4mmer med den som observerats hos vuxna, men irritabilitet kan vara f\xf6renad med andra kliniska implikationer hos barn och ungdomar \xe4n hos vuxna.']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, anemi, minskat trombocytantal'],
             ['Immune system', u'\xd6verk\xe4nslighet (inklusive allergiska hudreaktioner)'],
             ['Immune system', u'Mindre vanliga Minskning av fritt T , hypotyreoidism'],
             ['Metabolism', u'Mindre vanliga Hyponatremi , diabetes mellitus'],
             ['Nervous system',
              u'Mindre vanliga Kramper , restless legs syndrom, tardiv dyskinesi'],
             ['Cardiac', u'Mindre vanliga QT f\xf6rl\xe4ngning 1,13,19 , bradykardi'],
             ['GI', u'Dysfagi'],
             ['Reproductive system', u'Sexuell dysfunktion']]],
           ['Rare',
            [['Blood', u'Agranulocytos'],
             ['Metabolism', u'Metaboliskt syndrom'],
             ['Psychiatric',
              u'Somnambulism och relaterade reaktioner s\xe5som s\xf6mng\xe5ng och s\xf6mnrelaterade \xe4tst\xf6rningar'],
             ['Vascular', u'Ven\xf6s trombo-embolisk sjukdom'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'S\xe4llsynta Gulsot , Hepatit'],
             ['Reproductive system',
              u'Priapism, galaktorr\xe9, br\xf6stsvullnad, menstruationsrubbning'],
             ['General', u'S\xe4llsynta Malignt neuroleptikasyndrom , hypotermi'],
             ['Investigations',
              u'F\xf6rh\xf6jt kreatinfosfokinas i blod Se avsnitt 4.4 Somnolens kan intr\xe4ffa, f\xf6retr\xe4desvis under de f\xf6rsta tv\xe5 behandlingsveckorna och f\xf6rsvinner vanligen vid fortsatt administrering av quetiapin. Asymptomatiska \xf6kningar (f\xf6r\xe4ndring fr\xe5n normal niv\xe5 till >3 x ULN vid n\xe5gon tidpunkt) av serumtransaminaser (ALAT, ASAT) eller gamma-GT har observerats hos patienter som behandlats med quetiapin. Dessa \xf6kningar var i de flesta fall reversibla under fortsatt quetiapin-behandling. Liksom andra antipsykotika som blockerar alfa-1-adrenerga receptorer kan quetiapin ofta inducera ortostatisk hypotoni, f\xf6rknippad med yrsel, takykardi och hos vissa patienter synkope. Detta intr\xe4ffar framf\xf6rallt under den initiala dostitreringsperioden (se avsnitt 4.4). F\xf6rs\xe4mring av befintlig diabetes har rapporterats i mycket s\xe4llsynta fall. 6 Ber\xe4kning av frekvens f\xf6r dessa biverkningar bygger endast p\xe5 data som erh\xe5llits efter marknadsintroduktion f\xf6r quetiapinformuleringen med omedelbar fris\xe4ttning. 7 Fasteblodglukos p\xe5 \u2265126 mg/dl (\u22657,0 mmol/l) eller icke fastande blodglukos p\xe5 \u2265200 mg/dl (\u226511,1 mmol/l) vid \xe5tminstone ett tillf\xe4lle. \xd6kad f\xf6rekomst av dysfagi vid behandling med quetiapin j\xe4mf\xf6rt med placebo har endast observerats i kliniska studier av bipol\xe4r depression. Baserat p\xe5 >7 % \xf6kning i kroppsvikt fr\xe5n baseline. Uppkommer fr\xe4mst under behandlingens f\xf6rsta veckor. F\xf6ljande uts\xe4ttningssymtom s\xe5gs mest frekvent i akuta placebokontrollerade kliniska pr\xf6vningar vid monoterapi, som utv\xe4rderade symtom efter avslutad behandling: s\xf6mnl\xf6shet, illam\xe5ende, huvudv\xe4rk, diarr\xe9, kr\xe4kningar, yrsel och irritabilitet. Uppkomsten av dessa reaktioner hade minskat signifikant 1 vecka efter avslutad behandling. Triglycerider \u2265200 mg/dl (\u22652,258 mmol/l) (patienter \u226518 \xe5r) eller \u2265150 mg/dl (\u22651,694 mmol/l) (patienter <18 \xe5r) vid \xe5tminstone ett tillf\xe4lle. Kolesterol \u2265240 mg/dl (\u22656,2064 mmol/l) (patienter \u226518 \xe5r) eller \u2265200 mg/dl (\u22655,172 mmol/l) (patienter <18 \xe5r) vid \xe5tminstone ett tillf\xe4lle. Ett f\xf6rh\xf6jt LDL-kolesterolv\xe4rde p\xe5 \u226530 mg/dl (\u22650,769 mmol/l) har varit en mycket vanlig observation. Genomsnittlig f\xf6r\xe4ndring hos patienter med denna f\xf6rh\xf6jning var 41,7 mg/dl (\u22651,07 mmol/l). Se nedanst\xe5ende text. Trombocytantal <100 x 10 /l vid \xe5tminstone ett tillf\xe4lle. Baserat p\xe5 biverkningsrapporter fr\xe5n kliniska studier av f\xf6rh\xf6jt kreatinfosfokinas som inte var associerat till malignt neuroleptika-syndrom. Prolaktinniv\xe5er (patienter >18 \xe5r): >20 \xb5g/l (>869,56 pmol/l) m\xe4n; >30 \xb5g/l (>1304,34 pmol/l) kvinnor oberoende av tidpunkt. Kan leda till fall. HDL-kolesterol: <40 mg/dl (1,025 mmol/l) f\xf6r m\xe4n; <50 mg/dl (1,282 mmol/l) f\xf6r kvinnor oberoende av tidpunkt. F\xf6rekomst hos patienter som f\xe5tt QT-f\xf6r\xe4ndring fr\xe5n <450 msek till \u2265450 msek med en \u226530 msek f\xf6rl\xe4ngning. I placebokontrollerade kliniska studier med quetiapin \xe4r den genomsnittliga f\xf6r\xe4ndringen och f\xf6rekomsten hos patienter med en kliniskt signifikant f\xf6r\xe4ndring j\xe4mf\xf6rbar med placebo. F\xf6r\xe4ndring fr\xe5n >132 mmol/l till \u2264132 mmol/l vid \xe5tminstone ett tillf\xe4lle. Fall av suicidtankar och suicidbeteende har rapporterats under behandling med quetiapin eller kort tid efter uts\xe4ttande av behandling (se avsnitt 4.4 och 5.1). Se avsnitt 5.1. En s\xe4nkning av hemoglobinv\xe4rdet till \u226413 g/dl (8,07 mmol/l) hos m\xe4n, \u226412 g/dl (7,45 mmol/l) hos kvinnor vid minst ett tillf\xe4lle f\xf6rekom hos 11 % av quetiapinpatienterna i samtliga studier inklusive \xf6ppna uppf\xf6ljningsstudier. F\xf6r dessa patienter var den genomsnittliga maximala s\xe4nkningen av hemoglobinv\xe4rdet vid n\xe5gon tidpunkt 1,50 g/dl. Dessa rapporter f\xf6rekom ofta vid takykardi, yrsel, ortostatisk hypotoni och/eller bakomliggande hj\xe4rt-/luftv\xe4gssjukdom. Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normalt utg\xe5ngsv\xe4rde till potentiellt kliniskt viktigt v\xe4rde vid n\xe5gon tidpunkt efter utg\xe5ngsv\xe4rdet i alla studier. F\xf6r\xe4ndringar av totalt T , fritt T , totalt T och fritt T definieras som <0,8 x LLN (pmol/l) och f\xf6r\xe4ndring av TSH \xe4r >5 mIE/l vid n\xe5gon tidpunkt. Baserat p\xe5 den \xf6kade frekvensen av kr\xe4kningar hos \xe4ldre patienter (\u226565 \xe5r). Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normalt utg\xe5ngsv\xe4rde till potentiellt kliniskt viktigt v\xe4rde vid n\xe5gon tidpunkt efter studiestart i alla studier. F\xf6r\xe4ndringar i Lkc definieras som <3 x 10 celler/l vid n\xe5gon tidpunkt. Baserat p\xe5 f\xf6r\xe4ndringar fr\xe5n normalt utg\xe5ngsv\xe4rde till potentiellt kliniskt viktigt v\xe4rde vid n\xe5gon tidpunkt efter studiestart i alla studier. F\xf6r\xe4ndringar i neutrofilantal definieras som >1 x 10 celler/l vid n\xe5gon tidpunkt. F\xf6r\xe4ndring av antal neutrofiler fr\xe5n ett utg\xe5ngsv\xe4rde p\xe5 >1,5 x 10 /l till <0,5 x 10 /l vid n\xe5gon tidpunkt under behandlingen. Baserat p\xe5 biverkningsrapporter om metaboliskt syndrom fr\xe5n alla kliniska pr\xf6vningar med quetiapin. Hos vissa patienter observerades en f\xf6rs\xe4mring av fler \xe4n en av de metabola faktorerna vikt, blodglukos och lipider i kliniska studier (se avsnitt 4.4). Kan intr\xe4ffa vid eller n\xe4ra behandlingsstart och kan vara kopplat till hypotension och/eller synkope. Frekvensen baseras p\xe5 biverkningsrapporter g\xe4llande bradykardi i alla kliniska pr\xf6vningar med quetiapin. Fall med QT-f\xf6rl\xe4ngning, ventrikul\xe4r arytmi, pl\xf6tslig of\xf6rklarlig d\xf6d, hj\xe4rtstillest\xe5nd och torsades de pointes har rapporterats vid anv\xe4ndning av neuroleptika och \xe4r att betrakta som klasseffekter.']]],
           ['Very rare',
            [['Immune system', u'Anafylaktisk reaktion Endokrina st\xf6rningar'],
             ['Immune system', u'Inadekvat sekretion av antidiuretiskt hormon'],
             ['Skin', u'Mycket s\xe4llsynta Angio\xf6dem , Stevens-Johnson syndrom'],
             ['Musculoskeletal', u'Rabdomyolys']]],
           ['Unknown',
            [['Blood', u'Neutropeni'],
             ['Skin', u'Toxisk epidermal nekrolys, erythema multiforme'],
             ['Pregnancy', u'Neonatalt uts\xe4ttningssymtom (se avsnitt 4.6)']]]],
 '_pages': [8, 12],
 u'_rank': 45,
 u'_type': u'LSFU'}