{'_data': [['Very common',
            [['Skin',
              u'Sm\xe4rta vid applikationsst\xe4llet, rodnad vid applikationsst\xe4llet Kl\xe5da vid applikationsst\xe4llet, papler vid applikationsst\xe4llet, vesikler vid']]],
           ['Common',
            [['Skin',
              u'applikationsst\xe4llet, \xf6dem vid applikationsst\xe4llet, svullnad vid applikationsst\xe4llet, torrhet vid applikationsst\xe4llet Urtikaria vid applikationsst\xe4llet, parestesi vid applikationsst\xe4llet, dermatit']]],
           ['Uncommon',
            [['Infections', u'Herpes zoster Centrala och perifera'],
             ['Infections', u'Dysgeusi, hypoestesi, br\xe4nnande k\xe4nsla'],
             ['Eye', u'\xd6gonirritation'],
             ['Cardiac', u'hj\xe4rtklappning'],
             ['Vascular', u'Hypertoni Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular', u'Hosta, svalgirritation'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Kl\xe5da Muskuloskeletala systemet och bindv\xe4v'],
             ['Skin',
              u'Sm\xe4rta i extremiteterna, muskelkramper Allm\xe4nna symptom och/eller symtom vid administreringsst\xe4llet'],
             ['Skin',
              u'vid applikationsst\xe4llet, hyperestesi vid applikationsst\xe4llet, inflammation vid applikationsst\xe4llet, reaktion vid applikationsst\xe4llet, irritation vid applikationsst\xe4llet, bl\xe5m\xe4rken vid applikationsst\xe4llet, perifert \xf6dem'],
             ['Investigations',
              u'Blodtrycksh\xf6jning Enligt kvantitativ sensorisk testning (QST) och neurologiska unders\xf6kningar har ingen behandlingsrelaterad neds\xe4ttning av neurologisk funktion observerats under kliniska studier med patienter med perifer neuropatisk sm\xe4rta. Tillf\xe4lliga sm\xe4rre f\xf6r\xe4ndringar av upplevelsen av v\xe4rme (1\xb0C till 2\xb0C) och av stick med n\xe5got vasst vid applikationsst\xe4llet uppt\xe4cktes vid studier av Qutenza med friska frivilliga f\xf6rs\xf6kspersoner.']]],
           ['Unknown',
            [['Cardiac',
              u'Atrioventrikul\xe4rt block (AV-block) av f\xf6rsta graden, takykardi,']]]],
 '_pages': [5, 5],
 u'_rank': 14,
 u'_type': u'LSFU'}