{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Respiratory', u'Rethosta, bronkit, sinusit, dyspne'],
             ['GI',
              u'Gastrointestinal inflammation, matsm\xe4ltnings-besv\xe4r, bukobehag, dyspepsi, diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'Hudutslag, s\xe4rskilt makulopapul\xe4ra'],
             ['Musculoskeletal', u'Muskelspasmer, myalgi'],
             ['Metabolism', u'\xd6kat blodkalium'],
             ['Vascular', u'Hypotension, ortostatiskt blodtrycksfall, synkope'],
             ['General', u'Br\xf6stsm\xe4rta, tr\xf6tthet']]],
           ['Uncommon',
            [['Cardiac',
              u'Myokardisk ischemi inklusive eller myokardinfarkt , takykardi, arytmi, palpitationer, perifert \xf6dem'],
             ['Blood', u'Eosinofili'],
             ['Nervous system', u'Svindel, parestesi, ageusi,'],
             ['Eye', u'Visuella st\xf6rningar inklusive dimsyn'],
             ['Respiratory', u'Bronkospasm inklusive f\xf6rs\xe4mrad n\xe4sa'],
             ['GI',
              u'Pankreatit (mycket s\xe4llsynta fall av d\xf6dlig utg\xe5ng har rapporterats med ACE-h\xe4mmare) \xf6kade pankreasenzy-mer, tunntarmen, \xf6vre magsm\xe4rta inklusive gastrit, f\xf6rstoppning, muntorrhet'],
             ['Renal',
              u'Nedsatt njurfunktion urinproduktion, tidigare proteinuri, \xf6kning blodkreatinin'],
             ['Skin',
              u'Angio\xf6dem; i mycket s\xe4llsynta fall i luftv\xe4garna f\xe5 en d\xf6dlig pruritus, hyperhidros'],
             ['Musculoskeletal', u'Artralgi'],
             ['Metabolism', u'Anorexi, minskad aptit'],
             ['Vascular', u'Blodvallningar'],
             ['General', u'Pyrexi'],
             ['Hepato', u'\xd6kning och/eller konjugerat bilirubin'],
             ['Reproductive system', u'\xd6verg\xe5ende erektil impotens, minskat libido'],
             ['Psychiatric',
              u'Nedst\xe4mdhet, oro, rastl\xf6shet, s\xf6mnst\xf6rningar inklusive somnolens']]],
           ['Rare',
            [['Blood',
              u'Minskat antal vita blodkroppar (inklusive neutropeni eller agranulocytos) , minskat antal r\xf6da blodkroppar, minskat hemoglobin, blodpl\xe4ttar'],
             ['Nervous system', u'Tremor, balansst\xf6rning'],
             ['Eye', u'Konjunktivit'],
             ['Ear', u'F\xf6rs\xe4mrad h\xf6rsel, tinnitus'],
             ['GI', u'Glossit'],
             ['Renal', u'av'],
             ['Skin', u'Exfoliativ dermatit, urtikaria,'],
             ['Vascular', u'Vaskul\xe4r stenos, hypoperfusion, vaskulit'],
             ['General', u'Asteni'],
             ['Hepato', u'av Kolestatisk hepatocellul\xe4r skada'],
             ['Psychiatric', u'F\xf6rvirring']]],
           ['Very rare', [['Skin', u'Ljusk\xe4nslig -hetsreaktio n']]],
           ['Unknown',
            [['Blood', u'Benm\xe4rgsdepression, pancytopeni, hemolytisk anemi'],
             ['Nervous system',
              u'Cerebral ischemi inklusive ischemisk stroke och transitorisk parosmi'],
             ['GI', u'Aft\xf6s stomatit'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnsons multiforme, pemfigus, psoriasiform dermatit, lichenoida exantem och enantem, alopeci'],
             ['Metabolism', u'Minskat blodnatrium'],
             ['Vascular', u'Raynauds fenomen'],
             ['Immune system',
              u'Anafylaktiska eller anafylaktoida \xf6kning i antinukle\xe4ra antikroppar'],
             ['Hepato',
              u'Akut leversvikt, cytolytisk hepatit (fatal utg\xe5ng har varit mycket s\xe4llsynt)'],
             ['Reproductive system', u'Gynekomasti'],
             ['Psychiatric', u'Uppm\xe4rksamhetsst\xf6rning']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 45,
 u'_type': u'MSFU'}