{'_data': [['Common',
            [['Nervous system', u'och perifera Huvudv\xe4rk, yrsel'],
<<<<<<< HEAD
             ['Respiratory', u'Rethosta, bronkit'],
             ['Skin', u'och subkutan '],
             ['General', u'Tr\xf6tthet, orkesl\xf6shetBr\xf6stsm\xe4rta, pyrexi'],
             ['Hepato', u'ochgallv\xe4gar']]],
=======
             ['Ear', u'och'],
             ['Respiratory', u'Rethosta, bronkit'],
             ['Skin', u'och subkutan '],
             ['General', u'Tr\xf6tthet, orkesl\xf6shetBr\xf6stsm\xe4rta, pyrexi vid'],
             ['Hepato', u'och gallv\xe4gar ']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Cardiac',
              u'Myokardisk ischemi inklusive angina pectoris, takykardi, arytmi, palpitationer, perifert \xf6dem'],
             ['Blood',
              u'Minskat antal vita blodkroppar, minskat antal r\xf6da blodkroppar, minskat hemoglobin, hemolytisk anemi, minskat antal blodpl\xe4ttar'],
             ['Nervous system',
              u'Svindel, parestesi, tremor, balansst\xf6rning, br\xe4nnande k\xe4nsla, dysgeusi, ageusi'],
             ['Eye', u'Visuella st\xf6rningar inklusive dimsyn, konjunktivit'],
             ['Ear', u'Tinnitus'],
             ['Respiratory', u'Sinusit, dyspn\xe9, t\xe4ppt n\xe4sa'],
             ['GI',
              u'Gastrointestinal inflammation, matsm\xe4ltningsbesv\xe4r, bukobehag, dyspepsi, gastrit, illam\xe5ende, f\xf6rstoppning Gingivit p.g.a. hydroklortiazid'],
             ['Skin', u'Angio\xf6dem; i mycket'],
             ['Vascular', u'Hypotension, ortostatiskt blodtrycksfall, synkope, blodvallningar'],
             ['Hepato',
<<<<<<< HEAD
              u'Kolestatisk eller cytolytisk hepatit (fatal utg\xe5ng har varit mycket s\xe4llsynt ), \xf6kning av leverenzymer och/eller konjugerat bilirubin Kolecystit med gallstenp.g.a. hydroklortiazid'],
=======
              u'Kolestatisk eller cytolytisk hepatit (fatal utg\xe5ng har varit mycket leverenzymer och/eller konjugerat bilirubin Kolecystit med gallstenp.g.a. hydroklortiazid'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Reproductive system', u'\xd6verg\xe5ende erektil impotens'],
             ['Psychiatric',
              u'Nedst\xe4mdhet, apati, oro, nervositet, s\xf6mnst\xf6rningar inklusive somnolens']]],
           ['Very rare',
            [['GI',
              u'Kr\xe4kningar, aft\xf6s stomatit, glossit, diarr\xe9, \xf6vre magsm\xe4rta, muntorrhet']]],
           ['Unknown',
            [['Cardiac', u'Hj\xe4rtinfarkt'],
             ['Blood',
              u'Benm\xe4rgsdepression, neutropeni inklusive agranulocytos, pancytopeni, eosinofili, hemokoncentration i samband med v\xe4tskebrist'],
             ['Nervous system',
              u'Cerebral ischemi inklusive ischemisk stroke och transitorisk ischemisk attack, f\xf6rs\xe4mring av psykomotorisk f\xf6rm\xe5ga, parosmi'],
             ['Eye', u'Xantopsi, minskat t\xe5rfl\xf6de p.g.a. hydroklortiazid'],
             ['Ear', u'F\xf6rs\xe4mrad h\xf6rsel'],
             ['Respiratory',
              u'Bronkospasm inklusive f\xf6rs\xe4mrad astma, Allergisk alveolit, icke kardiogent pulmon\xe4rt \xf6dem p.g.a. hydroklortiazid'],
             ['GI',
              u'Pankreatit (mycket s\xe4llsynta fall av d\xf6dlig utg\xe5ng har rapporterats med ACE-h\xe4mmare), \xf6kade pankreasenzymer, angio\xf6dem i tunntarmen, Sialoadenit p.g.a. hydroklortiazid'],
             ['Skin', u'Toxisk epidermal'],
             ['Vascular',
              u'Trombos relaterat till sv\xe5r v\xe4tskebrist, vaskul\xe4r stenos, hypoperfusion, Raynauds fenomen, vaskulit'],
             ['Immune system',
              u'Anafylaktiska eller anafylaktoida reaktioner p\xe5 antingen ramipril eller anafylaktisk reaktion p\xe5 hydroklortiazid, \xf6kning i antinukle\xe4ra antikroppar'],
             ['Hepato', u'Akut leversvikt, kolestatisk gulsot, hepatocellul\xe4r skada'],
             ['Reproductive system', u'Gynekomasti, minskat libido'],
             ['Psychiatric', u'F\xf6rvirring, rastl\xf6shet, uppm\xe4rksamhetsst\xf6rning']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
<<<<<<< HEAD
 u'_rank': 31,
=======
 u'_rank': 32,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}