{'_data': [['Common',
            [['Nervous system', u'yrsel, huvudv\xe4rk.'],
             ['GI', u'f\xf6rstoppning, kr\xe4kningar, illam\xe5ende.'],
             ['General', u'asteni.']]],
           ['Uncommon',
            [['Metabolism', u'anorexi, nedsatt aptit, dehydrering.'],
             ['Psychiatric',
              u'\xe5ngest, s\xf6mnl\xf6shet, f\xf6rvirringstillst\xe5nd, hallucinationer.'],
             ['Nervous system',
              u'letargi, synkope, hypoestesi, somnolens, tremor, postural yrsel.'],
             ['Eye', u'dimsyn, synst\xf6rningar.'],
             ['Ear', u'vertigo, tinnitus.'],
             ['Vascular', u'v\xe4rmevallningar, hypotoni.'],
             ['Respiratory', u'dyspn\xe9, hosta, epistaxis.'],
             ['GI',
              u'buksm\xe4rta, muntorrhet, dyspepsi, flatulens, obehagsk\xe4nsla i buken.'],
             ['Skin', u'pruritus, hyperhydros.'],
             ['Musculoskeletal', u'sm\xe4rta i extremitet, muskelkramp, ledsvullnad.'],
             ['Renal', u'dysuri, hematuri, kromaturi.'],
             ['General', u'tr\xf6tthet, perifert \xf6dem.'],
             ['Investigations',
              u'f\xf6rh\xf6jt blodkreatinin, f\xf6rh\xf6jt blodurea, f\xf6rl\xe4ngt korrigerat QT-intervall, f\xf6rh\xf6jt trombocyt- eller leukocytantal, minskad kroppsvikt.']]],
           ['Rare',
            [['Psychiatric', u'desorientering.'],
             ['Nervous system', u'amnesi, s\xe4nkt medvetandegrad, medvetsl\xf6shet, parosmi.'],
             ['Ear', u'h\xf6rselneds\xe4ttning.'],
             ['Vascular', u'perifer kyla, ortostatisk hypotoni.'],
             ['Respiratory', u'tr\xe5nghetsk\xe4nsla i svalget.'],
             ['GI', u'pankreatit, erosiv duodenit, oral hypoestesi.'],
             ['Skin',
              u'angio\xf6dem, allergisk dermatit, urtikaria, kallsvettningar, hudutslag.'],
             ['Renal', u'akut njursvikt'],
             ['Reproductive system', u'erektil dysfunktion.'],
             ['Investigations',
              u'f\xf6rh\xf6jda niv\xe5er av leverenzym. Biverkningsprofilen var i stort sett likartad i MERLIN-TIMI 36-studien. Under denna l\xe5ngtidsstudie rapporterades ocks\xe5 akut njursvikt med en incidens p\xe5 mindre \xe4n 1 % hos patienter som fick placebo eller ranolazin. Utv\xe4rderingar av patienter som kan anses l\xf6pa h\xf6gre risk f\xf6r biverkningar vid behandling med andra l\xe4kemedel mot angina, t.ex. patienter med diabetes, hj\xe4rtsvikt klass I och II eller obstruktiv luftv\xe4gssjukdom, bekr\xe4ftade att dessa tillst\xe5nd ej var f\xf6renade med kliniskt betydelsefulla \xf6kningar av biverkningsincidensen. \xc4ldre, nedsatt njurfunktion och l\xe5g kroppsvikt: I allm\xe4nhet f\xf6rekom biverkningar oftare hos \xe4ldre patienter och patienter med nedsatt njurfunktion; typerna av biverkningar i dessa undergrupper var dock snarlika dem som s\xe5gs hos populationen i allm\xe4nhet. Av de vanligaste rapporterade biverkningarna f\xf6rekom f\xf6ljande oftare med Ranexa (placebokorrigerade frekvenser) hos \xe4ldre > 75 \xe5r) \xe4n hos yngre patienter (< 75 \xe5r): f\xf6rstoppning (8 % mot 5 %), illam\xe5ende (6 % mot 3 %), hypotoni (5 % mot 1 %) och kr\xe4kningar (4 % mot 1 %). N\xe4r patienter med l\xe4tt eller m\xe5ttligt nedsatt njurfunktion (kreatininclearance > 30\u201380 ml/min) j\xe4mf\xf6rdes med patienter med normal njurfunktion (kreatininclearance > 80 ml/min), var de vanligaste rapporterade biverkningarna och de placebokorrigerade frekvenserna f\xf6rstoppning (8 % mot 4 %), yrsel (7 % mot 5 %) och illam\xe5ende (4 % mot 2 %). I allm\xe4nhet var typen och frekvensen av biverkningar rapporterade hos patienter med l\xe5g kroppsvikt < 60 kg) snarlika dem hos patienter med h\xf6gre vikt (> 60 kg); dock var de placebokorrigerade frekvenserna f\xf6r f\xf6ljande vanliga biverkningar h\xf6gre hos patienter med l\xe5g kroppsvikt \xe4n hos tyngre patienter: illam\xe5ende (14 % mot 2 %), kr\xe4kningar (6 % mot 1 %) och hypotoni (4 % mot 2 %). Laboratoriefynd: Sm\xe5, kliniskt ov\xe4sentliga reversibla h\xf6jningar av serumkreatininniv\xe5erna har iakttagits hos friska f\xf6rs\xf6kspersoner och patienter som behandlades med Ranexa. Det f\xf6rekom ingen njurtoxicitet relaterad till dessa fynd. En njurfunktionsstudie p\xe5 friska frivilliga visade en s\xe4nkning av kreatininclearance utan f\xf6r\xe4ndring av glomerul\xe4r filtrationshastighet, vilket \xe4r i \xf6verensst\xe4mmelse med en h\xe4mning av uts\xf6ndringen av kreatinin i njurtubuli.']]]],
 '_pages': [4, 6],
 u'_rank': 26,
 u'_type': u'LSFU'}