{'_data': [['Very common',
            [['Infections', u'Urinv\xe4gsinfektio n'],
             ['Neoplasms', u'Hudcancer*'],
             ['Blood', u'Trombocytopeni Trombotisk Anemi'],
             ['Immune system', u'\xd6verk\xe4nslighets'],
             ['Metabolism',
              u'Hypokalemi Hypofosfatemi Hyperkolesterol emi Hyperglykemi Hypertri-glyceridemi (hyper-lipidemi)'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Lymfocele Djup Hypertoni'],
             ['GI', u'Buksm\xe4rta Diarr\xe9 F\xf6rstoppning Illam\xe5ende'],
             ['Hepato', u'Onormala leverv\xe4rden'],
             ['Skin', u'Akne Utslag'],
             ['Musculoskeletal', u'Artralgi'],
             ['Renal', u'Proteinuri'],
             ['Reproductive system', u'Ovarialcystor'],
             ['General', u'Perifert \xf6dem Feber Sm\xe4rta'],
             ['Investigations',
              u'\xd6kat laktatdehydro-genas (LDH) i blodet Kreatinin-stegring i blodet']]],
           ['Common',
            [['Infections',
              u'Sepsis Pneumoni Pyelonefrit Herpes simplex Svamp-, virus-och bakteriella infektioner (t.ex. mykobakterie-infektioner, inklusive tuberkulos, Epstein-Barr-virus, CMV och Herpes zoster)'],
             ['Blood',
              u'trombocytopen purpura/hemolyt iskt uremi-syndrom Leukopeni Neutropeni'],
             ['Metabolism', u'Diabetes mellitus'],
             ['Vascular', u'ventrombos'],
             ['Respiratory', u'Pneumonit* Pleural v\xe4tske-utgjutning Epistaxis'],
             ['GI', u'Stomatit Ascites'],
             ['Musculoskeletal', u'Osteonekros'],
             ['Reproductive system',
              u'Menstruations-rubbningar (inklusive amenorr\xe9 och menorragi)'],
             ['General', u'F\xf6rs\xe4mrad l\xe4kning* \xd6dem'],
             ['Investigations',
              u'F\xf6rh\xf6jda halter av ASAT, f\xf6rh\xf6jda halter av ALAT']]],
           ['Uncommon',
            [['Neoplasms', u'Lymfom*/ lymfoproliferati v sjukdom efter transplantation'],
             ['Blood', u'Pancytopeni'],
             ['Cardiac',
              u'Perikardiell v\xe4tska (inklusive hemodynamiskt signifikanta v\xe4tskeansamling ar hos barn och vuxna)'],
             ['Vascular', u'Lungemboli Lymf\xf6dem'],
             ['Respiratory', u'Lungbl\xf6dning Alveol\xe4r'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt*'],
             ['Renal', u'Nefrotiskt syndrom (se avsnitt 4.4)']]],
           ['Rare',
            [['Immune system',
              u'reaktioner, inklusive anafylaktiska/ anafylaktoida reaktioner, angio\xf6dem, exfoliativ dermatit och \xf6verk\xe4nslighets -vaskulit (se avsnitt 4.4)'],
             ['Respiratory', u'proteininlagring'],
             ['Renal', u'Fokal']]],
           ['Unknown',
            [['Infections', u'Clostridium difficile enterokolit'],
             ['Renal', u'segmentell glomerulo-skleros*']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 13],
 u'_rank': 39,
 u'_type': u'MSFU'}