{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Cardiac', u'F\xf6r\xe4ndringar av ST-segment p\xe5 elektrokardiogram'],
             ['Vascular', u'Rodnad'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Mag-tarmbesv\xe4r'],
             ['General', u'Br\xf6stsm\xe4rta']]],
           ['Common',
            [['Nervous system', u'Parestesi, hypestesi, dysgeusi'],
             ['Cardiac',
              u'Angina pectoris, atrioventrikul\xe4rblock, takykardi, hj\xe4rtklappning, andra EKG-avvikelser inklusive f\xf6rl\xe4ngt korrigerat QT-intervall p\xe5 elektrokardiogram'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Tr\xe5ngt i halsen, halsirritation, hosta'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende, oralt obehag'],
             ['Skin', u'Hyperhidros'],
             ['Musculoskeletal',
              u'Rygg-, nack- eller k\xe4ksm\xe4rta, extremitetssm\xe4rta, muskuloskeletalt obehag'],
             ['General', u'Sjukdomsk\xe4nsla, asteni']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner, inklusive utslag, urtikaria, angio\xf6dem, anafylaxi och/eller tr\xe5nghetsk\xe4nsla i halsen'],
             ['Psychiatric', u'\xc5ngest, s\xf6mnl\xf6shet'],
             ['Nervous system',
              u'Konvulsioner, synkope, transitoriska ischemiska attacker, ok\xe4nslighet f\xf6r stimuli, s\xe4nkt medvetandegrad, tremor, somnolens'],
             ['Eye', u'Dimsyn, \xf6gonsm\xe4rta'],
             ['Ear', u'Tinnitus'],
             ['Cardiac',
              u'Hj\xe4rtstillest\xe5nd, myokardinfarkt, fullst\xe4ndigt AV-block, f\xf6rmaksflimmer/f\xf6rmaksfladder, bradykardi'],
             ['Vascular', u'Hypertoni, blekhet, perifer kyla'],
             ['Respiratory', u'Takypn\xe9'],
             ['GI', u'Uppsp\xe4nd buk, diarr\xe9, fekal inkontinens'],
             ['Skin', u'Erytem'],
             ['Musculoskeletal', u'Artralgi'],
             ['General',
              u'Sm\xe4rta p\xe5 injektionsst\xe4llet, allm\xe4n kroppssm\xe4rta Beskrivning av utvalda biverkningar Fatalt hj\xe4rtstillest\xe5nd, livshotande ventrikelarytmier och myokardinfarkt kan vara resultatet av den ischemi som induceras av farmakologiska provokationsmedel. Utrustning f\xf6r hj\xe4rt\xe5terupplivning och utbildad personal skall finnas tillg\xe4nglig f\xf6re administrering av Rapiscan (se avsnitt 4.4). Adenosinreceptoragonister, inklusive Rapiscan, kan h\xe4mma SA- och AV-knutorna och orsaka AV-block av f\xf6rsta, andra eller tredje graden eller sinusbradykardi som kr\xe4ver \xe5tg\xe4rd. I kliniska studier utvecklades AV-block av f\xf6rsta graden (f\xf6rl\xe4ngning av PR-intervallet p\xe5 > 220 msek) hos 3 % av patienterna inom 2 timmar efter administrering av Rapiscan; \xf6verg\xe5ende AV-block av andra graden med ett uteblivet slag observerades hos en patient som fick Rapiscan. Vid erfarenhet efter marknadsf\xf6ring har hj\xe4rtblock av tredje graden och asystoli rapporterats inom n\xe5gra minuter efter administrering av Rapiscan. Adenosinreceptoragonister, inklusive Rapiscan, inducerar arteriell vasodilatation och hypotoni. I kliniska studier observerades s\xe4nkt systoliskt blodtryck (> 35 mm Hg) hos 7 % av patienterna och s\xe4nkt diastoliskt blodtryck (> 25 mm Hg) hos 4 % av patienterna inom 45 minuter efter administrering av Rapiscan. Risken f\xf6r allvarlig hypotoni kan vara h\xf6gre hos patienter med autonom dysfunktion, hypovolemi, stenos i v\xe4nster koronarart\xe4rs huvudstam, hj\xe4rtklaffstenos, perikardit eller perikardiella utgjutningar, eller karotisstenos med cerebrovaskul\xe4r insufficiens. Vid erfarenhet efter marknadsf\xf6ring har synkope och transitoriska ischemiska attacker rapporterats. Regadenoson \xf6kar sympatisk tonus, vilket orsakar \xf6kad hj\xe4rtfrekvens och en f\xf6rkortning av QT-intervallet. Hos en patient med l\xe5ngt QT-syndrom kan sympatisk stimulering resultera i mindre f\xf6rkortning av QT-intervallet \xe4n normalt och kan \xe4ven orsaka en paradoxal f\xf6rl\xe4ngning av QT-intervallet. Hos dessa patienter kan fenomenet med R-p\xe5-T-syndrom f\xf6rekomma, d\xe4r ett extra slag avbryter T-v\xe5gen hos det f\xf6reg\xe5ende slaget, och detta \xf6kar risken f\xf6r ventrikul\xe4r takyarytmi.']]]],
 '_pages': [4, 6],
 u'_rank': 26,
 u'_type': u'LSFU'}