{'_data': [['Very common',
            [['Blood', u'Faktor VIII-inhibitorer -PUP'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Respiratory', u'Dyspn\xe9,'],
             ['GI', u'Kr\xe4kning'],
             ['Skin', u'Urtikaria,'],
             ['Musculoskeletal', u'Artralgi'],
             ['General', u'Asteni,'],
             ['Investigations',
              u'Utvecklingav antikroppar mot ovarieceller fr\xe5n kinesisk hamster (CHO-protein). Uppkomst av FVIII-antikroppar.']]],
           ['Common',
            [['Blood', u'Faktor VIII-inhibitorer -PTP'],
             ['Vascular', u'Bl\xf6dning/hematom'],
             ['GI', u'Illam\xe5ende'],
             ['General',
              u'feber. K\xe4rlaccesskomplikation d\xe4ribland komplikationer i anslutning till permanenta katetrar f\xf6r ven\xf6s tillf\xf6rsel'],
             ['Investigations', u'F\xf6rh\xf6jt']]],
           ['Uncommon',
            [['Immune system', u'Anafylaktoid   reaktion'],
             ['Nervous system', u'Neuropati,  yrsel, somnolens, dysgeusi'],
             ['Cardiac', u'Angina  pectoris,  takykardi, hj\xe4rtklappning'],
             ['Vascular', u'Hypotoni, tromboflebit,vasodilatation, blodvallning'],
             ['Respiratory', u'hosta'],
             ['GI', u'Buksm\xe4rta,   diarr\xe9'],
             ['Skin', u'kl\xe5da,  utslag, hyperhidros'],
             ['Musculoskeletal', u'Myalgi'],
             ['General',
              u'Frossa/ frysning, inflammation vid injektionsst\xe4llet, reaktion vid injektionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet'],
             ['Investigations',
              u'aspartataminotransferas, f\xf6rh\xf6jt alaninaminotransferas, f\xf6rh\xf6jt blodbilirubin, f\xf6rh\xf6jt blodkreatinfosfokinas']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 24,
 u'_type': u'MSFU'}