{'_data': [['Common',
            [['Infections', u'faryngit och rinit'],
             ['Nervous system',
              u'somnolens, huvudv\xe4rk, yrsel, stickningar eller myrkrypningar, hypertoni, hypoestesi, muskelsvaghet'],
             ['Ear', u'yrsel'],
             ['Cardiac', u'palpitationer, takykardi'],
             ['Vascular', u'rodnad'],
             ['Respiratory', u'\xe5tstramningsk\xe4nsla i halsen'],
             ['GI', u'buksm\xe4rta, illam\xe5ende, muntorrhet och dyspepsi.'],
             ['Skin', u'svettningar'],
             ['Musculoskeletal', u'ryggv\xe4rk, myalgi'],
             ['General',
              u'v\xe4rmek\xe4nsla, asteni, br\xf6stsymtom (sm\xe4rta, \xe5tstramnings- och tryckk\xe4nsla) och frossa'],
             ['General',
              u'som ses med eletriptan \xe4r typiska f\xf6r de klassbiverkningar som rapporterats f\xf6r 5-HT -agonister. F\xf6ljande biverkningar har rapporterats efter lansering av produkten: Immunsystemet: allergiska reaktioner som i vissa fall kan vara allvarliga, inklusive angio\xf6dem. Centrala och perifera nervsystemet: serotonergt syndrom, s\xe4llsynta fall av synkope Blodk\xe4rl: hypertension Mag-tarmkanalen: liksom f\xf6r n\xe5gra \xf6vriga 5HT 1B/D1 agonister har s\xe4llsynta fall av ischemisk colit, kr\xe4kningar rapporterats.']]],
           ['Uncommon',
            [['Metabolism', u'aneroxia'],
             ['Psychiatric',
              u'onormala tankar, agitation, f\xf6rvirring, depersonalisering, eufori, depression, insomnia.'],
             ['Eye',
              u'synst\xf6rning, \xf6gonv\xe4rk, ljusskygghet, t\xe5rfl\xf6desst\xf6rning'],
             ['Ear', u'\xf6ronsm\xe4rta, tinnitus'],
             ['Vascular', u'perifer vaskul\xe4r rubbning.'],
             ['Respiratory', u'andf\xe5ddhet, luftv\xe4gsbesv\xe4r och g\xe4spningar.'],
             ['GI', u'diarr\xe9, glossit'],
             ['Skin', u'utslag och kl\xe5da'],
             ['Musculoskeletal', u'artralgi, artros och skelettsm\xe4rta'],
             ['Renal',
              u'\xf6kad frekvens av urintr\xe4ngningar, polyuri och andra urinv\xe4gsbesv\xe4r'],
             ['General',
              u'sjukdomsk\xe4nsla, ansikts\xf6dem, t\xf6rst, \xf6dem och perifert \xf6dem.']]],
           ['Rare',
            [['Infections', u'luftv\xe4gsinfektion'],
             ['Blood', u'lymfadenopati'],
             ['Psychiatric', u'emotionell labilitet'],
             ['Nervous system',
              u'tremor, hyperestesi, ataxi, hypokinesi, talsv\xe5righeter, stupor, smakf\xf6r\xe4ndring'],
             ['Eye', u'konjunktivit'],
             ['Cardiac', u'bradykardi'],
             ['Vascular', u'chock'],
             ['Respiratory', u'astma och r\xf6stf\xf6r\xe4ndringar'],
             ['GI', u'f\xf6rstoppning, esofagit, tung\xf6dem och uppst\xf6tningar'],
             ['Hepato', u'bilirubinemi och ASAT-stegring.'],
             ['Skin', u'urtikaria och andra hudbesv\xe4r'],
             ['Musculoskeletal', u'artrit, myopati och muskelryckningar'],
             ['Reproductive system', u'\xd6mma br\xf6st och menorragi']]]],
 '_pages': [5, 7],
 u'_rank': 35,
 u'_type': u'LSFU'}