{'_data': [['Very common',
            [['Nervous system', u'skelettmuskelrigiditet'],
             ['Vascular', u'hypotension'],
             ['GI', u'illam\xe5ende, kr\xe4kning']]],
           ['Common',
            [['Cardiac', u'bradykardi'],
             ['Vascular', u'postoperativ hypertension'],
             ['Respiratory', u'akut andningsdepression, apn\xe9'],
             ['Skin', u'kl\xe5da'],
             ['General', u'postoperativa frossbrytningar']]],
           ['Uncommon',
            [['Respiratory', u'hypoxi'],
             ['GI', u'f\xf6rstoppning'],
             ['General', u'postoperativ sm\xe4rta']]],
           ['Rare',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inklusive anafylaxi har rapporterats hos patienter som f\xe5tt remifentanil tillsammans med ett eller flera anestesimedel'],
             ['Nervous system', u'sedering (under uppvaknandet efter allm\xe4n anestesi)'],
             ['Cardiac',
              u'asystoli/hj\xe4rtstopp med f\xf6reg\xe5ende bradykardi hos patienter som behandlats med remifentanil i kombination med andra anestetika']]],
<<<<<<< HEAD
           ['Unknown', [['Psychiatric', u'beroende']]]],
 '_pages': [17, 18],
 u'_rank': 15,
=======
           ['Unknown', [['Psychiatric', u'beroende'], ['Skin', u'Sida 17 av 24']]]],
 '_pages': [17, 18],
 u'_rank': 16,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}