{'_data': [['Very common',
            [['Nervous system', u'muskelrigiditet'],
             ['Vascular', u'hypotension'],
             ['GI', u'illam\xe5ende, kr\xe4kning']]],
           ['Common',
            [['Cardiac', u'bradykardi'],
             ['Vascular', u'postoperativ hypertension'],
             ['Respiratory', u'akut andningdepression, apn\xe9'],
             ['Skin', u'pruritus'],
             ['General', u'postoperativa skakningar']]],
           ['Uncommon',
            [['Respiratory', u'hypoxi'],
             ['GI', u'f\xf6rstoppning'],
             ['General', u'postoperativ v\xe4rk']]],
           ['Rare',
            [['Immune system',
              u'allergiska reaktioner inkluderande anafylaktiska reaktioner har rapporterats hos patienter som behandlats med remifentanil i kombination med annat anestetikum'],
             ['Nervous system', u'sedering (under uppvaknandet efter allm\xe4nanestesi)'],
             ['Cardiac',
              u'asystoli/hj\xe4rtstillest\xe5nd med f\xf6reg\xe5ende bradykardi hos patienter som behandlats med remifentanil i kombination med andra anestetika.']]],
           ['Unknown', [['Psychiatric', u'beroende']]]],
 '_pages': [16, 17],
 u'_rank': 15,
 u'_type': u'LSFU'}