{'_data': [['Common', [['Metabolism', u'Hypoglykemi'], ['GI', u'Buksm\xe4rta och diarr\xe9']]],
           ['Rare',
            [['Cardiac',
              u'Kardiovaskul\xe4r sjukdom Typ 2-diabetes \xe4r f\xf6renat med en \xf6kad risk f\xf6r kardiovaskul\xe4r sjukdom. I en epidemiologisk studie rapporterades en h\xf6gre frekvens av akut koronarsyndrom i repaglinidgruppen. Samband \xe4r dock os\xe4kert (se avsnitt 4.4 och 5.1).']]],
           ['Very rare',
            [['Immune system',
              u'Allergi Allm\xe4nna \xf6verk\xe4nslighetsreaktioner (t ex anafylaktisk reaktion), eller immunologiska reaktioner s\xe5som vaskuliter.'],
             ['GI', u'Kr\xe4kning och f\xf6rstoppning'],
             ['Eye',
              u'Synst\xf6rningar Det \xe4r k\xe4nt att \xe4ndringar av blodglukosniv\xe5n kan ge \xf6verg\xe5ende synst\xf6rningar, s\xe4rskilt i inledningen av behandlingen. S\xe5dana st\xf6rningar har endast rapporterats i mycket f\xe5 fall vid ins\xe4ttandet av repaglinid. Inga s\xe5dana fall har orsakat avbrott i behandlingen med repaglinid i kliniska pr\xf6vningar.'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Hepato',
              u'fall har sv\xe5r st\xf6rning av leverfunktionen rapporterats. N\xe5got orsakssamband med repaglinid har dock inte fastst\xe4llts.'],
             ['Hepato',
              u'Leverenzymstegring Leverenzymstegring har rapporterats i enstaka fall vid behandling med repaglinid. I de flesta fall var \xf6kningen lindrig och \xf6verg\xe5ende och mycket f\xe5 patienter avbr\xf6t behandlingen p\xe5 grund av denna stegring.']]],
           ['Unknown',
            [['Metabolism',
              u'Hypoglykemisk koma och hypoglykemisk medvetsl\xf6shet I likhet med andra antidiabetika har hypoglykemiska reaktioner observerats vid behandling med repaglinid. Reaktionerna \xe4r vanligen lindriga och behandlas l\xe4tt genom intag av kolhydrater. I sv\xe5rare fall, som kr\xe4ver hj\xe4lp av v\xe5rdpersonal, kan glukosinfusion vara n\xf6dv\xe4ndig. F\xf6rekomsten av s\xe5dana reaktioner beror, som vid all diabetesterapi, p\xe5 individuella faktorer s\xe5som kostvanor, dosering, motion och stress (se avsnitt 4.4). Interaktioner med andra l\xe4kemedel kan \xf6ka risken f\xf6r hypoglykemi (se avsnitt 4.5). Efter marknadsf\xf6ring av repaglinid har fall av hypoglykemi rapporterats hos patienter som f\xe5tt kombinationsbehandling med metformin eller tiazolidindion.'],
             ['GI',
              u'Illam\xe5ende Gastrointestinala symtom som buksm\xe4rta, diarr\xe9, illam\xe5ende, kr\xe4kning och f\xf6rstoppning har rapporterats i kliniska pr\xf6vningar. Frekvensen och sv\xe5righetsgraden av dessa symtom skilde sig inte fr\xe5n de som observerats med andra perorala insulinfris\xe4ttande antidiabetika.'],
             ['Skin',
              u'\xd6verk\xe4nslighet \xd6verk\xe4nslighetsreaktioner i huden s\xe5som erytem, kl\xe5da, utslag, och urticaria kan upptr\xe4da. P\xe5 grund av skillnad i kemisk struktur finns ej sk\xe4l att misst\xe4nka korsreaktion med sulfonylureider.']]]],
 '_pages': [5, 6],
 u'_rank': 12,
 u'_type': u'LSFU'}