{'_data': [['Very common',
            [['Metabolism', u'a: huvudv\xe4rk'],
             ['Vascular', u'blodvallning'],
             ['GI', u'illam\xe5ende'],
             ['Skin', u'frossbrytningar, feber, sm\xe4rta och obehag, tr\xf6tthet']]],
           ['Common',
            [['Metabolism', u'perifera \xf6dem Centrala och perifera'],
             ['Metabolism',
              u'yrsel, dysgeusi, neuropatisk sm\xe4rta, tremor, hypersomni, hypestesi, parestesi'],
             ['Eye', u'minskad kornealreflex, \xf6kad uts\xf6ndring av t\xe5rv\xe4tska'],
             ['Ear', u'tinnitus, f\xf6rv\xe4rrad tinnitus'],
             ['Cardiac', u'takykardi, palpitationer'],
             ['Vascular', u'hypertoni'],
             ['Vascular',
              u'hosta, heshet, tr\xe5nghetsk\xe4nsla i svalget, dyspn\xe9, nasofaryngit, faryngit, \xf6kad sekretion i halsen, rinorr\xe9'],
             ['GI', u'diarr\xe9, kr\xe4kningar, buksm\xe4rta/-obehag'],
             ['Skin', u'acne, erytem, pruritus, hudutslag, livedo reticularis'],
             ['Skin',
              u'muskuloskeletala besv\xe4r, myalgi, ryggsm\xe4rta, sm\xe4rta i extremiteterna, perifer svullnad, artralgi, ledsvullnad'],
             ['Skin',
              u'f\xf6rv\xe4rrad tr\xf6tthet, v\xe4rmek\xe4nsla, k\xf6ldk\xe4nsla, asteni, br\xf6stsm\xe4rta, tr\xe5nghetsk\xe4nsla i br\xf6stet, influensaliknande sjukdom, utslag vid injektionsst\xe4llet, sjukdomsk\xe4nsla Se \xe4ven avsnitt 4.4. Infusionsrelaterade reaktioner som rapporterats efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning (se \xe4ven avsnitt 4.4 Varningar och f\xf6rsiktighet) kan \xe4ven omfatta hj\xe4rth\xe4ndelser s\xe5som hj\xe4rtarytmier (f\xf6rmaksflimmer, ventrikul\xe4r extrasystole, takyarytmi), myokardischemi och hj\xe4rtsvikt hos patienter med Fabrys sjukdom involverande hj\xe4rtstrukturerna. Infusionsrelaterade symtom kan omfatta yrsel, hyperhidros och hypotoni. De vanligaste biverkningarna var lindriga infusionsrelaterade reaktioner som fr\xe4mst omfattade stelhet, feber, rodnad, huvudv\xe4rk, illam\xe5ende och dyspn\xe9.']]],
           ['Uncommon',
            [['Metabolism', u'parosmi'],
             ['Vascular', u'minskad syrem\xe4ttnad'],
             ['Skin', u'angioneurotiskt \xf6dem, urtikaria'],
             ['Skin',
              u'tyngdk\xe4nsla Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Unknown',
            [['Cardiac',
              u'hj\xe4rtarytmier (f\xf6rmaksflimmer, ventrikul\xe4r extrasystole, takyarytmi), ischemisk hj\xe4rtsjukdom, hj\xe4rtsvikt'],
             ['Vascular', u'hypotoni Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Skin', u'hyperhidros Muskuloskeletala systemet och bindv\xe4v']]]],
 '_pages': [3, 5],
 u'_rank': 22,
 u'_type': u'LSFU'}