{'_data': [['Very common',
            [['Nervous system', u's\xf6mnighet.'],
             ['Nervous system', u'synkope. Vid kombinationsbehandling'],
             ['Nervous system',
              u'dyskinesi. Hos patienter med avancerad Parkinsons sjukdom kan dyskinesi upptr\xe4da under den initiala titreringen av ropinirol. Kliniksa studier har visat att en minskning av levodopadosen kan f\xf6rb\xe4ttra symtomen av dyskinesi (se avsnitt 4.2)'],
             ['GI', u'illam\xe5ende.']]],
           ['Common',
            [['Psychiatric', u'hallucinationer.'],
             ['Psychiatric', u'f\xf6rvirring.'],
             ['Nervous system', u'yrsel (inklusive vertigo).'],
             ['GI', u'halsbr\xe4nna. Vid monoterapi'],
             ['GI', u'kr\xe4kningar, buksm\xe4rtor.'],
             ['General', u'\xf6dem i benen.']]],
           ['Uncommon',
            [['Psychiatric',
              u'psykotiska reaktioner (andra \xe4n hallucinationer) innefattande delirium, vanf\xf6rest\xe4llning, paranoia. Impulskontrollst\xf6rningar inklusive patologiskt hasardspelande, hypersexualitet och \xf6kad libido har rapporterats efter marknadsintroduktionen (se avsnitt 4.4). Vid kombinationsbehandling'],
             ['Nervous system',
              u'pl\xf6tsliga s\xf6mnattacker, uttalad s\xf6mnighet dagtid. Ropinirol har satts i samband med s\xf6mnighet och har i mindre vanliga fall givit upphov till uttalad s\xf6mnighet dagtid och pl\xf6tsliga s\xf6mnattacker. Vid monoterapi'],
             ['Vascular',
              u'postural hypotension, hypotension Postural hypotension eller hypotension \xe4r s\xe4llan allvarlig.']]],
           ['Unknown',
            [['Immune system',
              u'Hypersensitivitetsreaktioner (inklusive urtikaria, angio\xf6dem, utslag och pruritus).'],
             ['Hepato',
              u'leverp\xe5verkan, framf\xf6rallt f\xf6rh\xf6jda leverenzymv\xe4rden.']]]],
 '_pages': [4, 5],
 u'_rank': 15,
 u'_type': u'LSFU'}