{'_data': [['Common',
            [['Metabolism',
              u' Hypokalemi, hypokalcemi och d\xe4rtill relaterade symtom (se avsnitt 4.4 och 4.9)'],
             ['GI',
              u' Vid oral tillf\xf6rsel kv\xe4ljning, illam\xe5ende, kr\xe4kning, anorexi, obstipation (speciellt vid h\xf6g dos under l\xe4ngre tid), fekal klumpbildning, diarr\xe9.']]],
           ['Rare',
            [['Respiratory', u' Akut bronkit, bronkopneumoni (vid inhalation). '],
             ['GI', u' Tarmobstruktion. Ischemisk kolit, gastrointestinal']]]],
 '_pages': [3, 4],
 u'_rank': 4,
 u'_type': u'LSFU2'}