{'_data': [['Common', [['Respiratory', u'Lokal irritation, epistaxis,']]],
           ['Uncommon',
            [['Immune system',
              u'Omedelbara och f\xf6rdr\xf6jda  \xf6verk\xe4nslighetsreaktioner, inklusive urtikaria, rash, dermatit, angio\xf6dem och pruritus.']]],
           ['Rare',
            [['Endocrine',
              u'Tecken och symtom p\xe5  systemiska kortikosteroideffekter, inklusive h\xe4mmad binjurefunktion och h\xe4mmad l\xe4ngdtillv\xe4xt']]],
           ['Very rare',
            [['Immune system', u'Anafylaktisk reaktion'],
             ['Respiratory', u'N\xe4sseptumperforation,  slemhinneulceration.']]],
           ['Unknown', [['Eye', u'Katarakt  Glaukom']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'TSFU'}