{'_data': [['Unknown',
            [['Cardiac',
              u'Palpitationer Mycket vanliga Vanliga (1,8 %) F\xf6rl\xe4ngning av QT-intervallet Vanliga Vanliga (5,3 %)'],
             ['Nervous system',
              u'Huvudv\xe4rk Mycket vanliga Mycket vanliga (17,1 %) Yrsel Mycket vanliga Vanliga (5,5 %) Parestesier Vanliga Ataxi, hypoestesi Mindre vanliga Klonus, somnolens Mindre vanliga Mindre vanliga'],
             ['Respiratory', u'Hosta Vanliga Mycket vanliga (22,7 %)'],
             ['GI',
              u'Kr\xe4kning Mycket vanliga Mycket vanliga (20,2 %) Buksm\xe4rta Mycket vanliga Mycket vanliga (12,1 %) Illam\xe5ende Mycket vanliga Vanliga (6,5 %) Diarr\xe9 Vanliga Vanliga (8,4 %)'],
             ['Skin',
              u'Hudutslag Vanliga Vanliga (2,7 %) Pruritus Vanliga Mindre vanliga Urtikaria, angio\xf6dem** Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Musculoskeletal',
              u'Artralgi Mycket vanliga Vanliga (2,1 %) Myalgi Mycket vanliga Vanliga (2,2 %)'],
             ['Metabolism', u'Anorexi Mycket vanliga Mycket vanliga (16,8 %)'],
             ['General',
              u'Asteni Mycket vanliga Vanliga (5,2 %) Tr\xf6tthet Mycket vanliga Vanliga (9,2 %) G\xe5ngst\xf6rningar Vanliga'],
             ['Immune system', u'\xd6verk\xe4nslighet Ingen k\xe4nd frekvens S\xe4llsynta'],
             ['Hepato',
              u'F\xf6rh\xf6jda leverfunktionsv\xe4rden Mindre vanliga Vanliga (4,1 %)'],
             ['Psychiatric',
<<<<<<< HEAD
              u'S\xf6mnst\xf6rningar Mycket vanliga Vanliga (6,4 %) S\xf6mnl\xf6shet Vanliga Mindre vanliga']]]],
=======
              u'S\xf6mnst\xf6rningar Mycket vanliga Vanliga (6,4 %) S\xf6mnl\xf6shet Vanliga Mindre vanliga *: Dessa v\xe4rden kommer fr\xe5n de sammanfattande tabeller som ins\xe4ndes till l\xe4kemedelsmyndigheterna under utredningen av tre parallella typ II-\xe4ndringar (UK/H/035/001/II/042-044), i juli 2008. **: Dessa biverkningar har rapporterats efter introduktion p\xe5 marknaden. Eftersom dessa \xe4r spontanrapporter fr\xe5n en population av ok\xe4nd storlek \xe4r frekvensen sv\xe5ruppskattad.']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_pages': [5, 6],
 u'_rank': 11,
 u'_type': u'LSFU'}