{'_data': [['Very common',
            [['Infections', u'Virusinfektion, faryngit'],
             ['Blood', u'Anemi, neutropeni'],
             ['Metabolism', u'Anorexi'],
             ['Psychiatric', u'Depression, \xe5ngest, emotionell labilitet, insomnia'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, muntorrhet, nedsatt koncentration'],
             ['Respiratory', u'Dyspn\xe9, hosta'],
             ['GI', u'Diarr\xe9, kr\xe4kningar, illam\xe5ende, buksm\xe4rta'],
             ['Skin', u'Alopeci, pruritus, torr hud, utslag'],
             ['Musculoskeletal', u'Artralgi, myalgi, muskuloskeletal sm\xe4rta'],
             ['General',
              u'Inflammation vid injektionsst\xe4llet, reaktion vid injektionsst\xe4llet, tr\xf6tthet, stelhet, pyrexi, influensaliknande sjukdom, asteni, irritabilitet'],
             ['Investigations', u'Viktminiskning'],
             ['Infections', u'Virusinfektion, faryngit'],
             ['Blood', u'Anemi, neutropeni'],
             ['Endocrine', u'Hypotyroidism'],
             ['Metabolism', u'Anorexi, \xf6kad aptit, minskad aptit'],
             ['Psychiatric', u'Depression, insomnia, emotionell labilitet'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['GI',
              u'Buksm\xe4rta, \xf6vre abdominal sm\xe4rta, kr\xe4kningar, diarr\xe9, illam\xe5ende'],
             ['Skin', u'Alopeci, utslag'],
             ['Musculoskeletal', u'Artralgi, myalgi, muskuloskeletal sm\xe4rta'],
             ['General',
              u'Inflammation vid injektionsst\xe4llet, reaktion vid injektionsst\xe4llet, erytem vid injektionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet, tr\xf6tthet, stelhet, pyrexi, influensaliknande sjukdom, asteni, obehagsk\xe4nsla, irritabilitet'],
             ['Investigations',
              u'Minskad tillv\xe4xthastighet (l\xe4ngd och/eller vikt minskning relaterat till \xe5lder)']]],
           ['Common',
            [['Infections',
              u'Bakterieinfektion (inklusive sepsis), svampinfektion, influensa, luftv\xe4gsinfektion, bronkit, herpes simplex, bih\xe5leinflammation, otitis media, rinit, urinv\xe4gsinfektion'],
             ['Infections', u'Neoplasm (ospecificerad)'],
             ['Blood',
              u'Hemolytisk anemi, leukopeni, trombocytopeni, lymfadenopati, lymfopeni 11'],
             ['Endocrine', u'Hypotyroidism, hypertyroidism'],
             ['Metabolism',
              u'Hyperglykemi, hyperurikemi, hypokalcemi, dehydrering, \xf6kad aptit'],
             ['Psychiatric',
              u'Sj\xe4lvmordstankar, psykos, aggressivt beteende, f\xf6rvirring, agitation, ilska, hum\xf6rf\xf6r\xe4ndring, onormalt beteende, nervositet, s\xf6mnst\xf6rningar, minskad libido, apati, onormalt dr\xf6mmande, gr\xe5tmildhet'],
             ['Nervous system',
              u'Amnesi, f\xf6rs\xe4mrat minne, synkope, migr\xe4n, ataxi, parestesi, dysfoni, smakbortfall, hypoestesi, hyperestesi, hypotoni, somnolens, st\xf6rd uppm\xe4rksamhet, tremor, smakf\xf6r\xe4ndringar'],
             ['Eye',
              u'Synrubbning, dimsyn, konjunktivit, \xf6gonirritation, \xf6gonsm\xe4rta, onormal seende, t\xe5rk\xf6rtelrubbningar, torra'],
             ['Ear',
              u'Vertigo, h\xf6rself\xf6rs\xe4mring/h\xf6rselbortfall, tinnitus, \xf6ronsm\xe4rtor'],
             ['Cardiac', u'Hj\xe4rtklappning, takykardi'],
             ['Vascular', u'Hypotension, hypertension, synkope, rodnad 12'],
             ['Respiratory',
              u'N\xe4sbl\xf6dning, andningsbesv\xe4r, bronkospasm luftv\xe4gar, bih\xe5lebesv\xe4r, n\xe4st\xe4ppa, rinorr\xe9, \xf6kad sekretion i \xf6vre luftv\xe4garna, faryngolarynxsm\xe4rta, improduktiv hosta'],
             ['GI',
              u'Ulcer\xf6s stomatit, stomatit, muns\xe5r, kolit, sm\xe4rta i \xf6vre h\xf6gra kvadranten, dyspepsi, gastroesofagal reflux*, glossit, keilit, buksp\xe4nning, bl\xf6dningar i tandk\xf6ttet, gingivit, l\xf6s avf\xf6ring, tandsjukdom, f\xf6rstoppning, flatulens'],
             ['Hepato', u'Leverf\xf6rstoring, gulsot, hyperbilirubinemi*'],
             ['Skin',
              u'Psoriasis, f\xf6rv\xe4rrad psoriasis, eksem, fotosensitivitetsreaktion, makulopapul\xf6sa utslag, erytemat\xf6sa utslag, nattsvettningar, hyperhidros, dermatit, akne, furunkler, erytem, urtikaria, hudbesv\xe4r, bl\xe5m\xe4rken, \xf6kad svettning, onormal h\xe5rstruktur, nagelbesv\xe4r*'],
             ['Musculoskeletal',
              u'Artrit, ryggsm\xe4rta, muskelspasmer, sm\xe4rta i extremitet'],
             ['Renal', u'Urineringsbesv\xe4r, polyuri, onormal urin'],
             ['Reproductive system',
              u'Kvinnor amenorr\xe9, menorragi, menstruationsrubbningar, dysmenorr\xe9, br\xf6stsm\xe4rtor, \xe4ggstocksbesv\xe4r, vaginala besv\xe4r. M\xe4n: impotens, prostatit, erektil dysfunktion Sexuell dysfunktion (ospecificerad)*'],
             ['General',
              u'Br\xf6stsm\xe4rta, obehag i br\xf6stet, perifert \xf6dem, obehagsk\xe4nsla, sm\xe4rta vid injektionsst\xe4llet, onormal k\xe4nsla, t\xf6rst'],
             ['Investigations',
              u'Bl\xe5sljud fr\xe5n hj\xe4rtat * Eftersom ribavirin alltid f\xf6rskrivs tillsammans med en alfainterferon-produkt och de uppr\xe4knade biverkningarna som \xe5terspeglar erfarenheterna efter marknadsf\xf6ringen inte medger kvantifiering av frekvensen, \xe4r den frekvens som rapporteras ovan h\xe4mtad fr\xe5n kliniska pr\xf6vningar d\xe4r man anv\xe4nt ribavirin i kombination med interferon alfa-2b (pegylerat eller ickepegylerat). En minskning av hemoglobinkoncentrationen med > 4 g/dl observerades hos 30 % av patienterna behandlade med ribavirin och peginterferon alfa-2b och hos 37 % av patienterna behandlade med ribavirin och interferon alfa-2b. Hemoglobinniv\xe5erna sj\xf6nk under 10 g/dl hos upp till 14 % av vuxna patienter och hos 7 % av barn och ungdomar behandlade med ribavirin i kombination med antingen peginterferon alfa-2b eller interferon alfa-2b. De flesta fall av anemi, neutropeni och trombocytopeni var milda (WHO grad 1 eller 2). Det fanns en del mer allvarliga fall av neutropeni hos patienter behandlade med ribavirin i kombination med peginterferon alfa-2b (WHO grad 3; 39 patienter av 186 [21 %] och WHO grad 4; 13 patienter av 186 [7 %]); leukopeni av WHO grad 3 rapporterades ocks\xe5 hos 7 % i denna behandlingsgrupp. En \xf6kning av urinsyra- och indirekt bilirubinv\xe4rde f\xf6rknippad med hemolys observerades hos en del patienter behandlade med ribavirin i kombination med peginterferon alfa-2b eller interferon alfa-2b i kliniska studier, men v\xe4rdena \xe5tergick till utg\xe5ngsniv\xe5erna fyra veckor efter att behandlingen avslutats. Hos patienter med f\xf6rh\xf6jda urinsyrav\xe4rden som behandlades med kombinationsbehandlingen utvecklade mycket f\xe5 patienter gikt. F\xf6r inga av dessa patienter kr\xe4vdes modifiering av behandlingen eller att de avbr\xf6t studien. Patienter med samtidig HCV-/hivinfektion F\xf6r patienter med samtidig HCV-/hivinfektion som f\xe5r ribavirin i kombination med peginterferon alfa-2b, har andra biverkningar (som inte rapporterats hos patienter med monoinfektion) rapporterats i studier med en frekvens p\xe5 > 5 %. Dessa var: oral candidiasis (14 %), f\xf6rv\xe4rvad lipodystrofi (13 %), minskat antal CD4-lymfocyter (8 %), minskad aptit (8 %), \xf6kat gamma-glutamyltransferas (9 %), ryggsm\xe4rta (5 %), \xf6kat blodamylas (6 %), \xf6kad mj\xf6lksyra i blodet (5 %), cytolytisk hepatit (6 %), \xf6kat lipas (6 %) och sm\xe4rta i extremiteter (6 %). Mitokondriell toxicitet: Mitokondriell toxicitet och mj\xf6lksyraacidos har rapporterats hos hivpositiva patienter som erh\xe5ller NRTI behandling och till\xe4gg av ribavirin f\xf6r samtidig HCV-infektion (se avsnitt 4.4). Laboratoriev\xe4rden f\xf6r patienter med samtidig HCV-/hivinfektion: Trots att hematologisk toxicitet som neutropeni, trombocytopeni och anemi intr\xe4ffade oftare hos patienter med samtidig HCV-/hivinfektion, kunde majoriteten behandlas genom modifiering av dosen och behandlingen beh\xf6vde s\xe4llan avbrytas tidigt (se avsnitt 4.4). Hematologiska avvikelser rapporterades oftare hos patienter som erh\xf6ll ribavirin i kombination med peginterferon alfa-2b j\xe4mf\xf6rt med patienter som erh\xf6ll ribavirin i kombination med interferon alfa-2b. I Studie 1 (se avsnitt 5.1) s\xe5gs en minskning i totala antalet neutrofiler under 500 celler/mm hos 4 % (8/194) av patienterna och en minskning av trombocyter under 50 000/mm s\xe5gs hos 4 % (8/194) av de patienter som erh\xf6ll ribavirin tillsammans med peginterferon alfa-2b. Anemi (hemoglobin < 9,4 g/dl) rapporterades hos 12 % (23/194) av de patienter som behandlades med ribavirin i kombination med peginterferon alfa-2b. Minskning av CD4 lymfocyter: Behandling med ribavirin i kombination med peginterferon alfa-2b \xe5tf\xf6ljdes av minskning av totala antalet CD4+ celler inom de f\xf6rsta 4 veckorna utan reduktion av CD4+ celler i procent. Minskningen av antalet CD4+ celler var reversibel vid dosreduktion eller avbrytande av behandling. Anv\xe4ndning av ribavirin i kombination med peginterferon alfa-2b visade ingen negativ p\xe5verkan p\xe5 kontrollen av hivviremi under behandling eller uppf\xf6ljning. Begr\xe4nsade s\xe4kerhetsdata (N = 25) \xe4r tillg\xe4ngliga f\xf6r patienter med samtidig infektion n\xe4r det g\xe4ller antalet CD4+ celler < 200/\u03bcl (se avsnitt 4.4).'],
             ['Infections',
              u'Svampinfektion, bakteriell infektion, lunginfektion, nasofaryngit, streptokockfaryngit, otitis media, sinusit, tandabscess, influensa, oral herpes, herpes simplex, urinv\xe4gsinfektion, vaginit, gastroenterit'],
             ['Infections', u'Neoplasm (ospecificerad)'],
             ['Blood', u'Trombocytopeni, lymfadenopati'],
             ['Endocrine', u'Hypertyroidism, virilism'],
             ['Metabolism', u'Hypertriglyceridemi, hyperurikemi'],
             ['Psychiatric',
              u'Sj\xe4lvmordstankar, aggressivt beteende, f\xf6rvirring, emotionell labilitet, beteenderubbningar, agitation, s\xf6mng\xe5ng, \xe5ngest, f\xf6r\xe4ndrat st\xe4mningsl\xe4ge, rastl\xf6shet, nervositet, s\xf6mnrubbningar, onormalt dr\xf6mmande, apati'],
             ['Nervous system',
              u'Hyperkinesi, tremor, dysfoni, parestesi, hypoestesi, hyperestesi, koncentrationssv\xe5righeter, somnolens, st\xf6rd uppm\xe4rksamhet, d\xe5lig s\xf6mnkvalitet'],
             ['Eye',
              u'Konjunktivit, \xf6gonsm\xe4rta, synrubbningar, t\xe5rk\xf6rtelrubbningar'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Takykardi, palpationer'],
             ['Vascular', u'Pallor, rodnad'],
             ['Respiratory',
              u'Dyspn\xe9, takypn\xe9, n\xe4sbl\xf6dning, hosta, n\xe4st\xe4ppa, n\xe4sirritation, rinorr\xe9, nysningar, faryngolaryngeal sm\xe4rta'],
             ['GI',
              u'Muns\xe5r, ulcer\xf6s stomatit,stomatit, aft\xf6s stomatit, keilos, dyspepsi, glossit, sura uppst\xf6tningar, rektala besv\xe4r, gastrointestinala besv\xe4r, f\xf6rstoppning, l\xf6s avf\xf6ring, tandv\xe4rk, tandbesv\xe4r, magbesv\xe4r, oral sm\xe4rta'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin',
              u'Pruritus, fotosensitivitetsreaktion, makulopapul\xf6sa utslag, eksem, hyperhidros, akne, hudbesv\xe4r, nagelbesv\xe4r, hudmissf\xe4rgning, torr hud, erytem, bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Sm\xe4rta i extremitet, ryggsm\xe4rta, muskelkontraktur'],
             ['Renal', u'Enures, urineringsbesv\xe4r, urininkontinens, proteinuri'],
             ['Reproductive system',
              u'Flickor amenorr\xe9, menorragi, menstruationsrubbningar, vaginala besv\xe4r Pojkar: testikelsm\xe4rta'],
             ['General',
              u'Br\xf6stsm\xe4rta, \xf6dem, sm\xe4rta, pruritus vid injektionsst\xe4llet, utslag vid injektionsst\xe4llet, torrhet vid injektionsst\xe4llet, k\xf6ldk\xe4nsla'],
             ['Investigations',
              u'\xd6kat tyreoideastimulerande hormon i blodet, \xf6kat tyreoglobulin'],
             ['Injury', u'Hudlaceration']]],
           ['Uncommon',
            [['Infections', u'Infektion vid injektionsst\xe4llet, nedre luftvgsinfektion'],
             ['Immune system', u'\xd6verk\xe4nslighet mot l\xe4kemedlet'],
             ['Metabolism', u'Diabetes, hypertriglyceridemi*'],
             ['Psychiatric', u'Sj\xe4lvmordsf\xf6rs\xf6k, panikattack, hallucination'],
             ['Nervous system', u'Neuropati, perifer neuropati'],
             ['Cardiac', u'Hj\xe4rtinfarkt'],
             ['GI', u'Pankreatit, munsm\xe4rta'],
             ['Musculoskeletal', u'Bensm\xe4rta, muskelsvaghet'],
             ['General', u'Ansikts\xf6dem'],
             ['Infections',
              u'Pneumoni, ascariasis, enterobiasis, herpes zoster, cellulit Neoplasier, benigna, maligna och ospecificerade (inklusive cystor och polyper)'],
             ['Psychiatric',
              u'Onormalt beteende, s\xe4nkt st\xe4mningsl\xe4ge, emotionell rubbning, r\xe4dsla, mardr\xf6mmar'],
             ['Nervous system', u'Neuralgi, letargi, psykomotorisk hyperaktivitet'],
             ['Eye', u'Konjunktival bl\xf6dning, \xf6gonkl\xe5da, keratit, dimsyn, fotofobi'],
             ['Vascular', u'Hypertension 16'],
             ['Respiratory', u'V\xe4sande/pipande andning, n\xe4sbesv\xe4r'],
             ['GI', u'Gingivit'],
             ['Hepato', u'Hepatomegali'],
             ['Skin', u'Pigmentf\xf6r\xe4ndringar, atopisk dermatit, hudexfoliation'],
             ['Reproductive system', u'Flickor dysmenorr\xe9'],
             ['General',
              u'Br\xf6stkorgsbesv\xe4r, ansiktssm\xe4rta, induration vid injektionsst\xe4llet'],
             ['Investigations', u'Anti-tyreoid-antikropp-positiv'],
             ['Injury',
              u'Kontusion De flesta \xe4ndringarna av laboratoriev\xe4rden i den kliniska studien med ribavirin och peginterferon alfa-2b var milda eller m\xe5ttliga. Minskning av hemoglobin, vita blodkroppar, trombcyter, neutrofiler och \xf6kning av bilirubin kan kr\xe4va dosreduktion eller att behandlingen avbryts permanent (se avsnitt 4.2). F\xf6r\xe4ndringar i laboratoriev\xe4rden observerades hos n\xe5gra av patienterna i den kliniska studien med ribavirin i kombination med peginterferon alfa-2b, men v\xe4rdena \xe5tergick till utg\xe5ngsv\xe4rdet inom n\xe5gra f\xe5 veckor efter avslutad behandling. 17']]],
           ['Rare',
            [['Infections',
              u'Pneumoni* Neoplasier, benigna, maligna och ospecificerade (inklusive cystor och polyper)'],
             ['Immune system', u'Sarcoidos*, reumatoid artrit (debut eller f\xf6rv\xe4rrad)'],
             ['Endocrine', u'Diabetes'],
             ['Psychiatric', u'Bipol\xe4r sjukdom*'],
             ['Nervous system', u'Kramper (konvulsion)*'],
             ['Eye',
              u'Bl\xf6dningar i retina*, retinopatier (inklusive makula\xf6dem)*, ocklusion i retinalart\xe4r*, ocklusion i retinalven*, synnervsneurit*, papill\xf6dem*, f\xf6rlust av synsk\xe4rpa eller synf\xe4lt*, retinalt exsudat*'],
             ['Cardiac', u'Kardiomyopati*, arytmi*'],
             ['Vascular', u'Vaskulit'],
             ['GI', u'Ischemisk kolit'],
             ['Skin', u'Kutan sarkoidos'],
             ['Musculoskeletal', u'Rabdomyolys*, myosit*'],
             ['Renal', u'Njursvikt, njurinsufficiens*'],
             ['General', u'Nekros vid injektionsst\xe4llet']]],
           ['Very rare',
            [['Blood',
              u'Aplastisk anaemi* Ren erytrocytaplasi, idiopatisk trombocytopen purpura, trombotisk trombocytopen purpura'],
             ['Psychiatric',
              u'Sj\xe4lvmord* Tankar p\xe5 mord*, maniska tillst\xe5nd*, f\xf6r\xe4ndrat sinnestillst\xe5nd'],
             ['Nervous system',
              u'Cerebrovaskul\xe4r bl\xf6dning*, cerebrovaskul\xe4r ischaemi*, encefalopati*, polyneuropati*'],
             ['Cardiac', u'K\xe4rlkramp* Hj\xe4rts\xe4cksutgjutning*, perikardit*'],
             ['Vascular', u'Perifer ischemi*'],
             ['Respiratory', u'Lunginfiltrat*, pneumonit*, interstitiell pneumonit*'],
             ['GI', u'Ulcer\xf6s kolit* Tandlossning, tandproblem'],
             ['Hepato', u'Levertoxicitet (inklusive d\xf6dsfall)*'],
             ['Skin',
              u'Stevens Johnson syndrom*, toxisk epidermal nekrolys*, erytema multiforme*'],
             ['Renal', u'Nefrotiskt syndrom*']]],
           ['Unknown',
            [['Immune system',
              u'Vogt-Koyanagi-Harada syndrom, systemisk lupus erythematosus, vaskulit, akuta \xf6verk\xe4nslighetsreaktioner inklusive urtikaria, angio\xf6dem, bronkokonstriktion, anafylaxi'],
             ['Nervous system', u'Ansiktsf\xf6rlamning, mononeuropatier'],
             ['Investigations', u'13']]]],
 '_pages': [11, 17],
 u'_rank': 111,
 u'_type': u'LSFU'}