{'_data': [[u'Unknown',
            [['Infections', u'Infektion UNS*   Sepsis   Pneumoni,   prim\xe4r atypisk'],
             ['Blood', u'Leukopeni UNS*,   Bl\xf6dning,   Hemolys   trombocytopeni   anemi,'],
             ['Immune system', u'\xd6verk\xe4nslig-   Anafylaktisk   Anafylaktisk'],
             ['Nervous system',
              u'Insomni   Somnolens,   Dysgeusi,   afoni   parestesi,   perifer'],
             ['Cardiac', u'Hj\xe4rt-   Perikardiell   Takykardi,'],
             ['Vascular', u'Hypotoni,   Akut   Flebit'],
             ['Respiratory', u'Lung-   Lungfibros'],
             ['GI',
              u'Illam\xe5ende,   Diarr\xe9,   Bl\xf6dande   kr\xe4kningar   f\xf6rstoppning,   esofagit,'],
             ['Skin',
              u'Alopeci, hud-   Erytem,   f\xf6r\xe4ndringar   dermatit, kl\xe5da,   UNS*   makulo-'],
             ['Reproductive system', u'Amenorr\xe9   Infertilitet'],
             ['General', u'Slemhinne-   Sm\xe4rta, fross-   Multiorgan-'],
             ['General', u'anorexi']]]],
 '_pages': [4, 6],
 u'_rank': 12,
 u'_type': u'LFSU'}