{'_data': [['Common',
            [['General',
              u'Reaktioner vid injektionsst\xe4llet (bl\xe5m\xe4rke, sm\xe4rta, reaktion, svullnad, v\xe4rmek\xe4nsla, bl\xf6dning, irritation eller utslag vid infusion/injektions st\xe4llet)']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet inklusive anafylaxi'],
             ['Metabolism', u'Minskad aptit \xd6kad aptit'],
             ['Nervous system',
              u'Yrsel Dysgeusi Huvudv\xe4rk Somnolens Br\xe4nnande k\xe4nsla'],
             ['Vascular',
              u'Hypotension (hypotension, minskat blodtryck) Vallningar (vallningar, blodvallningar) Hypertension (hypertension, accelererad hypertension)'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI',
              u'Diarr\xe9 F\xf6rstoppning Illam\xe5ende Buksm\xe4rta (utsp\xe4nd buk, sm\xe4rta i \xf6vre buken, obehagsk\xe4nsla buken) Kr\xe4kning Missf\xe4rgad avf\xf6ring'],
             ['Skin',
              u'Utslag (utslag, allm\xe4n hudrodnad, utslag med kl\xe5da, urtikaria) Kl\xe5da (allm\xe4n kl\xe5da) Bl\xe5m\xe4rken Svettningar (hyperhidros, nattliga svettningar) Hudhyperpigment ering Hudreaktion'],
             ['Musculoskeletal',
              u'Muskel/led sm\xe4rta eller stelhet (artralgi, myalgi, muskelsvaghet, muskuloskeletal stelhet) Ryggsm\xe4rta Muskelspasmer'],
             ['General',
              u'Tr\xf6tthet (asteni, tr\xf6tthet) Br\xf6stsm\xe4rta (obehagsk\xe4nsla i br\xf6stet, br\xf6stsm\xe4rta) Frossbrytningar Feber (v\xe4rmek\xe4nsla, pyrexi)'],
             ['Investigations', u'F\xf6rh\xf6jt serumferritin'],
             ['Injury', u'Bl\xe5m\xe4rke']]],
           ['Rare',
            [['Blood', u'Eosinofili'],
             ['Metabolism', u'Dehydrering Gikt Hyperkalemi'],
             ['Nervous system', u'Parestesier'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de Dimsyn'],
             ['Respiratory', u'Epistaxis'],
             ['GI', u'Muntorrhet Dyspepsi Glossodyni'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Investigations', u'S\xe4nkt blodglukos']]],
           ['Unknown',
            [['Immune system', u'Livshotande anafylaktiska/ anafylaktoida reaktioner'],
             ['Nervous system', u'Synkope Ej kontaktbar S\xe4nkt medvetande grad'],
             ['Cardiac',
              u'Takykardi/arytmi, hj\xe4rtstopp Kardiorespiratoris kt stopp Myokardinfarkt Cyanos Hj\xe4rtsvikt med kongestion'],
             ['Vascular', u'Vasodilatation'],
             ['Respiratory',
              u'Bronkospasm Hosta Hyperventilation Hypoxi Laryngealt \xf6dem Faryngealt \xf6dem Andningsstopp Andningssvikt Svalgirritation Svullnad i svalget V\xe4sande andning'],
             ['GI', u'Svullna l\xe4ppar Svullen tunga'],
             ['Skin', u'Angio\xf6dem'],
             ['General',
              u'Missf\xe4rgning vid injektionsst\xe4llet Kl\xe5da vid injektionsst\xe4llet'],
             ['Investigations', u'Svag puls S\xe4nkt syrgasm\xe4ttnad']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 7],
 u'_rank': 29,
 u'_type': u'MSFU'}