{'_data': [['Very common',
            [['GI', u'illam\xe5ende'],
             ['Hepato',
              u'onormala leverfunktionprover*. \xd6kning av alaninaminotransferas uppstod vanligtvis inom 3 m\xe5nader efter att behandling med riluzol p\xe5b\xf6rjats; dessa var vanligtvis \xf6verg\xe5ende och v\xe4rdena \xe5tergick till under 2 g\xe5nger ULN efter 2-6 m\xe5nader medan behandlingen fortsatte. F\xf6rh\xf6jda v\xe4rden kan vara associerade med ikterus. Hos patienter (n=20) i kliniska studier med ALAT-f\xf6rh\xf6jning som var mer \xe4n 5 g\xe5nger ULN, avbr\xf6ts behandlingen och v\xe4rden \xe5tergick i de flesta fall till under 2 g\xe5nger ULN inom 2-4 m\xe5nader (se avsnitt 4.4).'],
             ['General', u'asteni']]],
           ['Common',
            [['Nervous system', u'huvudv\xe4rk, yrsel, oral parestesi och somnolens'],
             ['Cardiac', u'takykardi'],
             ['GI', u'diarr\xe9, buksm\xe4rta, kr\xe4kningar'],
             ['General', u'sm\xe4rta']]],
           ['Uncommon',
            [['Blood', u'anemi'],
             ['Immune system', u'anafylaktisk reaktion, angio\xf6dem'],
             ['Respiratory', u'interstitiell lungsjukdom (se avsnitt 4.4)'],
             ['GI', u'pankreatit']]],
           ['Unknown',
            [['Blood', u'sv\xe5r neutropeni (se avsnitt 4.4)'], ['Hepato', u'hepatit']]]],
 '_pages': [3, 4],
 u'_rank': 13,
 u'_type': u'LSFU'}