{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk (1,8 % mot 1,4 %)'],
             ['GI',
              u'f\xf6rstoppning (5,0 % mot 4,8 %), dyspepsi (4,5 % mot 4,1 %), illam\xe5ende (4,3 % mot 4,0 %), magsm\xe4rtor (3,5 % mot 3,3 %), diarr\xe9 (3,0 % mot 2,7 %)'],
             ['Musculoskeletal', u'muskuloskeletala sm\xe4rtor (2,1 % mot 1,9 %)']]],
           ['Uncommon',
            [['Eye', u'irit*'],
             ['GI',
              u'gastrit (0,9 % mot 0,7 %), esofagit (0,9 % mot 0,9 %), dysfagi (0,4 % mot 0,2 %) duodenit (0,2 % mot 0,1 %), esofaguss\xe5r (0,2 % mot 0,2 %)']]],
           ['Rare',
            [['GI', u'glossit (<0,1 % mot 0,1 %), esofagusstriktur (<0,1 % mot 0,0 %)'],
             ['Investigations', u'onormala leverfunktionstester*']]],
           ['Unknown',
            [['Eye', u'Irit, uveit'],
             ['Musculoskeletal', u'Osteonekros i k\xe4ken.'],
             ['Skin',
              u'\xd6verk\xe4nslighet och hudreaktioner, d\xe4ribland angio\xf6dem, generaliserat utslag samt bull\xf6sa hudreaktioner, vissa allvarliga inklusive enstaka fall av Steven Johnsons syndrom och toxisk epidermal nekrolys och leukocytoklastisk vaskulit. H\xe5ravfall.'],
             ['Immune system', u'Anafylaktiska reaktioner'],
             ['Hepato',
              u'Allvarliga leversjukdomar. I de flesta rapporterade fall var patienterna behandlade \xe4ven med andra produkter k\xe4nda f\xf6r att orsaka leversjukdomar. Under marknadsf\xf6ringen har f\xf6ljande reaktioner rapporterats (s\xe4llsynta): Atypiska subtrokant\xe4ra och diafyseala femurfrakturer (bisfosfonatklassbiverkning).']]]],
 '_pages': [4, 5],
 u'_rank': 12,
 u'_type': u'LSFU'}