{'_data': [['Very common', [['Psychiatric', u'S\xf6mnl\xf6shet']]],
           ['Common',
            [['Infections',
              u'Pneumoni, influensa, bronkit,  \xf6vre luftv\xe4gsinfektion, urinv\xe4gsinfektion'],
             ['Metabolism', u'Aptit\xf6kning, aptitminskning'],
             ['Psychiatric', u''],
             ['Psychiatric', u'\xc5ngest, agitation,  s\xf6mnst\xf6rning'],
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Takykardi'],
             ['Respiratory',
              u'Dyspn\xe9, n\xe4sbl\xf6dning, hosta,  n\xe4st\xe4ppa, faryngolaryngeal sm\xe4rta'],
             ['GI',
              u'Kr\xe4kningar, diarr\xe9,  f\xf6rstoppning, illam\xe5ende, buksm\xe4rta, dyspepsi, muntorrhet, magbesv\xe4r'],
             ['Skin', u'Hudutslag, erytem'],
             ['Musculoskeletal', u'Ledv\xe4rk, ryggsm\xe4rta,  extremitetssm\xe4rta'],
             ['Renal', u'Enures'],
             ['General', u'Feber, tr\xf6tthet, perifert \xf6dem,  asteni, br\xf6stsm\xe4rta']]],
           ['Uncommon',
            [['Infections',
              u'Sinuit, virusinfektion,  \xf6roninfektion, tonsillit,  cellv\xe4vsinflammation, mediaotit, \xf6goninfektion, lokaliserad infektion, akarodermatit, luftv\xe4gsinfektion, cystit, onykomykos'],
             ['Blood', u'Anemi, trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, mani,  minskad libido, h\xe5gl\xf6shet,  nervositet'],
             ['Eye',
              u'Konjunktivit, okul\xe4r  hyperemi, uts\xf6ndring av  \xf6gonsekret, \xf6gonsvullnad, \xf6gontorrhet, \xf6kat t\xe5rfl\xf6de, fotofobi'],
             ['Ear', u'\xd6ronv\xe4rk, tinnitus'],
             ['Cardiac',
              u'Atrioventrikul\xe4rt block,  sk\xe4nkelblock,  f\xf6rmaksflimmer, sinusbradykardi, palpitationer'],
             ['Vascular', u'Hypotension, ortostatisk  hypotension, rodnad'],
             ['Respiratory',
              u'V\xe4sande andning,  aspirationspneumoni,  lungstas, lungsjukdom, rassel, stas i andningsv\xe4garna, dysfoni'],
             ['GI', u'Dysfagi, gastrit,  fecesinkontinens, fekalom'],
             ['Skin',
              u'Angio\xf6dem, hudlesion,  hudproblem, kl\xe5da, akne,  missf\xe4rgning av huden, h\xe5ravfall, seborroiskt eksem, torr hud, hyperkeratos'],
             ['Musculoskeletal',
              u'Muskelsvaghet,  muskelsm\xe4rta, nacksm\xe4rta,  ledsvullnad, avvikande kroppsh\xe5llning, ledstelhet, muskuloskeletal br\xf6stsm\xe4rta'],
             ['Renal', u'Urinretention, dysuri,  urininkontinens, pollakisuri'],
             ['Reproductive system',
              u'Amenorr\xe9, sexuell  dysfunktion, erektil  dysfunktion, ejakulationsst\xf6rning, galaktorr\xe9, gynekomasti, menstruationsrubbning, vaginal flytning'],
             ['General',
              u'Ansikts\xf6dem, g\xe5ngrubbning,  k\xe4nsla av att inte m\xe5 som  vanligt, tr\xf6ghet, influensaliknande sjukdom, t\xf6rst, obehagsk\xe4nsla i br\xf6stet, frossa']]],
           ['Rare',
            [['Infections', u'Kronisk mediaotit'],
             ['Blood', u'Granulocytopeni'],
             ['Immune system', u'L\xe4kemedels\xf6verk\xe4nslighet'],
             ['Psychiatric', u'Anorgasmi, k\xe4nslom\xe4ssig  avtrubbning'],
             ['Eye', u'F\xf6rs\xe4mrad synsk\xe4rpa,  \xf6gonrullning, glaukom'],
             ['Respiratory', u'S\xf6mnapn\xe9syndrom,  hyperventilation'],
             ['GI', u'Tarmobstruktion, pankreatit,  l\xe4ppsvullnad, keilit'],
             ['Skin', u'Mj\xe4ll'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['General',
              u'Generaliserat \xf6dem,  hypotermi, l\xe4kemedelsabstinenssyndrom, perifer kyla']]],
           ['Unknown',
            [['Blood', u'Agranulocytos'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom  (se avsnitt 4.6)'],
             ['Reproductive system', u'Priapism']]]],
 '_pages': [8, 13],
 u'_rank': 41,
 u'_type': u'TSFU'}