{'_data': [['Very common',
<<<<<<< HEAD
            [['Psychiatric', u'S\xf6mn-l\xf6sh et, nervositet'],
             ['Nervous system', u'Huvud-v\xe4r k']]],
=======
            [['Psychiatric', u'S\xf6mn-l\xf6shet, nervositet'],
             ['Nervous system', u'Huvud-v\xe4rk']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Common',
            [['Infections', u'Nasofaryngit'],
             ['Metabolism',
              u'Anorexi, minskad aptit, m\xe5ttligt reducerad viktuppg\xe5ng och l\xe4ngdtillv\xe4xt under l\xe5ngvarig anv\xe4ndning hos barn*'],
             ['Psychiatric',
<<<<<<< HEAD
              u'Anorexi, affekt-labilite t, aggression*, agitation*, \xe5ngest*, depression*, irritabilitet, onormalt beteende'],
             ['Nervous system',
              u'Yrsel, dyskinesi, psyko-motori sk hyper-aktivit et, somnolens'],
             ['Cardiac', u'Arrytmi, takykardi, hj\xe4rt-klappni ng'],
             ['Vascular', u'Hypertoni'],
             ['Respiratory', u'Hosta, sm\xe4rta'],
=======
              u'Anorexi, affekt-labilitet, aggression*, agitation*, \xe5ngest*, depression*, irritabilitet, onormalt beteende'],
             ['Nervous system', u'Yrsel, dyskinesi, psyko-motorisk hyper-aktivitet, somnolens'],
             ['Cardiac', u'Arrytmi, takykardi, hj\xe4rt-klappning'],
             ['Vascular', u'Hypertoni'],
             ['Respiratory', u'Hosta, sm\xe4rta i svalg/strupe'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI',
              u'Buksm\xe4rta, diarr\xe9, illam\xe5ende, magbesv\xe4r och kr\xe4kningar. Muntorrhet.'],
             ['Skin', u'Alopeci, kl\xe5da, utslag, urtikaria'],
             ['Musculoskeletal', u'Artralgi'],
             ['General',
<<<<<<< HEAD
              u'Pyrexi, tillv\xe4xtf\xf6r-dr \xf6jning under l\xe5ngvarig anv\xe4ndning hos barn*'],
             ['Investigations',
              u'F\xf6r\xe4ndringar i blodtryck och hj\xe4rtfrekvens (vanligtvis \xf6kning)*, viktminsk-ni']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslig-het sreaktioner som angioneurotiskt \xf6dem, anafylaktiska reaktioner, \xf6ronsvullnad, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd, urtikaria, pruritus och utslag'],
             ['Psychiatric',
              u'Psykotiska tillst\xe5nd*, h\xf6rsel-, syn-och k\xe4nselhallucina-tioner*, ilska, sj\xe4lvmords-tank ar*, hum\xf6r-f\xf6r\xe4ndrin g, hum\xf6r-sv\xe4ngnin gar, rastl\xf6shet,'],
=======
              u'Pyrexi, tillv\xe4xtf\xf6r-dr\xf6jning under l\xe5ngvarig anv\xe4ndning hos barn*'],
             ['Investigations', u'F\xf6r\xe4ndringar i blodtryck och']]],
           ['Uncommon',
            [['Immune system',
              u'\xd6verk\xe4nslig-hetsreaktioner som angioneurotiskt \xf6dem, anafylaktiska reaktioner, \xf6ronsvullnad, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd, urtikaria, pruritus och utslag'],
             ['Psychiatric',
              u'Psykotiska tillst\xe5nd*, h\xf6rsel-, syn-och k\xe4nselhallucina-tioner*, ilska, sj\xe4lvmords-tankar*, hum\xf6r-f\xf6r\xe4ndring, hum\xf6r-sv\xe4ngningar, rastl\xf6shet,'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Sedation, tremor'],
             ['Eye', u'Diplopi, dimsyn'],
             ['Cardiac', u'Br\xf6stsm\xe4rta'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'F\xf6rstoppning'],
             ['Hepato', u'\xd6kning av leverenzymer'],
             ['Skin',
<<<<<<< HEAD
              u'Angio-neurotisk t \xf6dem, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd'],
             ['Musculoskeletal', u'Myalgi, muskel-rycknin gar'],
=======
              u'Angio-neurotiskt \xf6dem, vesikul\xf6sa tillst\xe5nd, exfoliativa tillst\xe5nd'],
             ['Musculoskeletal', u'Myalgi, muskel-ryckningar'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Renal', u'Hematuri'],
             ['General', u'Br\xf6stsm\xe4rta, tr\xf6tthet'],
             ['Investigations', u'Bl\xe5sljud p\xe5 hj\xe4rtat*, \xf6kning av leverenzymer']]],
           ['Rare',
<<<<<<< HEAD
            [['Psychiatric', u'Mani*, desorien-terin g, libido-st\xf6rnin gar'],
             ['Eye', u'Sv\xe5righeter att ackom-moder a, mydriasis, synst\xf6r-ninga r'],
             ['Cardiac', u'Angina pectoris'],
             ['Skin', u'Hyperhidros, makul\xe4ra utslag, erytem'],
             ['Reproductive system', u'Gyneko-mast']]],
           ['Very rare',
            [['Blood', u'leukopeni, trombocyto-p'],
             ['Psychiatric',
              u'Sj\xe4lvmords-f \xf6rs\xf6k (inklusive fullbordat sj\xe4lvmord)*, \xf6verg\xe5ende depressiv sinnes-st\xe4mni ng*, onormala tankar, apati,'],
             ['Nervous system',
              u'Konvulsio-ne r, koreoa-tetoid a r\xf6relser, reversibla ischemiska bortfallssymt om, malignt neuroleptika-syndrom (NMS; rapporterna var d\xe5ligt dokumen-tera de och i de flesta fall fick patienterna \xe4ven andra l\xe4kemedel. Metylfenidats roll \xe4r d\xe4rf\xf6r oklar.)'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, hj\xe4rtinfarkt'],
             ['Vascular', u'Cerebral arterit och/eller ocklusion, perifer kyla,'],
             ['Hepato', u'Onormal leverfunk-tio n inklusive leverkoma'],
             ['Skin', u'Erythema multiforme, exfoliativ dermatit, fixt l\xe4kemedels-u tslag'],
             ['Musculoskeletal', u'Muskel-kram per'],
             ['General', u'Pl\xf6tslig kardiell d\xf6d*'],
             ['Investigations',
              u'\xd6kning av alkaliska fosfater och bilirubin i blodet, minskat antal trombocyter,']]],
           ['Unknown',
            [['Blood', u'Pancytopeni'],
             ['Psychiatric',
              u'Vanf\xf6rest\xe4ll-ni ngar*, tanke-st\xf6rning ar*, f\xf6rvirrings-tills t\xe5nd, fall av missbruk och beroende har beskrivits, oftare med formuleringar'],
             ['Nervous system',
              u'Cerebrovas-kul \xe4ra st\xf6rningar* (inklusive vaskulit, cerebral bl\xf6dning, cerebro-vaskul \xe4ra h\xe4ndelser, cerebral artrit, cerebral ocklusion), grand mal-anfall*, migr\xe4n'],
             ['Cardiac',
              u'Supraventri-ku l\xe4r takykardi, bradykardi, ventrikul\xe4ra extrasystolier, extrasystolier'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General', u'Obehagsk\xe4nsla i br\xf6stet, hyperpyrexi']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 14],
 u'_rank': 48,
=======
            [['Psychiatric', u'Mani*, desorien-tering, libido-st\xf6rningar'],
             ['Eye', u'Sv\xe5righeter att ackom-modera, mydriasis, synst\xf6r-ningar'],
             ['Cardiac', u'Angina pectoris'],
             ['Skin', u'Hyperhidros, makul\xe4ra utslag, erytem'],
             ['Reproductive system', u'Gyneko-masti']]],
           ['Very rare',
            [['Blood', u'Anemi, leukopeni, trombocyto-peni, trombocyto-penisk purpura'],
             ['Psychiatric',
              u'Sj\xe4lvmords-f\xf6rs\xf6k (inklusive fullbordat sj\xe4lvmord)*, \xf6verg\xe5ende depressiv sinnes-st\xe4mning*, onormala tankar, apati,'],
             ['Nervous system',
              u'Konvulsio-ner, koreoa-tetoida r\xf6relser, reversibla ischemiska bortfallssymt om, malignt neuroleptika-syndrom (NMS; rapporterna var d\xe5ligt dokumen-terade och i de flesta fall fick patienterna \xe4ven andra l\xe4kemedel. Metylfenidats roll \xe4r d\xe4rf\xf6r oklar.)'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd, hj\xe4rtinfarkt'],
             ['Vascular', u'Cerebral arterit och/eller'],
             ['Hepato', u'Onormal leverfunk-tion inklusive leverkoma'],
             ['Skin', u'Erythema multiforme, exfoliativ dermatit, fixt l\xe4kemedels-utslag'],
             ['Musculoskeletal', u'Muskel-kramper'],
             ['General', u'Pl\xf6tslig kardiell d\xf6d*'],
             ['Investigations', u'\xd6kning av alkaliska fosfater och']]],
           ['Unknown',
            [['Blood', u'Pancytopeni'],
             ['Psychiatric',
              u'Vanf\xf6rest\xe4ll-ningar*, tanke-st\xf6rningar*, f\xf6rvirrings-tillst\xe5nd, fall av missbruk och beroende har beskrivits, oftare med formuleringar med omedelbar'],
             ['Nervous system',
              u'Cerebrovas-kul\xe4ra st\xf6rningar* (inklusive vaskulit, cerebral bl\xf6dning, cerebro-vaskul\xe4ra h\xe4ndelser, cerebral artrit, cerebral ocklusion), grand mal-anfall*, migr\xe4n'],
             ['Cardiac',
              u'Supraventri-kul\xe4r takykardi, bradykardi, ventrikul\xe4ra extrasystolier, extrasystolier'],
             ['General', u'Obehagsk\xe4nsla i br\xf6stet, hyperpyrexi']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 14],
 u'_rank': 47,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}