{'_data': [['Very common',
            [['Nervous system', u'Yrsel'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kningar'],
             ['GI', u'Diarr\xe9'],
             ['Metabolism', u'Anorexi'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kningar']]],
           ['Common',
            [['Psychiatric', u'Agitation'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Somnolens'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['Skin', u'\xd6kad svettning'],
             ['Skin', u'Tr\xf6tthet och asteni'],
             ['Skin', u'Olustk\xe4nsla'],
<<<<<<< HEAD
             ['Investigations', u'Viktnedg\xe5ng'],
=======
             ['Investigations',
              u'Viktnedg\xe5ng Tabell 2 visar biverkningar rapporterade vid rivastigminbehandling av patienter med demens vid Parkinsons sjukdom.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Psychiatric', u'Oro'],
             ['Psychiatric', u'Rastl\xf6shet'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'Somnolens'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'F\xf6rs\xe4mring av Parkinsons sjukdom'],
             ['Nervous system', u'Bradykinesi'],
             ['Nervous system', u'Dyskinesi'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Diarr\xe9'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['GI', u'Onormalt h\xf6g salivsekretion'],
             ['Skin', u'\xd6kad svettning'],
             ['Musculoskeletal', u'Muskelstelhet'],
             ['Metabolism', u'Anorexi'],
             ['Metabolism',
              u'Dehydrering Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Metabolism', u'Tr\xf6tthet och asteni'],
             ['Metabolism',
<<<<<<< HEAD
              u'Onormal g\xe5ng I tabell 3 listas antal och procent patienter som fick f\xf6rdefinierade biverkningar som kan tyda p\xe5 f\xf6rs\xe4mrad Parkinsons sjukdom i en specifik 24-veckors klinisk studie av rivastigminbehandling hos patienter med demens vid Parkinsons sjukdom.']]],
=======
              u'Onormal g\xe5ng I tabell 3 listas antal och procent patienter som fick f\xf6rdefinierade biverkningar som kan tyda p\xe5 f\xf6rs\xe4mrad Parkinsons sjukdom i en specifik 24-veckors klinisk studie av rivastigminbehandling hos patienter med demens vid Parkinsons sjukdom. Tabell 3 F\xf6rdefinierade biverkningar som kan rivastigmin (originalprodukt) n Placebo tyda p\xe5 f\xf6rv\xe4rrade parkinsonsymtom hos (%) n (%) patienter med demens vid Parkinsons sjukdom Totalt antal unders\xf6kta patienter 362 (100) 179 (100) Totalt antal patienter med f\xf6rdefinierade 99 (27,3) 28 (15,6) biverkningar Tremor 37 (10,2) 7 (3,9) Fall 21 (5,8) 11 (6,1) Parkinsons sjukdom (f\xf6rs\xe4mring) 12 (3,3) 2 (1,1) Onormalt h\xf6g salivsekretion 5 (1,4) 0 Dyskinesi 5 (1,4) 1 (0,6) Parkinsonism 8 (2,2) 1 (0,6) Hypokinesi 1 (0,3) 0 R\xf6relserubbning 1 (0,3) 0 Bradykinesi 9 (2,5) 3 (1,7) Dystoni 3 (0,8) 1 (0,6) Onormal g\xe5ng 5 (1,4) 0 Muskelstelhet 1 (0,3) 0 Balansrubbning 3 (0,8) 2 (1,1) Muskuloskeletal stelhet 3 (0,8) 0 Stelhet 1 (0,3) 0 Motorisk dysfunktion 1 (0,3) 0']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Synkope'],
             ['Hepato', u'F\xf6rh\xf6jda leverv\xe4rden'],
             ['Skin', u'Fallben\xe4genhet'],
             ['Nervous system', u'Dystoni'],
             ['Cardiac', u'F\xf6rmaksflimmer'],
             ['Cardiac', u'AV-block']]],
           ['Rare',
            [['GI',
<<<<<<< HEAD
              u'), mycket s\xe4llsynta (<1/10 000) och ingen k\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data).'],
=======
              u'(>1/10 000, <1/1 000), mycket s\xe4llsynta (<1/10 000) och ingen k\xe4nd frekvens (kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data). Tabell 1'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system', u'Krampanfall'],
             ['Cardiac', u'Angina pectoris'],
             ['GI', u'Mag- och duodenals\xe5r'],
             ['Skin',
              u'Hudutslag Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Very rare',
            [['Infections', u'Urinv\xe4gsinfektion'],
             ['Psychiatric', u'Hallucinationer'],
             ['Nervous system',
              u'Extrapyramidala symtom (inklusive f\xf6rs\xe4mring av Parkinsons sjukdom)'],
             ['Cardiac',
              u'Arytmier (t. ex bradykardi, AV-block, f\xf6rmaksflimmer och takykardi)'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Gastrointestinalbl\xf6dningar'],
             ['GI', u'Pankreatit']]],
           ['Unknown',
            [['GI',
              u'biverkningarna, speciellt under dostitrering. Kliniska studier har visat att kvinnliga patienter l\xf6per st\xf6rre risk \xe4n manliga f\xf6r att drabbas av gastroinestinala biverkningar och viktnedg\xe5ng. F\xf6ljande biverkningar, angivna nedan i tabell 1, har rapporterats f\xf6r patienter med Alzheimers demens som behandlats med rivastigmin. Biverkningarna presenteras inom varje frekvensomr\xe5de efter fallande allvarlighetsgrad enligt f\xf6ljande konvention: Mycket vanliga (\u22651/10), vanliga (\u22651/100, <1/10), mindre vanliga (\u22651/1 000, <1/100),'],
             ['GI',
              u'Vissa fall av sv\xe5ra kr\xe4kningar har f\xf6rknippats med esofagusruptur (se avsnitt 4.4)']]]],
 '_pages': [4, 6],
 u'_rank': 59,
 u'_type': u'LSFU'}