{'_data': [['Common',
            [['Nervous system',
              u'yrsel, somnolens, parestesi, huvudv\xe4rk, hypestesi, nedsatt mental sk\xe4rpa, tremor.'],
             ['Cardiac', u'palpitationer, takykardi.'],
             ['Vascular', u'v\xe4rmevallningar'],
             ['Respiratory', u'svalgbesv\xe4r, dyspn\xe9.'],
             ['GI', u'illam\xe5ende, muntorrhet, kr\xe4kningar, diarr\xe9.'],
             ['Skin', u'rodnad, svettning'],
             ['Musculoskeletal', u'lokal tyngdk\xe4nsla.'],
             ['General', u'asteni/orkesl\xf6shet, buk- eller br\xf6stsm\xe4rtor.']]],
           ['Uncommon',
            [['Immune system', u'desorientering, s\xf6mnl\xf6shet, nervositet.'],
             ['Nervous system', u'ataxi, vertigo.'],
             ['Eye', u'Dimsyn.'],
             ['Vascular', u'hypertoni'],
             ['GI', u't\xf6rst, dyspepsi.'],
             ['Skin', u'kl\xe5da, urtikaria'],
             ['Musculoskeletal',
              u'nacksm\xe4rta, lokal \xe5tstramningsk\xe4nsla, stelhet, muskelsvaghet.']]],
           ['Rare',
            [['Nervous system',
              u'synkope, dysgeusi/d\xe5lig smak i munnen, serotonergt syndrom.'],
             ['Cardiac',
              u'myokardischemi eller hj\xe4rtinfarkt, cerebrovaskul\xe4r h\xe4ndelse. De flesta av dessa biverkningar har rapporterats hos patienter med riskfaktorer f\xf6r koronar k\xe4rlsjukdom.'],
             ['Respiratory', u'v\xe4sande andning.'],
             ['Skin',
              u'angio\xf6dem (t.ex. ansikts\xf6dem, svullen tunga och svalg\xf6dem), utslag, toxisk epidermal nekrolys (r\xf6rande angio\xf6dem, se \xe4ven avsnitt 4.4).'],
             ['Musculoskeletal', u'ansiktssm\xe4rta.']]],
           ['Unknown',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktion, anafylaxi/anafylaktoid reaktion. Psykiatriska st\xf6rningar'],
             ['Nervous system', u'kramp.'],
             ['Cardiac', u'arytmi, bradykardi'],
             ['Vascular', u'perifer vaskul\xe4r sjukdom.'],
             ['GI', u'ulcer\xf6s kolit'],
             ['Musculoskeletal', u'myalgi'],
             ['Investigations', u'EKG-avvikelser.']]]],
 '_pages': [4, 6],
 u'_rank': 27,
 u'_type': u'LSFU'}