{'_data': [['Common',
            [['Vascular', u' D\xe5sighet (glykopyrron).  '],
             ['Nervous system',
              u' Bradykardi (neostigmin), takykardi (glykopyrron), hj\xe4rtarytmi (b\xe5da). GI: Muntorrhet (glykopyrron), salivation (neostigmin), \xf6kad gastrointestinal aktivitet (neostigmin). '],
             ['Other', u' Svettinhibering (glykopyrron). ']]],
           ['Uncommon',
            [['Reproductive system', u' Miktionsbesv\xe4r (glykopyrron).  '],
             ['Eye', u' Synrubbningar (glykopyrron). ']]],
           ['Rare',
            [['General', u' Anafylaktisk reaktion.  '],
             ['Vascular',
              u'AV-block grad III. Hypotension. Livshotande arytmi (inklusive ventrikelflimmer), f\xf6rl\xe4ngt QT-intervall och hj\xe4rtstillest\xe5nd. ']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'DFSU'}