{'_data': [['Very common', [['GI', u'Muntorrhet']]],
           ['Common',
            [['Nervous system', u'D\xe5sighet'],
             ['Eye', u'Synrubbningar'],
             ['Cardiac', u'Takykardi, hj\xe4rtklappning, ventrikul\xe4r arytmi'],
             ['Renal', u'Miktionsbesv\xe4r']]],
           ['Unknown', [['General', u'Anafylaktisk reaktion']]]],
 '_pages': [2, 2],
 u'_rank': 6,
 u'_type': u'LSFU'}