{'_data': [['Very common',
            [['Renal',
              u'-preparat. Betr\xe4ffande hyperkalcemi h\xe4nvisas till 4.2 Dosering och administreringss\xe4tt, Behandlingskontroll, samt 4.4 Varningar och f\xf6rsiktighetsm\xe5tt.']]],
           ['Very rare',
            [['Metabolism', u'Hyperkalcemi'],
             ['Skin',
              u'Allergiska reaktioner (kl\xe5da, utslag, urtikaria) allvarliga erytemat\xf6sa hudreaktioner']]],
           ['Unknown',
            [['Metabolism', u'Hyperfosfatemi'],
             ['Musculoskeletal',
              u'Mjukdelsf\xf6rkalkning (Samtidig hyperkalcemi och hyperfosfatemi kan leda till f\xf6rkalkning i mjukdelarna, vilket kan ses radiografiskt)'],
             ['Renal',
              u'F\xf6rh\xf6jt serumkreatinin (orsakat av kronisk hyperkalcemi) Kalcitriol ut\xf6var D-vitaminaktivitet, varf\xf6r risk f\xf6r hyperkalcemisyndrom eller kalciumintoxikation f\xf6religger (se avsnitt 4.2 och 4.4). Akuta symtom kan vara anorexi, huvudv\xe4rk, illam\xe5ende, kr\xe4kningar, buksm\xe4rtor och f\xf6rstoppning. Kroniska symtom kan vara dystrofi, k\xe4nselrubbningar, feber, polydipsi, polyuri, dehydrering, apati, tillv\xe4xth\xe4mning och urinv\xe4gsinfektioner. P\xe5 grund av kalcitriols korta halveringstid har farmakokinetiska unders\xf6kningar visat normalisering av f\xf6rh\xf6jt serumkalcium inom n\xe5gra dagar fr\xe5n uts\xe4ttande av behandling dvs.']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'LSFU'}