{'_data': [['Very common', [['General', u'\u2022sm\xe4rta/reaktion vid injektionsst\xe4llet*']]],
           ['Very rare',
            [['Immune system',
              u'\u2022anafylaktisk reaktion, t.ex. anafylaktisk chock \u2022anafylaktoid reaktion* \u2022\xf6verk\xe4nslighet'],
             ['Nervous system', u'\u2022paralys'],
             ['Cardiac', u'\u2022takykardi'],
             ['Vascular', u'\u2022hypotoni \u2022cirkulatorisk kollaps och chock'],
             ['Respiratory', u'\u2022bronkospasm'],
             ['Skin',
              u'\u2022hudutslag, erytemat\xf6st hudutslag \u2022angio\xf6dem \u2022urtikaria \u2022kl\xe5da \u2022exantem'],
             ['Investigations', u'\u2022\xf6kad histaminniv\xe5*'],
             ['Injury',
              u'\u2022f\xf6rl\xe4ngd neuromuskul\xe4r blockad * Ytterligare information om biverkningar: Anafylaktisk reaktion Allvarliga anafylaktiska reaktioner p\xe5 neuromuskul\xe4rt blockerande medel har i vissa fall varit fatala. P\xe5 grund av den m\xf6jliga allvarlighetsgraden av dessa reaktioner b\xf6r man alltid f\xf6ruts\xe4tta att de kan intr\xe4ffa och vidta n\xf6dv\xe4ndiga f\xf6rsiktighets\xe5tg\xe4rder. Lokal reaktion vid injektionsst\xe4llet Vid snabbinduktionsanestesi har sm\xe4rta vid injektionsst\xe4llet rapporterats, detta framf\xf6rallt d\xe5 patienten \xe4nnu inte helt f\xf6rlorat medvetandet och i synnerhet d\xe5 propofol anv\xe4nts som induktionsmedel. I kliniska studier angav 16 % av patienterna som genomgick snabbinduktionsanestesi med propofol sm\xe4rta vid injektionsst\xe4llet. Motsvarande siffra f\xf6r patienter som genomgick snabbinduktionsanestesi med fentanyl och tiopental var mindre \xe4n 0,5 %. \xd6kad histaminniv\xe5 Eftersom neuromuskul\xe4rt blockerande substanser \xe4r k\xe4nda f\xf6r att kunna inducera histaminfris\xe4ttning b\xe5de lokalt och systemiskt, b\xf6r risken f\xf6r utveckling av kl\xe5da och erytemat\xf6sa reaktioner p\xe5 injektionsst\xe4llet och/eller generaliserade histaminliknande (anafylaktoida) reaktioner s\xe5som bronkospasm och kardiovaskul\xe4ra f\xf6r\xe4ndringar t.ex. hypotoni och takykardi alltid beaktas n\xe4r dessa l\xe4kemedel ges. Hudutslag, exantem, urtikaria, bronkospasm och hypotoni har mycket s\xe4llan rapporterats hos patienter som getts rokuroniumbromid. I kliniska studier har endast l\xe4tt \xf6kning av genomsnittliga histaminniv\xe5er i plasma observerats efter snabb bolusadministrering av 0,3 - 0,9 mg rokuroniumbromid per kg kroppsvikt. F\xf6rl\xe4ngd neuromuskul\xe4r blockad Den vanligaste biverkningen av icke-depolariserande blockerande substanser som grupp \xe4r f\xf6rl\xe4ngning av l\xe4kemedlets farmakologiska effekt ut\xf6ver den tidsperiod som \xe4r n\xf6dv\xe4ndig. Denna kan variera fr\xe5n svaghet i skelettmuskler till djup och f\xf6rl\xe4ngd skelettmuskelparalys som leder till andningsinsufficiens eller apn\xe9.']]],
           ['Unknown',
            [['Respiratory', u'\u2022apn\xe9 \u2022respiratorisk svikt'],
             ['Musculoskeletal',
              u'\u2022svaghet i skelettmuskler \u2022steroid myopati (se avsnitt 4.4)']]]],
 '_pages': [6, 8],
 u'_rank': 11,
 u'_type': u'LSFU'}