{'_data': [['Very common', [['Nervous system', u' Huvudv\xe4rk  ']]],
           ['Common',
            [['Respiratory', u' Dyspn\xe9  '],
             ['Skin',
              u' Kontaktdermatit (lokalt erytem, kl\xe5da,  torr hud, skalpflagor, hudirritation, hudutslag). '],
             ['General', u' Perifert \xf6dem ']]],
           ['Rare',
            [['Cardiac', u' Hj\xe4rtklappning, \xf6kad hj\xe4rtfrekvens, br\xf6stsm\xe4rta.  '],
             ['Skin',
              u' Follikulit, seborr\xe9, hypertrikos p\xe5 ej  avsedda hudytor, tempor\xe4r alopeci, f\xf6r\xe4ndringar av h\xe5rf\xe4rg och/eller h\xe5rstruktur. ']]],
           ['Very rare',
            [['Vascular',
              u' Hypotension  Immunsystem: Angio\xf6dem, hypersensitivitet, allergisk  kontaktdermatit '],
             ['Nervous system', u' Yrsel '],
             ['Eye', u' \xd6gonirritation '],
             ['GI', u' Illam\xe5ende, kr\xe4kning ']]]],
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'DFSU'}