{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'bradykardi'],
             ['Vascular', u''],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['Renal', u'Urinretention']]],
           ['Common',
            [['Nervous system', u'parestesi, yrsel, hypestesi'],
             ['Vascular', u'Synkope'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Musculoskeletal', u'Ryggont, stelhet'],
             ['General', u'Hypotermi ']]],
           ['Rare',
            [['Immune system', u'Anafylaktisk reaktion'], ['Skin', u'Angio\xf6dem, urtikaria']]]],
 '_pages': [4, 5],
 u'_rank': 11,
 u'_type': u'LSFU2'}