{'_data': [['Very common',
            [['Nervous system', u's\xf6mnighet dyskinesi'],
             ['GI', u'Illam\xe5ende'],
             ['Nervous system', u'Mycket vanliga Synkope S\xf6mnighet'],
             ['Vascular', u'Illam\xe5ende']]],
           ['Common',
            [['Psychiatric', u'hallucinationer hallucinationer'],
             ['Nervous system',
              u'Yrsel (inklusive vertigo) S\xf6mnighet, yrsel (inklusive vertigo)'],
             ['Vascular', u'Postural hypotension, hypotension'],
             ['GI', u'Vanliga F\xf6rstoppning Illam\xe5ende, f\xf6rstoppning'],
             ['General',
              u'Vanliga Perifera \xf6dem Perifera \xf6dem Ut\xf6ver biverkningarna ovan har f\xf6ljande h\xe4ndelser rapporterats med ropinirol filmdragerade (omedelbar fris\xe4ttning) tabletter hos patienter med Parkinsons sjukdom i kliniska studier (vid doser upp till 24 mg/dag) och/eller efter marknadsintroduktionen. Vid monoterapi Till\xe4ggsbehandling'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Vascular', u'Vanliga Kr\xe4kningar, halsbr\xe4nna, Halsbr\xe4nna buksm\xe4rtor'],
             ['General',
              u'\xd6dem i benen * Ropinirol har satts i samband med s\xf6mnighet och har i mindre vanliga fall givit upphov till uttalad s\xf6mnighet dagtid och pl\xf6tsliga s\xf6mnattacker.']]],
           ['Uncommon',
            [['Vascular', u'Postural hypotension, hypotension'],
             ['Psychiatric',
              u'Mindre vanliga Psykotiska reaktioner (andra \xe4n Psykotiska reaktioner (andra \xe4n hallucinationer) innefattande hallucinationer) innefattande delirium, vanf\xf6rest\xe4llning, delirium, vanf\xf6rest\xe4llning, paranoia paranoia'],
             ['Nervous system',
              u'Mindre vanliga Pl\xf6tsliga s\xf6mnattacker, uttalad Pl\xf6tsliga s\xf6mnattacker, uttalad s\xf6mnighet dagtid s\xf6mnighet dagtid'],
             ['Vascular',
              u'Mindre vanliga Postural hypostension, Postural hypotension, hypotension hypotension (s\xe4llan allvarlig) (s\xe4llan allvarlig) Gastrointestinal disorders']]],
           ['Unknown',
            [['Immune system',
              u'Ingen k\xe4nd Hypersensitivitetsreaktioner Hypersensitivitetsreaktioner frekvens (inklusive urtikaria, angio\xf6dem, (inklusive urtikaria, angio\xf6dem, utslag och pruritus) utslag och pruritus)'],
             ['Psychiatric',
              u'Ingen k\xe4nd Impullskontrollst\xf6rningar Impullskontrollst\xf6rningar inklusive frekvens inklusive patologiskt patologiskt hasardspelande, hasardspelande, hypersexualitet hypersexualitet och \xf6kad libido (se och \xf6kad libido (se avsnitt 4.4) avsnitt 4.4)'],
             ['Hepato',
              u'Ingen k\xe4nd Leverp\xe5verkan, framf\xf6rallt Leverp\xe5verkan, framf\xf6rallt f\xf6rh\xf6jda frekvens f\xf6rh\xf6jda leverenzymv\xe4rden leverenzymv\xe4rden']]]],
 '_pages': [5, 6],
 u'_rank': 19,
 u'_type': u'LSFU'}