{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Hypotension'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar']]],
           ['Common',
            [['Nervous system', u'Parestesi, yrsel, hypoastesi'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Synkope'],
             ['Respiratory', u'Dyspn\xe9'],
             ['Renal', u'Urinretention'],
             ['General', u'Ryggsm\xe4rta, hypotermi, stelhet']]],
           ['Rare',
            [['General',
              u'Allergiska reaktioner  (anafylaktiska reaktioner, angioneurotiskt \xf6dem och urtikaria)']]]],
 '_pages': [4, 5],
 u'_rank': 10,
 u'_type': u'TSFU'}