{'_data': [['Very common',
            [['Nervous system', u'S\xf6mnighet Dykinesi'],
             ['GI', u'Illam\xe5ende'],
             ['Nervous system', u'Mycket vanliga Synkope S\xf6mnighet'],
             ['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Psychiatric', u'Hallucinationer Hallucinationer'],
             ['Nervous system',
              u'Yrsel (inklusive vertigo) S\xf6mnighet, yrsel (inklusive vertigo)'],
             ['Vascular', u'Postural hypotension, hypotension'],
             ['GI', u'Vanliga F\xf6rstoppning Illam\xe5ende, f\xf6rstoppning'],
             ['General',
              u'Vanliga Perifera \xf6dem Perifera \xf6dem Ut\xf6ver biverkningarna ovan har f\xf6ljande h\xe4ndelser rapporterats med ropinirol filmdragerade (omedelbar fris\xe4ttning) tabletter hos patienter med Parkinsons sjukdom i kliniska studier (vid doser upp till 24 mg/dag) och/eller efter marknadsintroduktionen. Monoterapi Till\xe4ggsbehandling'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['GI', u'Vanliga Kr\xe4kningar, halsbr\xe4nna, Halsbr\xe4nna buksm\xe4rtor.'],
<<<<<<< HEAD
             ['General', u'\xd6dem i benen.']]],
=======
             ['General',
              u'\xd6dem i benen. *Ropinirol har satts i samband med s\xf6mnighet och har i mindre vanliga fall givit upphov till uttalad s\xf6mnighet dagtid och pl\xf6tsliga s\xf6mnattacker.']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Vascular', u'Postural hypotension, hypotension'],
             ['Psychiatric',
              u'Mindre vanliga Psykotiska reaktioner (andra Psykotiska reaktioner (andra \xe4n hallucinationer) \xe4n hallucinationer) innefattande delirium, innefattande delirium, vanf\xf6rest\xe4llning, paranoia. vanf\xf6rest\xe4llning, paranoia.'],
             ['Nervous system',
              u'Mindre vanliga Pl\xf6tsliga s\xf6mnattacker, uttalad Pl\xf6tsliga s\xf6mnattacker, s\xf6mnighet dagtid.* uttalad s\xf6mnighet dagtid.*'],
             ['Vascular',
              u'Mindre vanliga Postural hypotension, Postural hypotension, hypotension (s\xe4llan allvarlig). hypotension (s\xe4llan allvarlig).']]],
           ['Unknown',
            [['Immune system',
              u'Ingen k\xe4nd frekvens Hypersensitivitetsreaktioner Hypersensitivitetsreaktioner (inklusive urtikaria, (inklusive urtikaria, angio\xf6dem, utslag och angio\xf6dem, utslag och pruritus). pruritus).'],
             ['Hepato',
              u'Ingen k\xe4nd frekvens Leverp\xe5verkan (framf\xf6rallt Leverp\xe5verkan (framf\xf6rallt f\xf6rh\xf6jda leverenzymv\xe4rden). f\xf6rh\xf6jda leverenzymv\xe4rden).']]]],
 '_pages': [5, 6],
 u'_rank': 18,
 u'_type': u'LSFU'}