{'_data': [['Very common',
<<<<<<< HEAD
            [['Nervous system', u'Yrsel'], ['Cardiac', u'\xd6verlednings-ru palpitationer']]],
           ['Common',
            [['Psychiatric', u'Oro, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Huvudv\xe4rk, smak-f\xf6r\xe4ndring ar'],
=======
            [['Nervous system', u'Yrsel'], ['Cardiac', u'\xd6verlednings-palpitationer']]],
           ['Common',
            [['Psychiatric', u'Oro, s\xf6mnst\xf6rningar'],
             ['Nervous system', u'Huvudv\xe4rk, smak-f\xf6r\xe4ndringar'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Sinusbradykardi, takykardi, f\xf6rmaksfladder'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI',
              u'Buksm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9, f\xf6rstoppning, muntorrhet,'],
             ['Hepato', u'Onormal leverfunktion'],
             ['General', u'Br\xf6stsm\xe4rta, asteni, svaghet, pyrexi']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni Agranulocytos,'],
             ['Metabolism', u'Minskad aptit'],
             ['Psychiatric', u'Mardr\xf6mmar'],
             ['Nervous system', u'Svimning, ataxi, parestesi'],
             ['Ear', u'Vertigo'],
<<<<<<< HEAD
             ['Cardiac', u'Kammar-takykar'],
=======
             ['Cardiac', u'Kammar-Arytmi'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Vascular', u'Hypotoni'],
             ['GI', u'Sp\xe4nd mage, flatulens'],
             ['Skin', u'Urtikaria, kl\xe5da, utslag, erytem'],
             ['Reproductive system', u'Erektil dysfunk-tion']]],
           ['Unknown',
            [['Blood', u'leukopeni, granulocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'F\xf6rvrirring'],
             ['Nervous system', u'Kramp, extrapyramidala symtom, rastl\xf6shet'],
             ['Cardiac', u'Kammarflimmer, minskad hj\xe4rtfrekvens'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['GI', u'Kv\xe4ljningar, obalans i magtarmkanalen'],
             ['Hepato', u'Hepatocellul\xe4r skada, kolestas, hepatit, gulsot'],
             ['Musculoskeletal', u'Lupusliknande symtom'],
             ['Reproductive system', u'Minskning i spermieantal']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 30,
 u'_type': u'MSFU'}