{'_data': [[u'Unknown',
            [['Infections', u'vaginal   candida'],
             ['Immune system', u'\xd6verk\xe4nslighe'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['Psychiatric',
              u'Nedst\xe4mdhet   Nedsatt libido   \xd6kad libido   Hum\xf6r-f\xf6r\xe4ndrin'],
             ['Nervous system', u'Huvudv\xe4rk   Migr\xe4n   Yrsel   Nervositet'],
             ['Eye', u'Intolerans mot'],
             ['Ear', u'Otoskleros'],
             ['Vascular', u'Hypertension   Tromboembol'],
             ['GI', u'Illam\xe5ende   Diarr\xe9,'],
             ['Skin', u'Akne   Utslag   Erythema   Urtikaria   nodosum,'],
             ['Reproductive system',
              u'Oregelbunden   Amenorr\xe9   Br\xf6sthypertrofi   Vaginal'],
             ['General', u'Vikt\xf6kning']]]],
 '_pages': [8, 9],
 u'_rank': 12,
 u'_type': u'LFSU'}