{'_data': [['Very common',
            [['Nervous system', u'somnolens'],
             ['Eye', u'synf\xe4ltsdefekter'],
             ['General', u'tr\xf6tthet'],
             ['Psychiatric', u'excitation (barn), agitation (barn)']]],
           ['Common',
            [['Investigations', u'vikt\xf6kning'],
             ['Nervous system',
              u'talrubbningar, huvudv\xe4rk, yrsel, parestesier, uppm\xe4rksamhets- och minnesst\xf6rningar, psykisk st\xf6rning (tankest\xf6rningar), tremor'],
             ['Eye', u'dimsyn, dubbelseende, nystagmus'],
             ['GI', u'illam\xe5ende, magsm\xe4rtor'],
             ['General', u'\xf6dem, irritabilitet'],
             ['Psychiatric',
              u'agitation, aggression, nervositet, depression, paranoida reaktioner']]],
           ['Uncommon',
            [['Nervous system', u'rubbning i koordinationsf\xf6rm\xe5gan (ataxi)'],
             ['Skin', u'hudutslag'],
             ['Psychiatric', u'hypomani, mani, psykotisk st\xf6rning']]],
           ['Rare',
            [['Nervous system', u'encefalopati**'],
             ['Eye', u'retinala st\xf6rningar(s\xe5som perifer retinal atrofi)'],
             ['Skin', u'angio\xf6dem, urtikaria'],
             ['Psychiatric', u'sj\xe4lvmordsf\xf6rs\xf6k']]],
           ['Very rare',
            [['Nervous system', u'optikusneurit'],
             ['Eye', u'optikusatrofi'],
             ['Hepato', u'hepatit'],
             ['Psychiatric', u'hallucinationer']]],
           ['Unknown',
            [['Nervous system',
              u'Fall av avvikelser vid MRT av hj\xe4rnan har rapporterats (se avsnitt 4.4). R\xf6relsest\xf6rningar inkluderande dystoni, dyskinesi eller hyperton muskulatur har rapporterats, antingen enskilt eller i samband med avvikelser vid MRT (se avsnitt 4.4).']]]],
 '_pages': [6, 8],
 u'_rank': 22,
 u'_type': u'LSFU'}