{'_data': [[u'Unknown',
            [['Blood', u'F\xf6r\xe4ndrad blodbild (aplastisk   anemi, agranulocytos,'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel   Perifer neuropati'],
             ['Cardiac', u'Myocardit, pericardit'],
             ['Respiratory', u'Allergiska och fibrotiska'],
             ['GI', u'Buksm\xe4rtor, diarr\xe9,   Akut pankreatit'],
             ['Renal', u'F\xf6rs\xe4mrad njurfunktion   inklusive akut och kronisk'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
             ['Hepato', u'F\xf6r\xe4ndringar i   leverfunktionsv\xe4rden'],
             ['Reproductive system', u'Oligospermi (reversibel)']]]],
 '_pages': [4, 5],
 u'_rank': 11,
 u'_type': u'LFSU'}