{'_data': [[u'Unknown',
            [['Blood', u'F\xf6r\xe4ndrad blodbild (aplastisk'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel   Perifer neuropati'],
             ['Cardiac', u'Myocardit, pericardit'],
             ['Respiratory',
              u'Allergiska och fibrotiska lung   reaktioner (inklusive dyspnoe, hosta,'],
             ['GI', u'Buksm\xe4rtor, diarr\xe9,   Akut pankreatit'],
             ['Renal', u'F\xf6rs\xe4mrad njurfunktion inklusive'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Myalgi, artralgi'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
             ['Hepato', u'F\xf6r\xe4ndringar i'],
             ['Reproductive system', u'Oligospermi (reversibel)']]]],
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'LFSU'}