{'_data': [['Common',
            [['Nervous system', u'Metallisk eller bitter smak.'], ['GI', u'Muntorrhet.']]],
           ['Uncommon',
            [['Cardiac',
              u'(> 1/1 000 till < 1/100) Br\xf6stsm\xe4rtor/angina pectoris, onormalt EKG.'],
             ['Nervous system', u'\xd6verg\xe5ende huvudv\xe4rk.'],
             ['GI', u'Illam\xe5ende.']]],
           ['Rare',
            [['Cardiac', u'Arytmi. Medf\xf6dda och/eller genetiska st\xf6rningar'],
             ['Nervous system', u'Yrsel, kramper, svimning, hypoestesi och parestesi.'],
             ['GI', u'Buksm\xe4rtor. Dyspepsi.'],
             ['Skin',
              u'Allergiska hud- och slemhinnereaktioner med exantem (pruritus, urtikaria, \xf6dem)'],
             ['Skin',
              u'\xd6verg\xe5ende artritliknande sm\xe4rta. Neoplasier; benigna, maligna och ospecificerade (samt cystor och polyper)'],
             ['Vascular',
              u'Rodnad, vasodilatation. Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Vascular', u'Inflammation vid injektionsst\xe4llet Feber, tr\xf6tthet.'],
             ['Immune system',
              u'Sv\xe5ra \xf6verk\xe4nslighetsreaktioner som dyspn\xe9, hypotension, bradykardi, asteni och uppkastningar (vanligen inom tv\xe5 timmar efter administrering), angio\xf6dem.']]],
           ['Unknown',
            [['Cardiac', u'\xc4rftliga defekter. tillg\xe4ngliga data)'],
             ['Skin',
              u'Icke-kliande utslag. tillg\xe4ngliga data) Muskuloskeletala systemet och bindv\xe4v']]]],
 '_pages': [6, 7],
 u'_rank': 15,
 u'_type': u'LSFU'}