{'_data': [['Common',
            [['General',
              u'Desorientering, huvudv\xe4rk, koncentrationssv\xe5righeter,   tr\xf6tthet, d\xe5sighet, svettning, aptit\xf6kning, vikt\xf6kning, yrsel.'],
             ['Vascular',
<<<<<<< HEAD
              u'Palpitationer, takykardi, EKG-f\xf6r\xe4ndringar (fr\xe4mst  QT-f\xf6rl\xe4ngning, flack eller inverterad T-v\xe5g), AV-block, ortostatiskt  blodtrycksfall.'],
=======
              u'Palpitationer, takykardi, EKG-f\xf6r\xe4ndringar (fr\xe4mst QT-  f\xf6rl\xe4ngning, flack eller inverterad T-v\xe5g), AV-block, ortostatiskt  blodtrycksfall.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Endocrine', u'Rubbning av libido och potens.'],
             ['GI',
              u'Illam\xe5ende, obstipation, muntorrhet, f\xf6r\xe4ndrad smakuppfattning.'],
             ['Nervous system', u'Tremor, parestesier, ataxi.'],
             ['Eye', u'Ackommodationsst\xf6rningar, mydriasis, dimsyn.']]],
           ['Uncommon',
            [['Vascular', u'Hypertension.'],
             ['GI', u'Kr\xe4kningar, diarr\xe9.'],
             ['Skin', u'Exantem, urtikaria, purpura, \xf6dem i ansikte och tunga.'],
             ['Psychiatric', u'Hypomani, mani, \xe5ngest, s\xf6mnl\xf6shet, mardr\xf6mmar.'],
             ['Reproductive system', u'Urinretention.'],
             ['Eye', u'F\xf6rh\xf6jt intraokul\xe4rt tryck.'],
             ['Ear', u'Tinnitus.']]],
           ['Rare',
            [['General', u'Aptitl\xf6shet, feber, viktminskning.'],
             ['Blood', u'Agranulocytos, eosinofili, leukopeni, trombocytopeni.'],
             ['Vascular', u'Arytmi, hj\xe4rtinfarkt.'],
             ['Endocrine', u'Gynekomasti, galaktorr\xe9.'],
             ['GI', u'Paralytisk ileus, parotissvullnad.'],
             ['Skin', u'H\xe5ravfall, fotosensibilisering.'],
             ['Hepato', u'Transaminasstegring, ikterus.'],
             ['Nervous system', u'Kramper'],
             ['Psychiatric',
              u'\xd6kad hallucinos hos schizofrena patienter, delirium (\xe4ldre  patienter).']]],
           ['Unknown',
            [['Psychiatric',
              u'Suicidtankar, suicidalt beteende   (kan inte ber\xe4knas  utifr\xe5n tillg\xe4ngliga  data)']]]],
 '_pages': [6, 7],
 u'_rank': 23,
 u'_type': u'LFSUR'}