{'_data': [[u'Unknown',
            [['Infections', u'faryngit'],
             ['Metabolism', u'anorexi (inklusive minskad   aptit), \xf6kad aptit'],
             ['Psychiatric', u'dissociation, upprymdhet,   paranoia, suicidala tankar,'],
             ['Nervous system',
              u'koncentrationssv\xe5righeter,  yrsel   dysartri, dysgeusi, letargi,   synkope   minnesrubbningar'],
             ['Eye', u'dimsyn'],
             ['Ear', u'yrsel'],
             ['Cardiac', u'palpitationer, takykardi'],
             ['Vascular', u'hypertoni'],
             ['GI', u'munh\xe5lan, illam\xe5ende,   munslemhinna*, rubbning i'],
             ['General', u'sm\xe4rta p\xe5'],
             ['General',
              u'kraftl\xf6shet, onormal k\xe4nsla,   appliceringsst\xe4llet   onykterhetsk\xe4nsla, olust']]]],
 '_pages': [7, 8],
 u'_rank': 11,
 u'_type': u'LFSU'}