{'_data': [['Very common',
            [['Nervous system', u's\xf6mnighet, yrsel.'],
             ['Eye',
              u'ackomodationsst\xf6rningar (cycloplegi) inklusive dimsyn, n\xe4rsynthet och mydriasis (ibland ensidiga).'],
             ['GI', u'muntorrhet.']]],
           ['Common', [['Eye', u'irritation i \xf6gonlocken.'], ['Skin', u'hudirritation.']]],
           ['Rare',
            [['Psychiatric', u'desorientering, f\xf6rvirring och hallucinationer.'],
             ['Nervous system',
              u'f\xf6rs\xe4mrat minne, p\xe5verkad uppm\xe4rksamhet, rastl\xf6shet.'],
             ['Renal',
              u'urinretention. Efter uts\xe4ttande av behandlingen med Scopoderm har i s\xe4llsynta fall \u2013 oftast efter flera dagars anv\xe4ndning - \xf6verg\xe5ende symtom s\xe5som yrsel, illam\xe5ende, kr\xe4kningar, huvudv\xe4rk och balanssv\xe5righeter rapporterats.']]],
           ['Very rare', [['Eye', u'tr\xe5ngvinkelglaukom.'], ['Skin', u'generella utslag']]],
           ['Unknown', [['General', u'br\xe4nnande k\xe4nsla vid administreringsst\xe4llet']]]],
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'LSFU'}