{'_data': [['Common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Respiratory', u'Hosta'],
             ['GI',
              u'F\xf6rh\xf6jt amylasv\xe4rde, diarr\xe9, f\xf6rh\xf6jt lipasv\xe4rde, illam\xe5ende, buksm\xe4rta'],
             ['Hepato', u'F\xf6rh\xf6jt alaninaminotransferasv\xe4rde i blodet'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'F\xf6rh\xf6jt kreatinkinasv\xe4rde'],
             ['Musculoskeletal', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Nervous system',
              u'Perifer neuropati, smakf\xf6r\xe4ndring, nedsatt k\xe4nsel, parestesier, ischias'],
             ['Hepato', u'F\xf6rh\xf6jt aspartataminotransferasv\xe4rde'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, myopati/myosit, sm\xe4rta i extremiteterna, ryggsm\xe4rta, muskelspasm, nacksm\xe4rta, flanksm\xe4rta'],
             ['Musculoskeletal',
              u'Sjukdomsk\xe4nsla *Denna biverkning har identifierats vid uppf\xf6ljning efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning men har inte observerats i kontrollerade kliniska pr\xf6vningar. Frekvensen uppskattades fr\xe5n en statistisk ber\xe4kning som baserades p\xe5 det totala antalet patienter som exponerats f\xf6r telbivudin i kliniska pr\xf6vningar (n = 8 914). Beskrivning av vissa biverkningar Kreatinkinasf\xf6rh\xf6jning F\xf6rh\xf6jda CK-v\xe4rden grad 3 eller 4 (>7x ULN) f\xf6rekom hos 12,6 % av de telbivudinbehandlade patienterna (n = 847) och hos 4,0 % av de lamivudinbehandlade patienterna (n = 846) efter 104 veckors behandling vid en sammanslagen analys av NV-02B-007 (GLOBE) och NV-02B-015. De flesta CK-\xf6kningarna var asymtomatiska och CK-v\xe4rdena hade i allm\xe4nhet g\xe5tt tillbaka vid n\xe4sta bes\xf6k vid fortsatt behandling.']]],
           ['Rare',
            [['Metabolism',
              u'* Laktacidos som sekund\xe4r h\xe4ndelse ofta f\xf6rknippat med allvarliga tillst\xe5nd (t ex multipel organsvikt eller sepsis)'],
             ['Musculoskeletal',
              u'Rabdomyolys Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]]],
 '_pages': [7, 9],
 u'_rank': 13,
 u'_type': u'LSFU'}