{'_data': [['Common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Respiratory', u'Hosta'],
             ['GI',
              u'F\xf6rh\xf6jt amylasv\xe4rde, diarr\xe9, f\xf6rh\xf6jt lipasv\xe4rde, illam\xe5ende, buksm\xe4rta'],
             ['Hepato', u'F\xf6rh\xf6jt alaninaminotransferasv\xe4rde i blodet'],
             ['Skin', u'Hudutslag'],
             ['Musculoskeletal', u'F\xf6rh\xf6jt kreatinkinasv\xe4rde'],
             ['Musculoskeletal', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Nervous system',
              u'Perifer neuropati, smakf\xf6r\xe4ndring, nedsatt k\xe4nsel, parestesier, ischias'],
             ['Hepato', u'F\xf6rh\xf6jt aspartataminotransferasv\xe4rde'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, myopati/myosit, sm\xe4rta i extremiteterna, ryggsm\xe4rta, muskelspasm, nacksm\xe4rta, flanksm\xe4rta'],
             ['Musculoskeletal', u'Sjukdomsk\xe4nsla']]],
           ['Rare',
            [['Metabolism',
              u'* Laktacidos som sekund\xe4r h\xe4ndelse ofta f\xf6rknippat med allvarliga tillst\xe5nd (t ex multipel organsvikt eller sepsis)'],
             ['Musculoskeletal',
              u'Rabdomyolys Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]]],
 '_pages': [6, 8],
 u'_rank': 13,
 u'_type': u'LSFU'}