{'_data': [['Common',
            [['Psychiatric',
              u'S\xf6mnst\xf6rningar, konfusion,  hallucinationer, \xe5ngest, psykos.'],
             ['Cardiac', u'Bradykardi'],
             ['GI', u'Illam\xe5ende'],
             ['Hepato', u'\xd6verg\xe5ende  transaminasstegring (ALAT).']]],
           ['Uncommon',
            [['Psychiatric', u'Hum\xf6rf\xf6r\xe4ndringar'],
             ['Cardiac', u'Supraventrikul\xe4r takykardi'],
             ['GI', u'Muntorrhet']]],
           ['Rare',
            [['Nervous system', u'Agitation.'],
             ['Vascular', u'Postural hypotension.'],
             ['Skin', u'Hudutslag.'],
             ['Renal', u'Miktionsbesv\xe4r.']]],
           ['Unknown',
            [['Psychiatric',
              u'St\xf6rd impulskontroll och  tv\xe5ngsm\xe4ssigt beteende* hypersexualitet'],
             ['Renal', u'Urinretention']]]],
 '_pages': [4, 5],
 u'_rank': 13,
 u'_type': u'TSFU'}