{'_data': [['Common',
            [['General', u'Tr\xf6tthet, huvudv\xe4rk, yrsel.'],
             ['Vascular', u'Perifer kyla i extremiteter, bradykardi. Palpitationer.'],
             ['GI',
              u'Buksm\xe4rtor, illam\xe5ende, kr\xe4kningar, diarr\xe9 och f\xf6rstoppning.']]],
           ['Uncommon',
            [['General', u'Br\xf6stsm\xe4rtor, vikt\xf6kning.'],
             ['Vascular',
              u'\xd6verg\xe5ende f\xf6rs\xe4mring av hj\xe4rtsvikt, kardiogen chock hos patienter med akut  myokardiell infarkt.'],
             ['Nervous system', u'S\xf6mnst\xf6rningar, parestesier.'],
             ['Respiratory',
              u'Andf\xe5ddhet, bronkospasm hos patienter med bronkialastma eller astmabesv\xe4r.']]],
           ['Rare',
            [['General',
              u'Hyperhidros, h\xe5ravfall, smakf\xf6r\xe4ndringar, reversibel libidost\xf6rning.'],
             ['Blood', u'Trombocytopeni.'],
             ['Vascular',
              u'F\xf6rl\xe4ngd AV-\xf6verledningstid, hj\xe4rtarytmier, \xf6dem, synkope.'],
             ['Nervous system',
              u'Mardr\xf6mmar, depressioner, minnesst\xf6rningar, konfusion, nervositet, oro,  hallucinationer.'],
             ['Skin',
              u'\xd6verk\xe4nslighetsreaktioner fr\xe5n huden, f\xf6rv\xe4rrad psoriasis, fotosensitivitet.'],
             ['Hepato', u'Transaminasstegring'],
             ['Eye', u'Synst\xf6rningar. Torra och/eller irriterade \xf6gon.'],
             ['Ear', u'Tinnitus.']]]],
 '_pages': [5, 6],
 u'_rank': 15,
 u'_type': u'LFSUR'}