{'_data': [['Common',
            [['Eye', u'Konjunktivit'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['GI', u'Diarr\xe9'],
             ['GI', u'F\xf6rstoppning'],
             ['GI', u'Buksm\xe4rta'],
             ['Hepato', u'Leverp\xe5verkan'],
             ['Skin', u'Alopeci'],
             ['Skin', u'Exantem'],
             ['Skin', u'Urtikaria'],
             ['Renal',
              u'Steril hemorragisk cystit f\xf6rekommer hos ca  10 % av patienterna vid h\xf6gdos- eller l\xe5ngtidsanv\xe4ndning']]],
           ['Rare',
            [['Immune system', u'Anafylaktisk chock'],
             ['Immune system', u'Anafylaktoid reaktion*'],
             ['Endocrine', u'SIADH (Syndrome of inadequate ADH  secretion)'],
             ['Metabolism', u'Hyponatremi'],
             ['Metabolism', u'V\xe4tskeretention'],
             ['Metabolism', u'Anorexi'],
             ['Eye', u'Dimsyn'],
             ['Cardiac', u'Kardiotoxiska effekter'],
             ['GI', u'Hemorragisk kolit'],
             ['GI', u'Mukosit'],
             ['GI', u'Akut pankreatit'],
             ['GI', u'S\xe5r i munslemhinna'],
             ['Skin',
              u'Hud- och nagelf\xf6r\xe4ndringar (missf\xe4rgning av  handflator, naglar, fotsulor)'],
             ['Renal', u'Tubul\xe4r nekros'],
             ['Renal', u'Hemorragisk uretrit'],
             ['Renal', u'Fibros i urinbl\xe5san'],
             ['Renal', u'Atypiska epitelceller fr\xe5n urinbl\xe5san'],
             ['Renal', u'Renala lesioner'],
             ['Reproductive system', u'Amenorr\xe9*****'],
             ['General', u'Feber  injektions-/infusionsst\xe4llet']]],
           ['Very rare',
            [['Skin', u'Toxisk epidermal nekrolys'], ['Skin', u'Stevens-Johnsons syndrom']]],
           ['Unknown',
            [['Immune system', u'Immunsuppression'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktion'],
             ['Endocrine', u'Vattenf\xf6rgiftning'],
             ['Metabolism', u'Blodglukosf\xf6r\xe4ndringar (\xf6kning, minskning)'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u'Encefalopati'],
             ['Nervous system', u'Kramper  Neurotoxicitet'],
             ['Eye', u'Synneds\xe4ttning'],
             ['Eye', u'\xd6kat t\xe5rfl\xf6de'],
             ['Ear', u'D\xf6vhet'],
             ['Ear', u'Nedsatt h\xf6rsel'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Hj\xe4rtstopp'],
             ['Cardiac', u'Kardiogen chock'],
             ['Cardiac', u'Arrytmier'],
             ['Vascular', u'Pulmon\xe4r embolism'],
             ['Vascular', u'Ventrombos'],
             ['Vascular', u'Vaskulit'],
             ['Vascular', u'Perifer ischemi'],
             ['Vascular', u'Hypertension'],
             ['Vascular', u'Hypotension'],
             ['Vascular', u'Blodvallningar'],
             ['Vascular', u'Pulmon\xe4r veno-ocklusiv sjukdom'],
             ['Vascular', u'Akut andn\xf6dssyndrom (ARDS)'],
             ['Vascular', u'Lungsvikt*'],
             ['Vascular', u'Obliterativ bronkiolit'],
             ['Vascular', u'Pneumonit'],
             ['Vascular', u'Allergisk alveolit'],
             ['Vascular', u'Organiserad pneumoni'],
             ['Vascular', u'Pulmonell hypertension'],
             ['Vascular', u'Pleural effusion'],
             ['Vascular', u'Pulmon\xe4rt \xf6dem'],
             ['Vascular', u'Bronkospasm'],
             ['Vascular', u'Hypoxi'],
             ['Vascular', u'Dyspn\xe9'],
             ['Vascular', u'Hosta'],
             ['Vascular', u'N\xe4st\xe4ppa'],
             ['Vascular', u'Nasalt obehag'],
             ['Vascular', u'Rinorr\xe9'],
             ['Vascular', u'Nysning'],
             ['Vascular', u'Orofaryngeal sm\xe4rta'],
             ['GI', u'Gastrointestinal bl\xf6dning'],
             ['GI', u'Kolit'],
             ['GI', u'Enterit'],
             ['GI', u'Inflammation i blindtarmen'],
             ['GI', u'Inflammation i \xf6ronspottk\xf6rteln'],
             ['GI', u'Bukobehag'],
             ['Hepato', u'Veno-ocklusiv leversjukdom'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Erythema multiforme'],
             ['Skin', u'Palmar-plantar erythrodysestesi- syndrom'],
             ['Skin', u'\u201dRadiation recall\u201d-dermatit'],
             ['Skin', u'Dermatit'],
             ['Skin', u'Pruritus (inklusive inflammatorisk kl\xe5da)'],
             ['Skin', u'Erytem'],
             ['Skin', u'Bl\xe5sor'],
             ['Skin', u'Ansiktssvullnad'],
             ['Skin', u'Hyperhidros'],
             ['Skin', u'Kramp'],
             ['Skin', u'Myalgi'],
             ['Skin', u'Artralgi'],
             ['Renal', u'Njursvikt/nedsatt njurfunktion'],
             ['Renal', u'Rubbningar i njurtubuli'],
             ['Renal', u'Toxisk nefropati'],
             ['Renal', u'Pyelit'],
             ['Renal', u'Nekros i bl\xe5san'],
             ['Renal', u'Ulcer\xf6s cystit'],
             ['Renal', u'Bl\xe5skontraktur'],
             ['Renal', u'Hematuri'],
             ['Renal', u'Nefrogen diabetes insipidus'],
             ['Renal', u'\xd6kat blodkreatinin'],
             ['Renal', u'Stegring av urea i blodet'],
             ['Reproductive system', u'Oligomenorr\xe9*****'],
             ['Reproductive system', u'Infertilitet'],
             ['Reproductive system', u'Ovariesvikt/sjukdom'],
             ['Reproductive system', u'Ovulationsst\xf6rning'],
             ['Reproductive system', u'Testikul\xe4r atrofi'],
             ['Reproductive system', u'Oligospermi*****'],
             ['Reproductive system', u'Minskad \xf6strogenhalt i blod'],
             ['Reproductive system', u'\xd6kad gonadotropinhalt i blod'],
             ['Reproductive system', u'Tillv\xe4xth\xe4mning av foster'],
             ['Reproductive system',
              u'Fostertoxicitet (inklusive myelosuppression  och gastroenterit)'],
             ['Investigations', u'\xd6kning av laktatdehydrogenas i blod'],
             ['Investigations', u'\xd6kning av C-reaktivt protein']]]],
 '_pages': [6, 11],
 u'_rank': 117,
 u'_type': u'TSFU'}