{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Skin', u'Reaktioner p\xe5 applikations -st\xe4llet, erytem'],
             ['Reproductive system',
              u'Br\xf6st-sp\xe4nn ing och v\xe4rk, dysmenorr\xe9, menstrua-tio ns-rubbning'],
             ['General', u'vid ']]],
           ['Common',
            [['Psychiatric', u'Depression, nervositet, affektlabilitet'],
             ['Nervous system', u'S\xf6mnsv\xe5rig-het'],
             ['GI', u'Illam\xe5ende, diarr\xe9, dyspepsi, buksm\xe4rta, flatulens'],
             ['Skin', u'Akne, utslag, pruritus, torr hud'],
             ['Reproductive system',
              u'Br\xf6stf\xf6rstoring, menorragi, vaginal flytning oregelbunden vaginal bl\xf6dning, uterinspasm, vaginal infektion, endometrie-hyp erplasi'],
             ['General', u'V\xe4rk, ryggv\xe4rk, asteni, perifert \xf6dem, vikt\xf6kning']]],
           ['Uncommon',
            [['Nervous system', u'Migr\xe4n, yrsel'],
             ['Vascular', u'F\xf6rh\xf6jt blodtryck'],
             ['GI', u'Kr\xe4kning'],
             ['Skin', u'Missf\xe4rg-ning av huden'],
             ['Investigations', u'Transaminas\xf6 kning']]],
           ['Rare',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'Libidof\xf6r\xe4ndrin'],
             ['Nervous system', u'Parestesi'],
             ['Vascular', u'Ven\xf6s emboli'],
             ['Hepato', u'Gallbl\xe5sesjukd om, kolelitiasis'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Myasteni'],
             ['Reproductive system', u'Myom, cystor p\xe5 \xe4ggledare, cervixpolyper']]],
           ['Very rare',
            [['Metabolism', u'Nedsatt kolhydrat-tolerans'],
             ['Nervous system', u'Korea'],
             ['Eye', u'\xd6verk\xe4nslig-h et f\xf6r kontaktlinser'],
             ['Hepato', u'Kolestatisk gulsot'],
             ['Skin', u'Hirsutism, hudnekros']]],
           ['Unknown', [['Musculoskeletal', u'Extremitetss * m\xe4rta']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 29,
 u'_type': u'MSFU'}