{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Tremor'],
             ['Cardiac', u'Palpitationer'],
             ['Musculoskeletal', u'Muskelkramp']]],
           ['Uncommon',
            [['Immune system', u'Hudutslag (kl\xe5da och rodnad)'],
             ['Psychiatric', u'Oro'],
             ['Cardiac', u'Takykardi']]],
           ['Rare',
            [['Metabolism', u'Hypokalemi'],
             ['Psychiatric', u'S\xf6mnsv\xe5righeter'],
             ['Nervous system', u'Yrsel']]],
           ['Very rare',
            [['Immune system',
              u'Anafylaktiska reaktioner inkl \xf6dem, angio\xf6dem,  bronkospasm och anafylaktisk chock'],
             ['Metabolism', u'Hyperglykemi'],
             ['Cardiac',
              u'Hj\xe4rtarytmi (t ex f\xf6rmaksflimmer, supraventrikul\xe4r  takykardi och extrasystolier)'],
             ['Respiratory', u'Irritation i munh\xe5la och svalg'],
             ['Respiratory', u'Paradoxal bronkospasm'],
             ['GI', u'Illam\xe5ende'],
             ['Musculoskeletal', u'Artralgi'],
             ['General', u'Ospecifik br\xf6stsm\xe4rta']]]],
 '_pages': [5, 6],
 u'_rank': 18,
 u'_type': u'TSFU'}