{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'], ['Respiratory', u'Nasofaryngit']]],
           ['Common',
            [['Infections', u'Candidainfektion i munh\xe5la och svalg'],
             ['Infections', u'Pneumoni'],
             ['Infections', u'Bronkit'],
             ['Metabolism', u'Hypokalemi'],
             ['Respiratory', u'Heshet/dysfoni'],
             ['Respiratory', u'Sinuit'],
             ['Skin', u'Bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Frakturer'],
             ['Musculoskeletal', u'Artralgi'],
             ['Musculoskeletal', u'Myalgi']]],
           ['Uncommon',
            [['Immune system', u'Andningssymtom (dyspn\xe9)'],
             ['Psychiatric', u'Oro  S\xf6mnsv\xe5righeter, beteendest\xf6rningar inkl'],
             ['Nervous system', u'Tremor'],
             ['Cardiac', u'Palpitationer'],
             ['Cardiac', u'Takykardi'],
             ['Cardiac', u'K\xe4rlkramp'],
             ['Respiratory', u'Halsirritation'],
             ['Musculoskeletal', u'Muskelkramp']]],
           ['Rare',
            [['Immune system', u'Kutana \xf6verk\xe4nslighetsreaktioner'],
             ['Immune system',
              u'Angio\xf6dem (huvudsakligen i ansikte, munh\xe5la och  svalg)'],
             ['Immune system', u'Andningssymtom (bronkospasm)'],
             ['Immune system', u'Anafylaktiska reaktioner inkl anafylaktisk chock'],
             ['Endocrine',
              u'Cushing\u2019s syndrom, Cushingliknande symtombild,  binjurebarksuppression, h\xe4mmad l\xe4ngdtillv\xe4xt hos barn och ungdomar, minskad bent\xe4thet'],
             ['Metabolism', u'F\xf6rh\xf6jda blodglukosniv\xe5er'],
             ['Psychiatric',
              u'psykomotorisk hyperaktivitet och irritabilitet  (fr\xe4mst hos barn)'],
             ['Eye', u'Katarakt, glaukom'],
             ['Cardiac',
              u'Hj\xe4rtarytmi (inklusive f\xf6rmaksflimmer,  supraventrikul\xe4r takykardi och extrasystolier)'],
             ['Respiratory', u'Paradoxal bronkospasm']]],
           ['Unknown', [['Psychiatric', u'']]]],
 '_pages': [7, 9],
 u'_rank': 30,
 u'_type': u'TSFU'}