{'_data': [['Very common',
            [['Endocrine',
              u'systemet Metabolism och nutrition Psykiska st\xf6rningar Insomni (19 %) Depression* Yrsel (11 %) Somnolens (13 %) Huvudv\xe4rk (21 %)* Mycket vanliga'],
             ['Eye', u'\xd6ron och balansorgan'],
             ['Respiratory', u'br\xf6stkorg och mediastinum'],
             ['GI',
              u'n Diarr\xe9 (18 %), Illam\xe5ende (24 %), Muntorrhet (14 %) Lever och gallv\xe4gar Hud och subkutan v\xe4vnad'],
             ['Musculoskeletal', u'a systemet och bindv\xe4v Njurar och urinv\xe4gar'],
             ['Reproductive system', u'gan och br\xf6stk\xf6rtel** Ejakula-tionssvikt (14 %)'],
             ['General',
              u'symtom och/eller symtom vid administrerings st\xe4llet Tr\xf6tthet %)* Sm\xe4rta'],
             ['Investigations',
              u'Skador och f\xf6rgiftningar och behandlingsko Mycket vanliga mplikationer Kirurgiska och medicinska \xe5tg\xe4rder placeboarmen. placebo (926 m\xe4n, Vid OCD, korttidsstudier, 4.4). Klasseffekt ok\xe4nd . \xc4ldre biverkning (se avsnitt Barn mycket vanliga illam\xe5ende (15 %). vanliga mindre vanliga']]],
           ['Common',
            [['Endocrine',
              u'Anorexi \xd6kad aptit* Depersonalis ation Mardr\xf6mmar \xc5ngest* Agitation* Oro Minskad libido* Bruxism Dysgeusi Uppm\xe4rksam hets-st\xf6rning Vanliga'],
             ['Eye', u'Synst\xf6rning Tinnitus*'],
             ['Cardiac', u'Palpitationer *'],
             ['Vascular', u'V\xe4rmevallnin gar*'],
             ['Respiratory', u'G\xe4spningar*'],
             ['GI',
              u'Buksm\xe4rta* Kr\xe4kningar* F\xf6rstoppning * Dyspepsi V\xe4dersp\xe4nnin g Utslag* Hyperhidros'],
             ['Musculoskeletal', u'Myalgi'],
             ['Reproductive system', u'Sexuella st\xf6rningar hos m\xe4n Erektil dysfunktion'],
             ['General', u'i -br\xf6stkorgen*'],
             ['Investigations',
              u'Vanliga 1 219 kvinnor) -endast 1-12 veckor. -4.4). -: huvudv\xe4rk (22 %), insomni (21 %), diarr\xe9 (11 %) och : sm\xe4rta i br\xf6stkorgen, mani, feber, kr\xe4kningar, anorexi, labilitet, : F\xf6rl\xe4ngd EKG QT, suicidf\xf6rs\xf6k, konvulsioner,']]],
           ['Uncommon',
            [['Endocrine',
              u'Hallucinationer* Eufori* Apati Onormala tankar tioner* Onormal koordination Hyperkinesi Amnesi Hypoestesi* Talst\xf6rning Postural yrsel Migr\xe4n* Mindre vanliga'],
             ['Eye', u'\xd6ronv\xe4rk'],
             ['Cardiac', u'Takykardi*'],
             ['Vascular', u'Hypertoni* Vallningar'],
             ['Respiratory', u'Bronkospasm* Dyspn\xe9 N\xe4sblod'],
             ['GI',
              u'Esofagit Dysfagi Hemorrojder Onormalt h\xf6g salivavs\xf6ndring St\xf6rningar i tungan Rapningar Periorbitalt \xf6dem* Purpura* Alopeci* Kallsvettning Hudtorrhet Urtikaria*'],
             ['Musculoskeletal',
              u'Osteoartrit Muskelsvaghet Ryggsm\xe4rta Muskelryckningar Nykturi Urinretention* Polyuri Pollakisuri Miktionsst\xf6rning'],
             ['Reproductive system', u'Vaginal bl\xf6dning Kvinnlig sexuell dysfunktion'],
             ['General', u'Sjukdomsk\xe4nsla* Frossa Pyrexi* Asteni* T\xf6rst'],
             ['Investigations', u'Viktnedg\xe5ng* Viktuppg\xe5ng* Mindre vanliga']]],
           ['Rare',
            [['Endocrine',
              u'Hyperkolesterol emi Hypoglykemi Konversionsst\xf6r ning L\xe4kemedel-sberoende Psykisk st\xf6rning* Aggression* F\xf6rf\xf6ljelsemani Suicidtankar S\xf6mng\xe5ng F\xf6r tidig utl\xf6sning Hyperestesi Sensoriska t\xf6rningar S\xe4llsynta'],
             ['Eye',
              u'Glaukom St\xf6rning i t\xe5rfl\xf6det Skotom, Diplopi Fotofobi Hyphemi Mydriasis*'],
             ['Cardiac', u'Hj\xe4rtinfarkt Bradykardi St\xf6rningar i hj\xe4rtfunktionen'],
             ['Vascular', u'Perifer ischemi'],
             ['Respiratory', u'Laryngospasm Hyperventilatio n Hypoventilation Hicka'],
             ['GI',
              u'Melena Hematochezi Stomatit Tungs\xe5r Tandproblem Glossit Muns\xe5r Onormal leverfunktion Dermatit Bull\xf6s dermatit Follikelutslag Onormal h\xe5rstruktur Onormal hudlukt'],
             ['Musculoskeletal',
              u'Bensjukdom Oliguri Urininkontinens * Bl\xe5st\xf6mnings-sv\xe5righeter'],
             ['Reproductive system',
              u'Menorragi Atrofisk vulvovaginit Balanopostit Genital flytning Priapism* Galaktorr\xe9*'],
             ['General',
              u'Br\xe5ck Fibros p\xe5 injektionsst\xe4llet Minskad l\xe4kemedelstolera'],
             ['Nervous system', u'G\xe5ngsv\xe5righeter Obest\xe4mbara symtom'],
             ['Investigations',
              u'\xd6kat ALAT* \xd6kat ASAT* Onormal sperma S\xe4llsynta Skada K\xe4rlutvidgnings -operation']]],
           ['Very rare',
            [['Endocrine', u'Mycket s\xe4llsynta'], ['Investigations', u'Mycket s\xe4llsynta']]],
           ['Unknown',
            [['Immune system', u'Anafylaktoid reaktion Allergisk reaktion Allergi'],
             ['Endocrine',
              u'Hyperprolakti nemi Hypotyreos Inadekvat ins\xf6ndring av ADH Hyponatremi Paroniri Suicidalt beteende, suicidtankar* ** symtom s\xe5som hyperkinesi, hypertoni, tandagnisslan eller onormal g\xe5ng), Synkope Tecken och symtom p\xe5 serotonergt syndrom har ocks\xe5 rapporterats, i vissa fall associerat med samtidig anv\xe4ndning av serotonerga l\xe4kemedel, s\xe5som agitation, f\xf6rvirring, diafores, diarr\xe9, feber, hypertoni, rigiditet och takykardi. Akatisi och psykomotoris Ingen k\xe4nd frekvens k rastl\xf6shet (se avsnitt 4.4)'],
             ['Eye', u'Onormal syn'],
             ['Vascular', u'Onormala bl\xf6dningar (s\xe5som n\xe4sblod,'],
             ['GI', u'al bl\xf6dning eller hematuri)'],
             ['GI',
              u'Pankreatit Allvarliga leverbiverkni ngar (inklusive hepatit, gulsot och leversvikt) S\xe4llsynta rapporter om sv\xe5ra hudreaktioner (SCAR), t.ex. Stevens-Johnsons syndrom och epidermal nekrolys Angio\xf6dem Ansikts\xf6dem Fotosensitivit et Hudreaktion Pruritus'],
             ['Musculoskeletal', u'Artralgi Muskelkramp er'],
             ['Reproductive system', u'Gynekomasti Oregelbundn a menstruation er'],
             ['General', u'Perifert \xf6dem'],
             ['Investigations',
              u'Onormala kliniska laboratorieres ultat F\xf6r\xe4ndrad trombocytfun serumkolester ol Ingen k\xe4nd frekvens']]]],
 '_note': u' ?MSFU',
 '_pages': [10, 17],
 u'_rank': 51,
 u'_type': u'MSFU'}