{'_data': [['Very common',
            [['Psychiatric', u'Insomni (19%)'],
             ['Nervous system', u'Yrsel (11 %), Somnolens (13%), Huvudv\xe4rk (21%)*'],
             ['GI', u'Diarr\xe9 (18 %), Illam\xe5ende (24 %), Muntorrhet (14 %)'],
             ['Reproductive system', u'Ejakulationssvikt (14 %) Tr\xf6tthet %)*'],
             ['Other',
<<<<<<< HEAD
              u'm\xe4n, 1 219 kvinnor) Vid OCD, korttidsstudier, avslutad behandling (se avsnitt Klasseffekt \xc4ldre Barn mycket vanliga vanliga : mindre vanliga :']]],
=======
              u'(926 m\xe4n, 1 219 kvinnor) Vid OCD, korttidsstudier, avslutad behandling (se avsnitt Klasseffekt \xc4ldre Barn mycket vanliga vanliga mindre vanliga']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Common',
            [['Infections', u'Faryngit'],
             ['Metabolism', u'Anorexi \xd6kad aptit*'],
             ['Psychiatric',
<<<<<<< HEAD
              u'Depression* Depersonali-satio n Mardr\xf6mmar \xc5ngest* Agitation* Oro Minskad libido* Bruxism'],
=======
              u'Depression* Depersonali-sation Mardr\xf6mmar \xc5ngest* Agitation* Oro Minskad libido* Bruxism'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system',
              u'Parestesier* Tremor Hypertoni Dysgeusi Uppm\xe4rksamhets st\xf6rning'],
             ['Eye', u'Synst\xf6rning'],
             ['Ear', u'Tinnitus*'],
             ['Cardiac', u'Palpitationer*'],
<<<<<<< HEAD
             ['Vascular', u'V\xe4rme-vallningar *'],
=======
             ['Vascular', u'V\xe4rme-vallningar*'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Respiratory', u'G\xe4spningar*'],
             ['GI',
              u'Buksm\xe4rta* Kr\xe4kningar* F\xf6rstoppning* Dyspepsi V\xe4dersp\xe4nning'],
             ['Skin', u'Utslag* Hyperhidros'],
             ['Musculoskeletal', u'Myalgi'],
             ['Reproductive system',
              u'Sexuella st\xf6rningar hos m\xe4n Erektil dysfunktion Sm\xe4rta i br\xf6stkorgen*'],
             ['Other',
<<<<<<< HEAD
              u'endast 1-12 veckor. -4.4). -: huvudv\xe4rk (22 %), insomni (21 %), diarr\xe9 (11 %) och illam\xe5ende (15 %). sm\xe4rta i br\xf6stkorgen, mani, feber, kr\xe4kningar, anorexi, labilitet, aggression, F\xf6rl\xe4ngd EKG QT, suicidf\xf6rs\xf6k, konvulsioner, extrapyramidala']]],
=======
              u'endast 1-12 veckor. -4.4). -: huvudv\xe4rk (22 %), insomni (21 %), diarr\xe9 (11 %) och illam\xe5ende (15 %). : sm\xe4rta i br\xf6stkorgen, mani, feber, kr\xe4kningar, anorexi, labilitet, aggression, : F\xf6rl\xe4ngd EKG QT, suicidf\xf6rs\xf6k, konvulsioner, extrapyramidala']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Infections', u'\xd6vre luftv\xe4gsinfektion Rinit'],
             ['Psychiatric', u'Hallucinationer* Eufori* Apati Onormala tankar'],
             ['Nervous system',
              u'Konvulsioner* Ofrivilliga muskelkontrak-tioner* Onormal koordination Hyperkinesi Amnesi Hypoestesi* Talst\xf6rning Postural yrsel Migr\xe4n*'],
             ['Ear', u'\xd6ronv\xe4rk'],
             ['Cardiac', u'Takykardi*'],
             ['Vascular', u'Hypertoni* Vallningar'],
             ['Respiratory', u'Bronkospasm* Dyspn\xe9 N\xe4sblod'],
             ['GI',
              u'Esofagit Dysfagi Hemorrojder Onormalt h\xf6g salivavs\xf6ndring St\xf6rningar i tungan Rapningar'],
             ['Skin',
              u'Periorbitalt \xf6dem* Purpura* Alopeci* Kallsvettning Hudtorrhet Urtikaria*'],
             ['Musculoskeletal', u'Osteoartrit Muskelsvaghet Ryggsm\xe4rta Muskelryckningar'],
             ['Renal', u'Nykturi Urinretention* Polyuri Pollakisuri Miktionsst\xf6rning'],
             ['Reproductive system',
              u'Vaginal bl\xf6dning Kvinnlig sexuell dysfunktion Sjukdomsk\xe4nsla* Frossa Pyrexi* Asteni* T\xf6rst'],
             ['Investigations', u'Viktnedg\xe5ng* Viktuppg\xe5ng*']]],
           ['Rare',
            [['Infections', u'Divertikulit Gastroenterit Otitis media'],
             ['Neoplasms', u'Neoplasm\u2020'],
<<<<<<< HEAD
             ['Blood', u'Lymfa-denopa'],
             ['Metabolism', u'Hyper-koleste rolemi Hypoglykemi'],
             ['Psychiatric',
              u'Konversions-s t\xf6rning L\xe4kemedels-b eroende Psykisk st\xf6rning* Aggression* F\xf6rf\xf6ljelse-ma ni Suicidtankar S\xf6mng\xe5ng F\xf6r tidig utl\xf6sning'],
=======
             ['Blood', u'Lymfa-denopati'],
             ['Metabolism', u'Hyper-kolesterolemi Hypoglykemi'],
             ['Psychiatric',
              u'Konversions-st\xf6rning L\xe4kemedels-beroende Psykisk st\xf6rning* Aggression* F\xf6rf\xf6ljelse-mani Suicidtankar S\xf6mng\xe5ng F\xf6r tidig utl\xf6sning'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system',
              u'Koma*, Koreoatetos Dyskinesi, Hyperestesi Sensoriska t\xf6rningar'],
             ['Eye',
              u'Glaukom St\xf6rning i t\xe5rfl\xf6det Skotom, Diplopi Fotofobi Hyphemi Mydriasis*'],
<<<<<<< HEAD
             ['Cardiac', u'Hj\xe4rtinfarkt Bradykardi St\xf6rningar i hj\xe4rt-funktion en'],
             ['Vascular', u'Perifer ischemi'],
             ['Respiratory',
              u'Laryngo-spas m Hyper-ventilat ion Hypo-ventilati on Stridor Dysfoni Hicka'],
=======
             ['Cardiac', u'Hj\xe4rtinfarkt Bradykardi St\xf6rningar i'],
             ['Cardiac', u'funktionen'],
             ['Vascular', u'Perifer ischemi'],
             ['Respiratory',
              u'Laryngo-spasm Hyper-ventilation Hypo-ventilation Stridor Dysfoni Hicka'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI', u'Melena Hematochezi Stomatit Tungs\xe5r Tandproblem Glossit Muns\xe5r'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin',
              u'Dermatit Bull\xf6s dermatit Follikelutslag Onormal h\xe5rstruktur Onormal hudlukt'],
             ['Musculoskeletal', u'Bensjukdom'],
<<<<<<< HEAD
             ['Renal', u'Oliguri Urin-inkontine ns* Bl\xe5st\xf6mnings-sv\xe5righeter'],
             ['Reproductive system',
              u'Menorragi Atrofisk vulvovaginit Balanopostit Genital flytning Priapism* Galaktorr\xe9* Br\xe5ck Minskad L\xe4kemedel-sto lerans G\xe5ngsv\xe5rig-he ter Obest\xe4mbara symtom'],
=======
             ['Renal', u'Oliguri Urin-inkontinens* Bl\xe5st\xf6mnings-sv\xe5righeter'],
             ['Reproductive system',
              u'Menorragi Atrofisk vulvovaginit Balanopostit Genital flytning Priapism* Galaktorr\xe9* Br\xe5ck Minskad L\xe4kemedel-stolerans G\xe5ngsv\xe5rig-heter Obest\xe4mbara symtom'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Investigations', u'\xd6kat ALAT* \xd6kat ASAT* Onormal sperma Skada'],
             ['Other', u'K\xe4rlutvidgnin gsoperation']]],
           ['Very rare', []],
           ['Unknown',
<<<<<<< HEAD
            [['Blood', u'Leukopeni Trombo-cytop eni'],
             ['Immune system', u'Anafylak-toid reaktion Allergisk reaktion Allergi'],
             ['Endocrine', u'Hyper-prolakt inemi Inadekvat ins\xf6ndring av ADH'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Paroniri Suicidalt beteende, Suicid-tankar ***'],
             ['Nervous system',
              u'R\xf6relsest\xf6rnin gar (inklusive extra-pyramid ala symtom s\xe5som hyperkinesi, hypertoni, tandagnisslan eller onormal g\xe5ng), Synkope Tecken och symtom p\xe5 serotonergt syndrom har ocks\xe5 rapporterats, i vissa fall associerat med samtidig anv\xe4ndning av serotonerga l\xe4kemedel, s\xe5som agitation, f\xf6rvirring, diafores, diarr\xe9, feber, hypertoni, rigiditet och takykardi. Akatisi och psyko-motoris k rastl\xf6shet (se avsnitt 4.4)'],
             ['Eye', u'Onormal syn'],
             ['Vascular', u'Onormala bl\xf6dningar (s\xe5som n\xe4sblod,'],
             ['GI', u'al bl\xf6dning eller hematuri)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Allvarliga lever-biverkni ngar (inklusive hepatit, gulsot och leversvikt)'],
             ['Skin',
              u'S\xe4llsynta rapporter om sv\xe5ra hudreaktioner (SCAR), t.ex. Stevens-Johns ons syndrom och epidermal nekrolys Angio\xf6dem Ansikts\xf6dem Foto-sensitivit et Hudreaktion Pruritus'],
             ['Musculoskeletal', u'Artralgi Muskel-kram per'],
             ['Reproductive system',
              u'Gynekomasti Oregelbundna Menstruatio-n er Perifert \xf6dem'],
             ['Investigations',
              u'Onormala kliniska laboratorieres ultat F\xf6r\xe4ndrad trombocyt-fun ktion \xd6kat serum-koleste rol']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 13],
 u'_rank': 65,
=======
            [['Blood', u'Leukopeni Trombo-cytopeni'],
             ['Immune system', u'Anafylak-toid reaktion Allergisk reaktion Allergi'],
             ['Endocrine', u'Hyper-prolaktinemi Inadekvat ins\xf6ndring av ADH'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Paroniri Suicidalt beteende, Suicid-tankar***'],
             ['Nervous system',
              u'R\xf6relsest\xf6rnin gar (inklusive extra-pyramidala symtom s\xe5som hyperkinesi, hypertoni, tandagnisslan eller onormal g\xe5ng), Synkope Tecken och symtom p\xe5 serotonergt syndrom har ocks\xe5 rapporterats, i vissa fall associerat med samtidig anv\xe4ndning av serotonerga l\xe4kemedel, s\xe5som agitation, f\xf6rvirring, diafores, diarr\xe9, feber, hypertoni, rigiditet och takykardi. Akatisi och'],
             ['Psychiatric', u'motorisk rastl\xf6shet (se avsnitt 4.4)'],
             ['Eye', u'Onormal syn'],
             ['Vascular',
              u'Onormala bl\xf6dningar (s\xe5som n\xe4sblod, gastro-intestinal bl\xf6dning eller hematuri)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Allvarliga lever-biverkningar (inklusive hepatit, gulsot och leversvikt)'],
             ['Skin',
              u'S\xe4llsynta rapporter om sv\xe5ra hudreaktioner (SCAR), t.ex. Stevens-Johnsons syndrom och epidermal nekrolys Angio\xf6dem Ansikts\xf6dem Foto-sensitivitet Hudreaktion Pruritus'],
             ['Musculoskeletal', u'Artralgi Muskel-kramper'],
             ['Reproductive system',
              u'Gynekomasti Oregelbundna Menstruatio-ner Perifert \xf6dem'],
             ['Investigations',
              u'Onormala kliniska laboratorieres ultat F\xf6r\xe4ndrad trombocyt-funktion \xd6kat serum-kolesterol']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 13],
 u'_rank': 66,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}