{'_data': [['Very common',
            [['Psychiatric', u'Agitation'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Illam\xe5ende  Kr\xe4kning']]],
           ['Common',
            [['Nervous system', u'S\xf6mnighet  Yrsel  Huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypertoni'],
             ['Respiratory',
              u'Respiratoriska st\xf6rningar  Respiratorisk depression Laryngospasm'],
             ['GI', u'Hypersekretion av saliv'],
             ['General', u'Frossa  Pyrexi'],
             ['Investigations',
              u'Avvikande blodglukos  Avvikande leverfunktionstest Avvikande antal vita blodkroppar F\xf6rh\xf6jd blodfosfor F\xf6rh\xf6jd serumkreatinin'],
             ['Injury', u'Hypotermi']]],
           ['Uncommon',
            [['Cardiac',
              u'Fullst\xe4ndig atrioventrikul\xe4rt  block Kardiella arytmier (inklusive ventrikul\xe4ra arytmier), f\xf6rmaksflimmer, extrasystole (ventrikul\xe4r, supraventrikul\xe4r, bigenimi)'],
             ['Respiratory', u'Andningsstillest\xe5nd  Astma Hypoxi'],
             ['Investigations', u'']]],
           ['Unknown',
            [['Immune system',
              u'Anafylaktisk reaktion  Anafylatoid reaktion Hyperk\xe4nslighet'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Nervous system', u'Krampanfall  Dystoni'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd'],
             ['Respiratory', u'Bronkospasm  Dyspn\xe9 V\xe4sande andning'],
             ['Hepato', u'Hepatit  Leversvikt Levernekros'],
             ['Skin', u'Kontaktdermatit  Kl\xe5da Utslag Svullnad i ansiktet N\xe4sselutslag'],
             ['General', u'Obehag i br\xf6stet  Malign hypertermi']]]],
 '_pages': [7, 10],
 u'_rank': 23,
 u'_type': u'TSFU'}