{'_data': [['Very common',
            [['Psychiatric', u'Agitation'],
             ['Cardiac', u'Bradykardi'],
             ['Blood', u'Hypotension'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Illam\xe5ende  Kr\xe4kningar']]],
           ['Common',
            [['Nervous system', u'Somnolens  Yrsel  Huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Blood', u'Hypertension'],
             ['Respiratory', u'Andningsbesv\xe4r  Laryngospasm'],
             ['GI', u'\xd6kad salivering'],
             ['General', u'Frossa  Feber'],
             ['Investigations',
              u'Avvikande blodglukos  Avvikande leverfunktionsprover Avvikande antal vita blodkroppar F\xf6rh\xf6jt fluorid i blodet'],
             ['Injury', u'Hypotermi']]],
           ['Uncommon', [['Cardiac', u'Fullst\xe4ndigt atrioventrikul\xe4rt  block']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk reaktion'],
             ['Nervous system', u'Kramper'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd'],
             ['Respiratory', u'Bronkospasm'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Kontaktdermatit'],
             ['General', u'Obehag i br\xf6stet']]]],
 '_pages': [6, 10],
 u'_rank': 21,
 u'_type': u'TSFU'}