{'_data': [['Very common',
            [['Nervous system', u'yrsel, dyskinesi, somnolens'],
             ['GI', u'vanliga illam\xe5ende f\xf6rstoppning, kr\xe4kningar'],
             ['GI', u'vanliga illam\xe5ende f\xf6rstoppning, kr\xe4kningar']]],
           ['Common',
            [['Psychiatric',
              u'onormala dr\xf6mmar, beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende, f\xf6rvirring, hallucinationer, s\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Eye', u'synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Vascular', u'hypotension'],
             ['General', u'tr\xf6tthet, perifert \xf6dem'],
             ['Investigations', u'viktminskning inklusive minskad aptit'],
             ['Psychiatric', u'onormala dr\xf6mmar, s\xf6mnl\xf6shet'],
             ['Nervous system', u'yrsel, huvudv\xe4rk, somnolens'],
             ['General', u'tr\xf6tthet']]],
           ['Uncommon',
            [['Infections', u'pneumoni'],
             ['Psychiatric',
              u'Mindre vanliga hets\xe4tning , tv\xe5ngsm\xe4ssigt k\xf6pbeteende, vanf\xf6rest\xe4llningar, hyperfagi , hypersexualitet, st\xf6rningar av libido, paranoia, patologiskt spelberoende, rastl\xf6shet'],
             ['Nervous system',
              u'minnesf\xf6rlust, hyperkinesi, episoder av pl\xf6tsligt insomnande, synkope'],
             ['Cardiac', u'hj\xe4rtsvikt'],
             ['Respiratory', u'Dyspn\xe9, hicka'],
             ['Skin', u'\xf6verk\xe4nslighet, pruritus, hudutslag'],
             ['Infections', u'pneumoni'],
             ['Psychiatric',
              u'beteendem\xe4ssiga symtom p\xe5 st\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende s\xe5som hets\xe4tning, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hypersexualitet och patologiskt spelberoende ; f\xf6rvirring, vanf\xf6rest\xe4llningar , hallucinationer, hyperfagi, st\xf6rningar av libido, paranoia , rastl\xf6shet'],
             ['Nervous system',
              u'Mindre vanliga minnesf\xf6rlust , dyskinesi, hyperkinesi , episoder av pl\xf6tsligt insomnande, synkope'],
             ['Cardiac', u'hj\xe4rtsvikt'],
             ['Eye', u'synf\xf6rs\xe4mring inklusive diplopi, dimsyn och nedsatt synsk\xe4rpa'],
             ['Respiratory', u'dyspn\xe9, hicka'],
             ['Skin', u'\xf6verk\xe4nslighet, pruritus, hudutslag'],
             ['General', u'perifert \xf6dem'],
             ['Investigations',
              u'viktminskning inklusive minskad aptit, vikt\xf6kning En biverkan som observerats efter att produkten kommit ut p\xe5 marknaden. Med 95 % s\xe4kerhet \xe4r frekvensen inte h\xf6gre \xe4n f\xf6r mindre vanliga, men den kan vara l\xe4gre. En exakt frekvensuppskattning \xe4r inte m\xf6jlig eftersom biverkan inte f\xf6rekom i den kliniska databasen d\xe4r 1395 patienter med Restless legs syndrom som behandlades med pramipexol ingick. Somnolens Pramipexol \xe4r vanligen associerat med somnolens och har \xe4ven associerats med en mindre vanlig biverkan, \xf6verdriven somnolens under dagtid och episoder av pl\xf6tsligt insomnande (se \xe4ven avsnitt 4.4). St\xf6rningar av libido Pramipexol kan i mindre vanliga fall ha samband med st\xf6rningar av libido (\xf6kning eller minskning). St\xf6rd impulskontroll och tv\xe5ngsm\xe4ssigt beteende Patienter som behandlas med dopaminagonister f\xf6r Parkinsons sjukdom, inklusive SIFROL s\xe4rskilt vid h\xf6ga doser, har rapporteras visa tecken p\xe5 patologiskt spelberoende, \xf6kad libido och hypersexualitet, vilket vanligen \xe4r reversibelt vid dosreduktion eller uts\xe4ttning (se \xe4ven avsnitt 4.4). I en retrospektiv tv\xe4rsnittsunders\xf6kning (cross sectional) och fall-kontroll-studie med 3 090 patienter med Parkinsons sjukdom, hade 13,6 % av alla patienter som fick dopaminerg eller icke-dopaminerg behandling symtom p\xe5 en st\xf6rd impulskontroll under de senaste sex m\xe5naderna. Symtomen som observerats inkluderar spelberoende, tv\xe5ngsm\xe4ssigt k\xf6pbeteende, hets\xe4tning, och tv\xe5ngsm\xe4ssigt sexuellt beteende (hypersexualitet). T\xe4nkbara oberoende riskfaktorer f\xf6r st\xf6rningar i impulskontrollen omfattade dopaminerg behandling och h\xf6gre doser av dopaminerg behandling, \xe5lder (\u2264 65 \xe5r), ensamst\xe5ende och enligt egen uppgift spelberoende i sl\xe4kten. Hj\xe4rtsvikt I kliniska studier och fr\xe5n observationer efter produktens intr\xe4de p\xe5 marknaden, har hj\xe4rtsvikt rapporterats hos patienter med pramipexol. I en farmakoepidemiologisk studie associerades pramipexol med en \xf6kad risk f\xf6r hj\xe4rtsvikt j\xe4mf\xf6rt med icke-anv\xe4ndning av pramipexol (observerat risk ratio 1,86; 95 % konfidensintervall, 1,21-2,85).']]],
           ['Unknown',
            [['Investigations',
              u'vanliga vikt\xf6kning En biverkan som observerats efter att produkten kommit ut p\xe5 marknaden. Med 95 % s\xe4kerhet \xe4r frekvensen inte h\xf6gre \xe4n f\xf6r mindre vanliga, men den kan vara l\xe4gre. En exakt frekvensuppskattning \xe4r inte m\xf6jlig eftersom biverkan inte f\xf6rekom i den kliniska databasen d\xe4r 2762 patienter med Parkinsons sjukdom som behandlades med pramipexol ingick. Restless Legs Syndrom, de vanligaste biverkningarna De vanligaste biverkningar (\u2265 5 %) som rapporterades hos patienter med restless legs vid behandling med pramipexol var illam\xe5ende, huvudv\xe4rk, yrsel och tr\xf6tthet. Illam\xe5ende och tr\xf6tthet f\xf6rekom oftare hos kvinnliga patienter som behandlades med SIFROL (20,8 % respektive 10,5 %) j\xe4mf\xf6rt med manliga (6,7 % respektive 7,3 %). Tabell 2: Restless legs syndrom Organsystem Biverkan'],
             ['Vascular', u'vanliga hypotension']]]],
 '_pages': [7, 10],
 u'_rank': 29,
 u'_type': u'LSFU'}