{'_data': [['Uncommon',
            [['Nervous system',
              u's\xf6mnproblem inklusive insomnia, mardr\xf6mmar, depression, minnesf\xf6rlust.'],
             ['Reproductive system', u'sexuella st\xf6rningar.']]],
           ['Rare',
            [['Blood', u'anemi.'],
             ['Nervous system', u'huvudv\xe4rk, parestesi, yrsel, perifer neuropati.'],
             ['GI',
              u'f\xf6rstoppning, buksm\xe4rta, gasbildning, dyspepsi, diarr\xe9, illam\xe5ende, kr\xe4kning, pankreatit.'],
             ['Hepato', u'hepatit/gulsot.'],
             ['Skin',
              u'hudutslag, pruritus, alopeci. Muskuloskeletala systemet, bindv\xe4v och skelett'],
             ['Skin',
              u'myopati* (inklusive myosit), rabdomyolys med eller utan akut njursvikt (se avsnitt 4.4), myalgi, muskelkramper, myosit, polymyosit. *I en klinisk studie intr\xe4ffade myopati oftare hos patienter som behandlades med simvastatin 80 mg dagligen j\xe4mf\xf6rt med patienter som behandlades med 20 mg dagligen (1,0 % j\xe4mf\xf6rt med 0,02 %) (se avsnitt 4.4 och 4.5).'],
             ['General',
              u'asteni. Det har kommit s\xe4llsynta rapporter om ett tydligt \xf6verk\xe4nslighetssyndrom som har inkluderat n\xe5gra av f\xf6ljande symtom: angio\xf6dem, lupusliknande syndrom, reumatisk polymyalgi, dermatomyosit, vaskulit, trombocytopeni, eosinifili, SR-stegring, artrit och artralgi, urtikaria, fotosensitivitet, feber, v\xe4rmevallning, dyspn\xe9 och allm\xe4n sjukdomsk\xe4nsla.'],
             ['Investigations',
              u'f\xf6rh\xf6jda serumtransaminaser (alaninaminotransferas, aspartataminotransferas, \u03b3 glutamyltranspeptidas) (se avsnitt 4.4 Effekter p\xe5 levern), f\xf6rh\xf6jt alkaliskt fosfatas; f\xf6rh\xf6jda CK niv\xe5er i serum (se avsnitt 4.4). F\xf6ljande biverkningar har dessutom rapporterats med vissa statiner: \u2022s\xf6mnst\xf6rningar inkluderande mardr\xf6mmar \u2022minnesf\xf6rlust \u2022sexuell dysfunktion. Diabetes Mellitus: Frekvensen kommer att bero p\xe5 n\xe4rvaron eller fr\xe5nvaron av riskfaktorer (fasteblodglukos > 5,6 mmol/l, BMI>30kg/m , f\xf6rh\xf6jda triglycerider, hypertoni i anamnesen).']]],
           ['Very rare',
            [['Psychiatric', u'insomnia : depression'],
             ['Nervous system', u'nedsatt minnesf\xf6rm\xe5ga'],
             ['Hepato', u'leversvikt.']]],
           ['Unknown',
            [['Respiratory', u'interstitiell lungsjukdom.'],
             ['Skin',
              u'tendinit, tendinopati som ibland kan kompliceras av senbrott, senbrott.'],
             ['Reproductive system', u'erektil dysfunktion']]]],
 '_pages': [10, 12],
 u'_rank': 16,
 u'_type': u'LSFU'}