{'_data': [['Very common',
            [['Infections',
              u'\xd6vre luftv\xe4gsinfektion (nasofaryngit, faryngit, laryngit och rinit)']]],
           ['Common',
            [['Infections',
              u'Bakteriella infektioner (s\xe5som cellulit), virusinfektioner (s\xe5som influensa och herpes), bronkit, sinuit, ytliga svampinfektioner'],
             ['Blood', u'Anemi'],
             ['Immune system',
              u'Allergiska reaktioner (bronkospasm, hypersensivitet, urtikaria), autoantikroppspositiv'],
             ['Psychiatric', u'Depression, insomnia Centrala och perifera'],
             ['Vascular', u'Hypertension'],
             ['GI', u'Konstipation, dyspepsi, magtarm- och buksm\xe4rtor, illam\xe5ende'],
             ['Hepato',
              u'Alaninaminotransferas f\xf6rh\xf6jda, aspartataminotransferas f\xf6rh\xf6jda'],
             ['Skin', u'Alopeci, dermatit, pruritus, utslag'],
             ['Renal',
              u'Feber, asteni, reaktion vid injektionsst\xe4llet (s\xe5som rodnad vid injektionsst\xe4llet, urtikaria, induration, sm\xe4rta, bl\xe5m\xe4rken, kl\xe5da, irritation och parestesi), f\xf6rs\xe4mrad l\xe4kning, obehag i br\xf6stet Skador och f\xf6rgiftningar och behandlingskomplikationer']]],
           ['Uncommon',
            [['Infections',
              u'Septisk chock, sepsis, tuberkulos, nedre luftv\xe4gsinfektion (s\xe5som pneumoni), opportunistiska infektioner (s\xe5som invasiv svampinfektion [histoplasmos, koccidioidomykos, pneumocytos], bakteriell, atypisk mykobakteriell infektion och protozoal), pyelonefrit, abscess, bakteriell artrit, infekti\xf6s bursit'],
             ['Infections',
              u'Neoplasm (s\xe5som hudcancer, skivepitelcarcinom och melanocytnevus)'],
             ['Blood', u'Leukopeni, trombocytopeni'],
             ['Endocrine',
              u'Thyroidearubbningar (s\xe5som hypothyroidism, hyperthyroidism och struma)'],
             ['Metabolism', u'F\xf6rh\xf6jt blodglukos, f\xf6rh\xf6jda lipider'],
             ['Eye',
              u'Synrubbningar (s\xe5som dimsyn och minskad synsk\xe4rpa), konjunktivit, \xf6gonallergi (s\xe5som kl\xe5da och irritation)'],
             ['Cardiac',
              u'Kronisk hj\xe4rtsvikt (ny eller f\xf6rv\xe4rrad), arytmi, ischemisk koronarart\xe4rsrubbning'],
             ['Vascular',
              u'Trombos (s\xe5som djup ven- och aortatrombos), Raynauds fenomen, blodvallning Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Vascular',
              u'Astma och relaterade symtom (s\xe5som v\xe4sningar och bronkiell hyperaktivitet)'],
             ['GI',
              u'Gastrointestinala inflammatoriska besv\xe4r (s\xe5som gastrit och kolit), gastroesofagal refluxsjukdom, stomatit'],
             ['Hepato', u'Kolelitiasis, leverrubbningar'],
             ['Skin',
              u'Psoriasis (ny eller f\xf6rs\xe4mring av befintlig psoriasis, palmar/plantar och pustul\xe4r), urtikaria, vaskulit (kutan)'],
             ['Renal', u'Urinbl\xe5serubbningar'],
             ['Renal',
              u'Br\xf6stbesv\xe4r, menstruationsrubbningar Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Renal', u'Benfraktur']]],
           ['Rare',
            [['Infections',
              u'Hepatit B reaktivering Neoplasier; benigna, maligna och ospecifiserade (samt cystor och polyper)'],
             ['Infections', u'Lymfom, leukemi, melanom'],
             ['Blood', u'Pancytopeni'],
             ['Immune system',
              u'Allvarliga systemiska \xf6verk\xe4nslighetsreaktioner (omfattar anafylaktisk reaktion), vaskulit (systemisk), sarkoidos'],
             ['Vascular', u'Interstitial lungsjukdom'],
             ['Skin', u'Hudexfoliation Muskuloskeletala systemet och bindv\xe4v'],
             ['Skin', u'Lupusliknande syndrom'],
             ['Renal', u'Njurrubbningar Reproduktionsorgan och br\xf6stk\xf6rtel']]],
           ['Unknown', [['Infections', u'Merkelcellskarcinom*'], ['Blood', u'Aplastisk anemi*']]]],
 '_pages': [7, 12],
 u'_rank': 35,
 u'_type': u'LSFU'}