{'_data': [['Rare',
            [['Blood', u'anemi'],
             ['Nervous system', u'huvudv\xe4rk, parestesi, yrsel, perifer neuropati'],
             ['GI',
              u'f\xf6rstoppning, buksm\xe4rtor, flatulens, dyspepsi, diarr\xe9, illam\xe5ende, kr\xe4kningar, pankreatit'],
             ['Hepato', u'hepatit/gulsot'],
             ['Skin', u'utslag, pruritus, alopesi'],
             ['Musculoskeletal',
              u'myopati*(inkluderande myosit), rabdomyolys med eller utan akut njursvikt (se avsnitt 4.4), myalgi, muskelkramper * I en klinisk studie intr\xe4ffade myopati oftare hos patienter som behandlades med simvastatin 80 mg dagligen j\xe4mf\xf6rt med patienter som behandlades med 20 mg dagligen (1,0 % j\xe4mf\xf6rt med 0,02 %).'],
             ['General',
              u'asteni Det har rapporterats om s\xe4llsynta fall av \xf6verk\xe4nslighetssyndrom med n\xe5gra av f\xf6ljande symptom: angio\xf6dem, lupusliknande syndrom, reumatisk polymyalgi, dermatomyosit, vaskulit, trombocytopeni, eosinofili, SR-stegring, artrit och artralgi, urtikaria, fotosensibilisering, feber, rodnad, dyspn\xe9, och allm\xe4n sjukdomsk\xe4nsla.'],
             ['Investigations',
              u'f\xf6rh\xf6jda aminotransferaser i serum (alaninaminotransferas, aspartataminotransferas, gamma-glutamyl-transferas) (se avsnitt 4.4 P\xe5verkan p\xe5 levern), f\xf6rh\xf6jda v\xe4rden av alkaliska fosfataser, f\xf6rh\xf6jda CK-niv\xe5er i serum. F\xf6ljande biverkningar har dessutom rapporterats med vissa statiner: \u2022s\xf6mnst\xf6rningar inkluderande mardr\xf6mmar \u2022minnesf\xf6rlust \u2022sexuell dysfunktion.']]],
           ['Very rare',
            [['Psychiatric', u'insomnia : depression'],
             ['Nervous system', u'nedsatt minnesf\xf6rm\xe5ga'],
             ['Hepato', u'leversvikt']]],
           ['Unknown',
            [['Respiratory', u'Interstitiell lungsjukdom (se avsnitt 4.4).'],
             ['Reproductive system', u'erektil dysfunktion']]]],
 '_pages': [10, 12],
 u'_rank': 13,
 u'_type': u'LSFU'}