{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk  '],
             ['General', u'Sm\xe4rta p\xe5 appliceringsst\xe4llet  '],
             ['Skin', u'Lokala misst\xe4nkta relaterade biverkningar \xe4r mindre ']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel  '],
             ['General', u'Irritation p\xe5 appliceringsst\xe4llet  '],
             ['GI', u'Illam\xe5ende  '],
             ['GI', u'Aft\xf6s stomatit  '],
             ['GI', u'Sm\xe4rta i tandk\xf6ttet  '],
             ['Skin', u'Erytem  ']]]],
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'LSFU'}