{'_data': [['Very common',
            [['Skin', u'sveda, pruritus,'], ['General', u'erytem vid applikationsst\xe4llet']]],
           ['Common', [['Skin', u'fj\xe4llning,'], ['General', u'sm\xe4rta, torrhet,']]],
           ['Uncommon',
            [['Skin', u'akne depigmen-terin g av huden parestesi,'],
             ['General', u'dermatit, obehagsk\xe4nsla,  eksem,']]],
           ['Rare',
            [['Skin', u'bl\xe5sor,'],
             ['General', u'hudutslag,'],
             ['Immune system', u'f\xf6rv\xe4rrad astma (se avsnitt']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'MSFU'}