{'_data': [['Common', [['General', u'Svag \xf6kning av kroppstemperatur en.']]],
           ['Uncommon',
            [['GI', u'Aptitl\xf6shet, illam\xe5ende, kr\xe4kningar.'],
             ['General', u'Frysningar.']]],
           ['Rare',
            [['Respiratory', u'Andn\xf6d.'],
             ['Vascular', u'Hypotoni, hypertoni.'],
             ['General',
              u'\xd6verk\xe4nslighets-reaktioner (t.ex. anafylaktiska eller anafylaktoida reaktioner, hudutslag, urtikaria, rodnad, huvudv\xe4rk), upplevelse av v\xe4rme eller kyla, blekhet (cyanos), sm\xe4rtor i hals, rygg, skelett, br\xf6st och l\xe4ndrygg.']]],
           ['Very rare', [['Reproductive system', u'Priapism.']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 7,
 u'_type': u'MSFU'}