<<<<<<< HEAD
{'_data': [[u'Unknown',
            [['Nervous system',
              u'yrsel, vertigo   vanliga   somnolens, huvudv\xe4rk, s\xf6mnst\xf6rningar   mindre vanliga'],
             ['Cardiac', u'palpitationer, angina pectoris   mindre vanliga'],
             ['Vascular', u'symtomatisk hypotoni (s\xe4rskilt hos patienter   mindre vanliga'],
             ['GI', u'buksm\xe4rta, f\xf6rstoppning   mindre vanliga'],
             ['General', u'asteni, tr\xf6tthet, \xf6dem   mindre vanliga'],
             ['Investigations', u'hyperkalemi   vanliga'],
             ['Nervous system', u'yrsel   vanliga'],
             ['Ear', u'vertigo   vanliga'],
             ['General', u'asteni/tr\xf6tthet   vanliga'],
             ['Nervous system', u'yrsel   vanliga   huvudv\xe4rk   mindre vanliga'],
             ['Cardiac', u'synkope, f\xf6rmaksflimmer, cerebrovaskul\xe4r   s\xe4llsynta'],
             ['Vascular', u'hypotoni inkluderande ortostatisk hypotoni   vanliga'],
             ['Blood', u'anemi   vanliga'],
             ['Respiratory', u'dyspn\xe9   mindre vanliga   hosta'],
             ['GI', u'diarr\xe9, illam\xe5ende, kr\xe4kningar   mindre vanliga'],
             ['Skin', u'urtikaria, pruritus, utslag   mindre vanliga'],
             ['General', u'asteni/tr\xf6tthet   mindre vanliga'],
             ['Investigations', u'f\xf6rh\xf6jda v\xe4rden av urea i blodet,   vanliga'],
             ['Metabolism', u'hyperkalemi   mindre vanliga*'],
             ['Renal', u'nedsatt njurfunktion   vanliga'],
             ['Nervous system', u'yrsel   vanliga'],
             ['Vascular', u'hypotoni   vanliga'],
             ['General', u'asteni/tr\xf6tthet   vanliga'],
             ['Investigations', u'hypoglykemi   vanliga'],
             ['Blood', u'anemi   ingen k\xe4nd'],
             ['Cardiac', u'synkope, palpitationer   ingen k\xe4nd'],
             ['Vascular', u'ortostatisk hypotoni   ingen k\xe4nd'],
             ['GI', u'diarr\xe9   ingen k\xe4nd'],
             ['Musculoskeletal', u'ryggv\xe4rk   ingen k\xe4nd   frekvens'],
             ['Renal', u'urinv\xe4gsinfektion   ingen k\xe4nd'],
             ['General', u'influensaliknande symtom   ingen k\xe4nd   frekvens'],
             ['Blood', u'anemi, trombocytopeni   ingen k\xe4nd'],
             ['Ear', u'tinnitus   ingen k\xe4nd'],
             ['Immune system',
              u'\xf6verk\xe4nslighet: anafylaktiska reaktioner,   s\xe4llsynta'],
             ['Nervous system', u'migr\xe4n   ingen k\xe4nd   frekvens'],
             ['Respiratory', u'hosta   ingen k\xe4nd   frekvens'],
             ['GI', u'diarr\xe9, pankreatit   ingen k\xe4nd'],
             ['General', u'sjukdomsk\xe4nsla   ingen k\xe4nd   frekvens'],
             ['Skin', u'urtikaria, pruritus, utslag, ljusk\xe4nslighet   ingen k\xe4nd'],
             ['Musculoskeletal', u'myalgi, artralgi, rabdomyolys   ingen k\xe4nd   frekvens'],
             ['Reproductive system', u'erektil dysfunktion/impotens   ingen k\xe4nd'],
             ['Psychiatric', u'depression   Ingen k\xe4nd'],
             ['Investigations', u'hyponatremi   Ingen k\xe4nd']]]],
 '_pages': [6, 9],
 u'_rank': 43,
 u'_type': u'LFSU'}
=======
{'_data': [['Common',
            [['Nervous system', u'yrsel, vertigo'],
             ['Investigations', u'hyperkalemi'],
             ['Nervous system', u'yrsel'],
             ['Ear', u'vertigo'],
             ['General', u'asteni/tr\xf6tthet'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'hypotoni inkluderande ortostatisk hypotoni'],
             ['Blood', u'anemi'],
             ['Investigations',
              u'f\xf6rh\xf6jda v\xe4rden av urea i blodet,  serumkreatinin och serumkalium'],
             ['Renal', u'nedsatt njurfunktion  njursvikt'],
             ['Nervous system', u'yrsel'],
             ['Vascular', u'hypotoni'],
             ['General', u'asteni/tr\xf6tthet'],
             ['Investigations', u'hypoglykemi  hyperkalemi*']]],
           ['Uncommon',
            [['Nervous system', u'somnolens, huvudv\xe4rk, s\xf6mnst\xf6rningar'],
             ['Cardiac', u'palpitationer, angina pectoris'],
             ['Vascular',
              u'symtomatisk hypotoni (s\xe4rskilt hos patienter  med minskad blodvolym t ex patienter med sv\xe5r hj\xe4rtsvikt eller kraftigt diuretikabehandlade patienter), dosrelaterade ortostatiska effekter, utslag'],
             ['GI', u'buksm\xe4rta, f\xf6rstoppning'],
             ['General', u'asteni, tr\xf6tthet, \xf6dem'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Respiratory', u'dyspn\xe9  hosta'],
             ['GI', u'diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Skin', u'urtikaria, pruritus, utslag'],
             ['General', u'asteni/tr\xf6tthet'],
             ['Metabolism', u'hyperkalemi']]],
           ['Rare',
            [['Investigations', u'f\xf6rh\xf6jt alaninaminotransferas (ALAT)*'],
             ['Nervous system', u'parestesier'],
             ['Cardiac', u'synkope, f\xf6rmaksflimmer, cerebrovaskul\xe4r  h\xe4ndelse'],
             ['Immune system',
              u'\xf6verk\xe4nslighet: anafylaktiska reaktioner,  angio\xf6dem inkluderande svullnad av larynx och glottis orsakande luftv\xe4gsobstruktion och/eller svullnad av ansikte, l\xe4ppar, svalg och/eller tunga (vissa av patienterna som upplevde angio\xf6dem hade tidigare haft denna biverkning vid behandling med andra l\xe4kemedel inklusive ACE-h\xe4mmare), vaskulit inkluderande Henoch-Sch\xf6nleins purpura'],
             ['Hepato', u'hepatit']]],
           ['Unknown',
            [['Blood', u'anemi'],
             ['Cardiac', u'synkope, palpitationer'],
             ['Vascular', u'ortostatisk hypotoni'],
             ['GI', u'diarr\xe9'],
             ['Musculoskeletal', u'ryggv\xe4rk'],
             ['Renal', u'urinv\xe4gsinfektion'],
             ['General', u'influensaliknande symtom'],
             ['Blood', u'anemi, trombocytopeni'],
             ['Ear', u'tinnitus'],
             ['Nervous system', u'migr\xe4n'],
             ['Respiratory', u'hosta'],
             ['GI', u'diarr\xe9, pankreatit'],
             ['General', u'sjukdomsk\xe4nsla'],
             ['Hepato', u'onormal leverfunktion'],
             ['Skin', u'urtikaria, pruritus, utslag, ljusk\xe4nslighet'],
             ['Musculoskeletal', u'myalgi, artralgi, rabdomyolys'],
             ['Reproductive system', u'erektil dysfunktion/impotens'],
             ['Psychiatric', u'depression'],
             ['Investigations', u'hyponatremi']]]],
 '_pages': [6, 9],
 u'_rank': 49,
 u'_type': u'TSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
