{'_data': [['Very common', [['Blood', u'Leukopeni'], ['Nervous system', u'Huvudv\xe4rk']]],
           ['Common',
            [['Infections',
              u'Meningokocksepsis, meningokockmeningit, sepsis, septisk chock, lunginflammation, bakteriell artrit, \xf6vre luftv\xe4gsinfektion, gastrointestinal infektion, urinv\xe4gsinfektion, cystit, virus infektion'],
             ['Blood', u'Trombocytopeni, hemolys*'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Nervous system', u'Yrsel, parestesi, dysgeusi'],
             ['Ear', u'Yrsel'],
             ['Vascular', u'Accelererad hypertoni'],
             ['Respiratory',
              u'Hosta, n\xe4st\xe4ppa, faryngolaryngeal sm\xe4rta, halsirritation'],
             ['GI',
              u'Diarr\xe9, kr\xe4kning, illam\xe5ende, buksm\xe4rta, f\xf6rstoppning, dyspepsi'],
             ['Skin', u'Hudutslag, alopeci, torr hud, kl\xe5da'],
             ['Musculoskeletal',
              u'Artralgi, myalgi, ryggv\xe4rk, nacksm\xe4rta, sm\xe4rta i extremiteter'],
             ['Renal', u'Dysuri'],
             ['Reproductive system', u'Spontan penil erektion'],
             ['General',
              u'\xd6dem, infusions-relaterade reaktioner, obehagsk\xe4nsla i br\xf6stet, pyrexi, frossa, tr\xf6tthet, asteni'],
             ['Investigations', u'Positivt Coombs test*']]],
           ['Uncommon',
            [['Infections',
              u'Neisseriainfektion, nedre luftv\xe4gsinfektion, svampinfektion, hemofilus infektion, abscess, celluliter, influensa, gingival infektion,'],
             ['Neoplasms', u'Malignt melanom, myelodysplastiskt syndrom'],
             ['Blood',
              u'Koagulopati, agglutination av r\xf6da blodkroppar, onormal koagulationsfaktor, anemi, lymfopeni'],
             ['Immune system', u'\xd6verk\xe4nslighetsreaktioner'],
             ['Endocrine', u'Basedows sjukdom'],
             ['Metabolism', u'Anorexi, nedsatt aptit'],
             ['Psychiatric',
              u'Depression, oro, s\xf6mnl\xf6shet, s\xf6mnst\xf6rningar, onormala dr\xf6mmar, hum\xf6rsv\xe4ngningar'],
             ['Nervous system', u'Synkope, tremor'],
             ['Eye', u'Dimsyn, konjunktival irritation'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypertoni, l\xe5gt blodtryck eller hypotension, hematom,'],
             ['Respiratory', u'Epistaxis, rinorre'],
             ['GI',
              u'Peritonit, gastroesofagal refluxsjukdom, utsp\xe4nd buk, gingival sm\xe4rta'],
             ['Hepato', u'Gulsot'],
             ['Skin', u'Urtikaria, dermatit, erytem, petekier, huddepigmentering, hyperhidros'],
             ['Musculoskeletal', u'Trismus, ledsvullnad, muskelkramper, skelettsm\xe4rta'],
             ['Renal', u'Nedsatt njurfunktion, hematuri'],
             ['Reproductive system', u'Menstruationsrubbningar'],
             ['General',
              u'Br\xf6stsm\xe4rtor, parestesi vid infusionsst\xe4llet, sm\xe4rta vid infusionsst\xe4llet, extravasering, influensaliknande sjukdoms-besv\xe4r, v\xe4rmek\xe4nsla'],
             ['Investigations',
              u'F\xf6rh\xf6jt ALAT och ASAT, f\xf6rh\xf6jt gammaglutamyl-transpeptidas, minskning av hematokrit, minskning av hemoglobin']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 9],
 u'_rank': 37,
 u'_type': u'MSFU'}