{'_data': [['Very common',
            [['GI', u'Diarr\xe9, l\xf6s avf\xf6ring, buksm\xe4rta'],
             ['Hepato', u'Gallstenssm\xe4rta']]],
           ['Common',
            [['Investigations',
              u'\xd6kat ALAT , onormal ASAT , onormal ALAT, \xf6kat bilirubin i blod , \xf6kad glukos i blod, \xf6kad glykosyl-haemoglobin, viktminskning'],
             ['Cardiac', u'Sinusbradykardi'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kningar, f\xf6rstoppning, gasbildning, buksp\xe4nning, obehagsk\xe4nsla i buken, dyspepsi'],
             ['Skin', u'Alopeci, hypotrikos'],
             ['Metabolism', u'Hypoglykemi'],
             ['General',
              u'Tr\xf6tthet, reaktion p\xe5 injektionsst\xe4llet (sm\xe4rta, svullnad, f\xf6rh\xe5rdnad, kn\xf6l, kl\xe5da)'],
             ['Hepato', u'Gallg\xe5ngsdilatation']]],
           ['Uncommon',
            [['Investigations',
              u'\xd6kat ASAT, \xf6kad alkalin-fosfatas i blodet, onormal bilirubin i blodet, minskat natrium i blodet'],
             ['GI', u'Missf\xe4rgad avf\xf6ring'],
             ['Metabolism', u'Diabetes mellitus, hyperglykemi'],
             ['Vascular', u'Flusher'],
             ['General', u'Asteni'],
             ['Psychiatric', u'Insomnia']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 5],
 u'_rank': 16,
 u'_type': u'MSFU'}