{'_data': [['Common',
            [['Nervous system', u'amnesi, parestesi, somnolens'],
             ['Reproductive system', u'Dysmenorr\xe9']]],
           ['Uncommon',
            [['Nervous system',
              u'ataxi/inkoordination, yrsel, uppm\xe4rksamhetsp\xe5verkan, parosmi, talsv\xe5righeter (dysartri, sluddrigt tal), hypestesi Se \xe4ven nedan under Amnesi'],
             ['Eye', u'synneds\xe4ttning, dubbelseende'],
             ['Ear', u'hyperakusi'],
             ['GI', u'illam\xe5ende'],
             ['Skin', u'ljusk\xe4nslighetsreaktion'],
             ['Metabolism',
              u'anorexi Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Metabolism', u'asteni, diffust obehag'],
             ['Psychiatric',
              u'depersonalisation, hallucinationer, depression, f\xf6rvirringstillst\xe5nd, apati']]],
           ['Very rare', [['Immune system', u'anafylaktisk/anafylaktioda reaktioner']]],
           ['Unknown',
            [['Skin', u'angioneurotiskt \xf6dem'],
             ['Hepato', u'Hepatotoxicitet (vanligen beskrivet som \xf6kad transaminas)'],
             ['Psychiatric',
              u's\xf6mng\xe5ng Se \xe4ven nedan under Depression och Psykiska st\xf6rningar och paradoxala reaktioner. Amnesi Anterograd amnesi kan intr\xe4ffa vid rekommenderade terapeutiska doser, med \xf6kad risk vid st\xf6rre doser. Amnesin kan vara f\xf6renad med beteendeavvikelser (se 4.4). Depression En redan befintlig depression kan framtr\xe4da vid anv\xe4ndning av bensodiazepiner eller bensodiazepinliknande medel. Psykiska st\xf6rningar och paradoxala reaktioner Reaktioner som t ex rastl\xf6shet, agitation, irritabilitet, minskade h\xe4mningar, aggressivitet, onormala tankar, vanf\xf6rest\xe4llningar, raseriutbrott, mardr\xf6mmar, depersonalisationar, hallucinationer, psykoser, avvikande upptr\xe4dande, extrovert beteende och andra beteendest\xf6rningar \xe4r k\xe4nda vid anv\xe4ndning av bensodiazepiner och bensodiazepinliknande medel. Denna typ av reaktioner \xe4r vanligare hos \xe4ldre. Beroende Anv\xe4ndningen (\xe4ven vid terapeutiska doser) kan leda till att patienten utvecklar ett fysiskt beroende: uts\xe4ttning av l\xe4kemedlet kan resultera i abstinenssymptom eller till de symptom som var orsaken till f\xf6rskrivningen av l\xe4kemedlet till patienten, (se 4.4). \xc4ven psykiskt beroende kan uppst\xe5. Missbruk av bensodiazepiner och bensodiazepinliknande aktiva substanser har rapporterats.']]]],
 '_pages': [6, 8],
 u'_rank': 14,
 u'_type': u'LSFU'}