{'_data': [['Common',
            [['Metabolism', u'hyperkalcemi, hypokalemi, hypomagnesemi'],
             ['GI', u'illam\xe5ende, kr\xe4kningar']]],
           ['Uncommon',
            [['GI',
              u'f\xf6rstoppning, diarr\xe9, tarmobstruktion, ulceration, kolonnekros som kan ge perforation, anorexi']]],
           ['Rare',
            [['GI',
              u'i sv\xe5ra fall ileus ocklusion (beroende p\xe5 sammanklumpning av pulvret i tarmen), fekal klumpbildning efter rektal administrering till barn, gastrointestinal konkretion efter oral administrering till nyf\xf6dda. Hematochezi har observerats hos prematura barn och nyf\xf6dda med l\xe5g f\xf6delsevikt som f\xe5tt lavemang inneh\xe5llande polystyrensulfonatharts. Vid oral administrering kan patienter f\xe5 sv\xe5rt att sv\xe4lja den ganska stora m\xe4ngden utr\xf6rt pulver. Omfattningen av dessa besv\xe4r \xe4r beroende av individuell disposition, sjukdom, administrering och behandlingstidens l\xe4ngd.']]],
           ['Very rare',
            [['Respiratory',
              u'akut bronkit och/eller bronkopneumoni vid inhalation av kalciumpolystyrensulfonat']]]],
 '_pages': [4, 4],
 u'_rank': 5,
 u'_type': u'LSFU'}