{'_data': [['Common',
            [['General', u' Feber  '],
             ['Vascular',
              u' Bradykardi. Andf\xe5ddhet. Br\xf6stsm\xe4rta. Hj\xe4rtklappning. \xd6dem  EKG-f\xf6r\xe4ndringar. Hypotension. Proarytmi. Synkope, svimningsk\xe4nsla. Hj\xe4rtsvikt. '],
             ['Skin', u' Exantem. '],
             ['GI',
              u' Illam\xe5ende/kr\xe4kningar. Diarr\xe9. Dyspepsi. Magsm\xe4rtor. Flatulens Muskeloskel.: Kramper. '],
             ['Nervous system',
              u' Tr\xf6tthet. Yrsel. Asteni. Huvudv\xe4rk. S\xf6mnst\xf6rningar. Nedst\xe4mdhet. \xc5ngest. Parestesier. '],
             ['Reproductive system', u' Sexuell dysfunktion. '],
             ['Other', u' Syn-, h\xf6rsel- och smakst\xf6rningar. ']]]],
 '_pages': [6, 6],
 u'_rank': 7,
 u'_type': u'DFSU'}