{'_data': [[u'Unknown',
            [['Respiratory', u'Andningsdepression'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, obstipation'],
             ['Renal', u'Urinretention'],
             ['General', u'Omt\xf6ckning'],
             ['Psychiatric', u'Dysfori'],
             ['Cardiac', u'Hj\xe4rtarrytmi'],
             ['Eye', u'Ackommodationsst\xf6rningar'],
             ['GI', u'Obstipation'],
             ['Renal', u'Urinretention'],
             ['General', u'Muntorrhet med risk f\xf6r tand- och   munslemhinneskador']]]],
 '_pages': [2, 3],
 u'_rank': 10,
 u'_type': u'LFSU'}