{'_data': [['Common', [['Infections', u'Mukokutan candidiasis  ']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel  '],
             ['Nervous system', u'Huvudv\xe4rk  '],
             ['Hepato', u'\xd6kningar av ASAT och/eller ALAT  ']]],
           ['Unknown',
            [['Infections', u'\xd6verv\xe4xt av icke-k\xe4nsliga organismer  '],
             ['Blood',
              u'neutropeni) Trombocytopeni S\xe4llsynta Reversibel agranulocytos Ingen k\xe4nd frekvens Hemolytisk anemi Ingen k\xe4nd frekvens F\xf6rl\xe4ngd bl\xf6dnings- och protrombintid Ingen k\xe4nd frekvens'],
             ['Immune system', u'Angioneurotiskt \xf6dem  '],
             ['Immune system', u'Anafylaxi  '],
             ['Immune system', u'Syndrom liknande serumsjuka  '],
             ['Immune system', u'\xd6verk\xe4nslighetvaskulit  '],
             ['Nervous system', u'Reversibel hyperaktivitet  '],
             ['Nervous system', u'Krampanfall  '],
             ['GI', u'Missf\xe4rgade t\xe4nder 11 Ingen k\xe4nd frekvens'],
             ['Hepato', u'Hepatit  '],
             ['Hepato', u'Kolestatisk gulsot  '],
             ['Skin', u'(AGEP)'],
             ['Renal',
              u'Se avsnitt 4.4. Se avsnitt 4.4. Illam\xe5ende f\xf6rknippas oftare med h\xf6ga orala doser. Om gastrointestinala reaktioner \xe4r p\xe5tagliga kan de reduceras genom att Spektramox tas i b\xf6rjan av en m\xe5ltid. 4 Inklusive pseudomembran\xf6s kolit och bl\xf6dande kolit (se avsnitt 4.4). En m\xe5ttlig \xf6kning av ASAT och/eller ALAT har noterats hos patienter behandlade med betalaktamantibiotika, men signifikansen av dessa resultat \xe4r ok\xe4nd. 6 Dessa h\xe4ndelser har noterats med andra penicilliner och cefalosporiner (se avsnitt 4.4). Om n\xe5gra hud\xf6verk\xe4nslighetsreaktioner intr\xe4ffar ska behandlingen s\xe4ttas ut (se avsnitt 4.4). Se avsnitt 4.9. Se avsnitt 4.3. Se avsnitt 4.4. 11 Ytlig missf\xe4rgning av t\xe4nder har rapporterats i mycket s\xe4llsynta fall hos barn. Bra munhygien kan hj\xe4lpa till att f\xf6rebygga missf\xe4rgade t\xe4nder eftersom missf\xe4rgningarna vanligtvis kan tas bort med tandborstning.']]]],
 '_pages': [6, 7],
 u'_rank': 17,
 u'_type': u'LSFU'}