{'_data': [['Common', [['GI', u'Muntorrhet  ']]],
           ['Uncommon',
            [['Nervous system', u'Yrsel  '],
             ['Nervous system', u'Huvudv\xe4rk  '],
             ['Nervous system', u'Smakf\xf6r\xe4ndring  '],
             ['Eye', u'Dimsyn  '],
             ['Cardiac', u'F\xf6rmaksflimmer  '],
             ['Respiratory', u'Faryngit  '],
             ['Respiratory', u'Dysfoni  '],
             ['Respiratory', u'Hosta  '],
             ['GI', u'Gastroesofagal refluxsjukdom  '],
             ['GI', u'F\xf6rstoppning  '],
             ['GI', u'Oral candidainfektion  '],
             ['Skin', u'Hudutslag  '],
             ['Renal', u'Sv\xe5righet att t\xf6mma urinbl\xe5san  '],
             ['Renal', u'Urinretention  ']]],
           ['Rare',
            [['Nervous system', u'S\xf6mnl\xf6shet  '],
             ['Eye', u'\xd6kat intraokul\xe4rt tryck  '],
             ['Eye', u'Glaukom  '],
             ['Cardiac', u'Supraventrikul\xe4r takykardi  '],
             ['Cardiac', u'Takykardi  '],
             ['Cardiac', u'Palpitationer  '],
             ['Respiratory', u'Bronkospasm  '],
             ['Respiratory', u'N\xe4sbl\xf6dning  '],
             ['Respiratory', u'Laryngit  '],
             ['Respiratory', u'Sinuit  '],
             ['GI', u'Stomatit  '],
             ['GI', u'Illam\xe5ende  '],
             ['GI', u'Tarmobstruktion inkl. paralytisk ileus  '],
             ['GI', u'Gingivit  '],
             ['GI', u'Glossit  '],
             ['GI', u'Sv\xe5righeter att sv\xe4lja  '],
             ['Skin', u'Urtikaria  '],
             ['Skin', u'Kl\xe5da  '],
             ['Skin', u'\xd6verk\xe4nslighet (inkl. omedelbara reaktioner)  '],
             ['Skin', u'Angio\xf6dem  '],
             ['Renal', u'Urinv\xe4gsinfektion  ']]],
           ['Unknown',
            [['Metabolism', u'*'],
             ['GI', u'Dental karies  '],
             ['Skin', u'Hudinfektion, hudulcerationer  '],
             ['Skin', u'Torr hy  '],
             ['Musculoskeletal', u'Ledsvullnad  '],
             ['Other',
              u'En \xf6kad antikolinergisk effekt kan f\xf6rekomma med \xf6kande \xe5lder.']]]],
 '_pages': [6, 7],
 u'_rank': 42,
 u'_type': u'LSFU'}