{'_data': [['Very common',
            [['Infections',
              u'infektion (inklusive bakteriell, viral, svamp och icke-specificerad)'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Vascular', u'bl\xf6dning*'],
             ['Respiratory', u'pleurautgjutning*, dyspn\xe9, hosta'],
             ['GI', u'diarr\xe9, kr\xe4kningar, illam\xe5ende, buksm\xe4rta'],
             ['Skin', u'hudutslag'],
             ['Musculoskeletal', u'muskeloskelatal sm\xe4rta'],
             ['General', u', feber']]],
           ['Common',
            [['Infections',
              u'lunginflammation (inklusive bakteriell, viral och svamporsakad), infektion/inflammation i \xf6vre luftv\xe4garna, herpesvirusinfektion, enterokolit, sepsis 68 (ibland med d\xf6dlig utg\xe5ng)'],
             ['Blood', u'febril neutropeni, pancytopeni'],
             ['Metabolism', u'anorexi, aptitst\xf6rningar, hyperurikemi'],
             ['Psychiatric', u'depression, s\xf6mnl\xf6shet'],
             ['Nervous system',
              u'neuropati (inklusive perifer neuropati), yrsel, smakf\xf6r\xe4ndring, somnolens'],
             ['Eye',
              u'synrubbningar (inklusive synst\xf6rning, dimsyn och nedsatt synsk\xe4rpa), torr\xf6gdhet'],
             ['Ear', u'tinnitus'],
             ['Cardiac',
              u'Vanliga hj\xe4rtsvikt/hj\xe4rtdysfunktion* , perikardiell utgjutning*, arytmi (inklusive takykardi), hj\xe4rtklappning'],
             ['Vascular', u'hypertoni, blodvallning'],
             ['Respiratory',
              u'lung\xf6dem*, pulmonell hypertoni*, lunginfiltration, pneumonit'],
             ['GI',
              u'gastrointestinal bl\xf6dning*, kolit (inklusive neutropen kolit), gastrit, slemhinneinflammation (inklusive mukosit/stomatit), dyspepsi, utsp\xe4nd buk, f\xf6rstoppning, mjukv\xe4vnadssjukdom i munnen'],
             ['Skin',
              u'alopeci, dermatit (inklusive eksem), pruritus, akne, torr hud, urticaria, hyperhidros'],
             ['Musculoskeletal',
              u'artralgi, myalgi, muskelsvaghet, muskuloskeletal stelhet, muskelkramp'],
             ['General',
              u'asteni, sm\xe4rta, br\xf6stsm\xe4rta, generaliserat \xf6dem*, frossbrytningar'],
             ['Investigations', u'viktminskning, vikt\xf6kning'],
             ['Injury',
              u'kontusion Inkluderar cerebralt hematom, cerebral bl\xf6dning, extraduralt hematom, intrakraniell bl\xf6dning, hemorragisk stroke, subaraknoidal bl\xf6dning, subduralt hematom och subdural bl\xf6dning. Inkluderar ventrikul\xe4r dysfunktion, hj\xe4rtsvikt, kronisk hj\xe4rtsvikt, kardiomyopati med eller utan hj\xe4rtsvikt, diastolisk dysfunktion, nedsatt ejektionsfraktion och ventrikul\xe4r svikt. Exkluderar gastrointestinal bl\xf6dning och CNS-bl\xf6dning: Dessa biverkningar \xe4r rapporterade under magtarmkanalens organklass respektive centrala och perfiera nervsystemets organklass. dInkluderar l\xe4kemedelsutslag, erytem, erythema multiforme, erytros, exfoliativa utslag, generaliserat erytem, genitala utslag, v\xe4rmeutslag, milia, utslag, erytemat\xf6sa utslag, follikul\xe4ra utslag, generaliserade utslag, makul\xe4ra utslag, makulopapul\xe4ra utslag, papul\xe4ra utslag, kliande utslag, pustul\xe4ra utslag, vesikul\xe4ra utslag, hudexfoliering, hudirritation och vesikul\xe4r urtikaria. Inkluderar \xf6ronsvullnad, konjunktivalt \xf6dem, \xf6gon\xf6dem, \xf6gonsvullnad, \xf6gonlocks\xf6dem, ansikts\xf6dem, genital svullnad, gravitations\xf6dem, \xf6dem p\xe5 incisionst\xe4llet, l\xe4pp\xf6dem, lokaliserat \xf6dem, makul\xe4rt \xf6dem, genital\xf6dem, mun\xf6dem, perifert \xf6dem, orbitalt \xf6dem, penilt \xf6dem, periorbitalt \xf6dem, pitting\xf6dem, skrotum\xf6dem, hudsvullnad, ansiktssvullnad och tung\xf6dem']]],
           ['Uncommon',
            [['Neoplasms', u'tum\xf6rlys-syndrom (TLS)'],
             ['Immune system', u'\xf6verk\xe4nslighet (inklusive erythema nodosum)'],
             ['Metabolism', u'hypoalbuminemi'],
             ['Psychiatric', u'\xe5ngest, f\xf6rvirring, labil affekt, minskad libido'],
             ['Nervous system', u', synkope, tremor, amnesi'],
             ['Eye', u'konjunktivit'],
             ['Ear', u'vertigo'],
             ['Cardiac',
              u'myokardinfarkt (ibland med d\xf6dlig utg\xe5ng)*, EKG QT-f\xf6rl\xe4ngning*, perikardit, ventrikul\xe4r arytmi (inklusive ventrikul\xe4r takykardi) angina pectoris, kardiomegali'],
             ['Vascular', u'hypotoni, tromboflebit'],
             ['Respiratory', u'bronkialspasm, astma'],
             ['GI',
              u'pankreatit, s\xe5r i \xf6vre magtarmkanalen, esofagit, ascites*, anal fissur, dysfagi 69'],
             ['Hepato', u'hepatit, kolecystit, kolestas'],
             ['Skin',
              u'akut febril neutrofil dermatos, fotosensibiliseringsreaktion, pigmentrubbning, pannikulit, huds\xe5r, bull\xf6sa sjukdomar, nagelsjukdomar, palmo-plantar erytrodysestesisyndrom'],
             ['Musculoskeletal', u'rabdomyolys, muskelinflammation, tendonit'],
             ['Renal', u'njursvikt, t\xe4ta urintr\xe4ngningar, proteinuri'],
             ['Reproductive system', u'gynekomasti, oregelbunden menstruation'],
             ['General', u'sjukdomsk\xe4nsla, temperaturintolerans'],
             ['Investigations', u'\xf6kning av kreatinfosfokinas i blod']]],
           ['Rare',
            [['Blood', u'pure red cell aplasia'],
             ['Nervous system',
              u'cerebrovaskul\xe4r insult, transitorisk ischemisk attack, krampanfall, optikusneurit, paralys av 7:e kranialnerven'],
             ['Eye', u'synneds\xe4ttning'],
             ['Cardiac', u'lunghj\xe4rta, myokardit, akut koronarsyndrom'],
             ['Vascular', u'livedo reticularis'],
             ['Respiratory', u'ARDS'],
             ['GI', u'proteinf\xf6rlorande gastroenteropati, ileus']]],
           ['Unknown',
            [['Cardiac', u'f\xf6rmaksflimmer/f\xf6rmaksfladder'],
             ['Vascular', u'trombos/emboli (inklusive pulmonell emboli, djup ventrombos)'],
             ['Respiratory',
              u'interstitiell lungsjukdom, pulmonell arteriell hypertension (prekapill\xe4r pulmonell arteriell hypertension)'],
             ['GI', u'd\xf6dlig gastrointestinal bl\xf6dning*'],
             ['GI',
              u'Ej rekommenderad startdos av SPRYCEL f\xf6r avancerad fas av KML och Ph+ ALL (se avsnitt 4.2). Inkluderar ventrikul\xe4r dysfunktion, hj\xe4rtsvikt, kronisk hj\xe4rtsvikt, kardiomyopati med eller utan hj\xe4rtsvikt, diastolisk dysfunktion, nedsatt ejektionsfraktion och ventrikul\xe4r svikt. Laboratorietest-avvikelser Hematologi I fas III-studien p\xe5 patienter med nydiagnostiserad KML i kronisk fas, rapporterades f\xf6ljande laboratorieavvikelser av grad 3 eller 4 hos patienter som behandlats med SPRYCEL efter minst 12 m\xe5naders uppf\xf6ljning: neutropeni (21%), trombocytopeni (19%) och anemi (10%). Efter minst 36 m\xe5naders uppf\xf6ljning var de kumulativa frekvenserna av neutropeni, trombocytopeni och anemi 24%, 19% respektive 12%. Generellt \xe5terh\xe4mtade sig SPRYCEL-behandlade patienter med nydiagnostiserad KML i kronisk fas fr\xe5n myelosuppression av grad 3 eller 4 efter kortare dosavbrott och/eller dosminskning; 1,6% av patienterna avbr\xf6t behandlingen permanent efter minst 12 m\xe5naders uppf\xf6ljning. Efter minst 36 m\xe5naders uppf\xf6ljning var den kumulativa frekvensen av permanent behandlingsavbrott, p\xe5 grund av myelosuppression av grad 3 eller 4, 2,3%. Hos patienter med KML med resistens eller intolerans mot tidigare imatinib-behandling var f\xf6rekomsten av cytopeni (trombocytopeni, neutropeni och anemi) konsekvent. F\xf6rekomsten av cytopeni var emellertid \xe4ven tydligt beroende av sjukdomsfasen. Frekvensen av hematologiska avvikelser av grad 3 eller 4 presenteras i tabell 4.']]]],
 '_pages': [8, 16],
 u'_rank': 54,
 u'_type': u'LSFU'}