{'_data': [['Common',
            [['General',
              u'Omedelbart efter injektionen kan patienten uppleva en metallisk eller bitter smak, delvis i kombination med muntorrhet och ett f\xf6r\xe4ndrat luktsinne.']]],
           ['Uncommon',
            [['Nervous system', u'Huvudv\xe4rk.'],
             ['Cardiac', u'Br\xf6stsm\xe4rta/angina pectoris, onormalt EKG.'],
             ['GI', u'Illam\xe5ende.']]],
           ['Rare',
            [['Immune system',
              u'Sv\xe5ra \xf6verk\xe4nslighetsreaktioner s\xe5som dyspn\xe9, hypotoni, bradykardi, asteni och kr\xe4kningar (vanligen inom tv\xe5 timmar fr\xe5n administrering), angio\xf6dem.'],
             ['Nervous system', u'Krampanfall (kort efter administrering), synkope.'],
             ['Cardiac', u'Arytmi.'],
             ['GI', u'Buksm\xe4rta.'],
             ['Skin',
              u'Allergiska hud- och slemhinnereaktioner med exantem (pruritus, urtikaria, \xf6dem), vasodilatation, lokala reaktioner p\xe5 injektionsst\xe4llet, hypoestesi och parestesi, rodnad.'],
             ['General',
              u'Feber, tr\xf6tthet, yrsel, \xf6verg\xe5ende artritliknande sm\xe4rta. \xd6vrigt: Exponering f\xf6r joniserande str\xe5lning \xe4r kopplad till cancerinduktion och en potential f\xf6r utveckling av \xe4rftliga missbildningar. Eftersom de flesta diagnostiska unders\xf6kningar med nuklearmedicinska l\xe4kemedel utf\xf6rs med l\xe5ga str\xe5ldoser p\xe5 under 20 mSv, f\xf6rv\xe4ntas sannolikheten f\xf6r att s\xe5dana biverkningar skall uppkomma vara l\xe5g. Den ber\xe4knade effektiva dosen vid en genomsnittlig aktivitetsm\xe4ngd p\xe5 2 000 MBq (500 i vila och 1 500 MBq vid stress) f\xf6r ett endagsprotokoll \xe4r 16,3 mSv.']]],
           ['Very rare',
            [['Skin',
              u'Andra \xf6verk\xe4nslighetsreaktioner har beskrivits hos predisponerade patienter.']]],
           ['Unknown', [['Skin', u'Erythema multiforme.']]]],
 '_pages': [5, 6],
 u'_rank': 12,
 u'_type': u'LSFU'}