{'_data': [['Very common', [['Infections', u' \xd6vre luftv\xe4gsinfektion, nasofaryngit']]],
           ['Common',
            [['Infections', u' Cellulit, virusinfektion i \xf6vre luftv\xe4garna'],
             ['Immune system',
              u' \xd6verk\xe4nslighetsreaktioner (inklusive utslag, urtikaria)'],
             ['Psychiatric', u' Depression'],
             ['Nervous system', u' Yrsel, huvudv\xe4rk'],
             ['Respiratory', u' Faryngolaryngeal sm\xe4rta, n\xe4st\xe4ppa '],
             ['GI', u' Diarr\xe9'],
             ['Skin', u' Kl\xe5da'],
             ['Musculoskeletal', u' Ryggsm\xe4rta, myalgi, artralgi '],
             ['General', u' Tr\xf6tthet, hudrodnad vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Infections', u' Herpes zoster'],
             ['General',
              u' Reaktioner vid injektionsst\xe4llet (exempelvis sm\xe4rta, svullnad, kl\xe5da, induration, bl\xf6dning, bl\xe5m\xe4rke och irritation)']]],
           ['Rare',
            [['Immune system',
              u' Allvarliga \xf6verk\xe4nslighetsreaktioner (inklusive anafylaxi, angio\xf6dem)'],
             ['Nervous system', u' Facialispares']]]],
 '_pages': [5, 7],
 u'_rank': 14,
 u'_type': u'LSFU2'}