{'_data': [['Uncommon',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Pruritus'],
             ['Skin', u'Erytem']]],
           ['Rare',
            [['Nervous system', u'Tremor'],
             ['Cardiac', u'\xd6kad hj\xe4rtfrekvens'],
             ['Vascular', u'Perifer kyla'],
             ['GI', u'Magsm\xe4rta'],
             ['Investigations', u'\xd6kning av alaninaminotransferas  (ALAT)']]],
           ['Unknown',
            [['Immune system', u'Anafylaktisk chock'],
             ['Immune system', u'Anafylaktisk/anafylaktoid reaktion'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Nervous system', u'Parestesi'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotoni'],
             ['GI', u'Kr\xe4kning'],
             ['GI', u'Oral parestesi']]]],
 '_pages': [4, 5],
 u'_rank': 17,
 u'_type': u'TSFU'}