{'_data': [['Very common',
            [['Psychiatric', u'S\xf6mnl\xf6shet \xc5ngest'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'F\xf6rstoppning Illam\xe5ende'],
             ['Skin', u'Svettningar'],
             ['Reproductive system', u'Abstinenssyndrom Asteni'],
             ['Investigations', u'opioidberoende.'],
             ['Immune system', u'Psykiska st\xf6rningar'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende Kr\xe4kningar'],
             ['Pregnancy',
              u'Beskrivning av andra biverkningar \uf0b7 hepatit rapporterats (se \uf0b7 buprenorfin ge en abstinenseffekt 4.2 och 4.4). \uf0b7 fastst\xe4lla ett orsakssamband, spontant missfall (se avsnitt \uf0b7 buprenorfin under graviditeten. kortverkande \u03bc-opioidagonister. missbruksproblem (se avsnitt']]],
           ['Common',
            [['Infections', u'Influensa Infektion Faryngit Rinit'],
             ['Blood', u'Anemi Leukocytos'],
             ['Immune system', u'Allergisk'],
             ['Metabolism', u'Minskad aptit'],
             ['Psychiatric', u'Depression Minskad libido Nervositet Onormala tankar'],
             ['Nervous system', u'Hypertoni Migr\xe4n Parestesi Somnolens Yrsel'],
             ['Eye', u'Amblyopi Lakrimationsst\xf6rning'],
             ['Cardiac', u'Angina Bradykardi'],
             ['Vascular', u'Hypertension Vasodilatation'],
             ['Respiratory', u'\xd6kad hosta'],
             ['GI', u'Buksm\xe4rtor Diarr\xe9 Dyspepsi Flatulens Kr\xe4kningar'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Kl\xe5da Utslag Urtikaria'],
             ['Musculoskeletal', u'Artralgi Artrit Muskelspasmer Myalgi Ryggsm\xe4rtor'],
             ['Renal', u'Urinabnormalitet'],
             ['Reproductive system',
              u'Impotens Amenorr\xe9 Br\xf6stsm\xe4rtor Feber Frossa Perifera \xf6dem Sjukdomsk\xe4nsla Sm\xe4rtor'],
             ['Investigations', u'Skada V\xe4rmeslag'],
             ['Nervous system', u'Yrsel Somnolens Svimning'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['Respiratory', u'Andningsdepression Bronkospasmer'],
             ['GI', u'F\xf6rstoppning'],
             ['Hepato', u'Levernekros Hepatit'],
             ['Skin', u'Svettningar Angio\xf6dem'],
             ['Pregnancy',
              u'Asteni Vid intraven\xf6st missbruk har lokala reaktioner (ibland septiska) samt potentiellt allvarlig akut avsnitt 4.4). -Hos patienter med ett p\xe5tagligt, p\xe5g\xe5ende drogberoende kan inledande administrering av liknande den som \xe4r f\xf6rknippad med naloxon (se avsnitt -Missfall har rapporterats f\xf6r b\xe5de buprenorfin och buprenorfin-naloxon. Det \xe4r inte m\xf6jligt att d\xe5 fallen i regel omfattar andra l\xe4kemedel eller riskfaktorer f\xf6r -4.6). -Ett neonatalt abstinenssyndrom har rapporterats bland nyf\xf6dda till kvinnor vilka erh\xe5llit Syndromet kan vara mildare och mer l\xe5ngvarigt \xe4n det fr\xe5n -Syndromets natur kan variera beroende p\xe5 moderns -4.6). ']]],
           ['Uncommon',
            [['Infections', u'Urinv\xe4gsinfektion Vaginit'],
             ['Blood', u'Leukopeni Lymfadenopati Trombocytopeni'],
             ['Immune system', u'reaktion'],
             ['Metabolism', u'Hyperglykemi Hyperlipidemi Hypoglykemi'],
             ['Psychiatric',
              u'Agitation Apati Drogberoende Eufori Fientlighet Onormala dr\xf6mmar Personlighetsf\xf6r\xe4ndring'],
             ['Nervous system', u'Minnesf\xf6rlust Hyperkinesi Kramper Talrubbning Tremor'],
             ['Eye', u'Konjunktivit Mios'],
             ['Cardiac', u'pectoris Hj\xe4rtinfarkt Palpitation Takykardi'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Astma Dyspn\xe9 G\xe4spningar'],
             ['GI', u'Missf\xe4rgning av tungan Ulcer\xf6s stomatit'],
             ['Skin', u'Akne Alopeci Exfoliativ dermatit Hudknutor Torr hud'],
             ['Renal', u'Albuminuri Dysuri Hematuri Njursten Urinretention'],
             ['Reproductive system',
              u'Menorragi Metrorragi Onormal ejakulation Hypotermi Neonatal'],
             ['Psychiatric', u'Hallucinationer'],
             ['Pregnancy', u'Drogabstinenssyndrom,']]],
           ['Unknown',
            [['Pregnancy', u'Missfall'],
             ['Reproductive system', u'abstinenssyndrom'],
             ['Psychiatric', u'Medvetet   drogmissbruk'],
             ['Pregnancy', u'Missfall Neonatalt abstinenssyndrom Lokal reaktion']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 9],
 u'_rank': 55,
 u'_type': u'MSFU'}