{'_data': [['Very common', [['Nervous system', u'Sedation'], ['Skin', u'Kl\xe5da']]],
           ['Common',
            [['Nervous system', u'Neonatal tremor, yrsel, huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypertoni, hypotoni, blekhet'],
             ['Respiratory', u'Neonatal cyanos'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende'],
<<<<<<< HEAD
             ['Skin', u'Missf\xe4rg-ni ng av huden'],
             ['Musculoskeletal', u'Muskel-ryc kningar'],
             ['Renal', u'Urinreten-ti on, urin-inkonti nens'],
             ['General', u'Pyrexi']]],
           ['Uncommon', [['Immune system', u'Hyper-sensitiv']]],
=======
             ['Skin', u'Missf\xe4rg-ning av huden'],
             ['Renal', u'Urinreten-tion, urin-inkontinens'],
             ['General', u'Pyrexi']]],
           ['Uncommon',
            [['Infections', u'Rinit'],
             ['Immune system', u'Hyper-sensitivitet'],
             ['Psychiatric', u'Apati, nervositet'],
             ['Nervous system',
              u'Ataxi, neonatal dyskinesi, dystoni, hyperrflexi, f\xf6rh\xf6jd muskeltonus, neonatal hypokinesi, somnolens'],
             ['Eye', u'Synst\xf6rning'],
             ['Cardiac',
              u'Atrioventri-kul\xe4rt block, cyanos, bradykardi, arytmi, onormalt EKG'],
             ['Respiratory',
              u'Bronkospasm, hypoventi-lering, dysfoni, hosta, hicka, andnings-st\xf6rning'],
             ['Skin',
              u'Allergisk dermatit, hyperhidros, hudutslag, hudutslag hos nyf\xf6dda, torr hud'],
             ['General', u'Hypotermi, minskad kropps-temperatur, \xf6kad kropps']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Rare', []],
           ['Unknown',
            [['Immune system',
              u'Anafylaktisk chock, anafylaktisk reaktion, anafylaktoid reaktion'],
             ['Nervous system', u'Koma, kramper, ofrivilliga muskelsammand ragningar'],
             ['Eye', u'Mios'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'Chock'],
             ['Respiratory',
<<<<<<< HEAD
              u'Andningsstille-s t\xe5nd, apn\xe9, andnings-depres sion, lung\xf6dem, laryngospasm'],
             ['Skin', u'Erytem'],
             ['Musculoskeletal', u'Muskelspasmer']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 20,
=======
              u'Andningsstille-st\xe5nd, apn\xe9, andnings-depression, lung\xf6dem, laryngospasm'],
             ['Skin', u'Erytem']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 26,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'MSFU'}