{'_data': [['Very common', [['Nervous system', u'Sedation'], ['Skin', u'Kl\xe5da']]],
           ['Common',
            [['Nervous system', u'Neonatal tremor, yrsel, huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypertoni, hypotoni, blekhet'],
             ['Respiratory', u'Neonatal cyanos'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende'],
             ['Skin', u'Missf\xe4rg-ni ng av huden'],
             ['Musculoskeletal', u'Muskel-ryc kningar'],
             ['Renal', u'Urinreten-ti on, urin-inkonti nens'],
             ['General', u'Pyrexi']]],
           ['Uncommon', [['Immune system', u'Hyper-sensitiv']]],
           ['Rare', []],
           ['Unknown',
            [['Immune system',
              u'Anafylaktisk chock, anafylaktisk reaktion, anafylaktoid reaktion'],
             ['Nervous system', u'Koma, kramper, ofrivilliga muskelsammand ragningar'],
             ['Eye', u'Mios'],
             ['Cardiac', u'Hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'Chock'],
             ['Respiratory',
              u'Andningsstille-s t\xe5nd, apn\xe9, andnings-depres sion, lung\xf6dem, laryngospasm'],
             ['Skin', u'Erytem'],
             ['Musculoskeletal', u'Muskelspasmer']]]],
 '_note': u' ?MSFU',
 '_pages': [4, 6],
 u'_rank': 20,
 u'_type': u'MSFU'}