{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Illam\xe5ende och kr\xe4kning, buksm\xe4rta'],
             ['Skin', u'Pruritus, huderuption'],
             ['Metabolism', u'Anorexia'],
             ['General', u'Tr\xf6tthet, asteni'],
             ['Reproductive system',
              u'Oligospermi hos m\xe4n, reversibel f\xf6rs\xe4mrad fertilitet']]],
           ['Common',
            [['Blood', u'Folsyrebristanemi (megaloblastos, makrocytemi), leukopeni'],
             ['Nervous system',
              u'D\xe5sighet, yrsel, nedsatt koncentrationsf\xf6rm\xe5ga, insomnia'],
             ['Skin', u'Urtikaria, ljusk\xe4nslighet'],
             ['General', u'Feber'],
             ['Hepato', u'F\xf6rh\xf6jning av leverenzymer']]],
           ['Uncommon',
            [['Cardiac', u'Palpitationer, takykardi'],
             ['Blood',
              u'Agranulocytos, pancytopeni, hemolytisk anemi, methemoglobinemi, trombocytopeni, pseudomononukleos'],
             ['Nervous system',
              u'Parestesi, perifer neuropati, st\xf6rningar i lukt- och smaksinne'],
             ['Eye', u'Allergisk konjunktivit'],
             ['Ear', u'Tinnitus'],
             ['Respiratory', u'Eosinofil pneumonit, hosta, astma, dyspn\xe9'],
             ['GI', u'Meteorism, diarr\xe9, pankreatit'],
             ['Skin', u'Cyanos i huden, Quinckes \xf6dem'],
             ['Musculoskeletal', u'Lupus erythematosus, myasteni, artralgi'],
             ['Vascular', u'H\xf6jt blodtryck'],
             ['General', u'Enantem'],
             ['Immune system',
              u'St\xf6rning som liknar serumsjuka, hypogammaglobulinemi, induktion av autoantikroppar'],
             ['Hepato', u'Leverdysfunktion'],
             ['Psychiatric', u'Depressioner']]],
           ['Rare',
            [['Blood', u'Benm\xe4rgsdepression, aplastisk anemi, plasmocytos'],
             ['Nervous system', u'Metallsmak'],
             ['Eye',
              u'Missf\xe4rgning av kontaktlins (ett enstaka fall d\xe4r mjuka kontaktlinser fick en gul nyans)'],
             ['Respiratory', u'Fibrotiserande alveolit'],
             ['GI', u'Stomatit'],
             ['Renal', u'Hematuri, kristalluri, gul-orange missf\xe4rgning av urinen'],
             ['Skin', u'Alopecia, exfoliativ dermatit, gul-orange missf\xe4rgning av huden'],
             ['Musculoskeletal', u'Myalgi'],
             ['Metabolism', u'Akuta attacker av porfyri'],
             ['Immune system',
              u'DRESS-syndrom (hudreaktion med eosinofili och systemiska symtom), reaktioner liknar delvis mononucleosis infectiosa eller serumsjuka; anafylaxi'],
             ['Hepato', u'Hepatit']]],
           ['Very rare',
            [['Cardiac', u'Myokardit, perikardit'],
             ['Nervous system', u'Aseptisk meningit, encefalopati, transversell myelit'],
             ['Respiratory', u'Obliterativ bronkiolit'],
             ['GI', u'Exacerbation av remittent ulcer\xf6s kolit'],
             ['Renal', u'Akut interstitiell nefrit, nefrotiskt syndrom, proteinuri'],
             ['Skin',
              u'Allvarliga hudbiverkningar (SCAR, severe cutaneous adverse reaction): Steven-Johnsons syndrom (SJS) och toxisk epidermal nekrolys (TEN; Lyells syndrom), se avsnitt 4.4'],
             ['Neoplasms', u'Myelodysplastiskt syndrom'],
             ['Vascular', u'Raynauds syndrom'],
             ['Hepato', u'Fulminant hepatit (med potentiellt d\xf6dlig utg\xe5ng)'],
             ['Psychiatric',
              u'Psykos Biverkningarna kan \xf6versiktligt delas in i tv\xe5 grupper: Den f\xf6rsta gruppen \xe4r dosrelaterad, beroende p\xe5 acetylerarfenotyp, och till stor del f\xf6ruts\xe4gbar. Denna grupp inbegriper illam\xe5ende och kr\xe4kningar, huvudv\xe4rk, hemolytisk anemi och methemoglobinemi. Den andra gruppen \xe4r \xf6verk\xe4nslighetsreaktioner, som i princip \xe4r of\xf6ruts\xe4gbara och oftast intr\xe4der vid behandlingens b\xf6rjan. Denna grupp inbegriper hudutslag, aplastisk anemi, lever- och lungdysfunktion samt autoimmun hemolys.']]]],
 '_pages': [5, 8],
 u'_rank': 46,
 u'_type': u'LSFU'}