{'_data': [['Common',
            [['Nervous system',
              u'yrsel, d\xe5sighet, sensoriska st\xf6rningar s\xe5som parestesi och hypestesi.'],
             ['Vascular',
              u'\xf6verg\xe5ende blodtrycksf\xf6rh\xf6jning strax efter behandling. Rodnad.'],
             ['Respiratory', u'dyspn\xe9.'],
             ['GI',
              u'illam\xe5ende och kr\xe4kningar har f\xf6rekommit hos en del patienter, men det \xe4r oklart om detta \xe4r relaterat till sumatriptan eller det bakomliggande tillst\xe5ndet.'],
             ['Musculoskeletal',
              u'tyngdk\xe4nsla (vanligtvis \xf6verg\xe5ende, kan vara intensiv och p\xe5verka olika delar av kroppen inklusive br\xf6stkorg och strupe). Myalgi.'],
             ['General',
              u'sm\xe4rta, k\xe4nsla av v\xe4rme, tryck eller \xe5tstramning (dessa biverkningar vanligtvis \xf6verg\xe5ende, kan vara intensiva och p\xe5verka olika delar av kroppen inklusive br\xf6stkorg och strupe). K\xe4nsla av svaghet, tr\xf6tthet (b\xe5da biverkningarna \xe4r oftast lindriga till m\xe5ttliga i sin intensitet och \xf6verg\xe5ende).']]],
           ['Very rare',
            [['Investigations',
              u'mindre f\xf6r\xe4ndringar av leverv\xe4rden har emellan\xe5t observerats.']]],
           ['Unknown',
            [['Nervous system',
              u'krampanfall, \xe4ven om det vissa fall har f\xf6rekommit hos patienter som antingen har anamnes p\xe5 krampanfall eller samtidiga tillst\xe5nd som predisponerar f\xf6r krampanfall finns det ocks\xe5 rapporter om patienter utan n\xe5gra uppenbara predisponerande faktorer. Tremor, dystoni, nystagmus, skotom.'],
             ['Vascular', u'hypotoni, Raynauds fenomen.'],
             ['GI', u'ischemisk kolit, diarr\xe9.'],
             ['Musculoskeletal', u'nackstelhet, artralgi.'],
             ['Psychiatric', u'\xe5ngest.'],
             ['Skin', u'hyperhidros.'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner som varierar fr\xe5n kutan \xf6verk\xe4nslighet (s\xe5som urtikaria) till s\xe4llsynta fall av anafylaxi.'],
             ['Eye',
              u'flimmer, diplopi, nedsatt syn. Synbortfall inklusive rapporter om permanenta defekter. Sj\xe4lva migr\xe4nanfallet kan dock ge upphov till synst\xf6rningar.'],
             ['Cardiac',
              u'bradykardi, takykardi, palpitationer, hj\xe4rtarytmier, \xf6verg\xe5ende ischemiska EKG-f\xf6r\xe4ndringar, spasm i hj\xe4rtats koronark\xe4rl, hj\xe4rtinfarkt (se avsnitt 4.3 och 4.4).']]]],
 '_pages': [5, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}