{'_data': [['Common',
            [['Nervous system',
              u'Yrsel, d\xe5sighet, stickningar s\xe5som parestesi och hypestesi.'],
             ['Vascular',
              u'\xd6verg\xe5ende f\xf6rh\xf6jt blodtryck som intr\xe4ffar direkt efter behandling. Rodnad.'],
             ['Respiratory', u'Dyspn\xe9.'],
             ['GI',
              u'Illam\xe5ende och kr\xe4kningar har intr\xe4ffat hos vissa patienter men det \xe4r oklart om detta \xe4r relaterat till sumatriptan eller bakomliggande tillst\xe5nd.'],
             ['Musculoskeletal',
              u'Tyngdk\xe4nsla (vanligtvis \xf6verg\xe5ende och kan vara intensiv och p\xe5verka andra kroppsdelar t ex br\xf6st- och halsomr\xe5det). Myalgi.'],
             ['General',
              u'Sm\xe4rta, v\xe4rme- eller k\xf6ldf\xf6rnimmelser, tryck- eller \xe5tstramningsk\xe4nsla (dessa symtom \xe4r vanligtvis \xf6verg\xe5ende och kan vara intensiva och kan p\xe5verka andra kroppsdelar t ex br\xf6st- och halsomr\xe5det). K\xe4nsla av svaghet, utamattning (b\xe5da \xe4r ofta svaga till m\xe5ttliga i intensitet och \xf6verg\xe5ende).']]],
           ['Uncommon',
            [['General',
              u'Somnoles (vanligtvis svaga till m\xe5ttliga i intensitet och \xf6verg\xe5ende).']]],
           ['Very rare',
            [['Investigations',
              u'Mindre st\xf6rningar i leverfunktionstester har ibland iakttagits.']]],
           ['Unknown',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner av alla sv\xe5righetsgrader fr\xe5n hudk\xe4nslighet till s\xe4llsynta fall av anafylaxi.'],
             ['Nervous system',
              u'Krampanfall. \xc4ven om vissa av dessa patienter har antingen en anamnes p\xe5 epilepsi eller en organskada som predisponerar f\xf6r krampanfall, finns \xe4ven rapporter om patienter utan n\xe5gra uppenbara predisponerande faktorer. Tremor, dystoni, nystagmus, skotom.'],
             ['Eye',
              u'Flimmer, dubbelseende och f\xf6rs\xe4mrad syn. Synbortfall inklusive rapporter om permanent synneds\xe4ttning. Emellertid kan sj\xe4lva migr\xe4nattacken ge upphov till synrubbningar.'],
             ['Cardiac',
              u'Bradykardi, takykardi, hj\xe4rtklappning, hj\xe4rtarrytmier, \xf6verg\xe5ende ischemiska EKG- f\xf6r\xe4ndringar, spasmangina, k\xe4rlkramp, hj\xe4rtinfarkt (se avsnitt 4.3 och 4.4).'],
             ['Vascular', u'Hypotension, Raynauds sjukdom.'],
             ['GI', u'Ischemisk kolit, diarr\xe9.'],
             ['Musculoskeletal', u'Stelhet i nacken, ledv\xe4rk.'],
             ['Psychiatric', u'\xc5ngest'],
             ['Skin', u'Hyperidros']]]],
 '_pages': [4, 6],
 u'_rank': 17,
 u'_type': u'LSFU'}