{'_data': [['Common',
            [['Nervous system',
              u'Yrsel, s\xf6mnighet, k\xe4nselst\xf6rningar inklusive parestesi och hypoestesi.'],
             ['Vascular',
              u'\xf6verg\xe5ende h\xf6jning av blodtrycket strax efter behandling, blodvallningar.'],
             ['GI',
              u'illam\xe5ende och kr\xe4kningar har f\xf6rekommit hos vissa patienter, men det \xe4r oklart om det hade samband med sumatriptan eller med underliggande tillst\xe5nd.'],
             ['Musculoskeletal',
              u'tyngdk\xe4nsla (vanligen \xf6verg\xe5ende; kan vara intensiv och drabba alla delar av kroppen inklusive br\xf6st och svalg), myalgi.'],
             ['General',
              u'sm\xe4rta, k\xe4nsla av v\xe4rme eller kyla, tryck eller \xe5tstramningsk\xe4nsla (vanligen \xf6verg\xe5ende; kan vara intensiv och drabba alla delar av kroppen inklusive br\xf6st och svalg), svaghetsk\xe4nsla, tr\xf6tthet (b\xe5da symptomen \xe4r f\xf6r det mesta milda till m\xe5ttliga i intensitet samt \xf6verg\xe5ende).'],
             ['Respiratory', u'Dyspn\xe9.']]],
           ['Very rare',
            [['Investigations',
              u'mindre st\xf6rningar i leverfunktionstester har tillf\xe4lligtvis observerats.']]],
           ['Unknown',
            [['Nervous system',
              u'Krampanfall \xe4ven om n\xe5gra krampanfall har drabbat patienter med antingen en anamnes p\xe5 krampanfall eller samtidiga sjukdomar som predisponerar f\xf6r krampanfall. Det finns ocks\xe5 rapporter fr\xe5n patienter utan n\xe5gra uppenbara predisponerande faktorer: tremor, dystoni, nystagmus, skotom.'],
             ['Vascular', u'Hypotension, Raynauds fenomen.'],
             ['GI', u'Ischemisk kolit, diarr\xe9.'],
             ['Musculoskeletal', u'Nackstelhet, artralgi.'],
             ['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner som varierar fr\xe5n \xf6verk\xe4nslighet i huden (s\xe5som utricaria) till anafylaxi.'],
             ['Eye',
              u'flimmer, dubbelseende, nedsatt syn, synbortfall inklusive rapporter om permanent synneds\xe4ttning. Synst\xf6rningar kan emellertid ocks\xe5 intr\xe4ffa under sj\xe4lva migr\xe4nattacken.'],
             ['Cardiac',
              u'bradykardi, takykardi, palpitationer, hj\xe4rtarytmier, \xf6verg\xe5ende ischemiska EKG- f\xf6r\xe4ndringar, vasospasm i kransart\xe4rer, angina, myokardinfarkt (se avsnitt 4.3 och 4.4).'],
             ['Skin', u'Hyperhidros'],
             ['Psychiatric', u'Oro']]]],
 '_pages': [4, 5],
 u'_rank': 16,
 u'_type': u'LSFU'}