{'_data': [['Very common', [['GI', u'Kr\xe4kningar +'], ['GI', u'Illam\xe5ende +']]],
           ['Common',
            [['Infections', u'Faryngit'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'Konjunktivit'],
             ['Cardiac', u'Nodul\xe4r arytmi'],
             ['Cardiac', u'Bradykardi'],
             ['Cardiac', u'Takykardi'],
             ['Cardiac', u'Hypertension'],
             ['Respiratory', u'+ Apn\xe9'],
             ['Respiratory', u'+ Hosta'],
             ['Respiratory', u'Laryngospasm*'],
             ['Investigations', u'\xd6kat kreatininfosfokinas'],
             ['Investigations', u'Onormalt EKG']]],
           ['Uncommon',
            [['Psychiatric', u'Agitation'],
             ['Nervous system', u'Yrsel'],
             ['Cardiac', u'Myokardinfarkt'],
             ['Cardiac', u'Myokardiell ischemi'],
             ['Cardiac', u'Arytmi'],
             ['Vascular', u'Vasodilatation'],
             ['Respiratory', u'Hypoxi +'],
             ['Musculoskeletal', u'Myalgi']]],
           ['Unknown',
            [['Blood', u'Koagulopati'],
             ['Metabolism', u'Hyperkalemi  Hypokalemi Metabolisk acidos'],
             ['Nervous system', u'Kramper'],
             ['Cardiac',
              u'Hj\xe4rtstillest\xe5nd  Torsade de pointes Ventrikul\xe4r svikt Ventrikul\xe4r hypokinesi'],
             ['Vascular', u'Malign hypertension  Bl\xf6dning Hypotension Chock'],
             ['Respiratory', u'Andningssvikt  Andn\xf6d Bronkospasm'],
             ['Hepato',
              u'Hepatisk nekros  Cytolytisk hepatit Kolestas Gulsot Onormal leverfunktion Leverrubbning'],
             ['Skin', u'Urtikaria  Erytem'],
             ['Musculoskeletal', u'Rhabdomyolys'],
             ['General', u'Malign hypertermi  Asteni  Sjukdomsk\xe4nsla'],
             ['Investigations',
              u'ST-T-f\xf6r\xe4ndring i EKG  T-v\xe5gsinversion i EKG \xd6kat alaninaminotransferas \xd6kat aspartataminotransferas Onormalt koagulationstest Ammonium\xf6kning']]]],
 '_pages': [5, 7],
 u'_rank': 33,
 u'_type': u'TSFU'}