{'_data': [['Very common',
            [['Immune system', u'Metabolism och   '],
             ['Eye', u'Stomatit/aft\xf6s 303 (29,2 %) 22 (2,1 %) 0 (0,0 %)'],
             ['Eye', u'Mycket Kr\xe4kningar 277 (26,7 %) 22 (2,1 %) 0 (0,0 %)'],
             ['Eye', u'Mycket Illam\xe5ende 456 (44,0 %) 29 (2,8 %) 0 (0,0 %)'],
             ['Eye', u'Mycket Dyspepsi 263 (25,4 %) 10 (1,0 %) 0 (0,0 %)'],
             ['Eye', u'Mycket Buksm\xe4rtor C /svullen 175 (16,9 %) 21 (2,0 %) 1 (0,1 %)'],
             ['Eye', u'Mycket F\xf6rstoppning 120 (11,6 %) 2 (0,2 %) 0 (0,0 %)'],
             ['Eye', u'Mycket Glossodyni 114 (11,0 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Hepato', u'Mycket Hand-fotsyndrom 230 (22,2 %) 66 (6,4 %) 0 (0,0 %)'],
             ['Hepato', u'Mycket Utslag 190 (18,3 %) 5 (0,5 %) 1 (0,1 %)'],
             ['Hepato',
              u'Mycket F\xf6r\xe4ndrad h\xe5rf\xe4rg 173 (16,7 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Hepato', u'Mycket Torr hud 142 (13,7 %) 1 (0,1 %) 0 (0,0 %)']]],
           ['Common',
            [['Immune system', u'Endokrina   '],
             ['Immune system', u'nutrition   '],
             ['Eye',
              u'\xd6gonlocks\xf6dem 19 (1,8 %) 1 (0,1 %) 0 (0,0 %) Hj\xe4rtat Mindre vanliga Kongestiv hj\xe4rtsvikt 4 (0,4 %) 3 (0,3 %) 1 (0,1 %)'],
             ['Eye', u'Blodvallning 18 (1,7 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye', u'Orofaryngeal sm\xe4rta 33 (3,2 %) 2 (0,2 %) 0 (0,0 %)'],
             ['Eye', u'Hosta 30 (2,9 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye', u'Anstr\xe4ngningsdys- 17 (1,6 %) 0 (0,0 %) 0 (0,0 %) pn\xe9'],
             ['Eye', u'Torr n\xe4sslemhinna 15 (1,4 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye', u'Pleurautgjutning 14 (1,4 %) 3 (0,3 %) 0 (0,0 %)'],
             ['Eye', u'N\xe4st\xe4ppa 14 (1,4 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye', u'stomatit'],
             ['Eye', u'vanliga'],
             ['Eye', u'vanliga'],
             ['Eye', u'vanliga'],
             ['Eye', u'buk'],
             ['Eye', u'vanliga'],
             ['Eye', u'vanliga'],
             ['Eye', u'Vanliga Sm\xe4rtor i munnen 104 (10,0 %) 3 (0,3 %) 0 (0,0 %)'],
             ['Eye', u'Vanliga Flatulens 100 (9,6 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'Vanliga Alopeci 92 (8,9 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Erytem 79 (7,6 %) 2 (0,2 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Hudreaktion 60 (5,8 %) 8 (0,8 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Hudexfoliation 57 (5,5 %) 4 (0,4 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Kl\xe5da 52 (5,0 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Dermatit 50 (4,8 %) 3 (0,3 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Periorbitalt \xf6dem 48 (4,6 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Hepato',
              u'Vanliga Nagelf\xf6r\xe4ndringar/ 39 (3,8 %) 0 (0,0 %) 0 (0,0 %) missf\xe4rgning'],
             ['Hepato', u'Vanliga Hudf\xf6r\xe4ndringar 35 (3,4 %) 2 (0,2 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Bl\xe5sor 29 (2,8 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Hyperkeratos 27 (2,6 %) 5 (0,5 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Acne 22 (2,1 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Hepato', u'Vanliga Hyperpigmentering 13 (1,3 %) 0 (0,0 %) 0 (0,0 %)'],
             ['General', u'vanliga'],
             ['General', u'Vanliga Pyrexi 58 (5,6 %) 5 (0,5 %) 0 (0,0 %)'],
             ['General', u'Vanliga Frossa 42 (4,1 %) 2 (0,2 %) 0 (0,0 %)'],
             ['General', u'Vanliga Br\xf6stsm\xe4rta 23 (2,2 %) 5 (0,5 %) 0 (0,0 %)'],
             ['General', u'Vanliga Sm\xe4rta 23 (2,2 %) 1 (0,1 %) 0 (0,0 %)'],
             ['General', u'Vanliga Influensaliknande 13 (1,3 %) 0 (0,0 %) 0 (0,0 %) sjukdom'],
             ['General', u'Vanliga Viktnedg\xe5ng 78 (7,5 %) 2 (0,2 %) 0 (0,0 %)'],
             ['General',
              u'Vanliga S\xe4nkt antal vita 68 (6,6 %) 32 (3,1 %) 2 (0,2 %) blodkroppar e'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt lipasv\xe4rde 66 (6,4 %) 30 (2,9 %) 17 (1,6 %)'],
             ['General',
              u'Vanliga S\xe4nkt trombocyt- 63 (6,1 %) 18 (1,7 %) 3 (0,3 %) v\xe4rde'],
             ['General',
              u'Vanliga S\xe4nkt hemoglobin- 49 (4,7 %) 12 (1,2 %) 0 (0,0 %) v\xe4rde'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt 40 (3,9 %) 8 (0,8 %) 2 (0,2 %) kreatininfosfokinas i serum'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt amylasv\xe4rde 37 (3,6 %) 17 (1,6 %) 2 (0,2 %)'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt 33 (3,2 %) 8 (0,8 %) 1 (0,1 %) aspartatamino transferasv\xe4rde (ASAT)'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt alanin- 27 (2,6 %) 9 (0,9 %) 2 (0,2 %) aminotransferas v\xe4rde (ALAT)'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt 26 (2,5 %) 2 (0,2 %) 1 (0,1 %) blodkreatininv\xe4rde 15 Organklass Frekvens Biverkningar Alla grader Grad 3 Grad 4 n (%) n (%) n (%)'],
             ['General', u'Vanliga H\xf6jt blodtryck 18 (1,7 %) 2 (0,2 %) 0 (0,0 %)'],
             ['General', u'Vanliga F\xf6rh\xf6jd urinsyra i11 (1,1 %) 0 (0,0 %) 11 (0,1 %)'],
             ['Infections', u'Vanliga Infektioner iandningsv\xe4garna'],
             ['Infections', u'Urinv\xe4gsinfektioner'],
             ['Infections', u'Hudinfektioner'],
             ['Infections', u'Abscesser'],
             ['Infections', u'infektioner'],
             ['Infections', u'infektioner'],
             ['Infections', u'Svampinfektioner'],
             ['GI', u'Esofagit']]],
           ['Uncommon',
            [['Immune system', u'systemet   '],
             ['Eye', u'Hj\xe4rtsvikt 3 (0,3 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Eye', u'Kardiomyopati 3 (0,3 %) 1 (0,1 %) 0 (0,0 %)'],
             ['Eye', u'Perikardiell 3 (0,3 %) 0 (0,0 %) 0 (0,0 %) utgjutning'],
             ['Eye', u'V\xe4nsterkammarsvikt 1 (0,1 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye',
              u'F\xf6rl\xe4ngt QT- 1 (0,1 %) 0 (0,0 %) 0 (0,0 %) intervall Blodk\xe4rl Mycket Hypertoni 236 (22,8 %) 96 (9,3 %) 0 (0,0 %)'],
             ['Eye',
              u'Djup ventrombos 6 (0,6 %) 4 (0,4 %) 0 (0,0 %) Andningsv\xe4gar, Mycket Epistaxis 126 (12,2 %) 4 (0,4 %) 0 (0,0 %) br\xf6stkorg och vanliga mediastinum Vanliga Dyspn\xe9 66 (6,4 %) 9 (0,9 %) 0 (0,0 %)'],
             ['Eye', u'Lungemboli 8 (0,8 %) 0 (0,0 %) 7 (0,7 %)'],
             ['Eye', u'Lungbl\xf6dning 2 (0,2 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye', u'Hemoptys 9 (0,9 %) 0 (0,0 %) 0 (0,0 %)'],
             ['Eye',
              u'Faryngolaryngeal 6 (0,6 %) 0 (0,0 %) 0 (0,0 %) sm\xe4rta Magtarm- Mycket Diarr\xe9 542 (52,3 %) 61 (5,9 %) 0 (0,0 %) kanalen vanliga'],
             ['Hepato',
              u'Mindre vanliga Kolecystit 1 (0,1 %) 1 (0,1 %) 0 (0,0 %) Hud och Mycket Gulf\xe4rgad 289 (27,9 %) 1 (0,1 %) 0 (0,0 %) subkutan v\xe4vnad vanliga hud/missf\xe4rgad hud/pigmentf\xf6r \xe4ndringar'],
             ['Hepato', u'Mindre vanliga Eksem 9 (0,9 %) 0 (0,0 %) 0 (0,0 %)'],
             ['General',
              u'Mindre vanliga F\xf6rs\xe4mrad 2 (0,2 %) 0 (0,0 %) 0 (0,0 %) s\xe5rl\xe4kning Unders\xf6kningar Vanliga S\xe4nkt/onormal 104 (10,0 %) 19 (1,8 %) 0 (0,0 %) ejektionsfraktion'],
             ['General',
              u'Mindre vanliga F\xf6rh\xf6jda niv\xe5er av 7 (0,7 %) 0 (0,0 %) 0 (0,0 %) tyreoideastimulerand e hormon (TSH) Biverkning av 974 (93,9 %) 482 (46,5 %) 112 (10,8 %) n\xe5got slag F\xf6ljande termer har kombinerats: aAnorexi och minskad aptit bDysgeusi, ageusi och smakst\xf6rningar cBuksm\xe4rta och sm\xe4rta i den \xf6vre delen av buken d\xd6dem, perifert \xf6dem och ansikts\xf6dem eMinskat antal vita blodkroppar, minskat antal neutrofiler, och minskat antal leukocyter'],
             ['Infections', u'Sepsis / septisk chock'],
             ['Blood', u'Trombotisk mikroangiopati'],
             ['Immune system', u'Angio\xf6dem'],
             ['Endocrine', u'Thyreoidit'],
             ['Respiratory', u'Andningsinsufficiens'],
             ['Hepato', u'Leversvikt'],
             ['Hepato', u'Hepatit'],
             ['Musculoskeletal', u'Myopati, rabdomyolys'],
             ['Musculoskeletal', u'K\xe4kosteonekros 16']]],
           ['Rare',
            [['Hepato', u'S\xe4llsynta Stevens-Johnson 1 (0,1 %) 1 (0,1 %) 0 (0,0 %) syndrom'],
             ['Infections', u'fascit'],
             ['Cardiac', u'S\xe4llsynta Torsade de pointes'],
             ['Skin', u'Toxisk epidermal nekrolys'],
             ['Skin', u'gangrenosum'],
             ['Skin', u'multiforme']]],
           ['Unknown',
            [['Hepato', u'leverfunktion'],
             ['General',
              u'vanliga symtom vid Mycket Slemhinne- 189 (18,2 %) 11 (1,1 %) 0 (0,0 %) administrerings- vanliga inflammation st\xe4llet Mycket d \xd6dem 120 (11,6 %) 5 (0,5 %) 0 (0,0 %)'],
             ['Infections',
              u'fall, har rapporterats. Ett f\xe5tal fall fick d\xf6dlig utg\xe5ng (se \xe4ven avsnitt 4.4). S\xe4llsynta fall av nekrotiserande fascit, \xe4ven i perineum, i vissa fall med d\xf6dlig utg\xe5ng, har rapporterats. Blodet och lymfsystemet: S\xe4llsynta fall av trombotisk mikroangiopati har rapporterats. Tempor\xe4r uts\xe4ttning av SUTENT rekommenderas. Behandlingen kan \xe5terupptas efter tillbakag\xe5ng, enligt den behandlande l\xe4karens bed\xf6mning. Immunsystemet: \xd6verk\xe4nslighetsreaktioner, inklusive angio\xf6dem, har rapporterats. Centrala och perifera nervsystemet: Det finns ett f\xe5tal rapporter, vissa fatala, g\xe4llande patienter med kramper och radiologiska fynd av reversibelt posteriort leukoencefalopatisyndrom (RPLS) (se \xe4ven avsnitt 4.4). Endokrina systemet: S\xe4llsynta fall av hypertyreos, somliga f\xf6ljda av hypotyreos, har rapporterats fr\xe5n kliniska studier och efter marknadsintroduktionen (se \xe4ven avsnitt 4.4). Metabolism och nutrition: Fall av tum\xf6rlyssyndrom, vissa med d\xf6dlig utg\xe5ng, har rapporterats hos patienter som behandlats med sunitinib. Hj\xe4rtat: Hj\xe4rth\xe4ndelser, \xe4ven hj\xe4rtsvikt, kardiomyopati och myokardiesjukdomar, vissa med d\xf6dlig utg\xe5ng, har rapporterats efter marknadsintroduktionen (se \xe4ven avsnitt 4.4). Andningsv\xe4gar, br\xf6stkorg och mediastinum: Fall av lungemboli och lungbl\xf6dning, vissa med d\xf6dlig utg\xe5ng, har rapporterats. Magtarmkanalen: Fall av esofagit, i vissa fall med d\xf6dlig utg\xe5ng, har rapporterats. Lever- och gallv\xe4gar: Leverdysfunktion har rapporterats och kan innefatta onormala leverfunktionsv\xe4rden, hepatit eller leversvikt. Kolecystitfall, i vissa fall med d\xf6dlig utg\xe5ng, har rapporterats (se \xe4ven avsnitt 4.4). Hud och subkutan v\xe4vnad: Fall av pyoderma gangrenosum, generellt reversibelt efter uts\xe4ttning av l\xe4kemedlet, har rapporterats i s\xe4llsynta fall (se \xe4ven avsnitt 4.4). Muskuloskeletala systemet och bindv\xe4v: S\xe4llsynta fall av myopati och/eller rabdomyolys, i n\xe5gra fall med akut njursvikt, har rapporterats. Patienter som visar tecken eller symtom p\xe5 muskeltoxicitet ska behandlas enligt medicinsk praxis. Fall av fistelbildning, ibland i samband med tum\xf6rnekros och regression, i n\xe5gra fall d\xf6dliga, har rapporterats. Fall av f\xf6rs\xe4mrad s\xe5rl\xe4kning har rapporterats under behandling med sunitinib. Fall av osteonekros i k\xe4ken har rapporterats hos patienter behandlade med SUTENT, de flesta intr\xe4ffade hos patienter med identifierad riskfaktor f\xf6r osteonekros i k\xe4ken, framf\xf6r allt hos patienter exponerade f\xf6r bisfosfonatbehandling intraven\xf6st eller tidigare tandsjukdom kr\xe4vande invasiva tandingrepp (se \xe4ven avsnitt 4.4). Njurar och urinv\xe4gar: Fall av nedsatt njurfunktion, njursvikt och/eller akut njursvikt, i n\xe5gra fall med d\xf6dlig utg\xe5ng, har rapporterats. Fall av proteinuri och s\xe4llsynta fall av nefrotiskt syndrom har rapporterats. S\xe4kerheten vid fortsatt behandling med SUTENT hos patienter med m\xe5ttlig till sv\xe5r']]]],
 '_pages': [10, 17],
 u'_rank': 107,
 u'_type': u'LSFU'}