{'_data': [['Common',
            [['Psychiatric', u'Nervositet'],
             ['GI', u'Diarr\xe9'],
             ['General', u'Feber  Reaktion p\xe5 injektionsst\xe4llet'],
             ['General', u'Feber  Reaktion p\xe5 injektionsst\xe4llet']]],
           ['Uncommon',
            [['Infections', u'Virusinfektion  \xd6vre luftv\xe4gsinfektion'],
             ['Blood', u'Leukopeni'],
             ['Respiratory', u'V\xe4sande  Rinitis  Hosta'],
             ['GI', u'Kr\xe4kning'],
             ['Skin', u'Utslag'],
             ['General', u'Sm\xe4rta'],
             ['Investigations',
              u'F\xf6rh\xf6jt ASAT  F\xf6rh\xf6jt ALAT Abnormala leverfunktionstest'],
             ['Infections', u'Gastroenterit  \xd6vre luftv\xe4gsinfektion'],
             ['Psychiatric', u'Nervositet'],
             ['Nervous system', u'Somnolens  Hyperkinesi'],
             ['Vascular', u'Bl\xf6dning'],
             ['Respiratory', u'Rinit'],
             ['GI', u'Kr\xe4kning  Diarr\xe9 F\xf6rstoppning'],
             ['Skin', u'Utslag  Eksem'],
             ['General', u'Asteni']]]],
 '_pages': [3, 5],
 u'_rank': 19,
 u'_type': u'TSFU'}