{'_data': [['Common',
            [['Nervous system', u'huvudv\xe4rk, tr\xf6tthet'],
             ['GI',
              u'illam\xe5ende, buksm\xe4rtor, matsm\xe4ltningsbesv\xe4r, diarr\xe9, f\xf6rstoppning']]],
           ['Uncommon', [['Skin', u'hudutslag, kl\xe5da, hudrodnad (\u201dflush\u201d)']]],
           ['Unknown',
            [['Nervous system', u'yrsel'],
             ['Respiratory', u'astma/f\xf6rv\xe4rrad astma'],
             ['GI', u'kr\xe4kningar'],
             ['Skin', u'angio\xf6dem, urtikaria'],
             ['Metabolism',
              u'f\xf6rs\xe4mrad kontroll av diabetes mellitus, hyperkolesterolemi'],
             ['General', u'\xf6dem/perifert \xf6dem']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 3],
 u'_rank': 9,
 u'_type': u'MSFU'}