{'_data': [['Uncommon',
            [['Metabolism',
              u'Antidiuretisk effekt vilket kan orsaka vatten-intoxikation med huvudv\xe4rk och illam\xe5ende.']]],
           ['Rare',
            [['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Hj\xe4rtarytmier.'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar.'],
             ['Skin', u'Hudrodnad, urtikaria.'],
             ['Respiratory', u'Larynx\xf6dem']]],
           ['Unknown',
            [['Immune system',
              u'Anafylaktoida reaktioner tillsammans med t ex hypotension, andn\xf6d och chock.']]]],
 '_pages': [2, 2],
 u'_rank': 7,
 u'_type': u'LSFU'}