{'_data': [['Very common',
            [['Infections', u'Bronkit, Nasofaryngit,'],
             ['Immune system', u'\xd6verk\xe4nslighets'],
             ['Nervous system', u'Huvudv\xe4rk Insomnia'],
             ['Cardiac', u'Hj\xe4rtarytmi'],
             ['Respiratory', u'Hosta,'],
             ['GI', u'Illam\xe5ende Kr\xe4kningar,'],
             ['Hepato', u'F\xf6rh\xf6jda'],
             ['Skin', u'Eksem,'],
             ['General', u'Sm\xe4rta,'],
             ['Infections', u'Otitis'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'Konjunktivit (inklusive'],
             ['Ear', u'\xd6ronv\xe4rk'],
             ['Respiratory', u'Hosta, N\xe4st\xe4ppa'],
             ['GI', u'Kr\xe4kningar Buksm\xe4rta'],
             ['Skin', u'Dermatit']]],
           ['Common',
            [['Infections', u'\xd6vre luftv\xe4gs-infektion, Sinuit'],
             ['Blood', u'Trombocytopeni'],
             ['Psychiatric', u'Agitation,'],
             ['Eye', u'Synrubbning'],
             ['Respiratory', u'Halsont, Rinorr\xe9'],
             ['GI', u'Buksm\xe4rta (inklusive sm\xe4rta i \xf6vre delen av buken), Dyspepsi'],
             ['Hepato', u'Biverkningar enligt frekvens'],
             ['General',
              u'Yrsel (inklusive vertigo), Tr\xf6tthet, Pyrexi, Sm\xe4rta i extremiteterna'],
             ['Infections', u'media'],
             ['Eye', u'\xf6gonrodnad, sekretion fr\xe5n \xf6gat och \xf6gonsm\xe4rta)'],
             ['Respiratory', u'Rinorr\xe9'],
             ['GI', u'(inklusive sm\xe4rta i \xf6vre delen av buken), Dyspepsi, Illam\xe5ende']]],
           ['Uncommon',
            [['Immune system', u'reaktion'],
             ['Nervous system', u'F\xf6r\xe4ndrade medvetande-niv\xe5er, Konvulsion'],
             ['GI', u'Gastrointestinala'],
             ['Hepato', u'leverenzymer'],
             ['Skin', u'Dermatit, Hudustlag, Urtikaria'],
             ['Ear', u'Sjukdomar  i trumhinnan'],
             ['Skin', u'(inklusive allergisk och atopisk dermatit)']]],
           ['Rare',
            [['Immune system', u'Anafylaktiska reaktioner, Anafylaktoida reaktioner'],
             ['Psychiatric',
              u'Onormalt beteende, \xc5ngest, F\xf6rvirring, Vanf\xf6rest\xe4llningar, Delirium, Hallucinationer, Mardr\xf6mmar, Sj\xe4lvskador'],
             ['GI', u'bl\xf6dningar, Hemorragisk kolit'],
             ['Hepato', u'Fulminant hepatit, Leversvikt, Hepatit'],
             ['Skin',
              u'Angioneurotiskt \xf6dem, Erythema multiforme, Stevens-Johnsons syndrom, Toxisk epidermal nekrolys']]]],
 '_note': u' ?MSFU ANOMALI in Headers ANOMALI in Headers ANOMALI in Headers',
 '_pages': [8, 12],
 u'_rank': 40,
 u'_type': u'MSFU'}