{'_data': [['Uncommon', [['Renal', u'glykosuri  '], ['Renal', u'proteinuri  ']]],
           ['Very rare',
            [['Investigations',
              u'ta fall kan lindriga \xf6verk\xe4nslighetsreaktioner utvecklas till allvarliga reaktioner med dyspn\xe9, blodtrycksfall och ibland chock. \xd6verk\xe4nslighetsreaktioner i huden kan f\xf6rekomma som kl\xe5da, utslag och urtikaria. Korsallergenicitet med sulfonureider, sulfonamider eller relaterade \xe4mnen \xe4r m\xf6jlig. 3 Efter marknadsintroduktion har \xf6verk\xe4nslighetsreaktioner rapporterats hos patienter som har behandlats med pioglitazon. Dessa reaktioner omfattar anafylaxi, angio\xf6dem och urtikaria. Synst\xf6rningar har fr\xe4mst rapporterats tidigt under behandlingen och \xe4r kopplade till f\xf6r\xe4ndringarna i blodglukos genom en tillf\xe4llig f\xf6r\xe4ndring av linsens turgiditet och brytningsindex som ses \xe4ven med andra hypoglykemiska medel. Gastrointestinala besv\xe4r \xe4r mycket s\xe4llsynta och leder s\xe4llan till att behandlingen avbryts.']]],
           ['Unknown',
            [['Infections',
              u'\xf6vre luftv\xe4gsinfektion vanlig vanlig sinusit mindre vanlig mindre vanlig Neoplasier; benigna, maligna och ospecificerade (samt cystor och polyper) bl\xe5scancer mindre vanlig mindre vanlig Blodet och lymfsystemet f\xf6r\xe4ndrad hematologi s\xe4llsynt s\xe4llsynt'],
             ['Immune system',
              u'allergisk chock mycket s\xe4llsynt mycket s\xe4llsynt allergisk vaskulit mycket s\xe4llsynt mycket s\xe4llsynt \xf6verk\xe4nslighets- och ingen k\xe4nd frekvens ingen k\xe4nd frekvens allergiska reaktioner Metabolism och nutrition hypoglykemi mindre vanlig \xf6kat aptit mindre vanlig Centrala och perifera'],
             ['Eye',
              u'synst\xf6rning vanlig mindre vanlig makula\xf6dem ingen k\xe4nd frekvens ingen k\xe4nd frekvens \xd6ron och balansorgan svindel mindre vanlig'],
             ['GI',
              u'kr\xe4kning mycket s\xe4llsynt mycket s\xe4llsynt diarr\xe9 mycket s\xe4llsynt mycket s\xe4llsynt illam\xe5ende mycket s\xe4llsynt mycket s\xe4llsynt buksm\xe4rta mycket s\xe4llsynt mycket s\xe4llsynt tryck i buken mycket s\xe4llsynt mycket s\xe4llsynt m\xe4ttnadsk\xe4nsla i mycket s\xe4llsynt mycket s\xe4llsynt 9 Biverkan Biverkansfrekvens Pioglitazon Glimepirid Tandemact magen'],
             ['Hepato',
              u'hepatit mycket s\xe4llsynt mycket s\xe4llsynt nedsatt leverfunktion mycket s\xe4llsynt mycket s\xe4llsynt (med kolestas och gulsot) Hud och subkutan v\xe4vnad svettning mindre vanlig \xf6verk\xe4nslighet f\xf6r ljus mycket s\xe4llsynt mycket s\xe4llsynt urtikaria ingen k\xe4nd frekvens ingen k\xe4nd frekvens kl\xe5da ingen k\xe4nd frekvens ingen k\xe4nd frekvens utslag ingen k\xe4nd frekvens ingen k\xe4nd frekvens Muskuloskeletala systemet och bindv\xe4v benfraktur vanlig vanlig'],
             ['General',
              u'och/eller symtom vid administreringsst\xe4llet \xf6dem vanlig tr\xf6tthet mindre vanlig'],
             ['Investigations',
              u'vikt\xf6kning vanlig vanlig vanlig \xf6kat mindre vanlig laktatdehydrogenas minskade mycket s\xe4llsynt mycket s\xe4llsynt natriumkoncentrationer i serum \xf6kat ingen k\xe4nd frekvens ingen k\xe4nd frekvens alaninaminotransferas Beskrivning av valda biverkningar 1 M\xe5ttlig till sv\xe5r trombocytopeni, leukopeni, erytrocytopeni, granulocytopeni, agranulocytos, hemolytisk anemi och pancytopeni kan f\xf6rekomma. Dessa \xe4r i allm\xe4nhet reversibla d\xe5 behandlingen avbryts.']]]],
 '_pages': [7, 10],
 u'_rank': 10,
 u'_type': u'LSFU'}