{'_data': [['Very common',
            [['Blood', u'Leukopeni'],
             ['Endocrine', u'Hypotyreoidism'],
             ['Metabolism', u'Hyperlipidemi, hyperkolesterolemi'],
             ['Skin', u'Exfoliativ dermatit, kl\xe5da, hudutslag'],
             ['General', u'Sm\xe4rta, huvudv\xe4rk, asteni 7']]],
           ['Common',
            [['Blood', u'Lymfomliknande reaktion, lymfadenopati, hypokrom anemi'],
             ['Endocrine', u'Sk\xf6ldk\xf6rtelrubbning'],
             ['Metabolism',
              u'Vikt\xf6kning, f\xf6rh\xf6jt ASAT, f\xf6rh\xf6jt ALAT, \xf6kad mj\xf6lksyredehydrogenas, \xf6kat kreatinin, hypoproteinemi'],
             ['Nervous system', u'Yrsel, hypestesi, insomnia'],
             ['Eye', u'\xd6gontorrhet, \xf6gonbesv\xe4r'],
             ['Ear', u'D\xf6vhet,'],
             ['Vascular', u'Perifert \xf6dem'],
             ['GI',
              u'Kr\xe4kningar, diarr\xe9 , illam\xe5ende , anorexi , onormala leverfunktionsv\xe4rden, keilit , muntorrhet , f\xf6rstoppning, flatulens'],
             ['Skin',
              u'S\xe5r, alopeci , hudhypertrofi, hudnodulus, akne, svettning, torr hud , hudbesv\xe4r'],
             ['Musculoskeletal', u'Skelettsm\xe4rta, artralgi, myalgi'],
             ['General',
              u'Allergisk reaktion, infektion, k\xf6ldrysningar , magsm\xe4rta, \xe4ndrad hormonniv\xe5']]],
           ['Uncommon',
            [['Blood',
              u'Bloddyskrasi, purpura, koagulationsrubbning, \xf6kad koagulationstid , anemi , trombocytopeni , trombocytemi, eosinofili , leukocytos , lymfocytos'],
             ['Endocrine', u'Hypertyreoidism'],
             ['Metabolism',
              u'Gikt, bilirubinemi , \xf6kat ureakv\xe4ve i blodet , minskat h\xf6gdensitetslipoprotein (HDL)'],
             ['Nervous system',
              u'Ataxi, neuropati, vertigo, hyperestesi, depression , agitation'],
             ['Eye',
              u'Konstaterad katarakt , amblyopi , synf\xe4ltsdefekter, s\xe5r p\xe5 kornea, onormal syn , blefarit, konjunktivit'],
             ['Ear', u'\xd6ronbesv\xe4r'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hemorragi, hypertoni, \xf6dem , vasodilatation , \xe5derbr\xe5ck'],
             ['GI', u'Pankreatit , leversvikt, gastrointestinal rubbning'],
             ['Skin',
              u'Ser\xf6st dr\xe4nage , herpes simplex, pustul\xf6st hudutslag, missf\xe4rgning av huden , h\xe5rbesv\xe4r , nagelbesv\xe4r'],
             ['Musculoskeletal', u'Myasteni'],
             ['Renal', u'Albuminuri , onormal njurfunktion'],
             ['General',
              u'Neoplasm, feber , cellulit, parasitinfektion, slemhinnerubbning , ryggsm\xe4rta , onormalt laboratorietest 1: biverkningar som noterats med \xf6kad frekvens n\xe4r bexaroten administrerats vid en dos p\xe5 >300 mg/m /dag 2: biverkningar som noterats med \xf6kad frekvens n\xe4r bexaroten administrerats vid en dos p\xe5 300 mg/m /dag till icke-CTCL-cancerpatienter 3: biverkningar som noterats med \xf6kad frekvens n\xe4r bexaroten administrerats vid en dos p\xe5 >300 mg/m /dag (j\xe4mf\xf6rt med administrering till CTCL-patienter vid 300 mg/m /dag) till icke-CTCL-cancerpatienter Ytterligare biverkningar som observerats vid anv\xe4ndning utanf\xf6r rekommenderad dos och indikation (dvs hos patienter med CTCL vid en initialdos > 300 mg/m /dag eller icke-CTCL cancerindikationer): Nytillkomna biverkningar som observerats: ekkymos, petekier, onormala vita blodkroppar, minskat tromboplastin, onormala erytrocyter, uttorkning, \xf6kad niv\xe5 av gonadotropt luteiniseringshormon (GLH), viktminskning, \xf6kat alkaliskt fosfatas, \xf6kat kreatininfosfokinas, \xf6kat lipas, hyperkalcemi, migr\xe4n, perifer neurit, parestesi, hypertoni, konfusion, oro, emotionell labilitet, somnolens, minskat libido, nervositet, nattblindhet, nystagmus, t\xe5rfl\xf6desrubbning, tinnitus, smakf\xf6r\xe4ndring, br\xf6stsm\xe4rta, arytmi, perifer cirkulationsrubbning, allm\xe4nt \xf6dem, hemoptys, dyspn\xe9, \xf6kad hosta, sinusit, faryngit, dysfagi, muns\xe5r, muntorsk, stomatit, dyspepsi, t\xf6rst, onormal avf\xf6ring, eruktation, vesikulobull\xf6st utslag, makulopapul\xf6st utslag, benkramper, hematuri, influensasyndrom, b\xe4ckensm\xe4rta och kroppsod\xf6r. Enstaka observationer av f\xf6ljande har ocks\xe5 rapporterats: benm\xe4rgsdepression, minskat protrombin, minskat gonadotropt luteiniseringshormon (GLH), \xf6kat amylas, hyponatremi, hypokalemi, hyperurikemi, hypokolesterolemi, hypolipemi, hypomagnesemi, g\xe5ngrubbning, stupor, cirkumoral parestesi, onormala tankar, \xf6gonsm\xe4rta, hypovolemi, subduralt hematom, hj\xe4rtsvikt, palpitation, epistaxis, vaskul\xe4r anomali, vaskul\xe4r rubbning, blekhet, pneumoni, luftv\xe4gsbesv\xe4r, lungbesv\xe4r, lungs\xe4cksbesv\xe4r, kolecystit, leverskada, gulsot, kolestatisk gulsot, melena, kr\xe4kningar, laryngism, tenesmus, rinit, aptit\xf6kning, gingivit, herpes zoster, psoriasis, furunkulos, kontaktdermatit, seborr\xe9, likenoid dermatit, artrit, ledbesv\xe4r, urinretention, nedsatt miktionsf\xf6rm\xe5ga, polyuri, nokturi, impotens, onormal miktion, br\xf6stf\xf6rstoring, karcinom, fotosensitivitetsreaktion, ansikts\xf6dem, sjukdomsk\xe4nsla, virusinfektion, bukf\xf6rstoring. De flesta biverkningar observerades med h\xf6gre frekvens vid doser \xf6ver 300 mg/m /dag. I allm\xe4nhet f\xf6rsvann dessa biverkningar utan f\xf6ljdtillst\xe5nd n\xe4r dosen minskades eller l\xe4kemedlet utsattes. Bland totalt 810 patienter, inklusive patienter utan malignitet, som behandlades med bexaroten intr\xe4ffade dock tre allvarliga biverkningar med d\xf6dlig utg\xe5ng (akut pankreatit, subduralt hematom och leversvikt). Av dessa var leversvikt den enda biverkningen som drabbade en CTCL-patient. Man kunde senare fastst\xe4lla att denna biverkning inte var relaterad till behandlingen med bexaroten. Hypotyreoidism upptr\xe4der i allm\xe4nhet 4\u20138 veckor efter behandlingens inledande. Reaktionen kan vara asymtomatisk och svarar p\xe5 behandling med tyroxin samt f\xf6rsvinner n\xe4r behandlingen uts\xe4tts. Bexaroten har inte samma biverkningar som andra orala, icke-retinoida X-receptor- (RXR) selektiva retinoider. P\xe5 grund av dess huvudsakligen RXR-bindande aktivitet orsakar bexaroten mindre mukokutan, nagel- och h\xe5rtoxicitet, artralgi och myalgi, vilka ofta rapporteras i samband med retinoidsyrereceptorbindande medel (RAR).']]]],
 '_pages': [5, 7],
 u'_rank': 29,
 u'_type': u'LSFU'}