{'_data': [['Common',
            [['Metabolism', u'Minskad aptit till aptitf\xf6rlust'],
             ['Psychiatric', u'S\xf6mnl\xf6shet'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk, somnolens'],
             ['Ear', u'Vertigo'],
             ['Vascular', u'Blodvallning'],
             ['GI',
              u'Buksm\xe4rtor, f\xf6rstoppning, diarr\xe9, muntorrhet, dyspepsi, kr\xe4kning, illam\xe5ende, flatulens'],
             ['Skin', u'Pruritus, hudreaktioner, hyperhidros'],
             ['General', u'Asteniska besv\xe4r'],
             ['Psychiatric',
              u'Hum\xf6r- och personlighetsf\xf6r\xe4ndringar, minskad aktivitet, psykomotorisk hyperaktivitet'],
             ['GI', u'Hicka'],
             ['Skin', u'Dysuri']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'Rastl\xf6shet, onormalt t\xe4nkande, oro, f\xf6rvirring, depression, nervositet'],
             ['Nervous system',
              u'Krampanfall (s\xe4rskilt hos personer med epilepsisjukdom eller predisposition f\xf6r krampanfall), uppm\xe4rksamhetsst\xf6rning, talst\xf6rningar, synkope, tremor'],
             ['Eye', u'Synskada'],
             ['Cardiac',
              u'Angina pectoris (s\xe4rskilt hos patienter som tidigare har lidit av kransk\xe4rlssjukdom), palpitationer'],
             ['Vascular', u'Blodtrycksfall, blodtrycks\xf6kning'],
             ['Respiratory', u'Dyspn\xe9, rinorr\xe9, hosta'],
             ['GI', u'Abdominell distension'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymer, gallkolik'],
             ['Musculoskeletal',
              u'Muskelspasmer, muskelryckningar, myalgi Njur- och urinv\xe4gsst\xf6rningar'],
             ['Musculoskeletal', u'Urintr\xe4ngningar'],
             ['General',
              u'Abstinenssyndrom, br\xf6stsm\xe4rta, frossa, olustk\xe4nsla, sm\xe4rta, perifert \xf6dem, viktminskning'],
             ['Injury',
              u'Olycksrelaterade skador F\xf6r den aktiva substansen oxikodonhydroklorid \xe4r f\xf6ljande tillkommande biverkningar k\xe4nda: P\xe5 grund av dess farmakologiska egenskaper kan oxikodonhydroklorid orsaka andningsdepression, mios, bronkial spasm och spasmer i den glatta muskulaturen liksom undertrycka hostreflexen.'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric',
              u'Uppr\xf6rdhet, perceptionsst\xf6rningar (t.ex. overklighetsk\xe4nsla), minskad libido, l\xe4kemedelsberoende'],
             ['Nervous system',
              u'Nedsatt koncentrationsf\xf6rm\xe5ga, migr\xe4n, dysgeusi, hypertoni, ofrivilliga muskelsammandragningar, hypestesi, onormal koordination'],
             ['Ear', u'H\xf6rselneds\xe4ttning'],
             ['Vascular', u'Vasodilatation'],
             ['Respiratory', u'Dysfoni'],
             ['GI', u'Dysfagi, ileus, muns\xe5r, stomatit'],
             ['Skin', u'Torr hud'],
             ['General', u'\xd6dem, t\xf6rst, l\xe4kemedelstolerans']]],
           ['Rare',
            [['Cardiac', u'Takykardi'],
             ['Respiratory', u'G\xe4spningar'],
             ['GI', u'Tandproblem'],
             ['General', u'Vikt\xf6kning'],
             ['Infections', u'Herpes simplex'],
             ['Metabolism', u'\xd6kad aptit'],
             ['GI', u'Melena, bl\xf6dande tandk\xf6tt'],
             ['Skin', u'Urtikaria Njur- och urinv\xe4gsst\xf6rningar']]],
           ['Unknown',
            [['Psychiatric', u'Eufori, hallucination, mardr\xf6mmar'],
             ['Nervous system', u'Parestesier, sl\xf6het'],
             ['Respiratory', u'Andningsdepression'],
             ['GI', u'Eruktation'],
             ['Reproductive system', u'Erektionsst\xf6rningar'],
             ['Musculoskeletal', u'Urinretention'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Hepato', u'Kolestas'],
             ['Reproductive system', u'Amenorr\xe9']]]],
 '_pages': [6, 8],
 u'_rank': 50,
 u'_type': u'LSFU'}