{'_data': [['Very common',
            [['Metabolism',
              u'hypofosfatemi (inkluderande minskande halter av fosfater i blodet).'],
             ['Hepato',
              u'hyperbilirubinemi (inkluderande \xf6kning av bilirubinhalten i blodet).'],
             ['Investigations',
              u'\xf6kat alaninaminotransferas, \xf6kat aspartataminotransferas, \xf6kat lipas.']]],
           ['Common',
            [['Nervous system', u'vanliga'],
             ['GI', u'vanliga F\xf6rstoppning Vanliga 10 0Mycket 12 <1 <1 0'],
             ['GI', u'vanliga Diarr\xe9 Vanliga 9 <1 Mycket 11 2 2 <1'],
             ['GI', u'vanliga Kr\xe4kningar Vanliga 6 0Mycket 10 <1 <1 0'],
             ['GI',
              u'vanliga Sm\xe4rta i \xf6vre Vanliga 10 1 Vanliga 5 <1 <1 0 delen av buken Buksm\xe4rta Vanliga 6 0Vanliga 6 <1 <1 <1 Dyspepsi Vanliga 5 0Vanliga 3 000'],
             ['Skin', u'vanliga Pruritus Mycket 18 <1 Mycket 24 <1 <1 0'],
             ['Skin',
              u'vanliga Alopeci Vanliga 10 0Vanliga 9 000 Torr hud Vanliga 9 0Vanliga 5 000 Erytem Vanliga 2 0Vanliga 5 <1 <1 0'],
             ['Musculoskeletal',
              u'vanliga Artralgi Vanliga 7 <1 Vanliga 7 <1 1 0 Muskelspasm Vanliga 9 0Vanliga 8 <1 <1 0 Skelettsm\xe4rta Vanliga 4 0Vanliga 6 <1 <1 0 Sm\xe4rta i Vanliga 5 <1 Vanliga 5 <1 <1 <1 extremiteterna'],
             ['General',
              u'vanliga Asteni Vanliga 9 <1 Vanliga 6 <1 0<1 \xd6dem, perifert Vanliga 5 0Vanliga 6 000'],
             ['Infections',
              u'follikulit, \xf6vre luftv\xe4gsinfektion (inkluderande faryngit, nasofaryngit, rinit).'],
             ['Neoplasms', u'hudpapillom.'],
             ['Blood', u'febril neutropeni, pancytopeni, lymfopeni.'],
             ['Metabolism',
              u'elektrolytobalans (inklusive hypomagnesemi, hyperkalemi, hypokalemi, hyponatremi, hypokalcemi, hyperkalcemi, hyperfosfatemi), diabetes mellitus, hyperglykemi, hypercholesterolaemia, hyperlipidemi.'],
             ['Psychiatric', u'depression, insomnia, oro.'],
             ['Nervous system', u'yrsel, perifer neuropati, hypoestesi, parestesi.'],
             ['Eye',
              u'\xf6gonbl\xf6dning, periorbitalt \xf6dem, \xf6gonpruritus, konjunktivit, torra \xf6gon (inkluderande xeroftalmi).'],
             ['Ear', u'vertigo.'],
             ['Cardiac',
              u'angina pectoris, arytmi (inklusive atrioventrikul\xe4rt block, hj\xe4rtfladder, extrasystole, takykardi, f\xf6rmaksflimmer, bradykardi), palpitationer, f\xf6rl\xe4ngt EKG-QT.'],
             ['Vascular', u'hypertoni, flushing.'],
             ['Respiratory',
              u'dyspn\xe9, anstr\xe4ngningsdyspn\xe9, epistaxis, hosta, dysfoni.'],
             ['GI',
              u'pankreatit, magbesv\xe4r, utsp\xe4nd buk, dysgeusi, v\xe4dersp\xe4nning.'],
             ['Hepato', u'onormal leverfunktion.'],
             ['Skin',
              u'nattliga svettningar, eksem, urtikaria, erytem, hyperhidros, kontusion, akne, dermatit (inkluderande allergisk, exfolierande och akneiform), torr hud.'],
             ['Musculoskeletal',
              u'muskuloskeletal br\xf6stsm\xe4rta, muskuloskeletal sm\xe4rta, ryggv\xe4rk, flanksm\xe4rta, nacksm\xe4rta.'],
             ['Renal', u'pollakisuri.'],
             ['General',
              u'br\xf6stsm\xe4rta (inkluderande icke kardiell br\xf6stsm\xe4rta), sm\xe4rta pyrexi, br\xf6stbesv\xe4r, sjukdomsk\xe4nsla.'],
             ['Investigations',
              u'minskat hemoglobin, minskat antal trombocyter, \xf6kat blodamylas, \xf6kat alkaliskt fosfatas i blod, \xf6kat gamma-glutamyltransferas, \xf6kat blodkreatininfosfokinas, viktnedg\xe5ng, vikt\xf6kning.']]],
           ['Uncommon',
            [['Infections',
              u'lunginflammation, urinv\xe4gsinfektion, gastroenterit, bronkit, herpes simplex, candidainfektion (inkluderande oral candidainfektion).'],
             ['Blood', u'trombocytemi, leukocytos, eosinofili.'],
             ['Endocrine', u'hypertyreos, hypotyreos.'],
             ['Metabolism', u'dehydrering, \xf6kad aptit, gikt.'],
             ['Nervous system',
              u'intrakraniell bl\xf6dning, migr\xe4n, medvetandef\xf6rlust (inklusive synkope), tremor, uppm\xe4rksamhetsst\xf6rning, hyperestesi.'],
             ['Eye',
              u'synneds\xe4ttning, dimsyn, konjunktival bl\xf6dning, reducerad synsk\xe4rpa, \xf6gonlocks\xf6dem, fotopsi, hyperemi (skleral, konjunktival, okul\xe4r), \xf6gonirritation.'],
             ['Cardiac',
              u'hj\xe4rtsvikt, perikardiell utgjutning, koronarart\xe4rsjukdom, hj\xe4rtbl\xe5sljud, cyanos.'],
             ['Vascular', u'hypertensiv kris, periferal arteriell ocklusiv sjukdom, hematom.'],
             ['Respiratory',
              u'lung\xf6dem, pleurautgjutning, interstitiell lungsjukdom, pleurasm\xe4rta, pleurit, ont i svalg/strupe, halsirritation.'],
             ['GI',
              u'gastrointestinal bl\xf6dning, melena, muns\xe5r, gastroesofagal reflux, stomatit, esofagal sm\xe4rta, muntorrhet k\xe4nslighet i t\xe4nderna.'],
             ['Hepato', u'hepatotoxicitet, toxisk hepatit, gulsot.'],
             ['Skin',
              u'exfoliativt utslag, l\xe4kemedelsutslag, hudsm\xe4rta, ekkymos, ansiktssvullnad.'],
             ['Musculoskeletal', u'muskuloskeletal stelhet, muskelsvaghet, svullna leder.'],
             ['Renal', u'dysuri, urintr\xe4ngningar, nykturi.'],
             ['Reproductive system', u'ont i br\xf6sten, gynekomasti, erektil dysfunktion.'],
             ['General',
              u'ansikts\xf6dem, gravitations\xf6dem, influensaliknande sjukdom, frossa, k\xe4nsla av kroppstemperaturf\xf6r\xe4ndringar (inkluderande v\xe4rmek\xe4nsla, k\xf6ldk\xe4nsla).'],
             ['Investigations',
              u'minskat antal neutrofiler, \xf6kat blodlaktathydrogenas, minskat blodglukos, \xf6kat blodurea, minskat antal globuliner.']]],
           ['Unknown',
            [['Metabolism', u'Minskad aptit* Vanliga 4 0Vanliga 8 <1 <1 0'],
             ['Nervous system', u'Huvudv\xe4rk Mycket 15 1 Mycket 15 1 2 <1'],
             ['GI', u'Illam\xe5ende Mycket 14 <1 Mycket 20 <1 <1 <1'],
             ['Skin', u'Utslag Mycket 33 <1 Mycket 28 1 2 0'],
             ['Musculoskeletal', u'Myalgi Mycket 10 <1 Mycket 10 <1 <1 <1'],
             ['General', u'Tr\xf6tthet Mycket 11 0Mycket 17 1 1 <1'],
             ['Infections', u'sepsis, subkutan abscess, anal abscess, furunkel, tinea pedis.'],
             ['Neoplasms', u'oral papillom, paraproteinemi.'],
             ['Immune system', u'\xf6verk\xe4nslighet.'],
             ['Endocrine', u'sekund\xe4r hyperparatyreoidism, tyreoidit.'],
             ['Metabolism', u'hyperurikemi, gikt, hypoglykemi, dyslipidemi.'],
             ['Psychiatric', u'desorientering, f\xf6rvirringstillst\xe5nd, amnesi, dysfori.'],
             ['Nervous system',
              u'hj\xe4rn\xf6dem, opticusneurit, letargi, dysestesi, restless legs.'],
             ['Eye',
              u'papill\xf6dem, korioretinopati, diplopi, fotofobi, \xf6gonsvullnad, blefarit, \xf6gonsm\xe4rta, allergisk konjunktivit, sjukdom p\xe5 \xf6gonytan.'],
             ['Ear', u'f\xf6rs\xe4mrad h\xf6rsel, \xf6ronsm\xe4rta, tinnitus.'],
             ['Cardiac',
              u'hj\xe4rtinfarkt, ventrikul\xe4r dysfunktion, perikardit, minskad ejektionsfraktion.'],
             ['Vascular', u'hemorragisk chock, hypotoni, trombos arteriell skleros.'],
             ['Respiratory',
              u'pulmonell hypertension, v\xe4sande andning sm\xe4rta i (mun)svalget.'],
             ['GI',
              u'gastrointestinalt s\xe5r med perforation, retroperitoneal bl\xf6dning, hematemes, mags\xe5r, ulcer\xf6s esofagit, subileus, gastrit, enterokolit, hemorrojder, hiatus hernia, rektal bl\xf6dning, gingivit.'],
             ['Hepato', u'kolestas, hepatomegali.'],
             ['Skin',
              u'erythema multiforme, erytema nodosum, huds\xe5r, palmar-plantar erytrodysestesi syndrom, petekier, ljusk\xe4nslighet, bl\xe5sor, hudcystor, sebaceus hyperplasi, hudatrofi, hudmissf\xe4rgning, hudexfoliation, hudhyperpigmentering, hudhypertrofi, hyperkeratos, psoriasis.'],
             ['Musculoskeletal', u'artrit.'],
             ['Renal', u'njursvikt, hematuri, urininkontinens, kromaturi.'],
             ['Reproductive system',
              u'br\xf6stinduration, menorragi, svullna br\xf6stv\xe5rtor.'],
             ['General', u'lokaliserat \xf6dem.'],
             ['Investigations',
              u'\xf6kat troponin, \xf6kat okonjugerat blodbilirubin, \xf6kat blodinsulin, minskat blodinsulin, minskat insulin C-peptid, f\xf6rh\xf6jt lipoprotein (inkluderande VLDL och HDL), \xf6kat blodparatyreoideahormon, \xf6kat blodkalium, minskat antal vita blodkroppar. Kliniskt relevanta eller allvarliga avvikelser fr\xe5n rutinv\xe4rdena vid hematologiska eller biokemiska laboratorietester framg\xe5r av Tabell 3.']]]],
 '_pages': [7, 12],
 u'_rank': 73,
 u'_type': u'LSFU'}