{'_data': [['Very common', [['Infections', u'Psykiska st\xf6rningar  ']]],
           ['Common',
            [['Nervous system',
              u'Hypokinesi Blodk\xe4rl Mycket vanliga Ortostatiska besv\xe4r'],
             ['Nervous system',
              u'Synkope 7 Organsystem Frekvens Biverkningar Andningsv\xe4gar br\xf6stkorg och mediastinum Vanliga Influensa Magtarmkanalen Mycket vanliga Illam\xe5ende Anorexi Diarr\xe9'],
             ['Nervous system',
              u'Kr\xe4kningar F\xf6rstoppning Muntorrhet Buksm\xe4rta Dyspepsi Hud och subkutan v\xe4vnad Vanliga \xd6kad transpiration Njurar och urinv\xe4gar Vanliga Missf\xe4rgad urin Allm\xe4nna symtom och/eller symtom vid Vanliga Br\xf6stsm\xe4rta administreringsst\xe4llet F\xf6rh\xf6jda ALAT-niv\xe5er till mer \xe4n tre g\xe5nger \xf6ver den \xf6vre normalgr\xe4nsen f\xf6rekom hos 1% av de patienter som fick 100 mg Tasmar tre g\xe5nger dagligen, och hos 3% av de patienter som fick 200 mg tre g\xe5nger dagligen. F\xf6rh\xf6jda niv\xe5er var ungef\xe4r dubbelt s\xe5 vanligt hos kvinnor. Denna \xf6kning upptr\xe4dde vanligtvis inom 6 till 12 veckor efter p\xe5b\xf6rjad behandling och var inte f\xf6rknippad med n\xe5gra kliniska statusfynd eller symtom. Hos ungef\xe4r h\xe4lften av dessa patienter \xe5tergick transaminasv\xe4rdena spontant till de ursprungliga niv\xe5erna under fortsatt behandling med Tasmar. Hos de \xf6vriga patienterna \xe5tergick transaminasv\xe4rderna till ursprungsniv\xe5erna efter avslutad behandling.']]],
           ['Rare',
            [['Nervous system',
              u'fall av sv\xe5r hepatocellul\xe4r skada som lett till d\xf6dsfall har rapporterats efter marknadsintroduktionen (se avsnitt 4.4). Enstaka patientfall med symtom som tyder p\xe5 malignt neuroleptikasyndrom (se avsnitt 4.4) har rapporterats efter minskning eller avbrytande av Tasmarbehandling och efter introduktion av Tasmar, n\xe4r detta \xe5tf\xf6ljdes av en signifikant dosreduktion av andra samtidigt administrerade dopaminerga l\xe4kemedel. Rabdomyolys, sekund\xe4rt till NMS eller sv\xe5r dyskinesi, har \xe4ven observerats. Missf\xe4rgning av urinen: Tolkapon och dess metaboliter \xe4r gula och kan f\xf6rorsaka en ofarlig intensifiering av f\xe4rgen p\xe5 patientens urin. Impulskontrollst\xf6rning: Patologiskt spelberoende, \xf6kad libido, hypersexualitet, tv\xe5ngsm\xe4ssiga utgifter eller k\xf6p, hets\xe4tning och tv\xe5ngsm\xe4ssigt \xe4tande kan f\xf6rekomma hos patienter som behandlas med dopamin agonister och/eller andra dopaminerga behandlingar s\xe5som Tasmar i samband med levodopa behandling (se avsnitt 4.4).']]],
           ['Unknown', [['Nervous system', u'Dystoni Huvudv\xe4rk Yrsel']]]],
 '_pages': [6, 7],
 u'_rank': 6,
 u'_type': u'LSFU'}