{'_data': [['Very common',
            [['Nervous system', u'Yrsel, ataxi, tr\xf6tthet'],
             ['GI', u'Kr\xe4kningar, illam\xe5ende'],
             ['Hepato', u'F\xf6rh\xf6jt gamma-GT']]],
           ['Common',
            [['Blood', u'Leukopeni, trombocytopeni, eosinofili'],
             ['Metabolism', u'Hyponatremi (v\xe4tskeretention)'],
             ['Eye', u'Ackommodationssv\xe5righeter, diplopi'],
             ['GI', u'Aptitl\xf6shet, muntorrhet'],
             ['Hepato',
              u'H\xf6jning av alkaliska fosfataser i blodet, f\xf6rh\xf6jda transaminaser'],
             ['Skin', u'Hudutslag, urtikaria']]],
           ['Uncommon',
            [['Blood', u'Leukocytos'],
             ['Nervous system',
              u'Huvudv\xe4rk, ofrivilliga r\xf6relser (tremor, dystonier, tics), orofacial dyskinesi, nystagmus'],
             ['GI', u'Diarr\xe9, obstipation']]],
           ['Rare',
            [['Blood',
              u'Agranulocytos, folsyrebrist, aplastisk anemi, pancytopeni, megaloblastisk anemi, retikulocytos'],
             ['Immune system',
              u'F\xf6rdr\xf6jd \xf6verk\xe4nslighetsreaktion som innefattar flera organ med hudrodnad, vaskulit, lymfadenopati, st\xf6rningar vilka efterliknar lymfom, artralgi, leukopeni, eosinofili, hepato-splenomegali, onormala leverv\xe4rden och destruktion av intrahepatiska gallv\xe4gar. Dessa kan intr\xe4ffa i olika kombinationer, ocks\xe5 andra organ kan p\xe5verkas t ex njurar, bukspottk\xf6rtel, myokardiet samt kolon. SLE-liknande syndrom'],
             ['Endocrine',
              u'Gynekomasti, galaktorr\xe9, osteomalaci efter l\xe5ngvarig behandling beroende p\xe5 \xf6kad nedbrytning av vitamin D genom enzyminduktion'],
             ['Metabolism',
              u'Vattenintoxikation (SIADH), laborationsm\xe4ssig bild som vid hypotyreos'],
             ['Psychiatric',
              u'Konfusion och aktivering av psykotiska symtom, agitation, oro, rastl\xf6shet, aggressivitet, depression, hallucinationer'],
             ['Nervous system',
              u'Dysartri, \xf6gonmotilitetsst\xf6rning, perifera neuropatier, parestesier, muskelsvaghet, aseptisk meningit'],
             ['Eye', u'Linsgrumling, konjunktivit'],
             ['Ear', u'Tinnitus, hyperakusi'],
             ['Cardiac',
              u'H\xf6jning och s\xe4nkning av blodtrycket, hj\xe4rtp\xe5verkan (bradykardi, AV-block), hj\xe4rtsvikt, f\xf6rv\xe4rrad koronarischemi, tromboflebit, tromboemboliska komplikationer (t ex lungembolism) Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['Cardiac', u'Pulmonella \xf6verk\xe4nslighetsreaktioner'],
             ['GI', u'Smakst\xf6rning, buksm\xe4rtor, glossit, stomatit'],
             ['Hepato',
              u'Hepatit, akut intermittent porfyri, destruktion av intrahepatiska gallv\xe4gar'],
             ['Skin',
              u'Fotosensibilitet, erythema multiforme, erythema nodosum, h\xe5ravfall, hirsutism, f\xf6r\xe4ndrad hudpigmentering, kl\xe5da, acne, purpura, svettningar, exfoliativ dermatit och erytrodermi'],
             ['Skin', u'Muskelv\xe4rk, ledv\xe4rk, muskelkramper'],
             ['Renal',
              u'Proteinuri, kreatininstegring, interstitiell nefrit, njurinsufficiens, hematuri, oliguri, pollakisuri, urinretention'],
             ['Reproductive system', u'Sexuell funktionsneds\xe4ttning'],
             ['Reproductive system', u'Feber']]],
           ['Very rare',
            [['Blood', u'R\xf6d blodkroppsaplasi Anemi'],
             ['Endocrine',
              u'\xd6kning av prolaktin i blodet med eller utan kliniska manifestationer, f\xf6rh\xf6jda niv\xe5er av kolesterol i blodet, inkluderande HDL-kolesterol samt triglycerider'],
             ['Nervous system', u'Malignt neuroleptikasyndrom'],
             ['Ear', u'Hypoakusi, f\xf6r\xe4ndrad tonuppfattning'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Leversvikt Porfyria variegata, porfyria cutanea tarda'],
             ['Skin',
              u'Angioneurotiskt \xf6dem, allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs), Stevens-Johnsons syndrom*, toxisk epidermal nekrolys (TEN) (se 4.4) Muskuloskeletala systemet och bindv\xe4v'],
             ['Reproductive system',
              u'Anafylaktisk reaktion * \xc4ven rapporterat som s\xe4llsynt i vissa asiatiska l\xe4nder. Se \xe4ven avsnitt 4.4 Varningar och f\xf6rsiktighet. M\xe5ttlig minskning av antalet leukocyter eller trombocyter \xe4r vanligt f\xf6rekommande men oftast \xf6verg\xe5ende, och beror mestadels inte p\xe5 n\xe5gon allvarlig benm\xe4rgsp\xe5verkan. Det har kommit rapporter om s\xe4nkning av benmineraldensitet, osteopeni, osteoporos och frakturer hos patienter som st\xe5r p\xe5 l\xe5ngtidsbehandling med Tegretol. Mekanismen, genom vilken Tegretol p\xe5verkar benmetabolismen, har inte identifierats. Biverkningar fr\xe5n spontana rapporter och fall beskrivna i litteraturen (ingen k\xe4nd frekvens) F\xf6ljande biverkningar har inkommit efter lansering av Tegretol via spontana fallrapporter och litteraturfall. Eftersom dessa biverkningar har rapporteras frivilligt fr\xe5n en population av ok\xe4nd storlek \xe4r det inte m\xf6jligt att ber\xe4kna frekvensen p\xe5 ett tillf\xf6rlitligt s\xe4tt varf\xf6r den klassificeras som ingen k\xe4nd frekvens. Biverkningarna anges utifr\xe5n organsystemklass och frekvenskategori enligt MedDRA. Inom varje organsystemklass presenteras biverkningarna i fallande allvarlighetsgrad.']]],
           ['Unknown',
            [['Immune system', u'Hypogammaglobulinemi'],
             ['Endocrine',
              u'Osteoporos efter l\xe5ngvarig behandling beroende p\xe5 \xf6kad nedbrytning av vitamin D genom enzyminduktion'],
             ['Eye', u'\xd6kat intraokul\xe4rt tryck'],
             ['Reproductive system',
              u'St\xf6rning av spermatogenesen (med minskat antal spermier och/eller minskad spermier\xf6rlighet) Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Immune system',
              u'L\xe4kemedelsrelaterade utslag med eosinofili och systemiska symptom (DRESS)'],
             ['Skin', u'Akut generaliserad exantemat\xf6s pustulos (AGEP)']]]],
 '_pages': [10, 13],
 u'_rank': 43,
 u'_type': u'LSFU'}