{'_data': [['Uncommon',
            [['Infections',
              u'a: \xd6vre luftv\xe4gsinfektioner inklusive faryngit och sinuit, urinv\xe4gsinfektioner inklusive cystit'],
             ['Blood', u'Anemi'],
             ['Metabolism', u'Hyperkalemi'],
             ['Psychiatric', u'Depression, s\xf6mnl\xf6shet'],
             ['Nervous system', u'Synkope'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Hypotoni , ortostatisk hypotoni'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Magsm\xe4rta, diarr\xe9, dyspepsi, uppk\xf6rdhet, kr\xe4kningar'],
             ['Skin', u'Hyperhidros, pruritus, hudutslag'],
             ['Musculoskeletal', u'Myalgi, ryggsm\xe4rtor (t ex sciatica), muskelkramp'],
             ['Renal', u'Nedsatt njurfunktion inklusive akut njursvikt'],
             ['General', u'Br\xf6stsm\xe4rtor, asteni (svaghet)'],
             ['Investigations', u'\xd6kat kreatinin i blod']]],
           ['Rare',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet,'],
             ['Psychiatric', u'\xc5ngest'],
             ['Eye', u'Synst\xf6rningar'],
             ['Cardiac', u'Takykardi'],
             ['GI', u'Orolig mage, muntorrhet'],
             ['Hepato', u'Avvikande leverfunktion/leversjukdom'],
             ['Skin',
              u'Erythem, angio\xf6dem, hudutslag pga l\xe4kemedel, toxiska hudutslag, eksem'],
             ['Musculoskeletal', u'Artralgi, sm\xe4rta i extremiteterna'],
             ['General', u'Influensaliknande sjukdom'],
             ['Investigations',
              u'\xd6kad urinsyra i blod; \xf6kade leverenzymer, \xf6kat kreatinfosfokinas i blod, minskat hemoglobin I PRoFESS-studien observerades en f\xf6rh\xf6jd incidens sepsis med telmisartan j\xe4mf\xf6rt med placebo. Dessa biverkningar kan vara en tillf\xe4llighet eller ha samband med en mekanism som f\xf6r n\xe4rvarande inte \xe4r k\xe4nd (se avsnitt 5.1). Rapporterades som vanligt f\xf6rekommande hos patienter med kontrollerat blodtryck som behandlades med telmisartan f\xf6r reduktion av kardiovaskul\xe4r morbiditet som till\xe4gg till standardbehandling.']]],
           ['Unknown',
            [['Infections', u'Sepsis \xe4ven med fatal utg\xe5ng'],
             ['Blood', u'Eosinofili'],
             ['Immune system', u'Anafylaktisk reaktion'],
             ['Skin', u'Urtikaria'],
             ['Musculoskeletal', u'Sm\xe4rta i senor (symtom som liknar seninflammation)']]]],
 '_pages': [6, 7],
 u'_rank': 31,
 u'_type': u'LSFU'}