{'_data': [['Very common',
            [['Metabolism', u'Anorexi'],
             ['Nervous system', u'Yrsel'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['GI', u'Diarr\xe9'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Kr\xe4kning'],
             ['General', u'Fall']]],
           ['Common',
            [['Psychiatric', u'Agitation'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Psychiatric', u'Oro'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'S\xf6mnighet'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['Skin', u'Hyperhidros'],
             ['General', u'Tr\xf6tthet och asteni'],
             ['General', u'Olustk\xe4nsla'],
             ['Investigations',
<<<<<<< HEAD
              u'Viktminskning F\xf6ljande ytterligare biverkningar har observerats med rivastigmin depotpl\xe5ster: delirium, pyrexi (vanliga).'],
=======
              u'Viktminskning F\xf6ljande ytterligare biverkningar har observerats med rivastigmin depotpl\xe5ster: delirium, pyrexi (vanliga). Tabell 2 visar biverkningar som rapporterats under kliniska pr\xf6vningar som utf\xf6rts med Parkinson-patienter med demens som behandlats med rivastigmin kapslar Tabell 2'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Metabolism', u'Minskad aptit'],
             ['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Insomni'],
             ['Psychiatric', u'Oro'],
             ['Psychiatric', u'Rastl\xf6shet'],
             ['Psychiatric', u'Hallucination, visuell'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'S\xf6mnighet'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'F\xf6rs\xe4mring av Parkinsons sjukdom'],
             ['Nervous system', u'Bradykinesi'],
             ['Nervous system', u'Dyskinesi'],
             ['Nervous system', u'Hypokinesi'],
             ['Nervous system', u'Kugghjulsstelhet'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Diarr\xe9'],
             ['GI', u'Buksm\xe4rtor och dyspepsi'],
             ['GI', u'\xd6kad salivation'],
             ['Skin', u'Hyperhidros'],
             ['General', u'Tr\xf6tthet och asteni'],
             ['General', u'G\xe5ngrubbning'],
             ['General',
<<<<<<< HEAD
              u'Parkinsonliknande g\xe5ng F\xf6ljande ytterligare biverkningar har observerats i en studie med patienter med Parkinson-patienter med demens som behandlats med rivastigmin depotpl\xe5ster: agitation, depression (vanliga).']]],
=======
              u'Parkinsonliknande g\xe5ng F\xf6ljande ytterligare biverkningar har observerats i en studie med patienter med Parkinson patienter med demens som behandlats med rivastigmin depotpl\xe5ster: agitation, depression (vanliga). Tabell 3 visar antal och procentandel av patienterna i en specifik 24-veckors klinisk studie, som utf\xf6rts med rivastigmin hos patienter med demens vid Parkinsons sjukdom, med predefinierade biverkningar vilka kan t\xe4nkas spegla f\xf6rs\xe4mring av parkinsonsymtom Tabell 3 Predefinierade biverkningar som kan t\xe4nkas spegla rivastigmin Placebo f\xf6rs\xe4mring av parkinsonsymtom hos patienter med n (%) n (%) demens vid Parkinsons sjukdom Totala antalet unders\xf6kta patienter 362 (100) 179 (100) Totala antalet unders\xf6kta patienter med predefinierade 99 (27,3) 28 (15,6) biverkningar Tremor 37 (10,2) 7 (3,9) Fall 21 (5,8) 11 (6,1) Parkinsons sjukdom (f\xf6rs\xe4mring) 12 (3,3) 2 (1,1) \xd6kad salivation 5 (1,4) 0 Dyskinesi 5 (1,4) 1 (0,6) Parkinsonism 8 (2,2) 1 (0,6) Hypokinesi 1 (0,3) 0 R\xf6relserubbning 1 (0,3) 0 Bradykinesi 9 (2,5) 3 (1,7) Dystoni 3 (0,8) 1 (0,6) Onormal g\xe5ng 5 (1,4) 0 Muskelstelhet 1 (0,3) 0 Balanssv\xe5righeter 3 (0,8) 2 (1,1) Muskuloskeletal stelhet 3 (0,8) 0 Rigor 1 (0,3) 0 Motorisk dysfunktion 1 (0,3) 0']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon',
            [['Psychiatric', u'Insomni'],
             ['Psychiatric', u'Depression'],
             ['Nervous system', u'Synkope'],
             ['Hepato', u'F\xf6rh\xf6jda leverfunktionsv\xe4rden'],
             ['General', u'Fall'],
             ['Nervous system', u'Dystoni'],
             ['Cardiac', u'F\xf6rmaksflimmer'],
             ['Cardiac', u'Atrioventrikul\xe4r-block'],
             ['Vascular', u'Hypotension']]],
           ['Rare',
            [['Nervous system', u'Krampanfall'],
             ['Cardiac', u'Angina pectoris'],
             ['GI', u'Mags\xe5r och duodenals\xe5r'],
             ['Skin', u'Hudutslag']]],
           ['Very rare',
            [['Infections', u'Urinv\xe4gsinfektion'],
<<<<<<< HEAD
             ['Psychiatric', u'Hallucinationer'],
=======
             ['Psychiatric', u'Hallucinationer Aggression, rastl\xf6shet'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Nervous system',
              u'Extrapyramidala symtom (inklusive f\xf6rs\xe4mring av Parkinsons sjukdom)'],
             ['Cardiac',
              u'Hj\xe4rtarytmier (t.ex. bradykardi, atrioventrikul\xe4ra block, f\xf6rmaksflimmer och takykardi)'],
             ['Vascular', u'Hypertoni'],
             ['GI', u'Gastrointestinala bl\xf6dningar'],
<<<<<<< HEAD
             ['GI', u'Pankreatit']]],
           ['Unknown',
            [['Metabolism', u'Dehydrering'],
             ['Psychiatric', u'Aggression, rastl\xf6shet'],
             ['Cardiac', u'Sjuk sinusknuta (sick sinus syndrome)'],
             ['GI',
              u'Vissa fall av sv\xe5r kr\xe4kning har f\xf6rknippats med esofageal ruptur (se avsnitt 4,4).'],
=======
             ['GI',
              u'Pankreatit Vissa fall av sv\xe5r kr\xe4kning har f\xf6rknippats med esofageal ruptur (se avsnitt 4,4).']]],
           ['Unknown',
            [['Metabolism', u'Dehydrering'],
             ['Cardiac', u'Sjuk sinusknuta (sick sinus syndrome)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Hepato', u'Hepatit'],
             ['Skin', u'Pruritus'],
             ['Psychiatric', u'Aggression'],
             ['Cardiac', u'Sjuk sinusknuta (sick sinus syndrome)'],
             ['Hepato', u'Hepatit']]]],
 '_pages': [5, 8],
<<<<<<< HEAD
 u'_rank': 73,
=======
 u'_rank': 71,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'LSFU'}