{'_data': [['Very common', [['Local', u')']]],
           ['Common', [['Skin', u'Hudflagning, kl\xe5da']]],
           ['Uncommon',
            [['Skin',
              u'Hudlesioner, s\xe5rskorpor, hudf\xf6r\xe4ndringar, pigmentf\xf6r\xe4ndringar, erytem, br\xe4nnande k\xe4nsla i huden'],
             ['Skin',
              u'Sm\xe4rta, sm\xe4rta vid applikationsst\xe4llet, irritation vid applikationsst\xe4llet']]],
           ['Rare',
            [['Local', u')'],
             ['Eye', u'\xd6gonirritation'],
             ['Skin', u'Torr hud, kontaktdermatit, eksem'],
             ['Skin', u'F\xf6rv\xe4rrad svampinfektion']]],
           ['Unknown',
            [['Local',
              u'huden, erytem och s\xe5rskorpor kan upptr\xe4da p\xe5 applikationsst\xe4llet. Dessa symtom ska s\xe4rskiljas fr\xe5n \xf6verk\xe4nslighetsreaktioner, inklusive utslag, som rapporterats i enstaka fall och som kr\xe4ver uts\xe4ttande av behandlingen. Vid oavsiktlig kontakt med \xf6gonen kan terbinafin vara irriterande f\xf6r \xf6gonen. I s\xe4llsynta fall kan en underliggande svampinfektion f\xf6rv\xe4rras. Inom varje frekvensgrupp presenteras biverkningarna efter minskande allvarlighetsgrad.'],
             ['Immune system', u'Hypersensibilitet*'],
             ['Skin', u'Utslag* Allm\xe4nna symtom och/eller vid administrationsst\xe4llet']]]],
 '_pages': [3, 3],
 u'_rank': 11,
 u'_type': u'LSFU'}