{'_data': [['Common',
            [['Skin',
              u'Icke allvarliga former av allergiska hudreaktioner (utslag, urtikaria).'],
             ['GI',
              u'M\xe4ttnadsk\xe4nsla, aptitf\xf6rlust, dyspepsi, illam\xe5ende, lindrig buksm\xe4rta, diarr\xe9.'],
             ['Musculoskeletal', u'Muskuloskeletala reaktioner (artralgi, myalgi).'],
             ['Nervous system', u'huvudv\xe4rk.']]],
           ['Uncommon',
            [['Nervous system',
              u'Smakf\xf6r\xe4ndringar, inklusive f\xf6rlust av smaksinnet, som vanligen kommer tillbaka inom ett antal veckor efter l\xe4kemedlets uts\xe4ttande. Enstaka fall av l\xe5ngvariga smakf\xf6r\xe4ndringar har rapporterats. Minskat f\xf6dointag som lett till betydande viktminskning har observerats i ett litet f\xe5tal, allvarliga fall.']]],
           ['Rare',
            [['Skin', u'Fotosensitivitet.'],
             ['Nervous system', u'Parestesi, hypestesi och yrsel.'],
             ['Hepato',
              u'Hepatobili\xe4r dysfunktion och idiosynkratisk akut hepatit (prim\xe4rt av kolestatisk natur) har observerats i samband med terbinafintabletter, inklusive mycket s\xe4llsynta fall av allvarlig leversvikt med d\xf6dlig utg\xe5ng (se avsnitt 4.4).']]],
           ['Very rare',
            [['Skin',
              u'Allvarliga hudreaktioner (t.ex. Stevens-Johnsons syndrom, toxisk epidermal nekrolys). Behandling med terbinafintabletter ska avbrytas om progressivt hudutslag uppst\xe5r. Exacerbation av psoriasis.'],
             ['Nervous system', u'Svindel.'],
             ['Psychiatric', u'Depression och \xe5ngest.'],
             ['Hepato', u'Grav leversvikt.'],
             ['Immune system',
              u'Anafylaktoida reaktioner (inklusive angio\xf6dem), manifestation och exacerbation av kutan och systemisk lupus erythematosus.'],
             ['Blood',
              u'Enstaka fall av hematologiska rubbningar, s\xe5 som neutropeni, agranulocytos och trombocytopeni, har rapporterats.'],
             ['General', u'Tr\xf6tthet.']]]],
 '_pages': [4, 5],
 u'_rank': 15,
 u'_type': u'LSFU'}