{'_data': [['Very common',
            [['Metabolism', u'\u2212Anorexi (\xe4tst\xf6rningar)'],
             ['Psychiatric', u'\u2212Nervositet (irritabilitet) \u2212Onormalt gr\xe5tande'],
             ['Nervous system', u'\u2212Somnolens (d\xe5sighet) \u2212Huvudv\xe4rk'],
             ['GI', u'\u2212Kr\xe4kningar'],
             ['Musculoskeletal', u'\u2212Myalgi'],
             ['General',
              u'\u2212Rodnad vid injektionsst\xe4llet \u2212Sm\xe4rta vid injektionsst\xe4llet \u2212Svullnad vid injektionsst\xe4llet \u2212Pyrexi (feber) > 38 C \u2212Sjukdomsk\xe4nsla']]],
           ['Common',
            [['Psychiatric', u'\u2212Insomni (s\xf6mnst\xf6rningar)'],
             ['GI', u'\u2212Diarr\xe9'],
             ['General', u'\u2212F\xf6rh\xe5rdnad vid injektionsst\xe4llet']]],
           ['Uncommon',
            [['Psychiatric', u'\u2212Ih\xe5llande, otr\xf6stligt gr\xe5tande'],
             ['General',
              u'\u2212Rodnad och svullnad > 5 cm p\xe5 injektionsst\xe4llet \u2212Pyrexi (feber) > 39 C']]],
           ['Rare', [['General', u'\u2212Pyrexi > 40 C (h\xf6g feber)']]],
           ['Unknown',
            [['Immune system',
              u's: \u2212Anafylaktiska reaktioner s\xe5som ansikts\xf6dem, Quincke\xf6dem.'],
             ['Nervous system', u'\u2212Kramper med eller utan feber \u2212Synkope.'],
             ['Skin',
              u'\u2212Allergiliknande symptom s\xe5som olika typers hudutslag, erytem och urtikaria'],
             ['General',
              u'\u2212Kraftiga reaktioner vid injektionsst\xe4llet (>50 mm), inklusive omfattande svullnad i extremiteten fr\xe5n injektionsst\xe4llet som str\xe4cker sig \xf6ver ena eller b\xe5da lederna, har rapporterats hos barn. Dessa reaktioner b\xf6rjar inom 24\u201372 timmar efter vaccinationen, kan vara associerade med erytem, v\xe4rme, \xf6mhet eller sm\xe4rta vid injektionsst\xe4llet, och g\xe5r spontant \xf6ver inom 3\u20135 dagar. Risken f\xf6refaller vara beroende av antalet f\xf6reg\xe5ende doser av vaccin som inneh\xe5ller acellul\xe4rt pertussisantigen, med en st\xf6rre risk efter den 4:e och 5:e dosen. Hypotoniska-hyporesponsiva episoder har inte rapporterats efter vaccinering med Tetravac under kliniska studier men har rapporterats f\xf6r andra kikhostevacciner. \xd6demat\xf6sa reaktioner i det ena eller b\xe5da benen kan uppkomma efter vaccination med vacciner som inneh\xe5ller Haemophilus influenzae typ b. Om denna reaktion uppkommer sker den huvudsakligen efter prim\xe4ra injektioner och observeras inom de f\xf6rsta timmarna efter vaccination. Associerade symtom kan innefatta cyanos, rodnad, \xf6verg\xe5ende purpura och h\xe4ftig gr\xe5t. Alla reaktioner g\xe5r \xf6ver spontant utan sequela inom 24 timmar. Ett s\xe5dant fall har rapporterats vid kliniska pr\xf6vningar utf\xf6rda med difteri-stelkramp-acellul\xe4rt pertussis-poliomyelitis-vaccin Tetravac administrerat samtidigt med konjugerat Haemophilus influenzae typ b-vaccin p\xe5 tv\xe5 separata injektionsst\xe4llen. N\xe4r Tetravac \xe4r indikerat f\xf6r administrering till barn fr\xe5n 5 till 12 \xe5rs \xe5lder som en sen boosterdos, \xe4r reaktioner mot Tetravac hos barn i denna \xe5ldersgrupp mindre eller lika frekvent rapporterade som efter administrering av DTP-IPV (helcells-pertussis) respektive DT-IPV, vid samma \xe5lder. Det har f\xf6rekommit mycket s\xe4llsynta fall av brakial neurit och Guillain-Barr\xe9s syndrom efter administrering av andra vacciner inneh\xe5llandes tetanustoxoider. Ytterligare information om speciella populationer: Apn\xe9 hos mycket prematura sp\xe4dbarn (\u2264 28 graviditetsveckor) (se avsnitt 4.4)']]]],
 '_pages': [4, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}