{'_data': [['Common',
            [['GI', u'Illam\xe5ende, buksm\xe4rta, diarr\xe9'],
             ['Nervous system', u'Huvudv\xe4rk']]],
           ['Unknown',
            [['Blood', u'Neutropeni, trombocytopeni'],
             ['Eye', u'Synst\xf6rningar'],
             ['GI',
              u'Glossit, enterokolit, kr\xe4kningar,  epigastralgi (sm\xe4rta i  maggropen)'],
             ['General', u'Pyrexi'],
             ['Hepato', u'Gulsot'],
             ['Immune system',
              u'\xd6verk\xe4nslighet, urticaria,  angioneurotiskt \xf6dem,  anafylaktisk reaktion'],
             ['Investigations',
              u'F\xf6rh\xf6jda v\xe4rden p\xe5  transaminaser, f\xf6rh\xf6jda v\xe4rden  p\xe5 alkaliska fosfataser och  bilirubin i blodet'],
             ['Nervous system', u'Yrsel, intrakraniell  hypertension*'],
             ['Skin',
              u'Erytemat\xf6sa utslag,  ljusk\xe4nslighetsreaktioner,  kl\xe5da, Stevens Johnsons  syndrom']]]],
 '_pages': [2, 4],
 u'_rank': 11,
 u'_type': u'TSFU'}