{'_data': [['Very common',
            [['Metabolism',
              u'F\xf6rh\xf6jt alkalisk fosfatas, f\xf6rh\xf6jt  LDH, f\xf6rh\xf6jd urinsyra'],
             ['GI', u'Illam\xe5ende/kr\xe4kningar'],
             ['Hepato', u'f\xf6rh\xf6jt GGT-v\xe4rde'],
             ['Musculoskeletal', u'Br\xf6stsm\xe4rta, muskel- och  skelettv\xe4rk'],
             ['Blood', u'Leukocytos, trombocytopeni'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Musculoskeletal', u'Muskel- och skelettv\xe4rk'],
             ['Blood', u'Anemi, splenomegali'],
             ['Metabolism',
              u'S\xe4nkt glukos, f\xf6rh\xf6jt alkalisk  fosfatas, f\xf6rh\xf6jt LDH, hyperurikemi'],
             ['Respiratory', u'N\xe4sbl\xf6dning'],
             ['Musculoskeletal', u'Muskel- och skelettv\xe4rk'],
             ['Musculoskeletal', u'Muskel- och skelettv\xe4rk']]],
           ['Common',
            [['Respiratory', u'Hosta, ont i halsen'],
             ['GI', u'F\xf6rstoppning, anorexi, diarr\xe9,  inflammation i slemhinnorna'],
             ['General', u'Tr\xf6tthet, allm\xe4n svaghet'],
             ['Metabolism', u'F\xf6rh\xf6jt alkalisk fosfatas, f\xf6rh\xf6jt  LDH'],
             ['Skin', u'Alopeci, kutan vaskulit, sm\xe4rta  vid injektionsst\xe4llet, utslag']]],
           ['Uncommon',
            [['General', u'Ospecifik sm\xe4rta'],
             ['Blood', u'Mj\xe4ltrubbning'],
             ['Metabolism', u'F\xf6rh\xf6jt ASAT, hyperurikemi'],
             ['Musculoskeletal', u'Exacerbation av reumatoid artrit'],
             ['General', u'Sv\xe5r allergisk reaktion'],
             ['Blood', u'Mj\xe4ltrubbning'],
             ['Renal', u'Hematuri, proteinuri']]],
           ['Very rare',
            [['Respiratory', u'Lunginfiltrat'],
             ['Skin', u'Sweets syndrom, kutan vaskulit'],
             ['Musculoskeletal', u'Exacerbation av reumatoid artrit'],
             ['Renal', u'P\xe5verkan p\xe5 urinv\xe4garna'],
             ['General', u'Allergisk reaktion']]]],
 '_pages': [9, 13],
 u'_rank': 29,
 u'_type': u'TSFU'}