{'_data': [['Very common',
            [['Blood', u'Neutropeni Leukopeni Anemi Lymfopeni Trombocytopeni'],
             ['Nervous system',
              u'Perifer neuropati* Tremor Yrsel Parestesi Dysestesi Somnolens'],
             ['GI', u'F\xf6rstoppning'],
             ['General', u'Perifert \xf6dem']]],
           ['Common',
            [['Infections', u'Lunginflammation'],
             ['Psychiatric', u'F\xf6rvirring Depression'],
             ['Nervous system', u'Onormal koordination'],
             ['Cardiac', u'Hj\xe4rtsvikt Bradykardi'],
             ['Vascular', u'Djup ventrombos*'],
             ['Respiratory',
              u'Lungemboli* Interstitiell lungsjukdom Bronkopneumopati Dyspn\xe9'],
             ['GI', u'Kr\xe4kningar Muntorrhet'],
             ['Skin', u'Toxiska hudutslag Utslag Torr hud'],
             ['General', u'Pyrexi Asteni Allm\xe4n sjukdomsk\xe4nsla']]]],
 '_pages': [9, 12],
 u'_rank': 13,
 u'_type': u'LSFU2'}