{'_data': [['Common',
            [['General', u' Tr\xf6tthet, huvudv\xe4rk, l\xe4tt yrsel.  '],
             ['GI', u' Muntorrhet.  '],
             ['Respiratory', u' N\xe4st\xe4ppa. ']]],
           ['Uncommon',
            [['GI', u' Obstipation.  '],
             ['Reproductive system', u' Urinretention.  '],
             ['Eye', u' Ackommodationsst\xf6rningar. ']]],
           ['Rare',
            [['General', u' Malignt neuroleptikasyndrom.  '],
             ['Blood', u' Agranulocytos, leukopeni.  '],
             ['Vascular',
              u' QT-f\xf6rl\xe4ngning, Torsade de Pointes, hj\xe4rtstillest\xe5nd, ventrikul\xe4ra arytmier -- ventrikelflimmer, ventrikeltakykardi, blodtrycksfall, takykardi. '],
             ['Hepato', u' Hepatit med ikterus av stastyp. '],
             ['Nervous system', u' Tardiv dyskinesi, parkinsonism, akatisi, akut dystoni. '],
             ['Eye', u' Lins- och corneagrumlingar (h\xf6gdos/l\xe5ngtidsbehandling). ']]]],
 '_pages': [3, 4],
 u'_rank': 12,
 u'_type': u'DFSU'}