{'_data': [['Rare',
            [['Blood',
              u' Trombocytrubbning, stamcellsrubbning,  -agranulocytos, leukopeni, trombocytopeni,  -hemolytisk anemi, pancytopeni '],
             ['Immune system', u' Allergier (ej angio\xf6dem)  '],
             ['Psychiatric', u' Depression NOS, f\xf6rvirring,  -hallucinationer '],
             ['Nervous system', u' Darrningar NOS, huvudv\xe4rk NOS  '],
             ['Eye', u' Synst\xf6rningar  '],
             ['Cardiac', u' \xd6dem  '],
             ['GI',
              u' Bl\xf6dning NOS, buksm\xe4rta NOS, diarr\xe9  -NOS, illam\xe5ende, kr\xe4kningar '],
             ['Hepato', u' Onormal leverfunktion, leversvikt,  -levernekros, gulsot. '],
             ['Skin', u' Pruritus, utslag, svettningar, purpura,  -angio\xf6dem, urtikaria. '],
             ['General', u' Yrsel (ej svindel), obehag, feber, sedation  ']]],
           ['Very rare',
            [['Respiratory', u' br\xf6stkorg och  Bronkospasm  mediastinum  -'],
             ['Hepato', u' Levertoxicitet  '],
             ['General',
              u' \xd6verk\xe4nslighetsreaktioner (som kr\xe4ver  -avbrytande av behandling) Metabolism  Hypoglykemi  '],
             ['Renal', u' Steril pyuri (grumlig urin) och p\xe5verkan  -p\xe5 njuren ']]]],
 '_pages': [4, 5],
 u'_rank': 14,
 u'_type': u'DFSU'}