{'_data': [['Very common',
            [['Endocrine', u'Hypotyroidism'],
             ['Eye',
              u'Siccasyndrom, endokrin oftalmopati, f\xf6rtr\xe4ngning av t\xe5rkanaler'],
             ['GI',
              u'\xd6verg\xe5ende eller ih\xe5llande sialadenit, inklusive muntorrhet, illam\xe5ende, kr\xe4kningar Skador, f\xf6rgiftning och andra komplikationer'],
             ['GI',
              u'Str\xe5lskada inklusive inflammatorisk thyreoidit, sm\xe4rta associerad med str\xe5lning, trakeal obstruktion Rubbningar i fortplantningssystem och br\xf6st']]],
           ['Uncommon', [['Neoplasms', u'Leukemi']]],
           ['Unknown',
            [['Neoplasms', u'Mags\xe4ckscancer, bl\xe5scancer och br\xf6stcancer'],
             ['Blood',
              u'Benm\xe4rgsdepression inklusive allvarlig trombocytopeni, erytrotrombocytopeni och/eller leukopeni'],
             ['Immune system', u'Hypersensitivitet'],
             ['Endocrine',
              u'F\xf6rsv\xe5rad hypotyreoidism, Graves sjukdom, hypoparatyroidism, hyperparatyroidism'],
             ['GI',
              u'Nedsatt fertilitet hos man och kvinna Medf\xf6dda, k\xe4nda och genetiska sjukdomar']]]],
 '_pages': [5, 7],
 u'_rank': 10,
 u'_type': u'LSFU'}