{'_data': [['Very common',
            [['Blood', u'Lymfopeni, neutropeni, trombocytopeni'],
             ['Infections',
              u'Infektion Benigna och maligna neoplasier och ospecificerad (inkl. cystor och polyper)'],
             ['General', u'Feber']]],
           ['Common',
            [['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Diarr\xe9, dysfagi, illam\xe5ende, kr\xe4kning'],
             ['Skin', u'Kl\xe5da, hudutslag'],
             ['Musculoskeletal', u'Myalgi'],
             ['Infections', u'Malignitet'],
             ['Vascular', u'Hypotoni'],
             ['General', u'Darrningar'],
             ['Immune system', u'Serumsjuka']]],
           ['Rare',
            [['Local',
              u'I s\xe4llsynta fall har maligniteter, inklusive men ej begr\xe4nsat till lymfoproliferativa tillst\xe5nd och andra lymfom (som kan orsakas av virus) s\xe5v\xe4l som solida tum\xf6rer rapporterats. Dessa tillst\xe5nd har ibland associerats med d\xf6dlig utg\xe5ng (se avsnitt 4.4). Dessa biverkningar s\xe5gs alltid i samband med att flera immunsuppressiva medel kombinerats. F\xf6r s\xe4kerhet avseende infekti\xf6sa agens, se avsnitt 4.4.']]],
           ['Unknown',
            [['Immune system', u'>1/10)'],
             ['Local',
              u'rapporterats. Biverkningar p\xe5 grund av immunsuppression Infektioner, reaktivering av infektion, febril neuropeni och sepsis har rapporterats efter administration av Thymoglobuline i kombination med flera andra immunsuppressiva medel. I']]]],
 '_pages': [5, 6],
 u'_rank': 14,
 u'_type': u'LSFU'}