{'_data': [['Very common', [['GI', u'illam\xe5ende']]],
           ['Common',
            [['Nervous system', u'yrsel, huvudv\xe4rk, parestesier'],
             ['GI', u'kr\xe4kning, diarr\xe9'],
             ['General', u'tr\xf6tthet, kraftl\xf6shet']]],
           ['Uncommon',
            [['Vascular', u'v\xe4rmek\xe4nsla'],
             ['Skin', u'urtikaria, utslag'],
             ['General', u'influensaliknande symtom, feber, stelhet, ryggv\xe4rk']]],
           ['Very rare',
            [['Investigations',
              u'fall av hypertyreoidism eller f\xf6rmaksflimmer har observerats n\xe4r Thyrogen 0,9 mg administrerats till patienter med antingen partiell eller fullst\xe4ndig sk\xf6ldk\xf6rtel. Manifestationer av \xf6verk\xe4nslighet har rapporterats i mindre vanliga fall b\xe5de under kliniska studier och efter godk\xe4nnandet f\xf6r f\xf6rs\xe4ljning. Dessa reaktioner bestod av urtikaria, utslag, kl\xe5da, vallningar samt tecken och symtom fr\xe5n andningsv\xe4garna. I kliniska pr\xf6vningar som omfattade 481 patienter har ingen patient utvecklat antikroppar mot tyreotropin alfa, varken efter enstaka eller upprepad begr\xe4nsad (27 patienter) anv\xe4ndning av produkten. Upptr\xe4dande av antikroppar som skulle kunna st\xf6ra endogena TSH-analyser kan inte uteslutas. F\xf6rstoring av kvarvarande tyreoideav\xe4vnad eller metastaser kan uppkomma efter behandling med Thyrogen. Det kan leda till akuta symtom, vilka beror p\xe5 var i anatomin v\xe4vnaden sitter. Exempelvis har hemiplegi, hemipares eller f\xf6rlust av synen f\xf6rekommit hos patienter med']]],
           ['Unknown',
            [['Neoplasms', u'tum\xf6rsvullnad, metastassm\xe4rta'],
             ['Nervous system', u'tremor, stroke'],
             ['Cardiac', u'hj\xe4rtklappning'],
             ['Vascular', u'v\xe4rmevallningar'],
             ['Respiratory', u'dyspn\xe9'],
             ['Skin', u'kl\xe5da, hyperhidros'],
             ['Musculoskeletal', u'artralgi, myalgi'],
             ['General',
              u'allm\xe4nt obehag, sm\xe4rta, kl\xe5da, utslag och urtikaria p\xe5 det intramuskul\xe4ra injektionsst\xe4llet'],
             ['Investigations', u's\xe4nkning av TSH Beskrivning av selekterade biverkningar']]]],
 '_pages': [4, 6],
 u'_rank': 17,
 u'_type': u'LSFU'}