{'_data': [['Common', [['Eye', u'\xd6verg\xe5ende dimsyn, br\xe4nnande k\xe4nsla och rodnad.']]],
           ['Uncommon',
            [['Nervous system', u'): Huvudv\xe4rk, yrsel.'],
             ['Eye',
              u'): Konjunktivit, keratit, k\xe4nsla av \u201dskr\xe4p\u201d i \xf6gat, torra \xf6gon.'],
             ['Respiratory',
              u'): Dyspn\xe9. F\xf6ljande ytterligare biverkningar har observerats f\xf6r \xf6gondroppar inneh\xe5llande betablockerare och kan uppst\xe5 vid anv\xe4ndning av Timosan']]],
           ['Rare', [['Eye', u'): Minskad korneal k\xe4nslighet.']]],
           ['Unknown',
            [['Systemic', u'generaliserade utslag, pruritus, anafylaktisk reaktion.'],
             ['Metabolism', u'Hypoglykemi.'],
             ['Psychiatric',
              u'Insomni, depression, mardr\xf6mmar, minnesf\xf6rlust, f\xf6rvirring.'],
             ['Nervous system',
              u'Synkope, cerebrovaskul\xe4r h\xe4ndelse, cerebral ischemi, f\xf6rv\xe4rrade tecken och symtom p\xe5 myasthenia gravis, parestesi.'],
             ['Eye',
              u'Tecken och symtom p\xe5 okul\xe4r irritation (t.ex. stickande, kliande k\xe4nsla, t\xe5rfl\xf6de), blefarit, minskad t\xe5rsekretion, korneal erosion, ptos, diplopi, synrubbningar t.ex. refraktionsf\xf6r\xe4ndringar (i vissa fall p.g.a. uts\xe4ttande av miotika), koroidalavlossning efter filtrationskirurgi (se 4.4 \u201dVarningar och f\xf6rsiktighet\u201d).'],
             ['Ear', u'Tinnitus.'],
             ['Cardiac',
              u'Bradykardi, br\xf6stsm\xe4rta, hj\xe4rtklappning, \xf6dem, arytmi, hj\xe4rtinfarkt, atrioventrikul\xe4rt block, hj\xe4rtstillest\xe5nd, hj\xe4rtsvikt.'],
             ['Vascular', u'Hypotension, Raynauds fenomen, kalla h\xe4nder och f\xf6tter.'],
             ['Respiratory',
              u'Bronkospasm (framf\xf6r allt hos patienter med tidigare bronkospastisk sjukdom), hosta, respiratorisk insufficiens.'],
             ['GI',
              u'Dysgeusi, illam\xe5ende, dyspepsi, diarr\xe9, muntorrhet, buksm\xe4rta, kr\xe4kningar.'],
             ['Skin',
              u'Alopeci, hudutslag, psoriasisliknande utslag eller f\xf6rv\xe4rrad psoriasis.'],
             ['Musculoskeletal', u'Myalgi.'],
             ['Reproductive system',
              u'Sexuell dysfunktion, minskad libido, Peyronies sjukdom.'],
             ['General', u'Asteni/tr\xf6tthet.']]]],
 '_pages': [4, 6],
 u'_rank': 19,
 u'_type': u'LSFU'}