{'_data': [['Common',
            [['Eye',
              u'Tecken och symtom p\xe5 okul\xe4r irritation (t.ex.  br\xe4nnande, stickande, kliande k\xe4nsla, t\xe5rfl\xf6de, r\xf6da \xf6gon), dimsyn']]],
           ['Uncommon',
            [['Psychiatric', u'Depression'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel, synkope'],
             ['Eye',
              u'Keratit, konjunktivit, refraktionsf\xf6r\xe4ndringar (i  vissa fall p\xe5 grund av uts\xe4ttande av miotika).'],
             ['Cardiac', u'Bradykardi'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Illam\xe5ende'],
             ['General', u'Asteni, tr\xf6tthet']]],
           ['Rare',
            [['Immune system',
              u'Systemisk lupus erythematosus, systemiska  allergiska reaktioner inklusive angio\xf6dem, urtikaria, lokala och generaliserade utslag, pruritus, anafylaktisk reaktion'],
             ['Psychiatric', u'Insomnia, mardr\xf6mmar, minnesf\xf6rlust'],
             ['Nervous system',
              u'F\xf6rv\xe4rrade tecken och symtom p\xe5 myasthenia  gravis, cerebral ischemi'],
             ['Eye', u'Blefarit, ptosis, diplopi, nedsatt kornealsensibilitet,  torra \xf6gon'],
             ['Cardiac',
              u'\xd6dem, br\xf6stsm\xe4rta, hj\xe4rtklappning, arytmi,  hj\xe4rtinsufficiens, hj\xe4rtblock, hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'Hypotension'],
             ['Respiratory',
              u'Bronkospasm (f\xf6retr\xe4desvis allt hos patienter med  existerande bronkospastisk sjukdom), andningsstillest\xe5nd'],
             ['Skin',
              u'Hudutslag, alopeci, psoriasisutslag eller  f\xf6rv\xe4rrande av psoriasis']]],
           ['Unknown',
            [['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Cerebrovaskul\xe4r h\xe4ndelse, parestesi'],
             ['Eye',
              u'Koroidalavlossning efter filtrationskirurgi (se  avsnitt 4.4), korneal erosion'],
             ['Cardiac', u'Hj\xe4rtinfarkt'],
             ['Vascular', u'Raynauds fenomen, kalla h\xe4nder och f\xf6tter'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Dysgeusi, dyspepsi, diarr\xe9, muntorrhet, buksm\xe4rta,  kr\xe4kning'],
             ['Musculoskeletal', u'Myalgi'],
             ['Reproductive system',
              u'Sexuell dysfunktion (s\xe5som impotens), minskad  libido']]]],
 '_pages': [5, 6],
 u'_rank': 25,
 u'_type': u'TSFU'}