{'_data': [['Common',
            [['Nervous system', u'Yrsel, huvudv\xe4rk, d\xe5sighet.'],
             ['GI', u'Muntorrhet, illam\xe5ende, kr\xe4kningar, f\xf6rstoppning.'],
             ['Skin', u'Svettning.']]],
           ['Uncommon',
            [['Cardiac', u'Takykardi, postural hypotension eller kardiovaskul\xe4r kollaps.'],
             ['GI',
              u'Kv\xe4ljningar, gastrointestinal irritation (tryckk\xe4nsla i magen, uppsv\xe4lldhet), diarr\xe9.'],
             ['Skin', u'Kl\xe5da, utslag, urtikaria.']]],
           ['Rare',
            [['Cardiac', u'Hypertension, bradykardi.'],
             ['Nervous system', u'Krampanfall, parestesier, tremor, syncope.'],
             ['Eye', u'Dimsyn.'],
             ['Respiratory',
              u'F\xf6rs\xe4mring av astma har rapporterats, men orsakssamband har inte fast\xe4llts.'],
             ['Renal', u'Miktionsst\xf6rningar.'],
             ['Skin',
              u'Angioneurotiskt \xf6dem (inklusive svullnad av munh\xe5la, svalg och larynx).'],
             ['Musculoskeletal', u'Muskelsvaghet.'],
             ['Metabolism', u'Aptitf\xf6r\xe4ndringar.'],
             ['Immune system',
              u'Allergiska reaktioner som andn\xf6d, bronkospam, v\xe4sljud och anafylaktisk chock.'],
             ['Psychiatric',
              u'F\xf6r\xe4ndring av sinnesst\xe4mning (upprymdhet, ibland dysfori) samt av kognitiv och sensorisk kapacitet, \xf6kad eller minskad aktivitetsniv\xe5, hallucinationer, mardr\xf6mmar, konfusion.']]]],
 '_pages': [4, 5],
 u'_rank': 16,
 u'_type': u'LSFU'}