{'_data': [['Uncommon', [['Respiratory', u'dysfoni, dyspn\xe9, hosta, faryngit']]],
           ['Rare',
            [['Infections', u'laryngit'],
             ['Metabolism', u'anorexi'],
             ['Nervous system', u'huvudv\xe4rk, yrsel, afoni'],
             ['Ear', u'tinnitus, h\xf6rselbortfall'],
             ['Respiratory',
              u'bronkospasm, tr\xe5nghetsk\xe4nsla i br\xf6stet , lungsjukdom, \xf6kad sputumproduktion , hemoptys, n\xe4sblod, rinit, astma'],
             ['GI',
              u'f\xf6r\xe4ndrad smakk\xe4nsla, illam\xe5ende, s\xe5rbildning i munnen , kr\xe4kning'],
             ['Skin', u'hudutslag'],
             ['General', u'asteni, feber, br\xf6stsm\xe4rta, sm\xe4rta'],
             ['Investigations',
              u'f\xf6rs\xe4mrad lungfunktion I \xf6ppna studier, samt efter godk\xe4nnandet, har n\xe5gra patienter med l\xe5ngvarig tidigare eller samtidig anv\xe4ndning av intraven\xf6sa aminoglykosider f\xe5tt h\xf6rselbortfall (se avsnitt 4.4). Parenterala aminoglykosider har associerats med \xf6verk\xe4nslighet, ototoxicitet och njurtoxicitet (se avsnitt 4.3 och 4.4).']]],
           ['Very rare',
            [['Infections', u'oral moniliasis , svampinfektion'],
             ['Blood', u'lymfadenopati'],
             ['Immune system', u'\xf6verk\xe4nslighetsreaktioner'],
             ['Nervous system', u'somnolens'],
             ['Ear', u'\xf6ronbesv\xe4r, \xf6ronsm\xe4rta'],
             ['Respiratory', u'hyperventilation, hypoxi, sinuit'],
             ['GI', u'diarr\xe9, buksm\xe4rta'],
             ['Skin', u'urtikaria, kl\xe5da'],
             ['Musculoskeletal', u'ryggsm\xe4rta'],
             ['General', u'sjukdomsk\xe4nsla']]],
           ['Unknown',
            [['Other',
              u'sputum, luftv\xe4gsinfektion, myalgi, n\xe4spolyp och inflammation i mellan\xf6rat. Efter godk\xe4nnandet av TOBI har f\xf6ljande biverkningar rapporterats med f\xf6ljande frekvenser']]]],
 '_pages': [5, 6],
 u'_rank': 21,
 u'_type': u'LSFU'}