{'_data': [['Very common',
            [['Investigations', u'Vikt-mi nsk-nin g'],
             ['Nervous system', u'Parestes i Somnol -ens, yrsel'],
             ['GI', u'Illam\xe5e n-de, diarr\xe9'],
             ['Metabolism', u'ch'],
             ['Infections', u'Naso-fa ryngit*'],
             ['General', u'Tr\xf6tthet Pyrexi, asteni,'],
             ['Reproductive system', u'och'],
             ['Psychiatric', u'Depress -ion']]],
           ['Common',
            [['Investigations', u'Vikt\xf6kning*'],
             ['Blood', u'Anemi'],
             ['Nervous system',
              u'St\xf6rd uppm\xe4rksam-h et, minnesf\xf6r-s\xe4mr ing, amnesi, kognitiv st\xf6rning, mental f\xf6rs\xe4mring, f\xf6rs\xe4mrade psykomotori-sk a f\xe4rdigheter, kramper, onormal koordination, tremor, letargi, hypestesi, nystagmus, smakrubbning, balansrubbning intensions-trem or, sedering'],
             ['Eye', u'Dimsyn, diplopi, synst\xf6rning'],
             ['Ear', u'Vertigo, tinnitus, \xf6ronv\xe4rk'],
             ['Respiratory', u'Dyspn\xe9, n\xe4sbl\xf6dning, n\xe4st\xe4ppa, rinorr\xe9'],
             ['GI',
              u'Kr\xe4kningar, f\xf6rstoppning, \xf6vre buksm\xe4rta, dyspepsi, buksm\xe4rta, muntorrhet, magobehag, oral parestesi, gastrit, bukobehag'],
             ['Renal', u'Njursten, pollakisuri, dysuri'],
             ['Skin', u'Alopeci, hudutslag, kl\xe5da'],
             ['Musculoskeletal',
              u'Artralgi, muskelkramper myalgi, muskelrycknin gar, muskelsvaghet, muskuloskeleta l br\xf6stsm\xe4rta'],
             ['Metabolism', u'Anorexi, minskad aptit'],
             ['General',
              u'irritabilitet, g\xe5ngrubbning, k\xe4nslaav att vara onormal, sjukdoms-k\xe4nsl a'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'Bradyfreni (l\xe5ngsamma f\xf6rst\xe5nds och k\xe4nslom\xe4ssi-ga funktioner), insomni, expressiv spr\xe5kst\xf6rn-ing, \xe5ngest, f\xf6rvirrings-tillst \xe5nd, desorientering, aggression, hum\xf6rf\xf6r-\xe4ndri ng, agitation, hum\xf6rsv\xe4ng-ni ngar, nedst\xe4mdhet, vrede, onormalt beteende']]],
           ['Uncommon',
            [['Investigations',
              u'F\xf6rekomst av kristaller i urin, onormalt tandemg\xe5ng-test , minskat antal vita blodkroppar'],
             ['Cardiac', u'Bradykardi, sinus bradykardi, palpitations'],
             ['Blood', u'Leukopeni, trombocytopeni, lymfadeno-pati, eosinofi'],
             ['Nervous system',
              u'Minskad medvetandegrad , grand mal-anfall, defekt synf\xe4lt, komplexa partiella anfall, talst\xf6rning, psykomotorisk hyperaktivitet, synkope, sensorisk st\xf6rning, dregling, hypersomni, afasi, repetitivt tal, hypokinesi, dyskinesi, postural yrsel, d\xe5lig s\xf6mnkvalitet, br\xe4nnande k\xe4nsla, sensorisk f\xf6rlust, felaktig luktf\xf6rnimmelse , cerebell\xe4rt syndrom, dysestesi, nedsatt smak-f\xf6rnimme lse, stupor, klumpighet, aura, f\xf6rlorad smak-f\xf6rnimme lse, dysgrafi, dysfasi, perifer neuropati, presynkope, dystoni, myrkrypningar'],
             ['Eye',
              u'Minskad synsk\xe4rpa, skotom, myopi*, onormal k\xe4nsla I \xf6gonen*, torra \xf6gon, fotofobi, blefarospasm, \xf6kad t\xe5rproduktion, fotopsi, mydriasis, presbyopi'],
             ['Ear',
              u'D\xf6vhet, ensidig d\xf6vhet, neurosensorisk \xf6ronen, f\xf6rs\xe4mrad h\xf6rsel'],
             ['Respiratory',
              u'Anstr\xe4ngnings-dyspn\xe9, paranasal sinushypersekre -tion, dysfoni'],
             ['GI',
              u'Pankreatit, flatulens, gastroesofagal refluxsjukdom, nedre buksm\xe4rta, oral hypestesi, gingival bl\xf6dning, uppsp\xe4nd buk, epigastriskt buk, saliv-hypersekre tion, andedr\xe4kt, glossodyni'],
             ['Renal',
              u'Urinsten, urininkontinens, hematuri, inkontinens, miktionstr\xe4ngni -ngar, njurkolik, njursm\xe4rta'],
             ['Skin',
              u'Anhidros, facial hypertesi, urtikaria, erytem, generell kl\xe5da, makul\xe4ra utslag, hudmissf\xe4rgnin gar, allergisk dermatit, svullet ansikte'],
             ['Musculoskeletal',
              u'Ledsvullnad*, muskuloskeletal stelhet, flanksm\xe4rta, muskeltr\xf6tthet'],
             ['Metabolism', u'Metabolisk acidos, hypokalemi, \xf6kad polydipsi'],
             ['Vascular', u'Hypotension, ortostatisk hypotension, rodnad, v\xe4rmevallning'],
             ['General',
              u'Hypertermi, t\xf6rst, influensalik-nande sjukdom*, tr\xf6ghet, perifer kyla, berusnings-k\xe4ns la, nervositet'],
             ['Reproductive system', u'Erektil dysfunktion, sexuell dysfunktion'],
             ['Psychiatric',
              u'Sj\xe4lsmordstank-ar, sj\xe4lvmords-f\xf6rs \xf6k, hallucination, psykotisk st\xf6rning, h\xf6rselhallucina-tion, synhallucination , apati, avsaknad av spontant tal, s\xf6mnst\xf6rning, affektlabilitet, minskad libido, rastl\xf6shet, gr\xe5t, dysfemi, euforisk sinnesst\xe4mning, paranoia, perseveration, panikattack, gr\xe5tmildhet, l\xe4sst\xf6rning, insomningssv\xe5ri -heter, flack affekt, onormalt t\xe4nkande, f\xf6rlust av libido, h\xe5gl\xf6shet, sv\xe5righeter att vidmakth\xe5lla s\xf6mnen, distraherbarhet, f\xf6r tidigt uppvaknande, panikreaktion, f\xf6rh\xf6jd sinnesst\xe4mning']]],
           ['Rare',
            [['Investigations', u'Minskat blod-bikarbona'],
             ['Blood', u'Neutropeni*'],
             ['Nervous system',
              u'Apraxi, s\xf6mn-st\xf6rning vid dygnsrytm-st\xf6r ning, hyperestesi, nedsatt lukt-f\xf6rm\xe5ga, avsaknad av luktsinne, essentiell tremor, akinesi, ok\xe4nslighet f\xf6r stimuli'],
             ['Eye',
              u'Ensidig blindhet, \xf6verg\xe5ende blindhet, glaukom, ackommodatio ns-st\xf6rning, f\xf6r\xe4ndrat djupseende, flimmerskot-o m, \xf6gonlocks\xf6de m*, nattblindhet, amblyopi'],
             ['GI', u'oral'],
             ['Renal', u'Uret\xe4rsten, renal tubul\xe4r acidos*'],
             ['Skin',
              u'Stevens-Johns ons syndrom*, erythema multiforme*, onormal hudlukt, periorbitalt \xf6dem*, lokal urtikaria'],
             ['Musculoskeletal', u'Extremitets-ob ehag'],
             ['Metabolism', u'Hyperkloremis k acidos aptit,'],
             ['Vascular', u'Raynauds fenomen'],
             ['General', u'Ansikts-\xf6dem, kalcinos'],
             ['Psychiatric',
              u'Mani, anorgasmi, paniksyndrom, st\xf6rd sexuell upphetsning, k\xe4nsla f\xf6rtvivlan*, onormal orgasm, hypomani, minskad orgasmk\xe4nsla']]],
           ['Unknown',
            [['Eye',
              u'Glauk-om med tr\xe5ng kamm-arvink-el*, makulo -pati*, \xf6gon-r \xf6relse-st\xf6r-ning*'],
             ['Skin', u'Toxisk epider-mal nekro-l ys*'],
             ['Immune system', u'Allergi s-kt \xf6dem*, bind-hinne-\xf6 dem*'],
             ['Psychiatric', u'av']]]],
 '_note': u' ?MSFU',
 '_pages': [11, 16],
 u'_rank': 54,
 u'_type': u'MSFU'}