{'_data': [['Very common',
            [['Investigations', u'Viktminsknin g'],
             ['Nervous system', u'Parestesi, somnolens, yrsel'],
             ['GI', u'Illam\xe5ende, diarr\xe9'],
             ['Infections', u'Nasofaryngit*'],
             ['General', u'Tr\xf6tthet'],
             ['Psychiatric', u'Depression']]],
           ['Common',
            [['Investigations', u'Vikt\xf6kning*'],
             ['Blood', u'Anemi'],
             ['Nervous system',
              u'St\xf6rd uppm\xe4rksamhet, minnesf\xf6rs\xe4mring, amnesi, kognitiv st\xf6rning, mental f\xf6rs\xe4mring, f\xf6rs\xe4mrade psykomotoriska f\xe4rdigheter, kramper, onormal koordination, tremor, letargi, hypestesi, nystagmus, smakrubbning, balansrubbning, dysartri, intensions tremor, sedering'],
             ['Eye', u'Dimsyn, diplopi, synst\xf6rning'],
             ['Ear', u'Vertigo, tinnitus, \xf6ronv\xe4rk'],
             ['Respiratory', u'Dyspn\xe9, n\xe4sbl\xf6dning, n\xe4st\xe4ppa, rinorr\xe9'],
             ['GI',
              u'Kr\xe4kningar, f\xf6rstoppning, \xf6vre buksm\xe4rta, dyspepsi, buksm\xe4rta, muntorrhet, magobehag, oral parestesi, gastrit, bukobehag'],
             ['Renal', u'Njursten, pollakisuri, dysuri'],
             ['Skin', u'Alopeci, hudutslag, kl\xe5da'],
             ['Musculoskeletal',
              u'Artralgi, muskelkramper, myalgi, muskelryckningar, muskelsvaghet, muskuloskeletal br\xf6stsm\xe4rta'],
             ['Metabolism', u'Anorexi, minskad aptit'],
             ['General',
              u'Pyrexi, asteni, irritabilitet, g\xe5ngrubbning, k\xe4nsla av att vara onormal, sjukdomsk\xe4nsla'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric',
              u'Bradyfreni (l\xe5ngsamma f\xf6rst\xe5nds och k\xe4nslom\xe4ssiga funktioner), insomni, expressiv spr\xe5kst\xf6rning, \xe5ngest, f\xf6rvirrings tillst\xe5nd, desorientering, aggression, hum\xf6rf\xf6r\xe4ndring, agitation, hum\xf6r sv\xe4ngningar, nedst\xe4mdhet, vrede, onormalt beteende']]],
           ['Uncommon',
            [['Investigations',
              u'F\xf6rekomst av kristaller i urin, onormalt tandemg\xe5ngtest, minskat antal vita blodkroppar'],
             ['Cardiac', u'Bradykardi, sinusbradykardi, palpitationer'],
             ['Blood', u'Leukopeni, trombocytopeni, lymfadenopati, eosinofili'],
             ['Nervous system',
              u'Minskad medvetandegrad , grand mal-anfall, defekt synf\xe4lt, komplexa partiella anfall, talst\xf6rning, psykomotorisk hyperaktivitet, synkope, sensorisk st\xf6rning, dregling, hypersomni, afasi, repetitivt tal, hypokinesi, dyskinesi, postural yrsel, d\xe5lig s\xf6mnkvalitet, br\xe4nnande k\xe4nsla, sensorisk f\xf6rlust, felaktig luktf\xf6rnimmelse , cerebell\xe4rt syndrom, dysestesi, nedsatt smakf\xf6rnimmelse, stupor, klumpighet, aura, f\xf6rlorad smakf\xf6rnimmelse, dysgrafi, dysfasi, perifer neuropati, presynkope, dystoni, myrkrypningar'],
             ['Eye',
              u'Minskad synsk\xe4rpa, skotom, myopi*, onormal k\xe4nsla i \xf6gonen*, torra \xf6gon, fotofobi, blefarospasm, \xf6kad t\xe5rproduktion, fotopsi, mydriasis, presbyopi'],
             ['Ear',
              u'D\xf6vhet, ensidig d\xf6vhet, neurosensorisk d\xf6vhet, obehag i \xf6ronen, f\xf6rs\xe4mrad h\xf6rsel'],
             ['Respiratory',
              u'Anstr\xe4ngnings dyspn\xe9, paranasal sinushyper sekretion, dysfoni'],
             ['GI',
              u'Pankreatit, flatulens, gastroesofagal refluxsjukdom, nedre buksm\xe4rta, oral hypestesi, gingival bl\xf6dning, uppsp\xe4nd buk, epigastriskt obehag, \xf6m buk, salivhyper sekretion, oral sm\xe4rta, d\xe5lig andedr\xe4kt, glossodyni'],
             ['Renal',
              u'Urinsten, urininkontinens, hematuri, inkontinens, miktions-tr\xe4ngnin gar, njurkolik, njursm\xe4rta'],
             ['Skin',
              u'Anhidros, facial hypestesi, urtikaria, erytem, generell kl\xe5da, makul\xe4ra utslag, hudmiss f\xe4rgningar, allergisk dermatit, svullet ansikte'],
             ['Musculoskeletal',
              u'Ledsvullnad*, muskuloskeletal stelhet, flanksm\xe4rta, muskeltr\xf6tthet'],
             ['Metabolism', u'Metabolisk acidos, hypokalemi, \xf6kad aptit, polydipsi'],
             ['Vascular', u'Hypotension, ortostatisk hypotension, rodnad, v\xe4rmevallning'],
             ['General',
              u'Hypertermi, t\xf6rst, influensaliknande sjukdom*, tr\xf6ghet, perifer kyla, berusningsk\xe4nsla, nervositet'],
             ['Reproductive system', u'Erektil dysfunktion, sexuell dysfunktion'],
             ['Psychiatric',
              u'Sj\xe4lvmordstankar, sj\xe4lvmords f\xf6rs\xf6k, hallucination, psykotisk st\xf6rning, h\xf6rsel hallucination, synhallucination , apati, avsaknad av spontant tal, s\xf6mnst\xf6rning, affektlabilitet, minskad libido, rastl\xf6shet, gr\xe5t, dysfemi, euforisk sinnesst\xe4mning, paranoia, perseveration, panikattack, gr\xe5tmildhet, l\xe4sst\xf6rning, insomnings sv\xe5righeter, flack affekt, onormalt t\xe4nkande, f\xf6rlust av libido, h\xe5gl\xf6shet, sv\xe5righeter att vidmakth\xe5lla s\xf6mnen, distraherbarhet, f\xf6r tidigt uppvaknande, panikreaktion, f\xf6rh\xf6jd sinnesst\xe4mning']]],
           ['Rare',
            [['Investigations', u'Minskat blodbikarbonat'],
             ['Blood', u'Neutropeni*'],
             ['Nervous system',
              u'Apraxi, s\xf6mnst\xf6rning vid dygnsrytmst\xf6rning hyperestesi, nedsatt luktf\xf6rm\xe5ga, avsaknad av luktsinne, essentiell tremor, akinesi, ok\xe4nslighet f\xf6r stimuli'],
             ['Eye',
              u'Ensidig blindhet, \xf6verg\xe5ende blindhet, glaukom, ackommodations st\xf6rning, f\xf6r\xe4ndrat djupseende, flimmerskotom, \xf6gonlocks\xf6dem*, nattblindhet, amblyopi'],
             ['Renal', u'Uret\xe4rsten, renal tubul\xe4r acidos*'],
             ['Skin',
              u'Stevens-Johnsons syndrom*, erythema multiforme *, onormal hudlukt, periorbitalt \xf6dem*, lokal urtikaria'],
             ['Musculoskeletal', u'Extremitets obehag*'],
             ['Metabolism', u'Hyperkloremisk acidos'],
             ['Vascular', u'Raynauds fenomen'],
             ['General', u'Ansikts\xf6dem, kalcinos'],
             ['Psychiatric',
              u'Mani, anorgasmi, paniksyndrom, st\xf6rd sexuell upphetsning, k\xe4nsla av f\xf6rtvivlan*, onormal orgasm, hypomani, minskad orgasmk\xe4nsla']]],
           ['Unknown',
            [['Eye',
              u'Glaukom med tr\xe5ng kammarvink el*, makulopati* \xf6gonr\xf6relse st\xf6rning*'],
             ['Skin', u'Toxisk epidermal nekrolys*'],
             ['Immune system', u'Allergiskt \xf6dem*, bindhinne \xf6dem*']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 14],
 u'_rank': 50,
 u'_type': u'MSFU'}