{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk Yrsel'],
             ['GI', u'Illam\xe5ende Dyspepsi Gastrointestinal sm\xe4rta Diarr\xe9'],
             ['Skin', u'Svettning'],
             ['General', u'\xd6dem']]],
           ['Uncommon',
            [['Nervous system', u'Parestesi Smakf\xf6r\xe4ndringar'],
             ['Eye', u'Synf\xf6r\xe4ndringar'],
             ['Respiratory', u'Astma Dyspn\xe9 Epistaxis'],
             ['GI',
              u'Melena Kr\xe4kningar Stomatit Mags\xe5r F\xf6rstoppning Flatulens Bl\xf6dningar i rektum Gastrit Ulcerativ stomatit Muntorrhet'],
             ['Renal', u'\xd6kad miktionsfrekvens Oliguri Urinretention'],
             ['Skin', u'Kl\xe5da Urtikaria Rodnad Purpura'],
             ['Musculoskeletal', u'Myalgi'],
             ['General', u'Asteni Blekhet Om\xe5ttlig t\xf6rst'],
             ['Psychiatric',
              u'D\xe5sighetAbnorma tankar Depression Eufori Koncentrationsst\xf6 rningar S\xf6mnl\xf6shet Nervositet']]],
           ['Rare',
            [['Cardiac', u'Hj\xe4rtsvikt'],
             ['Blood', u'Trombocytopeni'],
             ['Nervous system', u'Konvulsioner Hyperkinesi'],
             ['Ear', u'H\xf6rselneds\xe4ttning Tinnitus, yrsel'],
             ['Respiratory', u'Lung\xf6dem'],
             ['GI',
              u'Gastrointestinal bl\xf6dning Gastrointestinal perforation Hematemes F\xf6rs\xe4mring av ulcer\xf6s kolit F\xf6rs\xe4mring av Crohns sjukdom'],
             ['Renal',
              u'Akut njursvikt Flanksm\xe4rta med eller utan hematuri och/eller azotemi'],
             ['Skin',
              u'Toxisk epidermal nekrolys (Lyells syndrom) Stevens-Johnsons syndrom Exfoliativ dermatit Makulopapul\xf6st utslag'],
             ['Vascular', u'Hypertoni Hypotoni Postoperativ bl\xf6dning'],
             ['Immune system',
              u'Anafylaktiska reaktioner som bronkospasm, laryngealt \xf6dem, hypotension, rodnad och hudutslag'],
             ['Psychiatric', u'Abnorma dr\xf6mmar Hallucinationer']]],
           ['Unknown',
            [['Cardiac', u'Hj\xe4rtklappning, bradykardi'],
             ['GI', u'Esofagit, pankreatit Peptisk ulcus Rapningar M\xe4ttnadsk\xe4nsla'],
             ['Renal', u'Interstitiell nefrit Nefrotiskt syndrom Hemolytiskt uremsikt syndrom'],
             ['Skin', u'Angio\xf6dem'],
             ['Vascular', u'Hematom Rodnad Blekhet'],
             ['General', u'Reaktion vid injektionsst\xe4llet, feber, br\xf6stsm\xe4rta'],
             ['Psychiatric', u'\xc5ngest Psykotiska reaktioner'],
             ['Metabolism', u'Anorexi Hyperkalemi Hyponatremi'],
             ['Infections', u'Aseptisk meningit'],
             ['Hepato', u'Hepatit, kolestatisk gulsot, leversvikt'],
             ['Reproductive system', u'Kvinnlig infertilitet'],
             ['Investigations',
              u'F\xf6rl\xe4ngd bl\xf6dningstid, f\xf6rh\xf6jt S-urea, f\xf6rh\xf6jt kreatinin, hyperkalemi, hyponatremi Onormala leverfunktions-v\xe4rden']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 11],
 u'_rank': 36,
 u'_type': u'MSFU'}