{'_data': [['Common', [['General', u'Huvudv\xe4rk.   (>1/100):  CNS: Yrsel.']]],
           ['Uncommon',
            [['GI',
              u'Aptitf\xf6rlust, magsm\xe4rtor, illam\xe5ende, kr\xe4kning, diarr\xe9, obstipation.    (1/100-1/1000)  Lever: Gamma-GT-stegring.'],
             ['Metabolism',
              u'Hyperglykemi, hyperurikemi, hypokalemi, \xf6kning av kolesterol,  triglycerider.'],
             ['Musculoskeletal', u'Muskelkramp, muskelv\xe4rk.'],
             ['Other', u'Asteni.']]],
           ['Rare',
            [['General', u'Muntorrhet.   (<1/1000):  Blod: Leukopeni, trombocytopeni.'],
             ['Vascular', u'Hypovolemi.'],
             ['Skin', u'Exantem, fotosensibilitet, kl\xe5da, urticaria.'],
             ['Metabolism', u'Kreatininstegring, hyponatremi.'],
             ['Nervous system', u'Parestesi av extremiteter.'],
             ['Ear', u'Tinnitus, h\xf6rselneds\xe4ttning.']]]],
 '_pages': [3, 4],
 u'_rank': 11,
 u'_type': u'LFSUR'}