{'_data': [['Very common',
            [['General', u'Reaktioner vid appliceringsomr\xe5det'],
             ['Metabolism',
              u'Vikt\xf6kning, elektrolytf\xf6r\xe4ndringar (retention av natrium, klorid, kalium, kalcium, oorganiskt fosfat och vatten) vid h\xf6g dos och/eller l\xe5ngvarig behandling.'],
             ['Nervous system', u'Nervositet, fientlighet, depression.'],
             ['Respiratory', u'S\xf6mnapn\xe9.'],
             ['GI', u'Illam\xe5ende.'],
             ['Hepato',
              u'I mycket s\xe4llsynta fall gulsot och avvikande leverfunktionstester.'],
             ['Skin',
              u'Olika hudreaktioner kan uppst\xe5, inklusive akne, seborr\xe9 och h\xe5ravfall (alopeci).'],
             ['Musculoskeletal', u'Muskelkramper, muskelsm\xe4rta.'],
             ['Reproductive system',
              u'F\xf6r\xe4ndrad libido, \xf6kad frekvens av erektioner; behandling med h\xf6ga doser av testosteronpreparat stoppar eller minskar vanligen reversibelt spermatogenesen, och minskar d\xe4rigenom testiklarnas storlek. Substitutionsbehandling med testosteron mot hypogonadism kan i'],
             ['General',
              u'H\xf6ga doser eller l\xe5ngvarig administrering av testosteron \xf6kar ibland f\xf6rekomsten av vattenretention och \xf6dem; \xf6verk\xe4nslighetsreaktioner kan f\xf6rekomma.']]],
           ['Common',
            [['Blood', u'\xd6kning av hemoglobin och hematokrit'],
             ['Endocrine', u'\xd6kad beh\xe5ring av manlig distributionstyp'],
             ['Vascular', u'Hypertoni'],
             ['Reproductive system', u'Gynekomasti'],
             ['General', u'Perifert \xf6dem'],
             ['Investigations', u'\xd6kning av prostataspecifikt antigen (PSA)']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 6],
 u'_rank': 16,
 u'_type': u'MSFU'}