{'_data': [['Very common', [['Nervous system', u'Yrsel.'], ['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk, d\xe5sighet.'],
             ['GI', u'Kr\xe4kning, muntorrhet, f\xf6rstoppning.'],
             ['Skin', u'Svettningar'],
             ['General', u'Tr\xf6tthet']]],
           ['Uncommon',
            [['Cardiac',
<<<<<<< HEAD
              u'): Kardiovaskul\xe4ra effekter (hj\xe4rtklappning, takykardi, postural hypotension, kardiovaskul\xe4r kollaps). Dessa effekter upptr\xe4der s\xe4rskilt i samband med intraven\xf6s administrering av tramadol samt hos patienter som \xe4r fysiskt stressade.'],
=======
              u'(>1/1 000, <1/100): Kardiovaskul\xe4ra effekter (hj\xe4rtklappning, takykardi, postural hypotension, kardiovaskul\xe4r kollaps). Dessa effekter upptr\xe4der s\xe4rskilt i samband med intraven\xf6s administrering av tramadol samt hos patienter som \xe4r fysiskt stressade.'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['GI',
              u'Kv\xe4ljningar, gastrointestinal irritation (t ex m\xe4ttnadsk\xe4nsla, tryckk\xe4nsla i magen, v\xe4dersp\xe4nning), diarr\xe9.'],
             ['Skin', u'Hudreaktioner (t ex pruritus, hudutslag, n\xe4sselutslag).']]],
           ['Rare',
            [['Cardiac', u'Bradykardi, f\xf6rh\xf6jt blodtryck.'],
             ['Nervous system',
              u'Aptitf\xf6r\xe4ndringar, parestesier, tremor, andningsdepression, epileptiska kramper, synkope. Epileptiforma kramper har rapporterats. Detta har huvudsakligen intr\xe4ffat efter administrering av h\xf6ga doser tramadol eller efter samtidig behandling med l\xe4kemedel som s\xe4nker kramptr\xf6skeln eller i sig framkallar cerebrala kramper (t ex antidepressiva medel och psykofarmaka \u2013 se 4.5 Interaktioner med andra l\xe4kemedel och \xf6vriga interaktioner).'],
             ['Psychiatric',
              u'Hallucinationer, konfusion, s\xf6mnst\xf6rningar, mardr\xf6mmar. Olika psykiska biverkningar som varierar fr\xe5n individ till individ med avseende p\xe5 sv\xe5righetsgrad och art (beroende p\xe5 personlighet och behandlingstid). Dessa biverkningar innefattar f\xf6r\xe4ndring av sinnesst\xe4mning (vanligtvis upprymdhet, ibland dysfori), f\xf6r\xe4ndring av aktivitetsniv\xe5 (vanligtvis d\xe4mpning, ibland \xf6kning) och f\xf6r\xe4ndring i kognitiv och sensorisk f\xf6rm\xe5ga (t ex beslutsf\xf6rm\xe5ga, uppfattningsf\xf6rm\xe5ga). Tramadol kan ge upphov till beroende.'],
             ['Eye', u'Dimsyn'],
             ['Respiratory',
              u'Dyspn\xe9 F\xf6rs\xe4mring av astma har rapporterats, men ett orsakssamband har inte fastst\xe4llts.'],
             ['Musculoskeletal', u'Muskelsvaghet'],
             ['Renal',
              u'Bl\xe5st\xf6mningsrubbningar (sv\xe5righet att kasta vatten och urinretention).'],
             ['Immune system',
              u'Allergiska reaktioner (t ex dyspn\xe9, bronkospasm, v\xe4sande andning, angio\xf6dem innefattande svullnad i svalg/munh\xe5la/larynx), anafylaktisk chock. Andningsdepression har rapporterats. Risk f\xf6r andningsdepression f\xf6religger om rekommenderade doser v\xe4sentligen \xf6verskrids och andra centrald\xe4mpande medel ges samtidigt. Beroende kan f\xf6rekomma. Abstinenssymtom, liknande de som upptr\xe4der under opiatavv\xe4njning, kan visa sig p\xe5 f\xf6ljande s\xe4tt: upphetsning, \xe4ngslan, nervositet, s\xf6mnl\xf6shet, hyperkinesi, tremor och gastrointestinala symtom (se 4.4 Varningar och f\xf6rsiktig).']]],
           ['Very rare',
            [['Hepato',
              u'Enstaka fall av leverenzymstegring i blod har rapporterats i samband med behandling med tramadol.']]]],
 '_pages': [4, 5],
 u'_rank': 18,
 u'_type': u'LSFU'}