{'_data': [['Common',
            [['General', u' Svettning, yrsel, huvudv\xe4rk, tr\xf6tthet, d\xe5sighet.  '],
             ['Vascular', u' Ortostatiska besv\xe4r.  '],
             ['GI', u' Muntorrhet, illam\xe5ende, kr\xe4kningar. ']]],
           ['Uncommon',
            [['General', u' Somnolens.  '],
             ['Vascular', u' Takykardi, hypertension. '],
             ['Nervous system', u' Tremor, oro, hallucinationer. '],
             ['GI', u' F\xf6rstoppning, diarr\xe9, abdominell sm\xe4rta, dyspepsi. '],
             ['Skin', u' Kl\xe5da, urtikaria. '],
             ['Reproductive system', u' Miktionsst\xf6rningar. '],
             ['Eye', u' Synst\xf6rningar. '],
             ['Ear', u' Tinnitus. ']]],
           ['Rare',
            [['General',
              u' Hicka, allergiska reaktioner som angioneurotiskt \xf6dem inklusive  svullnad i svalg, munh\xe5la och struphuvud.  '],
             ['Nervous system', u' Parestesier, f\xf6rvirring, depression, hallucinationer. '],
             ['GI', u' Flatulens, smakf\xf6r\xe4ndringar, stomatit. '],
             ['Skin', u' Hudutslag. ']]]],
 '_pages': [3, 4],
 u'_rank': 15,
 u'_type': u'DFSU'}