{'_data': [['Very common', [['Nervous system', u'Yrsel.'], ['GI', u'Illam\xe5ende']]],
           ['Common',
            [['Nervous system', u'Huvudv\xe4rk, d\xe5sighet.'],
             ['GI', u'Kr\xe4kningar, f\xf6rstoppning, muntorrhet'],
             ['Skin', u'Svettning'],
             ['General', u'Tr\xf6tthet.']]],
           ['Uncommon',
            [['Cardiac',
              u'Kardiovaskul\xe4ra effekter (palpitationer, takykardi, postural hypotension eller kardiovaskul\xe4r kollaps). Dessa biverkningar kan framf\xf6r allt uppst\xe5 vid intraven\xf6s administrering samt hos patienter som st\xe5r under fysisk stress.'],
             ['GI',
              u'Kv\xe4ljningar, gastrointestinal irritation i magtarmkanalen (tryckk\xe4nsla i magen, uppsv\xe4lldhet), diarr\xe9'],
             ['Skin',
              u'Hudreaktioner (t ex pruritus, utslag, urtikaria) Muskuloskeletala systemet']]],
           ['Rare',
            [['Cardiac', u'Bradykardi, f\xf6rh\xf6jt blodtryck.'],
             ['Nervous system',
              u'Aptitf\xf6r\xe4ndringar, parestesier, tremor, andningsdepression, epileptiska kramper, ofrivilliga muskelkontraktioner, onormal koordination och synkope.'],
             ['Psychiatric',
              u'Hallucinationer, f\xf6rvirring, \xe5ngest, s\xf6mnrubbningar och mardr\xf6mmar. Psykiska individuellt i intensitet och natur (beroende p\xe5 personlighet och behandlingstid). Dessa inkluderar hum\xf6rf\xf6r\xe4ndringar (vanligen upprymdhet, ibland dysfori), aktivitetsf\xf6r\xe4ndringar (vanligen minskad aktivitet, i s\xe4llsynta fall \xf6kad aktivitet) och f\xf6r\xe4ndringar i kognitiv och sensorisk kapacitet (t ex beslutsbeteende, perceptionsst\xf6rningar). Beroende kan uppkomma.'],
             ['Eye', u'Dimsyn.'],
             ['Respiratory',
              u'dyspn\xe9 F\xf6rv\xe4rrande av astma har rapporterats \xe4ven om kausalsamband inte har fastst\xe4llts.'],
             ['Skin', u'Motorisk svaghet'],
             ['Renal',
              u'Miktionsst\xf6rningar (sv\xe5righeter att urinera, dysuria samt urinretention)'],
             ['General',
              u'Allergiska reaktioner (t ex dyspn\xe9, bronkospasm, v\xe4sande andning, angioneurotiskt \xf6dem) och anafylaxi. Symtom p\xe5 abstinensbesv\xe4r, liknandede som f\xf6rekommer i samband med opioidavv\xe4njning kan visa sig p\xe5 f\xf6ljande s\xe4tt: agitation, \xe5ngest, nervositet, s\xf6mnsv\xe5righet, hyperkinesi, tremor och symtom fr\xe5n magtarmkanalen. Andra symtom som mycket s\xe4llan har observerats i samband med tramadolbehandling inkluderar:: panikattacker, sv\xe5r \xe5ngest, hallucinationer, parestesier, tinnitus samt ovanliga CNS-symtom (tex f\xf6rvirring, vanf\xf6rest\xe4llningar, depersonalisering, derealisation, paranoia)..']]],
           ['Unknown',
            [['Nervous system',
              u'talsv\xe5righeter. Om de rekommenderade doserna \xf6verskrids avsev\xe4rt och om andra centrald\xe4mpande medel administreras samtidigt (se avsnitt 4.5) kan andningsdepression uppst\xe5. Epileptiska kramper intr\xe4ffade fr\xe4mst efter administrering av h\xf6ga doser tramadol eller efter samtidig behandling med l\xe4kemedel som kan s\xe4nka kramptr\xf6skeln eller som i sig sj\xe4lva framkallar cerebrala kramper (se avsnitt 4.4 och 4.5).'],
             ['Eye', u'mydriasis'],
             ['Hepato',
              u'Enstaka fall av leverenzymstegring i blod har rapporterats i samband med behandling med tramadol.']]]],
 '_pages': [4, 6],
 u'_rank': 20,
 u'_type': u'LSFU'}