{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['Eye',
              u'Illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rtor. Hud \xa0och \xa0subkutan \xa0v\xe4vnad']]],
           ['Uncommon', [['Eye', u'Dermatit, urtikaria, exantem.']]],
           ['Rare',
            [['Eye', u'F\xe4rgsinnesdefekter eller andra synrubbningar. Magtar m ka n alen']]],
           ['Unknown', [['Vascular', u'Enstaka fall av tromboembolism har rapporterats.']]]],
 '_pages': [3, 3],
 u'_rank': 5,
 u'_type': u'LSFU'}