{'_data': [['Common',
            [['Nervous system', u'Huvudv\xe4rk, yrsel'],
             ['Respiratory', u'Rethosta, bronkit'],
             ['Metabolism',
              u'Okontrollerad diabetes mellitus, minskad glukostolerans, \xf6kat blodglukos, \xf6kat urinsyra i blodet, f\xf6rs\xe4mrad gikt, \xf6kat kolesterol och/eller triglycerider p.g.a. hydroklortiazid'],
             ['General', u'Tr\xf6tthet, orkesl\xf6shet']]],
           ['Uncommon',
            [['Cardiac',
              u'Myokardisk ischemi inklusive angina pectoris, takykardi, arytmi, palpitationer, perifert \xf6dem'],
             ['Blood',
              u'Minskat antal vita blodkroppar, minskat antal r\xf6da blodkroppar, minskat hemoglobin, hemolytisk anemi, minskat antal blodpl\xe4ttar'],
             ['Nervous system',
              u'Svindel, parestesi, tremor, balansst\xf6rning, br\xe4nnande k\xe4nsla, dysgeusi, ageusi'],
             ['Eye', u'Visuella st\xf6rningar inklusive dimsyn, konjunktivit'],
             ['Ear', u'Tinnitus'],
             ['Respiratory', u'Sinusit, dyspn\xe9, t\xe4ppt n\xe4sa'],
             ['GI',
              u'Gastrointestinal inflammation, matsm\xe4ltningsbesv\xe4r , bukobehag, dyspepsi, gastrit, illam\xe5ende, f\xf6rstoppning Gingivit p.g.a. hydroklortiazid'],
             ['Renal',
              u'Nedsatt njurfunktion inklusive akut njursvikt, \xf6kad urinproduktion, \xf6kning av blodurea och blodkreatinin'],
             ['Skin',
              u'Angio\xf6dem; i mycket s\xe4llsynta fall kan obstruktion i luftv\xe4garna p.g.a. angio\xf6dem f\xe5 en d\xf6dlig utg\xe5ng, psoriasiform dermatit, hyperhidros, utslag, s\xe4rskilt makulopapul\xe4ra, pruritus, alopeci'],
             ['Musculoskeletal', u'Myalgi'],
             ['Metabolism',
              u'Anorexi, minskad aptit Minskat blodkalium, t\xf6rst p.g.a. hydroklortiazid'],
             ['Vascular', u'Hypotension, ortostatiskt blodtrycksfall, synkope, blodvallningar'],
             ['General', u'Br\xf6stsm\xe4rta, pyrexi'],
             ['Hepato',
              u'Kolestatisk eller cytolytisk hepatit (fatal utg\xe5ng har varit mycket leverenzymer och/eller konjugerat bilirubin Kolecystit med gallsten p.g.a. hydroklortiazid'],
             ['Reproductive system', u'\xd6verg\xe5ende erektil impotens'],
             ['Psychiatric',
              u'Nedst\xe4mdhet, apati, oro, nervositet, s\xf6mnst\xf6rningar inklusive somnolens']]],
           ['Very rare',
            [['GI',
              u'Kr\xe4kningar, aft\xf6s stomatit, glossit, diarr\xe9, \xf6vre magsm\xe4rta, muntorrhet'],
             ['Metabolism', u'\xd6kat blodkalium p.g.a. ramipril']]],
           ['Unknown',
            [['Cardiac', u'Hj\xe4rtinfarkt'],
             ['Blood',
              u'Benm\xe4rgsdepression, neutropeni inklusive agranulocytos, pancytopeni, eosinofili, hemokoncentration i samband med v\xe4tskebrist'],
             ['Nervous system',
              u'Cerebral ischemi inklusive ischemisk stroke och transitorisk ischemisk attack, f\xf6rs\xe4mring av psykomotorisk f\xf6rm\xe5ga, parosmi'],
             ['Eye', u'Xantopsi, minskat t\xe5rfl\xf6de p.g.a. hydroklortiazid'],
             ['Ear', u'F\xf6rs\xe4mrad h\xf6rsel'],
             ['Respiratory',
              u'Bronkospasm inklusive f\xf6rs\xe4mrad astma, Allergisk alveolit, icke kardiogent pulmon\xe4rt \xf6dem p.g.a. hydroklortiazid'],
             ['GI',
              u'Pankreatit (mycket s\xe4llsynta fall av d\xf6dlig utg\xe5ng har rapporterats med ACE-h\xe4mmare), \xf6kade pankreasenzymer, angio\xf6dem i tunntarmen, Sialoadenit p.g.a. hydroklortiazid'],
             ['Renal',
              u'F\xf6rv\xe4rring av tidigare proteinuri Interstitiell nefrit p.g.a. hydroklortiazid'],
             ['Skin',
              u'Toxisk epidermal nekrolys, Stevens-Johnsons syndrom, erythema multiforme, pemfigus, f\xf6rv\xe4rrad psoriasis, exfoliativ dermatit, ljusk\xe4nslighetsreaktion , onkolys, pemfigoida eller lichenoida exantem och enantem, urtikaria SLE p.g.a. hydroklortiazid'],
             ['Musculoskeletal',
              u'Muskelspasmer, artralgi Muskul\xe4r svaghet, muskuloskeletal stelhet, tetanus p.g.a. hydroklortiazid'],
             ['Metabolism',
              u'Minskat blodnatrium Glykosuri, metabol alkalos, hypokloremi, hypomagnesemi, hyperkalcemi, dehydrering p.g.a. hydroklortiazid'],
             ['Vascular',
              u'Trombos relaterat till sv\xe5r v\xe4tskebrist, vaskul\xe4r stenos, hypoperfusion, Raynauds fenomen, vaskulit'],
             ['Immune system',
              u'Anafylaktiska eller anafylaktoida reaktioner p\xe5 antingen ramipril eller anafylaktisk reaktion p\xe5 hydroklortiazid, \xf6kning i antinukle\xe4ra antikroppar'],
             ['Hepato', u'Akut leversvikt, kolestatisk gulsot, hepatocellul\xe4r skada'],
             ['Reproductive system', u'Gynekomasti, minskat libido'],
<<<<<<< HEAD
             ['Psychiatric', u'F\xf6rvirring, rastl\xf6shet, uppm\xe4rksamhetsst\xf6r-n ing']]]],
=======
             ['Psychiatric', u'F\xf6rvirring, rastl\xf6shet, uppm\xe4rksamhetsst\xf6r-ning']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_note': u' ?MSFU',
 '_pages': [8, 10],
 u'_rank': 38,
 u'_type': u'MSFU'}