{'_data': [['Common',
            [['GI', u' Illam\xe5ende, kr\xe4kningar, glossit.  '],
             ['Skin', u' Kl\xe5da, exantem.  ']]],
           ['Uncommon', [['Blood', u' Eosinofili, leukopeni.  '], ['Skin', u' Urtikaria. ']]],
           ['Rare',
            [['General', u' Feber.  '],
             ['Blood', u' Agranulocytos, megaloblastisk anemi,  trombocytopeni. '],
             ['Infections', u' Aseptisk meningit, pseudomembran\xf6s kolit. '],
             ['GI', u' Diarr\xe9. '],
             ['Skin', u' Stevens-Johnson syndrome, erythrema multiforme, fotosensibilitet. '],
             ['Eye', u' Konjunktivit. ']]]],
 '_pages': [3, 3],
 u'_rank': 10,
 u'_type': u'DFSU'}