{'_data': [['Common',
            [['GI', u' Illam\xe5ende, kr\xe4kningar, glossit.  '],
             ['Skin', u' Kl\xe5da, exantem.  ']]],
           ['Uncommon', [['Blood', u' Eosinofili, leukopeni.  '], ['Skin', u' Urtikaria. ']]],
           ['Rare',
            [['General', u' Feber.  '],
             ['Blood', u' Agranulocytos, megaloblastisk anemi,  trombocytopeni. '],
             ['Infections', u' Aseptisk meningit, pseudomembran\xf6s kolit. '],
             ['GI', u' Diarr\xe9. '],
             ['Skin', u' Stevens-Johnson syndrome, erythrema multiforme, fotosensibilitet. '],
             ['Eye', u' Konjunktivit. ']]],
           ['Very rare',
            [['Immune system',
              u' \xd6verk\xe4nslighetsreaktioner s\xe5som angioneurotiskt \xf6dem  och anafylaktiska reaktioner.  ']]]],
 '_pages': [3, 3],
 u'_rank': 11,
 u'_type': u'DFSU'}