{'_data': [['Common',
            [['Blood', u'Leukopeni, trombocytopeni, eosinofili'],
             ['Nervous system', u'Somnolens, ataxi'],
             ['Eye', u'Ackommodations-sv\xe5righeter, diplopi'],
             ['GI',
              u'Aptitl\xf6shet, illam\xe5ende, kr\xe4kning, diarr\xe9, obstipation, muntorrhet'],
             ['Skin', u'Hudutslag* (se Immunsystemet)'],
             ['Metabolism', u'Hyponatremi (v\xe4tskeretention)'],
             ['General', u'Yrsel, tr\xf6tthet'],
             ['Hepato', u'Reversibel h\xf6jning av leverenzymer']]],
           ['Uncommon',
            [['Blood', u'Leukocytos'],
             ['Nervous system',
              u'Ofrivilliga r\xf6relser, (s\xe5som tremor, dyskinesier, dystonier och tics), nystagmus'],
             ['General', u'Huvudv\xe4rk']]],
           ['Rare',
            [['Cardiac',
              u'Hj\xe4rtp\xe5verkan, (bradykardi, AV-block), hj\xe4rtsvikt, f\xf6rh\xf6jning eller s\xe4nkning av blodtrycket, f\xf6rv\xe4rrad koronarischemi.'],
             ['Blood',
              u'Agranulocytos, pancytopeni, aplastisk anemi, megaloblastisk anemi, retikulocytos, svullna lymfk\xf6rtlar. M\xe5ttlig minskning av antalet leukocyter eller trombocyter \xe4r vanligt f\xf6rekommande, men oftast \xf6verg\xe5ende, och beror mestadels inte p\xe5 n\xe5gon allvarlig benm\xe4rgsp\xe5verkan.'],
             ['Nervous system',
              u'Dysartri, \xf6gonmotilitets-st\xf6rning, perifera neuriter, parestesier, aseptisk meningit'],
             ['Eye', u'Linsgrumling, konjunktivit'],
             ['Ear', u'Tinnitus, hyperakusi'],
             ['Respiratory', u'Pulmonella \xf6verk\xe4nslighetsreaktioner* (se Immunsystemet)'],
             ['GI', u'Smakst\xf6rning, glossit, stomatit, buksm\xe4rtor'],
             ['Renal',
              u'Proteinuri, kreatinstegring, interstitiell nefrit, njurinsufficiens, hematuri, oliguri, pollakisuri, urinretention'],
             ['Skin',
<<<<<<< HEAD
              u'Allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs); Stevens-Johnson syndrome (SJS) och toxisk epidermal nekrolys (TEN) har rapporterats (se avsnitt 4.4). Erythema multiforme, exfoliativ dermatiti, h\xe5ravfall, erythema nodosum, hirsutism, f\xf6r\xe4ndrad hudpigmentering, kl\xe5da, acne, purpura, svettningar, fotosensibilitet'],
=======
              u'Allvarliga hudreaktioner (severe cutaneous adverse reactions, SCARs); Stevens- Johnson syndrome (SJS) och toxisk epidermal nekrolys (TEN) har rapporterats (se avsnitt 4.4). Erythema multiforme, exfoliativ dermatiti, h\xe5ravfall, erythema nodosum, hirsutism, f\xf6r\xe4ndrad hudpigmentering, kl\xe5da, acne, purpura, svettningar, fotosensibilitet'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Musculoskeletal',
              u'Muskelv\xe4rk, ledv\xe4rk, muskelkramper, SLE-liknande reaktioner'],
             ['Endocrine', u'Gynekomasti, galaktorr\xe9'],
             ['Metabolism',
              u'Vattenintoxikation, laboratoriem\xe4ssig bild som vid hypothyreos, hyperlipidemi, akut intermittent porfyri, osteomalaci efter l\xe5ngvarig behandling beroende p\xe5 \xf6kad nedbrytning av vitamin D genom enzyminduktion'],
             ['Vascular', u'Trombos, tromboemboliska komplikationer, tromboflebit'],
             ['General', u'Feber'],
             ['Hepato', u'Hepatit'],
             ['Reproductive system',
              u'Sexuell funktionsned-s\xe4ttning Det finns rapporter om nedsatt fertilitet hos karbamazepinbehandlade m\xe4n, men n\xe5got s\xe4kert samband har h\xe4rvid inte kunnat konstateras.'],
             ['Psychiatric',
              u'Konfusion och aktivering av andra psykotiska symtom, hallucinationer, agitation, oro, rastl\xf6shet, aggressivitet, depression']]],
<<<<<<< HEAD
           ['Very rare', [['Immune system', u'Anafylaktoida reaktioner']]],
=======
           ['Very rare',
            [['Immune system',
              u'Anafylaktoida reaktioner *\xd6verk\xe4nslighetsreaktioner i form av varierande kombinationer av feber, hudutslag, vaskulit, lymfadenopati, pseudolymfom, ledv\xe4rk, leukopeni, eosinofili, hepatosplenomegali, och onormal leverfunktionstester har rapporterats. Andra organ kan ocks\xe5 p\xe5verkas (t.ex. lever, lungor, njurar, bukspottsk\xf6rteln, hj\xe4rtmuskulaturen, tarmen).']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Unknown',
            [['Skin',
              u'Det finns \xf6kad bevisning ang\xe5ende associationen av genetiska mark\xf6rer och f\xf6rekomsten av hudbiverkningar s\xe5som SJS,TEN,DRESS,AGEP och makulopapul\xf6sa utslag. Hos japanska och europeiska patienter har dessa biverkningar rapporterats som associerade med anv\xe4ndningen av karbamazepin och n\xe4rvaron av allelen HLA-A*3101. En annan mark\xf6r, HLA-B*1502 har p\xe5visats vara starkt relaterat till SJS och TEN bland individer med hankinesiskt,thail\xe4ndskt och vissa andra asiatiska ursprung (se avsnitt 4.2 och 4.4 f\xf6r ytterligare information).'],
             ['Musculoskeletal',
              u'Det har kommit rapporter om s\xe4nkning av benmineraldensitet, osteopeni, osteoporos och frakturer hos patienter som st\xe5r p\xe5 l\xe5ngtidsbehandling med Trimonil retard. Mekanismen, genom vilken Trimonil retard p\xe5verkar benmetabolismen, har inte identifierats.']]]],
 '_pages': [8, 10],
 u'_rank': 31,
 u'_type': u'LSFU'}