{'_data': [['Common',
            [['GI', u' Illam\xe5ende, kr\xe4kning, buksm\xe4rta.  '],
             ['Skin', u' Akne.  Immunol.: Vaginit, candidainfektion. '],
             ['Nervous system', u' Huvudv\xe4rk \xe4ven migr\xe4n, oro, yrsel. '],
             ['Psychiatric',
              u' Nedst\xe4mdhet inkluderande depression, f\xf6r\xe4ndring av libido. '],
             ['Other',
              u' Bl\xf6dningar, dysmenorr\xe9, \xe4ndrad menstruation, f\xf6r\xe4ndring av cervixsekretion och cervixektopi, amenorr\xe9, br\xf6stsp\xe4nningar, sm\xe4rta i br\xf6sten, br\xf6stf\xf6rstoring, sekretion fr\xe5n br\xf6sten, v\xe4tskeretention/\xf6dem, f\xf6r\xe4ndringar i kroppsvikt. ']]],
           ['Uncommon',
            [['GI', u' Bukkramp, gaser.  '],
             ['Skin', u' Utslag, kloasma (melasma) som kan kvarst\xe5, hirsutism, alopecia.  '],
             ['Metabolism', u' Minskad eller \xf6kad aptit.  '],
             ['Other',
              u' Utebliven bortfallsbl\xf6dning, blodtrycksf\xf6rh\xf6jning, f\xf6r\xe4ndring av serum lipid niv\xe5erna inkluderande hypertriglyceridemi. ']]],
           ['Rare',
            [['Vascular',
              u' Djup ventrombos, lungemboli, hj\xe4rtinfarkt, f\xf6rs\xe4mring av varicer.  '],
             ['Endocrine',
              u' S\xe4nkt glukostolerans, f\xf6rh\xf6jt blodsocker, \xf6kat insulinbehov.  '],
             ['GI', u' Pankreatit, benigna leveradenom, hepatocellul\xe4r karcinom. '],
             ['Skin',
              u' Erythema multiforme, erythema nodosum. Immunol.: Exacerbation av lupus erythemtosus disseminatus, anafylaktiska/anafylaktoida reaktioner inkluderande mycket s\xe4llsynta fall av urticaria, angio\xf6dem och sv\xe5ra reaktioner med andnings- och cirkulationssymtom. '],
             ['Hepato',
              u' F\xf6r\xe4ndringar i leverfunktionen, kl\xe5da, gulsot av stastyp, sjukdomar i gallbl\xe5san och gallsten, fokal nodul\xe4r hyperplasi. '],
             ['Metabolism', u' Exacerbation av porfyri. '],
             ['Nervous system', u' Exacerbation av chorea. '],
             ['Reproductive system', u' Hemolytiskt uremiskt syndrom. '],
             ['Eye',
              u' Minskat t\xe5rfl\xf6de, k\xe4nslighet f\xf6r kontaktlinser, optisk neurit, retinalvenstrombos. '],
             ['Other', u' Minskning av folatniv\xe5n i serum. ']]],
           ['Very rare', [['GI', u' Ischemisk kolit.  ']]],
           ['Unknown',
            [['Hepato', u' Leverp\xe5verkan (d.v.s. hepatit, nedsatt leverfunktion).  ']]]],
 '_pages': [9, 11],
 u'_rank': 21,
 u'_type': u'DFSU'}