{'_data': [['Unknown',
            [['Infections',
              u'Herpes zoster Vanliga Ingen k\xe4nd frekvens Sepsis Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens Lunginflammation Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Blood',
              u'Neutropeni med feber Vanliga Vanliga Leukocytos Vanliga Vanliga Neutropeni Vanliga Vanliga Pancytopeni Vanliga Vanliga Trombocytopeni Vanliga Vanliga Anemi Vanliga Ingen k\xe4nd frekvens Leukopeni Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens Lymfopeni Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Metabolism',
              u'Hyperglykemi Mycket vanliga Mycket vanliga Hypokalemi Mycket vanliga Mycket vanliga Hypomagnesemi Mycket vanliga Vanliga Hypernatremi Vanliga Vanliga Ketoacidos Vanliga Vanliga Hypermagnesemi Vanliga Ingen k\xe4nd frekvens Dehydrering Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens V\xe4tskeretention Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Psychiatric', u'F\xf6rvirring Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Nervous system',
              u'Parestesi Mycket vanliga Vanliga Yrsel Mycket vanliga Ingen k\xe4nd frekvens Huvudv\xe4rk Mycket vanliga Ingen k\xe4nd frekvens Kramper Vanliga Ingen k\xe4nd frekvens'],
             ['Eye', u'Suddig syn Vanliga Ingen k\xe4nd frekvens'],
             ['Cardiac',
              u'Takykardi Mycket vanliga Vanliga Hj\xe4rts\xe4cksutgjutning Vanliga Vanliga Ventrikul\xe4r extrasystole Vanliga Ingen k\xe4nd frekvens Hj\xe4rtsvikt Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens Ventrikul\xe4r takykardi Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['Vascular', u'Vaskulit Vanliga Vanliga Hypotoni Vanliga Ingen k\xe4nd frekvens'],
             ['Respiratory',
              u'Differentieringssyndrom Mycket vanliga Mycket vanliga 6 Alla grader Grader >3 Dyspn\xe9 Mycket vanliga Vanliga Hypoxi Vanliga Vanliga Pleurautgjutning Vanliga Vanliga Pleuritisk sm\xe4rta Vanliga Vanliga Pulmon\xe4r alveol\xe4r bl\xf6dning Vanliga Vanliga Pneumonit Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens'],
             ['GI',
              u'Diarr\xe9 Mycket vanliga Vanliga Kr\xe4kningar Mycket vanliga Ingen k\xe4nd frekvens Illam\xe5ende Mycket vanliga Ingen k\xe4nd frekvens Buksm\xe4rta Vanliga Vanliga'],
             ['Skin',
              u'Pruritus Mycket vanliga Ingen k\xe4nd frekvens Hudutslag Mycket vanliga Ingen k\xe4nd frekvens Erytem Vanliga Vanliga Ansikts\xf6dem Vanliga Ingen k\xe4nd frekvens'],
             ['Musculoskeletal',
              u'Myalgi Mycket vanliga Vanliga Artralgi Vanliga Vanliga Sm\xe4rta i benv\xe4vnad Vanliga Vanliga'],
             ['Renal', u'Njursvikt Vanliga Ingen k\xe4nd frekvens'],
             ['General',
              u'Pyrexi Mycket vanliga Vanliga V\xe4rk Mycket vanliga Vanliga Tr\xf6tthet Mycket vanliga Ingen k\xe4nd frekvens \xd6dem Mycket vanliga Ingen k\xe4nd frekvens Br\xf6stsm\xe4rta Vanliga Vanliga Frossa Vanliga Ingen k\xe4nd frekvens'],
             ['Investigations',
              u'Alaninaminotransferas \xf6kat Mycket vanliga Vanliga Aspartataminotransferas \xf6kat Mycket vanliga Vanliga Elektrokardiogram QT f\xf6rl\xe4ngd Mycket vanliga Vanliga Hyperbilirubinemi Vanliga Vanliga \xd6kad blodkreatinin Vanliga Ingen k\xe4nd frekvens \xd6kad vikt Vanliga Ingen k\xe4nd frekvens F\xf6rh\xf6jt gammaglutamyltransferas* Ingen k\xe4nd frekvens Ingen k\xe4nd frekvens']]]],
 '_pages': [4, 7],
 u'_rank': 15,
 u'_type': u'LSFU'}