{'_data': [['Very common',
            [['General',
              u'a: Sm\xe4rta vid injektionsst\xe4llet, f\xf6rh\xe5rdnad vid injektionsst\xe4llet, erytem vid injektionsst\xe4llet.']]],
           ['Common', [['General', u'feber']]],
           ['Unknown',
            [['Immune system', u'Anafylaktoida reaktioner, serumsjuka, chock'],
             ['Nervous system', u'Huvudv\xe4rk \u2212Yrsel'],
             ['Respiratory', u'Astma'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta.'],
             ['Skin', u'Allergiska reaktioner s\xe5som kl\xe5da, utslag, urtikaria.'],
             ['Musculoskeletal', u'Ledv\xe4rk, muskelv\xe4rk.'],
             ['General',
              u'Tr\xf6tthet, sjukdomsk\xe4nsla. Apn\xe9 hos mycket prematura barn (f\xf6dda i graviditetsvecka \u2264 28) (se 4.4 Varningar och f\xf6rsiktighet).']]]],
 '_pages': [3, 4],
 u'_rank': 9,
 u'_type': u'LSFU'}