{'_data': [['Uncommon', [['General', u'']]],
           ['Very rare', [['GI', u'Kr\xe4kningar']]],
           ['Unknown',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Immune system', u'Anafylaktisk chock'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Hypotension'],
             ['GI', u'Illam\xe5ende'],
             ['GI', u'Hudreaktioner'],
             ['Skin', u'Erytem'],
             ['Skin', u'Kl\xe5da  Pruritus'],
             ['Musculoskeletal', u'och Artralgi'],
             ['General', u'llerFeber'],
             ['General', u'Allm\xe4n sjukdomsk\xe4nsla'],
             ['General', u'Frossa']]]],
 '_pages': [4, 5],
 u'_rank': 14,
 u'_type': u'TSFU'}