{'_data': [['Unknown',
            [['Skin',
              u'v\xe4vnad Muskuloskeletala Myalgi, systemet och artralgi* bindv\xe4v Allm\xe4nna symtom Feber, och/eller symtom sjukdomsk\xe4nsla vid , frossa, tr\xf6tthet administrerings- Lokala st\xe4llet reaktioner: rodnad, svullnad, sm\xe4rta, ekkymos, f\xf6rh\xe5rdnader* *Dessa reaktioner f\xf6rsvinner vanligtvis inom 1\u20132 dagar utan behandling. BIVERKNINGAR RAPPORTERADE I SAMBAND MED UPPF\xd6LJNING EFTER GODK\xc4NNANDE F\xd6R F\xd6RS\xc4LJNING F\xf6rutom de reaktioner som observerats vid kliniska pr\xf6vningar har \xe4ven f\xf6ljande biverkningar rapporterats i samband med uppf\xf6ljning efter godk\xe4nnande f\xf6r f\xf6rs\xe4ljning'],
             ['Blood', u'\xd6verg\xe5ende trombocytopeni, \xf6verg\xe5ende lymfadenopati'],
             ['Immune system',
              u'Allergiska reaktioner som i s\xe4llsynta fall leder till chock, angio\xf6dem'],
             ['Nervous system',
              u'Neuralgi, parestesi, feberkramper, neurologiska st\xf6rningar s\xe5som encefalomyelit, neurit och Guillain-Barr\xe9s syndrom'],
             ['Vascular',
              u'Vaskulit, i mycket s\xe4llsynta fall associerad med \xf6verg\xe5ende njurp\xe5verkan'],
             ['Skin',
              u'Generaliserade hudreaktioner inklusive pruritus, urtikaria och icke-specifika utslag']]]],
 '_pages': [3, 4],
 u'_rank': 6,
 u'_type': u'LSFU'}