{'_data': [['Very common', [['Nervous system', u'huvudv\xe4rk']]],
           ['Common',
            [['GI', u'illam\xe5ende Post Marketing Data'],
             ['Blood',
              u'Leukopeni har huvudsakligen rapporterats hos patienter med nedsatt immunf\xf6rsvar.'],
             ['Psychiatric',
              u'yrsel Mindre f\xf6rvirring, hallucinationer, nedsatt medvetande, tremor, agitation'],
             ['Respiratory', u'kr\xe4kningar, diarr\xe9 Mindre obehag i buken'],
             ['Skin', u'utslag inkluderande fotosensitivitet, pruritus Mindre urtikaria']]],
           ['Rare', [['Immune system', u'anafylaxi']]],
           ['Unknown',
            [['Blood', u'leukopeni, trombocytopeni'],
             ['Psychiatric',
              u'Neurologiska besv\xe4r, ibland sv\xe5ra, kan vara kopplade till encefalopati och inkludera f\xf6rvirring, agitation, konvulsioner, hallucinationer, koma. Dessa h\xe4ndelser \xe4r i allm\xe4nhet reversibla och ses vanligtvis hos patienter med njurfunktionsneds\xe4ttning eller d\xe4r andra predisponerande faktorer f\xf6rekommer (se avsnitt 4.4). Hos patienter som genomg\xe5tt organtransplantation och som f\xe5r h\xf6ga doser (8 g dagligen) av valaciklovir vid CMV-profylax, f\xf6rekom neurologiska reaktioner mer frekvent j\xe4mf\xf6rt med d\xe5 l\xe4gre doser anv\xe4ndes vid andra indikationer.'],
             ['Respiratory', u'dyspn\xe9'],
             ['Renal',
              u'njursm\xe4rta, hematuri (ofta i samband med andra biverkningar fr\xe5n njurarna)']]]],
 '_pages': [6, 8],
 u'_rank': 11,
 u'_type': u'LSFU'}