{'_data': [['Common',
            [['Psychiatric', u'emotionelllabilitet '],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'buksm\xe4rta'],
             ['Skin', u'akne'],
             ['Reproductive system',
              u'br\xf6stsm\xe4rta br\xf6stf\xf6rstoring dysmenorr\xe9 metrorragi'],
             ['Investigations', u'vikt\xf6kning']]],
           ['Uncommon',
            [['Infections', u'candidia herpes simplex'],
             ['Immune system', u'allergisk reaktion'],
             ['Metabolism', u'\xf6kad aptit'],
             ['Psychiatric', u'depression nervositet s\xf6mnst\xf6rningar nedsatt libido'],
             ['Nervous system', u'parestesi vertigo'],
             ['Eye', u'synrubbningar'],
             ['Cardiac', u'extrasystole takykardi'],
             ['Vascular', u'lungemboli hypertoni migr\xe4n varicer'],
             ['Respiratory', u'faryngit'],
             ['GI',
              u'illam\xe5ende kr\xe4kningar gastroenterit diarr\xe9 f\xf6rstoppning gastrointestinala besv\xe4r'],
             ['Skin', u'angio\xf6dem alopeci pruritus utslag torr hud seborr\xe9 hudbesv\xe4r'],
             ['Musculoskeletal', u'nacksm\xe4rta sm\xe4rta i extremiteter muskelkramper'],
             ['Renal', u'cystit'],
             ['Reproductive system',
              u'br\xf6stneoplasm fibrocystiska br\xf6st galaktorr\xe9 ovariecysta blodvallningar menstruationsrubbning amenorr\xe9 menorragi vaginal candida vaginit flytning fr\xe5n slidan vulvovaginal sjukdom vaginal torrhet b\xe4ckensm\xe4rta misst\xe4nkta Papanicolaou smear'],
             ['General', u'\xf6dem asteni sm\xe4rta omfattande t\xf6rst \xf6kad svettning'],
             ['Investigations', u'viktminskning']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 11],
 u'_rank': 22,
 u'_type': u'MSFU'}