{'_data': [['Common',
            [['Nervous system',
              u'huvudv\xe4rk, yrsel, s\xf6mnighet, s\xf6mnl\xf6shet, migr\xe4n'],
             ['Psychiatric', u'\xe5ngest'],
             ['GI',
              u'illam\xe5ende, diarr\xe9, f\xf6rstoppning, sm\xe4rta i buken, kr\xe4kningar*'],
             ['Skin', u'\xf6kad svettning'],
             ['Musculoskeletal', u'ryggv\xe4rk'],
             ['General', u'tr\xf6tthet'],
             ['Hepato',
              u'\xf6kade ALAT och/eller ASAT (i kliniska studier observerades \xf6kningar som var > 3 g\xe5nger h\xf6gre \xe4n den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet i ALAT och/eller ASAT hos 1,4 % av de patienter som fick 25 mg agomelatin dagligen och 2,5 % av dem som fick 50 mg dagligen, j\xe4mf\xf6rt med 0,6 % av dem som fick placebo).']]],
           ['Uncommon',
            [['Nervous system', u'parestesi'],
             ['Psychiatric',
              u'agitation och relaterade symptom* (s\xe5som irritabilitet och rastl\xf6shet), aggression*, mardr\xf6mmar*, onormala dr\xf6mmar*'],
             ['Eye', u'dimsyn'],
             ['Skin', u'eksem, pruritus*']]],
           ['Rare',
            [['Psychiatric',
              u'mani/hypomani*. Dessa symptom kan ocks\xe5 bero p\xe5 den underliggande sjukdomen (se avsnitt 4.4), hallucinationer*'],
             ['Skin', u'erytemat\xf6sa hudutslag'],
             ['Hepato',
              u'hepatit, \xf6kat gammaglutamyltransferas * (GGT) (> 3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet), \xf6kat alkaliskt fosfatas * (> 3 g\xe5nger den \xf6vre gr\xe4nsen f\xf6r normalv\xe4rdet), leversvikt*, gulsot*'],
             ['Investigations',
              u'vikt\xf6kning*, viktminskning* *Frekvensen \xe4r ber\xe4knat fr\xe5n spontanrapportering av biverkningar i kliniska pr\xf6vningar.']]],
           ['Unknown',
            [['Psychiatric', u'suicidtankar och suicidalt beteende (se avsnitt 4.4)']]]],
 '_pages': [5, 6],
 u'_rank': 16,
 u'_type': u'LSFU'}