{'_data': [['Common',
            [['Nervous system', u'Yrsel, postural yrsel'],
             ['Vascular', u'Hypotoni, ortostatisk hypotoni'],
             ['Renal', u'Njursvikt och nedsatt njurfunktion']]],
           ['Uncommon',
            [['Ear', u'Vertigo'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Buksm\xe4rta'],
             ['General', u'Tr\xf6tthet'],
             ['Metabolism', u'Hyperkalemi'],
             ['Nervous system', u'Synkope, huvudv\xe4rk'],
             ['Ear', u'Vertigo'],
             ['Cardiac', u'Hj\xe4rtsvikt'],
             ['Respiratory', u'Hosta'],
             ['GI', u'Illam\xe5ende, diarr\xe9'],
             ['Skin', u'Angioneurotiskt \xf6dem'],
             ['Renal', u'Akut njursvikt, f\xf6rh\xf6jt serumkreatinin'],
             ['General', u'Asteni, tr\xf6tthet']]],
           ['Unknown',
            [['Blood', u'S\xe4nkt hemoglobin, s\xe4nkt hematokrit, neutropeni, trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet inklusive serumsjuka'],
             ['Metabolism', u'\xd6kning av serumkalium, hyponatremi'],
             ['Vascular', u'Vaskulit'],
             ['Hepato',
              u'F\xf6rh\xf6jda leverfunktionsv\xe4rden inklusive \xf6kning av serumbilirubin'],
             ['Skin', u'Angioneurotiskt \xf6dem, utslag, kl\xe5da'],
             ['Musculoskeletal', u'Myalgi'],
             ['Renal', u'Njursvikt och nedsatt njurfunktion, f\xf6rh\xf6jt serumkreatinin'],
             ['Blood', u'Trombocytopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet inklusive serumsjuka'],
             ['Metabolism', u'F\xf6rh\xf6jt serumkalium, hyponatremi'],
             ['Vascular', u'Vaskulit'],
             ['Hepato', u'F\xf6rh\xf6jda leverfunktionsv\xe4rden'],
             ['Skin', u'Utslag, kl\xe5da'],
             ['Musculoskeletal', u'Myalgi'],
             ['Renal', u'\xd6kning av urea i blod']]]],
 '_pages': [5, 9],
 u'_rank': 32,
 u'_type': u'LSFU'}