{'_data': [['Common',
            [['Vascular', u's\xe4nkt blodtryck, tromboflebit'],
             ['Respiratory', u'dyspn\xe9, stridor'],
             ['Skin', u'exantem och inflammation i mukosa, pruritus, urtikaria'],
             ['Renal', u'njurinsufficiens manifesterad fr\xe4mst genom \xf6kat serumkreatinin'],
             ['General',
              u'flebit, rodnad p\xe5 \xf6verkroppen och i ansiktet, sm\xe4rta och spasmer i br\xf6st- och ryggmuskler']]],
           ['Uncommon', [['Ear', u'\xf6verg\xe5ende eller permanent h\xf6rselbortfall']]],
           ['Rare',
            [['Blood', u'trombocytopeni, neutropeni, agranulocytos, eosinofili'],
             ['Immune system', u'anafylaktiska reaktioner, \xf6verk\xe4nslighetsreaktioner'],
             ['Ear', u'tinnitus, yrsel'],
             ['GI', u'illam\xe5ende, diarr\xe9'],
             ['Renal', u'interstitiell nefrit, akut njursvikt'],
             ['General',
              u'l\xe4kemedelsframkallad feber, frossa L\xe4kemedelsorsakat utslag med eosinifili och systemiska symtom (DRESS syndrom) har rapporterats efter marknadsf\xf6ring av preparatet.']]],
           ['Very rare',
            [['Cardiac', u'hj\xe4rtstillest\xe5nd'],
             ['Vascular', u'vaskulit'],
             ['GI', u'pseudomembran\xf6s enterokolit'],
             ['Skin',
              u'exfoliativ dermatit, Stevens-Johnsons syndrom, IgA-framkallad bull\xf6s dermatit, Lyells syndrom']]]],
 '_pages': [7, 8],
 u'_rank': 16,
 u'_type': u'LSFU'}