<<<<<<< HEAD
{'_data': [[u'Unknown',
            [['Blood',
              u'Ekkymos,   Slemhinnebl\xf6dning,   gastrointestin   f\xf6rl\xe4ngd bl\xf6dningstid,'],
             ['Immune system', u'Anafylax'],
             ['Endocrine', u'Inadekvat'],
             ['Metabolism', u'Minskad aptit   Vikt\xf6kning   Hyponatremi   (anorexia),'],
             ['Psychiatric',
              u'Onormala   Apati,   Manisk   Delirium, suicidalt   dr\xf6mmar,   hallucinatione   reaktion   beteende,'],
             ['Nervous system',
              u'Muntorrhet   Yrsel,   Myoklonus,   Akatisi/   Malignt   %),   \xf6kad   f\xf6rs\xe4mrad   Psyko-moto   neuroleptikasyndrom   huvudv\xe4rk   muskeltonus   koordination   risk   (NMS),'],
             ['Eye', u'Onormal   Tr\xe5ngvinkelglaukom'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Hj\xe4rtklappnin   Takykardi   QT-f\xf6rl\xe4ngning,'],
             ['Vascular', u'Hypertoni,   Postural   Hypotoni'],
             ['Respiratory', u'G\xe4spning   Pulmonell eosinofili'],
             ['Hepato', u'Hepatit, onormala   leverfunktionsprover'],
             ['Skin',
              u'Svettning   Hudutslag,   Erythema multiforme,   (inklusive   alopeci,   toxisk epidermal'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Renal', u'F\xf6rs\xe4mrad   Urinretention Urin-inkonti   urinering   nens'],
             ['Reproductive system', u'Onormal   Onormal'],
             ['General', u'Asteni'],
             ['General', u'frossbrytninga']]]],
 '_pages': [8, 11],
 u'_rank': 18,
 u'_type': u'LFSU'}
=======
{'_data': [['Very common',
            [['Nervous system', u'Muntorrhet %), huvudv\xe4rk (30,3%)*'],
             ['GI', u'Illam\xe5ende (20,0%)'],
             ['Skin', u'Svettning (inklusive nattlig svettning) (12,2%)']]],
           ['Common',
            [['Metabolism',
              u'Minskad aptit (anorexia), f\xf6rh\xf6jt serumkoles-terol, viktminskning'],
             ['Psychiatric',
              u'Onormala dr\xf6mmar, s\xe4nkt libido, insomnia, nervositet, parestesier, sedation, f\xf6rvirring, personlighets-f\xf6r\xe4ndring'],
             ['Nervous system', u'Yrsel, \xf6kad muskeltonus (hypertoni) tremor'],
             ['Eye', u'Onormal ackommodati on mydriasis, synst\xf6rning'],
             ['Cardiac', u'Hj\xe4rtklappnin g'],
             ['Vascular',
              u'Hypertoni, vasodilatation (mest v\xe4rmevall-ningar/ blodvallninga r)'],
             ['Respiratory', u'G\xe4spning'],
             ['GI', u'F\xf6rstoppning, kr\xe4kning'],
             ['Renal',
              u'F\xf6rs\xe4mrad urinering (mest sv\xe5righeter att komma ig\xe5ng), pollakisuri'],
             ['Reproductive system',
              u'Onormal ejakulation/ orgasm (m\xe4n), anorgasmi, erektil dysfunktion (impotens), menstruations -st\xf6rningar s\xe5som \xf6kad bl\xf6dning eller mer oregelbunden bl\xf6dning (t.ex. menorrhagi, metrorrhagi)'],
             ['General', u'Asteni (tr\xf6tthet), frossbrytninga']]],
           ['Uncommon',
            [['Blood', u'Ekkymos, gastrointestin al bl\xf6dning'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['Psychiatric', u'Apati, hallucinatione r, agitation'],
             ['Nervous system', u'Myoklonus, f\xf6rs\xe4mrad koordination och balans'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Takykardi'],
             ['Vascular', u'Postural hypotoni, synkope'],
             ['GI', u'Bruxism, diarr\xe9 f\xf6r\xe4ndrad smakupplevel se'],
             ['Skin', u'Hudutslag, alopeci, Ljus-k\xe4nslighets-reaktion, angio\xf6dem'],
             ['Renal', u'Urinretention Urin'],
             ['Reproductive system', u'Onormal orgasm (kvinnor)']]],
           ['Rare',
            [['Psychiatric', u'Manisk reaktion'],
             ['Nervous system', u'Akatisi/ Psyko-motorisk rastl\xf6shet, kramper'],
             ['Renal', u'inkontinens']]],
           ['Unknown',
            [['Blood',
              u'Slemhinnebl\xf6dning, f\xf6rl\xe4ngd bl\xf6dningstid, trombocytopeni, bloddyskrasier (inklusive agranulocytos, aplastisk anemi, neutropeni och pancytopeni)'],
             ['Immune system', u'Anafylax'],
             ['Endocrine', u'Inadekvat ADH-sekretion (SIADH), \xf6kat prolaktin'],
             ['Metabolism', u'Hyponatremi'],
             ['Psychiatric', u'Delirium, suicidalt beteende, suicidtankar**, aggression***'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom (NMS), serotonergt syndrom, extrapyramidala reaktioner (inklusive dystoni och dyskinesi), tardiv dyskinesi, yrsel'],
             ['Eye', u'Tr\xe5ngvinkelglaukom'],
             ['Cardiac',
              u'QT-f\xf6rl\xe4ngning, kammarflimmer, kammartakykardi (inklusive Torsade de Pointes)'],
             ['Vascular', u'Hypotoni'],
             ['Respiratory', u'Pulmonell eosinofili'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit, onormala leverfunktionsprover'],
             ['Skin',
              u'Erythema multiforme, toxisk epidermal nekrolys, Stevens-Johnsons syndrom kl\xe5da, n\xe4sselutslag'],
             ['Musculoskeletal', u'Rabdomyolys']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 11],
 u'_rank': 42,
 u'_type': u'MSFU'}
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
