{'_data': [[u'Unknown',
            [['Blood',
              u'Ekkymos,   Slemhinnebl\xf6dning,   gastrointesti-   f\xf6rl\xe4ngd bl\xf6dningstid,'],
             ['Metabolism',
              u'F\xf6rh\xf6jt   Vikt\xf6kning   Onormala   serum-   leverfunktionsprover,'],
             ['Nervous system',
              u'Muntorrhet   Onormala   Apati,   Akatisi/   Malignt   %),   dr\xf6mmar,   Hallucination-   Psyko-   Neuroleptika-   huvudv\xe4rk   s\xe4nkt libido,   er,   motorisk   syndrom (NMS),'],
             ['Special Senses', u'Onormal   F\xf6r\xe4ndrad   Tr\xe5ngvinkel-'],
             ['Vascular', u'vasodilatation   hypotoni,   f\xf6rl\xe4ngning,'],
             ['Respiratory', u'G\xe4spning   Pulmonell eosinofili'],
             ['GI', u'Illam\xe5ende   Minskad aptit   Bruxism,   Pankreatit'],
             ['Skin', u'Svettning   Hudutslag,   Erythema multiforme,'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Reproductive system', u'Onormal   Onormal   Urin-'],
             ['Systemic',
              u'Asteni   Angio\xf6dem,   Anafylaxi   (tr\xf6tthet),   ljusk\xe4nslighet']]]],
 '_pages': [8, 10],
 u'_rank': 11,
 u'_type': u'LFSU'}