{'_data': [['Very common',
            [['Nervous system', u'Muntorrhet %), huvudv\xe4rk (30,3 %)*'],
             ['Cardiac', u'och'],
             ['GI', u'Illam\xe5ende (20,0 %)'],
             ['Skin', u'Svettning (inklusive nattsvettning ) [12,2 %]'],
             ['Systemic',
              u'* F\xf6rekomsten av huvudv\xe4rk i poolade kliniska studier var 30,3 % med venlafaxin och 31.3 % med placebo. ** Fall av suicidtankar och suicidalt beteende har rapporterats under behandling med venlafaxin eller direkt efter avslutad behandling (se avsnitt 4.4), *** Se avsnitt 4.4 Avbrytande av venlafaxinbehandling (s\xe4rskilt n\xe4r det sker abrupt) medf\xf6r ofta uts\xe4ttningssymtom. Yrsel, k\xe4nselst\xf6rningar (inklusive parestesier), s\xf6mnst\xf6rningar (inklusive insomni och intensiva dr\xf6mmar), agitation eller \xe5ngest, illam\xe5ende och/eller kr\xe4kningar, tremor, vertigo, huvudv\xe4rk och influensaliknande symtom \xe4r de vanligast rapporterade biverkningarna. I allm\xe4nhet \xe4r dessa symtom milda till m\xe5ttliga och upph\xf6r spontant, men hos vissa patienter kan de vara sv\xe5ra och/eller l\xe5ngvariga. D\xe4rf\xf6r rekommenderas ett stegvis uts\xe4ttande n\xe4r behandling med venlafaxin ska avslutas (se avsnitt 4.2 och 4.4). Barn och ungdomar I allm\xe4nhet var biverkningsprofilen f\xf6r venlafaxin (i placebokontrollerade kliniska studier) hos barn och ungdomar (6 till 17 \xe5r) liknande den som s\xe5gs hos vuxna. Liksom hos vuxna observerades minskad aptit, viktminskning, f\xf6rh\xf6jt blodtryck och f\xf6rh\xf6jt serumkolesterol (se avsnitt 4.4). I kliniska studier p\xe5 barn och ungdomar observerades sj\xe4lvmordstankar som biverkning. Det f\xf6rekom \xe4ven ett \xf6kat antal rapporter om fientlighet och, i synnerhet vid egentlig depression, sj\xe4lvskador. I synnerhet observerades f\xf6ljande biverkningar hos barn och ungdomar: buksm\xe4rta, agitation, dyspepsi, ekkymos, epistaxis och myalgi.']]],
           ['Common',
            [['Metabolism', u'F\xf6rh\xf6jt serumkolesterol, viktminskning'],
             ['Nervous system',
<<<<<<< HEAD
              u'Onormala dr\xf6mmar, s\xe4nkt libido, yrsel, \xf6kad muskeltonus (hypertoni), insomnia, nervositet, parestesier, sedation, tremor, f\xf6rvirring, personlighets-f\xf6r\xe4n dring'],
=======
              u'Onormala dr\xf6mmar, s\xe4nkt libido, yrsel, \xf6kad muskeltonus (hypertoni), insomnia, nervositet, parestesier, sedation, tremor, f\xf6rvirring, personlighets-f\xf6r\xe4ndring'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Special Senses', u'Onormal ackommodation, mydriasis, synst\xf6rning'],
             ['Cardiac', u'Hypertoni,'],
             ['Vascular',
              u'vasodilatation (mest v\xe4rmevallningar/ blodvallningar), hj\xe4rtklappning'],
             ['Respiratory', u'G\xe4spning'],
             ['GI', u'Minskad aptit (anorexi), f\xf6rstoppning, kr\xe4kning'],
             ['Reproductive system',
<<<<<<< HEAD
              u'Onormal ejakulation/orgasm (m\xe4n), anorgasmi, erektil dysfunktion (impotens), f\xf6rs\xe4mrad urinering (mest sv\xe5righeter att komma ig\xe5ng), menstruations-st\xf6rn ingar s\xe5som \xf6kad bl\xf6dning eller mer oregelbunden bl\xf6dning (t.ex. menorragi, metrorragi), pollakisuri'],
=======
              u'Onormal ejakulation/orgasm (m\xe4n), anorgasmi, erektil dysfunktion (impotens), f\xf6rs\xe4mrad urinering (mest sv\xe5righeter att komma ig\xe5ng), menstruations-st\xf6rningar s\xe5som \xf6kad bl\xf6dning eller mer oregelbunden bl\xf6dning (t.ex. menorragi, metrorragi), pollakisuri'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Systemic', u'Asteni (tr\xf6tthet), frossbrytningar']]],
           ['Uncommon',
            [['Blood', u'Ekkymos, gastrointestinal bl\xf6dning'],
             ['Metabolism', u'Vikt\xf6kning'],
             ['Nervous system',
              u'Apati, hallucinationer, myoklonus, agitation, f\xf6rs\xe4mrad koordination och balans'],
             ['Special Senses', u'F\xf6r\xe4ndrad smakupplevelse, tinnitus'],
             ['Cardiac', u'Postural hypotoni,'],
             ['Vascular', u'synkope, takykardi'],
             ['GI', u'Bruxism, diarr\xe9'],
             ['Skin', u'Hudutslag, alopeci'],
             ['Reproductive system', u'Onormal orgasm (kvinnor), urinretention'],
<<<<<<< HEAD
             ['Systemic', u'Angio\xf6dem, Ljusk\xe4nslighets-reakt ion']]],
           ['Rare',
            [['Nervous system',
              u'Akatisi/psyko-m otorisk rastl\xf6shet, kramper, manisk reaktion'],
=======
             ['Systemic', u'Angio\xf6dem, Ljusk\xe4nslighets-reaktion']]],
           ['Rare',
            [['Nervous system',
              u'Akatisi/psyko-motorisk rastl\xf6shet, kramper, manisk reaktion'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Reproductive system', u'Urininkontinens']]],
           ['Unknown',
            [['Blood',
              u'Slemhinnebl\xf6dning, f\xf6rl\xe4ngd bl\xf6dningstid, trombocytopeni, bloddyskrasier (inklusive agranulocytos, aplastisk anemi, neutropeni och pancytopeni)'],
             ['Metabolism',
              u'Onormala leverfunktionsprover, hyponatremi, hepatit, inadekvat ADH-sekretion (SIADH), f\xf6rh\xf6jt prolaktin'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom (NMS), serotonergt syndrom, delirium, extrapyramidala reaktioner (inklusive dystoni och dyskinesi), tardiv dyskinesi, suicidalt beteende, suicidtankar** Vertigo Aggression***'],
             ['Special Senses', u'Tr\xe5ngvinkelglaukom'],
<<<<<<< HEAD
             ['Cardiac', u'Hypotoni,'],
             ['Vascular',
              u'QT-f\xf6rl\xe4gning, kammarflimmer, kammartakykardi (inklusive torsade de pointes)'],
=======
             ['Cardiac', u'Hypotoni, QT'],
             ['Vascular',
              u'f\xf6rl\xe4gning, kammarflimmer, kammartakykardi (inklusive torsade de pointes)'],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
             ['Respiratory', u'Pulmonell eosionofili'],
             ['GI', u'Pankreatit'],
             ['Skin',
              u'Erythema multiforme, toxisk epidermal nekrolys, Stevens-Johnsons syndrom, kl\xe5da, n\xe4sselutlag'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Systemic', u'Anafylaxi']]]],
 '_note': u' ?MSFU',
 '_pages': [9, 11],
 u'_rank': 37,
 u'_type': u'MSFU'}