{'_data': [['Very common',
            [['Blood',
              u'S\xe4nkt hematokrit och minskad koncentration av plasmaproteiner p\xe5 grund av sp\xe4dning.'],
             ['Investigations',
              u'Infusion av hydroxietylst\xe4rkelse leder till \xf6kade serum \u03b1-amylasniv\xe5er. Denna effekt \xe4r ett resultat av bildandet av ett amylaskomplex av hydroxietylst\xe4rkelse med f\xf6rdr\xf6jd renal och extrarenal elimination. Detta f\xe5r inte misstolkas som en pankreasst\xf6rning.']]],
           ['Common',
            [['Blood',
              u'St\xf6rre doser av hydroxietylst\xe4rkelse leder till sp\xe4dning av koagulationsfaktorer och kan d\xe4rmed p\xe5verka blodkoagulationen. Bl\xf6dningstid och aPTT kan f\xf6rl\xe4ngas och niv\xe5n p\xe5 FVIII/vWF komplex kan reduceras efter administration av stora doser. Se 4.4 \u201cVarningar och f\xf6rsiktighetsm\xe5tt\u201d']]],
           ['Uncommon',
            [['General',
              u'Upprepade infusioner av HES under flera dagar, i synnerhet d\xe5 h\xf6ga kumulativa doser uppn\xe5s, leder i allm\xe4nhet till kl\xe5da som knappast svarar p\xe5 n\xe5gon terapi. S\xe5dan kl\xe5da kan uppkomma flera veckor efter avslutade st\xe4rkelseinfusioner och kan kvarst\xe5 i m\xe5nader. Sannolikheten f\xf6r denna o\xf6nskade effekt har inte studerats tillr\xe4ckligt med Venofundin .']]],
           ['Rare',
            [['Immune system',
              u'Efter administrering av hydroxietylst\xe4rkelse kan anafylaktisk reaktion av varierande grad uppkomma. D\xe4rf\xf6r m\xe5ste alla patienter som f\xe5r st\xe4rkelseinfusioner \xf6vervakas noggrant med avseende p\xe5 anafylaktisk reaktion. Vid anafylaktisk reaktion skall infusionen omedelbart avbrytas och sedvanlig akutbehandling ges. Det g\xe5r inte att f\xf6ruts\xe4ga med tester vilka patienter som kan f\xf6rv\xe4ntas f\xe5 en anafylaktisk reaktion, och det g\xe5r heller inte att f\xf6ruts\xe4ga f\xf6rlopp och allvarlighetsgrad vid en s\xe5dan reaktion. Profylax med kortikosteroider har inte visat sig effektivt.']]]],
 '_pages': [3, 4],
 u'_rank': 5,
 u'_type': u'LSFU'}