{'_data': [['Common',
            [['Eye',
              u' f\xf6rh\xf6jt intraokul\xe4rt tryck, dimsyn, \xf6gonsm\xe4rta, \xf6gonuts\xf6ndring, \xf6gonobehag och k\xe4nsla av fr\xe4mmande kropp i \xf6gat.']]],
           ['Uncommon',
            [['Infections', u' faryngit, rinit'],
             ['Eye',
              u' ulcer\xf6s keratit, korneal erosion, keratit, fibrin i fr\xe4mre kammaren, torra \xf6gon, fotofobi, kornealt \xf6dem, korneala infiltrat, korneal missf\xe4rgning, \xf6gon\xf6dem, konjunktivalt \xf6dem, \xf6gonkl\xe5da, onormal k\xe4nsla i \xf6gat, \xf6gonirritation, \xf6kad t\xe5rproduktion, \xf6gonhyperemi och krustor p\xe5 \xf6gonlockens kanter.'],
             ['Eye', u' hypotoni ']]],
           ['Rare',
            [['Immune system', u' \xf6verk\xe4nslighet'],
             ['Eye', u' makula\xf6dem och \xf6gonlocks\xf6dem.']]],
           ['Unknown',
            [['Eye', u' nedsatt synsk\xe4rpa.'], ['General', u' br\xf6stsm\xe4rta  ']]]],
 '_pages': [3, 4],
 u'_rank': 8,
 u'_type': u'LSFU2'}