{'_data': [['Very common',
            [['Psychiatric', u'Huvudv\xe4rk'],
             ['Eye',
              u'Synst\xf6rningar (inklusive dimsyn (se avsnitt 4.4), kromatopsi och fotofobi)'],
             ['Cardiac', u'Perifert \xf6dem'],
             ['GI', u'Magsm\xe4rtor, illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Skin', u'Hudutslag'],
             ['Renal', u'Feber']]],
           ['Common',
            [['Infections', u'Gastroenterit, influensasyndrom'],
             ['Blood',
              u'Pancytopeni, benm\xe4rgsdepression, leukopeni, trombocytopeni, anemi, purpura'],
             ['Immune system', u'Sinuit'],
             ['Metabolism', u'hypokalemi'],
             ['Psychiatric', u'Depression, hallucinationer, \xe5ngest,'],
             ['Psychiatric', u'Yrsel, f\xf6rvirring, tremor, agitation, parestesi'],
             ['Vascular', u'Tromboflebit, hypotoni, flebit'],
             ['Vascular',
              u'Akut respiratoriskt distressyndrom, lung\xf6dem, respiratoriskt distress, br\xf6stsm\xe4rtor'],
             ['Hepato', u'Gulsot, kolestatisk gulsot,'],
             ['Skin',
              u'Exfoliativ dermatit, ansikts\xf6dem, fototoxiskreaktion, makulopapul\xe4ra utslag, makula utslag, papul\xf6sa utslag, keilit, pruritis, alopeci, erytem'],
             ['Skin', u'Ryggsm\xe4rtor'],
             ['Renal', u'Akut njursvikt, hematuri'],
             ['Renal', u'(Reaktion/inflammation vid injektionsst\xe4llet), frossa, asteni'],
             ['Investigations',
              u'F\xf6rh\xf6jda leverfunktionsv\xe4rden (inklusive ASAT, ALAT, alkaliskt fosfatas, GGT, LDH, bilirubin), f\xf6rh\xf6jda blodkreatinv\xe4rden']]],
           ['Uncommon',
            [['Blood',
              u'Disseminerad intravaskul\xe4r koagulation, agranulocytos, lymfadenopati, eosinofili'],
             ['Immune system', u'Anafylaktoid reaktion, \xf6verk\xe4nslighet'],
             ['Endocrine', u'Binjuresinsufficiens'],
             ['Psychiatric', u'Hj\xe4rn\xf6dem, ataxi, diplopi, vertigo, hypoestesi'],
             ['Eye',
              u'Papill\xf6dem (se avsnitt 4.4), synnervsst\xf6rning (inklusive optikusneurit, se avsnitt 4.4), nystagmus, sklerit, blefarit'],
             ['Cardiac',
              u'Kammarflimmer, ventrikul\xe4r arytmi, synkope, supraventrikul\xe4r arytmi, supraventrikul\xe4r takykardi, takykardi, bradykardi'],
             ['GI',
              u'Pankreatit, peritonit, duodenit, gingivit, glossit, tung\xf6dem, dyspepsi, f\xf6rstoppning'],
             ['Hepato', u'Leversvikt, hepatit, f\xf6rstorad lever, kolecystit, kolelitiasis'],
             ['Skin',
              u'Stevens-Johnson syndrom, angioneurotisk \xf6dem, allergisk dermatit, urtikaria, l\xe4kemedelsutslag, psoriasis'],
             ['Skin', u'Artrit'],
             ['Renal', u'Proteinuri, nefrit'],
             ['Investigations',
              u'F\xf6rl\xe4ngning av QT-intervallet, f\xf6rh\xf6jt urea, f\xf6rh\xf6jda kolesterolv\xe4rden Beskrivning av ett urval biverkningar Synst\xf6rningar I kliniska studier var behandlingsrelaterade synst\xf6rningar med vorikonazol mycket vanliga. I dessa studier, omfattande korttids- s\xe5v\xe4l som l\xe5ngtidsbehandling, upplevde ca 30% av f\xf6rs\xf6kspersonerna 17 f\xf6r\xe4ndrad / f\xf6rst\xe4rkt synupplevelse, dimsyn, f\xf6r\xe4ndrat f\xe4rgseende eller ljusskygghet. Dessa synst\xf6rningar var \xf6verg\xe5ende och fullst\xe4ndigt reversibla, merparten gick spontant \xf6ver inom 60 minuter och inga kliniskt signifikanta l\xe5ngtidseffekter av synen observerades. Det fanns bel\xe4gg f\xf6r att de mildras vid upprepad dosering av vorikonazol. Synst\xf6rningarna var vanligtvis milda, resulterade s\xe4llan i avbrytande av behandlingen och sattes inte i samband med l\xe5ngtidseffekter. Synst\xf6rningar kan t\xe4nkas ha ett samband med h\xf6gre plasmakoncentrationer och/eller doser. Verkningsmekanismen \xe4r oklar, men reaktionen sker med stor sannolikhet i retina. I en studie p\xe5 friska frivilliga av vorikonazols inverkan p\xe5 retinafunktionen, orsakade vorikonazol en minskning av elektroretinogram (ERG)-v\xe5gornas amplitud. ERG m\xe4ter elektriska str\xf6mmar i retina. N\xe5gon f\xf6r\xe4ndring av ERG efter 29 dagars behandling noterades inte och samtliga f\xf6r\xe4ndringar var helt reversibla efter uts\xe4ttande av vorikonazol. Hudreaktioner Hudreaktioner var vanliga hos patienter som behandlats med vorikonazol i kliniska pr\xf6vningar. Dessa patienter hade dock allvarliga bakomliggande sjukdomar och behandlades med ett flertal andra l\xe4kemedel samtidigt. Sv\xe5righetsgraden av merparten av hudutslagen var mild till m\xe5ttlig. I s\xe4llsynta fall har patienter utvecklat allvarliga hudreaktioner inklusive Stevens-Johnsons syndrom, toxisk epidermal nekrolys och erytema multiforme vid behandling med VFEND. Patienter som f\xe5r hudutslag ska observeras noga och VFEND ska s\xe4ttas ut om hudf\xf6r\xe4ndringarna f\xf6r v\xe4rras. Vid framf\xf6rallt l\xe5ngtidsbehandling har fotosensitivitetsreaktioner rapporterats (se avsnitt 4.4). Leverfunktionsprover Den sammanlagda incidensen av kliniskt signifikanta transaminasavvikelser i det kliniska programmet med vorikonazol var 13,4% (200/1493) hos patienter som behandlats med vorikonazol. Avvikelser i leverfunktionsprover kan eventuellt s\xe4ttas i samband med h\xf6gre plasmakoncentrationer och/eller doser. Merparten av de onormala leverfunktionsproverna \xe5tergick till det normala under behandlingen utan dosjustering, eller efter dosjustering inkluderande avbrytande av behandlingen. Vorikonazol har i f\xe5 fall satts i samband med allvarliga fall av levertoxicitet hos patienter med andra allvarliga bakomliggande tillst\xe5nd. Dessa inkluderar fall av ikterus, och s\xe4llsynta fall av hepatit och leversvikt som lett till d\xf6den (se avsnitt 4.4).']]],
           ['Rare',
            [['Infections', u'Pseudomembran\xf6s kolit'],
             ['Endocrine', u'hypotyreoidism'],
             ['Psychiatric', u'S\xf6mnl\xf6shet Centrala och perifera'],
             ['Psychiatric',
              u'Krampanfall, encefalopati, Guillain Barre-syndrom, extrapyramidalsymtom, (s\xf6mnighet under infusion), perifer neuropati'],
             ['Eye',
              u'Optisk atropi, n\xe4thinnebl\xf6dning, okulogyration, hornhinnegrumling'],
             ['Ear', u'Hyperakusi, tinnitus'],
             ['Cardiac',
              u'Torsades de pointes, ventrikul\xe4r takykardi, totalt AV-block, grenblock, nodal arytmi'],
             ['Vascular', u'Lymfangit 16 Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['GI', u'F\xf6r\xe4ndrad smakk\xe4nsla'],
             ['Hepato', u'Leverkoma'],
             ['Skin',
              u'Toxisk epidermal nekrolys, erytema multiforme, diskoid lupus erytematosus, pseudoporfyri Muskuloskeletala systemet och bindv\xe4v'],
             ['Skin', u'Hypertoni'],
             ['Renal',
              u'Tubul\xe4r njurnekros Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Unknown', [['Skin', u'Periostit']]]],
 '_pages': [14, 17],
 u'_rank': 46,
 u'_type': u'LSFU'}