{'_data': [['Very common',
            [['Psychiatric', u'Huvudv\xe4rk'],
             ['Eye',
              u'Synst\xf6rningar (inklusive dimsyn (se avsnitt 4.4), kromatopsi och fotofobi)'],
             ['Cardiac', u'Perifert \xf6dem'],
             ['GI', u'Magsm\xe4rtor, illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Skin', u'Hudutslag'],
             ['Renal', u'Feber']]],
           ['Common',
            [['Infections', u'Gastroenterit, influensasyndrom'],
             ['Blood',
              u'Pancytopeni, benm\xe4rgsdepression, leukopeni, trombocytopeni, anemi, purpura,'],
             ['Immune system', u'Sinuit'],
             ['Metabolism', u'hypokalemi'],
             ['Psychiatric', u'Depression, hallucinationer, \xe5ngest,'],
             ['Psychiatric', u'Yrsel, f\xf6rvirring, tremor, agitation, parestesi'],
             ['Vascular', u'Tromboflebit, hypotoni, flebit'],
             ['Vascular',
              u'Akut respiratoriskt distressyndrom, lung\xf6dem, respiratoriskt distress, br\xf6stsm\xe4rtor'],
             ['Hepato', u'Gulsot, kolestatisk gulsot,'],
             ['Skin',
              u'Exfoliativ dermatit, ansikts\xf6dem, fototoxiskreaktion, makulopapul\xe4ra utslag, makula utslag, papul\xf6sa utslag, keilit, pruritis, alopeci, erytem'],
             ['Skin', u'Ryggsm\xe4rtor'],
             ['Renal', u'Akut njursvikt, hematuri'],
             ['Renal', u'(Reaktion/inflammation vid injektionsst\xe4llet), frossa, asteni'],
             ['Investigations',
              u'F\xf6rh\xf6jda leverfunktionsv\xe4rden (inklusive ASAT, ALAT, alkaliskt fosfatas, GGT, LDH, bilirubin), f\xf6rh\xf6jda blodkreatinv\xe4rden']]],
           ['Uncommon',
            [['Blood',
              u'Disseminerad intravaskul\xe4r koagulation, agranulocytos, lymfadenopati, eosinofili'],
             ['Immune system', u'Anafylaktoid reaktion, \xf6verk\xe4nslighet'],
             ['Endocrine', u'Binjuresinsufficiens'],
             ['Psychiatric', u'Hj\xe4rn\xf6dem, ataxi, diplopi, vertigo, hypoestesi'],
             ['Eye',
              u'Papill\xf6dem (se avsnitt 4.4), synnervsst\xf6rning (inklusive optikusneurit, se avsnitt 4.4), nystagmus, sklerit, blefarit'],
             ['Cardiac',
              u'Kammarflimmer, ventrikul\xe4r arytmi, synkope, supraventrikul\xe4r arytmi, supraventrikul\xe4r takykardi, takykardi, bradykardi'],
             ['GI',
              u'Pankreatit, peritonit, duodenit, gingivit, glossit, tung\xf6dem, dyspepsi, f\xf6rstoppning'],
             ['Hepato', u'Leversvikt, hepatit, f\xf6rstorad lever, kolecystit, kolelitiasis'],
             ['Skin',
              u'Stevens-Johnson syndrom, angioneurotisk \xf6dem, allergisk dermatit, urtikaria, l\xe4kemedelsutslag, psoriasis'],
             ['Skin', u'Artrit'],
             ['Renal', u'Proteinuri, nefrit'],
             ['Investigations',
              u'F\xf6rl\xe4ngning av QT-intervallet, f\xf6rh\xf6jt urea, f\xf6rh\xf6jda kolesterolv\xe4rden']]],
           ['Rare',
            [['Infections', u'Pseudomembran\xf6s kolit'],
             ['Endocrine', u'hypotyreoidism'],
             ['Psychiatric', u'S\xf6mnl\xf6shet Centrala och perifera'],
             ['Psychiatric',
              u'Krampanfall, encefalopati, Guillain Barre-syndrom, extrapyramidalsymtom, (s\xf6mnighet under infusion), perifer neuropati'],
             ['Eye',
              u'Optisk atropi, n\xe4thinnebl\xf6dning, okulogyration, hornhinnegrumling'],
             ['Ear', u'Hyperakusi, tinnitus'],
             ['Cardiac',
              u'Torsades de pointes, ventrikul\xe4r takykardi, totalt AV-block, grenblock, nodal arytmi'],
             ['Vascular', u'Lymfangit Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['GI', u'F\xf6r\xe4ndrad smakk\xe4nsla'],
             ['Hepato', u'Leverkoma'],
             ['Skin',
              u'Toxisk epidermal nekrolys,erytema multiforme, diskoid lupus erytematosus, pseudoporfyri Muskuloskeletala systemet och bindv\xe4v'],
             ['Skin', u'Hypertoni'],
             ['Renal',
              u'Tubul\xe4r njurnekros Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet']]],
           ['Unknown', [['Skin', u'Periostit']]]],
 '_pages': [13, 16],
 u'_rank': 46,
 u'_type': u'LSFU'}