{'_data': [['Very common', [['Nervous system', u'dysgeusi'], ['GI', u'illam\xe5ende']]],
           ['Common',
            [['Infections', u'svampinfektion'],
             ['Psychiatric', u's\xf6mnl\xf6shet'],
             ['Nervous system', u'huvudv\xe4rk, yrsel'],
             ['GI', u'f\xf6rstoppning, diarr\xe9, kr\xe4kningar'],
             ['Hepato',
              u'f\xf6rh\xf6jt alaninaminotransferas, f\xf6rh\xf6jt aspartataminotransferas'],
             ['Skin', u'Authorisation pruritus, hudutslag'],
             ['Renal',
              u'akut njursvikt, f\xf6rh\xf6jt serumkreatinin, skummande urin (lower level term)']]],
           ['Uncommon',
            [['Infections', u'clostridiumkolit, urinv\xe4gsinfektioner'],
             ['Blood',
              u'anemi, leukopeni, trombocytemi, trombocytopeni, \xf6kat antal eosinofiler, \xf6kat antal neutrofiler Marketing Immunsystemet'],
             ['Blood', u'\xf6verk\xe4nslighet'],
             ['Metabolism',
              u'minskad aptit, hyperglykemi, hyperkalemi, hypoglykemi, hypokalemi, hypomagnesemi 18'],
             ['Psychiatric', u'agitation, \xe5ngest, f\xf6rvirringstillst\xe5nd, depression'],
             ['Nervous system', u'ageusi, migr\xe4n, parestesi, parosmi, somnolens, tremor'],
             ['Eye', u'\xf6gonirritation, dimsyn'],
             ['Ear', u'tinnitus'],
             ['Cardiac',
              u'angina pectoris, f\xf6rmaksflimmer, bradykardi, kronisk hj\xe4rtsvikt, korrigerat f\xf6rl\xe4ngt QT-intervall, palpitationer, sinustakykardi, supraventrikul\xe4ra extrasystolier, ventrikul\xe4ra extrasystolier Blodk\xe4rl Suspended'],
             ['Cardiac', u'rodnad, hypertension, hypotension, flebit'],
             ['Respiratory', u'dyspn\xe9, hicka, n\xe4st\xe4ppa, svalgsm\xe4rta'],
             ['GI',
              u'magsm\xe4rta, muntorrhet, dyspepsi, v\xe4dersp\xe4nning, oral hypoestesi'],
             ['Hepato', u'hepatit'],
             ['Skin', u'erytem, ansikts\xf6dem, hyperhidros, urtikaria'],
             ['Musculoskeletal', u'artralgi, ryggsm\xe4rta, muskelkramper, myalgi'],
             ['Renal',
              u'f\xf6rh\xf6jt S-urea, dysuri, hematuri, mikroalbuminuri, oliguri, pollakuri, nedsatt njurfunktion, onormal urinlukt'],
             ['General',
              u'asteni, reaktioner p\xe5 infusionsst\xe4llet, sjukdomsk\xe4nsla, br\xf6stsm\xe4rta utan kardiell orsak, perifert \xf6dem, sm\xe4rta, feber, \u201dRed Man\u201d-syndrom'],
             ['Investigations', u'\xf6kat internationellt normaliserat ratio']]],
           ['Rare', [['Ear', u'd\xf6vhet']]],
           ['Unknown', [['Blood', u'anafylaxi'], ['General', u'tr\xf6tthet, frossa']]]],
 '_pages': [5, 7],
 u'_rank': 30,
 u'_type': u'LSFU'}