{'_data': [['Common', [['GI', u' Illam\xe5ende, kr\xe4kningar, diarr\xe9.  ']]],
           ['Uncommon', [['Skin', u' Exantem, urtikaria, fotosensibilitet.  ']]],
           ['Rare',
            [['General', u' anafylaktisk chock, anafylaktisk reaktion  '],
             ['Blood', u' Trombocytopeni.  '],
             ['Nervous system', u' \xd6kat intrakraniellt tryck. '],
             ['GI', u' Pseudomembran\xf6s colit. '],
             ['Skin', u' Onykolys, erytema multiforme, mukokutant syndrom. ']]]],
 '_pages': [4, 4],
 u'_rank': 7,
 u'_type': u'DFSU'}