{'_data': [['Very common',
            [['Blood', u'Anemi*, neutropeni*'],
             ['Metabolism', u'Minskad aptit*'],
             ['Psychiatric', u'Oro*, depression*, insomnia, irritabilitet'],
             ['Nervous system', u'Yrsel*, huvudv\xe4rk*'],
             ['Respiratory', u'Hosta*, dyspn\xe9*'],
             ['GI', u'Diarr\xe9*, illam\xe5ende*, kr\xe4kningar*, muntorrhet, dysgeusi'],
             ['Skin', u'Alopeci, torr hud, pruritus, utslag'],
             ['Musculoskeletal', u'Artralgi, myalgi'],
             ['General', u'Asteni*, frossa, tr\xf6tthet*, feber*, influensaliknande symtom'],
             ['Investigations', u'Viktnedg\xe5ng']]],
           ['Common',
            [['Infections',
              u'Bronkit*, cellulit*, herpes simplex, influensa, oral svampinfektion, sinusit'],
             ['Blood', u'Leukopeni*, trombocytopeni*'],
             ['Endocrine', u'Struma, hypotyreoidism'],
             ['Metabolism', u'Dehydrering*, hyperglykemi*, hypertriglyceridemi, hyperurikemi'],
             ['Psychiatric',
              u'Affektlabilitet, agitation, libidost\xf6rning, hum\xf6rf\xf6r\xe4ndringar, s\xf6mnst\xf6rning'],
             ['Nervous system',
              u'Hypestesi*, parestesi*, synkope*, amnesi, uppm\xe4rksamhetsst\xf6rning, f\xf6rs\xe4mrat minne, migr\xe4n, parosmi, tremor, vertigo'],
             ['Eye', u'Torra \xf6gon, n\xe4thinneexsudat, dimsyn, synneds\xe4ttning'],
             ['Ear', u'Tinnitus'],
             ['Cardiac', u'Palpitationer'],
             ['Vascular', u'Hypotension*, hypertension'],
             ['Respiratory',
              u'N\xe4sbl\xf6dning, n\xe4st\xe4ppa, orofaryngeal sm\xe4rta, t\xe4ppta andningsv\xe4gar, t\xe4ppta bih\xe5lor, v\xe4sande/pipande andning'],
             ['GI',
              u'Buksm\xe4rta*, sm\xe4rta i \xf6vre delen av buken*, konstipation*, gastroesofagal refluxsjukdom*, hemorrojder*, bukbesv\xe4r, uppsp\xe4nd buk, anorektala besv\xe4r, aft\xf6s stomatit, keilit, dyspepsi, flatulens, glossodyni, muns\xe5r, munsm\xe4rta, stomatit, tandbesv\xe4r'],
             ['Skin',
              u'Dermatit, eksem, erytem, hyperhidros, nattliga svettningar, perifera \xf6dem, psoriasis, erytemat\xf6sa utslag, makul\xf6sa utslag, makulopapul\xf6sa utslag, papul\xf6sa utslag, kliande utslag, hudlesioner'],
             ['Musculoskeletal',
              u'Ryggsm\xe4rta*, sm\xe4rta i extremitet*, muskelkramper, muskelsvaghet, sm\xe4rta i nacke'],
             ['Renal', u'Pollakisuri'],
             ['Reproductive system', u'Erektil dysfunktion'],
             ['General',
              u'Obehagsk\xe4nsla i br\xf6stet*, br\xf6stsm\xe4rta*, sjukdomsk\xe4nsla*, k\xe4nsla av f\xf6r\xe4ndring av kroppstemperatur, torra slemhinnor, sm\xe4rta']]],
           ['Uncommon',
            [['Blood', u'Bl\xf6dningsben\xe4genhet, lymfadenopati, lymfopeni'],
             ['Endocrine', u'Hypertyreoidism'],
             ['Metabolism',
              u'Hypokalemi*, aptitst\xf6rning, diabetes mellitus, gikt, hyperkalcemi'],
             ['Psychiatric',
              u'Aggression*, mordtankar*, panikattack*, paranoia*, missbruk*, sj\xe4lvmordstankar*, onormalt beteende, ilska, apati, f\xf6rvirringstillst\xe5nd, f\xf6r\xe4ndring av det mentala tillst\xe5ndet, rastl\xf6shet'],
             ['Nervous system',
              u'Perifer neuropati*, kognitiv st\xf6rning, hyperestesi, letargi, medvetsl\xf6shet, psykisk f\xf6rs\xe4mring, neuralgi, presynkope'],
             ['Eye',
              u'Retinal ischemi*, retinopati*, onormal k\xe4nsla i \xf6gon, konjunktival bl\xf6dning, konjunktivit, \xf6gonsm\xe4rta, \xf6gonkl\xe5da, \xf6gonsvullnad, \xf6gonlocks\xf6dem, \xf6kat t\xe5rfl\xf6de, okul\xe4r hyperemi, fotofobi'],
             ['Ear', u'D\xf6vhet*, \xf6ronbesv\xe4r, h\xf6rselneds\xe4ttning'],
             ['Cardiac', u'Takykardi*, arytmi, kardiovaskul\xe4r sjukdom'],
             ['Vascular', u'Djup ventrombos*, vallningar, blekhet, perifer kyla'],
             ['Respiratory',
              u'Pleurasm\xe4rta*, lungemboli*, halstorrhet, dysfoni, \xf6kad sekretion fr\xe5n \xf6vre luftv\xe4gar, orofaryngeal bl\xe5sbildning'],
             ['GI',
              u'Sm\xe4rta i nedre delen av buken*, gastrit*, pankreatit*, analkl\xe5da, kolit, dysfagi, missf\xe4rgad feces, \xf6kade tarmr\xf6relser, bl\xf6dande tandk\xf6tt, sm\xe4rta i tandk\xf6tt, gingivit, glossit, torra l\xe4ppar, odynofagi, proktalgi, rektalbl\xf6dning, hypersalivation, k\xe4nsliga t\xe4nder, missf\xe4rgning av tunga, s\xe5r p\xe5 tungan'],
             ['Hepato', u'Hyperbilirubinemi'],
             ['Skin', u'Fotosensitivitetsreaktion, s\xe5r i huden, urtikaria'],
             ['Musculoskeletal',
              u'Muskuloskeletal br\xf6stsm\xe4rta*, artrit, skelettsm\xe4rta, ledsvullnad, muskuloskeletal sm\xe4rta'],
             ['Renal', u'Dysuri, nokturi'],
             ['Reproductive system',
              u'Amenorr\xe9, menorragi, metrorragi 15 Organsystem Biverkningar'],
             ['General',
              u'K\xe4nna sig onormal, f\xf6rs\xe4mrad l\xe4kning, icke-kardiell br\xf6stsm\xe4rta'],
             ['Investigations',
              u'Kardiella bl\xe5sljud, \xf6kad hj\xe4rtfrekvens * Inkluderar biverkningar, vilka enligt pr\xf6vningsledarens bed\xf6mning kan vara allvarliga, hos f\xf6rs\xf6kspersoner i kliniska pr\xf6vningar. \u2020 Eftersom Victrelis f\xf6rskrivs tillsammans med peginterferon alfa och ribavirin, se \xe4ven respektive produktresum\xe9 f\xf6r peginterferon alfa och ribavirin. \u2021 Reaktioner vid injektionsst\xe4llet har inte inkluderats eftersom Victrelis administreras peroralt. Beskrivning av utvalda biverkningar Anemi (se avsnitt 4.4) Anemi observerades hos 49% av de f\xf6rs\xf6kspersoner som behandlades med kombinationen Victrelis tillsammans med peginterferon alfa-2b och ribavirin j\xe4mf\xf6rt med 29% av de f\xf6rs\xf6kspersoner som behandlades med enbart peginterferon alfa-2b och ribavirin. Victrelis associerades med en ytterligare minskning av hemoglobinkoncentrationen, med cirka 1 g/dl (10 g/l) (se avsnitt 4.4). De genomsnittliga s\xe4nkningarna av hemoglobinv\xe4rden fr\xe5n baselinev\xe4rde var st\xf6rre hos patienter som var tidigare behandlade j\xe4mf\xf6rt med patienter som aldrig tidigare f\xe5tt behandling. Dosjusteringar p\xe5 grund av anemi/hemolytisk anemi f\xf6rekom dubbelt s\xe5 ofta hos patienter som behandlats med kombinationen Victrelis med peginterferon alfa-2b och ribavirin (26%) j\xe4mf\xf6rt med enbart peginterferon alfa-2b och ribavirin (13%). I kliniska pr\xf6vningar var andelen f\xf6rs\xf6kspersoner som fick erytropoietin f\xf6r behandling av anemi 43% (667/1 548) av f\xf6rs\xf6kspersoner i behandlingsgrupperna inneh\xe5llande Victrelis j\xe4mf\xf6rt med 24% (131/547) av f\xf6rs\xf6kspersoner som fick enbart peginterferon alfa-2b och ribavirin. Majoriteten av f\xf6rs\xf6kspersoner med anemi fick erytropoietin n\xe4r hemoglobinniv\xe5erna var \u226410 g/dl (100 g/l eller 6,2 mmol/l). Andelen f\xf6rs\xf6kspersoner som fick transfusion f\xf6r behandling av anemi i behandlingsgrupperna inneh\xe5llande Victrelis var 3% j\xe4mf\xf6rt med <1% av f\xf6rs\xf6kspersonerna som fick enbart peginterferon alfa-2b och ribavirin. Neutrofiler (se avsnitt 4.4) Andelen f\xf6rs\xf6kspersoner med minskat antal neutrofiler var h\xf6gre i behandlingsgrupperna inneh\xe5llande Victrelis j\xe4mf\xf6rt med f\xf6rs\xf6kspersoner som fick enbart peginterferon alfa-2b och ribavirin. Den procentuella andelen patienter med neutropeni grad 3-4 (antal neutrofiler <0,75 x 10 /l) var h\xf6gre hos boceprevirbehandlade patienter (29%) \xe4n hos placebobehandlade patienter (17%), i kombination med peginterferon alfa-2b och ribavirin. Sju procent av f\xf6rs\xf6kspersoner som fick kombination av Victrelis med peginterferon alfa-2b och ribavirin hade antal neutrofiler <0,5 x 10 /l (grad 4 neutropeni), j\xe4mf\xf6rt med 4% som enbart fick peginterferon alfa-2b och ribavirin. F\xf6r kombinerad anv\xe4ndning med peginterferon alfa-2a se s\xe4rskilt avsnitt i avsnitt 4.4. Trombocyter Antalet trombocyter minskade hos f\xf6rs\xf6kspersoner i behandlingsgrupperna inneh\xe5llande Victrelis (3%) j\xe4mf\xf6rt med f\xf6rs\xf6kspersoner som fick enbart peginterferon alfa-2b och ribavirin (1%). I b\xe5da behandlingsgrupperna, hade patienter med cirros h\xf6gre risk att f\xe5 trombocytopeni grad 3-4 j\xe4mf\xf6rt med icke-cirrotiska patienter.']]],
           ['Rare',
            [['Neoplasms', u'Tyreoideaneoplasm (noduli)'],
             ['Blood', u'Hemolys'],
             ['Immune system', u'Sarkoidos*, icke-akut porfyri'],
             ['Psychiatric',
              u'Bipol\xe4r sjukdom*, fullbordat sj\xe4lvmord*, sj\xe4lvmordsf\xf6rs\xf6k*, h\xf6rselhallucination, synhallucination, psykisk dekompensation'],
             ['Nervous system', u'Cerebral ischemi*, encefalopati'],
             ['Eye', u'Papill\xf6dem'],
             ['Cardiac',
              u'Akut hj\xe4rtinfarkt*, f\xf6rmaksflimmer*, kransk\xe4rlssjukdom*, perikardit*, hj\xe4rts\xe4cksutgjutning'],
             ['Vascular', u'Ventrombos'],
             ['Respiratory', u'Pleurafibros*, ortopn\xe9, respiratorisk svikt'],
             ['GI', u'Pankreasinsufficiens'],
             ['Hepato', u'Kolecystit*'],
             ['Reproductive system', u'Aspermi']]],
           ['Unknown',
            [['Other',
              u'Till\xe4gget av Victrelis till peginterferon alfa-2b och ribavirin var associerat med h\xf6gre incidenser av \xf6kning av urinsyra, triglycerider och totalkolesterol j\xe4mf\xf6rt med enbart peginterferon alfa-2b och ribavirin.']]]],
 '_pages': [13, 17],
 u'_rank': 58,
 u'_type': u'LSFU'}