{'_data': [['Very common',
            [['Infections', u'pneumoni*, nasofaryngit'],
             ['Blood', u'febril neutropeni, neutropeni, leukopeni, trombocytopeni, anemi'],
             ['Metabolism', u'anorexi'],
             ['Nervous system', u'yrsel, huvudv\xe4rk'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, kr\xe4kning, f\xf6rstoppning, illam\xe5ende, buksm\xe4rta'],
             ['Skin', u'petekier, pruritus, utslag, ecchymos'],
             ['Musculoskeletal', u'artralgi'],
             ['General', u'tr\xf6tthet, pyrexi,']]],
           ['Common',
            [['Infections',
              u'neutropen sepsis*, \xf6vre luftv\xe4gsinfektion, urinv\xe4gsinfektion, cellulit, sinuit, faryngit, rinit, herpes simplex'],
             ['Blood', u'benm\xe4rgssvikt, pancytopeni'],
             ['Metabolism', u'hypokalemi'],
             ['Psychiatric', u'f\xf6rvirringstillst\xe5nd, \xe5ngest, insomni'],
             ['Nervous system', u'intrakraniell bl\xf6dning, letargi'],
             ['Eye', u'\xf6gonbl\xf6dning, konjunktival bl\xf6dning'],
             ['Vascular', u'hypertoni, hypotoni, hematom'],
             ['Respiratory', u'dyspn\xe9 vid anstr\xe4ngning, faryngolaryngeal sm\xe4rta'],
             ['GI',
              u'gastrointestinal bl\xf6dning, hemorrojdbl\xf6dning , stomatit, gingival bl\xf6dning, dyspepsi'],
             ['Skin', u'purpura, alopeci, erytem, makul\xe4ra utslag'],
             ['Musculoskeletal', u'myalgi, muskuloskeletal sm\xe4rta'],
             ['Renal', u'njursvikt, hematuri*, f\xf6rh\xf6jt serumkreatinin'],
             ['General', u'injektionsst\xe4llet:'],
             ['Investigations', u'viktminskning']]],
           ['Uncommon',
            [['Immune system', u'\xf6verk\xe4nslighets-reaktioner'],
             ['Hepato', u'leversvikt*, progredierande leverkoma'],
             ['Renal', u'renal tubul\xe4r acidos']]],
           ['Rare',
            [['Metabolism', u'tum\xf6rlyssyndrom'],
             ['Respiratory', u'interstitiell lungsjukdom'],
             ['General', u'nekros vid']]]],
 '_note': u' ?MSFU',
 '_pages': [5, 7],
 u'_rank': 29,
 u'_type': u'MSFU'}