{'_data': [['Common',
            [['Nervous system', u'Dysgeusi'],
             ['Eye',
              u'\xd6gonsm\xe4rta, \xf6gonirritation, torra \xf6gon, \xf6gonkl\xe5da, konjunktival hyperemi, okul\xe4r hyperemi']]],
           ['Uncommon',
            [['Blood', u'S\xe4nkt hemoglobin'],
             ['Nervous system', u'Huvudv\xe4rk, parestesi'],
             ['Eye',
              u'Korneal epiteldefekt, punktuell keratit, korneal missf\xe4rgning, konjunktival bl\xf6dning, konjunktivit, \xf6gonsvullnad, \xf6gonobehag, dimsyn, f\xf6rs\xe4mrad synsk\xe4rpa, \xf6gonlocksst\xf6rning, \xf6gonlockserytem, onormal k\xe4nsla i \xf6gat'],
             ['Respiratory',
              u'N\xe4sobehag, faryngolaryngeal sm\xe4rta, k\xe4nsla av fr\xe4mmande kropp (i svalget)'],
             ['GI', u'Kr\xe4kning'],
             ['Hepato',
              u'F\xf6rh\xf6jt alaninaminotransferas, f\xf6rh\xf6jt gammaglutamyltransferas Biverkningar som identifierats efter godk\xe4nnandet och som inte tidigare rapporterats i kliniska pr\xf6vningar med l\xe4kemedlet inkluderar f\xf6ljande. Frekvenskategorin f\xf6r dessa biverkningar \xe4r ok\xe4nd och kan inte ber\xe4knas fr\xe5n tillg\xe4ngliga data.']]],
           ['Unknown',
            [['Cardiac', u'Palpitationer'],
             ['Nervous system', u'Yrsel'],
             ['Eye',
              u'Endoftalmit, ulcerativ keratit, korneal erosion, korneal abrasion, f\xf6rh\xf6jt intraokul\xe4rt tryck, korneal opacitet, korneala infiltrat, korneala utf\xe4llningar, \xf6gonallergi, keratit, korneala \xf6dem, fotofobi, korneal st\xf6rning, blefarit, \xf6gonlocks\xf6dem, \xf6kat t\xe5rfl\xf6de, \xf6gonsekretion, k\xe4nsla av fr\xe4mmande kropp i \xf6gonen'],
             ['Respiratory', u'Dyspn\xe9'],
             ['GI', u'Illam\xe5ende'],
             ['Skin', u'Erytem, utslag, kl\xe5da'],
             ['Immune system',
              u'\xd6verk\xe4nslighet Barn Grundat p\xe5 uppgifter fr\xe5n kliniska pr\xf6vningar p\xe5 barn, inklusive nyf\xf6dda (se avsnitt 5.1), \xe4r typen och allvarlighetsgraden av biverkningar i den pediatriska populationen liknande den f\xf6r vuxna.']]]],
 '_pages': [3, 4],
 u'_rank': 15,
 u'_type': u'LSFU'}