{'_data': [['Very common',
            [['Blood', u'neutropeni, anemi.'],
             ['Nervous system',
              u'obstipation (se \xe4ven \u201dMagtarmkanalen\u201d), f\xf6rlust av djupa senreflexer.'],
             ['GI',
              u'obstipation (se \xe4ven \u201dCentrala och perifera nervsystemet\u201d), illam\xe5ende, kr\xe4kningar, diarr\xe9, stomatit, esofagit, anorexi.'],
             ['Hepato',
              u'onormala leverfunktionsv\xe4rden (f\xf6rh\xf6jt totalbilirubin, f\xf6rh\xf6jt alkaliskt fosfatas, f\xf6rh\xf6jt aspartataminotransferas, f\xf6rh\xf6jt alaninaminotransferas).'],
             ['Skin', u'alopeci.'],
             ['General',
              u'tr\xf6tthet, feber, sm\xe4rta p\xe5 olika st\xe4llen, asteni. Erytem, sm\xe4rta, missf\xe4rgning eller flebit vid injektionsst\xe4llet.']]],
           ['Common',
            [['Infections', u'infektion.'],
             ['Blood',
              u'trombocytopeni, febril neutropeni, neutropen sepsis med risk f\xf6r fatal utg\xe5ng.'],
             ['Immune system',
              u'allergiska reaktioner (hudreaktioner, reaktion i andningsv\xe4garna).'],
             ['Nervous system', u'parestesier med sensoriska och motoriska symtom.'],
             ['Respiratory', u'dyspn\xe9, bronkospasm.'],
             ['Skin', u'hudreaktioner.'],
             ['Musculoskeletal', u'myalgi, artralgi.'],
             ['Renal', u'f\xf6rh\xf6jt kreatinin.']]],
           ['Rare',
            [['Metabolism', u'kraftig hyponatremi.'],
             ['Nervous system',
              u'svaghet i nedre extremiteterna, paralytisk ileus (se \xe4ven \u201dMagtarmkanalen\u201d).'],
             ['Cardiac',
              u'ischemisk hj\xe4rtsjukdom s\xe5som angina pectoris, EKG-f\xf6r\xe4ndringar, hj\xe4rtinfarkt.'],
             ['Respiratory', u'interstitiell lungsjukdom.'],
             ['GI',
              u'pankreatit, paralytisk ileus (se \xe4ven \u201dCentrala och perifera nervsystemet\u201d).'],
             ['Musculoskeletal', u'k\xe4ksm\xe4rta'],
             ['General',
              u'nekros vid injektionsst\xe4llet. Toxicitetsgrad (G) anges enligt WHOs klassifikation.'],
             ['Respiratory',
              u'fall av interstitiell lungsjukdom har rapporterats, s\xe4rskilt hos patienter behandlade med vinorelbin i kombination med mitomycin.']]],
           ['Very rare',
            [['Metabolism', u'p\xe5verkad sekretion av antidiuretiskt hormon (SIADH)'],
             ['Nervous system', u'Guillain-Barr\xe9s syndrom.'],
             ['Nervous system',
              u'fall av Guillain-Barr\xe9s syndrom. Svaghet i de nedre extremiteterna har rapporterats efter l\xe5ngtidsbehandling. Parestesier med sensoriska och motoriska symtom (G3- G4: < 3 %). Dessa symtom \xe4r i allm\xe4nhet reversibla vid avbrott i behandlingen. Effekter p\xe5 det autonoma nervsystemet kan orsaka tarmpares och f\xf6rstoppning, men f\xf6rv\xe4rras s\xe4llan till paralytisk ileus (< 3 %). Se \xe4ven \u201dMagtarmkanalen\u201d.']]],
           ['Unknown',
            [['Infections',
              u'Infektioner kan vara vanliga, framf\xf6r allt p\xe5 grund av benm\xe4rgsdepression.'],
             ['Blood',
              u'24,3 %, G4 27,8 %), som \xe4r reversibel inom 5\u20137 dagar och icke-kumulativ \xf6ver tid. Febril neutropeni och neutropen sepsis, som i vissa fall (1,2 %) hade d\xf6dlig utg\xe5ng. Anemi (G3\u20134: 7,4 %), trombocytopeni (G3\u20134: 2,5 %) kan upptr\xe4da men \xe4r s\xe4llan allvarliga.'],
             ['Immune system', u'Allergiska reaktioner (i hud och andningsv\xe4gar).'],
             ['Metabolism',
              u'Sv\xe5r hyponatremi och SIADH-syndrom (Syndrome of Inappropriate Antidiuretic Hormone Secretion) har rapporterats.'],
             ['Nervous system', u'2,6 %; G4 0,1 %) inklusive f\xf6rlust av djupa senreflexer.'],
             ['Cardiac',
              u'Ischemisk hj\xe4rtsjukdom (angina pectoris och/eller transitoriska EKG-f\xf6r\xe4ndringar, hj\xe4rtinfarkt).'],
             ['Respiratory',
              u'Dyspn\xe9 och bronkospasm kan f\xf6rekomma vid behandling med vinorelbin, som med andra vincaalkaloider.'],
             ['GI',
              u'7,6 %; G2 3,6 %; G3 0,7 %; G4 0,1 % med vinorelbin i monoterapi) och esofagit. Illam\xe5ende och kr\xe4kningar (G1: 19,9 %; G2: 8,3 %, G3: 1,9 %; G4: 0,3 %). Antiemetisk behandling kan reducera f\xf6rekomsten. F\xf6rstoppning \xe4r det huvudsakliga symtomet (G3-4: 2,7%), som s\xe4llan utvecklas till paralytisk ileus med vinorelbin i monoterapi och i kombination med annan kemoterapi (G3-4: 4,1%). Diarr\xe9, vanligtvis mild till m\xe5ttlig, kan f\xf6rekomma. Paralytisk ileus, behandlingen kan \xe5terupptas vid \xe5terst\xe4lld normal tarmfunktion. Pankreatit har rapporterats. Anorexi (G1\u20132: 14%; G3: 1%).'],
             ['Hepato',
              u'Tillf\xe4llig \xf6kning i leverfunktionsv\xe4rden (G1-2) utan kliniska symtom har rapporterats (bilirubin, alkaliskt fosfatas, ASAT hos 27,6%, ALAT hos 29,3%).'],
             ['Skin',
              u'4,1% med vinorelbin i monoterapi). Allm\xe4nna hudreaktioner s\xe5som kl\xe5da, utslag, n\xe4sselfeber och erytem p\xe5 h\xe4nder och f\xf6tter har rapporterats med vinorelbin.'],
             ['Musculoskeletal', u'Artralgi inklusive k\xe4ksm\xe4rta och myalgi.'],
             ['Renal', u'F\xf6rh\xf6jt blodkreatinin har rapporterats.'],
             ['General',
              u'Liksom andra vincaalkaloider kan vinorelbin leda till bl\xe5sbildning. Patienter som behandlas med vinorelbin kan uppleva tr\xf6tthet, feber, asteni och sm\xe4rtor med olika lokalisation, s\xe5som br\xf6stsm\xe4rtor och sm\xe4rta i tum\xf6ren. Reaktioner p\xe5 injektionsst\xe4llet kan innefatta erytem, svidande sm\xe4rta, missf\xe4rgning av venen och lokal flebit (G3: 3,6 %; G4: 0,1 % med vinorelbin i monoterapi). Lokal nekros har observerats. R\xe4tt positionering av den intraven\xf6sa kanylen eller katetern och infusion f\xf6ljd av riklig sk\xf6ljning av venen kan begr\xe4nsa dessa effekter.']]]],
 '_pages': [5, 7],
 u'_rank': 38,
 u'_type': u'LSFU'}