{'_data': [['Very common',
            [['Metabolism', u'hypofosfatemi'],
             ['Nervous system', u'yrsel'],
             ['GI', u'diarr\xe9, kr\xe4kning, illam\xe5ende'],
             ['Skin', u'hudutslag'],
             ['General', u'asteni']]],
           ['Common',
            [['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'buksm\xe4rta, uppsv\xe4lld buk, flatulens'],
             ['Hepato', u'f\xf6rh\xf6jda transaminaser'],
             ['General',
              u'tr\xf6tthet Denna biverkning kan f\xf6rekomma som en f\xf6ljd av proximal renal tubulopati. Den anses inte ha n\xe5got orsakssamband med tenofovirdisoproxilfumarat i fr\xe5nvaro av detta tillst\xe5nd. Denna biverkning identifierades genom s\xe4kerhetsuppf\xf6ljning efter introduktionen p\xe5 marknaden men observerades inte i randomiserade kontrollerade kliniska studier eller programmet f\xf6r ut\xf6kad tillg\xe5ng till tenofovirdisoproxilfumarat. Frekvenskategorin bed\xf6mdes utg\xe5ende fr\xe5n en statistisk ber\xe4kning baserad p\xe5 det totala antalet patienter som exponerats f\xf6r tenofovirdisoproxilfumarat i randomiserade kontrollerade kliniska studier och programmet f\xf6r ut\xf6kad tillg\xe5ng (n = 7 319). Se avsnitt 4.8 Beskrivning av valda biverkningar f\xf6r mer information. 96 Beskrivning av valda biverkningar Hiv-1 och hepatit B: Nedsatt njurfunktion Eftersom Viread kan orsaka njurskada rekommenderas \xf6vervakning av njurfunktionen (se avsnitt 4.4 och 4.8 Sammanfattning av s\xe4kerhetsprofil). Hiv-1: Interaktion med didanosin Samtidig administrering av tenofovirdisoproxilfumarat och didanosin rekommenderas inte eftersom den resulterar i att den systemiska exponeringen f\xf6r didanosin \xf6kar med 40-60 %, vilket kan \xf6ka risken f\xf6r didanosinrelaterade biverkningar (se avsnitt 4.5). S\xe4llsynta fall av pankreatit och laktacidos, ibland d\xf6dliga, har rapporterats. Lipider, lipodystrofi och metabola st\xf6rningar Antiretroviral kombinationsbehandling har associerats med metabola st\xf6rningar s\xe5som hypertriglyceridemi, hyperkolesterolemi, insulinresistens, hyperglykemi och hyperlaktatemi (se avsnitt 4.4). Antiretroviral kombinationsbehandling har associerats med omf\xf6rdelning av kroppsfett (lipodystrofi) hos hiv-patienter, inkluderande minskning av perifert och facialt subkutant fett, \xf6kning av intraabdominellt och visceralt fett, br\xf6sthypertrofi och dorsocervikal fettackumulering (\u201cbuffalo hump\u201d) (se avsnitt 4.4). I en 144-veckors kontrollerad klinisk studie med vuxna patienter som tidigare inte behandlats med antiretrovirala medel, i vilken tenofovirdisoproxilfumarat j\xe4mf\xf6rdes med stavudin i kombination med lamivudin och efavirenz, var incidensen av lipodystrofi signifikant l\xe4gre hos de patienter som fick tenofovirdisoproxil j\xe4mf\xf6rt med de som fick stavudin. I den grupp som fick tenofovirdisoproxilfumarat var ocks\xe5 den genomsnittliga \xf6kningen av triglycerider och totalt kolesterol vid fasta signifikant mindre \xe4n i j\xe4mf\xf6relsegruppen. Immunreaktiveringssyndrom Hos hiv-infekterade patienter med sv\xe5r immunbrist vid tidpunkten f\xf6r ins\xe4ttande av antiretroviral kombinationsterapi, kan en inflammatorisk reaktion mot asymtomatiska eller kvarvarande opportunistiska infektioner uppst\xe5 (se avsnitt 4.4). Osteonekros Fall av osteonekros har rapporterats, speciellt hos patienter med k\xe4nda riskfaktorer, framskriden hiv-sjukdom eller l\xe5ngvarig exponering f\xf6r antiretroviral kombinationsbehandling (CART). Frekvensen av detta \xe4r ok\xe4nd (se avsnitt 4.4). Laktacidos och sv\xe5r hepatomegali med steatos Laktacidos, vanligtvis f\xf6renad med leversteatos, har rapporterats vid anv\xe4ndning av nukleosidanaloger. Behandling med nukleosidanaloger skall uts\xe4ttas vid symtomatisk hyperlaktatemi och metabolisk acidos/laktacidos, progressiv hepatomegali eller snabbt stigande aminotransferasniv\xe5er (se avsnitt 4.4). Hepatit B: Exacerbationer av hepatit under behandling I studier p\xe5 patienter som inte tidigare behandlats med nukleosider upptr\xe4dde ALAT-f\xf6rh\xf6jningar under behandling > 10 g\xe5nger ULN (\xf6vre normalgr\xe4nsen) och > 2 g\xe5nger baseline hos 2,6 % av de tenofovirdisoproxilfumaratbehandlade. ALAT-f\xf6rh\xf6jning under behandling hade en mediantid till debut p\xe5 8 veckor, f\xf6rsvann vid fortsatt behandling och var, hos majoriteten av fallen, associerad med en s\xe4nkning med > 2 log kopior/ml av den virusm\xe4ngd som f\xf6regick eller sammanf\xf6ll med ALAT f\xf6rh\xf6jningen. Regelbunden kontroll av leverfunktionen rekommenderas under behandling (se avsnitt 4.4).']]],
           ['Uncommon',
            [['Metabolism', u'hypokalemi'],
             ['GI', u'pankreatit'],
             ['Musculoskeletal', u'rabdomyolys , muskelsvaghet'],
             ['Renal',
              u'f\xf6rh\xf6jda kreatininv\xe4rden akut njursvikt, njursvikt, akut tubul\xe4r nekros, proximal renal tubulopati (inklusive']]],
           ['Rare',
            [['Metabolism', u'laktacidos'],
             ['Hepato', u'leversteatos , hepatit'],
             ['Skin', u'angio\xf6dem'],
             ['Musculoskeletal',
              u'osteomalaci (manifesterad som skelettsm\xe4rta och som i s\xe4llsynta fall bidrar till frakturer) , myopati'],
             ['Renal',
              u'Fanconis syndrom), nefrit (inklusive akut interstitiell nefrit) , nefrogen diabetes insipidus']]]],
 '_pages': [12, 15],
 u'_rank': 18,
 u'_type': u'LSFU'}