{'_data': [['Common',
            [['General', u' Sm\xe4rta, v\xe4rmek\xe4nsla, k\xf6ldk\xe4nsla '],
             ['GI', u'Kr\xe4kningar, illam\xe5ende'],
             ['General', u' Sm\xe4rta, v\xe4rk i rygg, nacke eller extremiteter.'],
             ['Nervous system', u'HSG: Feber, huvudv\xe4rk'],
             ['GI',
              u' : HSG och gastrointesinalt: Buksm\xe4rta, illam\xe5ende, kr\xe4kningar. Gastrointestinalt: Diarr\xe9'],
             ['Musculoskeletal', u'Artrografi: Skelettsm\xe4rta'],
             ['General',
              u'Artrografi: Tryckk\xe4nsla vid punktionsst\xe4llet, unders\xf6kningsrelaterad sm\xe4rta HSG: Vaginal bl\xf6dning.']]],
           ['Uncommon',
            [['GI', u' Illam\xe5ende, kr\xe4kningar'],
             ['Skin', u' Exantem, erytem, kl\xe5da, urtikaria, angio\xf6dem']]],
           ['Rare',
            [['Immune system',
              u' Anafylaktoid reaktion, Jodreaktion i form av sialadenit och vaskulit'],
             ['Nervous system', u' Neurologiska reaktioner, yrsel'],
             ['Cardiac', u' K\xe4rlspasm'],
             ['Vascular', u' Tromboflebit'],
             ['Respiratory', u' Luftv\xe4gssymtom, hosta'],
             ['Renal', u' Njurfunktionsneds\xe4ttning'],
             ['Nervous system',
              u'Psykiska reaktioner, \xf6verg\xe5ende EEG-f\xf6r\xe4ndringar, aseptisk meningit'],
             ['Immune system', u' Anafylaktoid reaktion']]],
           ['Very rare',
            [['Cardiac',
              u' Vagala reaktioner (bradykardi, hypotoni). Arytmier,eller tecken p\xe5 ischemi, hypertoni, hj\xe4rtstillest\xe5nd'],
             ['Respiratory',
              u' Dyspn\xe9. Sv\xe5ra \xf6verk\xe4nslighetsreaktioner (laryngalt \xf6dem, bronkospasm, lung\xf6dem, anafylaktisk chock)'],
             ['GI', u' Buksm\xe4rta/-obehag.']]],
           ['Unknown',
            [['Nervous system',
              u' \xd6verg\xe5ende kontrast-inducerad encefalopati inklusive amnesi, hallucination, f\xf6rvirringstillst\xe5nd och andra neurologiska symtom'],
             ['Cardiac', u' myokardiell infarkt'],
             ['Nervous system',
              u' \xd6verg\xe5ende kontrast-inducerad encefalopati inklusive amnesi, hallucination, f\xf6rvirringstillst\xe5nd och andra neurologiska symtom']]]],
 '_pages': [5, 6],
 u'_rank': 23,
 u'_type': u'LSFU2'}