{'_data': [['Common',
            [['Nervous system', u'Yrsel Vanlig'],
             ['Cardiac', u'Hj\xe4rtsvikt  '],
             ['Cardiac', u'Hj\xe4rtklappning  '],
             ['GI', u'Buksm\xe4rta  '],
             ['GI', u'F\xf6rstoppning  '],
             ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9  '],
             ['Hepato', u'Autoimmun hepatit (se avsnitt 4.4) Mindre'],
             ['Hepato',
              u'Br\xf6stsm\xe4rta/obehag Vanlig Asteni och fatigue Vanlig Se avsnittet \u201dBeskrivning av vissa biverkningar\u201d. Frekvensen f\xf6r huvudv\xe4rk var h\xf6gre med 10 mg ambrisentan. 3 Data kommer fr\xe5n uppf\xf6ljning efter att produkten har introducerats p\xe5 marknaden och frekvensen \xe4r baserad p\xe5 erfarenheter fr\xe5n placebokontrollerade kliniska studier. Flertalet av de rapporterade fallen med hj\xe4rtsvikt var f\xf6rknippade med v\xe4tskeretention. Data kommer fr\xe5n erfarenheter efter att produkten har introducerats p\xe5 marknaden, frekvensen \xe4r baserad p\xe5 statistisk modellering av data fr\xe5n placebokontrollerade kliniska studier. Fall av f\xf6rv\xe4rrad dyspn\xe9 av ok\xe4nd orsak har rapporterats kort efter p\xe5b\xf6rjad behandling med ambrisentan. F\xf6rekomsten av n\xe4st\xe4ppa var dosrelaterad under ambrisentanbehandling. 7 Fall med autoimmun hepatit, inklusive f\xf6rs\xe4mring av autoimmun hepatit och leverskada, har rapporterats vid ambrisentanbehandling. 8 Perifert \xf6dem rapporterades oftare med 10 mg ambrisentan. I kliniska studier rapporterades perifert \xf6dem oftare och tenderade att vara sv\xe5rare hos patienter >65 \xe5r (se avsnitt 4.4).']]],
           ['Unknown',
            [['Blood', u'Anemi (s\xe4nkt hemoglobin, s\xe4nkt hematokrit) 1 Vanlig'],
             ['Nervous system',
              u'7 Huvudv\xe4rk (\xe4ven sinushuvudv\xe4rk, migr\xe4n) Mycket'],
             ['Vascular',
              u'T\xe4ppta \xf6vre luftv\xe4gar (t.ex. n\xe4sa , bih\xe5lor), sinuit, Vanlig nasofaryngit, rinit']]]],
 '_pages': [6, 8],
 u'_rank': 11,
 u'_type': u'LSFU'}