{'_data': [['Very common',
            [['Nervous system', u'Huvudv\xe4rk (\xe4ven sinushuvudv\xe4rk, migr\xe4n)  '],
             ['General', u'Perifert \xf6dem, v\xe4tskeretention  ']]],
           ['Common',
            [['Nervous system', u'Yrsel  '],
             ['Cardiac', u'Hj\xe4rtsvikt  '],
             ['Cardiac', u'Hj\xe4rtklappning  '],
             ['Vascular', u'Hypotension  '],
             ['Vascular', u'Blodvallningar  '],
             ['GI', u'Buksm\xe4rta  '],
             ['GI', u'F\xf6rstoppning  '],
             ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9  '],
             ['Hepato', u'\xd6kade levertransaminaser  '],
             ['General', u'Br\xf6stsm\xe4rta/obehag  '],
             ['General', u'Asteni och fatigue  ']]],
           ['Uncommon',
            [['Vascular', u'Syncope  '],
             ['Hepato', u'Leverskada (se avsnitt 4.4)  '],
             ['Hepato', u'Autoimmun hepatit (se avsnitt 4.4)  ']]],
           ['Unknown',
            [['Blood', u'Anemi (s\xe4nkt hemoglobin, s\xe4nkt hematokrit) 1 Vanlig'],
             ['Immune system', u'kl\xe5da)'],
             ['Respiratory',
              u'T\xe4ppta \xf6vre luftv\xe4gar (t.ex. n\xe4sa , bih\xe5lor), sinuit, Vanlig nasofaryngit, rinit']]]],
 '_pages': [6, 8],
 u'_rank': 19,
 u'_type': u'LSFU'}