{'_data': [['Common',
            [['GI',
              u', <1/100), s\xe4llsynta (>1/10000, <1/1000), mycket s\xe4llsynta (<1/10000), inklusive enstaka rapporter.'],
             ['GI',
              u'Epigastrisk sm\xe4rta, illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta, dyspepsi, flatulens, anorexi.'],
             ['Nervous system', u'Huvudv\xe4rk, yrsel.'],
             ['Ear', u'Vertigo.'],
             ['Hepato', u'Transaminasstegringar (ASAT, ALAT).'],
             ['Skin', u'Utslag'],
             ['General', u'Lokal irritation']]],
           ['Uncommon',
            [['Respiratory', u'Bronkospasm'],
             ['Hepato',
              u'Leverfunktionsst\xf6rningar inklusive hepatit med eller utan ikterus.']]],
           ['Rare',
            [['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inklusive anafylaktiska och anafylaktoida reaktioner (inklusive hypotension och chock).'],
             ['GI',
              u'Gastrit, gastrointestinal bl\xf6dning, hematemes, melaena, peptiska s\xe5r eller tarms\xe5r med eller utan bl\xf6dning eller perforation, blodiga diarr\xe9er. Diafragmaliknande tarmstrikturer. Tjocktarmsbesv\xe4r (ospecifik hemorragisk kolit och exacerbationer av ulcer\xf6s kolit eller Crohns proktokolit). Ulcerativ stomatit, glossit, esofagusst\xf6rningar, obstipation, pankreatit, exacerbationer av hemorrojder, proktit.'],
             ['Nervous system', u'Somnolens.'],
             ['Respiratory', u'Astma (inklusive dyspn\xe9).'],
             ['Hepato', u'Fulminant hepatit.'],
             ['Skin', u'Urtikaria.'],
             ['Reproductive system', u'Impotens (samband tveksamt).'],
             ['General',
              u'\xd6dem. Kliniska pr\xf6vningar och epidemiologiska data tyder p\xe5 att anv\xe4ndning av diklofenak, s\xe4rskilt i h\xf6ga doser (150 mg dagligen) och vid l\xe5ngtidsbehandling, kan medf\xf6ra en liten \xf6kad risk f\xf6r arteriella trombotiska h\xe4ndelser (till exempel hj\xe4rtinfarkt eller stroke, se avsnitt 4.4). F\xf6r NSAID f\xf6rekommer i s\xe4llsynta fall allvarliga hud- och mjukdelsinfektioner i samband med vattkoppor.']]],
           ['Very rare',
            [['Blood',
              u'Trombocytopeni, leukopeni, agranulocytos, hemolytisk anemi, aplastisk anemi.'],
             ['Immune system', u'Angioneurotiskt \xf6dem (inklusive ansikts\xf6dem).'],
             ['Psychiatric',
              u'Desorientering, insomningssv\xe5righeter, irritabilitet, depression, mardr\xf6mmar, psykotiska st\xf6rningar.'],
             ['Nervous system',
              u'K\xe4nselbortfall s\xe5som parestesi, minnesst\xf6rningar, kramper, \xe4ngslan, tremor, smakf\xf6r\xe4ndringar,aseptisk meningit, cerebrovaskul\xe4r h\xe4ndelse'],
             ['Eye', u'Synst\xf6rningar (dimsyn, dubbelseende).'],
             ['Ear', u'Nedsatt h\xf6rsel och \xf6ronsusningar.'],
             ['Cardiac', u'Palpitationer, br\xf6stsm\xe4rta, hj\xe4rtsvikt, hj\xe4rtinfarkt.'],
             ['Vascular', u'Hypertoni, vaskulit.'],
             ['Respiratory', u'Pneumonit.'],
             ['Hepato', u'Levernekros, leversvikt.'],
             ['Skin',
              u'Bull\xf6sa eruptioner, eksem, erythema, erytema multiforme, Steven Johnsons syndrom, Lyells syndrom, (akut toxisk epidermal nekrolys), erytrodermi (exfoliativ dermatit), h\xe5ravfall, ljus\xf6verk\xe4nslighetsreaktioner, purpura, allergisk purpura, pruritus.'],
             ['Renal',
              u'Akut njurinsufficiens, hematuri, proteinuri, interstitiell nefrit, nefrotiskt syndrom, papillarnekros.']]],
           ['Unknown',
            [['GI',
              u'vanligen inom n\xe5gra dagar, \xe4ven under fortsatt terapi. Gastroduodenals\xe5r, perforation eller gastrointestinal bl\xf6dning kan ibland vara livshotande, s\xe4rskilt hos \xe4ldre (se avsnitt 4.4). Detta kan intr\xe4ffa n\xe4r som helst under behandlingen med eller utan varningssymtom eller tidigare sjukdomshistoria. Diklofenak h\xe4mmar tempor\xe4rt trombocytaggregationen, vilket kan leda till \xf6kad risk hos patienter med olika bl\xf6dningssjukdomar. Biverkningarna i tabellen \xe4r ordnade efter frekvens, med de vanligast f\xf6rekommande biverkningarna f\xf6rst, enligt f\xf6ljande frekvensangivelse: vanliga (>1/100, <1/10), mindre']]]],
 '_pages': [7, 8],
 u'_rank': 30,
 u'_type': u'LSFU'}