{'_data': [['Very common',
            [['Endocrine', u'Minskad aptit 317 (28 %) 14 (1 %) 0'],
             ['Metabolism', u'Dysgeusi 254 (22 %) 1 (< 1 %) 0'],
             ['Metabolism', u'Mycket Hypertoni 473 (41 %) 115 (10 %) 1 (< 1 %)'],
             ['General', u'Mycket F\xf6rh\xf6jt 246 (21 %) 84 (7 %) 14 (1 %)'],
             ['General', u'Mycket F\xf6rh\xf6jt 211 (18 %) 51 (4 %) 10'],
             ['Endocrine', u'Mycket Minskad aptit 108 12 (3 %) 0'],
             ['Endocrine', u'Mycket Dysgeusi 79 (21 %) 0 0'],
             ['Endocrine', u'Mycket Huvudv\xe4rk 54 (14 %) 2 (< 1 %) 0'],
             ['Vascular', u'Mycket Diarr\xe9 174 17 (4 %) 0'],
             ['Vascular', u'Mycket Illam\xe5ende 167 8 (2 %) 0'],
             ['Vascular', u'Mycket Kr\xe4kningar 96 (25 %) 7 (2 %) 0'],
             ['Vascular', u'Mycket Buksm\xe4rta 55 (14 %) 4 (1 %) 0'],
             ['Vascular', u'Mycket Stomatit 41 (11 %) 1 (< 1 %) 0'],
             ['Hepato', u'Mycket \xc4ndrad h\xe5rf\xe4rg 93 (24 %) 0 0'],
             ['Hepato', u'Mycket Hypopigmentering av 80 (21 %) 0 0'],
             ['Hepato', u'Mycket Exfoliativa utslag 52 (14 %) 2 (< 1 %) 0']]],
           ['Common',
            [['Metabolism', u'41 Psykiska Vanliga Insomnia 30 (3 %) 00 st\xf6rningar'],
             ['Metabolism', u'Letargi 30 (3 %) 3 (< 1 %) 0'],
             ['Metabolism', u'Parestesi 20 (2 %) 2 (< 1 %) 0'],
             ['Metabolism',
              u'Perifer sensorisk 17 (< 1 %) 00 Centrala och neuropati perifera Mindre Hypestesi 8 (< 1 %) 00 nervsystemet vanliga Mindre Transitorisk ischemisk 7 (< 1 %) 4 (< 1 %) 0'],
             ['Metabolism', u'attack Mindre Somnolens 3 (< 1 %) 1 (< 1 %) 0'],
             ['Metabolism', u'vanliga Mindre Cerebrovaskul\xe4r 2 (< 1 %) 1 (< 1 %) 1 (< 1 %)'],
             ['Metabolism', u'sjukdom Mindre Ischemisk stroke 2 (< 1 %) 01 (< 1 %)'],
             ['Metabolism', u'vanliga'],
             ['Metabolism',
              u'Vanliga Dimsyn 19 (2 %) 1 (< 1 %) 0 \xd6gon Mindre Missf\xe4rgade \xf6gonfransar 4 (< 1 %) 00'],
             ['Metabolism', u'vanliga Mindre Bradykardi 6 (< 1 %) 00'],
             ['Metabolism', u'vanliga Mindre Myokardinfarkt 5 (< 1 %) 1 (< 1 %) 4 (< 1 %)'],
             ['Metabolism',
              u'vanliga Hj\xe4rtat Mindre Hj\xe4rtdysfunktion 4 (< 1 %) 1 (< 1 %) 0'],
             ['Metabolism', u'vanliga Mindre Myokardischemi 3 (< 1 %) 1 (< 1 %) 0'],
             ['Metabolism', u'vanliga'],
             ['Metabolism', u'vanliga'],
             ['Metabolism', u'Vanliga V\xe4rmevallningar 16 (1 %) 00'],
             ['Metabolism',
              u'Vanliga Ven\xf6s tromboembolisk 13 (1 %) 6 (< 1 %) 7 (< 1 %) h\xe4ndelse Blodk\xe4rl Vanliga Blodvallning 12 (< 1 %) 00 Mindre Hypertonisk kris 6 (< 1 %) 02 (< 1 %)'],
             ['Metabolism', u'vanliga Mindre Bl\xf6dning 1 (< 1 %) 00'],
             ['Metabolism', u'vanliga'],
             ['Metabolism', u'Vanliga Epistaxi 50 (4 %) 1 (< 1 %) 0'],
             ['Metabolism', u'Vanliga Dysfoni 48 (4 %) 00'],
             ['Metabolism', u'Vanliga Dyspn\xe9 42 (4 %) 8 (< 1 %) 1 (< 1 %)'],
             ['Metabolism',
              u'Vanliga Hemoptys 15 (1 %) 1 (< 1 %) 0 Andningsv\xe4gar, br\xf6stkorg och Mindre Rinorr\xe9 8 (< 1 %) 00 mediastinum vanliga Mindre Pulmonell bl\xf6dning 2 (< 1 %) 00'],
             ['Metabolism', u'vanliga Mindre Pneumotorax 1 (< 1 %) 00'],
             ['Metabolism', u'vanliga'],
             ['GI', u'vanliga Mindre Frekventa 3 (< 1 %) 00'],
             ['GI', u'tarmt\xf6mningar Mindre Anal bl\xf6dning 2 (< 1 %) 00'],
             ['GI', u'vanliga Mindre Perforation av 2 (< 1 %) 1 (< 1 %) 0'],
             ['GI', u'grovtarmen Mindre Munbl\xf6dning 2 (< 1 %) 00'],
             ['GI', u'vanliga Mindre \xd6vre gastrointestinal 2 (< 1 %) 1 (< 1 %) 0'],
             ['GI', u'bl\xf6dning Mindre Enterokutan fistel 1 (< 1 %) 00'],
             ['GI', u'vanliga Mindre Hematemes 1 (< 1 %) 00'],
             ['GI', u'vanliga Mindre Hemorroidal bl\xf6dning 1 (< 1 %) 00'],
             ['GI', u'vanliga Mindre Perforation av ileum 1 (< 1 %) 01 (< 1 %)'],
             ['GI', u'vanliga Mindre Esofageal bl\xf6dning 1 (< 1 %) 00'],
             ['GI', u'vanliga Mindre Retroperitoneal 1 (< 1 %) 00'],
             ['GI', u'bl\xf6dning'],
             ['GI', u'Vanliga Hyperbilirubinemi 38 (3 %) 2 (< 1 %) 1 (< 1 %)'],
             ['GI',
              u'Vanliga Onormal leverfunktion 29 (3 %) 13 (1 %) 2 (< 1 %) Lever och Vanliga Hepatotoxicitet 18 (2 %) 11 (< 1 %) 2 (< 1 %) gallv\xe4gar Mindre Gulsot 3 (< 1 %) 1 (< 1 %) 0'],
             ['GI', u'vanliga Mindre L\xe4kemedelsinducerad 2 (< 1 %) 2 (< 1 %) 0'],
             ['GI', u'leverskada'],
             ['Skin', u'vanliga Mindre Erytemat\xf6st utslag 6 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Hudsjukdom 5 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Makul\xe4rt utslag 4 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Kliande utslag 3 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Vesikul\xe4rt utslag 3 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Generaliserad kl\xe5da 2 (< 1 %) 1 (< 1 %) 0'],
             ['Skin', u'vanliga Mindre Generaliserat utslag 2 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Papul\xf6st utslag 2 (< 1 %) 00'],
             ['Skin', u'vanliga Mindre Plantart erytem 1 (< 1 %) 00'],
             ['Skin', u'vanliga'],
             ['Skin',
              u'Vanliga Artralgi 48 (4 %) 8 (< 1 %) 0 Muskuloskeletala Vanliga Myalgi 35 (3 %) 2 (< 1 %) 0 systemet och Vanliga Muskelryckningar 25 (2 %) 00 bindv\xe4v Mindre Muskuloskeletal sm\xe4rta 9 (< 1 %) 1 (< 1 %) 0'],
             ['Skin', u'vanliga'],
             ['Skin',
              u'Vanliga Proteinuri 135 (12 %) 32 (3 %) 0 Njurar och urinv\xe4gar Mindre Bl\xf6dning i urinv\xe4garna 1 (< 1 %) 00'],
             ['Skin',
              u'vanliga Reproduktions- Mindre Menorragi 3 (< 1 %) 00 organ och vanliga br\xf6stk\xf6rtel Mindre Vaginal bl\xf6dning 3 (< 1 %) 00'],
             ['General', u'vanliga Mindre Slemhinnerubbningar 1 (< 1 %) 00'],
             ['General', u'vanliga'],
             ['General', u'alaninaminotransferas'],
             ['General', u'vanliga aspartataminotransferas (< 1 %)'],
             ['General', u'Vanliga Viktminskning 96 (8 %) 7 (< 1 %) 0'],
             ['General', u'Vanliga F\xf6rh\xf6jt blodbilirubin 61 (5 %) 6 (< 1 %) 1 (< 1 %)'],
             ['General', u'Vanliga F\xf6rh\xf6jt blodkreatinin 55 (5 %) 3 (< 1 %) 0'],
             ['General', u'Vanliga F\xf6rh\xf6jt lipas 51 (4 %) 21 (2 %) 7 (< 1 %)'],
             ['General',
              u'Vanliga S\xe4nkt v\xe4rde f\xf6r vita 51 (2 %) 3 (< 1 %) 0 blodkroppar'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt 36 (3 %) 00 tyreoideastimulerande hormon i blodet'],
             ['General', u'Vanliga F\xf6rh\xf6jt blodamylas 35 (3 %) 7 (< 1 %) 0'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt gamma- 31 (3 %) 9 (< 1 %) 4 (< 1 %) glutamyltransferas'],
             ['General',
              u'Vanliga F\xf6rh\xf6jt blodtryck 15 (1 %) 2 (< 1 %) 0 Unders\xf6kningar Vanliga F\xf6rh\xf6jt blodurea 12 (< 1 %) 1 (< 1 %) 0'],
             ['General',
              u'Vanliga Onormalt 12 (1 %) 6 (< 1 %) 1 (< 1 %) leverfunktionstest Mindre F\xf6rh\xf6jt leverenzym 11 (< 1 %) 4 (< 1 %) 3 (< 1 %)'],
             ['General', u'vanliga Mindre S\xe4nkt blodglukos 7 (< 1 %) 01 (< 1 %)'],
             ['General', u'vanliga Mindre F\xf6rl\xe4ngt QT i 7 (< 1 %) 2 (< 1 %) 0'],
             ['General',
              u'elektrokardiogram Mindre F\xf6rh\xf6jt transaminas 7 (< 1 %) 1 (< 1 %) 0'],
             ['General', u'vanliga Mindre Onormalt 3 (< 1 %) 00'],
             ['General',
              u'tyreoideafunktionstest Mindre F\xf6rh\xf6jt diastoliskt 2 (< 1 %) 00'],
             ['General', u'blodtryck Mindre F\xf6rh\xf6jt systoliskt 1 (< 1 %) 00'],
             ['General',
              u'blodtryck \u2020Behandlingsrelaterade biverkningar rapporterade perioden efter att produkten introducerats p\xe5 marknaden (spontana fallrapporter och allvarliga biverkningar fr\xe5n alla kliniska studier p\xe5 pazopanib). F\xf6ljande biverkningar har kombinerats: Buksm\xe4rta, sm\xe4rta i \xf6vre buken och sm\xe4rta i nedre buken'],
             ['Endocrine',
              u'(28 %) Metabolism och Mycket Hyperalbuminemi 81 (34 %) 2 (< 1 %) 0 nutrition vanliga'],
             ['Endocrine',
              u'Vanliga Dehydrering 4 (1 %) 2 (1 %) 0 Mindre Hypomagnesemi 1 (< 1 %) 00'],
             ['Endocrine',
              u'vanliga Psykiska st\xf6rningar Vanliga Insomni 5 (1 %) 1 (< 1 %) 0'],
             ['Endocrine', u'vanliga'],
             ['Endocrine', u'vanliga'],
             ['Endocrine',
              u'Vanliga Perifer sensorisk neuropati 30 (8 %) 1 (< 1 %) 0 Centrala och perifera Vanliga Yrsel 15 (4 %) 00 nervsystemet Mindre Somnolens 3 (< 1 %) 00'],
             ['Endocrine', u'vanliga Mindre Parestesi 1 (< 1 %) 00'],
             ['Endocrine', u'vanliga Mindre Cerebral infarkt 1 (< 1 %) 01 (< 1 %)'],
             ['Endocrine', u'vanliga \xd6gon Vanliga Dimsyn 15 (4 %) 00'],
             ['Endocrine',
              u'Vanliga Hj\xe4rtdysfunktion 21 (5 %) 3 (< 1 %) 1 (< 1 %) Hj\xe4rtat Vanliga V\xe4nsterkammardysfunktion 13 (3 %) 3 (< 1 %) 0'],
             ['Vascular',
              u'Vanliga Rodnader 4 (1 %) 00 Mindre Bl\xf6dning 2 (< 1 %) 1 (< 1 %) 0'],
             ['Vascular', u'vanliga'],
             ['Vascular', u'Vanliga Epistaxi 22 (6 %) 00'],
             ['Vascular', u'Vanliga Dysfoni 20 (5 %) 00'],
             ['Vascular', u'Vanliga Dyspn\xe9 14 (4 %) 3 (< 1 %) 0'],
             ['Vascular', u'Vanliga Hosta 12 (3 %) 00'],
             ['Vascular', u'Vanliga Pneumothorax 7 (2 %) 2 (< 1 %) 1 (< 1 %)'],
             ['Vascular',
              u'Vanliga Hicka 4 (1 %) 00 Andningsv\xe4gar, Vanliga Pulmonell bl\xf6dning 4 (1 %) 1 (< 1 %) 0 br\xf6stkorg och Mindre Orofaryngeal sm\xe4rta 3 (< 1 %) 00 mediastinum vanliga Mindre Bronkialbl\xf6dning 2 (< 1 %) 00'],
             ['Vascular', u'vanliga Mindre Rinnor\xe9 1 (< 1 %) 00'],
             ['Vascular', u'vanliga Mindre Hemoptys 1 (< 1 %) 00'],
             ['Vascular', u'vanliga'],
             ['Vascular', u'(46 %)'],
             ['Vascular', u'(44 %)'],
             ['Vascular', u'vanliga'],
             ['Vascular', u'vanliga'],
             ['Vascular', u'vanliga'],
             ['Vascular',
              u'Vanliga Utsp\xe4nd buk 16 (4 %) 2 (1 %) 0 Magtarmkanalen Vanliga Muntorrhet 14 (4 %) 00'],
             ['Vascular', u'Vanliga Dyspepsi 12 (3 %) 00'],
             ['Vascular', u'Vanliga Munbl\xf6dning 5 (1 %) 00'],
             ['Vascular', u'Vanliga Flatulens 5 (1 %) 00'],
             ['Vascular',
              u'Vanliga Analbl\xf6dning 4 (1 %) 00 Mindre Gastrointestinal bl\xf6dning 2 (< 1 %) 00'],
             ['Vascular', u'vanliga Mindre Rektal bl\xf6dning 2 (< 1 %) 00'],
             ['Vascular', u'vanliga Mindre Enterokutan fistel 1 (< 1 %) 1 (< 1 %) 0'],
             ['Vascular', u'vanliga Mindre Gastrisk bl\xf6dning 1 (< 1 %) 00'],
             ['Vascular', u'vanliga'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'huden'],
             ['Hepato', u'vanliga'],
             ['Hepato', u'Vanliga Alopeci 30 (8 %) 00'],
             ['Hepato', u'Vanliga Hudproblem c26 (7 %) 4 (1 %) 0'],
             ['Hepato', u'Vanliga Torr hud 21 (5 %) 00'],
             ['Hepato', u'Vanliga Hyperhydros 18 (5 %) 00'],
             ['Hepato',
              u'Vanliga Nagelproblem 13 (3 %) 00 Hud och subkutan v\xe4vnad Vanliga Pruritus 11 (3 %) 00'],
             ['Hepato', u'Vanliga Erytem 4 (1 %) 00 Mindre Huds\xe5r 3 (< 1 %) 1 (< 1 %) 0'],
             ['Hepato', u'vanliga Mindre Utslag 1 (< 1 %) 00'],
             ['Hepato', u'vanliga Mindre Papul\xf6st utslag 1 (< 1 %) 00'],
             ['Hepato', u'vanliga Mindre \xd6verk\xe4nslighetsreaktion 1 (< 1 %) 00'],
             ['Hepato', u'vanliga Mindre Palmar-plantar 2 (<1 %) 00'],
             ['Hepato', u'erytrodysestesisyndrom'],
             ['Hepato', u'Vanliga Muskuloskeletal v\xe4rk 35 (9 %) 2 (< 1 %) 0'],
             ['Hepato',
              u'Vanliga Myalgi 28 (7 %) 2 (< 1 %) 0 Muskuloskeletala Vanliga Muskelkramper 8 (2 %) 00 systemet och bindv\xe4v Mindre Artralgi 2 (< 1 %) 00'],
             ['Hepato',
              u'vanliga Mindre Proteinuri 2 (<1 %) 00 Njurar och urinv\xe4gar vanliga Graviditet, Mindre Vaginal bl\xf6dning 3 (< 1 %) 00 puerperium och vanliga perinatalperiod Mindre Menorragi 1 (< 1 %) 00'],
             ['Hepato',
              u'vanliga Allm\xe4nna symtom Mycket Tr\xf6tthet 178 34 (9 %) 1 (< 1 %) och/eller symtom vid vanliga (47 %)'],
             ['Investigations', u'vanliga Mindre Aspartataminotransferas 2 (< 1 %) 02 (< 1 %)'],
             ['Investigations', u'vanliga Mindre Alaninaminotransferas 1 (< 1 %) 01 (< 1 %)'],
             ['Investigations',
              u'vanliga Mindre Minskat antal trombocyter 1 (< 1 %) 01 (< 1 %)'],
             ['Investigations', u'vanliga Mindre F\xf6rl\xe4ngt QT I 2 (< 1 %) 1 (< 1 %) 0'],
             ['Investigations',
              u'elektrokardiogram F\xf6ljande biverkningar har kombinerats: Buksm\xe4rta, sm\xe4rta i \xf6vre buken och gastrointestinal sm\xe4rta \xd6dem, perifert \xf6dem och \xf6gonlocks\xf6dem Majoriteten av dessa fall var palmar-plantar erytrodysestesisyndrom d Ven\xf6sa tromboemboliska h\xe4ndelser \u2013 omfattar djup ventrombos, lungemboli och trombosbiverkningar e Majoriteten av dessa fall beskriver mukosit f Frekvensen baseras p\xe5 tabeller \xf6ver laboratoriev\xe4rden fr\xe5n VEG110727 (N=240). Dessa rapporterades mindre frekvent som biverkningar av pr\xf6varna \xe4n vad som framg\xe5r av tabellerna \xf6ver laboratoriev\xe4rdena. H\xe4ndelser av hj\xe4rtdysfunktion \u2013 omfattar v\xe4nsterkammardysfunktion, hj\xe4rtsvikt och restriktiv kardiomyopati. h Frekvensen baseras p\xe5 biverkningar som rapporterats av pr\xf6varna. Onormala laboratoriev\xe4rden rapporterades mindre frekvent som biverkningar av pr\xf6varna \xe4n vad som framg\xe5r av tabellerna \xf6ver laboratoriev\xe4rdena.']]],
           ['Unknown',
            [['Endocrine', u'systemet'],
             ['Metabolism', u'Mindre Hypomagnesemi 10 (< 1 %) 00'],
             ['Skin', u'subkutan v\xe4vnad Mindre Ljusk\xe4nslighetsreaktion 7 (1 %) 00'],
             ['General',
              u'och/eller symtom vid administ- Vanliga Br\xf6stsm\xe4rta 18 (2 %) 2 (< 1 %) 0 reringsst\xe4llet Mindre Frossa 4 (< 1 %) 00'],
             ['Investigations', u'Mindre F\xf6rh\xf6jt blodbilirubin 2 (<1 %) 00']]]],
 '_pages': [9, 18],
 u'_rank': 155,
 u'_type': u'LSFU'}