{'_data': [['Very common', [['Blood', u'Bl\xf6dning fr\xe5n olika organ']]],
           ['Common',
            [['Blood', u'\xd6kad k\xe4nslighet f\xf6r warfarin efter l\xe5ngtidsbehandling']]],
           ['Uncommon',
            [['Blood', u'Anemi'],
             ['GI', u'Kr\xe4kning, buksm\xe4rta, illam\xe5ende, diarr\xe9']]],
           ['Rare',
            [['Blood', u'Eosinofili'],
             ['Hepato', u'\xd6kning av leverenzymer, gulsot'],
             ['Skin', u'Eksem, vaskulit, nekros, alopeci, utslag, urtikaria, kl\xe5da'],
             ['Renal', u'Nefrit, urolitiasis, tubul\xe4r nekros']]]],
 '_pages': [10, 11],
 u'_rank': 8,
 u'_type': u'LSFU'}