{'_data': [['Common',
            [['Vascular', u'Bl\xf6dning'], ['GI', u'Illam\xe5ende, kr\xe4kning, diarr\xe9']]],
           ['Rare', [['Vascular', u'Kumarinnekros, \u201dpurple toe-syndrome\u201d']]],
           ['Very rare',
            [['Vascular', u'Vaskulit'],
             ['Respiratory', u'Trakeal kalcifiering'],
             ['Hepato', u'Reversibel hepatisk enzymh\xf6jning, kolestatisk hepatit'],
             ['Skin', u'Reversibel alopeci, utslag.'],
             ['Reproductive system', u'Priapism'],
             ['General', u'Allergiska reaktioner (vanligtvis manifesterat som hudutslag)'],
             ['Investigations', u'Kolesterolembolism']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 8],
 u'_rank': 10,
 u'_type': u'MSFU'}