{'_data': [['Very common', [['GI', u'illam\xe5ende'], ['Skin', u'hudutslag, kl\xe5da']]],
           ['Common',
            [['Blood', u'anemi, neutropeni'],
             ['Metabolism', u'hyponatremi'],
             ['Psychiatric', u'insomnia'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'diarr\xe9, kr\xe4kningar'],
             ['Hepato', u'f\xf6rh\xf6jda leverenzymv\xe4rden'],
             ['Immune system',
              u'\xf6verk\xe4nslighetsreaktioner inkluderande angio\xf6dem, bronkospasm och tr\xe5nghetsk\xe4nsla i halsen'],
             ['Skin', u'urtikaria'],
             ['General', u'feber']]],
           ['Uncommon', [['Investigations', u'f\xf6rh\xf6jda amylasniv\xe5er']]],
           ['Unknown', [['Skin', u'erythema multiforme, Stevens-Johnsons syndrom']]]],
 '_pages': [4, 4],
 u'_rank': 13,
 u'_type': u'LSFU'}