{'_data': [['Very common', [['Blood', u'leukopeni och  trombocytopeni']]],
           ['Common',
            [['Blood', u'Anemi  Artralgi, hudutslag,'],
             ['Metabolism', u'Anorexi  Stomatit, diarr\xe9, kr\xe4kningar,'],
             ['Metabolism', u'illam\xe5ende'],
             ['Hepato', u'Gallstas, levertoxicitet']]],
           ['Uncommon',
            [['Immune system', u'l\xe4kemedelsfeber'],
             ['GI', u'Pankreatit, orala s\xe5r'],
             ['Hepato', u'Levernekros']]],
           ['Rare',
            [['Immune system', u'Ansikts\xf6dem'],
             ['Skin', u'Alopeci'],
             ['Reproductive system', u'\xd6verg\xe5ende oligospermi']]],
           ['Very rare',
            [['Neoplasms', u'Sekund\xe4r leukemi och myelodysplasi Benm\xe4rgssuppression,'],
             ['GI', u'Intestinala s\xe5r']]]],
 '_pages': [6, 7],
 u'_rank': 13,
 u'_type': u'TSFU'}