{'_data': [['Very common', [['Nervous system', u'Sedation, somnolens']]],
           ['Common',
            [['Metabolism', u'Minskad aptit'],
             ['Psychiatric',
              u'F\xf6rvirringstillst\xe5nd, depression, desorientering, nedsatt libido'],
             ['Nervous system',
              u'Ataxi, balansst\xf6rningar, koordinationssv\xe5righeter, f\xf6rs\xe4mrat minne, dysarti, koncentrationssv\xe5righeter, hypersomni, letargi, yrsel, huvudv\xe4rk'],
             ['Eye', u'Dimsyn'],
             ['GI', u'F\xf6rstoppning, muntorrhet, illam\xe5ende'],
             ['Reproductive system', u'Tr\xf6tthet, irritabilitet']]],
           ['Uncommon',
            [['Endocrine', u'Hyperprolaktinemi'],
             ['Psychiatric',
              u'Oro, insomni, nervositet, hypomani, mani (se avsnitt 4.4), hallucinationer, ilska, aggressivitet, fientlighet, agitation, p\xe5verkan p\xe5 libido, vanf\xf6rest\xe4llningar, psykomotorisk hyperaktivitet'],
             ['Nervous system', u'Amnesi, tremor, dystoni'],
             ['GI', u'Gastrointestinala symptom'],
             ['Hepato', u'Hepatit, onormal leverfunktion, gulsot'],
             ['Skin', u'Dermatit'],
             ['Musculoskeletal', u'Muskelsvaghet'],
             ['Renal', u'Inkontinens, urinretention'],
             ['Reproductive system',
              u'Sexuell dysfunktion, oregelbunden menstruation Allm\xe4nna symtom och/eller symtom vid administreringsst\xe4llet'],
             ['Investigations',
              u'Viktf\xf6r\xe4ndring, \xf6kat intraokul\xe4rt tryck Depression Hos k\xe4nsliga individer kan tidigare ouppt\xe4ckt depression bli tydlig vid anv\xe4ndning av bensodiazepiner. Psykiatriska och \u201dparadoxala\u201d reaktioner Reaktioner som rastl\xf6shet, agitation, irritation, aggressivitet, vanf\xf6rest\xe4llningar, raseriutbrott, mardr\xf6mmar, hallucinationer, psykoser, ol\xe4mpligt beteende och andra beteendest\xf6rningar kan f\xf6rekomma, de uppst\xe5r fr\xe4mst hos \xe4ldre patienter. Beroende Anv\xe4ndning av denna substans (\xe4ven vid terapeutiska doser) kan leda till utvecklande av ett fysiskt beroende. Behandlingsavbrott kan d\xe4rf\xf6r leda till uts\xe4ttningsreaktioner och reboundfenomen (se \xe4ven avsnitt 4.4). Psykiskt beroende kan uppst\xe5. Exempel p\xe5 missbruk har rapporterats. Amnesi Anterograd amnesi kan uppst\xe5 \xe4ven vid terapeutiska doser och risken \xf6kar vid h\xf6gre doser. Amnesi kan \xe5tf\xf6ljas av ol\xe4mpligt beteende (se \xe4ven avsnitt 4.4).']]],
           ['Unknown',
            [['Metabolism', u'Anorexi, aptitstimulering'],
             ['Nervous system',
              u'Obalans i autonoma nervsystemet, nedsatt reaktionsf\xf6rm\xe5ga, talsv\xe5righeter'],
             ['Vascular', u'Hypotoni'],
             ['GI', u'Dysfagi']]]],
 '_pages': [5, 7],
 u'_rank': 21,
 u'_type': u'LSFU'}