{'_data': [['Common',
            [['Blood', u'Anemi (inkl. respektive laboratorieparameter)'],
             ['Nervous system', u'Yrsel, huvudv\xe4rk'],
             ['Eye', u'Bl\xf6dning fr\xe5n \xf6gat (inkl. konjunktivalbl\xf6dning)'],
             ['Vascular', u'Hypotoni, hematom'],
             ['Respiratory', u'Epistaxis, hemoptys'],
             ['GI',
              u'Gingivalbl\xf6dning, bl\xf6dning i magtarmkanalen (inkl. rektalbl\xf6dning),'],
             ['GI', u'buksm\xe4rta, dyspepsi, illam\xe5ende, konstipation kr\xe4kning A'],
             ['Skin',
              u'Kl\xe5da (inkl. s\xe4llsynta fall av generaliserad kl\xe5da), hudutslag, ekkymos, kutan och subkutan bl\xf6dning'],
             ['Musculoskeletal', u'Sm\xe4rta i extremitet'],
             ['Renal',
              u'Urogenitala bl\xf6dningar (inkl. hematuri och menorragi B ), f\xf6rs\xe4mrad njurfunktion (inkl. f\xf6rh\xf6jning av blodkreatinin, f\xf6rh\xf6jning av blodurea) A , perifert \xf6dem, A minskad allm\xe4n kraft och energi (inkl. tr\xf6tthet, asteni)'],
             ['Investigations',
              u'F\xf6rh\xf6jning av transaminaser Bl\xf6dning efter ingrepp (inkl. postoperativ anemi och s\xe5rbl\xf6dning), kontusion, s\xe5rsekret A kirurgisk elektiv h\xf6ft-vanlig koronarsyndrom (efter perkutan']]],
           ['Uncommon',
            [['Blood', u'Trombocytemi (inkl. f\xf6rh\xf6jt trombocytv\xe4rde) A'],
             ['Immune system', u'Allergisk reaktion, allergisk dermatit'],
             ['Nervous system', u'Cerebral och intrakraniell bl\xf6dning, synkope'],
             ['Cardiac', u'Takykardi'],
             ['GI', u'Muntorrhet'],
             ['GI', u'A , diarr\xe9,'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin', u'Urtikaria'],
             ['Musculoskeletal', u'A Hemartros'],
             ['Renal', u'Feber Sjukdomsk\xe4nsla (inkl. malaise)'],
             ['Investigations',
              u'F\xf6rh\xf6jt bilirubin, f\xf6rh\xf6jt alkaliskt fosfatas i blod A , f\xf6rh\xf6jt LDH eller kn\xe4ledsplastik -hos kvinnor <55 \xe5r intervention) ']]],
           ['Rare',
            [['Hepato', u'Gulsot'],
             ['Musculoskeletal', u'Muskelbl\xf6dning Kompartment'],
             ['Renal', u'Lokalt \xf6dem A'],
             ['Investigations',
              u'F\xf6rh\xf6jning av A , f\xf6rh\xf6jt konjugerat samtidig ALAT-f\xf6rh\xf6jning) Vaskul\xe4rt pseudoaneurys C m']]],
           ['Unknown',
            [['Musculoskeletal', u'syndrom sekund\xe4rt till bl\xf6dning'],
             ['Renal',
              u'Njursvikt/akut njursvikt sekund\xe4rt till bl\xf6dning tillr\xe4cklig f\xf6r att orsaka hypoperfusion']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 10],
 u'_rank': 28,
 u'_type': u'MSFU'}