{'_data': [['Common',
            [['Cardiac',
              u'Postural hypotension (initialt, framf\xf6r allt vid f\xf6r h\xf6g dos, eller vid \xe5terupptagen terapi efter kortare avbrott).'],
             ['Cardiac', u'Svindel, yrsel, sjukdomsk\xe4nsla, huvudv\xe4rk.'],
             ['GI', u'Buksm\xe4rtor, diarr\xe9, illam\xe5ende, muntorrhet.'],
             ['General', u'Asteni.']]],
           ['Uncommon',
            [['Cardiac',
              u'Synkope (initialt, framf\xf6r allt vid f\xf6r h\xf6g dos, eller vid \xe5terupptagen terapi efter kortare avbrott), takykardi, palpitationer.'],
             ['Cardiac', u'D\xe5sighet.'],
             ['Eye', u'Synst\xf6rningar.'],
             ['Eye', u'Rinit.'],
             ['GI', u'Kr\xe4kningar, dyspepsi.'],
             ['Renal', u'Urininkontinens.'],
             ['Skin', u'Hudutslag (urtikaria, exantem), pruritus.'],
             ['General', u'V\xe4rmevallningar, \xf6dem, br\xf6stsm\xe4rtor.']]],
           ['Very rare',
            [['Cardiac',
              u'Angina pectoris, f\xf6retr\xe4desvis hos patienter med befintlig kransk\xe4rlssjukdom (se avsnitt 4.4).'],
             ['Skin', u'Angio\xf6dem.']]],
           ['Unknown',
            [['Blood', u'Neutropeni, trombocytopeni.'],
             ['Cardiac', u'F\xf6rmaksflimmer. Centrala och perifera'],
             ['Eye',
              u'Intraoperative Floppy Iris Syndrome (se avsnitt 4.4). Andningsv\xe4gar, br\xf6stkorg och mediastinum'],
             ['General', u'och/eller symtom vid administreringsst\xe4llet'],
             ['Hepato',
              u'Hepatocellul\xe4r skada, kolestatisk leversjukdom. Reproduktionsorgan och br\xf6stk\xf6rtel']]]],
 '_pages': [3, 4],
 u'_rank': 19,
 u'_type': u'LSFU'}