{'_data': [['Common',
            [['Investigations',
              u'a Vanliga Baserat p\xe5 f\xf6rekomst oavsett om ett samband f\xf6rel\xe5g eller ej. Biverkningar rapporterade efter marknadsf\xf6ring. Se avsnitt 4.4. Sammantaget i de olika kliniska studierna observerades en liten \xf6kning av antalet vita blodkroppar (LPK) till f\xf6ljd av \xf6kad m\xe4ngd neutrofila granulocyter (skillnaden i LPK j\xe4mf\xf6rt med placebo var ca 0,2x10 /l; medelutg\xe5ngsv\xe4rdet f\xf6r LPK var i genomsnitt 6,6x10 /l). Detta observerades i de flesta men inte alla studier. Denna f\xf6r\xe4ndring av laboratoriev\xe4rden anses inte kliniskt relevant.']]],
           ['Unknown',
            [['Infections', u'\xf6vre luftv\xe4gsinfektion Vanliga nasofaryngit Vanliga'],
             ['Immune system',
              u'\xf6verk\xe4nslighets- reaktioner inkluderande Ingen k\xe4nd frekvens anafylaxi'],
             ['Metabolism',
              u'hypoglykemi Vanliga Vanliga Vanliga Mycket Vanliga Vanliga Vanliga'],
             ['Respiratory', u'interstitiell lungsjukdom Ingen k\xe4nd frekvens'],
             ['GI',
              u'Mindre diarr\xe9 vanliga Mindre muntorrhet vanliga illam\xe5ende Vanliga flatulens Vanliga Vanliga Mindre Mindre Vanliga Mindre f\xf6rstoppning vanliga vanliga vanliga Mindre \xf6vre buksm\xe4rta vanliga kr\xe4kningar Ingen k\xe4nd Vanliga Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd frekvens frekvens frekvens frekvens frekvens frekvens akut pankreatit Ingen k\xe4nd frekvens'],
             ['Skin',
              u'exfoliativa hudtillst\xe5nd inkluderande Ingen k\xe4nd frekvens Stevens-Johnsons syndrom'],
             ['Musculoskeletal',
              u'Ingen sm\xe4rta i armar eller Vanliga k\xe4nd Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd Ingen k\xe4nd ben frekvens frekvens frekvens frekvens frekvens frekvens artralgi Ingen k\xe4nd frekvens myalgi Ingen k\xe4nd frekvens ryggsm\xe4rta Ingen k\xe4nd frekvens'],
             ['Renal',
              u'nedsatt njurfunktion Ingen k\xe4nd frekvens akut njursvikt Ingen k\xe4nd frekvens'],
             ['General', u'perifert \xf6dem Vanliga Vanliga']]]],
 '_pages': [4, 6],
 u'_rank': 10,
 u'_type': u'LSFU'}