{'_data': [['Very common',
            [['Psychiatric', u'Depression'],
             ['Nervous system',
              u'D\xe5sighet Parkinsonism (kan innefatta: f\xf6rs\xe4mrad balans, tremor,hyper-salivation)'],
             ['Cardiac', u'Bradykardi'],
             ['Vascular', u'Posturalhypotension ']]],
           ['Common', [['Psychiatric', u'Oro F\xf6rvirring \xc5ngest S\xf6mnl\xf6shet']]],
           ['Uncommon', []],
           ['Rare', []],
           ['Very rare',
            [['Blood', u'Leukopeni'],
             ['Nervous system', u'Malignt neuroleptikasyndrom'],
             ['Eye', u'Okulogyr kris Fotofobi']]]],
 '_note': u' ?MSFU',
 '_pages': [3, 4],
 u'_rank': 8,
 u'_type': u'MSFU'}