{'_data': [['Very common', [['Respiratory', u'Dyspn\xe9'], ['GI', u'Diarr\xe9']]],
           ['Common',
            [['Metabolism', u'Hypokalcemi'],
             ['Metabolism', u'Hypofosfatemi'],
             ['GI', u'Tandextraktion'],
             ['Skin', u'Hyperhidros'],
             ['Musculoskeletal', u'Osteonekros i k\xe4ken']]],
           ['Uncommon',
            [['Infections', u'Cellulit'],
             ['Immune system', u'\xd6verk\xe4nslighet mot l\xe4kemedel']]]],
 '_pages': [4, 5],
 u'_rank': 9,
 u'_type': u'TSFU'}