{'_data': [['Very common',
            [['Metabolism', u'ga Mindre S\xe4llsynta Mycket'],
             ['GI', u'ga Mindre S\xe4llsynta Mycket'],
             ['General', u'ga Mindre S\xe4llsynta Mycket']]],
           ['Common',
            [['Metabolism', u'vanliga s\xe4llsynta diabetespatienter) Hyponatremi SIADH'],
             ['GI', u'vanliga s\xe4llsynta (10,3 %) Flatulens D\xe5lig andedr\xe4kt'],
             ['General', u'vanliga s\xe4llsynta varm']]],
           ['Unknown',
            [['Infections', u'Laryngit'],
             ['Endocrine', u'Hypotyreos'],
             ['Metabolism',
              u'Aptitneds\xe4tt- Dehydrering Hyperglykemi ning (s\xe4rskilt hos 7'],
             ['Psychiatric',
              u'S\xf6mnl\xf6shet Bruxism Sj\xe4lvmords- Agitation Desorien- beteende 5,6 Minskad tering Sj\xe4lvmords libido Abnorma 5,7 tankar \xc5ngest dr\xf6mmar 6 Mani S\xf6mn- Apati Hallucinationer st\xf6rningar Onormal Aggression och orgasm vrede Abnorma dr\xf6mmar'],
             ['Nervous system',
              u'Huvudv\xe4rk Oro Serotonergt Yrsel Uppm\xe4rksam- syndrom Letargi hetsst\xf6rning Krampanfall 1,6 Somnolens Dysgeusi Myoklonus Tremor D\xe5lig s\xf6mn 6 Akatisi Parestesier Psykomotorisk oro Extrapyramidala symtom Dyskinesi Restless legs'],
             ['Eye', u'Dimsyn Mydriasis Glaukom F\xf6rs\xe4mrad syn Torra \xf6gon'],
             ['Ear', u'\xd6ronsm\xe4rta'],
             ['Cardiac', u'f\xf6rmaksflimmer'],
             ['Vascular',
              u'Hypertoni Synkope Hypertonisk kris Rodnad Blodtrycks- Ortostatisk 3 \xf6kning hypotoni Extremitetskyla'],
             ['Respiratory', u'N\xe4sbl\xf6dning'],
             ['GI',
              u'Illam\xe5ende Diarr\xe9 Gastrointesti- Hematochezi (22,8 %) Buksm\xe4rta nal bl\xf6dning Muntorrhet Kr\xe4kningar Gastroenterit (12,1 %) Dyspepsi Stomatit F\xf6rstopp- Rapningar ning Gastrit 8'],
             ['Hepato',
              u'leverenzym- v\xe4rden (ALAT, ASAT, alkalisk fosfatas) Akut leverskada'],
             ['Skin',
              u'\xd6kad Utslag Stevens-Johnsons svettning Nattsvettning syndrom 6 Urtikaria Angioneurotiskt Kontakt- 6 \xf6dem dermatit Fotosensitivi Kallsvettning tetsreaktioner \xd6kad ben\xe4genhet att f\xe5 bl\xe5m\xe4rken'],
             ['Musculoskeletal', u'Muskel- sp\xe4nning Muskelkramp Trismus'],
             ['Renal', u'Nykturi Avvikande urinlukt'],
             ['Reproductive system', u'prolaktinemi'],
             ['General',
              u'Tr\xf6tthet Asteni Br\xf6stsm\xe4rta G\xe5ngrubbning (10,9 %) Frossa \xd6kad fallrisk K\xe4nna sig avvikande K\xe4nna sig kall T\xf6rst Sjukdoms k\xe4nsla K\xe4nna sig 9'],
             ['Investigations',
              u'\xd6kning av blodkolesterol F\xf6rh\xf6jning av kreatinkinas i blodet 1 Fall av krampanfall och tinnitus har \xe4ven rapporterats efter att behandlingen avslutats. 2 Fall av ortostatisk hypotoni och synkope har rapporterats, s\xe4rskilt i b\xf6rjan av behandlingen. Se avsnitt 4.4. 4 Fall av aggression och vrede har rapporterats speciellt i b\xf6rjan av behandlingen eller efter att behandlingen avslutats. 5 Fall av sj\xe4lvmordsfantasier och sj\xe4lvmordsbeteende har rapporterats under duloxetinbehandling eller kort efter avslutat behandling (se avsnitt 4.4). 6 Ber\xe4knad frekvens av biverkningar efter att l\xe4kemedlet b\xf6rjat marknadsf\xf6ras; ej observerade i placebo-kontrollerade kliniska pr\xf6vningar. 7 Ingen statistiskt signifikant skillnad mot placebo. \xd6kad fallrisk var vanligare hos \xe4ldre (\u226565 \xe5rs \xe5lder). c. Beskrivning av utvalda biverkningar Uts\xe4ttningssymtom \xe4r vanliga vid avbrytande av behandling med duloxetin (s\xe4rskilt vid abrupt uts\xe4ttning). Yrsel, k\xe4nselst\xf6rningar (inklusive parestesier), s\xf6mnst\xf6rningar (inklusive insomni och intensiva dr\xf6mmar), tr\xf6tthet, s\xf6mnighet, agitation eller \xe5ngest, illam\xe5ende och/eller kr\xe4kning, tremor, huvudv\xe4rk, irritabilitet, diarr\xe9, kraftiga svettningar och svindel \xe4r de vanligast rapporterade biverkningarna. Vanligtvis \xe4r dessa biverkningar med SSRI- och SNRI-l\xe4kemedel l\xe4tta till m\xe5ttliga och \xf6verg\xe5ende. Emellertid kan de hos vissa patienter vara allvarliga och/eller l\xe5ngvariga. N\xe4r behandling med duloxetin inte l\xe4ngre beh\xf6vs rekommenderas d\xe4rf\xf6r en gradvis nedtrappning av dosen (se avsnitten 4.2 och 4.4). QT-tider, korrigerade f\xf6r hj\xe4rtfrekvens, skiljde sig inte mellan duloxetinbehandlade patienter och placebobehandlade patienter. Inga kliniskt signifikanta skillnader observerades med avseende p\xe5 QT, PR, QRS eller QTcB mellan duloxetinbehandlade och placebobehandlade patienter. Under den 12 veckor l\xe5nga akuta fasen i tre kliniska studier p\xe5 patienter med sm\xe4rtsam diabetesneuropati s\xe5gs en liten men statistiskt signifikant \xf6kning av blodglukos vid fasta hos patienter behandlade med duloxetin. HbA 1c var stabilt hos b\xe5de duloxetin- och placebobehandlade patienter. Under studiernas forts\xe4ttningsfas, som p\xe5gick i upp till 52 veckor, f\xf6rekom en \xf6kning av HbA1c hos b\xe5de duloxetin- och rutinv\xe5rdsgruppen. Den genomsnittliga \xf6kningen var dock 0,3 % h\xf6gre i den duloxetinbehandlade gruppen. Det f\xf6rekom ocks\xe5 en liten \xf6kning av blodglukos vid fasta och totalkolesterol hos duloxetinbehandlade patienter, medan laboratorietest visade en liten s\xe4nkning i rutinv\xe5rdsgruppen.']]]],
 '_pages': [7, 10],
 u'_rank': 24,
 u'_type': u'LSFU'}