{'_data': [['Very common',
            [['Blood',
              u'Neutropeni* (grad 3 = 26 %, grad 4 = 24 %), trombocytopeni* (grad 3 = 11 %, grad 4 = 2 %), anemi* (grad 3 = 10 %, grad 4 = 3 %), leukopeni*'],
             ['Metabolism', u'Anorexi (grad 3-4 <1 %)'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI',
              u'Kr\xe4kningar (grad 3-4 = 6,5 %), illam\xe5ende (grad 3-4 = 6 %), f\xf6rstoppning (grad 3-4 <1 %)'],
             ['Hepato',
              u'Hyperbilirubinemi* (grad 3 = 1 %), f\xf6rh\xf6jda niv\xe5er av alaninaminotransferas* (grad 3 = 38 %, grad 4 = 3 %), f\xf6rh\xf6jda niv\xe5er av aspartataminotransferas* (grad 3 = 44 %, grad 4 = 7 %), \xf6kat alkalisk fosfatas i blodet*, \xf6kat gamma-glutamyltransferas*'],
             ['General', u'Utmattning (grad 3-4 = 9 %), asteni (grad 3-4 = 1 %)'],
             ['Investigations',
              u'F\xf6rh\xf6jt blodkreatinfosfokinas* (grad 3-4 = 4 %), f\xf6rh\xf6jt blodkreatinin*, s\xe4nkt blodalbumin*']]],
           ['Common',
            [['Infections', u'Infektion'],
             ['Blood', u'Febril neutropeni'],
             ['Metabolism', u'Uttorkning, minskad aptit, hypokalemi'],
             ['Psychiatric', u'Insomnia'],
             ['Nervous system', u'Perifer sensorisk neuropati, dysgeusi, yrsel, parestesi'],
             ['Vascular', u'Hypotension, rodnad'],
             ['Respiratory', u'Dyspn\xe9 (grad 3-4 = 2 %), hosta '],
             ['GI',
              u'Diarr\xe9 (grad 3-4 < 1 %), stomatit (grad 3-4 <1 %), magsm\xe4rta, dyspepsi, \xf6vre buksm\xe4rta'],
             ['Skin', u'Alopeci'],
             ['Musculoskeletal', u'Myalgi, artralgi, ryggsm\xe4rta '],
             ['General',
              u'Pyrexi, \xf6dem, perifert \xf6dem, reaktion vid injektionsst\xe4llet '],
             ['Investigations', u'Viktminskning']]]],
 '_pages': [6, 11],
 u'_rank': 19,
 u'_type': u'LSFU2'}