{'_data': [['Very common',
            [['Metabolism', u'Viktuppg\xe5ng'],
             ['Nervous system', u'Somnolens'],
             ['Investigations',
              u'F\xf6rh\xf6jd plasmaprolaktinniv\xe5 var vanligt (4,2%) och var det mycket vanligt Normala v\xe4rden (<5,17 mmol/l) F\xf6r\xe4ndringar i totalkolesterolv\xe4rden b\xf6rjan till h\xf6ga ( Normala niv\xe5er fasteglukos F\xf6r\xe4ndringar i fasteglukos var mycket vanligt. Normala v\xe4rden (<1,69 mmol/l) F\xf6r\xe4ndringar i triglyceridv\xe4rden b\xf6rjan till h\xf6ga ( syndrom. rapporterats vid abrupt L\xe5ngtidsbehandling (minst gav \xf6kad frekvens ( seminatriumvalproat f\xf6rekom gav en \xf6kning i kroppsvikt studiens b\xf6rjan. Pediatrisk population ungdomar med data fr\xe5n ungdomar. Kliniskt signifikant frekvensangivelser anv\xe4nds:'],
             ['Metabolism', u'Mycket vanlig: viktuppg\xe5ng vanlig'],
             ['Nervous system', u'mycket vanlig'],
             ['GI', u'vanlig : muntorrhet.'],
             ['Hepato', u'mycket vanlig (ALAT/ASAT, se avsnitt'],
             ['Investigations',
              u'Mycket vanlig: minskat 9 Vid korttidsbehandling (kg) fr\xe5n studiens b\xf6rjan studiens b\xf6rjan var vanlig veckor), fick 89,4% en viktuppg\xe5ng om Normala v\xe4rden 16 mmol/l) F\xf6r\xe4ndringar i triglyceridv\xe4rden b\xf6rjan till h\xf6ga ( h\xf6gt ( studiens b\xf6rjan (']]],
           ['Common',
            [['Blood', u'Eosinofili'],
             ['Metabolism',
              u'F\xf6rh\xf6jd kolesterolniv\xe5 F\xf6rh\xf6jd glukosniv\xe5 F\xf6rh\xf6jd triglyceridniv\xe5 Glykosuri \xd6kad aptit'],
             ['Nervous system', u'Yrsel Akatisi Parkinsonism Dyskinesi'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['GI',
              u'Milda, \xf6verg\xe5ende antikolinerga effekter, inklusive f\xf6rstoppning och muntorrhet'],
             ['Hepato',
              u'\xd6verg\xe5ende, asymtomatiska f\xf6rh\xf6jningar av leveramino-transferaser (ALAT, ASAT), s\xe4rskilt i b\xf6rjan av behandlingen (se avsnitt 4.4)'],
             ['Skin', u'Utslag'],
             ['Reproductive system',
              u'Erektil dysfunktion hos m\xe4n Minskad libido hos b\xe5da k\xf6nen Asteni Tr\xf6tthet \xd6dem'],
             ['Investigations',
              u'>25% var mindre vanligt (0,8%). Under l\xe5ngtidsbehandling (minst 48 veckor) (64,4%, 31,7% respektive 12,3%) att patienterna fick en viktuppg\xe5ng p\xe5 >7%, -vid fasta vid studiens b\xf6rjan \xf6kade till h\xf6ga ( -vid fasta fr\xe5n gr\xe4nsfall ( ->6,2 mmol/l) var mycket vanligt. (<5,56 mmol/l) vid studiens b\xf6rjan \xf6kade till h\xf6ga ( -fr\xe5n gr\xe4nsfall ( -vid fasta vid studiens b\xf6rjan \xf6kade till h\xf6ga ( -vid fasta fr\xe5n gr\xe4nsfall ( ->2,26 mmol/l) var mycket vanligt. uts\xe4ttande av olanzapin. -48 veckor) ->10 %) av tremor, muntorrhet, \xf6kad aptit och vikt\xf6kning. Talsv\xe5righeter en \xf6kning i kroppsvikt om -om >7 % hos 39,9 % av patienterna, j\xe4mf\xf6rt med kroppsvikten f\xf6re studier p\xe5 vuxna. -viktuppg\xe5ng ( -mycket vanlig ( '],
             ['Metabolism',
              u', f\xf6rh\xf6jd triglyceridniv\xe5 : f\xf6rh\xf6jd kolesterolniv\xe5'],
             ['Nervous system', u': sedering (inklusive hypersomni, letargi, somnolens).'],
             ['Hepato', u': f\xf6rh\xf6jda niv\xe5er av leveraminotransferaser 4.4). '],
             ['Investigations',
              u'totalbilirubin, \xf6kat GGT, f\xf6rh\xf6jd plasmaprolaktinniv\xe5 -(median behandlingstid 22 dagar) var viktuppg\xe5ng om -mycket vanlig (40,6%), viktuppg\xe5ng om -(7,1%) och -viktuppg\xe5ng om ->25% av kroppsvikten fr\xe5n studiens b\xf6rjan. vid fasta vid studiens b\xf6rjan \xf6kade till h\xf6ga ( -vid fasta fr\xe5n gr\xe4nsfall ( ->1,467 mmol/l). >5,17 mmol/l) var vanligt. F\xf6r\xe4ndringar i totalt kolesterolv\xe4rde vid fasta fr\xe5n gr\xe4nsfall vid >4,39-<5,17 mmol/l) till h\xf6gt (>5,17 mmol/l) var mycket vanligt.']]],
           ['Uncommon',
            [['Blood', u'Leukopeni Neutropeni'],
             ['Cardiac', u'Bradykardi QTc-f\xf6rl\xe4ngning (se avsnitt 4.4)'],
             ['Vascular',
              u'Tromboemboli (inklusive lungemboli och djup ventrombos) (se avsnitt 4.4)'],
             ['Skin', u'Fotosensitivitetsreaktioner Alopeci'],
             ['Renal', u'Urininkontinens, urinretention'],
             ['Reproductive system',
              u'Amenorr\xe9 Br\xf6stf\xf6rstoring Galaktorr\xe9 hos kvinnor Gynekomasti/br\xf6stf\xf6rstoring hos m\xe4n'],
             ['Investigations',
              u'H\xf6g kreatinfosfokinasniv\xe5 \xd6kad total bilirubinniv\xe5 >5,17 mmol/l-<6,2 mmol/l) vid studiens >5,56-<7 mmol/l) vid studiens b\xf6rjan till h\xf6ga (>7 mmol/l) >1,69 mmol/l-<2,26 mmol/l) vid studiens >7 % hos 17,4 % av patienterna under den >7 %) tycks upptr\xe4da oftare hos den unga >, vanlig .'],
             ['Metabolism', u', \xf6kad aptit.'],
             ['Investigations',
              u'>25% var vanlig (2,5%). Under l\xe5ngtidsbehandling (minst 24 >7%, 55,3% en viktuppg\xe5ng om >15% och 29,1% en >16 mmol/l-<1,467 mmol/l) vid studiens']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Allergisk reaktion'],
             ['Metabolism',
              u'Utveckling eller f\xf6rs\xe4mring av diabetessjukdomen, ibland associerat med ketoacidos eller koma, inklusive n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4) Hypotermi'],
             ['Nervous system',
              u'Kramper, d\xe4r det i de flesta fall finns kramper eller riskfaktorer f\xf6r kramper i anamnesen. Malignt neuroleptikasyndrom (se avsnitt 4.4) Dystoni (inklusive okulogyration Tardiv dyskinesi Uts\xe4ttningssymtom'],
             ['Cardiac',
              u'Ventrikul\xe4r takykardi/flimmer, pl\xf6tsligt d\xf6dsfall (se avsnitt 4.4)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (inklusive hepatocellul\xe4r, kolestatisk eller blandad leverskada)'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Renal', u'Urintr\xe4ngningar'],
             ['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom (se avsnitt 4.6)'],
             ['Reproductive system', u'Priapism'],
             ['Investigations',
              u'\xd6kat alkaliskt fosfatas >6,2 mmol/l). >7 mmol/l). >2,26 mmol/l).'],
             ['Investigations',
              u'. >7% av kroppsvikten >15% av kroppsvikten fr\xe5n >1,467 mmol/l).']]]],
 '_note': u' ?MSFU',
 '_pages': [6, 10],
 u'_rank': 43,
 u'_type': u'MSFU'}