{'_data': [['Common', [['Eye', u'\xd6gonirritation, \xf6gonsm\xe4rta, punktuell keratit.']]],
           ['Uncommon',
            [['Eye',
              u'Dimsyn (under instillation), \xf6gontorrhet, \xf6gonlocksirritation, konjunktivit, ljusk\xe4nslighet, konjunktival bl\xf6dning.'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['General', u'Somnolens'],
             ['Skin', u'Hudutslag, eksem, urticaria'],
             ['GI', u'Muntorrhet'],
             ['Immune system', u'\xd6verk\xe4nslighet']]]],
 '_pages': [2, 3],
 u'_rank': 7,
 u'_type': u'LSFU'}