{'_data': [['Uncommon', [['Cardiac', u'Takykardi  Palpitationer'], ['Vascular', u'Flushing']]],
           ['Rare',
            [['Psychiatric', u'S\xf6mnighet'],
             ['Cardiac', u'Angina pectoris'],
             ['GI', u'Illam\xe5ende; dyspepsi; diarr\xe9;  buksm\xe4rta; kr\xe4kningar'],
             ['Skin', u'Hudutslag']]],
           ['Very rare', [['Immune system', u'\xd6verk\xe4nslighet'], ['Vascular', u'Synkope']]]],
 '_pages': [4, 5],
 u'_rank': 8,
 u'_type': u'TSFU'}