{'_data': [['Very common',
            [['Nervous system', u'yrsel'],
             ['Eye', u'dimsyn'],
             ['Respiratory', u'hosta'],
             ['GI', u'illam\xe5ende.'],
             ['General', u'asteni']]],
           ['Common',
            [['Immune system',
              u'\xf6verk\xe4nslighet, angio\xf6dem angioneurotiskt \xf6dem i ansikte, extremiteter, l\xe4ppar, tunga, st\xe4mband och/eller svalg har rapporterats (se avsnitt 4.4).'],
             ['Psychiatric', u'depression.'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['Cardiac',
              u'hj\xe4rtinfarkt, m\xf6jligt sekund\xe4r till stark hypotoni i h\xf6griskpatienter (se avsnitt 4.4), arrytmi, angina pectoris, tackykardi.'],
             ['Vascular',
              u'hypotension, synkope, cerebrovaskul\xe4ra rubbningar, m\xf6jligt sekund\xe4r till stark hyper toni i h\xf6griskpatienter (se avsnitt 4.4)'],
             ['Respiratory', u'dyspn\xe9'],
             ['GI', u'diarr\xe9, magsm\xe4rtor, smakf\xf6r\xe4ndringar.'],
             ['Skin', u'utslag'],
             ['General', u'tr\xf6tthet, br\xf6stsm\xe4rtor'],
             ['Investigations', u'f\xf6rh\xf6jda niv\xe5er i blodet av kalium och kreatinin.']]],
           ['Uncommon',
            [['Blood', u'anemi (inklusive aplastiska och hemolytiska former)'],
             ['Metabolism', u'hypoglykemi (se avsnitt 4.4), anorexi.'],
             ['Psychiatric', u'f\xf6rvirring, somnolens, s\xf6mnl\xf6shet, nervositet.'],
             ['Nervous system', u'parestesier'],
             ['Ear', u'yrsel, tinnitus'],
             ['Cardiac', u'palpitationer'],
             ['Vascular', u'rodnad, ortostatisk hypotoni'],
             ['Respiratory',
              u'rinnsnuva, pharolyngolaryeal sm\xe4rta och dysfoni, bronkospasm/astma.'],
             ['GI',
              u'tarmvred, pankreatit, kr\xe4kningar, dyspepsi, f\xf6rstoppning, orolig mage, muntorrhet, peptiskt ulkus'],
             ['Skin', u'hyperhidros, pruritus, urtikaria, alopeci.'],
             ['Renal', u'nedsatt njurfunktion, njursvikt, proteinuri'],
             ['Reproductive system', u'erektil dysfunktion'],
             ['General', u'malaise'],
             ['Investigations',
              u'f\xf6rh\xf6jda niv\xe5er av urea i blodet, s\xe4nkta niv\xe5er av natrium i blodet.'],
             ['Nervous system', u'huvudv\xe4rk, yrsel'],
             ['Cardiac', u'tackykardi, palpitationer'],
             ['Vascular', u'rodnad'],
             ['General', u'perifert \xf6dem']]],
           ['Rare',
            [['Blood',
              u'neutropeni, trombocytopeni, agranulocytos, rubbningar i benm\xe4rg, pancytopeni, lymfadenopati'],
             ['Immune system', u'autoimmuna rubbningar'],
             ['Psychiatric', u'abnormala dr\xf6mmar, s\xf6mnst\xf6rningar.'],
             ['Vascular', u'Raynaud\xb4s fenomen'],
             ['Respiratory',
              u'lunginfiltration, rinit, allergisk alveolit/eosinofil lunginflammation.'],
             ['GI', u'stomatit, aft\xf6s stomatit, glossit.'],
             ['Hepato',
              u'leversvikt, hepatit \u2013 kolestatisk hepatit eller hepatisk nekros, kolestas (inklusive gulsot).'],
             ['Skin',
              u'erytema multiforme, Steven-Johnson\xb4s syndrom, exfoliativ dermatit, toxisk epidermal nekrolys, pemfigus. Ett komplext symtom har beskrivits, som kan inkludera ett eller flera f\xf6ljande symtom: feber, serotit, vaskulit, myalgi/myosit, artralgi/artrit, positiva antinukle\xe4ra antikroppar (ANA), f\xf6rh\xf6jd erytrocytsedimentationshastighet (ESR), eosinofili, leukocytos. Utslag, fotosensitivitet eller andra dermalogiska symtom kan f\xf6rekomma.'],
             ['Renal', u'oliguri.'],
             ['Reproductive system', u'gynekomasti'],
             ['Investigations',
              u'S\xe4nkta niv\xe5er av hemoglobin, s\xe4nkt hematokritv\xe4rde, \xf6kad m\xe4ngd leverenzymer, \xf6kad niv\xe5 av blodbilirubin. Lerkanidipin Biverkningar upptr\xe4dde hos cirka 1.8% av de behandlade patienterna. De vanligast f\xf6rekommande biverkningarna som rapporterades i kliniska pr\xf6vningar var huvudv\xe4rk, yrsel, perifert \xf6dem, tackykardi, palpitationer och rodnad, som samtliga f\xf6rekom hos mindre \xe4n 1% av patienterna.'],
             ['Psychiatric', u'somnolens'],
             ['Cardiac', u'angina pectoris'],
             ['GI', u'illam\xe5ende, dyspepsi, diarr\xe9, magsm\xe4rtor, kr\xe4kningar'],
             ['Skin', u'utslag'],
             ['Musculoskeletal', u'myalgi'],
             ['Renal', u'polyuri'],
             ['General',
              u'asteni, tr\xf6tthet Efter marknadsf\xf6ring har spontanrapportering av f\xf6ljande mycket s\xe4llsynta (<1/10 000) biverkningar inkommit; gingival hypertrofi, reversibla \xf6kningar av leverenzymer (transaminaser) i serum, hypotoni, \xf6kad urinfrekvens och br\xf6stsm\xe4rtor. Vissa dihydropyridinderivat kan i s\xe4llsynta fall orsaka br\xf6stsm\xe4rta eller angina pectoris. I mycket'],
             ['General',
              u'fall kan patienter som redan lider av angina pectoris drabbas av t\xe4tare, sv\xe5rare eller mer l\xe5ngdragna attacker. Enstaka fall av hj\xe4rtinfarkt har rapporterats. Lerkanidipin tycks inte p\xe5verka blodsocker- eller serumlipidniv\xe5er.']]],
           ['Very rare',
            [['GI', u'intestinalt \xf6dem'],
             ['Immune system', u'\xf6verk\xe4nslighet'],
             ['Vascular', u'synkope']]],
           ['Unknown',
            [['Respiratory',
              u'mediastinum Magtarmkanalen Magsm\xe4rtor, f\xf6rstoppning*, dyspepsi*, illam\xe5ende*, tungrubbningar* Hud och subkutan v\xe4vnad Erytem*, utslag* Muskoloskeletala systemet och Artralgi* bindv\xe4v Njurar och urinv\xe4gar Nocturi* Allm\xe4nna symtom Perifert \xf6dem Asteni, tr\xf6tthet, v\xe4rmek\xe4nsla* Unders\xf6kningar \xd6kning i ASAT/ALAT *endast hos en patient'],
             ['Musculoskeletal', u'muskelspasmer']]]],
 '_pages': [10, 13],
 u'_rank': 57,
 u'_type': u'LSFU'}