{'_data': [['Common', [['Hepato', u'\xd6verg\xe5ende leverenzymstegring.']]],
           ['Rare',
<<<<<<< HEAD
            [['Nervous system', u'Ofrivilliga r\xf6relser s\xe5som tremor och  myokloni'],
             ['GI',
              u'Buksm\xe4rta, f\xf6rstoppning, illam\xe5ende (dessa  symtom avtar vanligtvis vid fortsatt behandling)'],
             ['Hepato', u'Leversvikt (fatala fall har rapporterats).'],
             ['Skin', u'Ospecifika hudreaktioner.'],
             ['Renal',
              u'\xd6kade niv\xe5er av plasmakreatinin (vanligtvis  l\xe4tt f\xf6rh\xf6jning; normaliseras vid fortsatt behandling)']]],
           ['Very rare',
            [['Psychiatric',
=======
            [['Immune system', u'hypotension och br\xf6stsm\xe4rta.'],
             ['GI',
              u'Buksm\xe4rta, f\xf6rstoppning, illam\xe5ende (dessa  symtom avtar vanligtvis vid fortsatt behandling)'],
             ['Hepato', u'Leversvikt (fatala fall har rapporterats).'],
             ['Renal',
              u'\xd6kade niv\xe5er av plasmakreatinin (vanligtvis l\xe4tt  f\xf6rh\xf6jning; normaliseras vid fortsatt behandling)']]],
           ['Very rare',
            [['Blood',
              u'Agranulocytos, pancytopeni \xe4ven inkluderande  benm\xe4rgshypoplasi, hemolytisk anemi.'],
             ['Immune system', u'Anafylaktisk chock (har rapporterats efter en  singeldos).'],
             ['Psychiatric',
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
              u'Reversibel f\xf6rvirring, depression och  hallucinationer, s\xe4rskilt hos \xe4ldre och sv\xe5rt sjuka.'],
             ['Nervous system', u'Huvudv\xe4rk (ibland kraftig), yrsel, tr\xf6tthet.'],
             ['Eye', u'Ackommodationsrubbningar.'],
             ['Cardiac', u'Bradykardi, AV-block.'],
             ['Vascular', u'Vaskulit.'],
             ['GI', u'Pankreatit, diarr\xe9'],
             ['Hepato', u'Hepatit, ibland med gulsot.'],
<<<<<<< HEAD
             ['Skin', u'Erythema multiforme. Alopeci.'],
             ['Musculoskeletal', u'Atralgi. Myalgi.'],
             ['Renal', u'Akut interstitiell nefrit'],
             ['Reproductive system', u'Reversibel impotens. Gynekomasti.  Galaktorr\xe9.']]]],
 '_pages': [5, 6],
 u'_rank': 17,
=======
             ['Hepato', u'Erythema multiforme. Alopeci.'],
             ['Renal', u'Akut interstitiell nefrit']]]],
 '_pages': [5, 6],
 u'_rank': 16,
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 u'_type': u'TSFU'}