{'_data': [['Very common',
            [['Musculoskeletal', u'Muskuloskeletal sm\xe4rta (lindrig eller m\xe5ttlig)'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er i blodet av alkaliskt fosfatas, laktatdehydrogenas (LDH) och gamma-glutamyltransferas (GGT) och urinsyra (reversibelt, dosberoende, lindrigt eller m\xe5ttligt) * se nedan'],
             ['Blood',
              u'Leukocytos (Lkc > 50 x 10 /l), trombocytopeni (trombocyter < 100 x 10 /l, \xf6verg\xe5ende)'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (lindrig till m\xe5ttlig, \xf6verg\xe5ende)'],
             ['Blood', u'Anemi, splenomegali (kan vara progressiv i en minoritet av fallen)'],
             ['Respiratory', u'Epistaxis'],
             ['Musculoskeletal', u'Allm\xe4n muskuloskeletal sm\xe4rta, skelettsm\xe4rta'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er i blodet av alkaliskt fosfatas, LDH och urinsyra (\xf6verg\xe5ende), s\xe4nkt glukosniv\xe5 i blodet (\xf6verg\xe5ende, m\xe5ttlig)'],
             ['Musculoskeletal',
              u'Muskuloskeletal sm\xe4rta (lindrig till m\xe5ttlig) * se nedan I randomiserade, placebokontrollerade kliniska studier \xf6kade inte filgrastim incidensen av biverkningar i samband med cytotoxisk kemoterapi. De biverkningar som rapporterats med samma frekvens hos patienter som behandlas med filgrastim/kemoterapi och placebo/kemoterapi omfattade illam\xe5ende och kr\xe4kningar, alopeci, diarr\xe9, tr\xf6tthet, anorexi, mukosit, huvudv\xe4rk, hosta, hudutslag, br\xf6stsm\xe4rta, allm\xe4n svaghet, ont i halsen, f\xf6rstoppning och ospecificerad sm\xe4rta. Allergiska reaktioner f\xf6rekom vid initial eller senare behandling hos patienter som fick filgrastim. Generellt var rapporter vanligare efter intraven\xf6s administrering. I vissa fall har symtomen \xe5terkommit vid f\xf6rnyad behandling, vilket tyder p\xe5 ett orsakssamband. Filgrastim ska avbrytas permanent hos patienter som drabbas av en sv\xe5r allergisk reaktion. Det har f\xf6rekommit rapporter p\xe5 graft-versus-host-sjukdom (GvHD) och d\xf6dsfall hos patienter som f\xe5tt G-CSF efter allogen benm\xe4rgstransplantation (se avsnitt 5.1). Vaskul\xe4ra st\xf6rningar har rapporterats hos patienter som f\xe5r h\xf6gdos kemoterapi f\xf6ljd av autolog benm\xe4rgstransplantation. Orsakssambandet med filgrastim har inte fastst\xe4llts. Pulmonella biverkningar har i n\xe5gra fall rapporterats resultera i andningssvikt eller andn\xf6dssyndrom (ARDS) som kan vara fatalt. Hos friska donatorer har pulmonella biverkningar (hemoptys, lungbl\xf6dning, pulmonella infiltrat, dyspn\xe9 och hypoxi) rapporterats i mycket s\xe4llsynta fall efter marknadsf\xf6ring (se avsnitt 4.4).']]],
           ['Common',
            [['Musculoskeletal', u'Muskuloskeletal sm\xe4rta (sv\xe5r)'],
             ['Blood', u'Splenomegali (generellt asymtomatisk, \xe4ven hos patienter)'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er i blodet av alkaliskt fosfatas och LDH (\xf6verg\xe5ende, mindre)'],
             ['Blood', u'Trombocytopeni'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['GI', u'Diarr\xe9'],
             ['Hepato', u'Hepatomegali'],
             ['Skin', u'Kutan vaskulit (vid l\xe5ngtidsanv\xe4ndning), alopeci, utslag'],
             ['Musculoskeletal', u'Osteoporos, artralgi'],
             ['General', u'Sm\xe4rta p\xe5 injektionsst\xe4llet'],
             ['Blood', u'Mj\xe4ltrubbningar, splenomegali*']]],
           ['Uncommon',
            [['Vascular', u'Hypotoni (\xf6verg\xe5ende)'],
             ['Immune system',
              u'Sv\xe5r allergisk reaktion anafylaxi, angio\xf6dem, urtikaria, utslag'],
             ['Blood', u'Mj\xe4ltrubbningar'],
             ['Musculoskeletal', u'Reumatoid artrit och f\xf6rv\xe4rrade artritsymtom'],
             ['Investigations',
              u'F\xf6rh\xf6jda niv\xe5er av aspartataminotransferas (ASAT) och urinsyra (\xf6verg\xe5ende, mindre) i blodet * se nedan'],
             ['Blood', u'Mj\xe4ltrubbningar'],
             ['Renal', u'Hematuri, proteinuri']]],
           ['Rare',
            [['Vascular',
              u'Vaskul\xe4ra rubbningar* inklusive venocklusiv sjukdom och rubbningar i v\xe4tskevolym']]],
           ['Very rare',
            [['Immune system',
              u'Reaktioner av allergisk typ*, inklusive anafylaxi, hudutslag, urtikaria, angio\xf6dem, dyspn\xe9 och hypotoni'],
             ['Respiratory', u'Lung\xf6dem*, interstitiell pneumoni*, pulmonella infiltrat*'],
             ['Skin', u'Sweets syndrom*, kutan vaskulit'],
             ['Musculoskeletal', u'F\xf6rv\xe4rrad reumatoid artrit'],
             ['Renal', u'Miktionsst\xf6rningar (fr\xe4mst dysuri)'],
             ['Blood', u'Mj\xe4ltruptur (\xe4ven hos patienter)'],
             ['Respiratory',
              u'Hemoptys*, lungbl\xf6dning*, pulmonella infiltrat*, dyspn\xe9*, hypoxi*']]]],
 '_pages': [10, 13],
 u'_rank': 36,
 u'_type': u'LSFU'}