{'_data': [['Very common',
            [['Metabolism', u'Viktminskning, minskad aptit'],
             ['Nervous system', u'Tremor'],
             ['GI', u'Diarr\xe9, gaser, magsm\xe4rtor,']]],
           ['Common',
            [['Blood', u'Trombocytopeni'],
             ['Psychiatric', u'Depression, insomnia, minskad libido'],
             ['Nervous system',
              u'Perifer neuropati, ataxi, amnesi, parestesi, hypoestesi, huvudv\xe4rk, yrsel'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kning, mag-distension/obehag, f\xf6rstoppning, dyspepsi'],
             ['Musculoskeletal', u'Muskelspasm, muskelsvaghet'],
             ['General', u'Tr\xf6tthet, asteni, frossa och allm\xe4n sjukdomsk\xe4nsla'],
             ['Investigations', u'Abnormal nervledningshastighet']]]],
 '_pages': [6, 7],
 u'_rank': 10,
 u'_type': u'LSFU'}