{'_data': [['Common',
            [['Nervous system',
              u'Akatisi, yrsel, dystoni, huvudv\xe4rk, sedation, somnolens, extrapyramidala st\xf6rningar*'],
             ['Vascular', u'Hypertension, hypotension'],
             ['GI', u'Illam\xe5ende, kr\xe4kningar'],
             ['Musculoskeletal', u'Muskelstelhet'],
             ['General',
              u'Asteni, tr\xf6tthet, br\xe4nnande k\xe4nsla vid injektionsst\xe4llet, sm\xe4rta vid injektionsst\xe4llet'],
             ['Psychiatric', u'Rastl\xf6shet'],
             ['Nervous system',
              u'Dystoni, akatisi, extrapyramidal st\xf6rning, parkinsonism (inklusive kugghjulsstelhet, bradykinesi, hypokinesi), tremor, yrsel, sedation, somnolens, huvudv\xe4rk'],
             ['Eye', u'Dimsyn'],
             ['GI',
              u'Illam\xe5ende, kr\xe4kningar, f\xf6rstoppning, dyspepsi, muntorrhet, hypersalivering'],
             ['Musculoskeletal', u'Muskuloskeletal stelhet'],
             ['General', u'Asteni, tr\xf6tthet']]],
           ['Uncommon',
            [['Metabolism', u'Anorexi'],
             ['Psychiatric',
              u'Agitation, asocialt beteende, psykotiska st\xf6rningar, s\xf6mnsv\xe5righeter, tick'],
             ['Nervous system',
              u'Kugghjulsstelhet, postural yrsel, dysartri, dyskinesi, dyspraxi, parkinsonism, tremor'],
             ['Nervous system', u'Bradykardi, takykardi'],
             ['Ear', u'Vertigo'],
             ['Vascular', u'Flush, ortostatisk hypotension'],
             ['Respiratory', u'Laryngospasm'],
             ['GI', u'F\xf6rstoppning, diarr\xe9, l\xf6s avf\xf6ring, muntorrhet'],
             ['Skin', u'Hyperhidros'],
             ['General',
              u'Uts\xe4ttningssymtom, influensaliknande sjukdom, obehagsk\xe4nsla vid injektionsst\xe4llet, irritation vid injektionsst\xe4llet'],
             ['Investigations', u'S\xe4nkt blodtryck'],
             ['Metabolism', u'\xd6kad aptit'],
             ['Psychiatric', u'Agitation, oro, tr\xe5nghetsk\xe4nsla i halsen, mardr\xf6mmar'],
             ['Nervous system',
              u'Generaliserad tonisk-klonisk kramp, tardiv dyskinesi, dyskinesi, \xf6kat salivfl\xf6de, ataxi, dysartri, okulogyr kris, koncentrationsst\xf6rning, hypersomni, hypoestesi, parestesi, letargi'],
             ['Cardiac', u'Palpitationer, takykardi'],
             ['Eye', u'Fotofobi Organsystem Biverkningar Frekvens'],
             ['Ear', u'Vertigo, tinnitus'],
             ['Vascular',
              u'Hypertensiv kris, hypertension, ortostatisk hypotension, hypotension'],
             ['Respiratory', u'Dyspne, halsont'],
             ['GI',
              u'Diarre, dysfagi, gastrit, gastrointestinal obehagsk\xe4nsla, svullen tunga, f\xf6rtjockad tunga, flatulens'],
             ['Skin', u'Urtikaria, makulopapul\xe4ra utslag, andra utslag, akne'],
             ['Musculoskeletal',
              u'Muskuloskeletalt obehag, muskelkramp, sm\xe4rta i extremiteter, ledstelhet'],
             ['General',
              u'Obehagsk\xe4nsla i br\xf6stkorgen, onormal g\xe5ng, sm\xe4rta, t\xf6rst']]],
           ['Rare',
            [['Renal', u'Urininkontinens, dysuri'],
             ['Infections', u'Rinit'],
             ['Metabolism', u'Hypokalcemi'],
             ['Psychiatric',
              u'Panik\xe5ngest, depressiva symtom, bradyfreni, emotionell avtrubbning, anorgasmi'],
             ['Nervous system',
              u'Tortikollis, pares, akinesi, hypertonus, restless legs syndrom'],
             ['Blood', u'Lymfopeni'],
             ['Cardiac', u'S\xe4llsynt F\xf6rl\xe4ngt QT -intervall'],
             ['Eye', u'Amblyopi, synrubbning, \xf6gonprurit, torra \xf6gon'],
             ['Ear', u'\xd6ronv\xe4rk'],
             ['Vascular',
              u'Systolisk hypertension, diastolisk hypertension, instabilt blodtryck'],
             ['Respiratory', u'Hicka'],
             ['GI', u'Gastroesofagal reflux, l\xf6s avf\xf6ring'],
             ['Skin',
              u'Psoriasis, allergisk dermatit, alopeci, ansiktssvullnad, erytem, papul\xe4ra utslag, hudirritation'],
             ['Musculoskeletal', u'Trismus'],
             ['Renal', u'Urininkontinens, dysuri'],
             ['Reproductive system',
              u'Erektil dysfunktion, \xf6kad erektion, galaktorre\xb4, gynekomasti'],
             ['General', u'Pyrexi, v\xe4rmek\xe4nsla'],
             ['Investigations', u'\xd6kning av laktatdehydrogenas']]],
           ['Unknown',
            [['Psychiatric', u'Mani/hypomani'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom, serotoninsyndrom (se avsnitt 4.5), ansiktsf\xf6rlamning Hj\xe4rta'],
             ['Vascular', u'Synkope, ven\xf6s tromboembolism'],
             ['Skin', u'Hypersensitivitet, angio\xf6dem'],
             ['Musculoskeletal', u'Biverkningar Frekvens'],
             ['Renal', u'Enures Rubbningar i immunsystemet'],
             ['Pregnancy', u'Abstinensbesv\xe4r hos nyf\xf6dda (se avsnitt 4.6)'],
             ['Psychiatric', u'Insomnia, mani/hypomani'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom, serotoninsyndrom (se avsnitt 4.5), ansiktsf\xf6rlamning'],
             ['Cardiac', u'Torsade de pointes (se avsnitt 4.4)'],
             ['Vascular', u'Synkope, ven\xf6s tromboembolism'],
             ['Skin', u'Hypersensitivitet, angio\xf6dem'],
             ['Renal', u'Enures'],
             ['Reproductive system', u'Priapism Rubbningar i immunsystemet']]]],
 '_pages': [5, 10],
 u'_rank': 66,
 u'_type': u'LSFU'}