{'_data': [['Common',
            [['Metabolism', u' lipoatrofi**, lipodystrofi**, asymptomatisk hyperlaktatemi'],
             ['Psychiatric', u' depression'],
             ['Nervous system',
              u' perifera neurologiska symtom inklusive perifer neuropati, parestesi och perifer neurit; yrsel; onormala dr\xf6mmar; huvudv\xe4rk, insomnia; onormala tankar, d\xe5sighet'],
             ['Skin', u' hudutslag; pruritus'],
             ['General', u' tr\xf6tthet']]],
           ['Uncommon',
            [['Endocrine', u' gynekomasti'],
             ['Metabolism',
              u' laktacidos (i vissa fall innefattande motorisk svaghet), anorexi'],
             ['Psychiatric', u' oro; emotionell labilitet'],
             ['Hepato', u' pankreatit, kr\xe4kningar'],
             ['Hepato', u' hepatit eller gulsot'],
             ['Skin', u' urtikaria'],
             ['Musculoskeletal', u' artalgi, myalgi '],
             ['General', u' asteni ']]],
           ['Rare',
            [['Blood', u' anemi*'],
             ['Metabolism', u'hyperglykemi*'],
             ['Hepato', u'leversteatos*']]],
           ['Very rare',
            [['Blood', u'neutropeni*, trombocytopeni'],
             ['Metabolism', u'diabetes mellitus*'],
             ['Nervous system', u'motorisk svaghet* (oftast rapporterat i samband'],
             ['Hepato', u'leversvikt*']]]],
 '_pages': [6, 9],
 u'_rank': 20,
 u'_type': u'LSFU2'}