{'_data': [['Common',
            [['Metabolism', u'anorexia'],
             ['Nervous system', u'huvudv\xe4rk'],
             ['GI', u'illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Skin', u'utslag (utan systemiska symtom)'],
             ['General',
              u'feber, letargi, tr\xf6tthet Fall av laktacidos, ibland med d\xf6dlig utg\xe5ng, vanligtvis i samband med uttalad hepatomegali och leversteatos, har rapporterats vid anv\xe4ndning av nukleosidanaloger (se avsnitt 4.4). Antiretroviral kombinationsbehandling har associerats med omf\xf6rdelning av kroppsfett (lipodystrofi) hos hivpatienter, inkluderande minskning av perifert och facialt subkutant fett, \xf6kning av intraabdominellt och visceralt fett, br\xf6sthypertrofi och dorsocervikal fettackumulering (\u201cbuffalo hump\u201d). Antiretroviral kombinationsbehandling har associerats med metaboliska st\xf6rningar s\xe5som hypertriglyceridemi, hyperkolesterolemi, insulinresistens, hyperglykemi och hyperlaktatemi (se avsnitt 4.4). Hos hivinfekterade patienter med sv\xe5r immunbrist vid tidpunkten f\xf6r ins\xe4ttande av antiretroviral kombinationsterapi, kan en inflammatorisk reaktion mot asymtomatiska eller kvarvarande opportunistiska infektioner uppst\xe5. Autoimmuna sjukdomar (s\xe5som Graves sjukdom) har ocks\xe5 rapporterats i samband med immunreaktivering; emellertid \xe4r den rapporterade tidpunkten f\xf6r debut mer varierad och dessa h\xe4ndelser kan intr\xe4ffa flera m\xe5nader efter att behandlingen p\xe5b\xf6rjats.(se avsnitt 4.4). Fall av osteonekros har rapporterats, speciellt hos patienter med k\xe4nda riskfaktorer, framskriden hivsjukdom eller l\xe5ngvarig exponering f\xf6r antiretroviral kombinationsbehandling (CART). Frekvensen av detta \xe4r ok\xe4nd (se avsnitt 4.4). Avvikelser i laboratoriev\xe4rden I kontrollerade kliniska studier var laboratorieavvikelser relaterade till Ziagen-behandling ovanliga och inga skillnader i incidens noterades mellan patienterna i Ziagen- och kontrollgrupperna.']]],
           ['Rare', [['GI', u'pankreatit']]],
           ['Very rare',
            [['Skin',
              u'erythema multiforme, Steven-Johnsons syndrom och toxisk epidermal nekrolys']]]],
 '_pages': [8, 10],
 u'_rank': 7,
 u'_type': u'LSFU'}