{'_data': [['Common',
            [['Metabolism', u'anorexia'],
             ['Nervous system',
              u'huvudv\xe4rk Magtarmkanalen Vanlig: illam\xe5ende, kr\xe4kningar, diarr\xe9'],
             ['Skin', u'utslag (utan systemiska symtom)'],
             ['General',
              u'feber, letargi, tr\xf6tthet Fall av laktacidos, ibland med d\xf6dlig utg\xe5ng, vanligtvis i samband med uttalad hepatomegali och leversteatos, har rapporterats vid anv\xe4ndning av nukleosidanaloger (se avsnitt 4.4). Antiretroviral kombinationsbehandling har associerats med omf\xf6rdelning av kroppsfett (lipodystrofi) hos hivpatienter, inkluderande minskning av perifert och facialt subkutant fett, \xf6kning av intraabdominellt och visceralt fett, br\xf6sthypertrofi och dorsocervikal fettackumulering (\u201cbuffalo hump\u201d). Antiretroviral kombinationsbehandling har associerats med metaboliska st\xf6rningar s\xe5som hypertriglyceridemi, hyperkolesterolemi, insulinresistens, hyperglykemi och hyperlaktatemi (se avsnitt 4.4). Hos hivinfekterade patienter med sv\xe5r immunbrist vid tidpunkten f\xf6r ins\xe4ttande av antiretroviral kombinationsterapi, kan en inflammatorisk reaktion mot asymtomatiska eller kvarvarande opportunistiska infektioner uppst\xe5 (se avsnitt 4.4). Fall av osteonekros har rapporterats, speciellt hos patienter med k\xe4nda riskfaktorer, framskriden hivsjukdom eller l\xe5ngvarig exponering f\xf6r antiretroviral kombinationsbehandling (CART). Frekvensen av detta \xe4r ok\xe4nd (se avsnitt 4.4). Avvikelser i laboratoriev\xe4rden I kontrollerade kliniska studier var laboratorieavvikelser relaterade till Ziagen-behandling ovanliga och inga skillnader i incidens noterades mellan patienterna i Ziagen- och kontrollgrupperna.']]],
           ['Rare', [['Nervous system', u'pankreatit']]],
           ['Very rare',
            [['Skin',
              u'erythema muliforme, Steven-Johnsons syndrom och toxisk epidermal nekrolys']]]],
 '_pages': [9, 11],
 u'_rank': 6,
 u'_type': u'LSFU'}