{'_data': [['Common',
            [['Infections', u'Vaginal candidainfektion.'],
             ['Metabolism', u'Minskad aptit.'],
             ['Psychiatric', u'Huvudv\xe4rk, yrsel'],
             ['GI',
              u'Magbesv\xe4r/magsm\xe4rtor, illam\xe5ende och/eller kr\xe4kningar, obehaglig smak/ovanlig k\xe4nsla p\xe5 tungan.'],
             ['Renal',
              u'Vaginal kl\xe5da/irritation/sveda/k\xe4nsell\xf6shet, b\xe4ckenbesv\xe4r, flytningar.']]],
           ['Uncommon',
            [['Psychiatric', u'Depression, s\xf6mnsv\xe5righeter. Centrala och perifera'],
             ['Psychiatric', u'Ovanlig k\xe4nsla i extremiteterna, metallsmak.'],
             ['GI',
              u'Diarr\xe9, f\xf6rstoppning, v\xe4dersp\xe4nningar/bullrig mage, torr i munnen.'],
             ['Skin', u'Kl\xe5da. Muskuloskeletala systemet och bindv\xe4v'],
             ['Skin', u'Kramp.'],
             ['Renal',
              u'Missf\xe4rgning av urin, symtom p\xe5 urinv\xe4gsinfektion. Reproduktionsorgan och br\xf6stk\xf6rtel'],
             ['Renal',
              u'Svullnad i vulva, besv\xe4rlig/oregelbunden menstruation, vaginal st\xe4nkbl\xf6dning/bl\xf6dning. Allm\xe4nna symtom och/eller symtom vid administeringsst\xe4llet'],
             ['Renal', u'Utmattning, irritation.']]]],
 '_pages': [2, 3],
 u'_rank': 13,
 u'_type': u'LSFU'}