{'_data': [['Common',
            [['Blood', u'Neutropeni, eosinofili.'],
             ['Hepato', u'\xd6verg\xe5ende f\xf6rh\xf6jda leverenzymv\xe4rden.'],
             ['General', u'Tromboflebit.']]],
           ['Uncommon',
            [['Blood', u'Leukopeni, s\xe4nkt hemoglobin, positiv Coombs test.'],
             ['GI', u'Mag-tarmbesv\xe4r s\xe5som diarr\xe9, illam\xe5ende, kr\xe4kningar'],
             ['Hepato', u'\xd6verg\xe5ende f\xf6rh\xf6jda bilirubinv\xe4rden.'],
             ['Skin', u'Hudutslag, urticaria och kl\xe5da.']]],
           ['Rare', [['Infections', u'Candida\xf6verv\xe4xt.']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni, hemolytisk anemi'],
             ['Immune system', u'L\xe4kemedelsutl\xf6st feber (drug fever), anafylaxi.'],
             ['GI', u'Pseudomembran\xf6s kolit.'],
             ['Skin',
              u'Erythema multiforme, toxisk epidermal nekrolys och Stevens-Johnsons syndrom, kutan vaskulit.'],
             ['Renal',
              u'F\xf6rh\xf6jda serumkreatininv\xe4rden, stegring av urea/kv\xe4ve i blodet och minskat kreatininclearance (se 4.4 Varningar och f\xf6rsiktighet), interstitiell nefrit.'],
             ['General', u'\xd6verg\xe5ende sm\xe4rta p\xe5 injektionsst\xe4llet.']]]],
 '_pages': [3, 4],
 u'_rank': 14,
 u'_type': u'LSFU'}