{'_data': [['Common',
            [['Psychiatric', u'rastl\xf6shet'],
             ['Nervous system',
              u'dystoni, akatisi, extrapyramidal st\xf6rning, parkinsonism (inklusive kugghjulsstelhet, bradykinesi, hypokinesi), tremor, yrsel, sedation, somnolens, huvudv\xe4rk'],
             ['Eye', u'dimsyn'],
             ['GI',
              u'illam\xe5ende, kr\xe4kningar, f\xf6rstoppning, dyspepsi, muntorrhet, hypersalivering'],
             ['Musculoskeletal', u'muskuloskeletal stelhet'],
             ['General', u'asteni, tr\xf6tthet']]],
           ['Uncommon',
            [['Metabolism', u'\xf6kad aptit'],
             ['Psychiatric', u'agitation, oro, tr\xe5nghetsk\xe4nsla i halsen, mardr\xf6mmar'],
             ['Nervous system',
              u'generaliserad tonisk-klonisk kramp, tardiv dyskinesi, dyskinesi, \xf6kat salivfl\xf6de, ataxi, dysartri, okulogyr kris, koncentrationsst\xf6rning, hypersomni, hypoestesi, parestesi, letargi'],
             ['Cardiac', u'palpitationer, takykardi'],
             ['Eye', u'fotofobi'],
             ['Ear', u'vertigo, tinnitus'],
             ['Vascular',
              u'hypertensiv kris, hypertension, ortostatisk hypotension, hypotension'],
             ['Respiratory', u'dyspn\xe9, halsont'],
             ['GI',
              u'diarr\xe9, dysfagi, gastrit, gastrointestinal obehagsk\xe4nsla, svullen tunga, f\xf6rtjockad tunga, flatulens'],
             ['Skin', u'urtikaria, utslag, makulopapul\xe4ra utslag, akne'],
             ['Musculoskeletal',
              u'muskuloskeletalt obehag, muskelkramp, sm\xe4rta i extremiteter, ledstelhet'],
             ['General',
              u'obehagsk\xe4nsla i br\xf6stkorgen, onormal g\xe5ng, sm\xe4rta, t\xf6rst']]],
           ['Rare',
            [['Infections', u'rinit'],
             ['Metabolism', u'hypokalcemi'],
             ['Psychiatric',
              u'panik\xe5ngest, depressiva symtom, bradyfreni, emotionell avtrubbning, anorgasmi'],
             ['Nervous system',
              u'tortikollis, pares, akinesi, hypertonus, restless legs syndrom'],
             ['Blood', u'lymfopeni, eosinofili'],
             ['Cardiac', u'f\xf6rl\xe4ngt QT -intervall'],
             ['Eye', u'amblyopi, synrubbning, \xf6gonprurit, torra \xf6gon'],
             ['Ear', u'\xf6ronv\xe4rk'],
             ['Vascular',
              u'systolisk hypertension, diastolisk hypertension, instabilt blodtryck'],
             ['Respiratory', u'hicka'],
             ['GI', u'gastroesofagal reflux, l\xf6s avf\xf6ring'],
             ['Skin',
              u'psoriasis, allergisk dermatit, alopeci, ansiktssvullnad, erytem, papul\xe4ra utslag, hudirritation'],
             ['Musculoskeletal', u'trismus'],
             ['Renal', u'urininkontinens, dysuri'],
             ['Reproductive system',
              u'erektil dysfunktion, \xf6kad erektion, galaktorr\xe9, gynekomasti'],
             ['General', u'pyrexi, v\xe4rmek\xe4nsla'],
             ['Investigations',
              u'\xf6kning av laktatdehydrogenas I kliniska korttids- och l\xe5ngtidsstudier av schizofreni och bipol\xe4r mani med ziprasidon var tonisk kloniska kramper och hypotension mindre vanligt f\xf6rekommande, f\xe4rre \xe4n 1% av ziprasidonbehandlade patienter drabbades. Ziprasidon orsakar en mild till m\xe5ttlig dosrelaterad f\xf6rl\xe4ngning av QT-intervallet (se avsnitt 5.1). I kliniska schizofrenistudier s\xe5gs en \xf6kning p\xe5 30-60 millisekunder p\xe5 12,3 % (976/7941) av de EKG m\xe4tningar som gjordes p\xe5 patienter behandlade med ziprasidon och 7,5 % (73/975) av de EKG m\xe4tningar som gjordes p\xe5 patienter behandlade med placebo. En f\xf6rl\xe4ngning p\xe5 >60 millisekunder s\xe5gs p\xe5 1,6 % (128/7941) respektive 1,2 % (12/975) av de EKG-m\xe4tningar som gjordes p\xe5 ziprasidon respektive placebobehandlade patienter. En f\xf6rl\xe4ngning av QTc-intervallet \xf6ver 500 millisekunder f\xf6rekom hos 3 av totalt 3266 (0,1 %) ziprasidonbehandlade patienter och hos 1 av totalt 538 (0,2 %) placebobehandlade patienter. Liknande resultat s\xe5gs i kliniska studier av bipol\xe4r mani. I kliniska l\xe5ngtidsstudier av underh\xe5llsbehandling vid schizofreni var prolaktinniv\xe5erna hos patienter som behandlades med ziprasidon ibland f\xf6rh\xf6jda. Hos de flesta patienter \xe5tergick niv\xe5erna till normala v\xe4rden utan att behandlingen avbr\xf6ts. Kliniska manifestationer (exempelvis gynekomasti och br\xf6stf\xf6rstoring) var s\xe4llsynta.']]],
           ['Unknown',
            [['Psychiatric', u'insomnia, mani/hypomani'],
             ['Nervous system',
              u'malignt neuroleptikasyndrom, serotoninsyndrom (se avsnitt 4.5), ansiktsf\xf6rlamning'],
             ['Cardiac', u'torsade de pointes (se avsnitt 4.4)'],
             ['Vascular', u'synkope, ven\xf6s tromboembolism'],
             ['Skin', u'hypersensitivitet, angio\xf6dem'],
             ['Renal', u'enures'],
             ['Reproductive system', u'priapism Rubbningar i immunsystemet']]]],
 '_pages': [5, 7],
 u'_rank': 42,
 u'_type': u'LSFU'}