{'_data': [['Rare',
            [['Blood', u'anemi'],
             ['Nervous system', u'huvudv\xe4rk, parestesier, yrsel, perifer neuropati'],
             ['GI',
              u'f\xf6rstoppning, buksm\xe4rtor, flatulens, dyspepsi, diarr\xe9, illam\xe5ende, kr\xe4kningar, pankreatit'],
             ['Hepato', u'hepatit/gulsot'],
             ['Skin', u'kl\xe5da, hudutslag, h\xe5ravfall'],
             ['Musculoskeletal',
              u'myopati*(inkluderande myosit), rabdomyolys med eller utan akut njursvikt (se avsnitt 4.4), myalgi, muskelkramper'],
             ['General',
              u'asteni Ett \xf6verk\xe4nslighetssyndrom best\xe5ende av n\xe5gra av f\xf6ljande symtom har rapporterats i s\xe4llsynta fall: angio\xf6dem, lupusliknande sjukdomsbild, reumatisk polymyalgi, dermatomyosit, vaskulit, trombocytopeni, eosinofili, SR-stegring, artrit och artralgi, urtikaria, fotosensibilisering, feber, rodnad, dyspn\xe9 och allm\xe4n sjukdomsk\xe4nsla.'],
             ['Investigations',
              u'f\xf6rh\xf6jda serumtransaminaser (alaninaminotransferas, aspartataminotranseras, \u03b3glutamyltranspeptidas (se avsnitt 4.4 Leverp\xe5verkan), f\xf6rh\xf6jda alkaliska fosfataser, f\xf6rh\xf6jda serum CKv\xe4rden (se avsnitt 4.4). F\xf6rh\xf6jda v\xe4rden av HbA1c och fasteserumglukos har rapporterats med statiner, inklusive Zocord. Efter godk\xe4nnandet av l\xe4kemedlet har ett f\xe5tal rapporter om kognitiv f\xf6rs\xe4mring (t ex minnesf\xf6rlust, gl\xf6mska, amnesi, f\xf6rs\xe4mrat minne, f\xf6rvirring) i samband med statinanv\xe4ndning, inklusive simvastatin, rapporterats. Dessa fall \xe4r vanligtvis icke allvarliga och reversibla vid avbrytande av statinbehandling, med olika tid f\xf6r symtomdebut (1 dag till \xe5r) och f\xf6rsvinnande av symtom (3 veckor i median). F\xf6ljande biverkningar har dessutom rapporterats med vissa statiner: \u2022S\xf6mnst\xf6rningar inkluderande mardr\xf6mmar \u2022Sexuell dysfunktion \u2022Diabetes mellitus: Frekvensen \xe4r beroende av f\xf6rekomst eller avsaknad av riskfaktorer (fasteglukos > 5,6 mmol/l; BMI >30 kg/m ; f\xf6rh\xf6jda triglycerider; hypertension i anamnesen).']]],
           ['Very rare',
            [['Psychiatric', u'insomnia'],
             ['Nervous system', u'nedsatt minnesf\xf6rm\xe5ga'],
             ['Hepato', u'fatal och icke-fatal leversvikt']]],
           ['Unknown',
            [['Psychiatric', u'depression'],
             ['Respiratory', u'interstitiell lungsjukdom (se avsnitt 4.4)'],
             ['Reproductive system', u'erektil dysfunktion']]]],
 '_pages': [9, 10],
 u'_rank': 14,
 u'_type': u'LSFU'}