{'_data': [['Very common', [['Investigations', u'Hypofosfatemi']]],
           ['Common',
            [['Blood', u'Anemi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Eye', u'Konjunktivit'],
             ['GI', u'Illam\xe5ende, kr\xe4kning, anorexi'],
             ['Musculoskeletal', u'Bensm\xe4rtor, myalgi, artralgi, allm\xe4nna'],
             ['Renal', u'Njurf\xf6rs\xe4mring'],
             ['General',
              u'Feber, influensaliknande syndrom (inklusive tr\xf6tthet, rigor, olustk\xe4nslor och vallning)'],
             ['Investigations', u'\xd6kning i blodkreatinin och blodurea, hypokalcemi']]],
           ['Uncommon',
            [['Blood', u'Trombocytopeni, leukopeni'],
             ['Immune system', u'\xd6verk\xe4nslighet'],
             ['Psychiatric', u'\xc5ngest, s\xf6mnrubbningar'],
             ['Nervous system',
              u'Yrsel, parestesi, smakrubbningar, hypoestesi, hyperestesi, darrningar, s\xf6mnighet'],
             ['Eye', u'Dimsyn, sklerit och orbital inflammation'],
             ['Cardiac',
              u'Hypertension, hypotension, f\xf6rmaksflimmer, hypotension som leder till synkope eller kollaps i blodomloppet'],
             ['GI',
              u'Diarr\xe9, f\xf6rstoppning, buksm\xe4rtor, dyspepsi, stomatit, muntorrhet'],
             ['Skin',
              u'Pruritus, utslag (inklusive erytemat\xf6sa och makul\xe4ra utslag), \xf6kad svettning'],
             ['Musculoskeletal', u'sm\xe4rtor Muskelkramper, osteonekros i k\xe4kbenet'],
             ['Renal', u'Akut njursvikt, hematuri, proteinuri'],
             ['General',
              u'Asteni, periferalt \xf6dem, reaktioner vid injiceringsst\xe4llet (inklusive sm\xe4rtor, irritation, svullnad, induration), br\xf6stsm\xe4rtor, vikt\xf6kning, anafylaktisk reaktion/chock, urtikaria'],
             ['Investigations', u'Hypomagnesemi, hypokalemi']]],
           ['Rare',
            [['Blood', u'Pancytopeni'],
             ['Immune system', u'Angioneurotiskt \xf6dem'],
             ['Psychiatric', u'F\xf6rvirring'],
             ['Cardiac', u'Bradykardi'],
             ['Investigations',
              u'Hyperkalemi, hypernatremi Beskrivning av valda biverkningar Nedsatt njurfunktion Zoledronsyra har f\xf6rknippats med rapporter om renal dysfunktion. I en poolad analys av s\xe4kerhetsdata fr\xe5n registreringsstudierna p\xe5 f\xf6rebyggande av skelettrelaterade h\xe4ndelser hos patienter med avancerade benv\xe4vnadsmetastaser, var frekvensen av njurrelaterade o\xf6nskade h\xe4ndelser med misst\xe4nkt orsakssamband (biverkningar) f\xf6r zoledronsyra enligt f\xf6ljande: multipelt myelom (3,2 %), prostatacancer (3,1 %), br\xf6stcancer (4,3 %), lung- och andra solida tum\xf6rer (3,2 %). Till faktorerna som kan \xf6ka potentialen f\xf6r f\xf6rs\xe4mring i njurfunktionen h\xf6r uttorkning, redan existerande f\xf6rs\xe4mring i njurarna, flera cykler med zoledronsyra och andra bisfosfonater liksom den samtidiga anv\xe4ndningen av nefrotoxiska l\xe4kemedel och anv\xe4ndningen av en kortare infusionstid \xe4n den som f\xf6r n\xe4rvarande rekommenderas. F\xf6rs\xe4mring av njurarna, vidareutveckling till njursvikt och dialys har rapporterats hos patienter efter den f\xf6rsta dosen eller en enkel dos 4 mg zoledronsyra (se avsnitt 4.4). Osteonekros i k\xe4kbenet Fall av osteonekros (huvudsakligen i k\xe4kbenet) har rapporterats, huvudsakligen hos cancerpatienter som behandlas med l\xe4kemedel som h\xe4mmar benresorption, som t.ex. zoledronsyra. M\xe5nga s\xe5dana patienter uppvisade tecken p\xe5 lokal infektion inklusive osteomyelit och st\xf6rre delen av rapporterna ber\xf6r cancerpatienter efter tandutdragningar eller annan tandkirurgi. Osteonekros i k\xe4kbenet har flera dokumenterade riskfaktorer inklusive en cancerdiagnos, samtidiga behandlingar (t.ex. cytostatikabehandling, str\xe5lbehandling, kortikosteroider) och komorbida tillst\xe5nd (t.ex. anemi, koagulopatier, infektion, tidigare existerande munsjukdom). \xc4ven om kausalitet inte har fastst\xe4llts F\xf6rmaksflimmerrekommenderas att undvika tandkirurgi d\xe5 \xe5terh\xe4mtning kan f\xf6rdr\xf6jas (se avsnitt 4.4). F\xf6rmaksflimmer I ett tre\xe5rigt, randomiserat, dubbelblint kontrollerat f\xf6rs\xf6k som utv\xe4rderade verkningsfullhet och s\xe4kerhet hos zoledronsyra 5 mg en g\xe5ng per \xe5r kontra placebo i behandlingen av postmenstruell osteoporos (PMO) var den totala f\xf6rekomsten av f\xf6rmaksflimmer 2,5 % (96 av 3 862) respektive 1,9 % (75 av 3 852) hos patienter som fick zoledronsyra 5 mg respektive placebo. Frekvensen f\xf6r biverkningen f\xf6rmaksflimmer var 1,3 % (51 av 3 862) respektive 0,6 % (22 av 3 852) hos patienter som fick zoledronsyra 5 mg respektive placebo. Obalansen som observerades i detta f\xf6rs\xf6k har inte observerats i andra f\xf6rs\xf6k med zoledronsyra, inklusive s\xe5dana d\xe4r zoledronsyra 4 mg var 3:e-4:e vecka anv\xe4ndes med onkologipatienter. Mekanismen bakom den \xf6kade f\xf6rekomsten av f\xf6rmaksflimmer i detta enda kliniska f\xf6rs\xf6k \xe4r ok\xe4nd. Reaktion med akut fas Denna l\xe4kemedelsbiverkning best\xe5r av en konstellation med symtom som inkluderar feber, myalgi, huvudv\xe4rk, extrem sm\xe4rta, illam\xe5ende, kr\xe4kning, diarr\xe9 och artralgi. Starttiden \xe4r \u2264 3 dagar efter infusion med zoledronsyra och reaktionen kallas \xe4ven \u201cinfluensaliknande symptom\u201d eller \u201cefterdossymtom\u201d. Atypiska femurfrakturer Vid erfarenheter i eftermarknaden har f\xf6ljande reaktioner rapporterats (frekvens s\xe4llsynt): Atypisk subtrokanteriska och diafysala femurfrakturer (klassbiverkning f\xf6r bisfosfonater) Hypokalcemi - relaterade biverkningar Hypokalcemi \xe4r en viktig, identifierad risk med zoledronsyra under godk\xe4nda indikationer. Baserat p\xe5 granskningen av b\xe5de kliniska studier och fall efter marknadsf\xf6ring finns det tillr\xe4ckligt med bevis f\xf6r att st\xf6da en sammankoppling mellan behandling med zoledronsyra, rapporterade h\xe4ndelser av hypokalcemi och sekund\xe4r utveckling av hj\xe4rtarytmi. Dessutom finns det bevis p\xe5 en sammankoppling mellan hypokalcemi och sekund\xe4ra neurologiska biverkningar, rapporterade i dessa fall, inklusive kramper, domningar och tetani (se avsnitt 4.4).']]],
           ['Very rare',
            [['Nervous system',
              u'Kramper, domningar och tetani (sekund\xe4r till hypokalcemi)'],
             ['Eye', u'Uveit, episklerit'],
             ['Cardiac', u'Hj\xe4rtarytmi (sekund\xe4r till hypokalcemi)']]],
           ['Unknown',
            [['Respiratory',
              u'Dyspn\xe9, hosta, bronkokonstriktion mediastinum S\xe4llsynta: Interstitiell lungsjukdom']]]],
 '_pages': [6, 10],
 u'_rank': 30,
 u'_type': u'LSFU'}