{'_data': [['Very common',
            [['Cardiac', u'Hj\xe4rtinfarkt;'],
             ['GI', u'Ischemi eller infarkt (t ex intestinal'],
             ['Renal', u'Urintr\xe4ngningar']]],
           ['Common',
            [['Nervous system',
              u'Avvikelser eller st\xf6rningar i k\xe4nsel;  Yrsel;  Huvudv\xe4rk; Hyperestesi; Parestesi; Somnolens; Varm k\xe4nsla'],
             ['Cardiac', u'Hj\xe4rtklappningar'],
             ['GI', u'Buksm\xe4rtor;  Illam\xe5ende; Kr\xe4kningar; Torr mun'],
             ['Musculoskeletal', u'Muskelsvaghet;  Myalgi'],
             ['General',
              u'Asteni;  Tyngdk\xe4nsla, \xe5tstramningsk\xe4nsla, sm\xe4rta  eller tryck i hals, lemmar eller br\xf6st']]],
           ['Uncommon',
            [['Cardiac', u'Takykardi'],
             ['Vascular',
              u'En liten \xf6kning av blodtryck;  \xd6verg\xe5ende \xf6kningar av det systemiska blodtrycket'],
             ['Renal', u'Polyuri;  \xd6kad urineringsfrekvens']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner inklusive  urtikaria, angio\xf6dem och anafylaktiska reaktioner'],
             ['Cardiac', u'K\xe4rlkramp;  Koronark\xe4rlsspasm'],
             ['GI',
              u'ischemi, intestinal infarkt, mj\xe4ltinfarkt)  som kan f\xf6rekomma som blodig diarr\xe9 eller buksm\xe4rtor'],
             ['Renal', u'']]]],
 '_pages': [5, 6],
 u'_rank': 14,
 u'_type': u'TSFU'}