{'_data': [['Common',
            [['Systemic',
<<<<<<< HEAD
              u'   avvikand e   eller   rubba d   sinne sf\xf6rni m m el s e ,   yrsel,   huvudv \xe4rk,   hyper e st e si,  '],
             ['Systemic',
              u'  buks m\xe4 r t a ,  illam\xe5 e n d e ,  kr\xe4kningar,  muntorrh e t.  '],
             ['Systemic', u'  muskelsva g h e t ,  myalgi.  '],
             ['Systemic',
              u'  ast e ni,  tyngdk\xe4 n sl a,  sm\xe4rt a  eller  tryck  i svalg,  hals,  ben,  armar  eller  ']]],
           ['Uncommon', [['Systemic', u'  polyuri,  frekvent a  urntr\xe4 ng ning a r.  ']]],
           ['Rare',
            [['Systemic',
              u'  \xf6verk\xe4 n sligh e t sr e a k tion e r  inklusive  urticaria,  angio\xf6d e m  och  anafylaktiska  ']]],
           ['Very rare',
            [['Systemic', u':  myokardinfarkt,  angina  pectoris , koronar  vasosp a s m.  '],
             ['Systemic',
              u':  ische mi  eller  infarkt  (t.ex.  intestinal  ische mi,  intestinal  infarkt,  '],
             ['Systemic', u':  behov  att  t\xf6mm a  bl\xe5sa n.  ']]]],
=======
              u':   avvikand e   eller   rubba d   sinne sf\xf6rni m m e l s e ,   yrsel,   huvudv \xe4rk,   hyper e s t e si,  '],
             ['Systemic',
              u':  buks m \xe4 r t a ,  illam\xe5 e n d e ,  kr\xe4kninga r,  muntorr h e t.  '],
             ['Systemic', u':  musk elsva g h e t ,  myalgi.  '],
             ['Systemic',
              u':  ast e ni,  tyngdk\xe4 n sl a,  sm\xe4r t a  eller  tryck  i svalg,  hals,  ben,  arma r  eller  ']]],
           ['Uncommon', [['Systemic', u'a:  polyuri,  frekvent a  urntr\xe4 n g ning a r.  ']]],
           ['Rare',
            [['Systemic',
              u':  \xf6verk\xe4 nslighe t sr e a k tion e r  inklusive   urticaria,  angio\xf6d e m  och  anafylaktiska  ']]],
           ['Very rare',
            [['Systemic', u'a:  myokar dinfarkt,  angina  pectoris , koronar  vasosp a s m.  '],
             ['Systemic',
              u'a:  ische mi  eller  infarkt  (t.ex.  intestinal  ische mi,  intestinal  infarkt,  '],
             ['Systemic', u'a:  behov  att  t\xf6mm a  bl\xe5sa n.  ']]]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
 '_pages': [5, 6],
 u'_rank': 9,
 u'_type': u'LSFU3'}