{'_data': [['Very common',
            [['Psychiatric', u'Insomni (19 %)'],
             ['Nervous system',
              u'Yrsel Parestesier* (11 %), Somnolens (13 %), Huvudv\xe4rk (21 %)*'],
             ['Respiratory', u'G\xe4spningar*'],
             ['GI', u'Diarr\xe9 (18 %), Illam\xe5ende (24 %), Muntorrhet (14 %)'],
             ['Musculoskeletal', u'Myalgi'],
             ['Reproductive system', u'Ejakula-tionssvikt (14 %) Tr\xf6tthet %)*'],
             ['Other',
              u'(926 m\xe4n, 1 219 Vid OCD, korttidsstudier, avslutad behandling \xc4ldre Barn mycket vanliga vanliga mindre vanliga onormal hudlukt, ingen k\xe4nd frekvens Klasseffekt']]],
           ['Common',
            [['Infections', u'Faryngit'],
             ['Metabolism', u'Anorexi \xd6kad aptit*'],
             ['Psychiatric',
              u'Depression* Depersonalisation Mardr\xf6mmar \xc5ngest* Agitation* Oro Minskad libido* Bruxism'],
             ['Nervous system', u'Tremor Hypertoni Dysgeusi Uppm\xe4rksamhets-st\xf6rning'],
             ['Eye', u'Synst\xf6rning'],
             ['Ear', u'Tinnitus*'],
             ['Cardiac', u'Palpitationer*'],
             ['Vascular', u'V\xe4rmevallningar* Hypertoni*'],
             ['GI',
              u'Buksm\xe4rta* Kr\xe4kningar* F\xf6rstoppning* Dyspepsi V\xe4dersp\xe4nning'],
             ['Skin', u'Utslag* Hyperhidros'],
             ['Reproductive system',
              u'Sexuella st\xf6rningar hos m\xe4n Erektil dysfunktion Sm\xe4rta i br\xf6stkorgen*'],
             ['Other',
              u'kvinnor) -endast 1-12 veckor. -(se avsnitt 4.4). -: huvudv\xe4rk (22 %), insomni (21 %), diarr\xe9 (11 %) och illam\xe5ende (15 %). : sm\xe4rta i br\xf6stkorgen, mani, feber, kr\xe4kningar, anorexi, labilitet, aggression, : F\xf6rl\xe4ngd EKG QT, suicidf\xf6rs\xf6k, konvulsioner, extrapyramidala urtikaria, bruxism, vallningar. -: enures']]],
           ['Uncommon',
            [['Infections', u'\xd6vre luftv\xe4gsinfektion Rinit'],
             ['Psychiatric', u'Hallucinationer* Eufori* Apati Onormala tankar'],
             ['Nervous system',
              u'Konvulsioner* Ofrivilliga muskelkontrak-tioner* Onormal koordination Hyperkinesi Amnesi Hypoestesi* Talst\xf6rning Postural yrsel Migr\xe4n*'],
             ['Ear', u'\xd6ronv\xe4rk'],
             ['Cardiac', u'Takykardi*'],
             ['Vascular', u'Vallningar'],
             ['Respiratory', u'Bronkospasm* Dyspn\xe9 N\xe4sblod'],
             ['GI',
              u'Esofagit Dysfagi Hemorrojder Onormalt h\xf6g salivavs\xf6ndring St\xf6rningar i tungan Rapningar'],
             ['Skin',
              u'Periorbitalt \xf6dem* Purpura* Alopeci* Kallsvettning Hudtorrhet Urtikaria*'],
             ['Musculoskeletal', u'Osteoartrit Muskelsvaghet Ryggsm\xe4rta Muskelryckningar'],
             ['Renal', u'Nykturi Urinretention* Polyuri Pollakisuri Miktionsst\xf6rning'],
             ['Reproductive system',
              u'Vaginal bl\xf6dning Kvinnlig sexuell dysfunktion Sjukdomsk\xe4nsla* Frossa Pyrexi* Asteni* T\xf6rst'],
             ['Investigations', u'Viktnedg\xe5ng* Viktuppg\xe5ng*']]],
           ['Rare',
            [['Infections', u'Divertikulit Gastroenterit Otitis media'],
             ['Neoplasms', u'Neoplasm\u2020'],
             ['Blood', u'Lymfadenopati'],
             ['Metabolism', u'Hyperkolesterolemi Hypoglykemi'],
             ['Psychiatric',
              u'Konversionsst\xf6rning L\xe4kemedelsberoende Psykisk st\xf6rning* Aggression* F\xf6rf\xf6ljelsemani Suicidtankar/Suicidalt beteende*** S\xf6mng\xe5ng F\xf6r tidig utl\xf6sning'],
             ['Nervous system',
              u'Koma*, Koreoatetos Dyskinesi Hyperestesi Sensoriska st\xf6rningar'],
             ['Eye',
              u'Glaukom St\xf6rning i t\xe5rfl\xf6det Skotom, Diplopi Fotofobi Hyphemi Mydriasis*'],
             ['Cardiac', u'Hj\xe4rtinfarkt Bradykardi St\xf6rningar i hj\xe4rtfunktionen'],
             ['Vascular', u'Perifer ischemi'],
             ['Respiratory',
              u'Laryngospasm Hyperventilation Hypoventilation Stridor Dysfoni Hicka'],
             ['GI', u'Melena Hematochezi Stomatit Tungs\xe5r Tandproblem Glossit Muns\xe5r'],
             ['Hepato', u'Onormal leverfunktion'],
             ['Skin',
              u'Dermatit Bull\xf6s dermatit Follikelutslag Onormal h\xe5rstruktur Onormal hudlukt'],
             ['Musculoskeletal', u'Bensjukdom'],
             ['Renal', u'Oliguri Urininkontinens* Bl\xe5st\xf6mningssv\xe5rig-heter'],
             ['Reproductive system',
              u'Menorragi Atrofisk vulvovaginit Balanopostit Genital flytning Priapism* Galaktorr\xe9* Br\xe5ck Minskad l\xe4kemedelstolerans G\xe5ngsv\xe5righeter Obest\xe4mbara symtom'],
             ['Investigations', u'\xd6kat ALAT* \xd6kat ASAT* Onormal sperma Skada'],
             ['Other', u'K\xe4rlutvidgnings-operation']]],
           ['Very rare', []],
           ['Unknown',
            [['Blood', u'Leukopeni Trombocytopeni'],
             ['Immune system', u'Anafylaktoid reaktion Allergisk reaktion Allergi'],
             ['Endocrine', u'Hyperprolaktinemi Hypotyreos Inadekvat ins\xf6ndring av ADH'],
             ['Metabolism', u'Hyponatremi Diabetes mellitus Hyperglykemi'],
             ['Psychiatric', u'Paroniri'],
             ['Nervous system',
              u'R\xf6relsest\xf6rningar (inklusive extrapyramidala symtom s\xe5som hyperkinesi, hypertoni, dystoni, tandagnisslan eller onormal g\xe5ng), Synkope. Tecken och symtom p\xe5 serotonergt syndrom eller malignt neuroleptikasyndrom har ocks\xe5 rapporterats, i vissa fall associerat med samtidig anv\xe4ndning av serotonerga l\xe4kemedel, s\xe5som agitation, f\xf6rvirring, diafores, diarr\xe9, feber, hypertoni, rigiditet och takykardi. Akatisi och psykomotorisk rastl\xf6shet (se avsnitt 4.4). Cerebrovaskul\xe4r spasm (inklusive och Call-Fleming syndrom).'],
             ['Eye', u'Onormal syn'],
             ['Vascular', u'Onormala bl\xf6dningar (s\xe5som n\xe4sblod,'],
             ['GI', u'bl\xf6dning eller hematuri)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Allvarliga leverbiverkningar (inklusive hepatit, gulsot och leversvikt)'],
             ['Skin',
              u'S\xe4llsynta rapporter om sv\xe5ra hudreaktioner (SCAR), t.ex. Stevens-Johnsons syndrom och epidermal nekrolys Angio\xf6dem Ansikts\xf6dem Fotosensitivitet Hudreaktion Pruritus'],
             ['Musculoskeletal', u'Artralgi Muskelkramper'],
             ['Reproductive system',
              u'Gynekomasti Oregelbundna menstruationer Perifert \xf6dem'],
             ['Investigations',
              u'Onormala kliniska laboratorieresultat F\xf6r\xe4ndrad trombocytfunktion \xd6kat serumkolesterol']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 14],
 u'_rank': 65,
 u'_type': u'MSFU'}