{'_data': [['Common',
            [['Nervous system',
              u'D\xe5sighet under n\xe4stf\xf6ljande dag, avtrubbade k\xe4nslor, minskad vakenhet, f\xf6rvirring, tr\xf6tthet, huvudv\xe4rk.'],
             ['Eye', u'Dubbelseende'],
             ['Ear', u'Vertigo, ataxi'],
             ['Musculoskeletal', u'Muskelsvaghet']]],
           ['Uncommon',
            [['Psychiatric',
              u'): Paradoxala reaktioner: Rastl\xf6shet, agitation, irritabilitet, aggressivitet, vanf\xf6rest\xe4llningar, raserianfall, mardr\xf6mmar, hallucinationer, psykoser, somnambulism, ol\xe4mpligt beteende och andra beteendest\xf6rningar (s\xe5dana reaktioner f\xf6rekommer oftare hos \xe4ldre patienter, se avsnitt 4.4), anterograd amnesi, vilken kan vara associerad med ol\xe4mpligt beteende. En befintlig depression kan bli manifest vid behandling med bensodiazepiner eller bensodiazepinliknande medel (se avsnitt 4.4). Anv\xe4ndning (\xe4ven vid terapeutiska doser) kan leda till fysiskt beroende; Uts\xe4ttande av behandling kan leda till abstinens eller rebound-effekt (se avsnitt 4.4). Psykologiskt beroende kan intr\xe4ffa. Missbruk har rapporterats hos blandmissbrukare. Nedsatt libido.'],
             ['GI', u'Gastrointestinala besv\xe4r (diarr\xe9, illam\xe5ende, kr\xe4kningar)'],
             ['Skin', u'Hudreaktioner']]]],
 '_pages': [4, 5],
 u'_rank': 7,
 u'_type': u'LSFU'}