{'_data': [['Very common',
            [['GI',
              u'Illam\xe5ende, kr\xe4kningar, diarr\xe9, buksm\xe4rta och aptitf\xf6rlust']]],
           ['Common',
            [['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Tremor'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Nervous system', u'Yrsel'],
             ['GI',
              u'Illam\xe5ende Beskrivning av valda biverkningar I kontrollerade kliniska studier med kombinationen 100 mg vildagliptin dagligen + metformin var det inga patienter som avbr\xf6t studien p\xe5 grund av biverkningar i n\xe5gondera av behandlingsgrupperna, vildagliptin 100 mg dagligen + metformin respektive placebo + metformin. I kliniska studier var f\xf6rekomsten av hypoglykemi vanligt hos patienter som fick vildagliptin i kombination med metformin (1 %) och mindre vanlig hos patienter som fick placebo + metformin (0,4 %). Inga sv\xe5ra h\xe4ndelser av hypoglykemi rapporterades i vildagliptingrupperna. I kliniska studier \xe4ndrades inte kroppsvikten fr\xe5n utg\xe5ngsv\xe4rdet d\xe5 vildagliptin 100 mg dagligen gavs som till\xe4ggsbehandling till metformin (+0,2 kg och -1,0 kg f\xf6r vidagliptin respektive placebo). Inga ytterligare s\xe4kerhetssignaler eller of\xf6rutsedda risker s\xe5gs i studier som p\xe5g\xe5tt i upp till 2 \xe5r eller mer n\xe4r vildagliptin gavs som till\xe4gg till metformin. Kombination med en sulfonureid Tabell 2 Biverkningar som rapporterats hos patienter som f\xe5tt vildagliptin 50 mg tv\xe5 g\xe5nger dagligen i kombination med metformin och en sulfonureid (N=157)'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Yrsel, tremor'],
             ['Skin', u'Hyperhidros'],
             ['General',
              u'Asteni Beskrivning av valda biverkningar I behandlingsgruppen med vildagliptin + metformin + glimepirid rapporterades ingen avbruten behandling p\xe5 grund av biverkningar mot 0,6 % i behandlingsgruppen med placebo + metformin + glimepirid. F\xf6rekomsten av hypoglykemi var vanlig i b\xe5da behandlingsgrupperna (5,1 % f\xf6r gruppen med vildagliptin + metformin + glimepirid mot 1,9 % f\xf6r gruppen med placebo + metformin + glimepirid gruppen). Ett fall av allvarlig hypoglykemi rapporterades i vildagliptingruppen. Vid slutet av studien s\xe5 var effekten p\xe5 medelkroppsvikten neutral (+0,6 kg i vildagliptingruppen och 0,1 kg i placebogruppen).'],
             ['Metabolism', u'Minskat blodglukos'],
             ['Nervous system', u'Huvudv\xe4rk, frossa'],
             ['GI', u'Illam\xe5ende, gastroesofageal refluxsjukdom'],
             ['Nervous system', u'Yrsel'],
             ['Nervous system', u'Metallsmak i munnen']]],
           ['Uncommon',
            [['Nervous system', u'Tr\xf6tthet'],
             ['GI',
              u'Diarr\xe9, gasbildning Beskrivning av valda biverkningar I kontrollerade kliniska studier med vildagliptin 50 mg tv\xe5 g\xe5nger dagligen i kombination med insulin, med eller utan samtidigt anv\xe4ndning av metformin, var den totala f\xf6rekomsten av patienter som avbr\xf6t studien p\xe5 grund av biverkningar 0,3 % i vildagliptingruppen och inga som avbr\xf6t studien i placebogruppen. F\xf6rekomsten av hypoglykemi var likartad i b\xe5da behandlingsgrupperna (14,0 % i vildagliptingruppen mot 16,4 % i placebogruppen). Tv\xe5 patienter rapporterade allvarliga hypoglykemiska h\xe4ndelser i vildagliptingruppen och 6 patienter i placebogruppen. Vid slutet av studien var effekten p\xe5 medelkroppsvikten neutral (+0,6 kg \xe4ndring fr\xe5n studiestart i vildagliptingruppen och ingen vikt\xe4ndring i placebogruppen). Ytterligare information om de enskilda aktiva substanserna i den fasta kombinationen Vildagliptin Tabell 4 Biverkningar som rapporterats hos patienter som f\xe5tt vildagliptin 100 mg dagligen som monoterapi i dubbelblinda studier (N=1 855)'],
             ['Metabolism', u'Hypoglykemi'],
             ['Nervous system', u'Huvudv\xe4rk'],
             ['Vascular', u'Perifert \xf6dem'],
             ['GI', u'F\xf6rstoppning'],
             ['Musculoskeletal',
              u'Ledv\xe4rk Beskrivning av valda biverkningar I kontrollerade monoterapistudier var den totala f\xf6rekomsten av patienter som avbr\xf6t studien p\xe5 grund av biverkningar inte st\xf6rre f\xf6r patienter som behandlades med vildagliptin vid doser om 100 mg dagligen (0,3 %) \xe4n f\xf6r placebo (0,6 %) eller j\xe4mf\xf6relsel\xe4kemedel (0,5 %). I j\xe4mf\xf6rande kontrollerade monoterapistudier var hypoglykemi en mindre vanlig biverkan och rapporterades hos 0,4 % (7 av 1855) av patienterna som behandlades med vildagliptin 100 mg 9 dagligen, j\xe4mf\xf6rt med 0,2 % (2 av 1082) av patienterna i de grupper som behandlades med aktivt j\xe4mf\xf6relsel\xe4kemedel eller placebo, utan att n\xe5gra allvarliga eller sv\xe5ra h\xe4ndelser rapporterades. I kliniska studier \xe4ndrades inte kroppsvikten fr\xe5n utg\xe5ngsv\xe4rdet d\xe5 vildagliptin 100 mg dagligen gavs som monoterapi (-0,3 kg och -1,3 kg f\xf6r vidagliptin respektive placebo). Inga ytterligare s\xe4kerhetssignaler eller of\xf6rutsedda risker s\xe5gs i studier som p\xe5g\xe5tt i upp till 2 \xe5r med vildagliptin i monoterapi. Metformin Tabell 5 K\xe4nda biverkningar f\xf6r metforminkomponenten']]],
           ['Very rare',
            [['Infections', u'Infektion i \xf6vre luftv\xe4garna'],
             ['Infections', u'Nasofaryngit'],
             ['Metabolism',
              u'Mycket s\xe4llsynta Minskad absorption av vitamin B samt laktacidos*'],
             ['Hepato', u'Onormala leverfunktionstester eller hepatit**'],
             ['Skin',
              u'Hudreaktioner s\xe5som erytem, pruritus och urtikaria *Minskad absorption av vitamin B och minskade serumniv\xe5er har mycket s\xe4llsynt observerats hos patienter som f\xe5tt l\xe5ngtidsbehandling med metformin. H\xe4nsyn b\xf6r tas till denna etiologi vid uppkomst av megaloblastisk anemi hos en patient. **Isolerade fall av onormala leverfunktionstester eller hepatit, som avklingat efter uts\xe4ttande av metformin har rapporterats. Gastrointestinala biverkningar \xe4r vanligt f\xf6rekommande i b\xf6rjan av behandlingen men f\xf6rsvinner vanligtvis utan \xe5tg\xe4rd. F\xf6r att f\xf6rhindra dem rekommenderas att metformin tas vid tv\xe5 dagliga doseringstillf\xe4llen, under eller efter m\xe5ltid. En l\xe5ngsam dos\xf6kning kan f\xf6rb\xe4ttra den gastrointestinala toleransen. Erfarenheter efter att l\xe4kemedlet godk\xe4nts f\xf6r f\xf6rs\xe4ljning Tabell 6 Biverkningar som rapporterats efter att l\xe4kemedlet godk\xe4nts f\xf6r f\xf6rs\xe4ljning']]],
           ['Unknown',
            [['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (reversibelt vid uts\xe4ttning av l\xe4kemedlet) Onormala leverfunktionstester (reversibelt vid uts\xe4ttning av l\xe4kemedlet)'],
             ['Skin', u'Urtikaria Bull\xf6sa eller exfoliativa hudlesioner']]]],
 '_pages': [7, 10],
 u'_rank': 30,
 u'_type': u'LSFU'}