{'_data': [['Very common',
            [['Cardiac', u'Myokardinfarkt;'],
             ['GI', u'Ischemi eller infarkt (t.ex. intestinal'],
             ['Renal', u'Akuta urintr\xe4ngningar']]],
           ['Common',
            [['Nervous system',
              u'Onormal eller rubbad  sinnesf\xf6rnimmelse;  Yrsel; Huvudv\xe4rk; Hyperestesi; Parestesier; Somnolens; V\xe4rmek\xe4nsla'],
             ['Cardiac', u'Palpitationer'],
             ['GI', u'Buksm\xe4rta;  Illam\xe5ende; Kr\xe4kningar; Muntorrhet'],
             ['Musculoskeletal', u'Muskelsvaghet;  Myalgi'],
             ['General',
<<<<<<< HEAD
              u'Asteni;  Tyngdk\xe4nsla, \xe5tstramningsk\xe4nsla,  sm\xe4rta eller tryck i strupe, hals,  extremiteter eller br\xf6stkorg.']]],
=======
              u'Asteni;  Tyngdk\xe4nsla, \xe5tstramningsk\xe4nsla,  sm\xe4rta eller tryck i strupe, hals, extremiteter eller br\xf6stkorg.']]],
>>>>>>> eb0dbf7cfbd3e1c8a568eedcf6ca5658233104cc
           ['Uncommon', [['Cardiac', u'Takykardi']]],
           ['Rare',
            [['Immune system',
              u'\xd6verk\xe4nslighetsreaktioner inkluderande  urtikaria, angio\xf6dem och anafylaktiska reaktioner'],
             ['Cardiac', u'Angina pectoris;  Koronar vasospasm'],
             ['GI',
              u'ischemi, intestinal infarkt, mj\xe4ltinfarkt),  vilket kan upptr\xe4da som blodig diarr\xe9 eller buksm\xe4rtor'],
             ['Renal', u'']]]],
 '_pages': [4, 5],
 u'_rank': 12,
 u'_type': u'TSFU'}