{'_data': [['Common',
            [['Nervous system', u'D\xe5sighet'],
             ['General', u'Smakf\xf6r\xe4ndringar (bitter smak), muntorrhet.']]],
           ['Uncommon',
            [['Nervous system', u'Oro, f\xf6r\xe4ndrat dr\xf6mm\xf6nster'],
             ['GI', u'Illam\xe5ende'],
             ['General',
              u'Huvudv\xe4rk, yrsel Uts\xe4ttningssymptom har rapporterats vid avslutad behandling med zopiklon (se avsnitt 4.4). Uts\xe4ttningssymptomen varierar och inkluderar s\xf6mnsv\xe5righeter, oro, tremor, svettningar, agitation, konfusion, huvudv\xe4rk, palpitationer, takykardi, delirium, mardr\xf6mmar, hallucinationer och irritabilitet. I mycket s\xe4llsynta fall har \xe4ven kramper f\xf6rekommit.']]],
           ['Rare',
            [['Nervous system',
              u'\xc5ngest, irritabilitet, aggressivitet. Hallucinationer, konfusion, koncentrationssv\xe5righeter, minnesluckor (anterograd amnesi)'],
             ['Hepato',
              u'Mild till m\xe5ttlig h\xf6jning av serumtransaminaser och/eller alkaliska fosfataser.'],
             ['Skin',
              u'Exantem, kl\xe5da, urtikaria. Angio\xf6dem och/eller anafylaktoida reaktioner']]]],
 '_pages': [4, 5],
 u'_rank': 8,
 u'_type': u'LSFU'}