{'_data': [['Very common',
            [['Skin',
              u'Erytem  S\xe5rskorpor Hudexfoliering Hud\xf6dem Huds\xe5r Hypopigmentering av hud'],
             ['General',
              u'Erytem p\xe5 appliceringsst\xe4lle  Skorpbildning p\xe5 appliceringsst\xe4lle  Exfoliering p\xe5 appliceringsst\xe4lle Torrhet p\xe5 appliceringsst\xe4lle \xd6dem p\xe5 appliceringsst\xe4lle Huds\xe5r p\xe5 appliceringsst\xe4lle Uts\xf6ndring p\xe5 appliceringsst\xe4lle']]],
           ['Common',
            [['Metabolism', u'Anorexi  F\xf6rh\xf6jt blodglukos'],
             ['Nervous system', u'Huvudv\xe4rk  Yrsel'],
             ['GI', u'Illam\xe5ende  Diarr\xe9 Uppkastningar'],
             ['Skin', u'Dermatit'],
             ['Musculoskeletal', u'Muskelv\xe4rk  Ledsm\xe4rta'],
             ['General',
              u'Reaktion p\xe5 appliceringsst\xe4lle  Kl\xe5da p\xe5 appliceringsst\xe4lle Sm\xe4rta p\xe5 appliceringsst\xe4lle Svullnad p\xe5 appliceringsst\xe4lle Sveda p\xe5 appliceringsst\xe4lle Irritation p\xe5 appliceringsst\xe4lle Eksem p\xe5 appliceringsst\xe4lle Utmattning Pyrexi Influensaliknande sjukdom Sm\xe4rta Br\xf6stsm\xe4rta']]],
           ['Uncommon',
            [['Infections', u'Infektion  Pustlar'],
             ['Psychiatric', u'Depression  Irritabilitet'],
             ['Eye', u'Konjunktival irritation'],
             ['Respiratory', u'N\xe4st\xe4ppa  Faryngolaryngeal sm\xe4rta'],
             ['GI', u'Muntorrhet'],
             ['Skin', u'Ansikts\xf6dem'],
             ['Musculoskeletal', u'Ryggont  Sm\xe4rta i extremitet'],
             ['General',
              u'Dermatit p\xe5 appliceringsst\xe4lle  Bl\xf6dning p\xe5 appliceringsst\xe4lle Papuler p\xe5 appliceringsst\xe4lle Paraestesi p\xe5 appliceringsst\xe4lle Hyperestesi p\xe5 appliceringsst\xe4lle Inflammation p\xe5 appliceringsst\xe4lle \xc4rr p\xe5 appliceringsst\xe4lle Hudnedbrytning p\xe5 appliceringsst\xe4lle Vesiklar p\xe5 appliceringsst\xe4lle V\xe4rmek\xe4nsla p\xe5 appliceringsst\xe4lle Tr\xf6tthet Frossa Letargi Obehag Inflammation']]],
           ['Rare',
            [['Immune system', u'F\xf6rs\xe4mring av autoimmunt tillst\xe5nd'],
             ['Skin', u'Dermatologisk reaktion p\xe5 andra st\xe4llen']]],
           ['Unknown',
            [['Infections', u'Hudinfektion'],
             ['Blood', u'Hemoglobin sj\xf6nk'],
             ['Hepato', u'F\xf6rh\xf6jda leverenzymv\xe4rden'],
             ['Skin', u'Alopeci']]]],
 '_pages': [5, 8],
 u'_rank': 22,
 u'_type': u'TSFU'}