{'_data': [['Very common',
            [['Metabolism', u'Viktuppg\xe5ng'],
             ['Nervous system', u'Somnolens'],
             ['Vascular', u'Ortostatisk hypotoni'],
             ['Investigations', u'F\xf6rh\xf6jd plasmaprolaktinniv\xe5'],
             ['Pregnancy',
              u'med Normala v\xe4rden (<5,17 studiens b\xf6 Normala niv\xe5er fasteglukos F\xf6r\xe4ndringar i fasteglukos (>7 mmol/l) var mycket Normala v\xe4rden (<1,69 F\xf6r\xe4ndringar i triglyceridv\xe4rden extrapyramidala syndrom. rapporterats vid abrupt hj\xe4lp av den integrerade L\xe5ngtidsexponering (minst cirka 6 m\xe5nader. seminatriumvalproat f\xf6rekom bipol\xe4r sjukdom gav en kroppsvikten f\xf6re studiens Pediatrisk population kortare tids exponering. frekvensangivelser anv\xe4nds:'],
             ['Metabolism',
              u'Mycket vanliga: Vikt\xf6kning Vanliga: F\xf6rh\xf6jd kolesterolniv\xe5'],
             ['Nervous system', u'mycket vanliga:'],
             ['GI', u'vanliga: Muntorrhet.'],
             ['Hepato', u'mycket vanliga:'],
             ['Investigations',
              u'mycket vanliga: plasma . 13 Vid korttidsbehandling kroppsvikten (kg) fr\xe5n kroppsvikten fr\xe5n studiens l\xe5ngtidsbehandling (minst 14 Normala v\xe4rden 16 f\xf6r\xe4ndringar i triglyceridv\xe4rden b\xf6rjan \xf6kade till h\xf6ga']]],
           ['Common',
            [['Blood', u'Eosinofili Leukopeni Neutropeni'],
             ['Metabolism',
              u'F\xf6rh\xf6jd kolesterolniv\xe5 F\xf6rh\xf6jd glukosniv\xe5 F\xf6rh\xf6jd triglyceridniv\xe5 Glykosuri \xd6kad aptit'],
             ['Nervous system', u'Yrsel Akatisi Parkinsonism Dyskinesi'],
             ['GI',
              u'Milda, \xf6verg\xe5ende antikolinerga effekter, inklusive f\xf6rstoppning och muntorrhet'],
             ['Hepato',
              u'\xd6verg\xe5ende, asymtomatiska f\xf6rh\xf6jningar av leveramino-transferaser (ALAT, ASAT), s\xe4rskilt i b\xf6rjan av behandlingen (se avsnitt 4.4)'],
             ['Skin', u'Utslag'],
             ['Musculoskeletal', u'Artralgi'],
             ['Reproductive system',
              u'Erektil dysfunktion hos m\xe4n Minskad libido hos b\xe5da k\xf6nen Asteni Tr\xf6tthet \xd6dem Feber Sm\xe4rta p\xe5 injektionsst\xe4llet'],
             ['Investigations',
              u'F\xf6rh\xf6jt alkaliskt 8 fosfatas 10 H\xf6g kreatinfosfokinas'],
             ['Pregnancy',
              u'> 7 % j\xe4mf\xf6rt med kroppsvikten vid studiens b\xf6rjan mycket vanligt (22,2 %), viktuppg\xe5ng med mmol/l) vid fasta vid studiens b\xf6rjan \xf6kade till h\xf6ga -rjan till h\xf6ga (>6,2 mmol/l) var mycket vanligt. (<5,56 mmol/l) vid studiens b\xf6rjan \xf6kade till h\xf6ga ( -fr\xe5n gr\xe4nsfall -vanligt. -mmol/l) vid fasta vid studiens b\xf6rjan \xf6kade till h\xf6ga (>2,26 mmol/l). vid fasta fr\xe5n gr\xe4nsfall (>1,69 mmol/l -<2,26 mmol/l) vid studiens uts\xe4ttande av olanzapin. -olanzapindatabasen. -48 veckor) -en \xf6kning i kroppsvikten om -\xf6kning i kroppsvikten -b\xf6rjan. -mycket vanlig '],
             ['Metabolism', u', f\xf6rh\xf6jd triglyceridniv\xe5'],
             ['Nervous system', u'Sedering (inkluderande: hypersomni, letargi, somnolens).'],
             ['Hepato', u'F\xf6rh\xf6jda leveraminotransferaser (ALAT/ASAT; se avsnitt 4.4)'],
             ['Investigations',
              u'Reducering av totalbilirubin, \xf6kning av gamma-GT, f\xf6rh\xf6jda prolaktinniv\xe5er i (median behandlingstid 22 dagar) var -studiens b\xf6rjan mycket vanlig (40,6%), -b\xf6rjan var vanlig (7,1%) och -24 veckor), fick 89,4% en viktuppg\xe5ng om -mmol/l) vid fasta vid studie -vid fasta fr\xe5n gr\xe4nsfall 16 mmol/l -<1,467 mmol/l) vid studiens (>1,467 mmol/l). ']]],
           ['Uncommon',
            [['Immune system', u'\xd6verk\xe4nslighet'],
             ['Metabolism',
              u'Utveckling eller f\xf6rs\xe4mring av diabetes, ibland associerat med ketoacidos eller koma, inklusive n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4)'],
             ['Nervous system',
              u'Kramper, d\xe4r det i de flesta fall finns kramper eller riskfaktorer f\xf6r kramper i anamnesen Dystoni (inklusive okulogyration) Dysartri'],
             ['Respiratory', u'Epistaxis'],
             ['Cardiac', u'Bradykardi QTc-f\xf6rl\xe4ngning (se avsnitt 4.4)'],
             ['Vascular',
              u'Tromboemboli (inklusive lungemboli och djup ventrombos) (se avsnitt 4.4)'],
             ['GI', u'Utsp\xe4nd buk'],
             ['Skin', u'Fotosensitivitetsreaktioner Alopeci'],
             ['Renal', u'Urininkontinens, urinretention, urintr\xe4ngningar'],
             ['Reproductive system',
              u'Amenorr\xe9 Br\xf6stf\xf6rstoring Galaktorr\xe9 hos kvinnor Gynekomasti/br\xf6stf\xf6rstoring hos m\xe4n'],
             ['Investigations', u'\xd6kad total bilirubinniv\xe5'],
             ['Pregnancy',
              u'(>5,56 -<7 mmol/l) vid studiens b\xf6rjan till h\xf6ga >7% hos 17,4% av patienterna under den om >7% hos 39,9% av patienterna, j\xe4mf\xf6rt med a , vanliga .'],
             ['Metabolism', u', \xf6kad aptit.'],
             ['Investigations',
              u'viktuppg\xe5ng om >15 % av > 25 % var vanlig (2,5%). Under ns b\xf6rjan \xf6kade till h\xf6ga (>1,467 mmol/l) och']]],
           ['Rare',
            [['Blood', u'Trombocytopeni'],
             ['Metabolism', u'Hypotermi'],
             ['Nervous system',
              u'Malignt neuroleptikasyndrom (se avsnitt 4.4) Uts\xe4ttningssymtom'],
             ['Cardiac',
              u'Ventrikul\xe4r takykardi/flimmer, pl\xf6tsligt d\xf6dsfall (se avsnitt 4.4)'],
             ['GI', u'Pankreatit'],
             ['Hepato',
              u'Hepatit (inklusive hepatocellul\xe4r, kolestatisk eller blandad leverskada)'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Reproductive system', u'Priapism Abscess p\xe5 injektionsst\xe4llet'],
             ['Investigations', u'Frekvens ok\xe4nd'],
             ['Pregnancy',
              u'Neonatalt uts\xe4ttningssyndrom (se avsnitt 4.6) (>6,2 mmol/l). >7 mmol/l).'],
             ['Investigations', u'viktuppg\xe5ng om >7 % av > 7 %, 55,3% en viktuppg\xe5ng']]]],
 '_note': u' ?MSFU',
 '_pages': [8, 12],
 u'_rank': 49,
 u'_type': u'MSFU'}