{'_data': [['Very common',
            [['Blood', u'Eosinofili'],
             ['Immune system', u'Organsystem'],
             ['Metabolism', u'Viktuppg\xe5ng F\xf6rh\xf6jd'],
             ['Nervous system', u'Somnolens Yrsel'],
             ['Vascular', u'Ortostatisk'],
             ['GI', u'Milda,'],
             ['Hepato', u'\xd6verg\xe5ende,'],
             ['Skin', u'Utslag'],
             ['Investigations',
              u'F\xf6rh\xf6jd plasma-prolaktinniv\xe5 (>7 mmol/l) var mycket syndrom. rapporterats vid abrupt L\xe5ngtidsbehandling (minst seminatriumvalproat f\xf6rekom studiens b\xf6rjan. Pediatrisk population ungdomar med data fr\xe5n'],
             ['Metabolism', u'Mycket vanlig: viktuppg\xe5ng : f\xf6rh\xf6jd kolesterolniv\xe5'],
             ['Nervous system', u'mycket vanlig'],
             ['GI', u'vanlig : muntorrhet.'],
             ['Hepato', u'mycket vanlig (ALAT/ASAT, se avsnitt'],
             ['Investigations', u'Mycket vanlig: minskat studiens b\xf6rjan till h\xf6ga']]],
           ['Common',
            [['Immune system', u'Very common'],
             ['Metabolism',
              u'kolesterolniv\xe5 F\xf6rh\xf6jd glukosniv\xe5 F\xf6rh\xf6jd triglyceridniv\xe5 Glykosuri \xd6kad aptit'],
             ['Nervous system', u'Akatisi Parkinsonism Dyskinesi'],
             ['Vascular', u'hypotoni'],
             ['GI',
              u'\xf6verg\xe5ende antikolinerga effekter, inklusive f\xf6rstoppning och muntorrhet'],
             ['Hepato',
              u'asymtomatiska f\xf6rh\xf6jningar av leveramino-transferaser (ALAT, ASAT), s\xe4rskilt i b\xf6rjan av behandlingen (se avsnitt 4.4)'],
             ['Reproductive system',
              u'Erektil dysfunktion hos m\xe4n Minskad libido hos b\xe5da k\xf6nen Asteni Tr\xf6tthet \xd6dem'],
             ['Investigations',
              u'H\xf6g vanligt. -uts\xe4ttande av olanzapin. -48 veckor) -en \xf6kning i kroppsvikt om -studier p\xe5 vuxna. '],
             ['Metabolism', u', f\xf6rh\xf6jd triglyceridniv\xe5 vanlig 11'],
             ['Nervous system', u': sedering (inklusive hypersomni, letargi, somnolens).'],
             ['Hepato', u': f\xf6rh\xf6jda niv\xe5er av leveraminotransferaser 4.4). '],
             ['Investigations',
              u'totalbilirubin, \xf6kat GGT, f\xf6rh\xf6jd plasmaprolaktinniv\xe5 -(>1,467 mmol/l). ']]],
           ['Uncommon',
            [['Blood', u'Leukopeni Neutropeni'],
             ['Immune system', u'Common'],
             ['Metabolism', u'Utveckling eller'],
             ['Cardiac', u'Bradykardi QTc-f\xf6rl\xe4ngning (se avsnitt 4.4)'],
             ['Vascular',
              u'Tromboemboli (inklusive lungemboli och djup ventrombos) (se avsnitt 4.4)'],
             ['GI', u'Pankreatit'],
             ['Hepato', u'Hepatit'],
             ['Skin', u'Fotosensitivitetsreaktioner Alopeci'],
             ['Renal', u'urinretention'],
             ['Reproductive system',
              u'Amenorr\xe9 Br\xf6stf\xf6rstoring Galaktorr\xe9 hos kvinnor Gynekomasti/br\xf6stf\xf6rstoring hos m\xe4n'],
             ['Investigations',
              u'kreatinfosfokinasniv\xe5 \xd6kad total bilirubinniv\xe5 >7 % hos 17,4 % av patienterna under den'],
             ['Metabolism', u'10  , \xf6kad aptit.']]],
           ['Unknown',
            [['Blood', u'Trombocytopeni'],
             ['Immune system', u'Uncommon'],
             ['Metabolism',
              u'f\xf6rs\xe4mring av diabetessjukdomen, ibland associerat med ketoacidos eller koma, inklusive n\xe5gra fall med d\xf6dlig utg\xe5ng (se avsnitt 4.4) Hypotermi'],
             ['Nervous system',
              u'Kramper, d\xe4r det i de flesta fall finns kramper eller riskfaktorer f\xf6r kramper i anamnesen. Malignt neuroleptikasyndrom (se avsnitt 4.4) Dystoni (inklusive okulogyration Tardiv dyskinesi Uts\xe4ttningssymtom'],
             ['Cardiac',
              u'Ventrikul\xe4r takykardi/flimmer, pl\xf6tsligt d\xf6dsfall (se avsnitt 4.4)'],
             ['Hepato', u'(inklusive hepatocellul\xe4r, kolestatisk eller blandad leverskada)'],
             ['Musculoskeletal', u'Rabdomyolys'],
             ['Pregnancy', u'Neonatalt uts\xe4ttningssyndrom (se avsnitt 4.6)'],
             ['Reproductive system', u'Priapism'],
             ['Investigations', u'\xd6kat alkaliskt fosfatas'],
             ['Investigations', u'12 .']]]],
 '_note': u' ?MSFU',
 '_pages': [7, 11],
 u'_rank': 49,
 u'_type': u'MSFU'}