{'_data': [['Very common',
            [['Infections', u' urinv\xe4gsinfektion'],
             ['Metabolism', u' hypokalemi'],
             ['Vascular', u' hypertoni'],
             ['General', u' perifert \xf6dem ']]],
           ['Common',
            [['Metabolism', u' hypertriglyceridemi'],
             ['Cardiac',
              u' hj\xe4rtsvikt*, angina pectoris, arytmi, f\xf6rmaksflimmer, takykardi'],
             ['GI', u' dyspepsi'],
             ['Hepato',
              u' f\xf6rh\xf6jt alaninaminotransferas, f\xf6rh\xf6jt aspartataminotransferas'],
             ['Skin', u' utslag'],
             ['Renal', u'hematuri'],
             ['Injury', u' frakturer** ']]],
           ['Uncommon', [['Endocrine', u' binjureinsufficiens']]]],
 '_pages': [6, 8],
 u'_rank': 12,
 u'_type': u'LSFU2'}